### PR TITLE
Remove unused module.

### PR DESCRIPTION
**Pull request by SomeoneToIgnore**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3233)

### CODE REVIEW

**Comment by ahie** [comment]
The module is still referenced in `flow-components-parent`

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3233#-:-L1q2BONav54BTe5y3iM:b57ovr4)*

**Comment by ahie** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-components-parent/flow-component/.gitignore, line 1 at r1](https://reviewable.io:443/reviews/vaadin/flow/3233#-L1q2N20aDcdW_bU_yx4:-L1q2N20aDcdW_bU_yx5:b-okktnx) ([raw file](https://github.com/vaadin/flow/blob/c83d1ce23bc81f1b1a0c209b11891ed008f8511c/flow-components-parent/flow-component/.gitignore#L1)):*
> ```
> /bin/
> ```

Is this change related?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3233)*

**Comment by SomeoneToIgnore** [comment]
Right, fixed.

---

Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-components-parent/flow-component/.gitignore, line 1 at r1](https://reviewable.io:443/reviews/vaadin/flow/3233#-L1q2N20aDcdW_bU_yx4:-L1q2i4Ki9XmGDK6-oYy:b9129ta) ([raw file](https://github.com/vaadin/flow/blob/c83d1ce23bc81f1b1a0c209b11891ed008f8511c/flow-components-parent/flow-component/.gitignore#L1)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

Is this change related?
</blockquote></details>

Yes, it's the module's contents.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3233#-:-L1q2d8ouCMwKArUQr09:b-o419a3)*

**Comment by ahie** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3233#-:-L1q326v2KuDsog9fHfo:bnfp4nl)*

**Pull request merged**
