### PR TITLE
Add Flow version of get started tutorial

### PR DESCRIPTION
**Pull request by hezamu**
Add a basic version of the get started tutorial. Does not include Designer parts, also videos need to be redone.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/2902)

### CODE REVIEW

**Comment by caalador** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2902#-Kyp1dRrcLEyzy8aRD5G:-Kyp1dRrcLEyzy8aRD5H:b-jiviz6) (no related file):*
Found 146 problems with documentation.

Test documentation with 'mvn verify'  to see that there are no problems.
Right now error range from `Tutorial get-started.asciidoc has the code block, but has no corresponding code files for code block [source,java]` to `Received malformed asciidoc link, tutorial = get-started.asciidoc, line = image::images/DebugAsMavenProjectAddSources.png[]`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2902)*

**Comment by hezamu** [comment]
Fix errors from 'mvn verify'

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2902#-:-KypJfRroWgGAqtO8WTq:b-xqky8z)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 10 files at r3.
Review status: 1 of 13 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2902#-Kyp1dRrcLEyzy8aRD5G:-Kyt0i09kMkYQWk8dD0-:b-mzxjut) (no related file):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Found 146 problems with documentation.

Test documentation with 'mvn verify'  to see that there are no problems.
Right now error range from `Tutorial get-started.asciidoc has the code block, but has no corresponding code files for code block [source,java]` to `Received malformed asciidoc link, tutorial = get-started.asciidoc, line = image::images/DebugAsMavenProjectAddSources.png[]`
</blockquote></details>

It looks like it's "work in progress", because I see a number of TODOs.
Please prefix your commit message "WIP" so that we know that it's not ready for review yet.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2902)*

**Comment by hezamu** [comment]
*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2902#-Kyp1dRrcLEyzy8aRD5G:-KytStiVFQyWzztFG79_:b-uohxte) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

It looks like it's "work in progress", because I see a number of TODOs.
Please prefix your commit message "WIP" so that we know that it's not ready for review yet.
</blockquote></details>

The TODOs were about to videos which will be added by marketing and are not needed for the first version. I deleted the TODOs and commented out the video related stuff.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2902)*

**Comment by denis-anisimov** [comment]
Reviewed 3 of 5 files at r2, 9 of 10 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2902#-Kyp1dRrcLEyzy8aRD5G:-KyuLDUmGY0xfDxrW8Eo:b-ja0a8n) (no related file):*
<details><summary><i>Previously, hezamu (Henri Muurimaa) wrote…</i></summary><blockquote>

The TODOs were about to videos which will be added by marketing and are not needed for the first version. I deleted the TODOs and commented out the video related stuff.
</blockquote></details>

Not blocking ( minor): looks like you are using TABs instead of spaces in formatting. Would be good to replace TABs to spaces and reformat. 
But as I said: not blocking.

---

*[flow-documentation/get-started.asciidoc, line 124 at r4](https://reviewable.io:443/reviews/vaadin/flow/2902#-KyuM94tP3t08lD0S58-:-KyuM94tP3t08lD0S580:b-9jyd97) ([raw file](https://github.com/vaadin/flow/blob/951e56e09d4a5e05e8592e3fc5cb1297e2d7666a/flow-documentation/get-started.asciidoc#L124)):*
> TIP: 

In all our docs the TIP is done as 
```
[TIP]
a tip text
```

It makes a special markdown.
I think it should be used here as well.

---

*[flow-documentation/get-started.asciidoc, line 139 at r4](https://reviewable.io:443/reviews/vaadin/flow/2902#-KyuMTy3IK9Tjbls2yI9:-KyuMTy4CGSUwoUF8ifx:b-dr8nu6) ([raw file](https://github.com/vaadin/flow/blob/951e56e09d4a5e05e8592e3fc5cb1297e2d7666a/flow-documentation/get-started.asciidoc#L139)):*
> TIP:

see above about TIP

---

*[flow-documentation/get-started.asciidoc, line 166 at r4](https://reviewable.io:443/reviews/vaadin/flow/2902#-KyuNFOfwQadtEnFsO9U:-KyuNFOfwQadtEnFsO9V:b-9lc6ky) ([raw file](https://github.com/vaadin/flow/blob/951e56e09d4a5e05e8592e3fc5cb1297e2d7666a/flow-documentation/get-started.asciidoc#L166)):*
> A default servlet is also generated behind the scenes based on this annotation.

Does it?

The default Vaadin servlet should be registered out of the box if there is no a custom servlet defined.
So if we generate the servlet class then it looks like it's an issue : there is no need in it unless a specific config is required.

---

*[flow-documentation/get-started.asciidoc, line 181 at r4](https://reviewable.io:443/reviews/vaadin/flow/2902#-KyuMeSMRY8Xi_4o7UB1:-KyuMeSMRY8Xi_4o7UB2:b-dr8nu6) ([raw file](https://github.com/vaadin/flow/blob/951e56e09d4a5e05e8592e3fc5cb1297e2d7666a/flow-documentation/get-started.asciidoc#L181)):*
> TIP:

see above about TIP

---

*[flow-documentation/get-started.asciidoc, line 304 at r4](https://reviewable.io:443/reviews/vaadin/flow/2902#-KyuOJeSY-PDtiWiq2xR:-KyuOJeSY-PDtiWiq2xS:b-dr8nu6) ([raw file](https://github.com/vaadin/flow/blob/951e56e09d4a5e05e8592e3fc5cb1297e2d7666a/flow-documentation/get-started.asciidoc#L304)):*
> TIP:

see above about TIP

---

*[flow-documentation/get-started.asciidoc, line 334 at r4](https://reviewable.io:443/reviews/vaadin/flow/2902#-KyuOUb03r1re_U3hVq-:-KyuOUb03r1re_U3hVq0:blgpcu9) ([raw file](https://github.com/vaadin/flow/blob/951e56e09d4a5e05e8592e3fc5cb1297e2d7666a/flow-documentation/get-started.asciidoc#L334)):*
> to the [classname]#MyUI# 

What's the `MyUI` ?

We are trying yo hide the fact that there is `UI` class at all.
Normally you don't need to create any `UI` and know that it's created at all.
The standard `UI` is created out of the box and normally it should be enough.
Everything in Flow is done via `@Route` annotations and the `UI` class is entirely hidden.

---

*[flow-documentation/get-started.asciidoc, line 335 at r4](https://reviewable.io:443/reviews/vaadin/flow/2902#-KyuP1MA6GwaE7j_4Fhy:-KyuP1MA6GwaE7j_4Fhz:b-ou03dl) ([raw file](https://github.com/vaadin/flow/blob/951e56e09d4a5e05e8592e3fc5cb1297e2d7666a/flow-documentation/get-started.asciidoc#L335)):*
> the [methodname]#init()#


I believe it's a reference to the `init` method of `UI` class which as I said above is not needed.

In the example below the view class doesn't have this method.

---

*[flow-documentation/get-started.asciidoc, line 352 at r4](https://reviewable.io:443/reviews/vaadin/flow/2902#-KyuPHHZeWIi0JHciN6-:-KyuPHHZeWIi0JHciN60:b-dr8nu6) ([raw file](https://github.com/vaadin/flow/blob/951e56e09d4a5e05e8592e3fc5cb1297e2d7666a/flow-documentation/get-started.asciidoc#L352)):*
> TIP:

see above about TIP

---

*[flow-documentation/get-started.asciidoc, line 458 at r4](https://reviewable.io:443/reviews/vaadin/flow/2902#-KyuPZrn8CbAkmIGvP6r:-KyuPZrn8CbAkmIGvP6s:b-dr8nu6) ([raw file](https://github.com/vaadin/flow/blob/951e56e09d4a5e05e8592e3fc5cb1297e2d7666a/flow-documentation/get-started.asciidoc#L458)):*
> TIP:

see above about TIP

---

*[flow-documentation/get-started.asciidoc, line 659 at r4](https://reviewable.io:443/reviews/vaadin/flow/2902#-KyuPtBsFimMQQM3o8Zc:-KyuPtBsFimMQQM3o8Zd:b-dr8nu6) ([raw file](https://github.com/vaadin/flow/blob/951e56e09d4a5e05e8592e3fc5cb1297e2d7666a/flow-documentation/get-started.asciidoc#L659)):*
> TIP:

see above about TIP

---

*[flow-documentation/get-started.asciidoc, line 693 at r4](https://reviewable.io:443/reviews/vaadin/flow/2902#-KyuPwQJt7zQ1LtMgbP_:-KyuPwQJt7zQ1LtMgbPa:b-dr8nu6) ([raw file](https://github.com/vaadin/flow/blob/951e56e09d4a5e05e8592e3fc5cb1297e2d7666a/flow-documentation/get-started.asciidoc#L693)):*
> TIP:

see above about TIP

---

*[flow-documentation/src/main/java/com/vaadin/flow/tutorial/getstarted/CustomerService.java, line 40 at r4](https://reviewable.io:443/reviews/vaadin/flow/2902#-KyuKMSuNIXzMMRiQr7z:-KyuKMSuNIXzMMRiQr8-:b-vu0q5l) ([raw file](https://github.com/vaadin/flow/blob/951e56e09d4a5e05e8592e3fc5cb1297e2d7666a/flow-documentation/src/main/java/com/vaadin/flow/tutorial/getstarted/CustomerService.java#L40)):*
> if (instance == null) {
> 			instance = new CustomerService();
> 			instance.ensureTestData();
> 		}
> 		return instance;

Since other methods are `synchronized` this class is supposed to be used within multiple threads.
Then:
- either has to be `synchronized` as well
- or initialization should be done in the `static final` field declaration which makes the field thread-safe. Here just return the instance.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2902)*

**Comment by hezamu** [comment]
*[flow-documentation/get-started.asciidoc, line 124 at r4](https://reviewable.io:443/reviews/vaadin/flow/2902#-KyuM94tP3t08lD0S58-:-KyyxYo47LTGcc8tT7RS:b-c142s0) ([raw file](https://github.com/vaadin/flow/blob/951e56e09d4a5e05e8592e3fc5cb1297e2d7666a/flow-documentation/get-started.asciidoc#L124)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> TIP: 

In all our docs the TIP is done as 
```
[TIP]
a tip text
```

It makes a special markdown.
I think it should be used here as well.
</blockquote></details>

Fixed. I used the same format that was used in the source material: https://github.com/vaadin/framework/blob/master/documentation/tutorial.adoc

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2902)*

**Comment by hezamu** [comment]
*[flow-documentation/get-started.asciidoc, line 166 at r4](https://reviewable.io:443/reviews/vaadin/flow/2902#-KyuNFOfwQadtEnFsO9U:-Kyyyz70h3CDdLDXiBME:bhhtiud) ([raw file](https://github.com/vaadin/flow/blob/951e56e09d4a5e05e8592e3fc5cb1297e2d7666a/flow-documentation/get-started.asciidoc#L166)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> A default servlet is also generated behind the scenes based on this annotation.

Does it?

The default Vaadin servlet should be registered out of the box if there is no a custom servlet defined.
So if we generate the servlet class then it looks like it's an issue : there is no need in it unless a specific config is required.
</blockquote></details>

Copypaste mistake, fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2902)*

**Comment by hezamu** [comment]
*[flow-documentation/get-started.asciidoc, line 334 at r4](https://reviewable.io:443/reviews/vaadin/flow/2902#-KyuOUb03r1re_U3hVq-:-Kyyz6NDTD2omS-QPtwB:b-x52gbo) ([raw file](https://github.com/vaadin/flow/blob/951e56e09d4a5e05e8592e3fc5cb1297e2d7666a/flow-documentation/get-started.asciidoc#L334)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> to the [classname]#MyUI# 

What's the `MyUI` ?

We are trying yo hide the fact that there is `UI` class at all.
Normally you don't need to create any `UI` and know that it's created at all.
The standard `UI` is created out of the box and normally it should be enough.
Everything in Flow is done via `@Route` annotations and the `UI` class is entirely hidden.
</blockquote></details>

Thanks, fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2902)*

**Comment by denis-anisimov** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2902#-Kyp1dRrcLEyzy8aRD5G:-Kyz3vxqwpEw90evzWF-:bz1v1j0) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Not blocking ( minor): looks like you are using TABs instead of spaces in formatting. Would be good to replace TABs to spaces and reformat. 
But as I said: not blocking.
</blockquote></details>

@caalador , looks like you are blocking this comment.
Everything else is fine.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2902)*

**Pull request merged**
