### PR TITLE
Allow Spring add-on co-exist with other Spring services

### PR DESCRIPTION
**Pull request by denis-anisimov**
Fix for #2660

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/2769)

### CODE REVIEW

**Comment by caalador** [comment]
Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[flow-spring-addon/src/main/java/com/vaadin/spring/RootMappedCondition.java, line 23 at r1](https://reviewable.io:443/reviews/vaadin/flow/2769#-KxMS2USB4VwEW0Sd_TJ:-KxMS2USB4VwEW0Sd_TK:b-wblgy4) ([raw file](https://github.com/vaadin/flow/blob/b40efce0c6ee59b1907de4da2325af4cdb285533/flow-spring-addon/src/main/java/com/vaadin/spring/RootMappedCondition.java#L23)):*
> ```Java
> 
> /**
>  * @author Vaadin Ltd
> ```

Seems like Sonar isn't run for this branch.
The JavaDocs could be more descriptive =)

---

*[flow-spring-addon/src/main/java/com/vaadin/spring/RootMappedCondition.java, line 37 at r1](https://reviewable.io:443/reviews/vaadin/flow/2769#-KxMSMMw2nQNh5yWE_Y8:-KxMSMMw2nQNh5yWE_Y9:bwywyy9) ([raw file](https://github.com/vaadin/flow/blob/b40efce0c6ee59b1907de4da2325af4cdb285533/flow-spring-addon/src/main/java/com/vaadin/spring/RootMappedCondition.java#L37)):*
> ```Java
>     }
> 
>     public static boolean isRootMapping(String mapping) {
> ```

JavaDoc

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2769)*

**Comment by denis-anisimov** [comment]
Review status: 13 of 14 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[flow-spring-addon/src/main/java/com/vaadin/spring/RootMappedCondition.java, line 23 at r1](https://reviewable.io:443/reviews/vaadin/flow/2769#-KxMS2USB4VwEW0Sd_TJ:-KxN5YVlholnanmYWdlJ:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/b40efce0c6ee59b1907de4da2325af4cdb285533/flow-spring-addon/src/main/java/com/vaadin/spring/RootMappedCondition.java#L23)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Seems like Sonar isn't run for this branch.
The JavaDocs could be more descriptive =)

</blockquote></details>

Done.

---

*[flow-spring-addon/src/main/java/com/vaadin/spring/RootMappedCondition.java, line 37 at r1](https://reviewable.io:443/reviews/vaadin/flow/2769#-KxMSMMw2nQNh5yWE_Y8:-KxN5Z2suh0ne89DsRZz:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/b40efce0c6ee59b1907de4da2325af4cdb285533/flow-spring-addon/src/main/java/com/vaadin/spring/RootMappedCondition.java#L37)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

JavaDoc
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2769)*

**Comment by caalador** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2769)*

**Comment by caalador** [comment]
Reviewed 3 of 3 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2769)*

**Pull request merged**
