### PR TITLE
Keep client side model property values

### PR DESCRIPTION
**Pull request by denis-anisimov**
Don't set model property values that are not explicitly set by the developer on the server side. As a result they won't override client-side default property values.

Fix for #2897

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3023)

### CODE REVIEW

**Comment by caalador** [comment]
Reviewed 7 of 11 files at r1, 8 of 8 files at r2.
Review status: 15 of 16 files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-client/src/main/java/com/vaadin/client/ExecuteJavaScriptElementUtils.java, line 325 at r2](https://reviewable.io:443/reviews/vaadin/flow/3023#-Kzhteo-C6wfT_RlebBe:-Kzhteo-C6wfT_RlebBf:bfqmr4k) ([raw file](https://github.com/vaadin/flow/blob/bb1eb2160d7638f724644587b07ecc6a1e35ac78/flow-client/src/main/java/com/vaadin/client/ExecuteJavaScriptElementUtils.java#L325)):*
> ```Java
>     private static native boolean isPropertyDefined(Node node, String property)
>     /*-{
>         return node["constructor"] && node["constructor"]["properties"] &&
> ```

At a glance this would return a truthy response. Would it make sense to make it an actual boolean with `!!(node....)`

---

*[flow-server/src/main/java/com/vaadin/ui/polymertemplate/PolymerTemplate.java, line 227 at r2](https://reviewable.io:443/reviews/vaadin/flow/3023#-Kzi516TKRGL5JaP-RxS:-Kzi516TKRGL5JaP-RxT:b5big20) ([raw file](https://github.com/vaadin/flow/blob/bb1eb2160d7638f724644587b07ecc6a1e35ac78/flow-server/src/main/java/com/vaadin/ui/polymertemplate/PolymerTemplate.java#L227)):*
> ```Java
>                 .filter(name -> !(map.getProperty(name) instanceof StateNode))
>                 .collect(Collectors.toList());
>         props.forEach(map::removeProperty);
> ```

should we really remove the properties from the actual map?

Also couldn't we just filter the unset properties from the propertyNames list in initModel and then just create the array based on these instead of checking again at that point if they exist in the map.
 or just return the props as `propertyNames` as we don't use the removed properties anyway.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3023)*

**Comment by denis-anisimov** [comment]
Review status: 14 of 16 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[flow-client/src/main/java/com/vaadin/client/ExecuteJavaScriptElementUtils.java, line 325 at r2](https://reviewable.io:443/reviews/vaadin/flow/3023#-Kzhteo-C6wfT_RlebBe:-KzwCvhchXvbMkH-TWtI:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/bb1eb2160d7638f724644587b07ecc6a1e35ac78/flow-client/src/main/java/com/vaadin/client/ExecuteJavaScriptElementUtils.java#L325)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

At a glance this would return a truthy response. Would it make sense to make it an actual boolean with `!!(node....)`
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/ui/polymertemplate/PolymerTemplate.java, line 227 at r2](https://reviewable.io:443/reviews/vaadin/flow/3023#-Kzi516TKRGL5JaP-RxS:-KzwCxCm9KHEvOWiDSz1:bt7gio1) ([raw file](https://github.com/vaadin/flow/blob/bb1eb2160d7638f724644587b07ecc6a1e35ac78/flow-server/src/main/java/com/vaadin/ui/polymertemplate/PolymerTemplate.java#L227)):*
> should we really remove the properties from the actual map?

That's the whole point of this PR: there shouldn't be any property in the map which has not been explicitly set.
If you call `getModel()` then the model is populated and all its properties get their default values.
If we don't remove those properties then they will be sent to the client and all client-side preset values will be lost.

We should not call `getModel()` at all actually. But:
- it's the easiest way to get all properties
- we cannot prevent the developer from calling `getModel()`. But developer may need the model _ONLY_ to set _one_ property. But regardless of developer intention `getModel()` will set all other properties as well ( to their default values).

So the whole point of the patch:
- call `getModel()` to retrieve all property names
- remove all properties ( would be nice to remove ALL of them but we `StateNode` values have issues)
- this will exclude implicit values in the properties that have not been set by the developer
- but if the developer explicitly  sets values to the model then they will be sent and override the client-side values

>Also couldn't we just filter the unset properties from the propertyNames list in initModel and then just create the array based on these instead of checking again at that point if they exist in the map.
or just return the props as propertyNames as we don't use the removed properties anyway.

Please see above: we should not set any property value by ourselves.
But all properties that are set by the developer should be set to the required values.

`getModel()` is called in the CTOR of the class which means that there will be no calls before it.
So first: all properties are collected and removed.
Now we now all the model properties.

Then the developer may call `getModel()` (which won't be initialized one more time anymore) and set _explicitly_ some model properties.
Those values have to be sent as is to the client side.
This will happen _BEFORE_ sending data to the client side.
And that is checked in the call here: before sending _ALL MODEL PROPERTIES_ to the client side to initialize them via JS call the properties are checked whether they are set or not.
And this has no any relation to the previous model properties collecting.
If property has been explicitly set by the developer then it shouldn't be populated on the client side via JS. It will be set from the server-side.

I've added the bunch of comments here along with unit tests.
I hoped that it will clear the picture. But apparently it's still no clear enough.

Please let me know what to improve to make the logic of the code clear here: add more comments?
What kind and where? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3023)*

**Comment by caalador** [comment]
Reviewed 1 of 1 files at r3.
Review status: 15 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-server/src/main/java/com/vaadin/ui/polymertemplate/PolymerTemplate.java, line 227 at r2](https://reviewable.io:443/reviews/vaadin/flow/3023#-Kzi516TKRGL5JaP-RxS:-KzwW_55aSlue679IikY:b1i43th) ([raw file](https://github.com/vaadin/flow/blob/bb1eb2160d7638f724644587b07ecc6a1e35ac78/flow-server/src/main/java/com/vaadin/ui/polymertemplate/PolymerTemplate.java#L227)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> should we really remove the properties from the actual map?

That's the whole point of this PR: there shouldn't be any property in the map which has not been explicitly set.
If you call `getModel()` then the model is populated and all its properties get their default values.
If we don't remove those properties then they will be sent to the client and all client-side preset values will be lost.

We should not call `getModel()` at all actually. But:
- it's the easiest way to get all properties
- we cannot prevent the developer from calling `getModel()`. But developer may need the model _ONLY_ to set _one_ property. But regardless of developer intention `getModel()` will set all other properties as well ( to their default values).

So the whole point of the patch:
- call `getModel()` to retrieve all property names
- remove all properties ( would be nice to remove ALL of them but we `StateNode` values have issues)
- this will exclude implicit values in the properties that have not been set by the developer
- but if the developer explicitly  sets values to the model then they will be sent and override the client-side values

>Also couldn't we just filter the unset properties from the propertyNames list in initModel and then just create the array based on these instead of checking again at that point if they exist in the map.
or just return the props as propertyNames as we don't use the removed properties anyway.

Please see above: we should not set any property value by ourselves.
But all properties that are set by the developer should be set to the required values.

`getModel()` is called in the CTOR of the class which means that there will be no calls before it.
So first: all properties are collected and removed.
Now we now all the model properties.

Then the developer may call `getModel()` (which won't be initialized one more time anymore) and set _explicitly_ some model properties.
Those values have to be sent as is to the client side.
This will happen _BEFORE_ sending data to the client side.
And that is checked in the call here: before sending _ALL MODEL PROPERTIES_ to the client side to initialize them via JS call the properties are checked whether they are set or not.
And this has no any relation to the previous model properties collecting.
If property has been explicitly set by the developer then it shouldn't be populated on the client side via JS. It will be set from the server-side.

I've added the bunch of comments here along with unit tests.
I hoped that it will clear the picture. But apparently it's still no clear enough.

Please let me know what to improve to make the logic of the code clear here: add more comments?
What kind and where? 
</blockquote></details>

No this is quite clear as is. Only change I'm proposing would be to have the unset list gotten from the unsetting and not doing the same job multiple times:

```
    private JsonArray filterUnsetProperties(List<String> properties) {
        JsonArray array = Json.createArray();
        ElementPropertyMap map = getStateNode()
                .getFeature(ElementPropertyMap.class);
        int i = 0;
        for (String property : properties) {
            array.set(i, property);
            i++;
        }
        return array;
    }
 
    private void initModelProperties() {
        // initialize model: fill all model properties with their initial value
        getModel();
        // now collect all property names
        ElementPropertyMap properties = getStateNode()
                .getFeature(ElementPropertyMap.class);
 
        // remove properties whose values are not StateNode from the property
        // map
        List<String> unsetProperties = removeSimpleProperties();
 
        /*
         * Now populate model properties on the client side. Only explicitly set
         * by the developer properties are in the map at the moment of execution
         * since all simple properties have been removed from the map above.
         * Such properties are excluded from the argument list and won't be
         * populated on the client side.
         *
         * All explicitly set model properties will be sent from the server as
         * usual and will take precedence over the client side values.
         */
        getStateNode().runWhenAttached(ui -> ui.getInternals().getStateTree()
                .beforeClientResponse(getStateNode(),
                        () -> ui.getPage().executeJavaScript(
                                "this.populateModelProperties($0, $1)",
                                getElement(),
                                filterUnsetProperties(unsetProperties))));
    }
 
    private List<String> removeSimpleProperties() {
        ElementPropertyMap map = getStateNode()
                .getFeature(ElementPropertyMap.class);
        List<String> props = map.getPropertyNames()
                .filter(name -> !(map.getProperty(name) instanceof StateNode))
                .collect(Collectors.toList());
        props.forEach(map::removeProperty);
        return props;
    }
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3023)*

**Comment by denis-anisimov** [comment]
Review status: 15 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-server/src/main/java/com/vaadin/ui/polymertemplate/PolymerTemplate.java, line 227 at r2](https://reviewable.io:443/reviews/vaadin/flow/3023#-Kzi516TKRGL5JaP-RxS:-Kzwc0ce1FmWvFZZJhmP:b-2hs43g) ([raw file](https://github.com/vaadin/flow/blob/bb1eb2160d7638f724644587b07ecc6a1e35ac78/flow-server/src/main/java/com/vaadin/ui/polymertemplate/PolymerTemplate.java#L227)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

No this is quite clear as is. Only change I'm proposing would be to have the unset list gotten from the unsetting and not doing the same job multiple times:

```
    private JsonArray filterUnsetProperties(List<String> properties) {
        JsonArray array = Json.createArray();
        ElementPropertyMap map = getStateNode()
                .getFeature(ElementPropertyMap.class);
        int i = 0;
        for (String property : properties) {
            array.set(i, property);
            i++;
        }
        return array;
    }
 
    private void initModelProperties() {
        // initialize model: fill all model properties with their initial value
        getModel();
        // now collect all property names
        ElementPropertyMap properties = getStateNode()
                .getFeature(ElementPropertyMap.class);
 
        // remove properties whose values are not StateNode from the property
        // map
        List<String> unsetProperties = removeSimpleProperties();
 
        /*
         * Now populate model properties on the client side. Only explicitly set
         * by the developer properties are in the map at the moment of execution
         * since all simple properties have been removed from the map above.
         * Such properties are excluded from the argument list and won't be
         * populated on the client side.
         *
         * All explicitly set model properties will be sent from the server as
         * usual and will take precedence over the client side values.
         */
        getStateNode().runWhenAttached(ui -> ui.getInternals().getStateTree()
                .beforeClientResponse(getStateNode(),
                        () -> ui.getPage().executeJavaScript(
                                "this.populateModelProperties($0, $1)",
                                getElement(),
                                filterUnsetProperties(unsetProperties))));
    }
 
    private List<String> removeSimpleProperties() {
        ElementPropertyMap map = getStateNode()
                .getFeature(ElementPropertyMap.class);
        List<String> props = map.getPropertyNames()
                .filter(name -> !(map.getProperty(name) instanceof StateNode))
                .collect(Collectors.toList());
        props.forEach(map::removeProperty);
        return props;
    }
```

</blockquote></details>

Well....
That's just a small improvement, but yes, it can be done in this way.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3023)*

**Comment by denis-anisimov** [comment]
Review status: 15 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-server/src/main/java/com/vaadin/ui/polymertemplate/PolymerTemplate.java, line 227 at r2](https://reviewable.io:443/reviews/vaadin/flow/3023#-Kzi516TKRGL5JaP-RxS:-Kzwdez0PFb4Priz5_dE:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/bb1eb2160d7638f724644587b07ecc6a1e35ac78/flow-server/src/main/java/com/vaadin/ui/polymertemplate/PolymerTemplate.java#L227)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Well....
That's just a small improvement, but yes, it can be done in this way.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3023)*

**Comment by caalador** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3023)*

**Pull request merged**
