### PR TITLE
Resolve url translations on the fly.

### PR DESCRIPTION
**Pull request by caalador**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3442)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 3 of 6 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java, line 69 at r2](https://reviewable.io:443/reviews/vaadin/flow/3442#-L46NT0aByO9QV_1TVIx:-L46NT0aByO9QV_1TVIy:b-t9utef) ([raw file](https://github.com/vaadin/flow/blob/ac8c592cbc32a94c386eae7cd48cd0055765a647/flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java#L69)):*
>  private final Map<Class<? extends AbstractTheme>, Map<String, String>> themeTranslations = new HashMap<>();

Could you initialize this field lazily please ?
I'm struggling right now with memory consumption and empty `HashMap` eats quite a lot of memory being instantiated in many places.
This is 1:1 to servlet so shouldn't be a big issue but anyway.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3442)*

**Comment by caalador** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java, line 69 at r2](https://reviewable.io:443/reviews/vaadin/flow/3442#-L46NT0aByO9QV_1TVIx:-L49huKyUAzuWDS8LCa5:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/ac8c592cbc32a94c386eae7cd48cd0055765a647/flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java#L69)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

>  private final Map<Class<? extends AbstractTheme>, Map<String, String>> themeTranslations = new HashMap<>();

Could you initialize this field lazily please ?
I'm struggling right now with memory consumption and empty `HashMap` eats quite a lot of memory being instantiated in many places.
This is 1:1 to servlet so shouldn't be a big issue but anyway.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3442)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3442)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3442)*

**Pull request merged**
