### PR TITLE
Add docs about adding all components

### PR DESCRIPTION
**Pull request by ZheSun88**
As a developer, i don't want to add flow components one by one, I want to add one dependency for all of them with the newest version, So that i don't need to update by myself.

people asked this before, with the platform release, our components will be released to the users, too.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3086)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-documentation/flow-components/tutorial-flow-components-setup.asciidoc, line 29 at r1](https://reviewable.io:443/reviews/vaadin/flow/3086#-L-Fk91CpYk4g79pMhKH:-L-Fk91CpYk4g79pMhKI:b8jhh2f) ([raw file](https://github.com/vaadin/flow/blob/6fbfd4bb7121108a12cf031eaa08ca75259d9f7b/flow-documentation/flow-components/tutorial-flow-components-setup.asciidoc#L29)):*
> Besides, you can add `vaadin-platform` dependency, if you need flow components for your project.

Please emphasize that this is the option that can be used if the developer doesn't want to add dependency to every component one by one.
This dependency automatically adds dependencies to _ALL_ available components.
It's important to understand that because I could decide to avoid having a bunch of unneeded jars in my WAR but only several of them even though I need to add them manually one by one.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3086)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-documentation/flow-components/tutorial-flow-components-setup.asciidoc, line 45 at r1](https://reviewable.io:443/reviews/vaadin/flow/3086#-L-Fl64TBF_jwSRCbXXC:-L-Fl64UIlk5OMfscrBQ:by9340z) ([raw file](https://github.com/vaadin/flow/blob/6fbfd4bb7121108a12cf031eaa08ca75259d9f7b/flow-documentation/flow-components/tutorial-flow-components-setup.asciidoc#L45)):*
> <version>10.0.0.alpha8</version>

Also it might be that the explicit version from the doc should be somehow removed/replaced (replaced with variable e.g.) because it will become outdated quite soon.

Here , below and everywhere.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3086)*

**Comment by ZheSun88** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-documentation/flow-components/tutorial-flow-components-setup.asciidoc, line 29 at r1](https://reviewable.io:443/reviews/vaadin/flow/3086#-L-Fk91CpYk4g79pMhKH:-L-GpYSSrTgQ9b7auXiX:bhxzrdc) ([raw file](https://github.com/vaadin/flow/blob/6fbfd4bb7121108a12cf031eaa08ca75259d9f7b/flow-documentation/flow-components/tutorial-flow-components-setup.asciidoc#L29)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> Besides, you can add `vaadin-platform` dependency, if you need flow components for your project.

Please emphasize that this is the option that can be used if the developer doesn't want to add dependency to every component one by one.
This dependency automatically adds dependencies to _ALL_ available components.
It's important to understand that because I could decide to avoid having a bunch of unneeded jars in my WAR but only several of them even though I need to add them manually one by one.
</blockquote></details>

how does it read now?

---

*[flow-documentation/flow-components/tutorial-flow-components-setup.asciidoc, line 45 at r1](https://reviewable.io:443/reviews/vaadin/flow/3086#-L-Fl64TBF_jwSRCbXXC:-L-GpaoxmwsYHayuIcu8:b92tq72) ([raw file](https://github.com/vaadin/flow/blob/6fbfd4bb7121108a12cf031eaa08ca75259d9f7b/flow-documentation/flow-components/tutorial-flow-components-setup.asciidoc#L45)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> <version>10.0.0.alpha8</version>

Also it might be that the explicit version from the doc should be somehow removed/replaced (replaced with variable e.g.) because it will become outdated quite soon.

Here , below and everywhere.
</blockquote></details>

I add a note below for readers to check the platform version number. how does it look now?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3086)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3086)*

**Pull request merged**
