### PR TITLE
Don't traverse parent layouts for enter navigation event

### LINKED ISSUE #3614: BeforeEnter is called for wrong view if views have common parent layout
Use case 1.
I have 2 separate views with different routes and links to each other.
When I navigate from one to another I see proper order of events:
a. leave from one view
b. enter another view

Use case 2.
I have 2 separate view with different routes, but with same parent layout
`@Route(value="someroute", layout=ParentLayout.class)
I navigate from 1st view to 2nd:
a. leave from 1st view
b. enter 2nd view
c. enter 1st view !!!

In first case NavigationStateRenderer.executeBeforeEnterNavigation() has only one element in `List<HasElement> elements`(2nd view).
In second case there are 2 elements: 2nd view and parent layout, which at this point still has a 1st view inside. So beforeEnter is called for all of my views. 

Small example:
https://github.com/alexberazouski/skeleton-starter-flow-spring/commit/e1bf2270f420cf22b625067468cff2bfbf299c8e

### PR DESCRIPTION
**Pull request by denis-anisimov**
Fixes #3614

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3629)

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3629)*

**Comment by heruan** [comment]
Will this mean parent layout's `beforeEnter` methods won't be called anymore?

**Comment by denis-anisimov** [comment]
>Will this mean parent layout's beforeEnter methods won't be called anymore?
It will if parent layout implements required interface.

It means that _ALL CHILDREN_ of parent layout won't be notified unless they are children of the navigation target.

**Comment by heruan** [comment]
To understand better:
```java
public class Parent extends Div implements ParentLayout, BeforeEnterObserver {

    @Override
    public void beforeEnter(BeforeEnterEvent event) {
        // check i.e. permission to access the target
    }
}

public class Child extends Div implements BeforeEnterObserver {

    @Override
    public void beforeEnter(BeforeEnterEvent event) {
    }
}

@Route(value = "", layout = Parent.class)
public class Target extends Div implements BeforeEnterObserver {

    public Target() {
        add(new Child());
    }

    @Override
    public void beforeEnter(BeforeEnterEvent event) {
    }
}
```

Before this all the three observer triggered, now which one won't?

**Comment by denis-anisimov** [comment]
All of them will be triggered.

This change has relation to the situation when:

```
parent, ParentLayout
  |
  ------------ child, BeforeEnterObserver
  |
  ------------ navigation target, BeforeEnterObserver
                         |
                         -------------- children of navigation target, BeforeEnterObservers

```

Before this change all `BeforeEnterObserver` have been notified if navigation happens into the `navigation target`.
After this change the first `child`  of the `parent` won't be notified anymore (all others will).

Please see a ticket for the exact usecase: if navigation has been done from `child` to the `navigation target` then before this PR `child` also has been triggered which has no sense.

**Pull request merged**
