### PR TITLE
Ph/ticket 7369

### PR DESCRIPTION
**Pull request by petrixh**
Ticket #7369 enhancements to flow-client that exposes request start/received events to native JS as well as fires a separate event when Vaadin has completed all processing, including any pending RPC's.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/7388)

### CODE REVIEW

**Comment by petrixh** [comment]
Some additions coming to this PR tomorrow, please hold off reviewing until those are in.

**Comment by petrixh** [comment]
Ok, all known changes are in, ready for review

**Comment by pleku** [comment]
@petrixh can you say if this is still relevant and would you be able to address the issues in the PR or should we assign someone from the devteam to fix those ? This in itself is not a priority for us, but since it seems that there was a significant effort for this already done, we could try to nudge it in.

**Comment by pleku** [comment]
We've tried to figure out if this is still relevant for the users (who requested this) but to no success.

Since this would require further effort before being accepted and we have higher work priorities than finishing this PR ourselves, I'm closing it.

**Pull request closed without merging**
