### PR TITLE
Apply full body size by default

### PR DESCRIPTION
**Pull request by pekam**
If no `@BodySize` has been defined, set width:100vw and height:100vh for
the body.

Also refactored the code a bit to avoid setting margin in two places.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3821)

### CODE REVIEW

**Comment by gilberto-torrezan** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/flow/3821#-L9FoqhB8PcI1aIDOdFi:-L9FoqhB8PcI1aIDOdFj:bjp85ok) (no related file):*
When creating the PRs for the starters, you may want to follow the same structure I did for the `@Theme(Lumo.class)` change. The starters use the platform version, so you need to use the next package (yet to be released).

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3821#-:-L9FsPck8Od0iYSYsjof:bnfp4nl)*

**Comment by pekam** [comment]
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/flow/3821#-L9FoqhB8PcI1aIDOdFi:-L9Fupx52PK8GOm9jwDT:b-ukupdd) (no related file):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

When creating the PRs for the starters, you may want to follow the same structure I did for the `@Theme(Lumo.class)` change. The starters use the platform version, so you need to use the next package (yet to be released).
</blockquote></details>

Ah, I didn't notice that. Thanks for the tip!

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/flow/3821#-L9FuuIlDT9jwKeWVxhp:-L9FuuIlDT9jwKeWVxhq:b-m6fl0v) (no related file):*
Actually don't merge this one yet. I should also write a test about CSS values and `@ BodySize` (which should override which).

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3821)*

**Comment by pekam** [comment]
:lgtm_cancel: 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3821#-:-L9FwR57ChcNL6H9sJH4:b8b79qu)*

**Comment by gilberto-torrezan** [comment]
:lgtm_cancel: 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3821#-:-L9FwYSVE3xc4wl8wZdg:b8b79qu)*

**Comment by gilberto-torrezan** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3821)*

**Comment by gilberto-torrezan** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/flow/3821#-L9FuuIlDT9jwKeWVxhp:-L9JV0zv5aZ4KCCTPwoD:b-896fig) (no related file):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

Actually don't merge this one yet. I should also write a test about CSS values and `@ BodySize` (which should override which).
</blockquote></details>

Done?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3821)*

**Comment by pekam** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/flow/3821#-L9FuuIlDT9jwKeWVxhp:-L9Jbaxe6n_XTywgnOZy:b-16zhni) (no related file):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Done?
</blockquote></details>

Yes. I would have liked an IT to check the effective css-property of the body in the dom but I can't do that in flow-server. So I just have to trust that adding a style after another overrides it.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3821)*

**Comment by gilberto-torrezan** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3821#-:-L9JdNQp8xK8PGn6ci2l:bnfp4nl)*

**Pull request merged**
