### PR TITLE
Create the Lumo theme package

### PR DESCRIPTION
**Pull request by caalador**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3328)

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
Reviewed 27 of 30 files at r1, 2 of 2 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[flow-documentation/theme/tutorial-built-in-themes.asciidoc, line 93 at r2](https://reviewable.io:443/reviews/vaadin/flow/3328#-L2yzKLtyBYWAeFgw0SF:-L2yzKLtyBYWAeFgw0SG:b-geyvf1) ([raw file](https://github.com/vaadin/flow/blob/ab1b91708827f64749845945da00c66a818e9cce/flow-documentation/theme/tutorial-built-in-themes.asciidoc#L93)):*
> ```AsciiDoc
> which makes it possible to resolve the uri scheme.
> 
> .Import link for a "frontend://" file
> ```

Small typo: the dot at the beginning of the line.

---

*[flow-theme-integrations/pom.xml, line 25 at r3](https://reviewable.io:443/reviews/vaadin/flow/3328#-L2z3V7LcyS5ppMtk4JV:-L2z3V7LcyS5ppMtk4JW:bop5u56) ([raw file](https://github.com/vaadin/flow/blob/30786f4b69271154f478ab9afa84e30fa012c523/flow-theme-integrations/pom.xml#L25)):*
> ```XML
>             <dependency>
>                 <groupId>com.vaadin</groupId>
>                 <artifactId>vaadin-webjars-bom</artifactId>
> ```

Isn't it already included into the root pom? This module has it as parent, so it should be fine without it.

---

*[flow-theme-integrations/lumo/src/main/java/com/vaadin/flow/theme/lumo/Lumo.java, line 60 at r3](https://reviewable.io:443/reviews/vaadin/flow/3328#-L2z32eAjt7ZxOD5xDBp:-L2z32eAjt7ZxOD5xDBq:b-wh5ws7) ([raw file](https://github.com/vaadin/flow/blob/30786f4b69271154f478ab9afa84e30fa012c523/flow-theme-integrations/lumo/src/main/java/com/vaadin/flow/theme/lumo/Lumo.java#L60)):*
> ```Java
>     @Override
>     public List<String> getBodyInlineContents() {
>         return Arrays.asList("<custom-style>\n"
> ```

Just in case you'd like to save some memory for the clients, `Collections.singletonList` may be used here.

---

*[webjars-bom/pom.xml, line 77 at r3](https://reviewable.io:443/reviews/vaadin/flow/3328#-L2z2IJxdl80wl-0hYh8:-L2z2IJxdl80wl-0hYh9:b-wd619t) ([raw file](https://github.com/vaadin/flow/blob/30786f4b69271154f478ab9afa84e30fa012c523/webjars-bom/pom.xml#L77)):*
> ```XML
>             <dependency>
>                 <groupId>org.webjars.bower</groupId>
>                 <artifactId>github-com-vaadin-vaadin-lumo-styles</artifactId>
> ```

Zhe have added it already, so this one is not needed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3328)*

**Comment by caalador** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[flow-documentation/theme/tutorial-built-in-themes.asciidoc, line 93 at r2](https://reviewable.io:443/reviews/vaadin/flow/3328#-L2yzKLtyBYWAeFgw0SF:-L2z4KIbNZqFMdzJr5Lh:b10upmy) ([raw file](https://github.com/vaadin/flow/blob/ab1b91708827f64749845945da00c66a818e9cce/flow-documentation/theme/tutorial-built-in-themes.asciidoc#L93)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Small typo: the dot at the beginning of the line.
</blockquote></details>

The dot in the asciiDoc actually makes it a Title for the source block.

---

*[flow-theme-integrations/pom.xml, line 25 at r3](https://reviewable.io:443/reviews/vaadin/flow/3328#-L2z3V7LcyS5ppMtk4JV:-L2z54Fj2ZeEsUc2StkN:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/30786f4b69271154f478ab9afa84e30fa012c523/flow-theme-integrations/pom.xml#L25)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Isn't it already included into the root pom? This module has it as parent, so it should be fine without it.
</blockquote></details>

Done.

---

*[flow-theme-integrations/lumo/src/main/java/com/vaadin/flow/theme/lumo/Lumo.java, line 60 at r3](https://reviewable.io:443/reviews/vaadin/flow/3328#-L2z32eAjt7ZxOD5xDBp:-L2z5EjRcdmLmpCtb6Wf:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/30786f4b69271154f478ab9afa84e30fa012c523/flow-theme-integrations/lumo/src/main/java/com/vaadin/flow/theme/lumo/Lumo.java#L60)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Just in case you'd like to save some memory for the clients, `Collections.singletonList` may be used here.
</blockquote></details>

Done.

---

*[webjars-bom/pom.xml, line 77 at r3](https://reviewable.io:443/reviews/vaadin/flow/3328#-L2z2IJxdl80wl-0hYh8:-L2z5H1tGqmKcbxwheH_:b9e57oz) ([raw file](https://github.com/vaadin/flow/blob/30786f4b69271154f478ab9afa84e30fa012c523/webjars-bom/pom.xml#L77)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Zhe have added it already, so this one is not needed.
</blockquote></details>

I'll merge.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3328)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[flow-documentation/theme/tutorial-built-in-themes.asciidoc, line 93 at r2](https://reviewable.io:443/reviews/vaadin/flow/3328#-L2yzKLtyBYWAeFgw0SF:-L2z5qiV83B2nvXignvp:b5r3pq7) ([raw file](https://github.com/vaadin/flow/blob/ab1b91708827f64749845945da00c66a818e9cce/flow-documentation/theme/tutorial-built-in-themes.asciidoc#L93)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

The dot in the asciiDoc actually makes it a Title for the source block.
</blockquote></details>

Oh, nice.

---

*[webjars-bom/pom.xml, line 77 at r3](https://reviewable.io:443/reviews/vaadin/flow/3328#-L2z2IJxdl80wl-0hYh8:-L2z6Bew8QJ_Y5BRcQyS:bh1kppc) ([raw file](https://github.com/vaadin/flow/blob/30786f4b69271154f478ab9afa84e30fa012c523/webjars-bom/pom.xml#L77)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

I'll merge.
</blockquote></details>

Won't help, have done this already: now you have two identical packages here.
Just remove this one, the added one is on the bottom of the file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3328)*

**Comment by caalador** [comment]
Review status: 24 of 25 files reviewed at latest revision, 8 unresolved discussions.

---

*[webjars-bom/pom.xml, line 77 at r3](https://reviewable.io:443/reviews/vaadin/flow/3328#-L2z2IJxdl80wl-0hYh8:-L2z7tus_xmsnm8kHh-P:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/30786f4b69271154f478ab9afa84e30fa012c523/webjars-bom/pom.xml#L77)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Won't help, have done this already: now you have two identical packages here.
Just remove this one, the added one is on the bottom of the file.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3328)*

**Comment by SomeoneToIgnore** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3328#-:-L2z8-FutMHyX8aK30E-:bnfp4nl)*

**Pull request merged**
