### PR TITLE
Improve DataProvider tutorial

### PR DESCRIPTION
**Pull request by ahie**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/2953)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2953#-Kz7qrbgAv9Mx1n-Mp-N:-Kz7qrbgAv9Mx1n-Mp-O:bi2elng) (no related file):*
This can be merged but it's not the fix for the issue.

Please see the ticket description. It refers to https://github.com/vaadin/framework/blob/master/documentation/datamodel/datamodel-providers.asciidoc.

This document should be as much close to the Flow documentation as possible.
If you compare it then I will see that it doesn't.

At the moment of migration the DataProviders docs there was only one component which worked with `DataProvider` at all. It was `Grid`.

As a result a number of examples from the referenced tutorial have been totally removed.

They have to be moved back.

So generally one should go through all the `DataProvider` FW tutorial and check that everything is added back (may be with some corrections).

Specifically: `ComboBox` is a special case. It didn't support `DataProvider` at all when the tutorial gas been created.
So there are no references to `ComboBox` at all.
They should be returned back.

Why?

Because as I said: it's a special case. There are some features in `DataProvider` which are designed specifically for `ComboBox` like components. E.g. filtering  feature. 
In the `Grid` case the filtering is coming externally.
In the `ComboBox` case the filtering is coming internally (filter is a part of the component itself). That's why there is a specific filtering API for `DataProvider`.
It's impossible to demonstrate it without `ComboBox`  at all.

Also I replaced other `ComboBox`  examples  to use `Grid` instead.
They became a bit ugly. 
Everything should be returned back (if it's possible now). May be it still not the correct time to do this.
I don't know. But it should be done at some point.

All `DataProvider`  features should be described in the tutorial in very similar way as it's done in the https://github.com/vaadin/framework/blob/master/documentation/datamodel/datamodel-providers.asciidoc.

And this is not true at the moment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2953)*

**Comment by ahie** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2953#-Kz7qrbgAv9Mx1n-Mp-N:-Kz7uMGveTkq5qD7UPom:b-vdfps0) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

This can be merged but it's not the fix for the issue.

Please see the ticket description. It refers to https://github.com/vaadin/framework/blob/master/documentation/datamodel/datamodel-providers.asciidoc.

This document should be as much close to the Flow documentation as possible.
If you compare it then I will see that it doesn't.

At the moment of migration the DataProviders docs there was only one component which worked with `DataProvider` at all. It was `Grid`.

As a result a number of examples from the referenced tutorial have been totally removed.

They have to be moved back.

So generally one should go through all the `DataProvider` FW tutorial and check that everything is added back (may be with some corrections).

Specifically: `ComboBox` is a special case. It didn't support `DataProvider` at all when the tutorial gas been created.
So there are no references to `ComboBox` at all.
They should be returned back.

Why?

Because as I said: it's a special case. There are some features in `DataProvider` which are designed specifically for `ComboBox` like components. E.g. filtering  feature. 
In the `Grid` case the filtering is coming externally.
In the `ComboBox` case the filtering is coming internally (filter is a part of the component itself). That's why there is a specific filtering API for `DataProvider`.
It's impossible to demonstrate it without `ComboBox`  at all.

Also I replaced other `ComboBox`  examples  to use `Grid` instead.
They became a bit ugly. 
Everything should be returned back (if it's possible now). May be it still not the correct time to do this.
I don't know. But it should be done at some point.

All `DataProvider`  features should be described in the tutorial in very similar way as it's done in the https://github.com/vaadin/framework/blob/master/documentation/datamodel/datamodel-providers.asciidoc.

And this is not true at the moment.
</blockquote></details>

Thanks for the information. I will look into this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2953)*

**Comment by denis-anisimov** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[flow-documentation/data-provider/tutorial-flow-data-provider.asciidoc, line 73 at r1](https://reviewable.io:443/reviews/vaadin/flow/2953#-KzN43DTdyR0l4lpvChi:-KzN43DTdyR0l4lpvChj:bkih6r0) ([raw file](https://github.com/vaadin/flow/blob/9e42dd87a6809432bcd04ba3bd6f47a84319087a/flow-documentation/data-provider/tutorial-flow-data-provider.asciidoc#L73)):*
> NOT IMPLEMENTED

Here and everywhere else : what does it mean ?

- There is no API ?
- It's possible to do but it won't work ?

If there is no  such API then you just can't merge this since validation won't pass (and that was the reason why I've removed all non-existing examples from the tutorial).

If there is such API but it doesn't work: are you sure that it doesn't work ?
Because those features are server-side features only. I would expect that they work if the API exists.

---

*[flow-documentation/data-provider/tutorial-flow-data-provider.asciidoc, line 236 at r1](https://reviewable.io:443/reviews/vaadin/flow/2953#-KzN3Nhiu4HPNPgDqQ0e:-KzN3Nhiu4HPNPgDqQ0f:b-jc8oxx) ([raw file](https://github.com/vaadin/flow/blob/9e42dd87a6809432bcd04ba3bd6f47a84319087a/flow-documentation/data-provider/tutorial-flow-data-provider.asciidoc#L236)):*
> ;

extra ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2953)*

**Comment by ahie** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[flow-documentation/data-provider/tutorial-flow-data-provider.asciidoc, line 73 at r1](https://reviewable.io:443/reviews/vaadin/flow/2953#-KzN43DTdyR0l4lpvChi:-KzNX1eO5_f-PR8uI3b3:b-bcdl92) ([raw file](https://github.com/vaadin/flow/blob/9e42dd87a6809432bcd04ba3bd6f47a84319087a/flow-documentation/data-provider/tutorial-flow-data-provider.asciidoc#L73)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> NOT IMPLEMENTED

Here and everywhere else : what does it mean ?

- There is no API ?
- It's possible to do but it won't work ?

If there is no  such API then you just can't merge this since validation won't pass (and that was the reason why I've removed all non-existing examples from the tutorial).

If there is such API but it doesn't work: are you sure that it doesn't work ?
Because those features are server-side features only. I would expect that they work if the API exists.
</blockquote></details>

There is no such thing as `CaptionFilter` right now. Both sections that are commented out reference that class. The build passes because the example code is also commented out in the java file.

The question is, do we keep this here and open an issue about adding `CaptionFilter` or remove this documentation altogether? The issue should also note that this part of the documentation should be uncommented.

---

*[flow-documentation/data-provider/tutorial-flow-data-provider.asciidoc, line 236 at r1](https://reviewable.io:443/reviews/vaadin/flow/2953#-KzN3Nhiu4HPNPgDqQ0e:-KzNXphLJcdxw48Z1Oq2:bl7w5yt) ([raw file](https://github.com/vaadin/flow/blob/9e42dd87a6809432bcd04ba3bd6f47a84319087a/flow-documentation/data-provider/tutorial-flow-data-provider.asciidoc#L236)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ;

extra ?
</blockquote></details>

It's needed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2953)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-documentation/data-provider/tutorial-flow-data-provider.asciidoc, line 73 at r1](https://reviewable.io:443/reviews/vaadin/flow/2953#-KzN43DTdyR0l4lpvChi:-KzNemuG5UAKpE0gXCb_:byytson) ([raw file](https://github.com/vaadin/flow/blob/9e42dd87a6809432bcd04ba3bd6f47a84319087a/flow-documentation/data-provider/tutorial-flow-data-provider.asciidoc#L73)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

There is no such thing as `CaptionFilter` right now. Both sections that are commented out reference that class. The build passes because the example code is also commented out in the java file.

The question is, do we keep this here and open an issue about adding `CaptionFilter` or remove this documentation altogether? The issue should also note that this part of the documentation should be uncommented.
</blockquote></details>

Let's keep it here _AND_ create a ticket ( or number of tickets, one per each commented block here).

Otherwise it will be forgotten.
And keeping it here will simplify the task of correcting the documentation since there will be no need to go through all the text and find missing parts.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2953)*

**Comment by ahie** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-documentation/data-provider/tutorial-flow-data-provider.asciidoc, line 73 at r1](https://reviewable.io:443/reviews/vaadin/flow/2953#-KzN43DTdyR0l4lpvChi:-KzOA2_QaEobgsPneTr5:b-cokq1n) ([raw file](https://github.com/vaadin/flow/blob/9e42dd87a6809432bcd04ba3bd6f47a84319087a/flow-documentation/data-provider/tutorial-flow-data-provider.asciidoc#L73)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Let's keep it here _AND_ create a ticket ( or number of tickets, one per each commented block here).

Otherwise it will be forgotten.
And keeping it here will simplify the task of correcting the documentation since there will be no need to go through all the text and find missing parts.
</blockquote></details>

Created https://github.com/vaadin/flow/issues/2976.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2953)*

**Pull request merged**
