### PR TITLE
Show the stacktrace on the web page and a warning in case of SLF4J binding absence

### PR DESCRIPTION
**Pull request by denis-anisimov**
Fix for #3216

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3266)

### CODE REVIEW

**Comment by gilberto-torrezan** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[flow-server/src/main/java/com/vaadin/flow/router/InternalServerError.java, line 73 at r1](https://reviewable.io:443/reviews/vaadin/flow/3266#-L24bKd-3nYrJAn6zi6Y:-L24bKd-3nYrJAn6zi6Z:b-ooe7rx) ([raw file](https://github.com/vaadin/flow/blob/772809eb08815ec1297fe36b4064d12465ca35bd/flow-server/src/main/java/com/vaadin/flow/router/InternalServerError.java#L73)):*
> ```Java
>      * @return {@code true} if there is a SLF4J logging binding
>      */
>     protected boolean hasLogBinding() {
> ```

Any particular reason for this to be `protected` and not `private`?

... never mind, I just realized it is protected to make it easier to test.

---

*[flow-server/src/main/java/com/vaadin/flow/router/InternalServerError.java, line 118 at r1](https://reviewable.io:443/reviews/vaadin/flow/3266#-L24bWksimVBNBlNeN-e:-L24bWksimVBNBlNeN-f:b-3009pu) ([raw file](https://github.com/vaadin/flow/blob/772809eb08815ec1297fe36b4064d12465ca35bd/flow-server/src/main/java/com/vaadin/flow/router/InternalServerError.java#L118)):*
> ```Java
>                             + "Add some binding as a dependency to your project. "
>                             + "See details ");
>             logInfo.getStyle().set("marginTop", "10px");
> ```

`Style.set` is fluent, so you could chain `set("foo", "bar")` without calling `logInfo.getStyle()`  everytime. Not a blocker though.

---

*[flow-server/src/test/java/com/vaadin/flow/router/InternalServerErrorTest.java, line 96 at r1](https://reviewable.io:443/reviews/vaadin/flow/3266#-L24cECr6T8gdjQstJ_V:-L24cECr6T8gdjQstJ_W:b-8k5fmm) ([raw file](https://github.com/vaadin/flow/blob/772809eb08815ec1297fe36b4064d12465ca35bd/flow-server/src/test/java/com/vaadin/flow/router/InternalServerErrorTest.java#L96)):*
> ```Java
>         Element stacktrace = testInstance.getElement().getChild(2);
>         Assert.assertEquals("pre", stacktrace.getTag());
>         Assert.assertTrue(stacktrace.getText()
> ```

Why not also verifying the text of the NPE, since you have set it?

---

*[flow-server/src/test/java/com/vaadin/flow/router/InternalServerErrorTest.java, line 121 at r1](https://reviewable.io:443/reviews/vaadin/flow/3266#-L24cR42GDs3HZgcjrYg:-L24cR42GDs3HZgcjrYh:b-n4w04m) ([raw file](https://github.com/vaadin/flow/blob/772809eb08815ec1297fe36b4064d12465ca35bd/flow-server/src/test/java/com/vaadin/flow/router/InternalServerErrorTest.java#L121)):*
> ```Java
>         Element stacktrace = testInstance.getElement().getChild(1);
>         Assert.assertEquals("pre", stacktrace.getTag());
>         Assert.assertTrue(stacktrace.getText()
> ```

Same question as above.

---

*[flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ExceptionStacktraceIT.java, line 37 at r1](https://reviewable.io:443/reviews/vaadin/flow/3266#-L24a0W5SrQb-SVi9W2K:-L24a0W5SrQb-SVi9W2L:b-i4ydu2) ([raw file](https://github.com/vaadin/flow/blob/772809eb08815ec1297fe36b4064d12465ca35bd/flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ExceptionStacktraceIT.java#L37)):*
> ```Java
>         // no any SLF4J binding dependency in the project so this warning should
>         // be shown
>         Assert.assertTrue(
> ```

Replace this with `Assert.assertThat("There is no warning message about SLF4J binding absence", warning.getText(), CoreMatchers.containsString("SL4J"))` for a better test error message.

---

*[flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ExceptionStacktraceIT.java, line 46 at r1](https://reviewable.io:443/reviews/vaadin/flow/3266#-L24aTKMVhWVr10OVsnT:-L24aTKMVhWVr10OVsnU:bc1tnpv) ([raw file](https://github.com/vaadin/flow/blob/772809eb08815ec1297fe36b4064d12465ca35bd/flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ExceptionStacktraceIT.java#L46)):*
> ```Java
>         // second string is the cause of the exception. Both should be in the
>         // stacktrace
>         Assert.assertTrue("There is no stacktrace on the page",
> ```

Same as above: `assertThat` is preferable since it produces a better error message when the test fails.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3266)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[flow-server/src/test/java/com/vaadin/flow/router/InternalServerErrorTest.java, line 96 at r1](https://reviewable.io:443/reviews/vaadin/flow/3266#-L24cECr6T8gdjQstJ_V:-L24zyF6HBE9zlqYwDS1:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/772809eb08815ec1297fe36b4064d12465ca35bd/flow-server/src/test/java/com/vaadin/flow/router/InternalServerErrorTest.java#L96)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Why not also verifying the text of the NPE, since you have set it?
</blockquote></details>

Done.

---

*[flow-server/src/test/java/com/vaadin/flow/router/InternalServerErrorTest.java, line 121 at r1](https://reviewable.io:443/reviews/vaadin/flow/3266#-L24cR42GDs3HZgcjrYg:-L24zysX3WWuMXkKrFgY:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/772809eb08815ec1297fe36b4064d12465ca35bd/flow-server/src/test/java/com/vaadin/flow/router/InternalServerErrorTest.java#L121)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Same question as above.
</blockquote></details>

Done.

---

*[flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ExceptionStacktraceIT.java, line 37 at r1](https://reviewable.io:443/reviews/vaadin/flow/3266#-L24a0W5SrQb-SVi9W2K:-L25-ksvixIqISgtfzFN:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/772809eb08815ec1297fe36b4064d12465ca35bd/flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ExceptionStacktraceIT.java#L37)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Replace this with `Assert.assertThat("There is no warning message about SLF4J binding absence", warning.getText(), CoreMatchers.containsString("SL4J"))` for a better test error message.
</blockquote></details>

Done.

---

*[flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ExceptionStacktraceIT.java, line 46 at r1](https://reviewable.io:443/reviews/vaadin/flow/3266#-L24aTKMVhWVr10OVsnT:-L25-kUgUiZfJ5cljKgb:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/772809eb08815ec1297fe36b4064d12465ca35bd/flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ExceptionStacktraceIT.java#L46)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Same as above: `assertThat` is preferable since it produces a better error message when the test fails.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3266)*

**Comment by caalador** [comment]
You need to fix the RouterTest exception strings to match the new content created by the `InternalServerError`

**Comment by caalador** [comment]
Reviewed 2 of 5 files at r1, 2 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3266)*

**Comment by gilberto-torrezan** [comment]
Reviewed 2 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3266)*

**Comment by ahie** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ExceptionStacktraceIT.java, line 38 at r3](https://reviewable.io:443/reviews/vaadin/flow/3266#-L25A11jI-SXj6Xf5SL9:-L25A11jI-SXj6Xf5SLA:bqem15s) ([raw file](https://github.com/vaadin/flow/blob/b88849164da718b4de9406d7c5bf3983e19bd32f/flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ExceptionStacktraceIT.java#L38)):*
> ```Java
>         // no any SLF4J binding dependency in the project so this warning should
>         // be shown
>         Assert.assertThat(
> ```

Looks like this assertion is failing during validation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3266)*

**Comment by denis-anisimov** [comment]
Review status: 5 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ExceptionStacktraceIT.java, line 38 at r3](https://reviewable.io:443/reviews/vaadin/flow/3266#-L25A11jI-SXj6Xf5SL9:-L25B589VV1aRUhGmQE4:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/b88849164da718b4de9406d7c5bf3983e19bd32f/flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ExceptionStacktraceIT.java#L38)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

Looks like this assertion is failing during validation.
</blockquote></details>

Done.

---

*[flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ExceptionStacktraceIT.java, line 40 at r3](https://reviewable.io:443/reviews/vaadin/flow/3266#-L25A9xqjMtU9ZwlaFqV:-L25B2WAwvrw3GExWzYW:bmin8qf) ([raw file](https://github.com/vaadin/flow/blob/b88849164da718b4de9406d7c5bf3983e19bd32f/flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ExceptionStacktraceIT.java#L40)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

> SL4J

SLF4J perhaps
</blockquote></details>

Of course.
Thanks a lot !

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3266)*

**Comment by ahie** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3266)*

**Comment by ahie** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[flow-server/src/main/java/com/vaadin/flow/router/InternalServerError.java, line 97 at r4](https://reviewable.io:443/reviews/vaadin/flow/3266#-L24Vgi3U-t6k663S0Zg-r4-97:-L25F9_lyFv5qwW6tOpW:b-984q0a) ([raw file](https://github.com/vaadin/flow/blob/0fc00570a091db6efa10569f4f17d7ebe9a86014/flow-server/src/main/java/com/vaadin/flow/router/InternalServerError.java#L97)):*
> Change this "try" to a try-with-resources.

Would make it simpler, but not blocking in my opinion. You can dismiss sonar and merge, up to you.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3266)*

**Pull request merged**
