### PR TITLE
Add ListBox to bower.json

### PR DESCRIPTION
**Pull request by ZheSun88**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3281)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3281)*

**Comment by pekam** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3281#-L2Oq0fcKDvYUawFJIXb:-L2Oq0fcKDvYUawFJIXc:b-6ylc0o) (no related file):*
I think it's a bit misleading to have it in the bower.json without actually generating the API. (which I know you can't do)
Also, I recall this creating some dependency conflict that should be resolved too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3281)*

**Comment by SomeoneToIgnore** [comment]
*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3281#-L2Oq0fcKDvYUawFJIXb:-L2OqorJEjMvNgXgXqx1:buijikz) (no related file):*
> without actually generating the API

So you don't use the generated API after all?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3281)*

**Comment by ZheSun88** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3281#-L2Oq0fcKDvYUawFJIXb:-L2OqjmUnwA2jQvnzDUj:b-2hywqo) (no related file):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

> without actually generating the API

So you don't use the generated API after all?
</blockquote></details>

you mean the `ECONFLICT Unable to find suitable version for vaadin-list-mixin`, right, that is ture. so in this way, should we add it to the bower.json or not? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3281)*

**Comment by ZheSun88** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3281#-L2Oq0fcKDvYUawFJIXb:-L2OrK8ikhCMIsHfsaIY:b-9qmhgk) (no related file):*
> So you don't use the generated API after all?
he used the generated file, but i think he means that i should put the generated file into flow too...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3281)*

**Comment by SomeoneToIgnore** [comment]
*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3281#-L2Oq0fcKDvYUawFJIXb:-L2Or3Kfy2Q8RBOpx9Em:b-nsmbj6) (no related file):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

> So you don't use the generated API after all?
he used the generated file, but i think he means that i should put the generated file into flow too...
</blockquote></details>

My point is that if you use the generated API, then you have to sync the versions in bower.json (this is where the generated files come from now) and in webjars bom (this one ensures that we use the correct version when running the app).

Otherwise it looks really weird: you generate a java file for some specific webcomponent version and then use different version of the same webcomponent in runtime.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3281)*

**Comment by pekam** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3281#-L2Oq0fcKDvYUawFJIXb:-L2OrWMZ4Er9Jrgq5Qe8:bz9b0as) (no related file):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

My point is that if you use the generated API, then you have to sync the versions in bower.json (this is where the generated files come from now) and in webjars bom (this one ensures that we use the correct version when running the app).

Otherwise it looks really weird: you generate a java file for some specific webcomponent version and then use different version of the same webcomponent in runtime.
</blockquote></details>

I did use the generated API, I got the file from caalador who didn't make any PR to Flow about it.
The conflict can be resolved by updating `vaadin-tabs` to `2.0.0-alpha5`.

So the conflict should be resolved, the files should be actually generated and the new file for `vaadin-tabs` should be taken into use.

I would have done all of this if I could've run the generator...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3281)*

**Comment by ZheSun88** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3281#-L2Oq0fcKDvYUawFJIXb:-L2Ov50W80vfGnhIaNrG:b-pfr9l4) (no related file):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

I did use the generated API, I got the file from caalador who didn't make any PR to Flow about it.
The conflict can be resolved by updating `vaadin-tabs` to `2.0.0-alpha5`.

So the conflict should be resolved, the files should be actually generated and the new file for `vaadin-tabs` should be taken into use.

I would have done all of this if I could've run the generator...
</blockquote></details>

and same from my side, as i cannot generate the file either... the issue ticket has been taken by Ilia, so maybe at this point, i should ask someone for those two generated files and add them into this PR. Okay? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3281)*

**Comment by SomeoneToIgnore** [comment]
*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3281#-L2Oq0fcKDvYUawFJIXb:-L2Ov1-JTeyUQaIQODDb:by1cp1y) (no related file):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

and same from my side, as i cannot generate the file either... the issue ticket has been taken by Ilia, so maybe at this point, i should ask someone for those two generated files and add them into this PR. Okay? 
</blockquote></details>

Awesome, so the plan is to resolve conflicts (don't forget to update the bom with new vaadin-tabs version too), regenerate the files, hope that Ilia fixes the generator soon.

I'll do it in this branch then, if no one opposes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3281)*

**Comment by pekam** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3281#-L2Oq0fcKDvYUawFJIXb:-L2OwD6ajRSodbahnIcE:b-30yfwl) (no related file):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Awesome, so the plan is to resolve conflicts (don't forget to update the bom with new vaadin-tabs version too), regenerate the files, hope that Ilia fixes the generator soon.

I'll do it in this branch then, if no one opposes.
</blockquote></details>

Sounds good :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3281)*

**Comment by ZheSun88** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3281#-L2Oq0fcKDvYUawFJIXb:-L2Ovz4dMwVjX13BcScw:btodwo9) (no related file):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

Sounds good :)
</blockquote></details>

one concern is that,,, we are really not using the `vaadin-tabs` for the 2.0.0-alpha5 version in the component, which will cause some conflict there too... the version for the component is `1.0.0-beta1`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3281)*

**Comment by pekam** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3281#-L2Oq0fcKDvYUawFJIXb:-L2OwZ9spouerZ9jkgIk:bb60pm2) (no related file):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

one concern is that,,, we are really not using the `vaadin-tabs` for the 2.0.0-alpha5 version in the component, which will cause some conflict there too... the version for the component is `1.0.0-beta1`
</blockquote></details>

That's why I mentioned we should take the new generated file for `vaadin-tabs` into use

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3281)*

**Comment by ZheSun88** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3281#-L2Oq0fcKDvYUawFJIXb:-L2Owgg9O7Uc-UNg7tlz:b-hozy9s) (no related file):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

That's why I mentioned we should take the new generated file for `vaadin-tabs` into use
</blockquote></details>

so in this case... i can take the new generated `vaadin-tabs` and try to add it to the `vaadin-tabs-flow` .. solved?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3281)*

**Comment by pekam** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3281#-L2Oq0fcKDvYUawFJIXb:-L2OxF_RReJ9oc862g-2:b925x98) (no related file):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

so in this case... i can take the new generated `vaadin-tabs` and try to add it to the `vaadin-tabs-flow` .. solved?
</blockquote></details>

Maybe yes... But there might be some changes there that require further changes in the component. So make sure that everything works and check if there are some new generated methods that might need to be demonstrated etc.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3281)*

**Comment by ZheSun88** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3281#-L2Oq0fcKDvYUawFJIXb:-L2OxuzyIXiuFSCd2TOU:b-xmngzf) (no related file):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

Maybe yes... But there might be some changes there that require further changes in the component. So make sure that everything works and check if there are some new generated methods that might need to be demonstrated etc.
</blockquote></details>

sure... so i will ask @someonetoignore to offer me the new generated `vaadin-tabs` then.. :-)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3281)*

**Comment by SomeoneToIgnore** [comment]
*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3281#-L2Oq0fcKDvYUawFJIXb:-L2OxLl6CGFuvK7eNbaI:b-j9osuk) (no related file):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

sure... so i will ask @someonetoignore to offer me the new generated `vaadin-tabs` then.. :-)
</blockquote></details>

By the way, you have a very similar situation with `vaadin-dialog`: it's `1.0.1` in bower.json and `2.0.0-alpha1` in the bom. And if you upgrade the version in bower.json, it gives you a conflict also.

I have no clue how does it work now and I won't touch it in this PR, but this one is better to be fixed at some point also.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3281)*

**Comment by ZheSun88** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3281#-L2Oq0fcKDvYUawFJIXb:-L2OyuueZsu8ZVHdP2Qq:b8riyrc) (no related file):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

By the way, you have a very similar situation with `vaadin-dialog`: it's `1.0.1` in bower.json and `2.0.0-alpha1` in the bom. And if you upgrade the version in bower.json, it gives you a conflict also.

I have no clue how does it work now and I won't touch it in this PR, but this one is better to be fixed at some point also.
</blockquote></details>

maybe later, i will check and verify this issue.  better create a ticket based on this...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3281)*

**Comment by SomeoneToIgnore** [comment]
*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3281#-L2Oq0fcKDvYUawFJIXb:-L2OzHqikklRl46RC5Eh:bl15dgu) (no related file):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

maybe later, i will check and verify this issue.  better create a ticket based on this...
</blockquote></details>

https://github.com/vaadin/flow/issues/3237

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3281)*

**Comment by ZheSun88** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3281#-L2Oq0fcKDvYUawFJIXb:-L2OzQuhE031-IlCrdvy:b8hqyn3) (no related file):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

https://github.com/vaadin/flow/issues/3237
</blockquote></details>

NICE!!!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3281)*

**Comment by pekam** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3281#-L2Oq0fcKDvYUawFJIXb:-L2OzEl2o5CHEiVPP2bY:b-majvtp) (no related file):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

NICE!!!
</blockquote></details>

Oh, the dialog is my bad too... Luckily there seems to be no changes in the element-api so the api generated based on the older version works for the newest element version also.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3281)*

**Comment by ZheSun88** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3281#-L2Oq0fcKDvYUawFJIXb:-L2P-A9EICp6JE8GL8Oz:b8621kb) (no related file):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

Oh, the dialog is my bad too... Luckily there seems to be no changes in the element-api so the api generated based on the older version works for the newest element version also.
</blockquote></details>

okay, so for now, we will aim at fix the issue related to this branch..
@someonetoignore  will generate and add the files (tabs and listbox) into flow in this branch, maybe update the bom at the same time?

@pekam continue your work on listbox

I will update the tabs with the new generated tabs

do i understand correctly?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3281)*

**Comment by pekam** [comment]
Review status: 0 of 59 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3281#-L2Oq0fcKDvYUawFJIXb:-L2P0A17Bf3Cpv3wUfAH:b64o96x) (no related file):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

okay, so for now, we will aim at fix the issue related to this branch..
@someonetoignore  will generate and add the files (tabs and listbox) into flow in this branch, maybe update the bom at the same time?

@pekam continue your work on listbox

I will update the tabs with the new generated tabs

do i understand correctly?
</blockquote></details>

I think so :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3281)*

**Comment by SomeoneToIgnore** [comment]
*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3281#-L2Oq0fcKDvYUawFJIXb:-L2P0ElDnqV37xA-loIJ:b-goqxex) (no related file):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

I think so :)
</blockquote></details>

Files are in.
Someone had formatted the imports before committing them before (or generator had changed), that's why so many files are changed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3281)*

**Comment by pekam** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1, 60 of 60 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3281#-:-L2P4OjpdT5YO-B960E-:bnfp4nl)*

**Pull request merged**
