### PR TITLE
Add servlet containers parent IT tests module and tomcat modules

### PR DESCRIPTION
**Pull request by denis-anisimov**
Fix for #4220

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/4239)

### CODE REVIEW

**Comment by caalador** [comment]
Not running the tests at all on the server?

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4239#-:-LEP5eWGD3LkJG5zsFJ-:blhg0on)*

**Comment by denis-anisimov** [comment]
What do you mean ?

Tests are added as a dependency from `flow-test-root-context`  module.
`verify` goal will execute those IT tests.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4239#-:-LEPFQIuB4xOEx2uVdna:b-cue5xq)*

**Comment by caalador** [comment]
Yes, but I checked the build logs an it didn't run any tests on that module as the profile is not active nor activated. So no tomcat was ever initiated nor any extra tests run. 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4239#-:-LEPHUUU3ROHI06As7VH:bgcb6py)*

**Comment by caalador** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4239#-:-LEQ5QkY4Tjfb2c_bchh:bnfp4nl)*

**Pull request merged**
