### PR TITLE
Fix homebrew try-with-resources to behave like it is supposed to.

### PR DESCRIPTION
**Pull request by archiecobbs**
## Description

The fix for #8740 is broken because it doesn't properly replicate the behavior of the try-with-resources block that it replaced.

In particular, if an exception is thrown, and then another exception is thrown when trying to `close()` the stream, the exception that gets propagated to the outside world is the bogus/meaningless `close()` exception, not the actual root cause exception. This makes debugging much harder because the root cause exception is being completely lost.

## Type of change

- [X] Bugfix
- [ ] Feature

## Checklist

- [X] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [X] I have added a description following the guideline.
- [X] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [X] New and existing tests are passing locally with my change.
- [X] I have performed self-review and corrected misspellings.

### CODE REVIEW

**Comment by archiecobbs** [comment]
If accepted, please back-port this to 23.x as well. Thanks.

**Comment by mcollovati** [comment]
@archiecobbs thank you for the contribution.
The change looks good to me, and it is already covered by an existing test.
Can you please format the code, as reported in the above comment?

**Comment by mcollovati** [comment]
Just one more thing. To avoid regressions in the future, may I ask you to update the `StreamResourceHandlerTest` test?

* adding an assertion to ensure the expected exception is propagated in `inputStreamFactoryThrowsException_responseStatusIs500` and `inputStreamResourceWriterThrows_responseStatusIs500`
  ```java
    } catch (RuntimeException exception) {
        Assert.assertEquals("Simulated", exception.getMessage());
    }
  ```
* add a new test that simulates an exception on `ServletOutputStream.close()` and verifies that the expected exception is propagated
  ```java
  @Test
  public void inputStreamResourceWriterAndResponseThrows_streamResourceWriterExceptionIsPropagated()
          throws IOException {
      ServletOutputStream servletOutputStream = Mockito.mock(ServletOutputStream.class);
      Mockito.when(response.getOutputStream()).thenReturn(servletOutputStream);
      Mockito.doThrow(new RuntimeException("Error on close")).when(servletOutputStream).close();
      StreamResource res = new StreamResource("readme.md",
              (StreamResourceWriter) (stream, session) -> {
                  throw new RuntimeException("Simulated");
              });
      try {
          handler.handleRequest(session, request, response, res);
      } catch (RuntimeException exception) {
          Assert.assertEquals("Simulated", exception.getMessage());
      }
      Mockito.verify(response)
            .setStatus(HttpStatusCode.INTERNAL_SERVER_ERROR.getCode());
    }

  ```

**Review by mcollovati — DISMISSED** [review]

**Review by mcollovati — APPROVED** [review]

**Comment by mcollovati** [comment]
@archiecobbs thank you for the contribution!

**Comment by mcollovati** [comment]
I'll take care of the manual cherry-pick

**Pull request merged**
