### PR TITLE
Allow overriding default disabled behavior for client->server communication

### PR DESCRIPTION
**Pull request by denis-anisimov**
Fix for #3808

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3862)

### CODE REVIEW

**Comment by gilberto-torrezan** [comment]
Reviewed 32 of 32 files at r1, 1 of 8 files at r2.
Review status: 24 of 31 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[flow-server/src/main/java/com/vaadin/flow/component/ComponentEventBus.java, line 160 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3862#-L9oR5yL-8blLm2k-U-Q:-L9oR5yL-8blLm2k-U-R:byp2v9t) ([raw file](https://github.com/vaadin/flow/blob/5f6978612982c02de67be51d39c71d407fd1d3d4/flow-server/src/main/java/com/vaadin/flow/component/ComponentEventBus.java#L160)):*
> ```Java
>      */
>     private void addDomTrigger(Class<? extends ComponentEvent<?>> eventType,
>             String domEventType, DisabledUpdateMode mode) {
> ```

The be consistent with the other parameters, there should be an `assert` for the `DisabledUpdateMode` here as well.

---

*[flow-server/src/main/java/com/vaadin/flow/component/ComponentEventBusUtil.java, line 227 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3862#-L9oRd-T0kwz5vTbC0Wl:-L9oRd-T0kwz5vTbC0Wm:b-1vnoff) ([raw file](https://github.com/vaadin/flow/blob/5f6978612982c02de67be51d39c71d407fd1d3d4/flow-server/src/main/java/com/vaadin/flow/component/ComponentEventBusUtil.java#L227)):*
> if annotation presents.

`if the annotation is present.`

---

*[flow-server/src/main/java/com/vaadin/flow/component/ComponentUtil.java, line 305 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3862#-L9oSFTbEgIk-CV9ufym:-L9oSFTbEgIk-CV9ufyn:b8pds0r) ([raw file](https://github.com/vaadin/flow/blob/5f6978612982c02de67be51d39c71d407fd1d3d4/flow-server/src/main/java/com/vaadin/flow/component/ComponentUtil.java#L305)):*
> ```Java
>      * @return the synchronized properties defined declaratively for the class
>      */
>     public static Map<String, DisabledUpdateMode> getSynchronizedProperties(
> ```

You are converting from `SynchronizedPropertyInfo` to a Map just because the `SynchronizedPropertyInfo` is from the `internal` package? If there's no strong reason to create the Map I'd say it would be better to use the object, since things can be more easily updated in the future if needed (by adding and removing fields on the object).

---

*[flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/EventHandler.java, line 41 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3862#-L9oT8Vc210hWZo4qrx0:-L9oT8Vc210hWZo4qrx1:bswvt4u) ([raw file](https://github.com/vaadin/flow/blob/5f6978612982c02de67be51d39c71d407fd1d3d4/flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/EventHandler.java#L41)):*
> RPC for the method

`event handling`

---

*[flow-server/src/main/java/com/vaadin/flow/dom/Element.java, line 1522 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3862#-L9oTli-4OvN7p3L6t6Y:-L9oTli-4OvN7p3L6t6Z:bieoxc0) ([raw file](https://github.com/vaadin/flow/blob/5f6978612982c02de67be51d39c71d407fd1d3d4/flow-server/src/main/java/com/vaadin/flow/dom/Element.java#L1522)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>         while (parent != null) {
>             if (!parent.isEnabled()) {
>                 return false;
>             }
>             parent = parent.getParent();
>         }
> ```
</details>


This can be simplified to:
```
if (parent != null) {
    return parent.isEnabled();
}
```

---

*[flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/AbstractRpcInvocationHandler.java, line 64 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3862#-L9oV_1ACl0j4b4yUSe8:-L9oV_1ACl0j4b4yUSe9:b-o8a3ca) ([raw file](https://github.com/vaadin/flow/blob/5f6978612982c02de67be51d39c71d407fd1d3d4/flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/AbstractRpcInvocationHandler.java#L64)):*
> ```Java
>             return handleNode(node, invocationJson);
>         }
>         return Optional.empty();
> ```

This `return Optional.empty()` at the end of the method now looks strange, because it is executed when the `if` is executed. I suggest moving this inside the `if` block to make it clearer and isolated.

---

*[flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/MapSyncRpcHandler.java, line 90 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3862#-L9oWAoyEehZweHgcASD:-L9oWAoyEehZweHgcASE:b-dn2xia) ([raw file](https://github.com/vaadin/flow/blob/5f6978612982c02de67be51d39c71d407fd1d3d4/flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/MapSyncRpcHandler.java#L90)):*
> ```Java
>                     property);
>         } else {
>             LoggerFactory.getLogger(MapSyncRpcHandler.class).warn(
> ```

I wonder how spamy this will be, but only user feedback will tell.

---

*[flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/PublishedServerEventHandlerRpcHandler.java, line 105 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3862#-L9oWYs--WFnelnVv3Td:-L9oWYs--WFnelnVv3Te:b-fhlm2) ([raw file](https://github.com/vaadin/flow/blob/5f6978612982c02de67be51d39c71d407fd1d3d4/flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/PublishedServerEventHandlerRpcHandler.java#L105)):*
> ```Java
>         }
> 
>         boolean execute = isEnabled;
> ```

You don't use the `isEnabled` anymore after this point, so creating two booleans for the same thing feels redundant.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3862)*

**Comment by gilberto-torrezan** [comment]
Reviewed 7 of 8 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3862)*

**Comment by gilberto-torrezan** [comment]
Reviewed 8 of 8 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3862)*

**Comment by gilberto-torrezan** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/flow/3862#-L9olWTYConQ-38DzlqP:-L9olWTYConQ-38DzlqQ:b-fjnqdj) (no related file):*
Test are some weird test failures still.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3862)*

**Comment by denis-anisimov** [comment]
Review status: 30 of 31 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/flow/3862#-L9olWTYConQ-38DzlqP:-L9om6Td3P009RtLLgA0:b6nq1m6) (no related file):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Test are some weird test failures still.
</blockquote></details>

Compilation failure not a test failure.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3862)*

**Comment by gilberto-torrezan** [comment]
Review status: 30 of 31 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/flow/3862#-L9olWTYConQ-38DzlqP:-L9onqUMBREIpJhbkmRC:b-u1f1jz) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Compilation failure not a test failure.
</blockquote></details>

Oh, I saw `testbench` on the stacktrace and I thought it was a test failure. 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3862)*

**Comment by gilberto-torrezan** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3862)*

**Comment by gilberto-torrezan** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3862)*

**Comment by gilberto-torrezan** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[flow-server/src/main/java/com/vaadin/flow/internal/StateNode.java, line 852 at r6](https://beta.reviewable.io/reviews/vaadin/flow/3862#-L9sZvbz8S1BAepMr88V:-L9sZvc-9XQgigaU2XWP:b-hva5nt) ([raw file](https://github.com/vaadin/flow/blob/561d2eba8253ebbb2c18cbfbd61c33cf69286873/flow-server/src/main/java/com/vaadin/flow/internal/StateNode.java#L852)):*
> ```Java
>      * @return the node enabled own state
>      */
>     public boolean isEnabledSelf() {
> ```

Not sure about this name, but as usual I don't have better ideas. Maybe `isExplicitlyEnabled`. Meh. Not blocking.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3862#-:-L9s_Nap1IEpWReXMcjZ:bnfp4nl)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[flow-server/src/main/java/com/vaadin/flow/internal/StateNode.java, line 852 at r6](https://beta.reviewable.io/reviews/vaadin/flow/3862#-L9sZvbz8S1BAepMr88V:-L9sb0VX6Ib7BV1c-LFz:bfa9zxc) ([raw file](https://github.com/vaadin/flow/blob/561d2eba8253ebbb2c18cbfbd61c33cf69286873/flow-server/src/main/java/com/vaadin/flow/internal/StateNode.java#L852)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Not sure about this name, but as usual I don't have better ideas. Maybe `isExplicitlyEnabled`. Meh. Not blocking.
</blockquote></details>

The name is far away from the best I agree.
But I can't come up with better name. Can be a separate PR with the name change.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3862)*

**Pull request merged**
