### PR TITLE
Keep an eye on following the data provider contract

### PR DESCRIPTION
**Pull request by denis-anisimov**
Fixes vaadin/vaadin-grid-flow#171

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/4036)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java, line 324 at r1](https://reviewable.io/reviews/vaadin/flow/4036#-LBPll2Z0ylHkL9CTGMq:-LBQgArO0WminjjZVv5N:b-6fji5f) ([raw file](https://github.com/vaadin/flow/blob/fd5eabf6329217c09b4889fb63d72d15f1e0122b/flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java#L324)):*
> as long as we assert that stream.isParallel() is false

This is the exact assertion which I'm trying to avoid.
Would be  absolutely agree about `AtomicInteger` if didn't care about parallel streams.
Can we really make this assertion for sure ?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4036)*

**Comment by Legioth** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java, line 324 at r1](https://reviewable.io/reviews/vaadin/flow/4036#-LBPll2Z0ylHkL9CTGMq:-LBQjL02-tU1YBJFqkGz:b-scuk5y) ([raw file](https://github.com/vaadin/flow/blob/fd5eabf6329217c09b4889fb63d72d15f1e0122b/flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java#L324)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> as long as we assert that stream.isParallel() is false

This is the exact assertion which I'm trying to avoid.
Would be  absolutely agree about `AtomicInteger` if didn't care about parallel streams.
Can we really make this assertion for sure ?
</blockquote></details>

I actually think it would be better to explicitly require that the stream is not parallel, since the returned stream is terminated by a `forEach` that manipulates shared state.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4036)*

**Comment by denis-anisimov** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java, line 324 at r1](https://reviewable.io/reviews/vaadin/flow/4036#-LBPll2Z0ylHkL9CTGMq:-LBULdhR7Q3c57ZLe25i:bdl9kzn) ([raw file](https://github.com/vaadin/flow/blob/fd5eabf6329217c09b4889fb63d72d15f1e0122b/flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java#L324)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

I actually think it would be better to explicitly require that the stream is not parallel, since the returned stream is terminated by a `forEach` that manipulates shared state.
</blockquote></details>

You mean check whether it's parallel or not right here ?

At least javadocs also needs to be updated.
But this is just only place which uses this method.
It would be better to prevent returning parallel streams from the data provider directly somehow....

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4036)*

**Comment by Legioth** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java, line 324 at r1](https://reviewable.io/reviews/vaadin/flow/4036#-LBPll2Z0ylHkL9CTGMq:-LBUe1S1DXHibcBrXws8:b6igeub) ([raw file](https://github.com/vaadin/flow/blob/fd5eabf6329217c09b4889fb63d72d15f1e0122b/flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java#L324)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

You mean check whether it's parallel or not right here ?

At least javadocs also needs to be updated.
But this is just only place which uses this method.
It would be better to prevent returning parallel streams from the data provider directly somehow....
</blockquote></details>

I think it's reasonable to update the `DataProvider` API to explicitly require that the stream is not parallel. We cannot fully enforce this this requirement, but we can mention it in the javadocs and make at least the most common caller (i.e. this method) check the status of the stream.

Another alternative could be to change this method to explicitly `collect` the items to a list if the stream is parallel (or always to keep the code simple and consistent), and then the size check can be done based on the list instead.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4036)*

**Comment by denis-anisimov** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java, line 324 at r1](https://reviewable.io/reviews/vaadin/flow/4036#-LBPll2Z0ylHkL9CTGMq:-LBUnhDdBPnNIKkJCKV8:b3yx9cl) ([raw file](https://github.com/vaadin/flow/blob/fd5eabf6329217c09b4889fb63d72d15f1e0122b/flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java#L324)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

I think it's reasonable to update the `DataProvider` API to explicitly require that the stream is not parallel. We cannot fully enforce this this requirement, but we can mention it in the javadocs and make at least the most common caller (i.e. this method) check the status of the stream.

Another alternative could be to change this method to explicitly `collect` the items to a list if the stream is parallel (or always to keep the code simple and consistent), and then the size check can be done based on the list instead.
</blockquote></details>

Decided to make some kind of hybrid approach.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4036)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java, line 351 at r2](https://reviewable.io/reviews/vaadin/flow/4036#-LBZdLxJC1yKM1wnoCu9:-LBZloSb0R0NBhPL3x4V:bxhn048) ([raw file](https://github.com/vaadin/flow/blob/ab64394f908aac47aab84102b4770cbeef39dd46/flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java#L351)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Why do you need to check whether the stream is parallel?
</blockquote></details>

There should be a discussion with Leif available around.

The stream instance which is parallel may be navigated through by many threads at the moment.
It means that consumer in the `peek` method should be thread safe.
In original commit I've been using `AtomicReference`  but Leif noticed that we may assert that stream is not parallel since we are using `forEach` which modifies the internal state and this is already not thread safe.

One of the suggestion was to collect stream into list which cannot be parallel.
As a result I've decided to go with the hybrid approach.

---

*[flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java, line 354 at r2](https://reviewable.io/reviews/vaadin/flow/4036#-LBZdC2s-0y6skO_Gll1:-LBZmqdX8zM1f4yczmMI:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/ab64394f908aac47aab84102b4770cbeef39dd46/flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java#L354)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Typo on ` parallell` (extra `l` in the end)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4036)*

**Comment by gilberto-torrezan** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4036#-:-LBZoB_u-JnTA2uD24i8:bnfp4nl)*

**Pull request merged**
