### PR TITLE
Properly encoded URIs use %20

### LINKED ISSUE #5360: Vaadin downloader (via StreamResource) replaces spaces ' ' with '+'
File name, which contains '+' is not handled by downloader properly, since Vaadin downloader  (via StreamResource) replaces spaces ' ' with '+' and interprets '+' not as a regular character.

### PR DESCRIPTION
**Pull request by ajgassner**
should fix #5360

see https://stackoverflow.com/a/31612226/1296333

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/8271)

### CODE REVIEW

**Comment by caalador** [comment]
This patch should fix the PR I couldn't push so I need to as if you could put in the patch.
[0001-Do-not-change-resource-name.patch.txt](https://github.com/vaadin/flow/files/4633007/0001-Do-not-change-resource-name.patch.txt)

**Comment by ajgassner** [comment]
@caalador you are now contributor of git@github.com:ajgassner/flow.git Please push your changes to master.

**Comment by mehdi-vaadin** [comment]
@ajgassner thanks for your PR. Is the proposed change supposed to fix the following piece of code too? 
```
Anchor downloadAnchor = new Anchor(new StreamResource("a+b.txt", (stream, session) -> {
    stream.write("Something".getBytes());
}), "download");

add(downloadAnchor);
```
I tried it and got this error:
HTTP ERROR 404 Resource is not found for path=VAADIN/dynamic/resource/2/50719cd4-6a52-4240-a9f9-dbcae9618f49/a+b.txt

**Comment by ajgassner** [comment]
@mehdi-vaadin Yes it is. Mhm the genmerated URI should end with a%20b.txt

**Comment by mehdi-vaadin** [comment]
The whole error page:
image

**Comment by caalador** [comment]
@mehdi did you test with my patch in?

**Comment by mehdi-vaadin** [comment]
Yes, I got your patch.

**Comment by caalador** [comment]
That's interesting as if I add a new test:
```

    @Test
    public void streamResourceNameContainsPlusInMiddle_resourceIsStreamed()
            throws IOException {
        final String testString = "test";

        final byte[] testBytes = testString.getBytes();
        StreamResource res = new StreamResource("readme+mine.md",
                () -> new ByteArrayInputStream(testBytes));

        final StreamRegistration streamRegistration = streamResourceRegistry
                .registerResource(res);

        ServletOutputStream outputStream = Mockito
                .mock(ServletOutputStream.class);
        Mockito.when(response.getOutputStream()).thenReturn(outputStream);
        Mockito.when(request.getPathInfo()).thenReturn(
                String.format("/%s%s/%s/%s", DYN_RES_PREFIX,
                        ui.getId().orElse("-1"), res.getId(), res.getName()));

        handler.handleRequest(session, request, response);

        Mockito.verify(response).getOutputStream();

        ArgumentCaptor<byte[]> argument = ArgumentCaptor.forClass(byte[].class);
        Mockito.verify(outputStream)
                .write(argument.capture(), Mockito.anyInt(), Mockito.anyInt());

        byte[] buf = new byte[1024];
        for (int i = 0; i < testBytes.length; i++) {
            buf[i] = testBytes[i];
        }
        Assert.assertArrayEquals("Output differed from expected", buf,
                argument.getValue());
        Mockito.verify(response).setCacheTime(Mockito.anyInt());
        Mockito.verify(response).setContentType("application/octet-stream");
    }
```
for StreamRequestHandlerTest it passes and also if I change the IT to use a+b.txt istead of file+.jpg the test passes

**Comment by mehdi-vaadin** [comment]
Apparently, I missed something when I tried it earlier. I tested it again and it worked well.

**Pull request merged**
