### PR TITLE
Registered routes can now be requested.

### PR DESCRIPTION
**Pull request by caalador**
All router registered routes can be gotten as a List<RouteData>

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3205)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 5 of 5 files at r1.
Review status: 3 of 5 files reviewed at latest revision, 12 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/internal/ReflectTools.java, line 588 at r1](https://reviewable.io:443/reviews/vaadin/flow/3205#-L0xN0EneAQdNyVn_uTB:-L0xN0EneAQdNyVn_uTC:b-suqf08) ([raw file](https://github.com/vaadin/flow/blob/f8cb68eb0dc720a50880e25c06885337dc22f207/flow-server/src/main/java/com/vaadin/flow/internal/ReflectTools.java#L588)):*
>  Type[] genericInterfaces = getGenericInterfaces(clazz, interfaceType);
<details><summary><i alt="summary">Quoted 16 lines of code…</i></summary>
>         ParameterizedType parameterizedType = null;
>         for (Type genericInterface : genericInterfaces) {
>             Class<?> interfaceClass = getInterfaceClass(genericInterface);
>             if (interfaceType.isAssignableFrom(interfaceClass)) {
>                 parameterizedType = (ParameterizedType) genericInterface;
>             }
>         }
>         if (parameterizedType == null) {
>             return null;
>         }
>         Type[] typeArguments = parameterizedType.getActualTypeArguments();
>         if (typeArguments[0] instanceof Class) {
>             return (Class<?>) typeArguments[0];
>         }
>         return null;
>     }
</details>


There is a new code as I understand.

I would like to have unit tests for this code.

---

*[flow-server/src/main/java/com/vaadin/flow/internal/ReflectTools.java, line 634 at r1](https://reviewable.io:443/reviews/vaadin/flow/3205#-L0xKgs0E9YvlXh8spNq:-L0xKgs0E9YvlXh8spNr:b-hx44i7) ([raw file](https://github.com/vaadin/flow/blob/f8cb68eb0dc720a50880e25c06885337dc22f207/flow-server/src/main/java/com/vaadin/flow/internal/ReflectTools.java#L634)):*
> combine

I don't think that array is a good choice here.
Every time when this method is invoked a new array is created and copy is done.
Use list instead. Event `ArrayList`  is better here since it may increase its internal storage so that 
it doesn't need to create a new array all the time.

---

*[flow-server/src/main/java/com/vaadin/flow/internal/ReflectTools.java, line 640 at r1](https://reviewable.io:443/reviews/vaadin/flow/3205#-L0xKSZXmwN5cXMgKKV6:-L0xKSZXmwN5cXMgKKV7:bcgibxr) ([raw file](https://github.com/vaadin/flow/blob/f8cb68eb0dc720a50880e25c06885337dc22f207/flow-server/src/main/java/com/vaadin/flow/internal/ReflectTools.java#L640)):*
> combine

`merge`  ?

---

*[flow-server/src/main/java/com/vaadin/flow/router/RouteData.java, line 36 at r1](https://reviewable.io:443/reviews/vaadin/flow/3205#-L0xGQS91Cz5tVXxd_cg-r1-36:-L0xLHfjJZ-9-YwLAfWK:br0b89u) ([raw file](https://github.com/vaadin/flow/blob/f8cb68eb0dc720a50880e25c06885337dc22f207/flow-server/src/main/java/com/vaadin/flow/router/RouteData.java#L36)):*
<details><summary><i>Previously, vaadin-bot (Vaadin Bot) wrote…</i></summary><blockquote>

CRITICAL First sentence of Javadoc is incomplete (period is missing) or not present. [rule](https://sonar.projects.vaadin.com/coding_rules#rule_key=checkstyle%3Acom.puppycrawl.tools.checkstyle.checks.javadoc.SummaryJavadocCheck)
</blockquote></details>

You will need to fix this.

---

*[flow-server/src/main/java/com/vaadin/flow/router/RouteData.java, line 52 at r1](https://reviewable.io:443/reviews/vaadin/flow/3205#-L0xGQS91Cz5tVXxd_cg-r1-52:-L0xLMs_jeI7h0hMdw8Y:b-h27cr1) ([raw file](https://github.com/vaadin/flow/blob/f8cb68eb0dc720a50880e25c06885337dc22f207/flow-server/src/main/java/com/vaadin/flow/router/RouteData.java#L52)):*
<details><summary><i>Previously, vaadin-bot (Vaadin Bot) wrote…</i></summary><blockquote>

MAJOR Should com.vaadin.flow.router.RouteData$AliasData be a _static_ inner class? [rule](https://sonar.projects.vaadin.com/coding_rules#rule_key=findbugs%3ASIC_INNER_SHOULD_BE_STATIC)
</blockquote></details>

Most likely it's true

---

*[flow-server/src/main/java/com/vaadin/flow/router/RouteData.java, line 102 at r1](https://reviewable.io:443/reviews/vaadin/flow/3205#-L0xLZEUVNKaGKGhFXV4:-L0xLZEUVNKaGKGhFXV5:b-ndjel9) ([raw file](https://github.com/vaadin/flow/blob/f8cb68eb0dc720a50880e25c06885337dc22f207/flow-server/src/main/java/com/vaadin/flow/router/RouteData.java#L102)):*
> Collections.sort(routeAliases,
>                 (o1, o2) -> o1.getUrl().compareToIgnoreCase(o2.getUrl()));

Why don't make `AliasData` comparable ?

---

*[flow-server/src/main/java/com/vaadin/flow/router/Router.java, line 409 at r1](https://reviewable.io:443/reviews/vaadin/flow/3205#-L0xLlyMCZcpqOX1xSfe:-L0xLlyMCZcpqOX1xSff:bhdnrco) ([raw file](https://github.com/vaadin/flow/blob/f8cb68eb0dc720a50880e25c06885337dc22f207/flow-server/src/main/java/com/vaadin/flow/router/Router.java#L409)):*
> getRoutes().forEach(route -> {
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>
>             List<RouteData> routeDataList = grouped.computeIfAbsent(
>                     route.getParentLayout(), key -> new ArrayList<>());
>             routeDataList.add(route);
>         });
</details>

I think it may be done via `Stream` and `collect` using `Collectros.toMap()`.
But it's not a blocker.

---

*[flow-server/src/main/java/com/vaadin/flow/server/startup/RouteRegistry.java, line 176 at r1](https://reviewable.io:443/reviews/vaadin/flow/3205#-L0xM4rx5toU2DW-lMXX:-L0xM4rx5toU2DW-lMXY:b-wqj98q) ([raw file](https://github.com/vaadin/flow/blob/f8cb68eb0dc720a50880e25c06885337dc22f207/flow-server/src/main/java/com/vaadin/flow/server/startup/RouteRegistry.java#L176)):*
> Collections.sort(routes,
>                     (o1, o2) -> o1.getUrl().compareToIgnoreCase(o2.getUrl()));

Why not make `RouteData` `Comparable` ?

---

*[flow-server/src/main/java/com/vaadin/flow/server/startup/RouteRegistry.java, line 178 at r1](https://reviewable.io:443/reviews/vaadin/flow/3205#-L0xMG9lZeP8r7cyNpkZ:-L0xMG9lZeP8r7cyNpk_:b3oawkt) ([raw file](https://github.com/vaadin/flow/blob/f8cb68eb0dc720a50880e25c06885337dc22f207/flow-server/src/main/java/com/vaadin/flow/server/startup/RouteRegistry.java#L178)):*
> routeData.set(routes);

May be it doesn't matter but this code may be executed several times.
If the result is always the same then `set` is safe here.
But it might be that `compareAndSet(null, routes)`  is better.
Though it doesn't prevent the possible computation of the list anyway.
It just allows to make sure that the list instance is always the same.
May be it doesn't matter.

---

*[flow-server/src/main/java/com/vaadin/flow/server/startup/RouteRegistry.java, line 190 at r1](https://reviewable.io:443/reviews/vaadin/flow/3205#-L0xMdzhzihyq0qtL06B:-L0xMdzhzihyq0qtL06C:b-zi1iyp) ([raw file](https://github.com/vaadin/flow/blob/f8cb68eb0dc720a50880e25c06885337dc22f207/flow-server/src/main/java/com/vaadin/flow/server/startup/RouteRegistry.java#L190)):*
> private Optional<List<Class<?>>> 

Is it important to return `Optional` here?
Empty list is not enough ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3205)*

**Comment by denis-anisimov** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3205)*

**Comment by caalador** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks broke.

---

*[flow-server/src/main/java/com/vaadin/flow/internal/ReflectTools.java, line 588 at r1](https://reviewable.io:443/reviews/vaadin/flow/3205#-L0xN0EneAQdNyVn_uTB:-L0xOQRj-q1cCSf-zLss:b-sa0gkc) ([raw file](https://github.com/vaadin/flow/blob/f8cb68eb0dc720a50880e25c06885337dc22f207/flow-server/src/main/java/com/vaadin/flow/internal/ReflectTools.java#L588)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

>  Type[] genericInterfaces = getGenericInterfaces(clazz, interfaceType);
>         ParameterizedType parameterizedType = null;
>         for (Type genericInterface : genericInterfaces) {
>             Class<?> interfaceClass = getInterfaceClass(genericInterface);
>             if (interfaceType.isAssignableFrom(interfaceClass)) {
>                 parameterizedType = (ParameterizedType) genericInterface;
>             }
>         }
>         if (parameterizedType == null) {
>             return null;
>         }
>         Type[] typeArguments = parameterizedType.getActualTypeArguments();
>         if (typeArguments[0] instanceof Class) {
>             return (Class<?>) typeArguments[0];
>         }
>         return null;
>     }


There is a new code as I understand.

I would like to have unit tests for this code.
</blockquote></details>

It's the same code that was there it's just moved into 2 different methods for reuse.

Added direct test, but feature is also tested through Router and RouterRegistry tests.

---

*[flow-server/src/main/java/com/vaadin/flow/internal/ReflectTools.java, line 634 at r1](https://reviewable.io:443/reviews/vaadin/flow/3205#-L0xKgs0E9YvlXh8spNq:-L0xPIsz10ef0MvsvgEF:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/f8cb68eb0dc720a50880e25c06885337dc22f207/flow-server/src/main/java/com/vaadin/flow/internal/ReflectTools.java#L634)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> combine

I don't think that array is a good choice here.
Every time when this method is invoked a new array is created and copy is done.
Use list instead. Event `ArrayList`  is better here since it may increase its internal storage so that 
it doesn't need to create a new array all the time.
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/flow/internal/ReflectTools.java, line 640 at r1](https://reviewable.io:443/reviews/vaadin/flow/3205#-L0xKSZXmwN5cXMgKKV6:-L0xPJAmvEyi35tGM_89:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/f8cb68eb0dc720a50880e25c06885337dc22f207/flow-server/src/main/java/com/vaadin/flow/internal/ReflectTools.java#L640)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> combine

`merge`  ?
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/flow/router/RouteData.java, line 36 at r1](https://reviewable.io:443/reviews/vaadin/flow/3205#-L0xGQS91Cz5tVXxd_cg-r1-36:-L0xR70BcL3LnMVenBkX:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/f8cb68eb0dc720a50880e25c06885337dc22f207/flow-server/src/main/java/com/vaadin/flow/router/RouteData.java#L36)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

You will need to fix this.
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/flow/router/RouteData.java, line 52 at r1](https://reviewable.io:443/reviews/vaadin/flow/3205#-L0xGQS91Cz5tVXxd_cg-r1-52:-L0xR8FKNr0QvqKIQCz_:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/f8cb68eb0dc720a50880e25c06885337dc22f207/flow-server/src/main/java/com/vaadin/flow/router/RouteData.java#L52)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Most likely it's true
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/flow/router/RouteData.java, line 102 at r1](https://reviewable.io:443/reviews/vaadin/flow/3205#-L0xLZEUVNKaGKGhFXV4:-L0xU4k-ftlBZJnNWHZN:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/f8cb68eb0dc720a50880e25c06885337dc22f207/flow-server/src/main/java/com/vaadin/flow/router/RouteData.java#L102)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> Collections.sort(routeAliases,
>                 (o1, o2) -> o1.getUrl().compareToIgnoreCase(o2.getUrl()));

Why don't make `AliasData` comparable ?
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/flow/router/Router.java, line 409 at r1](https://reviewable.io:443/reviews/vaadin/flow/3205#-L0xLlyMCZcpqOX1xSfe:-L0xSQNq-XUMmbYFmFoS:bay47ms) ([raw file](https://github.com/vaadin/flow/blob/f8cb68eb0dc720a50880e25c06885337dc22f207/flow-server/src/main/java/com/vaadin/flow/router/Router.java#L409)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> getRoutes().forEach(route -> {
>             List<RouteData> routeDataList = grouped.computeIfAbsent(
>                     route.getParentLayout(), key -> new ArrayList<>());
>             routeDataList.add(route);
>         });

I think it may be done via `Stream` and `collect` using `Collectros.toMap()`.
But it's not a blocker.
</blockquote></details>

I'll keep this for readability that strange stream mappings bring.
Also removed lambda as it just makes it look messy.

---

*[flow-server/src/main/java/com/vaadin/flow/server/startup/RouteRegistry.java, line 176 at r1](https://reviewable.io:443/reviews/vaadin/flow/3205#-L0xM4rx5toU2DW-lMXX:-L0xSi-1ghu-CNQrcpu0:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/f8cb68eb0dc720a50880e25c06885337dc22f207/flow-server/src/main/java/com/vaadin/flow/server/startup/RouteRegistry.java#L176)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> Collections.sort(routes,
>                     (o1, o2) -> o1.getUrl().compareToIgnoreCase(o2.getUrl()));

Why not make `RouteData` `Comparable` ?
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/flow/server/startup/RouteRegistry.java, line 178 at r1](https://reviewable.io:443/reviews/vaadin/flow/3205#-L0xMG9lZeP8r7cyNpkZ:-L0xSnWsnG_TaWkA1T3X:b3tcngh) ([raw file](https://github.com/vaadin/flow/blob/f8cb68eb0dc720a50880e25c06885337dc22f207/flow-server/src/main/java/com/vaadin/flow/server/startup/RouteRegistry.java#L178)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> routeData.set(routes);

May be it doesn't matter but this code may be executed several times.
If the result is always the same then `set` is safe here.
But it might be that `compareAndSet(null, routes)`  is better.
Though it doesn't prevent the possible computation of the list anyway.
It just allows to make sure that the list instance is always the same.
May be it doesn't matter.
</blockquote></details>

Basically it doesn't matter, it's just to have to construct it "once" when it's first needed as it doesn't change, but we probably never need the data so we don't pre construct it either.

---

*[flow-server/src/main/java/com/vaadin/flow/server/startup/RouteRegistry.java, line 190 at r1](https://reviewable.io:443/reviews/vaadin/flow/3205#-L0xMdzhzihyq0qtL06B:-L0xTUm3AFM9L694AINA:bch0pxe) ([raw file](https://github.com/vaadin/flow/blob/f8cb68eb0dc720a50880e25c06885337dc22f207/flow-server/src/main/java/com/vaadin/flow/server/startup/RouteRegistry.java#L190)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> private Optional<List<Class<?>>> 

Is it important to return `Optional` here?
Empty list is not enough ?
</blockquote></details>

It is. Don't know what I was thinking at the time... Something smart I hope.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3205)*

**Comment by denis-anisimov** [comment]
Reviewed 5 of 5 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[flow-server/src/test/java/com/vaadin/flow/internal/ReflectToolsTest.java, line 170 at r3](https://reviewable.io:443/reviews/vaadin/flow/3205#-L0xaBWbYq1NMru1oprK:-L0xaBWbYq1NMru1oprL:b-61r4dm) ([raw file](https://github.com/vaadin/flow/blob/f4162aa3577ded886af1804528f7742fb63eba57/flow-server/src/test/java/com/vaadin/flow/internal/ReflectToolsTest.java#L170)):*
> Class<?> genericInterfaceType = ReflectTools
>                 .getGenericInterfaceType(HasInterface.class,
>                         TestInterface.class);

I didn't go into details but the code in the test looks very familiar to me.
Doesn't it do the same as `GenericTypeReflector.getTypeParameter` (or very similar).
Please check `Composite::findContentType` .
Should we rewrite this method or even completely remove it from the `ReflectTools` ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3205)*

**Comment by caalador** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[flow-server/src/test/java/com/vaadin/flow/internal/ReflectToolsTest.java, line 170 at r3](https://reviewable.io:443/reviews/vaadin/flow/3205#-L0xaBWbYq1NMru1oprK:-L0xce7fMwH3fcqmSb07:b-ic4zey) ([raw file](https://github.com/vaadin/flow/blob/f4162aa3577ded886af1804528f7742fb63eba57/flow-server/src/test/java/com/vaadin/flow/internal/ReflectToolsTest.java#L170)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> Class<?> genericInterfaceType = ReflectTools
>                 .getGenericInterfaceType(HasInterface.class,
>                         TestInterface.class);

I didn't go into details but the code in the test looks very familiar to me.
Doesn't it do the same as `GenericTypeReflector.getTypeParameter` (or very similar).
Please check `Composite::findContentType` .
Should we rewrite this method or even completely remove it from the `ReflectTools` ?
</blockquote></details>

It's not the same as here we can target any interface eg we could implement 5 different interfaces and pick the 1 generic type that we need.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3205)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks broke.

---

*[flow-server/src/test/java/com/vaadin/flow/internal/ReflectToolsTest.java, line 170 at r3](https://reviewable.io:443/reviews/vaadin/flow/3205#-L0xaBWbYq1NMru1oprK:-L0xi2xhZ4Qo3K90Zouu:btlmj8m) ([raw file](https://github.com/vaadin/flow/blob/f4162aa3577ded886af1804528f7742fb63eba57/flow-server/src/test/java/com/vaadin/flow/internal/ReflectToolsTest.java#L170)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

It's not the same as here we can target any interface eg we could implement 5 different interfaces and pick the 1 generic type that we need.
</blockquote></details>

Sorry........
I didn't get it.
I would say that you described exactly what `GenericTypeReflector.getTypeParameter` .
What's the difference ?

`GenericTypeReflector.getTypeParameter` allows to get any real type from any superinterface/supertype of the class.
The only difference is that you should provide not a superinterface/superclass as a parameter to the `getTypeParameter` method but you need the "type parameter" itself.
Everything else is the same.

At least I don't see here an example which is not covered by the  `GenericTypeReflector.getTypeParameter`.

If we still are not on the same page then please:
- crest a test here which is not covered by the `GenericTypeReflector.getTypeParameter` in your opinion (or just point me one from the existing).
- I will try to show a code which solves the usecase via `GenericTypeReflector.getTypeParameter`.

At least this works fine: 

```
interface A<T> {

    }

    interface B<U> {

    }

    interface C extends B<String> {

    }

    interface D extends C, A<Long> {

    }

    @Test
    public void test() {
        Assert.assertEquals(Long.class, GenericTypeReflector
                .getTypeParameter(D.class, A.class.getTypeParameters()[0]));
        Assert.assertEquals(String.class, GenericTypeReflector
                .getTypeParameter(D.class, B.class.getTypeParameters()[0]));
    }
```

Am I missing something ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3205)*

**Comment by caalador** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks broke.

---

*[flow-server/src/test/java/com/vaadin/flow/internal/ReflectToolsTest.java, line 170 at r3](https://reviewable.io:443/reviews/vaadin/flow/3205#-L0xaBWbYq1NMru1oprK:-L0xwVctxIGQDNROZsnB:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/f4162aa3577ded886af1804528f7742fb63eba57/flow-server/src/test/java/com/vaadin/flow/internal/ReflectToolsTest.java#L170)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Sorry........
I didn't get it.
I would say that you described exactly what `GenericTypeReflector.getTypeParameter` .
What's the difference ?

`GenericTypeReflector.getTypeParameter` allows to get any real type from any superinterface/supertype of the class.
The only difference is that you should provide not a superinterface/superclass as a parameter to the `getTypeParameter` method but you need the "type parameter" itself.
Everything else is the same.

At least I don't see here an example which is not covered by the  `GenericTypeReflector.getTypeParameter`.

If we still are not on the same page then please:
- crest a test here which is not covered by the `GenericTypeReflector.getTypeParameter` in your opinion (or just point me one from the existing).
- I will try to show a code which solves the usecase via `GenericTypeReflector.getTypeParameter`.

At least this works fine: 

```
interface A<T> {

    }

    interface B<U> {

    }

    interface C extends B<String> {

    }

    interface D extends C, A<Long> {

    }

    @Test
    public void test() {
        Assert.assertEquals(Long.class, GenericTypeReflector
                .getTypeParameter(D.class, A.class.getTypeParameters()[0]));
        Assert.assertEquals(String.class, GenericTypeReflector
                .getTypeParameter(D.class, B.class.getTypeParameters()[0]));
    }
```

Am I missing something ?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3205)*

**Comment by denis-anisimov** [comment]
You will need unblock SQ.

:lgtm: 

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3205#-:-L0y9O8uevr2Nbe-HVpk:b-kp6gq6)*

**Pull request merged**
