### PR TITLE
Update Spring-boot to 2.0.0.M7

### PR DESCRIPTION
**Pull request by caalador**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3084)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-tests/test-spring-boot/src/main/java/com/vaadin/flow/spring/TestServletInitializer.java, line 25 at r1](https://reviewable.io:443/reviews/vaadin/flow/3084#-L-AsnpALFDUH738Ma84:-L-AsnpALFDUH738Ma85:bnlhz3t) ([raw file](https://github.com/vaadin/flow/blob/f6668c55c6e43ddb4171cddaab1646d2fb4eaf90/flow-tests/test-spring-boot/src/main/java/com/vaadin/flow/spring/TestServletInitializer.java#L25)):*
> //@EnableAuthorizationServer

????
That's very important thing.

It's intentionally here. There is a test for that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3084)*

**Comment by caalador** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-tests/test-spring-boot/src/main/java/com/vaadin/flow/spring/TestServletInitializer.java, line 25 at r1](https://reviewable.io:443/reviews/vaadin/flow/3084#-L-AsnpALFDUH738Ma84:-L-AuWmKvWyHdLCjNuNi:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/f6668c55c6e43ddb4171cddaab1646d2fb4eaf90/flow-tests/test-spring-boot/src/main/java/com/vaadin/flow/spring/TestServletInitializer.java#L25)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> //@EnableAuthorizationServer

????
That's very important thing.

It's intentionally here. There is a test for that.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3084)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3084)*

**Comment by denis-anisimov** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3084)*

**Comment by denis-anisimov** [comment]
Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3084)*

**Comment by denis-anisimov** [comment]
Reviewed 6 of 6 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3084)*

**Pull request merged**
