### PR TITLE
Add tabs for the demos. Refactor the demo to use @Route.

### PR DESCRIPTION
**Pull request by gilberto-torrezan**
Remove duplicated code between demo-flow-components and
flow-component-demo-helpers.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/2889)

### CODE REVIEW

**Comment by torok-peter** [comment]
Reviewed 38 of 38 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2889)*

**Comment by torok-peter** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2889)*

**Comment by torok-peter** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2889)*

**Comment by ahie** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2889)*

**Comment by torok-peter** [comment]
Reviewed 1 of 1 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2889)*

**Pull request merged**
