### PR TITLE
servlet path should not be considered when resolving files.

### PR DESCRIPTION
**Pull request by caalador**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3583)

### CODE REVIEW

**Comment by gilberto-torrezan** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[flow-server/src/test/java/com/vaadin/flow/theme/ThemeUrlResolverTest.java, line 129 at r1](https://reviewable.io:443/reviews/vaadin/flow/3583#-L5ri1wApvS9A-jjXdK2:-L5ri1wApvS9A-jjXdK3:b2f6jab) ([raw file](https://github.com/vaadin/flow/blob/393c36dd26a3c1d45f77abd1fa4f1567c7b3569f/flow-server/src/test/java/com/vaadin/flow/theme/ThemeUrlResolverTest.java#L129)):*
> ```Java
>     public void servlet_context_file_resolves_correct_url() throws Exception {
>         String path = "theme/custom/button.html";
>         Mockito.when(servletContext.getResource("/" + path))
> ```

Shouldn't we have some tests for both paths with and without `/` in the beginning (instead of converting all to `"/" + ...`) ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3583)*

**Comment by denis-anisimov** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java, line 664 at r1](https://reviewable.io:443/reviews/vaadin/flow/3583#-L5rjSeBy2AkOAt6SOQ8:-L5rjSeBy2AkOAt6SOQ9:bjfzyaq) ([raw file](https://github.com/vaadin/flow/blob/393c36dd26a3c1d45f77abd1fa4f1567c7b3569f/flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java#L664)):*
> if (!resolvedUrl.startsWith("/")) {
>             resolvedUrl = "/" + resolvedUrl;
>         }

The same code inside the `resourceIsFound` method.
May be worth to refactor ?

---

*[flow-server/src/test/java/com/vaadin/flow/theme/ThemeUrlResolverTest.java, line 129 at r1](https://reviewable.io:443/reviews/vaadin/flow/3583#-L5ri1wApvS9A-jjXdK2:-L5rjix61mjQnL7J2ie7:b-8ayu6x) ([raw file](https://github.com/vaadin/flow/blob/393c36dd26a3c1d45f77abd1fa4f1567c7b3569f/flow-server/src/test/java/com/vaadin/flow/theme/ThemeUrlResolverTest.java#L129)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Shouldn't we have some tests for both paths with and without `/` in the beginning (instead of converting all to `"/" + ...`) ?
</blockquote></details>

Agree

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3583)*

**Comment by caalador** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java, line 664 at r1](https://reviewable.io:443/reviews/vaadin/flow/3583#-L5rjSeBy2AkOAt6SOQ8:-L5rtn4zDvr1H7EFqOrI:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/393c36dd26a3c1d45f77abd1fa4f1567c7b3569f/flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java#L664)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> if (!resolvedUrl.startsWith("/")) {
>             resolvedUrl = "/" + resolvedUrl;
>         }

The same code inside the `resourceIsFound` method.
May be worth to refactor ?
</blockquote></details>

Done.

---

*[flow-server/src/test/java/com/vaadin/flow/theme/ThemeUrlResolverTest.java, line 129 at r1](https://reviewable.io:443/reviews/vaadin/flow/3583#-L5ri1wApvS9A-jjXdK2:-L5rmKWv82l4ItVbSbPE:b9xmw5h) ([raw file](https://github.com/vaadin/flow/blob/393c36dd26a3c1d45f77abd1fa4f1567c7b3569f/flow-server/src/test/java/com/vaadin/flow/theme/ThemeUrlResolverTest.java#L129)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Agree
</blockquote></details>

Well this is the mock of the servletContext. The thing is that both translations "/theme/custom/" and "theme/custom/" work, but the request that is made to the servletContext will always be with the starting "/" as else it's not a valid URL and will throw a MalformedURLException.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3583)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3583)*

**Comment by gilberto-torrezan** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3583)*

**Comment by gilberto-torrezan** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java, line 726 at r3](https://reviewable.io:443/reviews/vaadin/flow/3583#-L5ra8XGzMVbyj_7EWi1-r3-726:-L61-Ijvw8i8hDCFlfOl:b32v57) ([raw file](https://github.com/vaadin/flow/blob/273184406856ed34e5b234648116c1f026c67557/flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java#L726)):*
<details><summary><i>Previously, vaadin-bot (Vaadin Bot) wrote…</i></summary><blockquote>

MINOR Put single-quotes around '/' to use the faster "lastIndexOf(char)" method. [rule](https://sonar.projects.vaadin.com/coding_rules#rule_key=squid%3AS3027)
</blockquote></details>

+1

---

*[flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java, line 732 at r3](https://reviewable.io:443/reviews/vaadin/flow/3583#-L61AsGiNZNu5xyIoq7S:-L61AsGiNZNu5xyIoq7T:bacjry1) ([raw file](https://github.com/vaadin/flow/blob/273184406856ed34e5b234648116c1f026c67557/flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java#L732)):*
> ```Java
>             // context root.
>             for (String path : servletPath.split("/")) {
>                 resolvedUrl = resolvedUrl.replaceFirst("(../)", "");
> ```

This code looks a bit strange.... Maybe could use a single regex to rule them all?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3583)*

**Comment by caalador** [comment]
Review status: 4 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java, line 726 at r3](https://reviewable.io:443/reviews/vaadin/flow/3583#-L5ra8XGzMVbyj_7EWi1-r3-726:-L61F9KZAc4kiMLDM6iG:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/273184406856ed34e5b234648116c1f026c67557/flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java#L726)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java, line 732 at r3](https://reviewable.io:443/reviews/vaadin/flow/3583#-L61AsGiNZNu5xyIoq7S:-L61FBQ-X75xR_RiLm3v:bny1zjc) ([raw file](https://github.com/vaadin/flow/blob/273184406856ed34e5b234648116c1f026c67557/flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java#L732)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

This code looks a bit strange.... Maybe could use a single regex to rule them all?
</blockquote></details>

Changed it to read cleaner.
sadly I don't have a regex master badge yet. Nor do I want to get one.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3583)*

**Comment by gilberto-torrezan** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3583)*

**Pull request merged**
