### PR TITLE
Provide a way to listen polymer element readiness 

### PR DESCRIPTION
**Pull request by denis-anisimov**
Fix for #3276

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3280)

### CODE REVIEW

**Comment by caalador** [comment]
Some javaDocs missing. Also agree with sonar about removing the unused private methods.

---

Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3280#-:-L2OnT5IZ8P5LZ0w5sO5:b-5nkzde)*

**Comment by denis-anisimov** [comment]
Javadocs are corrected.

Unused private methods are out of scope of this PR.
Actually I don't even think that there are unused methods (SQ is not able to detect method references or they are referenced inside native JS code).

---

Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3280#-:-L2OoXq8JX01846FEVNn:b-p57tnr)*

**Comment by caalador** [comment]
I can't find any reference for extractNodeId (also it uses Optional which has had problems on the client side) nor bindElementFromShadowRootByTagName.

Added ticket ab out this as else it's always "out of scope" #3282

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3280#-:-L2Oq2rQ2ZMZPr8LZzmv:b-w5o0v0)*

**Comment by denis-anisimov** [comment]
I can fix it in the following PR which will modify the logic in the `SimpleElementBindingStrategy`  class.
This PR is quite isolated. Don't want to introduce more modifications.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3280#-:-L2OrT1pi0xEDWL3cWng:b-dtf2fg)*

**Pull request merged**
