### PR TITLE
Use project version for Flow dependencies

### PR DESCRIPTION
**Pull request by ZheSun88**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/2662)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 20 of 20 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2662)*

**Comment by SomeoneToIgnore** [comment]
*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2662#-KwF-KMxbnOY4M7emJr6:-KwF-HOyL8AK0oRfVjQ4:b-c34y8n) (no related file):*
Not all `${flow.version}` usages are removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2662)*

**Comment by ZheSun88** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2662#-KwF-KMxbnOY4M7emJr6:-KwF-NsNearzrQi2qKG6:b-9da2vf) (no related file):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Not all `${flow.version}` usages are removed.
</blockquote></details>

oh. let me check

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2662)*

**Comment by SomeoneToIgnore** [comment]
*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2662#-KwF-KMxbnOY4M7emJr6:-KwF-qbCdGLg4Mh2xoLO:b-vh16h1) (no related file):*
<details><summary><i>Previously, ZheSun88 wrote…</i></summary><blockquote>

oh. let me check
</blockquote></details>

/Users/someonetoignore/Work/flow/flow/flow-html-components/pom.xml

This requires to be adjusted also.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2662)*

**Comment by SomeoneToIgnore** [comment]
*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2662#-KwF-KMxbnOY4M7emJr6:-KwF-z60PiAHUJQoa_4h:br7dbxs) (no related file):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

/Users/someonetoignore/Work/flow/flow/flow-html-components/pom.xml

This requires to be adjusted also.
</blockquote></details>

flow/flow-tests/test-spring-boot/pom.xml

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2662)*

**Comment by SomeoneToIgnore** [comment]
*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2662#-KwF-KMxbnOY4M7emJr6:-KwF013eKlxAVC13TDIV:blstxna) (no related file):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

flow/flow-tests/test-spring-boot/pom.xml
</blockquote></details>

flow/flow-tests/test-spring-boot/pom.xml

That's not really a dependency, but it should be also fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2662)*

**Comment by ZheSun88** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2662#-KwF-KMxbnOY4M7emJr6:-KwF-uVy5MasK4bONK9C:b-oais10) (no related file):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

flow/flow-tests/test-spring-boot/pom.xml

That's not really a dependency, but it should be also fixed.
</blockquote></details>

you mean inside the artifactItem?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2662)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 1 of 20 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2662)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 17 of 20 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2662)*

**Pull request merged**
