### PR TITLE
Add event handler feature to the TamplteRenderer, and support for it on Grid cells.

### PR DESCRIPTION
**Pull request by gilberto-torrezan**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/2674)

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
Reviewed 5 of 7 files at r1, 1 of 1 files at r2.
Review status: 6 of 7 files reviewed at latest revision, 7 unresolved discussions.

---

*[flow-client/src/main/java/com/vaadin/client/ApplicationConnection.java, line 153 at r1](https://reviewable.io:443/reviews/vaadin/flow/2674#-KwJo-KbDWlW-yrrXeGK:-KwJo-KbDWlW-yrrXeGL:bw2bsao) ([raw file](https://github.com/vaadin/flow/blob/4bcb3cf86910579184e45c6829ad3e8206e7fc69/flow-client/src/main/java/com/vaadin/client/ApplicationConnection.java#L153)):*
> ```Java
>         
>         $wnd.vaadin.sendEventMessage = $entry(function(nodeId, eventType, eventData) {
>         	var sc = ap.@com.vaadin.client.ApplicationConnection::registry.@com.vaadin.client.Registry::getServerConnector()();
> ```

Tabs again. Is it configurable in Eclipse?

---

*[flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/views/GridView.java, line 96 at r1](https://reviewable.io:443/reviews/vaadin/flow/2674#-KwJrNv3cVU-4CKzVFJy:-KwJrNv3cVU-4CKzVFJz:b-3t1ajv) ([raw file](https://github.com/vaadin/flow/blob/4bcb3cf86910579184e45c6829ad3e8206e7fc69/flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/views/GridView.java#L96)):*
> ```Java
>             final int prime = 31;
>             int result = 1;
>             result = prime * result + id;
> ```

Would it be easier just to return an id? It's not like you make any difference if you add a constant to it, see `Integer#hasCode`

I also find it very dangerous to have non-final field being used in equals and hashCode computation, but, I guess, it does not really matter for the example.

---

*[flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/views/GridView.java, line 109 at r1](https://reviewable.io:443/reviews/vaadin/flow/2674#-KwJibjcawAYa9IqwjbE-r1-109:-KwJu6eRJauPLiJVZ_14:b8b25vc) ([raw file](https://github.com/vaadin/flow/blob/4bcb3cf86910579184e45c6829ad3e8206e7fc69/flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/views/GridView.java#L109)):*
<details><summary><i>Previously, vaadin-bot (Vaadin Bot) wrote…</i></summary><blockquote>

MINOR Replace this if-then-else statement by a single return statement. [rule](https://sonar.projects.vaadin.com/coding_rules#rule_key=squid%3AS1126)
</blockquote></details>

Why not.

---

*[flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/views/GridView.java, line 193 at r1](https://reviewable.io:443/reviews/vaadin/flow/2674#-KwJuhYv3izI2H_hC2DB:-KwJuhYv3izI2H_hC2DC:b7jvhzs) ([raw file](https://github.com/vaadin/flow/blob/4bcb3cf86910579184e45c6829ad3e8206e7fc69/flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/views/GridView.java#L193)):*
> ```Java
>          * portion of the data.
>          */
>         Random random = new Random(0);
> ```

Can you just use `ThreadLocalRandom` here? 
You don't have to duplicate it and drag it around and you will be able to use `createPerson` as a method reference again.

---

*[flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/views/GridView.java, line 195 at r1](https://reviewable.io:443/reviews/vaadin/flow/2674#-KwJtYHWyQfhmVERmfmN:-KwJtYHXMsCYpTOsLeZ-:bdl8sw) ([raw file](https://github.com/vaadin/flow/blob/4bcb3cf86910579184e45c6829ad3e8206e7fc69/flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/views/GridView.java#L195)):*
> ```Java
>         Random random = new Random(0);
>         grid.setDataProvider(DataProvider.fromCallbacks(query -> {
>             return IntStream
> ```

In case you'd like to remove some extra verbosity, `return` can be removed.

---

*[flow-components-parent/demo-flow-components/src/test/java/com/vaadin/flow/demo/ComponentDemoTest.java, line 74 at r1](https://reviewable.io:443/reviews/vaadin/flow/2674#-KwJxTvKc6l0DS0bEEOr:-KwJxTvKc6l0DS0bEEOs:b-6ua94z) ([raw file](https://github.com/vaadin/flow/blob/4bcb3cf86910579184e45c6829ad3e8206e7fc69/flow-components-parent/demo-flow-components/src/test/java/com/vaadin/flow/demo/ComponentDemoTest.java#L74)):*
> ```Java
>     }
> 
>     public void nativeClick(WebElement element) {
> ```

Would you rather move it to `TestBenchHelpers` where all those kind of methods are?
It would be easier to refactor them in a single class.

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 546 at r2](https://reviewable.io:443/reviews/vaadin/flow/2674#-KwJibjcawAYa9IqwjbH-r2-546:-KwJyICQKjvgKwtPOSUQ:b-wybwl3) ([raw file](https://github.com/vaadin/flow/blob/4fd162c939330e8a2b698edc397eed9813c57ea0/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L546)):*
<details><summary><i>Previously, vaadin-bot (Vaadin Bot) wrote…</i></summary><blockquote>

MINOR Remove useless curly braces around statement [rule](https://sonar.projects.vaadin.com/coding_rules#rule_key=squid%3AS1602)
</blockquote></details>

Why not.
And also the lambda is huge, can you make it more readable by extracting it to separate method?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2674)*

**Comment by SomeoneToIgnore** [comment]
*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 546 at r2](https://reviewable.io:443/reviews/vaadin/flow/2674#-KwJibjcawAYa9IqwjbH-r2-546:-KwKFdZFcftNPR3_EEP0:b-e2g7pr) ([raw file](https://github.com/vaadin/flow/blob/4fd162c939330e8a2b698edc397eed9813c57ea0/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L546)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Why not.
And also the lambda is huge, can you make it more readable by extracting it to separate method?
</blockquote></details>

On the other hand, disregard the "huge" part :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2674)*

**Comment by SomeoneToIgnore** [comment]
*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 546 at r2](https://reviewable.io:443/reviews/vaadin/flow/2674#-KwJibjcawAYa9IqwjbH-r2-546:-KwKFlEKjqas4S1nn01t:b-5nnt3h) ([raw file](https://github.com/vaadin/flow/blob/4fd162c939330e8a2b698edc397eed9813c57ea0/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L546)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

On the other hand, disregard the "huge" part :)
</blockquote></details>

Damn, cannot edit the comments.
Sorry, I still think that the lambda is huge, now it's final :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2674)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 1 of 7 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 570 at r2](https://reviewable.io:443/reviews/vaadin/flow/2674#-KwKFtw2MqtphVAoVlJR:-KwKFtw2MqtphVAoVlJS:bs8apkz) ([raw file](https://github.com/vaadin/flow/blob/4fd162c939330e8a2b698edc397eed9813c57ea0/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L570)):*
> ```Java
> 
>         colElement.addEventListener(handlerName, event -> {
>             if (event.getEventData() != null) {
> ```

Again, would it improve the readability to have it extracted into a method?

---

*[flow-server/src/main/java/com/vaadin/ui/renderers/TemplateRenderer.java, line 119 at r2](https://reviewable.io:443/reviews/vaadin/flow/2674#-KwKG0lxYtHPEu1CzC9_:-KwKG0lxYtHPEu1CzC9a:b-cjdltu) ([raw file](https://github.com/vaadin/flow/blob/4fd162c939330e8a2b698edc397eed9813c57ea0/flow-server/src/main/java/com/vaadin/ui/renderers/TemplateRenderer.java#L119)):*
> ```Java
>         Objects.requireNonNull(property, "The property must not be null");
>         Objects.requireNonNull(provider,
>                 "The property provider must not be null");
> ```

Isn't it `value provider`?

---

*[flow-server/src/main/java/com/vaadin/ui/renderers/TemplateRenderer.java, line 138 at r2](https://reviewable.io:443/reviews/vaadin/flow/2674#-KwKGNwJK2-YN9uPHV44:-KwKGNwJK2-YN9uPHV45:b-v4r1mx) ([raw file](https://github.com/vaadin/flow/blob/4fd162c939330e8a2b698edc397eed9813c57ea0/flow-server/src/main/java/com/vaadin/ui/renderers/TemplateRenderer.java#L138)):*
> ```Java
>      * 
>      * // You can handle custom events from webcomponents as well, using the same syntax
>      * TemplateRenderer.of("<my-webcomponent on-customevent=
> ```

This line break looks a bit out of place. Can you check it out and see if formatting is weird in the rendered javadoc?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2674)*

**Comment by SomeoneToIgnore** [comment]
*[flow-server/src/main/java/com/vaadin/ui/renderers/TemplateRenderer.java, line 191 at r2](https://reviewable.io:443/reviews/vaadin/flow/2674#-KwKGSLel6Q0ceUwINRw:-KwKGSLel6Q0ceUwINRx:brt790i) ([raw file](https://github.com/vaadin/flow/blob/f230c91e1fd9f0db7ea749b13e10a5fb8ee78136/flow-server/src/main/java/com/vaadin/ui/renderers/TemplateRenderer.java#L191)):*
> ```Java
>     }
> 
>     public Map<String, SerializableConsumer<SOURCE>> getEventConsumers() {
> ```

Javadoc would be nice, I guess.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2674)*

**Comment by gilberto-torrezan** [comment]
Review status: 1 of 8 files reviewed at latest revision, 11 unresolved discussions.

---

*[flow-client/src/main/java/com/vaadin/client/ApplicationConnection.java, line 153 at r1](https://reviewable.io:443/reviews/vaadin/flow/2674#-KwJo-KbDWlW-yrrXeGK:-KwKL8CG6xszVDeT-kZD:b-borh14) ([raw file](https://github.com/vaadin/flow/blob/4bcb3cf86910579184e45c6829ad3e8206e7fc69/flow-client/src/main/java/com/vaadin/client/ApplicationConnection.java#L153)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Tabs again. Is it configurable in Eclipse?
</blockquote></details>

My Eclipse is all messed up after I worked for vcom for a day (they use tabs there). For some reason I have to manually format some stuff now. Very annoying.

---

*[flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/views/GridView.java, line 96 at r1](https://reviewable.io:443/reviews/vaadin/flow/2674#-KwJrNv3cVU-4CKzVFJy:-KwKLKioueCzg3nAi0j_:b-cyn1jz) ([raw file](https://github.com/vaadin/flow/blob/4bcb3cf86910579184e45c6829ad3e8206e7fc69/flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/views/GridView.java#L96)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Would it be easier just to return an id? It's not like you make any difference if you add a constant to it, see `Integer#hasCode`

I also find it very dangerous to have non-final field being used in equals and hashCode computation, but, I guess, it does not really matter for the example.
</blockquote></details>

This was created automatically by Eclipse. I guess the `hashCode` generated by it is not that good...
Fixed by hand.

---

*[flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/views/GridView.java, line 109 at r1](https://reviewable.io:443/reviews/vaadin/flow/2674#-KwJibjcawAYa9IqwjbE-r1-109:-KwKLTn60l775urFkCrt:b-yk7xmp) ([raw file](https://github.com/vaadin/flow/blob/4bcb3cf86910579184e45c6829ad3e8206e7fc69/flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/views/GridView.java#L109)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Why not.
</blockquote></details>

Auto generated as well =/ 
Fixed by hand.

---

*[flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/views/GridView.java, line 193 at r1](https://reviewable.io:443/reviews/vaadin/flow/2674#-KwJuhYv3izI2H_hC2DB:-KwKOOhGlQ8GdpOBEmzi:b1yqn00) ([raw file](https://github.com/vaadin/flow/blob/4bcb3cf86910579184e45c6829ad3e8206e7fc69/flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/views/GridView.java#L193)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Can you just use `ThreadLocalRandom` here? 
You don't have to duplicate it and drag it around and you will be able to use `createPerson` as a method reference again.
</blockquote></details>

As far as I understood, it's not possible to set the seed for the `ThreadLocalRandom`. That's bad because introduces variations to our tests.

---

*[flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/views/GridView.java, line 195 at r1](https://reviewable.io:443/reviews/vaadin/flow/2674#-KwJtYHWyQfhmVERmfmN:-KwKZc5qkZeyXQA_-Fsp:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/4bcb3cf86910579184e45c6829ad3e8206e7fc69/flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/views/GridView.java#L195)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

In case you'd like to remove some extra verbosity, `return` can be removed.
</blockquote></details>

Done.

---

*[flow-components-parent/demo-flow-components/src/test/java/com/vaadin/flow/demo/ComponentDemoTest.java, line 74 at r1](https://reviewable.io:443/reviews/vaadin/flow/2674#-KwJxTvKc6l0DS0bEEOr:-KwK_YiLoYnyJOyBj5cz:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/4bcb3cf86910579184e45c6829ad3e8206e7fc69/flow-components-parent/demo-flow-components/src/test/java/com/vaadin/flow/demo/ComponentDemoTest.java#L74)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Would you rather move it to `TestBenchHelpers` where all those kind of methods are?
It would be easier to refactor them in a single class.
</blockquote></details>

Done.

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 546 at r2](https://reviewable.io:443/reviews/vaadin/flow/2674#-KwJibjcawAYa9IqwjbH-r2-546:-KwKaPjllsTA47QexuDJ:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/f230c91e1fd9f0db7ea749b13e10a5fb8ee78136/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L546)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Damn, cannot edit the comments.
Sorry, I still think that the lambda is huge, now it's final :)
</blockquote></details>

Done.

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 570 at r2](https://reviewable.io:443/reviews/vaadin/flow/2674#-KwKFtw2MqtphVAoVlJR:-KwKbCxRQX9KX1UzHGIV:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/f230c91e1fd9f0db7ea749b13e10a5fb8ee78136/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L570)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Again, would it improve the readability to have it extracted into a method?
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/ui/renderers/TemplateRenderer.java, line 119 at r2](https://reviewable.io:443/reviews/vaadin/flow/2674#-KwKG0lxYtHPEu1CzC9_:-KwKbMurvtKpc2CZrole:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/f230c91e1fd9f0db7ea749b13e10a5fb8ee78136/flow-server/src/main/java/com/vaadin/ui/renderers/TemplateRenderer.java#L119)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Isn't it `value provider`?
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/ui/renderers/TemplateRenderer.java, line 138 at r2](https://reviewable.io:443/reviews/vaadin/flow/2674#-KwKGNwJK2-YN9uPHV44:-KwKM1n3otkQnBGTGjDi:b6dp0t2) ([raw file](https://github.com/vaadin/flow/blob/f230c91e1fd9f0db7ea749b13e10a5fb8ee78136/flow-server/src/main/java/com/vaadin/ui/renderers/TemplateRenderer.java#L138)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

This line break looks a bit out of place. Can you check it out and see if formatting is weird in the rendered javadoc?
</blockquote></details>

To make it not break I have to ignore the Flow formatting on Eclipse. Or change the text.

---

*[flow-server/src/main/java/com/vaadin/ui/renderers/TemplateRenderer.java, line 191 at r2](https://reviewable.io:443/reviews/vaadin/flow/2674#-KwKGSLel6Q0ceUwINRw:-KwKMBw8Q-GkGsEW8Bh0:b-qbo9zf) ([raw file](https://github.com/vaadin/flow/blob/f230c91e1fd9f0db7ea749b13e10a5fb8ee78136/flow-server/src/main/java/com/vaadin/ui/renderers/TemplateRenderer.java#L191)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Javadoc would be nice, I guess.
</blockquote></details>

Ooops. I wonder why Sonar didn't get this one.
Renamed to `getEventHandlers` for consistency with the `withEventHandler` method.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2674)*

**Comment by SomeoneToIgnore** [comment]
*[flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/views/GridView.java, line 193 at r1](https://reviewable.io:443/reviews/vaadin/flow/2674#-KwJuhYv3izI2H_hC2DB:-KwKg6L4HUlygWMc8E61:b9255bw) ([raw file](https://github.com/vaadin/flow/blob/4bcb3cf86910579184e45c6829ad3e8206e7fc69/flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/views/GridView.java#L193)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

As far as I understood, it's not possible to set the seed for the `ThreadLocalRandom`. That's bad because introduces variations to our tests.
</blockquote></details>

Well, it's not really random then, isn't it? You're using it wrong :)
But whatever.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2674)*

**Comment by SomeoneToIgnore** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/ui/renderers/TemplateRenderer.java, line 138 at r2](https://reviewable.io:443/reviews/vaadin/flow/2674#-KwKGNwJK2-YN9uPHV44:-KwKgV4YlZq-aD407hjh:b2nhll9) ([raw file](https://github.com/vaadin/flow/blob/f230c91e1fd9f0db7ea749b13e10a5fb8ee78136/flow-server/src/main/java/com/vaadin/ui/renderers/TemplateRenderer.java#L138)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

To make it not break I have to ignore the Flow formatting on Eclipse. Or change the text.
</blockquote></details>

Ok.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2674#-:-KwKgai-BCvJWI4lTXTp:bnfp4nl)*

**Comment by SomeoneToIgnore** [comment]
*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 600 at r4](https://reviewable.io:443/reviews/vaadin/flow/2674#-KwKj-ULP1jajNdomITP:-KwKj-ULP1jajNdomITQ:b-wuwdao) ([raw file](https://github.com/vaadin/flow/blob/5a45513fe6dc2703b369b89beb169ff8fd06ab18/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L600)):*
> ```Java
>                     () -> String.format(
>                             "Received an event for the handler '%s' without any data. Ignoring event.",
>                             handlerName, handlerName));
> ```

2 params now?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2674)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2674)*

**Comment by gilberto-torrezan** [comment]
Review status: 7 of 8 files reviewed at latest revision, 5 unresolved discussions.

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 600 at r4](https://reviewable.io:443/reviews/vaadin/flow/2674#-KwKj-ULP1jajNdomITP:-KwKjq7AKQ1n_qIzBKuW:b-l9btd1) ([raw file](https://github.com/vaadin/flow/blob/5a45513fe6dc2703b369b89beb169ff8fd06ab18/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L600)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

2 params now?
</blockquote></details>

That's called redundancy. Or mistake. You choose.
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2674)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2674)*

**Pull request merged**
