### PR TITLE
Add manual navigation listeners.

### PR DESCRIPTION
**Pull request by caalador**
Now the user can register navigation state change
listeners manually and always get an event even if we
are not connected to the actual navigation chain.

This PR completes #2754

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3679)

### CODE REVIEW

**Comment by Legioth** [comment]
Review status: 0 of 16 files reviewed at latest revision, 8 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3679#-L79OzgcUapNfdpGEJtf:-L79OzgdNdQRXtpathWd:b-dr2hi0) (no related file):*
What's the point of creating a separate listener instance for each UI instance? Why not have one listener instance that is used for all UIs (i.e. registered with the Router or VaadinService instance)?

In that way, registration would also be much simpler since there wouldn't be necessary to register a separate UI listener. There are still also other use cases for a listener that is triggered every time a new UI instance is created, but that can be done separately.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3679)*

**Comment by caalador** [comment]
Review status: 0 of 16 files reviewed at latest revision, 8 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3679#-L79OzgcUapNfdpGEJtf:-L79SrQvd2f7Rh0Kug8T:bn1eprm) (no related file):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

What's the point of creating a separate listener instance for each UI instance? Why not have one listener instance that is used for all UIs (i.e. registered with the Router or VaadinService instance)?

In that way, registration would also be much simpler since there wouldn't be necessary to register a separate UI listener. There are still also other use cases for a listener that is triggered every time a new UI instance is created, but that can be done separately.
</blockquote></details>

Registering with router/service sounds like a different use case all together. Also sounds like a way to easily have a who belongs where what is happening listener problem.

Also the ticket specifies ` for a specific UI.` 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3679)*

**Comment by Legioth** [comment]
Review status: 0 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3679#-L79OzgcUapNfdpGEJtf:-L7TsCKmmFDFSoIvHWu2:b-jsyija) (no related file):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Registering with router/service sounds like a different use case all together. Also sounds like a way to easily have a who belongs where what is happening listener problem.

Also the ticket specifies ` for a specific UI.` 
</blockquote></details>

I guess the problem is that it's not really clear what actual problem this feature is intended to solve.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3679)*

**Comment by gilberto-torrezan** [comment]
Review status: 0 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/flow/3679#-L79OzgcUapNfdpGEJtf:-L7UIfIB084PKfohjMq4:b-mdkzhh) (no related file):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

I guess the problem is that it's not really clear what actual problem this feature is intended to solve.
</blockquote></details>

(I'm confused if I should review this or not)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3679)*

**Comment by berndhopp** [comment]
*[a discussion](https://beta.reviewable.io/reviews/vaadin/flow/3679#-L79OzgcUapNfdpGEJtf:-L7Yl7WSDDvvddR8QtZ5:bbn04vq) (no related file):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

(I'm confused if I should review this or not)
</blockquote></details>

since I was the author of the original PR that this one evolved from, I feel authorized to answer that question. 
The problem to be solved is to bring back something similar to a ViewChangeListener in V8. ViewChangeListeners by nature lived in a 'UI-Scope' since the navigator was bound to a specific UI. If we now change that scope to 'singleton', a single listener for 'all' navigations would need to be stateless, since it deals with often times sensitive session-scoped information like login, credentials etc.. And if people port over their ViewChangeListeners from V8, it would make things a lot harder for them if they would be forced to use a singleton now.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3679)*

**Comment by Legioth** [comment]
*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3679#-L79OzgcUapNfdpGEJtf:-L7Yp7uwWdMmLnBGHnOx:b-k009ts) (no related file):*
<details><summary><i>Previously, berndhopp (bernd hopp) wrote…</i></summary><blockquote>

since I was the author of the original PR that this one evolved from, I feel authorized to answer that question. 
The problem to be solved is to bring back something similar to a ViewChangeListener in V8. ViewChangeListeners by nature lived in a 'UI-Scope' since the navigator was bound to a specific UI. If we now change that scope to 'singleton', a single listener for 'all' navigations would need to be stateless, since it deals with often times sensitive session-scoped information like login, credentials etc.. And if people port over their ViewChangeListeners from V8, it would make things a lot harder for them if they would be forced to use a singleton now.
</blockquote></details>

Let's continue the discussion in the ticket: https://github.com/vaadin/flow/issues/2754. I also copied your response there.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3679)*

**Comment by Legioth** [comment]
*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3679#-L79OzgcUapNfdpGEJtf:-L7ZbNyl55ggKEYvecrQ:b4sbpgd) (no related file):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

Let's continue the discussion in the ticket: https://github.com/vaadin/flow/issues/2754. I also copied your response there.
</blockquote></details>

Unblocked on my behalf. The conclusion in #2754 is that supporting both ways might be a considerable option. If going that route, then this patch can go in assuming there are no other issue with it. Support for global registration can then be added separately at any point.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3679)*

**Comment by berndhopp** [comment]
*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3679#-L79OzgcUapNfdpGEJtf:-L7d39ARZxWd1AP_7haS:b1mnd4y) (no related file):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

Unblocked on my behalf. The conclusion in #2754 is that supporting both ways might be a considerable option. If going that route, then this patch can go in assuming there are no other issue with it. Support for global registration can then be added separately at any point.
</blockquote></details>

I think you need to give a LGTM then, to unblock it for reviewable

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3679)*

**Comment by berndhopp** [comment]
*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3679#-L79OzgcUapNfdpGEJtf:-L7e5YPu7TRoFEu8WaVM:biz7emr) (no related file):*
<details><summary><i>Previously, berndhopp (bernd hopp) wrote…</i></summary><blockquote>

I think you need to give a LGTM then, to unblock it for reviewable
</blockquote></details>

@legioth 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3679)*

**Comment by caalador** [comment]
Leif is not a valid reviewer as such. So this needs to be reviewed by someone in the team.

**Comment by Legioth** [comment]
I only get to complain, but not take responsibility for anything :)

---

Review status: 0 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3679#-L79OzgcUapNfdpGEJtf:-L7e6hb8nFoANs6UTY6o:bepspyk) (no related file):*
<details><summary><i>Previously, berndhopp (bernd hopp) wrote…</i></summary><blockquote>

@legioth 
</blockquote></details>

I think I'm the only person in this particular discussion thread that isn't blocking it since everyone else has `Discussing: OK to resolve only if acknowledged or OK'd last comment. (Currently: not OK.)`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3679#-:-L7e7935DAetHTC0MEW0:blqm4up)*

**Comment by denis-anisimov** [comment]
:lgtm:

---

Reviewed 12 of 16 files at r1, 1 of 3 files at r2, 1 of 1 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/router/internal/NavigationStateRenderer.java, line 131 at r4](https://reviewable.io:443/reviews/vaadin/flow/3679#-L86jawXMB9D7MLjPdEY:-L86jawYyx8OxOLwGhPR:b-nn09fb) ([raw file](https://github.com/vaadin/flow/blob/72f47208e466df1f6091ef86c71df8943803facd/flow-server/src/main/java/com/vaadin/flow/router/internal/NavigationStateRenderer.java#L131)):*
> leaveHandlers = postponed.getLeaveObservers();
>             if (!leaveHandlers.isEmpty()) {
>                 postponed = null;
>             }

This part logic is new.
Does it relate to the listeners manual registration ?
Or it fixes something additionally?

Ah, alright. The logic is moved from the `executeBeforeLeaveNavigation`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3679#-:-L86l-PNRVTNmSxKJZ3W:bnfp4nl)*

**Pull request merged**
