### PR TITLE
fix: Allow all Java features when parsing endpoint code

### PR DESCRIPTION
**Pull request by Artur-**
Fixes https://github.com/vaadin/hilla/issues/216

### CODE REVIEW

**Comment by Artur-** [comment]
With the project in the issue, this prints
```
2022-02-23 15:33:06.828 DEBUG 18106 --- [onPool-worker-1] c.v.f.generator.OpenAPIObjectGenerator   : Unable to parse Java file com/example/application/data/endpoint/BetaEndpoint.java: Parsing failed:
(line 16,col 10) Switch expressions are not supported.

2022-02-23 15:33:06.830 DEBUG 18106 --- [onPool-worker-1] c.v.f.generator.OpenAPIObjectGenerator   : Unable to parse Java file com/example/application/data/endpoint/AlphaEndpoint.java: Parsing failed:
(line 16,col 7) Use of patterns with instanceof is not supported.

```

**Comment by platosha** [comment]
Thanks for the PR.

Would be great to have some tests here to prevent regressions in future. Do you know if this is possible to test @Artur- ?

**Comment by Artur-** [comment]
Adding tests using features newer than Java 11 would require compiling with something newer than Java 11. That wouldn't work with the current setup as far as I know

**Comment by Artur-** [comment]
Added a test module, let's see if the build can handle it..

**Review by platosha — APPROVED** [review]

**Pull request merged**
