### PR TITLE
Implement Grid column grouping

### PR DESCRIPTION
**Pull request by ahie**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/2828)

### CODE REVIEW

**Comment by torok-peter** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 967 at r1](https://reviewable.io:443/reviews/vaadin/flow/2828#-KxsDU3F1ta9BmA6PeLa:-KxsDU3G0o6Co58Z-Bo6:b-eyq82m) ([raw file](https://github.com/vaadin/flow/blob/c8d8b696c9630ec9e79ea858eb86d23187cc8bb3/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L967)):*
> ```Java
> 
>         parentColumns.add(insertIndex, columnGroup);
>         parentColumns.removeAll(columnsToMerge);
> ```

The changes in the child elements vs parentColumns are not done consistently; that would improve readability and reduce the chance of errors.

Moreover, is there any possibility of an exception getting thrown during this change? If so, it would leave the grid and/or the UI in an inconsistent and probably broken state. This should practically be an atomic transaction.

I guess  this method is not expected to be thread-safe; it may be good to make this clear in the Javadoc though.

---

*[flow-components-parent/flow-components/src/test/java/com/vaadin/ui/grid/GridColumnGroupingTest.java, line 69 at r1](https://reviewable.io:443/reviews/vaadin/flow/2828#-KxsF3T4AnTgOn-Xx5IA:-KxsF3T4AnTgOn-Xx5IB:b-e1vdpf) ([raw file](https://github.com/vaadin/flow/blob/c8d8b696c9630ec9e79ea858eb86d23187cc8bb3/flow-components-parent/flow-components/src/test/java/com/vaadin/ui/grid/GridColumnGroupingTest.java#L69)):*
> ```Java
>         grid.mergeColumns("", firstColumn, thirdColumn);
>     }
> }
> ```

How about testing two or more merges in a row, like first merging columns A and B, then merging the resulting column group with C?

---

*[flow-components-parent/flow-components/src/test/java/com/vaadin/ui/grid/GridColumnGroupingTest.java, line 69 at r1](https://reviewable.io:443/reviews/vaadin/flow/2828#-KxsFMbzcg9F6Scrq6QB:-KxsFMbzcg9F6Scrq6QC:b-l3qjpu) ([raw file](https://github.com/vaadin/flow/blob/c8d8b696c9630ec9e79ea858eb86d23187cc8bb3/flow-components-parent/flow-components/src/test/java/com/vaadin/ui/grid/GridColumnGroupingTest.java#L69)):*
> ```Java
>         grid.mergeColumns("", firstColumn, thirdColumn);
>     }
> }
> ```

Is there a way to split merged columns? If so, test that too

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2828)*

**Comment by ahie** [comment]
Review status: 5 of 7 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 967 at r1](https://reviewable.io:443/reviews/vaadin/flow/2828#-KxsDU3F1ta9BmA6PeLa:-KxwEs5G3TycC1Mxe94D:bu73fhn) ([raw file](https://github.com/vaadin/flow/blob/c8d8b696c9630ec9e79ea858eb86d23187cc8bb3/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L967)):*
> The changes in the child elements vs parentColumns are not done consistently; that would improve readability and reduce the chance of errors.

Attempted to make the code clearer.

> I guess this method is not expected to be thread-safe; it may be good to make this clear in the Javadoc though.

No UI component code is expected to be thread safe. If you are accessing a component from a background thread you should use for example `UI.access(Runnable)`.

---

*[flow-components-parent/flow-components/src/test/java/com/vaadin/ui/grid/GridColumnGroupingTest.java, line 69 at r1](https://reviewable.io:443/reviews/vaadin/flow/2828#-KxsFMbzcg9F6Scrq6QB:-Kxviq6S_2sj5iQ_RPWj:b-ogrd1n) ([raw file](https://github.com/vaadin/flow/blob/c8d8b696c9630ec9e79ea858eb86d23187cc8bb3/flow-components-parent/flow-components/src/test/java/com/vaadin/ui/grid/GridColumnGroupingTest.java#L69)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

Is there a way to split merged columns? If so, test that too
</blockquote></details>

There's no way to split merged columns.

---

*[flow-components-parent/flow-components/src/test/java/com/vaadin/ui/grid/GridColumnGroupingTest.java, line 69 at r1](https://reviewable.io:443/reviews/vaadin/flow/2828#-KxsF3T4AnTgOn-Xx5IA:-KxvixFQVQ6caIGBM6g4:b33t8rl) ([raw file](https://github.com/vaadin/flow/blob/c8d8b696c9630ec9e79ea858eb86d23187cc8bb3/flow-components-parent/flow-components/src/test/java/com/vaadin/ui/grid/GridColumnGroupingTest.java#L69)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

How about testing two or more merges in a row, like first merging columns A and B, then merging the resulting column group with C?
</blockquote></details>

That's already tested in `merged_column_order` and there is also an integration test for it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2828)*

**Comment by torok-peter** [comment]
Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2828)*

**Comment by gilberto-torrezan** [comment]
Reviewed 5 of 6 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2828)*

**Comment by gilberto-torrezan** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 950 at r3](https://reviewable.io:443/reviews/vaadin/flow/2828#-KxwoOxp6w55tHygnd9E:-KxwoOxp6w55tHygnd9F:b-amtn59) ([raw file](https://github.com/vaadin/flow/blob/bf1273ecb02f7c8092cf0db3381a20c7ee879d48/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L950)):*
> ```Java
>         }
>         if (columnsToMerge.stream()
>                 .filter(column -> !parentColumns.contains(column)).findAny()
> ```

You can use `stream().anyMatch()` instead of `stream().filter().findAny().isPresent()`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2828)*

**Comment by ahie** [comment]
Review status: 6 of 7 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 950 at r3](https://reviewable.io:443/reviews/vaadin/flow/2828#-KxwoOxp6w55tHygnd9E:-Ky-j8qUPxMVSl8sUJ_M:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/bf1273ecb02f7c8092cf0db3381a20c7ee879d48/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L950)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

You can use `stream().anyMatch()` instead of `stream().filter().findAny().isPresent()`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2828)*

**Comment by gilberto-torrezan** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2828)*

**Pull request merged**
