### PR TITLE
Add LocaleChangeObserver support.

### PR DESCRIPTION
**Pull request by caalador**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/2886)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/router/NavigationStateRenderer.java, line 146 at r1](https://reviewable.io:443/reviews/vaadin/flow/2886#-KyZl0bgeR5dgIy-99n_:-KyZl0bgeR5dgIy-99na:b-29ryv) ([raw file](https://github.com/vaadin/flow/blob/668730c2a904122d2af69c76cfc43fe2cd03e413/flow-server/src/main/java/com/vaadin/router/NavigationStateRenderer.java#L146)):*
> EventUtil.informLocaleChangeObservers(ui, chain);

Each time on navigation the locale change event is fired ?

---

*[flow-server/src/main/java/com/vaadin/ui/UI.java, line 609 at r1](https://reviewable.io:443/reviews/vaadin/flow/2886#-KyZlCjLU4nnqFg_bLeE:-KyZlCjLU4nnqFg_bLeF:b-b8qprp) ([raw file](https://github.com/vaadin/flow/blob/668730c2a904122d2af69c76cfc43fe2cd03e413/flow-server/src/main/java/com/vaadin/ui/UI.java#L609)):*
> EventUtil.informLocaleChangeObservers(this);

Should it fire an event only of there is a real change ?

---

*[flow-server/src/main/java/com/vaadin/ui/i18n/LocaleChangeEvent.java, line 25 at r1](https://reviewable.io:443/reviews/vaadin/flow/2886#-KyZlKegW6LMSIHlEwXy:-KyZlKegW6LMSIHlEwXz:b-cptx6d) ([raw file](https://github.com/vaadin/flow/blob/668730c2a904122d2af69c76cfc43fe2cd03e413/flow-server/src/main/java/com/vaadin/ui/i18n/LocaleChangeEvent.java#L25)):*
> private Locale locale;

`final`

---

*[flow-server/src/main/java/com/vaadin/ui/i18n/LocaleChangeObserver.java, line 28 at r1](https://reviewable.io:443/reviews/vaadin/flow/2886#-KyZlPXG9wxvNh2xI-LL:-KyZlPXG9wxvNh2xI-LM:bx9821k) ([raw file](https://github.com/vaadin/flow/blob/668730c2a904122d2af69c76cfc43fe2cd03e413/flow-server/src/main/java/com/vaadin/ui/i18n/LocaleChangeObserver.java#L28)):*
> void localeChange(LocaleChangeEvent event);

SQ will complain about javadoc absence

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2886)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2886#-KyZnXrrr-A27IDDTDKe:-KyZnXrrr-A27IDDTDKf:b-s3q7dz) (no related file):*
Request for enhancement: it's seen from the demo that VaadinService.getCurrent()
 ( getUI().getSession().setService()).getInstantiator().getProvider() is used in many places.

Suggestion:
add a convenient method to the `Component` class.

- either Component::getI18NProvider()
- or Component::getMessage(String key, Object... params)
- or both.

May be a separate ticket and PR.

Up to you to decide.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2886)*

**Comment by torok-peter** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[flow-documentation/miscellaneous/tutorial-i18n-localization.asciidoc, line 204 at r1](https://reviewable.io:443/reviews/vaadin/flow/2886#-KyZgKBgB5ND0nSXOSb1:-KyZgKBgB5ND0nSXOSb2:b-b1l8ew) ([raw file](https://github.com/vaadin/flow/blob/668730c2a904122d2af69c76cfc43fe2cd03e413/flow-documentation/miscellaneous/tutorial-i18n-localization.asciidoc#L204)):*
> ```AsciiDoc
>     public void localeChange(LocaleChangeEvent event) {
>         setText(getProvider().getTranslation("my.translation",
>                 "My parameter!"));
> ```

Would it be more realistic as an example to set different text depending on the actual locale?

---

*[flow-documentation/src/main/java/com/vaadin/flow/tutorial/misc/TranslationSources.java, line 32 at r1](https://reviewable.io:443/reviews/vaadin/flow/2886#-KyZgl8OVqEjUdzIdPdP:-KyZgl8OVqEjUdzIdPdQ:b-2guby3) ([raw file](https://github.com/vaadin/flow/blob/668730c2a904122d2af69c76cfc43fe2cd03e413/flow-documentation/src/main/java/com/vaadin/flow/tutorial/misc/TranslationSources.java#L32)):*
> ```Java
>         public void localeChange(LocaleChangeEvent event) {
>             setText(getProvider().getTranslation("my.translation",
>                     "My parameter!"));
> ```

same here

---

*[flow-server/src/main/java/com/vaadin/router/event/EventUtil.java, line 176 at r1](https://reviewable.io:443/reviews/vaadin/flow/2886#-KyZpd_aYGK2DG0yXk4w:-KyZpd_aYGK2DG0yXk4x:bea9pt3) ([raw file](https://github.com/vaadin/flow/blob/668730c2a904122d2af69c76cfc43fe2cd03e413/flow-server/src/main/java/com/vaadin/router/event/EventUtil.java#L176)):*
> ```Java
>                 ui.getLocale());
>         collectLocaleChangeObservers(components)
>                 .forEach(observer -> observer.localeChange(localeChangeEvent));
> ```

Should it check whether the locale actually changed, before notifying anyone?

---

*[flow-server/src/test/java/com/vaadin/flow/router/event/EventUtilTest.java, line 57 at r1](https://reviewable.io:443/reviews/vaadin/flow/2886#-KyZpzrBKr4PXZ7oJTFi:-KyZpzrBKr4PXZ7oJTFj:b-fqe89o) ([raw file](https://github.com/vaadin/flow/blob/668730c2a904122d2af69c76cfc43fe2cd03e413/flow-server/src/test/java/com/vaadin/flow/router/event/EventUtilTest.java#L57)):*
> ```Java
> 
>     @Tag("nested")
>     public static class Listener extends Component
> ```

Observer?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2886)*

**Comment by caalador** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2886#-KyZnXrrr-A27IDDTDKe:-KyZtj3HlTamusUaOSVV:bnjwgcw) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Request for enhancement: it's seen from the demo that VaadinService.getCurrent()
 ( getUI().getSession().setService()).getInstantiator().getProvider() is used in many places.

Suggestion:
add a convenient method to the `Component` class.

- either Component::getI18NProvider()
- or Component::getMessage(String key, Object... params)
- or both.

May be a separate ticket and PR.

Up to you to decide.
</blockquote></details>

Added the getProvider shorthand.

---

*[flow-documentation/miscellaneous/tutorial-i18n-localization.asciidoc, line 204 at r1](https://reviewable.io:443/reviews/vaadin/flow/2886#-KyZgKBgB5ND0nSXOSb1:-KyZtIKc8neOX-efrlcg:b-qz67xl) ([raw file](https://github.com/vaadin/flow/blob/668730c2a904122d2af69c76cfc43fe2cd03e413/flow-documentation/miscellaneous/tutorial-i18n-localization.asciidoc#L204)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

Would it be more realistic as an example to set different text depending on the actual locale?
</blockquote></details>

Changed the parameter to be a number.

---

*[flow-documentation/src/main/java/com/vaadin/flow/tutorial/misc/TranslationSources.java, line 32 at r1](https://reviewable.io:443/reviews/vaadin/flow/2886#-KyZgl8OVqEjUdzIdPdP:-KyZtLSI0A1pNDlNbzEA:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/668730c2a904122d2af69c76cfc43fe2cd03e413/flow-documentation/src/main/java/com/vaadin/flow/tutorial/misc/TranslationSources.java#L32)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/router/NavigationStateRenderer.java, line 146 at r1](https://reviewable.io:443/reviews/vaadin/flow/2886#-KyZl0bgeR5dgIy-99n_:-KyZouC2KYw4kO67U3Mj:b3y04pk) ([raw file](https://github.com/vaadin/flow/blob/668730c2a904122d2af69c76cfc43fe2cd03e413/flow-server/src/main/java/com/vaadin/router/NavigationStateRenderer.java#L146)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> EventUtil.informLocaleChangeObservers(ui, chain);

Each time on navigation the locale change event is fired ?
</blockquote></details>

From the ticket we have:
Clarification: The observer method should also be triggered when the component is attached, regardless of any changes to the UI locale.

---

*[flow-server/src/main/java/com/vaadin/router/event/EventUtil.java, line 176 at r1](https://reviewable.io:443/reviews/vaadin/flow/2886#-KyZpd_aYGK2DG0yXk4w:-KyZt5f8zu5ZBg0em_Qm:bv402ys) ([raw file](https://github.com/vaadin/flow/blob/668730c2a904122d2af69c76cfc43fe2cd03e413/flow-server/src/main/java/com/vaadin/router/event/EventUtil.java#L176)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

Should it check whether the locale actually changed, before notifying anyone?
</blockquote></details>

UI should, the event util doesn't know of any previous states.

---

*[flow-server/src/main/java/com/vaadin/ui/UI.java, line 609 at r1](https://reviewable.io:443/reviews/vaadin/flow/2886#-KyZlCjLU4nnqFg_bLeE:-KyZt2NxznWI46tHfbFU:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/668730c2a904122d2af69c76cfc43fe2cd03e413/flow-server/src/main/java/com/vaadin/ui/UI.java#L609)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> EventUtil.informLocaleChangeObservers(this);

Should it fire an event only of there is a real change ?
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/ui/i18n/LocaleChangeEvent.java, line 25 at r1](https://reviewable.io:443/reviews/vaadin/flow/2886#-KyZlKegW6LMSIHlEwXy:-KyZsDSBmyFBnBZOcj_K:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/668730c2a904122d2af69c76cfc43fe2cd03e413/flow-server/src/main/java/com/vaadin/ui/i18n/LocaleChangeEvent.java#L25)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> private Locale locale;

`final`
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/ui/i18n/LocaleChangeObserver.java, line 28 at r1](https://reviewable.io:443/reviews/vaadin/flow/2886#-KyZlPXG9wxvNh2xI-LL:-KyZsRYumZl-lywJzI_m:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/668730c2a904122d2af69c76cfc43fe2cd03e413/flow-server/src/main/java/com/vaadin/ui/i18n/LocaleChangeObserver.java#L28)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> void localeChange(LocaleChangeEvent event);

SQ will complain about javadoc absence
</blockquote></details>

Done.

---

*[flow-server/src/test/java/com/vaadin/flow/router/event/EventUtilTest.java, line 57 at r1](https://reviewable.io:443/reviews/vaadin/flow/2886#-KyZpzrBKr4PXZ7oJTFi:-KyZsZTKYlO_upo9mDcR:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/668730c2a904122d2af69c76cfc43fe2cd03e413/flow-server/src/test/java/com/vaadin/flow/router/event/EventUtilTest.java#L57)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

Observer?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2886)*

**Comment by denis-anisimov** [comment]
Reviewed 8 of 8 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[flow-server/src/main/java/com/vaadin/router/NavigationStateRenderer.java, line 146 at r1](https://reviewable.io:443/reviews/vaadin/flow/2886#-KyZl0bgeR5dgIy-99n_:-Ky_4IsxUJeT3Zad4nxY:b6r7kux) ([raw file](https://github.com/vaadin/flow/blob/668730c2a904122d2af69c76cfc43fe2cd03e413/flow-server/src/main/java/com/vaadin/router/NavigationStateRenderer.java#L146)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

From the ticket we have:
Clarification: The observer method should also be triggered when the component is attached, regardless of any changes to the UI locale.

</blockquote></details>

OK.

"The component is attached."

But the component may be attached because of  different reasons. It doesn't have to be a navigation event.

Or this attachment in the ticket is only about navigation ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2886)*

**Comment by torok-peter** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2886#-:-Ky_6FReVOF__WdPNO4I:bnfp4nl)*

**Comment by caalador** [comment]
Review status: 7 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-server/src/main/java/com/vaadin/router/NavigationStateRenderer.java, line 146 at r1](https://reviewable.io:443/reviews/vaadin/flow/2886#-KyZl0bgeR5dgIy-99n_:-Ky_AJWmowUdJSuLLpSS:b-4ty9q3) ([raw file](https://github.com/vaadin/flow/blob/668730c2a904122d2af69c76cfc43fe2cd03e413/flow-server/src/main/java/com/vaadin/router/NavigationStateRenderer.java#L146)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

OK.

"The component is attached."

But the component may be attached because of  different reasons. It doesn't have to be a navigation event.

Or this attachment in the ticket is only about navigation ?
</blockquote></details>

You are totally correct. Fixed it to be fired for component.attach

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2886)*

**Comment by denis-anisimov** [comment]
Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[flow-server/src/main/java/com/vaadin/ui/ComponentUtil.java, line 215 at r3](https://reviewable.io:443/reviews/vaadin/flow/2886#-Ky_EEFITuJm-SFIpkeC:-Ky_EEFITuJm-SFIpkeD:bw50fjh) ([raw file](https://github.com/vaadin/flow/blob/8a241b195967c5bfe1036b6cbb074361697dc4c9/flow-server/src/main/java/com/vaadin/ui/ComponentUtil.java#L215)):*
> initialAttach

Are you sure about initial attach only ?

There is a possibility of :  
- component is attached
- component is removed from the parent
- locale is changed
- component is added back

In this case the component won't get any notification about the locale change .
And it will be attached back with the wrong locale text.

---

*[flow-server/src/test/java/com/vaadin/ui/LocationObserverTest.java, line 94 at r3](https://reviewable.io:443/reviews/vaadin/flow/2886#-Ky_F-iUUx6qYUTnUhmb:-Ky_F-iUUx6qYUTnUhmc:by5jk6a) ([raw file](https://github.com/vaadin/flow/blob/8a241b195967c5bfe1036b6cbb074361697dc4c9/flow-server/src/test/java/com/vaadin/ui/LocationObserverTest.java#L94)):*
> router = new Router(new TestRouteRegistry());
>         ui = new RouterTestUI(router);

You don't need router for this test at all most likely.

---

*[flow-server/src/test/java/com/vaadin/ui/LocationObserverTest.java, line 105 at r3](https://reviewable.io:443/reviews/vaadin/flow/2886#-Ky_Ev99EmdSyuTZ2wEQ:-Ky_Ev99EmdSyuTZ2wER:b9laj9c) ([raw file](https://github.com/vaadin/flow/blob/8a241b195967c5bfe1036b6cbb074361697dc4c9/flow-server/src/test/java/com/vaadin/ui/LocationObserverTest.java#L105)):*
>  ui.navigateTo("");

Should this be replaced with pure attach action ?

Like add()/remove().

---

*[flow-server/src/test/java/com/vaadin/ui/LocationObserverTest.java, line 130 at r3](https://reviewable.io:443/reviews/vaadin/flow/2886#-Ky_EtOoT2K4TllcLiKT:-Ky_EtOoT2K4TllcLiKU:bofpf6) ([raw file](https://github.com/vaadin/flow/blob/8a241b195967c5bfe1036b6cbb074361697dc4c9/flow-server/src/test/java/com/vaadin/ui/LocationObserverTest.java#L130)):*
> ui.navigateTo("");

Should this be replaced with pure attach action ?

Like add()/remove().

---

*[flow-server/src/test/java/com/vaadin/ui/LocationObserverTest.java, line 160 at r3](https://reviewable.io:443/reviews/vaadin/flow/2886#-Ky_ElLY4vmilb8e99du:-Ky_ElLY4vmilb8e99dv:bofpf6) ([raw file](https://github.com/vaadin/flow/blob/8a241b195967c5bfe1036b6cbb074361697dc4c9/flow-server/src/test/java/com/vaadin/ui/LocationObserverTest.java#L160)):*
> ui.navigateTo("");

Should this be replaced with pure attach action ?

Like add()/remove().

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2886)*

**Comment by torok-peter** [comment]
Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2886)*

**Comment by denis-anisimov** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2886)*

**Comment by caalador** [comment]
Review status: 8 of 13 files reviewed at latest revision, 5 unresolved discussions.

---

*[flow-server/src/test/java/com/vaadin/ui/LocationObserverTest.java, line 105 at r3](https://reviewable.io:443/reviews/vaadin/flow/2886#-Ky_Ev99EmdSyuTZ2wEQ:-Kyp48KKfxmvTqKDXtXQ:bxjg0a2) ([raw file](https://github.com/vaadin/flow/blob/8a241b195967c5bfe1036b6cbb074361697dc4c9/flow-server/src/test/java/com/vaadin/ui/LocationObserverTest.java#L105)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

>  ui.navigateTo("");

Should this be replaced with pure attach action ?

Like add()/remove().
</blockquote></details>

This one tests that the event is also gotten on the attach from a navigation event.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2886)*

**Comment by denis-anisimov** [comment]
Reviewed 2 of 2 files at r5, 3 of 3 files at r6.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2886)*

**Pull request merged**
