### PR TITLE
Describe how @EventData expressions are evaluated

### PR DESCRIPTION
**Pull request by Legioth**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3746)

### CODE REVIEW

**Comment by caalador** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-server/src/main/java/com/vaadin/flow/component/EventData.java, line 24 at r1](https://reviewable.io:443/reviews/vaadin/flow/3746#-L8BYokATf2jz5dW-UY0:-L8BYokATf2jz5dW-UY1:b-79g3p0) ([raw file](https://github.com/vaadin/flow/blob/9e16e9a7fe293961b3508332763c5d448ea0625b/flow-server/src/main/java/com/vaadin/flow/component/EventData.java#L24)):*
> ```Java
> import java.lang.annotation.Target;
> 
> import com.vaadin.flow.dom.DomEventListener;
> ```

Why do you want this as an import as it's only used in the javaDoc?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3746)*

**Comment by Legioth** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-server/src/main/java/com/vaadin/flow/component/EventData.java, line 24 at r1](https://reviewable.io:443/reviews/vaadin/flow/3746#-L8BYokATf2jz5dW-UY0:-L8BcIPx2rwXeGA2OaYw:b-s9v7kh) ([raw file](https://github.com/vaadin/flow/blob/9e16e9a7fe293961b3508332763c5d448ea0625b/flow-server/src/main/java/com/vaadin/flow/component/EventData.java#L24)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Why do you want this as an import as it's only used in the javaDoc?
</blockquote></details>

Because fully qualified names are equally ugly in JavaDoc sources as in regular sources.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3746)*

**Comment by caalador** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-server/src/main/java/com/vaadin/flow/component/EventData.java, line 24 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3746#-L8BYokATf2jz5dW-UY0:-L8BcxWy2BYmalWoJ_mH:bw7yrg0) ([raw file](https://github.com/vaadin/flow/blob/9e16e9a7fe293961b3508332763c5d448ea0625b/flow-server/src/main/java/com/vaadin/flow/component/EventData.java#L24)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

Because fully qualified names are equally ugly in JavaDoc sources as in regular sources.
</blockquote></details>

Please change all applicable JavaDoc parts in the code that this change touches. e.g. value()

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3746)*

**Comment by Legioth** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-server/src/main/java/com/vaadin/flow/component/EventData.java, line 24 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3746#-L8BYokATf2jz5dW-UY0:-L8Bo4YXAtJHWCYPlgKk:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/9e16e9a7fe293961b3508332763c5d448ea0625b/flow-server/src/main/java/com/vaadin/flow/component/EventData.java#L24)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Please change all applicable JavaDoc parts in the code that this change touches. e.g. value()
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3746)*

**Comment by caalador** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3746#-:-L8Boz7O1Lt3HsPGob72:bnfp4nl)*

**Pull request merged**
