### PR TITLE
Add `setEnabled` feature to element and node.

### PR DESCRIPTION
**Pull request by caalador**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3842)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/EnabledData.java, line 26 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3842#-L9PehuwBIbJbz3j-jUB:-L9PehuwBIbJbz3j-jUC:bnhfl4z) ([raw file](https://github.com/vaadin/flow/blob/89365429cf7776d008d17ffb0ec85816e2f2d1ad/flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/EnabledData.java#L26)):*
> ```
> public class EnabledData
> ```


I'm not sure BUT it looks like we have a lot of features that are `NodeValue` subclasses.
All features are instantiated immediately once a `StateNode` is instantiated.
It means that it's not possible to init this feature lazily: every component will have this feature regardless of the need for this feature.

Does it makes sense to embed "enabled" into `ElementData` feature ?
So that `ElementData` will become `NodeMap` subclass (not `NodeValue`) and "tag", "enabled" will be just properties in it (also may be "visibility" should also be merged into the `ElementData` feature).

As a result it will increase a bit memory for `ElementData` feature but it will remove several single element features. And "enabled" will become just a property which doesn't have to be set at all (the same for "visibility").
As a result it should decrease memory consumption overall.


Alright.......
May be it't not possible because of `allowsChanges()` method.

---

*[flow-server/src/test/java/com/vaadin/flow/internal/StateNodeTest.java, line 565 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3842#-L9PgiU82QetJ8mTlS8W:-L9PgiU98TF46QJB7Wbd:b-k1ltfh) ([raw file](https://github.com/vaadin/flow/blob/89365429cf7776d008d17ffb0ec85816e2f2d1ad/flow-server/src/test/java/com/vaadin/flow/internal/StateNodeTest.java#L565)):*
> ```
> assertCollectChanges_initiallyEnabled
> ```

This test says that it's about activity/inactivity which is visibility related feature.
Not sure what the `assertCollectChanges_initiallyEnabled` method does but its name is confusing.

---

*[flow-server/src/test/java/com/vaadin/flow/server/communication/rpc/AbstractRpcInvocationHandlerTest.java, line 76 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3842#-L9PiQgd88KBKeUT1oen:-L9PiQgd88KBKeUT1oeo:b-4y94u5) ([raw file](https://github.com/vaadin/flow/blob/89365429cf7776d008d17ffb0ec85816e2f2d1ad/flow-server/src/test/java/com/vaadin/flow/server/communication/rpc/AbstractRpcInvocationHandlerTest.java#L76)):*
> ```
> createRpcInvocationData(ui, elem -> elem.setEnabled(false));
> ```

I think there should be IT test in addition to unit tests.

Visibility feature has an IT test.

The reason why I care about client side:
not all changes are sent to the client side if the element is disabled initially.

Invisible element has additional logic on the client side which handle the case when the element is not visible initially (it's not bound until it becomes visible).
Most likely `enabled` doesn't require any client side logic in that regard but I would like to be sure 
that initially disabled element becomes fully functional once it enabled.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3842)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---

*[flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/EnabledData.java, line 26 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3842#-L9PehuwBIbJbz3j-jUB:-L9PjLxk47mxKkLZt1fF:b3b8zxb) ([raw file](https://github.com/vaadin/flow/blob/89365429cf7776d008d17ffb0ec85816e2f2d1ad/flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/EnabledData.java#L26)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
> public class EnabledData
> ```


I'm not sure BUT it looks like we have a lot of features that are `NodeValue` subclasses.
All features are instantiated immediately once a `StateNode` is instantiated.
It means that it's not possible to init this feature lazily: every component will have this feature regardless of the need for this feature.

Does it makes sense to embed "enabled" into `ElementData` feature ?
So that `ElementData` will become `NodeMap` subclass (not `NodeValue`) and "tag", "enabled" will be just properties in it (also may be "visibility" should also be merged into the `ElementData` feature).

As a result it will increase a bit memory for `ElementData` feature but it will remove several single element features. And "enabled" will become just a property which doesn't have to be set at all (the same for "visibility").
As a result it should decrease memory consumption overall.


Alright.......
May be it't not possible because of `allowsChanges()` method.
</blockquote></details>

Though `allowsChanges()`  may be implemented in `ElementData` via checking both `enabled` OR `visible` properties.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3842)*

**Comment by caalador** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---

*[flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/EnabledData.java, line 26 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3842#-L9PehuwBIbJbz3j-jUB:-L9PjaSJ9nX1x57a4KsO:b-4zytsc) ([raw file](https://github.com/vaadin/flow/blob/89365429cf7776d008d17ffb0ec85816e2f2d1ad/flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/EnabledData.java#L26)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Though `allowsChanges()`  may be implemented in `ElementData` via checking both `enabled` OR `visible` properties.
</blockquote></details>

Sounds like a good idea to combine these so that if there comes up other similar "features" then adding them would be simpler. I'll see to this.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3842)*

**Comment by caalador** [comment]
Review status: 6 of 25 files reviewed at latest revision, 4 unresolved discussions.

---

*[flow-server/src/test/java/com/vaadin/flow/internal/StateNodeTest.java, line 565 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3842#-L9PgiU82QetJ8mTlS8W:-L9dPrNd0sJd29fnLLQC:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/89365429cf7776d008d17ffb0ec85816e2f2d1ad/flow-server/src/test/java/com/vaadin/flow/internal/StateNodeTest.java#L565)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
> assertCollectChanges_initiallyEnabled
> ```

This test says that it's about activity/inactivity which is visibility related feature.
Not sure what the `assertCollectChanges_initiallyEnabled` method does but its name is confusing.
</blockquote></details>

Done.

---

*[flow-server/src/test/java/com/vaadin/flow/server/communication/rpc/AbstractRpcInvocationHandlerTest.java, line 76 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3842#-L9PiQgd88KBKeUT1oen:-L9dQ09d1JpG8uu_29i7:bq0efpf) ([raw file](https://github.com/vaadin/flow/blob/89365429cf7776d008d17ffb0ec85816e2f2d1ad/flow-server/src/test/java/com/vaadin/flow/server/communication/rpc/AbstractRpcInvocationHandlerTest.java#L76)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
> createRpcInvocationData(ui, elem -> elem.setEnabled(false));
> ```

I think there should be IT test in addition to unit tests.

Visibility feature has an IT test.

The reason why I care about client side:
not all changes are sent to the client side if the element is disabled initially.

Invisible element has additional logic on the client side which handle the case when the element is not visible initially (it's not bound until it becomes visible).
Most likely `enabled` doesn't require any client side logic in that regard but I would like to be sure 
that initially disabled element becomes fully functional once it enabled.
</blockquote></details>

Working on this.

---

*[flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/EnabledData.java, line 26 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3842#-L9PehuwBIbJbz3j-jUB:-L9dPyDLDzH0VoxWvLoP:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/89365429cf7776d008d17ffb0ec85816e2f2d1ad/flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/EnabledData.java#L26)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Sounds like a good idea to combine these so that if there comes up other similar "features" then adding them would be simpler. I'll see to this.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3842)*

**Comment by denis-anisimov** [comment]
Reviewed 20 of 20 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java, line 607 at r2](https://beta.reviewable.io/reviews/vaadin/flow/3842#-L9dUo-t5bBd_IkLWQmS:-L9dUo-u92Ola0zkA6nO:b-okprom) ([raw file](https://github.com/vaadin/flow/blob/866dec76b277c18501587c4b68c44d4b73ca6b87/flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java#L607)):*
> ```
>  if (!node.hasFeature(NodeFeatures.ELEMENT_DATA)) {
> ```

I think this may be removed now.
The very first thing that is done in `bind` is `assert hasSameTag(stateNode, htmlNode)`.
This check uses the `ElementData` feature. So it always has to be when `SimpleElementBindingStrategy` is used.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3842)*

**Comment by caalador** [comment]
Review status: 19 of 27 files reviewed at latest revision, 3 unresolved discussions.

---

*[flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java, line 607 at r2](https://beta.reviewable.io/reviews/vaadin/flow/3842#-L9dUo-t5bBd_IkLWQmS:-L9dXqgWBzh__ZVtp2ou:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/866dec76b277c18501587c4b68c44d4b73ca6b87/flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java#L607)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
>  if (!node.hasFeature(NodeFeatures.ELEMENT_DATA)) {
> ```

I think this may be removed now.
The very first thing that is done in `bind` is `assert hasSameTag(stateNode, htmlNode)`.
This check uses the `ElementData` feature. So it always has to be when `SimpleElementBindingStrategy` is used.
</blockquote></details>

Done.

---

*[flow-server/src/test/java/com/vaadin/flow/server/communication/rpc/AbstractRpcInvocationHandlerTest.java, line 76 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3842#-L9PiQgd88KBKeUT1oen:-L9dZToX0NTPBoYfTrta:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/89365429cf7776d008d17ffb0ec85816e2f2d1ad/flow-server/src/test/java/com/vaadin/flow/server/communication/rpc/AbstractRpcInvocationHandlerTest.java#L76)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Working on this.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3842)*

**Comment by denis-anisimov** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3842#-:-L9e-EpXAlY8_AzPVjA0:bnfp4nl)*

**Comment by denis-anisimov** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3842#-:-L9e1gLtEH_aFwBMgF9k:bnfp4nl)*

**Pull request merged**
