### PR TITLE
chore: bump frontend dependency to 24.0.0-alpha13

### PR DESCRIPTION
**Pull request by ZheSun88**
combine #15685 #15686 #15687 #15688

### CODE REVIEW

**Review by mcollovati — CHANGES_REQUESTED** [review]
`flow-tests/test-resources/src/main/java/com/vaadin/flow/uitest/ui/dependencies/TestVersion.java` has a constant referencing `23.3.0-alpha2` that should also be updated

```java
public static final String VAADIN = "23.3.0-alpha2";
```

**Comment by mcollovati** [comment]
It seems like that for Vaadin 24 `@vaadin/text-field` must be used instead of `@vaadin/vaadin-text-field`

**Comment by ZheSun88** [comment]
oh, yes, in V24 the WCs with Vaadin- prefix have been dropped. 
Thanks @mcollovati 

it seems the github action is not running.. i will take a look

**Comment by mcollovati** [comment]
After upgrading Vaadin npm packages to `24.0.0-alpha10` the `DevBundleThemeIT.serveStylesInExpressBuildMode_assetsAreCopiedToBundle` test fails
It seems that body `font-family` of the theme is overridden

image

ping @caalador @mshabarov that perhaps can help here

```
[ERROR] Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 14.486 s <<< FAILURE! - in com.vaadin.flow.devbuild.DevBundleThemeIT
[ERROR] serveStylesInExpressBuildMode_assetsAreCopiedToBundle[ANY_Chrome_](com.vaadin.flow.devbuild.DevBundleThemeIT)  Time elapsed: 11.209 s  <<< ERROR!
org.openqa.selenium.TimeoutException: 
Expected condition failed: waiting for com.vaadin.flow.devbuild.DevBundleThemeIT$$Lambda$448/0x0000000800f0f090@228a49e5 (tried for 10 second(s) with 500 milliseconds interval)
Build info: version: '4.7.2', revision: '4d4020c3b7'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.19.0-29-generic', java.version: '17.0.5'
Driver info: com.vaadin.testbench.TestBenchDriverProxy_$$_jvstd5a_0
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 109.0.5414.74, chrome: {chromedriverVersion: 109.0.5414.74 (e7c5703604da..., userDataDir: /tmp/.com.google.Chrome.rY7zZZ}, goog:chromeOptions: {debuggerAddress: localhost:33137}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: LINUX, proxy: Proxy(), se:cdp: ws://localhost:33137/devtoo..., se:cdpVersion: 109.0.5414.74, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 1e190295ac878ceaed99477be581475a
	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:87)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:231)
	at com.vaadin.testbench.TestBenchTestCase.waitUntil(TestBenchTestCase.java:197)
	at com.vaadin.testbench.TestBenchTestCase.waitUntil(TestBenchTestCase.java:224)
	at com.vaadin.flow.devbuild.DevBundleThemeIT.waitUntilCustomFont(DevBundleThemeIT.java:139)
	at com.vaadin.flow.devbuild.DevBundleThemeIT.serveStylesInExpressBuildMode_assetsAreCopiedToBundle(DevBundleThemeIT.java:85)

```

**Comment by mshabarov** [comment]
This looks like a bug that the font is not applied to the `body` with express build mode. I'll make an issue.

**Review by mshabarov — APPROVED** [review]

**Review by mcollovati — APPROVED** [review]

**Pull request merged**
