### PR TITLE
 Add a new constructor for Grid allowing to set the pageSize

### PR DESCRIPTION
**Pull request by gilberto-torrezan**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/2689)

### CODE REVIEW

**Comment by torok-peter** [comment]
Reviewed 6 of 7 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2689)*

**Comment by SomeoneToIgnore** [comment]
*[flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/grid/GridViewIT.java, line 67 at r2](https://reviewable.io:443/reviews/vaadin/flow/2689#-Kwe1ul-g4__6OuCLV2j:-Kwe1ul-g4__6OuCLV2k:b1mq1kb) ([raw file](https://github.com/vaadin/flow/blob/886803ee99a6c5e468d666d55a9c9ddbc701030e/flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/grid/GridViewIT.java#L67)):*
> ```Java
>         open();
> 
>         waitForElementPresent(By.tagName("vaadin-grid"));
> ```

This looks like a duplication.

Can `open` method be overridden in `AbstractComponentIT`? You can wait for `body` to be present there.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2689)*

**Comment by gilberto-torrezan** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/grid/GridViewIT.java, line 67 at r2](https://reviewable.io:443/reviews/vaadin/flow/2689#-Kwe1ul-g4__6OuCLV2j:-KweI8a5SMdeNxKSy1X_:b-vq70nz) ([raw file](https://github.com/vaadin/flow/blob/886803ee99a6c5e468d666d55a9c9ddbc701030e/flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/grid/GridViewIT.java#L67)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

This looks like a duplication.

Can `open` method be overridden in `AbstractComponentIT`? You can wait for `body` to be present there.
</blockquote></details>

`body` would always be present - this wait here makes sure Flow has loaded and imported the webcomponent. Locally this is not needed, but I developed the habit to put this in every test I make to reduce weird behavior on CI server.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2689)*

**Comment by SomeoneToIgnore** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/grid/GridViewIT.java, line 67 at r2](https://reviewable.io:443/reviews/vaadin/flow/2689#-Kwe1ul-g4__6OuCLV2j:-KweInNoX6thFGIKazQC:bqog9xj) ([raw file](https://github.com/vaadin/flow/blob/886803ee99a6c5e468d666d55a9c9ddbc701030e/flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/grid/GridViewIT.java#L67)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

`body` would always be present - this wait here makes sure Flow has loaded and imported the webcomponent. Locally this is not needed, but I developed the habit to put this in every test I make to reduce weird behavior on CI server.
</blockquote></details>

The habit is awesome, it's just the duplication that bothers me.
Bit since it's not that easy to update it, then ok.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2689)*

**Comment by gilberto-torrezan** [comment]
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/grid/GridViewIT.java, line 67 at r2](https://reviewable.io:443/reviews/vaadin/flow/2689#-Kwe1ul-g4__6OuCLV2j:-KweKCDMO0rfs_Fo82zS:b-mnmgtm) ([raw file](https://github.com/vaadin/flow/blob/886803ee99a6c5e468d666d55a9c9ddbc701030e/flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/grid/GridViewIT.java#L67)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

The habit is awesome, it's just the duplication that bothers me.
Bit since it's not that easy to update it, then ok.
</blockquote></details>

Moved the repeated code to a `@Before` method. Better than nothing =)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2689)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/grid/GridViewIT.java, line 67 at r2](https://reviewable.io:443/reviews/vaadin/flow/2689#-Kwe1ul-g4__6OuCLV2j:-KweKT4wqZvQIWca-GCs:b7s7fkx) ([raw file](https://github.com/vaadin/flow/blob/886803ee99a6c5e468d666d55a9c9ddbc701030e/flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/grid/GridViewIT.java#L67)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Moved the repeated code to a `@Before` method. Better than nothing =)
</blockquote></details>

Cool :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2689)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 1 of 1 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2689)*

**Pull request merged**
