### PR TITLE
Use VaadinService resolve methods in HtmlDependencyParser

### PR DESCRIPTION
**Pull request by Artur-**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3945)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 7 of 8 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[flow-server/src/main/java/com/vaadin/flow/component/internal/ComponentMetaData.java, line 220 at r2](https://beta.reviewable.io/reviews/vaadin/flow/3945#-LAWmVqH93wvmyo8bzza:-LAWmVqI2RE1z3fH0mzZ:b2se7hr) ([raw file](https://github.com/vaadin/flow/blob/9099ee93aced371b22489695015bcb51924f787c/flow-server/src/main/java/com/vaadin/flow/component/internal/ComponentMetaData.java#L220)):*
> ```
> VaadinService service = VaadinService.getCurrent();
> ```

`VaadinService` is singleton in reality, right ?
Shouldn't we rename `getCurrent` in `getInstance()` and make it threadsafe?

---

*[flow-server/src/main/java/com/vaadin/flow/component/internal/HtmlDependencyParser.java, line 61 at r2](https://beta.reviewable.io/reviews/vaadin/flow/3945#-LAWmta9BpzkhdFFKNZY:-LAWmta9BpzkhdFFKNZZ:bxxiwri) ([raw file](https://github.com/vaadin/flow/blob/9099ee93aced371b22489695015bcb51924f787c/flow-server/src/main/java/com/vaadin/flow/component/internal/HtmlDependencyParser.java#L61)):*
> ```
> VaadinService service
> ```

If it's a singleton then this parameter is not needed.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3945)*

**Comment by Artur-** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/component/internal/ComponentMetaData.java, line 220 at r2](https://beta.reviewable.io/reviews/vaadin/flow/3945#-LAWmVqH93wvmyo8bzza:-LAWrYr69xdT3OxTGGsV:b-dz2uey) ([raw file](https://github.com/vaadin/flow/blob/9099ee93aced371b22489695015bcb51924f787c/flow-server/src/main/java/com/vaadin/flow/component/internal/ComponentMetaData.java#L220)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
> VaadinService service = VaadinService.getCurrent();
> ```

`VaadinService` is singleton in reality, right ?
Shouldn't we rename `getCurrent` in `getInstance()` and make it threadsafe?
</blockquote></details>

It's only a singleton if you do a `/*` mapping for the servlet

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3945)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/component/internal/ComponentMetaData.java, line 220 at r2](https://beta.reviewable.io/reviews/vaadin/flow/3945#-LAWmVqH93wvmyo8bzza:-LAWtOFo0kBhMuYxTSCI:brxen7g) ([raw file](https://github.com/vaadin/flow/blob/9099ee93aced371b22489695015bcb51924f787c/flow-server/src/main/java/com/vaadin/flow/component/internal/ComponentMetaData.java#L220)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

It's only a singleton if you do a `/*` mapping for the servlet
</blockquote></details>

`VaadinServletService` is not a singleton at all since it requires a servlet in its CTOR.
There might be several servlet instances.

Shouldn't the servlet context be passed as a parameter then since it's only needed ?

```
        // (VaadinServletService) as the methods are only using the servlet
        // context
```

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3945)*

**Comment by Artur-** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/flow/3945#-LAWvBuA6ffCNX_X1Swg:-LAWzS24AobT3-qioibB:bhf1164) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Shouldn't the global cache `static ReflectionCache<Component, ComponentMetaData>` in the `ComponentUtil` be replaced to something more appropriate since `getCurrent` is removed from everywhere ?
May be this cache should be stored in the `VaadinService` instance ?
</blockquote></details>

In reality the cache is global as the assumption is that you have one `/frontend` in your app regardless of how many servlets/services you have

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3945)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/flow/3945#-LAWvBuA6ffCNX_X1Swg:-LAX-cxb9Npasplbl3vi:bhu61r8) (no related file):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

In reality the cache is global as the assumption is that you have one `/frontend` in your app regardless of how many servlets/services you have
</blockquote></details>

Right.
And that assumption is not really valid since it's possible to have `/frontend` per servlet (hard to do technically but possible).
And there is an issue which will allow it via just a configuration (if you have several mappings then it will be possible to use their own frontends per servlet).

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3945)*

**Comment by Artur-** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/flow/3945#-LAWvBuA6ffCNX_X1Swg:-LAX3omD8_ae0O_EHwlB:b-4rzuke) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Right.
And that assumption is not really valid since it's possible to have `/frontend` per servlet (hard to do technically but possible).
And there is an issue which will allow it via just a configuration (if you have several mappings then it will be possible to use their own frontends per servlet).
</blockquote></details>

Except that no add-ons would likely work if `/frontend` is not `/frontend`

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3945)*

**Comment by Artur-** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/flow/3945#-LAWvBuA6ffCNX_X1Swg:-LAX4dRUDD2ABWUYtpDc:bh7s0ek) (no related file):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Except that no add-ons would likely work if `/frontend` is not `/frontend`
</blockquote></details>

But if we do decide to add support for multiple frontend folders, this should probably be considered at that point

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3945)*

**Comment by denis-anisimov** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3945#-:-LAX9R2l6K8pvppNxlo_:bnfp4nl)*

**Pull request merged**
