### PR TITLE
Defer binding initially invisible element on the client side

### PR DESCRIPTION
**Pull request by denis-anisimov**
Initially invisible element shouldn't be bound to avoid sending data from the client side to the server side until it becomes visible.

Fix for #3148

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3212)

### CODE REVIEW

**Comment by gilberto-torrezan** [comment]
Reviewed 16 of 19 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java, line 523 at r2](https://reviewable.io:443/reviews/vaadin/flow/3212#-L1M0wB8f3L7Xxn9rISW:-L1M0wB96cct_CGCAfaz:b-xces4g) ([raw file](https://github.com/vaadin/flow/blob/f51bb14a6bc52e8c60108d1efc9e60c757214a91/flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java#L523)):*
> ```Java
>         return node.hasFeature(NodeFeatures.VISIBILITY_DATA) && Boolean.FALSE
>                 .equals(node.getMap(NodeFeatures.VISIBILITY_DATA)
>                         .getProperty(NodeProperties.VISIBILITY_BOUND_PROPERTY)
> ```

Does the `VISIBILITY_BOUND_PROPERTY` also have the same behavior as the `VISIBLE`? (`true` or absence of value means `bound`). If so, a more descriptive method strucutre, like used in `isVisible(StateNode)`  would make sense.

---

*[flow-client/src/test-gwt/java/com/vaadin/client/flow/GwtBasicElementBinderTest.java, line 1334 at r2](https://reviewable.io:443/reviews/vaadin/flow/3212#-L1M22pS9K76jHc1dNli:-L1M22pT5uHJfCDVZS7x:bxg0i6a) ([raw file](https://github.com/vaadin/flow/blob/f51bb14a6bc52e8c60108d1efc9e60c757214a91/flow-client/src/test-gwt/java/com/vaadin/client/flow/GwtBasicElementBinderTest.java#L1334)):*
> ```Java
>         node.setDomNode(element);
> 
>         List<Integer> list = Arrays.asList(0);
> ```

The same behavior can be done with an `AtomicInteger`. Not blocking though.

---

*[flow-client/src/test-gwt/java/com/vaadin/client/flow/GwtBasicElementBinderTest.java, line 1354 at r2](https://reviewable.io:443/reviews/vaadin/flow/3212#-L1M2OTR52YPzKbE3Ukk:-L1M2OTR52YPzKbE3Ukl:b8q4eyj) ([raw file](https://github.com/vaadin/flow/blob/f51bb14a6bc52e8c60108d1efc9e60c757214a91/flow-client/src/test-gwt/java/com/vaadin/client/flow/GwtBasicElementBinderTest.java#L1354)):*
> ```Java
> 
>         // DOM node set listener is notified at least once
>         assertTrue(list.get(0) > 1);
> ```

For the sake of this test, does it matter if the listener is notified 1 or 10 times? Would it be a bug if it is notified `X` times?
My point is: should this assert be `list.get(0) == 1` instead?

---

*[flow-client/src/test-gwt/java/com/vaadin/client/flow/GwtBasicElementBinderTest.java, line 1388 at r2](https://reviewable.io:443/reviews/vaadin/flow/3212#-L1M41JDHbP7D85M1ag_:-L1M41JDHbP7D85M1aga:b-gfkuyu) ([raw file](https://github.com/vaadin/flow/blob/f51bb14a6bc52e8c60108d1efc9e60c757214a91/flow-client/src/test-gwt/java/com/vaadin/client/flow/GwtBasicElementBinderTest.java#L1388)):*
> but we
>         // should check that initial visibility listener (in partial binding) is
>         // removed as well

How is that check performed here?

---

*[flow-client/src/test/java/com/vaadin/client/flow/ExecuteJavaScriptProcessorTest.java, line 395 at r2](https://reviewable.io:443/reviews/vaadin/flow/3212#-L1M6g0GvReBK1c2Pvs7:-L1M6g0GvReBK1c2Pvs8:b-dherzg) ([raw file](https://github.com/vaadin/flow/blob/f51bb14a6bc52e8c60108d1efc9e60c757214a91/flow-client/src/test/java/com/vaadin/client/flow/ExecuteJavaScriptProcessorTest.java#L395)):*
> ```Java
>         Assert.assertFalse(processor.isBound(node));
>     }
> }
> ```

For the sake of completeness and documentation, I suggest adding a `isBound_hasElementHasFeatureAndBoundAndUnboundParent_notBound` test, testing that setting the property has no effect if the parent is not bound.

---

*[flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/VisibilityIT.java, line 54 at r2](https://reviewable.io:443/reviews/vaadin/flow/3212#-L1MAJYlSr4dnGGkPhvb:-L1MAJYlSr4dnGGkPhvc:b1opo2f) ([raw file](https://github.com/vaadin/flow/blob/f51bb14a6bc52e8c60108d1efc9e60c757214a91/flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/VisibilityIT.java#L54)):*
> ```Java
>         visibilityButton.click();
> 
>         Assert.assertEquals(Boolean.TRUE.toString(),
> ```

I didn't get it. When you set the `visibility` to `false`, isn't the `div` supposed to be removed from the DOM (instead of `hidden`) ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3212)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java, line 523 at r2](https://reviewable.io:443/reviews/vaadin/flow/3212#-L1M0wB8f3L7Xxn9rISW:-L1MHuAGm5z9vHhrkbBK:b-u7z1fh) ([raw file](https://github.com/vaadin/flow/blob/f51bb14a6bc52e8c60108d1efc9e60c757214a91/flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java#L523)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Does the `VISIBILITY_BOUND_PROPERTY` also have the same behavior as the `VISIBLE`? (`true` or absence of value means `bound`). If so, a more descriptive method strucutre, like used in `isVisible(StateNode)`  would make sense.
</blockquote></details>

No.......
and yes.

`VISIBILITY_BOUND_PROPERTY` is an addition to the `VISIBLE`.
`VISIBILITY_BOUND_PROPERTY` has initially the same value is `VISIBLE` value. 
But then its reset _only once_. `VISIBLE` property may change it's value as many times as it's requested from the server side.

Well, I understand you concern: the code for `isVisible`  is almost the same as the code for `needsRebind` with only difference which is the property value. But they have different lifecycle and meaning (actually the code is not the same). 

Two options:
- element is visible initially. Then it should be completely bound. `VISIBILITY_BOUND_PROPERTY` property value is set to `true`  and never changed in the future.
- element is invisible initially. Then it's partially bound: visibility feature is bound only. Once it become visible later on it should be completely re-bound. `VISIBILITY_BOUND_PROPERTY`  value is set to `false` and it means that the node should be re-bound. Once the node becomes visible the value of the property is set to `true` and never changed anymore.

Technically this is implementation detail which should not be exposed at all.
The only difference is the freaking JS execution which needs to be deferred if element is not completely bound. And this method is made public only to avoid code duplication.

---

*[flow-client/src/test-gwt/java/com/vaadin/client/flow/GwtBasicElementBinderTest.java, line 1334 at r2](https://reviewable.io:443/reviews/vaadin/flow/3212#-L1M22pS9K76jHc1dNli:-L1MLp2KqN3WtuGf94Bt:bokcgs9) ([raw file](https://github.com/vaadin/flow/blob/f51bb14a6bc52e8c60108d1efc9e60c757214a91/flow-client/src/test-gwt/java/com/vaadin/client/flow/GwtBasicElementBinderTest.java#L1334)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

The same behavior can be done with an `AtomicInteger`. Not blocking though.
</blockquote></details>

Can't be most likely.

This is GWT unite test.
I have serious doubts that `AtomicInteger` is emulated by GWT.

---

*[flow-client/src/test-gwt/java/com/vaadin/client/flow/GwtBasicElementBinderTest.java, line 1354 at r2](https://reviewable.io:443/reviews/vaadin/flow/3212#-L1M2OTR52YPzKbE3Ukk:-L1MM4LmYIrwLEeRsj02:bygferc) ([raw file](https://github.com/vaadin/flow/blob/f51bb14a6bc52e8c60108d1efc9e60c757214a91/flow-client/src/test-gwt/java/com/vaadin/client/flow/GwtBasicElementBinderTest.java#L1354)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

For the sake of this test, does it matter if the listener is notified 1 or 10 times? Would it be a bug if it is notified `X` times?
My point is: should this assert be `list.get(0) == 1` instead?
</blockquote></details>

At the moment `==1` is not `true`.
Listener is notified twice. This is not a bug.
( DOM node is set to `null` first then it set to the same value as it has before `null` just to notify the listener).
It should be notified once at least.
Doesn't matter how many times it's called if it's called at least once. I avoid exact numbers here because the implementation may be changed in the future but this test will still work.

---

*[flow-client/src/test-gwt/java/com/vaadin/client/flow/GwtBasicElementBinderTest.java, line 1388 at r2](https://reviewable.io:443/reviews/vaadin/flow/3212#-L1M41JDHbP7D85M1ag_:-L1MMhjzlZ1sbBMJ9HVJ:b8w4501) ([raw file](https://github.com/vaadin/flow/blob/f51bb14a6bc52e8c60108d1efc9e60c757214a91/flow-client/src/test-gwt/java/com/vaadin/client/flow/GwtBasicElementBinderTest.java#L1388)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

> but we
>         // should check that initial visibility listener (in partial binding) is
>         // removed as well

How is that check performed here?
</blockquote></details>

The very last line.

The attribute value would be `true` instead of `null` if the listener is not removed since the node is set visible before `flush`.

Comment is extended.

---

*[flow-client/src/test/java/com/vaadin/client/flow/ExecuteJavaScriptProcessorTest.java, line 395 at r2](https://reviewable.io:443/reviews/vaadin/flow/3212#-L1M6g0GvReBK1c2Pvs7:-L1MOMCEYu6AqU3HFJKo:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/f51bb14a6bc52e8c60108d1efc9e60c757214a91/flow-client/src/test/java/com/vaadin/client/flow/ExecuteJavaScriptProcessorTest.java#L395)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

For the sake of completeness and documentation, I suggest adding a `isBound_hasElementHasFeatureAndBoundAndUnboundParent_notBound` test, testing that setting the property has no effect if the parent is not bound.
</blockquote></details>

Done.

---

*[flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/VisibilityIT.java, line 54 at r2](https://reviewable.io:443/reviews/vaadin/flow/3212#-L1MAJYlSr4dnGGkPhvb:-L1MNk-63uxXhFxj6I19:bw21sfb) ([raw file](https://github.com/vaadin/flow/blob/f51bb14a6bc52e8c60108d1efc9e60c757214a91/flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/VisibilityIT.java#L54)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

I didn't get it. When you set the `visibility` to `false`, isn't the `div` supposed to be removed from the DOM (instead of `hidden`) ?
</blockquote></details>

No.
As decided: we don't modify DOM tree.
The element just becomes invisible ( it gets hidden attribute).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3212)*

**Comment by gilberto-torrezan** [comment]
Review status: 16 of 19 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/VisibilityIT.java, line 54 at r2](https://reviewable.io:443/reviews/vaadin/flow/3212#-L1MAJYlSr4dnGGkPhvb:-L1MQDpsPJdSWH4KnyaG:b-qxfdb2) ([raw file](https://github.com/vaadin/flow/blob/f51bb14a6bc52e8c60108d1efc9e60c757214a91/flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/VisibilityIT.java#L54)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

No.
As decided: we don't modify DOM tree.
The element just becomes invisible ( it gets hidden attribute).
</blockquote></details>

Ok, in this case what happens if the user screws up, by doing this:

1) adds an element (visible)
2) in a separate call (as listener to a button click, for instance), sets the visibility of the item as `false`
3) then sets `element.setAttribute("hidden", "false");` manually

If I understood it correctly, the `setAttribute`  call is never sent from the server since the communication is blocked after the `setVisible(false)`. So it should be fine. I wonder if it makes sense to include this case in the IT though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3212)*

**Comment by denis-anisimov** [comment]
Review status: 16 of 19 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/VisibilityIT.java, line 54 at r2](https://reviewable.io:443/reviews/vaadin/flow/3212#-L1MAJYlSr4dnGGkPhvb:-L1MULdi3FpxnoLQLWKK:bvgkwst) ([raw file](https://github.com/vaadin/flow/blob/f51bb14a6bc52e8c60108d1efc9e60c757214a91/flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/VisibilityIT.java#L54)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Ok, in this case what happens if the user screws up, by doing this:

1) adds an element (visible)
2) in a separate call (as listener to a button click, for instance), sets the visibility of the item as `false`
3) then sets `element.setAttribute("hidden", "false");` manually

If I understood it correctly, the `setAttribute`  call is never sent from the server since the communication is blocked after the `setVisible(false)`. So it should be fine. I wonder if it makes sense to include this case in the IT though.
</blockquote></details>

The communication is not blocked at the moment.
Server side always sends all updates to the client side regardless of visibility.
The functionality which blocks this communication will be implemented in the #3213.

It's possible to do a thing you have described.

But this has no any relation to this PR.
This PR doesn't bind the node if it's initially invisible.

So it's totally out of the scope of this PR and its issue.

I think that this would not have been an issue even without #3213.

But the issue you described will be really fixed by the #3213.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3212)*

**Comment by gilberto-torrezan** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3212)*

**Comment by gilberto-torrezan** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3212#-:-L1MgjUZaE2DSQJRIdHw:bnfp4nl)*

**Pull request merged**
