### PR TITLE
Add support for ValueChangeMode.ON_CHANGE

### PR DESCRIPTION
**Pull request by marcushellberg**
Fix https://github.com/vaadin/vaadin-text-field-flow/issues/55

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3685)

### CODE REVIEW

**Comment by pleku** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[flow-data/src/main/java/com/vaadin/flow/data/value/HasValueChangeMode.java, line 55 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3685#-L7EaHcGArRQvRWP7ocm:-L7EaHcGArRQvRWP7ocn:bluxf6r) ([raw file](https://github.com/vaadin/flow/blob/6698e12ded2758e5ec89e8724bd10cb9c566f49e/flow-data/src/main/java/com/vaadin/flow/data/value/HasValueChangeMode.java#L55)):*
> ```Java
>      *            new value change mode, not {@code null}
>      */
>     default void setValueChangeMode(ValueChangeMode valueChangeMode) {
> ```

It seems to me we should add a unit test to verify this methods logic, so that nobody accidentally breaks things. But we can do that (not blocking) 

---

*[flow-data/src/main/java/com/vaadin/flow/data/value/HasValueChangeMode.java, line 61 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3685#-L7E_LSDAz_LZesnRW1w:-L7E_LSDAz_LZesnRW1x:bow1q0b) ([raw file](https://github.com/vaadin/flow/blob/6698e12ded2758e5ec89e8724bd10cb9c566f49e/flow-data/src/main/java/com/vaadin/flow/data/value/HasValueChangeMode.java#L61)):*
>  element.removeSynchronizedPropertyEvent("blur");

This line should be extracted to outside the switch-case and should use `getClientPropertyChangeEventName()`. Now after adding a third option, this would be broken.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3685)*

**Comment by heruan** [comment]
As @Legioth commented on the issue, is there any reason to keep `ON_BLUR`? The `blur` event will fire even if there is not change (i.e. unnecessary server request).

**Comment by pleku** [comment]
>As @Legioth commented on the issue, is there any reason to keep ON_BLUR? The blur event will fire even if there is not change (i.e. unnecessary server request).

That is false, there is no unnecessary property update on `blur` when the value has not changed. Just tested with https://vaadin.com/components/vaadin-text-field/java-examples

I didn't comment on removing that, since I think it is possible that you might have some component where there is a lot of data being set to the value, eg. you are selecting 20 items or such, and then you want the event to the server only after the user has finished the selection and switches focus to somewhere else. Thus the difference with `blur` and `change` is that `change` might trigger an update after picking each item and `blur` only when you have selected everything you wanted.

I don't have a component to provide as an example now, but I think there can be such.

**Comment by pekam** [comment]
Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-data/src/main/java/com/vaadin/flow/data/value/HasValueChangeMode.java, line 55 at r1](https://reviewable.io:443/reviews/vaadin/flow/3685#-L7EaHcGArRQvRWP7ocm:-L7UN-9y9CshALVRhODF:bb7f2mf) ([raw file](https://github.com/vaadin/flow/blob/6698e12ded2758e5ec89e8724bd10cb9c566f49e/flow-data/src/main/java/com/vaadin/flow/data/value/HasValueChangeMode.java#L55)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

It seems to me we should add a unit test to verify this methods logic, so that nobody accidentally breaks things. But we can do that (not blocking) 
</blockquote></details>

done

---

*[flow-data/src/main/java/com/vaadin/flow/data/value/HasValueChangeMode.java, line 61 at r1](https://reviewable.io:443/reviews/vaadin/flow/3685#-L7E_LSDAz_LZesnRW1w:-L7UN26mLN9rZ63jMjH6:bb7f2mf) ([raw file](https://github.com/vaadin/flow/blob/6698e12ded2758e5ec89e8724bd10cb9c566f49e/flow-data/src/main/java/com/vaadin/flow/data/value/HasValueChangeMode.java#L61)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

>  element.removeSynchronizedPropertyEvent("blur");

This line should be extracted to outside the switch-case and should use `getClientPropertyChangeEventName()`. Now after adding a third option, this would be broken.
</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3685)*

**Comment by pleku** [comment]
Oopsie, :lgtm_cancel: since I realized the issue but forgot to update the comment

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3685#-:-L7UUa_G0rvI3o7z8vew:b1ek0oy)*

**Comment by pekam** [comment]
Review status: 1 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[flow-data/src/main/java/com/vaadin/flow/data/value/HasValueChangeMode.java, line 27 at r2](https://reviewable.io:443/reviews/vaadin/flow/3685#-L7UTsYY5MqpoCEXYWKZ:-L7U_8CxqlNG4oRpWhwY:bb7f2mf) ([raw file](https://github.com/vaadin/flow/blob/7f1104634a15bddd84be92ec30121e81dbc69ee0/flow-data/src/main/java/com/vaadin/flow/data/value/HasValueChangeMode.java#L27)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Probably should mention that any component implementing this interface should set the default value ?
</blockquote></details>

done

---

*[flow-data/src/main/java/com/vaadin/flow/data/value/HasValueChangeMode.java, line 43 at r2](https://reviewable.io:443/reviews/vaadin/flow/3685#-L7UTaoNAVsKB3wbqY5-:-L7UmPFeVmRBR_99Zs5X:b-59ihf8) ([raw file](https://github.com/vaadin/flow/blob/7f1104634a15bddd84be92ec30121e81dbc69ee0/flow-data/src/main/java/com/vaadin/flow/data/value/HasValueChangeMode.java#L43)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Probably should add that the default value is `null`but dependent on the web component, and it should be explicitly set in a component ?
</blockquote></details>

Are you sure? IMO the javadoc on the class is enough. I don't like adding "depends on the implementing component" -kind of text into a javadoc that will be shown in the implementing component's API (unless overridden).

---

*[flow-data/src/main/java/com/vaadin/flow/data/value/HasValueChangeMode.java, line 45 at r2](https://reviewable.io:443/reviews/vaadin/flow/3685#-L7UTzP1CKehR_50-Dsx:-L7U_Eb8SQj1Hr2-PyDH:b15kv80) ([raw file](https://github.com/vaadin/flow/blob/7f1104634a15bddd84be92ec30121e81dbc69ee0/flow-data/src/main/java/com/vaadin/flow/data/value/HasValueChangeMode.java#L45)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Is `null` a valid return value ?
</blockquote></details>

it is now

---

*[flow-data/src/main/java/com/vaadin/flow/data/value/HasValueChangeMode.java, line 53 at r2](https://reviewable.io:443/reviews/vaadin/flow/3685#-L7UU3d5dYY6hFd7GIfz:-L7U_jpP8qkcDIoGH6s-:b5oo7xk) ([raw file](https://github.com/vaadin/flow/blob/7f1104634a15bddd84be92ec30121e81dbc69ee0/flow-data/src/main/java/com/vaadin/flow/data/value/HasValueChangeMode.java#L53)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Why cannot I set `null` if that is the default value however if nothing has been set explicitly ?
I have to clear the value using element API ?
</blockquote></details>

Now `null` removes the synchronization

---

*[flow-data/src/main/java/com/vaadin/flow/data/value/ValueChangeMode.java, line 27 at r2](https://reviewable.io:443/reviews/vaadin/flow/3685#-L7UT20BI9NGFRVDZxXw:-L7UcouOJah_vBVvII-B:b-79tcks) ([raw file](https://github.com/vaadin/flow/blob/7f1104634a15bddd84be92ec30121e81dbc69ee0/flow-data/src/main/java/com/vaadin/flow/data/value/ValueChangeMode.java#L27)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Could you add also that this is specified by the `HasValue.getClientPropertyChangeEventName()` method ?

And actually technically this should be renamed to `ON_PROPERTY_CHANGE` instead of `EAGER` since it is totally up to the Web Component that whether that firing is eager or not.
</blockquote></details>

Added that to javadoc.

If we rename this we should IMO do it in a separate PR. Then it's easier to locate where the breaking change happened compared to it being as a side note of this PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3685)*

**Comment by pleku** [comment]
Reviewed 1 of 3 files at r3.
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-data/src/main/java/com/vaadin/flow/data/value/ValueChangeMode.java, line 27 at r2](https://reviewable.io:443/reviews/vaadin/flow/3685#-L7UT20BI9NGFRVDZxXw:-L7UvHUe7ZoJ7IMe01HJ:bm3hjm4) ([raw file](https://github.com/vaadin/flow/blob/7f1104634a15bddd84be92ec30121e81dbc69ee0/flow-data/src/main/java/com/vaadin/flow/data/value/ValueChangeMode.java#L27)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

Added that to javadoc.

If we rename this we should IMO do it in a separate PR. Then it's easier to locate where the breaking change happened compared to it being as a side note of this PR.
</blockquote></details>

Yeah by default it is now kind of eager event compared to the other options. But that was only a side note.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3685)*

**Comment by pleku** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[flow-data/src/main/java/com/vaadin/flow/data/value/HasValueChangeMode.java, line 43 at r2](https://reviewable.io:443/reviews/vaadin/flow/3685#-L7UTaoNAVsKB3wbqY5-:-L7UvqZm-uznlIvDEkoY:bap2gpj) ([raw file](https://github.com/vaadin/flow/blob/7f1104634a15bddd84be92ec30121e81dbc69ee0/flow-data/src/main/java/com/vaadin/flow/data/value/HasValueChangeMode.java#L43)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

Are you sure? IMO the javadoc on the class is enough. I don't like adding "depends on the implementing component" -kind of text into a javadoc that will be shown in the implementing component's API (unless overridden).
</blockquote></details>

Yes, in ideal world the components should override the method to provide better javadocs. In real world though...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3685#-:-L7Uw2b28qgdk8YxmrsW:bnfp4nl)*

**Comment by pleku** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3685)*

**Comment by pleku** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3685)*

**Comment by pleku** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3685#-:-L7YTHq-BlA6DISoU_g3:bnfp4nl)*

**Pull request merged**
