### PR TITLE
Webjars added into Flow

### PR DESCRIPTION
**Pull request by SomeoneToIgnore**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/2634)

### CODE REVIEW

**Comment by gilberto-torrezan** [comment]
Reviewed 16 of 18 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pom.xml, line 316 at r2](https://reviewable.io:443/reviews/vaadin/flow/2634#-Kw9xUHeMrggxioRASge:-Kw9xUHf2FTHrcXGhW2Z:btatd7k) ([raw file](https://github.com/vaadin/flow/blob/2b57d61e225c030fa334da6692181580d6803184/pom.xml#L316)):*
> ```XML
>             <dependency>
>                 <groupId>org.webjars.bower</groupId>
>                 <artifactId>iron-a11y-announcer</artifactId>
> ```

Do we need to explicitly import this? It's only used internally by other webcomponents. Same for other packages, like `iron-overlay-behavior`.

(In other words: webjars don't manage dependencies?)

---

*[flow-server/src/main/java/com/vaadin/server/DefaultDeploymentConfiguration.java, line 410 at r2](https://reviewable.io:443/reviews/vaadin/flow/2634#-Kw9yVIHHBYsZM13p_f_:-Kw9yVIHHBYsZM13p_fa:b-cx65r7) ([raw file](https://github.com/vaadin/flow/blob/2b57d61e225c030fa334da6692181580d6803184/flow-server/src/main/java/com/vaadin/server/DefaultDeploymentConfiguration.java#L410)):*
> ```Java
>         getLogger().log(Level.CONFIG, () -> formatDefaultPolyfillMessage(
>                 "Will use webcomponents polyfill discovered in " + dirName));
>         return ApplicationConstants.CONTEXT_PROTOCOL_PREFIX + dirName + '/';
> ```

`context://`? So the URL for the polyfills won't change if transpilation is used?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2634)*

**Comment by SomeoneToIgnore** [comment]
*[pom.xml, line 316 at r2](https://reviewable.io:443/reviews/vaadin/flow/2634#-Kw9xUHeMrggxioRASge:-Kw9ziMIaQHexS9VqArp:b-q4xknh) ([raw file](https://github.com/vaadin/flow/blob/41195cb4029ef4f65fb5d1b1e5ed6c7130a94994/pom.xml#L316)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Do we need to explicitly import this? It's only used internally by other webcomponents. Same for other packages, like `iron-overlay-behavior`.

(In other words: webjars don't manage dependencies?)
</blockquote></details>

It's a `dependencyManagement` section, not `dependencies`, so we don't add dependencies, we just enforce some resolution rules.

Main reason for this is that all webjars transitive dependencies' versions are specified as range:
```
<dependency>
            <groupId>org.webjars.bower</groupId>
            <artifactId>github-com-polymer-polymer</artifactId>
            <version>[1.9,3)</version>
        </dependency>
```

So, by enforcing dependencies we
1. Make sure that we take the needed versions
2. Make sure that those versions won't change in the future
3. Fix potential issues with differently named webjars for the same bower dependency name.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2634)*

**Comment by heruan** [comment]
Tried to follow the changes but got lost: would this basically lock webjars versions via `dependencyManagement` in `flow-components-parent` and require them explicitly on the final project?

**Comment by SomeoneToIgnore** [comment]
A bit different thing: it'll add all required webjar dependencies to `flow-components` module so that you can use our server side components without providing any external webcomponents via bower.json
And the versions are fixed in root pom, but it does not really matter.

**Comment by SomeoneToIgnore** [comment]
*[flow-server/src/main/java/com/vaadin/server/DefaultDeploymentConfiguration.java, line 410 at r2](https://reviewable.io:443/reviews/vaadin/flow/2634#-Kw9yVIHHBYsZM13p_f_:-KwQnNuy3rfAiRrS_n8f:be8ggmz) ([raw file](https://github.com/vaadin/flow/blob/3fc2422b77f8d5f0dc46f310ee0f5ae132da9c0f/flow-server/src/main/java/com/vaadin/server/DefaultDeploymentConfiguration.java#L410)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

`context://`? So the URL for the polyfills won't change if transpilation is used?
</blockquote></details>

Done. This change can be moved into a separate PR, if necessary.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2634)*

**Comment by gilberto-torrezan** [comment]
Reviewed 16 of 17 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2634)*

**Pull request merged**
