### PR TITLE
Revert "Update jetty version (#4094)"

### PR DESCRIPTION
**Pull request by denis-anisimov**
This reverts commit 352855779ec4ce3da48b9f1bb0a70551feb89d14.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/4098)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-components-parent/flow-component-demo-helpers/pom.xml, line 19 at r1](https://reviewable.io/reviews/vaadin/flow/4098#-LC2kfxZ-1BUDUWjsxYs:-LC2s03o-eb7nUbZUDo9:b-ovymmo) ([raw file](https://github.com/vaadin/flow/blob/b5a5423c532abf34b3f1f6c5b45cc7a695cad604/flow-components-parent/flow-component-demo-helpers/pom.xml#L19)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

This issue is already closed, which is why the version here was changed in the first place.

So at least remove that comment and if you come up with any explanation why this is still needed, that would be great.
</blockquote></details>

This is revert.
I've not changed anything and not going to change.

Please see the description of this PR `This reverts commit 3528557.`

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4098)*

**Comment by pekam** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-components-parent/flow-component-demo-helpers/pom.xml, line 19 at r1](https://reviewable.io/reviews/vaadin/flow/4098#-LC2kfxZ-1BUDUWjsxYs:-LC2sw-s3zC_lYTNCtBo:b-b8rl33) ([raw file](https://github.com/vaadin/flow/blob/b5a5423c532abf34b3f1f6c5b45cc7a695cad604/flow-components-parent/flow-component-demo-helpers/pom.xml#L19)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

This is revert.
I've not changed anything and not going to change.

Please see the description of this PR `This reverts commit 3528557.`

</blockquote></details>

I see that your changes match the description. I just don't think this is a good change to make as it currently is.

I don't care if it's a revert or not. This PR adds a comment about an issue that is already closed and thus I don't think it should be merged "just because it's a revert".

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4098)*

**Comment by pekam** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-components-parent/flow-component-demo-helpers/pom.xml, line 19 at r1](https://reviewable.io/reviews/vaadin/flow/4098#-LC2kfxZ-1BUDUWjsxYs:-LC2uHnY7mOeKOqcQDTg:b-krbb9z) ([raw file](https://github.com/vaadin/flow/blob/b5a5423c532abf34b3f1f6c5b45cc7a695cad604/flow-components-parent/flow-component-demo-helpers/pom.xml#L19)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

I see that your changes match the description. I just don't think this is a good change to make as it currently is.

I don't care if it's a revert or not. This PR adds a comment about an issue that is already closed and thus I don't think it should be merged "just because it's a revert".
</blockquote></details>

One concrete reason is that if we keep the comment, we might end up doing the same mistake again just because someone notices that hey, that issue is closed already so everything should be fine.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4098)*

**Comment by denis-anisimov** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-components-parent/flow-component-demo-helpers/pom.xml, line 19 at r1](https://reviewable.io/reviews/vaadin/flow/4098#-LC2kfxZ-1BUDUWjsxYs:-LC2uaeC1F-Z0ZZtTuSR:b-x71rjk) ([raw file](https://github.com/vaadin/flow/blob/b5a5423c532abf34b3f1f6c5b45cc7a695cad604/flow-components-parent/flow-component-demo-helpers/pom.xml#L19)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

One concrete reason is that if we keep the comment, we might end up doing the same mistake again just because someone notices that hey, that issue is closed already so everything should be fine.
</blockquote></details>

This PR is not intended to fix anything except failing components build.

I don't care about any comment , mistakes or anything.

ONE MORE TIME: THIS IS A REVERT CHANGE.

It's made via `git revert`.

That's it.

I need working builds for components since I need to make a release.
Current state of the source code prevents me to do this.
I don't care about anything else .

If you want something to be fixed then please create another PR and remove the comment and make anything you want.

This PR  is  just a revert.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4098)*

**Comment by pekam** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-components-parent/flow-component-demo-helpers/pom.xml, line 19 at r1](https://reviewable.io/reviews/vaadin/flow/4098#-LC2kfxZ-1BUDUWjsxYs:-LC2xX9-Ehqd49t2Ftib:b-vvsf1g) ([raw file](https://github.com/vaadin/flow/blob/b5a5423c532abf34b3f1f6c5b45cc7a695cad604/flow-components-parent/flow-component-demo-helpers/pom.xml#L19)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

This PR is not intended to fix anything except failing components build.

I don't care about any comment , mistakes or anything.

ONE MORE TIME: THIS IS A REVERT CHANGE.

It's made via `git revert`.

That's it.

I need working builds for components since I need to make a release.
Current state of the source code prevents me to do this.
I don't care about anything else .

If you want something to be fixed then please create another PR and remove the comment and make anything you want.

This PR  is  just a revert.
</blockquote></details>

Okay, so we start using caps now :D

ONE MORE TIME: YOUR PR ADDS A FAULTY COMMENT TO THE CODEBASE WHICH INCREASES THE RISK OF BREAKING EVERYTHING AGAIN IN THE FUTURE

But sure, I can make another PR to help you out :)

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4098)*

**Comment by pekam** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4098#-:-LC2yXbe32GeGXTfjdDS:bnfp4nl)*

**Comment by pekam** [comment]
You need to read the conversation more carefully if you think the problem is in my understanding of `git revert`.
I disagreed whether `git revert` is the best way to fix this.

**Pull request merged**
