### PR TITLE
Move InternalContainerAnnotationForX into X

### PR DESCRIPTION
**Pull request by Legioth**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3088)

### CODE REVIEW

**Comment by ZheSun88** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3088)*

**Comment by caalador** [comment]
Review status: all files reviewed at latest revision, 12 unresolved discussions, some commit checks pending.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3088#-L-H-LUS6u5I2qIPe4NA:-L-H-LUS6u5I2qIPe4NB:b-jdq44k) (no related file):*
Clearer I’d say, but I think they should stop after `NOT meant to be used directly`

---

*[flow-server/src/main/java/com/vaadin/flow/model/Convert.java, line 62 at r1](https://reviewable.io:443/reviews/vaadin/flow/3088#-L-H-Xhp2EnT5R6KxGsX:-L-H-Xhp2EnT5R6KxGsY:bkmrtt2) ([raw file](https://github.com/vaadin/flow/blob/26b734678bd035e1ddf49be2a979470272308e11/flow-server/src/main/java/com/vaadin/flow/model/Convert.java#L62)):*
> ```Java
>      * Annotation enabling use of multiple {@link Convert} annotations.
>      * <p>
>      * <b>NOT meant to be used</b>, for multiple converters, {@link Convert}
> ```

Should stop after the bolded part

---

*[flow-server/src/main/java/com/vaadin/flow/model/Convert.java, line 73 at r1](https://reviewable.io:443/reviews/vaadin/flow/3088#-L-H-lU_lKv__OyU8bAX:-L-H-lU_lKv__OyU8bAY:bi59mel) ([raw file](https://github.com/vaadin/flow/blob/26b734678bd035e1ddf49be2a979470272308e11/flow-server/src/main/java/com/vaadin/flow/model/Convert.java#L73)):*
> ```Java
> 
>         /**
>          * Not to be used, instead multiple {@link Convert} annotations should
> ```

end at comma?

---

*[flow-server/src/main/java/com/vaadin/router/RouteAlias.java, line 80 at r1](https://reviewable.io:443/reviews/vaadin/flow/3088#-L-H-Pe_Ml7kdX7Yuz_A:-L-H-Pe_Ml7kdX7Yuz_B:b-ubx0jb) ([raw file](https://github.com/vaadin/flow/blob/26b734678bd035e1ddf49be2a979470272308e11/flow-server/src/main/java/com/vaadin/router/RouteAlias.java#L80)):*
> ```Java
>      * annotations.
>      * <p>
>      * <b>NOT meant to be used directly</b>, for multiple style sheet
> ```

Should stop after the bolded part, also talks about style sheet.

---

*[flow-server/src/main/java/com/vaadin/router/RouteAlias.java, line 92 at r1](https://reviewable.io:443/reviews/vaadin/flow/3088#-L-H-YeWathx2Bpg8h8z:-L-H-YeWathx2Bpg8h9-:bi59mel) ([raw file](https://github.com/vaadin/flow/blob/26b734678bd035e1ddf49be2a979470272308e11/flow-server/src/main/java/com/vaadin/router/RouteAlias.java#L92)):*
> ```Java
> 
>         /**
>          * Not to be used, instead multiple {@link RouteAlias @RouteAlias}
> ```

end at comma?

---

*[flow-server/src/main/java/com/vaadin/ui/common/HtmlImport.java, line 88 at r1](https://reviewable.io:443/reviews/vaadin/flow/3088#-L-H-sP0yfxvRZsjab52:-L-H-sP0yfxvRZsjab53:bkmrtt2) ([raw file](https://github.com/vaadin/flow/blob/26b734678bd035e1ddf49be2a979470272308e11/flow-server/src/main/java/com/vaadin/ui/common/HtmlImport.java#L88)):*
> ```Java
>      * annotations.
>      * <p>
>      * <b>NOT meant to be used</b>, for multiple HTML dependencies,
> ```

Should stop after the bolded part

---

*[flow-server/src/main/java/com/vaadin/ui/common/HtmlImport.java, line 99 at r1](https://reviewable.io:443/reviews/vaadin/flow/3088#-L-H-bwYOnZu5Jv-bYSU:-L-H-bwYOnZu5Jv-bYSV:bi59mel) ([raw file](https://github.com/vaadin/flow/blob/26b734678bd035e1ddf49be2a979470272308e11/flow-server/src/main/java/com/vaadin/ui/common/HtmlImport.java#L99)):*
> ```Java
> 
>         /**
>          * Not to be used, instead multiple {@link HtmlImport @HtmlImport}
> ```

end at comma?

---

*[flow-server/src/main/java/com/vaadin/ui/common/JavaScript.java, line 74 at r1](https://reviewable.io:443/reviews/vaadin/flow/3088#-L-H-uiOrErd41CFd0Xz:-L-H-uiOrErd41CFd0Y-:b-ubx0jb) ([raw file](https://github.com/vaadin/flow/blob/26b734678bd035e1ddf49be2a979470272308e11/flow-server/src/main/java/com/vaadin/ui/common/JavaScript.java#L74)):*
> ```Java
>      * annotations.
>      * <p>
>      * <b>NOT meant to be used</b>, for multiple style sheet dependencies,
> ```

Should stop after the bolded part, also talks about style sheet.

---

*[flow-server/src/main/java/com/vaadin/ui/common/JavaScript.java, line 85 at r1](https://reviewable.io:443/reviews/vaadin/flow/3088#-L-H-eIwg-ho0f2jpJGB:-L-H-eIwg-ho0f2jpJGC:bi59mel) ([raw file](https://github.com/vaadin/flow/blob/26b734678bd035e1ddf49be2a979470272308e11/flow-server/src/main/java/com/vaadin/ui/common/JavaScript.java#L85)):*
> ```Java
> 
>         /**
>          * Not to be used, instead multiple {@link JavaScript @JavaScript}
> ```

end at comma?

---

*[flow-server/src/main/java/com/vaadin/ui/common/StyleSheet.java, line 74 at r1](https://reviewable.io:443/reviews/vaadin/flow/3088#-L-H-vf3DYVtJE6Hkvq_:-L-H-vf3DYVtJE6Hkvqa:bkmrtt2) ([raw file](https://github.com/vaadin/flow/blob/26b734678bd035e1ddf49be2a979470272308e11/flow-server/src/main/java/com/vaadin/ui/common/StyleSheet.java#L74)):*
> ```Java
>      * annotations.
>      * <p>
>      * <b>NOT meant to be used</b>, for multiple style sheet dependencies,
> ```

Should stop after the bolded part

---

*[flow-server/src/main/java/com/vaadin/ui/common/StyleSheet.java, line 85 at r1](https://reviewable.io:443/reviews/vaadin/flow/3088#-L-H-f2V87pIbFR2n7OY:-L-H-f2V87pIbFR2n7OZ:bi59mel) ([raw file](https://github.com/vaadin/flow/blob/26b734678bd035e1ddf49be2a979470272308e11/flow-server/src/main/java/com/vaadin/ui/common/StyleSheet.java#L85)):*
> ```Java
> 
>         /**
>          * Not to be used, instead multiple {@link StyleSheet @StyleSheet}
> ```

end at comma?

---

*[flow-server/src/main/java/com/vaadin/ui/common/Uses.java, line 66 at r1](https://reviewable.io:443/reviews/vaadin/flow/3088#-L-H-gL-Di3m3x99disM:-L-H-gL0uH7fyDCdx0Jf:bi59mel) ([raw file](https://github.com/vaadin/flow/blob/26b734678bd035e1ddf49be2a979470272308e11/flow-server/src/main/java/com/vaadin/ui/common/Uses.java#L66)):*
> ```Java
> 
>         /**
>          * Not to be used directly, use {@link Uses @Uses} instead.
> ```

end at comma?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3088)*

**Comment by Legioth** [comment]
Review status: all files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[flow-server/src/main/java/com/vaadin/flow/model/Convert.java, line 62 at r1](https://reviewable.io:443/reviews/vaadin/flow/3088#-L-H-Xhp2EnT5R6KxGsX:-L-H5OgIcDGflJWaKq9M:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/26b734678bd035e1ddf49be2a979470272308e11/flow-server/src/main/java/com/vaadin/flow/model/Convert.java#L62)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Should stop after the bolded part
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/flow/model/Convert.java, line 73 at r1](https://reviewable.io:443/reviews/vaadin/flow/3088#-L-H-lU_lKv__OyU8bAX:-L-H5Z_n12BXyNj85b2W:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/26b734678bd035e1ddf49be2a979470272308e11/flow-server/src/main/java/com/vaadin/flow/model/Convert.java#L73)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

end at comma?
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/router/RouteAlias.java, line 80 at r1](https://reviewable.io:443/reviews/vaadin/flow/3088#-L-H-Pe_Ml7kdX7Yuz_A:-L-H5x3y_A_i7f9YdIlG:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/26b734678bd035e1ddf49be2a979470272308e11/flow-server/src/main/java/com/vaadin/router/RouteAlias.java#L80)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Should stop after the bolded part, also talks about style sheet.
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/router/RouteAlias.java, line 92 at r1](https://reviewable.io:443/reviews/vaadin/flow/3088#-L-H-YeWathx2Bpg8h8z:-L-H5xRpCMcXhvNhAAyo:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/26b734678bd035e1ddf49be2a979470272308e11/flow-server/src/main/java/com/vaadin/router/RouteAlias.java#L92)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

end at comma?
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/ui/common/HtmlImport.java, line 88 at r1](https://reviewable.io:443/reviews/vaadin/flow/3088#-L-H-sP0yfxvRZsjab52:-L-H66AIhcNZHFbqy4lm:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/26b734678bd035e1ddf49be2a979470272308e11/flow-server/src/main/java/com/vaadin/ui/common/HtmlImport.java#L88)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Should stop after the bolded part
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/ui/common/HtmlImport.java, line 99 at r1](https://reviewable.io:443/reviews/vaadin/flow/3088#-L-H-bwYOnZu5Jv-bYSU:-L-H66WpizNw0eiRdKmf:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/26b734678bd035e1ddf49be2a979470272308e11/flow-server/src/main/java/com/vaadin/ui/common/HtmlImport.java#L99)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

end at comma?
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/ui/common/JavaScript.java, line 74 at r1](https://reviewable.io:443/reviews/vaadin/flow/3088#-L-H-uiOrErd41CFd0Xz:-L-H6CFCFh8-rUDhJKkx:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/26b734678bd035e1ddf49be2a979470272308e11/flow-server/src/main/java/com/vaadin/ui/common/JavaScript.java#L74)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Should stop after the bolded part, also talks about style sheet.
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/ui/common/JavaScript.java, line 85 at r1](https://reviewable.io:443/reviews/vaadin/flow/3088#-L-H-eIwg-ho0f2jpJGB:-L-H6CZ0HegeKFOoysPc:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/26b734678bd035e1ddf49be2a979470272308e11/flow-server/src/main/java/com/vaadin/ui/common/JavaScript.java#L85)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

end at comma?
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/ui/common/StyleSheet.java, line 74 at r1](https://reviewable.io:443/reviews/vaadin/flow/3088#-L-H-vf3DYVtJE6Hkvq_:-L-H6JyVfn6U9Wg-kIAh:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/26b734678bd035e1ddf49be2a979470272308e11/flow-server/src/main/java/com/vaadin/ui/common/StyleSheet.java#L74)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Should stop after the bolded part
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/ui/common/StyleSheet.java, line 85 at r1](https://reviewable.io:443/reviews/vaadin/flow/3088#-L-H-f2V87pIbFR2n7OY:-L-H6KMamMWNkLvpsKWf:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/26b734678bd035e1ddf49be2a979470272308e11/flow-server/src/main/java/com/vaadin/ui/common/StyleSheet.java#L85)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

end at comma?
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/ui/common/Uses.java, line 66 at r1](https://reviewable.io:443/reviews/vaadin/flow/3088#-L-H-gL-Di3m3x99disM:-L-H6V9R39_n4u-cM533:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/26b734678bd035e1ddf49be2a979470272308e11/flow-server/src/main/java/com/vaadin/ui/common/Uses.java#L66)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

end at comma?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3088)*

**Comment by caalador** [comment]
Reviewed 6 of 12 files at r1, 6 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3088)*

**Pull request merged**
