### PR TITLE
Client side in memory virtual children elements

### PR DESCRIPTION
**Pull request by denis-anisimov**
Make it possible to create an element on the client side which is not attached to the DOM tree.
The element is addressed from the server side via Element API.

Fix for #2826.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3070)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
The JS API is in the https://github.com/vaadin/flow/pull/3078.

**Comment by caalador** [comment]
Reviewed 4 of 22 files at r1.
Review status: 4 of 22 files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3070#-L-AfhuZ7IcD1s2Is8xX:-L-AfhuZ7IcD1s2Is8xY:b17na75) (no related file):*
Could you just update the old VirtualChildMap, just add the overridden `add(int index, StateNode node)` method that ShadowRoot uses and it should be fine as is.

I just don't see the use of adding a NewXYZ that will be then renamed, especially as its more about extending old functionality and the shadowroot node shouldn't even be run so that it would do the bindNewVirtualChildren.

---

*[flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java, line 573 at r2](https://reviewable.io:443/reviews/vaadin/flow/3070#-L-AWSW3VGnlv62olk0g:-L-AWSW3VGnlv62olk0h:bpezu3) ([raw file](https://github.com/vaadin/flow/blob/b91dc07930e6c7c93c062f159169c8c6229f87de/flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java#L573)):*
> ```Java
>     }
> 
>     private EventRemover bindNewVirtualChildren(BindingContext context) {
> ```

Should we just rename these so that this is `bindVirtualChildren` and the old method would be `bindShadowRootVirtualChildren` also unify the 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3070)*

**Comment by denis-anisimov** [comment]
Review status: 4 of 22 files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3070#-L-AfhuZ7IcD1s2Is8xX:-L-AhgT6aG_gGF9MWhs1:b28fvik) (no related file):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Could you just update the old VirtualChildMap, just add the overridden `add(int index, StateNode node)` method that ShadowRoot uses and it should be fine as is.

I just don't see the use of adding a NewXYZ that will be then renamed, especially as its more about extending old functionality and the shadowroot node shouldn't even be run so that it would do the bindNewVirtualChildren.
</blockquote></details>

I would like do not touch the existing `@Id` functionality at all at the moment.
Once I start working on rewriting it I will modify the client-side code and remove the current `VirtualChildList`.

I prefer to avoid touching any unrelated functionality at the moment.

---

*[flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java, line 573 at r2](https://reviewable.io:443/reviews/vaadin/flow/3070#-L-AWSW3VGnlv62olk0g:-L-AiJR_sJ9c-2xQsOK2:b-h9iznw) ([raw file](https://github.com/vaadin/flow/blob/b91dc07930e6c7c93c062f159169c8c6229f87de/flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java#L573)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Should we just rename these so that this is `bindVirtualChildren` and the old method would be `bindShadowRootVirtualChildren` also unify the 
</blockquote></details>

Will be renamed to `bindVirtualChildren` .
The old method will be removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3070)*

**Comment by denis-anisimov** [comment]
Review status: 4 of 22 files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3070#-L-AfhuZ7IcD1s2Is8xX:-L-AjLEzpfdWW07b8mvK:byx1i8a) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

I would like do not touch the existing `@Id` functionality at all at the moment.
Once I start working on rewriting it I will modify the client-side code and remove the current `VirtualChildList`.

I prefer to avoid touching any unrelated functionality at the moment.
</blockquote></details>

The problem with `VirtualChildList` : if I reuse it on the server side then I will have to  significantly modify the `bindVirtualChildren`  method which I would like to avoid. 
Instead there is a new unrelated method `bindNewVirtualChildren` which doesn't collide anyhow with the existing code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3070)*

**Comment by denis-anisimov** [comment]
Review status: 4 of 22 files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3070#-L-AfhuZ7IcD1s2Is8xX:-L-AlFsKJBmf0HQSzYET:bf9sj1j) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

The problem with `VirtualChildList` : if I reuse it on the server side then I will have to  significantly modify the `bindVirtualChildren`  method which I would like to avoid. 
Instead there is a new unrelated method `bindNewVirtualChildren` which doesn't collide anyhow with the existing code.
</blockquote></details>

I see only one usage of the `VirtualChildrenList` class: from `ShadowRoot::insertVirtualChild`. And this method is used only from the `AttachTemplateChildRpcHandler` class.
This class handles responses from the client about any attaching functionality (`@Id` , template-in-template).
So in reality `VirtualChildrenList` exists only because of attaching functionality.

I'm going to remove all this code along with `VirtualChildrenList` and replace it with `NewVirtualChildrenList`.
And the old code on the client side will be just completely removed along with the feature.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3070)*

**Comment by caalador** [comment]
Reviewed 17 of 22 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3070)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3070#-L-AfhuZ7IcD1s2Is8xX:-L-Am-2y78SDKVsPkdO8:bao3rr7) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

I see only one usage of the `VirtualChildrenList` class: from `ShadowRoot::insertVirtualChild`. And this method is used only from the `AttachTemplateChildRpcHandler` class.
This class handles responses from the client about any attaching functionality (`@Id` , template-in-template).
So in reality `VirtualChildrenList` exists only because of attaching functionality.

I'm going to remove all this code along with `VirtualChildrenList` and replace it with `NewVirtualChildrenList`.
And the old code on the client side will be just completely removed along with the feature.
</blockquote></details>

And a bit off topic: I will remove `ShadowRoot::insertVirtualChild` and "attached" virtual children will be directly on the template itself instead of it's shadow root (even if it's not exactly correct from the DOM point of view).
I think on the server side it would be easier to deal with those children when their parent is the component itself, not its shadow root.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3070)*

**Pull request merged**
