### PR TITLE
Simplify HasValue

### PR DESCRIPTION
**Pull request by Legioth**
* Remove default implementations that require a component instance
* Remove interface methods that are only needed for the removed default
implementations
* Change ValueChangeEvent to an interface and a separate component event
implementation
* Simplify HasValue generics to not not depend on the component type

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/4003)

### CODE REVIEW

**Comment by Legioth** [comment]
Review status: 0 of 19 files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow/4003#-LAwtG2wArryhWx7-Dvz:-LAwtG2wArryhWx7-Dw-:blmz6fs) (no related file):*
Should not be merged until all components have been updated to use AbstractField

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4003)*

**Comment by denis-anisimov** [comment]
Reviewed 17 of 19 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java, line 973 at r2](https://reviewable.io/reviews/vaadin/flow/4003#-LB-foEN3nR9Ol3u5Pc4:-LB-foEN3nR9Ol3u5Pc5:b-k17w2h) ([raw file](https://github.com/vaadin/flow/blob/5ffb9a462a5992b1211a2758f3db775a7c243674/flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java#L973)):*
> ```
> event -> handleFieldValueChange(event)
> ```

Is it necessary to change the method reference to this lambda with changes in `addValueChangeListener` ?

---

*[flow-server/src/main/java/com/vaadin/flow/component/HasValue.java, line 194 at r2](https://reviewable.io/reviews/vaadin/flow/4003#-LB-iYXw46Q3ue-bqkIX:-LB-iYXw46Q3ue-bqkIY:b-2gs2ei) ([raw file](https://github.com/vaadin/flow/blob/abaf893f2e056ce8185356ebadc67b76649a2ca1/flow-server/src/main/java/com/vaadin/flow/component/HasValue.java#L194)):*
<details><summary><i alt="summary">Quoted 26 lines of code…</i></summary>

> ```
>         return getComponent().getElement().addPropertyChangeListener(
>                 getClientValuePropertyName(), event -> {
>                     /*
>                      * For the state tree, the default empty value of any
>                      * property is {@code null}, but for any component it might
>                      * be something else as defined by {@link #getEmptyValue()}.
>                      * (#3496)
>                      */
>                     final V oldValue;
>                     final V emptyValue = getEmptyValue();
>                     final V propertyChangeEventValue = (V) event.getOldValue();
>                     if (propertyChangeEventValue == null) {
>                         oldValue = emptyValue;
>                         if (Objects.equals(oldValue, getValue())) {
>                             // there is no value change in component API
>                             // perspective
>                             return;
>                         }
>                     } else {
>                         oldValue = propertyChangeEventValue;
>                     }
>                     listener.onComponentEvent(
>                             new ValueChangeEvent<>(getComponent(), this,
>                                     oldValue, event.isUserOriginated()));
>  
>                 });
> ```
</details>


Is this part just lost from the implementation ? (not moved anywhere)

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4003)*

**Comment by Legioth** [comment]
Review status: 16 of 22 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java, line 973 at r2](https://reviewable.io/reviews/vaadin/flow/4003#-LB-foEN3nR9Ol3u5Pc4:-LB0Nn0L61kptpM3eig4:b-b65zxj) ([raw file](https://github.com/vaadin/flow/blob/5ffb9a462a5992b1211a2758f3db775a7c243674/flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java#L973)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
> event -> handleFieldValueChange(event)
> ```

Is it necessary to change the method reference to this lambda with changes in `addValueChangeListener` ?
</blockquote></details>

Without this change, there are lots of `java.lang.invoke.LambdaConversionException: Type mismatch for lambda argument 0: class java.lang.Object is not convertible to interface com.vaadin.flow.component.HasValue$ValueChangeEvent` from various tests.

---

*[flow-server/src/main/java/com/vaadin/flow/component/HasValue.java, line 194 at r2](https://reviewable.io/reviews/vaadin/flow/4003#-LB-iYXw46Q3ue-bqkIX:-LB0O8YH6mugljeHgoD5:bamk3is) ([raw file](https://github.com/vaadin/flow/blob/abaf893f2e056ce8185356ebadc67b76649a2ca1/flow-server/src/main/java/com/vaadin/flow/component/HasValue.java#L194)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
>         return getComponent().getElement().addPropertyChangeListener(
>                 getClientValuePropertyName(), event -> {
>                     /*
>                      * For the state tree, the default empty value of any
>                      * property is {@code null}, but for any component it might
>                      * be something else as defined by {@link #getEmptyValue()}.
>                      * (#3496)
>                      */
>                     final V oldValue;
>                     final V emptyValue = getEmptyValue();
>                     final V propertyChangeEventValue = (V) event.getOldValue();
>                     if (propertyChangeEventValue == null) {
>                         oldValue = emptyValue;
>                         if (Objects.equals(oldValue, getValue())) {
>                             // there is no value change in component API
>                             // perspective
>                             return;
>                         }
>                     } else {
>                         oldValue = propertyChangeEventValue;
>                     }
>                     listener.onComponentEvent(
>                             new ValueChangeEvent<>(getComponent(), this,
>                                     oldValue, event.isUserOriginated()));
>  
>                 });
> ```

Is this part just lost from the implementation ? (not moved anywhere)
</blockquote></details>

Handled in a better way through `AbstractFieldSupport.setValue` that has been implemented separately

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4003)*

**Comment by denis-anisimov** [comment]
Reviewed 7 of 7 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4003)*

**Comment by denis-anisimov** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4003#-:-LB0XyqwEAEvzbhh7Aza:bnfp4nl)*

**Comment by gilberto-torrezan** [comment]
Review status: 18 of 29 files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow/4003#-LBK0jiX7zFbxgf5ytBX:-LBK0jiYAwcHfSHNgOPe:b61jiyt) (no related file):*
Shouldn't `getClientValuePropertyName` method go away?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4003)*

**Comment by ZheSun88** [comment]
:lgtm:

---

Reviewed 14 of 19 files at r1, 4 of 7 files at r3, 10 of 10 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4003#-:-LBLBLgp2Jl6zgBf73tn:bnfp4nl)*

**Pull request merged**
