### PR TITLE
Add JS API to get DOM Node by the server-side node id.

### PR DESCRIPTION
**Pull request by denis-anisimov**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3078)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
To be able to invoke JS API one needs:
- the node id (can be provided from the server side as a JS parameter) (`getNode().getId()`)
- the application id. It's returned by the `VaadinService::getMainDivId()` method (and also can be provided from the server side as a JS parameter) .

**Comment by ZheSun88** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3078)*

**Comment by gilberto-torrezan** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[flow-client/src/main/java/com/vaadin/client/ApplicationConnection.java, line 135 at r1](https://reviewable.io:443/reviews/vaadin/flow/3078#-L-6bn-5hty3jIAe_ANa:-L-6bn-5hty3jIAe_ANb:b-e7ths8) ([raw file](https://github.com/vaadin/flow/blob/3abf6bed62df7fa4532966a27fda68599ab49bd7/flow-client/src/main/java/com/vaadin/client/ApplicationConnection.java#L135)):*
> var tree = ap.@com.vaadin.client.ApplicationConnection::registry.@com.vaadin.client.Registry::getStateTree()();

Using `var` is painful to see to today standards, but I'm not sure if the GWT compiler supports `let` and `const`. Not a blocker.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3078)*

**Comment by gilberto-torrezan** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3078)*

**Comment by gilberto-torrezan** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/JsApiGetByIdIT.java, line 31 at r2](https://reviewable.io:443/reviews/vaadin/flow/3078#-L-6no72z5JyHJUQB39f:-L-6no72z5JyHJUQB39g:b-vd2ps3) ([raw file](https://github.com/vaadin/flow/blob/1c3dc0ebb45dbdb2aea9c9357845b52cc565ef8a/flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/JsApiGetByIdIT.java#L31)):*
> ```Java
>         open();
> 
>         WebElement target = findElement(By.id("source"));
> ```

Is this right? The `target` getting the id `source` and the `source` getting the id `target`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3078)*

**Comment by denis-anisimov** [comment]
Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/JsApiGetByIdIT.java, line 31 at r2](https://reviewable.io:443/reviews/vaadin/flow/3078#-L-6no72z5JyHJUQB39f:-L-6ta8fxDNyRpMIGTz0:b-sh0zzy) ([raw file](https://github.com/vaadin/flow/blob/1c3dc0ebb45dbdb2aea9c9357845b52cc565ef8a/flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/JsApiGetByIdIT.java#L31)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Is this right? The `target` getting the id `source` and the `source` getting the id `target`
</blockquote></details>

Thanks.
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3078)*

**Comment by gilberto-torrezan** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/JsApiGetByIdView.java, line 45 at r3](https://reviewable.io:443/reviews/vaadin/flow/3078#-L-6ulRT2fnn-UgkvUKx:-L-6ulRUGtqlACm38zLu:b-550mvo) ([raw file](https://github.com/vaadin/flow/blob/16815e05d5c0a0a7155cb3c7171fb0a69da1a516/flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/JsApiGetByIdView.java#L45)):*
> ```Java
>                 .runWhenAttached(ui -> ui.getPage().executeJavaScript(
>                         "window.jsApiConnector.jsFunction($0, this.$appId, $2)",
>                         target, appId.replaceAll("-\\d+$", ""),
> ```

You don't need to send the `appId.replaceAll(...)` parameter here anymore.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3078)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/JsApiGetByIdView.java, line 45 at r3](https://reviewable.io:443/reviews/vaadin/flow/3078#-L-6ulRT2fnn-UgkvUKx:-L-6vc09ZIo4aeFqd3H6:bpfugyi) ([raw file](https://github.com/vaadin/flow/blob/16815e05d5c0a0a7155cb3c7171fb0a69da1a516/flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/JsApiGetByIdView.java#L45)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

You don't need to send the `appId.replaceAll(...)` parameter here anymore.
</blockquote></details>

Right, thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3078)*

**Comment by gilberto-torrezan** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3078)*

**Pull request merged**
