### PR TITLE
test: Split pnpm and npm tests into separate modules

### PR DESCRIPTION
**Pull request by Artur-**

### CODE REVIEW

**Review by manolo — APPROVED** [review]

**Comment by manolo** [comment]
Failing in TC, it might be that order of the module matters in the build, wha happens if you move modules up to the place where the others were?

**Comment by Artur-** [comment]
Now it should work..

**Review by manolo — DISMISSED** [review]

**Comment by manolo** [comment]
Rebased with master so as sonar action is run

**Comment by manolo** [comment]
Rebased with master so as it runs sonar action

**Review by manolo — APPROVED** [review]

**Pull request merged**
