### PR TITLE
Remove open tags (<) from the UIDL when a comment is present

### LINKED ISSUE #4285: Sending "<!-- <script>" to the client breaks the whole view
Hey guys, we found a quite serious bug in Flow especially for data the user can input:

If you send "<!-- <script>" for example via template model to the client, the whole page is broken. 

To reproduce just clone the simple flow skeleton starter and apply the change below:

```diff --git a/src/main/java/com/vaadin/starter/skeleton/ExampleTemplate.java b/src/main/java/com/vaadin/starter/skeleton/ExampleTemplate.java
index eafedbc..3753118 100644
--- a/src/main/java/com/vaadin/starter/skeleton/ExampleTemplate.java
+++ b/src/main/java/com/vaadin/starter/skeleton/ExampleTemplate.java
@@ -23,7 +23,7 @@ public class ExampleTemplate extends PolymerTemplate<ExampleModel> {
 
     public ExampleTemplate() {
         // Set the initial value to the "value" property.
-        getModel().setValue("Not clicked");
+        getModel().setValue("<!-- <script>");
     }
 
     /*
```

### PR DESCRIPTION
**Pull request by gilberto-torrezan**
Fix #4285

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/4292)

### CODE REVIEW

**Comment by gilberto-torrezan** [comment]
Review status: 1 unresolved discussion, 0 of 1 LGTMs obtained

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow/4292#-LEyO9H01XSbV4uequue:-LEyO9H14I-KwLjF7vTS:bskj0yx) (no related file):*
Opened the PR to discuss about the implementation.
I personally don't like it, but I couldn't come up with a standalone regex to solve it.
Also I'm not sure if it makes sense to consider comment blocks in the UIDL (starting with `<!--` and ending with `-->`).

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4292)*

**Comment by Legioth** [comment]
Review status: 2 unresolved discussions, 0 of 1 LGTMs obtained

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow/4292#-LEyO9H01XSbV4uequue:-LEyT5bI3wvRTLtWgbCr:b-ll5h43) (no related file):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Opened the PR to discuss about the implementation.
I personally don't like it, but I couldn't come up with a standalone regex to solve it.
Also I'm not sure if it makes sense to consider comment blocks in the UIDL (starting with `<!--` and ending with `-->`).
</blockquote></details>

Can be significantly simplified by instead replacing all `<` chars regardless of the context. This would be safe as long as this is only used for the JSON structures that we're generating and not arbitrary JS.

---

*[flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java, line 886 at r1](https://reviewable.io/reviews/vaadin/flow/4292#-LEyTGyfCnsujAtm3cS_:-LEyTGyfCnsujAtm3cSa:bld3wa7) ([raw file](https://github.com/vaadin/flow/blob/f5ac503cc1d5ec381d6a659bc8c74f14db0b2fff/flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java#L886)):*
> ```Java
> 
>             builder.append(initialUIDLString.substring(commentIndex + 4)
>                     .replace("<", "&lt;"));
> ```

This is not the right replacement in a JS context. Should instead use `\x3C` which the JS string escape parser will replace with the expected `<` char in the actual string.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4292)*

**Comment by gilberto-torrezan** [comment]
Review status: all discussions resolved, 0 of 1 LGTMs obtained

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow/4292#-LEyO9H01XSbV4uequue:-LEyUfl90Phj1qPy_wCu:bb6un1j) (no related file):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

Can be significantly simplified by instead replacing all `<` chars regardless of the context. This would be safe as long as this is only used for the JSON structures that we're generating and not arbitrary JS.
</blockquote></details>

Done

---

*[flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java, line 886 at r1](https://reviewable.io/reviews/vaadin/flow/4292#-LEyTGyfCnsujAtm3cS_:-LEyUhTi-sAnN8dB_dkY:bb6un1j) ([raw file](https://github.com/vaadin/flow/blob/f5ac503cc1d5ec381d6a659bc8c74f14db0b2fff/flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java#L886)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

This is not the right replacement in a JS context. Should instead use `\x3C` which the JS string escape parser will replace with the expected `<` char in the actual string.
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4292)*

**Comment by Legioth** [comment]
Review status: 1 unresolved discussion, 0 of 1 LGTMs obtained

---

*[flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java, line 871 at r2](https://reviewable.io/reviews/vaadin/flow/4292#-LEyVQer1UgGmtUj_kBn:-LEyVQer1UgGmtUj_kBo:b-nidl7w) ([raw file](https://github.com/vaadin/flow/blob/82516c882064313f809db0461f7233e78899fc26/flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java#L871)):*
> ```Java
>         String initialUIDLString = JsonUtil.stringify(initialUIDL, indent);
> 
>         // "

**Comment by gilberto-torrezan** [comment]
Review status: all discussions resolved, 0 of 1 LGTMs obtained

---

*[flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java, line 871 at r2](https://reviewable.io/reviews/vaadin/flow/4292#-LEyVQer1UgGmtUj_kBn:-LEyWY8M1fY_HZtr-iE3:bb6un1j) ([raw file](https://github.com/vaadin/flow/blob/82516c882064313f809db0461f7233e78899fc26/flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java#L871)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

Comment is no longer correct since this now also protects against e.g. `</script>`  without any `<!--` anywhere.
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4292)*

**Comment by pekam** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: all discussions resolved, 0 of 1 LGTMs obtained, and 1 stale

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4292#-:-LEyYyu78cku2ePRnhMs:bnfp4nl)*

**Pull request merged**
