### PR TITLE
Add beforeEnterListeners before navigating to the target.

### PR DESCRIPTION
**Pull request by SomeoneToIgnore**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3996)

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow/3996#-LAwJ2xb07xuko7XsTM_:-LAwMRXR6rSEdcaH2XPv:bl15irv) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Which issue does it fix ?
</blockquote></details>

https://github.com/vaadin/flow/issues/3982

---

*[flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java, line 1034 at r1](https://reviewable.io/reviews/vaadin/flow/3996#-LAwIdDZ43Lb7RKl6y4U:-LAwMTSc3-vYHK3NumzQ:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/e53ef4901a69bca793de02355ba66c4488756c6b/flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java#L1034)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
> // Use router if it's active
> ```

Router is always active now so this comment is obsolete.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/3996)*

**Comment by denis-anisimov** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/3996#-:-LAwOT9eBNAk6eDTqERf:bnfp4nl)*

**Comment by denis-anisimov** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/3996#-:-LAwZcwK1i7SKkp69IUB:bnfp4nl)*

**Comment by denis-anisimov** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/3996#-:-LB-ZsSQBJCcBZqsXFTT:bnfp4nl)*

**Pull request merged**
