### PR TITLE
fix: Not fetch entire page if number of requested items is less

### PR DESCRIPTION
**Pull request by s76527**
## Description

fixed bug that caused grid with multi select mode to select not only the item that was clicked on, but also every item below

Fixes:
- [https://github.com/vaadin-component-factory/selection-grid-flow/issues/34](https://github.com/vaadin-component-factory/selection-grid-flow/issues/34)
- [https://github.com/vaadin-component-factory/selection-grid-flow/issues/16#issuecomment-809987669](https://github.com/vaadin-component-factory/selection-grid-flow/issues/16#issuecomment-809987669)

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

### CODE REVIEW

**Review by mshabarov — CHANGES_REQUESTED** [review]
@s76527 thank you for contribution! This fix looks reasonable and indeed shall solve the issues on add-ons side.
Please modify `DataCommunicatorTest::fetchFromProvider_limitLessThanPageSize_singleQuery` test as follows, since it gets obsolete and shall be updated due to this fix:

```java
    @Test
    public void fetchFromProvider_limitLessThanPageSize_singleQuery_fetchedLessThanPage() {
        AbstractDataProvider<Item, Object> dataProvider = createDataProvider(
                100);
        dataProvider = Mockito.spy(dataProvider);

        dataCommunicator.setDataProvider(dataProvider, null);
        Stream<Item> stream = dataCommunicator.fetchFromProvider(10, 42);

        ArgumentCaptor<Query> queryCaptor = ArgumentCaptor
                .forClass(Query.class);

        Mockito.verify(dataProvider).fetch(queryCaptor.capture());

        List<Item> items = stream.collect(Collectors.toList());
        Assert.assertEquals(42, items.size());

        Assert.assertEquals(IntStream.range(10, 52).mapToObj(Item::new)
                .collect(Collectors.toList()), items);

        Query query = queryCaptor.getValue();
        Assert.assertEquals(10, query.getOffset());
        Assert.assertEquals(42, query.getLimit());
        Assert.assertEquals(0, query.getPage());
        Assert.assertEquals(42, query.getPageSize());
    }
```

and then rebase/merge a current `master` to your branch.

**Comment by s76527** [comment]
so um, i didn't read your last comment and already committed the test modification and then merged with upstream
unfortunately, i didn't set up the git config on my PC so now @CLAassistant thinks there is an other user, who committed it

**Comment by mshabarov** [comment]
@s76527 ok, thanks. Could you update git config with your email, as described here https://docs.github.com/en/pull-requests/committing-changes-to-your-project/troubleshooting-commits/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user ?

**Comment by s76527** [comment]
I added the email address that was used in my local .gitconfig to my github profile and verified it. But it seems that the @CLAassistant doesn't take it into account.

**Comment by mshabarov** [comment]
Thanks @s76527 , I run the recheck of CLA, should be fine now. Lets wait until validation finishes.

**Comment by mshabarov** [comment]
The validation is currently failing because of swagger dependency issue in Flow. As soon as it's fixed in master, we need to merge master again.

**Comment by mshabarov** [comment]
@s76527 could you please merge latest `master` again? The problem with swagger has been fixed.

**Review by mshabarov — APPROVED** [review]

**Comment by mshabarov** [comment]
@s76527 our PR validation complains again about the license due to forked repo. We had to revert the script change supporting forked repos since it caused another issues. It would take time for us to find another solution. Do you have an opportunity to create a pull request without forked repo? Apologies for inconvenience.

**Comment by s76527** [comment]
@mshabarov I tried to create a new branch with the fix and push it to this repo to then have the option to make a PR on top of it, but i got 403 error on pushing. Other than that, I have no clue how to make a successful PR. It might be easier if you apply this fix by yourself with a quick commit.

**Comment by mshabarov** [comment]
@s76527 ok, I see. Yep, I'll create a PR by myself and mention you as a contributor.

**Pull request closed without merging**
