### PR TITLE
Fire an event on removeProperty

### LINKED ISSUE #3994: Element.removeProperty should fire PropertyChangeEvent if property was removed

### PR DESCRIPTION
**Pull request by denis-anisimov**
Fixes #3994

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/4037)

### CODE REVIEW

**Comment by caalador** [comment]
[14:23:09][Step 4/6] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project flow-server: Compilation failure: Compilation failure:
[14:23:09][Step 4/6] [ERROR] /opt/agent/work/655b228800368b4e/flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/ElementAttributeMap.java:[87,19] remove(java.lang.String) in com.vaadin.flow.internal.nodefeature.ElementAttributeMap cannot override remove(java.lang.String) in com.vaadin.flow.internal.nodefeature.NodeMap
[14:23:09][Step 4/6] [ERROR] return type java.lang.Object is not compatible with java.io.Serializable
[14:23:09][Step 4/6] [ERROR] /opt/agent/work/655b228800368b4e/flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/ElementAttributeMap.java:[86,5] method does not override or implement a method from a supertype

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4037#-:-LBURCkN9_X-FPDKktdM:b-d7ixkl)*

**Comment by denis-anisimov** [comment]
Done

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4037#-:-LBUklIH8hDVBXwiwX4b:bb6un1j)*

**Comment by caalador** [comment]
10 `NodeMapTest`s fail on `Node is not valid as an element`.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4037#-:-LBUoNpQ0lDAzdPV3m1L:b3hdwdc)*

**Comment by denis-anisimov** [comment]
Done

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4037#-:-LBUrPQG7vpnoqnYjt3L:bb6un1j)*

**Comment by caalador** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/NodeMapTest.java, line 40 at r1](https://reviewable.io/reviews/vaadin/flow/4037#-LBUu5Qs-m2d4efT9Ymt:-LBUu5Qs-m2d4efT9Ymu:b-bml1ya) ([raw file](https://github.com/vaadin/flow/blob/42905ef4630919031fc18c6d88b3595ce177af31/flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/NodeMapTest.java#L40)):*
> ```Java
> import elemental.json.JsonValue;
> 
> // Using ElementProperties since it closely maps to the underlying map
> ```

Comment should be updated to reflect the change. e.g. `Using ElementStyleProperties since...`

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4037)*

**Comment by denis-anisimov** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/NodeMapTest.java, line 40 at r1](https://reviewable.io/reviews/vaadin/flow/4037#-LBUu5Qs-m2d4efT9Ymt:-LBUuo4fD4IT21sHp2qn:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/42905ef4630919031fc18c6d88b3595ce177af31/flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/NodeMapTest.java#L40)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Comment should be updated to reflect the change. e.g. `Using ElementStyleProperties since...`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4037)*

**Comment by caalador** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4037#-:-LBUv-6K6LmqYA9iNo5D:bnfp4nl)*

**Pull request merged**
