### PR TITLE
Use PropertyChangeListener in generated components

### PR DESCRIPTION
**Pull request by pekam**
In case of property changes, generated listeners don't just wait for the asynchronous dom-events to occur but instead use `PropertyChangeListeners` which take care of firing the events immediately when the property is changed from server-side. This is how `HasValue::addValueChangeListener` works already.

Also, the property change events now always contain a getter for the changed property.

Because of these changes the property change events no longer contain `EventData` from the client-side.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3620)

### CODE REVIEW

**Comment by gilberto-torrezan** [comment]
Reviewed 1 of 26 files at r1, 1 of 1 files at r2.
Review status: 2 of 26 files reviewed at latest revision, 6 unresolved discussions.

---

*[flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/ComponentGenerator.java, line 1453 at r1](https://reviewable.io:443/reviews/vaadin/flow/3620#-L6RBKikqu8HtcpQGwC0-r1-1453:-L6RYy-j6YeksB6lp8_i:bhwzwmr) ([raw file](https://github.com/vaadin/flow/blob/3b9e731a3a9a55551599f40bbb2fa9510703f628/flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/ComponentGenerator.java#L1453)):*
> ```Java
>         }
> 
>         else {
> ```

+1, formatting issue here

---

*[flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/ComponentGenerator.java, line 740 at r2](https://reviewable.io:443/reviews/vaadin/flow/3620#-L6RUkFEtvcAyP_tkjuL:-L6RUkFEtvcAyP_tkjuM:bopgg7m) ([raw file](https://github.com/vaadin/flow/blob/097fb7a50c0d251b22e7e99678d2954cd46292d0/flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/ComponentGenerator.java#L740)):*
> ```Java
>             String basePackage, String licenseNote) {
> 
>         propertyToGetterMap.clear();
> ```

That is the first time the generator gets a state related to a specific class (it was stateless so far, allowing generation of multiple classes in parallel at the same time, for instance).

I suggest we keep it stateless. To achieve it, you can do one of these things:

1 - get the getters using the Roaster API `javaClass.getMethod(name)`, removing the need of the map, or
2 - Create the map inside the scope of the method and pass it as a parameter to all methods that needs to read from or write to it

---

*[flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/ComponentGenerator.java, line 1351 at r2](https://reviewable.io:443/reviews/vaadin/flow/3620#-L6RX6aIY03f3tb9iJdd:-L6RX6aIY03f3tb9iJde:byqoq00) ([raw file](https://github.com/vaadin/flow/blob/097fb7a50c0d251b22e7e99678d2954cd46292d0/flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/ComponentGenerator.java#L1351)):*
> ```Java
>                     eventJavaApiName.length() - 1);
> 
>             propertyNameCamelCase = eventJavaApiName.replace("Change", "");
> ```

This is dangerous. Imagine something weird like a property called "change" - we would have a `addChangeChangeListener`, and this replacement would make it `addListener`.

So I suggest removing the text by index. You know at this point that `eventJavaApiName` ends with `Change`, so you can remove the last 6 characters. Also, this is way faster than String matching.

---

*[flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/ComponentGenerator.java, line 1375 at r2](https://reviewable.io:443/reviews/vaadin/flow/3620#-L6RYH0kUzgRtjnl_fOW:-L6RYH0kUzgRtjnl_fOX:b-l9o7py) ([raw file](https://github.com/vaadin/flow/blob/097fb7a50c0d251b22e7e99678d2954cd46292d0/flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/ComponentGenerator.java#L1375)):*
> ```Java
>                         "a {@link Registration} for removing the event listener");
> 
>         if (propertyNameCamelCase != null) {
> ```

I suggest declaring a boolean like you did bellow `isPropertyChange = propertyNameCamelCase != null;`. It makes the code clearer.

---

*[flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/ComponentGenerator.java, line 1422 at r2](https://reviewable.io:443/reviews/vaadin/flow/3620#-L6RYZpt4spscuKsmNvs:-L6RYZpt4spscuKsmNvt:bhct6pq) ([raw file](https://github.com/vaadin/flow/blob/097fb7a50c0d251b22e7e99678d2954cd46292d0/flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/ComponentGenerator.java#L1422)):*
> ```Java
>         eventConstructor.addParameter("boolean", "fromClient");
> 
>         if (isPropertyChange) {
> ```

This if/else block is big enough to consider extracting to two separate methods.

---

*[flow-components-parent/flow-code-generator-api/src/test/java/com/vaadin/generator/ComponentGeneratorTest.java, line 363 at r2](https://reviewable.io:443/reviews/vaadin/flow/3620#-L6RZkTG6Li1cDiov6BK:-L6RZkTG6Li1cDiov6BL:by705e2) ([raw file](https://github.com/vaadin/flow/blob/097fb7a50c0d251b22e7e99678d2954cd46292d0/flow-components-parent/flow-code-generator-api/src/test/java/com/vaadin/generator/ComponentGeneratorTest.java#L363)):*
> ```Java
> 
>         Assert.assertTrue("Custom event class was not found.",
>                 generatedClass.contains(
> ```

You can replace all `Assert.assertTrue(..., generatedClass.contains(...))` with:
```
Assert.assertThat(generatedClass, CoreMatchers.containsString(...));
```

When you use in that way, the error message is way better to debug.
(I know, most tests in this class don't use it - but we should start from somewhere)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3620)*

**Comment by gilberto-torrezan** [comment]
Reviewed 24 of 26 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3620)*

**Comment by pekam** [comment]
Review status: 24 of 26 files reviewed at latest revision, 6 unresolved discussions.

---

*[flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/ComponentGenerator.java, line 1453 at r1](https://reviewable.io:443/reviews/vaadin/flow/3620#-L6RBKikqu8HtcpQGwC0-r1-1453:-L6Rk23HJT_hPdd9RF3n:b-quts7p) ([raw file](https://github.com/vaadin/flow/blob/3b9e731a3a9a55551599f40bbb2fa9510703f628/flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/ComponentGenerator.java#L1453)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

+1, formatting issue here
</blockquote></details>

I don't see any formatting issue

---

*[flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/ComponentGenerator.java, line 740 at r2](https://reviewable.io:443/reviews/vaadin/flow/3620#-L6RUkFEtvcAyP_tkjuL:-L6ReumefH4U8aYtAXPC:b-jfmyf5) ([raw file](https://github.com/vaadin/flow/blob/097fb7a50c0d251b22e7e99678d2954cd46292d0/flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/ComponentGenerator.java#L740)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

That is the first time the generator gets a state related to a specific class (it was stateless so far, allowing generation of multiple classes in parallel at the same time, for instance).

I suggest we keep it stateless. To achieve it, you can do one of these things:

1 - get the getters using the Roaster API `javaClass.getMethod(name)`, removing the need of the map, or
2 - Create the map inside the scope of the method and pass it as a parameter to all methods that needs to read from or write to it
</blockquote></details>

I would have used the option 1 in the first place, but it's too hard with the different prefixes and possible type suffices. I executed plan 2 even though it is ugly.

---

*[flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/ComponentGenerator.java, line 1351 at r2](https://reviewable.io:443/reviews/vaadin/flow/3620#-L6RX6aIY03f3tb9iJdd:-L6RiWOBqxDgvbJ9Wyk3:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/097fb7a50c0d251b22e7e99678d2954cd46292d0/flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/ComponentGenerator.java#L1351)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

This is dangerous. Imagine something weird like a property called "change" - we would have a `addChangeChangeListener`, and this replacement would make it `addListener`.

So I suggest removing the text by index. You know at this point that `eventJavaApiName` ends with `Change`, so you can remove the last 6 characters. Also, this is way faster than String matching.
</blockquote></details>

Done.

---

*[flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/ComponentGenerator.java, line 1375 at r2](https://reviewable.io:443/reviews/vaadin/flow/3620#-L6RYH0kUzgRtjnl_fOW:-L6RiZdsQ-ovOR0LkOo1:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/097fb7a50c0d251b22e7e99678d2954cd46292d0/flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/ComponentGenerator.java#L1375)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

I suggest declaring a boolean like you did bellow `isPropertyChange = propertyNameCamelCase != null;`. It makes the code clearer.
</blockquote></details>

Done.

---

*[flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/ComponentGenerator.java, line 1422 at r2](https://reviewable.io:443/reviews/vaadin/flow/3620#-L6RYZpt4spscuKsmNvs:-L6Rjoo5lHcoyYTJ19jX:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/097fb7a50c0d251b22e7e99678d2954cd46292d0/flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/ComponentGenerator.java#L1422)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

This if/else block is big enough to consider extracting to two separate methods.
</blockquote></details>

Done.

---

*[flow-components-parent/flow-code-generator-api/src/test/java/com/vaadin/generator/ComponentGeneratorTest.java, line 363 at r2](https://reviewable.io:443/reviews/vaadin/flow/3620#-L6RZkTG6Li1cDiov6BK:-L6Rn0Y0htYjRse09sxg:b-5n3ble) ([raw file](https://github.com/vaadin/flow/blob/097fb7a50c0d251b22e7e99678d2954cd46292d0/flow-components-parent/flow-code-generator-api/src/test/java/com/vaadin/generator/ComponentGeneratorTest.java#L363)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

You can replace all `Assert.assertTrue(..., generatedClass.contains(...))` with:
```
Assert.assertThat(generatedClass, CoreMatchers.containsString(...));
```

When you use in that way, the error message is way better to debug.
(I know, most tests in this class don't use it - but we should start from somewhere)
</blockquote></details>

Done for my new methods

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3620)*

**Comment by gilberto-torrezan** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3620)*

**Pull request merged**
