### PR TITLE
Show correct servlet/Flow version and publish it to JS

### LINKED ISSUE #2881: Version.getFullVersion always returns "9.9.9.INTERNAL-DEBUG-BUILD"
It should return the Flow version

### PR DESCRIPTION
**Pull request by Artur-**
Removes confusing mentions of a "widget set" version

Fixes #2881

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/2927)

### CODE REVIEW

**Comment by caalador** [comment]
Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-server/src/main/java/com/vaadin/server/Version.java, line 16 at r1](https://reviewable.io:443/reviews/vaadin/flow/2927#-Kz3pn9SKk4AdzgTK3wC:-Kz3pn9SKk4AdzgTK3wD:bar76tg) ([raw file](https://github.com/vaadin/flow/blob/6575173ceb33019a45d0c6211bbc349e797f657d/flow-server/src/main/java/com/vaadin/server/Version.java#L16)):*
> ```Java
>  * the License.
>  */
> package com.vaadin.server;
> ```

Why is this moved to the server package from the shared package as it is sill used from the client module?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2927)*

**Comment by torok-peter** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2927)*

**Comment by Artur-** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-server/src/main/java/com/vaadin/server/Version.java, line 16 at r1](https://reviewable.io:443/reviews/vaadin/flow/2927#-Kz3pn9SKk4AdzgTK3wC:-Kz47Jq0eoe-DwzScaW4:bhorv7c) ([raw file](https://github.com/vaadin/flow/blob/6575173ceb33019a45d0c6211bbc349e797f657d/flow-server/src/main/java/com/vaadin/server/Version.java#L16)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Why is this moved to the server package from the shared package as it is sill used from the client module?
</blockquote></details>

It's no longer used by the client module as the client module is unable to load the version property file

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2927)*

**Comment by knoobie** [comment]
OT: Would be nice, if this can be deactivated with a Server API. (at least for flow) 
We had some security audits where on of the open points was that an attacker can easily find the used Vaadin Framework Version and search for security bugs.

**Comment by caalador** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[flow-client/src/main/java/com/vaadin/client/communication/AtmospherePushConnection.java, line 27 at r1](https://reviewable.io:443/reviews/vaadin/flow/2927#-Kz7ZglklkSnNBTsPnyu:-Kz7ZglklkSnNBTsPnyv:bcte537) ([raw file](https://github.com/vaadin/flow/blob/6575173ceb33019a45d0c6211bbc349e797f657d/flow-client/src/main/java/com/vaadin/client/communication/AtmospherePushConnection.java#L27)):*
> ```Java
> import com.vaadin.client.ResourceLoader.ResourceLoadEvent;
> import com.vaadin.client.ResourceLoader.ResourceLoadListener;
> import com.vaadin.server.Version;
> ```

Remove un-used import.

---

*[flow-client/src/main/java/com/vaadin/client/communication/MessageSender.java, line 20 at r1](https://reviewable.io:443/reviews/vaadin/flow/2927#-Kz7ZoyoU0AFbNoYJXbP:-Kz7ZoyoU0AFbNoYJXbQ:b4kmfe3) ([raw file](https://github.com/vaadin/flow/blob/6575173ceb33019a45d0c6211bbc349e797f657d/flow-client/src/main/java/com/vaadin/client/communication/MessageSender.java#L20)):*
> ```Java
> import com.vaadin.client.Console;
> import com.vaadin.client.Registry;
> import com.vaadin.server.Version;
> ```

remove un-used import

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2927)*

**Comment by Artur-** [comment]
Thanks, I was going to enable this only for production mode but apparently forgot it. Fixed now

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2927#-:-Kz7sOnUyeQcBLgRZu12:b-bt335u)*

**Comment by Artur-** [comment]
Where "production mode" obviously means "development mode"

---

Review status: 6 of 12 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2927#-:-Kz81OHhjIKO0IaZS1Yy:b2crvju)*

**Comment by caalador** [comment]
Reviewed 7 of 7 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2927)*

**Pull request merged**
