### PR TITLE
Rework template parser to return template URI and use it in logger

### LINKED ISSUE #3265: Error message about missing element for id mapping should mention the name of the template
Right now, having an `@Id` without a corresponding element in the shows a message like `There is no element with id='foobar' in the template file. Cannot map it using @Id`. Fixing this issue would be easier if the error message would also mention the name of the offending template file.

### PR DESCRIPTION
**Pull request by denis-anisimov**
Fixes #3265

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3719)

### CODE REVIEW

**Comment by caalador** [comment]
Compilation failure: Compilation failure:

[14:18:03][Step 4/6] [ERROR] /opt/agent/work/655b228800368b4e/flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/dependencies/FrontendInlineApiView.java:[34,23] incompatible types: bad return type in lambda expression
[14:18:03][Step 4/6] [ERROR] org.jsoup.nodes.Document cannot be converted to com.vaadin.flow.component.polymertemplate.TemplateParser.TemplateData

[14:18:03][Step 4/6] [ERROR] /opt/agent/work/655b228800368b4e/flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/LazyLoadingTemplateView.java:[40,46] incompatible types: bad return type in lambda expression
[14:18:03][Step 4/6] [ERROR] org.jsoup.nodes.Document cannot be converted to com.vaadin.flow.component.polymertemplate.TemplateParser.TemplateData

---

Review status: 0 of 11 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3719#-:-L7xk19RYqqlbUOG1IRP:b3jqy4r)*

**Comment by denis-anisimov** [comment]
Ops.....
Thanks !

---

Review status: 0 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3719#-:-L7xnkz_esgzl7OqX9Ag:bduapyv)*

**Comment by caalador** [comment]
Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/TemplateDataAnalyzer.java, line 219 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3719#-L7xykDy9vJJlj-nnBkL:-L7xykDy9vJJlj-nnBkM:bthk8m5) ([raw file](https://github.com/vaadin/flow/blob/32cb97dba9b996cc8562228f02327810208f4375/flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/TemplateDataAnalyzer.java#L219)):*
> ```Java
>                     "Class '%s' contains field '%s' annotated with @Id('%s'). "
>                             + "Corresponding element was found in a sub template, "
>                             + "for which injection is not supported. The template URI is '%s'",
> ```

Which template uri is this. the main or the sub template?

---

*[flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/TemplateDataAnalyzer.java, line 287 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3719#-L7xyv6s0q58zimT94iA:-L7xyv6s0q58zimT94iB:b-ta0slk) ([raw file](https://github.com/vaadin/flow/blob/32cb97dba9b996cc8562228f02327810208f4375/flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/TemplateDataAnalyzer.java#L287)):*
> ```Java
>                 throw new IllegalStateException(String.format(
>                         "Couldn't parse the template '%s': "
>                                 + "sub-templates are not supported. Sub-template found: \n",
> ```

The \n should be changed to %s so we add the element.toString to the message.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3719)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/TemplateDataAnalyzer.java, line 219 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3719#-L7xykDy9vJJlj-nnBkL:-L7yIqdA2HgjuaY7OTgC:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/32cb97dba9b996cc8562228f02327810208f4375/flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/TemplateDataAnalyzer.java#L219)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Which template uri is this. the main or the sub template?
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/TemplateDataAnalyzer.java, line 287 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3719#-L7xyv6s0q58zimT94iA:-L7yJ22NDEaF4IXEejOZ:b-36lps) ([raw file](https://github.com/vaadin/flow/blob/32cb97dba9b996cc8562228f02327810208f4375/flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/TemplateDataAnalyzer.java#L287)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

The \n should be changed to %s so we add the element.toString to the message.
</blockquote></details>

Forgot to add `%s` , thanks.
But `\n` is not replaced because the sun template content will be multiline string.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3719)*

**Comment by caalador** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3719#-:-L7yL5QGAQ0IKwwPhsSW:bnfp4nl)*

**Pull request merged**
