### PR TITLE
Add primitive default data support on evendata

### PR DESCRIPTION
**Pull request by mikotin**
Added primitive checking on event data value decoding, so that primitive values get default values instead of null.

Fixes issue #4112

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/4132)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[flow-server/src/main/java/com/vaadin/flow/component/ComponentEventBus.java, line 26 at r1](https://reviewable.io/reviews/vaadin/flow/4132#-LCma0oUDLDJZ98APnTR:-LCma0oUDLDJZ98APnTS:b-bnleq5) ([raw file](https://github.com/vaadin/flow/blob/d817fac04f0895c5245d6916930efb3898297606/flow-server/src/main/java/com/vaadin/flow/component/ComponentEventBus.java#L26)):*
> ```
> import javafx.util.Pair;
> ```

Is `javafx` part of JDK nowadays ?
Not sure that this is good to use `javafx` in the code which should work without it just because of this class.

---

*[flow-server/src/main/java/com/vaadin/flow/component/ComponentEventBusUtil.java, line 108 at r1](https://reviewable.io/reviews/vaadin/flow/4132#-LCmakbp7wA6vD6HwoP_:-LCmakbp7wA6vD6HwoPa:b-n1e9n8) ([raw file](https://github.com/vaadin/flow/blob/d817fac04f0895c5245d6916930efb3898297606/flow-server/src/main/java/com/vaadin/flow/component/ComponentEventBusUtil.java#L108)):*
> ```
>                     new Pair<>(ReflectTools.convertPrimitiveType(p.getType()),
>                             p.getType().isPrimitive()));
> ```

Are you sure that you need `boolean` in the `Pair` instance and `Pair` instance at all if you may ask `p.getType.isPrimitive()`  for the type which may be asked directly for `isPrimitive()` ?

May be do not call `ReflectTools.convertPrimitiveType()` here but do it where the method is called since you anyway have changed the return value ?

---

*[flow-server/src/main/java/com/vaadin/flow/internal/JsonCodec.java, line 233 at r1](https://reviewable.io/reviews/vaadin/flow/4132#-LCmcNNY92nFdq0g--_Y:-LCmcNNY92nFdq0g--_Z:bh29hcz) ([raw file](https://github.com/vaadin/flow/blob/d817fac04f0895c5245d6916930efb3898297606/flow-server/src/main/java/com/vaadin/flow/internal/JsonCodec.java#L233)):*
> ```
>     public static <T> T decodeAs(JsonValue json, Class<T> type, boolean allowNull) {
>         assert json != null;
> ```

What does it return if `null` is not allowed ?

Is it possible do not create a new method but reuse existing one and check `isPrimitive` here with the proper logic ?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4132)*

**Comment by Legioth** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/component/ComponentEventBus.java, line 26 at r1](https://reviewable.io/reviews/vaadin/flow/4132#-LCma0oUDLDJZ98APnTR:-LCmdRDm1JMfahCAyLnG:b3yyikt) ([raw file](https://github.com/vaadin/flow/blob/d817fac04f0895c5245d6916930efb3898297606/flow-server/src/main/java/com/vaadin/flow/component/ComponentEventBus.java#L26)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
> import javafx.util.Pair;
> ```

Is `javafx` part of JDK nowadays ?
Not sure that this is good to use `javafx` in the code which should work without it just because of this class.
</blockquote></details>

`javafx` will be dropped in Java 11.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4132)*

**Comment by mikotin** [comment]
Review status: 3 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[flow-server/src/main/java/com/vaadin/flow/internal/JsonCodec.java, line 233 at r1](https://reviewable.io/reviews/vaadin/flow/4132#-LCmcNNY92nFdq0g--_Y:-LDB752vBTmfinB8uwqz:b-axotqc) ([raw file](https://github.com/vaadin/flow/blob/d817fac04f0895c5245d6916930efb3898297606/flow-server/src/main/java/com/vaadin/flow/internal/JsonCodec.java#L233)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
>     public static <T> T decodeAs(JsonValue json, Class<T> type, boolean allowNull) {
>         assert json != null;
> ```

What does it return if `null` is not allowed ?

Is it possible do not create a new method but reuse existing one and check `isPrimitive` here with the proper logic ?
</blockquote></details>

If null is not allowed and value is null, then it will fall back to get default data, like false for boolean / Boolean.

Can't really do all the conversion logic within the decodeAs -method,  for it would either need:
- casting to primitive value, which will throw something like:  java.lang.ClassCastException: Cannot cast java.lang.Integer to int
- Solving the non-primitive class from primitive class and returning that, but that it is against generics of the method

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4132)*

**Comment by denis-anisimov** [comment]
Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/internal/JsonCodec.java, line 233 at r1](https://reviewable.io/reviews/vaadin/flow/4132#-LCmcNNY92nFdq0g--_Y:-LDBNuKr756MJysADsME:buhmu7z) ([raw file](https://github.com/vaadin/flow/blob/d817fac04f0895c5245d6916930efb3898297606/flow-server/src/main/java/com/vaadin/flow/internal/JsonCodec.java#L233)):*
> casting to primitive value, which will throw something like: java.lang.ClassCastException: Cannot cast java.lang.Integer to int

of course

> Solving the non-primitive class from primitive class and returning that, but that it is against generics of the method

Why ? (`ReflectTools.convertPrimitiveType` )
The method returns a value.
A primitive value is always castable to its boxed type. So I don't see any issue with that.
You will need to cast the result to `T` (with a warning from a compiler) but that should be fine, isn't it ?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4132)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4132)*

**Comment by mikotin** [comment]
Review status: 3 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-server/src/main/java/com/vaadin/flow/internal/JsonCodec.java, line 233 at r1](https://reviewable.io/reviews/vaadin/flow/4132#-LCmcNNY92nFdq0g--_Y:-LDGMdGQCwE439MvHkSa:b-ryo77) ([raw file](https://github.com/vaadin/flow/blob/d817fac04f0895c5245d6916930efb3898297606/flow-server/src/main/java/com/vaadin/flow/internal/JsonCodec.java#L233)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> casting to primitive value, which will throw something like: java.lang.ClassCastException: Cannot cast java.lang.Integer to int

of course

> Solving the non-primitive class from primitive class and returning that, but that it is against generics of the method

Why ? (`ReflectTools.convertPrimitiveType` )
The method returns a value.
A primitive value is always castable to its boxed type. So I don't see any issue with that.
You will need to cast the result to `T` (with a warning from a compiler) but that should be fine, isn't it ?
</blockquote></details>

Changed as requested, also added tests for new supported types

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4132)*

**Comment by denis-anisimov** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4132#-:-LDGdt1h0tEtbYfXRpMA:bnfp4nl)*

**Pull request merged**
