### PR TITLE
Add RPC support for composite components

### LINKED ISSUE #4198: Can't use as Composite<IronList>
@heruan commented on [Tue May 29 2018](https://github.com/vaadin/vaadin-iron-list-flow/issues/40)

Using the component as generic type of `Composite` results in this exception:

```
java.lang.IllegalStateException: Neither class 'MyList' nor its super classes declare
event handler method 'setRequestedRange'
```

Use case:

```java
abstract ListLayout<T, L extends Component & HasDataProvider<T>> extends Composite<L> {}

class MyList extends ListLayout<Person, IronList<Person>> {}
```

---

@Legioth commented on [Tue May 29 2018](https://github.com/vaadin/vaadin-iron-list-flow/issues/40#issuecomment-392733195)

I think this is a generic Flow issue related to finding `$server` methods from composite content classes.

### PR DESCRIPTION
**Pull request by heruan**
Fixes #4198

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/4298)

### CODE REVIEW

**Comment by Legioth** [comment]
Review status: 1 unresolved discussion, 0 of 1 LGTMs obtained

---

*[flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/PublishedServerEventHandlerRpcHandler.java, line 139 at r1](https://reviewable.io/reviews/vaadin/flow/4298#-LFGfg0FCBrbNKjiieJI:-LFGfg0FCBrbNKjiieJJ:b3qohna) ([raw file](https://github.com/vaadin/flow/blob/21bcbb83e52f8eb8f4c77493ece651d59a9b34c0/flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/PublishedServerEventHandlerRpcHandler.java#L139)):*
> ```Java
>         } else if (methods.size() == 1) {
>             invokeMethod(instance, methods.get(0), args);
>         } else if (Composite.class.equals(clazz)) {
> ```

This assumes there's only one level of composites. It's also possible (but not very common) that a composite is created out of another composite.

I'm also not sure if we should also support `@ClientCallable` methods on the composite class itself, and in that case also choose what to do if both the composite and the content defines a method method with the same name.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4298)*

**Comment by heruan** [comment]
Review status: 1 unresolved discussion, 0 of 1 LGTMs obtained

---

*[flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/PublishedServerEventHandlerRpcHandler.java, line 139 at r1](https://reviewable.io/reviews/vaadin/flow/4298#-LFGfg0FCBrbNKjiieJI:-LFGluzQ4wlc1elBnLUs:b57svmf) ([raw file](https://github.com/vaadin/flow/blob/21bcbb83e52f8eb8f4c77493ece651d59a9b34c0/flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/PublishedServerEventHandlerRpcHandler.java#L139)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

This assumes there's only one level of composites. It's also possible (but not very common) that a composite is created out of another composite.

I'm also not sure if we should also support `@ClientCallable` methods on the composite class itself, and in that case also choose what to do if both the composite and the content defines a method method with the same name.
</blockquote></details>

My intention here is to let the handler check if there's a method on the `Composite` first, so if the developer is importing its own client code there's still a chance to catch the call. I didn't consider multiple level of `Composite`s though, I'll try to figure something out.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4298)*

**Comment by heruan** [comment]
Now this supports composites of composites, with this flow:

1. The instance class has the method: invoke that.
2. The instance is a `Composite`, try to invoke on the content.
3. If it fails, step up in the hierarchy.

**Comment by Legioth** [comment]
Using any except for control flow sounds wrong to me. What about splitting out a separate method that finds a method to invoke (potentially recursively)?

---

Review status: 2 unresolved discussions, 0 of 1 LGTMs obtained

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4298#-:-LFH7_9n6xeo_OArW5G-:bnpp53k)*

**Comment by heruan** [comment]
Now a new method looks for the target method in the class hierarchy; if not found and `instance` is a `Composite` it starts over with the composite content.

**Comment by heruan** [comment]
Do you feel this needs other improvements, or tests?

**Comment by Legioth** [comment]
Seems fine to me, but won't merge this right away to reduce the risk of further regressions during the release candidate period.

**Comment by denis-anisimov** [comment]
:lgtm:

---

Review status: all discussions resolved, 0 of 1 LGTMs obtained, and 1 stale

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4298#-:-LG4AYAO3bnTvdT7bChr:bnfp4nl)*

**Pull request merged**
