### PR TITLE
Scan Synchronized annotation for all superclasses and superinterfaces

### PR DESCRIPTION
**Pull request by denis-anisimov**
Fix for vaadin-text-field-flow/issues/4

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/2811)

### CODE REVIEW

**Comment by Legioth** [comment]
#4 does not seem to be the right ticket. Maybe you're referring to #4 in some other repository?

**Comment by gilberto-torrezan** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[flow-server/src/main/java/com/vaadin/ui/ComponentMetaData.java, line 153 at r1](https://reviewable.io:443/reviews/vaadin/flow/2811#-KxmTCdSjKe1lt3mCQbD:-KxmTCdSjKe1lt3mCQbE:bnzvalm) ([raw file](https://github.com/vaadin/flow/blob/505091705380646e6b4f36033596c22b1ea18942/flow-server/src/main/java/com/vaadin/ui/ComponentMetaData.java#L153)):*
> ```Java
>      * Framework internal data, thus package-private.
>      *
>      * @return a set of information objects about properties to be synchronized
> ```

`@return a set of ...` ->  `@return a collection of ...`

Since it's an internal API, it's not a blocker

---

*[flow-server/src/test/java/com/vaadin/ui/ComponentMetaDataTest.java, line 28 at r1](https://reviewable.io:443/reviews/vaadin/flow/2811#-KxmU5Lw0eHhQv8SF5xV:-KxmU5Lw0eHhQv8SF5xW:b1pnszv) ([raw file](https://github.com/vaadin/flow/blob/505091705380646e6b4f36033596c22b1ea18942/flow-server/src/test/java/com/vaadin/ui/ComponentMetaDataTest.java#L28)):*
> ```Java
> import com.vaadin.ui.event.Synchronize;
> 
> public class ComponentMetaDataTest {
> ```

I suggest also adding a test where one method of the super and the sub class has the `@Synchronize` annotation at the same time.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2811)*

**Comment by gilberto-torrezan** [comment]
Review status: 5 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-components-parent/demo-flow-components/src/test/java/com/vaadin/flow/demo/views/CheckboxIT.java, line 65 at r2](https://reviewable.io:443/reviews/vaadin/flow/2811#-KxmWJ2jxH50KfkzDraI:-KxmWJ2jxH50KfkzDraJ:b47e259) ([raw file](https://github.com/vaadin/flow/blob/21c56027de8ee370b8718ef74cdd6b210bfdeacc/flow-components-parent/demo-flow-components/src/test/java/com/vaadin/flow/demo/views/CheckboxIT.java#L65)):*
> ```Java
>         WebElement reset = layout.findElement(By.id("reset-indeterminate"));
>         scrollIntoViewAndClick(reset);
>         waitUntil(driver -> checkbox.getAttribute("indeterminate") != null);
> ```

Ok, the problem here is the `attribute` thing - can you try to run `executeScript("return arguments[0].checked;", checkbox);` to see if it is `null/false` ? That measures the value of the property, not the attribute.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2811)*

**Comment by gilberto-torrezan** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2811)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-components-parent/demo-flow-components/src/test/java/com/vaadin/flow/demo/views/CheckboxIT.java, line 65 at r2](https://reviewable.io:443/reviews/vaadin/flow/2811#-KxmWJ2jxH50KfkzDraI:-KxmXARZDbNm7GdIiper:bdh28wi) ([raw file](https://github.com/vaadin/flow/blob/21c56027de8ee370b8718ef74cdd6b210bfdeacc/flow-components-parent/demo-flow-components/src/test/java/com/vaadin/flow/demo/views/CheckboxIT.java#L65)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Ok, the problem here is the `attribute` thing - can you try to run `executeScript("return arguments[0].checked;", checkbox);` to see if it is `null/false` ? That measures the value of the property, not the attribute.
</blockquote></details>

No need to do it.
I see this property in the DOM when run manually.
"Checked" is not removed.

It's removed after the second click.

https://github.com/vaadin/vaadin-checkbox-flow/issues/6

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2811)*

**Comment by denis-anisimov** [comment]
Review status: 4 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-server/src/test/java/com/vaadin/ui/ComponentMetaDataTest.java, line 28 at r1](https://reviewable.io:443/reviews/vaadin/flow/2811#-KxmU5Lw0eHhQv8SF5xV:-Kxma974IY4owJjbm_6k:bdcv6l8) ([raw file](https://github.com/vaadin/flow/blob/505091705380646e6b4f36033596c22b1ea18942/flow-server/src/test/java/com/vaadin/ui/ComponentMetaDataTest.java#L28)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

I suggest also adding a test where one method of the super and the sub class has the `@Synchronize` annotation at the same time.
</blockquote></details>

Good point.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2811)*

**Comment by gilberto-torrezan** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2811)*

**Pull request merged**
