### PR TITLE
Recursively checks for parents in order to verify whether a node is enabled or visible

### PR DESCRIPTION
**Pull request by gilberto-torrezan**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3857)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/AbstractRpcInvocationHandler.java, line 55 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3857#-L9nbo0T4N-10aRcijeK:-L9nbo0T4N-10aRcijeL:b-xz7tyr) ([raw file](https://github.com/vaadin/flow/blob/d79f96b963c6b6309797fb599804daee35db4a37/flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/AbstractRpcInvocationHandler.java#L55)):*
> ```
> isVisibleAndEnabled(node);
> ```

Please make `StateNode::isInactive()` public and use it here.

Don't care about `enabled` state since I'm going to rewrite this functionality in my patch.
`AbstractRpcInvocationHandler`  is not a correct  place for this check.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3857)*

**Comment by gilberto-torrezan** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/AbstractRpcInvocationHandler.java, line 55 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3857#-L9nbo0T4N-10aRcijeK:-L9nfYqR5VTjrY9IaPf6:b-p5o4cy) ([raw file](https://github.com/vaadin/flow/blob/d79f96b963c6b6309797fb599804daee35db4a37/flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/AbstractRpcInvocationHandler.java#L55)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
> isVisibleAndEnabled(node);
> ```

Please make `StateNode::isInactive()` public and use it here.

Don't care about `enabled` state since I'm going to rewrite this functionality in my patch.
`AbstractRpcInvocationHandler`  is not a correct  place for this check.
</blockquote></details>

Mikael's patch will also change everything, so I'll close this PR.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3857)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/AbstractRpcInvocationHandler.java, line 55 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3857#-L9nbo0T4N-10aRcijeK:-L9nfzo9Aq7XsB8xZPwS:b7wfltb) ([raw file](https://github.com/vaadin/flow/blob/d79f96b963c6b6309797fb599804daee35db4a37/flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/AbstractRpcInvocationHandler.java#L55)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Mikael's patch will also change everything, so I'll close this PR.
</blockquote></details>

Proper inactivity state is not checked anywhere.
So this part is still relevant.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3857)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/AbstractRpcInvocationHandler.java, line 55 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3857#-L9nbo0T4N-10aRcijeK:-L9ng80N5j0h5c8pEZk9:bcjugr4) ([raw file](https://github.com/vaadin/flow/blob/d79f96b963c6b6309797fb599804daee35db4a37/flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/AbstractRpcInvocationHandler.java#L55)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Proper inactivity state is not checked anywhere.
So this part is still relevant.
</blockquote></details>

Please create a ticket at least.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3857)*

**Pull request closed without merging**
