### PR TITLE
Add more data to stats.json

### LINKED ISSUE #8053: stats.json optimization in 2.2 causes addons templates excluded in the file
It seems that https://github.com/vaadin/flow/commit/9e037137b4a39e88b1201ef521d9996c2faffe3e introduced a regression that causes that templates in addons cannot be found.
The problem only happen in production due to the webpack configuration that discards the chunks key.

Attached a project that manifests the problem [test-project.zip](https://github.com/vaadin/flow/files/4475568/test-project.zip)  
1. uncompress the project
2. run the project in devMode
  - run `mvn`  
  - visit http://localhost:8080
  - there should not be any error in console
3.  compile for production and run the project
  - run `mvn package -Pproduction`
  - run `java -jar target/*.jar`
  - visit http://localhost:8080
  - there is an exception in console `Couldn't find the definition of the element with tag 'apex-charts-wrapper' in any template file`

Related with: https://github.com/vaadin/flow/issues/7752

### PR DESCRIPTION
**Pull request by caalador**
Add chunks also to production stats.

Fixes #8053

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/8056)

### CODE REVIEW

**Comment by pleku** [comment]
We should add a test to a production mode module that would catch this type of things in the future.
But IMO that can done in another PR.

**Comment by caalador** [comment]
Yes. I'm looking into how to best test the webpack output.

**Comment by pleku** [comment]
>Yes. I'm looking into how to best test the webpack output.

Ok, if that is possible, sure. I meant an integration test with an add-on in production mode.

**Comment by caalador** [comment]
But let's do it in another ticket to get this cherry picked and fixed asap so it can be validation tested.

**Pull request merged**
