### PR TITLE
Add polyfills, when browser does not support ES6.

### PR DESCRIPTION
**Pull request by SomeoneToIgnore**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/2907)

### CODE REVIEW

**Comment by gilberto-torrezan** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[flow-documentation/miscellaneous/tutorial-flow-runtime-configuration.asciidoc, line 18 at r1](https://reviewable.io:443/reviews/vaadin/flow/2907#-KypPNpxO2hBTir3mYDk:-KypPNpxO2hBTir3mYDl:bdvvaji) ([raw file](https://github.com/vaadin/flow/blob/273f33adcb66d35d24ae8b2ee4a582c0e139aa08/flow-documentation/miscellaneous/tutorial-flow-runtime-configuration.asciidoc#L18)):*
> ```AsciiDoc
> * by setting the system property
> 
> In this case, `vaadin.` prefix is recommended to avoid name collisions.
> ```

Do you _have_ to use or is it _recommended_ to use the  `vaadin.`prefix? (See my comment on the `tutorial-webcomponents-es5.asciidoc` file).

---

*[flow-documentation/miscellaneous/tutorial-flow-runtime-configuration.asciidoc, line 95 at r1](https://reviewable.io:443/reviews/vaadin/flow/2907#-KypS40cDPo61Ha_dNl-:-KypS40cDPo61Ha_dNl0:b73gyw4) ([raw file](https://github.com/vaadin/flow/blob/273f33adcb66d35d24ae8b2ee4a582c0e139aa08/flow-documentation/miscellaneous/tutorial-flow-runtime-configuration.asciidoc#L95)):*
> ```AsciiDoc
> Webjars are enabled for development mode and disabled for production mode by default,
> unless explicitly overridden by parameter specified.
> In future, webjars should be expected to be enabled always.
> ```

Suggestion: In the future, webjars are expected to the always enabled by default.

---

*[flow-documentation/miscellaneous/tutorial-flow-runtime-configuration.asciidoc, line 104 at r1](https://reviewable.io:443/reviews/vaadin/flow/2907#-KypR3IgxiyNb3BLRSl6:-KypR3IgxiyNb3BLRSl7:bimjgag) ([raw file](https://github.com/vaadin/flow/blob/273f33adcb66d35d24ae8b2ee4a582c0e139aa08/flow-documentation/miscellaneous/tutorial-flow-runtime-configuration.asciidoc#L104)):*
> https://docs.jboss.org/jbossas/guides/webguide/r2/en/html/ch06.html

JBoss? I'm not sure if providing this link would be helpful or more confusing. 

Maybe also worth mentioning the location of the folder inside the project (when using maven -> `src/main/webapp/frontend`)

---

*[flow-documentation/web-components/tutorial-webcomponents-es5.asciidoc, line 466 at r1](https://reviewable.io:443/reviews/vaadin/flow/2907#-KypP4I-hWO4ltP8z_5X:-KypP4I-hWO4ltP8z_5Y:bop99u0) ([raw file](https://github.com/vaadin/flow/blob/273f33adcb66d35d24ae8b2ee4a582c0e139aa08/flow-documentation/web-components/tutorial-webcomponents-es5.asciidoc#L466)):*
> ```AsciiDoc
> * `vaadin.frontend.url.es5` for the ES5 files URL
> 
> When setting those properties from the command line, you have to use the `vaadin`
> ```

Do you _have_ to use or is it _recommended_ to use the  `vaadin.`prefix? (See my comment on the `tutorial-flow-runtime-configuration.asciidoc` file).

---

*[flow-server/src/main/java/com/vaadin/server/BootstrapHandler.java, line 91 at r1](https://reviewable.io:443/reviews/vaadin/flow/2907#-KypPbC1XTa1aNpma9Wx:-KypPbC1XTa1aNpma9Wy:b-cu40bj) ([raw file](https://github.com/vaadin/flow/blob/273f33adcb66d35d24ae8b2ee4a582c0e139aa08/flow-server/src/main/java/com/vaadin/server/BootstrapHandler.java#L91)):*
> ```Java
>             "BootstrapHandler.js");
>     private static final String BABEL_HELPERS_JS = readResource(
>             "babel-helpers.min.js");
> ```

Did you discover why this is needed? I remember that we have some ticket sometime ago where there were a discussion about this file not being needed at runtime. But it was a long time ago, so I don't remember the details.

If you discovered (or even better, if you have some link explaining it), I recommend putting a comment here in the code, and/or a explanation in the tutorial about which files are added by default when running in ES5 mode.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2907)*

**Comment by gilberto-torrezan** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-documentation/miscellaneous/tutorial-flow-runtime-configuration.asciidoc, line 95 at r2](https://reviewable.io:443/reviews/vaadin/flow/2907#-Kyp_DXM1X50REFLqfU6:-Kyp_DXM1X50REFLqfU7:b58jfe6) ([raw file](https://github.com/vaadin/flow/blob/0a23614d02aa79fe00214c7f2fb2139798ea3ed3/flow-documentation/miscellaneous/tutorial-flow-runtime-configuration.asciidoc#L95)):*
> ```AsciiDoc
> Webjars are enabled for development mode and disabled for production mode by default,
> unless explicitly overridden by parameter specified.
> Suggestion: In the future, webjars are expected to the always enabled by default.
> ```

Copy pasted the entire sentence =P
The `Suggestion: `  is not meant to be there

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2907)*

**Comment by SomeoneToIgnore** [comment]
*[flow-documentation/miscellaneous/tutorial-flow-runtime-configuration.asciidoc, line 95 at r2](https://reviewable.io:443/reviews/vaadin/flow/2907#-Kyp_DXM1X50REFLqfU6:-Kyp_jaoixTNcP4qN-nx:b-838vte) ([raw file](https://github.com/vaadin/flow/blob/0a23614d02aa79fe00214c7f2fb2139798ea3ed3/flow-documentation/miscellaneous/tutorial-flow-runtime-configuration.asciidoc#L95)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Copy pasted the entire sentence =P
The `Suggestion: `  is not meant to be there
</blockquote></details>

Ok :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2907)*

**Comment by gilberto-torrezan** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2907)*

**Pull request merged**
