### PR TITLE
refactor: Split dev bundle related utils to a separate class

### PR DESCRIPTION
**Pull request by Artur-**

### CODE REVIEW

**Review by czp13 — APPROVED** [review]
This seems safe to me, checked out, imports good, etc. 
Just refactoring, with a small optimization /fix around logging.

**Comment by czp13** [comment]
I can fix the tests later, as they are because of refactoring (only unit tests, because how we mock could be changed, logging is changed, etc)

**Comment by Artur-** [comment]
I think #16537 will solve most of the issues

**Review by czp13 — APPROVED** [review]
This seems safe to me, checked out, imports good, etc. 
Just refactoring, with a small optimization /fix around logging.

**Pull request merged**
