### PR TITLE
fix!: Use servlet context path as the default logout url

### PR DESCRIPTION
**Pull request by TatuLund**
CP of https://github.com/vaadin/flow/pull/15532

### CODE REVIEW

**Comment by mshabarov** [comment]
This is the behaviour change and might break some apps with a context path (e.g. if they don't have a route for "/context-path"). Not so safe to include it into maintenance/patch releases in my opinion.

**Comment by mshabarov** [comment]
@TatuLund do we have any requests from Customers about including it into 23.3 ? I would prefer to at least include it into next minor 23.4 (ofc if we plan it).

**Comment by mshabarov** [comment]
Alright, in this case let's merge it, because we have no plans for 23.4 at the moment. Also assuming that this fix hasn't raised any complains in V24.
We can state in the release notes that `setLoginView(http, flowLoginView, "/");` can be used as a fallback if a new behaviour is not desired for any reason.

**Review by mshabarov — APPROVED** [review]

**Review by mshabarov — CHANGES_REQUESTED** [review]
This seems to require modifications in tests.
Makes sense to compare the failed module with the main branch.
Failed test module is `test-spring-security-flow-methodsecurity`, 
the exception is 
```
Caused by: java.lang.IllegalArgumentException: defaultTarget must start with '/' or with 'http(s)'
	at org.springframework.util.Assert.isTrue(Assert.java:121)
	at org.springframework.security.web.authentication.AbstractAuthenticationTargetUrlRequestHandler.setDefaultTargetUrl(AbstractAuthenticationTargetUrlRequestHandler.java:158)
	at com.vaadin.flow.spring.security.VaadinWebSecurity.configureLogout(VaadinWebSecurity.java:530)
	at com.vaadin.flow.spring.security.VaadinWebSecurity.setLoginView(VaadinWebSecurity.java:414)
	at com.vaadin.flow.spring.security.VaadinWebSecurity.setLoginView(VaadinWebSecurity.java:374)
	at com.vaadin.flow.spring.flowsecurity.SecurityConfig.configure(SecurityConfig.java:72)
	at com.vaadin.flow.spring.security.VaadinWebSecurity.filterChain(VaadinWebSecurity.java:128)
	at com.vaadin.flow.spring.flowsecurity.SecurityConfig$$EnhancerBySpringCGLIB$$75a62034.CGLIB$filterChain$4(<generated>)
	at com.vaadin.flow.spring.flowsecurity.SecurityConfig$$EnhancerBySpringCGLIB$$75a62034$$FastClassBySpringCGLIB$$9933c018.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
	at com.vaadin.flow.spring.flowsecurity.SecurityConfig$$EnhancerBySpringCGLIB$$75a62034.filterChain(<generated>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 42 more
```

**Review by mshabarov — APPROVED** [review]

**Review by mcollovati — APPROVED** [review]

**Review by czp13 — APPROVED** [review]

**Pull request merged**
