### PR TITLE
Allow to override Lumo theme styles

### LINKED ISSUE #4076: Lumo.java should not place <custom-style> inside <body>
Overriding font styles for the `<html>` element using `shared-styles.html` does not work, since `Lumo.java` is overriding those styles by placing styles inside the `<body>` element.

`getBodyInlineContents` should probably be `getHeadInlineContents` (or have both options available), and produce the content before any app-specific HTML imports are processed so that the CSS cascade order or as expected.

### PR DESCRIPTION
**Pull request by denis-anisimov**
Fixes #4076

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/4121)

### CODE REVIEW

**Comment by caalador** [comment]
Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---

*[flow-theme-integrations/lumo/src/main/java/com/vaadin/flow/theme/lumo/Lumo.java, line 53 at r1](https://reviewable.io/reviews/vaadin/flow/4121#-LCYitxR8qFLCKR69kpt:-LCYitxR8qFLCKR69kpu:b-p4cab4) ([raw file](https://github.com/vaadin/flow/blob/543d21332670c11d6fe1de775a948556519772c7/flow-theme-integrations/lumo/src/main/java/com/vaadin/flow/theme/lumo/Lumo.java#L53)):*
> ```Java
> 
>     @Override
>     public List<String> getBodyInlineContents() {
> ```

Would change this to `getCustomStyles` and just script tag them all in `BootstrapUtils` to head instead of body.

You wouldn't want to write the script things again and again.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4121)*

**Comment by denis-anisimov** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-theme-integrations/lumo/src/main/java/com/vaadin/flow/theme/lumo/Lumo.java, line 53 at r1](https://reviewable.io/reviews/vaadin/flow/4121#-LCYitxR8qFLCKR69kpt:-LCbe5k66Kue6J3d5HRD:btrb44d) ([raw file](https://github.com/vaadin/flow/blob/543d21332670c11d6fe1de775a948556519772c7/flow-theme-integrations/lumo/src/main/java/com/vaadin/flow/theme/lumo/Lumo.java#L53)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Would change this to `getCustomStyles` and just script tag them all in `BootstrapUtils` to head instead of body.

You wouldn't want to write the script things again and again.
</blockquote></details>

Makes sense BUT: what should it returns ?
Now it returns  a list of generic contents. It's up to the developer decide what string exactly should be returned (according to the method name).

With the method name `getCustomStyles` it should return only custom styles.
Does it mean that it should not return `<custom-style>` tag but only its content?
It become quite error-prone (should it be wrapped into `<custom-style>` or not ?)
Should it return only one string now instead of a `List`?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4121)*

**Comment by caalador** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-theme-integrations/lumo/src/main/java/com/vaadin/flow/theme/lumo/Lumo.java, line 53 at r1](https://reviewable.io/reviews/vaadin/flow/4121#-LCYitxR8qFLCKR69kpt:-LCbjZL6EKxRmbRqMjaz:b-o8fm1z) ([raw file](https://github.com/vaadin/flow/blob/543d21332670c11d6fe1de775a948556519772c7/flow-theme-integrations/lumo/src/main/java/com/vaadin/flow/theme/lumo/Lumo.java#L53)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Makes sense BUT: what should it returns ?
Now it returns  a list of generic contents. It's up to the developer decide what string exactly should be returned (according to the method name).

With the method name `getCustomStyles` it should return only custom styles.
Does it mean that it should not return `<custom-style>` tag but only its content?
It become quite error-prone (should it be wrapped into `<custom-style>` or not ?)
Should it return only one string now instead of a `List`?


</blockquote></details>

I guess what we would want here is something where you give the element tag + innerHtml and all that are given would then  be added inside a script tag that is executed when bootstrapping.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4121)*

**Comment by denis-anisimov** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-theme-integrations/lumo/src/main/java/com/vaadin/flow/theme/lumo/Lumo.java, line 53 at r1](https://reviewable.io/reviews/vaadin/flow/4121#-LCYitxR8qFLCKR69kpt:-LCbkTxy6lUuSLcfpofo:brnqdgb) ([raw file](https://github.com/vaadin/flow/blob/543d21332670c11d6fe1de775a948556519772c7/flow-theme-integrations/lumo/src/main/java/com/vaadin/flow/theme/lumo/Lumo.java#L53)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

I guess what we would want here is something where you give the element tag + innerHtml and all that are given would then  be added inside a script tag that is executed when bootstrapping.
</blockquote></details>

Don't really understand:
- inside a script tag: you mean that the content should be just the `innerHTML` of the script tag created inside `head` ? (Here it's not true. `script` contains a JS which adds a custom style into the `head` ). Will it work at all (without real JS)?
- Still don't understand what is expected to be returned by the `getCustomStyles` method ? a `List` , a `String`? Should it be a `custom-style` innerHTML only or it should be along with `custom-style`?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4121)*

**Comment by caalador** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-theme-integrations/lumo/src/main/java/com/vaadin/flow/theme/lumo/Lumo.java, line 53 at r1](https://reviewable.io/reviews/vaadin/flow/4121#-LCYitxR8qFLCKR69kpt:-LCbt1uZ5i2bNKtpp_79:b-urnj9l) ([raw file](https://github.com/vaadin/flow/blob/543d21332670c11d6fe1de775a948556519772c7/flow-theme-integrations/lumo/src/main/java/com/vaadin/flow/theme/lumo/Lumo.java#L53)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Don't really understand:
- inside a script tag: you mean that the content should be just the `innerHTML` of the script tag created inside `head` ? (Here it's not true. `script` contains a JS which adds a custom style into the `head` ). Will it work at all (without real JS)?
- Still don't understand what is expected to be returned by the `getCustomStyles` method ? a `List` , a `String`? Should it be a `custom-style` innerHTML only or it should be along with `custom-style`?
</blockquote></details>

We wouldn't want to copy paste the script injection part around for new themes.
I would say the return value should be a `List<InjectElement>` where `InjectElement` contains `String tag` and `String innerHtml` these would then be wrapped by the script part and get injected using the now added script.

Then the name would be `

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4121)*

**Comment by denis-anisimov** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-theme-integrations/lumo/src/main/java/com/vaadin/flow/theme/lumo/Lumo.java, line 53 at r1](https://reviewable.io/reviews/vaadin/flow/4121#-LCYitxR8qFLCKR69kpt:-LCbz1mrDyBJ13nCjoj5:b3bmpfg) ([raw file](https://github.com/vaadin/flow/blob/543d21332670c11d6fe1de775a948556519772c7/flow-theme-integrations/lumo/src/main/java/com/vaadin/flow/theme/lumo/Lumo.java#L53)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

We wouldn't want to copy paste the script injection part around for new themes.
I would say the return value should be a `List<InjectElement>` where `InjectElement` contains `String tag` and `String innerHtml` these would then be wrapped by the script part and get injected using the now added script.

Then the name would be `
</blockquote></details>

Name part is missed.

Why do we need `InjectElement` if only html snippet as a `String`  is enough?
Several things:
- the method name is still important because we either allow to have _any_ content and then `tag` makes sense since it's not just `custom-style`.
- I guess the main idea here is to use the `tag` in the script to create it via the `document.createElement`  and then set its `innerHtml` content as here in the code. So it's an implementation point of view.

But from the API point of view it's a bit weird to have `InjectElement` is only a `String` may be provided.
If we still want the string then we just may parse it using `Jsoup` and detect the top level tag. And then get its `innerHtml`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4121)*

**Comment by caalador** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-theme-integrations/lumo/src/main/java/com/vaadin/flow/theme/lumo/Lumo.java, line 53 at r1](https://reviewable.io/reviews/vaadin/flow/4121#-LCYitxR8qFLCKR69kpt:-LCc4DL-8yhQN2hbg4eJ:b-ynjk2f) ([raw file](https://github.com/vaadin/flow/blob/543d21332670c11d6fe1de775a948556519772c7/flow-theme-integrations/lumo/src/main/java/com/vaadin/flow/theme/lumo/Lumo.java#L53)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Name part is missed.

Why do we need `InjectElement` if only html snippet as a `String`  is enough?
Several things:
- the method name is still important because we either allow to have _any_ content and then `tag` makes sense since it's not just `custom-style`.
- I guess the main idea here is to use the `tag` in the script to create it via the `document.createElement`  and then set its `innerHtml` content as here in the code. So it's an implementation point of view.

But from the API point of view it's a bit weird to have `InjectElement` is only a `String` may be provided.
If we still want the string then we just may parse it using `Jsoup` and detect the top level tag. And then get its `innerHtml`.
</blockquote></details>

It should be able to take any content.
I don't know what someone might want to have there, but it shouldn't be restricted to custom-style.

Implementation doesn't matter, but the content to give should be a simple Object/String.
Also now the BodyInline is wrong as it may or may not be inlined in body.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4121)*

**Comment by denis-anisimov** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-theme-integrations/lumo/src/main/java/com/vaadin/flow/theme/lumo/Lumo.java, line 53 at r1](https://reviewable.io/reviews/vaadin/flow/4121#-LCYitxR8qFLCKR69kpt:-LCc8KnB1Yl4KeFqcDzS:b-my6onv) ([raw file](https://github.com/vaadin/flow/blob/543d21332670c11d6fe1de775a948556519772c7/flow-theme-integrations/lumo/src/main/java/com/vaadin/flow/theme/lumo/Lumo.java#L53)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

It should be able to take any content.
I don't know what someone might want to have there, but it shouldn't be restricted to custom-style.

Implementation doesn't matter, but the content to give should be a simple Object/String.
Also now the BodyInline is wrong as it may or may not be inlined in body.

</blockquote></details>

Aaaaaand.

What is the suggested method name ?

`getHeaderInlineContents`?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4121)*

**Comment by caalador** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-theme-integrations/lumo/src/main/java/com/vaadin/flow/theme/lumo/Lumo.java, line 53 at r1](https://reviewable.io/reviews/vaadin/flow/4121#-LCYitxR8qFLCKR69kpt:-LCc8jkq-AQQF1jclQuy:b-aildtx) ([raw file](https://github.com/vaadin/flow/blob/543d21332670c11d6fe1de775a948556519772c7/flow-theme-integrations/lumo/src/main/java/com/vaadin/flow/theme/lumo/Lumo.java#L53)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Aaaaaand.

What is the suggested method name ?

`getHeaderInlineContents`?
</blockquote></details>

That's probably what it was called when it was supposed to insert everything to the head in the beginning.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4121)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 7 files at r1.
Review status: 1 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-theme-integrations/lumo/src/main/java/com/vaadin/flow/theme/lumo/Lumo.java, line 53 at r1](https://reviewable.io/reviews/vaadin/flow/4121#-LCYitxR8qFLCKR69kpt:-LCc9HXLA7TBiTRZYIfX:b32w0x) ([raw file](https://github.com/vaadin/flow/blob/543d21332670c11d6fe1de775a948556519772c7/flow-theme-integrations/lumo/src/main/java/com/vaadin/flow/theme/lumo/Lumo.java#L53)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

That's probably what it was called when it was supposed to insert everything to the head in the beginning.
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4121)*

**Comment by denis-anisimov** [comment]
Review status: 0 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-theme-integrations/lumo/src/main/java/com/vaadin/flow/theme/lumo/Lumo.java, line 53 at r1](https://reviewable.io/reviews/vaadin/flow/4121#-LCYitxR8qFLCKR69kpt:-LCcj-16CY8vXRHsa_RJ:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/543d21332670c11d6fe1de775a948556519772c7/flow-theme-integrations/lumo/src/main/java/com/vaadin/flow/theme/lumo/Lumo.java#L53)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

OK
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4121)*

**Comment by caalador** [comment]
Reviewed 5 of 7 files at r1, 8 of 8 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java, line 487 at r2](https://reviewable.io/reviews/vaadin/flow/4121#-LCgay2M-4kaPG5WjqMj:-LCgay2N3wBH-Jt3-0l2:b-yg8qcf) ([raw file](https://github.com/vaadin/flow/blob/2fbe4f028f936975afe73d8c408c727779f8a5b7/flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java#L487)):*
> ```
> document.body()
> ```
Wouldn't we want to append to head instead of body as it now is a <script> tag which is ok to have in header?
As it's wrapped in a script it would mean that it's run a bit earlier.

---

*[flow-server/src/main/java/com/vaadin/flow/server/BootstrapUtils.java, line 324 at r2](https://reviewable.io/reviews/vaadin/flow/4121#-LCgbSxX-InpMlmL_WHA:-LCgbSxX-InpMlmL_WHB:b-slxqqa) ([raw file](https://github.com/vaadin/flow/blob/2fbe4f028f936975afe73d8c408c727779f8a5b7/flow-server/src/main/java/com/vaadin/flow/server/BootstrapUtils.java#L324)):*
> ```Java
>                 + "var firstScript = document.body.querySelector('script');\n"
>                 + "} document.head.insertBefore(customStyle,firstScript);\n"
>                 + "}\n");
> ```

Is there a possibility to remove this `

---

*[flow-server/src/test/java/com/vaadin/AssertionTest.java, line 35 at r2](https://reviewable.io/reviews/vaadin/flow/4121#-LCgc-Re30FXbKSjEExH:-LCgc-Re30FXbKSjEExI:b-eq3wjc) ([raw file](https://github.com/vaadin/flow/blob/2fbe4f028f936975afe73d8c408c727779f8a5b7/flow-server/src/test/java/com/vaadin/AssertionTest.java#L35)):*
> ```Java
>                 assertOn);
>     }
> ```

Formatting change only which doesn't have to do with the pach... not blocking.

---

*[flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/theme/CustomStylesIT.java, line 33 at r2](https://reviewable.io/reviews/vaadin/flow/4121#-LCgd1rr-qu_lRyQucQV:-LCgd1rs3YnMEcrynCAQ:b-4uhszl) ([raw file](https://github.com/vaadin/flow/blob/2fbe4f028f936975afe73d8c408c727779f8a5b7/flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/theme/CustomStylesIT.java#L33)):*
> ```Java
>         WebElement text = findElement(By.id("custom-style"));
>         String fontSize = text.getCssValue("font-size");
>         Assert.assertEquals("12px", fontSize);
> ```

Shouldn't this be `9px` as defined in `shared-styles.html`?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4121)*

**Comment by caalador** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/server/BootstrapUtils.java, line 324 at r2](https://reviewable.io/reviews/vaadin/flow/4121#-LCgbSxX-InpMlmL_WHA:-LCgfZof3RBZmwCcmYCh:b-ofd8xr) ([raw file](https://github.com/vaadin/flow/blob/2fbe4f028f936975afe73d8c408c727779f8a5b7/flow-server/src/main/java/com/vaadin/flow/server/BootstrapUtils.java#L324)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Is there a possibility to remove this `
</blockquote></details>

Reviewable keeps dropping things when I add code parts.
the comment was is it possible to remove the script tag after it has executed so we don't pollute the dom with it.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4121)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java, line 487 at r2](https://reviewable.io/reviews/vaadin/flow/4121#-LCgay2M-4kaPG5WjqMj:-LCgiFf_8NFo0cKjTNRL:biqj2lj) ([raw file](https://github.com/vaadin/flow/blob/2fbe4f028f936975afe73d8c408c727779f8a5b7/flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java#L487)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

> ```
> document.body()
> ```
Wouldn't we want to append to head instead of body as it now is a <script> tag which is ok to have in header?
As it's wrapped in a script it would mean that it's run a bit earlier.
</blockquote></details>

Aaaah, alright. Makes sense.

---

*[flow-server/src/main/java/com/vaadin/flow/server/BootstrapUtils.java, line 324 at r2](https://reviewable.io/reviews/vaadin/flow/4121#-LCgbSxX-InpMlmL_WHA:-LCgiVt-Dfr60vZsx8CG:bjvatmg) ([raw file](https://github.com/vaadin/flow/blob/2fbe4f028f936975afe73d8c408c727779f8a5b7/flow-server/src/main/java/com/vaadin/flow/server/BootstrapUtils.java#L324)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Reviewable keeps dropping things when I add code parts.
the comment was is it possible to remove the script tag after it has executed so we don't pollute the dom with it.
</blockquote></details>

How may I address this code in the header ?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4121)*

**Comment by caalador** [comment]
Review status: 10 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/server/BootstrapUtils.java, line 324 at r2](https://reviewable.io/reviews/vaadin/flow/4121#-LCgbSxX-InpMlmL_WHA:-LCgmeZdAnk9kfON_H59:bapumr1) ([raw file](https://github.com/vaadin/flow/blob/2fbe4f028f936975afe73d8c408c727779f8a5b7/flow-server/src/main/java/com/vaadin/flow/server/BootstrapUtils.java#L324)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

How may I address this code in the header ?
</blockquote></details>

Perhaps we should have the function defined in its own script tag (if there is a theme/theme headers) as it will in any case be left in browser memory and the headerInjectionCalls would then go in their own script tag the would have an id e.g. `<script id="headerInjection">` , and we would then add the part 
```
if(document.getElementById('headerInjection')) {
    head.removeChild(document.getElementById('headerInjection'));
}
```

That way the script for injecting would stay visible, but the run parts where we add the things wouldn't stay as duplicate code in the dom.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4121)*

**Comment by denis-anisimov** [comment]
Review status: 10 of 13 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[flow-server/src/main/java/com/vaadin/flow/server/BootstrapUtils.java, line 324 at r2](https://reviewable.io/reviews/vaadin/flow/4121#-LCgbSxX-InpMlmL_WHA:-LCgpUP6-SPMKIFfb0sT:b-3b7qvi) ([raw file](https://github.com/vaadin/flow/blob/2fbe4f028f936975afe73d8c408c727779f8a5b7/flow-server/src/main/java/com/vaadin/flow/server/BootstrapUtils.java#L324)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Perhaps we should have the function defined in its own script tag (if there is a theme/theme headers) as it will in any case be left in browser memory and the headerInjectionCalls would then go in their own script tag the would have an id e.g. `<script id="headerInjection">` , and we would then add the part 
```
if(document.getElementById('headerInjection')) {
    head.removeChild(document.getElementById('headerInjection'));
}
```

That way the script for injecting would stay visible, but the run parts where we add the things wouldn't stay as duplicate code in the dom.
</blockquote></details>

Yeah, and I will spend a half an our to update tests........

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4121)*

**Comment by caalador** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4121#-:-LCgzHK82thcOh0ryv0x:bnfp4nl)*

**Comment by caalador** [comment]
Both failing tests are ones using simple custom `MyTheme` theme.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4121#-:-LCh4SnoBpci0m1ZsNH4:b-r3y3jj)*

**Comment by denis-anisimov** [comment]
Failing tests ?
Is validation already passed ?
I don't see the status report of the validation.......
Weird.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4121#-:-LCh593r2wu7hnisFyro:b-sglosq)*

**Comment by caalador** [comment]
2 tests failed
com.vaadin.flow.uitest.ui.theme (2)
HtmlParserThemeTemplateIT.themeComponentShouldLoadForTemplate[ANY_Chrome_] 	
MyThemeIT.loadThemeComponent[ANY_Chrome_] 

Both get a blank error screenshot and have element not found.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4121#-:-LCh5XP84DfFtw5Rz1Sc:bkoexfi)*

**Comment by denis-anisimov** [comment]
Right, now I see it as well. Thanks.

---

Review status: 11 of 14 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4121#-:-LCh9hL883dLeWp7k7AO:b8bl8tz)*

**Comment by caalador** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java, line 1085 at r5](https://reviewable.io/reviews/vaadin/flow/4121#-LChAPFV9UY5Qbvwb9C9:-LChAPFW8GHAJVIaUWGB:b-jaqhcl) ([raw file](https://github.com/vaadin/flow/blob/b026800c61ae2d162bcd6a47e54efbe57090b992/flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java#L1085)):*
> ```Java
>         allElements = page.head().getAllElements();
>         // Note element 0 is the full head element.
>         System.out.println(allElements.get(14).toString());
> ```

Extra sys out.
Remove if other fixes incoming else just ignore.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4121#-:-LChB8h01AWqCocQqaOc:bnfp4nl)*

**Comment by caalador** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/theme/CustomStylesIT.java, line 33 at r2](https://reviewable.io/reviews/vaadin/flow/4121#-LCgd1rr-qu_lRyQucQV:-LChCu4e03-dsb4ciLfb:b-3um08f) ([raw file](https://github.com/vaadin/flow/blob/2fbe4f028f936975afe73d8c408c727779f8a5b7/flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/theme/CustomStylesIT.java#L33)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

It's `9pt` in the styles which is `12px`.  But it's better to have both in pixels.
Done.
</blockquote></details>

Reviewable is keeping this as in progress with tooth and nail.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4121)*

**Comment by caalador** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4121#-:-LChDmi1-oF7EyNNUMrk:bnfp4nl)*

**Comment by caalador** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java, line 1085 at r5](https://reviewable.io/reviews/vaadin/flow/4121#-LChAPFV9UY5Qbvwb9C9:-LChEaGbCdegbYYyzPEN:bxjx0vr) ([raw file](https://github.com/vaadin/flow/blob/b026800c61ae2d162bcd6a47e54efbe57090b992/flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java#L1085)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Oh, crap, sop many mistakes/changes in this PR......
</blockquote></details>

again reviewable failed to acc this and left it as in progress.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4121)*

**Pull request merged**
