### PR TITLE
Add more documentation on WebJars.

### PR DESCRIPTION
**Pull request by SomeoneToIgnore**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/2756)

### CODE REVIEW

**Comment by gilberto-torrezan** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 21 unresolved discussions.

---

*[flow-documentation/flow-components/tutorial-flow-components-setup.asciidoc, line 119 at r1](https://reviewable.io:443/reviews/vaadin/flow/2756#-KxBvwDW6jYTZFHueQEQ:-KxBvwDW6jYTZFHueQER:b2vflsu) ([raw file](https://github.com/vaadin/flow/blob/3e2f9de9b556ddbd568a6be0515d89a9792757e3/flow-documentation/flow-components/tutorial-flow-components-setup.asciidoc#L119)):*
> ```AsciiDoc
> == bower.json configuration
> 
> Currently `bower.json` is needed for production mode and in cases wne you'd like to be able
> ```

Not your patch's fault, but there's a typo on `wne`.

---

*[flow-documentation/flow-components/tutorial-flow-components-setup.asciidoc, line 120 at r1](https://reviewable.io:443/reviews/vaadin/flow/2756#-KxBwJX6QCBYG3NdVThK:-KxBwJX6QCBYG3NdVThL:burnh10) ([raw file](https://github.com/vaadin/flow/blob/3e2f9de9b556ddbd568a6be0515d89a9792757e3/flow-documentation/flow-components/tutorial-flow-components-setup.asciidoc#L120)):*
> ```AsciiDoc
> 
> Currently `bower.json` is needed for production mode and in cases wne you'd like to be able
> to manipulate web component's files before adding them to the application (transpile, minify, check, bundle etc)
> ```

Missing period at the end of the sentence.

---

*[flow-documentation/flow-components/tutorial-flow-components-setup.asciidoc, line 121 at r1](https://reviewable.io:443/reviews/vaadin/flow/2756#-KxBwD2cIJdezWGSkVGT:-KxBwD2cIJdezWGSkVGU:bksbw3c) ([raw file](https://github.com/vaadin/flow/blob/3e2f9de9b556ddbd568a6be0515d89a9792757e3/flow-documentation/flow-components/tutorial-flow-components-setup.asciidoc#L121)):*
> ```AsciiDoc
> Currently `bower.json` is needed for production mode and in cases wne you'd like to be able
> to manipulate web component's files before adding them to the application (transpile, minify, check, bundle etc)
> It is also can be used in developmentMode as a webjars' substitution.
> ```

`It is also can be used` -> `It also can be used`

---

*[flow-documentation/flow-components/tutorial-flow-components-setup.asciidoc, line 160 at r1](https://reviewable.io:443/reviews/vaadin/flow/2756#-KxBxeFAIMvCk3PKHpPH:-KxBxeFAIMvCk3PKHpPI:b-m6qqo1) ([raw file](https://github.com/vaadin/flow/blob/3e2f9de9b556ddbd568a6be0515d89a9792757e3/flow-documentation/flow-components/tutorial-flow-components-setup.asciidoc#L160)):*
> ```AsciiDoc
> == Runtime configuration
> 
> Extra parameters can be specified to configure `flow`:
> ```

I think we don't have a proper format convention on the name of the project, but I saw several places using Flow instead of `flow`. Your call if you want to fix it.

---

*[flow-documentation/flow-components/tutorial-flow-components-setup.asciidoc, line 163 at r1](https://reviewable.io:443/reviews/vaadin/flow/2756#-KxBwf7fNuzP3G_8qjG_:-KxBwf7fNuzP3G_8qjGa:blmjhch) ([raw file](https://github.com/vaadin/flow/blob/3e2f9de9b556ddbd568a6be0515d89a9792757e3/flow-documentation/flow-components/tutorial-flow-components-setup.asciidoc#L163)):*
> ```AsciiDoc
> 
> * disable.webjars - if set to `true`, webjars would be ignored during request resolving,
> allows `flow` to use external source of web components' files.
> ```

`allows` -> `allowing`

---

*[flow-documentation/flow-components/tutorial-flow-components-setup.asciidoc, line 173 at r1](https://reviewable.io:443/reviews/vaadin/flow/2756#-KxBx7XIL7flLCZiOYIF:-KxBx7XIL7flLCZiOYIG:bbwb3lw) ([raw file](https://github.com/vaadin/flow/blob/3e2f9de9b556ddbd568a6be0515d89a9792757e3/flow-documentation/flow-components/tutorial-flow-components-setup.asciidoc#L173)):*
> ```AsciiDoc
> Development mode:
> 
> * frontend.url.dev (default value is context://frontend) – a location `flow` searches web components' files in development mode.
> ```

I suggest using `content://frontend` (with ` for formatting the value as code). This applies to the other mentions in this file as well (as in `content://frontend-es5`).

---

*[flow-documentation/flow-components/tutorial-flow-webjars.asciidoc, line 7 at r1](https://reviewable.io:443/reviews/vaadin/flow/2756#-KxBy3RgwpZz9S4JZmsM:-KxBy3RgwpZz9S4JZmsN:brr6k8t) ([raw file](https://github.com/vaadin/flow/blob/3e2f9de9b556ddbd568a6be0515d89a9792757e3/flow-documentation/flow-components/tutorial-flow-webjars.asciidoc#L7)):*
> ```AsciiDoc
> ---
> 
> This tutorial is intended to explain what options the user has
> ```

This sentence feels incomplete.

---

*[flow-documentation/flow-components/tutorial-flow-webjars.asciidoc, line 8 at r1](https://reviewable.io:443/reviews/vaadin/flow/2756#-KxByEUsyYX6LlFvBvY0:-KxByEUsyYX6LlFvBvY1:bl8duqk) ([raw file](https://github.com/vaadin/flow/blob/3e2f9de9b556ddbd568a6be0515d89a9792757e3/flow-documentation/flow-components/tutorial-flow-webjars.asciidoc#L8)):*
> ```AsciiDoc
> 
> This tutorial is intended to explain what options the user has
> Explanation on how to use WebJars is arbitrary project is in <<tutorial-how-to-use-webjars#, How to use webjars>>
> ```

`how to use WebJars is arbitrary project` ->  `how to use WebJars in an arbitrary project`

---

*[flow-documentation/flow-components/tutorial-flow-webjars.asciidoc, line 18 at r1](https://reviewable.io:443/reviews/vaadin/flow/2756#-KxBy_v7Psuhfa4RG1OS:-KxBy_v7Psuhfa4RG1OT:b75p0bj) ([raw file](https://github.com/vaadin/flow/blob/3e2f9de9b556ddbd568a6be0515d89a9792757e3/flow-documentation/flow-components/tutorial-flow-webjars.asciidoc#L18)):*
> ```AsciiDoc
> That's the https://www.polymer-project.org/2.0/start/install-2-0[recommended way] currently.
> 
> In future, when https://www.polymer-project.org/blog/2017-08-23-hands-on-30-preview[Polymer 3.0]
> ```

Suggested sentence refactory ->  In the future, Polymer 3.0 will migrate to npm and yarn instead.

---

*[flow-documentation/flow-components/tutorial-flow-webjars.asciidoc, line 24 at r1](https://reviewable.io:443/reviews/vaadin/flow/2756#-KxBz456s_kv-eNxUoyp:-KxBz456s_kv-eNxUoyq:b-8g6ew3) ([raw file](https://github.com/vaadin/flow/blob/3e2f9de9b556ddbd568a6be0515d89a9792757e3/flow-documentation/flow-components/tutorial-flow-webjars.asciidoc#L24)):*
> ```AsciiDoc
> runtime configuration (more details in <<tutorial-flow-components-setup#,Flow components setup>>)
> 
> Although Flow does not need to know about those tools, it would be nice to integrate this workflow as part of Flow and
> ```

`it would be nice` -> `it is possible to`

---

*[flow-documentation/flow-components/tutorial-flow-webjars.asciidoc, line 29 at r1](https://reviewable.io:443/reviews/vaadin/flow/2756#-KxC02c0ftY5QE82XnTx:-KxC02c0ftY5QE82XnTy:b-1ci6dl) ([raw file](https://github.com/vaadin/flow/blob/3e2f9de9b556ddbd568a6be0515d89a9792757e3/flow-documentation/flow-components/tutorial-flow-webjars.asciidoc#L29)):*
> ```AsciiDoc
> = Integration options:
> 
> Here are considered ways of getting web components' files into the project, summary is in the next section.
> ```

I'd call it a conclusion instead of summary - this chapter looks more like a justification of the current approach than a list of possible options.

---

*[flow-documentation/flow-components/tutorial-flow-webjars.asciidoc, line 31 at r1](https://reviewable.io:443/reviews/vaadin/flow/2756#-KxC0vB431Dz41mKE8mV:-KxC0vB431Dz41mKE8mW:b-d3kjfr) ([raw file](https://github.com/vaadin/flow/blob/3e2f9de9b556ddbd568a6be0515d89a9792757e3/flow-documentation/flow-components/tutorial-flow-webjars.asciidoc#L31)):*
> ```AsciiDoc
> Here are considered ways of getting web components' files into the project, summary is in the next section.
> 
> == Maven (Gradle) plugin to download bower dependencies
> ```

`(Gradle)` -> `(or Gradle)`

---

*[flow-documentation/flow-components/tutorial-flow-webjars.asciidoc, line 55 at r1](https://reviewable.io:443/reviews/vaadin/flow/2756#-KxC1ONN0PRguS2JXgRT:-KxC1ONN0PRguS2JXgRU:bp2mzso) ([raw file](https://github.com/vaadin/flow/blob/3e2f9de9b556ddbd568a6be0515d89a9792757e3/flow-documentation/flow-components/tutorial-flow-webjars.asciidoc#L55)):*
> ```AsciiDoc
> pull new transitive dependencies' versions which may break things.
> 
> bower has no file caching mechanism (it has some sort of resolution caching, but it's a different thing)
> ```

Missing capital B at the start of the sentence.

---

*[flow-documentation/flow-components/tutorial-flow-webjars.asciidoc, line 88 at r1](https://reviewable.io:443/reviews/vaadin/flow/2756#-KxC5a8JdDeYDw7-Qs9Z:-KxC5a8JdDeYDw7-Qs9_:bxthvxy) ([raw file](https://github.com/vaadin/flow/blob/3e2f9de9b556ddbd568a6be0515d89a9792757e3/flow-documentation/flow-components/tutorial-flow-webjars.asciidoc#L88)):*
> ```AsciiDoc
> Additional challenges provided by the https://www.webjars.org/ website:
> * Rich ui with multiple ways of adding the same bower dependency that lead to confusion and different names of the artifacts
> * https://github.com/webjars/webjars/issues/1648 sometimes deploy breaks, some artifacts are present in BinTray, not MavenCentral
> ```

`MavenCentral` -> `Maven Central`

---

*[flow-documentation/flow-components/tutorial-how-to-use-webjars.asciidoc, line 59 at r1](https://reviewable.io:443/reviews/vaadin/flow/2756#-KxC4peJHceZMvBCX-EU:-KxC4peJHceZMvBCX-EV:bgni02) ([raw file](https://github.com/vaadin/flow/blob/3e2f9de9b556ddbd568a6be0515d89a9792757e3/flow-documentation/flow-components/tutorial-how-to-use-webjars.asciidoc#L59)):*
> ```AsciiDoc
> There are two things that may go wrong:
> * Artifact won't be present in the repository
> * Artifact will be present in the repository, but there would be a conflict between
> ```

`a conflict between` -> `a conflict among different versions of the package`

---

*[flow-documentation/flow-components/tutorial-how-to-use-webjars.asciidoc, line 66 at r1](https://reviewable.io:443/reviews/vaadin/flow/2756#-KxC5BVyJ3F3yyxYhWhZ:-KxC5BVyJ3F3yyxYhWh_:bp4xq9f) ([raw file](https://github.com/vaadin/flow/blob/3e2f9de9b556ddbd568a6be0515d89a9792757e3/flow-documentation/flow-components/tutorial-how-to-use-webjars.asciidoc#L66)):*
> ```AsciiDoc
> 
> All current issues with WebJars are related to dependency resolution.
> Currently, the more webjars are added as a dependencies, the more probability that dependency resolution will go wrong.
> ```

`the more probability` -> `the greater is the probability of`

---

*[flow-documentation/flow-components/tutorial-how-to-use-webjars.asciidoc, line 85 at r1](https://reviewable.io:443/reviews/vaadin/flow/2756#-KxC5khfsY-2-So8nm1c:-KxC5khgkVosQc_GG6zn:bu20u1g) ([raw file](https://github.com/vaadin/flow/blob/3e2f9de9b556ddbd568a6be0515d89a9792757e3/flow-documentation/flow-components/tutorial-how-to-use-webjars.asciidoc#L85)):*
> ```AsciiDoc
> 
> Due to Maven caching mechanism, by default, after Maven fails to find an artifact, it caches this result for 24 hours.
> Using `-U` flag in `mvn` runs forces it to redownload the dependencies and usually fixes the problem.
> ```

I suggest adding a full, copy-pastable example:

```
mvn clean install -U
```

---

*[flow-documentation/flow-components/tutorial-how-to-use-webjars.asciidoc, line 102 at r1](https://reviewable.io:443/reviews/vaadin/flow/2756#-KxC68x12aoiCZmZr-No:-KxC68x12aoiCZmZr-Np:b-byyuvk) ([raw file](https://github.com/vaadin/flow/blob/3e2f9de9b556ddbd568a6be0515d89a9792757e3/flow-documentation/flow-components/tutorial-how-to-use-webjars.asciidoc#L102)):*
> ```AsciiDoc
> You will need to specify GitHub url, for paper-button it is `https://github.com/PolymerElements/paper-button`.
> Depending ot the case of the url string the long name would be resolved either into `github-com-PolymerElements-paper-button`
> for the example above or into `github-com-polymerelements-paper-button` for `https://github.com/polymerelements/paper-button`.
> ```

The paragraph could be enriched with a screenshot. One image worth more than thousand words they say. But it's optional.

---

*[flow-documentation/flow-components/tutorial-how-to-use-webjars.asciidoc, line 123 at r1](https://reviewable.io:443/reviews/vaadin/flow/2756#-KxC6W0gVo-fTZ_yvjtm:-KxC6W0gVo-fTZ_yvjtn:bmrtdkh) ([raw file](https://github.com/vaadin/flow/blob/3e2f9de9b556ddbd568a6be0515d89a9792757e3/flow-documentation/flow-components/tutorial-how-to-use-webjars.asciidoc#L123)):*
> ```AsciiDoc
> </repositories>
> ----
> this repository is an intermediate one, where all WebJars are published initially.
> ```

Missing capital T.

---

*[flow-documentation/flow-components/tutorial-how-to-use-webjars.asciidoc, line 139 at r1](https://reviewable.io:443/reviews/vaadin/flow/2756#-KxC6efyjI_-nw4-Vq5x:-KxC6efyjI_-nw4-Vq5y:bsp66l7) ([raw file](https://github.com/vaadin/flow/blob/3e2f9de9b556ddbd568a6be0515d89a9792757e3/flow-documentation/flow-components/tutorial-how-to-use-webjars.asciidoc#L139)):*
> ```AsciiDoc
> 
> A big help in resolving those kind of issues is a command that prints dependency tree for the project.
> For Maven this can be achieved with `mvn dependency:tree` command.
> ```

I suggest removing the last sentence and adding the command as a code block instead of inline code.

---

*[flow-documentation/flow-components/tutorial-how-to-use-webjars.asciidoc, line 146 at r1](https://reviewable.io:443/reviews/vaadin/flow/2756#-KxC8Tn2YH-Qo7C7ZbYF:-KxC8Tn2YH-Qo7C7ZbYG:bcb5tad) ([raw file](https://github.com/vaadin/flow/blob/3e2f9de9b556ddbd568a6be0515d89a9792757e3/flow-documentation/flow-components/tutorial-how-to-use-webjars.asciidoc#L146)):*
> ```AsciiDoc
> == Alternative ways with WebJars
> 
> Currently no better webjars' analog was found, but Flow eases the pain having predefined
> ```

`eases the pain having bom and dependency ...` -> `eases the pain by having a bom and the dependency ... webjars already resolved`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2756)*

**Comment by SomeoneToIgnore** [comment]
Review status: all files reviewed at latest revision, 21 unresolved discussions.

---

*[flow-documentation/flow-components/tutorial-flow-components-setup.asciidoc, line 119 at r1](https://reviewable.io:443/reviews/vaadin/flow/2756#-KxBvwDW6jYTZFHueQEQ:-KxC9gPOfPCS8vHBMASo:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/639d17c70ef963c831b77394d295d9b224b2e64a/flow-documentation/flow-components/tutorial-flow-components-setup.asciidoc#L119)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Not your patch's fault, but there's a typo on `wne`.
</blockquote></details>

Done.

---

*[flow-documentation/flow-components/tutorial-flow-components-setup.asciidoc, line 120 at r1](https://reviewable.io:443/reviews/vaadin/flow/2756#-KxBwJX6QCBYG3NdVThK:-KxC9iL_eFmsW7Tf3SDG:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/639d17c70ef963c831b77394d295d9b224b2e64a/flow-documentation/flow-components/tutorial-flow-components-setup.asciidoc#L120)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Missing period at the end of the sentence.
</blockquote></details>

Done.

---

*[flow-documentation/flow-components/tutorial-flow-components-setup.asciidoc, line 121 at r1](https://reviewable.io:443/reviews/vaadin/flow/2756#-KxBwD2cIJdezWGSkVGT:-KxC9mqJdVhhL3puJ38l:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/639d17c70ef963c831b77394d295d9b224b2e64a/flow-documentation/flow-components/tutorial-flow-components-setup.asciidoc#L121)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

`It is also can be used` -> `It also can be used`
</blockquote></details>

Done.

---

*[flow-documentation/flow-components/tutorial-flow-components-setup.asciidoc, line 160 at r1](https://reviewable.io:443/reviews/vaadin/flow/2756#-KxBxeFAIMvCk3PKHpPH:-KxCA18G6nDcLZnvLunZ:b-xs3x0a) ([raw file](https://github.com/vaadin/flow/blob/639d17c70ef963c831b77394d295d9b224b2e64a/flow-documentation/flow-components/tutorial-flow-components-setup.asciidoc#L160)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

I think we don't have a proper format convention on the name of the project, but I saw several places using Flow instead of `flow`. Your call if you want to fix it.
</blockquote></details>

Replaced to Flow.

---

*[flow-documentation/flow-components/tutorial-flow-components-setup.asciidoc, line 163 at r1](https://reviewable.io:443/reviews/vaadin/flow/2756#-KxBwf7fNuzP3G_8qjG_:-KxCA5Fp50JZjMfep-WE:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/639d17c70ef963c831b77394d295d9b224b2e64a/flow-documentation/flow-components/tutorial-flow-components-setup.asciidoc#L163)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

`allows` -> `allowing`
</blockquote></details>

Done.

---

*[flow-documentation/flow-components/tutorial-flow-components-setup.asciidoc, line 173 at r1](https://reviewable.io:443/reviews/vaadin/flow/2756#-KxBx7XIL7flLCZiOYIF:-KxCA9iF1yjujDm0d-LT:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/639d17c70ef963c831b77394d295d9b224b2e64a/flow-documentation/flow-components/tutorial-flow-components-setup.asciidoc#L173)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

I suggest using `content://frontend` (with ` for formatting the value as code). This applies to the other mentions in this file as well (as in `content://frontend-es5`).
</blockquote></details>

Done.

---

*[flow-documentation/flow-components/tutorial-flow-webjars.asciidoc, line 7 at r1](https://reviewable.io:443/reviews/vaadin/flow/2756#-KxBy3RgwpZz9S4JZmsM:-KxCAM2xsnXc2aqYS8Ag:bo6apac) ([raw file](https://github.com/vaadin/flow/blob/639d17c70ef963c831b77394d295d9b224b2e64a/flow-documentation/flow-components/tutorial-flow-webjars.asciidoc#L7)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

This sentence feels incomplete.
</blockquote></details>

Indeed.

---

*[flow-documentation/flow-components/tutorial-flow-webjars.asciidoc, line 8 at r1](https://reviewable.io:443/reviews/vaadin/flow/2756#-KxByEUsyYX6LlFvBvY0:-KxCAc8uoLzN1Le4vm2U:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/639d17c70ef963c831b77394d295d9b224b2e64a/flow-documentation/flow-components/tutorial-flow-webjars.asciidoc#L8)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

`how to use WebJars is arbitrary project` ->  `how to use WebJars in an arbitrary project`
</blockquote></details>

Done.

---

*[flow-documentation/flow-components/tutorial-flow-webjars.asciidoc, line 18 at r1](https://reviewable.io:443/reviews/vaadin/flow/2756#-KxBy_v7Psuhfa4RG1OS:-KxCC-fFocdPHo9P21Dv:b92bt5n) ([raw file](https://github.com/vaadin/flow/blob/639d17c70ef963c831b77394d295d9b224b2e64a/flow-documentation/flow-components/tutorial-flow-webjars.asciidoc#L18)):*
> In the future, Polymer 3.0 will migrate to npm and yarn instead.

Done with slight changes.

---

*[flow-documentation/flow-components/tutorial-flow-webjars.asciidoc, line 24 at r1](https://reviewable.io:443/reviews/vaadin/flow/2756#-KxBz456s_kv-eNxUoyp:-KxCC6SPjW2Kdh-W7bQ_:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/639d17c70ef963c831b77394d295d9b224b2e64a/flow-documentation/flow-components/tutorial-flow-webjars.asciidoc#L24)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

`it would be nice` -> `it is possible to`
</blockquote></details>

Done.

---

*[flow-documentation/flow-components/tutorial-flow-webjars.asciidoc, line 29 at r1](https://reviewable.io:443/reviews/vaadin/flow/2756#-KxC02c0ftY5QE82XnTx:-KxCCEgmJUtIWHbha2tz:bmqjz93) ([raw file](https://github.com/vaadin/flow/blob/639d17c70ef963c831b77394d295d9b224b2e64a/flow-documentation/flow-components/tutorial-flow-webjars.asciidoc#L29)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

I'd call it a conclusion instead of summary - this chapter looks more like a justification of the current approach than a list of possible options.
</blockquote></details>

Done + removed the part mentioned here.

---

*[flow-documentation/flow-components/tutorial-flow-webjars.asciidoc, line 31 at r1](https://reviewable.io:443/reviews/vaadin/flow/2756#-KxC0vB431Dz41mKE8mV:-KxCCS5CnU5CMXQ_1-RL:bm7tlr0) ([raw file](https://github.com/vaadin/flow/blob/639d17c70ef963c831b77394d295d9b224b2e64a/flow-documentation/flow-components/tutorial-flow-webjars.asciidoc#L31)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

`(Gradle)` -> `(or Gradle)`
</blockquote></details>

Replaced with `Build system plugin to download bower dependencies`

---

*[flow-documentation/flow-components/tutorial-flow-webjars.asciidoc, line 55 at r1](https://reviewable.io:443/reviews/vaadin/flow/2756#-KxC1ONN0PRguS2JXgRT:-KxCC_WHUP_-KmFLY6tz:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/639d17c70ef963c831b77394d295d9b224b2e64a/flow-documentation/flow-components/tutorial-flow-webjars.asciidoc#L55)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Missing capital B at the start of the sentence.
</blockquote></details>

Done.

---

*[flow-documentation/flow-components/tutorial-flow-webjars.asciidoc, line 88 at r1](https://reviewable.io:443/reviews/vaadin/flow/2756#-KxC5a8JdDeYDw7-Qs9Z:-KxCCcOW9JagMBeQ1vz6:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/639d17c70ef963c831b77394d295d9b224b2e64a/flow-documentation/flow-components/tutorial-flow-webjars.asciidoc#L88)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

`MavenCentral` -> `Maven Central`
</blockquote></details>

Done.

---

*[flow-documentation/flow-components/tutorial-how-to-use-webjars.asciidoc, line 59 at r1](https://reviewable.io:443/reviews/vaadin/flow/2756#-KxC4peJHceZMvBCX-EU:-KxCChcjhLBqte2P85lk:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/639d17c70ef963c831b77394d295d9b224b2e64a/flow-documentation/flow-components/tutorial-how-to-use-webjars.asciidoc#L59)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

`a conflict between` -> `a conflict among different versions of the package`
</blockquote></details>

Done.

---

*[flow-documentation/flow-components/tutorial-how-to-use-webjars.asciidoc, line 66 at r1](https://reviewable.io:443/reviews/vaadin/flow/2756#-KxC5BVyJ3F3yyxYhWhZ:-KxCCpN-tAr1wXhWiHvN:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/639d17c70ef963c831b77394d295d9b224b2e64a/flow-documentation/flow-components/tutorial-how-to-use-webjars.asciidoc#L66)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

`the more probability` -> `the greater is the probability of`
</blockquote></details>

Done.

---

*[flow-documentation/flow-components/tutorial-how-to-use-webjars.asciidoc, line 85 at r1](https://reviewable.io:443/reviews/vaadin/flow/2756#-KxC5khfsY-2-So8nm1c:-KxCD5ZD4VFqRv1YbRjq:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/639d17c70ef963c831b77394d295d9b224b2e64a/flow-documentation/flow-components/tutorial-how-to-use-webjars.asciidoc#L85)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

I suggest adding a full, copy-pastable example:

```
mvn clean install -U
```
</blockquote></details>

Done.

---

*[flow-documentation/flow-components/tutorial-how-to-use-webjars.asciidoc, line 102 at r1](https://reviewable.io:443/reviews/vaadin/flow/2756#-KxC68x12aoiCZmZr-No:-KxCDCZpvEIVClIj39Gu:bpqvqne) ([raw file](https://github.com/vaadin/flow/blob/639d17c70ef963c831b77394d295d9b224b2e64a/flow-documentation/flow-components/tutorial-how-to-use-webjars.asciidoc#L102)):*

I've got one 

> image:../images/webjars_ui.png[WebJars UI]

with all the buttons and other windows require to publish an artifact which I don't want to do.

---

*[flow-documentation/flow-components/tutorial-how-to-use-webjars.asciidoc, line 123 at r1](https://reviewable.io:443/reviews/vaadin/flow/2756#-KxC6W0gVo-fTZ_yvjtm:-KxCDpQ8KV5wxnbndimP:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/639d17c70ef963c831b77394d295d9b224b2e64a/flow-documentation/flow-components/tutorial-how-to-use-webjars.asciidoc#L123)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Missing capital T.
</blockquote></details>

Done.

---

*[flow-documentation/flow-components/tutorial-how-to-use-webjars.asciidoc, line 139 at r1](https://reviewable.io:443/reviews/vaadin/flow/2756#-KxC6efyjI_-nw4-Vq5x:-KxCG3dRL4mTNIC-85lO:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/639d17c70ef963c831b77394d295d9b224b2e64a/flow-documentation/flow-components/tutorial-how-to-use-webjars.asciidoc#L139)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

I suggest removing the last sentence and adding the command as a code block instead of inline code.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2756)*

**Comment by SomeoneToIgnore** [comment]
*[flow-documentation/flow-components/tutorial-how-to-use-webjars.asciidoc, line 146 at r1](https://reviewable.io:443/reviews/vaadin/flow/2756#-KxC8Tn2YH-Qo7C7ZbYF:-KxCGV0bGr9CIm-g24uJ:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/639d17c70ef963c831b77394d295d9b224b2e64a/flow-documentation/flow-components/tutorial-how-to-use-webjars.asciidoc#L146)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

`eases the pain having bom and dependency ...` -> `eases the pain by having a bom and the dependency ... webjars already resolved`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2756)*

**Comment by gilberto-torrezan** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-documentation/flow-components/tutorial-flow-webjars.asciidoc, line 7 at r2](https://reviewable.io:443/reviews/vaadin/flow/2756#-KxCOBtsvQaiGWOo68Jr:-KxCOBtsvQaiGWOo68Js:b-89bmap) ([raw file](https://github.com/vaadin/flow/blob/60f9890c9ed1502e08a926298e18ea44a0c40c2d/flow-documentation/flow-components/tutorial-flow-webjars.asciidoc#L7)):*
> ```AsciiDoc
> ---
> 
> This tutorial is intended to explain what options the user when he's willing to use web components in the project.
> ```

Bright back the `has` -> `what options the user [has] when he's ...`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2756)*

**Comment by SomeoneToIgnore** [comment]
*[flow-documentation/flow-components/tutorial-flow-webjars.asciidoc, line 7 at r2](https://reviewable.io:443/reviews/vaadin/flow/2756#-KxCOBtsvQaiGWOo68Jr:-KxCP0cQqtVYskw4Yx3p:b-9yy7en) ([raw file](https://github.com/vaadin/flow/blob/60f9890c9ed1502e08a926298e18ea44a0c40c2d/flow-documentation/flow-components/tutorial-flow-webjars.asciidoc#L7)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Bright back the `has` -> `what options the user [has] when he's ...`
</blockquote></details>

Right, done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2756)*

**Comment by gilberto-torrezan** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2756)*

**Pull request merged**
