### PR TITLE
Log the actual cause of errors from execJavaScript

### PR DESCRIPTION
**Pull request by Legioth**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3858)

### CODE REVIEW

**Comment by gilberto-torrezan** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ClientSideExceptionHandlingView.java, line 37 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3858#-L9ndGEX13YOYn6XbpAW:-L9ndGEX13YOYn6XbpAX:b-n3vpre) ([raw file](https://github.com/vaadin/flow/blob/ee85430ef90f7a7d1cfd3e2b087fd30dfa632328/flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ClientSideExceptionHandlingView.java#L37)):*
> ```Java
>         causeException.setId(CAUSE_EXCEPTION_ID);
> 
>         NativeButton causeExternalException = new NativeButton(
> ```

Missing an IT that uses this button.

---

*[flow-tests/test-root-context/src/main/webapp/frontend/externalErrorTrigger.js, line 3 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3858#-L9ncDpp4_1aKv7Cm8yt:-L9ncDpp4_1aKv7Cm8yu:b-czqoko) ([raw file](https://github.com/vaadin/flow/blob/ee85430ef90f7a7d1cfd3e2b087fd30dfa632328/flow-tests/test-root-context/src/main/webapp/frontend/externalErrorTrigger.js#L3)):*
> ```JavaScript
> window.externalErrorTrigger = function() {
> 	null.bar;
> }
> ```

Evil tab instead of space, and missing new line

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3858)*

**Comment by Legioth** [comment]
Review status: 3 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ClientSideExceptionHandlingView.java, line 37 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3858#-L9ndGEX13YOYn6XbpAW:-L9nhDz70mxfOiI06ayI:b-ubpmec) ([raw file](https://github.com/vaadin/flow/blob/ee85430ef90f7a7d1cfd3e2b087fd30dfa632328/flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ClientSideExceptionHandlingView.java#L37)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Missing an IT that uses this button.
</blockquote></details>

I don't know how to make that IT test the only thing that is relevant there, namely that the correct stacktrace will be logged by the browser's native uncaught exception handerl´

---

*[flow-tests/test-root-context/src/main/webapp/frontend/externalErrorTrigger.js, line 3 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3858#-L9ncDpp4_1aKv7Cm8yt:-L9nhXAF9Qzs1Zb3gPCl:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/ee85430ef90f7a7d1cfd3e2b087fd30dfa632328/flow-tests/test-root-context/src/main/webapp/frontend/externalErrorTrigger.js#L3)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Evil tab instead of space, and missing new line
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3858)*

**Comment by gilberto-torrezan** [comment]
Review status: 3 of 4 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ClientSideExceptionHandlingView.java, line 37 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3858#-L9ndGEX13YOYn6XbpAW:-L9njX3TD1iYZ_wQSsbQ:b-w7um7v) ([raw file](https://github.com/vaadin/flow/blob/ee85430ef90f7a7d1cfd3e2b087fd30dfa632328/flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ClientSideExceptionHandlingView.java#L37)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

I don't know how to make that IT test the only thing that is relevant there, namely that the correct stacktrace will be logged by the browser's native uncaught exception handerl´
</blockquote></details>

In this case I suggest adding a comment then, stating that this button is there for manual testing only (to prevent someone from removing it).

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3858)*

**Comment by gilberto-torrezan** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3858)*

**Comment by Legioth** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ClientSideExceptionHandlingView.java, line 37 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3858#-L9ndGEX13YOYn6XbpAW:-L9nxsFB6OsrTBx5RLHc:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/ee85430ef90f7a7d1cfd3e2b087fd30dfa632328/flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ClientSideExceptionHandlingView.java#L37)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

In this case I suggest adding a comment then, stating that this button is there for manual testing only (to prevent someone from removing it).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3858)*

**Comment by gilberto-torrezan** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3858#-:-L9o6rgh6CLbnI6axnXk:bnfp4nl)*

**Pull request merged**
