### PR TITLE
Fix parameter serialisation for Router:getUrl

### PR DESCRIPTION
**Pull request by caalador**
Parameter serialisation for get URL should not require
instantiation.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3022)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 1 of 4 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3022)*

**Comment by denis-anisimov** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-server/src/main/java/com/vaadin/router/ParameterSerializer.java, line 26 at r3](https://reviewable.io:443/reviews/vaadin/flow/3022#-KzbeBTuq1y9u-V4nyfT:-KzbeBTuq1y9u-V4nyfU:b-ntawqm) ([raw file](https://github.com/vaadin/flow/blob/a85e2a2a7e3c69903ba13d9c8a0526237e72f629/flow-server/src/main/java/com/vaadin/router/ParameterSerializer.java#L26)):*
>   type parameter type

Tautology: doesn't explain anything.
Type parameter of what ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3022)*

**Comment by caalador** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-server/src/main/java/com/vaadin/router/ParameterSerializer.java, line 26 at r3](https://reviewable.io:443/reviews/vaadin/flow/3022#-KzbeBTuq1y9u-V4nyfT:-KzbituFY-ZFuO3TZQHo:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/a85e2a2a7e3c69903ba13d9c8a0526237e72f629/flow-server/src/main/java/com/vaadin/router/ParameterSerializer.java#L26)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

>   type parameter type

Tautology: doesn't explain anything.
Type parameter of what ?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3022)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3022)*

**Comment by Legioth** [comment]
I see a couple of problems with the design as implemented by the current design:
1) We still don't have any real-world use case for this, only theoretical cases where it would be convenient. 
2) This puts the burden on the caller of `getUrl` to know what conventions the target's `deserializeUrlParameters` implementation is using.

For 1., I don't have any real solutions (except dropping the *entire* feature until a case is found). For 2., I'd suggest also moving `deserializeUrlParameters` to the same interface and introduce an annotation on the navigation target that points to the `ParameterSerializer` implementation that should be used together with that navigation target. In that way, related logic is in the same class and the caller of `getUrl` doesn't have to know that there's anything special with that particular navigation target.

**Pull request merged**
