### PR TITLE
Remove redundant type arguments.

### PR DESCRIPTION
**Pull request by asashour**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/2990)

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2990#-KzSioNcrpLc8vQ6GQwV:-KzSioNcrpLc8vQ6GQwW:bbjuagp) (no related file):*
I propose to fix `ComponentMetaData::findDependencies` in the same PR also.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2990)*

**Comment by SomeoneToIgnore** [comment]
Just in case you're interested in more bulk changes, fixing raw types usage and throwing away corresponding `@SuppressWarnings` whenever possible would be super cool.
Idea has two inspections for this at least: `Raw type can be generic` and `Raw use of parameterized class`.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2990#-:-KzSkDOuP-336klF74OM:b-uddx0m)*

**Comment by asashour** [comment]
Sure, I would like to remove all project warnings.  I use Eclipse at the moment.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2990#-KzSioNcrpLc8vQ6GQwV:-KzSlu_Lw8wJBfSxegnu:bemxjdi) (no related file):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

I propose to fix `ComponentMetaData::findDependencies` in the same PR also.
</blockquote></details>

Can you please explain what the issue with `ComponentMetaData::findDependencies` is?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2990#-:-KzSllLgWh8tzdlwpWQY:b-v9p8p0)*

**Comment by SomeoneToIgnore** [comment]
Wow, thanks.
Any reason you try to do it? Because it may be a bit futile, since I cannot guarantee that no new warnings will appear in the project in the future.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2990#-KzSioNcrpLc8vQ6GQwV:-KzSlGnRn0AqF7Mt8zvQ:b-jaoqqy) (no related file):*
<details><summary><i>Previously, asashour (Ahmed Ashour) wrote…</i></summary><blockquote>

Can you please explain what the issue with `ComponentMetaData::findDependencies` is?
</blockquote></details>

The issue is here: 
`findDependencies(componentClass, dependencyInfo, new HashSet<Class<? extends Component>>()); `

This method seems to be the last in the project now with unnecessary generics, so why not change it in the same PR?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2990#-:-KzSmUMNH001UXAVJuCG:b-f4qgtz)*

**Comment by asashour** [comment]
Actually, I see them a little distracting, because there is a small yellow [triangle](https://www.eclipse.org/webtools/dali/docs/3.2/user_guide/img/error_sample.png), which denotes warning.

---

Review status: 5 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2990#-KzSioNcrpLc8vQ6GQwV:-KzSrw-DvXXippU5XpUK:b277jd3) (no related file):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

The issue is here: 
`findDependencies(componentClass, dependencyInfo, new HashSet<Class<? extends Component>>()); `

This method seems to be the last in the project now with unnecessary generics, so why not change it in the same PR?
</blockquote></details>

Done, it seems it was missed by Eclipse compiler.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2990#-:-KzSosCiZCLfNvDYzh8s:bq2rech)*

**Comment by SomeoneToIgnore** [comment]
Ok, up to you.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2990#-KzSioNcrpLc8vQ6GQwV:-KzSsBhaDa1-q9np4YES:b-ucfkn4) (no related file):*
<details><summary><i>Previously, asashour (Ahmed Ashour) wrote…</i></summary><blockquote>

Done, it seems it was missed by Eclipse compiler.
</blockquote></details>

Thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2990#-:-KzSs89e_-Xl91vAoLLX:bl05iuc)*

**Comment by SomeoneToIgnore** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2990#-:-KzSsFSkHr2xP6CvYUzt:bnfp4nl)*

**Pull request merged**
