### PR TITLE
Rename packages in the server module

### PR DESCRIPTION
**Pull request by denis-anisimov**
Part of #3032

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3167)

### CODE REVIEW

**Comment by caalador** [comment]
Reviewed 833 of 833 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3167)*

**Comment by pleku** [comment]
Reviewed 12 of 949 files at r1, 3 of 238 files at r2, 468 of 1024 files at r3.
Review status: 576 of 1062 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3167#-L0VmhidJEEpPQnW1Gh4:-L0VmhieVtSfDAZWOjQr:brahf73) (no related file):*
Noticed that there is lot of event stuff now in `com.vaadin.flow.component` that used to be in a subpackage `event` before. This would mayhaps mean that we stop using the `event` subpackage anywhere in Flow ? @legioth 

At least it reduces the imports since there is a lot of things in that package that are tied together (component & events & listeners)

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3167#-L0VnhsNgTrAP_Tg8w0T:-L0VnhsNgTrAP_Tg8w0U:b4pjaqq) (no related file):*
> com.vaadin.flow.component.internal.KeyboardEvent;

Not sure why this should be in `internal` since it is e.g. used in `KeyEventListener` which is not internal

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3167)*

**Comment by denis-anisimov** [comment]
Review status: 476 of 1062 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3167#-L0VmhidJEEpPQnW1Gh4:-L0Ypiu-IwASEj9f1phO:b-yqdtpe) (no related file):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Noticed that there is lot of event stuff now in `com.vaadin.flow.component` that used to be in a subpackage `event` before. This would mayhaps mean that we stop using the `event` subpackage anywhere in Flow ? @legioth 

At least it reduces the imports since there is a lot of things in that package that are tied together (component & events & listeners)
</blockquote></details>

Done because of:

`Avoid into .util or .event packages`.

Let's decide whether we still want to have `event` package.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3167#-L0VnhsNgTrAP_Tg8w0T:-L0Yq4OpG6r4mbBBFklC:b-vwx25f) (no related file):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> com.vaadin.flow.component.internal.KeyboardEvent;

Not sure why this should be in `internal` since it is e.g. used in `KeyEventListener` which is not internal
</blockquote></details>

You are right.
Thanks.
Decided to move it into internal because it's abstract (not abstract classes are not in `internal`).
But sine it's used in public API then it shouldn't be internal.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3167)*

**Comment by caalador** [comment]
Reviewed 97 of 952 files at r1, 108 of 238 files at r2, 859 of 1029 files at r3, 164 of 164 files at r4, 6 of 6 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3167)*

**Comment by pleku** [comment]
:lgtm:

I've brought up maybe missed things in slack, let's change those in separate PR if necessary, those are just internal parts in `server`

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3167#-:-L0cNQl5jos0eGs5fIy4:bbctf0h)*

**Pull request merged**
