### PR TITLE
Convenience methods for RoutesChangedEvent #5310

### PR DESCRIPTION
**Pull request by thiyagu-7**
Adding isRouteAdded, isRouteRemoved, isPathAdded and isPathRemoved methods to RoutesChangedEvent.

This simplifies the client code to know if a route (represented by a URL or a `Component` class) was added or removed during the change.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/6853)

### CODE REVIEW

**Comment by Legioth** [comment]
I kind-of appreciate the idea behind this, but I'd still like to understand the exact use case for when it's useful to have this info.

I'm also not 100% sure about the exact method naming. We've used "navigation target" rather than "route" in most cases, though that would make the API quite verbose in this case. Would there be any other alternatives?

**Comment by pleku** [comment]
>I kind-of appreciate the idea behind this, but I'd still like to understand the exact use case for when it's useful to have this info.

@Legioth The use case for the API is for instance building a stand-alone navigation menu for your application. This could of course be a feature of a such component (like `AppLayout`), but I see that many applications will anyway choose to build their own menu which would also benefit from reduced boilerplate.

**Comment by pleku** [comment]
Hi @thiyagu-7 and thanks for the contribution. Sorry that this has not progressed as the release window for 2.1 was already closed for this and we have been looking at other things. Now it would be possible to get this in for 2.2.

Would you also be interested in adding the API described here https://github.com/vaadin/flow/pull/6853#issuecomment-551448581 ? Or should we go about it ourselves.

**Comment by thiyagu-7** [comment]
> Hi @thiyagu-7 and thanks for the contribution. Sorry that this has not progressed as the release window for 2.1 was already closed for this and we have been looking at other things. Now it would be possible to get this in for 2.2.
> 
> Would you also be interested in adding the API described here [#6853 (comment)](https://github.com/vaadin/flow/pull/6853#issuecomment-551448581) ? Or should we go about it ourselves.

Hi. I missed the notification somehow. Please go ahead with your changes.

**Comment by jm-ferreira** [comment]
> > Hi @thiyagu-7 and thanks for the contribution. Sorry that this has not progressed as the release window for 2.1 was already closed for this and we have been looking at other things. Now it would be possible to get this in for 2.2.
> > Would you also be interested in adding the API described here [#6853 (comment)](https://github.com/vaadin/flow/pull/6853#issuecomment-551448581) ? Or should we go about it ourselves.
> 
> Hi. I missed the notification somehow. Please go ahead with your changes.

@thiyagu-7 , we have implemented more methods in addition to the code you delivered, so we could provide a more extended API. Your code was very useful and we are most certainly going to use it. We've made some adjustments to the JavaDocs you provided in order to keep them streamlined with the rest of the docs in our repo.
In name of everybody at Vaadin we value and thank you for your contribution. Keep up the good work!

**Pull request merged**
