### PR TITLE
chore: add dummy class to get javadocs generated

### PR DESCRIPTION
**Pull request by pleku**

### CODE REVIEW

**Comment by pleku** [comment]
@caalador I don't know if we should merge this or test the dokka plugin if it works on top of master branch ?

**Comment by manolo** [comment]
JVM crashed, re-running

**Review by manolo — APPROVED** [review]

**Comment by caalador** [comment]
If you want to test there is the branch `gradle/javaDoc` with dokka for master.
Else as the JavaDoc is not used I would be fine with this also.

**Comment by pleku** [comment]
This caused other issues, and it seems that the dokka plugin started to work today so we're retrying in 7.0 with that https://bender.vaadin.com/viewLog.html?buildId=234529&buildTypeId=Flow_Flow70_Flow70Snapshot

**Pull request closed without merging**
