### PR TITLE
chore: Upgrade to Spring Boot 3 RC1

### PR DESCRIPTION
**Pull request by Artur-**

### CODE REVIEW

**Comment by vursen** [comment]
I wonder if it should be something other than a chore taking into account that the PR drops `VaadinWebSecurityConfigurerAdapter.java`.

**Comment by Artur-** [comment]
Updated to slf4j 2.0.3 which Spring Boot 3 RC1 uses

**Comment by Artur-** [comment]
> I wonder if it should be something other than a chore taking into account that this PR drops `VaadinWebSecurityConfigurerAdapter.java`.

I can extract that into a separate PR that would be `chore!` and which would make sense in release notes

**Comment by Artur-** [comment]
This probably cannot work before https://github.com/spring-projects/spring-authorization-server/milestone/19 is released

**Comment by knoobie** [comment]
> [chore(deps): bump slf4j.version from 1.7.36 to 2.0.3](https://github.com/vaadin/flow/pull/14911/commits/3517c94715c049ddba94dbe52e8539c33a8dec91)

Should this be done seperatly as well as? See discussion here https://github.com/vaadin/flow/pull/14409

**Comment by Artur-** [comment]
Well Spring Boot 3 RC1 depends on slf4j 2.0.3 so at least this project does not work when mixing the versions

**Comment by knoobie** [comment]
Yeah :) I'm not against the updated, would just recommend to do it first as `chore!` so that people know about this once their update to V24

**Comment by Artur-** [comment]
Yep, probably does not work with Spring Boot M5 though, that uses slf4j 1.7...

Maybe we can make the "Upgrade to Spring Boot 3" PR with `!`and list the relevant info there

**Comment by knoobie** [comment]
It should work 🙂 it was already in master some weeks ago and build successfully on M4 or so and was reverted by @mshabarov after my comment

**Comment by Artur-** [comment]
Let's see then

**Comment by Artur-** [comment]
#14916 indeed looks pretty 🍏

**Comment by Artur-** [comment]
Depends on #14916 , otherwise should be ok

**Review by mshabarov — APPROVED** [review]

**Pull request merged**
