### PR TITLE
fix: clean commented css before handling

### LINKED ISSUE #14770: Commenting @import in styles.css gives net::ERR_ABORTED 404
### Description of the bug

image

(File exists on disk)

image

### Expected behavior

Parser should ignore everything in comments

### Minimal reproducible example

`/*@import "my-style.css";*/`

### Versions

Hilla: 23.2.3
Flow: 23.2.3
Java: JetBrains s.r.o. 17.0.2
OS: amd64 Windows 10 10.0
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
Live reload: Java active (HotswapAgent): Front end active

### PR DESCRIPTION
**Pull request by caalador**
Remove any comment blocks in CSS
before creating link references.

Fixes #14770

### CODE REVIEW

**Review by Artur- — COMMENTED** [review]
Would it make sense to use e.g. https://www.npmjs.com/package/strip-comments instead?

**Comment by caalador** [comment]
Does it note that http://... the // is not a comment and to only handle block comments?
Need to test.

**Comment by Artur-** [comment]
"Strip line and/or block comments from a string. Blazing fast, and works with JavaScript, Sass, CSS, Less.js, and a number of other languages."

"block {Boolean}: if false strip only line comments, default true"

**Comment by caalador** [comment]
Testing say seems to work.
Drops away upkeep from us, even though it is 90 lines more than our own with strange regex handling.

**Review by Artur- — DISMISSED** [review]

**Comment by caalador** [comment]
Seems it removes something extra. I'll try to investigate what and from where exactly.

**Comment by caalador** [comment]
Couldn't get strip-comments to not remove line comment for `url(http://` even with the setting to ignore line comments.
Changed to strip-css-comments which is more css specific and doesn't handle css as javascript

**Review by Artur- — APPROVED** [review]

**Pull request merged**
