### PR TITLE
Improve tutorial and javaDoc for HasErrorParameter

### PR DESCRIPTION
**Pull request by caalador**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3261)

### CODE REVIEW

**Comment by ZheSun88** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3261)*

**Comment by ahie** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[flow-server/src/main/java/com/vaadin/flow/router/HasErrorParameter.java, line 25 at r1](https://reviewable.io:443/reviews/vaadin/flow/3261#-L2031qGfmFjKqcUrdRJ-r1-25:-L20UcI1CGqBXZ1Svu-x:b-qi0pqw) ([raw file](https://github.com/vaadin/flow/blob/c932af01ce459f2e930fa1182f1f6dc2b7945c78/flow-server/src/main/java/com/vaadin/flow/router/HasErrorParameter.java#L25)):*
> Document the parameter(s)

+1

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3261)*

**Comment by denis-anisimov** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3261#-L20jeXYsTRyggVBYKBQ:-L20jeXZwqdkAOuLQR05:b-ahm30d) (no related file):*
This PR still doesn't solve the issue.

There are two additions : 
- a handler for `AccessDeniedException`
- reroute to a handler using the `rerouteToError` method.

So those additions are about _handlers_.

What I don't understand is: at which point the handlers are invoked?
What if I have my own (or existing exception, it doesn't matter) and I throw it in my code.
At which point I should throw it so that some handler is invoked?

Apparently the exception should be thrown somehow during a navigation (if I throw an exception during e.g. a click handler then handler won't be invoked).
So I would like to understand:
- the exact description when and how should I throw an exception so that the handler is invoked (may I throw such exception at all?).
- some examples when the handler is definitely not invoked (unexpected usage).

At the moment there are examples:
- `NotFoundException` : the exception which is thrown somehow internally by the core itself. Not intended to be thrown by the developer
- `AccessDeniedException` : there  is a handler but not the code which throws this exception.

So it's not clear how the developer may throw the custom exception so that its handler is invoked.
That's what I meant in the ticket at least.

`AccessDeniedException` is a good example actually. But there should be a code which throws this exception.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3261)*

**Comment by caalador** [comment]
Review status: 1 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3261#-L20jeXYsTRyggVBYKBQ:-L23vTA0HO7ZqCxbMgJC:bok72jc) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

This PR still doesn't solve the issue.

There are two additions : 
- a handler for `AccessDeniedException`
- reroute to a handler using the `rerouteToError` method.

So those additions are about _handlers_.

What I don't understand is: at which point the handlers are invoked?
What if I have my own (or existing exception, it doesn't matter) and I throw it in my code.
At which point I should throw it so that some handler is invoked?

Apparently the exception should be thrown somehow during a navigation (if I throw an exception during e.g. a click handler then handler won't be invoked).
So I would like to understand:
- the exact description when and how should I throw an exception so that the handler is invoked (may I throw such exception at all?).
- some examples when the handler is definitely not invoked (unexpected usage).

At the moment there are examples:
- `NotFoundException` : the exception which is thrown somehow internally by the core itself. Not intended to be thrown by the developer
- `AccessDeniedException` : there  is a handler but not the code which throws this exception.

So it's not clear how the developer may throw the custom exception so that its handler is invoked.
That's what I meant in the ticket at least.

`AccessDeniedException` is a good example actually. But there should be a code which throws this exception.
</blockquote></details>

Some rewording, longer, bigger example.
I'm getting the feeling that someone else should update this as I'm too close to the source functionality.

---

*[flow-server/src/main/java/com/vaadin/flow/router/HasErrorParameter.java, line 25 at r1](https://reviewable.io:443/reviews/vaadin/flow/3261#-L2031qGfmFjKqcUrdRJ-r1-25:-L23dFpRyfHLfGYUJvml:bqqoayk) ([raw file](https://github.com/vaadin/flow/blob/c932af01ce459f2e930fa1182f1f6dc2b7945c78/flow-server/src/main/java/com/vaadin/flow/router/HasErrorParameter.java#L25)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

> Document the parameter(s)

+1
</blockquote></details>

It is added in #3260 so it will come in from there.
Was expecting Denis to look at this on monday not asap.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3261)*

**Comment by denis-anisimov** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3261)*

**Comment by denis-anisimov** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3261)*

**Pull request merged**
