### PR TITLE
Update generator to support the new SerializableBiFunction constructor

### PR DESCRIPTION
**Pull request by gilberto-torrezan**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/4033)

### CODE REVIEW

**Comment by caalador** [comment]
:lgtm:

---

Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4033#-:-LBK6nWw4zBxB8wRSe4b:bnfp4nl)*

**Comment by denis-anisimov** [comment]
Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow/4033#-LBK7wyL-FQ2CE2qaKaA:-LBK7wyL-FQ2CE2qaKaB:b2xaydi) (no related file):*
No tests ?

---

*[flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/ComponentGenerator.java, line 624 at r1](https://reviewable.io/reviews/vaadin/flow/4033#-LBK6s-CD_IWgiKDaGMF:-LBK6s-D-8vnG6_K1aek:brt6cyo) ([raw file](https://github.com/vaadin/flow/blob/99c96f75b62827fefe8421a89d9cd758aa5f9293/flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/ComponentGenerator.java#L624)):*
> ```
> "Constructor."
> ```

This is tautology.
I understand that javadocs for  CTORs are always useless and we just need something to write just because.
But mat be better to use "Creates a new XXX class instance" ?

Or is it not new but just used way to generate javadocs ?
Then it's OK.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4033)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks broke.

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow/4033#-LBK7wyL-FQ2CE2qaKaA:-LBKNL8Y0dq3Sxpv_JQl:bjxgqu4) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

No tests ?
</blockquote></details>

The easiest way for adding a test is reusing those tests checking the output of  a date-picker and a checkbox like components

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4033)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks broke.

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow/4033#-LBK7wyL-FQ2CE2qaKaA:-LBKOHFoDDW4tXTacW1j:b-2vscrb) (no related file):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

The easiest way for adding a test is reusing those tests checking the output of  a date-picker and a checkbox like components
</blockquote></details>

The generator has its own generic tests which don't know anything about checkbox or date-picker (AFAIK).
I think it's easier to extend those tests instead of applying generator somehow in the tests for checkbox.
But it doesn't matter. Any way.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4033)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks broke.

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow/4033#-LBK7wyL-FQ2CE2qaKaA:-LBKb9U9C6fb2-MvEQ82:b-logv9i) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

The generator has its own generic tests which don't know anything about checkbox or date-picker (AFAIK).
I think it's easier to extend those tests instead of applying generator somehow in the tests for checkbox.
But it doesn't matter. Any way.
</blockquote></details>

What I meant is that there are two generic tests, that does not depend in any way on date-picker or checkbox, they just mock the same name and significant  properties, so as you can take the output and compare with real stuff. It resulted very useful to me to compare what I wanted to get. 

I meant these tests : https://github.com/vaadin/flow/blob/master/flow-components-parent/flow-code-generator-api/src/test/java/com/vaadin/generator/ComponentGeneratorTest.java#L955  https://github.com/vaadin/flow/blob/master/flow-components-parent/flow-code-generator-api/src/test/java/com/vaadin/generator/ComponentGeneratorTest.java#L1012 

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4033)*

**Comment by pleku** [comment]
Review status: 13 of 14 files reviewed at latest revision, 10 unresolved discussions.

---

*[flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/ComponentGenerator.java, line 624 at r1](https://reviewable.io/reviews/vaadin/flow/4033#-LBK6s-CD_IWgiKDaGMF:-LBKyXS2-P4Y2QL0HbUY:bo0zycv) ([raw file](https://github.com/vaadin/flow/blob/99c96f75b62827fefe8421a89d9cd758aa5f9293/flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/ComponentGenerator.java#L624)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
> "Constructor."
> ```

This is tautology.
I understand that javadocs for  CTORs are always useless and we just need something to write just because.
But mat be better to use "Creates a new XXX class instance" ?

Or is it not new but just used way to generate javadocs ?
Then it's OK.
</blockquote></details>

Done.

(As a side note, the whole javadocs creation and content is a total mess and lots of repeating code, but that is for you to worry and refactor in later PRs that don't block the platform release)

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4033)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4033)*

**Comment by caalador** [comment]
Review status: 4 of 15 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow/4033#-LBK7wyL-FQ2CE2qaKaA:-LBL58-j23uUoSLn-u3J:bymgseq) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Sure, no problems.
</blockquote></details>

Added tests. Generated new javadocs.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4033)*

**Comment by denis-anisimov** [comment]
:lgtm:

---

Reviewed 11 of 11 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4033#-:-LBL5PWq3Ng8IWtvi3Ih:bnfp4nl)*

**Comment by manolo** [comment]
:lgtm: 

---

Reviewed 13 of 14 files at r1, 1 of 1 files at r2, 11 of 11 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4033#-:-LBL5k3sDhZnB1kwoR_N:bg7igkv)*

**Pull request merged**
