### PR TITLE
feat: add a feature flag for new field validation behavior

### PR DESCRIPTION
**Pull request by vursen**
## Description

This PR adds a feature flag for the new field validation behavior. The flag will be used by Flow field components. For more information about the new behavior, please refer to https://github.com/vaadin/platform/issues/3066.

Part of https://github.com/vaadin/platform/issues/3066

## Type of change

- [x] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [x] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

### CODE REVIEW

**Review by mshabarov — CHANGES_REQUESTED** [review]
Conflicts with master should be resolved.

By the way, where is this flag supposed to be checked? Does the Flow's `Binder` need to check it and behave accordingly?

**Comment by vursen** [comment]
> By the way, where is this flag supposed to be checked? Does the Flow's Binder need to check it and behave accordingly?

The flag is planned to be used only in Flow field components.

**Review by mshabarov — DISMISSED** [review]

**Comment by vursen** [comment]
@yuriy-fix suggested an alternative naming for the flag: `synchronizedValidation`

**Comment by knoobie** [comment]
Another name could be `(enforce) Field / Client Validation` because it enables the field validation to run before the binder. I don't think a lot of people understand the concept of chaining and validation ordering.

**Comment by vursen** [comment]
@knoobie I agree that the current naming is not descriptive and that we need to find a better alternative. 

It is noteworthy the field constraint validation has already been somewhat integrated into the binder validation by implementing `getDefaultValidator` which is already available without feature flags, so the field validation is already enforced in a way. This is probably not a problem and your suggested naming would still work. I wonder how we should name the feature flag itself then: `enforceClientFieldValidation`? `enforceClientValidation`?

**Comment by knoobie** [comment]
> and this is already available without feature flags, so the field validation is already enforced in a way.

Oh! I was expecting the whole epic (including the field changes) would be behind the feature flag and not just the client side. (Don't mind, was just unexpected) 

> enforceClientFieldValidation

I would think this describes it the best

**Comment by vursen** [comment]
After an internal discussion, we came to the agreement that 

- We will hide everything related to the new validation behavior behind a feature flag, **including the recent `getDefaultValidator` changes** 
- We will name the feature flag `enforceFieldValidation`.

**Review by yuriy-fix — APPROVED** [review]

**Review by mshabarov — APPROVED** [review]

**Pull request merged**
