### PR TITLE
Have a dedicated WrapMode for InitialPageSettings

### LINKED ISSUE #3168: InitialPageSettings.addInlineWithContents() creates a <span> in the document head
When using `InitialPageSettings.addInlineWithContents()` to add inline HTML to the initial response, that HTML is wrapped into a `<span hidden></span>` and appended to the `<head>` of the document. Having a `<span>` inside the `<head>` element is [invalid HTML](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/head#See_also). (Chrome automatically moves such `<span>` into the `<body>`).

Example:
```java
settings.addInlineWithContents(
		"<link rel=\"shortcut icon\" href=\"icons/favicon.ico\">" +
		"<link rel=\"icon\" sizes=\"192x192\" href=\"icons/icon-192.png\">" +
		"<link rel=\"icon\" sizes=\"96x96\" href=\"icons/icon-96.png\">" +
		"<link rel=\"apple-touch-icon\" sizes=\"512x512\" href=\"icons/icon-512.png\">" +
		"<link rel=\"apple-touch-icon\" sizes=\"192x192\" href=\"icons/icon-192.png\">" +
		"<link rel=\"apple-touch-icon\" sizes=\"96x96\" href=\"icons/icon-96.png\">",
		Dependency.Type.HTML_IMPORT);
```

results in
```html
<head>
  ...
  <span hidden>
    <link href="icons/favicon.ico" rel="shortcut icon">
    <link href="icons/icon-192.png" sizes="192x192" rel="icon">
    <link href="icons/icon-96.png" sizes="96x96" rel="icon">
    <link href="icons/icon-512.png" sizes="512x512" rel="apple-touch-icon">
    <link href="icons/icon-192.png" sizes="192x192" rel="apple-touch-icon">
    <link href="icons/icon-96.png" sizes="96x96" rel="apple-touch-icon">
  </span>
  ...
</head>
```

Note: the type constant `Dependency.Type.HTML_IMPORT` looks really confusing in this context because it's not adding an HTML import.

### PR DESCRIPTION
**Pull request by caalador**
Also Fixes #3168

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3249)

### CODE REVIEW

**Comment by ahie** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-server/src/main/java/com/vaadin/flow/component/page/Inline.java, line 46 at r1](https://reviewable.io:443/reviews/vaadin/flow/3249#-L1vkWd0grdZusRlPZn4:-L1vkWd0grdZusRlPZn5:blgrr7b) ([raw file](https://github.com/vaadin/flow/blob/92b0f0233ef8a201665b64ff114fdc5d1a5f211e/flow-server/src/main/java/com/vaadin/flow/component/page/Inline.java#L46)):*
> ```Java
>      * File content wrapping enum.
>      */
>     enum Wrapping {
> ```

Do we need both `Inline.Wrapping` and `InitialPageSettings.WrapMode` or could it be simplified?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3249)*

**Comment by ahie** [comment]
Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[flow-documentation/application-structure/tutorial-bootstrap.asciidoc, line 115 at r1](https://reviewable.io:443/reviews/vaadin/flow/3249#-L1vm4WqRRVQFMIVzdtF:-L1vm4WqRRVQFMIVzdtG:b-hh3bpu) ([raw file](https://github.com/vaadin/flow/blob/92b0f0233ef8a201665b64ff114fdc5d1a5f211e/flow-documentation/application-structure/tutorial-bootstrap.asciidoc#L115)):*
> ```AsciiDoc
>     public void configurePage(InitialPageSettings settings) {
>         settings.addInlineFromFile(InitialPageSettings.Position.PREPEND,
>                 "inline.js", InitialPageSettings.Wrapping.JAVASCRIPT);
> ```

`Wrapping` used here, `WrapMode` in the corresponding java file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3249)*

**Comment by caalador** [comment]
Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[flow-documentation/application-structure/tutorial-bootstrap.asciidoc, line 115 at r1](https://reviewable.io:443/reviews/vaadin/flow/3249#-L1vm4WqRRVQFMIVzdtF:-L1vn6UbBNALEQVs_t44:b-drylbh) ([raw file](https://github.com/vaadin/flow/blob/92b0f0233ef8a201665b64ff114fdc5d1a5f211e/flow-documentation/application-structure/tutorial-bootstrap.asciidoc#L115)):*
> WrapMode
My bad. fixed.

---

*[flow-server/src/main/java/com/vaadin/flow/component/page/Inline.java, line 46 at r1](https://reviewable.io:443/reviews/vaadin/flow/3249#-L1vkWd0grdZusRlPZn4:-L1vosWUPa67JGh4RZMv:b-d9uqzv) ([raw file](https://github.com/vaadin/flow/blob/92b0f0233ef8a201665b64ff114fdc5d1a5f211e/flow-server/src/main/java/com/vaadin/flow/component/page/Inline.java#L46)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

Do we need both `Inline.Wrapping` and `InitialPageSettings.WrapMode` or could it be simplified?
</blockquote></details>

The thing was that Inline has the AUTOMATIC mode that we can't use for inline content in InitialPageSettings

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3249)*

**Comment by ahie** [comment]
Reviewed 7 of 8 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-documentation/application-structure/tutorial-bootstrap.asciidoc, line 64 at r2](https://reviewable.io:443/reviews/vaadin/flow/3249#-L1vuVqgj-o6JZg9w5vc:-L1vuVqgj-o6JZg9w5vd:b-e8za6j) ([raw file](https://github.com/vaadin/flow/blob/5523a59e09b27b62969450b8e2d0ba2ca9d1b8ed/flow-documentation/application-structure/tutorial-bootstrap.asciidoc#L64)):*
> CSS, SCRIPT

STYLESHEET, JAVASCRIPT?

---

*[flow-server/src/main/java/com/vaadin/flow/server/InitialPageSettings.java, line 47 at r2](https://reviewable.io:443/reviews/vaadin/flow/3249#-L1vrbPbaN3T9VD4ot4G:-L1vrbPbaN3T9VD4ot4H:b-5feff) ([raw file](https://github.com/vaadin/flow/blob/5523a59e09b27b62969450b8e2d0ba2ca9d1b8ed/flow-server/src/main/java/com/vaadin/flow/server/InitialPageSettings.java#L47)):*
> ```Java
>     }
> 
>     public enum WrapMode {
> ```

Missing javadoc here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3249)*

**Comment by caalador** [comment]
Review status: 6 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-documentation/application-structure/tutorial-bootstrap.asciidoc, line 64 at r2](https://reviewable.io:443/reviews/vaadin/flow/3249#-L1vuVqgj-o6JZg9w5vc:-L1vvMTyiBihZy31I86j:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/5523a59e09b27b62969450b8e2d0ba2ca9d1b8ed/flow-documentation/application-structure/tutorial-bootstrap.asciidoc#L64)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

> CSS, SCRIPT

STYLESHEET, JAVASCRIPT?
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/flow/server/InitialPageSettings.java, line 47 at r2](https://reviewable.io:443/reviews/vaadin/flow/3249#-L1vrbPbaN3T9VD4ot4G:-L1vvMtdXC76nnfbQZKo:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/5523a59e09b27b62969450b8e2d0ba2ca9d1b8ed/flow-server/src/main/java/com/vaadin/flow/server/InitialPageSettings.java#L47)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

Missing javadoc here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3249)*

**Comment by ahie** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3249)*

**Comment by ahie** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[flow-server/src/main/java/com/vaadin/flow/server/InitialPageSettings.java, line 47 at r3](https://reviewable.io:443/reviews/vaadin/flow/3249#-L1veay8cBYiUH5jCEBr-r3-47:-L1vzAWiFBAwccUNPUnk:bfh4fhq) ([raw file](https://github.com/vaadin/flow/blob/860640f033cc381516ace25d0b18502184d3e117/flow-server/src/main/java/com/vaadin/flow/server/InitialPageSettings.java#L47)):*
> Document this public enum by adding an explicit description.

Not sure why sonar is still complaining about this.

---

*[flow-server/src/main/java/com/vaadin/flow/shared/ui/Dependency.java, line 45 at r3](https://reviewable.io:443/reviews/vaadin/flow/3249#-L1veay8cBYiUH5jCEBt-r3-45:-L1vz47W27azexuFiY_C:biilst1) ([raw file](https://github.com/vaadin/flow/blob/860640f033cc381516ace25d0b18502184d3e117/flow-server/src/main/java/com/vaadin/flow/shared/ui/Dependency.java#L45)):*
> Document this public method by adding an explicit description. 

+1, sorry missed this one.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3249)*

**Comment by caalador** [comment]
Review status: 5 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/shared/ui/Dependency.java, line 45 at r3](https://reviewable.io:443/reviews/vaadin/flow/3249#-L1veay8cBYiUH5jCEBt-r3-45:-L1w-PA32MgFv1EzrP77:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/860640f033cc381516ace25d0b18502184d3e117/flow-server/src/main/java/com/vaadin/flow/shared/ui/Dependency.java#L45)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

> Document this public method by adding an explicit description. 

+1, sorry missed this one.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3249)*

**Comment by ahie** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3249)*

**Pull request merged**
