### PR TITLE
Use TB Query method instead of find/getInShadowRoot methods

### PR DESCRIPTION
**Pull request by ZheSun88**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/4300)

### CODE REVIEW

**Comment by pekam** [comment]
Reviewed 1 of 13 files at r1.
Review status: 1 unresolved discussion, 0 of 1 LGTMs obtained

---

*[flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/frontend/FrontendProtocolIT.java, line 98 at r2](https://reviewable.io/reviews/vaadin/flow/4300#-LFHl8xB55zR5Li0Mx9X:-LFHl8xB55zR5Li0Mx9Y:bkbxunv) ([raw file](https://github.com/vaadin/flow/blob/d7b29288ef7e1373bac7a02d9b6c92e4d20cd268/flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/frontend/FrontendProtocolIT.java#L98)):*
> ```Java
> 
>         TestBenchElement element = $("frontend-protocol").first();
>         DivElement interList = element.$(DivElement.class).id("frontend-protocol-div");
> ```

name changed randomly, typo?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4300)*

**Comment by pekam** [comment]
Reviewed 1 of 13 files at r1.
Review status: 2 unresolved discussions, 0 of 1 LGTMs obtained

---

*[flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/BasicTypeInListIT.java, line 32 at r2](https://reviewable.io/reviews/vaadin/flow/4300#-LFHlFSR4ZqDwiFVc3A2:-LFHlFSR4ZqDwiFVc3A3:b-e2xqdy) ([raw file](https://github.com/vaadin/flow/blob/d7b29288ef7e1373bac7a02d9b6c92e4d20cd268/flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/BasicTypeInListIT.java#L32)):*
> ```Java
>     public void basicTypeInModeList() {
>         open();
>         TestBenchElement tempalte = $(TestBenchElement.class).id("template");
> ```

name typo: tempalte

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4300)*

**Comment by pekam** [comment]
Reviewed 11 of 13 files at r1.
Review status: 5 unresolved discussions, 0 of 1 LGTMs obtained

---

*[flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/ChildOrderIT.java, line 123 at r2](https://reviewable.io/reviews/vaadin/flow/4300#-LFHlflE2RnCDUlNyLTi:-LFHlflE2RnCDUlNyLTj:b-iyvhz2) ([raw file](https://github.com/vaadin/flow/blob/d7b29288ef7e1373bac7a02d9b6c92e4d20cd268/flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/ChildOrderIT.java#L123)):*
> ```Java
>         TestBenchElement container = root.$(TestBenchElement.class)
>                 .id("containerWithText");
>         
> ```

whitespace

---

*[flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/TemplateWithConnectedCallbacksIT.java, line 46 at r2](https://reviewable.io/reviews/vaadin/flow/4300#-LFHmfvb8twqDLuM4CNP:-LFHmfvb8twqDLuM4CNQ:b-6nwr91) ([raw file](https://github.com/vaadin/flow/blob/d7b29288ef7e1373bac7a02d9b6c92e4d20cd268/flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/TemplateWithConnectedCallbacksIT.java#L46)):*
> ```Java
>         TestBenchElement element = $(
>                 "template-with-connected-callbacks").first();
>         TestBenchElement Message = element.$(TestBenchElement.class)
> ```

Why renamed `messageElement` -> `Message`?
Variable names shouldn't start with upper-case letters.

---

*[flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/collections/ModelListIT.java, line 27 at r2](https://reviewable.io/reviews/vaadin/flow/4300#-LFHn_RS0qEeM7SJ2c7x:-LFHn_RS0qEeM7SJ2c7y:b-wgpyzu) ([raw file](https://github.com/vaadin/flow/blob/d7b29288ef7e1373bac7a02d9b6c92e4d20cd268/flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/collections/ModelListIT.java#L27)):*
> ```Java
>     public void init() {
>         open();
>         modelList = $("model-list");
> ```

why not `modelList = $("model-list").first();` so you can have reference to the `TestBenchElement` instead of the `ElementQuery`?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4300)*

**Comment by ZheSun88** [comment]
Review status: 5 unresolved discussions, 0 of 1 LGTMs obtained

---

*[flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/frontend/FrontendProtocolIT.java, line 98 at r2](https://reviewable.io/reviews/vaadin/flow/4300#-LFHl8xB55zR5Li0Mx9X:-LFHo5nk4ED_smtpDwtJ:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/d7b29288ef7e1373bac7a02d9b6c92e4d20cd268/flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/frontend/FrontendProtocolIT.java#L98)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

name changed randomly, typo?
</blockquote></details>

Done.

---

*[flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/BasicTypeInListIT.java, line 32 at r2](https://reviewable.io/reviews/vaadin/flow/4300#-LFHlFSR4ZqDwiFVc3A2:-LFHo5OQ7rZ4JDOicYQk:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/d7b29288ef7e1373bac7a02d9b6c92e4d20cd268/flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/BasicTypeInListIT.java#L32)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

name typo: tempalte
</blockquote></details>

Done.

---

*[flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/ChildOrderIT.java, line 123 at r2](https://reviewable.io/reviews/vaadin/flow/4300#-LFHlflE2RnCDUlNyLTi:-LFHoMpIC3IXN09aZUjf:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/d7b29288ef7e1373bac7a02d9b6c92e4d20cd268/flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/ChildOrderIT.java#L123)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

whitespace
</blockquote></details>

Done.

---

*[flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/TemplateWithConnectedCallbacksIT.java, line 46 at r2](https://reviewable.io/reviews/vaadin/flow/4300#-LFHmfvb8twqDLuM4CNP:-LFHofSbBwyn86UbKg5k:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/d7b29288ef7e1373bac7a02d9b6c92e4d20cd268/flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/TemplateWithConnectedCallbacksIT.java#L46)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

Why renamed `messageElement` -> `Message`?
Variable names shouldn't start with upper-case letters.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4300)*

**Comment by ZheSun88** [comment]
Review status: 5 unresolved discussions, 0 of 1 LGTMs obtained

---

*[flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/collections/ModelListIT.java, line 27 at r2](https://reviewable.io/reviews/vaadin/flow/4300#-LFHn_RS0qEeM7SJ2c7x:-LFHpcHM4bmKfFrhV-OF:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/d7b29288ef7e1373bac7a02d9b6c92e4d20cd268/flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/collections/ModelListIT.java#L27)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

why not `modelList = $("model-list").first();` so you can have reference to the `TestBenchElement` instead of the `ElementQuery`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4300)*

**Comment by pekam** [comment]
Reviewed 5 of 5 files at r3.
Review status: all discussions resolved, 0 of 1 LGTMs obtained

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4300)*

**Comment by pekam** [comment]
:lgtm:

---

Review status: all discussions resolved, 0 of 1 LGTMs obtained, and 1 stale

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4300#-:-LFHs2rU7ocSRPVQBSO-:bnfp4nl)*

**Pull request merged**
