### PR TITLE
Enabled state change should fire on attach and detach.

### PR DESCRIPTION
**Pull request by caalador**
method should also check if the enabled state has actually
changed so we don't fire events when things stay the same.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3867)

### CODE REVIEW

**Comment by gilberto-torrezan** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/flow/3867#-L9sXFOPDzjuujfHmOoW:-L9sXFOQCQOj5loLdL4f:b-knarnv) (no related file):*
This is super important for Grid, since it resets the DataCommunicator every time the method is called.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3867#-:-L9sXElZ4oSs4mubD94O:bnfp4nl)*

**Comment by Legioth** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[flow-server/src/main/java/com/vaadin/flow/component/ComponentUtil.java, line 268 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3867#-L9s_421AsVsk_ojNwB0:-L9s_421AsVsk_ojNwB1:bgbetwe) ([raw file](https://github.com/vaadin/flow/blob/1028b72ad488b92f265f15791d91f6282ae21d19/flow-server/src/main/java/com/vaadin/flow/component/ComponentUtil.java#L268)):*
> ```Java
>             boolean enabled) {
>         component.onEnabledStateChanged(enabled);
>         component.getChildren().forEach(child -> child.onEnabledStateChanged(
> ```

What about grandchildren?

---

*[flow-server/src/test/java/com/vaadin/flow/component/ComponentTest.java, line 1111 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3867#-L9s_I8n9_WWO4T6ckDG:-L9s_I8n9_WWO4T6ckDH:b-hf7z1u) ([raw file](https://github.com/vaadin/flow/blob/1028b72ad488b92f265f15791d91f6282ae21d19/flow-server/src/test/java/com/vaadin/flow/component/ComponentTest.java#L1111)):*
> ```Java
> 
>     @Test // 3818
>     public void enabledStateChangeOnAttachCalledForParentState() {
> ```

Also test that the `disabled

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3867)*

**Comment by Legioth** [comment]
*[flow-server/src/test/java/com/vaadin/flow/component/ComponentTest.java, line 1111 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3867#-L9s_I8n9_WWO4T6ckDG:-L9s_eRQ5xMe8_GoOvtu:b-o62gkl) ([raw file](https://github.com/vaadin/flow/blob/1028b72ad488b92f265f15791d91f6282ae21d19/flow-server/src/test/java/com/vaadin/flow/component/ComponentTest.java#L1111)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

Also test that the `disabled
</blockquote></details>

I was trying to say that the attribute value should also be tested

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3867)*

**Comment by caalador** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/component/ComponentUtil.java, line 268 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3867#-L9s_421AsVsk_ojNwB0:-L9swZRyBX8HaTpI2l3c:bkj7ddh) ([raw file](https://github.com/vaadin/flow/blob/1028b72ad488b92f265f15791d91f6282ae21d19/flow-server/src/main/java/com/vaadin/flow/component/ComponentUtil.java#L268)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

What about grandchildren?
</blockquote></details>

Tested and work as they should.

---

*[flow-server/src/test/java/com/vaadin/flow/component/ComponentTest.java, line 1111 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3867#-L9s_I8n9_WWO4T6ckDG:-L9syHMk8dMd19_Q2XJ3:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/1028b72ad488b92f265f15791d91f6282ae21d19/flow-server/src/test/java/com/vaadin/flow/component/ComponentTest.java#L1111)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

I was trying to say that the attribute value should also be tested
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3867)*

**Comment by gilberto-torrezan** [comment]
:lgtm:

---

Reviewed 3 of 4 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3867#-:-L9tc8tK6oz7yFeA8WOP:bnfp4nl)*

**Pull request merged**
