### PR TITLE
Remove angular support

### LINKED ISSUE #2492: Remove AngularTemplate from flow
The old Router classes and AngularTemplate server side classes should be moved from `flow-server` to another module `flow-server-legacy` or `flow-legacy-server` (?) while keeping the same package names. Everything inside this package should already be deprecated.

This is for keeping demos and the website project up and running, but to not have outdated stuff in flow artifacts.

### PR DESCRIPTION
**Pull request by caalador**
Remove AngularTemplate support from Flow

Closes #2492

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/2598)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 151 of 154 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2598#-KvgKSPJ4_SYLOgaLZh3:-KvgKSPKo_qrnx2eWHxi:b-s3379h) (no related file):*
Not really complete.

Angular templates had feature: their accompanied template file name is derived from the class name  (if there  is no overriding annotation).
So each angular template Java class most has `html` file with the same name in the resources folder.
See e.g. flow/flow-tests/test-root-context/src/main/resources/com/vaadin/flow/uitest/ui/template/SvgTemplate.html

I  think I didn't see any such html file removed.

Please check all those files and remove them as well.

---

*[flow-server/src/main/java/com/vaadin/flow/model/BeanModelType.java, line 386 at r2](https://reviewable.io:443/reviews/vaadin/flow/2598#-KvgHVWr8rID6RlsJihd:-KvgHVWr8rID6RlsJihe:b-nrh4vy) ([raw file](https://github.com/vaadin/flow/blob/cc615464463e3496af7594708e1d9e4a794cac9f/flow-server/src/main/java/com/vaadin/flow/model/BeanModelType.java#L386)):*
> this.propertyFilter = propertyFilter;

Does this change relate to the PR ?

---

*[flow-server/src/test/java/com/vaadin/flow/nodefeature/ClientDelegteHandlersTest.java, line 28 at r2](https://reviewable.io:443/reviews/vaadin/flow/2598#-KvgIuw0lLfWPqpTOY0n:-KvgIuw0lLfWPqpTOY0o:b952qvk) ([raw file](https://github.com/vaadin/flow/blob/cc615464463e3496af7594708e1d9e4a794cac9f/flow-server/src/test/java/com/vaadin/flow/nodefeature/ClientDelegteHandlersTest.java#L28)):*
> ClientDelegteHandlersTest 

Could you please rename this class (I guess it's my bad).

`Delegte` -> `Delegate`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2598)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2598#-KvgKSPJ4_SYLOgaLZh3:-KvgLKeYD4KtVWfu_rpS:bh8rfq7) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Not really complete.

Angular templates had feature: their accompanied template file name is derived from the class name  (if there  is no overriding annotation).
So each angular template Java class most has `html` file with the same name in the resources folder.
See e.g. flow/flow-tests/test-root-context/src/main/resources/com/vaadin/flow/uitest/ui/template/SvgTemplate.html

I  think I didn't see any such html file removed.

Please check all those files and remove them as well.
</blockquote></details>

I think all `flow/flow-tests/test-root-context/src/main/resources/com/vaadin/flow/uitest/ui` should be removed in the result.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2598)*

**Comment by caalador** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2598#-KvgKSPJ4_SYLOgaLZh3:-KvgSdnfQiNpKptsnmum:bozlyv2) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

I think all `flow/flow-tests/test-root-context/src/main/resources/com/vaadin/flow/uitest/ui` should be removed in the result.
</blockquote></details>

Yes I totally forgot about them. I'll see to them asap tomorrow.

---

*[flow-server/src/main/java/com/vaadin/flow/model/BeanModelType.java, line 386 at r2](https://reviewable.io:443/reviews/vaadin/flow/2598#-KvgHVWr8rID6RlsJihd:-KvgSCSljmSBizLdaDHF:bx90ol2) ([raw file](https://github.com/vaadin/flow/blob/cc615464463e3496af7594708e1d9e4a794cac9f/flow-server/src/main/java/com/vaadin/flow/model/BeanModelType.java#L386)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> this.propertyFilter = propertyFilter;

Does this change relate to the PR ?
</blockquote></details>

The old version never used this importProperties, but the angular BeanModelType.

The property filter was required to handle the case where we used the faulty bean from which we filtered out the faulty property.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2598)*

**Comment by caalador** [comment]
Review status: 154 of 176 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2598#-KvgKSPJ4_SYLOgaLZh3:-Kw-bwdnXwsK4o7p4wim:b-n25tbo) (no related file):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Yes I totally forgot about them. I'll see to them asap tomorrow.
</blockquote></details>

Done. I think.

---

*[flow-server/src/test/java/com/vaadin/flow/nodefeature/ClientDelegteHandlersTest.java, line 28 at r2](https://reviewable.io:443/reviews/vaadin/flow/2598#-KvgIuw0lLfWPqpTOY0n:-Kw-c75gdAGWAqrWxN_n:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/cc615464463e3496af7594708e1d9e4a794cac9f/flow-server/src/test/java/com/vaadin/flow/nodefeature/ClientDelegteHandlersTest.java#L28)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ClientDelegteHandlersTest 

Could you please rename this class (I guess it's my bad).

`Delegte` -> `Delegate`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2598)*

**Comment by denis-anisimov** [comment]
Reviewed 22 of 22 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2598)*

**Comment by SomeoneToIgnore** [comment]
---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2598#-:-KwF74Bb6ie5X17pW156:b-5kd0gz)*

**Comment by pleku** [comment]
Review status: 175 of 176 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2598#-KwKHCj2a-7a0z_1B3jk:-KwKHCj2a-7a0z_1B3jl:b-ucjgmy) (no related file):*
Blocked for now

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2598)*

**Pull request closed without merging**
