### PR TITLE
Do not resend all if both previous and effective is empty.

### PR DESCRIPTION
**Pull request by caalador**
Empty does not intersect with empty.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3570)

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
Is a test possible?

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3570#-:-L5hBPKjXkMlkj75gWET:b-6zrdlc)*

**Comment by caalador** [comment]
There is a possibility. Perhaps. Seems like DataCommunicator is not  tested at all?

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3570#-:-L5hCUex5PEI_xn5Q_mX:b-tscapa)*

**Comment by SomeoneToIgnore** [comment]
Looks so indeed.

Then I propose to write one.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3570#-:-L5hCn0AJa39iKVL3zQN:b-opo7iw)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3570)*

**Comment by SomeoneToIgnore** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3570#-:-L5hSbZW9K07xBLh4R3i:bnfp4nl)*

**Pull request merged**
