### PR TITLE
Rewrite attach by @Id and template-in-template features

### PR DESCRIPTION
**Pull request by denis-anisimov**
Fix for #3057, #3058.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3098)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Ready for review even though it's not completely done.
There are failing tests because they should be rewritten.
And there are a bunch of tests that needs to be written.

**Comment by caalador** [comment]
Reviewed 28 of 38 files at r1, 1 of 1 files at r2, 6 of 8 files at r3, 4 of 5 files at r5, 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 19 unresolved discussions.

---

*[flow-client/src/main/java/com/vaadin/client/flow/StateNode.java, line 243 at r6](https://reviewable.io:443/reviews/vaadin/flow/3098#-L-jfC7mwFMf_AWwtGUV:-L-jfC7n9l4BHdeNup35:b-qozzgb) ([raw file](https://github.com/vaadin/flow/blob/36c6261012cd281ebe5e6a7333ef75056ec2728d/flow-client/src/main/java/com/vaadin/client/flow/StateNode.java#L243)):*
> ```Java
>                 .set(domNodeSetListeners);
>         copy.forEach(listener -> {
>             if (listener.apply(this) == Boolean.TRUE) {
> ```

Should this just be `listener.apply(this)` as it already returns a boolean.

---

*[flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java, line 599 at r5](https://reviewable.io:443/reviews/vaadin/flow/3098#-L-jjPmJvElgtlT088qb:-L-jjPmJvElgtlT088qc:b-qc00ze) ([raw file](https://github.com/vaadin/flow/blob/1eba7e6a2cf83ebc2e36dc9b3e1eed26ff268c3c/flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java#L599)):*
> ```Java
>     }
> 
>     private void appendVirtualChild(BindingContext context, StateNode node,
> ```

Due to the complexity collecting to appendVirtualChild would it be a good idea/possible to move the virtual child binding parts to a util class or such? (not blocking)

---

*[flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java, line 709 at r7](https://reviewable.io:443/reviews/vaadin/flow/3098#-L-ju8xYrgoDFv4J4HCQ:-L-ju8xYrgoDFv4J4HCR:b-y7743x) ([raw file](https://github.com/vaadin/flow/blob/cc3cc5af04c79a3a2c1e1dba5183f816ed3e3b23/flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java#L709)):*
> ```Java
> 
>         if (existingId != null) {
>             failure = true;
> ```

This is not needed as we just return false if we come here.

---

*[flow-client/src/main/java/com/vaadin/client/flow/util/ClientJsonCodec.java, line 97 at r6](https://reviewable.io:443/reviews/vaadin/flow/3098#-L-jk5ae4-93NXpkTuKa:-L-jk5ae4-93NXpkTuKb:b-ui6xn5) ([raw file](https://github.com/vaadin/flow/blob/36c6261012cd281ebe5e6a7333ef75056ec2728d/flow-client/src/main/java/com/vaadin/client/flow/util/ClientJsonCodec.java#L97)):*
> ```Java
>                 int nodeId = (int) array.getNumber(1);
>                 Node domNode = tree.getNode(nodeId).getDomNode();
>                 return domNode;
> ```

How does `ExecuteJavaScriptProcessor::handleInvocation` manage if it receives a null value?

---

*[flow-client/src/test-gwt/java/com/vaadin/client/flow/GwtBasicElementBinderTest.java, line 759 at r7](https://reviewable.io:443/reviews/vaadin/flow/3098#-L-jkioV9YWter-kPnRn:-L-jkioV9YWter-kPnRo:b-e6aish) ([raw file](https://github.com/vaadin/flow/blob/cc3cc5af04c79a3a2c1e1dba5183f816ed3e3b23/flow-client/src/test-gwt/java/com/vaadin/client/flow/GwtBasicElementBinderTest.java#L759)):*
> ```Java
> 
>         // nothing has changed: no new child
>         assertEquals(1, element.getChildElementCount());
> ```

Could also have a message that opens assert failure instead of the now uninformative 'expected: 1 actual: N'.
Same would go for all new asserts added to tests.

---

*[flow-server/src/main/java/com/vaadin/flow/nodefeature/VirtualChildrenList.java, line 80 at r6](https://reviewable.io:443/reviews/vaadin/flow/3098#-L-jqLd_isXIyktqsdp8:-L-jqLd_isXIyktqsdp9:b-vlgaa3) ([raw file](https://github.com/vaadin/flow/blob/36c6261012cd281ebe5e6a7333ef75056ec2728d/flow-server/src/main/java/com/vaadin/flow/nodefeature/VirtualChildrenList.java#L80)):*
> ```Java
>         assert node != null;
> 
>         JsonObject object = Json.createObject();
> ```

The `object` name could be more descriptive `elementDataObject` or `dataObject`... (not blocking)

---

*[flow-server/src/main/java/com/vaadin/flow/nodefeature/VirtualChildrenList.java, line 86 at r6](https://reviewable.io:443/reviews/vaadin/flow/3098#-L-jq5lxYKebjNElGm6p:-L-jq5lxYKebjNElGm6q:b-pky38k) ([raw file](https://github.com/vaadin/flow/blob/36c6261012cd281ebe5e6a7333ef75056ec2728d/flow-server/src/main/java/com/vaadin/flow/nodefeature/VirtualChildrenList.java#L86)):*
> ```Java
>         }
> 
>         node.getFeature(ElementData.class).setPyload(object);
> ```

Mind fixing `setPyload()` to `setPayload()`

---

*[flow-server/src/main/java/com/vaadin/server/communication/rpc/AttachTemplateChildRpcHandler.java, line 99 at r6](https://reviewable.io:443/reviews/vaadin/flow/3098#-L-jrPkKLPMJ4aU6giUq:-L-jrPkKLPMJ4aU6giUr:b-7xy1lp) ([raw file](https://github.com/vaadin/flow/blob/36c6261012cd281ebe5e6a7333ef75056ec2728d/flow-server/src/main/java/com/vaadin/server/communication/rpc/AttachTemplateChildRpcHandler.java#L99)):*
> ```Java
>             }
>         } else {
>             logger.severe("Attach existing element request succeded");
> ```

This log marking should perhaps open a bit on why it's severe and add that no response should have come from the client.
Or drop the whole log line as the exception is thrown in any case.

---

*[flow-server/src/main/java/com/vaadin/ui/polymertemplate/TemplateInitializer.java, line 211 at r6](https://reviewable.io:443/reviews/vaadin/flow/3098#-L-jruw7haAQyVoXdn60:-L-jruw7haAQyVoXdn61:b-tzkcru) ([raw file](https://github.com/vaadin/flow/blob/36c6261012cd281ebe5e6a7333ef75056ec2728d/flow-server/src/main/java/com/vaadin/ui/polymertemplate/TemplateInitializer.java#L211)):*
> ```Java
> 
>         Element element = new Element(tag);
>         // TODO: should this be exposed as Element API ?
> ```

On both counts I would say that it should not be exposed in the API.
Some documentation for us would be good as we have some use cases where we need to get possible virtual children.

---

*[flow-server/src/test/java/com/vaadin/flow/nodefeature/VirtualChildrenListTest.java, line 41 at r6](https://reviewable.io:443/reviews/vaadin/flow/3098#-L-jsKqS2RaDCAqRTO1m:-L-jsKqS2RaDCAqRTO1n:bh6di3h) ([raw file](https://github.com/vaadin/flow/blob/36c6261012cd281ebe5e6a7333ef75056ec2728d/flow-server/src/test/java/com/vaadin/flow/nodefeature/VirtualChildrenListTest.java#L41)):*
> ```Java
>     @Test
>     public void insert_atIndexWithType_payloadIsSetAndElementIsInserted() {
>         list.add(0, child, "foo", (String) null);
> ```

the String casts are redundant and not needed.

---

*[flow-tests/test-root-context/src/main/webapp/frontend/com/vaadin/flow/uitest/ui/template/JsGrandParent.html, line 32 at r6](https://reviewable.io:443/reviews/vaadin/flow/3098#-L-jtiKAHfD7glE5hYWL:-L-jtiKAHfD7glE5hYWM:b-d0wxhj) ([raw file](https://github.com/vaadin/flow/blob/36c6261012cd281ebe5e6a7333ef75056ec2728d/flow-tests/test-root-context/src/main/webapp/frontend/com/vaadin/flow/uitest/ui/template/JsGrandParent.html#L32)):*
> ```HTML
>         customElements.define(JsGrandTemplate.is, JsGrandTemplate);
>     </script>
> </dom-module>
> ```

new line

---

*[flow-tests/test-root-context/src/main/webapp/frontend/com/vaadin/flow/uitest/ui/template/JsSubTemplate.html, line 32 at r6](https://reviewable.io:443/reviews/vaadin/flow/3098#-L-jtn6wMiTGE8PS9-mN:-L-jtn6wMiTGE8PS9-mO:bmebhsl) ([raw file](https://github.com/vaadin/flow/blob/36c6261012cd281ebe5e6a7333ef75056ec2728d/flow-tests/test-root-context/src/main/webapp/frontend/com/vaadin/flow/uitest/ui/template/JsSubTemplate.html#L32)):*
> ```HTML
>         customElements.define(JsSubTemplate.is, JsSubTemplate);
>     </script>
> </dom-module>
> ```

new line.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3098)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[flow-client/src/main/java/com/vaadin/client/flow/StateNode.java, line 243 at r6](https://reviewable.io:443/reviews/vaadin/flow/3098#-L-jfC7mwFMf_AWwtGUV:-L-jyXrOuJY5St5QimjG:b7j6muy) ([raw file](https://github.com/vaadin/flow/blob/36c6261012cd281ebe5e6a7333ef75056ec2728d/flow-client/src/main/java/com/vaadin/client/flow/StateNode.java#L243)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Should this just be `listener.apply(this)` as it already returns a boolean.
</blockquote></details>

`listener.apply(this)` returns a `Boolean`.

Technically it may be `null` so this check is preferable than without `==`.

But in reality I don't trust GWT compiler with its boxing/unboxing. So I prefer to use the exact type declared in the method return value (did you know e.g. that `new Integer(1)`  doesn't equal `new Integer(1)` in GWT world ? so you can't use `Integer` as keys in a map)

---

*[flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java, line 599 at r5](https://reviewable.io:443/reviews/vaadin/flow/3098#-L-jjPmJvElgtlT088qb:-L-k-3BlVQ6RATL4JTy7:b-y39vc9) ([raw file](https://github.com/vaadin/flow/blob/1eba7e6a2cf83ebc2e36dc9b3e1eed26ff268c3c/flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java#L599)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Due to the complexity collecting to appendVirtualChild would it be a good idea/possible to move the virtual child binding parts to a util class or such? (not blocking)
</blockquote></details>

I don't like utility classes because of logical spreading.
The logic is not that complex actually.
It just contains slightly unrelated blocks here which would have been extracted as methods.
But there is "break" logic inside them ( `return` statement) which prevents to improve this blocks.
It's the same with extracting to utility methods.

I would like to extract the logic out of the blocks but unfortunately it doesn't improve the code significantly.

---

*[flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java, line 709 at r7](https://reviewable.io:443/reviews/vaadin/flow/3098#-L-ju8xYrgoDFv4J4HCQ:-L-k0DynbiW-7k3onIRb:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/cc3cc5af04c79a3a2c1e1dba5183f816ed3e3b23/flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java#L709)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

This is not needed as we just return false if we come here.
</blockquote></details>

Done.

---

*[flow-client/src/main/java/com/vaadin/client/flow/util/ClientJsonCodec.java, line 97 at r6](https://reviewable.io:443/reviews/vaadin/flow/3098#-L-jk5ae4-93NXpkTuKa:-L-k0NiDa7uRmwDGFP8t:b8pkcbb) ([raw file](https://github.com/vaadin/flow/blob/36c6261012cd281ebe5e6a7333ef75056ec2728d/flow-client/src/main/java/com/vaadin/client/flow/util/ClientJsonCodec.java#L97)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

How does `ExecuteJavaScriptProcessor::handleInvocation` manage if it receives a null value?
</blockquote></details>

The same as it had done previously : it should care about this itself.
It may happen only if the element is detached. And that's the developer responsibility to care about it.
 
This code has been introduced as a workaround for attach elements which are targets of JS execution.
Now such executions are deferred so the Dom node will be available at the moment when it's executed.

---

*[flow-client/src/test-gwt/java/com/vaadin/client/flow/GwtBasicElementBinderTest.java, line 759 at r7](https://reviewable.io:443/reviews/vaadin/flow/3098#-L-jkioV9YWter-kPnRn:-L-kU_aEO_FTbm5AOX6E:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/cc3cc5af04c79a3a2c1e1dba5183f816ed3e3b23/flow-client/src/test-gwt/java/com/vaadin/client/flow/GwtBasicElementBinderTest.java#L759)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Could also have a message that opens assert failure instead of the now uninformative 'expected: 1 actual: N'.
Same would go for all new asserts added to tests.
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/flow/nodefeature/VirtualChildrenList.java, line 80 at r6](https://reviewable.io:443/reviews/vaadin/flow/3098#-L-jqLd_isXIyktqsdp8:-L-k260-Zy18RQIP7HOW:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/36c6261012cd281ebe5e6a7333ef75056ec2728d/flow-server/src/main/java/com/vaadin/flow/nodefeature/VirtualChildrenList.java#L80)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

The `object` name could be more descriptive `elementDataObject` or `dataObject`... (not blocking)
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/flow/nodefeature/VirtualChildrenList.java, line 86 at r6](https://reviewable.io:443/reviews/vaadin/flow/3098#-L-jq5lxYKebjNElGm6p:-L-k1swFcqCbC-hFHDVn:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/36c6261012cd281ebe5e6a7333ef75056ec2728d/flow-server/src/main/java/com/vaadin/flow/nodefeature/VirtualChildrenList.java#L86)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Mind fixing `setPyload()` to `setPayload()`
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/server/communication/rpc/AttachTemplateChildRpcHandler.java, line 99 at r6](https://reviewable.io:443/reviews/vaadin/flow/3098#-L-jrPkKLPMJ4aU6giUq:-L-k2ypTHZZtztSLaHth:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/36c6261012cd281ebe5e6a7333ef75056ec2728d/flow-server/src/main/java/com/vaadin/server/communication/rpc/AttachTemplateChildRpcHandler.java#L99)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

This log marking should perhaps open a bit on why it's severe and add that no response should have come from the client.
Or drop the whole log line as the exception is thrown in any case.
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/ui/polymertemplate/TemplateInitializer.java, line 211 at r6](https://reviewable.io:443/reviews/vaadin/flow/3098#-L-jruw7haAQyVoXdn60:-L-k3Cuslj3beSL3jiXf:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/36c6261012cd281ebe5e6a7333ef75056ec2728d/flow-server/src/main/java/com/vaadin/ui/polymertemplate/TemplateInitializer.java#L211)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

On both counts I would say that it should not be exposed in the API.
Some documentation for us would be good as we have some use cases where we need to get possible virtual children.
</blockquote></details>

Done.

---

*[flow-server/src/test/java/com/vaadin/flow/nodefeature/VirtualChildrenListTest.java, line 41 at r6](https://reviewable.io:443/reviews/vaadin/flow/3098#-L-jsKqS2RaDCAqRTO1m:-L-k3TsnQnUcvM4wJffM:byi7zx6) ([raw file](https://github.com/vaadin/flow/blob/36c6261012cd281ebe5e6a7333ef75056ec2728d/flow-server/src/test/java/com/vaadin/flow/nodefeature/VirtualChildrenListTest.java#L41)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

the String casts are redundant and not needed.
</blockquote></details>

No.
There are two overloaded methods `add` : one has a `String` as a parameter type, another has a `JsonValue` . So the compiler just doesn't know which one to invoke.

---

*[flow-tests/test-root-context/src/main/webapp/frontend/com/vaadin/flow/uitest/ui/template/JsGrandParent.html, line 32 at r6](https://reviewable.io:443/reviews/vaadin/flow/3098#-L-jtiKAHfD7glE5hYWL:-L-k4MYeOjEjSsL80qNm:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/36c6261012cd281ebe5e6a7333ef75056ec2728d/flow-tests/test-root-context/src/main/webapp/frontend/com/vaadin/flow/uitest/ui/template/JsGrandParent.html#L32)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

new line
</blockquote></details>

Done.

---

*[flow-tests/test-root-context/src/main/webapp/frontend/com/vaadin/flow/uitest/ui/template/JsSubTemplate.html, line 32 at r6](https://reviewable.io:443/reviews/vaadin/flow/3098#-L-jtn6wMiTGE8PS9-mN:-L-k4Q_SzPwHPercVZzA:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/36c6261012cd281ebe5e6a7333ef75056ec2728d/flow-tests/test-root-context/src/main/webapp/frontend/com/vaadin/flow/uitest/ui/template/JsSubTemplate.html#L32)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

new line.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3098)*

**Comment by caalador** [comment]
Reviewed 9 of 9 files at r8.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[flow-client/src/main/java/com/vaadin/client/flow/StateNode.java, line 243 at r6](https://reviewable.io:443/reviews/vaadin/flow/3098#-L-jfC7mwFMf_AWwtGUV:-L-kefvuwnXOiOlBXZdM:b6v8fb1) ([raw file](https://github.com/vaadin/flow/blob/36c6261012cd281ebe5e6a7333ef75056ec2728d/flow-client/src/main/java/com/vaadin/client/flow/StateNode.java#L243)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

`listener.apply(this)` returns a `Boolean`.

Technically it may be `null` so this check is preferable than without `==`.

But in reality I don't trust GWT compiler with its boxing/unboxing. So I prefer to use the exact type declared in the method return value (did you know e.g. that `new Integer(1)`  doesn't equal `new Integer(1)` in GWT world ? so you can't use `Integer` as keys in a map)
</blockquote></details>

That's true, but should it then be `Boolean.TRUE.equals(listener.apply(this))` don't have a great preference on this so it's fine as is.

---

*[flow-client/src/main/java/com/vaadin/client/flow/util/ClientJsonCodec.java, line 97 at r6](https://reviewable.io:443/reviews/vaadin/flow/3098#-L-jk5ae4-93NXpkTuKa:-L-kf75vr2n8MSmSfD4t:bkmj2nv) ([raw file](https://github.com/vaadin/flow/blob/36c6261012cd281ebe5e6a7333ef75056ec2728d/flow-client/src/main/java/com/vaadin/client/flow/util/ClientJsonCodec.java#L97)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

The same as it had done previously : it should care about this itself.
It may happen only if the element is detached. And that's the developer responsibility to care about it.
 
This code has been introduced as a workaround for attach elements which are targets of JS execution.
Now such executions are deferred so the Dom node will be available at the moment when it's executed.
</blockquote></details>

ok. Then it's fine.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3098)*

**Pull request merged**
