### PR TITLE
Fix test not considering two filters in list

### PR DESCRIPTION
**Pull request by manolo**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3989)

### CODE REVIEW

**Comment by gilberto-torrezan** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/3989#-:-LAs2IGv1Gdl7YeS2QSm:bnfp4nl)*

**Comment by manolo** [comment]
Sorry, @gilberto-torrezan I did a bit refactoring in order to test cover both ES5 and ES6 browsers instead of one, mind to review again ? 

---

Review status: 1 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/3989#-:-LAs5kcB8iHYrntnmRmM:bsqeoyk)*

**Comment by gilberto-torrezan** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[flow-server/src/test/java/com/vaadin/flow/server/startup/BundleFilterInitializerTest.java, line 262 at r2](https://reviewable.io/reviews/vaadin/flow/3989#-LAs7TE24zdiCWGD3zIV:-LAs7TE35j1XY03Yt_Ls:b-65cdkl) ([raw file](https://github.com/vaadin/flow/blob/6ee1e3c0a2a27407fc1bb3e90f0bb40806798f37/flow-server/src/test/java/com/vaadin/flow/server/startup/BundleFilterInitializerTest.java#L262)):*
> ```Java
>         Assert.assertEquals(unfilteredResult, dependencies);
> 
>         // Second filter in list is ES5, it should filter dependencies when browser is ES6
> ```

When the browser is ES6...?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/3989)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-server/src/test/java/com/vaadin/flow/server/startup/BundleFilterInitializerTest.java, line 262 at r2](https://reviewable.io/reviews/vaadin/flow/3989#-LAs7TE24zdiCWGD3zIV:-LAs809m19K2KUgDvP9q:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/6ee1e3c0a2a27407fc1bb3e90f0bb40806798f37/flow-server/src/test/java/com/vaadin/flow/server/startup/BundleFilterInitializerTest.java#L262)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

When the browser is ES6...?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/3989)*

**Comment by gilberto-torrezan** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/3989#-:-LAs8iSHBsT_ki-ZEFgB:bnfp4nl)*

**Comment by gilberto-torrezan** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/3989#-:-LAsNjSJ19EP07qUpQdG:bnfp4nl)*

**Pull request merged**
