### PR TITLE
Add documentation for Grid selection and column configuration

### PR DESCRIPTION
**Pull request by ahie**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/2812)

### CODE REVIEW

**Comment by gilberto-torrezan** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-documentation/flow-components/tutorial-flow-grid.asciidoc, line 95 at r1](https://reviewable.io:443/reviews/vaadin/flow/2812#-KxrvqaYxxFGmyERQD9L:-KxrvqaYxxFGmyERQD9M:byl0gut) ([raw file](https://github.com/vaadin/flow/blob/28c6ac0816ea4039753089dc3c7cd59388cf13da/flow-documentation/flow-components/tutorial-flow-grid.asciidoc#L95)):*
> ```AsciiDoc
> 
> The current selection can be obtained from the [classname]#Grid# by
> [methodname]#getSelectedItems()#, and the returned [classname]#Set# contains either
> ```

Those `[methodname]` and `[classname]` don't seem to affect the rendering in any way (at least I couldn't see any difference at https://github.com/vaadin/flow/blob/grid-documentation/flow-documentation/flow-components/tutorial-flow-grid.asciidoc ). Is this a syntax copied from the old documentation?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2812)*

**Comment by ahie** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[flow-documentation/flow-components/tutorial-flow-grid.asciidoc, line 95 at r1](https://reviewable.io:443/reviews/vaadin/flow/2812#-KxrvqaYxxFGmyERQD9L:-KxvhNijlcs7gJYSaQrL:b-dmqrch) ([raw file](https://github.com/vaadin/flow/blob/28c6ac0816ea4039753089dc3c7cd59388cf13da/flow-documentation/flow-components/tutorial-flow-grid.asciidoc#L95)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Those `[methodname]` and `[classname]` don't seem to affect the rendering in any way (at least I couldn't see any difference at https://github.com/vaadin/flow/blob/grid-documentation/flow-documentation/flow-components/tutorial-flow-grid.asciidoc ). Is this a syntax copied from the old documentation?
</blockquote></details>

Changed these to use backticks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2812)*

**Comment by gilberto-torrezan** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[flow-documentation/flow-components/tutorial-flow-grid.asciidoc, line 95 at r1](https://reviewable.io:443/reviews/vaadin/flow/2812#-KxrvqaYxxFGmyERQD9L:-Kxw39TMO4uzN3VRlHBX:bz8hqqm) ([raw file](https://github.com/vaadin/flow/blob/28c6ac0816ea4039753089dc3c7cd59388cf13da/flow-documentation/flow-components/tutorial-flow-grid.asciidoc#L95)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

Changed these to use backticks.
</blockquote></details>

Did you push it? I don't see any changes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2812)*

**Comment by gilberto-torrezan** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2812)*

**Pull request merged**
