### PR TITLE
Logg warn information for missing @Theme

### PR DESCRIPTION
**Pull request by caalador**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3341)

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3341)*

**Comment by SomeoneToIgnore** [comment]
*[flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java, line 800 at r1](https://reviewable.io:443/reviews/vaadin/flow/3341#-L33L9yszMb_jWWJHGV0:-L33L9yszMb_jWWJHGV1:bgc62pa) ([raw file](https://github.com/vaadin/flow/blob/2ebd76df19417efc36dfbe7a94ed6ab7b1e62966/flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java#L800)):*
> 11

Should it be 12? `substring` includes starting index in the string and `src/vaadin-` has 11 chars in it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3341)*

**Comment by SomeoneToIgnore** [comment]
*[flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java, line 800 at r1](https://reviewable.io:443/reviews/vaadin/flow/3341#-L33L9yszMb_jWWJHGV0:-L33LGToPWu8h2Xh_H8r:b-8hopwc) ([raw file](https://github.com/vaadin/flow/blob/2ebd76df19417efc36dfbe7a94ed6ab7b1e62966/flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java#L800)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

> 11

Should it be 12? `substring` includes starting index in the string and `src/vaadin-` has 11 chars in it.
</blockquote></details>

Also, may it be better to get non-hardcoded value?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3341)*

**Comment by SomeoneToIgnore** [comment]
*[flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java, line 800 at r1](https://reviewable.io:443/reviews/vaadin/flow/3341#-L33L9yszMb_jWWJHGV0:-L33LiHPLOvhCaZmV9L_:b2l478b) ([raw file](https://github.com/vaadin/flow/blob/2ebd76df19417efc36dfbe7a94ed6ab7b1e62966/flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java#L800)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Also, may it be better to get non-hardcoded value?
</blockquote></details>

And, strictly speaking, no one guarantees that `src/vaadin-` is present in the string, since we check for `src/vaadin` presence, so we might want to enforce the check a bit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3341)*

**Comment by SomeoneToIgnore** [comment]
*[flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java, line 803 at r1](https://reviewable.io:443/reviews/vaadin/flow/3341#-L33HdNbSu027g1g97oN-r1-803:-L33T3CfPE0vTpqXyolU:bvy4mtb) ([raw file](https://github.com/vaadin/flow/blob/2ebd76df19417efc36dfbe7a94ed6ab7b1e62966/flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java#L803)):*
<details><summary><i>Previously, vaadin-bot (Vaadin Bot) wrote…</i></summary><blockquote>

MAJOR Use the built-in formatting to construct this argument. [rule](https://sonar.projects.vaadin.com/coding_rules#rule_key=squid%3AS2629)
</blockquote></details>

Oh, that's a nice catch btw.
https://www.slf4j.org/faq.html#logging_performance

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3341)*

**Comment by SomeoneToIgnore** [comment]
*[flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java, line 803 at r1](https://reviewable.io:443/reviews/vaadin/flow/3341#-L33HdNbSu027g1g97oN-r1-803:-L33TKraxwErzm_hj2BK:buh7dds) ([raw file](https://github.com/vaadin/flow/blob/2ebd76df19417efc36dfbe7a94ed6ab7b1e62966/flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java#L803)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Oh, that's a nice catch btw.
https://www.slf4j.org/faq.html#logging_performance
</blockquote></details>

I propose to do the same for the logging above also.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3341)*

**Comment by caalador** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java, line 803 at r1](https://reviewable.io:443/reviews/vaadin/flow/3341#-L33HdNbSu027g1g97oN-r1-803:-L34fgxWUibj0pj44lra:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/2ebd76df19417efc36dfbe7a94ed6ab7b1e62966/flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java#L803)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

I propose to do the same for the logging above also.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3341)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3341)*

**Pull request merged**
