### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by asashour**
And using US English

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3099)

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
Reviewed 1 of 14 files at r1.
Review status: 1 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-tests/test-root-ui-context/src/main/java/com/vaadin/flow/uitest/servlet/ApplicationRunnerServlet.java, line 305 at r1](https://reviewable.io:443/reviews/vaadin/flow/3099#-L-aLRAx8IDHH6eOzVkH:-L-aLDkM8Ft1qJfsgCxR:b-sy0ht) ([raw file](https://github.com/vaadin/flow/blob/8a0dea54c4fe0ad994e48562e53dcd7da306903b/flow-tests/test-root-ui-context/src/main/java/com/vaadin/flow/uitest/servlet/ApplicationRunnerServlet.java#L305)):*
https://owl.english.purdue.edu/owl/resource/540/01/

This states that `an` is used when the next work begins with the vowel.
> In some cases where "h" is pronounced, such as "historical," you can use an. However, a is more commonly used and preferred.

I agree with it, do you? Same for other `an` changes in the PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3099)*

**Comment by SomeoneToIgnore** [comment]
> And using US English

Why told you that we should use this dialect?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3099#-:-L-aLvubtoqth5n4euqA:b-4e7wae)*

**Comment by SomeoneToIgnore** [comment]
/s/Why/Who/

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3099#-:-L-aMGe_wSQZNCl-aIUm:b-qebqde)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 13 of 14 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3099)*

**Comment by asashour** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-tests/test-root-ui-context/src/main/java/com/vaadin/flow/uitest/servlet/ApplicationRunnerServlet.java, line 305 at r1](https://reviewable.io:443/reviews/vaadin/flow/3099#-L-aLRAx8IDHH6eOzVkH:-L-aMEBizlINJXXPpjTx:b-78t3ew) ([raw file](https://github.com/vaadin/flow/blob/8a0dea54c4fe0ad994e48562e53dcd7da306903b/flow-tests/test-root-ui-context/src/main/java/com/vaadin/flow/uitest/servlet/ApplicationRunnerServlet.java#L305)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

https://owl.english.purdue.edu/owl/resource/540/01/

This states that `an` is used when the next work begins with the vowel.
> In some cases where "h" is pronounced, such as "historical," you can use an. However, a is more commonly used and preferred.

I agree with it, do you? Same for other `an` changes in the PR.
</blockquote></details>

Yes, I agree it should be "a historical", but in acronym, since it is pronounced as "an aitch":

https://www.quora.com/Why-do-we-use-an-HTML-when-it-should-be-a-HTML

Same thing goes for "an SAP" as another example

https://www.quora.com/Why-is-the-article-an-used-for-SAP

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3099)*

**Comment by SomeoneToIgnore** [comment]
*[flow-tests/test-root-ui-context/src/main/java/com/vaadin/flow/uitest/servlet/ApplicationRunnerServlet.java, line 305 at r1](https://reviewable.io:443/reviews/vaadin/flow/3099#-L-aLRAx8IDHH6eOzVkH:-L-aNeuY-Y3kd-k78cg4:b-kx9h9q) ([raw file](https://github.com/vaadin/flow/blob/8a0dea54c4fe0ad994e48562e53dcd7da306903b/flow-tests/test-root-ui-context/src/main/java/com/vaadin/flow/uitest/servlet/ApplicationRunnerServlet.java#L305)):*
<details><summary><i>Previously, asashour (Ahmed Ashour) wrote…</i></summary><blockquote>

Yes, I agree it should be "a historical", but in acronym, since it is pronounced as "an aitch":

https://www.quora.com/Why-do-we-use-an-HTML-when-it-should-be-a-HTML

Same thing goes for "an SAP" as another example

https://www.quora.com/Why-is-the-article-an-used-for-SAP
</blockquote></details>

What is the value of this PR to the project?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3099)*

**Comment by asashour** [comment]
Dialect changed reverted, now with only 'typos/spaces'.

In some places, e.g. we use `color' not `colour`, and I thought unifying the dialect is something for better documentation.

**Comment by SomeoneToIgnore** [comment]
Nice, thanks.

---

Reviewed 4 of 13 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3099#-:-L-aPqXi5J2rUtFcbxyW:b-wdj8z5)*

**Comment by SomeoneToIgnore** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3099#-:-L-aROccRsa79CYg0oay:bnfp4nl)*

**Pull request merged**
