### PR TITLE
Create a String-to-UUID Converter (#4400)

### PR DESCRIPTION
**Pull request by ovidiupopa91**
This change introduces a new converter (StringToUuidConverter) which
converts from String to UUID and back.
- Leading and trailing white spaces are ignored when converting from a
String.
- Empty/null strings are converted to Result.ok(null)
- Invalid UUID string throws exception and returns Result.error

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/5870)

### CODE REVIEW

**Comment by ovidiupopa91** [comment]
Hi @denis-anisimov . I will rebase the PR based on master. I will let you know when I'm finished.

**Comment by denis-anisimov** [comment]
> Hi @denis-anisimov . I will rebase the PR based on master. I will let you know when I'm finished.

Thank you

**Comment by pleku** [comment]
@ovidiupopa91 can you please address the review comments ? This PR has been stale for a while, and unless it receives some attention in a reasonable time, we will close it. Thanks

**Comment by pleku** [comment]
The PR has become stale and has conflicts - closing it has it would require effort that is better spent elsewhere. Thanks for the contribution.

**Pull request closed without merging**
