### PR TITLE
Disregard all client side changes to MapProperty if there are server updates

### PR DESCRIPTION
**Pull request by denis-anisimov**
Fix for #2460 and #3312

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3331)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Needs tests : GWT and IT.
For now it should verify that the suggestion doesn't break anything.

**Comment by SomeoneToIgnore** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[flow-client/src/main/java/com/vaadin/client/flow/nodefeature/MapProperty.java, line 129 at r1](https://reviewable.io:443/reviews/vaadin/flow/3331#-L33R0j3XNBWt3HW0IAT:-L33R0j3XNBWt3HW0IAU:bt38z97) ([raw file](https://github.com/vaadin/flow/blob/361869cf9bc359798ebbf04bd9e90a208f5cc59d/flow-client/src/main/java/com/vaadin/client/flow/nodefeature/MapProperty.java#L129)):*
> ```Java
>      */
>     public void setValue(Object value) {
>         // mark as server update is in progress
> ```

This particular comment is rather redundant, imo.

---

*[flow-client/src/main/java/com/vaadin/client/flow/nodefeature/MapProperty.java, line 153 at r1](https://reviewable.io:443/reviews/vaadin/flow/3331#-L33RHMQOlUj4CEoUjel:-L33RHMQOlUj4CEoUjem:b8vmpiq) ([raw file](https://github.com/vaadin/flow/blob/361869cf9bc359798ebbf04bd9e90a208f5cc59d/flow-client/src/main/java/com/vaadin/client/flow/nodefeature/MapProperty.java#L153)):*
> ```Java
>             // mark as server update is in progress
>             isServerUpdate = true;
>             updateValue(null, false);
> ```

So, we call `updateValue` in two places and set `isServerUpdate = true;` in same two places, right before the method.
Would it make sense to put the `isServerUpdate = true;` into the method?
We can also rename it to state that we blocking all other updates.

---

*[flow-client/src/main/java/com/vaadin/client/flow/nodefeature/MapProperty.java, line 161 at r1](https://reviewable.io:443/reviews/vaadin/flow/3331#-L33QgjA8mI06z9m1d5W:-L33QgjA8mI06z9m1d5X:b-jdhauv) ([raw file](https://github.com/vaadin/flow/blob/361869cf9bc359798ebbf04bd9e90a208f5cc59d/flow-client/src/main/java/com/vaadin/client/flow/nodefeature/MapProperty.java#L161)):*
> ```Java
> 
>     private void doSetValue(Object value) {
>         if (hasValue && Objects.equals(value, this.value)) {
> ```

This looks like the same case as in `syncToServer` method when we set `isServerUpdate = false;` if new value equals to old value.
Should we do the same here also?

If my previous comment about putting `isServerUpdate = true;` into `updateValue` will be done, then this is **not** needed.

---

*[flow-tests/test-root-context/src/main/webapp/frontend/com/vaadin/flow/uitest/ui/template/MultiplePropsMutation.html, line 29 at r1](https://reviewable.io:443/reviews/vaadin/flow/3331#-L33Sh93Ffn7E2mjsnG_:-L33Sh93Ffn7E2mjsnGa:b-azhxg5) ([raw file](https://github.com/vaadin/flow/blob/361869cf9bc359798ebbf04bd9e90a208f5cc59d/flow-tests/test-root-context/src/main/webapp/frontend/com/vaadin/flow/uitest/ui/template/MultiplePropsMutation.html#L29)):*
> ```HTML
>             static get is() { return 'multiple-props-mutation' }
>         
> 	        static get properties(){
> ```

Tabs again.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3331)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[flow-client/src/main/java/com/vaadin/client/flow/nodefeature/MapProperty.java, line 129 at r1](https://reviewable.io:443/reviews/vaadin/flow/3331#-L33R0j3XNBWt3HW0IAT:-L36zVxV-9mFE2dapxTH:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/361869cf9bc359798ebbf04bd9e90a208f5cc59d/flow-client/src/main/java/com/vaadin/client/flow/nodefeature/MapProperty.java#L129)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

This particular comment is rather redundant, imo.
</blockquote></details>

Done.

---

*[flow-client/src/main/java/com/vaadin/client/flow/nodefeature/MapProperty.java, line 153 at r1](https://reviewable.io:443/reviews/vaadin/flow/3331#-L33RHMQOlUj4CEoUjel:-L36zkPdOjCpIxoyGW3S:b-1t0bid) ([raw file](https://github.com/vaadin/flow/blob/361869cf9bc359798ebbf04bd9e90a208f5cc59d/flow-client/src/main/java/com/vaadin/client/flow/nodefeature/MapProperty.java#L153)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

So, we call `updateValue` in two places and set `isServerUpdate = true;` in same two places, right before the method.
Would it make sense to put the `isServerUpdate = true;` into the method?
We can also rename it to state that we blocking all other updates.
</blockquote></details>

`into the method`

you mean `updateValue`  method ?

No.
`syncToServer` delegates its call to `doSetValue` which also calls the `updateValue`  method.
And this way flag should not be set.
Otherwise the whole idea won't work at all.

---

*[flow-client/src/main/java/com/vaadin/client/flow/nodefeature/MapProperty.java, line 161 at r1](https://reviewable.io:443/reviews/vaadin/flow/3331#-L33QgjA8mI06z9m1d5W:-L37-M3i8H86Ha2Re83z:b-q1mu89) ([raw file](https://github.com/vaadin/flow/blob/361869cf9bc359798ebbf04bd9e90a208f5cc59d/flow-client/src/main/java/com/vaadin/client/flow/nodefeature/MapProperty.java#L161)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

This looks like the same case as in `syncToServer` method when we set `isServerUpdate = false;` if new value equals to old value.
Should we do the same here also?

If my previous comment about putting `isServerUpdate = true;` into `updateValue` will be done, then this is **not** needed.
</blockquote></details>

There are two different aspects of checking for the same value:
- this one checks whether the value needs to be updated at all and event needs to be sent if the update is required. This allows to avoid endless loop of update: e.g. client side updates the value , the value is updated and event is sent, then the event causes updates in client side which may again request set value (exactly happens with `notify` properties).
- the check inside `syncToServer` is another side of the same story: if the property change on the client side fires an event then `syncToServer` will be called. It may happen event when we are changing the property value from the server side: client side property is updated as a result of the event from `setValue` , then client fires an event (for synchronized property) and then `syncToServer` is called with the same value which has been set from the server. Normally it should be ignored and this is expected (again: preventing the endless loop). But I use this is as an indicator that now server side update is applied and the flag can be reset.

I will update comments inside `syncToServer`.

---

*[flow-tests/test-root-context/src/main/webapp/frontend/com/vaadin/flow/uitest/ui/template/MultiplePropsMutation.html, line 29 at r1](https://reviewable.io:443/reviews/vaadin/flow/3331#-L33Sh93Ffn7E2mjsnG_:-L371LjH0rBEy_o9G-B2:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/361869cf9bc359798ebbf04bd9e90a208f5cc59d/flow-tests/test-root-context/src/main/webapp/frontend/com/vaadin/flow/uitest/ui/template/MultiplePropsMutation.html#L29)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Tabs again.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3331)*

**Comment by SomeoneToIgnore** [comment]
*[flow-tests/test-root-context/src/main/webapp/frontend/com/vaadin/flow/uitest/ui/template/MultiplePropsMutation.html, line 29 at r1](https://reviewable.io:443/reviews/vaadin/flow/3331#-L33Sh93Ffn7E2mjsnG_:-L37Ky4T9moFvh6_vSXU:bsqjeix) ([raw file](https://github.com/vaadin/flow/blob/361869cf9bc359798ebbf04bd9e90a208f5cc59d/flow-tests/test-root-context/src/main/webapp/frontend/com/vaadin/flow/uitest/ui/template/MultiplePropsMutation.html#L29)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Was not done btw, but whatever.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3331)*

**Comment by denis-anisimov** [comment]
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[flow-tests/test-root-context/src/main/webapp/frontend/com/vaadin/flow/uitest/ui/template/MultiplePropsMutation.html, line 29 at r1](https://reviewable.io:443/reviews/vaadin/flow/3331#-L33Sh93Ffn7E2mjsnG_:-L37Vb1fthOqbPMV3P9w:b9aafd0) ([raw file](https://github.com/vaadin/flow/blob/361869cf9bc359798ebbf04bd9e90a208f5cc59d/flow-tests/test-root-context/src/main/webapp/frontend/com/vaadin/flow/uitest/ui/template/MultiplePropsMutation.html#L29)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Was not done btw, but whatever.
</blockquote></details>

Weird, I've reformatted the code...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3331)*

**Pull request merged**
