### PR TITLE
Add documentation for using ComponentRenderer with Grid

### PR DESCRIPTION
**Pull request by pekam**
Also docs about details row

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/2938)

### CODE REVIEW

**Comment by gilberto-torrezan** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-documentation/flow-components/tutorial-flow-grid.asciidoc, line 469 at r1](https://reviewable.io:443/reviews/vaadin/flow/2938#-Kz2iIIPdSjaol2FiqC7:-Kz2iIIPdSjaol2FiqC8:b163sy8) ([raw file](https://github.com/vaadin/flow/blob/e7e98c31a3bc1acb4a07bdb3791535336cedcdd5/flow-documentation/flow-components/tutorial-flow-grid.asciidoc#L469)):*
> ```AsciiDoc
> }));
> ----
> After this you can expand any row simply by clicking on it. Clicking on the same row again or expanding another
> ```

Ah, the problem with the `expand` term.

Let me try to find a better way of saying this without using the `expand` word.

"After this you can open the details for the row simply by clicking on it. Clicking on the same row again or opening the details for another row closes the currently opened one. You can also show and hide row details programmatically with the `setDetailsVisible()` method, and test whether the details for an item is visible with `isDetailsVisible()`"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2938)*

**Comment by pekam** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[flow-documentation/flow-components/tutorial-flow-grid.asciidoc, line 469 at r1](https://reviewable.io:443/reviews/vaadin/flow/2938#-Kz2iIIPdSjaol2FiqC7:-Kz3jMwY-QePQAheX_6D:b-wsdfml) ([raw file](https://github.com/vaadin/flow/blob/e7e98c31a3bc1acb4a07bdb3791535336cedcdd5/flow-documentation/flow-components/tutorial-flow-grid.asciidoc#L469)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Ah, the problem with the `expand` term.

Let me try to find a better way of saying this without using the `expand` word.

"After this you can open the details for the row simply by clicking on it. Clicking on the same row again or opening the details for another row closes the currently opened one. You can also show and hide row details programmatically with the `setDetailsVisible()` method, and test whether the details for an item is visible with `isDetailsVisible()`"
</blockquote></details>

Sounds good, so I just copied that. :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2938)*

**Comment by ahie** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2938#-:-Kz48pGiB7b5_fpBwmQx:bnfp4nl)*

**Comment by gilberto-torrezan** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2938)*

**Pull request merged**
