### PR TITLE
Replace HasValue with AbstractSinglePropertyField

### PR DESCRIPTION
**Pull request by manolo**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/4013)

### CODE REVIEW

**Comment by gilberto-torrezan** [comment]
Reviewed 3 of 5 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow/4013#-LB0UZx_CDVe6dqYCI0D:-LB0UZx_CDVe6dqYCI0E:bsi36zg) (no related file):*
Don't forget to also push the new generated classes.

---

*[flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/ComponentGenerator.java, line 433 at r2](https://reviewable.io/reviews/vaadin/flow/4013#-LB0VUNZ5ZYRvaI0QeP6:-LB0VUNZ5ZYRvaI0QeP7:b45t20r) ([raw file](https://github.com/vaadin/flow/blob/81e030e1e205e2811d858ce9ddf76d11e976360f/flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/ComponentGenerator.java#L433)):*
> ```Java
>         boolean hasValue =  !hasParent && shouldImplementHasValue(metadata);
> 
>         if (!hasParent) {
> ```

This is dangerous. The subclass can have more properties that qualify it to have some extra interfaces that the parent doesn't. For instance, the subclass can have a `slot` (making it implement `HasComponents`) while the parent doesn't have it.

---

*[flow-components-parent/flow-code-generator-api/src/test/java/com/vaadin/generator/ComponentGeneratorTest.java, line 941 at r1](https://reviewable.io/reviews/vaadin/flow/4013#-LB0T2msEsXeoLtpzaci:-LB0T2msEsXeoLtpzacj:b-pix7va) ([raw file](https://github.com/vaadin/flow/blob/096f11ea055832aa1fe3e29b5077978aa1227751/flow-components-parent/flow-code-generator-api/src/test/java/com/vaadin/generator/ComponentGeneratorTest.java#L941)):*
> ```Java
>         generatedClass = ComponentGeneratorTestUtils.removeIndentation(generatedClass);
> 
>         Assert.assertThat(generatedClass, CoreMatchers.not("getValue()"));
> ```

Looks like it is missing the `containsString` here. It should be  `CoreMatchers.not(CoreMatchers.containsString("getValue()"))`.

---

*[flow-components-parent/flow-code-generator-api/src/test/java/com/vaadin/generator/ComponentGeneratorTest.java, line 952 at r1](https://reviewable.io/reviews/vaadin/flow/4013#-LB0TXhQ1zPTbLWFSJ9r:-LB0TXhQ1zPTbLWFSJ9s:b-meny3x) ([raw file](https://github.com/vaadin/flow/blob/096f11ea055832aa1fe3e29b5077978aa1227751/flow-components-parent/flow-code-generator-api/src/test/java/com/vaadin/generator/ComponentGeneratorTest.java#L952)):*
> ```Java
> 
>         Assert.assertThat(generatedClass, CoreMatchers
>                 .not("AbstractSinglePropertyField<R, T>"));
> ```

Same thing here. The `not` method alone only evaluates equality.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4013)*

**Comment by manolo** [comment]
Review status: 3 of 39 files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow/4013#-LB0UZx_CDVe6dqYCI0D:-LB14V-R6cSv1FI01JKC:br9qch6) (no related file):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Don't forget to also push the new generated classes.
</blockquote></details>

Added generated

---

*[flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/ComponentGenerator.java, line 440 at r3](https://reviewable.io/reviews/vaadin/flow/4013#-LB0GOdo6fU8hO_PntbF-r3-440:-LB14avdBBMvrRq4m6Ug:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/1cb89905e15c1bf9fc113622594a7e09066dd01b/flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/ComponentGenerator.java#L440)):*
<details><summary><i>Previously, vaadin-bot (Vaadin Bot) wrote…</i></summary><blockquote>

MAJOR Replace this use of System.out or System.err by a logger. [rule](https://sonar.projects.vaadin.com/coding_rules#rule_key=squid%3AS106)
</blockquote></details>

Done.

---

*[flow-components-parent/flow-code-generator-api/src/test/java/com/vaadin/generator/ComponentGeneratorTest.java, line 941 at r1](https://reviewable.io/reviews/vaadin/flow/4013#-LB0T2msEsXeoLtpzaci:-LB14DU-35YtUIvmVjVD:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/096f11ea055832aa1fe3e29b5077978aa1227751/flow-components-parent/flow-code-generator-api/src/test/java/com/vaadin/generator/ComponentGeneratorTest.java#L941)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Looks like it is missing the `containsString` here. It should be  `CoreMatchers.not(CoreMatchers.containsString("getValue()"))`.
</blockquote></details>

Done.

---

*[flow-components-parent/flow-code-generator-api/src/test/java/com/vaadin/generator/ComponentGeneratorTest.java, line 952 at r1](https://reviewable.io/reviews/vaadin/flow/4013#-LB0TXhQ1zPTbLWFSJ9r:-LB14Rgz9ew_sjgmKail:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/096f11ea055832aa1fe3e29b5077978aa1227751/flow-components-parent/flow-code-generator-api/src/test/java/com/vaadin/generator/ComponentGeneratorTest.java#L952)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Same thing here. The `not` method alone only evaluates equality.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4013)*

**Comment by gilberto-torrezan** [comment]
Reviewed 34 of 36 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4013)*

**Comment by gilberto-torrezan** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4013#-:-LB15QVK0hI8DhS7aLL9:bnfp4nl)*

**Pull request merged**
