### PR TITLE
Make ComponentRenderers use virtual children

### PR DESCRIPTION
**Pull request by gilberto-torrezan**
These are the changes needed for Grid to use ComponentRenderers based on virtual children instead of a real element in the DOM tree.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3116)

### CODE REVIEW

**Comment by ahie** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[flow-data/src/main/java/com/vaadin/data/provider/PassivationListener.java, line 28 at r2](https://reviewable.io:443/reviews/vaadin/flow/3116#-L-p1BkHW-EYmONrbIDl:-L-p1BkHW-EYmONrbIDm:bget6zf) ([raw file](https://github.com/vaadin/flow/blob/d808801a76573e99192055caf48eb5676733e1c0/flow-data/src/main/java/com/vaadin/data/provider/PassivationListener.java#L28)):*
> ```Java
>  */
> @FunctionalInterface
> public interface PassivationListener extends Serializable {
> ```

Seems to me this concept is very similar to `destroyData`/`destroyAllData` of the `DataGenerator`.  Could that be used instead?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3116)*

**Comment by gilberto-torrezan** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[flow-data/src/main/java/com/vaadin/data/provider/PassivationListener.java, line 28 at r2](https://reviewable.io:443/reviews/vaadin/flow/3116#-L-p1BkHW-EYmONrbIDl:-L-p3OPr6EULQFPQpHFQ:bd80bcr) ([raw file](https://github.com/vaadin/flow/blob/d808801a76573e99192055caf48eb5676733e1c0/flow-data/src/main/java/com/vaadin/data/provider/PassivationListener.java#L28)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

Seems to me this concept is very similar to `destroyData`/`destroyAllData` of the `DataGenerator`.  Could that be used instead?
</blockquote></details>

Seems like it but... there's no mention to those methods on the `DataCommunicator` at all. At they even supported?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3116)*

**Comment by gilberto-torrezan** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[flow-data/src/main/java/com/vaadin/data/provider/PassivationListener.java, line 28 at r2](https://reviewable.io:443/reviews/vaadin/flow/3116#-L-p1BkHW-EYmONrbIDl:-L-p3togd84i8sbD3pke:b-ivlsx3) ([raw file](https://github.com/vaadin/flow/blob/d808801a76573e99192055caf48eb5676733e1c0/flow-data/src/main/java/com/vaadin/data/provider/PassivationListener.java#L28)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Seems like it but... there's no mention to those methods on the `DataCommunicator` at all. At they even supported?
</blockquote></details>

*Are they

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3116)*

**Comment by ahie** [comment]
Reviewed 2 of 7 files at r1.
Review status: 2 of 7 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[flow-data/src/main/java/com/vaadin/data/provider/PassivationListener.java, line 28 at r2](https://reviewable.io:443/reviews/vaadin/flow/3116#-L-p1BkHW-EYmONrbIDl:-L-p7JEsnIcCx1GU-CSU:b-b7a8f7) ([raw file](https://github.com/vaadin/flow/blob/d808801a76573e99192055caf48eb5676733e1c0/flow-data/src/main/java/com/vaadin/data/provider/PassivationListener.java#L28)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

*Are they
</blockquote></details>

`destroyAllData` is in use, but `destroyData` isn't called, perhaps because no data generator has had to drop internal data on passivation. In the data communicator instead of calling
```
notifyPassivationListeners(passivated);
``` 
you could do something like this
```
passivated.forEach(key -> dataGenerator.destroyData(keyMapper.get(key)));
```
that is, if the data generator pattern makes sense for the renderer.

---

*[flow-server/src/main/java/com/vaadin/ui/renderers/ComponentTemplateRenderer.java, line 57 at r2](https://reviewable.io:443/reviews/vaadin/flow/3116#-L-p9DP9pHFyAPH2kgYI:-L-p9DP9pHFyAPH2kgYJ:b-sd0qgu) ([raw file](https://github.com/vaadin/flow/blob/d808801a76573e99192055caf48eb5676733e1c0/flow-server/src/main/java/com/vaadin/ui/renderers/ComponentTemplateRenderer.java#L57)):*
> componentRendererTag

Should this be mutable? Could it just be set in a constructor or a protected getter method that subclasses could override? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3116)*

**Comment by gilberto-torrezan** [comment]
Review status: 2 of 7 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[flow-data/src/main/java/com/vaadin/data/provider/PassivationListener.java, line 28 at r2](https://reviewable.io:443/reviews/vaadin/flow/3116#-L-p1BkHW-EYmONrbIDl:-L-pERRrGNbcKEacIZb_:bybhk61) ([raw file](https://github.com/vaadin/flow/blob/d808801a76573e99192055caf48eb5676733e1c0/flow-data/src/main/java/com/vaadin/data/provider/PassivationListener.java#L28)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

`destroyAllData` is in use, but `destroyData` isn't called, perhaps because no data generator has had to drop internal data on passivation. In the data communicator instead of calling
```
notifyPassivationListeners(passivated);
``` 
you could do something like this
```
passivated.forEach(key -> dataGenerator.destroyData(keyMapper.get(key)));
```
that is, if the data generator pattern makes sense for the renderer.
</blockquote></details>

All right, that reduces some other complexity in the Grid as well. I will refactor and repush.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3116)*

**Comment by ahie** [comment]
Reviewed 1 of 7 files at r1.
Review status: 3 of 7 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[flow-server/src/main/java/com/vaadin/server/startup/RouteTarget.java, line 91 at r2](https://reviewable.io:443/reviews/vaadin/flow/3116#-L-pF4E9wXqQwsLlIkv3:-L-pF4E9wXqQwsLlIkv4:bs8btxn) ([raw file](https://github.com/vaadin/flow/blob/d808801a76573e99192055caf48eb5676733e1c0/flow-server/src/main/java/com/vaadin/server/startup/RouteTarget.java#L91)):*
> ```Java
>             throw new InvalidRouteConfigurationException(String.format(
>                     "Navigation targets must have unique routes, found navigation targets '%s' and '%s' with parameter have the same route.",
>                     getClassName(parameter), getClassName(target)));
> ```

These changes seem unrelated. Judging by the change these were made to avoid a NPE, so I guess it is fine to include these small changes.

---

*[flow-server/src/main/java/com/vaadin/server/startup/RouteTarget.java, line 133 at r2](https://reviewable.io:443/reviews/vaadin/flow/3116#-L-pFjdQIrgGWEa4V3gi:-L-pFjdQIrgGWEa4V3gj:b-xe6yrd) ([raw file](https://github.com/vaadin/flow/blob/d808801a76573e99192055caf48eb5676733e1c0/flow-server/src/main/java/com/vaadin/server/startup/RouteTarget.java#L133)):*
> ```Java
>     }
> 
>     private String getClassName(Class<?> clazz) {
> ```

Could be static.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3116)*

**Comment by gilberto-torrezan** [comment]
Review status: 2 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/ui/renderers/ComponentTemplateRenderer.java, line 57 at r2](https://reviewable.io:443/reviews/vaadin/flow/3116#-L-p9DP9pHFyAPH2kgYI:-L-pK33DQOZ8dsWhxDiK:b-9pfjod) ([raw file](https://github.com/vaadin/flow/blob/d808801a76573e99192055caf48eb5676733e1c0/flow-server/src/main/java/com/vaadin/ui/renderers/ComponentTemplateRenderer.java#L57)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

> componentRendererTag

Should this be mutable? Could it just be set in a constructor or a protected getter method that subclasses could override? 
</blockquote></details>

That's a problem. The developer is not supposed to know which subclass should he pass to the Grid for it to work properly. So internally in the Grid we set this attribute to `flow-grid-component-renderer` when rendering cells (the headers/footers still use the standard `flow-component-renderer`).

---

*[flow-data/src/main/java/com/vaadin/data/provider/PassivationListener.java, line 28 at r2](https://reviewable.io:443/reviews/vaadin/flow/3116#-L-p1BkHW-EYmONrbIDl:-L-pMMHSV9-ekGayK_CX:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/d808801a76573e99192055caf48eb5676733e1c0/flow-data/src/main/java/com/vaadin/data/provider/PassivationListener.java#L28)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

All right, that reduces some other complexity in the Grid as well. I will refactor and repush.
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/server/startup/RouteTarget.java, line 91 at r2](https://reviewable.io:443/reviews/vaadin/flow/3116#-L-pF4E9wXqQwsLlIkv3:-L-pJryAisYfoM9Z4se1:bexzkhx) ([raw file](https://github.com/vaadin/flow/blob/d808801a76573e99192055caf48eb5676733e1c0/flow-server/src/main/java/com/vaadin/server/startup/RouteTarget.java#L91)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

These changes seem unrelated. Judging by the change these were made to avoid a NPE, so I guess it is fine to include these small changes.
</blockquote></details>

Reverted after Mikael's patch.

---

*[flow-server/src/main/java/com/vaadin/server/startup/RouteTarget.java, line 133 at r2](https://reviewable.io:443/reviews/vaadin/flow/3116#-L-pFjdQIrgGWEa4V3gi:-L-pJvb3-pOXBGwEiH_i:bexzkhx) ([raw file](https://github.com/vaadin/flow/blob/d808801a76573e99192055caf48eb5676733e1c0/flow-server/src/main/java/com/vaadin/server/startup/RouteTarget.java#L133)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

Could be static.
</blockquote></details>

Reverted after Mikael's patch.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3116)*

**Comment by ahie** [comment]
Reviewed 1 of 7 files at r1, 3 of 3 files at r3.
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/ui/renderers/ComponentTemplateRenderer.java, line 57 at r2](https://reviewable.io:443/reviews/vaadin/flow/3116#-L-p9DP9pHFyAPH2kgYI:-L-pgaHZT2SEJzehJjSz:bjpegwa) ([raw file](https://github.com/vaadin/flow/blob/d808801a76573e99192055caf48eb5676733e1c0/flow-server/src/main/java/com/vaadin/ui/renderers/ComponentTemplateRenderer.java#L57)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

That's a problem. The developer is not supposed to know which subclass should he pass to the Grid for it to work properly. So internally in the Grid we set this attribute to `flow-grid-component-renderer` when rendering cells (the headers/footers still use the standard `flow-component-renderer`).
</blockquote></details>

Could instead an overload `getTemplate(String)` be added? As far as I can see, that is the only place where it is used and this way the ordering of operations wouldn't matter. The no-args overload `getTemplate()` would then use the default string `"flow-component-renderer"`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3116)*

**Comment by ahie** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3116)*

**Comment by gilberto-torrezan** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-server/src/main/java/com/vaadin/ui/renderers/ComponentTemplateRenderer.java, line 57 at r2](https://reviewable.io:443/reviews/vaadin/flow/3116#-L-p9DP9pHFyAPH2kgYI:-L-pxm_ApZ-EOdwO6ApS:bg29b5t) ([raw file](https://github.com/vaadin/flow/blob/d808801a76573e99192055caf48eb5676733e1c0/flow-server/src/main/java/com/vaadin/ui/renderers/ComponentTemplateRenderer.java#L57)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

Could instead an overload `getTemplate(String)` be added? As far as I can see, that is the only place where it is used and this way the ordering of operations wouldn't matter. The no-args overload `getTemplate()` would then use the default string `"flow-component-renderer"`.
</blockquote></details>

That was my first approach actually. I reverted that because it made the generic parts on Grid (the ones that are the same for Template and Component) to be not generic anymore, leading to completely two different implementations and causing a lot of refactoring. I can revert that again and push, but that will only be visible in the `vaadin-grid-flow` repository.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3116)*

**Comment by gilberto-torrezan** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-server/src/main/java/com/vaadin/ui/renderers/ComponentTemplateRenderer.java, line 57 at r2](https://reviewable.io:443/reviews/vaadin/flow/3116#-L-p9DP9pHFyAPH2kgYI:-L-q28RDqgA-Ob8VQujZ:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/d808801a76573e99192055caf48eb5676733e1c0/flow-server/src/main/java/com/vaadin/ui/renderers/ComponentTemplateRenderer.java#L57)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

That was my first approach actually. I reverted that because it made the generic parts on Grid (the ones that are the same for Template and Component) to be not generic anymore, leading to completely two different implementations and causing a lot of refactoring. I can revert that again and push, but that will only be visible in the `vaadin-grid-flow` repository.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3116)*

**Comment by ahie** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3116)*

**Comment by ahie** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3116#-:-L-q2Y65-BUc7Fo1QC6X:bnfp4nl)*

**Pull request merged**
