### PR TITLE
Throw an exception if the generator return value is null

### PR DESCRIPTION
**Pull request by denis-anisimov**
Fix for #2996

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3125)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
One more PR is required to fix the issue for the combobox.

**Comment by SomeoneToIgnore** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/ui/renderers/IconRenderer.java, line 92 at r1](https://reviewable.io:443/reviews/vaadin/flow/3125#-L-roO7OXImaH6q_aCNu:-L-roO7OXImaH6q_aCNv:b-5d3ea5) ([raw file](https://github.com/vaadin/flow/blob/85f4edce6fa500c69f2b2e40dd59a8fd4ffe9967/flow-server/src/main/java/com/vaadin/ui/renderers/IconRenderer.java#L92)):*
We have a javadoc that ways that this `null` should be

> shown as an empty string

https://github.com/vaadin/flow/blob/942aba0182999f05115017e88fcef849732da6db/flow-server/src/main/java/com/vaadin/ui/common/ItemLabelGenerator.java#L36

Should we update the javadoc also?

As for the other generator, would it make sense to add javadoc about the limitations?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3125)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/ui/renderers/IconRenderer.java, line 92 at r1](https://reviewable.io:443/reviews/vaadin/flow/3125#-L-roO7OXImaH6q_aCNu:-L-tqXCL__OOXFUOAmY0:b81np6x) ([raw file](https://github.com/vaadin/flow/blob/85f4edce6fa500c69f2b2e40dd59a8fd4ffe9967/flow-server/src/main/java/com/vaadin/ui/renderers/IconRenderer.java#L92)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

We have a javadoc that ways that this `null` should be

> shown as an empty string

https://github.com/vaadin/flow/blob/942aba0182999f05115017e88fcef849732da6db/flow-server/src/main/java/com/vaadin/ui/common/ItemLabelGenerator.java#L36

Should we update the javadoc also?

As for the other generator, would it make sense to add javadoc about the limitations?
</blockquote></details>

Done.

About other generators: what generators you have in your mind?
I don't see any other generators at the moment.
There are renderers in their package.
I've updated the renderer Javadoc.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3125)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/ui/renderers/IconRenderer.java, line 86 at r1](https://reviewable.io:443/reviews/vaadin/flow/3125#-L-qRvYBJSvuCoJu-LQ7-r1-86:-L-uX7M70wumakLAla6l:bgzuwht) ([raw file](https://github.com/vaadin/flow/blob/85f4edce6fa500c69f2b2e40dd59a8fd4ffe9967/flow-server/src/main/java/com/vaadin/ui/renderers/IconRenderer.java#L86)):*
<details><summary><i>Previously, vaadin-bot (Vaadin Bot) wrote…</i></summary><blockquote>

MAJOR Format-string method String.format(String, Object[]) called with format string "Got 'null' as an icon for the item '%s'. Icon generator instance may not return 'null' values" wants 1 arguments but is given 2 in com.vaadin.ui.renderers.IconRenderer.createComponent(Object) [rule](https://sonar.projects.vaadin.com/coding_rules#rule_key=findbugs%3AVA_FORMAT_STRING_EXTRA_ARGUMENTS_PASSED)
</blockquote></details>

It's, actually, a nice one: there are two parameters and one '%s' in this `String.format`.

---

*[flow-server/src/main/java/com/vaadin/ui/renderers/IconRenderer.java, line 92 at r1](https://reviewable.io:443/reviews/vaadin/flow/3125#-L-roO7OXImaH6q_aCNu:-L-uXXCE407JbCCvpE4i:bbe9haf) ([raw file](https://github.com/vaadin/flow/blob/85f4edce6fa500c69f2b2e40dd59a8fd4ffe9967/flow-server/src/main/java/com/vaadin/ui/renderers/IconRenderer.java#L92)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Done.

About other generators: what generators you have in your mind?
I don't see any other generators at the moment.
There are renderers in their package.
I've updated the renderer Javadoc.
</blockquote></details>

I was referring to `iconGenerator` that has no description on behavior, but I don't know if it's feasible to describe it, just a proposal.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3125)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-server/src/main/java/com/vaadin/ui/renderers/IconRenderer.java, line 86 at r1](https://reviewable.io:443/reviews/vaadin/flow/3125#-L-qRvYBJSvuCoJu-LQ7-r1-86:-L-vfYlpWV5a-7Zak8_2:b-8ty6jv) ([raw file](https://github.com/vaadin/flow/blob/85f4edce6fa500c69f2b2e40dd59a8fd4ffe9967/flow-server/src/main/java/com/vaadin/ui/renderers/IconRenderer.java#L86)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

It's, actually, a nice one: there are two parameters and one '%s' in this `String.format`.
</blockquote></details>

Thanks, copy/paste as usual.

---

*[flow-server/src/main/java/com/vaadin/ui/renderers/IconRenderer.java, line 92 at r1](https://reviewable.io:443/reviews/vaadin/flow/3125#-L-roO7OXImaH6q_aCNu:-L-vfbQTZl1uO7Mr_Vcz:bx0q9hq) ([raw file](https://github.com/vaadin/flow/blob/85f4edce6fa500c69f2b2e40dd59a8fd4ffe9967/flow-server/src/main/java/com/vaadin/ui/renderers/IconRenderer.java#L92)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

I was referring to `iconGenerator` that has no description on behavior, but I don't know if it's feasible to describe it, just a proposal.
</blockquote></details>

Icon generator is just a `SerializableFunction`.
I'm quite uncertain that we should introduce a new interface here for the icon generator just because of Javadoc.
Especially considering that nobody reads javadocs until something goes in unexpected way.

I've been thinking about javadoc for icon generator as well, but decided to skip it since it's just a `SerializableFunction`.
I would suggest to introduce the interface and javadocs once there is a user request.
Or we will need this interface somewhere in another place.
But not now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3125)*

**Comment by denis-anisimov** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-server/src/main/java/com/vaadin/ui/renderers/IconRenderer.java, line 86 at r1](https://reviewable.io:443/reviews/vaadin/flow/3125#-L-qRvYBJSvuCoJu-LQ7-r1-86:-L-vgwIP1Gk6D1Z_sBzH:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/85f4edce6fa500c69f2b2e40dd59a8fd4ffe9967/flow-server/src/main/java/com/vaadin/ui/renderers/IconRenderer.java#L86)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Thanks, copy/paste as usual.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3125)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3125)*

**Pull request merged**
