### PR TITLE
Make lock checking more strict

### LINKED ISSUE #3790: Improve debuggability of missing session locking
Various cases of `assert session.hasLock()` has been carried over from Vaadin 8, but the coverage is currently not good enough to catch the most common cases. The main omission is that `ConnectorTracker` is not carried over. This class contained an assert for every time a connector was marked as dirty, which covered very many cases.

We should introduce some additional asserts so that at least state tree modifications and `executeJavaScript` are also covered.

### PR DESCRIPTION
**Pull request by Legioth**
Fixes #3790

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3797)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 19 of 19 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[flow-server/src/main/java/com/vaadin/flow/internal/StateTree.java, line 362 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3797#-L8rFjBEDAb_X-Wm5QRU:-L8rFjBEDAb_X-Wm5QRV:b-s16fze) ([raw file](https://github.com/vaadin/flow/blob/4b292b42f7956ab29ad28565e41b5512fe5594d0/flow-server/src/main/java/com/vaadin/flow/internal/StateTree.java#L362)):*
> ```
> if (ui != null) {
> ```

Are there usecases when it's `null` ?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3797)*

**Comment by Legioth** [comment]
Review status: 18 of 19 files reviewed at latest revision, all discussions resolved.

---

*[flow-server/src/main/java/com/vaadin/flow/internal/StateTree.java, line 362 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3797#-L8rFjBEDAb_X-Wm5QRU:-L8zwBVo1k-Ozo3bWnJ7:bfe7zfj) ([raw file](https://github.com/vaadin/flow/blob/d4b1cf83919d241c9e29ed273cd5da203584486e/flow-server/src/main/java/com/vaadin/flow/internal/StateTree.java#L362)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
> if (ui != null) {
> ```

Are there usecases when it's `null` ?
</blockquote></details>

Happens during initialization. Added a comment about this to the code.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3797)*

**Comment by denis-anisimov** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[flow-server/src/main/java/com/vaadin/flow/internal/StateTree.java, line 362 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3797#-L8rFjBEDAb_X-Wm5QRU:-L9E7KWJE0t8zVtF56ga:b-ca8rh5) ([raw file](https://github.com/vaadin/flow/blob/d4b1cf83919d241c9e29ed273cd5da203584486e/flow-server/src/main/java/com/vaadin/flow/internal/StateTree.java#L362)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

Happens during initialization. Added a comment about this to the code.
</blockquote></details>

`ui`  is `final` in `StateTree` so it may be causes by `new RootNode` only but this may be fixed via changing the order........

Whatever, it's not blocking.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3797#-:-L9E7hfm9OOyWFX6lbNh:bnfp4nl)*

**Comment by Legioth** [comment]
Review status: 17 of 19 files reviewed at latest revision, all discussions resolved.

---

*[flow-server/src/main/java/com/vaadin/flow/internal/StateTree.java, line 362 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3797#-L8rFjBEDAb_X-Wm5QRU:-L9KcXSB42xDrLSoaZqH:b8j3g0b) ([raw file](https://github.com/vaadin/flow/blob/d4b1cf83919d241c9e29ed273cd5da203584486e/flow-server/src/main/java/com/vaadin/flow/internal/StateTree.java#L362)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

`ui`  is `final` in `StateTree` so it may be causes by `new RootNode` only but this may be fixed via changing the order........

Whatever, it's not blocking.
</blockquote></details>

The problem was not that `ui` would be null, but rather that the `UI` instance is not yet fully initialized, which causes `getSession()` to explode. I fixed this by changing `StateTree` to be initialized based on `UIInternals` instead of `UI`.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3797)*

**Comment by denis-anisimov** [comment]
:lgtm:

---

Review status: 17 of 19 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-server/src/main/java/com/vaadin/flow/internal/StateTree.java, line 362 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3797#-L8rFjBEDAb_X-Wm5QRU:-L9Khqkd9-ZuWQblFW5U:b32w0x) ([raw file](https://github.com/vaadin/flow/blob/d4b1cf83919d241c9e29ed273cd5da203584486e/flow-server/src/main/java/com/vaadin/flow/internal/StateTree.java#L362)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

The problem was not that `ui` would be null, but rather that the `UI` instance is not yet fully initialized, which causes `getSession()` to explode. I fixed this by changing `StateTree` to be initialized based on `UIInternals` instead of `UI`.
</blockquote></details>

OK

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3797#-:-L9Khs7QDO3t_woK0kv-:bnfp4nl)*

**Comment by denis-anisimov** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3797)*

**Comment by gilberto-torrezan** [comment]
:lgtm:

---

Reviewed 3 of 19 files at r1, 16 of 23 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3797#-:-LAqfB1U-5MrXPZ0-xnW:bnfp4nl)*

**Pull request merged**
