### PR TITLE
Add keyboard events

### LINKED ISSUE #2449: Improved keyboard shortcuts API
For instance, if i want to have a search field with a search button, pressing the enter key should also perform the search. in V8 i could use a click shortcut, but couldn't find anything similar for Flow.

I'm sure it can be done with JS, but it would be really, really good if there was a Java API for it.

### PR DESCRIPTION
**Pull request by heruan**
This PR adds keyboard events and notifiers mixins, following the latest W3 [spec](https://www.w3.org/TR/uievents/#interface-keyboardevent).

Added files:

- `Key`: class of keys constants mapped to their `event.key` value;
- `KeyModifier`: enum of modifiers keys (now <kbd>CTRL</kbd>, <kbd>SHIFT</kbd>, <kbd>ALT</kbd> and <kbd>META</kbd> but can be extend to others as well);
- `KeyLocation`: enum of key location on keyboard;
- `KeyboardEvent`: abstract class for keyboard events;
- `KeyDownEvent`: class for `keydown` event;
- `KeyPressEvent`: class for `keypress` event;
- `KeyUpEvent`: class for `keyup` event;
- `KeyNotifier`: mixin interface for keyboard event listeners.

Use case example, in the case `TextField`/`TextArea` implementing `KeyNotifier`:

```java
TextField field = new TextField("Search");
field.addKeyUpListener(Key.ENTER, event -> doSearch(field.getValue());

TextArea area = new TextArea();
area.addKeyUpListener(event -> {
    switch (event.getKey()) {
        case HASH:
            showHashTagDropdown();
            break;
        case AT:
            showMentionDropdown();
            break;
    }
});
```

Might be a start to fix #2449.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3110)

### CODE REVIEW

**Comment by heruan** [comment]
Adding also composition events:

- `CompositionStartEvent` for DOM event `compositionstart`;
- `CompositionUpdateEvent` for DOM event `compositionupdate`;
- `CompositionEndEvent` for DOM event `compositionend`;
- `CompositionNotifier` mixin interface.

**Comment by caalador** [comment]
There are 3 JavaDoc errors that fail the build in `flow-server/src/main/java/com/vaadin/ui/event/Key.java`:
```
/Key.java:249: error: bad HTML entity
      * String for "<code>&</code>" key.

Key.java:364: error: malformed HTML
      * String for "<code><</code>" key.

Key.java:374: error: bad use of '>'
      * String for "<code>></code>" key.
```

Run ` mvn javadoc:javadoc -Dmaven.javadoc.skip=false` to check that javadocs are fine after the changes. There are some Warnings, but there shouldn't be Errors.

**Comment by heruan** [comment]
I notice that since I've parameterize the events for `HtmlComponent` the mixins cannot be implemented by e.g. `TextField`. Should I change the generic parameter to `Component`?

**Comment by SomeoneToIgnore** [comment]
Reviewed 2 of 14 files at r1, 10 of 12 files at r2, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/ui/event/CompositionEvent.java, line 51 at r4](https://reviewable.io:443/reviews/vaadin/flow/3110#-L04Q1HraMjN5ATHai69:-L04Q1HraMjN5ATHai6A:b-vg8gn7) ([raw file](https://github.com/vaadin/flow/blob/94182bc110e4c627bc8180427432b1f7ae69bbfa/flow-server/src/main/java/com/vaadin/ui/event/CompositionEvent.java#L51)):*
> ```Java
>         super(source, fromClient);
>         this.data = data;
>         this.locale = locale;
> ```

If `locale` will be `null`, you'll get an error only when you call `getLocation` method, which may be too late.
Should we
* introduce parameters checks
* require `Locale` object to be passed here

?

---

*[flow-server/src/main/java/com/vaadin/ui/event/CompositionEvent.java, line 75 at r4](https://reviewable.io:443/reviews/vaadin/flow/3110#-L04QPWENxEP48qGvjkp:-L04QPWENxEP48qGvjkq:b-j6ly4m) ([raw file](https://github.com/vaadin/flow/blob/94182bc110e4c627bc8180427432b1f7ae69bbfa/flow-server/src/main/java/com/vaadin/ui/event/CompositionEvent.java#L75)):*
> ```Java
> 
>     /**
>      * Gets the {@link Locale} of the event.
> ```

Can you elaborate a bit on what location we're getting from here? 
For now I see Locale only, but having some locale set up on a machine does not mean that the user is in the locale's location.
Also, the subclasses mention no `location` when accepting locale in the constructors. only `language` of the events.

---

*[flow-server/src/main/java/com/vaadin/ui/event/CompositionNotifier.java, line 23 at r4](https://reviewable.io:443/reviews/vaadin/flow/3110#-L04RVCja4SW99kTE_oh:-L04RTfkCvLXN331pMcB:bj1q6n5) ([raw file](https://github.com/vaadin/flow/blob/94182bc110e4c627bc8180427432b1f7ae69bbfa/flow-server/src/main/java/com/vaadin/ui/event/CompositionNotifier.java#L23)):*
> ```Java
>  * Mixin interface for components that support adding composition listeners to
>  * the their root elements.
>  *
> ```

Would it make sense to provide some link to the events' descriptions?

---

*[flow-server/src/main/java/com/vaadin/ui/event/Key.java, line 21 at r4](https://reviewable.io:443/reviews/vaadin/flow/3110#-L04UH86BYHnHldWNtPk:-L04UH86BYHnHldWNtPl:b-mpmibb) ([raw file](https://github.com/vaadin/flow/blob/94182bc110e4c627bc8180427432b1f7ae69bbfa/flow-server/src/main/java/com/vaadin/ui/event/Key.java#L21)):*
> ```Java
>  * Keyboard keys.
>  */
> public class Key {
> ```

Looks like it can be an enum, any reasons not to do so?

---

*[flow-server/src/main/java/com/vaadin/ui/event/KeyboardEvent.java, line 70 at r3](https://reviewable.io:443/reviews/vaadin/flow/3110#-L-gj2GfxF1ekIif-tDL-r3-70:-L04S2A5JyQkc1uMYdk8:b-bg4yvk) ([raw file](https://github.com/vaadin/flow/blob/c9967cea2b97213a0c5aa205eb0acecc84ace776/flow-server/src/main/java/com/vaadin/ui/event/KeyboardEvent.java#L70)):*
<details><summary><i>Previously, vaadin-bot (Vaadin Bot) wrote…</i></summary><blockquote>

MAJOR Constructor has 10 parameters, which is greater than 7 authorized. [rule](https://sonar.projects.vaadin.com/coding_rules#rule_key=squid%3AS00107)
</blockquote></details>

May it be easier to work store modifiers as `EnumSet<KeyModifier>`  here also?
Then we can remove all `is` methods and check if a `Set` contains the required modifier.

I understand that you need to use `@EventData` annotations in the subclasses, but here you don't need it at all.
It will simplify `KeyEventListener#onComponentEvent` a lot.

---

*[flow-server/src/main/java/com/vaadin/ui/event/KeyboardEvent.java, line 71 at r4](https://reviewable.io:443/reviews/vaadin/flow/3110#-L04TWhlhyZEuLoI95wG:-L04TWhlhyZEuLoI95wH:b8tffw8) ([raw file](https://github.com/vaadin/flow/blob/94182bc110e4c627bc8180427432b1f7ae69bbfa/flow-server/src/main/java/com/vaadin/ui/event/KeyboardEvent.java#L71)):*
> int location

You convert it into`KeyLocation` in a getter only, lazily.
Should we fail fast instead, right in the constructor if someone passes non-existing value? 
Or rather require `KeyLocation` as a parameter in the constructor?
What is the reason for the lazy conversion anyway?

---

*[flow-server/src/main/java/com/vaadin/ui/event/KeyEventListener.java, line 62 at r4](https://reviewable.io:443/reviews/vaadin/flow/3110#-L04TETn99BVZHHVJ1aO:-L04TETn99BVZHHVJ1aP:b-8f8hyy) ([raw file](https://github.com/vaadin/flow/blob/94182bc110e4c627bc8180427432b1f7ae69bbfa/flow-server/src/main/java/com/vaadin/ui/event/KeyEventListener.java#L62)):*
> ```Java
>     @Override
>     public void onComponentEvent(E event) {
>         if (event.getKey().equals(key)) {
> ```

This looks like an actual logic.
Should we test it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3110)*

**Comment by heruan** [comment]
*[flow-server/src/main/java/com/vaadin/ui/event/CompositionEvent.java, line 51 at r4](https://reviewable.io:443/reviews/vaadin/flow/3110#-L04Q1HraMjN5ATHai69:-L04lJPXFbcTMoFhMIwH:b-6mvej7) ([raw file](https://github.com/vaadin/flow/blob/94182bc110e4c627bc8180427432b1f7ae69bbfa/flow-server/src/main/java/com/vaadin/ui/event/CompositionEvent.java#L51)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

If `locale` will be `null`, you'll get an error only when you call `getLocation` method, which may be too late.
Should we
* introduce parameters checks
* require `Locale` object to be passed here

?
</blockquote></details>

Since it's legit for the DOM event to have `locale` undefined, in that case I'd rather set the field to `null`. And of course convert to `Locale` in the constructor, no need to be done lazily!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3110)*

**Comment by heruan** [comment]
*[flow-server/src/main/java/com/vaadin/ui/event/CompositionEvent.java, line 75 at r4](https://reviewable.io:443/reviews/vaadin/flow/3110#-L04QPWENxEP48qGvjkp:-L04ll8X-f3bHRnGa74N:bhofjja) ([raw file](https://github.com/vaadin/flow/blob/94182bc110e4c627bc8180427432b1f7ae69bbfa/flow-server/src/main/java/com/vaadin/ui/event/CompositionEvent.java#L75)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Can you elaborate a bit on what location we're getting from here? 
For now I see Locale only, but having some locale set up on a machine does not mean that the user is in the locale's location.
Also, the subclasses mention no `location` when accepting locale in the constructors. only `language` of the events.
</blockquote></details>

`getLocation` was a typo, it should have been `getLocale` and it's the locale (if available) of the composition sessions, i.e. the language of the text being composed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3110)*

**Comment by heruan** [comment]
*[flow-server/src/main/java/com/vaadin/ui/event/CompositionNotifier.java, line 23 at r4](https://reviewable.io:443/reviews/vaadin/flow/3110#-L04RVCja4SW99kTE_oh:-L04m78FMEUO0WDEIDGH:b16ofku) ([raw file](https://github.com/vaadin/flow/blob/94182bc110e4c627bc8180427432b1f7ae69bbfa/flow-server/src/main/java/com/vaadin/ui/event/CompositionNotifier.java#L23)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Would it make sense to provide some link to the events' descriptions?
</blockquote></details>

JavaDoc links? Of course, I'll add them.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3110)*

**Comment by heruan** [comment]
*[flow-server/src/main/java/com/vaadin/ui/event/Key.java, line 21 at r4](https://reviewable.io:443/reviews/vaadin/flow/3110#-L04UH86BYHnHldWNtPk:-L04mC_zusnssdT6n-qq:bopzt3t) ([raw file](https://github.com/vaadin/flow/blob/94182bc110e4c627bc8180427432b1f7ae69bbfa/flow-server/src/main/java/com/vaadin/ui/event/Key.java#L21)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Looks like it can be an enum, any reasons not to do so?
</blockquote></details>

The constants in `Key` are just shortcuts, since every char produced by pressing a key on the keyboard can be the `key` value of the event. I guess we can shortcut much more keys (e.g. `a`–`z` and maybe even `A`–`Z`) but we'll likely never be exhaustive with an enum.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3110)*

**Comment by SomeoneToIgnore** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/ui/event/CompositionNotifier.java, line 23 at r4](https://reviewable.io:443/reviews/vaadin/flow/3110#-L04RVCja4SW99kTE_oh:-L04nRFQA1n1_YdWwcbn:bbop070) ([raw file](https://github.com/vaadin/flow/blob/94182bc110e4c627bc8180427432b1f7ae69bbfa/flow-server/src/main/java/com/vaadin/ui/event/CompositionNotifier.java#L23)):*
<details><summary><i>Previously, heruan (Giovanni Lovato) wrote…</i></summary><blockquote>

JavaDoc links? Of course, I'll add them.
</blockquote></details>

I meant more like a link to MSDN documentation, some people may be confused by the events.
But I have no strong opinion on this, up to you.

---

*[flow-server/src/main/java/com/vaadin/ui/event/Key.java, line 21 at r4](https://reviewable.io:443/reviews/vaadin/flow/3110#-L04UH86BYHnHldWNtPk:-L04n_HfIZRvn4N_YExl:b-kufkx2) ([raw file](https://github.com/vaadin/flow/blob/94182bc110e4c627bc8180427432b1f7ae69bbfa/flow-server/src/main/java/com/vaadin/ui/event/Key.java#L21)):*
<details><summary><i>Previously, heruan (Giovanni Lovato) wrote…</i></summary><blockquote>

The constants in `Key` are just shortcuts, since every char produced by pressing a key on the keyboard can be the `key` value of the event. I guess we can shortcut much more keys (e.g. `a`–`z` and maybe even `A`–`Z`) but we'll likely never be exhaustive with an enum.
</blockquote></details>

I see, thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3110)*

**Comment by heruan** [comment]
*[flow-server/src/main/java/com/vaadin/ui/event/KeyboardEvent.java, line 70 at r3](https://reviewable.io:443/reviews/vaadin/flow/3110#-L-gj2GfxF1ekIif-tDL-r3-70:-L04s0W65sfaQN2ituvj:b3dbzma) ([raw file](https://github.com/vaadin/flow/blob/c9967cea2b97213a0c5aa205eb0acecc84ace776/flow-server/src/main/java/com/vaadin/ui/event/KeyboardEvent.java#L70)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

May it be easier to work store modifiers as `EnumSet<KeyModifier>`  here also?
Then we can remove all `is` methods and check if a `Set` contains the required modifier.

I understand that you need to use `@EventData` annotations in the subclasses, but here you don't need it at all.
It will simplify `KeyEventListener#onComponentEvent` a lot.
</blockquote></details>

Agreed! I'll keep the booleans of the super constructor and populate the set there.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3110)*

**Comment by heruan** [comment]
*[flow-server/src/main/java/com/vaadin/ui/event/KeyboardEvent.java, line 70 at r3](https://reviewable.io:443/reviews/vaadin/flow/3110#-L-gj2GfxF1ekIif-tDL-r3-70:-L04siqjrfY4r8J5huP-:b-c874t5) ([raw file](https://github.com/vaadin/flow/blob/c9967cea2b97213a0c5aa205eb0acecc84ace776/flow-server/src/main/java/com/vaadin/ui/event/KeyboardEvent.java#L70)):*
<details><summary><i>Previously, heruan (Giovanni Lovato) wrote…</i></summary><blockquote>

Agreed! I'll keep the booleans of the super constructor and populate the set there.
</blockquote></details>

Still, other events e.g. `ClickEvent` have `is...` methods. Maybe I should leave them here for consistency?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3110)*

**Comment by heruan** [comment]
*[flow-server/src/main/java/com/vaadin/ui/event/KeyboardEvent.java, line 71 at r4](https://reviewable.io:443/reviews/vaadin/flow/3110#-L04TWhlhyZEuLoI95wG:-L04sSmIre26Gj6ToS1G:bksix2j) ([raw file](https://github.com/vaadin/flow/blob/94182bc110e4c627bc8180427432b1f7ae69bbfa/flow-server/src/main/java/com/vaadin/ui/event/KeyboardEvent.java#L71)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

> int location

You convert it into`KeyLocation` in a getter only, lazily.
Should we fail fast instead, right in the constructor if someone passes non-existing value? 
Or rather require `KeyLocation` as a parameter in the constructor?
What is the reason for the lazy conversion anyway?
</blockquote></details>

No reason, actually. Definitely better on the constructor!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3110)*

**Comment by heruan** [comment]
*[flow-server/src/main/java/com/vaadin/ui/event/KeyEventListener.java, line 62 at r4](https://reviewable.io:443/reviews/vaadin/flow/3110#-L04TETn99BVZHHVJ1aO:-L04tvOXtLdb3hr_HuQc:b-95q7k2) ([raw file](https://github.com/vaadin/flow/blob/94182bc110e4c627bc8180427432b1f7ae69bbfa/flow-server/src/main/java/com/vaadin/ui/event/KeyEventListener.java#L62)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

This looks like an actual logic.
Should we test it?
</blockquote></details>

Probably yes :wink: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3110)*

**Comment by heruan** [comment]
*[flow-server/src/main/java/com/vaadin/ui/event/KeyboardEvent.java, line 70 at r3](https://reviewable.io:443/reviews/vaadin/flow/3110#-L-gj2GfxF1ekIif-tDL-r3-70:-L04xnIRdOvQ9oyGQnKO:bg1p2c4) ([raw file](https://github.com/vaadin/flow/blob/c9967cea2b97213a0c5aa205eb0acecc84ace776/flow-server/src/main/java/com/vaadin/ui/event/KeyboardEvent.java#L70)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Might make sense, up to you.
</blockquote></details>

If `KeyModifier` gets introduced, I'd use it in other events rather than the `is...` methods.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3110)*

**Comment by heruan** [comment]
Review status: 13 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/ui/event/CompositionEvent.java, line 51 at r4](https://reviewable.io:443/reviews/vaadin/flow/3110#-L04Q1HraMjN5ATHai69:-L04xdxRwBfvMb1qEKq4:ben9xin) ([raw file](https://github.com/vaadin/flow/blob/94182bc110e4c627bc8180427432b1f7ae69bbfa/flow-server/src/main/java/com/vaadin/ui/event/CompositionEvent.java#L51)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Nice, so let's either do `Locale.forLanguageTag` in the constructor or just put `Locale locale` as a parameter then.
</blockquote></details>

I made it `Optional`, since it is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3110)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 1 of 1 files at r6.
Review status: 13 of 14 files reviewed at latest revision, 4 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/ui/event/CompositionEvent.java, line 31 at r6](https://reviewable.io:443/reviews/vaadin/flow/3110#-L04y6y0G_bkTgWumz68:-L04y6y0G_bkTgWumz69:b-atwqky) ([raw file](https://github.com/vaadin/flow/blob/9f18f131fde26ce4a5ffb1269940b8a677b9bb07/flow-server/src/main/java/com/vaadin/ui/event/CompositionEvent.java#L31)):*
> ```Java
> 
>     private final String data;
>     private final Optional<Locale> locale;
> ```

Is `ComponentEvent` serializable? 
If so, this won't work alas: `Optional` is not serializable and is intended to be used as method return type only.

---

*[flow-server/src/main/java/com/vaadin/ui/event/CompositionEvent.java, line 80 at r6](https://reviewable.io:443/reviews/vaadin/flow/3110#-L04yKlaCcDAtZYwo68o:-L04yKlaCcDAtZYwo68p:bqu4teh) ([raw file](https://github.com/vaadin/flow/blob/9f18f131fde26ce4a5ffb1269940b8a677b9bb07/flow-server/src/main/java/com/vaadin/ui/event/CompositionEvent.java#L80)):*
> ```Java
>      * @return the optional {@link Locale} of the event
>      */
>     public Optional<Locale> getLocale() {
> ```

Nice idea for the `Optional` return type here.

---

*[flow-server/src/main/java/com/vaadin/ui/event/KeyboardEvent.java, line 70 at r3](https://reviewable.io:443/reviews/vaadin/flow/3110#-L-gj2GfxF1ekIif-tDL-r3-70:-L04yQPWDclSt2dlWqd9:b-838vte) ([raw file](https://github.com/vaadin/flow/blob/c9967cea2b97213a0c5aa205eb0acecc84ace776/flow-server/src/main/java/com/vaadin/ui/event/KeyboardEvent.java#L70)):*
<details><summary><i>Previously, heruan (Giovanni Lovato) wrote…</i></summary><blockquote>

If `KeyModifier` gets introduced, I'd use it in other events rather than the `is...` methods.
</blockquote></details>

Ok :)

---

*[flow-server/src/main/java/com/vaadin/ui/event/KeyboardEvent.java, line 150 at r5](https://reviewable.io:443/reviews/vaadin/flow/3110#-L-gj2GfxF1ekIif-tDL-r5-150:-L04yS0j0aQ56Rthnt3U:b37pycx) ([raw file](https://github.com/vaadin/flow/blob/1b3a23137ae314a1db2a94807d98868cd125ec2f/flow-server/src/main/java/com/vaadin/ui/event/KeyboardEvent.java#L150)):*
<details><summary><i>Previously, vaadin-bot (Vaadin Bot) wrote…</i></summary><blockquote>

MINOR The return type of this method should be an interface such as "Set" rather than the implementation "EnumSet". [rule](https://sonar.projects.vaadin.com/coding_rules#rule_key=squid%3AS1319)
</blockquote></details>

If you'll be fixing that `Serializable` issue, can you also fix this and return a `Set`?
Another small win would be to make `modifiers` `private`, since why do we need to share it anyway when we have a getter for it?

All minors, up to you to fix.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3110)*

**Comment by SomeoneToIgnore** [comment]
*[flow-server/src/main/java/com/vaadin/ui/event/CompositionEvent.java, line 51 at r4](https://reviewable.io:443/reviews/vaadin/flow/3110#-L04Q1HraMjN5ATHai69:-L04yqhk6Jym8g_dWcOw:bvcz1o7) ([raw file](https://github.com/vaadin/flow/blob/94182bc110e4c627bc8180427432b1f7ae69bbfa/flow-server/src/main/java/com/vaadin/ui/event/CompositionEvent.java#L51)):*
<details><summary><i>Previously, heruan (Giovanni Lovato) wrote…</i></summary><blockquote>

I made it `Optional`, since it is.
</blockquote></details>

Yep, almost nailed it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3110)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3110)*

**Comment by SomeoneToIgnore** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3110#-:-L05-gCkpk4MbnH914f4:bnfp4nl)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 1 of 1 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3110)*

**Comment by heruan** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/ui/event/KeyboardEvent.java, line 150 at r5](https://reviewable.io:443/reviews/vaadin/flow/3110#-L-gj2GfxF1ekIif-tDL-r5-150:-L05-xwRcdh_OmDEdHpR:b-s50qhh) ([raw file](https://github.com/vaadin/flow/blob/1b3a23137ae314a1db2a94807d98868cd125ec2f/flow-server/src/main/java/com/vaadin/ui/event/KeyboardEvent.java#L150)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

If you'll be fixing that `Serializable` issue, can you also fix this and return a `Set`?
Another small win would be to make `modifiers` `private`, since why do we need to share it anyway when we have a getter for it?

All minors, up to you to fix.
</blockquote></details>

Sure! At first it was protected to add modifiers on subclasses, then I realized it was better to do that on the super constructor but I forgot to change the field visibility :sweat_smile: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3110)*

**Pull request merged**
