### PR TITLE
Add AbstractCompositeField

### PR DESCRIPTION
**Pull request by Legioth**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/4009)

### CODE REVIEW

**Comment by gilberto-torrezan** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/component/AbstractCompositeField.java, line 35 at r1](https://reviewable.io/reviews/vaadin/flow/4009#-LB-erXC353Plx7ZjFWt:-LB-erXC353Plx7ZjFWu:b66j5in) ([raw file](https://github.com/vaadin/flow/blob/d240949563bfe30cd3b0135393cdcff71194cd2d/flow-server/src/main/java/com/vaadin/flow/component/AbstractCompositeField.java#L35)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>  * @param <C>
>  *            the type of the content component
>  * @param <S>
>  *            the source type for value change events
>  * @param <T>
>  *            the value type
> ```
</details>


Anything against using more meaningful (yet more verbose) names for the parameterized types instead of single letters?

---

*[flow-server/src/main/java/com/vaadin/flow/component/AbstractCompositeField.java, line 89 at r1](https://reviewable.io/reviews/vaadin/flow/4009#-LB-pvMz3o7i3X2u-_3t:-LB-pvMz3o7i3X2u-_3u:bno1oxp) ([raw file](https://github.com/vaadin/flow/blob/d240949563bfe30cd3b0135393cdcff71194cd2d/flow-server/src/main/java/com/vaadin/flow/component/AbstractCompositeField.java#L89)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>      * If {@link #setModelValue(Object, boolean)} is called from within this
>      * method, then value of the last invocation will be used as the model value
>      * instead of the value passed to this method. In this case
>      * {@link #setPresentationValue(Object)} will not be called again. Changing
>      * the provided value might be useful if the provided value is sanitized.
> ```
</details>


Can you provide a test for that?

---

*[flow-server/src/main/java/com/vaadin/flow/component/internal/AbstractFieldSupport.java, line 217 at r1](https://reviewable.io/reviews/vaadin/flow/4009#-LB-p7Xk5XmvQKeTac2d:-LB-p7Xk5XmvQKeTac2e:b33iiqa) ([raw file](https://github.com/vaadin/flow/blob/d240949563bfe30cd3b0135393cdcff71194cd2d/flow-server/src/main/java/com/vaadin/flow/component/internal/AbstractFieldSupport.java#L217)):*
> ```Java
>         }
> 
>         return valueSetFromPresentationUpdate;
> ```

Impressed by Sonar on this one. The method is always returning `false`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4009)*

**Comment by denis-anisimov** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/component/AbstractCompositeField.java, line 24 at r1](https://reviewable.io/reviews/vaadin/flow/4009#-LB-oMBWEceuBmz4EEqW:-LB-oMBWEceuBmz4EEqX:busce1n) ([raw file](https://github.com/vaadin/flow/blob/d240949563bfe30cd3b0135393cdcff71194cd2d/flow-server/src/main/java/com/vaadin/flow/component/AbstractCompositeField.java#L24)):*
> ```
> A an abstract
> ```
`A` or `an` ?

---

*[flow-server/src/main/java/com/vaadin/flow/component/AbstractCompositeField.java, line 52 at r1](https://reviewable.io/reviews/vaadin/flow/4009#-LB-oYJcA6VHubGHbm48:-LB-oYJcA6VHubGHbm49:b-vrgdwx) ([raw file](https://github.com/vaadin/flow/blob/d240949563bfe30cd3b0135393cdcff71194cd2d/flow-server/src/main/java/com/vaadin/flow/component/AbstractCompositeField.java#L52)):*
> ```
> thisD
> ```

Minor , but why it's `D`?

---

*[flow-server/src/main/java/com/vaadin/flow/component/AbstractCompositeField.java, line 113 at r1](https://reviewable.io/reviews/vaadin/flow/4009#-LB-ovBwA-lm3bwUlMGs:-LB-ovBwA-lm3bwUlMGt:b-24bta3) ([raw file](https://github.com/vaadin/flow/blob/d240949563bfe30cd3b0135393cdcff71194cd2d/flow-server/src/main/java/com/vaadin/flow/component/AbstractCompositeField.java#L113)):*
> ```
> setModelValue
> ```

I think `presentation` and `model` are confusing here. It's not clear for me how do they differs from each other and why there are two `value`  at all.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4009)*

**Comment by Legioth** [comment]
Review status: 2 of 5 files reviewed at latest revision, 8 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/component/AbstractCompositeField.java, line 24 at r1](https://reviewable.io/reviews/vaadin/flow/4009#-LB-oMBWEceuBmz4EEqW:-LB-x9yy3KzQKrs7XNxL:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/d240949563bfe30cd3b0135393cdcff71194cd2d/flow-server/src/main/java/com/vaadin/flow/component/AbstractCompositeField.java#L24)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
> A an abstract
> ```
`A` or `an` ?
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/flow/component/AbstractCompositeField.java, line 35 at r1](https://reviewable.io/reviews/vaadin/flow/4009#-LB-erXC353Plx7ZjFWt:-LB-ssTU5yxYJiLfGfKv:bnizl4p) ([raw file](https://github.com/vaadin/flow/blob/d240949563bfe30cd3b0135393cdcff71194cd2d/flow-server/src/main/java/com/vaadin/flow/component/AbstractCompositeField.java#L35)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

> ```
>  * @param <C>
>  *            the type of the content component
>  * @param <S>
>  *            the source type for value change events
>  * @param <T>
>  *            the value type
> ```

Anything against using more meaningful (yet more verbose) names for the parameterized types instead of single letters?
</blockquote></details>

Main argument against is the naming conventions described in https://docs.oracle.com/javase/tutorial/java/generics/types.html

---

*[flow-server/src/main/java/com/vaadin/flow/component/AbstractCompositeField.java, line 52 at r1](https://reviewable.io/reviews/vaadin/flow/4009#-LB-oYJcA6VHubGHbm48:-LB-thm64XU83ZokiySC:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/d240949563bfe30cd3b0135393cdcff71194cd2d/flow-server/src/main/java/com/vaadin/flow/component/AbstractCompositeField.java#L52)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
> thisD
> ```

Minor , but why it's `D`?
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/flow/component/AbstractCompositeField.java, line 89 at r1](https://reviewable.io/reviews/vaadin/flow/4009#-LB-pvMz3o7i3X2u-_3t:-LB-t2U43v2CmUcNw6Vq:blqu121) ([raw file](https://github.com/vaadin/flow/blob/d240949563bfe30cd3b0135393cdcff71194cd2d/flow-server/src/main/java/com/vaadin/flow/component/AbstractCompositeField.java#L89)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

> ```
>      * If {@link #setModelValue(Object, boolean)} is called from within this
>      * method, then value of the last invocation will be used as the model value
>      * instead of the value passed to this method. In this case
>      * {@link #setPresentationValue(Object)} will not be called again. Changing
>      * the provided value might be useful if the provided value is sanitized.
> ```

Can you provide a test for that?
</blockquote></details>

The actual implementation is shared with `AbstractField`, for which there  are tests. Do you think it's necessary to duplicate all those tests instead of the current strategy that is based on smoke tests for AbstractCompositeField and detailed tests for AbstractField.

---

*[flow-server/src/main/java/com/vaadin/flow/component/AbstractCompositeField.java, line 113 at r1](https://reviewable.io/reviews/vaadin/flow/4009#-LB-ovBwA-lm3bwUlMGs:-LB-tovG5kR5VfPmQE_I:b-7dqruo) ([raw file](https://github.com/vaadin/flow/blob/d240949563bfe30cd3b0135393cdcff71194cd2d/flow-server/src/main/java/com/vaadin/flow/component/AbstractCompositeField.java#L113)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
> setModelValue
> ```

I think `presentation` and `model` are confusing here. It's not clear for me how do they differs from each other and why there are two `value`  at all.
</blockquote></details>

This is copied directly from AbstractField, where it is assumed that the reader is also familiar with the concepts described in the class-level javadocs of that class. I'll still slightly clarify the description here as well.

---

*[flow-server/src/main/java/com/vaadin/flow/component/internal/AbstractFieldSupport.java, line 217 at r1](https://reviewable.io/reviews/vaadin/flow/4009#-LB-p7Xk5XmvQKeTac2d:-LB-wto2E42dLRAY3njF:bohfeqq) ([raw file](https://github.com/vaadin/flow/blob/d240949563bfe30cd3b0135393cdcff71194cd2d/flow-server/src/main/java/com/vaadin/flow/component/internal/AbstractFieldSupport.java#L217)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Impressed by Sonar on this one. The method is always returning `false`.
</blockquote></details>

Sonar is drunk. This is an instance field that is set to true if `setPresentationValue.accept` causes `setModelValue` to be run. Changing the method to explicitly return false breaks `AbstractFieldTest.setPresentation_revertsValue_noEvent` and `AbstractFieldTest.setPresentation_changesValue_onlyOneEvent`.

Added a clarifying code comment.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4009)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 3 files at r2.
Review status: 3 of 5 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4009)*

**Comment by denis-anisimov** [comment]
Reviewed 2 of 3 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4009)*

**Comment by gilberto-torrezan** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/component/AbstractCompositeField.java, line 89 at r1](https://reviewable.io/reviews/vaadin/flow/4009#-LB-pvMz3o7i3X2u-_3t:-LB0-pOg7TJa57OPGgIK:bjv45z) ([raw file](https://github.com/vaadin/flow/blob/d240949563bfe30cd3b0135393cdcff71194cd2d/flow-server/src/main/java/com/vaadin/flow/component/AbstractCompositeField.java#L89)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

The actual implementation is shared with `AbstractField`, for which there  are tests. Do you think it's necessary to duplicate all those tests instead of the current strategy that is based on smoke tests for AbstractCompositeField and detailed tests for AbstractField.
</blockquote></details>

Oh I didn't realize this method was an override for the docs. Maybe it is missing the `@Override` then?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4009)*

**Comment by gilberto-torrezan** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4009)*

**Comment by gilberto-torrezan** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4009#-:-LB02wsX8jxwymp4RGHI:bnfp4nl)*

**Pull request merged**
