### PR TITLE
Move documentation to a separate repository

### PR DESCRIPTION
**Pull request by Artur-**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3419)

### CODE REVIEW

**Comment by Artur-** [comment]
Review status: 0 of 199 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3419#-L3yVAGgWsYGQLab_B80:-L3yVAGgWsYGQLab_B81:b-sxzj2b) (no related file):*
Can't be done unless doc build is changed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3419)*

**Comment by SomeoneToIgnore** [comment]
> This branch has conflicts that must be resolved

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3419#-:-L3yZrw1aphiZr5z91rv:b-uj8er5)*

**Comment by gilberto-torrezan** [comment]
Reviewed 199 of 199 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3419)*

**Comment by Artur-** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3419#-L3yVAGgWsYGQLab_B80:-L44rLLerNkPvyC2ehOd:bqilo02) (no related file):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Can't be done unless doc build is changed
</blockquote></details>

Fixed in https://github.com/vaadin/vaadin-docs/pull/116

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3419)*

**Comment by gilberto-torrezan** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3419)*

**Comment by gilberto-torrezan** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3419)*

**Pull request merged**
