### PR TITLE
test: Extract Spring test helpers to a helpers package

### PR DESCRIPTION
**Pull request by Artur-**
The helpers package can be included in any test project without side effects like deployed routes.

### CODE REVIEW

**Comment by mcollovati** [comment]
Should `test-spring-helpers` be added to `computeMatrix.js`, similar to `test-spring-common`?

```
'flow-tests/vaadin-spring-tests/test-spring-common': { weight: 2 },
```

**Comment by Artur-** [comment]
Yes, done

**Comment by mcollovati** [comment]
Seems like `test-spring-common` is built without pre-build `test-spring-helpers`.
Should we maybe force `pos: 4` in `computeMatrix.js for `test-spring-common`?

**Comment by Artur-** [comment]
zomg, seems like the build passes

**Review by mcollovati — APPROVED** [review]

**Pull request merged**
