### PR TITLE
fix: Classes should not be loaded from the plugin

### PR DESCRIPTION
**Pull request by Artur-**
Related-to https://github.com/vaadin/flow/issues/19009

### CODE REVIEW

**Comment by Artur-** [comment]
Does @mcollovati, @platosha  or somebody else know why this should not be done? The current implementation finds Flow classes the plugin was built with and not from the project. No tests here fail, does Hilla rely on this somehow?

**Comment by mcollovati** [comment]
The only reason I can see against `null` parent is that the provided URLs might not cover all possible location for parent classes, so a specific class cannot be loaded because the classloader cannot find one ancestor.

Looking at the flow maven plugin code, it looks like we provide all runtime dependencies (`compile` + `runtime` scopes) but we filter out `provided` and `system` to only get portlet and servlet-api.
However, according to the [documentation](https://maven.apache.org/guides/mini/guide-maven-classloading.html#Plugin_Classloaders), the plugin class loader should not contain the project dependencies, so the execution may fail anyway for dependencies excluded from URL. Unless the same dependencies are defined as plugin dependencies.

I wonder if we should provide to `ReflectionsClassFinder` also a class loader, and create that one based on all `MavenProject` dependencies.
Or temporarily change the context class loader during mojo execution.

**Comment by mcollovati** [comment]
The Surefire plugin for in-process execution uses a custom class loader, temporarily set as the current thread context class loader. The classloader is built on project dependencies (` getProject().getArtifacts()`).

```java
        @Override
        public RunResult invoke(Object forkTestSet) throws ReporterException, InvocationTargetException {
            ClassLoader current = swapClassLoader(testsClassLoader);
            try {
                Method invoke = getMethod(providerInOtherClassLoader.getClass(), "invoke", INVOKE_PARAMETERS);
                Object result = invokeMethodWithArray2(providerInOtherClassLoader, invoke, forkTestSet);
                return (RunResult) surefireReflector.convertIfRunResult(result);
            } finally {
                if (System.getSecurityManager() == null) {
                    Thread.currentThread().setContextClassLoader(current);
                }
            }
        }

        private ClassLoader swapClassLoader(ClassLoader newClassLoader) {
            ClassLoader current = Thread.currentThread().getContextClassLoader();
            Thread.currentThread().setContextClassLoader(newClassLoader);
            return current;
        }
```

**Comment by Artur-** [comment]
and presumably the built test classloader does not use the plugin classloader as its parent?

**Comment by mcollovati** [comment]
If I got it correctly, it uses the platform classloader as parent.

https://github.com/apache/maven-surefire/blob/4281a9bdd41a5cc4f17f4ed101ee9e8a1a089aa5/surefire-booter/src/main/java/org/apache/maven/surefire/booter/Classpath.java#L120-L136

https://github.com/apache/maven-surefire/blob/master/surefire-booter/src/main/java/org/apache/maven/surefire/booter/IsolatedClassLoader.java

**Comment by Artur-** [comment]
Added the platform classloader as parent..

**Comment by Artur-** [comment]
Should we merge this for 24.6 or try to figure out if it breaks something or is there some better approach?

**Comment by mcollovati** [comment]
Building a hybrid application with this change results in an error

```
[ERROR] Failed to execute goal com.vaadin:vaadin-maven-plugin:24.6-SNAPSHOT:prepare-frontend (default) on project spring-petclinic-vaadin-flow: Could not execute prepare-frontend goal.: Error occured during goal execution: class com.vaadin.hilla.internal.EndpointGeneratorTaskFactoryImpl cannot be cast to class com.vaadin.flow.server.frontend.EndpointGeneratorTaskFactory (com.vaadin.hilla.internal.EndpointGeneratorTaskFactoryImpl is in unnamed module of loader java.net.URLClassLoader @2b20caed; com.vaadin.flow.server.frontend.EndpointGeneratorTaskFactory is in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @78d92eef)
```

**Comment by mcollovati** [comment]
I think the missing piece here is to make the Flow mojos set the `ClassFinder` as thread context class loader.
At least, this seems to work for Flow projects: for example, if the project uses Vaadin 24.5.0 but sets flow-maven-plugin to version 24.6-SNAPSHOT, the resources are then correctly collected from the 24.5 `flow-server` jar.

I wonder if the previous error can be fixed by applying the same pattern to the Hilla `configure` mojo, that seems to be executed before `prepare-fronted`, and probably is loading the `EndpointGeneratorTaskFactory` into a shared classloader.

**Comment by mcollovati** [comment]
Isolating the execution so that flow-server classes are not loaded into the plugin class loader seems to be more complicated than expected.

**Comment by mcollovati** [comment]
Changing the thread context class loader during mojo execution does not work. flow-server classes are still loaded into the plugin class loader, causing a `ClassCastException` when Hilla or Copilot classes are loaded.

**Comment by mcollovati** [comment]
Also, making `flow-server` as provided dependency seems not to work. In addition, we might end up in situations where the plugin might fail or misbehave because of incompatibilities between the `flow-server` version expected by the plugin and the one used by the end-user project.

**Comment by mcollovati** [comment]
Superseded by #20465

**Pull request closed without merging**
