### PR TITLE
Make Binder tests independent of Vaadin components

### PR DESCRIPTION
**Pull request by Artur-**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3416)

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
> This branch has conflicts that must be resolved

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3416#-:-L3yZNqdt9RkwTzu8OkE:b-uj8er5)*

**Comment by gilberto-torrezan** [comment]
Reviewed 53 of 53 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[flow-data/src/test/java/com/vaadin/flow/data/binder/testcomponents/AbstractTestHasValueAndValidation.java, line 1 at r1](https://reviewable.io:443/reviews/vaadin/flow/3416#-L415ZlEk35HSKptZceu:-L415ZlEk35HSKptZcev:b-qa3nwa) ([raw file](https://github.com/vaadin/flow/blob/8319571d855416ff976b08ac3da334a47ce6f62a/flow-data/src/test/java/com/vaadin/flow/data/binder/testcomponents/AbstractTestHasValueAndValidation.java#L1)):*
> ```Java
> package com.vaadin.flow.data.binder.testcomponents;
> ```

It is missing our fancy license header. No idea why Sonar didn't catch that.

---

*[flow-data/src/test/java/com/vaadin/flow/data/binder/testcomponents/TestCheckbox.java, line 1 at r1](https://reviewable.io:443/reviews/vaadin/flow/3416#-L415j81DgVarHY-ziVe:-L415j81DgVarHY-ziVf:b-63bqw3) ([raw file](https://github.com/vaadin/flow/blob/8319571d855416ff976b08ac3da334a47ce6f62a/flow-data/src/test/java/com/vaadin/flow/data/binder/testcomponents/TestCheckbox.java#L1)):*
> ```Java
> package com.vaadin.flow.data.binder.testcomponents;
> ```

License header again.

---

*[flow-data/src/test/java/com/vaadin/flow/data/binder/testcomponents/TestDatePicker.java, line 1 at r1](https://reviewable.io:443/reviews/vaadin/flow/3416#-L415lhHL7SY2zEnD_FH:-L415lhHL7SY2zEnD_FI:bio604c) ([raw file](https://github.com/vaadin/flow/blob/8319571d855416ff976b08ac3da334a47ce6f62a/flow-data/src/test/java/com/vaadin/flow/data/binder/testcomponents/TestDatePicker.java#L1)):*
> ```Java
> package com.vaadin.flow.data.binder.testcomponents;
> ```

And again.

---

*[flow-data/src/test/java/com/vaadin/flow/data/binder/testcomponents/TestFormLayout.java, line 1 at r1](https://reviewable.io:443/reviews/vaadin/flow/3416#-L415nh2nAwN47djab_F:-L415nh2nAwN47djab_G:b-p3ibdw) ([raw file](https://github.com/vaadin/flow/blob/8319571d855416ff976b08ac3da334a47ce6f62a/flow-data/src/test/java/com/vaadin/flow/data/binder/testcomponents/TestFormLayout.java#L1)):*
> ```Java
> package com.vaadin.flow.data.binder.testcomponents;
> ```

Guess what...

---

*[flow-data/src/test/java/com/vaadin/flow/data/binder/testcomponents/TestTextField.java, line 1 at r1](https://reviewable.io:443/reviews/vaadin/flow/3416#-L415po0uCrOHlQ1selR:-L415po0uCrOHlQ1selS:b-tg12j4) ([raw file](https://github.com/vaadin/flow/blob/8319571d855416ff976b08ac3da334a47ce6f62a/flow-data/src/test/java/com/vaadin/flow/data/binder/testcomponents/TestTextField.java#L1)):*
> ```Java
> package com.vaadin.flow.data.binder.testcomponents;
> ```

And here...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3416)*

**Comment by Artur-** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[flow-data/src/test/java/com/vaadin/flow/data/binder/testcomponents/AbstractTestHasValueAndValidation.java, line 1 at r1](https://reviewable.io:443/reviews/vaadin/flow/3416#-L415ZlEk35HSKptZceu:-L41JTTL2FB1TiOxL6uF:bcnv24x) ([raw file](https://github.com/vaadin/flow/blob/8319571d855416ff976b08ac3da334a47ce6f62a/flow-data/src/test/java/com/vaadin/flow/data/binder/testcomponents/AbstractTestHasValueAndValidation.java#L1)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

It is missing our fancy license header. No idea why Sonar didn't catch that.
</blockquote></details>

Are they required also for test classes?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3416)*

**Comment by gilberto-torrezan** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[flow-data/src/test/java/com/vaadin/flow/data/binder/testcomponents/AbstractTestHasValueAndValidation.java, line 1 at r1](https://reviewable.io:443/reviews/vaadin/flow/3416#-L415ZlEk35HSKptZceu:-L44sxUQ0G2ASLIrlMQ8:b-xdp20v) ([raw file](https://github.com/vaadin/flow/blob/8319571d855416ff976b08ac3da334a47ce6f62a/flow-data/src/test/java/com/vaadin/flow/data/binder/testcomponents/AbstractTestHasValueAndValidation.java#L1)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Are they required also for test classes?
</blockquote></details>

Sonar doesn't run on those classes because the code itself is not supposed to be beautiful - but the license header should be in every source file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3416)*

**Pull request merged**
