### PR TITLE
Setup the template of the renderer earlier

### PR DESCRIPTION
**Pull request by jcgueriaud1**
The renderer sets the template when the parent element is attached (runWhenAttached/beforeClientResponse).
Sometimes the template is set after the call of generateData of the rendering. This leads to display an empty element instead of the component.
This pull request creates the template when render method is called, generate a random id for the renderer (instead of using node id which requires an attached node).

This PL will fix this bug: https://github.com/vaadin/vaadin-grid-flow/issues/710

(I also created a PL to add some tests in the grid https://github.com/vaadin/vaadin-grid-flow/pull/730)

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/6144)

### CODE REVIEW

**Review by denis-anisimov — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/flow/6144)* status: 5 unresolved discussions, 0 of 1 LGTMs obtained (waiting on @denis-anisimov)

*[a discussion](https://reviewable.io/reviews/vaadin/flow/6144#-LlBvpY331eB_SbQDacI:-LlBvpY4DRCfGpqt9rNJ:bdryeyp) (no related file):*
Besides the issue with generating the unique id I don't really see what and how this fixes the issue.
I would like to see some tests preferable unit tests which give me an idea what's wrong with the current impl and
how it becomes fixed via this PR.

I think I feel uncomfortable with removal of `runWhenAttached` , `beforeClientResponse` calls.
Those calls are used quite often to be sure that the command (or code that does something) is executed only once
instead of theoretical several times execution. And there are normally some reasons for that.
Though may be in this specific case the only reason of calling the command is to get the node id. And in that case it's fine.

But: 
- in one case the `getTemplatePropertyName` method really doesn't rely on exact node id value. It has to be just unique
- in other case `nodeId` replacement to the generated  "unique" number may be just a mistake since there may be a code (on the client side) which uses this id to find the node on the client side: in most cases we really need the node id and not just a unique identifier.

So : 
- tests are definitely needed for this PR 
- there should be at least IT tests in Grid repo 
- existing IT tests in Grid have to be executed before this is merged
- would be nice to see unit tests in this repo.
- I feel IT tests in Grid will fail for this PR (the second replacement looks quite scary).

---
___
*[flow-data/src/main/java/com/vaadin/flow/data/renderer/BasicRenderer.java, line 128 at r2](https://reviewable.io/reviews/vaadin/flow/6144#-LlBsUlgDSR903s_0bhP:-LlBsUlgDSR903s_0bhQ:b1fgp83) ([raw file](https://github.com/vaadin/flow/blob/c75d286e2ac8c73f876e85b4b6a0fdebdfe9d2a6/flow-data/src/main/java/com/vaadin/flow/data/renderer/BasicRenderer.java#L128)):*
> ```
> rendererId
> ```

This is unique only inside one thread.
So this is 1 per thread.

`templateElement.getNode().getId()`  is 1 per `StateNode`.

This is definitely not the same.

I'm not sure whether it has to be unique "globally" .
But what I may say for sure: servlet doesn't have to handle various HTTP requests inside the same thread .
It means that `rendererId` may be the same for different templates .
So this doesn't look correct for me.
___
*[flow-data/src/main/java/com/vaadin/flow/data/renderer/ComponentRenderer.java, line 163 at r2](https://reviewable.io/reviews/vaadin/flow/6144#-LlBv7FQ4RjOaKRxXT6h:-LlBv7FQ4RjOaKRxXT6i:bwonqmk) ([raw file](https://github.com/vaadin/flow/blob/c75d286e2ac8c73f876e85b4b6a0fdebdfe9d2a6/flow-data/src/main/java/com/vaadin/flow/data/renderer/ComponentRenderer.java#L163)):*
> ```
> UI.getCurrent() != null
> ```

`UI.getCurrent()`  should be avoided generally.

As I understand from the `else` branch the code should be executed if element is already attached. 
This may be checked via `container.getNode().isAttached()`.
In fact I the code in else branch does both things: it checks whether the element is already attached and it schedules the command to execute when attach event is fired.
___
*[flow-data/src/main/java/com/vaadin/flow/data/renderer/ComponentRenderer.java, line 203 at r2](https://reviewable.io/reviews/vaadin/flow/6144#-LlBu4dT6yVSb6BtvLpf:-LlBu4dT6yVSb6BtvLpg:b-b4mjsg) ([raw file](https://github.com/vaadin/flow/blob/c75d286e2ac8c73f876e85b4b6a0fdebdfe9d2a6/flow-data/src/main/java/com/vaadin/flow/data/renderer/ComponentRenderer.java#L203)):*
> ```
> rendererId
> ```

same thing here as in the file above.
___
*[flow-data/src/main/java/com/vaadin/flow/data/renderer/Renderer.java, line 61 at r2](https://reviewable.io/reviews/vaadin/flow/6144#-LlBuAqYCIs-lmPnB8L9:-LlBuAqYCIs-lmPnB8LA:bafco8l) ([raw file](https://github.com/vaadin/flow/blob/c75d286e2ac8c73f876e85b4b6a0fdebdfe9d2a6/flow-data/src/main/java/com/vaadin/flow/data/renderer/Renderer.java#L61)):*
> ```
> 
> ```

No changes.
Any reason to have this file in the PR ?

**Comment by jcgueriaud1** [comment]
I also think it need some tests, I don't know exactly which one I can add in this repo.
I added some IT tests for the grid in this PL: https://github.com/vaadin/vaadin-grid-flow/issues/710

I run the grid tests and also vaadin-combobox tests locally.

If I remove UI.getCurrent() test and replace it to this:
container.getNode()
                    .runWhenAttached(ui -> setupTemplate(
                            ui, container, rendering,
                            keyMapper));

Then, as the column is not attached (container) the function is postponed and we don't need a random number (because you can use node id).

The first patch fix the bug (and grid IT are working):
https://github.com/vaadin/flow/pull/6144/commits/ed3646ef2ab7f2ed0a54d53520eac7161d3eb2b7

But that may lead to different bugs (because the function is still postponed).

**Comment by denis-anisimov** [comment]
>The first patch fix the bug (and grid IT are working): ed3646e

I would say this patch should work in the same way as the current impl.
The only difference is `beforeClientResponse` method which allows to avoid execution if the node has not been attached to the `StateTree` at all (if it's added and then removed).

On the other hand in this specific situation it might be that `beforeClientResponse` is not really needed since it doesn't (_may be_)  cause any issues even if the node is not attached in the end.

>The first patch fix the bug 

And this is what I would like to understand: how does it fix the bug ?
I would like to see a scenario which fails with the current impl and works with patch applied.
Preferably a unit test.

**Comment by jcgueriaud1** [comment]
> > The first patch fix the bug (and grid IT are working): [ed3646e](https://github.com/vaadin/flow/commit/ed3646ef2ab7f2ed0a54d53520eac7161d3eb2b7)
> 
> I would say this patch should work in the same way as the current impl.
> The only difference is `beforeClientResponse` method which allows to avoid execution if the node has not been attached to the `StateTree` at all (if it's added and then removed).

It does not work the same way. The current implementation has bug because refreshData is called after setupTemplate (so you can't display the component if the template is not setup).
In the current impl:
* render() -> whenAttach -> add setupTemplate in the queue -> run the queue
In the new impl:
* render() -> whenAttach -> run setupTemplate in the queue -> run the queue

So in my test case:
`add(gridThenComp);
 gridThenComp.addColumn(new NativeButtonRenderer<>("click", this::clicked));`
Current implementation:
1. add(grid) -> add refreshData in the queue
2. addComponentColumn -> add setupTemplate in the queue
3. run the queue refreshData then setupTemplate
New implementation:
1. add(grid) -> add refreshData in the queue
2. addComponentColumn -> run the setupTemplate when attached
3. run setupTemplate
4. run the queue refreshData

You can see here an example and here the IT: https://github.com/vaadin/vaadin-grid-flow/pull/730/commits/f94c6497d8a36bcb1976a46ee78f353504d8fd0d

This IT does not work before and works after the patch (with the first patch and with the patch with "random" number).
I also tried to add TemplateRenderer + NativeButtonRenderer with dom event (because RendererUtil uses the same trick) and also ItemDetailsRenderer and EditorRenderer. If you know other places where ComponentRenderer is used then I can test them. 

I will try to make a unit test in this repo.

-----------------
I don't know if it's possible but if this delay can be removed (when attached or attached/beforeListeners) this will be easier to test/use and will remove the real problem (setup template is done later) and may simplify some code elsewhere. That's why I tried to not use node id (but I still need UI).

**Comment by denis-anisimov** [comment]
I will just try to clarify the things...
You should be aware about :
- nobody introduces the delay just because of the delay.
- there are several things why the action is postponed:
  - There is no `UI`  instance available when the code is executed _IF_ the node is not yet attached. `UI.getCurrent` is just a bad way to access the `UI`. It has to be avoided in our internal code. It's intended to be used by the app developer for his convenience if he wants. We need a proper way to access the `UI` instance. Delaying the action to the moment when a node becomes attached is a proper way to get the `UI` instance. _But_ may be in this specific case it just doesn't work. Other way should be found to make it properly.
 - Once(if) we solved an issue (the above one) with `UI`  instance access another thing one should care of: it may be a mistake to run the code if node is not attached in the result at all (there is a code which adds it, then removes (and may be several times)). In some situations the delayed command may do wrong things assuming that the node is attached when it's executed. And if the node is not attached in the result the code may be simply wrong (it may just throw). That's why `beforeClientResponse` is used . It prevents such situations.

So: there is no any strict need in postponing. If something can be done (_properly_) without postponing then it's totally fine to do it without any delays.

But: the `UI`  instance should be properly accessed. And the code which is executed should not fail in any situation (should work even if the node is detached after attaching).

I personally don't have any preference in the way of how it's implemented. I just care about the proper way of doing this: the code should not introduce any new issues.

One possible way of fixing the issue ( I don't say that this is the correct/proper way and it should be used): postpone `generateData` (or  any other call which relies on template availability) so that it's executed for sure when template is already set. It might be it's not possible or even worse but I'm trying to say that there can be other ways to fix this instead of getting rid of a delay here.

And another thing: we are writing a lot of texts here explaining how it works .
It would be better to have a unit test which can be used to show the bug. Using such test is easier to understand what doesn't work and which way it may be fixed: what exactly the reason of the behavior.

I'm not an expert at all in this functionality so it's hard to understand whether the fix is a proper one or not without a test.

**Comment by jcgueriaud1** [comment]
I've just add a unit test for this case. That may help you to understand the problem (at least it's easy and fast to run before/after).

In my opinion, the problem is not really the implementation but how it can be misused (it works in almost the cases but you can break it).

I'm sure that the delay has not been added for fun but is there a possibility to avoid this? (remove the need of node id and UI when setupTemplate is called).

I will try to find a possibility. If you can share some idea, any ideas are welcomed.

**Review by denis-anisimov — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vaadin/flow/6144)* status: 2 unresolved discussions, 0 of 1 LGTMs obtained (waiting on @denis-anisimov)

___
*[flow-data/src/main/java/com/vaadin/flow/data/renderer/BasicRenderer.java, line 128 at r2](https://reviewable.io/reviews/vaadin/flow/6144#-LlBsUlgDSR903s_0bhP:-LlLKvav1a1qSCeQL2it:bly31zw) ([raw file](https://github.com/vaadin/flow/blob/c75d286e2ac8c73f876e85b4b6a0fdebdfe9d2a6/flow-data/src/main/java/com/vaadin/flow/data/renderer/BasicRenderer.java#L128)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
> rendererId
> ```

This is unique only inside one thread.
So this is 1 per thread.

`templateElement.getNode().getId()`  is 1 per `StateNode`.

This is definitely not the same.

I'm not sure whether it has to be unique "globally" .
But what I may say for sure: servlet doesn't have to handle various HTTP requests inside the same thread .
It means that `rendererId` may be the same for different templates .
So this doesn't look correct for me.
</blockquote></details>

I think this is fine to generate here any "unique" name.
It doesn't have to be based on node id.

I still think that any random number is not a proper replacement for unique id though.

I'm unblocking this comment since I won't be able to proceed with review.

Just for the reference : as I understand this method is used to create a fake property name in the `Element` which is used for transfer an internal data via a template binding `[some_template_element.propertyName]` where the `propertyName` is `getTemplatePropertyName()` return value.
So it doesn't matter whether it contains a node id or not.

The property should be just unique inside the template element and that's enough.
___
*[flow-data/src/main/java/com/vaadin/flow/data/renderer/ComponentRenderer.java, line 163 at r2](https://reviewable.io/reviews/vaadin/flow/6144#-LlBv7FQ4RjOaKRxXT6h:-LlLOBh10syREhsIPcP3:b-5w1s77) ([raw file](https://github.com/vaadin/flow/blob/c75d286e2ac8c73f876e85b4b6a0fdebdfe9d2a6/flow-data/src/main/java/com/vaadin/flow/data/renderer/ComponentRenderer.java#L163)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
> UI.getCurrent() != null
> ```

`UI.getCurrent()`  should be avoided generally.

As I understand from the `else` branch the code should be executed if element is already attached. 
This may be checked via `container.getNode().isAttached()`.
In fact I the code in else branch does both things: it checks whether the element is already attached and it schedules the command to execute when attach event is fired.
</blockquote></details>

Unblocked but I personally still don't like `UI.getCurrent()`.

`CurrentInstance` (which is used by `UI.getCurrent()`) is not inherited by threads in Flow .
It means it may be null outside request dispatcher thread.

And that's the reason why an `UI` instance should be explicitly found avoiding `UI.getCurrent()`.
___
*[flow-data/src/main/java/com/vaadin/flow/data/renderer/ComponentRenderer.java, line 203 at r2](https://reviewable.io/reviews/vaadin/flow/6144#-LlBu4dT6yVSb6BtvLpf:-LlLP6SV2TW3SPtMtjbA:b-6ezmob) ([raw file](https://github.com/vaadin/flow/blob/c75d286e2ac8c73f876e85b4b6a0fdebdfe9d2a6/flow-data/src/main/java/com/vaadin/flow/data/renderer/ComponentRenderer.java#L203)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
> rendererId
> ```

same thing here as in the file above.
</blockquote></details>

I think in this place the property name also doesn't have to be based on the node id.
I'm pretty sure that the situation is exactly the same as in `BasicRenderer`.
This should be just a unique property name in the `templateElement`.
___
*[flow-data/src/main/java/com/vaadin/flow/data/renderer/ComponentRenderer.java, line 217 at r3](https://reviewable.io/reviews/vaadin/flow/6144#-LlLPOreBDRmo4qGnQtL:-LlLPOreBDRmo4qGnQtM:b-b2p7ur) ([raw file](https://github.com/vaadin/flow/blob/5d92fe6a6a943acf4a12c050a57863c6d660f44e/flow-data/src/main/java/com/vaadin/flow/data/renderer/ComponentRenderer.java#L217)):*
> ```
> rendererId
> ```

And I'm pretty sure you may not use `redererId` here  instead of node id.

This code requires node id. It may not be any arbitrary (or just unique) number.
It has to be a node id since `flow-component-renderer.hml` (or `.js`)  uses this id to find a node by its id via client side.
See e.g.

```
_getRenderedComponent() {
      try {
        return window.Vaadin.Flow.clients[this.appid].getByNodeId(this.nodeid);
```
So in this specific case the node is is just required and it means that the component has to be attached.
___
*[flow-data/src/test/java/com/vaadin/flow/data/renderer/ComponentRendererTest.java, line 67 at r3](https://reviewable.io/reviews/vaadin/flow/6144#-LlLQAHl4dEg8Ciphe0N:-LlLQAHl4dEg8Ciphe0O:b-72q4ov) ([raw file](https://github.com/vaadin/flow/blob/5d92fe6a6a943acf4a12c050a57863c6d660f44e/flow-data/src/test/java/com/vaadin/flow/data/renderer/ComponentRendererTest.java#L67)):*
> ```
>     public void templateRenderered_parentAttachedBeforeChild() {
>         UI ui = new TestUI();
> ```

Thank you very much for the test.
Now at least I see what assumption is broken....

This test fails and the next one doesn't fail with the current impl (without the PR changes).

What I see from here is the wrong assumption made somewhere.
`renderer`  cares only about the element which it renders (`container` in this case).
And the test (in this specific case)  makes an assumption about `rendering.getNodeIdPropertyName()` .
But this assumption is wrong: the parent container is not attached yet.

So the test itself is good but it shows that the the problem is not exactly in the renderer itself but rather somewhere which uses the renderer and makes an assumption.

So at the first glance the problem should be fixed not in the renderer but somewhere where the renderer is used.

On the other hand the API may be done in a way that the client of renderer may not (or don't have to know) anything about this logic with `runWhenAttached` and so on....
So may be this should be solved in both places....

Not blocking comment.
___
*[flow-data/src/test/java/com/vaadin/flow/data/renderer/ComponentRendererTest.java, line 86 at r3](https://reviewable.io/reviews/vaadin/flow/6144#-LlLRbb21vbyXOkbpAOB:-LlLRbb21vbyXOkbpAOC:b-5c4q7r) ([raw file](https://github.com/vaadin/flow/blob/5d92fe6a6a943acf4a12c050a57863c6d660f44e/flow-data/src/test/java/com/vaadin/flow/data/renderer/ComponentRendererTest.java#L86)):*
> ```
> Assert.assertNotNull("NodeIdPropertyName should not be null", rendering.getNodeIdPropertyName() 
> ```

This is an easy test and it's OK to show what's broken but I would recommend to check that 
`ComponentDataGenerator::generateData` method doesn't do anything in addition just because the property is `null`.
The important thing here is that the logic of `generateData` doesn't do what it should and it doesn't really matter whether the `nodeIdPropertyName` is `null`  or not. It's just an impl detail.
But `generateData` should change somehow a `JsonObject` instance. That's important. And this is what exactly broken in the end.

**Review by denis-anisimov — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/flow/6144)* status: all discussions resolved, 0 of 1 LGTMs obtained

**Comment by jcgueriaud1** [comment]
I changed the test case to test `ComponentDataGenerator::generateData.`.

I also removed random number for few reasons:
* That does not help to not postpone `setupTemplate` because I still need a UI. UI.getCurrent() should not be used.
* That may have a lot of consequences which are not easy to test automatically.
* Hard to understand (random number are put in nodeId property but it's not "nodeid" anymore)

The main problem is this PL does not help if the grid or combobox used componentRenderer  but call ComponentDataGenerator::generateData too soon.

**Review by caalador — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/flow/6144)* status: 1 unresolved discussion, 0 of 1 LGTMs obtained (waiting on @denis-anisimov and @jcgueriaud1)

*[a discussion](https://reviewable.io/reviews/vaadin/flow/6144#-LmiPFvDAaDRKTjqEm1m:-LmiPFvDAaDRKTjqEm1n:b5dzcj6) (no related file):*
After deliberation with Leif we see that this is ok as we want to backport the fix also, but would be good to have some comments to explain what and why. Mind bringing in the changes in
https://github.com/vaadin/flow/commit/30781d4a3da72488616ec9f922261dd3ecb0bd39 as we can't push to tour fork and update the PR with the comments.

---

**Review by caalador — COMMENTED** [review]
> Reviewed 3 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/vaadin/flow/6144)* status: 1 unresolved discussion, 0 of 1 LGTMs obtained (waiting on @jcgueriaud1)

**Comment by jcgueriaud1** [comment]
*[a discussion](https://reviewable.io/reviews/vaadin/flow/6144#-LmiPFvDAaDRKTjqEm1m:-LmikRie5sGwggGbdmBz:b-nijc3o) (no related file):*
> 30781d4
Comments have been added in the branch.

---

**Review by caalador — DISMISSED** [review]
:lgtm:

> Reviewed 3 of 3 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/vaadin/flow/6144#-:-Lmj1BB13IGBvH_kXrrd:bnfp4nl)* status: :shipit: complete! all discussions resolved, 1 of 1 LGTMs obtained

**Review by caalador — APPROVED** [review]
> Reviewed 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/vaadin/flow/6144)* status: all discussions resolved, 0 of 1 LGTMs obtained, and 1 stale

**Review by caalador — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/vaadin/flow/6144#-:-LmmNOW24AhV4OXmCvAi:bnfp4nl)* status: :shipit: complete! all discussions resolved, 1 of 1 LGTMs obtained

**Comment by ujoni** [comment]
Released in Flow versions:
- `1.0.13`
- `2.0.6`

**Pull request merged**
