### PR TITLE
Use new Bower webjars

### PR DESCRIPTION
**Pull request by Artur-**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3393)

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[flow-server/src/main/java/com/vaadin/flow/server/webjar/WebJarServer.java, line 52 at r1](https://reviewable.io:443/reviews/vaadin/flow/3393#-L3g9JuVxPGA5PRu7XV3:-L3g9JuVxPGA5PRu7XV4:bdxje5u) ([raw file](https://github.com/vaadin/flow/blob/327856d203040f09a61451c005e0fea580e8a08a/flow-server/src/main/java/com/vaadin/flow/server/webjar/WebJarServer.java#L52)):*
> ```Java
>  */
> public class WebJarServer implements Serializable {
>     private final transient WebJarAssetLocator locator = new WebJarAssetLocator();
> ```

Corresponding dependency should be removed from `flow-server` pom.xml

---

*[flow-server/src/main/java/com/vaadin/flow/server/webjar/WebJarServer.java, line 53 at r1](https://reviewable.io:443/reviews/vaadin/flow/3393#-L3g95otSVdaJ5viyHUA:-L3g95otSVdaJ5viyHUB:bea87ee) ([raw file](https://github.com/vaadin/flow/blob/327856d203040f09a61451c005e0fea580e8a08a/flow-server/src/main/java/com/vaadin/flow/server/webjar/WebJarServer.java#L53)):*
> WebJarBowerDependency

Now it can be removed, along with corresponding tests and `SemanticVersion` class.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3393)*

**Comment by Artur-** [comment]
Review status: 13 of 18 files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/server/webjar/WebJarServer.java, line 52 at r1](https://reviewable.io:443/reviews/vaadin/flow/3393#-L3g9JuVxPGA5PRu7XV3:-L3hT5ZZVGvy8N-AhPTJ:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/327856d203040f09a61451c005e0fea580e8a08a/flow-server/src/main/java/com/vaadin/flow/server/webjar/WebJarServer.java#L52)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Corresponding dependency should be removed from `flow-server` pom.xml
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/flow/server/webjar/WebJarServer.java, line 53 at r1](https://reviewable.io:443/reviews/vaadin/flow/3393#-L3g95otSVdaJ5viyHUA:-L3hTEHwvEYMmjTdHxqu:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/327856d203040f09a61451c005e0fea580e8a08a/flow-server/src/main/java/com/vaadin/flow/server/webjar/WebJarServer.java#L53)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

> WebJarBowerDependency

Now it can be removed, along with corresponding tests and `SemanticVersion` class.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3393)*

**Comment by SomeoneToIgnore** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3393#-L3hU6-LUivkklGCVKiy:-L3hU6-LUivkklGCVKiz:bishfu9) (no related file):*
Although :ltgm: , we should not just merge it before we're ready since it breaks every possible thing in the platform:
* plugin
* components
* demos
* skeletons

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3393#-:-L3hU5jg7bj6KMwPR4Ci:bnfp4nl)*

**Comment by ZheSun88** [comment]
Review status: 4 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[webjars-bom/pom.xml, line 96 at r3](https://reviewable.io:443/reviews/vaadin/flow/3393#-L4Kk31d_rjMIq0TO66Z:-L4Kk31d_rjMIq0TO66_:b50jw65) ([raw file](https://github.com/vaadin/flow/blob/787f831513bdf184e9baac3a847b80f73e85dc72/webjars-bom/pom.xml#L96)):*
> ```XML
>                 <groupId>org.webjars.bowergithub.vaadin</groupId>
>                 <artifactId>vaadin-item</artifactId>
>                 <version>2.0.0-alpha4</version>
> ```

May i know why we have two `vaadin-item` dependencies with different versions?

---

*[webjars-bom/pom.xml, line 118 at r3](https://reviewable.io:443/reviews/vaadin/flow/3393#-L4KkF02hJGTgMXirq86:-L4KkF02hJGTgMXirq87:b-sdlmzb) ([raw file](https://github.com/vaadin/flow/blob/787f831513bdf184e9baac3a847b80f73e85dc72/webjars-bom/pom.xml#L118)):*
> ```XML
>                 <groupId>org.webjars.bowergithub.vaadin</groupId>
>                 <artifactId>vaadin-item</artifactId>
>                 <version>2.0.0-alpha5</version>
> ```

that is the other one.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3393)*

**Comment by Artur-** [comment]
Review status: 4 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

*[webjars-bom/pom.xml, line 96 at r3](https://reviewable.io:443/reviews/vaadin/flow/3393#-L4Kk31d_rjMIq0TO66Z:-L4KnsLNrJxOn8M1Augc:b707ckj) ([raw file](https://github.com/vaadin/flow/blob/787f831513bdf184e9baac3a847b80f73e85dc72/webjars-bom/pom.xml#L96)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

May i know why we have two `vaadin-item` dependencies with different versions?
</blockquote></details>

Probably some merge issue, fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3393)*

**Comment by SomeoneToIgnore** [comment]
Ok, @pleku whenever we're ready, we can start breaking things.

---

Reviewed 7 of 14 files at r3, 3 of 3 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[webjars-bom/pom.xml, line 230 at r6](https://reviewable.io:443/reviews/vaadin/flow/3393#-L4L_PoV0YK6X_9VlEK4:-L4L_PoV0YK6X_9VlEK5:bihnspx) ([raw file](https://github.com/vaadin/flow/blob/a8db26e9f60f6eaeecab76fb4a9b54171725dc64/webjars-bom/pom.xml#L230)):*
> ```XML
>                 <groupId>org.webjars.bowergithub.vaadin</groupId>
>                 <artifactId>vaadin-lumo-styles</artifactId>
>                 <version>1.0.0-alpha3</version>
> ```

I see two lumo-styles, one alpha2 (at the top), one here.
Not a major though, we can fix it later.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3393#-:-L4LaKQkGygiipbCPrHt:b-rqtq07)*

**Comment by SomeoneToIgnore** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3393#-:-L4LaPhRVSvpAShUyr0n:bnfp4nl)*

**Comment by SomeoneToIgnore** [comment]
*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3393#-L4La_CPiJegWRnHZdVB:-L4La_CPiJegWRnHZdVC:b9eeig1) (no related file):*
@zhesun88 is working on verifying that all the WebJars needed are published. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3393)*

**Comment by Artur-** [comment]
Review status: 13 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[webjars-bom/pom.xml, line 230 at r6](https://reviewable.io:443/reviews/vaadin/flow/3393#-L4L_PoV0YK6X_9VlEK4:-L4Lba3HhlHmyi3eoryU:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/a8db26e9f60f6eaeecab76fb4a9b54171725dc64/webjars-bom/pom.xml#L230)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

I see two lumo-styles, one alpha2 (at the top), one here.
Not a major though, we can fix it later.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3393)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3393)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 1 of 3 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3393)*

**Pull request merged**
