### PR TITLE
Add API for freezing grid columns

### PR DESCRIPTION
**Pull request by ahie**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/2784)

### CODE REVIEW

**Comment by gilberto-torrezan** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[flow-components-parent/demo-flow-components/src/test/java/com/vaadin/flow/demo/views/GridViewIT.java, line 221 at r1](https://reviewable.io:443/reviews/vaadin/flow/2784#-KxRYJQCMWv3PgyZ045t:-KxRYJQCMWv3PgyZ045u:b-o57vk) ([raw file](https://github.com/vaadin/flow/blob/c1758281d5b87c932387d3972c8c527a925ba520/flow-components-parent/demo-flow-components/src/test/java/com/vaadin/flow/demo/views/GridViewIT.java#L221)):*
> ```Java
>                 grid.getAttribute("columnReorderingAllowed"));
> 
>         String idColumnFrozenStatusScript = "return arguments[0].shadowRoot.querySelectorAll('th')[0].getAttribute('frozen')";
> ```

This can break if the internals of the component changes over time. One way of testing this is just to evaluate the `frozen` property of the `vaadin-grid-column` element, outside the shadow root. That's public API, so it shouldn't change unless a major version is released.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2784)*

**Comment by ahie** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[flow-components-parent/demo-flow-components/src/test/java/com/vaadin/flow/demo/views/GridViewIT.java, line 221 at r1](https://reviewable.io:443/reviews/vaadin/flow/2784#-KxRYJQCMWv3PgyZ045t:-KxRZ2F0CUWnWG5U_dq_:b-pq306y) ([raw file](https://github.com/vaadin/flow/blob/c1758281d5b87c932387d3972c8c527a925ba520/flow-components-parent/demo-flow-components/src/test/java/com/vaadin/flow/demo/views/GridViewIT.java#L221)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

This can break if the internals of the component changes over time. One way of testing this is just to evaluate the `frozen` property of the `vaadin-grid-column` element, outside the shadow root. That's public API, so it shouldn't change unless a major version is released.
</blockquote></details>

Thing is, it is not actually applied to the `vaadin-grid-column` element.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2784)*

**Comment by ahie** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[flow-components-parent/demo-flow-components/src/test/java/com/vaadin/flow/demo/views/GridViewIT.java, line 221 at r1](https://reviewable.io:443/reviews/vaadin/flow/2784#-KxRYJQCMWv3PgyZ045t:-KxRZDAm0VAb7So3rO9O:b-da452c) ([raw file](https://github.com/vaadin/flow/blob/c1758281d5b87c932387d3972c8c527a925ba520/flow-components-parent/demo-flow-components/src/test/java/com/vaadin/flow/demo/views/GridViewIT.java#L221)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

Thing is, it is not actually applied to the `vaadin-grid-column` element.
</blockquote></details>

At least selenium didn't correctly pick it up from the column element.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2784)*

**Comment by ahie** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-components-parent/demo-flow-components/src/test/java/com/vaadin/flow/demo/views/GridViewIT.java, line 221 at r1](https://reviewable.io:443/reviews/vaadin/flow/2784#-KxRYJQCMWv3PgyZ045t:-KxSMhBjhsp64XlKh5hd:bdq0ila) ([raw file](https://github.com/vaadin/flow/blob/c1758281d5b87c932387d3972c8c527a925ba520/flow-components-parent/demo-flow-components/src/test/java/com/vaadin/flow/demo/views/GridViewIT.java#L221)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

At least selenium didn't correctly pick it up from the column element.
</blockquote></details>

Improved the test.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2784)*

**Comment by gilberto-torrezan** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2784)*

**Pull request merged**
