### PR TITLE
fix: Return 404 for /VAADIN/ urls which do not map to a file

### PR DESCRIPTION
**Pull request by Artur-**
Never serve the index.html page for URLs inside /VAADIN/

### CODE REVIEW

**Review by caalador — COMMENTED** [review]
IndexHtmlRequestHandler doesn't call `super.canHandleRequest(request)` so this doesn´t fix the issue outside of using deprecated bootstrap mode.

**Comment by caalador** [comment]
Fixing this to take into account BootstrapHandler would also fix [#12922](https://github.com/vaadin/flow/issues/12922)

**Comment by Artur-** [comment]
Damn, fixed also for `IndexHtmlRequestHandler`

**Comment by caalador** [comment]
Vite dev mode seems to fail with acces denied:
```
Error:  expectedFoldersAccessible[ANY_Chrome_](com.vaadin.viteapp.FileAccessIT)  Time elapsed: 64.734 s  <<< ERROR!
java.io.FileNotFoundException: http://localhost:8888/VAADIN/@fs/home/runner/work/flow/flow/flow-tests/test-frontend/vite-basics/frontend/index.ts
Starting ChromeDriver 97.0.4692.71 (adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}) on port 37455
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1920)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/java.net.URL.openStream(URL.java:1165)
	at org.apache.commons.io.IOUtils.toString(IOUtils.java:2953)
Only local connections are allowed.
	at com.vaadin.viteapp.FileAccessIT.assertAllowed(FileAccessIT.java:25)
	```

**Comment by Artur-** [comment]
Fixed Vite test to use a file the actually exists...

**Review by caalador — APPROVED** [review]

**Pull request merged**
