### PR TITLE
Improve nested property support for Binder

### PR DESCRIPTION
**Pull request by ZheSun88**
Port Change from FW 8.2.0.alpha3 to Flow

Original PR: vaadin/framework#9925

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3140)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[flow-data/src/main/java/com/vaadin/data/AbstractBeanPropertyDefinition.java, line 33 at r1](https://reviewable.io:443/reviews/vaadin/flow/3140#-L0DVs5QjQqlAPJ_f22S:-L0DVs5QjQqlAPJ_f22T:b-6eid72) ([raw file](https://github.com/vaadin/flow/blob/8a1781a356d5386e1243055d638fa94295f2e50e/flow-data/src/main/java/com/vaadin/data/AbstractBeanPropertyDefinition.java#L33)):*
> public abstract class AbstractBeanPropertyDefinition

The original PR doesn't contain this class.
It means it has been added before, in other patch.

So is this patch missed ?
What has happened ?

---

*[flow-data/src/main/java/com/vaadin/data/AbstractBeanPropertyDefinition.java, line 100 at r1](https://reviewable.io:443/reviews/vaadin/flow/3140#-L0DW8Rytowxmh8Uwtkw:-L0DW8Rytowxmh8Uwtkx:b-d0wxhj) ([raw file](https://github.com/vaadin/flow/blob/8a1781a356d5386e1243055d638fa94295f2e50e/flow-data/src/main/java/com/vaadin/data/AbstractBeanPropertyDefinition.java#L100)):*
> ```Java
>         return propertyHolderType;
>     }
> }
> ```

new line

---

*[flow-data/src/main/java/com/vaadin/data/PropertyFilterDefinition.java, line 27 at r1](https://reviewable.io:443/reviews/vaadin/flow/3140#-L0DXCOWQB-tA5dx8-Ax:-L0DXCOWQB-tA5dx8-Ay:b-ume73t) ([raw file](https://github.com/vaadin/flow/blob/8a1781a356d5386e1243055d638fa94295f2e50e/flow-data/src/main/java/com/vaadin/data/PropertyFilterDefinition.java#L27)):*
> public class PropertyFilterDefinition

This is no in the original patch.
Did you move the nested class in its own file ?

---

*[flow-data/src/main/java/com/vaadin/data/PropertyFilterDefinition.java, line 76 at r1](https://reviewable.io:443/reviews/vaadin/flow/3140#-L0DXJTiuUP8lhSzDyQ4:-L0DXJTiuUP8lhSzDyQ5:b-d0wxhj) ([raw file](https://github.com/vaadin/flow/blob/8a1781a356d5386e1243055d638fa94295f2e50e/flow-data/src/main/java/com/vaadin/data/PropertyFilterDefinition.java#L76)):*
> ```Java
>                 Arrays.asList("java"));
>     }
> }
> ```

new line

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3140)*

**Comment by ZheSun88** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[flow-data/src/main/java/com/vaadin/data/AbstractBeanPropertyDefinition.java, line 33 at r1](https://reviewable.io:443/reviews/vaadin/flow/3140#-L0DVs5QjQqlAPJ_f22S:-L0Da66jey2Bz3xhVvwL:b-m64lru) ([raw file](https://github.com/vaadin/flow/blob/8a1781a356d5386e1243055d638fa94295f2e50e/flow-data/src/main/java/com/vaadin/data/AbstractBeanPropertyDefinition.java#L33)):*
i have included this in the commit message.. this was after the original PR... 
(the process was -> someone add the constructor in and other people extract it out to a new file)

> Extract AbstractBeanPropertyDefinition and PropertyFilterDefinition
> 
> this comes from the FW vaadin/framework#10347

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3140)*

**Comment by ZheSun88** [comment]
Review status: 4 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[flow-data/src/main/java/com/vaadin/data/AbstractBeanPropertyDefinition.java, line 100 at r1](https://reviewable.io:443/reviews/vaadin/flow/3140#-L0DW8Rytowxmh8Uwtkw:-L0DcHqAjnydFFKWb510:bb7f2mf) ([raw file](https://github.com/vaadin/flow/blob/8a1781a356d5386e1243055d638fa94295f2e50e/flow-data/src/main/java/com/vaadin/data/AbstractBeanPropertyDefinition.java#L100)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

new line
</blockquote></details>

done

---

*[flow-data/src/main/java/com/vaadin/data/PropertyFilterDefinition.java, line 27 at r1](https://reviewable.io:443/reviews/vaadin/flow/3140#-L0DXCOWQB-tA5dx8-Ax:-L0DbCXtFbs2ZBHEo7xR:b-9x8hfc) ([raw file](https://github.com/vaadin/flow/blob/8a1781a356d5386e1243055d638fa94295f2e50e/flow-data/src/main/java/com/vaadin/data/PropertyFilterDefinition.java#L27)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> public class PropertyFilterDefinition

This is no in the original patch.
Did you move the nested class in its own file ?
</blockquote></details>

this one is the same as `AbstractBeanPropertyDefinition`

---

*[flow-data/src/main/java/com/vaadin/data/PropertyFilterDefinition.java, line 76 at r1](https://reviewable.io:443/reviews/vaadin/flow/3140#-L0DXJTiuUP8lhSzDyQ4:-L0DcL8u8Ky59jzpnWdf:bb7f2mf) ([raw file](https://github.com/vaadin/flow/blob/8a1781a356d5386e1243055d638fa94295f2e50e/flow-data/src/main/java/com/vaadin/data/PropertyFilterDefinition.java#L76)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

new line
</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3140)*

**Comment by denis-anisimov** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3140)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3140)*

**Pull request merged**
