### PR TITLE
Use latest testbench release

### PR DESCRIPTION
**Pull request by alvarezguille**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/2832)

### CODE REVIEW

**Comment by alvarezguille** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2832#-Kxw8blKttkYvv9XEWre:-Kxw8blLy989rU2-2i_U:b-kkuyka) (no related file):*
don't merge for now, just testing integration tests with latest TB

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2832)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2832)*

**Comment by alvarezguille** [comment]
Review status: 1 of 55 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2832#-Kxw8blKttkYvv9XEWre:-KxwVhU3rBjpAuGR46WG:b-wjqyg8) (no related file):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

don't merge for now, just testing integration tests with latest TB
</blockquote></details>

compilation issues fixed, ok to review if validation build passes

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2832)*

**Comment by SomeoneToIgnore** [comment]
*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2832#-Kxw8blKttkYvv9XEWre:-KxwgJ2vfCpQBsxV6Asr:b-nwbnm2) (no related file):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

compilation issues fixed, ok to review if validation build passes
</blockquote></details>

Only 3 test have failed, that's a nice result!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2832)*

**Comment by SomeoneToIgnore** [comment]
Closed the PR since no development is happening for more than half a month.

**Pull request closed without merging**
