### PR TITLE
Possibility to add ui init listeners.

### PR DESCRIPTION
**Pull request by caalador**
Support UIListeners in VaadinService.
The listeners get called every time a new UI is being created.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3691)

### CODE REVIEW

**Comment by pekam** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/server/UIInitEvent.java, line 48 at r1](https://reviewable.io:443/reviews/vaadin/flow/3691#-L7Pgty11c_DkYe0QyvZ:-L7Pgty11c_DkYe0Qyv_:b-phr0g1) ([raw file](https://github.com/vaadin/flow/blob/fc549743e98d94ba705e2e77cd835de547f0faf4/flow-server/src/main/java/com/vaadin/flow/server/UIInitEvent.java#L48)):*
> ```Java
>     }
> 
>     public UI getUi() {
> ```

Feels like the method name should have a capital I: `getUI`

---

*[flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java, line 1293 at r1](https://reviewable.io:443/reviews/vaadin/flow/3691#-L7PmLbM3BEg2N8rQuOa:-L7PmLbM3BEg2N8rQuOb:b-wj7hdj) ([raw file](https://github.com/vaadin/flow/blob/fc549743e98d94ba705e2e77cd835de547f0faf4/flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java#L1293)):*
> ```Java
> 
>     @Test // UIInitListeners
>     public void all_listeners_are_notified_on_ui_init() {
> ```

Why `all_listeners`? Aren't you just testing with one?

And why do you use different naming convention than usually?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3691)*

**Comment by caalador** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[flow-server/src/main/java/com/vaadin/flow/server/UIInitEvent.java, line 48 at r1](https://reviewable.io:443/reviews/vaadin/flow/3691#-L7Pgty11c_DkYe0QyvZ:-L7SpXOlEqrOdpaTK6AK:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/fc549743e98d94ba705e2e77cd835de547f0faf4/flow-server/src/main/java/com/vaadin/flow/server/UIInitEvent.java#L48)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

Feels like the method name should have a capital I: `getUI`
</blockquote></details>

Done.

---

*[flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java, line 1293 at r1](https://reviewable.io:443/reviews/vaadin/flow/3691#-L7PmLbM3BEg2N8rQuOa:-L7Sps4URKjf3GuZOHDN:bdrthp7) ([raw file](https://github.com/vaadin/flow/blob/fc549743e98d94ba705e2e77cd835de547f0faf4/flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java#L1293)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

Why `all_listeners`? Aren't you just testing with one?

And why do you use different naming convention than usually?
</blockquote></details>

Due to all tests having differen conventions?
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3691)*

**Comment by gilberto-torrezan** [comment]
Reviewed 4 of 6 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java, line 2183 at r2](https://reviewable.io:443/reviews/vaadin/flow/3691#-L7TAfsE_wo0TMHdikCQ:-L7TAfsE_wo0TMHdikCR:bp0uvl6) ([raw file](https://github.com/vaadin/flow/blob/a10eb6aa9df48d6d5f39a3d31a4204c8900bc01b/flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java#L2183)):*
> ```Java
>     public void fireUIInitListeners(UI ui) {
>         UIInitEvent initEvent = new UIInitEvent(ui, this);
>         uiInitListeners.forEach(listener -> listener.uiInit(initEvent));
> ```

What would happen if you add or remove a listener from inside a listener?
I suggest adding such test, to prevent `ConcurrentModificationExeception`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3691)*

**Comment by caalador** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java, line 2183 at r2](https://reviewable.io:443/reviews/vaadin/flow/3691#-L7TAfsE_wo0TMHdikCQ:-L7TWSJGaHO4Kz9obpfn:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/a10eb6aa9df48d6d5f39a3d31a4204c8900bc01b/flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java#L2183)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

What would happen if you add or remove a listener from inside a listener?
I suggest adding such test, to prevent `ConcurrentModificationExeception`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3691)*

**Comment by gilberto-torrezan** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java, line 2183 at r2](https://reviewable.io:443/reviews/vaadin/flow/3691#-L7TAfsE_wo0TMHdikCQ:-L7T_c1dLA4s2_zmAu8m:b-7zfbql) ([raw file](https://github.com/vaadin/flow/blob/a10eb6aa9df48d6d5f39a3d31a4204c8900bc01b/flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java#L2183)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Weird, I could swear that adding/removing an item during `forEach` (without protecting the collection) would cause an Exception. Ok then.

---

*[flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java, line 83 at r3](https://reviewable.io:443/reviews/vaadin/flow/3691#-L7T_BuHqFNGQC8_7yUd:-L7T_BuHqFNGQC8_7yUe:b-objrk8) ([raw file](https://github.com/vaadin/flow/blob/b149bcf3f9f6d35f482028e55d10af5175eef941/flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java#L83)):*
> ```Java
> import elemental.json.JsonObject;
> import elemental.json.impl.JsonUtil;
> import static java.nio.charset.StandardCharsets.UTF_8;
> ```

Duplicated import?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3691)*

**Comment by caalador** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java, line 2183 at r2](https://reviewable.io:443/reviews/vaadin/flow/3691#-L7TAfsE_wo0TMHdikCQ:-L7TlX0o6DxqfNJ1_c_v:b-xe4e2z) ([raw file](https://github.com/vaadin/flow/blob/a10eb6aa9df48d6d5f39a3d31a4204c8900bc01b/flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java#L2183)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Weird, I could swear that adding/removing an item during `forEach` (without protecting the collection) would cause an Exception. Ok then.
</blockquote></details>

It's using a `CopyOnWriteArrayList` that is thread safe.

---

*[flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java, line 83 at r3](https://reviewable.io:443/reviews/vaadin/flow/3691#-L7T_BuHqFNGQC8_7yUd:-L7TlaN-szt0C1f4Ie99:b-rm7hln) ([raw file](https://github.com/vaadin/flow/blob/b149bcf3f9f6d35f482028e55d10af5175eef941/flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java#L83)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Duplicated import?
</blockquote></details>

Merge from master.
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3691)*

**Comment by gilberto-torrezan** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3691#-:-L7UGwZeDVoNYmFfGuaK:bnfp4nl)*

**Pull request merged**
