### PR TITLE
chore: Change line length to a more modern 120

### PR DESCRIPTION
**Pull request by Artur-**

### CODE REVIEW

**Comment by knoobie** [comment]
Welcome in 2024! 🥳

**Comment by caalador** [comment]
Will this lead to updating the line length for other alive versions also so that cherry picking works (has a better change to work) automatically?

**Comment by Artur-** [comment]
It might work by happenstance. Otherwise #20164 and this + #20160 + #20185 should be backported to all relevant versions

**Comment by mshabarov** [comment]
Moved this to a draft as the discussion is ongoing about should we switch to longer lines or not.

**Comment by Artur-** [comment]
> Moved this to a draft as the discussion is ongoing about should we switch to longer lines or not.

Where is this discussion ongoing and what on earth are the arguments against it?

**Comment by mshabarov** [comment]
We discussed this change internally and the picture seems to be so that many people are neutral, few people voted up for 120, but the bigger group of people shared a strong wish to keep the old 80 chars formatting with a thorough argumentation. IMHO it’s fair to keep the existing formatting based on these results.

**Pull request closed without merging**
