### PR TITLE
Detect IE11 as IE11 when in compatibility mode (#3935)

### LINKED ISSUE #3935: IE11 in compatibility mode is not detected as IE11
IE11 is supported, but on intranets IE11 might have been configured to use compatibility mode.
If IE11 recognizes a URL as an intranet URL IE11 will send user-agent strings which flow currently detects as being IE7.
Since https://github.com/vaadin/flow/issues/2477 has been merged IE11 will happily render the app with all the capabilities of IE11 once you click "Continue without updating" on the "I'm sorry, but your browser is not supported" warning page.

IE11 in compatibility mode should be properly detected based on the user-agent string to provide a better user experience by not crying wolf.

Related: https://github.com/vaadin/framework/pull/8884

### PR DESCRIPTION
**Pull request by Darsstar**
Fixes #3935

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3937)

### CODE REVIEW

**Comment by gilberto-torrezan** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/flow/3937#-LAlU83P9XAgxwYUCzUk:-LAlU83P9XAgxwYUCzUl:b-pkub6y) (no related file):*
Hi, thanks for the PR. I put some comments in the review, please take a look.

---

*[flow-server/src/main/java/com/vaadin/flow/shared/BrowserDetails.java, line 126 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3937#-LAlTlRQ0MdIXEhSfRXF:-LAlTlRR7lWpzIjBWxcE:b-cvp9i4) ([raw file](https://github.com/vaadin/flow/blob/31bb93da5cbcae75e519762803372dbe457adeaf/flow-server/src/main/java/com/vaadin/flow/shared/BrowserDetails.java#L126)):*
> ```Java
>                 tmp = tmp.replaceFirst("([0-9]+\\.[0-9]+).*", "$1");
>                 browserEngineVersion = Float.parseFloat(tmp);
>                 if (browserEngineVersion > 7) {
> ```

Worth adding a comment here on the code about why version 8 should be considered version 7 for detection purposes.

---

*[flow-server/src/test/java/com/vaadin/flow/shared/BrowserDetailsTest.java, line 35 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3937#-LAlScb79YiQrK_cBP1y:-LAlScb79YiQrK_cBP1z:bxscn50) ([raw file](https://github.com/vaadin/flow/blob/31bb93da5cbcae75e519762803372dbe457adeaf/flow-server/src/test/java/com/vaadin/flow/shared/BrowserDetailsTest.java#L35)):*
> ```Java
>     private static final String IE11_IN_IE7_MODE_WINDOWS_7 = "Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E)";
>     private static final String IE11_IN_IE7_MODE_WINDOWS_10 = "Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 10.0; WOW64; Trident/7.0; .NET4.0C; .NET4.0E)";
>     private static final String IE11_IN_IE7_MODE_INITIAL_WINDOWS_10 = "Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 10.0; WOW64; Trident/8.0; .NET4.0C; .NET4.0E)";
> ```

What `INITIAL` in the name of the constant means? I see that the difference between initial and not initial is just Trident version, and the `initial` uses a higher version. Should the names be swapped?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3937)*

**Comment by Darsstar** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[flow-server/src/test/java/com/vaadin/flow/shared/BrowserDetailsTest.java, line 35 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3937#-LAlScb79YiQrK_cBP1y:-LAlUx5v75eyMtPKNcxe:bsqpffo) ([raw file](https://github.com/vaadin/flow/blob/31bb93da5cbcae75e519762803372dbe457adeaf/flow-server/src/test/java/com/vaadin/flow/shared/BrowserDetailsTest.java#L35)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

What `INITIAL` in the name of the constant means? I see that the difference between initial and not initial is just Trident version, and the `initial` uses a higher version. Should the names be swapped?
</blockquote></details>

Would `LAUNCH_DAY` be better? On the launch day of Windows 10 IE11 reported Trident/8.0.

---

*[flow-server/src/test/java/com/vaadin/flow/shared/BrowserDetailsTest.java, line 402 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3937#-LAlXfJxE-k0PF5MSkcJ:-LAlXfJxE-k0PF5MSkcK:b-4jtltz) ([raw file](https://github.com/vaadin/flow/blob/31bb93da5cbcae75e519762803372dbe457adeaf/flow-server/src/test/java/com/vaadin/flow/shared/BrowserDetailsTest.java#L402)):*
> ```Java
>          * Trident/4.0 in example user agent string based on beta even though it
>          * should be Trident/5.0 in real (non-beta) user agent strings
>          */
> ```

Or should the test contain a comment like this one? Or both?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3937)*

**Comment by Darsstar** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[flow-server/src/main/java/com/vaadin/flow/shared/BrowserDetails.java, line 126 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3937#-LAlTlRQ0MdIXEhSfRXF:-LAm2bPl26tZAImSbIY5:b-nb83w0) ([raw file](https://github.com/vaadin/flow/blob/31bb93da5cbcae75e519762803372dbe457adeaf/flow-server/src/main/java/com/vaadin/flow/shared/BrowserDetails.java#L126)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Worth adding a comment here on the code about why version 8 should be considered version 7 for detection purposes.
</blockquote></details>

Is this sufficient?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3937)*

**Comment by manolo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[flow-server/src/test/java/com/vaadin/flow/shared/BrowserDetailsTest.java, line 35 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3937#-LAlScb79YiQrK_cBP1y:-LAm7fIn1XApO4wjjaaQ:b-a03cbr) ([raw file](https://github.com/vaadin/flow/blob/31bb93da5cbcae75e519762803372dbe457adeaf/flow-server/src/test/java/com/vaadin/flow/shared/BrowserDetailsTest.java#L35)):*
<details><summary><i>Previously, Darsstar (Dos Moonen) wrote…</i></summary><blockquote>

Would `LAUNCH_DAY` be better? On the launch day of Windows 10 IE11 reported Trident/8.0.
</blockquote></details>

might be `IE11_IN_IE7_MODE_WINDOWS_10_RECENT`

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3937)*

**Pull request merged**
