### PR TITLE
Redirect with esc-key after internal error

### PR DESCRIPTION
**Pull request by pekam**
The message inside the internal error dialog claims that you can
continue either by clicking the dialog or pressing the esc-key. However,
it seems that continuing with the esc-key was never implemented.

Fixes partly #4089

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/4190)

### CODE REVIEW

**Comment by caalador** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow/4190#-LDfOWPOBNEUm8dcS0Z3:-LDfOWPOBNEUm8dcS0Z4:b-eosqnv) (no related file):*
Is there a way to validate that the esc actually goes to the handler and redirects?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4190)*

**Comment by pekam** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow/4190#-LDfOWPOBNEUm8dcS0Z3:-LDfU-N86Nc8eM3CJ6XD:bsr1m21) (no related file):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Is there a way to validate that the esc actually goes to the handler and redirects?
</blockquote></details>

Yes... In the same way as `ExpireSessionIT.sessionExpired_refreshByDefault()`.

But that's the test that is unstable:
https://teamcity.vaadin.com/project.html?projectId=Flow&testNameId=-5587487192688878333&tab=testDetails

Checking that the page has refreshed just randomly fails from time to time.
So I wouldn't want to add another unstable test.

Opinions, suggestions?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4190)*

**Comment by Artur-** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow/4190#-LDfOWPOBNEUm8dcS0Z3:-LDfXQ5a2ZOMJLUgFDgE:bl160dl) (no related file):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

Yes... In the same way as `ExpireSessionIT.sessionExpired_refreshByDefault()`.

But that's the test that is unstable:
https://teamcity.vaadin.com/project.html?projectId=Flow&testNameId=-5587487192688878333&tab=testDetails

Checking that the page has refreshed just randomly fails from time to time.
So I wouldn't want to add another unstable test.

Opinions, suggestions?
</blockquote></details>

https://github.com/vaadin/flow/issues/4200

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4190)*

**Comment by caalador** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow/4190#-LDfOWPOBNEUm8dcS0Z3:-LDfYUti4D_JQbdSkDck:b-pc70s1) (no related file):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

https://github.com/vaadin/flow/issues/4200
</blockquote></details>

So give the session tests their own module. IT test them there.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4190)*

**Comment by caalador** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow/4190#-LDfOWPOBNEUm8dcS0Z3:-LDfgOE39Ak_hHntKP6N:b-hbzold) (no related file):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

Thanks @artur- !

> So give the session tests their own module. IT test them there.

How does this solve the problem? They can still be executed in any order, right?

What if I just add an `@After` method for resetting the settings?
</blockquote></details>

The modules are run on their own on their own started server.
After might also work, but only if no other test runs in parallel at the same time.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4190)*

**Comment by caalador** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow/4190#-LDfOWPOBNEUm8dcS0Z3:-LDfhHCFAnl7DnO9nbA0:bg0mtj7) (no related file):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

The modules are run on their own on their own started server.
After might also work, but only if no other test runs in parallel at the same time.
</blockquote></details>

In their own `test-session-states` Maven module.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4190)*

**Comment by pekam** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow/4190#-LDfOWPOBNEUm8dcS0Z3:-LDfhCHr2_-5kzSe44pj:bdmz9mn) (no related file):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

The modules are run on their own on their own started server.
After might also work, but only if no other test runs in parallel at the same time.
</blockquote></details>

But if I create a new module for these tests they would still be in the same module. Or have I misunderstood something?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4190)*

**Comment by caalador** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow/4190#-LDfOWPOBNEUm8dcS0Z3:-LDfhckNE9-Fe9oXKik_:b-tewjso) (no related file):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

But if I create a new module for these tests they would still be in the same module. Or have I misunderstood something?
</blockquote></details>

It would be a sub module for flow-tests, but that wouldn't make the setting overflow to test-root-context module tests.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4190)*

**Comment by pekam** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow/4190#-LDfOWPOBNEUm8dcS0Z3:-LDfmouc6WrCJhxyu5qA:bwigt0f) (no related file):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

It would be a sub module for flow-tests, but that wouldn't make the setting overflow to test-root-context module tests.
</blockquote></details>

We are currently not understanding each other... Like I said, these tests that break each other would still be in the same module so it wouldn't fix the problem.

Unless we move only the one test-case which changes the settings to a new module. But it would be confusing to have so tightly related tests (which also currently use the same test view) in different modules.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4190)*

**Comment by caalador** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow/4190#-LDfOWPOBNEUm8dcS0Z3:-LDfrm893QXW2ZwgtTiF:bybusrv) (no related file):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

We are currently not understanding each other... Like I said, these tests that break each other would still be in the same module so it wouldn't fix the problem.

Unless we move only the one test-case which changes the settings to a new module. But it would be confusing to have so tightly related tests (which also currently use the same test view) in different modules.
</blockquote></details>

Don't both of the tests expect that the error notification is shown? 

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4190)*

**Comment by pekam** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow/4190#-LDfOWPOBNEUm8dcS0Z3:-LDfrxcc0Zh-z_RmDaUb:b2kg3xh) (no related file):*
> Don't both of the tests expect that the error notification is shown?

Currently we have two tests for `SessionExpired`: one that expects an instant refresh when the session is expired, and the other which changes the default setting to show notification instead.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4190)*

**Comment by pekam** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow/4190#-LDfOWPOBNEUm8dcS0Z3:-LDfvUxs0NPYYss75BnU:bp64hfk) (no related file):*
> A custom servlet in the same project should be enough, e.g. /view-custom-system-messages?

I'll try this.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4190)*

**Comment by pekam** [comment]
Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow/4190#-LDfOWPOBNEUm8dcS0Z3:-LDgCFx11cz1itmCpv19:b-oo0mvl) (no related file):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

> A custom servlet in the same project should be enough, e.g. /view-custom-system-messages?

I'll try this.
</blockquote></details>

I didn't manage to figure out how to configure another servlet for the ui-tests. But it's not the target of this ticket anyway, so I just added tests for the 'internal error' dialog. I realized that if I make an internal error instead of expire the session, the changes made in the other test don't affect these tests and I'm not at least introducing any new unstable tests.

I added also the `@After` method for resetting the setting. In case it doesn't fix the unstable session expired test, we can continue with it in the scope of the ticket that Artur created.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4190)*

**Comment by caalador** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4190#-:-LDjJyfDCSHtCNVPSkwT:bnfp4nl)*

**Pull request merged**
