### PR TITLE
Update demos to use new router

### PR DESCRIPTION
**Pull request by ZheSun88**
issue is partly related to #2594 
remove the servlet file;
implement new router in MainLayout;
remove view from DemoView.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/2629)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 3 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/MainLayout.java, line 128 at r1](https://reviewable.io:443/reviews/vaadin/flow/2629#-KvlYoa9lxBsiDEnuVr6:-KvlYoa9lxBsiDEnuVr7:b-6dbuej) ([raw file](https://github.com/vaadin/flow/blob/b375be69f07fcedeb448d10d03d9c7fbf0c6ac1d/flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/MainLayout.java#L128)):*
> ReflectTools.createInstance(
>                     ComponentDemoRegister.getViewFor(parameter).get())

Doesn't `createInstance`  always creates a new instance ? Then how this check may be `true` at all ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2629)*

**Comment by ZheSun88** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/MainLayout.java, line 128 at r1](https://reviewable.io:443/reviews/vaadin/flow/2629#-KvlYoa9lxBsiDEnuVr6:-Kvl_by_9fidMf-kuM6y:bu8f8ib) ([raw file](https://github.com/vaadin/flow/blob/b375be69f07fcedeb448d10d03d9c7fbf0c6ac1d/flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/MainLayout.java#L128)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ReflectTools.createInstance(
>                     ComponentDemoRegister.getViewFor(parameter).get())

Doesn't `createInstance`  always creates a new instance ? Then how this check may be `true` at all ?
</blockquote></details>

I am trying to reimplement the `setChildView` method based on the older router version. 
as it was 
```
if (selectedView == childView) {
            return;
        }
```
and `createInstance` is used for catching all exceptions. as i was using `selectedView = ComponentDemoRegister.getViewFor(parameter).get().newInstance();` instead.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2629)*

**Comment by denis-anisimov** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/MainLayout.java, line 128 at r1](https://reviewable.io:443/reviews/vaadin/flow/2629#-KvlYoa9lxBsiDEnuVr6:-Kvlca9FBsYuWKrsc0Q4:b6dvbxl) ([raw file](https://github.com/vaadin/flow/blob/b375be69f07fcedeb448d10d03d9c7fbf0c6ac1d/flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/MainLayout.java#L128)):*
<details><summary><i>Previously, ZheSun88 wrote…</i></summary><blockquote>

I am trying to reimplement the `setChildView` method based on the older router version. 
as it was 
```
if (selectedView == childView) {
            return;
        }
```
and `createInstance` is used for catching all exceptions. as i was using `selectedView = ComponentDemoRegister.getViewFor(parameter).get().newInstance();` instead.


</blockquote></details>

It's not the same at all.
Current impl has no sense.

The comparison will never be `true` since you are comparing some existing object with newly created. They are never the  same.

You either should remove this check at all with the block (not effective) or store a pair: parameter value and the `selectedView`. Then compare the parameter value: if it's the same as stored previously parameter value then use `selectedView` otherwise create a new one.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2629)*

**Comment by ZheSun88** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/MainLayout.java, line 128 at r1](https://reviewable.io:443/reviews/vaadin/flow/2629#-KvlYoa9lxBsiDEnuVr6:-Kvli5hp7PoaMjjzJldp:b-6ou210) ([raw file](https://github.com/vaadin/flow/blob/b375be69f07fcedeb448d10d03d9c7fbf0c6ac1d/flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/MainLayout.java#L128)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

It's not the same at all.
Current impl has no sense.

The comparison will never be `true` since you are comparing some existing object with newly created. They are never the  same.

You either should remove this check at all with the block (not effective) or store a pair: parameter value and the `selectedView`. Then compare the parameter value: if it's the same as stored previously parameter value then use `selectedView` otherwise create a new one.
</blockquote></details>

I think you must mean this way.  and it also avoids reloading the same page.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2629)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/MainLayout.java, line 128 at r1](https://reviewable.io:443/reviews/vaadin/flow/2629#-KvlYoa9lxBsiDEnuVr6:-KvwkCeKD9r880Mfoeoq:b9rem2b) ([raw file](https://github.com/vaadin/flow/blob/b375be69f07fcedeb448d10d03d9c7fbf0c6ac1d/flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/MainLayout.java#L128)):*
<details><summary><i>Previously, ZheSun88 wrote…</i></summary><blockquote>

I think you must mean this way.  and it also avoids reloading the same page.
</blockquote></details>

The same idea, different impl, yes.

---

*[flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/MainLayout.java, line 126 at r2](https://reviewable.io:443/reviews/vaadin/flow/2629#-KvwkHqdQ9RvqOOBI8OT:-KvwkHqdQ9RvqOOBI8OU:b-2rc21b) ([raw file](https://github.com/vaadin/flow/blob/59b90e2c58b04a97ac2c71dea1d953bc07fe0c34/flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/MainLayout.java#L126)):*
> selectedView.getClass().getAnnotation(ComponentDemo.class)
>                         .href()

never null ?
May be better check equality via `Objects.equals`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2629)*

**Comment by ZheSun88** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/MainLayout.java, line 126 at r2](https://reviewable.io:443/reviews/vaadin/flow/2629#-KvwkHqdQ9RvqOOBI8OT:-Kvzt96lcsRz9QEEyb-e:b-etr6f4) ([raw file](https://github.com/vaadin/flow/blob/59b90e2c58b04a97ac2c71dea1d953bc07fe0c34/flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/MainLayout.java#L126)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> selectedView.getClass().getAnnotation(ComponentDemo.class)
>                         .href()

never null ?
May be better check equality via `Objects.equals`.
</blockquote></details>

`selectedView.getClass().getAnnotation(ComponentDemo.class)
.href()` is a String value, i think it is not good to use `Objects.equals` directly. 

or it is better to check `selectedView` via `Objects.equals`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2629)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/MainLayout.java, line 126 at r2](https://reviewable.io:443/reviews/vaadin/flow/2629#-KvwkHqdQ9RvqOOBI8OT:-KvzxrHN7zNL9ihfs-be:b10ij8o) ([raw file](https://github.com/vaadin/flow/blob/59b90e2c58b04a97ac2c71dea1d953bc07fe0c34/flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/MainLayout.java#L126)):*
<details><summary><i>Previously, ZheSun88 wrote…</i></summary><blockquote>

`selectedView.getClass().getAnnotation(ComponentDemo.class)
.href()` is a String value, i think it is not good to use `Objects.equals` directly. 

or it is better to check `selectedView` via `Objects.equals`
</blockquote></details>

I don't understand you.
I'm suggesting to replace `String.equals(String)` to `Objects.equals(String,String)`.
What might be wrong here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2629)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2629)*

**Comment by ZheSun88** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/MainLayout.java, line 126 at r2](https://reviewable.io:443/reviews/vaadin/flow/2629#-KvwkHqdQ9RvqOOBI8OT:-Kw-3ojIDmccaUrXmMlK:b-cu8qix) ([raw file](https://github.com/vaadin/flow/blob/59b90e2c58b04a97ac2c71dea1d953bc07fe0c34/flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/MainLayout.java#L126)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

I don't understand you.
I'm suggesting to replace `String.equals(String)` to `Objects.equals(String,String)`.
What might be wrong here?
</blockquote></details>

now, it switches to `Objects.equals(String, String)`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2629)*

**Comment by caalador** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/MainLayout.java, line 51 at r3](https://reviewable.io:443/reviews/vaadin/flow/2629#-Kw4hTvLN4n_hR9WL9sZ:-Kw4hTvLN4n_hR9WL9s_:brr3c48) ([raw file](https://github.com/vaadin/flow/blob/3d9504ca653b1984ceeac6179a39bbbb34294871/flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/MainLayout.java#L51)):*
> ```Java
> @StyleSheet("src/css/prism.css")
> public class MainLayout extends PolymerTemplate<MainLayoutModel>
>         implements RouterLayout, HasUrlParameter<String> {
> ```

The RouterLayout is not needed as the MainLayout adds the content to itself and no one uses it as a RouterLayout.

---

*[flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/MainLayout.java, line 135 at r3](https://reviewable.io:443/reviews/vaadin/flow/2629#-Kw4iM3vYEvi6ViKz0YL:-Kw4iM3vYEvi6ViKz0YM:bwoxlmz) ([raw file](https://github.com/vaadin/flow/blob/3d9504ca653b1984ceeac6179a39bbbb34294871/flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/MainLayout.java#L135)):*
>  if (ComponentDemoRegister.getViewFor(parameter).isPresent()) {
>  
>                 selectedView = ReflectTools.createInstance(
>                         ComponentDemoRegister.getViewFor(parameter).get());
>                 getElement().appendChild(selectedView.getElement());
>  
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>
>                 if (selectedView instanceof DemoView) {
>                     getModel().setPage(selectedView.getClass()
>                             .getAnnotation(ComponentDemo.class).name());
>                 }
>             }
</details>

this would read better like this:
```
        ComponentDemoRegister.getViewFor(parameter)
                .ifPresent(this::addComponentToView);

    }

    private void addComponentToView(Class<? extends DemoView> view) {
        selectedView = ReflectTools.createInstance(view);
        getElement().appendChild(selectedView.getElement());

        if (DemoView.class.isAssignableFrom(view)) {
            getModel().setPage(view.getAnnotation(ComponentDemo.class).name());
        }
    }
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2629)*

**Comment by ZheSun88** [comment]
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/MainLayout.java, line 51 at r3](https://reviewable.io:443/reviews/vaadin/flow/2629#-Kw4hTvLN4n_hR9WL9sZ:-Kw5KplGfg81uZ-9yLTj:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/3d9504ca653b1984ceeac6179a39bbbb34294871/flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/MainLayout.java#L51)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

The RouterLayout is not needed as the MainLayout adds the content to itself and no one uses it as a RouterLayout.
</blockquote></details>

Done.

---

*[flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/MainLayout.java, line 135 at r3](https://reviewable.io:443/reviews/vaadin/flow/2629#-Kw4iM3vYEvi6ViKz0YL:-Kw5L-W2ZiOgsJDe-I-P:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/3d9504ca653b1984ceeac6179a39bbbb34294871/flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/MainLayout.java#L135)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

>  if (ComponentDemoRegister.getViewFor(parameter).isPresent()) {
>  
>                 selectedView = ReflectTools.createInstance(
>                         ComponentDemoRegister.getViewFor(parameter).get());
>                 getElement().appendChild(selectedView.getElement());
>  
>                 if (selectedView instanceof DemoView) {
>                     getModel().setPage(selectedView.getClass()
>                             .getAnnotation(ComponentDemo.class).name());
>                 }
>             }

this would read better like this:
```
        ComponentDemoRegister.getViewFor(parameter)
                .ifPresent(this::addComponentToView);

    }

    private void addComponentToView(Class<? extends DemoView> view) {
        selectedView = ReflectTools.createInstance(view);
        getElement().appendChild(selectedView.getElement());

        if (DemoView.class.isAssignableFrom(view)) {
            getModel().setPage(view.getAnnotation(ComponentDemo.class).name());
        }
    }
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2629)*

**Comment by caalador** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2629)*

**Pull request merged**
