### PR TITLE
ComponentGenerator to correctly handle HTML in JavaDoc

### PR DESCRIPTION
**Pull request by asashour**
Currently, `ComponentGenerator` generates something like:

```
 * {@code }
 * <code>html &lt;vaadin-combo-box label=&quot;Fruit&quot; items=&quot;[[data]]&quot;&gt; &lt;/vaadin-combo-box&gt; {@code }</code>
```

After the change that would be:
```
 * &lt;vaadin-combo-box label=&quot;Fruit&quot; items=&quot;[[data]]&quot;&gt; &lt;/vaadin-combo-box&gt;
```

I couldn't find a way to fully test it against an actual component, since the JSON files in e.g. `vaadin-combo-box` are not handled by the `ComponentGenerator`

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3028)

### CODE REVIEW

**Comment by gilberto-torrezan** [comment]
Hi @asashour, first of all, thanks for the PR!

We don't have it documented anywhere (and we should!), but to test the generator you can do this:

First, locally install the generator from `flow-code-generator-api`:
```
mvn install
```

Then in your `flow-generated-components`, regenerate the files by using:
```
mvn clean install -Pgenerator
```

That will delete the current files and generate new ones with your generator.

With the diff from the previous revision you can see everything that has changed (that's why we push the generated files).

**Comment by asashour** [comment]
Thanks for feedback, should I push the generated code files also? They seem different (other than HTML javadoc).

Please note there is committed PR #2983, which removed some redundant interfaces, however correct way to do it by the `generator` is proposed in #3018.

Other than this, I see changes in method signatures, e.g. `GeneratedVaadinComboBoxDropdownWrapper`.`linkPaths`, from:

```
public` void linkPaths(java.lang.String to, java.lang.String from) {
```

to

```
    protected void linkPaths(elemental.json.JsonObject to,
            elemental.json.JsonObject from) {

```

**Comment by gilberto-torrezan** [comment]
That's a known issue that we didn't fix yet. What happens is that we have several methods with the same names but different arguments - and they are generated in different orders each time, almost randomly.

We didn't track down the source of the problem, seems to be a `HashMap` somewhere that should be a `LinkedHashMap` instead, or something like it.

But answering the question, yes, please push the generated files as well. It's better for us to review by seeing how the changes actually impacts the generated code.

**Comment by gilberto-torrezan** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r3, 26 of 26 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/JavaDocFormatter.java, line 106 at r4](https://reviewable.io:443/reviews/vaadin/flow/3028#-Kzgs0_fkYc14WKEH0JM:-Kzgs0_fkYc14WKEH0JN:b7pphfk) ([raw file](https://github.com/vaadin/flow/blob/266500758f4b5677d58b50388399050ef8875b8d/flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/JavaDocFormatter.java#L106)):*
> Could be replaced by {@code org.apache.commons.text.StringEscapeUtils} if
>      * exists as a dependency.

The code generator dependency is not imported by Flow applications - it is part of a maven plugin used only by the `flow-generated-components`. That means we can (and should) add any external dependencies we feel are necessary to reduce our own code.

So go ahead and import it =)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3028)*

**Pull request merged**
