### PR TITLE
Add missing mixin interfaces to Grid

### PR DESCRIPTION
**Pull request by ahie**
Additionally adds a test for detecting missing interfaces
in other vaadin components.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/2758)

### CODE REVIEW

**Comment by torok-peter** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/ClasspathHelper.java, line 50 at r1](https://reviewable.io:443/reviews/vaadin/flow/2758#-KxDEwfLpKe_il8I7JUA:-KxDEwfLpKe_il8I7JUB:bwyxmoh) ([raw file](https://github.com/vaadin/flow/blob/f4cf55a2257eaf085380e24cb96cc96813eb63ea/flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/ClasspathHelper.java#L50)):*
> ```Java
>             + File.separatorChar + "vaadin" + File.separatorChar;
> 
>     public static Stream<Class<?>> getVaadinClassesFromClasspath(
> ```

Javadoc

---

*[flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/ClasspathHelper.java, line 50 at r1](https://reviewable.io:443/reviews/vaadin/flow/2758#-KxDMEwKlWxIm8d1BVVe:-KxDMEwKlWxIm8d1BVVf:bwc2b5m) ([raw file](https://github.com/vaadin/flow/blob/f4cf55a2257eaf085380e24cb96cc96813eb63ea/flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/ClasspathHelper.java#L50)):*
> ```Java
>             + File.separatorChar + "vaadin" + File.separatorChar;
> 
>     public static Stream<Class<?>> getVaadinClassesFromClasspath(
> ```

The path should be validated to prevent e.g. path traversal attacks

---

*[flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/ClasspathHelper.java, line 56 at r1](https://reviewable.io:443/reviews/vaadin/flow/2758#-KxDEPxvbCMJqOwOBTJI:-KxDEPxwshsVkd03quAG:bcdnoqw) ([raw file](https://github.com/vaadin/flow/blob/f4cf55a2257eaf085380e24cb96cc96813eb63ea/flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/ClasspathHelper.java#L56)):*
> ```Java
>                 .map(File::new).map(file -> getVaadinClassesFromFile(file))
>                 .flatMap(List::stream).filter(classFilter)
>                 .filter(cls -> !cls.isSynthetic() && !cls.isAnonymousClass()
> ```

Could exchange the last two filters to save some processing and reduce possibilities for errors

---

*[flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/ClasspathHelper.java, line 61 at r1](https://reviewable.io:443/reviews/vaadin/flow/2758#-KxDEyVQoj6wCicrqSKm:-KxDEyVQoj6wCicrqSKn:bwyxmoh) ([raw file](https://github.com/vaadin/flow/blob/f4cf55a2257eaf085380e24cb96cc96813eb63ea/flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/ClasspathHelper.java#L61)):*
> ```Java
>     }
> 
>     public static Stream<Class<?>> getVaadinClassesFromClasspath(
> ```

Javadoc

---

*[flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/MixinTest.java, line 80 at r1](https://reviewable.io:443/reviews/vaadin/flow/2758#-KxDNU6g4afGv1cDARmT:-KxDNU6g4afGv1cDARmU:bbtbf3e) ([raw file](https://github.com/vaadin/flow/blob/f4cf55a2257eaf085380e24cb96cc96813eb63ea/flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/MixinTest.java#L80)):*
> ```Java
>                                     clazz.getName(), requiredIface.getName()),
>                                     interfaces.contains(requiredIface)));
>                 });
> ```

Should also verify that all applicable classes are loaded

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2758)*

**Comment by gilberto-torrezan** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2758)*

**Comment by ahie** [comment]
Review status: 1 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

*[flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/ClasspathHelper.java, line 50 at r1](https://reviewable.io:443/reviews/vaadin/flow/2758#-KxDEwfLpKe_il8I7JUA:-KxDR3vLN2ljW-Hb-Aza:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/f4cf55a2257eaf085380e24cb96cc96813eb63ea/flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/ClasspathHelper.java#L50)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

Javadoc
</blockquote></details>

Done.

---

*[flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/ClasspathHelper.java, line 50 at r1](https://reviewable.io:443/reviews/vaadin/flow/2758#-KxDMEwKlWxIm8d1BVVe:-KxDR4QSebxRgKjjcx-k:blj6hro) ([raw file](https://github.com/vaadin/flow/blob/f4cf55a2257eaf085380e24cb96cc96813eb63ea/flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/ClasspathHelper.java#L50)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

The path should be validated to prevent e.g. path traversal attacks
</blockquote></details>

This is just a test helper class.

---

*[flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/ClasspathHelper.java, line 56 at r1](https://reviewable.io:443/reviews/vaadin/flow/2758#-KxDEPxvbCMJqOwOBTJI:-KxDR6x3xp7cF79pwDmd:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/f4cf55a2257eaf085380e24cb96cc96813eb63ea/flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/ClasspathHelper.java#L56)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

Could exchange the last two filters to save some processing and reduce possibilities for errors
</blockquote></details>

Done.

---

*[flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/ClasspathHelper.java, line 61 at r1](https://reviewable.io:443/reviews/vaadin/flow/2758#-KxDEyVQoj6wCicrqSKm:-KxDR8fNPk3VlpWs4BVf:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/f4cf55a2257eaf085380e24cb96cc96813eb63ea/flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/ClasspathHelper.java#L61)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

Javadoc
</blockquote></details>

Done.

---

*[flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/MixinTest.java, line 80 at r1](https://reviewable.io:443/reviews/vaadin/flow/2758#-KxDNU6g4afGv1cDARmT:-KxDRBXXK9cVPQXrMHnL:bslc4al) ([raw file](https://github.com/vaadin/flow/blob/f4cf55a2257eaf085380e24cb96cc96813eb63ea/flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/MixinTest.java#L80)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

Should also verify that all applicable classes are loaded
</blockquote></details>

The point of the test is to not have to manually add a collection of classes to test, but instead detect any new component class that is added. That's why the test class has a `CLASS_WHITELIST`, to specifically ignore some components this test shouldn't be applied to.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2758)*

**Comment by torok-peter** [comment]
Reviewed 1 of 2 files at r2.
Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2758)*

**Comment by torok-peter** [comment]
Reviewed 1 of 2 files at r2, 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2758)*

**Pull request merged**
