### PR TITLE
Support fragment names.

### PR DESCRIPTION
**Pull request by SomeoneToIgnore**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3361)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/common/BundleConfigurationReader.java, line 59 at r1](https://reviewable.io:443/reviews/vaadin/flow/3361#-L3Ry1gyib30Fr4INNu2:-L3Ry1gz6teNhAbMSYL6:b-l61q0n) ([raw file](https://github.com/vaadin/flow/blob/7f12ff174870657cb486292d66ea185b9ced0ce7/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/common/BundleConfigurationReader.java#L59)):*
> IllegalArgumentException

I'm not sure that this is IAE.
Technically the method expects a file and it gets a file.
It's the file content which is invalid.

May be it should be `IllegalStateException`, but I'm not sure.

I kind of consider IAE when the argument is `null` or the argument has type `Object` but the method is expected to be called with some narrowed type (like in reflection).
But I'm not sure.
It's not blocking.

---

*[flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/common/BundleConfigurationReader.java, line 80 at r1](https://reviewable.io:443/reviews/vaadin/flow/3361#-L3RylAGkBMbzyhRSZim:-L3RylAGkBMbzyhRSZin:bkbhagz) ([raw file](https://github.com/vaadin/flow/blob/7f12ff174870657cb486292d66ea185b9ced0ce7/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/common/BundleConfigurationReader.java#L80)):*
> IllegalArgumentException

Same as above. Not blocking either.

---

*[flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/common/BundleConfigurationReader.java, line 88 at r1](https://reviewable.io:443/reviews/vaadin/flow/3361#-L3Ryq2vfeirUwWGGH75:-L3Ryq2vfeirUwWGGH76:bkbhagz) ([raw file](https://github.com/vaadin/flow/blob/7f12ff174870657cb486292d66ea185b9ced0ce7/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/common/BundleConfigurationReader.java#L88)):*
> IllegalArgumentException

Same as above. Not blocking either.

---

*[flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/common/BundleConfigurationReader.java, line 101 at r1](https://reviewable.io:443/reviews/vaadin/flow/3361#-L3RysjqrrGZL1qcTkPZ:-L3RysjqrrGZL1qcTkP_:bkbhagz) ([raw file](https://github.com/vaadin/flow/blob/7f12ff174870657cb486292d66ea185b9ced0ce7/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/common/BundleConfigurationReader.java#L101)):*
> IllegalArgumentException

Same as above. Not blocking either.

---

*[flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/common/BundleConfigurationReader.java, line 104 at r1](https://reviewable.io:443/reviews/vaadin/flow/3361#-L3RyuUfBryfTdMIGoCz:-L3RyuUfBryfTdMIGoD-:bkbhagz) ([raw file](https://github.com/vaadin/flow/blob/7f12ff174870657cb486292d66ea185b9ced0ce7/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/common/BundleConfigurationReader.java#L104)):*
> IllegalArgumentException

Same as above. Not blocking either.

---

*[flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/common/BundleConfigurationReader.java, line 114 at r1](https://reviewable.io:443/reviews/vaadin/flow/3361#-L3RywJp42r1w9QBqy9t:-L3RywJp42r1w9QBqy9u:bkbhagz) ([raw file](https://github.com/vaadin/flow/blob/7f12ff174870657cb486292d66ea185b9ced0ce7/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/common/BundleConfigurationReader.java#L114)):*
> IllegalArgumentException

Same as above. Not blocking either.

---

*[flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/common/BundleConfigurationReader.java, line 122 at r1](https://reviewable.io:443/reviews/vaadin/flow/3361#-L3Ryxx0OmzUoT54l-eI:-L3Ryxx0OmzUoT54l-eJ:bkbhagz) ([raw file](https://github.com/vaadin/flow/blob/7f12ff174870657cb486292d66ea185b9ced0ce7/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/common/BundleConfigurationReader.java#L122)):*
> IllegalArgumentException

Same as above. Not blocking either.

---

*[flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/common/BundleConfigurationReader.java, line 127 at r1](https://reviewable.io:443/reviews/vaadin/flow/3361#-L3RyzLM3GtIm47nXsbn:-L3RyzLM3GtIm47nXsbo:bkbhagz) ([raw file](https://github.com/vaadin/flow/blob/7f12ff174870657cb486292d66ea185b9ced0ce7/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/common/BundleConfigurationReader.java#L127)):*
> IllegalArgumentException

Same as above. Not blocking either.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3361)*

**Comment by SomeoneToIgnore** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/common/BundleConfigurationReader.java, line 59 at r1](https://reviewable.io:443/reviews/vaadin/flow/3361#-L3Ry1gyib30Fr4INNu2:-L3SIlcH9JqAv8NU9dox:b-nt55wk) ([raw file](https://github.com/vaadin/flow/blob/7f12ff174870657cb486292d66ea185b9ced0ce7/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/common/BundleConfigurationReader.java#L59)):*
Updated everything but the current one, since here it's kind of argument. 

> It's not blocking.

But lots of others are :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3361)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 2 files at r2.
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/common/BundleConfigurationReader.java, line 59 at r1](https://reviewable.io:443/reviews/vaadin/flow/3361#-L3Ry1gyib30Fr4INNu2:-L3SN12XRE3orMZzuubJ:blgzod8) ([raw file](https://github.com/vaadin/flow/blob/7f12ff174870657cb486292d66ea185b9ced0ce7/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/common/BundleConfigurationReader.java#L59)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Updated everything but the current one, since here it's kind of argument. 

> It's not blocking.

But lots of others are :)
</blockquote></details>

Forgot to unblock other, sorry.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3361)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3361)*

**Pull request merged**
