### PR TITLE
Fix a link in docs

### PR DESCRIPTION
**Pull request by pekam**
From valo to lumo

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3342)

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
Would it make sense to update all other `valo` containing docs? I see more of them.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3342#-:-L33YjpySZPI-lQ6Tm1W:bkqkhjk)*

**Comment by SomeoneToIgnore** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3342#-:-L33YrBHcwydK_0ZBOAy:bnfp4nl)*

**Comment by pekam** [comment]
I didn't update the getting started tutorial, because it's based on an old Flow version and it's a bigger task to update that

---

Review status: 1 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3342#-:-L33h6ocLTY6sjQAxV9e:b-nbbwev)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3342)*

**Pull request merged**
