### PR TITLE
test: Backport test fix for npm 9

### PR DESCRIPTION
**Pull request by Artur-**

### CODE REVIEW

**Review by mshabarov — APPROVED** [review]

**Comment by czp13** [comment]
I am checking this quite much time ago, I have no idea why Flow Client shown failed here:
```
[INFO] Flow Client ........................................ FAILURE [02:25 min]
```

I do not see any Flow client related error:
```
[INFO] -----------------------< com.vaadin:flow-client >-----------------------
[INFO] Building Flow Client 999.99-SNAPSHOT                              [6/20]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
```

**Comment by Artur-** [comment]
The error is when running `intern`:
```
Ready
Tunnel started
BUG: suiteEnd was received for invalid session 
(ノಠ益ಠ)ノ彡┻━┻
Error: connect ECONNREFUSED ::1:4444
  at Server.post @ node_modules/src/Server.ts:401:16
  at Server.createSession @ node_modules/src/Server.ts:446:16
  at Suite.before @ src/lib/executors/Node.ts:497:15
  @ src/lib/Suite.ts:435:54
  at new t @ node_modules/@theintern/common/index.js:2:32720
  at runLifecycleMethod @ src/lib/Suite.ts:400:13
  at before @ src/lib/Suite.ts:503:13
  at Suite.run @ src/lib/Suite.ts:522:10
  @ src/lib/executors/Node.ts:987:27
  at FunctionQueue.next @ src/lib/executors/Node.ts:1115:19

```

**Comment by czp13** [comment]
Thanks for the comment. Hard to find the root cause for my eyes :(
- many Error lines in logs (I have gone through the thousands of lines but was unable to catch this)
- Also the previous line was related to `com.vaadin.flow.server.frontend.scanner.FrontendDependencies`so thought this is related to flow.server does not flow-client, which was shown failed in the summary.

If I understand correctly:
- Fixing this tunnel problem (which comes with the versioning?) blocking us from merging this to the master,
- And if we can merge the Java code to the master, then this part would fix the symlink test
```java
symlinkByNpm_deleteDirectory_doesNotDeleteSymlinkFolderFiles{
        ...
        File symbolicPackageJson = new File(symbolic, "package.json");
        FileUtils.writeStringToFile(symbolicPackageJson, "{}",
        ...
}
```

@Artur-: Not 100% sure if this approach would work, but Is it ok by you if I just cherry-pick your symlink test fix so the changes in the 
flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java to not block anymore the v23.3 PR-s, merges?

**Comment by czp13** [comment]
Also maybe we can try to use a different chrome version?:
```
"tunnelOptions": {
  "drivers": [
    { "name": "chrome", "version": "2.36" }
  ]
}
```
https://github.com/theintern/intern/issues/888

**Comment by Artur-** [comment]
Merging this to get one step closer

**Pull request merged**
