### PR TITLE
Aggregate dependency javadocs for flow

### PR DESCRIPTION
**Pull request by pleku**
Aggregation only works for one level transitive dependencies, thus need
to make aggredated javadocs for com.vaadin:flow dependency so that
aggregation also works for platform which uses flow dependency (instead
of flow-server etc.).

This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/4150)

### CODE REVIEW

**Comment by caalador** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[flow/pom.xml, line 48 at r1](https://reviewable.io/reviews/vaadin/flow/4150#-LD5GwiE7t_dASe4-1iE:-LD5GwiE7t_dASe4-1iF:bom7g7s) ([raw file](https://github.com/vaadin/flow/blob/ded230fc728bd75e64d280e7a0b2f64493dbe184/flow/pom.xml#L48)):*
> ```XML
>                         <dependencySourceExclude>com.vaadin:flow-client</dependencySourceExclude>
>                     </dependencySourceExcludes>
>                     
> ```

This should be don't fail on warnings as errors should fail the build.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4150)*

**Comment by caalador** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[flow/pom.xml, line 48 at r1](https://reviewable.io/reviews/vaadin/flow/4150#-LD5GwiE7t_dASe4-1iE:-LD5KU5J87c_Y9vsqj-S:bun8lpq) ([raw file](https://github.com/vaadin/flow/blob/ded230fc728bd75e64d280e7a0b2f64493dbe184/flow/pom.xml#L48)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

There are tons of errors in our javadocs, and without this line everything will :fire: 

I can make an issue for fixing those separately
</blockquote></details>

We have tons of warnings. I meant that the comment should be about ignoring the warnings not the errors as errors for failing links should fail the build.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4150)*

**Comment by pleku** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow/pom.xml, line 48 at r1](https://reviewable.io/reviews/vaadin/flow/4150#-LD5GwiE7t_dASe4-1iE:-LD5N4dx8hLCUMFwvZmN:be8vtws) ([raw file](https://github.com/vaadin/flow/blob/ded230fc728bd75e64d280e7a0b2f64493dbe184/flow/pom.xml#L48)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

We have tons of warnings. I meant that the comment should be about ignoring the warnings not the errors as errors for failing links should fail the build.
</blockquote></details>

Done.

I removed it completely since there were no errors now, unlike last night on my home laptop (windows). 

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4150)*

**Comment by pleku** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[flow/pom.xml, line 48 at r1](https://reviewable.io/reviews/vaadin/flow/4150#-LD5GwiE7t_dASe4-1iE:-LD5PVtE5kS9_mrjTtWX:b-j6pxmb) ([raw file](https://github.com/vaadin/flow/blob/ded230fc728bd75e64d280e7a0b2f64493dbe184/flow/pom.xml#L48)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Done.

I removed it completely since there were no errors now, unlike last night on my home laptop (windows). 
</blockquote></details>

Still fails when built from parent, adjusted comment.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4150)*

**Comment by caalador** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4150#-:-LD5Rg481lLmWqoBG3T0:bnfp4nl)*

**Comment by pleku** [comment]
This approach won't work since there are no sources for the `flow` artifact, thus platform won't still aggregate proper javadocs without sources.

**Pull request closed without merging**
