### PR TITLE
Make classes serializable

### PR DESCRIPTION
**Pull request by elmot**
Partial fix for https://github.com/vaadin/platform/issues/173
Related to #4105

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/4148)

### CODE REVIEW

**Comment by caalador** [comment]
JavaDoc fails build.

**Comment by denis-anisimov** [comment]
Reviewed 47 of 54 files at r1, 9 of 10 files at r2.
Review status: all files reviewed at latest revision, 15 unresolved discussions, some commit checks failed.

---

*[flow-server/src/main/java/com/vaadin/flow/dom/ElementFactory.java, line 28 at r2](https://reviewable.io/reviews/vaadin/flow/4148#-LD5Ul1WCsccwucrE2ym:-LD5Ul1WCsccwucrE2yn:b-36fpts) ([raw file](https://github.com/vaadin/flow/blob/f480771bfef6cb4aa1311d552856ed5a4b808b87/flow-server/src/main/java/com/vaadin/flow/dom/ElementFactory.java#L28)):*
> ```
> ElementFactory 
> ```

This is a mix-in without any single instance method.
Technically it's just a util class. So doesn't have to be serializable.
But it doesn't hurt.

---

*[flow-server/src/main/java/com/vaadin/flow/dom/NodeVisitor.java, line 28 at r2](https://reviewable.io/reviews/vaadin/flow/4148#-LD5V552AcNRXoqzEEJU:-LD5V552AcNRXoqzEEJV:b-48ytkk) ([raw file](https://github.com/vaadin/flow/blob/f480771bfef6cb4aa1311d552856ed5a4b808b87/flow-server/src/main/java/com/vaadin/flow/dom/NodeVisitor.java#L28)):*
> ```
>  extends Serializable 
> ```

That may be wrong......
I'm not sure.
Visitor is not intended to be stored in any state. It's temporary logic which is applied during request handling. So it's too much to require it to be serializable.

---

*[flow-server/src/main/java/com/vaadin/flow/dom/impl/ThemeListImpl.java, line 18 at r2](https://reviewable.io/reviews/vaadin/flow/4148#-LD5VUir3Hh5-R33gpGs:-LD5VUir3Hh5-R33gpGt:b-ctyyue) ([raw file](https://github.com/vaadin/flow/blob/f480771bfef6cb4aa1311d552856ed5a4b808b87/flow-server/src/main/java/com/vaadin/flow/dom/impl/ThemeListImpl.java#L18)):*
> ```
> import java.io.Serializable;
> ```

No other changes in this class.
Is it a mistake or something is missed ?

---

*[flow-server/src/main/java/com/vaadin/flow/router/RouteNotFoundError.java, line 118 at r2](https://reviewable.io/reviews/vaadin/flow/4148#-LD5WGYWEiivwiFJJwJS:-LD5WGYWEiivwiFJJwJT:bsqr17g) ([raw file](https://github.com/vaadin/flow/blob/f480771bfef6cb4aa1311d552856ed5a4b808b87/flow-server/src/main/java/com/vaadin/flow/router/RouteNotFoundError.java#L118)):*
> ```
>         private LazyInit() {
>         }
> ```

Why ?
The class is inner private.
What's the benefit to have explicit CTOR here ?

---

*[flow-server/src/main/java/com/vaadin/flow/templatemodel/PropertyMapBuilder.java, line 131 at r2](https://reviewable.io/reviews/vaadin/flow/4148#-LD5XNN15VVjwEcEfrFI:-LD5XNN15VVjwEcEfrFJ:b-78rfs4) ([raw file](https://github.com/vaadin/flow/blob/f480771bfef6cb4aa1311d552856ed5a4b808b87/flow-server/src/main/java/com/vaadin/flow/templatemodel/PropertyMapBuilder.java#L131)):*
> ```
> SerializablePredicate<String>
> ```

This is not really needed.
This predicate is not stored anywhere. It's used only at the creation time to filter the data and then it's lost.
But it looks this filter is our own filter which we may force to be serializable.

---

*[flow-server/src/main/java/com/vaadin/flow/templatemodel/TemplateModel.java, line 188 at r2](https://reviewable.io/reviews/vaadin/flow/4148#-LD5Y6vh1-qQwQYbpFKP:-LD5Y6vh1-qQwQYbpFKQ:byp4cyp) ([raw file](https://github.com/vaadin/flow/blob/f480771bfef6cb4aa1311d552856ed5a4b808b87/flow-server/src/main/java/com/vaadin/flow/templatemodel/TemplateModel.java#L188)):*
> ```
> SerializablePredicate<String>
> ```


I would say this is a mistake here to require Serializable.
Looks like this filter is used only to filter the data during other data creation and then it's not stored anywhere.
So it's too restrictive to require serializable here.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4148)*

**Comment by elmot** [comment]
Review status: 47 of 53 files reviewed at latest revision, 19 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/dom/ElementFactory.java, line 28 at r2](https://reviewable.io/reviews/vaadin/flow/4148#-LD5Ul1WCsccwucrE2ym:-LD5n_g_CVv1C8slHT1V:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/f480771bfef6cb4aa1311d552856ed5a4b808b87/flow-server/src/main/java/com/vaadin/flow/dom/ElementFactory.java#L28)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
> ElementFactory 
> ```

This is a mix-in without any single instance method.
Technically it's just a util class. So doesn't have to be serializable.
But it doesn't hurt.
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/flow/dom/NodeVisitor.java, line 28 at r2](https://reviewable.io/reviews/vaadin/flow/4148#-LD5V552AcNRXoqzEEJU:-LD5nn6SAYkgmPoR8vaz:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/f480771bfef6cb4aa1311d552856ed5a4b808b87/flow-server/src/main/java/com/vaadin/flow/dom/NodeVisitor.java#L28)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
>  extends Serializable 
> ```

That may be wrong......
I'm not sure.
Visitor is not intended to be stored in any state. It's temporary logic which is applied during request handling. So it's too much to require it to be serializable.
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/flow/router/RouteNotFoundError.java, line 118 at r2](https://reviewable.io/reviews/vaadin/flow/4148#-LD5WGYWEiivwiFJJwJS:-LD5oTo84IAnkzoPG3Fr:b8m151i) ([raw file](https://github.com/vaadin/flow/blob/f480771bfef6cb4aa1311d552856ed5a4b808b87/flow-server/src/main/java/com/vaadin/flow/router/RouteNotFoundError.java#L118)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
>         private LazyInit() {
>         }
> ```

Why ?
The class is inner private.
What's the benefit to have explicit CTOR here ?
</blockquote></details>

Technically there is no need of the CTOR, it's added to make code self-documented.

---

*[flow-server/src/main/java/com/vaadin/flow/templatemodel/TemplateModel.java, line 188 at r2](https://reviewable.io/reviews/vaadin/flow/4148#-LD5Y6vh1-qQwQYbpFKP:-LD5pJHZAWnjdkh_HO71:b-2aqf3g) ([raw file](https://github.com/vaadin/flow/blob/f480771bfef6cb4aa1311d552856ed5a4b808b87/flow-server/src/main/java/com/vaadin/flow/templatemodel/TemplateModel.java#L188)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
> SerializablePredicate<String>
> ```


I would say this is a mistake here to require Serializable.
Looks like this filter is used only to filter the data during other data creation and then it's not stored anywhere.
So it's too restrictive to require serializable here.
</blockquote></details>

Are `PropertyFilter`s stored anywhere? If yes, then it should be made of `SerializablePredicate`s and all classes around should be serializable as well. If not, then they could be reverted back to non-serializable version

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4148)*

**Comment by denis-anisimov** [comment]
Reviewed 3 of 9 files at r3.
Review status: 50 of 53 files reviewed at latest revision, 18 unresolved discussions, some commit checks failed.

---

*[flow-server/src/main/java/com/vaadin/flow/router/RouteNotFoundError.java, line 118 at r2](https://reviewable.io/reviews/vaadin/flow/4148#-LD5WGYWEiivwiFJJwJS:-LD5y7uz7tn6CY5HgtoW:b-t9t84w) ([raw file](https://github.com/vaadin/flow/blob/f480771bfef6cb4aa1311d552856ed5a4b808b87/flow-server/src/main/java/com/vaadin/flow/router/RouteNotFoundError.java#L118)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Technically there is no need of the CTOR, it's added to make code self-documented.
</blockquote></details>

Don't see how it makes self-documented code for the class which is nested and not visible from anywhere. Extra CTOR just adds more lines and what's bad: this change has no any relation to the main purpose of the PR.

But it's minor.

---

*[flow-server/src/main/java/com/vaadin/flow/templatemodel/TemplateModel.java, line 188 at r2](https://reviewable.io/reviews/vaadin/flow/4148#-LD5Y6vh1-qQwQYbpFKP:-LD5ybi688PhkkXNe6yj:bt3w09t) ([raw file](https://github.com/vaadin/flow/blob/f480771bfef6cb4aa1311d552856ed5a4b808b87/flow-server/src/main/java/com/vaadin/flow/templatemodel/TemplateModel.java#L188)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Are `PropertyFilter`s stored anywhere? If yes, then it should be made of `SerializablePredicate`s and all classes around should be serializable as well. If not, then they could be reverted back to non-serializable version
</blockquote></details>

That's the question.
The filter is stored inside an instance of `PropertyFilter`. But the `PropertyFilter` instance is not stored anywhere. It's temporary instance.
I didn't find any code which stores this instance.
And if `PropertyFilter`  also requires serializable filter in its CTOR it also should be reverted.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4148)*

**Comment by denis-anisimov** [comment]
Reviewed 6 of 9 files at r3.
Review status: all files reviewed at latest revision, 17 unresolved discussions, some commit checks failed.

---

*[flow-server/src/test/java/com/vaadin/tests/server/ClassesSerializableTest.java, line 213 at r3](https://reviewable.io/reviews/vaadin/flow/4148#-LD5zu4f5zjKY4obKvby:-LD5zu4f5zjKY4obKvbz:bd04nfq) ([raw file](https://github.com/vaadin/flow/blob/2b002fc83ade2d07732a865b82ca24f2efb7564a/flow-server/src/test/java/com/vaadin/tests/server/ClassesSerializableTest.java#L213)):*
> ```
> test
> ```

useless prefix. But it's minor.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4148)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 17 unresolved discussions, some commit checks failed.

---

*[flow-server/src/main/java/com/vaadin/flow/templatemodel/TemplateModel.java, line 188 at r2](https://reviewable.io/reviews/vaadin/flow/4148#-LD5Y6vh1-qQwQYbpFKP:-LD6Wgqt3ubYEhokT8EF:bjcjtyh) ([raw file](https://github.com/vaadin/flow/blob/f480771bfef6cb4aa1311d552856ed5a4b808b87/flow-server/src/main/java/com/vaadin/flow/templatemodel/TemplateModel.java#L188)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Ok, I am reverting both.
</blockquote></details>

No changes.
Not committed ?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4148)*

**Comment by denis-anisimov** [comment]
Reviewed 4 of 7 files at r4.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4148)*

**Comment by elmot** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks broke.

---

*[flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/TemplateDataAnalyzer.java, line 107 at r1](https://reviewable.io/reviews/vaadin/flow/4148#-LD26jwZzg2ZYAK-OQZY-r1-107:-LD6N5QH0l93NHmIRvej:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/2605c442800ae7d1d32a5a9e2c7fad6441670740/flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/TemplateDataAnalyzer.java#L107)):*
> ```Java
> 
>         private final Map<String, String> tagById;
>         private final Map<Field, String> idByField;
> ```

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4148)*

**Comment by elmot** [comment]
Review status: 42 of 48 files reviewed at latest revision, 5 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/dom/impl/ThemeListImpl.java, line 18 at r2](https://reviewable.io/reviews/vaadin/flow/4148#-LD5VUir3Hh5-R33gpGs:-LDB5CG4-hFdWsHXQuZc:b-c0sunc) ([raw file](https://github.com/vaadin/flow/blob/f480771bfef6cb4aa1311d552856ed5a4b808b87/flow-server/src/main/java/com/vaadin/flow/dom/impl/ThemeListImpl.java#L18)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
> import java.io.Serializable;
> ```

No other changes in this class.
Is it a mistake or something is missed ?
</blockquote></details>

Done. Now there are changes

---

*[flow-server/src/main/java/com/vaadin/flow/router/RouteNotFoundError.java, line 118 at r2](https://reviewable.io/reviews/vaadin/flow/4148#-LD5WGYWEiivwiFJJwJS:-LDB5w_s40_DnrWXabB_:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/f480771bfef6cb4aa1311d552856ed5a4b808b87/flow-server/src/main/java/com/vaadin/flow/router/RouteNotFoundError.java#L118)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Don't see how it makes self-documented code for the class which is nested and not visible from anywhere. Extra CTOR just adds more lines and what's bad: this change has no any relation to the main purpose of the PR.

But it's minor.
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/flow/templatemodel/PropertyMapBuilder.java, line 131 at r2](https://reviewable.io/reviews/vaadin/flow/4148#-LD5XNN15VVjwEcEfrFI:-LDB63Yk5jijW5uV5gGh:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/f480771bfef6cb4aa1311d552856ed5a4b808b87/flow-server/src/main/java/com/vaadin/flow/templatemodel/PropertyMapBuilder.java#L131)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
> SerializablePredicate<String>
> ```

This is not really needed.
This predicate is not stored anywhere. It's used only at the creation time to filter the data and then it's lost.
But it looks this filter is our own filter which we may force to be serializable.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4148)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 8 files at r4, 1 of 3 files at r5, 7 of 10 files at r6.
Review status: all files reviewed at latest revision, 27 unresolved discussions, some commit checks broke.

---

*[flow-test-generic/pom.xml, line 22 at r6](https://reviewable.io/reviews/vaadin/flow/4148#-LDBQjhA8YAAjPdKlOF8:-LDBQjhA8YAAjPdKlOF9:b-d0wxhj) ([raw file](https://github.com/vaadin/flow/blob/865a6e5022895bc8f76efe1c659f64759c47b856/flow-test-generic/pom.xml#L22)):*
> ```XML
> 
> 
> </project>
> ```

new line

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4148)*

**Comment by elmot** [comment]
Review status: 47 of 49 files reviewed at latest revision, 28 unresolved discussions.

---

*[flow-test-generic/pom.xml, line 22 at r6](https://reviewable.io/reviews/vaadin/flow/4148#-LDBQjhA8YAAjPdKlOF8:-LDBSPvN-1DRzL93P8Ge:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/865a6e5022895bc8f76efe1c659f64759c47b856/flow-test-generic/pom.xml#L22)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

new line
</blockquote></details>

Done.

---

*[flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java, line 36 at r6](https://reviewable.io/reviews/vaadin/flow/4148#-LDB6tR9veBv6EVm7kuq-r6-36:-LDBSRq7-zv4xrenuuky:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/865a6e5022895bc8f76efe1c659f64759c47b856/flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java#L36)):*
<details><summary><i>Previously, vaadin-bot (Vaadin Bot) wrote…</i></summary><blockquote>

CRITICAL Document this public class by adding an explicit description. [rule](https://sonar.projects.vaadin.com/coding_rules#rule_key=squid%3AUndocumentedApi)
</blockquote></details>

Done.

---

*[flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java, line 117 at r6](https://reviewable.io/reviews/vaadin/flow/4148#-LDB6tR9veBv6EVm7kuq-r6-117:-LDBSUGK18QjEPXK5739:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/865a6e5022895bc8f76efe1c659f64759c47b856/flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java#L117)):*
<details><summary><i>Previously, vaadin-bot (Vaadin Bot) wrote…</i></summary><blockquote>

MINOR Remove this empty statement. [rule](https://sonar.projects.vaadin.com/coding_rules#rule_key=squid%3AEmptyStatementUsageCheck)
</blockquote></details>

Done.

---

*[flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java, line 119 at r6](https://reviewable.io/reviews/vaadin/flow/4148#-LDB6tR9veBv6EVm7kuq-r6-119:-LDBSxaq2nyBK5KGUYod:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/865a6e5022895bc8f76efe1c659f64759c47b856/flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java#L119)):*
<details><summary><i>Previously, vaadin-bot (Vaadin Bot) wrote…</i></summary><blockquote>

CRITICAL Document this public method by adding an explicit description. [rule](https://sonar.projects.vaadin.com/coding_rules#rule_key=squid%3AUndocumentedApi)
MAJOR Refactor this method to throw at most one checked exception instead of: java.io.IOException, java.lang.ClassNotFoundException [rule](https://sonar.projects.vaadin.com/coding_rules#rule_key=squid%3AS1160)

</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4148)*

**Comment by denis-anisimov** [comment]
Reviewed 2 of 3 files at r7.
Review status: all files reviewed at latest revision, 27 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4148)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 2 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java, line 315 at r9](https://reviewable.io/reviews/vaadin/flow/4148#-LDFeuc_CtgAU67cxhQk:-LDFeuc_CtgAU67cxhQl:b-83yvw2) ([raw file](https://github.com/vaadin/flow/blob/3e696507d9a72ef44147d6ccf61c6ca4b06822eb/flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java#L315)):*
> ```
> if (iface == Runnable.class || iface == Comparator.class) {
> ```

So if I implement a `Runnable` or `Comparator` class myself  which is a real class it will be skipped?

I think it should check something `isAnonymousClass()` or `isSynthetic()` or whatever.

And `isSkippable` is a bad name. It should say why it may be ignored (or just `canIgnore` ).

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4148)*

**Comment by elmot** [comment]
Review status: 48 of 49 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java, line 315 at r9](https://reviewable.io/reviews/vaadin/flow/4148#-LDFeuc_CtgAU67cxhQk:-LDG8TlaA_A9SzPV1DmT:bv3edbd) ([raw file](https://github.com/vaadin/flow/blob/3e696507d9a72ef44147d6ccf61c6ca4b06822eb/flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java#L315)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
> if (iface == Runnable.class || iface == Comparator.class) {
> ```

So if I implement a `Runnable` or `Comparator` class myself  which is a real class it will be skipped?

I think it should check something `isAnonymousClass()` or `isSynthetic()` or whatever.

And `isSkippable` is a bad name. It should say why it may be ignored (or just `canIgnore` ).
</blockquote></details>

I also had some concerns about this code. Removed.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4148)*

**Comment by elmot** [comment]
Review status: 48 of 49 files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java, line 148 at r10](https://reviewable.io/reviews/vaadin/flow/4148#-LDGCDqg1Q3BG3ukb7hH:-LDGCDqg1Q3BG3ukb7hI:b-tf31r3) ([raw file](https://github.com/vaadin/flow/blob/2516547e57ad2f86866d159663cf49352c73deea/flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java#L148)):*
> ```
> serializeAndDeserialize
> ```

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4148)*

**Comment by denis-anisimov** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r11.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4148#-:-LDGMssdCxQURH_lFY1e:bnfp4nl)*

**Pull request merged**
