### PR TITLE
Update Copyright Header

### PR DESCRIPTION
**Pull request by ZheSun88**

### CODE REVIEW

**Comment by denis-anisimov** [comment]
You should update SQ rules related to the header.

**Comment by ZheSun88** [comment]
@denis-anisimov SonarQube rule has been changed. How about the left sonar issues? Can we ignore it somehow?

**Comment by ZheSun88** [comment]
@SomeoneToIgnore Yes, i think so. Found some more `*.java` files. will make another commit on that, Thanks.

**Comment by denis-anisimov** [comment]
If you make a new commit SQ will rerun.
In any case you may go to the settings and disable SQ for a while

**Pull request merged**
