### PR TITLE
Don't set the cache inside gridConnector

### PR DESCRIPTION
**Pull request by denis-anisimov**
Don't update the cache manually with the new items inside gridConnector.

The `_getItem` method of `vaadin-grid` calls `_loadPage` asynchronously.
So it's postponed. And its work relies on emptiness of the cache for the page.
If we set the cache right away then `loadPage` logic is never executed (which is bad generally) 
and this logic actually updates `_loading` property (to `false`).
The latter method updates the cache with the correct values (but it's postponed).

Fix for #2813.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/2856)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
We are using internal API and internal properties of `Grid` so I'm not sure whether it's a proper fix (and I have no idea a proper fix with the current approach).

**Comment by ahie** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-components-parent/flow-components/src/main/resources/META-INF/resources/gridConnector.js, line 84 at r1](https://reviewable.io:443/reviews/vaadin/flow/2856#-KyGFJ1wmwr6XpqIOmt1:-KyGFJ1wmwr6XpqIOmt2:bc5a8u5) ([raw file](https://github.com/vaadin/flow/blob/dbde56101ee2365e4cc04cdb9a46eebb216805a0/flow-components-parent/flow-components/src/main/resources/META-INF/resources/gridConnector.js#L84)):*
> // setTimeout to avoid race condition in ServerRpcQueue

This comment should be removed since it is no longer relevant.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2856)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-components-parent/flow-components/src/main/resources/META-INF/resources/gridConnector.js, line 84 at r1](https://reviewable.io:443/reviews/vaadin/flow/2856#-KyGFJ1wmwr6XpqIOmt1:-KyGGICUnVvJQ1f21fzn:b7t8ghd) ([raw file](https://github.com/vaadin/flow/blob/dbde56101ee2365e4cc04cdb9a46eebb216805a0/flow-components-parent/flow-components/src/main/resources/META-INF/resources/gridConnector.js#L84)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

> // setTimeout to avoid race condition in ServerRpcQueue

This comment should be removed since it is no longer relevant.
</blockquote></details>

Right.

Though there was no intention to update this part of the code at all :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2856)*

**Comment by denis-anisimov** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-components-parent/flow-components/src/main/resources/META-INF/resources/gridConnector.js, line 84 at r1](https://reviewable.io:443/reviews/vaadin/flow/2856#-KyGFJ1wmwr6XpqIOmt1:-KyGGgwesy7YHUAAABkZ:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/dbde56101ee2365e4cc04cdb9a46eebb216805a0/flow-components-parent/flow-components/src/main/resources/META-INF/resources/gridConnector.js#L84)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Right.

Though there was no intention to update this part of the code at all :)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2856)*

**Comment by ahie** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2856)*

**Pull request merged**
