### PR TITLE
Handle ES5 hash names

### PR DESCRIPTION
**Pull request by manolo**
Fixes: #3974

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3976)

### CODE REVIEW

**Comment by Artur-** [comment]
Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---

*[flow-server/src/main/java/com/vaadin/flow/server/startup/BundleDependencyFilter.java, line 73 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3976#-LAnb2vKEg9zT3EDrp1P:-LAnb2vKEg9zT3EDrp1Q:b-azr561) ([raw file](https://github.com/vaadin/flow/blob/138485e671e5ecd3aa867a74aa663afefdfd9b73/flow-server/src/main/java/com/vaadin/flow/server/startup/BundleDependencyFilter.java#L73)):*
> ```Java
>             FilterContext filterContext) {
> 
>         VaadinSession session = VaadinSession.getCurrent();
> ```

Do not use `getCurrent`, it only causes problems in the long run. If  the filter depends on `VaadinSession`, add it back to `FilterContext` where it used to be but ensure somehow that it is never used in filter intialization, which I think also uses the same `FilterContext`. 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3976)*

**Comment by SomeoneToIgnore** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-server/src/main/java/com/vaadin/flow/server/startup/BundleDependencyFilter.java, line 49 at r1](https://reviewable.io/reviews/vaadin/flow/3976#-LAq6vw-03geL7RauGsH:-LAq6vw-03geL7RauGsI:bwk096y) ([raw file](https://github.com/vaadin/flow/blob/138485e671e5ecd3aa867a74aa663afefdfd9b73/flow-server/src/main/java/com/vaadin/flow/server/startup/BundleDependencyFilter.java#L49)):*
> ```Java
>     /**
>      * Creates a filter with the required information.
>      * @param browser
> ```

Optional: your javadoc is not properly formatted, but up to you if you want to fix this one.

---

*[flow-server/src/main/java/com/vaadin/flow/server/startup/BundleDependencyFilter.java, line 59 at r1](https://reviewable.io/reviews/vaadin/flow/3976#-LAq72OXEZyYYP2SvBz5:-LAq72OXEZyYYP2SvBz6:b-3ce3pv) ([raw file](https://github.com/vaadin/flow/blob/138485e671e5ecd3aa867a74aa663afefdfd9b73/flow-server/src/main/java/com/vaadin/flow/server/startup/BundleDependencyFilter.java#L59)):*
> ```
> WebBrowser browser
> ```

Optional: not really sure why do you need the whole `WebBrowser` instance here, since you only store `es6` flag from it, I would have used a `boolean` parameter instead. But up to you.

---

*[flow-server/src/main/java/com/vaadin/flow/server/startup/BundleFilterInitializer.java, line 64 at r1](https://reviewable.io/reviews/vaadin/flow/3976#-LAq7Rud2BLajLIillRp:-LAq7Rud2BLajLIillRq:b9gkgxq) ([raw file](https://github.com/vaadin/flow/blob/138485e671e5ecd3aa867a74aa663afefdfd9b73/flow-server/src/main/java/com/vaadin/flow/server/startup/BundleFilterInitializer.java#L64)):*
> ```Java
>                 .ifPresent(event::addDependencyFilter);
> 
>         readBundleManifest(FakeBrowser.getEs5(), service).flatMap(
> ```

Optional: looks like a copy paste, the only thing that's different here is the browser, can be extracted into a method, up to you to change.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/3976)*

**Comment by manolo** [comment]
Since I'm not familiar with testing this stuff, it's taking a while, is it ok to add the test in separated PR?

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-server/src/main/java/com/vaadin/flow/server/startup/BundleDependencyFilter.java, line 49 at r1](https://reviewable.io/reviews/vaadin/flow/3976#-LAq6vw-03geL7RauGsH:-LAq_JQtCjhcMXxOuPxs:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/138485e671e5ecd3aa867a74aa663afefdfd9b73/flow-server/src/main/java/com/vaadin/flow/server/startup/BundleDependencyFilter.java#L49)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Optional: your javadoc is not properly formatted, but up to you if you want to fix this one.
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/flow/server/startup/BundleDependencyFilter.java, line 59 at r1](https://reviewable.io/reviews/vaadin/flow/3976#-LAq72OXEZyYYP2SvBz5:-LAq_Lh89rvF5hEUhJCE:b-d7yeyx) ([raw file](https://github.com/vaadin/flow/blob/138485e671e5ecd3aa867a74aa663afefdfd9b73/flow-server/src/main/java/com/vaadin/flow/server/startup/BundleDependencyFilter.java#L59)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

> ```
> WebBrowser browser
> ```

Optional: not really sure why do you need the whole `WebBrowser` instance here, since you only store `es6` flag from it, I would have used a `boolean` parameter instead. But up to you.
</blockquote></details>

I do prefer the meaningful object as argument than a boolean because makes the constructor more readable

---

*[flow-server/src/main/java/com/vaadin/flow/server/startup/BundleDependencyFilter.java, line 73 at r1](https://reviewable.io/reviews/vaadin/flow/3976#-LAnb2vKEg9zT3EDrp1P:-LAq_jfb34m2W2KSrvyo:b1l4o0f) ([raw file](https://github.com/vaadin/flow/blob/138485e671e5ecd3aa867a74aa663afefdfd9b73/flow-server/src/main/java/com/vaadin/flow/server/startup/BundleDependencyFilter.java#L73)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Do not use `getCurrent`, it only causes problems in the long run. If  the filter depends on `VaadinSession`, add it back to `FilterContext` where it used to be but ensure somehow that it is never used in filter intialization, which I think also uses the same `FilterContext`. 
</blockquote></details>

Adding back the `VaadinSession` to the `FilterContext` makes that in `DefaultTemplateParser` we need  `VaadinSession.getCurrent` again. 

`FilterContext` is only used in `DefaultTempateParser.getTemplateContent` and  in `UidWritter.populateDependencies`, during filter initialisation is not needed.

---

*[flow-server/src/main/java/com/vaadin/flow/server/startup/BundleFilterInitializer.java, line 64 at r1](https://reviewable.io/reviews/vaadin/flow/3976#-LAq7Rud2BLajLIillRp:-LAqbDiLDYFqyT3cP9ef:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/138485e671e5ecd3aa867a74aa663afefdfd9b73/flow-server/src/main/java/com/vaadin/flow/server/startup/BundleFilterInitializer.java#L64)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Optional: looks like a copy paste, the only thing that's different here is the browser, can be extracted into a method, up to you to change.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/3976#-:-LAqZz6o2IjRu-Cknss4:bs7mstq)*

**Comment by manolo** [comment]
Review status: 3 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-server/src/main/java/com/vaadin/flow/server/startup/BundleDependencyFilter.java, line 73 at r1](https://reviewable.io/reviews/vaadin/flow/3976#-LAnb2vKEg9zT3EDrp1P:-LAqf9987OTdHNA4fEjk:brllu1o) ([raw file](https://github.com/vaadin/flow/blob/138485e671e5ecd3aa867a74aa663afefdfd9b73/flow-server/src/main/java/com/vaadin/flow/server/startup/BundleDependencyFilter.java#L73)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Adding back the `VaadinSession` to the `FilterContext` makes that in `DefaultTemplateParser` we need  `VaadinSession.getCurrent` again. 

`FilterContext` is only used in `DefaultTempateParser.getTemplateContent` and  in `UidWritter.populateDependencies`, during filter initialisation is not needed.
</blockquote></details>

Passing browser info in filter context instead.

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/3976)*

**Comment by SomeoneToIgnore** [comment]
Ok.

---

Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/3976#-:-LAqfcfH75ohG09UV7PG:b2nhll9)*

**Comment by SomeoneToIgnore** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/3976#-:-LArbQ1m2SLMj-rPnQTq:bnfp4nl)*

**Pull request merged**
