### PR TITLE
Add AbstractSinglePropertyField

### PR DESCRIPTION
**Pull request by Legioth**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3997)

### CODE REVIEW

**Comment by gilberto-torrezan** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks broke.

---

*[flow-data/src/main/java/com/vaadin/flow/data/value/ValueChangeMode.java, line 60 at r1](https://reviewable.io/reviews/vaadin/flow/3997#-LAwXsR3ESH_xTX1Z5iR:-LAwXsR3ESH_xTX1Z5iS:b-u2g51r) ([raw file](https://github.com/vaadin/flow/blob/d683123bec535d8c5e22b209642ecc15bce2864f/flow-data/src/main/java/com/vaadin/flow/data/value/ValueChangeMode.java#L60)):*
> ```
>      * Gets the name of the event associated with the given mode. If the mode is
>      * {@link #EAGER}, then the provided eager event name is returned. If the
>      * mode is <code>null</code>, then null is returned.
> ```


Probably should swap the order of the `If the mode is EAGER, then the provided eager event name is returned.` and `If the mode is null, then null is returned. ` sentences, to make it clear which case has precedence over the other.

---

*[flow-data/src/main/java/com/vaadin/flow/data/value/ValueChangeMode.java, line 71 at r1](https://reviewable.io/reviews/vaadin/flow/3997#-LAwYbS_Cz3vzpYfIZBk:-LAwYbS_Cz3vzpYfIZBl:b-s036hu) ([raw file](https://github.com/vaadin/flow/blob/d683123bec535d8c5e22b209642ecc15bce2864f/flow-data/src/main/java/com/vaadin/flow/data/value/ValueChangeMode.java#L71)):*
> ```Java
>      * @return the event name
>      */
>     public static String eventForMode(ValueChangeMode mode,
> ```

On a second thought, wouldn't it be better to make it a instance method instead of a static method? `ValueChangeMode.ON_BLUR.getEventName("foo")` would return `blur`, for instance.

---

*[flow-server/src/main/java/com/vaadin/flow/component/AbstractSinglePropertyField.java, line 63 at r1](https://reviewable.io/reviews/vaadin/flow/3997#-LAwZOpf07lMf9DuP1xw:-LAwZOpf07lMf9DuP1xx:b-alxmv5) ([raw file](https://github.com/vaadin/flow/blob/d683123bec535d8c5e22b209642ecc15bce2864f/flow-server/src/main/java/com/vaadin/flow/component/AbstractSinglePropertyField.java#L63)):*
> ```Java
> 
>     /**
>      * Encapsulates all everything related to reading and writing element
> ```

`all everything` -> just `everything`

---

*[flow-server/src/test/java/com/vaadin/flow/component/AbstractSinglePropertyFieldTest.java, line 74 at r1](https://reviewable.io/reviews/vaadin/flow/3997#-LAw_PXN2u2ysjOqI6gh:-LAw_PXN2u2ysjOqI6gi:b-isezc3) ([raw file](https://github.com/vaadin/flow/blob/d683123bec535d8c5e22b209642ecc15bce2864f/flow-server/src/test/java/com/vaadin/flow/component/AbstractSinglePropertyFieldTest.java#L74)):*
> ```Java
>     }
> 
>     @Test(expected = NullPointerException.class)
> ```

This can potentially test the exception in the wrong place (which can happen pretty easily considering NPE).  I suggest using `@Rule ExpectedException`  instead.

---

*[flow-server/src/test/java/com/vaadin/flow/component/ValueChangeMonitor.java, line 45 at r1](https://reviewable.io/reviews/vaadin/flow/3997#-LAwaFvx0xaeaDBnbyt-:-LAwaFvx0xaeaDBnbyt0:b-vtb8de) ([raw file](https://github.com/vaadin/flow/blob/d683123bec535d8c5e22b209642ecc15bce2864f/flow-server/src/test/java/com/vaadin/flow/component/ValueChangeMonitor.java#L45)):*
> ```Java
>     public void assertEvent(boolean fromClient, T oldValue, T newValue) {
>         Assert.assertNotNull("There should be an event", capturedEvent);
>         Assert.assertTrue(fromClient == capturedEvent.isFromClient());
> ```

Why not `assertEquals(fromClient, capturedEvent.isFromClient())` ?

---

*[flow-server/src/test/java/com/vaadin/flow/component/ValueChangeMonitor.java, line 61 at r1](https://reviewable.io/reviews/vaadin/flow/3997#-LAwaP6-C8HJFh9bXGTG:-LAwaP6-C8HJFh9bXGTH:bdngjkw) ([raw file](https://github.com/vaadin/flow/blob/d683123bec535d8c5e22b209642ecc15bce2864f/flow-server/src/test/java/com/vaadin/flow/component/ValueChangeMonitor.java#L61)):*
> ```Java
>         Assert.assertEquals(newValue, event.getValue());
>     }
> }
> ```

New Line Cinema Corporation

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/3997)*

**Comment by Legioth** [comment]
Review status: all files reviewed at latest revision, 15 unresolved discussions, some commit checks broke.

---

*[flow-data/src/main/java/com/vaadin/flow/data/value/ValueChangeMode.java, line 60 at r1](https://reviewable.io/reviews/vaadin/flow/3997#-LAwXsR3ESH_xTX1Z5iR:-LAwc12rB22bCxmOZYe1:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/d683123bec535d8c5e22b209642ecc15bce2864f/flow-data/src/main/java/com/vaadin/flow/data/value/ValueChangeMode.java#L60)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

> ```
>      * Gets the name of the event associated with the given mode. If the mode is
>      * {@link #EAGER}, then the provided eager event name is returned. If the
>      * mode is <code>null</code>, then null is returned.
> ```


Probably should swap the order of the `If the mode is EAGER, then the provided eager event name is returned.` and `If the mode is null, then null is returned. ` sentences, to make it clear which case has precedence over the other.
</blockquote></details>

Done.

---

*[flow-data/src/main/java/com/vaadin/flow/data/value/ValueChangeMode.java, line 71 at r1](https://reviewable.io/reviews/vaadin/flow/3997#-LAwYbS_Cz3vzpYfIZBk:-LAwc1_NCXm94Jh8-u-R:b-7zex4o) ([raw file](https://github.com/vaadin/flow/blob/d683123bec535d8c5e22b209642ecc15bce2864f/flow-data/src/main/java/com/vaadin/flow/data/value/ValueChangeMode.java#L71)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

On a second thought, wouldn't it be better to make it a instance method instead of a static method? `ValueChangeMode.ON_BLUR.getEventName("foo")` would return `blur`, for instance.
</blockquote></details>

The problem is that `null.getEventName("foo")` doesn't return `null`.

---

*[flow-server/src/main/java/com/vaadin/flow/component/AbstractSinglePropertyField.java, line 63 at r1](https://reviewable.io/reviews/vaadin/flow/3997#-LAwZOpf07lMf9DuP1xw:-LAwcJQs6pHLPp5WbsxP:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/d683123bec535d8c5e22b209642ecc15bce2864f/flow-server/src/main/java/com/vaadin/flow/component/AbstractSinglePropertyField.java#L63)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

`all everything` -> just `everything`
</blockquote></details>

Done.

---

*[flow-server/src/test/java/com/vaadin/flow/component/AbstractSinglePropertyFieldTest.java, line 74 at r1](https://reviewable.io/reviews/vaadin/flow/3997#-LAw_PXN2u2ysjOqI6gh:-LAwdITLEzkj4aZ9bOYQ:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/d683123bec535d8c5e22b209642ecc15bce2864f/flow-server/src/test/java/com/vaadin/flow/component/AbstractSinglePropertyFieldTest.java#L74)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

This can potentially test the exception in the wrong place (which can happen pretty easily considering NPE).  I suggest using `@Rule ExpectedException`  instead.
</blockquote></details>

Done.

---

*[flow-server/src/test/java/com/vaadin/flow/component/ValueChangeMonitor.java, line 45 at r1](https://reviewable.io/reviews/vaadin/flow/3997#-LAwaFvx0xaeaDBnbyt-:-LAwdTst07wHzx2ph2xi:baf96o5) ([raw file](https://github.com/vaadin/flow/blob/d683123bec535d8c5e22b209642ecc15bce2864f/flow-server/src/test/java/com/vaadin/flow/component/ValueChangeMonitor.java#L45)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Why not `assertEquals(fromClient, capturedEvent.isFromClient())` ?
</blockquote></details>

There is no such overload.

---

*[flow-server/src/test/java/com/vaadin/flow/component/ValueChangeMonitor.java, line 61 at r1](https://reviewable.io/reviews/vaadin/flow/3997#-LAwaP6-C8HJFh9bXGTG:-LAwdaQOClKwraNbwl4D:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/d683123bec535d8c5e22b209642ecc15bce2864f/flow-server/src/test/java/com/vaadin/flow/component/ValueChangeMonitor.java#L61)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

New Line Cinema Corporation
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/3997)*

**Comment by gilberto-torrezan** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[flow-server/src/test/java/com/vaadin/flow/component/ValueChangeMonitor.java, line 45 at r1](https://reviewable.io/reviews/vaadin/flow/3997#-LAwaFvx0xaeaDBnbyt-:-LAwffzf5whWCTHF7Ort:b-eo13f3) ([raw file](https://github.com/vaadin/flow/blob/d683123bec535d8c5e22b209642ecc15bce2864f/flow-server/src/test/java/com/vaadin/flow/component/ValueChangeMonitor.java#L45)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

There is no such overload.
</blockquote></details>

That is strange 0o.
Ok.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/3997)*

**Comment by gilberto-torrezan** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/3997#-:-LAwg8OV8At166q40adN:bnfp4nl)*

**Pull request merged**
