### PR TITLE
Make possible to use RouteAlias annotation along with Route

### PR DESCRIPTION
**Pull request by denis-anisimov**
Fix for #2741

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/2888)

### CODE REVIEW

**Comment by caalador** [comment]
JavaDoc exception:

[07:03:30][Step 6/7] [ERROR] /opt/agent/work/cb794c0c39c9072d/flow-server/src/main/java/com/vaadin/router/RouteAlias.java:33: error: syntax error in reference
[07:03:30][Step 6/7] [ERROR] * declared by the {@link @Route #Route} annotation. Component has to have at
[07:03:30][Step 6/7] [ERROR] ^
[07:03:30][Step 6/7] [ERROR] /opt/agent/work/cb794c0c39c9072d/flow-server/src/main/java/com/vaadin/router/RouteAlias.java:34: error: syntax error in reference
[07:03:30][Step 6/7] [ERROR] * least one {@link @Route #Route} annotation which is considered as a primary
[07:03:30][Step 6/7] [ERROR] ^

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2888#-:-KyZlaJJIuYZ3Ht_ZLJy:bsg6h3t)*

**Comment by denis-anisimov** [comment]
Thanks.

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2888#-:-KyZsYuC84-nqbfuG-CN:b-ucfkn4)*

**Comment by torok-peter** [comment]
Reviewed 18 of 18 files at r1.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/router/InternalContainerAnnotationForRoute.java, line 29 at r1](https://reviewable.io:443/reviews/vaadin/flow/2888#-Ky_-FyZiKXv3qFo8I8x:-Ky_-FyZiKXv3qFo8I8y:b-6ovqq3) ([raw file](https://github.com/vaadin/flow/blob/b0c798ba181f46ff1cfc806c71f18e3a31a91e1f/flow-server/src/main/java/com/vaadin/router/InternalContainerAnnotationForRoute.java#L29)):*
> <b>NOT meant to be used _directly_</b>

---

*[flow-server/src/main/java/com/vaadin/router/RouteAlias.java, line 32 at r1](https://reviewable.io:443/reviews/vaadin/flow/2888#-Ky_-ex2RrHDDZWb5iEU:-Ky_-ex2RrHDDZWb5iEV:b-wcsab8) ([raw file](https://github.com/vaadin/flow/blob/b0c798ba181f46ff1cfc806c71f18e3a31a91e1f/flow-server/src/main/java/com/vaadin/router/RouteAlias.java#L32)):*
> allows _declaring_

or 

> allows _one_ to declare

---

*[flow-server/src/main/java/com/vaadin/router/RouteAlias.java, line 33 at r1](https://reviewable.io:443/reviews/vaadin/flow/2888#-Ky_-vhPudwiMvj-az-a:-Ky_-vhPudwiMvj-az-b:bx3d99d) ([raw file](https://github.com/vaadin/flow/blob/b0c798ba181f46ff1cfc806c71f18e3a31a91e1f/flow-server/src/main/java/com/vaadin/router/RouteAlias.java#L33)):*
> _The component_

---

*[flow-server/src/main/java/com/vaadin/router/RouteAlias.java, line 39 at r1](https://reviewable.io:443/reviews/vaadin/flow/2888#-Ky_09vST_-M0F_JW78_:-Ky_09vST_-M0F_JW78a:b-9zdhqy) ([raw file](https://github.com/vaadin/flow/blob/b0c798ba181f46ff1cfc806c71f18e3a31a91e1f/flow-server/src/main/java/com/vaadin/router/RouteAlias.java#L39)):*
Could be simplified as 

> This annotation can be used multiple times on the same class.

---

*[flow-server/src/main/java/com/vaadin/router/RouteAlias.java, line 69 at r1](https://reviewable.io:443/reviews/vaadin/flow/2888#-Ky_-VJPm959lAxVgL7T:-Ky_-VJPm959lAxVgL7U:bfjr5qj) ([raw file](https://github.com/vaadin/flow/blob/b0c798ba181f46ff1cfc806c71f18e3a31a91e1f/flow-server/src/main/java/com/vaadin/router/RouteAlias.java#L69)):*
> ```Java
> 
>     /**
>      * Have the rout chain break on defined class and not take into notice any
> ```

typo: rout

---

*[flow-server/src/main/java/com/vaadin/server/startup/RouteRegistry.java, line 35 at r1](https://reviewable.io:443/reviews/vaadin/flow/2888#-Ky_0wW6hM8CvY0uO_6E:-Ky_0wW6hM8CvY0uO_6F:b-z1ctg1) ([raw file](https://github.com/vaadin/flow/blob/b0c798ba181f46ff1cfc806c71f18e3a31a91e1f/flow-server/src/main/java/com/vaadin/server/startup/RouteRegistry.java#L35)):*
> ```Java
> import java.util.stream.Collectors;
> 
> import javax.servlet.ServletContext;
> ```

`javax` should be before `java` as per https://github.com/vaadin/flow/issues/1867 - please fix your IDE's import ordering configuration

---

*[flow-server/src/main/java/com/vaadin/server/startup/RouteRegistry.java, line 375 at r1](https://reviewable.io:443/reviews/vaadin/flow/2888#-Ky_56DTtU-vV0ekZwD4:-Ky_56DTtU-vV0ekZwD5:b-3r0jp6) ([raw file](https://github.com/vaadin/flow/blob/f6c42d66e134049b8d8c56b222ab39d7fc015070/flow-server/src/main/java/com/vaadin/server/startup/RouteRegistry.java#L375)):*
> ```Java
>                 navigationTargetMap.put(route,
>                         new RouteTarget(navigationTarget));
>             }
> ```

Where did this 7 lines of code go? I can't see it now.

---

*[flow-server/src/main/java/com/vaadin/server/startup/RouteRegistryInitializer.java, line 19 at r1](https://reviewable.io:443/reviews/vaadin/flow/2888#-Ky_2bO7sodUzr9hGTxz:-Ky_2bO7sodUzr9hGTy-:b-76zh6e) ([raw file](https://github.com/vaadin/flow/blob/b0c798ba181f46ff1cfc806c71f18e3a31a91e1f/flow-server/src/main/java/com/vaadin/server/startup/RouteRegistryInitializer.java#L19)):*
> ```Java
> 
> import java.util.Collections;
> import java.util.Set;
> ```

import ordering

---

*[flow-server/src/test/java/com/vaadin/flow/dom/ElementTest.java, line 49 at r1](https://reviewable.io:443/reviews/vaadin/flow/2888#-Ky_2xLV4CL-D-FvAe-x:-Ky_2xLV4CL-D-FvAe-y:b-m1ic55) ([raw file](https://github.com/vaadin/flow/blob/b0c798ba181f46ff1cfc806c71f18e3a31a91e1f/flow-server/src/test/java/com/vaadin/flow/dom/ElementTest.java#L49)):*
> ```Java
> import net.jcip.annotations.NotThreadSafe;
> 
> @NotThreadSafe
> ```

What's the point - will it prevent running test methods in parallel, or ...?

---

*[flow-server/src/test/java/com/vaadin/router/RouterTest.java, line 21 at r1](https://reviewable.io:443/reviews/vaadin/flow/2888#-Ky_3JxVsQpwwSIv9n9-:-Ky_3JxVsQpwwSIv9n90:b-76zh6e) ([raw file](https://github.com/vaadin/flow/blob/b0c798ba181f46ff1cfc806c71f18e3a31a91e1f/flow-server/src/test/java/com/vaadin/router/RouterTest.java#L21)):*
> ```Java
> import static org.hamcrest.CoreMatchers.startsWith;
> import static org.junit.Assert.assertThat;
> import static org.junit.Assert.fail;
> ```

import ordering

---

*[flow-server/src/test/java/com/vaadin/server/startup/CustomElementRegistryInitializerTest.java, line 26 at r1](https://reviewable.io:443/reviews/vaadin/flow/2888#-Ky_3RzL4FZpdPjMcNYx:-Ky_3RzL4FZpdPjMcNYy:b-76zh6e) ([raw file](https://github.com/vaadin/flow/blob/b0c798ba181f46ff1cfc806c71f18e3a31a91e1f/flow-server/src/test/java/com/vaadin/server/startup/CustomElementRegistryInitializerTest.java#L26)):*
> ```Java
> import java.util.stream.Stream;
> 
> import javax.servlet.ServletException;
> ```

import ordering

---

*[flow-server/src/test/java/com/vaadin/server/startup/RouteRegistryInitializerTest.java, line 25 at r1](https://reviewable.io:443/reviews/vaadin/flow/2888#-Ky_3YMmi3UyhvqBe1XZ:-Ky_3YMmi3UyhvqBe1X_:b-76zh6e) ([raw file](https://github.com/vaadin/flow/blob/b0c798ba181f46ff1cfc806c71f18e3a31a91e1f/flow-server/src/test/java/com/vaadin/server/startup/RouteRegistryInitializerTest.java#L25)):*
> ```Java
> 
> import javax.servlet.ServletContext;
> import javax.servlet.ServletException;
> ```

import ordering

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2888)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/server/startup/RouteRegistry.java, line 35 at r1](https://reviewable.io:443/reviews/vaadin/flow/2888#-Ky_0wW6hM8CvY0uO_6E:-Ky_5qS6RNGee4HVYGCF:b-dfxys1) ([raw file](https://github.com/vaadin/flow/blob/b0c798ba181f46ff1cfc806c71f18e3a31a91e1f/flow-server/src/main/java/com/vaadin/server/startup/RouteRegistry.java#L35)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

`javax` should be before `java` as per https://github.com/vaadin/flow/issues/1867 - please fix your IDE's import ordering configuration
</blockquote></details>

I'm using standard Vaadin conventions.
Have they been updated ?

I'm pretty sure that import ordering cannot be blocking issue at all.
I don't even want to care about this exactly as I don't want to care about extra spaces in the code.

Otherwise it will be a total hell instead of writing a code.

---

*[flow-server/src/main/java/com/vaadin/server/startup/RouteRegistry.java, line 375 at r1](https://reviewable.io:443/reviews/vaadin/flow/2888#-Ky_56DTtU-vV0ekZwD4:-Ky_6JapiFTyX6lU_QW-:b-3d9d43) ([raw file](https://github.com/vaadin/flow/blob/f6c42d66e134049b8d8c56b222ab39d7fc015070/flow-server/src/main/java/com/vaadin/server/startup/RouteRegistry.java#L375)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

Where did this 7 lines of code go? I can't see it now.
</blockquote></details>

Almost nowhere.

This is duplicating code. The same is done inside `registerNavigationTargets`code.
The check which throws an exception has been moved there.

---

*[flow-server/src/main/java/com/vaadin/server/startup/RouteRegistryInitializer.java, line 19 at r1](https://reviewable.io:443/reviews/vaadin/flow/2888#-Ky_2bO7sodUzr9hGTxz:-Ky_6ZwxXin04pjzv6yJ:b-8s2cad) ([raw file](https://github.com/vaadin/flow/blob/b0c798ba181f46ff1cfc806c71f18e3a31a91e1f/flow-server/src/main/java/com/vaadin/server/startup/RouteRegistryInitializer.java#L19)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

import ordering
</blockquote></details>

Don't want to care about it.

---

*[flow-server/src/test/java/com/vaadin/flow/dom/ElementTest.java, line 49 at r1](https://reviewable.io:443/reviews/vaadin/flow/2888#-Ky_2xLV4CL-D-FvAe-x:-Ky_6cfrRHOmu9e0_ktF:b-6hpp7k) ([raw file](https://github.com/vaadin/flow/blob/b0c798ba181f46ff1cfc806c71f18e3a31a91e1f/flow-server/src/test/java/com/vaadin/flow/dom/ElementTest.java#L49)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

What's the point - will it prevent running test methods in parallel, or ...?
</blockquote></details>

Yes, it prevents tests to be executed in parallel.

---

*[flow-server/src/test/java/com/vaadin/router/RouterTest.java, line 21 at r1](https://reviewable.io:443/reviews/vaadin/flow/2888#-Ky_3JxVsQpwwSIv9n9-:-Ky_6gOYN4coYJ-ikFMH:b-8s2cad) ([raw file](https://github.com/vaadin/flow/blob/b0c798ba181f46ff1cfc806c71f18e3a31a91e1f/flow-server/src/test/java/com/vaadin/router/RouterTest.java#L21)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

import ordering
</blockquote></details>

Don't want to care about it.

---

*[flow-server/src/test/java/com/vaadin/server/startup/CustomElementRegistryInitializerTest.java, line 26 at r1](https://reviewable.io:443/reviews/vaadin/flow/2888#-Ky_3RzL4FZpdPjMcNYx:-Ky_6lwtca9oYCNtnTnB:b-8s2cad) ([raw file](https://github.com/vaadin/flow/blob/b0c798ba181f46ff1cfc806c71f18e3a31a91e1f/flow-server/src/test/java/com/vaadin/server/startup/CustomElementRegistryInitializerTest.java#L26)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

import ordering
</blockquote></details>

Don't want to care about it.

---

*[flow-server/src/test/java/com/vaadin/server/startup/RouteRegistryInitializerTest.java, line 25 at r1](https://reviewable.io:443/reviews/vaadin/flow/2888#-Ky_3YMmi3UyhvqBe1XZ:-Ky_6knXUHaci0EZtQtC:b-8s2cad) ([raw file](https://github.com/vaadin/flow/blob/b0c798ba181f46ff1cfc806c71f18e3a31a91e1f/flow-server/src/test/java/com/vaadin/server/startup/RouteRegistryInitializerTest.java#L25)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

import ordering
</blockquote></details>

Don't want to care about it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2888)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/router/InternalContainerAnnotationForRoute.java, line 29 at r1](https://reviewable.io:443/reviews/vaadin/flow/2888#-Ky_-FyZiKXv3qFo8I8x:-Ky_8VigLVhQtxP1T0fk:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/b0c798ba181f46ff1cfc806c71f18e3a31a91e1f/flow-server/src/main/java/com/vaadin/router/InternalContainerAnnotationForRoute.java#L29)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

> <b>NOT meant to be used _directly_</b>
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/router/RouteAlias.java, line 32 at r1](https://reviewable.io:443/reviews/vaadin/flow/2888#-Ky_-ex2RrHDDZWb5iEU:-Ky_8e_0owUzBhEXsuSp:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/b0c798ba181f46ff1cfc806c71f18e3a31a91e1f/flow-server/src/main/java/com/vaadin/router/RouteAlias.java#L32)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

> allows _declaring_

or 

> allows _one_ to declare
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/router/RouteAlias.java, line 33 at r1](https://reviewable.io:443/reviews/vaadin/flow/2888#-Ky_-vhPudwiMvj-az-a:-Ky_8gfVZqtsGl9YHF9F:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/b0c798ba181f46ff1cfc806c71f18e3a31a91e1f/flow-server/src/main/java/com/vaadin/router/RouteAlias.java#L33)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

> _The component_
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/router/RouteAlias.java, line 39 at r1](https://reviewable.io:443/reviews/vaadin/flow/2888#-Ky_09vST_-M0F_JW78_:-Ky_8klwch1iBLC8Lmyc:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/b0c798ba181f46ff1cfc806c71f18e3a31a91e1f/flow-server/src/main/java/com/vaadin/router/RouteAlias.java#L39)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

Could be simplified as 

> This annotation can be used multiple times on the same class.

</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/router/RouteAlias.java, line 69 at r1](https://reviewable.io:443/reviews/vaadin/flow/2888#-Ky_-VJPm959lAxVgL7T:-Ky_8rMNGlIPGODgCW5T:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/b0c798ba181f46ff1cfc806c71f18e3a31a91e1f/flow-server/src/main/java/com/vaadin/router/RouteAlias.java#L69)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

typo: rout
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2888)*

**Comment by torok-peter** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-server/src/main/java/com/vaadin/server/startup/RouteRegistry.java, line 35 at r1](https://reviewable.io:443/reviews/vaadin/flow/2888#-Ky_0wW6hM8CvY0uO_6E:-Ky_FwgICuwUJ8EKmiRs:b3lxvx9) ([raw file](https://github.com/vaadin/flow/blob/b0c798ba181f46ff1cfc806c71f18e3a31a91e1f/flow-server/src/main/java/com/vaadin/server/startup/RouteRegistry.java#L35)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

I'm using standard Vaadin conventions.
Have they been updated ?

I'm pretty sure that import ordering cannot be blocking issue at all.
I don't even want to care about this exactly as I don't want to care about extra spaces in the code.

Otherwise it will be a total hell instead of writing a code.
</blockquote></details>

This defines the current Flow conventions regarding import ordering. This was also the source of our coding style document at https://drive.google.com/open?id=1_1S2VILmr8y5B3hD_fMbb9SwpkFKZjnAmaW2oE4_uYo .

So please update your IDE config accordingly - this is the fastest way out of hell, for all of us :-)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2888)*

**Comment by denis-anisimov** [comment]
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[flow-server/src/main/java/com/vaadin/server/startup/RouteRegistry.java, line 35 at r1](https://reviewable.io:443/reviews/vaadin/flow/2888#-Ky_0wW6hM8CvY0uO_6E:-Ky_KI-wybGchUwQAl_4:b-39v3ut) ([raw file](https://github.com/vaadin/flow/blob/b0c798ba181f46ff1cfc806c71f18e3a31a91e1f/flow-server/src/main/java/com/vaadin/server/startup/RouteRegistry.java#L35)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

This defines the current Flow conventions regarding import ordering. This was also the source of our coding style document at https://drive.google.com/open?id=1_1S2VILmr8y5B3hD_fMbb9SwpkFKZjnAmaW2oE4_uYo .

So please update your IDE config accordingly - this is the fastest way out of hell, for all of us :-)
</blockquote></details>

Reimported ./eclipse/VaadinJavaConventions.xml.

Tried to reformat.

No changes.

I'm OK to block this forever because of import order.
I will ask whether out team is OK with that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2888)*

**Pull request merged**
