### PR TITLE
Check the servlet version as soon as possible.

### PR DESCRIPTION
**Pull request by caalador**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3381)

### CODE REVIEW

**Comment by Artur-** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3381#-L3Y498rFCpK8PEEX2Ll:-L3Y498rFCpK8PEEX2Lm:b-jvl91a) (no related file):*
This would not resolve https://github.com/vaadin/flow/issues/3359 as the problem was that `ServletContainerInitializer`s are not run. `ServletContextListener` has been there since Servlet 2.3 and could be a better place to do the checking. There's no need to have the check ALSO in the servlet then

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3381)*

**Comment by caalador** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3381#-L3Y498rFCpK8PEEX2Ll:-L3Y5wjJDe3tHIuPIYQa:b-kfoclr) (no related file):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

This would not resolve https://github.com/vaadin/flow/issues/3359 as the problem was that `ServletContainerInitializer`s are not run. `ServletContextListener` has been there since Servlet 2.3 and could be a better place to do the checking. There's no need to have the check ALSO in the servlet then
</blockquote></details>

This does run and deployment fails on the expected exception for tomcat 7.0.39 and 7.0.82, the problem is that the received Set is always empty. But I can well move it to a contextListener.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3381)*

**Comment by caalador** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3381#-L3Y498rFCpK8PEEX2Ll:-L3Y6NEwX7GhMx8ZwMwc:bc9efo3) (no related file):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

This does run and deployment fails on the expected exception for tomcat 7.0.39 and 7.0.82, the problem is that the received Set is always empty. But I can well move it to a contextListener.
</blockquote></details>

```
.../apache-tomcat-7.0.82$ tail -n 50 logs/catalina.out 
SEVERE: Error during ServletContainerInitializer processing
javax.servlet.ServletException: Servlet 3.1+ is required
	at com.vaadin.flow.server.startup.ServletVerifier.onStartup(ServletVerifier.java:39)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5622)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:1015)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:991)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1127)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:2020)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodException: javax.servlet.http.HttpServletResponse.setContentLengthLong(long)
	at java.lang.Class.getMethod(Class.java:1786)
	at com.vaadin.flow.server.startup.ServletVerifier.onStartup(ServletVerifier.java:32)
	... 12 more

Jan 23, 2018 2:48:37 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Context [/flow-test-slot-1.0-SNAPSHOT] startup failed due to previous errors
```

```
apache-tomcat-7.0.39$ tail -n 50 logs/catalina.out 
INFO: Initializing ProtocolHandler ["http-bio-8080"]
Jan 23, 2018 2:39:13 PM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["ajp-bio-8009"]
Jan 23, 2018 2:39:13 PM org.apache.catalina.startup.Catalina load
INFO: Initialization processed in 641 ms
Jan 23, 2018 2:39:13 PM org.apache.catalina.core.StandardService startInternal
INFO: Starting service Catalina
Jan 23, 2018 2:39:13 PM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Apache Tomcat/7.0.39
Jan 23, 2018 2:39:13 PM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deploying web application archive /Users/Mikael/temp/apache/apache-tomcat-7.0.39/webapps/flow-test-slot-1.0-SNAPSHOT.war
Jan 23, 2018 2:39:15 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Error during ServletContainerInitializer processing
javax.servlet.ServletException: Servlet 3.1+ is required
	at com.vaadin.flow.server.startup.ServletVerifier.onStartup(ServletVerifier.java:39)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5370)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:633)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:977)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1655)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodException: javax.servlet.http.HttpServletResponse.setContentLengthLong(long)
	at java.lang.Class.getMethod(Class.java:1786)
	at com.vaadin.flow.server.startup.ServletVerifier.onStartup(ServletVerifier.java:32)
	... 12 more

Jan 23, 2018 2:39:15 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Context [/flow-test-slot-1.0-SNAPSHOT] startup failed due to previous errors
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3381)*

**Comment by Artur-** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3381#-L3Y498rFCpK8PEEX2Ll:-L3Y6wLLA3m-Ll6Jg24d:b-29oe44) (no related file):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

```
.../apache-tomcat-7.0.82$ tail -n 50 logs/catalina.out 
SEVERE: Error during ServletContainerInitializer processing
javax.servlet.ServletException: Servlet 3.1+ is required
	at com.vaadin.flow.server.startup.ServletVerifier.onStartup(ServletVerifier.java:39)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5622)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:1015)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:991)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1127)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:2020)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodException: javax.servlet.http.HttpServletResponse.setContentLengthLong(long)
	at java.lang.Class.getMethod(Class.java:1786)
	at com.vaadin.flow.server.startup.ServletVerifier.onStartup(ServletVerifier.java:32)
	... 12 more

Jan 23, 2018 2:48:37 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Context [/flow-test-slot-1.0-SNAPSHOT] startup failed due to previous errors
```

```
apache-tomcat-7.0.39$ tail -n 50 logs/catalina.out 
INFO: Initializing ProtocolHandler ["http-bio-8080"]
Jan 23, 2018 2:39:13 PM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["ajp-bio-8009"]
Jan 23, 2018 2:39:13 PM org.apache.catalina.startup.Catalina load
INFO: Initialization processed in 641 ms
Jan 23, 2018 2:39:13 PM org.apache.catalina.core.StandardService startInternal
INFO: Starting service Catalina
Jan 23, 2018 2:39:13 PM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Apache Tomcat/7.0.39
Jan 23, 2018 2:39:13 PM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deploying web application archive /Users/Mikael/temp/apache/apache-tomcat-7.0.39/webapps/flow-test-slot-1.0-SNAPSHOT.war
Jan 23, 2018 2:39:15 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Error during ServletContainerInitializer processing
javax.servlet.ServletException: Servlet 3.1+ is required
	at com.vaadin.flow.server.startup.ServletVerifier.onStartup(ServletVerifier.java:39)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5370)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:633)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:977)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1655)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodException: javax.servlet.http.HttpServletResponse.setContentLengthLong(long)
	at java.lang.Class.getMethod(Class.java:1786)
	at com.vaadin.flow.server.startup.ServletVerifier.onStartup(ServletVerifier.java:32)
	... 12 more

Jan 23, 2018 2:39:15 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Context [/flow-test-slot-1.0-SNAPSHOT] startup failed due to previous errors
```
</blockquote></details>

Alright, then ignore me :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3381)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java, line 81 at r1](https://reviewable.io:443/reviews/vaadin/flow/3381#-L3YBYmtJRb3hzM0dtYL:-L3YBYmtJRb3hzM0dtYM:b-s48epk) ([raw file](https://github.com/vaadin/flow/blob/b0556c9d5471b9f49d0996d838ae8d45cd2c18d3/flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java#L81)):*
> ```Java
>     @Override
>     public void init(ServletConfig servletConfig) throws ServletException {
>         ServletVerifier.verifyServletVersion();
> ```

So, now we verify the servlet version twice, right? Can we safely remove this check?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3381)*

**Comment by caalador** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java, line 81 at r1](https://reviewable.io:443/reviews/vaadin/flow/3381#-L3YBYmtJRb3hzM0dtYL:-L3afAySAz0nJS-UYrPN:b-eji9cg) ([raw file](https://github.com/vaadin/flow/blob/b0556c9d5471b9f49d0996d838ae8d45cd2c18d3/flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java#L81)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

So, now we verify the servlet version twice, right? Can we safely remove this check?
</blockquote></details>

Probably. I'll try to see what should be done for Spring as it doesn't run the container initializers.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3381)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3381)*

**Pull request merged**
