### PR TITLE
Add documentation for using TemplateRenderer with Grid

### PR DESCRIPTION
**Pull request by pekam**
The details row is ignored for now. I added a comment to include that in #2825

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/2910)

### CODE REVIEW

**Comment by ahie** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[flow-documentation/flow-components/tutorial-flow-grid.asciidoc, line 350 at r1](https://reviewable.io:443/reviews/vaadin/flow/2910#-Kypm5cxgpEVnolG-usK:-Kypm5cxgpEVnolG-usL:bj8ia4c) ([raw file](https://github.com/vaadin/flow/blob/dfa6adc49bd576767fb6b4c5802bae6fad62a271/flow-documentation/flow-components/tutorial-flow-grid.asciidoc#L350)):*
> DataCommunicator

Should rather direct users to `DataProvider#reset()` and `DataProvider#refresh(item)`. Removal of items requires a full reset, changes can be updated by just refreshing the single item.

---

*[flow-documentation/flow-components/tutorial-flow-grid.asciidoc, line 363 at r1](https://reviewable.io:443/reviews/vaadin/flow/2910#-KypmmHwAUfMdQMeMl5w:-KypmmHwAUfMdQMeMl5x:b-xipvex) ([raw file](https://github.com/vaadin/flow/blob/dfa6adc49bd576767fb6b4c5802bae6fad62a271/flow-documentation/flow-components/tutorial-flow-grid.asciidoc#L363)):*
> grid.getDataCommunicator().reset();

Rather use `grid.getDataProvider().reset()` here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2910)*

**Comment by ahie** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2910#-KypowvKde-UVkbG7bxY:-KypowvKde-UVkbG7bxZ:b-w6juzi) (no related file):*
You also need to add a java file that contains the example code snippets for this PR to pass validation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2910)*

**Comment by pekam** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2910#-KypowvKde-UVkbG7bxY:-KypzUsA1CLbLW3j8j2w:b-896fix) (no related file):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

You also need to add a java file that contains the example code snippets for this PR to pass validation.
</blockquote></details>

Done.

---

*[flow-documentation/flow-components/tutorial-flow-grid.asciidoc, line 350 at r1](https://reviewable.io:443/reviews/vaadin/flow/2910#-Kypm5cxgpEVnolG-usK:-KyppkUrwgGKXvA_iEp1:b-i8739h) ([raw file](https://github.com/vaadin/flow/blob/dfa6adc49bd576767fb6b4c5802bae6fad62a271/flow-documentation/flow-components/tutorial-flow-grid.asciidoc#L350)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

> DataCommunicator

Should rather direct users to `DataProvider#reset()` and `DataProvider#refresh(item)`. Removal of items requires a full reset, changes can be updated by just refreshing the single item.
</blockquote></details>

Done.
I've copied this example from the demo, so should that be changed also?

---

*[flow-documentation/flow-components/tutorial-flow-grid.asciidoc, line 363 at r1](https://reviewable.io:443/reviews/vaadin/flow/2910#-KypmmHwAUfMdQMeMl5w:-Kyppb7PXs9eFtRFUHC6:bx8u0ie) ([raw file](https://github.com/vaadin/flow/blob/dfa6adc49bd576767fb6b4c5802bae6fad62a271/flow-documentation/flow-components/tutorial-flow-grid.asciidoc#L363)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

> grid.getDataCommunicator().reset();

Rather use `grid.getDataProvider().reset()` here.
</blockquote></details>

There's no such method. You mean `refreshAll()`? That works so I used it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2910)*

**Comment by ahie** [comment]
Reviewed 1 of 2 files at r2.
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[flow-documentation/flow-components/tutorial-flow-grid.asciidoc, line 350 at r1](https://reviewable.io:443/reviews/vaadin/flow/2910#-Kypm5cxgpEVnolG-usK:-KytN2QjyWXYPKzkSCNA:b-pnwf7g) ([raw file](https://github.com/vaadin/flow/blob/dfa6adc49bd576767fb6b4c5802bae6fad62a271/flow-documentation/flow-components/tutorial-flow-grid.asciidoc#L350)):*
> After editing the server-side data used by the grid, you need to reset the grid's `DataCommunicator` to make those changes show up in the element.

Instead of removing this completely you could write:

>After editing the server-side data used by the grid, you need to refresh the grid's `DataProvider` to make those changes show up in the element.

The demo could also be updated.

---

*[flow-documentation/flow-components/tutorial-flow-grid.asciidoc, line 363 at r1](https://reviewable.io:443/reviews/vaadin/flow/2910#-KypmmHwAUfMdQMeMl5w:-KypmHQUFjNYQV_bf1ez:b-2xa3uq) ([raw file](https://github.com/vaadin/flow/blob/dfa6adc49bd576767fb6b4c5802bae6fad62a271/flow-documentation/flow-components/tutorial-flow-grid.asciidoc#L363)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

There's no such method. You mean `refreshAll()`? That works so I used it.
</blockquote></details>

Yes, sorry that's what I meant.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2910)*

**Comment by pekam** [comment]
Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[flow-documentation/flow-components/tutorial-flow-grid.asciidoc, line 350 at r1](https://reviewable.io:443/reviews/vaadin/flow/2910#-Kypm5cxgpEVnolG-usK:-KytTLWVc1PoR50uB_cv:b-beqmrv) ([raw file](https://github.com/vaadin/flow/blob/dfa6adc49bd576767fb6b4c5802bae6fad62a271/flow-documentation/flow-components/tutorial-flow-grid.asciidoc#L350)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

> After editing the server-side data used by the grid, you need to reset the grid's `DataCommunicator` to make those changes show up in the element.

Instead of removing this completely you could write:

>After editing the server-side data used by the grid, you need to refresh the grid's `DataProvider` to make those changes show up in the element.

The demo could also be updated.
</blockquote></details>

I didn't remove it, but moved it after the code snippet.

Demo updated.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2910)*

**Comment by ahie** [comment]
Reviewed 1 of 2 files at r2.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2910)*

**Comment by ahie** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2910)*

**Pull request merged**
