### PR TITLE
Take care about several property change executions

### PR DESCRIPTION
**Pull request by denis-anisimov**
On the client side there may be several property handling calls which should be deferred because of waiting of JS execution (which sets updatable properties).
All of them should be executed. Not only one.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3521)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3521#-L4tcarFdsohB1szfwJD:-L4tcarGUowKvwF1Z0UB:b-ffusnt) (no related file):*
Awaits for test.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3521)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java, line 343 at r1](https://reviewable.io:443/reviews/vaadin/flow/3521#-L597RCqfhQG8wa0rJZl:-L597RCqfhQG8wa0rJZm:b-133aef) ([raw file](https://github.com/vaadin/flow/blob/be729ff1acc0af75707bdce6578e7568ce5c8097/flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java#L343)):*
> ```Java
>         }
> 
>         MapProperty prop = mapProperty;
> ```

Guess you don't need that variable at all, but does not matter much.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3521)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java, line 343 at r1](https://reviewable.io:443/reviews/vaadin/flow/3521#-L597RCqfhQG8wa0rJZl:-L59TS7pG2MfHEvIOT4O:b-ob193b) ([raw file](https://github.com/vaadin/flow/blob/be729ff1acc0af75707bdce6578e7568ce5c8097/flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java#L343)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Guess you don't need that variable at all, but does not matter much.
</blockquote></details>

I don't but Java compiler does.
`mapProperty` is not effectively `final` (it's reassignable above).
And cannot be used inside lambda below.
That's why I need effectively final `prop`  variable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3521)*

**Comment by SomeoneToIgnore** [comment]
*[flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java, line 343 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3521#-L597RCqfhQG8wa0rJZl:-L59TttHB6NiFAmDaYDH:bccp0fr) ([raw file](https://github.com/vaadin/flow/blob/be729ff1acc0af75707bdce6578e7568ce5c8097/flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java#L343)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

I don't but Java compiler does.
`mapProperty` is not effectively `final` (it's reassignable above).
And cannot be used inside lambda below.
That's why I need effectively final `prop`  variable.
</blockquote></details>

Ah, I see. Thanks.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3521)*

**Pull request merged**
