### PR TITLE
Make WebComponentExporter.configureInstance protected

### LINKED ISSUE #5857: Make WebComponentExporter.configureInstance non-abstract
Currently, you need to provide an empty
```
        @Override
        public void configureInstance(WebComponent<BlogAdmin> webComponent, BlogAdmin component) {
        }
```
for all exported simple components. 

The method should be made optional and the constructor/class javadoc should tell about the method and what it can be used for.

### PR DESCRIPTION
**Pull request by Artur-**
---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/5858)

### CODE REVIEW

**Comment by Artur-** [comment]
What is the reason for it being mandatory when it is not needed in many cases?

**Comment by Legioth** [comment]
The idea was that the method would be needed often enough that the forced discoverability is more beneficial than the potentially additional boilerplate that it causes.

If it turns out that there are many use cases where there isn't any need to have any logic in the method, then we should reconsider.

**Comment by ujoni** [comment]
We had a discussion about this issue in grooming and for now, decided to take the stance similar to @Legioth's: let's keep the method abstract for now to bolster discoverability.

However, since the method should be called by Flow internals only, having it `protected` makes sense.

**Comment by Artur-** [comment]
Changed this PR to only make it protected and update javadocs

**Comment by denis-anisimov** [comment]
```
/WebComponentExporter.java:75: error: unknown tag: MyComponent
 *     protected void configureInstance(WebComponent<MyComponent> webComponent, MyComponent component) {
                                                    ^
```

**Pull request merged**
