### PR TITLE
Remove default body sizes.

### PR DESCRIPTION
**Pull request by caalador**
Make it simple to add body sizes to bootstrap page.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3120)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[flow-documentation/application-structure/tutorial-bootstrap.asciidoc, line 124 at r1](https://reviewable.io:443/reviews/vaadin/flow/3120#-L-q0mTpBYwuXYXLQTe9:-L-q0mTpBYwuXYXLQTeA:b7oc5gv) ([raw file](https://github.com/vaadin/flow/blob/3a719095d3edf5f68cd5ad0651d9fcdccd745c57/flow-documentation/application-structure/tutorial-bootstrap.asciidoc#L124)):*
> settings.addInlineWithContents("body {width: 100vw; height:100vh;}",
>                 Dependency.Type.STYLESHEET);

What does happen if I have `@BodySize` annotation along with this method implemented here?
With different values ?

---

*[flow-server/src/main/java/com/vaadin/server/BootstrapUtils.java, line 171 at r1](https://reviewable.io:443/reviews/vaadin/flow/3120#-L-q1gwmfPXolWxYf3Ng:-L-q1gwmfPXolWxYf3Nh:b-jxm4vv) ([raw file](https://github.com/vaadin/flow/blob/3a719095d3edf5f68cd5ad0651d9fcdccd745c57/flow-server/src/main/java/com/vaadin/server/BootstrapUtils.java#L171)):*
> viewportContent = navigationTarget
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>
>                     .flatMap(BootstrapUtils::getBodySizeAnnotation)
>                     .map(BootstrapUtils::composeBodySizeString).orElse(null);
>         }
>         return Optional.ofNullable(viewportContent);
</details>

A bit weird to return `null` from an optional and then return optional again from `null` (if it's `null`).
May be return immediately inside `if` ?

---

*[flow-server/src/main/java/com/vaadin/ui/BodySize.java, line 37 at r1](https://reviewable.io:443/reviews/vaadin/flow/3120#-L-q2OKvMz4JpPjv4yoC:-L-q2OKvMz4JpPjv4yoD:b-bja30o) ([raw file](https://github.com/vaadin/flow/blob/3a719095d3edf5f68cd5ad0651d9fcdccd745c57/flow-server/src/main/java/com/vaadin/ui/BodySize.java#L37)):*
> height
should end with the dot.

---

*[flow-server/src/main/java/com/vaadin/ui/BodySize.java, line 44 at r1](https://reviewable.io:443/reviews/vaadin/flow/3120#-L-q2L3iUAsYMxjJiQUW:-L-q2L3iUAsYMxjJiQUX:b-j6wr9h) ([raw file](https://github.com/vaadin/flow/blob/3a719095d3edf5f68cd5ad0651d9fcdccd745c57/flow-server/src/main/java/com/vaadin/ui/BodySize.java#L44)):*
> width

should end with the dot.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3120)*

**Comment by caalador** [comment]
Review status: 6 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[flow-documentation/application-structure/tutorial-bootstrap.asciidoc, line 124 at r1](https://reviewable.io:443/reviews/vaadin/flow/3120#-L-q0mTpBYwuXYXLQTe9:-L-q3CNt7VQX5Ug6_BAv:b7ky06) ([raw file](https://github.com/vaadin/flow/blob/3a719095d3edf5f68cd5ad0651d9fcdccd745c57/flow-documentation/application-structure/tutorial-bootstrap.asciidoc#L124)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> settings.addInlineWithContents("body {width: 100vw; height:100vh;}",
>                 Dependency.Type.STYLESHEET);

What does happen if I have `@BodySize` annotation along with this method implemented here?
With different values ?

</blockquote></details>

You'll have duplicate with the inline winning except if you prepend it then the @BodySize wins.

---

*[flow-server/src/main/java/com/vaadin/server/BootstrapUtils.java, line 171 at r1](https://reviewable.io:443/reviews/vaadin/flow/3120#-L-q1gwmfPXolWxYf3Ng:-L-q3YThyi8oLwryCPn5:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/3a719095d3edf5f68cd5ad0651d9fcdccd745c57/flow-server/src/main/java/com/vaadin/server/BootstrapUtils.java#L171)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> viewportContent = navigationTarget
>                     .flatMap(BootstrapUtils::getBodySizeAnnotation)
>                     .map(BootstrapUtils::composeBodySizeString).orElse(null);
>         }
>         return Optional.ofNullable(viewportContent);

A bit weird to return `null` from an optional and then return optional again from `null` (if it's `null`).
May be return immediately inside `if` ?
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/ui/BodySize.java, line 37 at r1](https://reviewable.io:443/reviews/vaadin/flow/3120#-L-q2OKvMz4JpPjv4yoC:-L-q3a-ca3pcY2iotKmh:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/3a719095d3edf5f68cd5ad0651d9fcdccd745c57/flow-server/src/main/java/com/vaadin/ui/BodySize.java#L37)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> height
should end with the dot.
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/ui/BodySize.java, line 44 at r1](https://reviewable.io:443/reviews/vaadin/flow/3120#-L-q2L3iUAsYMxjJiQUW:-L-q3aFMtIJRx-vv9C8G:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/3a719095d3edf5f68cd5ad0651d9fcdccd745c57/flow-server/src/main/java/com/vaadin/ui/BodySize.java#L44)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> width

should end with the dot.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3120)*

**Comment by denis-anisimov** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-documentation/application-structure/tutorial-bootstrap.asciidoc, line 124 at r1](https://reviewable.io:443/reviews/vaadin/flow/3120#-L-q0mTpBYwuXYXLQTe9:-L-q4Ni6H61N76UA7ocl:b-7b5ngm) ([raw file](https://github.com/vaadin/flow/blob/3a719095d3edf5f68cd5ad0651d9fcdccd745c57/flow-documentation/application-structure/tutorial-bootstrap.asciidoc#L124)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

You'll have duplicate with the inline winning except if you prepend it then the @BodySize wins.
</blockquote></details>

Technically I meant that the documentation should mention this situation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3120)*

**Comment by caalador** [comment]
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-documentation/application-structure/tutorial-bootstrap.asciidoc, line 124 at r1](https://reviewable.io:443/reviews/vaadin/flow/3120#-L-q0mTpBYwuXYXLQTe9:-L034VsgYjmGpVCl4XI-:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/3a719095d3edf5f68cd5ad0651d9fcdccd745c57/flow-documentation/application-structure/tutorial-bootstrap.asciidoc#L124)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Technically I meant that the documentation should mention this situation.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3120)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3120)*

**Comment by denis-anisimov** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/SynchronizedPropertyIT.java, line 43 at r5](https://reviewable.io:443/reviews/vaadin/flow/3120#-L044ymOYHhcalhXuBUd:-L044ymOYHhcalhXuBUe:br3j8na) ([raw file](https://github.com/vaadin/flow/blob/db59b9e883b17b57f18cdbb1753becdb5b0a3f1d/flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/SynchronizedPropertyIT.java#L43)):*
>  ((JavascriptExecutor) driver).

No need.
There is a protected `executeScript` method inherited from the `TestBenchHelpers`  class.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3120)*

**Comment by caalador** [comment]
Review status: 9 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/SynchronizedPropertyIT.java, line 43 at r5](https://reviewable.io:443/reviews/vaadin/flow/3120#-L044ymOYHhcalhXuBUd:-L045zMP8uhl491IMiLS:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/db59b9e883b17b57f18cdbb1753becdb5b0a3f1d/flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/SynchronizedPropertyIT.java#L43)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

>  ((JavascriptExecutor) driver).

No need.
There is a protected `executeScript` method inherited from the `TestBenchHelpers`  class.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3120)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3120)*

**Pull request merged**
