### PR TITLE
Make addListener protected and move the public method to utils.

### PR DESCRIPTION
**Pull request by denis-anisimov**
Fix for #4085

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/4100)

### CODE REVIEW

**Comment by Legioth** [comment]
Review status: 0 of 42 files reviewed at latest revision, 8 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/component/AttachNotifier.java, line 36 at r2](https://reviewable.io/reviews/vaadin/flow/4100#-LC3WXSD2lW0oxAT6-BE:-LC3WXSD2lW0oxAT6-BF:bp035om) ([raw file](https://github.com/vaadin/flow/blob/352855779ec4ce3da48b9f1bb0a70551feb89d14/flow-server/src/main/java/com/vaadin/flow/component/AttachNotifier.java#L36)):*
> ```Java
>     default Registration addAttachListener(
>             ComponentEventListener<AttachEvent> listener) {
>         return addListener(AttachEvent.class, listener);
> ```

Instead, leave the `default` method in place but change it to call `ComponentUtil.addListener((Component) this, ...)`.

That approach would fail if you add this mixin to a class that would have implemented `ComponentEventNotifier` while still not extending `Component`.  I think it's acceptable to fail in such cases.

The same also applies for all the other changed notifier interfaces.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4100)*

**Comment by denis-anisimov** [comment]
Review status: 0 of 13 files reviewed at latest revision, 8 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/component/AttachNotifier.java, line 36 at r2](https://reviewable.io/reviews/vaadin/flow/4100#-LC3WXSD2lW0oxAT6-BE:-LC3dv_e6L1ekQSVt0Gf:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/352855779ec4ce3da48b9f1bb0a70551feb89d14/flow-server/src/main/java/com/vaadin/flow/component/AttachNotifier.java#L36)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

Instead, leave the `default` method in place but change it to call `ComponentUtil.addListener((Component) this, ...)`.

That approach would fail if you add this mixin to a class that would have implemented `ComponentEventNotifier` while still not extending `Component`.  I think it's acceptable to fail in such cases.

The same also applies for all the other changed notifier interfaces.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4100)*

**Comment by pekam** [comment]
Reviewed 2 of 42 files at r1, 1 of 1 files at r2, 2 of 39 files at r3, 8 of 8 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[flow-server/src/main/java/com/vaadin/flow/component/BlurNotifier.java, line 45 at r5](https://reviewable.io/reviews/vaadin/flow/4100#-LCYCvt48uUzx_23jdmG:-LCYCvt48uUzx_23jdmH:b-ygppi2) ([raw file](https://github.com/vaadin/flow/blob/e56eb48c4377661a8e01de07222e64ea8403fad6/flow-server/src/main/java/com/vaadin/flow/component/BlurNotifier.java#L45)):*
> ```Java
>         if (this instanceof Component) {
>             return ComponentUtil.addListener((Component) this, BlurEvent.class,
>                     (ComponentEventListener) listener);
> ```

Why is casting needed here? Is it somehow because the event has a type parameter?
(Same for click and focus)

---

*[flow-server/src/main/java/com/vaadin/flow/component/Component.java, line 327 at r5](https://reviewable.io/reviews/vaadin/flow/4100#-LCYDlpz1gaGlgX7SIZr:-LCYDlpz1gaGlgX7SIZs:bjxv9z7) ([raw file](https://github.com/vaadin/flow/blob/e56eb48c4377661a8e01de07222e64ea8403fad6/flow-server/src/main/java/com/vaadin/flow/component/Component.java#L327)):*
The comment in the ticket says:
> Discussed with team and concluded that changing addListener to package protected and adding a method for it to ComponentUtil is fine.

So should the access modifier be `protected` or `package` instead? Personally I don't recall what was the idea behind that. Then everyone would be forced to use `ComponentUtils`so maybe it would then be even harder to abuse the method.

What do you think?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4100)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-server/src/main/java/com/vaadin/flow/component/BlurNotifier.java, line 45 at r5](https://reviewable.io/reviews/vaadin/flow/4100#-LCYCvt48uUzx_23jdmG:-LCYPp-V1XH4fZwS59o6:b-uaxrrg) ([raw file](https://github.com/vaadin/flow/blob/e56eb48c4377661a8e01de07222e64ea8403fad6/flow-server/src/main/java/com/vaadin/flow/component/BlurNotifier.java#L45)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

Why is casting needed here? Is it somehow because the event has a type parameter?
(Same for click and focus)
</blockquote></details>

Just let me know how the casting can be avoided here.
`Component` is a class. This is an interface.
Interface may not extend class. So how may I avoid casting ?

---

*[flow-server/src/main/java/com/vaadin/flow/component/Component.java, line 327 at r5](https://reviewable.io/reviews/vaadin/flow/4100#-LCYDlpz1gaGlgX7SIZr:-LCYQEoJE8iJxEPOcK06:b-d4aavq) ([raw file](https://github.com/vaadin/flow/blob/e56eb48c4377661a8e01de07222e64ea8403fad6/flow-server/src/main/java/com/vaadin/flow/component/Component.java#L327)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

I actually think the conclusion in the ticket is mistyped. To me, `protected` seems to be the most appropriate modifier since that makes it easy for component implementations to add support for their own (assumingly non-generic) event handlers.
</blockquote></details>

Component subclass should be able to reuse the method without `ComponentUtil`.
It's inconvenient to use `ComponentUtil`  in the component subclass. So I would definitely prefer the protected method.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4100)*

**Comment by pekam** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-server/src/main/java/com/vaadin/flow/component/BlurNotifier.java, line 45 at r5](https://reviewable.io/reviews/vaadin/flow/4100#-LCYCvt48uUzx_23jdmG:-LCYQk2k-rLbb78Hx-GZ:b-2440t0) ([raw file](https://github.com/vaadin/flow/blob/e56eb48c4377661a8e01de07222e64ea8403fad6/flow-server/src/main/java/com/vaadin/flow/component/BlurNotifier.java#L45)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Just let me know how the casting can be avoided here.
`Component` is a class. This is an interface.
Interface may not extend class. So how may I avoid casting ?
</blockquote></details>

I'm talking about `ComponentEventListener`.
You are casting
`(ComponentEventListener) ComponentEventListener<BlurEvent<T>> listener`

and it's only for these three mixins: blur, focus and click

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4100)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[flow-server/src/main/java/com/vaadin/flow/component/BlurNotifier.java, line 45 at r5](https://reviewable.io/reviews/vaadin/flow/4100#-LCYCvt48uUzx_23jdmG:-LCYdjms7ZhEu0JWZTk-:b-41jrvh) ([raw file](https://github.com/vaadin/flow/blob/e56eb48c4377661a8e01de07222e64ea8403fad6/flow-server/src/main/java/com/vaadin/flow/component/BlurNotifier.java#L45)):*
The previous code is 
`addListener(BlurEvent.class, (ComponentEventListener) listener);`
Is it different ?
Technically it's not changed.
Cast is done because otherwise there are compilation errors.

>Is it somehow because the event has a type parameter?

yes, it is.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4100)*

**Comment by pekam** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4100#-:-LCYeXIc8rrJmPOprsU5:bnfp4nl)*

**Pull request merged**
