### PR TITLE
Make registry classes thread safe

### PR DESCRIPTION
**Pull request by denis-anisimov**
Fix for #2667

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/2672)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
@Legioth please review the way how `RouteRegistry::getInstance()` work.
You have modified it from being singleton to method with a parameter.
I'm not entirely sure that this approach will work with the your usecase.

**Comment by SomeoneToIgnore** [comment]
*[flow-server/src/main/java/com/vaadin/server/startup/RouteRegistry.java, line 103 at r1](https://reviewable.io:443/reviews/vaadin/flow/2672#-KwJbw8d1tm6UudrT3Id:-KwJbw8d1tm6UudrT3Ie:b19xdlv) ([raw file](https://github.com/vaadin/flow/blob/54927d69f0ccf2b16fc73c4a1cab8c28b7bb2941/flow-server/src/main/java/com/vaadin/server/startup/RouteRegistry.java#L103)):*
> ```Java
>             servletContext.addListener(DESTROY_LISTENER);
>             registry = new RouteRegistry();
>             INSTANCE.compareAndSet(null, registry);
> ```

And what if CAS return `false`? Should we return a different registry and remove the destroy listener?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2672)*

**Comment by denis-anisimov** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[flow-server/src/main/java/com/vaadin/server/startup/RouteRegistry.java, line 103 at r1](https://reviewable.io:443/reviews/vaadin/flow/2672#-KwJbw8d1tm6UudrT3Id:-KwJer0z0OYd1Wg1rRxy:b-89c9hl) ([raw file](https://github.com/vaadin/flow/blob/54927d69f0ccf2b16fc73c4a1cab8c28b7bb2941/flow-server/src/main/java/com/vaadin/server/startup/RouteRegistry.java#L103)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

And what if CAS return `false`? Should we return a different registry and remove the destroy listener?
</blockquote></details>

I don't care what does `compareAndSet` return.
It's perfectly possible with thus pattern that it doesn't return `true`.
Since this code "is not thread safe" meaning that it can be executed several times from different threads in unhappy path (quite unlikely but possible).

But it is thread safe since only one correct instance of `RouteRegistry` will be used everywhere.

So it doesn't matter what  `compareAndSet` return.

Listener is not that important since it's attached to the instance that is going to be dead.
But I can add its reregistration. I have to fix tests anyway.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2672)*

**Comment by denis-anisimov** [comment]
Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[flow-server/src/main/java/com/vaadin/server/startup/RouteRegistry.java, line 103 at r1](https://reviewable.io:443/reviews/vaadin/flow/2672#-KwJbw8d1tm6UudrT3Id:-KwJgC1OKejW1lORrKc_:b-60cyz5) ([raw file](https://github.com/vaadin/flow/blob/54927d69f0ccf2b16fc73c4a1cab8c28b7bb2941/flow-server/src/main/java/com/vaadin/server/startup/RouteRegistry.java#L103)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

I don't care what does `compareAndSet` return.
It's perfectly possible with thus pattern that it doesn't return `true`.
Since this code "is not thread safe" meaning that it can be executed several times from different threads in unhappy path (quite unlikely but possible).

But it is thread safe since only one correct instance of `RouteRegistry` will be used everywhere.

So it doesn't matter what  `compareAndSet` return.

Listener is not that important since it's attached to the instance that is going to be dead.
But I can add its reregistration. I have to fix tests anyway.
</blockquote></details>

Actually there is no way to remove the listener. That's the issue.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2672)*

**Comment by Legioth** [comment]
*[flow-server/src/main/java/com/vaadin/server/startup/RouteRegistry.java, line 97 at r1](https://reviewable.io:443/reviews/vaadin/flow/2672#-KwJlw2uxySSUv6B_ICY:-KwJlw2uxySSUv6B_ICZ:bv13tdg) ([raw file](https://github.com/vaadin/flow/blob/54927d69f0ccf2b16fc73c4a1cab8c28b7bb2941/flow-server/src/main/java/com/vaadin/server/startup/RouteRegistry.java#L97)):*
> ```Java
>         assert servletContext != null;
> 
>         // Only one servlet context should be active in the application. So
> ```

I'm not sure about this assumption. Most servlet containers allow putting shared libraries outside each `.war` so that those classes are only loaded once and shared between all servlet contexts. We might instead have to use something like `ConcurrentHashMap<ServletContext, RouteRegistry>` (or maybe simpler and smaller risk of leaks with a `WeakHashMap<ServletContext, RouteRegistry>` guarded by a lock). 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2672)*

**Comment by denis-anisimov** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[flow-server/src/main/java/com/vaadin/server/startup/RouteRegistry.java, line 97 at r1](https://reviewable.io:443/reviews/vaadin/flow/2672#-KwJlw2uxySSUv6B_ICY:-KwJpfhuyHUgwv0L70bw:b-hz5ems) ([raw file](https://github.com/vaadin/flow/blob/54927d69f0ccf2b16fc73c4a1cab8c28b7bb2941/flow-server/src/main/java/com/vaadin/server/startup/RouteRegistry.java#L97)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

I'm not sure about this assumption. Most servlet containers allow putting shared libraries outside each `.war` so that those classes are only loaded once and shared between all servlet contexts. We might instead have to use something like `ConcurrentHashMap<ServletContext, RouteRegistry>` (or maybe simpler and smaller risk of leaks with a `WeakHashMap<ServletContext, RouteRegistry>` guarded by a lock). 
</blockquote></details>

I would suggest then just synchronize on `ServletContext` instance.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2672)*

**Comment by Legioth** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[flow-server/src/main/java/com/vaadin/server/startup/RouteRegistry.java, line 97 at r1](https://reviewable.io:443/reviews/vaadin/flow/2672#-KwJlw2uxySSUv6B_ICY:-KwJqkRUfiIq3Eg_GDTz:b-ibuk24) ([raw file](https://github.com/vaadin/flow/blob/54927d69f0ccf2b16fc73c4a1cab8c28b7bb2941/flow-server/src/main/java/com/vaadin/server/startup/RouteRegistry.java#L97)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

I would suggest then just synchronize on `ServletContext` instance.
</blockquote></details>

That might make even more sense

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2672)*

**Comment by Legioth** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2672#-:-KwK6945fJ7vKpMtUZrK:bnfp4nl)*

**Comment by denis-anisimov** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2672)*

**Pull request merged**
