### PR TITLE
Throw an exception when bundle not found.

### LINKED ISSUE #3825: jetty:run no longer works when enabling production mode and there is no way to find out why
Take any basic Flow app, start it with `mvn jetty:run` and it works as expected.

Add the Maven plugin for production mode and the app works as expected although you are not running in production mode as you might think because of #3824 .

Add `flow-server-production-mode` and the app no longer starts. The only error you get is
```
[qtp1192834021-67] INFO com.vaadin.flow.server.startup.BundleFilterInitializer - Bundling disabled: Flow bundle manifest '/frontend-es6/vaadin-flow-bundle-manifest.json' was not found in servlet context
```

As a user this tells me nothing. If I look in the target folder, I find a `frontend-es6/vaadin-flow-bundle-manifest.json` file. The error message also indicates that the app will work although bundling will not be used BUT it won't because it tries to load the files from a `frontend-es6` folder and that cannot be found either.

There should be some way for me as a user to find out that I need to run `mvn jetty:run-war` or do something else  to make it work. Or then `mvn jetty:run` should work also for production, out of the box

### PR DESCRIPTION
**Pull request by manolo**
- Improved error message.
- Added a parameter for disabling bundle and skip error.

Fixes #3825

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3941)

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
Reviewed 4 of 4 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/flow/3941#-LASlZxV82PFHGEuPfqI:-LASlZxV82PFHGEuPfqJ:b-bayb0y) (no related file):*
I think the issue should be solved completely differently, maybe because the ticket description is rather misleading.

What's Artur has described in the issue is the problem with our plugin and jetty plugin interop.
Our app finds the bundle json file when `run-war` goal of jetty plugin is used and does not find it when `run` goal is used.

This happens because our plugin puts all the necessary files into the `target` directory from where it is packed straight to the war file. 
`run-war` goal runs Jetty with that war file, that has the json file required and everything works smooth, because Jetty's `resourceBases` contain the whole war, including `frontend-es6` directory in the root of the war.

But `run` goal of the Jetty plugin is different – it runs using project sources, not even looking at the target directory.
That's why it's `resourceBases` have different values, making the Jetty that starts not to see the json file at all (since it does not include that target directory in those paths).

Of course, you can override those `resourceBases` by providing a plugin configuration, but apparently Artur wants no extra configuration.
That's the issue you're supposed to solve in this PR. Not sure if it's possible though.

More info about Jetty plugin parameters: https://www.eclipse.org/jetty/documentation/9.3.x/jetty-maven-plugin.html

To see the paths that Jetty sees, you can start the Jetty via the plugin and, in the very end of the starting log, there would be something like this:

```
[INFO] Started o.e.j.m.p.JettyWebAppContext@106c73ed{/,[file:///Users/someonetoignore/Work/flow/flow-demo/demo-minesweeper-polymer/target/build/, jar:file:///Users/someonetoignore/.m2/repository/com/vaadin/flow-push/1.0-SNAPSHOT/flow-push-1.0-SNAPSHOT.jar!/META-INF/resources, jar:file:///Users/someonetoignore/.m2/repository/org/webjars/bowergithub/webcomponents/webcomponentsjs/1.2.0/webcomponentsjs-1.2.0.jar!/META-INF/resources, jar:file:///Users/someonetoignore/.m2/repository/org/webjars/bowergithub/webcomponents/shadycss/1.1.3/shadycss-1.1.3.jar!/META-INF/resources, jar:file:///Users/someonetoignore/.m2/repository/org/webjars/bowergithub/polymer/polymer/2.5.0/polymer-2.5.0.jar!/META-INF/resources, jar:file:///Users/someonetoignore/.m2/repository/com/vaadin/flow-client/1.0-SNAPSHOT/flow-client-1.0-SNAPSHOT.jar!/META-INF/resources],AVAILABLE}{[file:///Users/someonetoignore/Work/flow/flow-demo/demo-minesweeper-polymer/target/build/]}
```

Those paths listed are the only paths Jetty will look for the resources in.

---

*[flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java, line 247 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3941#-LASkIKa79MTTBXnIX9-:-LASkIKa79MTTBXnIX90:bbt4wfy) ([raw file](https://github.com/vaadin/flow/blob/cb9575047ddcddd3ceb6371bddf1d0b581fa19c3/flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java#L247)):*
> ```Java
>      */
>     default String getEs6FrontendPrefix() {
>         return isBundleEnabled()
> ```

Did I understand right that if we run in production mode and the bundling is disabled via the environment variable, the app will start to return `getDevelopmentFrontendPrefix()` value as es6 and es5 paths?

This is wrong, we use custom es5/es6 paths disregarding of the bundling enabled in production mode.

---

*[flow-server/src/main/java/com/vaadin/flow/server/startup/BundleFilterInitializer.java, line 93 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3941#-LASm1RH6QJpS4srXGWt:-LASm1RH6QJpS4srXGWu:b1er55e) ([raw file](https://github.com/vaadin/flow/blob/cb9575047ddcddd3ceb6371bddf1d0b581fa19c3/flow-server/src/main/java/com/vaadin/flow/server/startup/BundleFilterInitializer.java#L93)):*
> ```Java
>                         manifestResource);
> 
>                 System.setProperty("vaadin." + Constants.DISABLE_BUNDLE, "true");
> ```

I don't think it's the right way: properties are created for users to set, not for our app to override.

If our app will start to silently set some global environment properties, we might spoil something for users and end up ourselves in a very bad situation when we don't know what's going on because of these variables set from our code.

Having a mutable global state is also a very bad idea without reasons.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3941)*

**Comment by manolo** [comment]
Review status: 2 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/flow/3941#-LASlZxV82PFHGEuPfqI:-LAStPc5ASwom4RaM5bB:b380dsb) (no related file):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

I think the issue should be solved completely differently, maybe because the ticket description is rather misleading.

What's Artur has described in the issue is the problem with our plugin and jetty plugin interop.
Our app finds the bundle json file when `run-war` goal of jetty plugin is used and does not find it when `run` goal is used.

This happens because our plugin puts all the necessary files into the `target` directory from where it is packed straight to the war file. 
`run-war` goal runs Jetty with that war file, that has the json file required and everything works smooth, because Jetty's `resourceBases` contain the whole war, including `frontend-es6` directory in the root of the war.

But `run` goal of the Jetty plugin is different – it runs using project sources, not even looking at the target directory.
That's why it's `resourceBases` have different values, making the Jetty that starts not to see the json file at all (since it does not include that target directory in those paths).

Of course, you can override those `resourceBases` by providing a plugin configuration, but apparently Artur wants no extra configuration.
That's the issue you're supposed to solve in this PR. Not sure if it's possible though.

More info about Jetty plugin parameters: https://www.eclipse.org/jetty/documentation/9.3.x/jetty-maven-plugin.html

To see the paths that Jetty sees, you can start the Jetty via the plugin and, in the very end of the starting log, there would be something like this:

```
[INFO] Started o.e.j.m.p.JettyWebAppContext@106c73ed{/,[file:///Users/someonetoignore/Work/flow/flow-demo/demo-minesweeper-polymer/target/build/, jar:file:///Users/someonetoignore/.m2/repository/com/vaadin/flow-push/1.0-SNAPSHOT/flow-push-1.0-SNAPSHOT.jar!/META-INF/resources, jar:file:///Users/someonetoignore/.m2/repository/org/webjars/bowergithub/webcomponents/webcomponentsjs/1.2.0/webcomponentsjs-1.2.0.jar!/META-INF/resources, jar:file:///Users/someonetoignore/.m2/repository/org/webjars/bowergithub/webcomponents/shadycss/1.1.3/shadycss-1.1.3.jar!/META-INF/resources, jar:file:///Users/someonetoignore/.m2/repository/org/webjars/bowergithub/polymer/polymer/2.5.0/polymer-2.5.0.jar!/META-INF/resources, jar:file:///Users/someonetoignore/.m2/repository/com/vaadin/flow-client/1.0-SNAPSHOT/flow-client-1.0-SNAPSHOT.jar!/META-INF/resources],AVAILABLE}{[file:///Users/someonetoignore/Work/flow/flow-demo/demo-minesweeper-polymer/target/build/]}
```

Those paths listed are the only paths Jetty will look for the resources in.
</blockquote></details>

Isn't a valid use case that the app can run in production mode, but without any bundling or transpilation at all, just using flat dependencies?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3941)*

**Comment by SomeoneToIgnore** [comment]
*[a discussion](https://beta.reviewable.io/reviews/vaadin/flow/3941#-LASlZxV82PFHGEuPfqI:-LASu_db6dcS6zl3zzpN:bcmzlxp) (no related file):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Isn't a valid use case that the app can run in production mode, but without any bundling or transpilation at all, just using flat dependencies?
</blockquote></details>

The app should be able to run in production mode without any transpilation or bundling, sure.
In production mode, it still looks at `context://frontend-es6` and `context://frontend-es5` directories (by default) for the files to use.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3941)*

**Comment by manolo** [comment]
Review status: 1 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/flow/3941#-LASlZxV82PFHGEuPfqI:-LAX35pqEgaWxqD05GBy:b-y3bzs4) (no related file):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

The app should be able to run in production mode without any transpilation or bundling, sure.
In production mode, it still looks at `context://frontend-es6` and `context://frontend-es5` directories (by default) for the files to use.
</blockquote></details>

After a discussion in daily we decided to:
- improve message when bundle not found, and fail with an exception
- keep the`disable.bundle` parameter  which means that the user does not want to use the bundle in production even thought it might be there

---

*[flow-server/src/main/java/com/vaadin/flow/server/startup/BundleFilterInitializer.java, line 93 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3941#-LASm1RH6QJpS4srXGWt:-LAX3d7X1IbSN4KR-bKO:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/cb9575047ddcddd3ceb6371bddf1d0b581fa19c3/flow-server/src/main/java/com/vaadin/flow/server/startup/BundleFilterInitializer.java#L93)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

I don't think it's the right way: properties are created for users to set, not for our app to override.

If our app will start to silently set some global environment properties, we might spoil something for users and end up ourselves in a very bad situation when we don't know what's going on because of these variables set from our code.

Having a mutable global state is also a very bad idea without reasons.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3941)*

**Comment by manolo** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java, line 247 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3941#-LASkIKa79MTTBXnIX9-:-LAXXath6GNlnnRXRlZ8:bi3k56t) ([raw file](https://github.com/vaadin/flow/blob/cb9575047ddcddd3ceb6371bddf1d0b581fa19c3/flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java#L247)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Did I understand right that if we run in production mode and the bundling is disabled via the environment variable, the app will start to return `getDevelopmentFrontendPrefix()` value as es6 and es5 paths?

This is wrong, we use custom es5/es6 paths disregarding of the bundling enabled in production mode.
</blockquote></details>

Renamed methods and flags as discussed in chat. 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3941)*

**Comment by caalador** [comment]
Failed to find `vaadin-flow-bundle-manifest.json` seems to be the failing part in all failing tests for this PR

**Comment by manolo** [comment]
We need `vaadin-flow-bundle-manifest.json` and `vaadin-flow-bundle.html` files to correct handle tests in es6 paths

---

Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3941#-:-LAmW54S7ZUHGAEWmJo7:b-1u8j41)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 4 of 6 files at r3, 2 of 2 files at r4, 4 of 4 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java, line 270 at r5](https://beta.reviewable.io/reviews/vaadin/flow/3941#-LAnCl4i2aui9yip1KaL:-LAnCl4i2aui9yip1KaM:b-1161pz) ([raw file](https://github.com/vaadin/flow/blob/ab8f9218f63e2aa3a26815e744e4cfe231b4bd21/flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java#L270)):*
> ```
>      * {@code true} or the user have not set the property at all and the
>      * production mode is enabled.
> ```

Not `true` anymore, propose to update the javadoc also.

---

*[flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java, line 279 at r5](https://beta.reviewable.io/reviews/vaadin/flow/3941#-LAnC-Wk4sejItw3rO-k:-LAnC-Wk4sejItw3rO-l:b1cwwen) ([raw file](https://github.com/vaadin/flow/blob/ab8f9218f63e2aa3a26815e744e4cfe231b4bd21/flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java#L279)):*
> ```
> bundled fragments
> ```

Not only bundled fragments. Two more places in the same javadoc below should also be fixed.

---

*[flow-server/src/main/java/com/vaadin/flow/server/Constants.java, line 90 at r5](https://beta.reviewable.io/reviews/vaadin/flow/3941#-LAnBXASCvpjtOCm0QaX:-LAnBXASCvpjtOCm0QaY:b96282m) ([raw file](https://github.com/vaadin/flow/blob/ab8f9218f63e2aa3a26815e744e4cfe231b4bd21/flow-server/src/main/java/com/vaadin/flow/server/Constants.java#L90)):*
> ```Java
>      * bundled fragments or not.
>      */
>     public static final String USE_ORIGINAL_FRONTEND_RESOURCES = "originalFrontendResources";
> ```

I propose to have this parameter in the same format as all others, with words separated by dots: `original.frontend.resources`

---

*[flow-server/src/test/java/com/vaadin/flow/server/DefaultDeploymentConfigurationTest.java, line 191 at r5](https://beta.reviewable.io/reviews/vaadin/flow/3941#-LAnDOsN6yiokMKDfv_w:-LAnDOsN6yiokMKDfv_x:bs1fkdh) ([raw file](https://github.com/vaadin/flow/blob/ab8f9218f63e2aa3a26815e744e4cfe231b4bd21/flow-server/src/test/java/com/vaadin/flow/server/DefaultDeploymentConfigurationTest.java#L191)):*
> ```Java
>         Assert.assertTrue(config.useCompiledFrontendResources());
>     }
> ```

Since the main idea of the parameter is the paths' change, would it make sense to check in both tests which pats are corresponding for es5/es6?

Any way we can check WebJars availability btw?

---

*[flow-server/src/test/java/com/vaadin/flow/server/startup/BundleFilterInitializerTest.java, line 110 at r5](https://beta.reviewable.io/reviews/vaadin/flow/3941#-LAnEBX71-DWSSE6DTjd:-LAnEBX71-DWSSE6DTje:b-3lwltl) ([raw file](https://github.com/vaadin/flow/blob/ab8f9218f63e2aa3a26815e744e4cfe231b4bd21/flow-server/src/test/java/com/vaadin/flow/server/startup/BundleFilterInitializerTest.java#L110)):*
> ```Java
>     }
> 
>     @Test(expected = IllegalArgumentException.class)
> ```

Please use `expectedException` and check the error message to be 100% sure that the exception we get is the correct one.

---

*[flow-server/src/test/java/com/vaadin/flow/server/startup/BundleFilterInitializerTest.java, line 115 at r5](https://beta.reviewable.io/reviews/vaadin/flow/3941#-LAnEU4f0ooCagegT13i:-LAnEU4f0ooCagegT13j:btzudl4) ([raw file](https://github.com/vaadin/flow/blob/ab8f9218f63e2aa3a26815e744e4cfe231b4bd21/flow-server/src/test/java/com/vaadin/flow/server/startup/BundleFilterInitializerTest.java#L115)):*
> ```Java
>     }
> 
>     public void when_bundle_disabled_doesnt_fail() {
> ```

`@Test` ?

---

*[flow-server/src/test/java/com/vaadin/flow/server/startup/BundleFilterInitializerTest.java, line 121 at r5](https://beta.reviewable.io/reviews/vaadin/flow/3941#-LAnEVJL5xmgmTav2RFd:-LAnEVJL5xmgmTav2RFe:btzudl4) ([raw file](https://github.com/vaadin/flow/blob/ab8f9218f63e2aa3a26815e744e4cfe231b4bd21/flow-server/src/test/java/com/vaadin/flow/server/startup/BundleFilterInitializerTest.java#L121)):*
> ```Java
>     }
> 
>     public void fail_when_loading_invalid_json() {
> ```

`@Test` ?

---

*[flow-tests/test-root-context/src/main/webapp/frontend-es6/vaadin-flow-bundle.html, line 1 at r5](https://beta.reviewable.io/reviews/vaadin/flow/3941#-LAnEbPGDN-kzoLKYjoR:-LAnEbPGDN-kzoLKYjoS:b-5jdnnw) ([raw file](https://github.com/vaadin/flow/blob/ab8f9218f63e2aa3a26815e744e4cfe231b4bd21/flow-tests/test-root-context/src/main/webapp/frontend-es6/vaadin-flow-bundle.html#L1)):*
> ```HTML
> 
> ```

Can you explain why do we need all those files? I thought that we don't run tests in production mode in flow repo.

If they are really needed, then I propose to use the new parameter instead, since it's easier to put it then to have 4 stub files.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3941)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java, line 270 at r5](https://reviewable.io/reviews/vaadin/flow/3941#-LAnCl4i2aui9yip1KaL:-LAqzt8eB2SFNUlMn1Tk:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/ab8f9218f63e2aa3a26815e744e4cfe231b4bd21/flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java#L270)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

> ```
>      * {@code true} or the user have not set the property at all and the
>      * production mode is enabled.
> ```

Not `true` anymore, propose to update the javadoc also.
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java, line 279 at r5](https://reviewable.io/reviews/vaadin/flow/3941#-LAnC-Wk4sejItw3rO-k:-LAr-J1lDZCgm8_dZUwc:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/ab8f9218f63e2aa3a26815e744e4cfe231b4bd21/flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java#L279)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

> ```
> bundled fragments
> ```

Not only bundled fragments. Two more places in the same javadoc below should also be fixed.
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/flow/server/Constants.java, line 90 at r5](https://reviewable.io/reviews/vaadin/flow/3941#-LAnBXASCvpjtOCm0QaX:-LAr-TkeB9G2_uGPfeTQ:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/ab8f9218f63e2aa3a26815e744e4cfe231b4bd21/flow-server/src/main/java/com/vaadin/flow/server/Constants.java#L90)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

I propose to have this parameter in the same format as all others, with words separated by dots: `original.frontend.resources`
</blockquote></details>

Done.

---

*[flow-server/src/test/java/com/vaadin/flow/server/DefaultDeploymentConfigurationTest.java, line 191 at r5](https://reviewable.io/reviews/vaadin/flow/3941#-LAnDOsN6yiokMKDfv_w:-LAr2nme6HakSVDZ5F29:b-jsr1vz) ([raw file](https://github.com/vaadin/flow/blob/ab8f9218f63e2aa3a26815e744e4cfe231b4bd21/flow-server/src/test/java/com/vaadin/flow/server/DefaultDeploymentConfigurationTest.java#L191)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Since the main idea of the parameter is the paths' change, would it make sense to check in both tests which pats are corresponding for es5/es6?

Any way we can check WebJars availability btw?
</blockquote></details>

es6 and es5 should be handled in tests related with bundling filters, I am working on that to propose a separated PR.
about checking webjars availability, I'm not sure about how to do, lately I'm not familiar with java testing.

---

*[flow-server/src/test/java/com/vaadin/flow/server/startup/BundleFilterInitializerTest.java, line 110 at r5](https://reviewable.io/reviews/vaadin/flow/3941#-LAnEBX71-DWSSE6DTjd:-LAr1NJdC1d9-CdwR67f:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/ab8f9218f63e2aa3a26815e744e4cfe231b4bd21/flow-server/src/test/java/com/vaadin/flow/server/startup/BundleFilterInitializerTest.java#L110)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Please use `expectedException` and check the error message to be 100% sure that the exception we get is the correct one.
</blockquote></details>

Done.

---

*[flow-server/src/test/java/com/vaadin/flow/server/startup/BundleFilterInitializerTest.java, line 115 at r5](https://reviewable.io/reviews/vaadin/flow/3941#-LAnEU4f0ooCagegT13i:-LAr1Nd3Dxm3l0YAatyH:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/ab8f9218f63e2aa3a26815e744e4cfe231b4bd21/flow-server/src/test/java/com/vaadin/flow/server/startup/BundleFilterInitializerTest.java#L115)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

`@Test` ?
</blockquote></details>

Done.

---

*[flow-server/src/test/java/com/vaadin/flow/server/startup/BundleFilterInitializerTest.java, line 121 at r5](https://reviewable.io/reviews/vaadin/flow/3941#-LAnEVJL5xmgmTav2RFd:-LAr1O3J5Svr6J4dvf4e:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/ab8f9218f63e2aa3a26815e744e4cfe231b4bd21/flow-server/src/test/java/com/vaadin/flow/server/startup/BundleFilterInitializerTest.java#L121)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

`@Test` ?
</blockquote></details>

Done.

---

*[flow-tests/test-root-context/src/main/webapp/frontend-es6/vaadin-flow-bundle.html, line 1 at r5](https://reviewable.io/reviews/vaadin/flow/3941#-LAnEbPGDN-kzoLKYjoR:-LAr1Vg77lv6xZxnA85K:b4g3635) ([raw file](https://github.com/vaadin/flow/blob/ab8f9218f63e2aa3a26815e744e4cfe231b4bd21/flow-tests/test-root-context/src/main/webapp/frontend-es6/vaadin-flow-bundle.html#L1)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Can you explain why do we need all those files? I thought that we don't run tests in production mode in flow repo.

If they are really needed, then I propose to use the new parameter instead, since it's easier to put it then to have 4 stub files.
</blockquote></details>

The problem is that when manifest and main bundle files are not found, server raises an exception and does not continue.
Obviously, before there were no failure and the test flow continued.

We can set the new parameter in `jetty:run` as I tried first because most test does not care about bundle filtering, but there are some tests testing the bundling that do not work otherwise, and we cannot force from test that the servlet paramter changes.

In my opinion, the IT environment must be complete. I don't see a huge problem on maintaining these files in the same way we need to maintain other production resources

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/3941)*

**Comment by SomeoneToIgnore** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-tests/test-root-context/src/main/webapp/frontend-es6/vaadin-flow-bundle.html, line 1 at r5](https://reviewable.io/reviews/vaadin/flow/3941#-LAnEbPGDN-kzoLKYjoR:-LAr4-2r75myMu88x3W_:b-lf1b3i) ([raw file](https://github.com/vaadin/flow/blob/ab8f9218f63e2aa3a26815e744e4cfe231b4bd21/flow-tests/test-root-context/src/main/webapp/frontend-es6/vaadin-flow-bundle.html#L1)):*
> there are some tests testing the bundling that do not work otherwise

Ok, so we need the bundles in those tests, got it.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/3941#-:-LAr42pKB9hS2wdwLbzs:bnfp4nl)*

**Pull request merged**
