### PR TITLE
Make generator to remove HasStyle from dialog and notification

### PR DESCRIPTION
**Pull request by ZheSun88**
Add and fix tests

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3995)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/ComponentGenerator.java, line 518 at r1](https://reviewable.io/reviews/vaadin/flow/3995#-LAw27aw8_BVsoJ2GSv1:-LAw27aw8_BVsoJ2GSv2:bfbqh6h) ([raw file](https://github.com/vaadin/flow/blob/e51ecbcbd31a54e87e4e6421271bfbf3e374aa43/flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/ComponentGenerator.java#L518)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>         if (!ExclusionRegistry.isBehaviorOrMixinExcluded(metadata.getTag(),
>                 HasStyle.class.getName())) {
>             javaClass.addInterface(HasStyle.class);
>         }
> ```
</details>


Does it make sense to reuse `isBehaviorOrMixinExcluded` method ?
I'm not sure.
I'm not familiar with the derails of the generator but behavior or mix-ins are Polymer concepts here I think.
We are trying to exclude Java concepts .
I would expect another method which checks `Class<?>`  instead of `String` (as a FQN).
And one more generic exclusion filter which check the `Class<?>` via `Map<String,Class<?>>` in the 
`ExclusionRegistry` to avoid a mixture between Java and Polymer JS.

@gilberto-torrezan , what do you think ?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/3995)*

**Comment by gilberto-torrezan** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/ComponentGenerator.java, line 518 at r1](https://reviewable.io/reviews/vaadin/flow/3995#-LAw27aw8_BVsoJ2GSv1:-LAwHUGbEj1y8CSGeQJz:b-v45k8l) ([raw file](https://github.com/vaadin/flow/blob/e51ecbcbd31a54e87e4e6421271bfbf3e374aa43/flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/ComponentGenerator.java#L518)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
>         if (!ExclusionRegistry.isBehaviorOrMixinExcluded(metadata.getTag(),
>                 HasStyle.class.getName())) {
>             javaClass.addInterface(HasStyle.class);
>         }
> ```

Does it make sense to reuse `isBehaviorOrMixinExcluded` method ?
I'm not sure.
I'm not familiar with the derails of the generator but behavior or mix-ins are Polymer concepts here I think.
We are trying to exclude Java concepts .
I would expect another method which checks `Class<?>`  instead of `String` (as a FQN).
And one more generic exclusion filter which check the `Class<?>` via `Map<String,Class<?>>` in the 
`ExclusionRegistry` to avoid a mixture between Java and Polymer JS.

@gilberto-torrezan , what do you think ?
</blockquote></details>

The ideal design would be a separate Registry (or method) to handle Java cases (not mixed with Polymer ones). Since `HasValue` is the only case we have now, I suggested to just reuse the registry.

But yes, a separate mechanism that handles Classes and not Strings would be better.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/3995)*

**Comment by ZheSun88** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/ComponentGenerator.java, line 518 at r1](https://reviewable.io/reviews/vaadin/flow/3995#-LAw27aw8_BVsoJ2GSv1:-LAwIHI_69XNHmbX6Q0z:bh3cigy) ([raw file](https://github.com/vaadin/flow/blob/e51ecbcbd31a54e87e4e6421271bfbf3e374aa43/flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/ComponentGenerator.java#L518)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

The ideal design would be a separate Registry (or method) to handle Java cases (not mixed with Polymer ones). Since `HasValue` is the only case we have now, I suggested to just reuse the registry.

But yes, a separate mechanism that handles Classes and not Strings would be better.
</blockquote></details>

I have one question, maybe a little bit off-topic.. Will we remove the `hasStyle` from `dialog` and `notification` permanently?  or just for some time... 

what will be the usage case in the future to have the separate method to deal with this?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/3995)*

**Comment by denis-anisimov** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/3995#-:-LAwQDXn1Dr2gvGNO7ke:bnfp4nl)*

**Comment by denis-anisimov** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/3995#-:-LAwQghm5n7uWa1Pqgmk:bnfp4nl)*

**Comment by gilberto-torrezan** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/registry/ExclusionRegistry.java, line 40 at r3](https://reviewable.io/reviews/vaadin/flow/3995#-LAwR2ui4dzp-ZmgmeTQ:-LAwR2ui4dzp-ZmgmeTR:b-fssva3) ([raw file](https://github.com/vaadin/flow/blob/6cd080c57a1c050fa4647b6e1ecc724b5566c5ef/flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/registry/ExclusionRegistry.java#L40)):*
> ```Java
>     private static final Map<String, Set<String>> METHOD_EXCLUSION_REGISTRY = new HashMap<>();
>     private static final Map<String, Set<String>> BEHAVIOR_EXCLUSION_REGISTRY = new HashMap<>();
>     private static final Map<String, Set<String>> INTERFACE_EXCLUSION_REGISTRY = new HashMap<>();
> ```

Use a `Map<String, Set<Class<?>>` instead.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/3995)*

**Comment by gilberto-torrezan** [comment]
Reviewed 3 of 5 files at r1, 2 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/registry/ExclusionRegistry.java, line 40 at r3](https://reviewable.io/reviews/vaadin/flow/3995#-LAwR2ui4dzp-ZmgmeTQ:-LAwRVR49v6EVZ5_9N4y:b1r2kkr) ([raw file](https://github.com/vaadin/flow/blob/6cd080c57a1c050fa4647b6e1ecc724b5566c5ef/flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/registry/ExclusionRegistry.java#L40)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Use a `Map<String, Set<Class<?>>` instead.
</blockquote></details>

Actually nevermind, it would change the structure of the entire class.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/3995)*

**Pull request merged**
