### PR TITLE
Add the TemplateRenderer class, change the Grid to use the renderers.

### PR DESCRIPTION
**Pull request by gilberto-torrezan**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/2646)

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
Reviewed 23 of 23 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/views/GridView.java, line 260 at r1](https://reviewable.io:443/reviews/vaadin/flow/2646#-Kw6SOffiuGH0oSPyGg7:-Kw6SOffiuGH0oSPyGg8:b-z58q7m) ([raw file](https://github.com/vaadin/flow/blob/e4071c0a0fa8ec3aa0d3448a36aad9740d73e2f2/flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/views/GridView.java#L260)):*
> ```Java
> 
>         grid.addColumn("Name", Person::getName);
>         grid.addColumn("Age", Person::getAge);
> ```

Any reason to do this in this place only? I see 4 more places with similar declaration.

---

*[flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/views/GridView.java, line 262 at r1](https://reviewable.io:443/reviews/vaadin/flow/2646#-Kw6SaAgf7J8f0eXto0Q:-Kw6SaAgf7J8f0eXto0R:bf5sgzt) ([raw file](https://github.com/vaadin/flow/blob/e4071c0a0fa8ec3aa0d3448a36aad9740d73e2f2/flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/views/GridView.java#L262)):*
> ```Java
>         grid.addColumn("Age", Person::getAge);
> 
>         grid.setSelectionMode(Grid.SelectionMode.NONE);
> ```

`SelectionMode` is already imported, do you really need to do this?
There is at least one place with plain `SelectionMode` usage left, why not change that also and remove the import?

---

*[flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/views/GridView.java, line 280 at r1](https://reviewable.io:443/reviews/vaadin/flow/2646#-Kw6alYUMs58KJIFpDFm:-Kw6alYUMs58KJIFpDFn:bejb03n) ([raw file](https://github.com/vaadin/flow/blob/e4071c0a0fa8ec3aa0d3448a36aad9740d73e2f2/flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/views/GridView.java#L280)):*
> \"

Would it be easier to use single quotes in such cases?
IMO, improves the readability a bit.

---

*[flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/views/GridView.java, line 286 at r1](https://reviewable.io:443/reviews/vaadin/flow/2646#-Kw6Tpb6tGiQoj-cuczq:-Kw6Tpb6tGiQoj-cuczr:b7rpbw2) ([raw file](https://github.com/vaadin/flow/blob/e4071c0a0fa8ec3aa0d3448a36aad9740d73e2f2/flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/views/GridView.java#L286)):*
> Youcan

Typo.

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 503 at r1](https://reviewable.io:443/reviews/vaadin/flow/2646#-Kw6YxRv_5bGguHfhSjt:-Kw6YxRv_5bGguHfhSju:bhlxl8s) ([raw file](https://github.com/vaadin/flow/blob/e4071c0a0fa8ec3aa0d3448a36aad9740d73e2f2/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L503)):*
> In-memory sorting

Can you please elaborate on what we sort here?

---

*[flow-server/src/main/java/com/vaadin/ui/renderers/TemplateRenderer.java, line 58 at r1](https://reviewable.io:443/reviews/vaadin/flow/2646#-Kw6_4Chi0RjausSFUfC:-Kw6_4Chi0RjausSFUfD:bfgridt) ([raw file](https://github.com/vaadin/flow/blob/e4071c0a0fa8ec3aa0d3448a36aad9740d73e2f2/flow-server/src/main/java/com/vaadin/ui/renderers/TemplateRenderer.java#L58)):*
> ```Java
>      * TemplateRenderer.of("[[index]]");
>      * 
>      *  // Prints the property of an item
> ```

Just in case you'd like to fix this, here is an extra space and '{@code' thingie is actually messing up `pre` by adding an extra space before first comment.
Same for all other combination of `pre` and `@{code` here.

---

*[flow-server/src/main/java/com/vaadin/ui/renderers/TemplateRenderer.java, line 88 at r1](https://reviewable.io:443/reviews/vaadin/flow/2646#-Kw6ZbtGNDf5KQdqYwsR:-Kw6ZbtGNDf5KQdqYwsS:b-w3hkvz) ([raw file](https://github.com/vaadin/flow/blob/e4071c0a0fa8ec3aa0d3448a36aad9740d73e2f2/flow-server/src/main/java/com/vaadin/ui/renderers/TemplateRenderer.java#L88)):*
> ```Java
>      * // Regular property
>      * TemplateRenderer.<Person> of("<div>Name: [[item.name]]</div>")
>      * 			.withProperty("name", Person::getName);
> ```

Tabs, a few more in the other places of the file.

---

*[flow-server/src/main/java/com/vaadin/ui/renderers/TemplateRenderer.java, line 90 at r1](https://reviewable.io:443/reviews/vaadin/flow/2646#-Kw6_ah_DGxMuNw4INnT:-Kw6_ah_DGxMuNw4INnU:b2js4h9) ([raw file](https://github.com/vaadin/flow/blob/e4071c0a0fa8ec3aa0d3448a36aad9740d73e2f2/flow-server/src/main/java/com/vaadin/ui/renderers/TemplateRenderer.java#L90)):*
> Adress

Typo.

---

*[flow-server/src/main/java/com/vaadin/ui/renderers/TemplateRenderer.java, line 108 at r1](https://reviewable.io:443/reviews/vaadin/flow/2646#-Kw6a7KmAp7O6L3koq_n:-Kw6a7KmAp7O6L3koq_o:bfbrilg) ([raw file](https://github.com/vaadin/flow/blob/e4071c0a0fa8ec3aa0d3448a36aad9740d73e2f2/flow-server/src/main/java/com/vaadin/ui/renderers/TemplateRenderer.java#L108)):*
> ```Java
>      *            the name of the property used inside the template
>      * @param provider
>      *            a {@link ValueProvider} that provides the actual
> ```

The phrase looks unfinished.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2646)*

**Comment by gilberto-torrezan** [comment]
Review status: 17 of 20 files reviewed at latest revision, 9 unresolved discussions.

---

*[flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/views/GridView.java, line 260 at r1](https://reviewable.io:443/reviews/vaadin/flow/2646#-Kw6SOffiuGH0oSPyGg7:-Kw8vogc63hd3d6RxThY:b-fv6000) ([raw file](https://github.com/vaadin/flow/blob/e4071c0a0fa8ec3aa0d3448a36aad9740d73e2f2/flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/views/GridView.java#L260)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Any reason to do this in this place only? I see 4 more places with similar declaration.
</blockquote></details>

A very important reason: I forgot to change the others =P
Done.

---

*[flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/views/GridView.java, line 262 at r1](https://reviewable.io:443/reviews/vaadin/flow/2646#-Kw6SaAgf7J8f0eXto0Q:-Kw8w1-q-oBhw5wcJmQ1:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/e4071c0a0fa8ec3aa0d3448a36aad9740d73e2f2/flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/views/GridView.java#L262)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

`SelectionMode` is already imported, do you really need to do this?
There is at least one place with plain `SelectionMode` usage left, why not change that also and remove the import?
</blockquote></details>

Done.

---

*[flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/views/GridView.java, line 280 at r1](https://reviewable.io:443/reviews/vaadin/flow/2646#-Kw6alYUMs58KJIFpDFm:-Kw8w2AbZUbCLBKtvxPO:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/e4071c0a0fa8ec3aa0d3448a36aad9740d73e2f2/flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/views/GridView.java#L280)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

> \"

Would it be easier to use single quotes in such cases?
IMO, improves the readability a bit.
</blockquote></details>

Done.

---

*[flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/views/GridView.java, line 286 at r1](https://reviewable.io:443/reviews/vaadin/flow/2646#-Kw6Tpb6tGiQoj-cuczq:-Kw8w4ZPnkTkO6PmW7W3:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/e4071c0a0fa8ec3aa0d3448a36aad9740d73e2f2/flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/views/GridView.java#L286)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

> Youcan

Typo.
</blockquote></details>

Done.

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 503 at r1](https://reviewable.io:443/reviews/vaadin/flow/2646#-Kw6YxRv_5bGguHfhSjt:-Kw8wq5VVHGYX8Ied9ic:bhpa9n9) ([raw file](https://github.com/vaadin/flow/blob/e4071c0a0fa8ec3aa0d3448a36aad9740d73e2f2/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L503)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

> In-memory sorting

Can you please elaborate on what we sort here?
</blockquote></details>

I copied that sentence from the method above it (`addColumn` with `ValueProvider`), which I think was copied from the Grid from FW8.
None of them make any sense really. So I removed both.

---

*[flow-server/src/main/java/com/vaadin/ui/renderers/TemplateRenderer.java, line 58 at r1](https://reviewable.io:443/reviews/vaadin/flow/2646#-Kw6_4Chi0RjausSFUfC:-Kw8xwkbS4m5JjXJ9IZj:b-ts0ahh) ([raw file](https://github.com/vaadin/flow/blob/e4071c0a0fa8ec3aa0d3448a36aad9740d73e2f2/flow-server/src/main/java/com/vaadin/ui/renderers/TemplateRenderer.java#L58)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Just in case you'd like to fix this, here is an extra space and '{@code' thingie is actually messing up `pre` by adding an extra space before first comment.
Same for all other combination of `pre` and `@{code` here.
</blockquote></details>

Fixed the leading space on the command, but I didn't understand the problem between `@code` and `<pre>` - they seem to work in Eclipse.

---

*[flow-server/src/main/java/com/vaadin/ui/renderers/TemplateRenderer.java, line 88 at r1](https://reviewable.io:443/reviews/vaadin/flow/2646#-Kw6ZbtGNDf5KQdqYwsR:-Kw8yEgDuW969zFPBmnX:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/e4071c0a0fa8ec3aa0d3448a36aad9740d73e2f2/flow-server/src/main/java/com/vaadin/ui/renderers/TemplateRenderer.java#L88)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Tabs, a few more in the other places of the file.
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/ui/renderers/TemplateRenderer.java, line 90 at r1](https://reviewable.io:443/reviews/vaadin/flow/2646#-Kw6_ah_DGxMuNw4INnT:-Kw8yF06cVHoEUNhRgKA:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/e4071c0a0fa8ec3aa0d3448a36aad9740d73e2f2/flow-server/src/main/java/com/vaadin/ui/renderers/TemplateRenderer.java#L90)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

> Adress

Typo.
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/ui/renderers/TemplateRenderer.java, line 108 at r1](https://reviewable.io:443/reviews/vaadin/flow/2646#-Kw6a7KmAp7O6L3koq_n:-Kw8yMLZQey8n3n_q6SE:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/e4071c0a0fa8ec3aa0d3448a36aad9740d73e2f2/flow-server/src/main/java/com/vaadin/ui/renderers/TemplateRenderer.java#L108)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

The phrase looks unfinished.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2646)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-server/src/main/java/com/vaadin/ui/renderers/TemplateRenderer.java, line 58 at r1](https://reviewable.io:443/reviews/vaadin/flow/2646#-Kw6_4Chi0RjausSFUfC:-Kw9A19q-nGCIYeFXLux:b-rxsig5) ([raw file](https://github.com/vaadin/flow/blob/e4071c0a0fa8ec3aa0d3448a36aad9740d73e2f2/flow-server/src/main/java/com/vaadin/ui/renderers/TemplateRenderer.java#L58)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Fixed the leading space on the command, but I didn't understand the problem between `@code` and `<pre>` - they seem to work in Eclipse.
</blockquote></details>

Funny, my ide displays comments this way:


Anyway, I don't really think it's that important.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2646)*

**Comment by SomeoneToIgnore** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2646#-:-Kw9AuUt2xanIMCwWYAH:bnfp4nl)*

**Comment by SomeoneToIgnore** [comment]
Have restarted the build.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2646#-:-Kw9Az3Gwqu-VBDDGw_w:bj02dh0)*

**Pull request merged**
