### PR TITLE
Validate return code in ErrorStateRenderer.

### PR DESCRIPTION
**Pull request by caalador**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/2733)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/router/ErrorStateRenderer.java, line 148 at r2](https://reviewable.io:443/reviews/vaadin/flow/2733#-Kwt0qUlqHriyMNJffa_:-Kwt0qUlqHriyMNJffaa:b-73mcl9) ([raw file](https://github.com/vaadin/flow/blob/8ff087d73d0e6c5353b0823087c828e10bfd399b/flow-server/src/main/java/com/vaadin/router/ErrorStateRenderer.java#L148)):*
> targetClass.getSimpleName()

Simple name could be not enough to identify the class.
Would be better to use FQN.

---

*[flow-server/src/main/java/com/vaadin/util/ReflectTools.java, line 668 at r2](https://reviewable.io:443/reviews/vaadin/flow/2733#-Kwt10_UDQj2Q5YitKhB:-Kwt10_UDQj2Q5YitKhC:b-7xrzvp) ([raw file](https://github.com/vaadin/flow/blob/8ff087d73d0e6c5353b0823087c828e10bfd399b/flow-server/src/main/java/com/vaadin/util/ReflectTools.java#L668)):*
> constantsClass

confusing name

---

*[flow-server/src/main/java/com/vaadin/util/ReflectTools.java, line 682 at r2](https://reviewable.io:443/reviews/vaadin/flow/2733#-Kwt1CwF8Rit3PkjAuYI:-Kwt1CwF8Rit3PkjAuYJ:b5aimd3) ([raw file](https://github.com/vaadin/flow/blob/8ff087d73d0e6c5353b0823087c828e10bfd399b/flow-server/src/main/java/com/vaadin/util/ReflectTools.java#L682)):*
> // Ignore this exception. Public fields should always be
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>
>                     // accessible.
>                     Logger.getLogger(ReflectTools.class.getName()).log(
>                             Level.WARNING,
>                             "Received access exception for public field '"
>                                     + field.getName() + "' in class '"
>                                     + constantsClass.getSimpleName() + "'",
>                             e);
</details>

Should it be an assert then ?

---

*[flow-server/src/main/java/com/vaadin/util/ReflectTools.java, line 691 at r2](https://reviewable.io:443/reviews/vaadin/flow/2733#-Kwt1LboWONl8GXSmg4B:-Kwt1LboWONl8GXSmg4C:b-jir5k3) ([raw file](https://github.com/vaadin/flow/blob/8ff087d73d0e6c5353b0823087c828e10bfd399b/flow-server/src/main/java/com/vaadin/util/ReflectTools.java#L691)):*
> getPublicStaticFinalFields

May be just `getConstants`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2733)*

**Comment by caalador** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[flow-server/src/main/java/com/vaadin/router/ErrorStateRenderer.java, line 148 at r2](https://reviewable.io:443/reviews/vaadin/flow/2733#-Kwt0qUlqHriyMNJffa_:-KwtAPvE8bedq0McDonv:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/8ff087d73d0e6c5353b0823087c828e10bfd399b/flow-server/src/main/java/com/vaadin/router/ErrorStateRenderer.java#L148)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> targetClass.getSimpleName()

Simple name could be not enough to identify the class.
Would be better to use FQN.

</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/util/ReflectTools.java, line 668 at r2](https://reviewable.io:443/reviews/vaadin/flow/2733#-Kwt10_UDQj2Q5YitKhB:-KwtAcndy0WZJfXtkzL6:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/8ff087d73d0e6c5353b0823087c828e10bfd399b/flow-server/src/main/java/com/vaadin/util/ReflectTools.java#L668)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> constantsClass

confusing name
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/util/ReflectTools.java, line 682 at r2](https://reviewable.io:443/reviews/vaadin/flow/2733#-Kwt1CwF8Rit3PkjAuYI:-KwtC0Z8Spp7ay7C40b8:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/8ff087d73d0e6c5353b0823087c828e10bfd399b/flow-server/src/main/java/com/vaadin/util/ReflectTools.java#L682)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> // Ignore this exception. Public fields should always be
>                     // accessible.
>                     Logger.getLogger(ReflectTools.class.getName()).log(
>                             Level.WARNING,
>                             "Received access exception for public field '"
>                                     + field.getName() + "' in class '"
>                                     + constantsClass.getSimpleName() + "'",
>                             e);

Should it be an assert then ?
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/util/ReflectTools.java, line 691 at r2](https://reviewable.io:443/reviews/vaadin/flow/2733#-Kwt1LboWONl8GXSmg4B:-KwtBiNnTCk1vpUBmTsv:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/8ff087d73d0e6c5353b0823087c828e10bfd399b/flow-server/src/main/java/com/vaadin/util/ReflectTools.java#L691)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> getPublicStaticFinalFields

May be just `getConstants`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2733)*

**Comment by denis-anisimov** [comment]
Reviewed 2 of 3 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2733)*

**Comment by torok-peter** [comment]
Reviewed 1 of 4 files at r1, 2 of 3 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[flow-server/src/main/java/com/vaadin/router/ErrorStateRenderer.java, line 143 at r4](https://reviewable.io:443/reviews/vaadin/flow/2733#-KwuB6wRRGO7rGdgViqU:-KwuB6wSs9hjzqcn7GNh:b-v2hnpb) ([raw file](https://github.com/vaadin/flow/blob/d585ab166c4113c694a213272c2842183ea8d64e/flow-server/src/main/java/com/vaadin/router/ErrorStateRenderer.java#L143)):*
> ```Java
>     private void validateStatusCode(int statusCode,
>             Class<? extends Component> targetClass) {
>         List<Integer> statusCodes = ReflectTools
> ```

It would make sense to compute this once at startup and store it as a constant - would save both CPU cycles and memory. Although this may be premature optimization.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2733)*

**Comment by caalador** [comment]
Review status: 3 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/router/ErrorStateRenderer.java, line 143 at r4](https://reviewable.io:443/reviews/vaadin/flow/2733#-KwuB6wRRGO7rGdgViqU:-Kx6Wes4quX8N7RpNuvg:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/d585ab166c4113c694a213272c2842183ea8d64e/flow-server/src/main/java/com/vaadin/router/ErrorStateRenderer.java#L143)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

It would make sense to compute this once at startup and store it as a constant - would save both CPU cycles and memory. Although this may be premature optimization.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2733)*

**Comment by torok-peter** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---

*[flow-server/src/main/java/com/vaadin/router/ErrorStateRenderer.java, line 144 at r5](https://reviewable.io:443/reviews/vaadin/flow/2733#-Kx75IcTBdHnHWsCLMkn:-Kx75IcTBdHnHWsCLMko:bkg9nvo) ([raw file](https://github.com/vaadin/flow/blob/6f1ec2cb71795dbd9558a13b98f0c1d6352c5db0/flow-server/src/main/java/com/vaadin/router/ErrorStateRenderer.java#L144)):*
> ```Java
>     private void validateStatusCode(int statusCode,
>             Class<? extends Component> targetClass) {
>         if (statusCodes == null) {
> ```

It could be simply initialized eagerly at the declaration, to simplify things, avoid race conditions and make Sonar happy :-)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2733)*

**Comment by caalador** [comment]
Review status: 3 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/router/ErrorStateRenderer.java, line 144 at r5](https://reviewable.io:443/reviews/vaadin/flow/2733#-Kx75IcTBdHnHWsCLMkn:-KxBeAO-ZBXEXLDcZVfh:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/cec42651fd73b968826c0a6313cc65c7a973098e/flow-server/src/main/java/com/vaadin/router/ErrorStateRenderer.java#L144)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

It could be simply initialized eagerly at the declaration, to simplify things, avoid race conditions and make Sonar happy :-)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2733)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/router/ErrorStateRenderer.java, line 46 at r6](https://reviewable.io:443/reviews/vaadin/flow/2733#-KxBui-k1o0qoq1BTpmJ:-KxBui-k1o0qoq1BTpmK:b-tqrq7o) ([raw file](https://github.com/vaadin/flow/blob/abbeb4e2088e9af240c897623ea43999ff07e1d5/flow-server/src/main/java/com/vaadin/router/ErrorStateRenderer.java#L46)):*
> ;s

compilation error

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2733)*

**Comment by torok-peter** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2733)*

**Comment by caalador** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/router/ErrorStateRenderer.java, line 46 at r6](https://reviewable.io:443/reviews/vaadin/flow/2733#-KxBui-k1o0qoq1BTpmJ:-KxC1YnRmUgemeo_gTSq:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/abbeb4e2088e9af240c897623ea43999ff07e1d5/flow-server/src/main/java/com/vaadin/router/ErrorStateRenderer.java#L46)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ;s

compilation error
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2733)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2733)*

**Comment by torok-peter** [comment]
Reviewed 1 of 1 files at r7.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2733)*

**Pull request merged**
