### PR TITLE
Look for parameter annotations on the more specific method

### PR DESCRIPTION
**Pull request by Legioth**
Eclipse only puts parameter annotations on the more specific method, but
not on the method declared for the raw type.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/2561)

### CODE REVIEW

**Comment by Legioth** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[flow-server/src/main/java/com/vaadin/router/HasUrlParameter.java, line 137 at r1](https://reviewable.io:443/reviews/vaadin/flow/2561#-KvNjy1YtD64jmbasWcU:-KvVfsvmaMfpJH0DNABv:bo4w1sx) ([raw file](https://github.com/vaadin/flow/blob/d4ba104a401240b75b509f740e9fc43089ae5c9a/flow-server/src/main/java/com/vaadin/router/HasUrlParameter.java#L137)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> String methodName = "setParameter";
>             assert methodName.equals(ReflectTools
>                     .getFunctionalMethod(HasUrlParameter.class).getName());

It has been intentionally done to avoid hardcoded string.
Don't see any reason to return back hardcoded method names.
</blockquote></details>

In my opinion, the code is much easier to understand when the name is explicitly written out there (and it runs slightly more quickly as an added bonus). At the same time, there's the `assert` here that verifies that we will not accidentally break anything by changing the name of that method without also updating the hardcoded string.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2561)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-server/src/main/java/com/vaadin/router/HasUrlParameter.java, line 137 at r1](https://reviewable.io:443/reviews/vaadin/flow/2561#-KvNjy1YtD64jmbasWcU:-KvVlQ7pp8d62u0vsDRY:b-8ikzel) ([raw file](https://github.com/vaadin/flow/blob/6db65794fb3f7b707c8e7886aabfaa18083ed16e/flow-server/src/main/java/com/vaadin/router/HasUrlParameter.java#L137)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

In my opinion, the code is much easier to understand when the name is explicitly written out there (and it runs slightly more quickly as an added bonus). At the same time, there's the `assert` here that verifies that we will not accidentally break anything by changing the name of that method without also updating the hardcoded string.
</blockquote></details>

Up to you but I don't see how the method name makes the code easier to understand.
It has no sense without it's context which is the `HasUrlParameter` class and once you go there you don't care about method name anymore.

Assertion just allows to identify the change. In case of method rename one still has to go here  because of _RUNTIME_ failure and fix it.
Without having this hardcoded nothing is needed to be done at all.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2561)*

**Comment by Legioth** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[flow-server/src/main/java/com/vaadin/router/HasUrlParameter.java, line 137 at r1](https://reviewable.io:443/reviews/vaadin/flow/2561#-KvNjy1YtD64jmbasWcU:-KvXlACuzvrcUKHlzyjj:b-u316g0) ([raw file](https://github.com/vaadin/flow/blob/6db65794fb3f7b707c8e7886aabfaa18083ed16e/flow-server/src/main/java/com/vaadin/router/HasUrlParameter.java#L137)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Up to you but I don't see how the method name makes the code easier to understand.
It has no sense without it's context which is the `HasUrlParameter` class and once you go there you don't care about method name anymore.

Assertion just allows to identify the change. In case of method rename one still has to go here  because of _RUNTIME_ failure and fix it.
Without having this hardcoded nothing is needed to be done at all.
</blockquote></details>

I think it's fine that some additional effort would be required if we'd want to make that kind of backwards incompatible change to the API.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2561)*

**Comment by Legioth** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2561)*

**Pull request merged**
