### PR TITLE
Make sure executeJavascript calls are pushed

### PR DESCRIPTION
**Pull request by Artur-**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3811)

### CODE REVIEW

**Comment by Legioth** [comment]
Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/flow/3811#-L9EHJ9UDXmT8TcNPnV3:-L9EHJ9UDXmT8TcNPnV4:bvycipe) (no related file):*
Please also test for `Element.callFunction` which will probably not work with the current implementation because of the way the execution ends up in the `beforeClientResponse` queue that isn't checked in the `push()` logic.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3811)*

**Comment by Artur-** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/flow/3811#-L9EHJ9UDXmT8TcNPnV3:-L9EKOmh77nm9WNQ-FDs:b-2ivtdj) (no related file):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

Please also test for `Element.callFunction` which will probably not work with the current implementation because of the way the execution ends up in the `beforeClientResponse` queue that isn't checked in the `push()` logic.
</blockquote></details>

Why does a separate issue block this PR?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3811)*

**Comment by Legioth** [comment]
*[a discussion](https://beta.reviewable.io/reviews/vaadin/flow/3811#-L9EHJ9UDXmT8TcNPnV3:-L9EStcp8Y6oW247Eyos:bzn66k) (no related file):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Why does a separate issue block this PR?
</blockquote></details>

Sure, the other thing that is essentially the same from the user's point of view can also be fixed as a separate PR.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3811)*

**Comment by Artur-** [comment]
Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/flow/3811#-L9EHJ9UDXmT8TcNPnV3:-L9KRqctBWuK_Orm-WbB:bq4gosx) (no related file):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

Sure, the other thing that is essentially the same from the user's point of view can also be fixed as a separate PR.
</blockquote></details>

Added fix as this has not yet been merged

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3811)*

**Comment by Legioth** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/flow/3811#-L9EHJ9UDXmT8TcNPnV3:-L9KZygy9nFaPcqM1c1n:bmuiu4c) (no related file):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Added fix as this has not yet been merged
</blockquote></details>

Seems like the IT wasn't updated to actually test the new case?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3811)*

**Comment by Artur-** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/flow/3811#-L9EHJ9UDXmT8TcNPnV3:-L9Kg3mI6thbYFgTkVt1:ba86dam) (no related file):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

Seems like the IT wasn't updated to actually test the new case?
</blockquote></details>

How so?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3811)*

**Comment by caalador** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3811#-:-L9jA_agA5bVv20Ock9K:bnfp4nl)*

**Pull request merged**
