### PR TITLE
modify the configuration for selenium

### PR DESCRIPTION
**Pull request by ZheSun88**
so we dont need to push driver.xml file to each component

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/2821)

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[flow-components-parent/flow-component/.gitignore, line 2 at r2](https://reviewable.io:443/reviews/vaadin/flow/2821#-Kxr0eRlmPbvt346Y3nq:-Kxr0eRmrhau6AujNwfL:bvt9mpa) ([raw file](https://github.com/vaadin/flow/blob/a323a8da7c1b897ca04d0b18569fba4254fbbab1/flow-components-parent/flow-component/.gitignore#L2)):*
I see that you've specified 
> <rootStandaloneServerDirectory>${project.build.directory}/driver</rootStandaloneServerDirectory> 
> <downloadedZipFileDirectory>${project.build.directory}/driver_zips</downloadedZipFileDirectory>

this directories for the plugin, and here the default are ignored, why?

---

*[flow-components-parent/flow-component/pom.xml, line 100 at r2](https://reviewable.io:443/reviews/vaadin/flow/2821#-Kxr12afEInOh4GcvlOc:-Kxr12afEInOh4GcvlOd:bbv1fi1) ([raw file](https://github.com/vaadin/flow/blob/a323a8da7c1b897ca04d0b18569fba4254fbbab1/flow-components-parent/flow-component/pom.xml#L100)):*
> ```XML
>                 <executions>
>                     <execution>
>                         
> ```

If it does, why specify it?

---

*[flow-components-parent/flow-component/pom.xml, line 108 at r2](https://reviewable.io:443/reviews/vaadin/flow/2821#-Kxr0xMfFVQYP42uxSFb:-Kxr0xMfFVQYP42uxSFc:bfv1n1x) ([raw file](https://github.com/vaadin/flow/blob/a323a8da7c1b897ca04d0b18569fba4254fbbab1/flow-components-parent/flow-component/pom.xml#L108)):*
> ```XML
>                             <url>https://raw.githubusercontent.com/vaadin/flow/master/drivers.xml</url>
>                             <outputFileName>drivers.xml</outputFileName>
>                             
> ```

What's the purpose of this comment?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2821)*

**Comment by SomeoneToIgnore** [comment]
*[flow-components-parent/flow-component/pom.xml, line 96 at r2](https://reviewable.io:443/reviews/vaadin/flow/2821#-Kxr1ozP2R90jT5oE7lc:-Kxr1ozP2R90jT5oE7ld:b-2k0znb) ([raw file](https://github.com/vaadin/flow/blob/a323a8da7c1b897ca04d0b18569fba4254fbbab1/flow-components-parent/flow-component/pom.xml#L96)):*
> ```XML
>             <plugin>
>                 <groupId>com.googlecode.maven-download-plugin</groupId>
>                 <artifactId>download-maven-plugin</artifactId>
> ```

Since we inherit parent pom now, would it make sense to configure `selenium-standalone-server-plugin` so that it does not need any `drivers.xml`?
It looks like it's possible: https://github.com/Ardesco/selenium-standalone-server-plugin#advanced-usage

This will allow us to have one less plugin in the build.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2821)*

**Comment by ZheSun88** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-components-parent/flow-component/.gitignore, line 2 at r2](https://reviewable.io:443/reviews/vaadin/flow/2821#-Kxr0eRlmPbvt346Y3nq:-Kxr2CBF_v3gQW7QADFz:b-23cds4) ([raw file](https://github.com/vaadin/flow/blob/a323a8da7c1b897ca04d0b18569fba4254fbbab1/flow-components-parent/flow-component/.gitignore#L2)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

I see that you've specified 
> <rootStandaloneServerDirectory>${project.build.directory}/driver</rootStandaloneServerDirectory> 
> <downloadedZipFileDirectory>${project.build.directory}/driver_zips</downloadedZipFileDirectory>

this directories for the plugin, and here the default are ignored, why?
</blockquote></details>

oops.. my mistake... i will remove it 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2821)*

**Comment by caalador** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[flow-components-parent/flow-component/pom.xml, line 96 at r2](https://reviewable.io:443/reviews/vaadin/flow/2821#-Kxr1ozP2R90jT5oE7lc:-KxrGOSAyerN0Y6bxfWB:bb9v7bo) ([raw file](https://github.com/vaadin/flow/blob/a323a8da7c1b897ca04d0b18569fba4254fbbab1/flow-components-parent/flow-component/pom.xml#L96)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Since we inherit parent pom now, would it make sense to configure `selenium-standalone-server-plugin` so that it does not need any `drivers.xml`?
It looks like it's possible: https://github.com/Ardesco/selenium-standalone-server-plugin#advanced-usage

This will allow us to have one less plugin in the build.
</blockquote></details>

How do you specify it to only download the chrome driver?

---

*[flow-components-parent/flow-component/pom.xml, line 100 at r2](https://reviewable.io:443/reviews/vaadin/flow/2821#-Kxr12afEInOh4GcvlOc:-KxrGSoolxKtMVgeMe8a:bsq7wp3) ([raw file](https://github.com/vaadin/flow/blob/a323a8da7c1b897ca04d0b18569fba4254fbbab1/flow-components-parent/flow-component/pom.xml#L100)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

If it does, why specify it?
</blockquote></details>

copy paste from example

---

*[flow-components-parent/flow-component/pom.xml, line 108 at r2](https://reviewable.io:443/reviews/vaadin/flow/2821#-Kxr0xMfFVQYP42uxSFb:-KxrGUfQfDsq1xRSZqBX:bsq7wp3) ([raw file](https://github.com/vaadin/flow/blob/a323a8da7c1b897ca04d0b18569fba4254fbbab1/flow-components-parent/flow-component/pom.xml#L108)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

What's the purpose of this comment?
</blockquote></details>

copy paste from example

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2821)*

**Comment by SomeoneToIgnore** [comment]
*[flow-components-parent/flow-component/pom.xml, line 96 at r2](https://reviewable.io:443/reviews/vaadin/flow/2821#-Kxr1ozP2R90jT5oE7lc:-KxrGk4S0svsP9ZI3Qo5:b-z0jzx2) ([raw file](https://github.com/vaadin/flow/blob/a323a8da7c1b897ca04d0b18569fba4254fbbab1/flow-components-parent/flow-component/pom.xml#L96)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

How do you specify it to only download the chrome driver?
</blockquote></details>

```
<!-- Provide a list of drivers and binary versions to download (this is a map so only one version can be specified per driver) -->
<getSpecificExecutableVersions>
    <googlechrome>18</googlechrome>
</getSpecificExecutableVersions>
```

This looks like can do the trick.
Never tried this thing though, so not sure.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2821)*

**Comment by caalador** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-components-parent/flow-component/pom.xml, line 96 at r2](https://reviewable.io:443/reviews/vaadin/flow/2821#-Kxr1ozP2R90jT5oE7lc:-KxrIKzoGZG8AmjNKAXK:b-dkcwt5) ([raw file](https://github.com/vaadin/flow/blob/a323a8da7c1b897ca04d0b18569fba4254fbbab1/flow-components-parent/flow-component/pom.xml#L96)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

```
<!-- Provide a list of drivers and binary versions to download (this is a map so only one version can be specified per driver) -->
<getSpecificExecutableVersions>
    <googlechrome>18</googlechrome>
</getSpecificExecutableVersions>
```

This looks like can do the trick.
Never tried this thing though, so not sure.
</blockquote></details>

the question is what is the value supposed to be. Just using that 18 gives me no drivers at all.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2821)*

**Comment by caalador** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-components-parent/flow-component/pom.xml, line 96 at r2](https://reviewable.io:443/reviews/vaadin/flow/2821#-Kxr1ozP2R90jT5oE7lc:-KxrIdMIZguQ2OXa1Qiq:b-3htold) ([raw file](https://github.com/vaadin/flow/blob/a323a8da7c1b897ca04d0b18569fba4254fbbab1/flow-components-parent/flow-component/pom.xml#L96)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

the question is what is the value supposed to be. Just using that 18 gives me no drivers at all.
</blockquote></details>

`[WARNING] No driver contexts detected for the current operating system, no maven properties set!`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2821)*

**Comment by SomeoneToIgnore** [comment]
*[flow-components-parent/flow-component/pom.xml, line 96 at r2](https://reviewable.io:443/reviews/vaadin/flow/2821#-Kxr1ozP2R90jT5oE7lc:-KxrIkOY0AkojKNdx-Tj:bqnu1z2) ([raw file](https://github.com/vaadin/flow/blob/a323a8da7c1b897ca04d0b18569fba4254fbbab1/flow-components-parent/flow-component/pom.xml#L96)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

`[WARNING] No driver contexts detected for the current operating system, no maven properties set!`
</blockquote></details>

Ew.
All right, screw the idea.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2821)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[flow-components-parent/flow-component/pom.xml, line 108 at r2](https://reviewable.io:443/reviews/vaadin/flow/2821#-Kxr0xMfFVQYP42uxSFb:-KxrJx3c95aDxKwJSqmZ:bgivio2) ([raw file](https://github.com/vaadin/flow/blob/a323a8da7c1b897ca04d0b18569fba4254fbbab1/flow-components-parent/flow-component/pom.xml#L108)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

copy paste from example
</blockquote></details>

That does not answer to the original question :)

Btw, you're blocking all 3 discussions.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2821)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2821)*

**Pull request merged**
