### PR TITLE
Remove BeforeNavigationObserver.

### PR DESCRIPTION
**Pull request by caalador**
Removed the BeforeNavigationObserver as it
was making it hard to know when it will fire and
why it would in some cases get fired 2 times.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3260)

### CODE REVIEW

**Comment by ahie** [comment]
Reviewed 26 of 52 files at r1, 22 of 24 files at r2, 2 of 2 files at r3.
Review status: 48 of 50 files reviewed at latest revision, 4 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/router/BeforeEvent.java, line 40 at r3](https://reviewable.io:443/reviews/vaadin/flow/3260#-L20TVjZl77qVqA82O6k:-L20TVj_IKyJVQ7xDlvR:b-xgw3l7) ([raw file](https://github.com/vaadin/flow/blob/643b947fab2e2a8b559dd431e45ea7d60fb93947/flow-server/src/main/java/com/vaadin/flow/router/BeforeEvent.java#L40)):*
> ActivationState

Can this enum be removed as well (the file is not removed in this PR)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3260)*

**Comment by caalador** [comment]
Review status: 48 of 51 files reviewed at latest revision, 4 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/router/BeforeEvent.java, line 40 at r3](https://reviewable.io:443/reviews/vaadin/flow/3260#-L20TVjZl77qVqA82O6k:-L23coci2g4giUXQff90:b-p0zsb6) ([raw file](https://github.com/vaadin/flow/blob/643b947fab2e2a8b559dd431e45ea7d60fb93947/flow-server/src/main/java/com/vaadin/flow/router/BeforeEvent.java#L40)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

> ActivationState

Can this enum be removed as well (the file is not removed in this PR)?
</blockquote></details>

Yes. It was supposed to be removed also.
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3260)*

**Comment by ahie** [comment]
Reviewed 1 of 52 files at r1, 1 of 24 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[flow-documentation/routing/tutorial-routing-lifecycle.asciidoc, line 27 at r4](https://reviewable.io:443/reviews/vaadin/flow/3260#-L24G3CChPDtoxyv_fOA:-L24G3CChPDtoxyv_fOB:bh6ksuk) ([raw file](https://github.com/vaadin/flow/blob/50482aa44d09d559de800b259eea7836d6254b96/flow-documentation/routing/tutorial-routing-lifecycle.asciidoc#L27)):*
> detached (<\<detached>>)

could these just be

> <\<detached>>

similar to the use later in this chapter:

> enables optional functions like <\<reroute>> and <\<postpone>>

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3260)*

**Comment by caalador** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[flow-documentation/routing/tutorial-routing-lifecycle.asciidoc, line 27 at r4](https://reviewable.io:443/reviews/vaadin/flow/3260#-L24G3CChPDtoxyv_fOA:-L24Hw6rmOrf5733o0Qs:b-bu5zip) ([raw file](https://github.com/vaadin/flow/blob/50482aa44d09d559de800b259eea7836d6254b96/flow-documentation/routing/tutorial-routing-lifecycle.asciidoc#L27)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

> detached (<\<detached>>)

could these just be

> <\<detached>>

similar to the use later in this chapter:

> enables optional functions like <\<reroute>> and <\<postpone>>
</blockquote></details>

They show up as `detached (BeforeLeaveObserver) or attached (BeforeEnterObserver) ` when the asciiDoc is parsed.

the <<reroute>> and <<postpone>> show up as `functions like Reroute and Postpone.`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3260)*

**Pull request merged**
