### PR TITLE
Pin @vaadin/vaadin-element-mixin to 2.1.5

### PR DESCRIPTION
**Pull request by Artur-**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/6986)

### CODE REVIEW

**Comment by Artur-** [comment]
Where does `+0.1.0` come from? It should go into 2.0.x

**Comment by pleku** [comment]
@Artur- not sure where it comes from, this doesn't say https://teamcity.vaadin.com/repository/download/Flow_FlowTests/55636:id/apidiff/flow-server/japicmp.html

**Comment by Legioth** [comment]
Sounds quite logical in the generic case that adding an annotation is at least `+0.1.0`. Imagine e.g. if the annotation would be `@Component` from Spring or `@Entity` from JPA.

**Comment by caalador** [comment]
Another way to pin it would be to in `TaskUpdatePackages::execute()`  before the `updatePackageJsonDependencies` call add the dependency to the map as `deps.put("@vaadin/vaadin-element-mixin", "~2.1.5");`

**Comment by Artur-** [comment]
That would be another way. Is it better or worse or the same?

**Comment by caalador** [comment]
For forcing the version it is at least better as if someone adds another version with NpmPackage it will just override the value. Where as for the annotation there will be an exception if the versions are not matching (or inside accepted range?)

**Pull request merged**
