### PR TITLE
Add Spring vaadin servlet, service and implement Spring instantiator

### LINKED ISSUE #2568: Ensure/make router work with Spring
#2567 should enable router initialization.

This ticket is about actual router work with Spring.
No scopes other than prototype should be considered here (classes annotated with `@Route` should be available via `ApplicationContext` (autowired) and retrieved from there (not instantiated via reflection)).

So it means that `@Autowire` /`@Inject` annotations should allow injecting beans into classes annotated with `@Route`.
As already said above: only existing scopes should be supported (injecting should work as it should). So normally prototype scope should be used for `@Route` classes so that they becomes Spring-aware which allows to inject other beans inside them.

### LINKED ISSUE #2596: Provide a custom Spring instantiator
The `Instantiator` class is used as SPI.
It makes possible to register custom classes to use them inside Flow.
E.g. `VaadinServiceInitListener` should be registered in a specific way (not via API) (see docs about the way).
Normally the standard Java SPI mechanism is used for this.
It's possible to use another way to register SPI in Spring (DI : asking beans from application context/autowiring ).

We should extend the way for Spring to register those classes.
Default behavior should be kept since it's still possible to use this way. But it also should be possible to register a bean (e.g. via `@Component`  annotation) and extends VaadinServiceInitListener.
Then such class becomes available for DI and it should be registered as a listener.

Please note that `Instantiator` itself is registered via standard Java SPI. It's an open question: should we extend `VaadinServletService` in our Spring add-on to load the instantiator via Spring mechanisms or should we keep standard Java SPI mechanism in this case.

### PR DESCRIPTION
**Pull request by denis-anisimov**
Also extract all UI and IT test classes into a separate module (test-jar) and use it in both WAR and Spring Boot application projects tpo avoid code duplication.

Fixes #2596
Fixes #2568

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/2626)

### CODE REVIEW

**Comment by caalador** [comment]
Reviewed 22 of 28 files at r1, 1 of 1 files at r2.
Review status: 20 of 24 files reviewed at latest revision, 9 unresolved discussions.

---

*[flow-spring-addon/src/main/java/com/vaadin/spring/SpringServlet.java, line 36 at r3](https://reviewable.io:443/reviews/vaadin/flow/2626#-Kw-5DYn6IqtQsxdU7n2:-Kw-5DYn6IqtQsxdU7n3:bp8rpsz) ([raw file](https://github.com/vaadin/flow/blob/97037190b0060d94c42553511d1556320e4c4f02/flow-spring-addon/src/main/java/com/vaadin/spring/SpringServlet.java#L36)):*
> ```Java
> public class SpringServlet extends VaadinServlet {
> 
>     private ApplicationContext context;
> ```

Shouldn't context be `final` in this case as it shouldn't change for the instance.
'not blocking on this'

---

*[flow-tests/test-spring-common/src/main/java/com/vaadin/flow/spring/DataBean.java, line 25 at r3](https://reviewable.io:443/reviews/vaadin/flow/2626#-Kw-7xN1nRZiJ8XHyeRp:-Kw-7xN1nRZiJ8XHyeRq:b-x8hm8e) ([raw file](https://github.com/vaadin/flow/blob/97037190b0060d94c42553511d1556320e4c4f02/flow-tests/test-spring-common/src/main/java/com/vaadin/flow/spring/DataBean.java#L25)):*
> ```Java
>  */
> @Component
> public class DataBean {
> ```

Servlet became a component bean?
Why does it track it as such. By all appearances it should be a new class.

---

*[flow-tests/test-spring-common/src/main/java/com/vaadin/flow/spring/RootNavigationTarget.java, line 34 at r3](https://reviewable.io:443/reviews/vaadin/flow/2626#-Kw-7W6PGfn1J9d39-xN:-Kw-7W6PGfn1J9d39-xO:bop60op) ([raw file](https://github.com/vaadin/flow/blob/97037190b0060d94c42553511d1556320e4c4f02/flow-tests/test-spring-common/src/main/java/com/vaadin/flow/spring/RootNavigationTarget.java#L34)):*
> ```Java
>         section.setText("singleton");
>     }
> }
> ```

New line (If other changes are made)

---

*[flow-tests/test-spring-common/src/test/java/com/vaadin/flow/spring/RouteBasicIT.java, line 40 at r3](https://reviewable.io:443/reviews/vaadin/flow/2626#-Kw-7b7JCqCS77t-RCsG:-Kw-7b7JCqCS77t-RCsH:b-nk0m79) ([raw file](https://github.com/vaadin/flow/blob/97037190b0060d94c42553511d1556320e4c4f02/flow-tests/test-spring-common/src/test/java/com/vaadin/flow/spring/RouteBasicIT.java#L40)):*
> ```Java
>         getDriver().get(getTestURL() + "foo");
> 
>         waitUntil(driver -> isElementPresent(By.id("singleton")));
> ```

Should something be checked after the element is present?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2626)*

**Comment by denis-anisimov** [comment]
Review status: 20 of 24 files reviewed at latest revision, 9 unresolved discussions.

---

*[flow-spring-addon/src/main/java/com/vaadin/spring/SpringServlet.java, line 36 at r3](https://reviewable.io:443/reviews/vaadin/flow/2626#-Kw-5DYn6IqtQsxdU7n2:-Kw-9K5AvC4Abwx7kvta:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/97037190b0060d94c42553511d1556320e4c4f02/flow-spring-addon/src/main/java/com/vaadin/spring/SpringServlet.java#L36)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Shouldn't context be `final` in this case as it shouldn't change for the instance.
'not blocking on this'
</blockquote></details>

Done.

---

*[flow-tests/test-spring-common/src/main/java/com/vaadin/flow/spring/DataBean.java, line 25 at r3](https://reviewable.io:443/reviews/vaadin/flow/2626#-Kw-7xN1nRZiJ8XHyeRp:-Kw-9e7pRloTjYpXiIFU:b-ttetgv) ([raw file](https://github.com/vaadin/flow/blob/97037190b0060d94c42553511d1556320e4c4f02/flow-tests/test-spring-common/src/main/java/com/vaadin/flow/spring/DataBean.java#L25)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Servlet became a component bean?
Why does it track it as such. By all appearances it should be a new class.
</blockquote></details>

Why do you talk about servlet here ?
Servlet is instantiated in `SpringBootAutoConfiguration`. 
Servlet in not a component bean. It uses `ApplicationContext` to access to Spring beans.
The servlet registration is moved to autoconfiguration, in the Spring add-on.

---

*[flow-tests/test-spring-common/src/main/java/com/vaadin/flow/spring/RootNavigationTarget.java, line 34 at r3](https://reviewable.io:443/reviews/vaadin/flow/2626#-Kw-7W6PGfn1J9d39-xN:-Kw-AIzFrNbiWmQioxWX:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/97037190b0060d94c42553511d1556320e4c4f02/flow-tests/test-spring-common/src/main/java/com/vaadin/flow/spring/RootNavigationTarget.java#L34)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

New line (If other changes are made)
</blockquote></details>

Done.

---

*[flow-tests/test-spring-common/src/test/java/com/vaadin/flow/spring/RouteBasicIT.java, line 40 at r3](https://reviewable.io:443/reviews/vaadin/flow/2626#-Kw-7b7JCqCS77t-RCsG:-Kw-APHcLLWKfaYNzfkc:br0uy9v) ([raw file](https://github.com/vaadin/flow/blob/97037190b0060d94c42553511d1556320e4c4f02/flow-tests/test-spring-common/src/test/java/com/vaadin/flow/spring/RouteBasicIT.java#L40)):*
> isElementPresent(By.id("singleton"))

That's the check.
It waits for the element appearance. 
It will throw if there is no element appears.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2626)*

**Comment by caalador** [comment]
Reviewed 5 of 28 files at r1, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[flow-tests/test-spring-common/src/main/java/com/vaadin/flow/spring/DataBean.java, line 25 at r3](https://reviewable.io:443/reviews/vaadin/flow/2626#-Kw-7xN1nRZiJ8XHyeRp:-Kw-E0K-r4Bzi6D8_H89:bc09fyf) ([raw file](https://github.com/vaadin/flow/blob/97037190b0060d94c42553511d1556320e4c4f02/flow-tests/test-spring-common/src/main/java/com/vaadin/flow/spring/DataBean.java#L25)):*
> File renamed
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>
>       
>         
>         from flow-tests/test-spring-boot/src/main/java/com/vaadin/flow/spring/boot/TestSpringServlet.java
>         at r1
>       
>       to flow-tests/test-spring-common/src/main/java/com/vaadin/flow/spring/DataBean.java.
</details>

File renamed from flow-tests/test-spring-boot/src/main/java/com/vaadin/flow/spring/boot/TestSpringServlet.java at r1 to flow-tests/test-spring-common/src/main/java/com/vaadin/flow/spring/DataBean.java.

Reviewable marks this like that that it was a SpringServlet and became a DataBean. I would have expected a remove and a completely new file. Just noting that it's really strange and had me spending way too much time wondering on the change.

---

*[flow-tests/test-spring-common/src/test/java/com/vaadin/flow/spring/RouteBasicIT.java, line 40 at r3](https://reviewable.io:443/reviews/vaadin/flow/2626#-Kw-7b7JCqCS77t-RCsG:-Kw-EVFqUE0VeBDWNCPZ:b-jfl2rw) ([raw file](https://github.com/vaadin/flow/blob/97037190b0060d94c42553511d1556320e4c4f02/flow-tests/test-spring-common/src/test/java/com/vaadin/flow/spring/RouteBasicIT.java#L40)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> isElementPresent(By.id("singleton"))

That's the check.
It waits for the element appearance. 
It will throw if there is no element appears.
</blockquote></details>

That it will. 
I just don't like the exception that waitUntil generates. It should take in a exception message, but it's not important for this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2626)*

**Comment by torok-peter** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/server/VaadinService.java, line 331 at r3](https://reviewable.io:443/reviews/vaadin/flow/2626#-Kw-97OLb0qg2SBaNVNf:-Kw-97OLb0qg2SBaNVNg:b-9ut02i) ([raw file](https://github.com/vaadin/flow/blob/97037190b0060d94c42553511d1556320e4c4f02/flow-server/src/main/java/com/vaadin/server/VaadinService.java#L331)):*
> ```Java
>      * @see Instantiator
>      */
>     protected Instantiator createInstantiator() throws ServiceException {
> ```

If this is not supposed to be overridable anymore, make it final. Otherwise may be worth re-adding Javadoc to explain how/when to override it?

---

*[flow-server/src/main/java/com/vaadin/server/VaadinService.java, line 365 at r3](https://reviewable.io:443/reviews/vaadin/flow/2626#-Kw-9sHGu7HpFdpgsgDr:-Kw-9sHGu7HpFdpgsgDs:bu0ghtc) ([raw file](https://github.com/vaadin/flow/blob/97037190b0060d94c42553511d1556320e4c4f02/flow-server/src/main/java/com/vaadin/server/VaadinService.java#L365)):*
> ```Java
>                         instantiators.add(instance);
>                     }
>                 });
> ```

Could be simplified to something like
```
List<Instantiator> instantiators = 
    ServiceLoader.load(Instantiator.class, getClassLoader()).stream()
        .filter(instance -> instance.init(this))
        .collect(Collectors.toList());
```

---

*[flow-server/src/main/java/com/vaadin/server/VaadinService.java, line 371 at r3](https://reviewable.io:443/reviews/vaadin/flow/2626#-Kw-AnKIv5eXClemDmcT:-Kw-AnKIv5eXClemDmcU:bxn4r48) ([raw file](https://github.com/vaadin/flow/blob/97037190b0060d94c42553511d1556320e4c4f02/flow-server/src/main/java/com/vaadin/server/VaadinService.java#L371)):*
> ```Java
>                             + instantiators);
>         }
>         return instantiators.stream().findFirst();
> ```

Would `instantiators.get(0)` be simpler?

---

*[flow-spring-addon/src/main/java/com/vaadin/spring/SpringInstantiator.java, line 43 at r3](https://reviewable.io:443/reviews/vaadin/flow/2626#-Kw-BNzc2UxerLulqmzM:-Kw-BNzdpEuX1QOU-kdo:bvmve3z) ([raw file](https://github.com/vaadin/flow/blob/97037190b0060d94c42553511d1556320e4c4f02/flow-spring-addon/src/main/java/com/vaadin/spring/SpringInstantiator.java#L43)):*
> ```Java
>      *
>      * @param service
>      *            service the service to use
> ```

typo: 'service' duplicated

---

*[flow-spring-addon/src/main/java/com/vaadin/spring/SpringVaadinServletService.java, line 81 at r3](https://reviewable.io:443/reviews/vaadin/flow/2626#-Kw-DlVfSHj0VTx_hTLy:-Kw-DlVfSHj0VTx_hTLz:b-j9dtjd) ([raw file](https://github.com/vaadin/flow/blob/97037190b0060d94c42553511d1556320e4c4f02/flow-spring-addon/src/main/java/com/vaadin/spring/SpringVaadinServletService.java#L81)):*
> ```Java
>         }
>         return spiInstantiator.isPresent() ? spiInstantiator
>                 : springInstantiators.stream().findFirst();
> ```

`springInstantiators.get(0)` ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2626)*

**Comment by torok-peter** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/server/VaadinService.java, line 371 at r3](https://reviewable.io:443/reviews/vaadin/flow/2626#-Kw-AnKIv5eXClemDmcT:-Kw-GxXZCW_jkyWqSceJ:b-42kjs2) ([raw file](https://github.com/vaadin/flow/blob/97037190b0060d94c42553511d1556320e4c4f02/flow-server/src/main/java/com/vaadin/server/VaadinService.java#L371)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

Would `instantiators.get(0)` be simpler?
</blockquote></details>

...except that it doesn't return an `Optional`. Sorry...

---

*[flow-spring-addon/src/main/java/com/vaadin/spring/SpringVaadinServletService.java, line 81 at r3](https://reviewable.io:443/reviews/vaadin/flow/2626#-Kw-DlVfSHj0VTx_hTLy:-Kw-HOPkcDEZ_FZu5LZd:b-42kjs2) ([raw file](https://github.com/vaadin/flow/blob/97037190b0060d94c42553511d1556320e4c4f02/flow-spring-addon/src/main/java/com/vaadin/spring/SpringVaadinServletService.java#L81)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

`springInstantiators.get(0)` ?
</blockquote></details>

...except that it doesn't return an `Optional`. Sorry...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2626)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/server/VaadinService.java, line 331 at r3](https://reviewable.io:443/reviews/vaadin/flow/2626#-Kw-97OLb0qg2SBaNVNf:-Kw-I55IILEPs_GsLqsF:bwkg9me) ([raw file](https://github.com/vaadin/flow/blob/97037190b0060d94c42553511d1556320e4c4f02/flow-server/src/main/java/com/vaadin/server/VaadinService.java#L331)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

If this is not supposed to be overridable anymore, make it final. Otherwise may be worth re-adding Javadoc to explain how/when to override it?
</blockquote></details>

Technically it may be `private` now.

But this will be incompatible change with FW8 (I'm not sure whether this is important or not).

OK, I will add some javadoc.

---

*[flow-server/src/main/java/com/vaadin/server/VaadinService.java, line 365 at r3](https://reviewable.io:443/reviews/vaadin/flow/2626#-Kw-9sHGu7HpFdpgsgDr:-Kw-IT6bYlx5joHj1bVk:bhkgg02) ([raw file](https://github.com/vaadin/flow/blob/97037190b0060d94c42553511d1556320e4c4f02/flow-server/src/main/java/com/vaadin/server/VaadinService.java#L365)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

Could be simplified to something like
```
List<Instantiator> instantiators = 
    ServiceLoader.load(Instantiator.class, getClassLoader()).stream()
        .filter(instance -> instance.init(this))
        .collect(Collectors.toList());
```
</blockquote></details>

Could be. It's just a refactoring of the existing code.
But I will change it.

---

*[flow-spring-addon/src/main/java/com/vaadin/spring/SpringInstantiator.java, line 43 at r3](https://reviewable.io:443/reviews/vaadin/flow/2626#-Kw-BNzc2UxerLulqmzM:-Kw-IgQkO0rc8G3nc2-z:b2cz0ny) ([raw file](https://github.com/vaadin/flow/blob/97037190b0060d94c42553511d1556320e4c4f02/flow-spring-addon/src/main/java/com/vaadin/spring/SpringInstantiator.java#L43)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

typo: 'service' duplicated
</blockquote></details>

Done.

Thanks.

---

*[flow-tests/test-spring-common/src/main/java/com/vaadin/flow/spring/DataBean.java, line 25 at r3](https://reviewable.io:443/reviews/vaadin/flow/2626#-Kw-7xN1nRZiJ8XHyeRp:-Kw-GkXCzLS8UR9C9xqB:boizxz5) ([raw file](https://github.com/vaadin/flow/blob/97037190b0060d94c42553511d1556320e4c4f02/flow-tests/test-spring-common/src/main/java/com/vaadin/flow/spring/DataBean.java#L25)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

> File renamed
>       
>         
>         from flow-tests/test-spring-boot/src/main/java/com/vaadin/flow/spring/boot/TestSpringServlet.java
>         at r1
>       
>       to flow-tests/test-spring-common/src/main/java/com/vaadin/flow/spring/DataBean.java.

File renamed from flow-tests/test-spring-boot/src/main/java/com/vaadin/flow/spring/boot/TestSpringServlet.java at r1 to flow-tests/test-spring-common/src/main/java/com/vaadin/flow/spring/DataBean.java.

Reviewable marks this like that that it was a SpringServlet and became a DataBean. I would have expected a remove and a completely new file. Just noting that it's really strange and had me spending way too much time wondering on the change.
</blockquote></details>

Hmm.......

I don't think I've renamed this file at all.
Interesting.
May be it's a git/reviewable issue ?
I'm pretty sure that this file has been created from scratch..

---

*[flow-tests/test-spring-common/src/test/java/com/vaadin/flow/spring/RouteBasicIT.java, line 40 at r3](https://reviewable.io:443/reviews/vaadin/flow/2626#-Kw-7b7JCqCS77t-RCsG:-Kw-HYwmzk3RNAVDCPvV:bkuldlr) ([raw file](https://github.com/vaadin/flow/blob/97037190b0060d94c42553511d1556320e4c4f02/flow-tests/test-spring-common/src/test/java/com/vaadin/flow/spring/RouteBasicIT.java#L40)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

That it will. 
I just don't like the exception that waitUntil generates. It should take in a exception message, but it's not important for this.
</blockquote></details>

Yes..... But there is no any sense to add a check after this wait since it will throw an exception if element is not present. 
But yeah, you are right.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2626)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/server/VaadinService.java, line 365 at r3](https://reviewable.io:443/reviews/vaadin/flow/2626#-Kw-9sHGu7HpFdpgsgDr:-Kw-KstcE673dg8KABLy:b-mvdslj) ([raw file](https://github.com/vaadin/flow/blob/97037190b0060d94c42553511d1556320e4c4f02/flow-server/src/main/java/com/vaadin/server/VaadinService.java#L365)):*
> List<Instantiator> instantiators = 
>     ServiceLoader.load(Instantiator.class, getClassLoader()).stream()
>         .filter(instance -> instance.init(this))
>         .collect(Collectors.toList());

By the way your code is wrong but it can be corrected.
Would be better if such small improvements are non-blocking.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2626)*

**Comment by torok-peter** [comment]
Review status: 22 of 24 files reviewed at latest revision, 8 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/server/VaadinService.java, line 365 at r3](https://reviewable.io:443/reviews/vaadin/flow/2626#-Kw-9sHGu7HpFdpgsgDr:-Kw-PfAuClsARw0xCdIU:bh4x2fr) ([raw file](https://github.com/vaadin/flow/blob/97037190b0060d94c42553511d1556320e4c4f02/flow-server/src/main/java/com/vaadin/server/VaadinService.java#L365)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> List<Instantiator> instantiators = 
>     ServiceLoader.load(Instantiator.class, getClassLoader()).stream()
>         .filter(instance -> instance.init(this))
>         .collect(Collectors.toList());

By the way your code is wrong but it can be corrected.
Would be better if such small improvements are non-blocking.
</blockquote></details>

Didn't test it myself, so it is entirely possible that it doesn't compile - just wanted to throw in an idea.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2626)*

**Comment by denis-anisimov** [comment]
Review status: 22 of 24 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-server/src/main/java/com/vaadin/server/VaadinService.java, line 331 at r3](https://reviewable.io:443/reviews/vaadin/flow/2626#-Kw-97OLb0qg2SBaNVNf:-Kw-Rql0MkaIJiuPDKh3:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/97037190b0060d94c42553511d1556320e4c4f02/flow-server/src/main/java/com/vaadin/server/VaadinService.java#L331)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Technically it may be `private` now.

But this will be incompatible change with FW8 (I'm not sure whether this is important or not).

OK, I will add some javadoc.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2626)*

**Comment by denis-anisimov** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2626)*

**Pull request merged**
