### PR TITLE
Enable sorting Grid Columns

### PR DESCRIPTION
**Pull request by ahie**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/2908)

### CODE REVIEW

**Comment by gilberto-torrezan** [comment]
Reviewed 11 of 11 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/grid/GridSortingTest.java, line 219 at r1](https://reviewable.io:443/reviews/vaadin/flow/2908#-KypYTsFvmF6niLT-S0Q:-KypYTsFvmF6niLT-S0R:b-b049lz) ([raw file](https://github.com/vaadin/flow/blob/eb37b69d01e2a3e4541a483435464fe2f927b069/flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/grid/GridSortingTest.java#L219)):*
> ```Java
>     private void callSortersChanged(JsonArray json) {
>         try {
>             Method method = Grid.class.getDeclaredMethod("sortersChanged",
> ```

Ouch, this is ugly. See my comment below about using an event instead of a `ClientDelegate` - maybe it can help with this test too.

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 450 at r1](https://reviewable.io:443/reviews/vaadin/flow/2908#-KypTTLQG_k8ZyYMHlkp:-KypTTLQG_k8ZyYMHlkq:b5j1qts) ([raw file](https://github.com/vaadin/flow/blob/eb37b69d01e2a3e4541a483435464fe2f927b069/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L450)):*
> ```Java
>         public <V extends Comparable<? super V>> Column<T> setComparator(
>                 ValueProvider<T, V> keyExtractor) {
>             Objects.requireNonNull(comparator, "Key extractor can't be null");
> ```

Copy-paste failure: `comparator`  -> `keyExtractor`

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 559 at r1](https://reviewable.io:443/reviews/vaadin/flow/2908#-KypUDIGmXl25dbJDmc8:-KypUDIGmXl25dbJDmc9:bit2phq) ([raw file](https://github.com/vaadin/flow/blob/eb37b69d01e2a3e4541a483435464fe2f927b069/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L559)):*
> ```Java
>                     .setAttribute("class", "header")
>                     .setProperty("innerHTML", innerHTML);
>             getElement().appendChild(headerTemplate);
> ```

Oh man, this will break so hard in my branch =P

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 1392 at r1](https://reviewable.io:443/reviews/vaadin/flow/2908#-KypV8nN3SH6JTzjYdcr:-KypV8nN3SH6JTzjYdcs:bg9wmtn) ([raw file](https://github.com/vaadin/flow/blob/eb37b69d01e2a3e4541a483435464fe2f927b069/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L1392)):*
> ```Java
>     public void setMultiSort(boolean multiSort) {
>         this.multiSort = multiSort;
>         getElement().setAttribute("multi-sort", multiSort);
> ```

Most of our interaction with the components is done by using properties instead of attributes. In this case you could use the `multiSort` property - and you don't even need to store it as a separate field. You could use the property from the element directly.

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/GridSortOrderBuilder.java, line 31 at r1](https://reviewable.io:443/reviews/vaadin/flow/2908#-KypWTXDUExh6CeFd3Nf:-KypWTXDUExh6CeFd3Ng:b539uv7) ([raw file](https://github.com/vaadin/flow/blob/eb37b69d01e2a3e4541a483435464fe2f927b069/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/GridSortOrderBuilder.java#L31)):*
> ```Java
>  * @see #thenDesc(Column)
>  * @see #build()
>  *
> ```

Missing `@author Vaadin Ltd` - I guess Sonar should point this out though.

---

*[flow-components-parent/flow-components/src/main/resources/META-INF/resources/gridConnector.js, line 102 at r1](https://reviewable.io:443/reviews/vaadin/flow/2908#-KypWm0vMSKESuglmMjy:-KypWm0vMSKESuglmMjz:bmyebys) ([raw file](https://github.com/vaadin/flow/blob/eb37b69d01e2a3e4541a483435464fe2f927b069/flow-components-parent/flow-components/src/main/resources/META-INF/resources/gridConnector.js#L102)):*
> ```JavaScript
>       }));
>     }
>     grid.addEventListener('sorter-changed', sorterChangeListener);
> ```

Can't you use the regular event handling in flow, without using a custom function to call a `ClientDelegate` ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2908)*

**Comment by torok-peter** [comment]
Reviewed 10 of 11 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 16 unresolved discussions, some commit checks failed.

---

*[flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/grid/GridSortingTest.java, line 178 at r1](https://reviewable.io:443/reviews/vaadin/flow/2908#-KypVKd-K-Be8gtL0CPb:-KypVKd-K-Be8gtL0CPc:b-drwz0l) ([raw file](https://github.com/vaadin/flow/blob/eb37b69d01e2a3e4541a483435464fe2f927b069/flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/grid/GridSortingTest.java#L178)):*
> ```Java
> 
>     @Test
>     public void gridSorting() {
> ```

Test name should be more descriptive of what is actually being verified here. It also seems to be too big, testing multiple things, so I would prefer slicing it into distinct smaller tests, with more of the repeating low-level setup code factored out into helper methods, to make the code easier to read.

---

*[flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/grid/GridSortingTest.java, line 226 at r1](https://reviewable.io:443/reviews/vaadin/flow/2908#-KypUgEH5JywuvndfnBG:-KypUgEH5JywuvndfnBH:b-azztf2) ([raw file](https://github.com/vaadin/flow/blob/eb37b69d01e2a3e4541a483435464fe2f927b069/flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/grid/GridSortingTest.java#L226)):*
> ```Java
>                 | IllegalAccessException | IllegalArgumentException
>                 | InvocationTargetException e) {
>             Assert.fail("Could not call Grid.sortersChanged");
> ```

Why handle these exceptions manually here, instead of passing them on to the test runner to report?

---

*[flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/grid/SortOrderBuildersTest.java, line 80 at r1](https://reviewable.io:443/reviews/vaadin/flow/2908#-KypWr_ymvwIvVJRKH9G:-KypWr_ymvwIvVJRKH9H:b-uw7fy4) ([raw file](https://github.com/vaadin/flow/blob/eb37b69d01e2a3e4541a483435464fe2f927b069/flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/grid/SortOrderBuildersTest.java#L80)):*
> ```Java
>         }
>     }
> }
> ```

Test also different column sort orders, like 3,2,1 / c,b,a or 2,1,3 / b,a,c

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 430 at r1](https://reviewable.io:443/reviews/vaadin/flow/2908#-KypXOdEAmETaogLZAPA:-KypXOdEAmETaogLZAPB:b-x15rbp) ([raw file](https://github.com/vaadin/flow/blob/eb37b69d01e2a3e4541a483435464fe2f927b069/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L430)):*
> ```Java
>          */
>         public Column<T> setComparator(Comparator<T> comparator) {
>             Objects.requireNonNull(comparator, "Comparator can't be null");
> ```

"must not" would be more precise

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 450 at r1](https://reviewable.io:443/reviews/vaadin/flow/2908#-KypX_t4f7pLY37vhwq4:-KypX_t4f7pLY37vhwq5:b-2guby3) ([raw file](https://github.com/vaadin/flow/blob/eb37b69d01e2a3e4541a483435464fe2f927b069/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L450)):*
> ```Java
>         public <V extends Comparable<? super V>> Column<T> setComparator(
>                 ValueProvider<T, V> keyExtractor) {
>             Objects.requireNonNull(comparator, "Key extractor can't be null");
> ```

same here

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 488 at r1](https://reviewable.io:443/reviews/vaadin/flow/2908#-KypXilaNX27eoURgvj7:-KypXilaNX27eoURgvj8:bji28bi) ([raw file](https://github.com/vaadin/flow/blob/eb37b69d01e2a3e4541a483435464fe2f927b069/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L488)):*
> ```Java
>          */
>         public Column<T> setSortProperty(String... properties) {
>             Objects.requireNonNull(properties, "Sort properties can't be null");
> ```

and here

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 513 at r1](https://reviewable.io:443/reviews/vaadin/flow/2908#-KypXml9UIt2o2iOY2vD:-KypXml9UIt2o2iOY2vE:bji28bi) ([raw file](https://github.com/vaadin/flow/blob/eb37b69d01e2a3e4541a483435464fe2f927b069/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L513)):*
> ```Java
>         public Column<T> setSortOrderProvider(SortOrderProvider provider) {
>             Objects.requireNonNull(provider,
>                     "Sort order provider can't be null");
> ```

and here

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 552 at r1](https://reviewable.io:443/reviews/vaadin/flow/2908#-KypYIp0_lBHYdAPRBUr:-KypYIp0_lBHYdAPRBUs:b5pslfd) ([raw file](https://github.com/vaadin/flow/blob/eb37b69d01e2a3e4541a483435464fe2f927b069/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L552)):*
> ```Java
>                     ? String.format(
>                             "<vaadin-grid-sorter path='%s'>%s</vaadin-grid-sorter>",
>                             columnId, HtmlUtils.escape(header))
> ```

Has the columnId been validated / escaped before? It apparently isn't validated in the `Column` constructor - can we trust its caller that it isn't trying anything naughty like HTML / Javascript injection?

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 553 at r1](https://reviewable.io:443/reviews/vaadin/flow/2908#-Kyp_IwpEPb4OT6ROjwc:-Kyp_IwpEPb4OT6ROjwd:b-7bkrfm) ([raw file](https://github.com/vaadin/flow/blob/eb37b69d01e2a3e4541a483435464fe2f927b069/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L553)):*
> ```Java
>                             "<vaadin-grid-sorter path='%s'>%s</vaadin-grid-sorter>",
>                             columnId, HtmlUtils.escape(header))
>                     : HtmlUtils.escape(header);
> ```

could extract `HtmlUtils.escape(header)` calls into local variable

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 922 at r1](https://reviewable.io:443/reviews/vaadin/flow/2908#-Kyp_jBVOczU7ogP02kv:-Kyp_jBVOczU7ogP02kw:bycmcra) ([raw file](https://github.com/vaadin/flow/blob/eb37b69d01e2a3e4541a483435464fe2f927b069/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L922)):*
> ```Java
>         Map<String, ValueProvider<T, ?>> valueProviders = renderer
>                 .getValueProviders();
>         Set<String> valueProvidersKeySet = renderer.getValueProviders()
> ```

there is already a local variable right above for `renderer.getValueProviders()`

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 925 at r1](https://reviewable.io:443/reviews/vaadin/flow/2908#-KypaCzfc21WVYbqioxy:-KypaCzfc21WVYbqioxz:b3ety1w) ([raw file](https://github.com/vaadin/flow/blob/eb37b69d01e2a3e4541a483435464fe2f927b069/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L925)):*
> ```Java
>                 .keySet();
>         List<String> matchingSortingProperties = Arrays
>                 .asList(sortingProperties).stream()
> ```

Instead of `Arrays.asList(sortingProperties).stream()`, use simply `Arrays.stream(sortingProperties)`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2908)*

**Comment by ahie** [comment]
Review status: 9 of 11 files reviewed at latest revision, 16 unresolved discussions, some commit checks failed.

---

*[flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/grid/GridSortingTest.java, line 178 at r1](https://reviewable.io:443/reviews/vaadin/flow/2908#-KypVKd-K-Be8gtL0CPb:-Kypjux4yD1rQpY87L5I:b-581ruj) ([raw file](https://github.com/vaadin/flow/blob/eb37b69d01e2a3e4541a483435464fe2f927b069/flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/grid/GridSortingTest.java#L178)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

Test name should be more descriptive of what is actually being verified here. It also seems to be too big, testing multiple things, so I would prefer slicing it into distinct smaller tests, with more of the repeating low-level setup code factored out into helper methods, to make the code easier to read.
</blockquote></details>

Looking into making more tests and splitting this up.

---

*[flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/grid/GridSortingTest.java, line 226 at r1](https://reviewable.io:443/reviews/vaadin/flow/2908#-KypUgEH5JywuvndfnBG:-KypjSYLNOdXSRj2RzJP:bbfq1h4) ([raw file](https://github.com/vaadin/flow/blob/eb37b69d01e2a3e4541a483435464fe2f927b069/flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/grid/GridSortingTest.java#L226)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

Why handle these exceptions manually here, instead of passing them on to the test runner to report?
</blockquote></details>

Don't want a long list of `throws ...` on every method that might call this. Also the message makes it clear what went wrong if this ever starts failing.

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 430 at r1](https://reviewable.io:443/reviews/vaadin/flow/2908#-KypXOdEAmETaogLZAPA:-KyphRVz4SXLDO1w9jsF:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/eb37b69d01e2a3e4541a483435464fe2f927b069/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L430)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

"must not" would be more precise
</blockquote></details>

Done.

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 450 at r1](https://reviewable.io:443/reviews/vaadin/flow/2908#-KypTTLQG_k8ZyYMHlkp:-KyphS26plnxJC6E5ieZ:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/eb37b69d01e2a3e4541a483435464fe2f927b069/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L450)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Copy-paste failure: `comparator`  -> `keyExtractor`
</blockquote></details>

Done.

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 450 at r1](https://reviewable.io:443/reviews/vaadin/flow/2908#-KypX_t4f7pLY37vhwq4:-KyphSTOcO1J0kk2Gwm6:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/eb37b69d01e2a3e4541a483435464fe2f927b069/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L450)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Done.

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 488 at r1](https://reviewable.io:443/reviews/vaadin/flow/2908#-KypXilaNX27eoURgvj7:-KyphSr7b4UHJCQkBxwI:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/eb37b69d01e2a3e4541a483435464fe2f927b069/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L488)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

and here
</blockquote></details>

Done.

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 513 at r1](https://reviewable.io:443/reviews/vaadin/flow/2908#-KypXml9UIt2o2iOY2vD:-KyphTMG32bL20CK0RZ1:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/eb37b69d01e2a3e4541a483435464fe2f927b069/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L513)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

and here
</blockquote></details>

Done.

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 552 at r1](https://reviewable.io:443/reviews/vaadin/flow/2908#-KypYIp0_lBHYdAPRBUr:-KyphUaDRfqkT3osr5g0:b-8wehfj) ([raw file](https://github.com/vaadin/flow/blob/eb37b69d01e2a3e4541a483435464fe2f927b069/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L552)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

Has the columnId been validated / escaped before? It apparently isn't validated in the `Column` constructor - can we trust its caller that it isn't trying anything naughty like HTML / Javascript injection?
</blockquote></details>

There is no way for the user to set to column id at the moment, it is generated by the grid.

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 553 at r1](https://reviewable.io:443/reviews/vaadin/flow/2908#-Kyp_IwpEPb4OT6ROjwc:-KyphjaCmjAELBtoyywY:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/eb37b69d01e2a3e4541a483435464fe2f927b069/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L553)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

could extract `HtmlUtils.escape(header)` calls into local variable
</blockquote></details>

Done.

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 922 at r1](https://reviewable.io:443/reviews/vaadin/flow/2908#-Kyp_jBVOczU7ogP02kv:-KyphrFtWM4oyhhDNVyB:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/eb37b69d01e2a3e4541a483435464fe2f927b069/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L922)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

there is already a local variable right above for `renderer.getValueProviders()`
</blockquote></details>

Done.

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 925 at r1](https://reviewable.io:443/reviews/vaadin/flow/2908#-KypaCzfc21WVYbqioxy:-KyphwUdfGc3I-ZSwHL6:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/eb37b69d01e2a3e4541a483435464fe2f927b069/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L925)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

Instead of `Arrays.asList(sortingProperties).stream()`, use simply `Arrays.stream(sortingProperties)`
</blockquote></details>

Done.

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 1392 at r1](https://reviewable.io:443/reviews/vaadin/flow/2908#-KypV8nN3SH6JTzjYdcr:-Kypi3J8bCWpGRpgM_ki:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/eb37b69d01e2a3e4541a483435464fe2f927b069/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L1392)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Most of our interaction with the components is done by using properties instead of attributes. In this case you could use the `multiSort` property - and you don't even need to store it as a separate field. You could use the property from the element directly.
</blockquote></details>

Done.

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/GridSortOrderBuilder.java, line 31 at r1](https://reviewable.io:443/reviews/vaadin/flow/2908#-KypWTXDUExh6CeFd3Nf:-Kypi8BctIllsJ2F2Hvr:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/eb37b69d01e2a3e4541a483435464fe2f927b069/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/GridSortOrderBuilder.java#L31)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Missing `@author Vaadin Ltd` - I guess Sonar should point this out though.
</blockquote></details>

Done.

---

*[flow-components-parent/flow-components/src/main/resources/META-INF/resources/gridConnector.js, line 102 at r1](https://reviewable.io:443/reviews/vaadin/flow/2908#-KypWm0vMSKESuglmMjy:-KypiBqKVGsnJsEDf5_n:byy0rtn) ([raw file](https://github.com/vaadin/flow/blob/eb37b69d01e2a3e4541a483435464fe2f927b069/flow-components-parent/flow-components/src/main/resources/META-INF/resources/gridConnector.js#L102)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Can't you use the regular event handling in flow, without using a custom function to call a `ClientDelegate` ?
</blockquote></details>

This listener collects all the current sorters (only the values of interest) and transmits them as a list. Also `_sorters` isn't defined as `notify: true` and I would rather not listen directly to a private property.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2908)*

**Comment by gilberto-torrezan** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 1394 at r3](https://reviewable.io:443/reviews/vaadin/flow/2908#-Kypkmj-EU4B2Y5meVvh:-Kypkmj-EU4B2Y5meVvi:b-403d2r) ([raw file](https://github.com/vaadin/flow/blob/ba6f14bdf7d2d4a90b438bb8c56255e47bcdb5ed/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L1394)):*
> ```Java
>      */
>     public void setMultiSort(boolean multiSort) {
>         getElement().setProperty("multi-sort", multiSort);
> ```

Does the `multi-sort` work? The property in the docs is `multiSort`, but I'm not sure if there's some conversion under the hood.

---

*[flow-components-parent/flow-components/src/main/resources/META-INF/resources/gridConnector.js, line 102 at r1](https://reviewable.io:443/reviews/vaadin/flow/2908#-KypWm0vMSKESuglmMjy:-KyplKASPHtU5CDUlH00:bvqwqsp) ([raw file](https://github.com/vaadin/flow/blob/eb37b69d01e2a3e4541a483435464fe2f927b069/flow-components-parent/flow-components/src/main/resources/META-INF/resources/gridConnector.js#L102)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

This listener collects all the current sorters (only the values of interest) and transmits them as a list. Also `_sorters` isn't defined as `notify: true` and I would rather not listen directly to a private property.
</blockquote></details>

Ok, but the lack of this feature on the element level sounds like a ticket for the elements team.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2908)*

**Comment by ahie** [comment]
Review status: 10 of 11 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 1394 at r3](https://reviewable.io:443/reviews/vaadin/flow/2908#-Kypkmj-EU4B2Y5meVvh:-KypoAdAFlW-KsfnuirY:bt2vr1b) ([raw file](https://github.com/vaadin/flow/blob/ba6f14bdf7d2d4a90b438bb8c56255e47bcdb5ed/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L1394)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Does the `multi-sort` work? The property in the docs is `multiSort`, but I'm not sure if there's some conversion under the hood.
</blockquote></details>

Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2908)*

**Comment by gilberto-torrezan** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2908)*

**Comment by torok-peter** [comment]
Reviewed 1 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks broke.

---

*[flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/grid/GridSortingTest.java, line 226 at r1](https://reviewable.io:443/reviews/vaadin/flow/2908#-KypUgEH5JywuvndfnBG:-KyptOgiRg2huy43T-PP:b-ogdg6d) ([raw file](https://github.com/vaadin/flow/blob/eb37b69d01e2a3e4541a483435464fe2f927b069/flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/grid/GridSortingTest.java#L226)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

Don't want a long list of `throws ...` on every method that might call this. Also the message makes it clear what went wrong if this ever starts failing.
</blockquote></details>

`throws Exception` would do just fine

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 552 at r1](https://reviewable.io:443/reviews/vaadin/flow/2908#-KypYIp0_lBHYdAPRBUr:-KypuVb_e4WdRMN_igik:b-501vro) ([raw file](https://github.com/vaadin/flow/blob/eb37b69d01e2a3e4541a483435464fe2f927b069/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L552)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

There is no way for the user to set to column id at the moment, it is generated by the grid.
</blockquote></details>

It's not necessarily coming from the user directly - someone could override the column generator code in a subclass of Grid, for example. Moreover, future changes may open up unforeseen attack routes. It would be more secure to escape `columnId` here, just to be on the safe side.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2908)*

**Comment by ahie** [comment]
Review status: 8 of 11 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/grid/SortOrderBuildersTest.java, line 80 at r1](https://reviewable.io:443/reviews/vaadin/flow/2908#-KypWr_ymvwIvVJRKH9G:-KytR-rPrhLZsR3j_vob:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/eb37b69d01e2a3e4541a483435464fe2f927b069/flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/grid/SortOrderBuildersTest.java#L80)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

Test also different column sort orders, like 3,2,1 / c,b,a or 2,1,3 / b,a,c
</blockquote></details>

Done.

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 552 at r1](https://reviewable.io:443/reviews/vaadin/flow/2908#-KypYIp0_lBHYdAPRBUr:-KytRK5o9ng_sKROCO5f:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/eb37b69d01e2a3e4541a483435464fe2f927b069/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L552)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

It's not necessarily coming from the user directly - someone could override the column generator code in a subclass of Grid, for example. Moreover, future changes may open up unforeseen attack routes. It would be more secure to escape `columnId` here, just to be on the safe side.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2908)*

**Comment by gilberto-torrezan** [comment]
Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 911 at r5](https://reviewable.io:443/reviews/vaadin/flow/2908#-KytjC_w30tAIsMyWOG-:-KytjC_w30tAIsMyWOG0:b-mozzog) ([raw file](https://github.com/vaadin/flow/blob/6a7b4ac601de391b1f4e9c2bf0783725deaa6a5d/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L911)):*
> ```Java
>      * <p>
>      * <strong>Note:</strong> if a property of the renderer that is used as a
>      * sorting property does not extend Comparable no in-memory sorting is
> ```

Small thing, I suggest putting a comma in the sentence to make it better to read. Some like this: `if [...] does not extend Comparable, no in-memory sorting is configured for it.`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2908)*

**Comment by gilberto-torrezan** [comment]
Reviewed 3 of 3 files at r6.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2908)*

**Comment by torok-peter** [comment]
Reviewed 2 of 3 files at r5, 3 of 3 files at r6.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 552 at r1](https://reviewable.io:443/reviews/vaadin/flow/2908#-KypYIp0_lBHYdAPRBUr:-KytpS3z0EnZXJdtn0BT:bmoghym) ([raw file](https://github.com/vaadin/flow/blob/eb37b69d01e2a3e4541a483435464fe2f927b069/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L552)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Escaped in the wrong place (I suppose `Element.setAttribute()` escapes it anyway).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2908)*

**Comment by ahie** [comment]
Review status: 10 of 11 files reviewed at latest revision, 4 unresolved discussions.

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 552 at r1](https://reviewable.io:443/reviews/vaadin/flow/2908#-KypYIp0_lBHYdAPRBUr:-KyuIoBQcqbf39Opo7GC:b-lx4fj3) ([raw file](https://github.com/vaadin/flow/blob/eb37b69d01e2a3e4541a483435464fe2f927b069/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L552)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

Escaped in the wrong place (I suppose `Element.setAttribute()` escapes it anyway).
</blockquote></details>

Fixed. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2908)*

**Comment by gilberto-torrezan** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2908)*

**Comment by torok-peter** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2908)*

**Pull request merged**
