### PR TITLE
Make Lit import rewrites lazy

### PR DESCRIPTION
**Pull request by Artur-**
The import rewrites must only match one row and not a similar import on the following row

Fixes https://github.com/vaadin/component-starter-flow/issues/369

### CODE REVIEW

**Comment by Artur-** [comment]
Maybe it would make sense to add an IT to this..

**Comment by mshabarov** [comment]
Tested manually with `component-starter-flow`. The original errors are gone, but I have others:

```
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker -  ERROR(TypeScript)  Type 'TemplateResult' is not generic.
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker -  FILE  /Users/mikhail/workspace/vaadin/component-starter-flow/target/flow-frontend/vaadin-dev-tools.d.ts:110:44
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker - 
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker -     108 |     setActive(yes: boolean): void;
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker -     109 |     getStatusColor(status: ConnectionStatus | undefined): import("lit").CSSResult;
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker -   > 110 |     renderMessage(messageObject: Message): import("lit-html").TemplateResult<1>;
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker -         |                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker -     111 |     render(): import("lit-html").TemplateResult<1>;
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker -     112 |     renderLog(): import("lit-html").TemplateResult<1>;
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker -     113 |     activateLog(): void;
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker - 
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker -  ERROR(TypeScript)  Type 'TemplateResult' is not generic.
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker -  FILE  /Users/mikhail/workspace/vaadin/component-starter-flow/target/flow-frontend/vaadin-dev-tools.d.ts:111:15
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker - 
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker -     109 |     getStatusColor(status: ConnectionStatus | undefined): import("lit").CSSResult;
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker -     110 |     renderMessage(messageObject: Message): import("lit-html").TemplateResult<1>;
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker -   > 111 |     render(): import("lit-html").TemplateResult<1>;
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker -         |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker -     112 |     renderLog(): import("lit-html").TemplateResult<1>;
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker -     113 |     activateLog(): void;
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker -     114 |     renderInfo(): import("lit-html").TemplateResult<1>;
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker - 
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker -  ERROR(TypeScript)  Type 'TemplateResult' is not generic.
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker -  FILE  /Users/mikhail/workspace/vaadin/component-starter-flow/target/flow-frontend/vaadin-dev-tools.d.ts:112:18
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker - 
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker -     110 |     renderMessage(messageObject: Message): import("lit-html").TemplateResult<1>;
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker -     111 |     render(): import("lit-html").TemplateResult<1>;
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker -   > 112 |     renderLog(): import("lit-html").TemplateResult<1>;
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker -         |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker -     113 |     activateLog(): void;
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker -     114 |     renderInfo(): import("lit-html").TemplateResult<1>;
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker -     115 |     private renderFeatures;
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker - 
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker -  ERROR(TypeScript)  Type 'TemplateResult' is not generic.
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker -  FILE  /Users/mikhail/workspace/vaadin/component-starter-flow/target/flow-frontend/vaadin-dev-tools.d.ts:114:19
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker - 
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker -     112 |     renderLog(): import("lit-html").TemplateResult<1>;
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker -     113 |     activateLog(): void;
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker -   > 114 |     renderInfo(): import("lit-html").TemplateResult<1>;
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker -         |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker -     115 |     private renderFeatures;
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker -     116 |     copyInfoToClipboard(): void;
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker -     117 |     toggleFeatureFlag(e: Event, feature: Feature): void;
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker - 
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker - [TypeScript] Found 4 errors. Watching for file changes.

```

Apparently this is caused by `lit-html` versions mismatch: `TemplateResult` is a generic type in one version, but not generic in the another version.

**Comment by Artur-** [comment]
Added test

**Comment by Artur-** [comment]
>Tested manually with component-starter-flow. The original errors are gone, but I have others:

Sounds unrelated to this issue

**Review by mshabarov — APPROVED** [review]

**Pull request merged**
