### PR TITLE
Remove components except Grid from Flow.

### PR DESCRIPTION
**Pull request by caalador**
Components are in their own repositories now
and should be fixed / updated there and not in Flow
as we get out of synch too easily.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/2961)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 23 of 23 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-components-parent/demo-flow-components/pom.xml, line 57 at r1](https://reviewable.io:443/reviews/vaadin/flow/2961#-Kz7aHQnDPIWqXacqDs5:-Kz7aHQnDPIWqXacqDs6:b-jk9zf6) ([raw file](https://github.com/vaadin/flow/blob/9ac9b5fe36cdf1056122f5196d62193fa2a56bab/flow-components-parent/demo-flow-components/pom.xml#L57)):*
> <version>1.0.0.alpha1</version>

There is an is an issue with the current approach in component versioning.
It's impossible to add a new component.
Because the component version has release version which refers to the Flow release vesion
which most likely is not what you want (e.g. web-jar has an incorrect version).

We should use snapshots everywhere: for components for Flow hardcoded in the POM files.
And use the same release procedure for the component: once it's released it gets the release version.

Another issue for now is that we have no snapshot versions for components 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2961)*

**Comment by caalador** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[flow-components-parent/demo-flow-components/pom.xml, line 57 at r1](https://reviewable.io:443/reviews/vaadin/flow/2961#-Kz7aHQnDPIWqXacqDs5:-Kz7dOKUO7_vhLrfvuIh:b9vayxj) ([raw file](https://github.com/vaadin/flow/blob/9ac9b5fe36cdf1056122f5196d62193fa2a56bab/flow-components-parent/demo-flow-components/pom.xml#L57)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> <version>1.0.0.alpha1</version>

There is an is an issue with the current approach in component versioning.
It's impossible to add a new component.
Because the component version has release version which refers to the Flow release vesion
which most likely is not what you want (e.g. web-jar has an incorrect version).

We should use snapshots everywhere: for components for Flow hardcoded in the POM files.
And use the same release procedure for the component: once it's released it gets the release version.

Another issue for now is that we have no snapshot versions for components 
</blockquote></details>

This is true, but the aim should be to remove both `flow-components` and `demo-flow-components`

The items are right now still in `flow-components` because the junit tests are there. Those should be migrated to 
the correct repos from here.

I'll look through the IT tests and remove those as they should already be in the component repositories.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2961)*

**Comment by gilberto-torrezan** [comment]
Review status: 21 of 34 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2961#-Kz7hewnBP2Y2McOCGQ_:-Kz7hewnBP2Y2McOCGQa:bfzapu) (no related file):*
Why "except Grid" by the way?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2961)*

**Comment by caalador** [comment]
Review status: 21 of 34 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2961#-Kz7hewnBP2Y2McOCGQ_:-Kz7ooS7EqhCgYShugvl:b-mp939c) (no related file):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Why "except Grid" by the way?
</blockquote></details>

Because you are still working on Grid in Flow and it doesn't have a own repo right now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2961)*

**Comment by denis-anisimov** [comment]
Reviewed 13 of 13 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2961)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2961)*

**Comment by denis-anisimov** [comment]
Reviewed 37 of 37 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2961)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 37 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2961)*

**Pull request merged**
