### PR TITLE
Mock System.getProperty in DevModeHandlerTest using PowerMock

### PR DESCRIPTION
**Pull request by mehdi-vaadin**
This is an example of how to get rid of calling `System.setProperty` in tests using PowerMock.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/7785)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
It would be really nice to get rid of `System` static calls.
But the validation fails: it's not that easy.
If you will be able to fix this then that will be a great improvement !

**Comment by mshabarov** [comment]
Awesome! I believe PowerMock is one of the few which provide static method mocking, since it's not trivial.

**Comment by mehdi-vaadin** [comment]
I couldn't spend time to fix it yet. I hope I can do it on CF someday :)

**Comment by mehdi-vaadin** [comment]
One point is that if we could upgrade Mockito and JUnit to newer versions it would be much easier to use PowerMock and possibly other similar tools. But, that needs a lot of effort.

**Comment by pleku** [comment]
As Mockito nowdays supports static Mocking, I'm not sure if this is still relevant ? Also I would encourage not introducing PowerMock since it is not compatible with newer versions of Mockito.

**Pull request closed without merging**
