### PR TITLE
Update Polymer Analyzer and fix bom dependency on the flow-webcomponent-api-analyzer module

### PR DESCRIPTION
**Pull request by gilberto-torrezan**
All the components were regenerated.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/2790)

### CODE REVIEW

**Comment by ahie** [comment]
Review status: 0 of 62 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2790#-KxShq3ukDGuKo4ZOGKz:-KxShq3ukDGuKo4ZOGL-:bsw5uzk) (no related file):*
Looks like the new analyzer has renamed/removed the `description` information?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2790)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 62 of 62 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2790)*

**Comment by SomeoneToIgnore** [comment]
*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2790#-KxShq3ukDGuKo4ZOGKz:-KxSiLOZUyXTe3Ev4nc0:b-jmtv2y) (no related file):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

Looks like the new analyzer has renamed/removed the `description` information?
</blockquote></details>

And added a bunch of new methods for layouts.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2790)*

**Comment by gilberto-torrezan** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2790#-KxShq3ukDGuKo4ZOGKz:-KxSkJ4ZAsheBh6gEKLt:b5tu3gb) (no related file):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

And added a bunch of new methods for layouts.
</blockquote></details>

The description is gone only for paper elements though. Weird.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2790)*

**Comment by denis-anisimov** [comment]
Sorry, Gilberto, you have to regenerate the components.

**Comment by caalador** [comment]
Will this PR be updated or will this be closed and a new PR made at a later time?

**Comment by SomeoneToIgnore** [comment]
Closed since no activity is made for a long time.

**Pull request closed without merging**
