### PR TITLE
Return 404 when not able to parse url parameter.

### PR DESCRIPTION
**Pull request by SomeoneToIgnore**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3528)

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
*[flow-server/src/main/java/com/vaadin/flow/router/internal/NavigationStateRenderer.java, line 157 at r1](https://reviewable.io:443/reviews/vaadin/flow/3528#-L4uwYE2ZBSKibsIpvBE:-L4uwYE2ZBSKibsIpvBF:b1st388) ([raw file](https://github.com/vaadin/flow/blob/f8e222dec6022dcf296ed20193a99861fb80a8ce/flow-server/src/main/java/com/vaadin/flow/router/internal/NavigationStateRenderer.java#L157)):*
> ```Java
>                         ParameterDeserializer.deserializeUrlParameters(
>                                 routeTargetType, urlParameters.get()));
>             } catch (Exception e) {
> ```

I'm not sure this is the right way to do it.
Alternatively, we can change `ParameterDeserializer` to return an object that will contain deserialization result and an optional error message.
But this requires `ParameterDeserializer` public api to be changes, so I'm not sure if we should do it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3528)*

**Comment by caalador** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-server/src/main/java/com/vaadin/flow/router/internal/NavigationStateRenderer.java, line 157 at r1](https://reviewable.io:443/reviews/vaadin/flow/3528#-L4uwYE2ZBSKibsIpvBE:-L57fPE-unRPrqPtRiGC:brfumq) ([raw file](https://github.com/vaadin/flow/blob/f8e222dec6022dcf296ed20193a99861fb80a8ce/flow-server/src/main/java/com/vaadin/flow/router/internal/NavigationStateRenderer.java#L157)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

I'm not sure this is the right way to do it.
Alternatively, we can change `ParameterDeserializer` to return an object that will contain deserialization result and an optional error message.
But this requires `ParameterDeserializer` public api to be changes, so I'm not sure if we should do it.
</blockquote></details>

Only have the deserialise inside the try catch as now the exception may be in the developer code in setParameter that will then show as a parsing error.
The setParameter should fail on an internalError.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3528)*

**Comment by SomeoneToIgnore** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-server/src/main/java/com/vaadin/flow/router/internal/NavigationStateRenderer.java, line 157 at r1](https://reviewable.io:443/reviews/vaadin/flow/3528#-L4uwYE2ZBSKibsIpvBE:-L58NJwaBu_HxLFfcBSI:bcppo66) ([raw file](https://github.com/vaadin/flow/blob/f8e222dec6022dcf296ed20193a99861fb80a8ce/flow-server/src/main/java/com/vaadin/flow/router/internal/NavigationStateRenderer.java#L157)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Only have the deserialise inside the try catch as now the exception may be in the developer code in setParameter that will then show as a parsing error.
The setParameter should fail on an internalError.
</blockquote></details>

Right, updated.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3528)*

**Comment by caalador** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3528)*

**Pull request merged**
