### PR TITLE
Collect custom components in Spring Boot application

### PR DESCRIPTION
**Pull request by denis-anisimov**
Refactor router servlet context initializer so that it also cares about custom elements.

Fix for #2595

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/2654)

### CODE REVIEW

**Comment by Legioth** [comment]
Review status: 0 of 17 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2654#-KwAQK3Rq0ZMo4Wprxtj:-KwAQK3Rq0ZMo4Wprxtk:b8fp7uo) (no related file):*
Might not be relevant if we do #2486 instead

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2654)*

**Comment by denis-anisimov** [comment]
Review status: 0 of 17 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2654#-KwAQK3Rq0ZMo4Wprxtj:-KwAcy_p9k8XCGnqa-5G:b-emi1fi) (no related file):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

Might not be relevant if we do #2486 instead
</blockquote></details>

Does it hurt to have it now since it's already implemented.

Let's decide what to do with this ASAP.
This patch contains changes that I would like to have for another patch.
If we are not going to merge it then I will extract them for another patch and close this one.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2654)*

**Comment by caalador** [comment]
Reviewed 17 of 18 files at r1.
Review status: 16 of 17 files reviewed at latest revision, 5 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/server/startup/CustomElementRegistry.java, line 48 at r1](https://reviewable.io:443/reviews/vaadin/flow/2654#-KwEIBdepwx9QBQet5-2:-KwEIBdepwx9QBQet5-3:bvif6v0) ([raw file](https://github.com/vaadin/flow/blob/c069f97e4babb23547faa30cbf05a717525345c7/flow-server/src/main/java/com/vaadin/server/startup/CustomElementRegistry.java#L48)):*
> ```Java
>     }
> 
>     public boolean isInitialized() {
> ```

JavaDoc for public method.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2654)*

**Comment by caalador** [comment]
Reviewed 1 of 18 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2654)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2654)*

**Pull request merged**
