### PR TITLE
fix: set "href" for element inside template as an attribute not a pro…

### LINKED ISSUE #11349: Regression in Anchor component
When upgrading from 14.4.10 to 14.6.1 the anchor component no longer sets the href attribute after the initial render.

This applies to both PolymerTemplate and LitTemplate.

See issue #3839 for attached code.

### PR DESCRIPTION
**Pull request by denis-anisimov**
…perty

fixes #11349

## Description

Please list all relevant dependencies in this section and provide summary of the change, motivation and context.

Fixes # (issue)

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [ ] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [ ] I have added a description following the guideline.
- [ ] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

### CODE REVIEW

**Review by caalador — APPROVED** [review]

**Review by caalador — COMMENTED** [review]
If adding IT then it should also be in polymer so both are tested the same.

**Comment by denis-anisimov** [comment]
> If adding IT then it should also be in polymer so both are tested the same.

Polymer is deprecated. So don't see a reason to have ITs for deprecated features.

**Comment by caalador** [comment]
It's not deprecated in 14.x series

**Comment by denis-anisimov** [comment]
> It's not deprecated in 14.x series

This is a `master` branch.

**Review by caalador — APPROVED** [review]

**Pull request merged**
