### PR TITLE
Add support for single item refreshes in DataCommunicator

### PR DESCRIPTION
**Pull request by ahie**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/2690)

### CODE REVIEW

**Comment by gilberto-torrezan** [comment]
Review status: 0 of 5 files reviewed at latest revision, 12 unresolved discussions, some commit checks broke.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2690#-KwcsJBWEW2biIRXWbto:-KwcsJBWEW2biIRXWbtp:b-c57pn) (no related file):*
I suggest add a sanity check test for the `updateData` function - a test to make sure the `updateData` function doesn't exist in the grid before you create it with the connector.

The reason is that the webcomponent can start having a function with that name in the future, and we don't want to be caught by surprise in case that happens.

Another way is to change the function name to be something exotic enough that the webcomponent would never have such function. But then we lose readability.

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 616 at r1](https://reviewable.io:443/reviews/vaadin/flow/2690#-KwcriMoih4nZGJzDJkA:-KwcriMoih4nZGJzDJkB:b9z6lpj) ([raw file](https://github.com/vaadin/flow/blob/892456da1a7aaf7367d10f1d617a4f464ccde49b/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L616)):*
> ```Java
>     @Override
>     public void setDataProvider(DataProvider<T, ?> dataProvider) {
>         Objects.requireNonNull(dataProvider, "data provider cannot be null");
> ```

The `DataCommunicator::setDataProvider` already checks for `null`. You don't need to check twice.

---

*[flow-components-parent/flow-components/src/main/resources/META-INF/resources/gridConnector.js, line 121 at r1](https://reviewable.io:443/reviews/vaadin/flow/2690#-Kwcp61ienCSWRRJWmFZ:-Kwcp61ienCSWRRJWmF_:bco7jgf) ([raw file](https://github.com/vaadin/flow/blob/892456da1a7aaf7367d10f1d617a4f464ccde49b/flow-components-parent/flow-components/src/main/resources/META-INF/resources/gridConnector.js#L121)):*
> ```JavaScript
>         };
> 
>         var itemToCacheLocation = function(itemKey) {
> ```

Note: IE11 supports `let` and `const`, so we can use those instead of `var`. Not a blocker though.

---

*[flow-data/src/main/java/com/vaadin/data/provider/DataCommunicator.java, line 277 at r1](https://reviewable.io:443/reviews/vaadin/flow/2690#-Kwco3_Ee_DH81Rd0dK6:-Kwco3_Ee_DH81Rd0dK7:b-u5wuiq) ([raw file](https://github.com/vaadin/flow/blob/892456da1a7aaf7367d10f1d617a4f464ccde49b/flow-data/src/main/java/com/vaadin/data/provider/DataCommunicator.java#L277)):*
> ```Java
>     }
> 
>     private void handleAttach() {
> ```

Since `handleAttach` and `attachDataProviderListener` are both private, why not calling `attachDataProviderListener` directly  are remove this method? Or rename the `attachDataProviderListener`.

---

*[flow-data/src/main/java/com/vaadin/data/provider/DataCommunicator.java, line 281 at r1](https://reviewable.io:443/reviews/vaadin/flow/2690#-KwcoL515VOmYKZunwTH:-KwcoL515VOmYKZunwTI:b-9ttr4) ([raw file](https://github.com/vaadin/flow/blob/892456da1a7aaf7367d10f1d617a4f464ccde49b/flow-data/src/main/java/com/vaadin/data/provider/DataCommunicator.java#L281)):*
> ```Java
>     }
> 
>     private void handleDetach() {
> ```

Same question as above, but for the detach

---

*[flow-data/src/main/java/com/vaadin/data/provider/DataCommunicator.java, line 504 at r1](https://reviewable.io:443/reviews/vaadin/flow/2690#-KwconWRhnp_dKZpM0V2:-KwconWRhnp_dKZpM0V3:bnbgj2z) ([raw file](https://github.com/vaadin/flow/blob/892456da1a7aaf7367d10f1d617a4f464ccde49b/flow-data/src/main/java/com/vaadin/data/provider/DataCommunicator.java#L504)):*
> ```Java
>         dataProviderUpdateRegistration = getDataProvider()
>                 .addDataProviderListener(event -> {
>                     UI.getCurrent().access(() -> {
> ```

Is the `UI.access` really needed here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2690)*

**Comment by gilberto-torrezan** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2690)*

**Comment by torok-peter** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 12 unresolved discussions, some commit checks broke.

---

*[flow-components-parent/flow-components-test/src/main/java/com/vaadin/flow/components/it/grid/GridItemRefreshView.java, line 86 at r1](https://reviewable.io:443/reviews/vaadin/flow/2690#-KwdHc1YqUbOYagBa4hH:-KwdHc1YqUbOYagBa4hI:b-g6ndoj) ([raw file](https://github.com/vaadin/flow/blob/892456da1a7aaf7367d10f1d617a4f464ccde49b/flow-components-parent/flow-components-test/src/main/java/com/vaadin/flow/components/it/grid/GridItemRefreshView.java#L86)):*
> ```Java
>                         UPDATED_FIRST_FIELD + " " + item.getFirstField());
>                 item.setSecondField(UPDATED_SECOND_FIELD);
>             });
> ```

Could extract the loop body into a named method to reduce code duplication

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2690)*

**Comment by ahie** [comment]
Review status: all files reviewed at latest revision, 13 unresolved discussions, some commit checks broke.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2690#-KwcsJBWEW2biIRXWbto:-KwdzEcNZSV7uTMFszdv:b-kj0sqx) (no related file):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

I suggest add a sanity check test for the `updateData` function - a test to make sure the `updateData` function doesn't exist in the grid before you create it with the connector.

The reason is that the webcomponent can start having a function with that name in the future, and we don't want to be caught by surprise in case that happens.

Another way is to change the function name to be something exotic enough that the webcomponent would never have such function. But then we lose readability.
</blockquote></details>

There are several methods that are directly added to the `Grid`. We should come up with a naming convention that minimizes the risk of conflict and apply it to all the existing methods. Something like `grid.$connector.foo` perhaps?

---

*[flow-components-parent/flow-components-test/src/main/java/com/vaadin/flow/components/it/grid/GridItemRefreshView.java, line 86 at r1](https://reviewable.io:443/reviews/vaadin/flow/2690#-KwdHc1YqUbOYagBa4hH:-Kwdyq34QDjFxdJ-Z_0W:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/892456da1a7aaf7367d10f1d617a4f464ccde49b/flow-components-parent/flow-components-test/src/main/java/com/vaadin/flow/components/it/grid/GridItemRefreshView.java#L86)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

Could extract the loop body into a named method to reduce code duplication
</blockquote></details>

Done.

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 616 at r1](https://reviewable.io:443/reviews/vaadin/flow/2690#-KwcriMoih4nZGJzDJkA:-Kwdw7Bb6SBn0AFvIB5K:b-1bqwa7) ([raw file](https://github.com/vaadin/flow/blob/892456da1a7aaf7367d10f1d617a4f464ccde49b/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L616)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

The `DataCommunicator::setDataProvider` already checks for `null`. You don't need to check twice.
</blockquote></details>

Javadocs of `HasDataProvider.setDataProvider` state it cannot be `null`, so added the check here as well. I think the resulting stack trace will also be more clear if the exception is also thrown here. In any case the double check doesn't hurt.

---

*[flow-components-parent/flow-components/src/main/resources/META-INF/resources/gridConnector.js, line 121 at r1](https://reviewable.io:443/reviews/vaadin/flow/2690#-Kwcp61ienCSWRRJWmFZ:-KwdwcCJPgFuacpWtHKn:b-3tmwga) ([raw file](https://github.com/vaadin/flow/blob/892456da1a7aaf7367d10f1d617a4f464ccde49b/flow-components-parent/flow-components/src/main/resources/META-INF/resources/gridConnector.js#L121)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Note: IE11 supports `let` and `const`, so we can use those instead of `var`. Not a blocker though.
</blockquote></details>

True, but seeing that the whole file is written in "old javascript" this is more consistent. If/when we end up having to add more client side code like this it could be worth investigating adding a build step that does transpilation from es6+ to js that is compatible with all the supported browsers, so that we could develop with something more modern.

---

*[flow-data/src/main/java/com/vaadin/data/provider/DataCommunicator.java, line 277 at r1](https://reviewable.io:443/reviews/vaadin/flow/2690#-Kwco3_Ee_DH81Rd0dK6:-KwdxctTMl2pwzLH2aZE:b-1enmyj) ([raw file](https://github.com/vaadin/flow/blob/892456da1a7aaf7367d10f1d617a4f464ccde49b/flow-data/src/main/java/com/vaadin/data/provider/DataCommunicator.java#L277)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Since `handleAttach` and `attachDataProviderListener` are both private, why not calling `attachDataProviderListener` directly  are remove this method? Or rename the `attachDataProviderListener`.
</blockquote></details>

For clarity, in case handling attach/detach will later need more logic. Anyway, removed the additional methods.

---

*[flow-data/src/main/java/com/vaadin/data/provider/DataCommunicator.java, line 504 at r1](https://reviewable.io:443/reviews/vaadin/flow/2690#-KwconWRhnp_dKZpM0V2:-Kwdxvc3q4lNjtZ5IZEK:b-bmlttp) ([raw file](https://github.com/vaadin/flow/blob/892456da1a7aaf7367d10f1d617a4f464ccde49b/flow-data/src/main/java/com/vaadin/data/provider/DataCommunicator.java#L504)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Is the `UI.access` really needed here?
</blockquote></details>

I also questioned this, but it was in use in FW8. Removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2690)*

**Comment by gilberto-torrezan** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2690#-KwcsJBWEW2biIRXWbto:-Kwe3FTYW0LAFx2WFtgF:bpb1giv) (no related file):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

There are several methods that are directly added to the `Grid`. We should come up with a naming convention that minimizes the risk of conflict and apply it to all the existing methods. Something like `grid.$connector.foo` perhaps?
</blockquote></details>

Sounds good. Do you want to change all the functions in this patch or create a separate ticket for that?

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 616 at r1](https://reviewable.io:443/reviews/vaadin/flow/2690#-KwcriMoih4nZGJzDJkA:-Kwe32dT02Q6ietzaRA5:b-ys42y7) ([raw file](https://github.com/vaadin/flow/blob/892456da1a7aaf7367d10f1d617a4f464ccde49b/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L616)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

Javadocs of `HasDataProvider.setDataProvider` state it cannot be `null`, so added the check here as well. I think the resulting stack trace will also be more clear if the exception is also thrown here. In any case the double check doesn't hurt.
</blockquote></details>

Hurts performance, but then this method is not supposed to be called several times per second. So it's ok.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2690)*

**Comment by ahie** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks broke.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2690#-KwcsJBWEW2biIRXWbto:-KweEwovUcrobQWbXt2g:bfvsozi) (no related file):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Sounds good. Do you want to change all the functions in this patch or create a separate ticket for that?
</blockquote></details>

Created a new issue for it https://github.com/vaadin/flow/issues/2697. Don't want to introduce many unrelated changes in this patch.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2690)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2690)*

**Pull request merged**
