### PR TITLE
Add tests for IronList component

### PR DESCRIPTION
**Pull request by gilberto-torrezan**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3029)

### CODE REVIEW

**Comment by torok-peter** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/iron/list/IronListViewIT.java, line 45 at r1](https://reviewable.io:443/reviews/vaadin/flow/3029#-KzhEcSQfAs2Nwn7S_H5:-KzhEcSQfAs2Nwn7S_H6:bbo23tu) ([raw file](https://github.com/vaadin/flow/blob/b88c665577b11c6de986469a1bca245037c90fb2/flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/iron/list/IronListViewIT.java#L45)):*
> ```Java
>     @Test
>     public void listWithStrings() {
>         testListOrDataProvider("list-with-strings", "list-with-strings-3-items",
> ```

It is far from obvious what this test and the 2 below are verifying; could you refactor the code to make it clearer?

---

*[flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/iron/list/IronListViewIT.java, line 73 at r1](https://reviewable.io:443/reviews/vaadin/flow/3029#-KzhFAJ3i1Nk1lmM5b5N:-KzhFAJ4O_HgHvEa8E7s:b-yrimx5) ([raw file](https://github.com/vaadin/flow/blob/b88c665577b11c6de986469a1bca245037c90fb2/flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/iron/list/IronListViewIT.java#L73)):*
> ```Java
>         Assert.assertEquals(3, items.length());
>         for (int i = 0; i < items.length(); i++) {
>             Assert.assertEquals(String.valueOf(i + 1),
> ```

Error description missing from all `assert*` calls

---

*[flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/iron/list/IronListViewIT.java, line 118 at r1](https://reviewable.io:443/reviews/vaadin/flow/3029#-KzhFenPjMm7RovDjeR-:-KzhFenQHDp_RXjY_ccL:brl55iy) ([raw file](https://github.com/vaadin/flow/blob/b88c665577b11c6de986469a1bca245037c90fb2/flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/iron/list/IronListViewIT.java#L118)):*
> ```Java
>         for (int i = 32; i < items.length(); i++) {
>             Assert.assertThat(items.get(i),
>                     CoreMatchers.instanceOf(JsonNull.class));
> ```

Using static imports would make the code easier to read

---

*[flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/iron/list/IronListViewIT.java, line 136 at r1](https://reviewable.io:443/reviews/vaadin/flow/3029#-KzhGC6rGOmO4Qt6iGOA:-KzhGC6rGOmO4Qt6iGOB:bhfutvc) ([raw file](https://github.com/vaadin/flow/blob/b88c665577b11c6de986469a1bca245037c90fb2/flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/iron/list/IronListViewIT.java#L136)):*
> ```Java
>         for (int i = items.length() - 32; i < items.length(); i++) {
>             if (items.get(i) instanceof JsonNull) {
>                 Assert.fail("Object at index " + i + " is null");
> ```

Why not `assertThat(items.get(i), not(instanceOf(JsonNull.class)));`?

---

*[flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/iron/list/IronListViewIT.java, line 159 at r1](https://reviewable.io:443/reviews/vaadin/flow/3029#-KzhEB4x3gegbPkNZXXU:-KzhEB4x3gegbPkNZXXV:b-yfnes9) ([raw file](https://github.com/vaadin/flow/blob/b88c665577b11c6de986469a1bca245037c90fb2/flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/iron/list/IronListViewIT.java#L159)):*
> ```Java
>         WebElement button1 = findElement(By.id(button1Id));
>         WebElement button2 = findElement(By.id(button2Id));
>         WebElement button3 = findElement(By.id(button3Id));
> ```

use more descriptive names

---

*[flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/iron/list/IronListViewIT.java, line 185 at r1](https://reviewable.io:443/reviews/vaadin/flow/3029#-KzhELuGQFxMDQfzpdpX:-KzhELuGQFxMDQfzpdpY:b78n5qr) ([raw file](https://github.com/vaadin/flow/blob/b88c665577b11c6de986469a1bca245037c90fb2/flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/iron/list/IronListViewIT.java#L185)):*
> ```Java
>         scrollIntoViewAndClick(button3);
>         waitUntil(driver -> getItems(list).length() == 0);
>     }
> ```

extract the different phases into separate methods with descriptive names

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3029)*

**Comment by gilberto-torrezan** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/iron/list/IronListViewIT.java, line 45 at r1](https://reviewable.io:443/reviews/vaadin/flow/3029#-KzhEcSQfAs2Nwn7S_H5:-KzhIYnoWzhwj7mKVof2:bod7729) ([raw file](https://github.com/vaadin/flow/blob/b88c665577b11c6de986469a1bca245037c90fb2/flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/iron/list/IronListViewIT.java#L45)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

It is far from obvious what this test and the 2 below are verifying; could you refactor the code to make it clearer?
</blockquote></details>

Three tests use the same structure, so I preferred to create a single method for them all, just changing the id of the tested elements. Aside from adding comments to it, do you suggest any other refactoring?

---

*[flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/iron/list/IronListViewIT.java, line 73 at r1](https://reviewable.io:443/reviews/vaadin/flow/3029#-KzhFAJ3i1Nk1lmM5b5N:-KzhJ81HcpYDBMlbESjM:bnbb4uk) ([raw file](https://github.com/vaadin/flow/blob/b88c665577b11c6de986469a1bca245037c90fb2/flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/iron/list/IronListViewIT.java#L73)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

Error description missing from all `assert*` calls
</blockquote></details>

`Assert.equals` gives a comprehensive error message already, do you want extra messages for each of the equals?

---

*[flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/iron/list/IronListViewIT.java, line 118 at r1](https://reviewable.io:443/reviews/vaadin/flow/3029#-KzhFenPjMm7RovDjeR-:-KzhJRKNi_Ebts2X_w7E:b63c6c8) ([raw file](https://github.com/vaadin/flow/blob/b88c665577b11c6de986469a1bca245037c90fb2/flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/iron/list/IronListViewIT.java#L118)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

Using static imports would make the code easier to read
</blockquote></details>

Sure, but most (or all?) Flow tests don't use static imports at all, so I just followed the pattern.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3029)*

**Comment by caalador** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3029#-Kzhf9fEVVGZAGosdS9-:-Kzhf9fEVVGZAGosdS90:b-e676cp) (no related file):*
Does this test have something specific that it needs from flow so that it needs to be in flow?

I almost would expect that the `flow-components-test` module should be removed as it's still using the old router and all the views should be at the component repositories.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3029)*

**Comment by gilberto-torrezan** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3029#-Kzhf9fEVVGZAGosdS9-:-Kzhlnn8o22KqiJDT7ul:b-at0vzd) (no related file):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Does this test have something specific that it needs from flow so that it needs to be in flow?

I almost would expect that the `flow-components-test` module should be removed as it's still using the old router and all the views should be at the component repositories.
</blockquote></details>

I expected that too as well. I even created a thread on Slack questioning about the location of these tests and I got mixed opinions about this. So I pushed them here, but I would prefer to have all the tests related to some component in its respective repo.

We have a potential problem in moving these tests to the component repos though - the test scope is used to create the demo jar (which will be used by `vaadin.com`), and that jar shouldn't contain extra views. So we can't use the test scope - or we need to change how the demo jar is built to manually exclude the extra tests.

Anyway, it's an open question. I could move these tests right away, but then I don't know if I would need to bring them back by the end of the day due to diverging opinions.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3029)*

**Comment by caalador** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3029#-Kzhf9fEVVGZAGosdS9-:-KzhnBidhy98nS3MYRx1:b4t47n) (no related file):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

I expected that too as well. I even created a thread on Slack questioning about the location of these tests and I got mixed opinions about this. So I pushed them here, but I would prefer to have all the tests related to some component in its respective repo.

We have a potential problem in moving these tests to the component repos though - the test scope is used to create the demo jar (which will be used by `vaadin.com`), and that jar shouldn't contain extra views. So we can't use the test scope - or we need to change how the demo jar is built to manually exclude the extra tests.

Anyway, it's an open question. I could move these tests right away, but then I don't know if I would need to bring them back by the end of the day due to diverging opinions.
</blockquote></details>

Right now the demo views for the demo are only classes matching  `**/*View.*` so if you have a view `IronListViewTest` and then override `getTestPath()` for the string then you can have the tests and view there without it being collected for the demo package.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3029)*

**Comment by torok-peter** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/iron/list/IronListViewIT.java, line 45 at r1](https://reviewable.io:443/reviews/vaadin/flow/3029#-KzhEcSQfAs2Nwn7S_H5:-KzhpzGe-BS3BUvIqGE4:b-v0jij6) ([raw file](https://github.com/vaadin/flow/blob/b88c665577b11c6de986469a1bca245037c90fb2/flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/iron/list/IronListViewIT.java#L45)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Three tests use the same structure, so I preferred to create a single method for them all, just changing the id of the tested elements. Aside from adding comments to it, do you suggest any other refactoring?
</blockquote></details>

Eliminating duplication is great, I like that.

To make it more readable, you could extract the 3 stages of the test into methods named e.g. `testRemovingSingleItemFromList`, `testAddingSingleItemToList` and `testRemovingAllItemsFromList`, then call these directly, effectively inlining `testListOrDataProvider`. Granted, 3 lines of code is a bit more verbose than 1, but I think that's a fair price for readable code. Having a single method named like `testRemovingSingleItemThenAddingSingleItemFromListAndFinallyRemovingAllItemsFromList` would be a bit too much for my eyes, and it wouldn't even fit into an 80 character line :-)

---

*[flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/iron/list/IronListViewIT.java, line 73 at r1](https://reviewable.io:443/reviews/vaadin/flow/3029#-KzhFAJ3i1Nk1lmM5b5N:-KzhqCyA4LQLgB4uyI58:b-xbplx3) ([raw file](https://github.com/vaadin/flow/blob/b88c665577b11c6de986469a1bca245037c90fb2/flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/iron/list/IronListViewIT.java#L73)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

`Assert.equals` gives a comprehensive error message already, do you want extra messages for each of the equals?
</blockquote></details>

That's the Flow convention AFAIK. And it does make it easier to identify which assertion failed in a failing test case, which would be handy here as you have several assertions in each test.

---

*[flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/iron/list/IronListViewIT.java, line 159 at r1](https://reviewable.io:443/reviews/vaadin/flow/3029#-KzhEB4x3gegbPkNZXXU:-KzhtrqUTlm74kJ0ij9V:b-ppk7ii) ([raw file](https://github.com/vaadin/flow/blob/b88c665577b11c6de986469a1bca245037c90fb2/flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/iron/list/IronListViewIT.java#L159)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

use more descriptive names
</blockquote></details>

such as `removeAnItemButton` etc.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3029)*

**Comment by gilberto-torrezan** [comment]
Those tests will be ported to the `vaadin-iron-list-flow` repository.

**Pull request closed without merging**
