### PR TITLE
fix: Make webpack work with Node 17

### PR DESCRIPTION
**Pull request by Artur-**

### CODE REVIEW

**Comment by joheriks** [comment]
I get with Node v17.0.1 / npm 8.0.1:
```
/usr/local/bin/node: --openssl-legacy-provider is not allowed in NODE_OPTIONS
```

**Comment by Artur-** [comment]
That's odd because
```
$ node --openssl-legacy-provider 
Welcome to Node.js v17.0.0.

$ NODE_OPTIONS=--openssl-legacy-provider node
Welcome to Node.js v17.0.0.
```

**Comment by joheriks** [comment]
Node 17.0.1 on macOS Catalina:
```
$ node -v
v17.0.1
$ NODE_OPTIONS=--openssl-legacy-provider node
node: --openssl-legacy-provider is not allowed in NODE_OPTIONS
```

**Comment by Artur-** [comment]
Does 17.1.0 work? I still see this on Big Sur
```
$ nvm use 16
Now using node v16.13.0 (npm v8.1.0)
$ NODE_OPTIONS=--openssl-legacy-provider node
node: --openssl-legacy-provider is not allowed in NODE_OPTIONS
$ nvm use 17.0.0
Now using node v17.0.0 (npm v8.1.0)
$ NODE_OPTIONS=--openssl-legacy-provider node
Welcome to Node.js v17.0.0.
Type ".help" for more information.
> 
$ nvm use 17.0.1
Now using node v17.0.1 (npm v8.1.3)
$ NODE_OPTIONS=--openssl-legacy-provider node
Welcome to Node.js v17.0.1.
Type ".help" for more information.
> 
```

**Comment by joheriks** [comment]
17.1.0 works.
```
$ node -v
v17.1.0
$ NODE_OPTIONS=--openssl-legacy-provider node
Welcome to Node.js v17.1.0.
Type ".help" for more information.
>
```

**Comment by Artur-** [comment]
Should we check for 17.1.0 or newer then and just print an unsupported error for 17.0.x?

**Comment by joheriks** [comment]
Sounds like a reasonable solution. We should verify that 17.1 works on other platforms as well (only tested Mac so far)

**Comment by pleku** [comment]
Tested with node 17.1.0 on Windows 10 and works.

**Comment by Artur-** [comment]
Now throws an exception for Node 17.0.x

**Review by pleku — APPROVED** [review]

**Comment by pleku** [comment]
Pick to 2.7 will need to be done manually.

**Comment by joheriks** [comment]
Tested with node 17.1.0 & 17.0.1 on Linux, both work.

**Pull request merged**
