### PR TITLE
Rename packages in "data" module

### PR DESCRIPTION
**Pull request by denis-anisimov**
Part of the package rename #3032

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3162)

### CODE REVIEW

**Comment by caalador** [comment]
Reviewed 242 of 242 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3162#-L0NsA1N4b07M8eg8IpG:-L0NsA1N4b07M8eg8IpH:b-gh4pq) (no related file):*
Lots of `flow-documentation` sources using wrong imports.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3162)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3162#-L0NsA1N4b07M8eg8IpG:-L0NuKdMPXgTxkUxWpXF:b-tz8pj3) (no related file):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Lots of `flow-documentation` sources using wrong imports.
</blockquote></details>

They use correct import from the point of view of the PR.
And yes, from the point of view of the components modules which are external those imports are wrong.
This is terrible circular dependency issue which I don't even know how to solve.......

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3162)*

**Comment by caalador** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3162#-L0NsA1N4b07M8eg8IpG:-L0NvQzSr2DuopFFElLG:b65q73x) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

They use correct import from the point of view of the PR.
And yes, from the point of view of the components modules which are external those imports are wrong.
This is terrible circular dependency issue which I don't even know how to solve.......
</blockquote></details>

Right. I see. The exception is a bit hard to understand...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3162)*

**Comment by caalador** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3162)*

**Comment by caalador** [comment]
Requires merging from master and fixing dependecies for tests in `flow-tests/test-components`

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3162#-:-L0O6kknwvybfpC7X-2h:b-2r4je)*

**Comment by caalador** [comment]
Reviewed 1 of 242 files at r1, 8 of 8 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3162)*

**Comment by caalador** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3162)*

**Comment by caalador** [comment]
Reviewed 1 of 242 files at r1, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3162)*

**Comment by caalador** [comment]
Reviewed 1 of 242 files at r1, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3162)*

**Pull request merged**
