### PR TITLE
Show available routes on the error view when in development mode

### PR DESCRIPTION
**Pull request by Artur-**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3578)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 10 of 11 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/router/RouteNotFoundError.java, line 68 at r2](https://reviewable.io:443/reviews/vaadin/flow/3578#-L6Fg56eJlA0Thk5VEzR:-L6Fg56eJlA0Thk5VEzS:bg19h1i) ([raw file](https://github.com/vaadin/flow/blob/69f8c9325b36364077dd55f26b8289f89bf3118b/flow-server/src/main/java/com/vaadin/flow/router/RouteNotFoundError.java#L68)):*
> getTemplate

`Template` has another main meaning in Flow so I would suggest to give more descriptive name.
May be `ErrorPageTemplate`? Ot whatever.

---

*[flow-server/src/main/java/com/vaadin/flow/router/RouteNotFoundError.java, line 71 at r2](https://reviewable.io:443/reviews/vaadin/flow/3578#-L6Fgi2P48Etc2vbZRuc:-L6Fgi2P48Etc2vbZRud:b-77irce) ([raw file](https://github.com/vaadin/flow/blob/69f8c9325b36364077dd55f26b8289f89bf3118b/flow-server/src/main/java/com/vaadin/flow/router/RouteNotFoundError.java#L71)):*
> prodModeTemplate = readTemplate("RouteNotFoundError_prod.html");

Similar mistake that I made in  the `TemplateInitializer`.
This code technically is not thread safe.
Though here it may be even kept as is.

But several things to understand:
- `readTemplate`  may be run several times (from different threads). But it's not a problem here.
- the return value of the method is String which is immutable so it's OK from this point of view as well
- `prodModeTemplate` can be cached by threads (inside them) and doesn't have to be shared.

All those issues are not problems and it will work even if all of them happens.
But they make the code a little bit fragile (and I would recommend to put the comments why it works).

In reality I would recommend to use `AtomicReference<String>`  for `prodModeTemplate` and make all operations atomic.

---

*[flow-server/src/main/java/com/vaadin/flow/router/RouteNotFoundError.java, line 86 at r2](https://reviewable.io:443/reviews/vaadin/flow/3578#-L6FiMxhHWKikONFcDyq:-L6FiMxhHWKikONFcDyr:b-xzhgsf) ([raw file](https://github.com/vaadin/flow/blob/69f8c9325b36364077dd55f26b8289f89bf3118b/flow-server/src/main/java/com/vaadin/flow/router/RouteNotFoundError.java#L86)):*
> This should not happen"

I don't think it helps me as a developer anyhow.
Would be better to explain a little bit why it should not happen (what's expected and why it failed).

---

*[flow-server/src/main/java/com/vaadin/flow/router/RouteNotFoundError.java, line 100 at r2](https://reviewable.io:443/reviews/vaadin/flow/3578#-L6Fj6vIue4qRcPDHAI8:-L6Fj6vIue4qRcPDHAI9:b4r6mqf) ([raw file](https://github.com/vaadin/flow/blob/69f8c9325b36364077dd55f26b8289f89bf3118b/flow-server/src/main/java/com/vaadin/flow/router/RouteNotFoundError.java#L100)):*
> text = "<root>";

Is this text auto-escaped in the `Element.setText()` ?

---

*[flow-server/src/main/java/com/vaadin/flow/router/RouteNotFoundError.java, line 104 at r2](https://reviewable.io:443/reviews/vaadin/flow/3578#-L6FiyON2lz9gA6GY7N-:-L6FiyON2lz9gA6GY7N0:befl8s2) ([raw file](https://github.com/vaadin/flow/blob/69f8c9325b36364077dd55f26b8289f89bf3118b/flow-server/src/main/java/com/vaadin/flow/router/RouteNotFoundError.java#L104)):*
> new Element(Tag.A).attr("href", route.getUrl())
>                         .text(text);


`ElementFactory.createAnchor(route.getUrl(), text);`

---

*[flow-server/src/main/java/com/vaadin/flow/router/RouteNotFoundError.java, line 108 at r2](https://reviewable.io:443/reviews/vaadin/flow/3578#-L6FihVsSMjph5NxTLWo:-L6FihVsSMjph5NxTLWp:by8ae) ([raw file](https://github.com/vaadin/flow/blob/69f8c9325b36364077dd55f26b8289f89bf3118b/flow-server/src/main/java/com/vaadin/flow/router/RouteNotFoundError.java#L108)):*
> route -> {
<details><summary><i alt="summary">Quoted 13 lines of code…</i></summary>
>             String text = route.getUrl();
>             if (text == null || text.isEmpty()) {
>                 text = "<root>";
>             }
>             if (route.getParameters().isEmpty()) {
>                 Element link = new Element(Tag.A).attr("href", route.getUrl())
>                         .text(text);
>                 elements.add(new Element(Tag.LI).appendChild(link));
>             } else {
>                 Element link = new Element(Tag.LI)
>                         .text(text + " (requires parameter)");
>                 elements.add(link);
>             }
</details>


Big lambda. Would be better to have it as a separate method.

---

*[flow-server/src/main/resources/com/vaadin/flow/router/RouteNotFoundError_dev.html, line 10 at r2](https://reviewable.io:443/reviews/vaadin/flow/3578#-L6FjJC2afeFP9JzWY80:-L6FjJC2afeFP9JzWY81:b-d0wxhj) ([raw file](https://github.com/vaadin/flow/blob/69f8c9325b36364077dd55f26b8289f89bf3118b/flow-server/src/main/resources/com/vaadin/flow/router/RouteNotFoundError_dev.html#L10)):*
> ```HTML
> 	</ul>
> 	<p>This detailed message is only shown when running in development mode.</p>
> </div>
> ```

new line

---

*[flow-server/src/main/resources/com/vaadin/flow/router/RouteNotFoundError_prod.html, line 4 at r2](https://reviewable.io:443/reviews/vaadin/flow/3578#-L6FjKVpLElNsDeA2_UI:-L6FjKVpLElNsDeA2_UJ:b-d0wxhj) ([raw file](https://github.com/vaadin/flow/blob/69f8c9325b36364077dd55f26b8289f89bf3118b/flow-server/src/main/resources/com/vaadin/flow/router/RouteNotFoundError_prod.html#L4)):*
> ```HTML
> 	Could not navigate to '{{path}}'
> 	<p>{{additionalInfo}}</p>
> </div>
> ```

new line

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3578)*

**Comment by Artur-** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/router/RouteNotFoundError.java, line 68 at r2](https://reviewable.io:443/reviews/vaadin/flow/3578#-L6Fg56eJlA0Thk5VEzR:-L6GlTadFP32tuGXb2VA:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/69f8c9325b36364077dd55f26b8289f89bf3118b/flow-server/src/main/java/com/vaadin/flow/router/RouteNotFoundError.java#L68)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> getTemplate

`Template` has another main meaning in Flow so I would suggest to give more descriptive name.
May be `ErrorPageTemplate`? Ot whatever.
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/flow/router/RouteNotFoundError.java, line 71 at r2](https://reviewable.io:443/reviews/vaadin/flow/3578#-L6Fgi2P48Etc2vbZRuc:-L6Go1Yx1ic_p0bE77XX:b-bttoee) ([raw file](https://github.com/vaadin/flow/blob/69f8c9325b36364077dd55f26b8289f89bf3118b/flow-server/src/main/java/com/vaadin/flow/router/RouteNotFoundError.java#L71)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> prodModeTemplate = readTemplate("RouteNotFoundError_prod.html");

Similar mistake that I made in  the `TemplateInitializer`.
This code technically is not thread safe.
Though here it may be even kept as is.

But several things to understand:
- `readTemplate`  may be run several times (from different threads). But it's not a problem here.
- the return value of the method is String which is immutable so it's OK from this point of view as well
- `prodModeTemplate` can be cached by threads (inside them) and doesn't have to be shared.

All those issues are not problems and it will work even if all of them happens.
But they make the code a little bit fragile (and I would recommend to put the comments why it works).

In reality I would recommend to use `AtomicReference<String>`  for `prodModeTemplate` and make all operations atomic.
</blockquote></details>

Added comment

---

*[flow-server/src/main/java/com/vaadin/flow/router/RouteNotFoundError.java, line 86 at r2](https://reviewable.io:443/reviews/vaadin/flow/3578#-L6FiMxhHWKikONFcDyq:-L6GnK0nWg25YyzXS7sD:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/69f8c9325b36364077dd55f26b8289f89bf3118b/flow-server/src/main/java/com/vaadin/flow/router/RouteNotFoundError.java#L86)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> This should not happen"

I don't think it helps me as a developer anyhow.
Would be better to explain a little bit why it should not happen (what's expected and why it failed).
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/flow/router/RouteNotFoundError.java, line 100 at r2](https://reviewable.io:443/reviews/vaadin/flow/3578#-L6Fj6vIue4qRcPDHAI8:-L6GnmTxNf0cxg0VD5rl:b2nhswy) ([raw file](https://github.com/vaadin/flow/blob/69f8c9325b36364077dd55f26b8289f89bf3118b/flow-server/src/main/java/com/vaadin/flow/router/RouteNotFoundError.java#L100)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> text = "<root>";

Is this text auto-escaped in the `Element.setText()` ?
</blockquote></details>

Yes

---

*[flow-server/src/main/java/com/vaadin/flow/router/RouteNotFoundError.java, line 104 at r2](https://reviewable.io:443/reviews/vaadin/flow/3578#-L6FiyON2lz9gA6GY7N-:-L6GnhWIR5gkITDF1Dwr:b-444hrf) ([raw file](https://github.com/vaadin/flow/blob/69f8c9325b36364077dd55f26b8289f89bf3118b/flow-server/src/main/java/com/vaadin/flow/router/RouteNotFoundError.java#L104)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> new Element(Tag.A).attr("href", route.getUrl())
>                         .text(text);


`ElementFactory.createAnchor(route.getUrl(), text);`
</blockquote></details>

That creates a Flow DOM `Element`, not a JSoup `Element`

---

*[flow-server/src/main/java/com/vaadin/flow/router/RouteNotFoundError.java, line 108 at r2](https://reviewable.io:443/reviews/vaadin/flow/3578#-L6FihVsSMjph5NxTLWo:-L6GpRy2Be3VBe9Lprgq:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/69f8c9325b36364077dd55f26b8289f89bf3118b/flow-server/src/main/java/com/vaadin/flow/router/RouteNotFoundError.java#L108)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> route -> {
>             String text = route.getUrl();
>             if (text == null || text.isEmpty()) {
>                 text = "<root>";
>             }
>             if (route.getParameters().isEmpty()) {
>                 Element link = new Element(Tag.A).attr("href", route.getUrl())
>                         .text(text);
>                 elements.add(new Element(Tag.LI).appendChild(link));
>             } else {
>                 Element link = new Element(Tag.LI)
>                         .text(text + " (requires parameter)");
>                 elements.add(link);
>             }


Big lambda. Would be better to have it as a separate method.
</blockquote></details>

Done.

---

*[flow-server/src/main/resources/com/vaadin/flow/router/RouteNotFoundError_dev.html, line 10 at r2](https://reviewable.io:443/reviews/vaadin/flow/3578#-L6FjJC2afeFP9JzWY80:-L6GnxOx8Vf9nPKShP2a:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/69f8c9325b36364077dd55f26b8289f89bf3118b/flow-server/src/main/resources/com/vaadin/flow/router/RouteNotFoundError_dev.html#L10)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

new line
</blockquote></details>

Done.

---

*[flow-server/src/main/resources/com/vaadin/flow/router/RouteNotFoundError_prod.html, line 4 at r2](https://reviewable.io:443/reviews/vaadin/flow/3578#-L6FjKVpLElNsDeA2_UI:-L6GnxkK7esZCp2N4N7c:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/69f8c9325b36364077dd55f26b8289f89bf3118b/flow-server/src/main/resources/com/vaadin/flow/router/RouteNotFoundError_prod.html#L4)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

new line
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3578)*

**Comment by denis-anisimov** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3578)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3578)*

**Pull request merged**
