### PR TITLE
Cherry picking two changes to 2.7

### PR DESCRIPTION
**Pull request by pleku**
DO NOT SQUASH

### CODE REVIEW

**Comment by pleku** [comment]
The behavior change in `Location` is so minor that I would consider it safe to include as long as it is highlighted in the release notes (like it will)

>A minor API behavior change: `Location:getQueryParameters` is unified with how `HttpServletRequest` works:
For a query string `?foo&bar` a list containing `""`  is returned for both `foo` and `bar` whereas the existing implementation returned empty lists.

**Comment by caalador** [comment]
LocationTest tests fail due to exception message changing.

**Comment by pleku** [comment]
It seems there is a behavior change with the pick for URLs like `/view/%3ffaulty` as shown in the other failed IT.

To me this is something that should have been reported as 400 instead of 404. And 404 should be resulting e.g. when `/view/missing-but-valid-path` is used instead.

The second failure instead is related to fragment going missing on router link navigation, and that is a regression, that is probably happening on `master` too (even earlier on) as the test has been ignored due to some other Fusion related change earlier on #7575 ... 
But I will need to take a further look into that before this can be merged.

**Comment by pleku** [comment]
Ok so based on the change from @Artur- that actually "fixes" `QueryParameters` behavior (#10521), the fragment part is dropped off from `Location`/`QueryParameters`, as it used to work with fragment _by chance_. So starting from Vaadin 19, the `History.pushState` has been broken in Flow for any user code using that containing a fragment in the URL, as it is now dropped off.

This would have been caught by tests `RouterLinkIT`, but as the test was already ignored by fusion-team (#7575), the regression has slipped through (I do admit a unit test should have been there too but it has not been). So now it probably needs to be fixed for both `master` and `2.7` too, but I will not include this change yet to 2.7 beta1.

**Comment by pleku** [comment]
The latest build had timeout - there is a lot of waiting after starting jetty in the tests, e.g.
```
[10:12:48] :	 [Step 7/11] [INFO] Started Jetty Server
[10:12:48] :	 [Step 7/11] [INFO] 
[10:12:48] :	 [Step 7/11] [INFO] --- maven-failsafe-plugin:2.22.2:integration-test (default) @ test-embedding-reusable-theme ---
[10:12:48] :	 [Step 7/11] [INFO] Failsafe report directory: /opt/agent/work/a69251da2b2bb9e9/flow-tests/test-embedding/test-embedding-reusable-theme/target/failsafe-reports
[10:12:48] :	 [Step 7/11] [INFO] parallel='all', perCoreThreadCount=true, threadCount=2, useUnlimitedThreads=false, threadCountSuites=0, threadCountClasses=0, threadCountMethods=0, parallelOptimized=true
[10:12:48] :	 [Step 7/11] [INFO] 
[10:12:48] :	 [Step 7/11] [INFO] -------------------------------------------------------
[10:12:48] :	 [Step 7/11] [INFO]  T E S T S
[10:12:48] :	 [Step 7/11] [INFO] -------------------------------------------------------
[10:29:28]W:		 [com.vaadin:test-embedding-reusable-theme] [qtp513009073-4576] WARN com.vaadin.flow.server.DefaultDeploymentConfiguration - Following issues were discovered with deployment configuration:
[10:29:28]W:		 [com.vaadin:test-embedding-reusable-theme] 
[10:29:28]W:		 [com.vaadin:test-embedding-reusable-theme] WARNING: Vaadin is running in DEBUG MODE with debug features enabled, but with a prebuild frontend bundle (production ready).
[10:29:28]W:		 [com.vaadin:test-embedding-reusable-theme] When deploying application for production, disable debug features by enabling production mode!
[10:29:28]W:		 [com.vaadin:test-embedding-reusable-theme] See more from https://vaadin.com/docs/v14/flow/production/tutorial-production-mode-basic.html
[10:29:30]W:		 [com.vaadin:test-embedding-reusable-theme] [qtp513009073-4597] INFO com.vaadin.flow.router.RouteNotFoundError - Couldn't find route for 'path/VAADIN/static/@fortawesome/fontawesome-free/webfonts/fa-solid-900.woff2'
[10:29:30]W:		 [com.vaadin:test-embedding-reusable-theme] com.vaadin.flow.router.NotFoundException: Couldn't find route for 'path/VAADIN/static/@fortawesome/fontawesome-free/webfonts/fa-solid-900.woff2'
```

```
[10:29:42] :	 [Step 7/11] [INFO] -------------------------------------------------------
[10:29:42] :	 [Step 7/11] [INFO]  T E S T S
[10:29:42] :	 [Step 7/11] [INFO] -------------------------------------------------------
[10:36:32]W:		 [com.vaadin:flow-misc-test] [qtp1605622488-4679] INFO com.vaadin.flow.server.DefaultDeploymentConfiguration - Vaadin is running in production mode.
[10:36:32]W:		 [com.vaadin:flow-misc-test] [qtp1605622488-4679] ERROR com.vaadin.flow.server.PwaRegistry - Image is not found or can't be loaded: file:/opt/agent/work/a69251da2b2bb9e9/flow-tests/test-misc/src/main/webapp/icons/icon.png
[10:36:33] :	 [Step 7/11] [INFO] Running com.vaadin.flow.misc.ui.MiscelaneousIT
```
Or during a test
```
[10:46:11]i:	 [Step 7/11] com.vaadin.flow.uitest.ui.LogoutWithNotificationIT
[10:46:11]i:		 [com.vaadin.flow.uitest.ui.LogoutWithNotificationIT] setLocationWithNotificationEnabled_noErrorMessages[ANY_Chrome_]
[10:46:15]W:		 [com.vaadin:flow-test-root-context] Aug 30, 2021 7:45:47 AM org.openqa.selenium.remote.ProtocolHandshake createSession
[10:46:15]W:		 [com.vaadin:flow-test-root-context] INFO: Detected dialect: W3C
[10:46:15] :	 [Step 7/11] [INFO] Running com.vaadin.flow.uitest.ui.CompositeNestedIT
[10:46:15] :	 [Step 7/11] [INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 8.145 s - in com.vaadin.flow.uitest.ui.CompositeNestedIT
[10:46:15]i:	 [Step 7/11] com.vaadin.flow.uitest.ui.CompositeNestedIT
[10:46:15]i:		 [com.vaadin.flow.uitest.ui.CompositeNestedIT] testBasics[ANY_Chrome_]
[11:00:04] :	 [Step 7/11] [INFO] Running com.vaadin.flow.uitest.ui.scroll.PushStateScrollIT
[11:00:04]W:		 [com.vaadin:flow-test-root-context] Aug 30, 2021 7:46:14 AM org.openqa.selenium.remote.ProtocolHandshake createSession
[11:00:04]W:		 [com.vaadin:flow-test-root-context] INFO: Detected dialect: W3C
[11:00:04]W:		 [com.vaadin:flow-test-root-context] Aug 30, 2021 7:46:14 AM org.openqa.selenium.remote.ProtocolHandshake createSession
[11:00:04]W:		 [com.vaadin:flow-test-root-context] INFO: Detected dialect: W3C
[11:00:04] :	 [Step 7/11] [INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5.88 s - in com.vaadin.flow.uitest.ui.scroll.PushStateScrollIT
```

and last delay during frontend compilation ending on timeout 

```
[11:18:55] :	 [Step 7/11] [INFO]  T E S T S
[11:18:55] :	 [Step 7/11] [INFO] -------------------------------------------------------
[11:18:55] :	 [Step 7/11] 
[11:18:55] :	 [Step 7/11] ------------------ Starting Frontend compilation. ------------------
[11:37:47]E:	 [Step 7/11] The build Flow Public::Flow Pull Requests Run Validation #18662 {buildId=87796} has been running for more than 120 minutes. Terminating...
[11:37:49]E:	 [Step 7/11] Execution timeout
```

**Comment by pleku** [comment]
Retriggered the build but not sure if the changes could have some side effect that causes some request that is not meant for the bootstraphandler to fail more directly instead of serving an UI and then cause issues elsewhere ?

**Comment by pleku** [comment]
OMG the build is 🟢 
(FYI @caalador 😄 )

**Review by caalador — APPROVED** [review]

**Pull request merged**
