### PR TITLE
Use the new router by default

### PR DESCRIPTION
**Pull request by caalador**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/2929)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 65 of 67 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[flow-server/src/test/java/com/vaadin/server/MockVaadinServletService.java, line 53 at r2](https://reviewable.io:443/reviews/vaadin/flow/2929#-Kz2Sf7EsxCFeh2_b6IF:-Kz2Sf7EsxCFeh2_b6IG:b89wuy5) ([raw file](https://github.com/vaadin/flow/blob/1791ebc571e0c449aa8857b0df6bf519fbb98eb3/flow-server/src/test/java/com/vaadin/server/MockVaadinServletService.java#L53)):*
>  e.printStackTrace();

Are you sure that it shouldn't throw a runtime exception ?

---

*[flow-test-util/src/main/java/com/vaadin/flow/testutil/AbstractParallelTestBenchTest.java, line 70 at r2](https://reviewable.io:443/reviews/vaadin/flow/2929#-Kz2T72bxKK9GEqi9Ay-:-Kz2T72bxKK9GEqi9Ay0:b-mzx94t) ([raw file](https://github.com/vaadin/flow/blob/1791ebc571e0c449aa8857b0df6bf519fbb98eb3/flow-test-util/src/main/java/com/vaadin/flow/testutil/AbstractParallelTestBenchTest.java#L70)):*
> public void setup() throws Exception {
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>
>         if(USE_HUB) {
>             setDesiredCapabilities(Browser.CHROME.getDesiredCapabilities());
>         }
>         super.setup();
>     }
</details>

What's the need for those changes ?

---

*[flow-test-util/src/main/java/com/vaadin/flow/testutil/AbstractParallelTestBenchTest.java, line 116 at r2](https://reviewable.io:443/reviews/vaadin/flow/2929#-Kz2TCUmI55gld01Si4K:-Kz2TCUmI55gld01Si4L:bqhi5xt) ([raw file](https://github.com/vaadin/flow/blob/1791ebc571e0c449aa8857b0df6bf519fbb98eb3/flow-test-util/src/main/java/com/vaadin/flow/testutil/AbstractParallelTestBenchTest.java#L116)):*
> @Override
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>
>     protected Browser getRunLocallyBrowser() {
>         if (USE_HUB) {
>             return null;
>         }
>         return Browser.CHROME;
</details>

What's the need for those changes ?

---

*[flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/servlet/ApplicationRunnerServlet.java, line 286 at r2](https://reviewable.io:443/reviews/vaadin/flow/2929#-Kz2TaUbWab9v8GutgUE:-Kz2TaUbWab9v8GutgUF:b-6bh3oz) ([raw file](https://github.com/vaadin/flow/blob/1791ebc571e0c449aa8857b0df6bf519fbb98eb3/flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/servlet/ApplicationRunnerServlet.java#L286)):*
> e.printStackTrace();

Throw a runtime exception ?

---

*[flow-tests/test-subcontext/src/main/java/com/vaadin/flow/contexttest/ui/DependencyUI.java, line 59 at r2](https://reviewable.io:443/reviews/vaadin/flow/2929#-Kz2UeRwhac8gKx1iEBF:-Kz2UeRwhac8gKx1iEBG:b-yg8k9l) ([raw file](https://github.com/vaadin/flow/blob/1791ebc571e0c449aa8857b0df6bf519fbb98eb3/flow-tests/test-subcontext/src/main/java/com/vaadin/flow/contexttest/ui/DependencyUI.java#L59)):*
> // Don't try to use router just display the

display what ?

---

*[flow-tests/test-subcontext/src/main/java/com/vaadin/flow/contexttest/ui/DependencyUI.java, line 72 at r2](https://reviewable.io:443/reviews/vaadin/flow/2929#-Kz2UbB9vZqO1TL3yPnt:-Kz2UbB9vZqO1TL3yPnu:b-6bh3oz) ([raw file](https://github.com/vaadin/flow/blob/1791ebc571e0c449aa8857b0df6bf519fbb98eb3/flow-tests/test-subcontext/src/main/java/com/vaadin/flow/contexttest/ui/DependencyUI.java#L72)):*
> e.printStackTrace();

Throw a runtime exception ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2929)*

**Comment by caalador** [comment]
Review status: 43 of 75 files reviewed at latest revision, 6 unresolved discussions.

---

*[flow-test-util/src/main/java/com/vaadin/flow/testutil/AbstractParallelTestBenchTest.java, line 70 at r2](https://reviewable.io:443/reviews/vaadin/flow/2929#-Kz2T72bxKK9GEqi9Ay-:-Kz2W-k6ndPSN-U1MPiE:b-k35pk) ([raw file](https://github.com/vaadin/flow/blob/1791ebc571e0c449aa8857b0df6bf519fbb98eb3/flow-test-util/src/main/java/com/vaadin/flow/testutil/AbstractParallelTestBenchTest.java#L70)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> public void setup() throws Exception {
>         if(USE_HUB) {
>             setDesiredCapabilities(Browser.CHROME.getDesiredCapabilities());
>         }
>         super.setup();
>     }

What's the need for those changes ?
</blockquote></details>

For some reason with merge from master TB started to default to FireFox and not read the BrowserConfiguration.

---

*[flow-test-util/src/main/java/com/vaadin/flow/testutil/AbstractParallelTestBenchTest.java, line 116 at r2](https://reviewable.io:443/reviews/vaadin/flow/2929#-Kz2TCUmI55gld01Si4K:-Kz2W7gxK5-kMaM4-ADI:b-lm3tre) ([raw file](https://github.com/vaadin/flow/blob/1791ebc571e0c449aa8857b0df6bf519fbb98eb3/flow-test-util/src/main/java/com/vaadin/flow/testutil/AbstractParallelTestBenchTest.java#L116)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> @Override
>     protected Browser getRunLocallyBrowser() {
>         if (USE_HUB) {
>             return null;
>         }
>         return Browser.CHROME;

What's the need for those changes ?
</blockquote></details>

Local browser was not gotten from the same place as before and tests were trying to run only on the test hub target localhost:4444/...

---

*[flow-tests/test-subcontext/src/main/java/com/vaadin/flow/contexttest/ui/DependencyUI.java, line 59 at r2](https://reviewable.io:443/reviews/vaadin/flow/2929#-Kz2UeRwhac8gKx1iEBF:-Kz2WWDFNQf5Zv_kFPzQ:b2j1fwg) ([raw file](https://github.com/vaadin/flow/blob/1791ebc571e0c449aa8857b0df6bf519fbb98eb3/flow-tests/test-subcontext/src/main/java/com/vaadin/flow/contexttest/ui/DependencyUI.java#L59)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> // Don't try to use router just display the

display what ?
</blockquote></details>

it was supposed to end with `UI`. Removed due to small change to Router.

---

*[flow-tests/test-subcontext/src/main/java/com/vaadin/flow/contexttest/ui/DependencyUI.java, line 72 at r2](https://reviewable.io:443/reviews/vaadin/flow/2929#-Kz2UbB9vZqO1TL3yPnt:-Kz2WTHGXDiME5bwVIPR:bp98gyr) ([raw file](https://github.com/vaadin/flow/blob/1791ebc571e0c449aa8857b0df6bf519fbb98eb3/flow-tests/test-subcontext/src/main/java/com/vaadin/flow/contexttest/ui/DependencyUI.java#L72)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> e.printStackTrace();

Throw a runtime exception ?
</blockquote></details>

This is removed. Updated router.

---

*[flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/servlet/ApplicationRunnerServlet.java, line 286 at r2](https://reviewable.io:443/reviews/vaadin/flow/2929#-Kz2TaUbWab9v8GutgUE:-Kz2WNi1KPVq6WP3nFpE:bo90m9h) ([raw file](https://github.com/vaadin/flow/blob/1791ebc571e0c449aa8857b0df6bf519fbb98eb3/flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/servlet/ApplicationRunnerServlet.java#L286)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> e.printStackTrace();

Throw a runtime exception ?
</blockquote></details>

This is removed. Updated router and moved pure UI tests to own module.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2929)*

**Comment by denis-anisimov** [comment]
Reviewed 56 of 56 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2929)*

**Comment by caalador** [comment]
Review status: 73 of 76 files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-server/src/test/java/com/vaadin/server/MockVaadinServletService.java, line 53 at r2](https://reviewable.io:443/reviews/vaadin/flow/2929#-Kz2Sf7EsxCFeh2_b6IF:-Kz3WmVz1lWMKicEtLEO:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/1791ebc571e0c449aa8857b0df6bf519fbb98eb3/flow-server/src/test/java/com/vaadin/server/MockVaadinServletService.java#L53)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

>  e.printStackTrace();

Are you sure that it shouldn't throw a runtime exception ?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2929)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2929)*

**Pull request merged**
