### PR TITLE
refactor: Rename webpack server to webpack4 so we can add 5 in parallel

### PR DESCRIPTION
**Pull request by Artur-**

### CODE REVIEW

**Comment by caalador** [comment]
```
17:16:09   [ERROR] COMPILATION ERROR :
17:16:09   [INFO] -------------------------------------------------------------
17:16:09   [ERROR] /opt/agent/work/a69251da2b2bb9e9/flow-tests/test-jetty-reload/src/main/java/com/vaadin/flow/uitest/ui/WebpackDevServerPortView.java:[23,33] cannot find symbol
17:16:09     symbol:   class WebpackHandler
17:16:09     location: package com.vaadin.base.devserver
17:16:09   [ERROR] /opt/agent/work/a69251da2b2bb9e9/flow-tests/test-jetty-reload/src/main/java/com/vaadin/flow/uitest/ui/WebpackDevServerPortView.java:[47,9] cannot find symbol
17:16:09     symbol:   class WebpackHandler
17:16:09     location: class com.vaadin.flow.uitest.ui.WebpackDevServerPortView
17:16:09   [ERROR] /opt/agent/work/a69251da2b2bb9e9/flow-tests/test-jetty-reload/src/main/java/com/vaadin/flow/uitest/ui/WebpackDevServerPortView.java:[47,35] cannot find symbol
17:16:09     symbol:   class WebpackHandler
17:16:09     location: class com.vaadin.flow.uitest.ui.WebpackDevServerPortView
17:16:09   [INFO] 3 errors
```

**Comment by Artur-** [comment]
Fixed test

**Comment by Artur-** [comment]
Should we merge or abandon this?

**Comment by caalador** [comment]
I guess it depends on what the future plans are. If we are planning to go webpack5 with webpack4  support or only webpack5 or drop webpack fully... @joheriks

**Comment by Artur-** [comment]
I created the webpack 5 PR when it was uncertain whether Node 17 + webpack 4 would ever work properly. Now it seems the combination is working

**Comment by joheriks** [comment]
So perhaps we could close and reopen/continue if we make a decision to add Webpack 5 feature flag ?

**Pull request closed without merging**
