### PR TITLE
Add ErrorLevel to Validators and results

### PR DESCRIPTION
**Pull request by ZheSun88**
Port Change from FW 8.2.0.alpha3 to Flow

Original PR is vaadin/framework#10099

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3154)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 6 of 7 files at r1, 1 of 2 files at r3.
Review status: 6 of 7 files reviewed at latest revision, 4 unresolved discussions.

---

*[flow-data/src/main/java/com/vaadin/data/Binder.java, line 2095 at r1](https://reviewable.io:443/reviews/vaadin/flow/3154#-L0Esfj8f2k7QmGp7hqE:-L0Esfj91oRtQzlZiOJm:bxf6bny) ([raw file](https://github.com/vaadin/flow/blob/3c81d20e0495e4ba6cd5d7a430ee984431b6a929/flow-data/src/main/java/com/vaadin/data/Binder.java#L2095)):*
> Optional<ValidationResult> firstError = status
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>
>                     .getValidationResults().stream()
>                     .filter(ValidationResult::isError).findFirst();
>             if (firstError.isPresent()) {
>                 // Failed with a Validation error
>                 handleError(source, firstError.get());
>             } else {
</details>

This change is not in the original PR.
What's the reason?

---

*[flow-data/src/main/java/com/vaadin/data/ErrorLevel.java, line 58 at r1](https://reviewable.io:443/reviews/vaadin/flow/3154#-L0Esz_LEdd-pLs4fvVg:-L0Esz_LEdd-pLs4fvVh:b-d0wxhj) ([raw file](https://github.com/vaadin/flow/blob/3c81d20e0495e4ba6cd5d7a430ee984431b6a929/flow-data/src/main/java/com/vaadin/data/ErrorLevel.java#L58)):*
> ```Java
>         return ordinal();
>     }
> }
> ```

new line

---

*[flow-data/src/main/java/com/vaadin/data/ValidationResultWrap.java, line 35 at r1](https://reviewable.io:443/reviews/vaadin/flow/3154#-L0EtA-d2diL7iJfy_HD:-L0EtA-d2diL7iJfy_HE:bxijlf) ([raw file](https://github.com/vaadin/flow/blob/3c81d20e0495e4ba6cd5d7a430ee984431b6a929/flow-data/src/main/java/com/vaadin/data/ValidationResultWrap.java#L35)):*
> class

original class is public.
Why this one is not?

---

*[flow-data/src/main/java/com/vaadin/data/ValidationResultWrap.java, line 101 at r1](https://reviewable.io:443/reviews/vaadin/flow/3154#-L0EtFx08Xe_JLA0G2cj:-L0EtFx12arllCHC_F4r:b-d0wxhj) ([raw file](https://github.com/vaadin/flow/blob/3c81d20e0495e4ba6cd5d7a430ee984431b6a929/flow-data/src/main/java/com/vaadin/data/ValidationResultWrap.java#L101)):*
> ```Java
>     }
> 
> }
> ```

new line

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3154)*

**Comment by ZheSun88** [comment]
Review status: 6 of 7 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[flow-data/src/main/java/com/vaadin/data/Binder.java, line 2095 at r1](https://reviewable.io:443/reviews/vaadin/flow/3154#-L0Esfj8f2k7QmGp7hqE:-L0EuwDWeX-hcaBAoCfz:bednno6) ([raw file](https://github.com/vaadin/flow/blob/3c81d20e0495e4ba6cd5d7a430ee984431b6a929/flow-data/src/main/java/com/vaadin/data/Binder.java#L2095)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> Optional<ValidationResult> firstError = status
>                     .getValidationResults().stream()
>                     .filter(ValidationResult::isError).findFirst();
>             if (firstError.isPresent()) {
>                 // Failed with a Validation error
>                 handleError(source, firstError.get());
>             } else {

This change is not in the original PR.
What's the reason?
</blockquote></details>

sorry, did i miss something.. 
check https://github.com/vaadin/framework/commit/d0b5741b81d214491c93d4d042c79e10bb4f192e#diff-1dc5f1f8b8e35622e6f3bc3fbd5e56c1R2103

line 2107... 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3154)*

**Comment by ZheSun88** [comment]
Review status: 6 of 7 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[flow-data/src/main/java/com/vaadin/data/ValidationResultWrap.java, line 35 at r1](https://reviewable.io:443/reviews/vaadin/flow/3154#-L0EtA-d2diL7iJfy_HD:-L0Ev_OD0sDZTNMKjCeQ:b4l2ut0) ([raw file](https://github.com/vaadin/flow/blob/3c81d20e0495e4ba6cd5d7a430ee984431b6a929/flow-data/src/main/java/com/vaadin/data/ValidationResultWrap.java#L35)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> class

original class is public.
Why this one is not?
</blockquote></details>

https://github.com/vaadin/framework/blob/d0b5741b81d214491c93d4d042c79e10bb4f192e/server/src/main/java/com/vaadin/data/ValidationResultWrap.java#L36

 are you sure ???? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3154)*

**Comment by ZheSun88** [comment]
Review status: 4 of 7 files reviewed at latest revision, 4 unresolved discussions.

---

*[flow-data/src/main/java/com/vaadin/data/ErrorLevel.java, line 58 at r1](https://reviewable.io:443/reviews/vaadin/flow/3154#-L0Esz_LEdd-pLs4fvVg:-L0EwhMofafZFtj2tip5:bb7f2mf) ([raw file](https://github.com/vaadin/flow/blob/3c81d20e0495e4ba6cd5d7a430ee984431b6a929/flow-data/src/main/java/com/vaadin/data/ErrorLevel.java#L58)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

new line
</blockquote></details>

done

---

*[flow-data/src/main/java/com/vaadin/data/ValidationResultWrap.java, line 101 at r1](https://reviewable.io:443/reviews/vaadin/flow/3154#-L0EtFx08Xe_JLA0G2cj:-L0EwjvWTBU3Cbkmp2SD:bb7f2mf) ([raw file](https://github.com/vaadin/flow/blob/3c81d20e0495e4ba6cd5d7a430ee984431b6a929/flow-data/src/main/java/com/vaadin/data/ValidationResultWrap.java#L101)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

new line
</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3154)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 2 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-data/src/main/java/com/vaadin/data/Binder.java, line 2095 at r1](https://reviewable.io:443/reviews/vaadin/flow/3154#-L0Esfj8f2k7QmGp7hqE:-L0Ex13XwL2F4eECojt8:bvu9dk5) ([raw file](https://github.com/vaadin/flow/blob/3c81d20e0495e4ba6cd5d7a430ee984431b6a929/flow-data/src/main/java/com/vaadin/data/Binder.java#L2095)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

sorry, did i miss something.. 
check https://github.com/vaadin/framework/commit/d0b5741b81d214491c93d4d042c79e10bb4f192e#diff-1dc5f1f8b8e35622e6f3bc3fbd5e56c1R2103

line 2107... 
</blockquote></details>

Alright......
For some reason I've seen the very first commit in the original PR instead of the latest.
Sorry, my bad.

---

*[flow-data/src/main/java/com/vaadin/data/ValidationResultWrap.java, line 35 at r1](https://reviewable.io:443/reviews/vaadin/flow/3154#-L0EtA-d2diL7iJfy_HD:-L0ExDQXI5sTS6jNd7Zs:bl7ct0w) ([raw file](https://github.com/vaadin/flow/blob/3c81d20e0495e4ba6cd5d7a430ee984431b6a929/flow-data/src/main/java/com/vaadin/data/ValidationResultWrap.java#L35)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

https://github.com/vaadin/framework/blob/d0b5741b81d214491c93d4d042c79e10bb4f192e/server/src/main/java/com/vaadin/data/ValidationResultWrap.java#L36

 are you sure ???? 
</blockquote></details>

Same here: the very first commit instead of the latest one.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3154)*

**Comment by denis-anisimov** [comment]
Reviewed 4 of 6 files at r5, 4 of 4 files at r6.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[flow-data/src/main/java/com/vaadin/data/Binder.java, line 2099 at r6](https://reviewable.io:443/reviews/vaadin/flow/3154#-L0IdGYnjvhfKYxbTvlW:-L0IdGYnjvhfKYxbTvlX:b-rgcl9a) ([raw file](https://github.com/vaadin/flow/blob/3f38237befb8e442e4741f6c7236c339cfd6a5cb/flow-data/src/main/java/com/vaadin/data/Binder.java#L2099)):*
> fieldWithValidation.setInvalid(true);

Is this in the initial patch ?

I'm pretty sure it's not a correct place to set invalid status.
This method checks the error level which is bad indicator for the invalid state.
This should have been happened somewhere early.

---

*[flow-data/src/main/java/com/vaadin/data/BindingValidationStatus.java, line 90 at r1](https://reviewable.io:443/reviews/vaadin/flow/3154#-L0If-sNedoVYfzZG947:-L0If-sNedoVYfzZG948:b-bngnhm) ([raw file](https://github.com/vaadin/flow/blob/3c81d20e0495e4ba6cd5d7a430ee984431b6a929/flow-data/src/main/java/com/vaadin/data/BindingValidationStatus.java#L90)):*
> public BindingValidationStatus(Binding<?, TARGET> source,
>             ValidationResult result) {

Is it removed because it's deprecatated ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3154)*

**Comment by ZheSun88** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[flow-data/src/main/java/com/vaadin/data/Binder.java, line 2099 at r6](https://reviewable.io:443/reviews/vaadin/flow/3154#-L0IdGYnjvhfKYxbTvlW:-L0IgQ4b5n03xHIB2pFr:b-z8zk5z) ([raw file](https://github.com/vaadin/flow/blob/3f38237befb8e442e4741f6c7236c339cfd6a5cb/flow-data/src/main/java/com/vaadin/data/Binder.java#L2099)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> fieldWithValidation.setInvalid(true);

Is this in the initial patch ?

I'm pretty sure it's not a correct place to set invalid status.
This method checks the error level which is bad indicator for the invalid state.
This should have been happened somewhere early.
</blockquote></details>

yes, this is in the initial patch, I mean in flow but not framework. 

---

*[flow-data/src/main/java/com/vaadin/data/BindingValidationStatus.java, line 90 at r1](https://reviewable.io:443/reviews/vaadin/flow/3154#-L0If-sNedoVYfzZG947:-L0IgBIpLClUfCImUpzA:b-ioakrr) ([raw file](https://github.com/vaadin/flow/blob/3c81d20e0495e4ba6cd5d7a430ee984431b6a929/flow-data/src/main/java/com/vaadin/data/BindingValidationStatus.java#L90)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> public BindingValidationStatus(Binding<?, TARGET> source,
>             ValidationResult result) {

Is it removed because it's deprecatated ?
</blockquote></details>

yes. i didn;t find any place to use it.. and it also marked deprecated... so i just removed..

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3154)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[flow-data/src/main/java/com/vaadin/data/Binder.java, line 2099 at r6](https://reviewable.io:443/reviews/vaadin/flow/3154#-L0IdGYnjvhfKYxbTvlW:-L0IhYWfUC32luxEaoVb:b-dhss5m) ([raw file](https://github.com/vaadin/flow/blob/3f38237befb8e442e4741f6c7236c339cfd6a5cb/flow-data/src/main/java/com/vaadin/data/Binder.java#L2099)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

yes, this is in the initial patch, I mean in flow but not framework. 
</blockquote></details>

Which flow initial patch ?
Didn't get it.
Please provide me a link.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3154)*

**Comment by ZheSun88** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[flow-data/src/main/java/com/vaadin/data/Binder.java, line 2099 at r6](https://reviewable.io:443/reviews/vaadin/flow/3154#-L0IdGYnjvhfKYxbTvlW:-L0Ii3EMCUUQ0aTZarJU:b-p5gplw) ([raw file](https://github.com/vaadin/flow/blob/3f38237befb8e442e4741f6c7236c339cfd6a5cb/flow-data/src/main/java/com/vaadin/data/Binder.java#L2099)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Which flow initial patch ?
Didn't get it.
Please provide me a link.
</blockquote></details>

https://github.com/vaadin/flow/blob/master/flow-data/src/main/java/com/vaadin/data/Binder.java#L2050

here.. which is different with framework...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3154)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[flow-data/src/main/java/com/vaadin/data/Binder.java, line 2099 at r6](https://reviewable.io:443/reviews/vaadin/flow/3154#-L0IdGYnjvhfKYxbTvlW:-L0IjRmaFGDjTmiNJsna:b-2p7wlj) ([raw file](https://github.com/vaadin/flow/blob/3f38237befb8e442e4741f6c7236c339cfd6a5cb/flow-data/src/main/java/com/vaadin/data/Binder.java#L2099)):*
> https://github.com/vaadin/flow/blob/master/flow-data/src/main/java/com/vaadin/data/Binder.java#L2050

Right.....

But now I'm not sure that the code is not really correct.
The previous version has set the invalid status regardless of the error level presence.
Now the status is set only when it's present.

As I understand the error level is used to manage the error message appearance.
But in your code it also influence on field validness. 
It might be that the field should be set invalid regardless of the error level ( and regardless of the error message).
But might be I'm wrong. Could you please elaborate ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3154)*

**Comment by ZheSun88** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[flow-data/src/main/java/com/vaadin/data/Binder.java, line 2099 at r6](https://reviewable.io:443/reviews/vaadin/flow/3154#-L0IdGYnjvhfKYxbTvlW:-L0Im6CDzKLZp6wbQzxw:blmepdl) ([raw file](https://github.com/vaadin/flow/blob/3f38237befb8e442e4741f6c7236c339cfd6a5cb/flow-data/src/main/java/com/vaadin/data/Binder.java#L2099)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> https://github.com/vaadin/flow/blob/master/flow-data/src/main/java/com/vaadin/data/Binder.java#L2050

Right.....

But now I'm not sure that the code is not really correct.
The previous version has set the invalid status regardless of the error level presence.
Now the status is set only when it's present.

As I understand the error level is used to manage the error message appearance.
But in your code it also influence on field validness. 
It might be that the field should be set invalid regardless of the error level ( and regardless of the error message).
But might be I'm wrong. Could you please elaborate ?
</blockquote></details>

I am also a little bit confused here. I  removed the setInvalid() before but it caused some unit tests fail. Without this setInvaild() basically the getErrorMessage()  cannot return anything. My understand on binder is not that deep so I just tried to fix the error and bring that back. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3154)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[flow-data/src/main/java/com/vaadin/data/Binder.java, line 2099 at r6](https://reviewable.io:443/reviews/vaadin/flow/3154#-L0IdGYnjvhfKYxbTvlW:-L0Ip42zla_X7nexh7K9:b5zqrdn) ([raw file](https://github.com/vaadin/flow/blob/3f38237befb8e442e4741f6c7236c339cfd6a5cb/flow-data/src/main/java/com/vaadin/data/Binder.java#L2099)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

I am also a little bit confused here. I  removed the setInvalid() before but it caused some unit tests fail. Without this setInvaild() basically the getErrorMessage()  cannot return anything. My understand on binder is not that deep so I just tried to fix the error and bring that back. 
</blockquote></details>

It's not about `Binder`.
It's about newly introduced `ErrorLevel` enumeration, validation result ( which returns the error level) and `HasValidation`.

OK, I've checked the code and it the result it's correct.
But I suggest to change it.
`handleError` method is called _ONLY_ for an error `ValidationResult`.
It means that for such result there should be an error level available.
Since I don't see any usage of the level itself in the code I'm pretty sure that ` result.getErrorLevel().ifPresent` should be just completely removed here.
So the code here should be the same as before this PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3154)*

**Comment by ZheSun88** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[flow-data/src/main/java/com/vaadin/data/Binder.java, line 2099 at r6](https://reviewable.io:443/reviews/vaadin/flow/3154#-L0IdGYnjvhfKYxbTvlW:-L0IrWwLd3_VoKFQaUd5:bwkarrh) ([raw file](https://github.com/vaadin/flow/blob/3f38237befb8e442e4741f6c7236c339cfd6a5cb/flow-data/src/main/java/com/vaadin/data/Binder.java#L2099)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

It's not about `Binder`.
It's about newly introduced `ErrorLevel` enumeration, validation result ( which returns the error level) and `HasValidation`.

OK, I've checked the code and it the result it's correct.
But I suggest to change it.
`handleError` method is called _ONLY_ for an error `ValidationResult`.
It means that for such result there should be an error level available.
Since I don't see any usage of the level itself in the code I'm pretty sure that ` result.getErrorLevel().ifPresent` should be just completely removed here.
So the code here should be the same as before this PR.
</blockquote></details>

okay I will change this part back to it he original flow one after I get to the cabine. Thanks Denis. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3154)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3154)*

**Pull request merged**
