### PR TITLE
Remove resource scanner which does not work on Undertow

### LINKED ISSUE #3839: Polyfills not found when running with Undertow
Starting `test-spring-boot-undertow` using `spring-boot:run` outputs
```
2018-04-06 10:17:52.982  WARN 73294 --- [  XNIO-2 task-1] c.v.f.s.DefaultDeploymentConfiguration   : Unable to locate polyfill webcomponents-loader.js, proceeding without it
```

The underlying reason is that `VaadinServlet.scanForResources` is called with path `/`, which should scan through all webjars but scans through nothing because `ServletContext.getResourcePaths("/")` returns an empty set on Undertow.

I think that the whole `scanForResources` is just legacy and should be removed. Instead the polyfill should be found directly using the known path where it should be.

### PR DESCRIPTION
**Pull request by Artur-**
Fixes #3839

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3841)

### CODE REVIEW

**Comment by Artur-** [comment]
Depends on #3872

**Comment by SomeoneToIgnore** [comment]
Reviewed 21 of 28 files at r1, 6 of 7 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java, line 669 at r3](https://beta.reviewable.io/reviews/vaadin/flow/3841#-LAD5zGh355EMTKgWxtS:-LAD5zGh355EMTKgWxtT:btge37g) ([raw file](https://github.com/vaadin/flow/blob/3ad58983b263bb01e11ac1056fd447d833ba2aa0/flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java#L669)):*
> ```Java
>                 .getConfiguration();
> 
>         boolean loadEs5Adapter = config
> ```

We did not load es5 adapter if there were no webcomponentsjs polyfills before, now we do.
Are you sure that this is correct?
To me it looks unnecessary, since if we don't load basic polyfills, babel helpers won't help also.

---

*[flow-server/src/main/java/com/vaadin/flow/server/ServletContextUriResolver.java, line 35 at r3](https://beta.reviewable.io/reviews/vaadin/flow/3841#-LADMlHY8LUsHEP8s1A7:-LADMlHY8LUsHEP8s1A8:b-z538l0) ([raw file](https://github.com/vaadin/flow/blob/3ad58983b263bb01e11ac1056fd447d833ba2aa0/flow-server/src/main/java/com/vaadin/flow/server/ServletContextUriResolver.java#L35)):*
> ```
> "/"
> ```

Is it correct to always use `/` as the context root? What if we have an app deployed to some subroot, like we do on flow.app.fi?

---

*[flow-server/src/test/java/com/vaadin/flow/server/VaadinServletTest.java, line 127 at r3](https://beta.reviewable.io/reviews/vaadin/flow/3841#-LADJ4foE-DTxeGK5CzT:-LADJ4foE-DTxeGK5CzU:bnne6zi) ([raw file](https://github.com/vaadin/flow/blob/3ad58983b263bb01e11ac1056fd447d833ba2aa0/flow-server/src/test/java/com/vaadin/flow/server/VaadinServletTest.java#L127)):*
> ```Java
>         Assert.assertEquals("/other/foo",
>                 servlet.getUrlTranslation(new MyTheme(), "/other/foo"));
> //        Assert.assertEquals("/theme/src/foo",
> ```

Is something missing here?

---

*[flow-server/src/test/java/com/vaadin/flow/server/startup/BundleFilterInitializerTest.java, line 47 at r3](https://beta.reviewable.io/reviews/vaadin/flow/3841#-LADJinq91boGkWXuN89:-LADJinq91boGkWXuN8A:bcr676t) ([raw file](https://github.com/vaadin/flow/blob/3ad58983b263bb01e11ac1056fd447d833ba2aa0/flow-server/src/test/java/com/vaadin/flow/server/startup/BundleFilterInitializerTest.java#L47)):*
> ```Java
> 
>     @FunctionalInterface
>     private interface CheckedFunction<T, R, E extends Exception> {
> ```

Not needed anymore, can you remove it?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3841)*

**Comment by Artur-** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java, line 669 at r3](https://beta.reviewable.io/reviews/vaadin/flow/3841#-LAD5zGh355EMTKgWxtS:-LADUEAO6bKbQ-gN0ZWb:b-f74gwq) ([raw file](https://github.com/vaadin/flow/blob/3ad58983b263bb01e11ac1056fd447d833ba2aa0/flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java#L669)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

We did not load es5 adapter if there were no webcomponentsjs polyfills before, now we do.
Are you sure that this is correct?
To me it looks unnecessary, since if we don't load basic polyfills, babel helpers won't help also.
</blockquote></details>

Do you mean this should be inside the same `webcomponents-loader.js` if below? Would make sense

---

*[flow-server/src/main/java/com/vaadin/flow/server/ServletContextUriResolver.java, line 35 at r3](https://beta.reviewable.io/reviews/vaadin/flow/3841#-LADMlHY8LUsHEP8s1A7:-LADTXl39KYfYjcUDj9A:bwh6fr) ([raw file](https://github.com/vaadin/flow/blob/3ad58983b263bb01e11ac1056fd447d833ba2aa0/flow-server/src/main/java/com/vaadin/flow/server/ServletContextUriResolver.java#L35)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

> ```
> "/"
> ```

Is it correct to always use `/` as the context root? What if we have an app deployed to some subroot, like we do on flow.app.fi?
</blockquote></details>

This is the context root when resolving  on the server, i.e. it assumes that `frontend` is found directly inside the servlet context root

---

*[flow-server/src/test/java/com/vaadin/flow/server/VaadinServletTest.java, line 127 at r3](https://beta.reviewable.io/reviews/vaadin/flow/3841#-LADJ4foE-DTxeGK5CzT:-LADcD8FDzwsnio5nOtd:b-rxkw8j) ([raw file](https://github.com/vaadin/flow/blob/3ad58983b263bb01e11ac1056fd447d833ba2aa0/flow-server/src/test/java/com/vaadin/flow/server/VaadinServletTest.java#L127)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Is something missing here?
</blockquote></details>

Removed in #3872

---

*[flow-server/src/test/java/com/vaadin/flow/server/startup/BundleFilterInitializerTest.java, line 47 at r3](https://beta.reviewable.io/reviews/vaadin/flow/3841#-LADJinq91boGkWXuN89:-LADcFUD1owbE41Etphl:b-rxkw8j) ([raw file](https://github.com/vaadin/flow/blob/3ad58983b263bb01e11ac1056fd447d833ba2aa0/flow-server/src/test/java/com/vaadin/flow/server/startup/BundleFilterInitializerTest.java#L47)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Not needed anymore, can you remove it?
</blockquote></details>

Removed in #3872

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3841)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 3 of 3 files at r4.
Review status: 27 of 28 files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java, line 669 at r3](https://beta.reviewable.io/reviews/vaadin/flow/3841#-LAD5zGh355EMTKgWxtS:-LADfEUQ8JDESYI0Y8Wc:bedyp90) ([raw file](https://github.com/vaadin/flow/blob/3ad58983b263bb01e11ac1056fd447d833ba2aa0/flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java#L669)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Do you mean this should be inside the same `webcomponents-loader.js` if below? Would make sense
</blockquote></details>

Ok, now what's left is to fix the failing test (`webcomponentsPolyfillBasePresent_polyfillsLoaded`) – we don't need the polyfill there for es6 builds.

---

*[flow-server/src/main/java/com/vaadin/flow/server/ServletContextUriResolver.java, line 35 at r3](https://beta.reviewable.io/reviews/vaadin/flow/3841#-LADMlHY8LUsHEP8s1A7:-LADgIusEtmjncmS9EZF:b2nhll9) ([raw file](https://github.com/vaadin/flow/blob/3ad58983b263bb01e11ac1056fd447d833ba2aa0/flow-server/src/main/java/com/vaadin/flow/server/ServletContextUriResolver.java#L35)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

This is the context root when resolving  on the server, i.e. it assumes that `frontend` is found directly inside the servlet context root
</blockquote></details>

Ok.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3841)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3841)*

**Comment by Artur-** [comment]
Done, I hope

---

Review status: 24 of 28 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3841#-:-LAHXokI62qdPAVKmlG6:busre4u)*

**Comment by SomeoneToIgnore** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3841#-:-LAHYaX_5VNmAb6TV-yU:bnfp4nl)*

**Pull request merged**
