### PR TITLE
Restrict how model property updates are sent to the server

### LINKED ISSUE #1331: Only update server-side model values for properties that are used in a two-way binding
For security reasons, there should be an `@AllowClientUpdates` annotation that can be used on model properties with three different `ClientUpdateMode` values:
* `ALWAYS` to always allow updates from the client
* `NEVER` to always reject updates from the client
* `FOR_TWO_WAY_BINDINGS` to allow updates only for properties for which there is a two-way binding in the template. This is the default setting.

Client-side changes to any other properties should log a warning (on the server) but not cause any changes on the server.

Depends on #1271 (and probably also #1328 for parsing templates on the sever).

### PR DESCRIPTION
**Pull request by Legioth**
Fixes #1331

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3449)

### CODE REVIEW

**Comment by gilberto-torrezan** [comment]
Reviewed 6 of 18 files at r1.
Review status: 6 of 18 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/ElementPropertyMap.java, line 86 at r1](https://reviewable.io:443/reviews/vaadin/flow/3449#-L4A7djw1Qc4tRg1zweQ:-L4A7djw1Qc4tRg1zweR:bp7s9y6) ([raw file](https://github.com/vaadin/flow/blob/76db956a48970572e66c4e7c37c2979cf937eeff/flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/ElementPropertyMap.java#L86)):*
> ```Java
>             if (updateFromClientFilter != null
>                     && !updateFromClientFilter.test(key)) {
>                 getLogger().warn("Ignoring model update for {}", key);
> ```

How often those warnings are expected to the printed? How can the end developer prevent them (other than disabling the logging) ?

---

*[flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/NodeMap.java, line 96 at r1](https://reviewable.io:443/reviews/vaadin/flow/3449#-L4A8XNauxOUijnU9Fql:-L4A8XNauxOUijnU9Fqm:blm7rpw) ([raw file](https://github.com/vaadin/flow/blob/76db956a48970572e66c4e7c37c2979cf937eeff/flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/NodeMap.java#L96)):*
> or <code>null</code> if there was no previous value or if the new and the old value are identical

This contradicts the javadoc.

---

*[flow-server/src/main/java/com/vaadin/flow/templatemodel/AllowClientUpdates.java, line 42 at r1](https://reviewable.io:443/reviews/vaadin/flow/3449#-L4A9CNuJXUjlCQwsj82:-L4A9CNuJXUjlCQwsj83:boxw95z) ([raw file](https://github.com/vaadin/flow/blob/76db956a48970572e66c4e7c37c2979cf937eeff/flow-server/src/main/java/com/vaadin/flow/templatemodel/AllowClientUpdates.java#L42)):*
> ```Java
> @Target(ElementType.METHOD)
> @Repeatable(AllowClientUpdates.Container.class)
> public @interface AllowClientUpdates {
> ```

Missing `@Documented`

---

*[flow-server/src/main/java/com/vaadin/flow/templatemodel/AllowClientUpdates.java, line 42 at r1](https://reviewable.io:443/reviews/vaadin/flow/3449#-L4A9O9EDNqu0YS1uIAu:-L4A9O9F3QRoj6Q4elkA:baw1k4m) ([raw file](https://github.com/vaadin/flow/blob/76db956a48970572e66c4e7c37c2979cf937eeff/flow-server/src/main/java/com/vaadin/flow/templatemodel/AllowClientUpdates.java#L42)):*
> ```Java
> @Target(ElementType.METHOD)
> @Repeatable(AllowClientUpdates.Container.class)
> public @interface AllowClientUpdates {
> ```

Does it make sense to make it `@Inherited` as well?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3449)*

**Comment by Legioth** [comment]
Review status: 6 of 17 files reviewed at latest revision, 4 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/ElementPropertyMap.java, line 86 at r1](https://reviewable.io:443/reviews/vaadin/flow/3449#-L4A7djw1Qc4tRg1zweQ:-L4ABphVoy-_54mb5ddE:b-kf4m1l) ([raw file](https://github.com/vaadin/flow/blob/76db956a48970572e66c4e7c37c2979cf937eeff/flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/ElementPropertyMap.java#L86)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

How often those warnings are expected to the printed? How can the end developer prevent them (other than disabling the logging) ?
</blockquote></details>

There might be quite many of these at the moment. The grand plan is to make it so that the client won't send them at all, but that will have to be a separate PR since this one is already way too big.

---

*[flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/NodeMap.java, line 96 at r1](https://reviewable.io:443/reviews/vaadin/flow/3449#-L4A8XNauxOUijnU9Fql:-L4ADHorTLw0frmQ_3Gb:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/76db956a48970572e66c4e7c37c2979cf937eeff/flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/NodeMap.java#L96)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

> or <code>null</code> if there was no previous value or if the new and the old value are identical

This contradicts the javadoc.
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/flow/templatemodel/AllowClientUpdates.java, line 42 at r1](https://reviewable.io:443/reviews/vaadin/flow/3449#-L4A9CNuJXUjlCQwsj82:-L4ADUFprQfofiBj7CB-:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/76db956a48970572e66c4e7c37c2979cf937eeff/flow-server/src/main/java/com/vaadin/flow/templatemodel/AllowClientUpdates.java#L42)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Missing `@Documented`
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/flow/templatemodel/AllowClientUpdates.java, line 42 at r1](https://reviewable.io:443/reviews/vaadin/flow/3449#-L4A9O9EDNqu0YS1uIAu:-L4ADUTl1roJ7UsZdLPk:b-lk8hse) ([raw file](https://github.com/vaadin/flow/blob/76db956a48970572e66c4e7c37c2979cf937eeff/flow-server/src/main/java/com/vaadin/flow/templatemodel/AllowClientUpdates.java#L42)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Does it make sense to make it `@Inherited` as well?
</blockquote></details>

`@Inherited` has no effect for annotations that are targeting methods.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3449)*

**Comment by gilberto-torrezan** [comment]
Reviewed 10 of 18 files at r1, 2 of 2 files at r2, 1 of 1 files at r3.
Review status: 16 of 17 files reviewed at latest revision, 4 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/templatemodel/BeanModelType.java, line 318 at r1](https://reviewable.io:443/reviews/vaadin/flow/3449#-L4AK5bUaAcxzn-Hx_tP:-L4AK5bUaAcxzn-Hx_tQ:b-tgn7sh) ([raw file](https://github.com/vaadin/flow/blob/76db956a48970572e66c4e7c37c2979cf937eeff/flow-server/src/main/java/com/vaadin/flow/templatemodel/BeanModelType.java#L318)):*
> ```Java
>         ClientUpdateMode clientUpdateMode = getExistingProperty(propertyName)
>                 .getClientUpdateMode();
>         return Optional.ofNullable(clientUpdateMode);
> ```

Wouldn't it be better to enforce the default value `IF_TWO_WAY_BINDING` here in case of the missing annotation, instead of using `getClientUpdateMode(name).orElse(ClientUpdateMode.IF_TWO_WAY_BINDING);` everywhere ?

---

*[flow-server/src/main/java/com/vaadin/flow/templatemodel/PropertyMapBuilder.java, line 121 at r3](https://reviewable.io:443/reviews/vaadin/flow/3449#-L4AOu11yjF1wfZU-wz6:-L4AOu11yjF1wfZU-wz7:b-gfgu34) ([raw file](https://github.com/vaadin/flow/blob/30efc3520d2af196bee27587f6ca5d5c2d57dbf2/flow-server/src/main/java/com/vaadin/flow/templatemodel/PropertyMapBuilder.java#L121)):*
> ```Java
>                                                 + conflictMessageToken
>                                                 + " with the same path. Affected methods: "
>                                                 + accessors + ".");
> ```

Here you are printing out all the `accessors`, and not only those which conflicted - this can be confusing if you have lots of `accessors` in your model.

---

*[flow-server/src/test/java/com/vaadin/flow/templatemodel/Bean.java, line 3 at r1](https://reviewable.io:443/reviews/vaadin/flow/3449#-L4AM3-DntFZ94zS9XNg:-L4AM3-DntFZ94zS9XNh:b-pbq4qd) ([raw file](https://github.com/vaadin/flow/blob/76db956a48970572e66c4e7c37c2979cf937eeff/flow-server/src/test/java/com/vaadin/flow/templatemodel/Bean.java#L3)):*
> ```Java
> package com.vaadin.flow.templatemodel;
> 
> public class Bean {
> ```

I suggest adding the `@AllowClientUpdates(ClientUpdateMode.IF_TWO_WAY_BINDING)` to a random property just to validate that it behaves as it should (just like no annotation at all).

---

*[flow-tests/test-root-context/src/main/webapp/frontend/com/vaadin/flow/uitest/ui/template/ClientUpdateMode.html, line 32 at r1](https://reviewable.io:443/reviews/vaadin/flow/3449#-L4ANHhdQl5eaP1Aw2yz:-L4ANHhdQl5eaP1Aw2z-:b-m2hxc4) ([raw file](https://github.com/vaadin/flow/blob/76db956a48970572e66c4e7c37c2979cf937eeff/flow-tests/test-root-context/src/main/webapp/frontend/com/vaadin/flow/uitest/ui/template/ClientUpdateMode.html#L32)):*
> ```HTML
>             
>             updateIndirect() {
>             	this.indirect = this.value;
> ```

The tab side of the force is growing strong. Kill it before it's too late. May the space be with you.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3449)*

**Comment by gilberto-torrezan** [comment]
Reviewed 1 of 18 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3449)*

**Comment by Legioth** [comment]
Review status: 11 of 20 files reviewed at latest revision, 9 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/templatemodel/BeanModelType.java, line 318 at r1](https://reviewable.io:443/reviews/vaadin/flow/3449#-L4AK5bUaAcxzn-Hx_tP:-L4ARNkvUW_hH7v2ag0X:b39mjnl) ([raw file](https://github.com/vaadin/flow/blob/76db956a48970572e66c4e7c37c2979cf937eeff/flow-server/src/main/java/com/vaadin/flow/templatemodel/BeanModelType.java#L318)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Wouldn't it be better to enforce the default value `IF_TWO_WAY_BINDING` here in case of the missing annotation, instead of using `getClientUpdateMode(name).orElse(ClientUpdateMode.IF_TWO_WAY_BINDING);` everywhere ?
</blockquote></details>

I was originally thinking that it would be to discard information (i.e. whether an annotation is present or not), but we can add a separate getter for that if that information turns out to be necessary.

Done.

---

*[flow-server/src/main/java/com/vaadin/flow/templatemodel/PropertyMapBuilder.java, line 121 at r3](https://reviewable.io:443/reviews/vaadin/flow/3449#-L4AOu11yjF1wfZU-wz6:-L4AScvnszMQIsKwUSMc:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/30efc3520d2af196bee27587f6ca5d5c2d57dbf2/flow-server/src/main/java/com/vaadin/flow/templatemodel/PropertyMapBuilder.java#L121)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Here you are printing out all the `accessors`, and not only those which conflicted - this can be confusing if you have lots of `accessors` in your model.
</blockquote></details>

Done.

---

*[flow-server/src/test/java/com/vaadin/flow/templatemodel/Bean.java, line 3 at r1](https://reviewable.io:443/reviews/vaadin/flow/3449#-L4AM3-DntFZ94zS9XNg:-L4ASy8Tm6N2Ui9t1agd:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/76db956a48970572e66c4e7c37c2979cf937eeff/flow-server/src/test/java/com/vaadin/flow/templatemodel/Bean.java#L3)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

I suggest adding the `@AllowClientUpdates(ClientUpdateMode.IF_TWO_WAY_BINDING)` to a random property just to validate that it behaves as it should (just like no annotation at all).
</blockquote></details>

Done.

---

*[flow-tests/test-root-context/src/main/webapp/frontend/com/vaadin/flow/uitest/ui/template/ClientUpdateMode.html, line 32 at r1](https://reviewable.io:443/reviews/vaadin/flow/3449#-L4ANHhdQl5eaP1Aw2yz:-L4ATIewvdJ8Z5sRt98M:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/76db956a48970572e66c4e7c37c2979cf937eeff/flow-tests/test-root-context/src/main/webapp/frontend/com/vaadin/flow/uitest/ui/template/ClientUpdateMode.html#L32)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

The tab side of the force is growing strong. Kill it before it's too late. May the space be with you.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3449)*

**Comment by gilberto-torrezan** [comment]
Reviewed 3 of 5 files at r4, 7 of 7 files at r5.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3449)*

**Comment by gilberto-torrezan** [comment]
Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3449)*

**Pull request merged**
