### PR TITLE
Respect enabled state of the component in rendered components.

### PR DESCRIPTION
**Pull request by denis-anisimov**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3875)

### CODE REVIEW

**Comment by gilberto-torrezan** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/flow/3875#-L9ttarYC2hHYrmiHDse:-L9ttarYC2hHYrmiHDsf:b-oaii6c) (no related file):*
I just tested it with Grid and it is working with the current implementation. Do you have an example where it fails?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3875)*

**Comment by denis-anisimov** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/flow/3875#-L9ttarYC2hHYrmiHDse:-L9xUbQSCmgZnC7Gm4LI:b-n67ky7) (no related file):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

I just tested it with Grid and it is working with the current implementation. Do you have an example where it fails?
</blockquote></details>

Doesn't work for me in the `iron-list`. When it's disabled the components inside it are not disabled.
I don't know the exact details of the component renderer. May be it's not properly used in the `iron-list`, may be I'm testing on the outdated Flow sources. I will check with the most recent ones.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3875)*

**Comment by denis-anisimov** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/flow/3875#-L9ttarYC2hHYrmiHDse:-L9xWu6M5C9j3UQ-MjOy:bkv6kgk) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Doesn't work for me in the `iron-list`. When it's disabled the components inside it are not disabled.
I don't know the exact details of the component renderer. May be it's not properly used in the `iron-list`, may be I'm testing on the outdated Flow sources. I will check with the most recent ones.
</blockquote></details>

Alright, now it works as needed.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3875)*

**Comment by denis-anisimov** [comment]
This PR is not needed anymore.

**Pull request closed without merging**
