### PR TITLE
Check whether client-side update settings allow to have a getter

### PR DESCRIPTION
**Pull request by denis-anisimov**
Preliminary patch for #3425

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3494)

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
Reviewed 9 of 12 files at r1, 8 of 8 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3494#-L4eIFJk49vZoloCG3oT:-L4eIFJk49vZoloCG3oU:botfnfg) (no related file):*
Do I get it right that now, if we want to have any model property updated, we need to put `@AllowClientUpdates` on it explicitly?

I guess we should update our docs then.

---

*[flow-server/src/main/java/com/vaadin/flow/templatemodel/BeanModelType.java, line 578 at r3](https://reviewable.io:443/reviews/vaadin/flow/3494#-L4e9Vurh3wV60wW1Vw2:-L4e9Vus4Ah3GlUEW52-:b-90lwzw) ([raw file](https://github.com/vaadin/flow/blob/efe72d918efab4824cbee77dae5037dac90f5bbd/flow-server/src/main/java/com/vaadin/flow/templatemodel/BeanModelType.java#L578)):*
> are define

Minor typo, I guess you've meant `are defined`.

---

*[flow-server/src/main/java/com/vaadin/flow/templatemodel/BeanModelType.java, line 583 at r3](https://reviewable.io:443/reviews/vaadin/flow/3494#-L4eH2hRrRXakj4jYj2f:-L4eH2hRrRXakj4jYj2g:b-3skfym) ([raw file](https://github.com/vaadin/flow/blob/efe72d918efab4824cbee77dae5037dac90f5bbd/flow-server/src/main/java/com/vaadin/flow/templatemodel/BeanModelType.java#L583)):*
> ```Java
>      *         and indicator of their getters presence
>      */
>     public Map<String, Boolean> getClientUpdateAllowedProperties(
> ```

Just wondering: do you plan to use that `Boolean` values in the map? Because now you don't.

---

*[flow-server/src/main/java/com/vaadin/flow/templatemodel/BeanModelType.java, line 589 at r3](https://reviewable.io:443/reviews/vaadin/flow/3494#-L4eAN8AfbjKlw5Fvx0Z:-L4eAN8AfbjKlw5Fvx0_:b-pdsxln) ([raw file](https://github.com/vaadin/flow/blob/efe72d918efab4824cbee77dae5037dac90f5bbd/flow-server/src/main/java/com/vaadin/flow/templatemodel/BeanModelType.java#L589)):*
Minor and can be ignored.

> Collections.unmodifiableSet

Not sure why it's needed, since you don't change the set inside the `collectAllowedProperties` private method and the new set will change if `twoWayBindingPaths` is changed. 

---

*[flow-server/src/main/java/com/vaadin/flow/templatemodel/BeanModelType.java, line 634 at r3](https://reviewable.io:443/reviews/vaadin/flow/3494#-L4eCh6LMQZHGVIgGrA5:-L4eCh6LMQZHGVIgGrA6:b-18qyb4) ([raw file](https://github.com/vaadin/flow/blob/efe72d918efab4824cbee77dae5037dac90f5bbd/flow-server/src/main/java/com/vaadin/flow/templatemodel/BeanModelType.java#L634)):*
> info

Might be `debug` if we don't want to spam our users with lots of messages every time. 

---

*[flow-server/src/main/java/com/vaadin/flow/templatemodel/BeanModelType.java, line 636 at r3](https://reviewable.io:443/reviews/vaadin/flow/3494#-L4eB2ofL71dlWlS3SNo:-L4eB2ofL71dlWlS3SNp:buld1k0) ([raw file](https://github.com/vaadin/flow/blob/efe72d918efab4824cbee77dae5037dac90f5bbd/flow-server/src/main/java/com/vaadin/flow/templatemodel/BeanModelType.java#L636)):*
> explicitely

Did you mean `explicitly`? Same for two occurrences below, including 
> implicitely

---

*[flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/OneWayPolymerBindingView.java, line 47 at r3](https://reviewable.io:443/reviews/vaadin/flow/3494#-L4eGRT6VNhnVgJMVp4I:-L4eGRT6VNhnVgJMVp4J:b-hrya6w) ([raw file](https://github.com/vaadin/flow/blob/efe72d918efab4824cbee77dae5037dac90f5bbd/flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/OneWayPolymerBindingView.java#L47)):*
> ```Java
>         void setTitle(String title);
> 
>         @AllowClientUpdates(ClientUpdateMode.ALLOW)
> ```

Just FYI: after https://github.com/vaadin/flow/pull/3497 is merged, you can omit this long `(ClientUpdateMode.ALLOW)` things.
Might be handy in the next PRs or so.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3494)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 12 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/templatemodel/BeanModelType.java, line 578 at r3](https://beta.reviewable.io/reviews/vaadin/flow/3494#-L4e9Vurh3wV60wW1Vw2:-L4eJF5S8UqxZoka-hhs:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/efe72d918efab4824cbee77dae5037dac90f5bbd/flow-server/src/main/java/com/vaadin/flow/templatemodel/BeanModelType.java#L578)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

> are define

Minor typo, I guess you've meant `are defined`.
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/flow/templatemodel/BeanModelType.java, line 583 at r3](https://beta.reviewable.io/reviews/vaadin/flow/3494#-L4eH2hRrRXakj4jYj2f:-L4eJGRNB1X_L8s-s16y:bm5081e) ([raw file](https://github.com/vaadin/flow/blob/efe72d918efab4824cbee77dae5037dac90f5bbd/flow-server/src/main/java/com/vaadin/flow/templatemodel/BeanModelType.java#L583)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Just wondering: do you plan to use that `Boolean` values in the map? Because now you don't.
</blockquote></details>

Yes, of course.
That's the main purpose of this patch.
Will be used in the upcoming PR.

---

*[flow-server/src/main/java/com/vaadin/flow/templatemodel/BeanModelType.java, line 589 at r3](https://beta.reviewable.io/reviews/vaadin/flow/3494#-L4eAN8AfbjKlw5Fvx0Z:-L4eJTUDDjY2ejEWckvQ:baa3dmi) ([raw file](https://github.com/vaadin/flow/blob/efe72d918efab4824cbee77dae5037dac90f5bbd/flow-server/src/main/java/com/vaadin/flow/templatemodel/BeanModelType.java#L589)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Minor and can be ignored.

> Collections.unmodifiableSet

Not sure why it's needed, since you don't change the set inside the `collectAllowedProperties` private method and the new set will change if `twoWayBindingPaths` is changed. 
</blockquote></details>

This is unmodified code.
And I prefer to keep it as is.
It makes impossible to mutate the last parameter in the method `collectAllowedProperties` which kind of define a contract that this is incoming parameter: if implementor don't know the intention of the method contract and tries to modify the collection (not now in the future when the code evolves) it will throw immediately.  It forces the contract which is impossible to declare via API.

---

*[flow-server/src/main/java/com/vaadin/flow/templatemodel/BeanModelType.java, line 634 at r3](https://beta.reviewable.io/reviews/vaadin/flow/3494#-L4eCh6LMQZHGVIgGrA5:-L4eKABc6VIXBT77MjPx:bej3asr) ([raw file](https://github.com/vaadin/flow/blob/efe72d918efab4824cbee77dae5037dac90f5bbd/flow-server/src/main/java/com/vaadin/flow/templatemodel/BeanModelType.java#L634)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

> info

Might be `debug` if we don't want to spam our users with lots of messages every time. 
</blockquote></details>

It's a question do we want to show this message or not.
It's kind of important information. In reality the previous version of the PR threw an exception here at all.
But then I realized a usecase for disallowing property even if there is a getter (it's kind of nonsense to declare getter and have the annotation which deny the update for the property).

But .......
Done.

---

*[flow-server/src/main/java/com/vaadin/flow/templatemodel/BeanModelType.java, line 636 at r3](https://beta.reviewable.io/reviews/vaadin/flow/3494#-L4eB2ofL71dlWlS3SNo:-L4eKu38BHzp_eL_qSjI:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/efe72d918efab4824cbee77dae5037dac90f5bbd/flow-server/src/main/java/com/vaadin/flow/templatemodel/BeanModelType.java#L636)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

> explicitely

Did you mean `explicitly`? Same for two occurrences below, including 
> implicitely
</blockquote></details>

Done.

---

*[flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/OneWayPolymerBindingView.java, line 47 at r3](https://beta.reviewable.io/reviews/vaadin/flow/3494#-L4eGRT6VNhnVgJMVp4I:-L4eL2Ua4twA69MiJK_U:b-vrxf81) ([raw file](https://github.com/vaadin/flow/blob/efe72d918efab4824cbee77dae5037dac90f5bbd/flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/OneWayPolymerBindingView.java#L47)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Just FYI: after https://github.com/vaadin/flow/pull/3497 is merged, you can omit this long `(ClientUpdateMode.ALLOW)` things.
Might be handy in the next PRs or so.
</blockquote></details>

It doesn't hurt.
It's just tests.
Too many places to update. Modifying tests takes most of my time which I may spend on writing real code.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3494)*

**Comment by SomeoneToIgnore** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/templatemodel/BeanModelType.java, line 583 at r3](https://reviewable.io:443/reviews/vaadin/flow/3494#-L4eH2hRrRXakj4jYj2f:-L4eO-cFITIEsDgwepF7:b-83sjo4) ([raw file](https://github.com/vaadin/flow/blob/efe72d918efab4824cbee77dae5037dac90f5bbd/flow-server/src/main/java/com/vaadin/flow/templatemodel/BeanModelType.java#L583)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Yes, of course.
That's the main purpose of this patch.
Will be used in the upcoming PR.
</blockquote></details>

Nice.

---

*[flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/OneWayPolymerBindingView.java, line 47 at r3](https://reviewable.io:443/reviews/vaadin/flow/3494#-L4eGRT6VNhnVgJMVp4I:-L4eNvG7Dtpu81iuKqyf:b-82yn2v) ([raw file](https://github.com/vaadin/flow/blob/efe72d918efab4824cbee77dae5037dac90f5bbd/flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/OneWayPolymerBindingView.java#L47)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

It doesn't hurt.
It's just tests.
Too many places to update. Modifying tests takes most of my time which I may spend on writing real code.
</blockquote></details>

Sure, sure. Like I've said, it's just for you to note for future changes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3494#-:-L4eODlpNTHK35Z1Fkf2:bnfp4nl)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3494#-L4eIFJk49vZoloCG3oT:-L4eNZiRCGovdkVL-gcv:b-huvv95) (no related file):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Do I get it right that now, if we want to have any model property updated, we need to put `@AllowClientUpdates` on it explicitly?

I guess we should update our docs then.
</blockquote></details>

No.
- I haven't changed anything about working model properties YET. Yes we need updated the docs but it has no any relation to this PR. `@AllowClientUpdates` needs to be documented in details and there is a ticket about this.
- This PR is intended to find allowed properties which have getters. I will send those properties (which has getters only) to the client side and updates from the client side will be done only for those model properties.
- Currently you need do declare your property explicitly via `@AllowClientUpdates` or have it as two way binding property (it should be two way binding on the client side). By default absence of `@AllowClientUpdates`   means `if property is two way binding`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3494)*

**Comment by SomeoneToIgnore** [comment]
*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3494#-L4eIFJk49vZoloCG3oT:-L4eO_Rf95W4xNglLGp5:bk6j6w0) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

No.
- I haven't changed anything about working model properties YET. Yes we need updated the docs but it has no any relation to this PR. `@AllowClientUpdates` needs to be documented in details and there is a ticket about this.
- This PR is intended to find allowed properties which have getters. I will send those properties (which has getters only) to the client side and updates from the client side will be done only for those model properties.
- Currently you need do declare your property explicitly via `@AllowClientUpdates` or have it as two way binding property (it should be two way binding on the client side). By default absence of `@AllowClientUpdates`   means `if property is two way binding`.
</blockquote></details>

Got it, thanks.

Don't forget to unblock all the discussions, btw :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3494)*

**Pull request merged**
