### PR TITLE
Make StaticFileServer use servlet instead of service

### PR DESCRIPTION
**Pull request by Artur-**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3864)

### CODE REVIEW

**Comment by caalador** [comment]
Reviewed 2 of 4 files at r1.
Review status: 2 of 4 files reviewed at latest revision, all discussions resolved.

---

*[flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java, line 97 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3864#-L9yj_vO3JAW-IXqR99a:-L9yj_vO3JAW-IXqR99b:b-b2jpwv) ([raw file](https://github.com/vaadin/flow/blob/9d5dfe4137314161b9302dde27d1efb86d6a7337/flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java#L97)):*
> ```Java
>     private URL getResource(String path) {
>         try {
>             return servlet.getServletContext().getResource(path);
> ```

why do this as you have the same handling in `servlet.getResource(path)`

---

*[flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java, line 137 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3864#-L9yjulW9n64tXoa2Qzo:-L9yjulW9n64tXoa2Qzp:babr375) ([raw file](https://github.com/vaadin/flow/blob/9d5dfe4137314161b9302dde27d1efb86d6a7337/flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java#L137)):*
> ```Java
>     private VaadinServlet servlet = Mockito.mock(VaadinServlet.class);
>     private DeploymentConfiguration configuration;
>     private ServletContext servletContext;
> ```

Only use servlet. having the ServletContext is not needed after you start using `VaadinServlet::getResource(String path)` which uses the ServletContext.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3864)*

**Comment by Artur-** [comment]
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java, line 97 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3864#-L9yj_vO3JAW-IXqR99a:-L9ylH6zBJRhsTomEhAe:b2lkguf) ([raw file](https://github.com/vaadin/flow/blob/9d5dfe4137314161b9302dde27d1efb86d6a7337/flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java#L97)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

why do this as you have the same handling in `servlet.getResource(path)`
</blockquote></details>

So that  `servlet.getResource()` can be remvoed

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3864)*

**Comment by caalador** [comment]
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java, line 97 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3864#-L9yj_vO3JAW-IXqR99a:-L9ynLiiBG75BKAkzSMj:b5okseu) ([raw file](https://github.com/vaadin/flow/blob/9d5dfe4137314161b9302dde27d1efb86d6a7337/flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java#L97)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

So that  `servlet.getResource()` can be remvoed
</blockquote></details>

But that's explicitly there as you shouldn't directly use servletContext.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3864)*

**Comment by caalador** [comment]
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java, line 97 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3864#-L9yj_vO3JAW-IXqR99a:-L9yoBlnCfwhhHioqWld:bl15ggd) ([raw file](https://github.com/vaadin/flow/blob/9d5dfe4137314161b9302dde27d1efb86d6a7337/flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java#L97)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

But that's explicitly there as you shouldn't directly use servletContext.
</blockquote></details>

https://github.com/vaadin/flow/issues/3643

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3864)*

**Comment by Artur-** [comment]
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java, line 97 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3864#-L9yj_vO3JAW-IXqR99a:-L9yv72U43b1pfqC_ScZ:b-w3i752) ([raw file](https://github.com/vaadin/flow/blob/9d5dfe4137314161b9302dde27d1efb86d6a7337/flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java#L97)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

https://github.com/vaadin/flow/issues/3643
</blockquote></details>

In this case you explicitly want to find from the servlet context and not through some abstraction, which is btw introduced in #3881 . That actually abstracts away the underlying concepts of theme translations and webjars vs servlet context files.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3864)*

**Comment by SomeoneToIgnore** [comment]
*[flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java, line 137 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3864#-L9yjulW9n64tXoa2Qzo:-LAHp6TQ8-snvSSLIOgc:bsoz9lv) ([raw file](https://github.com/vaadin/flow/blob/9d5dfe4137314161b9302dde27d1efb86d6a7337/flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java#L137)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Only use servlet. having the ServletContext is not needed after you start using `VaadinServlet::getResource(String path)` which uses the ServletContext.
</blockquote></details>

I guess it's related to your other discussion and can be resolved, @artur- ?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3864)*

**Comment by Artur-** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java, line 137 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3864#-L9yjulW9n64tXoa2Qzo:-LAHpIbwBs9zqtc-nK5D:bne7jvk) ([raw file](https://github.com/vaadin/flow/blob/9d5dfe4137314161b9302dde27d1efb86d6a7337/flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java#L137)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

I guess it's related to your other discussion and can be resolved, @artur- ?
</blockquote></details>

It's the same yes

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3864)*

**Comment by SomeoneToIgnore** [comment]
:lgtm:

---

Reviewed 2 of 4 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3864#-:-LAHpWNY3_Dgw7wNtps1:bnfp4nl)*

**Pull request merged**
