### PR TITLE
Add basic template renderers.

### PR DESCRIPTION
**Pull request by gilberto-torrezan**
A demo with all the renderers will be pushed to `vaadin-grid-flow`.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3144)

### CODE REVIEW

**Comment by ahie** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[flow-server/src/main/java/com/vaadin/ui/renderers/ButtonRenderer.java, line 43 at r1](https://reviewable.io:443/reviews/vaadin/flow/3144#-L0Dyfp24uDUgt8HGB-e:-L0Dyfp24uDUgt8HGB-f:bfdt0xz) ([raw file](https://github.com/vaadin/flow/blob/e44fb6bdd2b75aa4155afff10e173af7e1d878a1/flow-server/src/main/java/com/vaadin/ui/renderers/ButtonRenderer.java#L43)):*
> ```Java
> 
>     private static AtomicInteger RENDERER_ID_GENERATOR = new AtomicInteger();
>     private String template;
> ```

The template uses the native `button` element. Thinking about theming, should we consider having an option to use `vaadin-button` instead? Something that the user can toggle on if he is already importing `vaadin-button` in his view. A class name for the button could also be desirable for theming.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3144)*

**Comment by gilberto-torrezan** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[flow-server/src/main/java/com/vaadin/ui/renderers/ButtonRenderer.java, line 43 at r1](https://reviewable.io:443/reviews/vaadin/flow/3144#-L0Dyfp24uDUgt8HGB-e:-L0E27uOAVEfppM5gadx:b-loooua) ([raw file](https://github.com/vaadin/flow/blob/e44fb6bdd2b75aa4155afff10e173af7e1d878a1/flow-server/src/main/java/com/vaadin/ui/renderers/ButtonRenderer.java#L43)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

The template uses the native `button` element. Thinking about theming, should we consider having an option to use `vaadin-button` instead? Something that the user can toggle on if he is already importing `vaadin-button` in his view. A class name for the button could also be desirable for theming.
</blockquote></details>

I asked about this on Slack (before implementing this), and Pekka answered that is fine to have a native button for now - we can provide another renderer in the future, or just make the developer use a `ComponentRenderer`. In either case, this will be properly validated in the DX tests.

One challenge in using `vaadin-button` is how to import it - since we don't have a proper Component, there's no place to put a `@Import` annotation. We can use the imperative API to import it, but then it wouldn't be scanned by the maven-plugin to generate bundles.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3144)*

**Comment by ahie** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[flow-server/src/main/java/com/vaadin/ui/renderers/LocalDateRenderer.java, line 186 at r1](https://reviewable.io:443/reviews/vaadin/flow/3144#-L0F9AJh2cNEOqFL45b5:-L0F9AJh2cNEOqFL45b6:b-vvnxya) ([raw file](https://github.com/vaadin/flow/blob/f2c8c834f7ac84efc4360d28c09beef8642e99d6/flow-server/src/main/java/com/vaadin/ui/renderers/LocalDateRenderer.java#L186)):*
> formatter.format(date)

This can throw. Should probably check the exception and rethrow a more flow user friendly exception.

---

*[flow-server/src/main/java/com/vaadin/ui/renderers/NumberRenderer.java, line 206 at r1](https://reviewable.io:443/reviews/vaadin/flow/3144#-L0F8aUroBVLfa5Ti_3u:-L0F8aUroBVLfa5Ti_3v:b-p8mw8n) ([raw file](https://github.com/vaadin/flow/blob/f2c8c834f7ac84efc4360d28c09beef8642e99d6/flow-server/src/main/java/com/vaadin/ui/renderers/NumberRenderer.java#L206)):*
> Internal bug

Makes it sound like a flow bug when it's actually a user error? Could change to "Unable to format the given value:" or similar?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3144)*

**Comment by gilberto-torrezan** [comment]
Review status: 4 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/ui/renderers/LocalDateRenderer.java, line 186 at r1](https://reviewable.io:443/reviews/vaadin/flow/3144#-L0F9AJh2cNEOqFL45b5:-L0IeEjyhlYaJtbtTJxB:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/f2c8c834f7ac84efc4360d28c09beef8642e99d6/flow-server/src/main/java/com/vaadin/ui/renderers/LocalDateRenderer.java#L186)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

> formatter.format(date)

This can throw. Should probably check the exception and rethrow a more flow user friendly exception.
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/ui/renderers/NumberRenderer.java, line 206 at r1](https://reviewable.io:443/reviews/vaadin/flow/3144#-L0F8aUroBVLfa5Ti_3u:-L0IclaLy_rN4DOrK8BE:b4pn9a3) ([raw file](https://github.com/vaadin/flow/blob/f2c8c834f7ac84efc4360d28c09beef8642e99d6/flow-server/src/main/java/com/vaadin/ui/renderers/NumberRenderer.java#L206)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

> Internal bug

Makes it sound like a flow bug when it's actually a user error? Could change to "Unable to format the given value:" or similar?
</blockquote></details>

That was copy-pasted from FW8. In fact there's no way for this else to be executed, since all the parameters are set in the constructors, and all of them have null checks. But I agree that the message is scary, I'll change that.

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3144)*

**Comment by ahie** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3144)*

**Comment by ahie** [comment]
Review status: all files reviewed at latest revision, 31 unresolved discussions, some commit checks broke.

---

*[flow-server/src/main/java/com/vaadin/ui/renderers/LocalDateRenderer.java, line 31 at r2](https://reviewable.io:443/reviews/vaadin/flow/3144#-L0DurhId1ClotfLRKVT-r2-31:-L0Ix3vTGd9NbMpC-zFv:b-qi0pqw) ([raw file](https://github.com/vaadin/flow/blob/ea158d73542e8542eaeb020feb3fa01efc64bfee/flow-server/src/main/java/com/vaadin/ui/renderers/LocalDateRenderer.java#L31)):*
> Document the parameter(s)

+1

---

*[flow-server/src/main/java/com/vaadin/ui/renderers/LocalDateTimeRenderer.java, line 31 at r2](https://reviewable.io:443/reviews/vaadin/flow/3144#-L0DurhId1ClotfLRKVU-r2-31:-L0IxYW_bHTvKzXAktwG:buv3uoo) ([raw file](https://github.com/vaadin/flow/blob/ea158d73542e8542eaeb020feb3fa01efc64bfee/flow-server/src/main/java/com/vaadin/ui/renderers/LocalDateTimeRenderer.java#L31)):*
> Document the parameter(s)
 
+1

---

*[flow-server/src/main/java/com/vaadin/ui/renderers/NumberRenderer.java, line 30 at r2](https://reviewable.io:443/reviews/vaadin/flow/3144#-L0DurhId1ClotfLRKVV-r2-30:-L0Ix-0APBAsTVMPQUaH:b-qi0pqw) ([raw file](https://github.com/vaadin/flow/blob/ea158d73542e8542eaeb020feb3fa01efc64bfee/flow-server/src/main/java/com/vaadin/ui/renderers/NumberRenderer.java#L30)):*
> Document the parameter(s)

+1

---

*[flow-server/src/main/java/com/vaadin/ui/renderers/NumberRenderer.java, line 86 at r2](https://reviewable.io:443/reviews/vaadin/flow/3144#-L0DurhId1ClotfLRKVV-r2-86:-L0IwyYvWBIfwNssVwsx:bowms0p) ([raw file](https://github.com/vaadin/flow/blob/ea158d73542e8542eaeb020feb3fa01efc64bfee/flow-server/src/main/java/com/vaadin/ui/renderers/NumberRenderer.java#L86)):*
> Remove the declaration of thrown exception 'java.lang.IllegalArgumentException' which is a runtime exception.

+1

---

*[flow-server/src/main/java/com/vaadin/ui/renderers/NumberRenderer.java, line 113 at r2](https://reviewable.io:443/reviews/vaadin/flow/3144#-L0DurhId1ClotfLRKVV-r2-113:-L0Iwx9NqiouLFlJtEtM:bowms0p) ([raw file](https://github.com/vaadin/flow/blob/ea158d73542e8542eaeb020feb3fa01efc64bfee/flow-server/src/main/java/com/vaadin/ui/renderers/NumberRenderer.java#L113)):*
> Remove the declaration of thrown exception 'java.lang.IllegalArgumentException' which is a runtime exception.

+1

---

*[flow-server/src/main/java/com/vaadin/ui/renderers/NumberRenderer.java, line 134 at r2](https://reviewable.io:443/reviews/vaadin/flow/3144#-L0DurhId1ClotfLRKVV-r2-134:-L0IwukzV21LA4xPbSq_:b-98mh4f) ([raw file](https://github.com/vaadin/flow/blob/ea158d73542e8542eaeb020feb3fa01efc64bfee/flow-server/src/main/java/com/vaadin/ui/renderers/NumberRenderer.java#L134)):*
> Remove the declaration of thrown exception 'java.lang.IllegalArgumentException' which is a runtime exception.

+1

---

*[flow-server/src/main/java/com/vaadin/ui/renderers/NumberRenderer.java, line 156 at r2](https://reviewable.io:443/reviews/vaadin/flow/3144#-L0DurhId1ClotfLRKVV-r2-156:-L0IwdCAzZAJ-FoeITiD:b-2awi0l) ([raw file](https://github.com/vaadin/flow/blob/ea158d73542e8542eaeb020feb3fa01efc64bfee/flow-server/src/main/java/com/vaadin/ui/renderers/NumberRenderer.java#L156)):*
> Remove the declaration of thrown exception 'java.lang.IllegalArgumentException' which is a runtime exception.

+1. 

---

*[flow-server/src/main/java/com/vaadin/ui/renderers/NumberRenderer.java, line 178 at r2](https://reviewable.io:443/reviews/vaadin/flow/3144#-L0DurhId1ClotfLRKVV-r2-178:-L0IwRNJVRJAPBo9_dl1:b-9ksewu) ([raw file](https://github.com/vaadin/flow/blob/ea158d73542e8542eaeb020feb3fa01efc64bfee/flow-server/src/main/java/com/vaadin/ui/renderers/NumberRenderer.java#L178)):*
> Document the parameter(s): nullRepresentation

+1

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3144)*

**Comment by gilberto-torrezan** [comment]
Review status: 1 of 6 files reviewed at latest revision, 31 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/ui/renderers/LocalDateRenderer.java, line 31 at r2](https://reviewable.io:443/reviews/vaadin/flow/3144#-L0DurhId1ClotfLRKVT-r2-31:-L0J3Tsr1jaapVmjgBGr:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/ea158d73542e8542eaeb020feb3fa01efc64bfee/flow-server/src/main/java/com/vaadin/ui/renderers/LocalDateRenderer.java#L31)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

> Document the parameter(s)

+1
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/ui/renderers/LocalDateTimeRenderer.java, line 31 at r2](https://reviewable.io:443/reviews/vaadin/flow/3144#-L0DurhId1ClotfLRKVU-r2-31:-L0J3SOzxBs8RCB9HFyG:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/ea158d73542e8542eaeb020feb3fa01efc64bfee/flow-server/src/main/java/com/vaadin/ui/renderers/LocalDateTimeRenderer.java#L31)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

> Document the parameter(s)
 
+1
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/ui/renderers/NumberRenderer.java, line 86 at r2](https://reviewable.io:443/reviews/vaadin/flow/3144#-L0DurhId1ClotfLRKVV-r2-86:-L0J3QtjgF1dNZPEXUTG:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/ea158d73542e8542eaeb020feb3fa01efc64bfee/flow-server/src/main/java/com/vaadin/ui/renderers/NumberRenderer.java#L86)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

> Remove the declaration of thrown exception 'java.lang.IllegalArgumentException' which is a runtime exception.

+1
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/ui/renderers/NumberRenderer.java, line 113 at r2](https://reviewable.io:443/reviews/vaadin/flow/3144#-L0DurhId1ClotfLRKVV-r2-113:-L0J3Q2vRgKcsSJdSffx:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/ea158d73542e8542eaeb020feb3fa01efc64bfee/flow-server/src/main/java/com/vaadin/ui/renderers/NumberRenderer.java#L113)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

> Remove the declaration of thrown exception 'java.lang.IllegalArgumentException' which is a runtime exception.

+1
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/ui/renderers/NumberRenderer.java, line 134 at r2](https://reviewable.io:443/reviews/vaadin/flow/3144#-L0DurhId1ClotfLRKVV-r2-134:-L0J3PNXB7WVpq9Qj8Uy:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/ea158d73542e8542eaeb020feb3fa01efc64bfee/flow-server/src/main/java/com/vaadin/ui/renderers/NumberRenderer.java#L134)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

> Remove the declaration of thrown exception 'java.lang.IllegalArgumentException' which is a runtime exception.

+1

</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/ui/renderers/NumberRenderer.java, line 156 at r2](https://reviewable.io:443/reviews/vaadin/flow/3144#-L0DurhId1ClotfLRKVV-r2-156:-L0J3OfwegHKxdnV0fIp:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/ea158d73542e8542eaeb020feb3fa01efc64bfee/flow-server/src/main/java/com/vaadin/ui/renderers/NumberRenderer.java#L156)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

> Remove the declaration of thrown exception 'java.lang.IllegalArgumentException' which is a runtime exception.

+1. 
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/ui/renderers/NumberRenderer.java, line 178 at r2](https://reviewable.io:443/reviews/vaadin/flow/3144#-L0DurhId1ClotfLRKVV-r2-178:-L0J3NhrjZBevL4EFAjX:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/ea158d73542e8542eaeb020feb3fa01efc64bfee/flow-server/src/main/java/com/vaadin/ui/renderers/NumberRenderer.java#L178)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

> Document the parameter(s): nullRepresentation

+1
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3144)*

**Comment by ahie** [comment]
Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 31 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3144)*

**Pull request merged**
