### PR TITLE
Same location navigation should be UI dependent.

### PR DESCRIPTION
**Pull request by caalador**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/2687)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[flow-server/src/main/java/com/vaadin/router/Router.java, line 168 at r1](https://reviewable.io:443/reviews/vaadin/flow/2687#-KwZMTVuyVJs-xOW0vY2:-KwZMTVuyVJs-xOW0vY3:b-in23hp) ([raw file](https://github.com/vaadin/flow/blob/cb89d2f578bb1097107def129f2b71ec38187c52/flow-server/src/main/java/com/vaadin/router/Router.java#L168)):*
> Optional<Location>

We don't use `Optional` as an argument.

---

*[flow-server/src/main/java/com/vaadin/ui/UIInternals.java, line 772 at r1](https://reviewable.io:443/reviews/vaadin/flow/2687#-KwZMeb2RN0KSrvh7qJR:-KwZMeb3nXG78jxRVkY8:b-8dd8yo) ([raw file](https://github.com/vaadin/flow/blob/cb89d2f578bb1097107def129f2b71ec38187c52/flow-server/src/main/java/com/vaadin/ui/UIInternals.java#L772)):*
> lastHandledNavigation = null;

Just to be consistent: `setLastHandledNavigation(null)`.

---

*[flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RouterParallelIT.java, line 27 at r1](https://reviewable.io:443/reviews/vaadin/flow/2687#-KwZN0RZieAyV6IkdMXL:-KwZN0RZieAyV6IkdMXM:b-fh5k9s) ([raw file](https://github.com/vaadin/flow/blob/cb89d2f578bb1097107def129f2b71ec38187c52/flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RouterParallelIT.java#L27)):*
> RouterParallelIT

Is this class is going to be instantiated and this _one_ single instance will be executed in parallel ?

Or there will be a several instances working in its own thread ?

I care about thread safety here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2687)*

**Comment by denis-anisimov** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/router/Router.java, line 168 at r1](https://reviewable.io:443/reviews/vaadin/flow/2687#-KwZY12TQQJU_BeGIFBL:-KwZY12UxWM6B8uOirLk:b-gso64n) ([raw file](https://github.com/vaadin/flow/blob/e514c64c0994c23e7d6573499232dd9e30b35b78/flow-server/src/main/java/com/vaadin/router/Router.java#L168)):*
> Optional<Location> lastHandledNavigation

We don't use Optional as an argument.

---

*[flow-server/src/main/java/com/vaadin/ui/UIInternals.java, line 772 at r1](https://reviewable.io:443/reviews/vaadin/flow/2687#-KwZY5aSggdhIIAHPbDA:-KwZY5aSggdhIIAHPbDB:b-8dd8yo) ([raw file](https://github.com/vaadin/flow/blob/e514c64c0994c23e7d6573499232dd9e30b35b78/flow-server/src/main/java/com/vaadin/ui/UIInternals.java#L772)):*
> lastHandledNavigation = null;

Just to be consistent: `setLastHandledNavigation(null)`.

---

*[flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RouterParallelIT.java, line 27 at r1](https://reviewable.io:443/reviews/vaadin/flow/2687#-KwZYA0P_sZd0RIIm51-:-KwZYA0P_sZd0RIIm510:b-vyk54b) ([raw file](https://github.com/vaadin/flow/blob/e514c64c0994c23e7d6573499232dd9e30b35b78/flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RouterParallelIT.java#L27)):*
> RouterParallelIT extends AbstractParallelTestBenchTest {


Is this class is going to be instantiated and this _one_ single instance will be executed in parallel ?

Or there will be a several instances working in its own thread ?

I care about thread safety here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2687)*

**Comment by caalador** [comment]
Review status: 3 of 5 files reviewed at latest revision, 7 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/router/Router.java, line 168 at r1](https://reviewable.io:443/reviews/vaadin/flow/2687#-KwZY12TQQJU_BeGIFBL:-KwZYaG2XpYsveoAgD_5:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/e514c64c0994c23e7d6573499232dd9e30b35b78/flow-server/src/main/java/com/vaadin/router/Router.java#L168)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> Optional<Location> lastHandledNavigation

We don't use Optional as an argument.
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/ui/UIInternals.java, line 772 at r1](https://reviewable.io:443/reviews/vaadin/flow/2687#-KwZY5aSggdhIIAHPbDA:-KwZYikD_VxdWNA-kV0U:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/e514c64c0994c23e7d6573499232dd9e30b35b78/flow-server/src/main/java/com/vaadin/ui/UIInternals.java#L772)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> lastHandledNavigation = null;

Just to be consistent: `setLastHandledNavigation(null)`.
</blockquote></details>

Done.

---

*[flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RouterParallelIT.java, line 27 at r1](https://reviewable.io:443/reviews/vaadin/flow/2687#-KwZYA0P_sZd0RIIm51-:-KwZZT5L14tLmJPBMKie:baq50st) ([raw file](https://github.com/vaadin/flow/blob/e514c64c0994c23e7d6573499232dd9e30b35b78/flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RouterParallelIT.java#L27)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> RouterParallelIT extends AbstractParallelTestBenchTest {


Is this class is going to be instantiated and this _one_ single instance will be executed in parallel ?

Or there will be a several instances working in its own thread ?

I care about thread safety here.
</blockquote></details>

'TestBench launches multiple browser windows to run each test in parallel.'

It uses the `BlockJUnit4ClassRunner` at base so I'm not making any promises, but it should execute them in own threads up to `MAX_CONCURRENT_TESTS`. Also there should be no bleed over on the tests. Only the chance that we have something iffy on the server side.

If you want exact functionality you need to ask the TestBench team or Artur.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2687)*

**Comment by denis-anisimov** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RouterParallelIT.java, line 27 at r1](https://reviewable.io:443/reviews/vaadin/flow/2687#-KwZYA0P_sZd0RIIm51-:-KwZN0RZieAyV6IkdMXM:blml0uo) ([raw file](https://github.com/vaadin/flow/blob/e514c64c0994c23e7d6573499232dd9e30b35b78/flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RouterParallelIT.java#L27)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

'TestBench launches multiple browser windows to run each test in parallel.'

It uses the `BlockJUnit4ClassRunner` at base so I'm not making any promises, but it should execute them in own threads up to `MAX_CONCURRENT_TESTS`. Also there should be no bleed over on the tests. Only the chance that we have something iffy on the server side.

If you want exact functionality you need to ask the TestBench team or Artur.
</blockquote></details>

Actually  I would say the test should be modified:
- `private WebElement buttonElement;` is a scary code in case if the same instance is run in different threads. That's why I asked the question.
- I would recommend to check element presence in each `a`, `b`, .. methods.


Now it's found once and checked several time without rerun the search. So the test doesn't do what's it intended for (otherwise there is no need in a number of test methods) .

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2687)*

**Comment by caalador** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RouterParallelIT.java, line 27 at r1](https://reviewable.io:443/reviews/vaadin/flow/2687#-KwZYA0P_sZd0RIIm51-:-KwZg6vsBL9EnwjZ1Op4:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/e514c64c0994c23e7d6573499232dd9e30b35b78/flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RouterParallelIT.java#L27)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Actually  I would say the test should be modified:
- `private WebElement buttonElement;` is a scary code in case if the same instance is run in different threads. That's why I asked the question.
- I would recommend to check element presence in each `a`, `b`, .. methods.


Now it's found once and checked several time without rerun the search. So the test doesn't do what's it intended for (otherwise there is no need in a number of test methods) .
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2687)*

**Comment by denis-anisimov** [comment]
Review status: 4 of 5 files reviewed at latest revision, 6 unresolved discussions.

---

*[flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RouterParallelIT.java, line 37 at r3](https://reviewable.io:443/reviews/vaadin/flow/2687#-KwZwzOPrBdaNyPcuj5G:-KwZwzOPrBdaNyPcuj5H:b-acn5xt) ([raw file](https://github.com/vaadin/flow/blob/b4264a02f30615bf59451e0d2f2ff47afa238fb3/flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RouterParallelIT.java#L37)):*
> WebElement button = findElements(By.tagName(Tag.BUTTON)).get(0);
>         Assert.assertNotNull(button);

Why not just `isElementPresent(By.tagName(Tag.BUTTON))`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2687)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2687)*

**Comment by caalador** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RouterParallelIT.java, line 37 at r3](https://reviewable.io:443/reviews/vaadin/flow/2687#-KwZwzOPrBdaNyPcuj5G:-Kw_-qHnMG6HzA3NiIsT:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/b4264a02f30615bf59451e0d2f2ff47afa238fb3/flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RouterParallelIT.java#L37)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> WebElement button = findElements(By.tagName(Tag.BUTTON)).get(0);
>         Assert.assertNotNull(button);

Why not just `isElementPresent(By.tagName(Tag.BUTTON))`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2687)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2687)*

**Pull request merged**
