### PR TITLE
Add support for detecting ChromeOS operating system

### PR DESCRIPTION
**Pull request by torok-peter**
Port change from Fw 8.1.1
Original PR:
https://github.com/vaadin/framework/pull/9698

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/2980)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2980)*

**Comment by torok-peter** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[flow-server/src/main/java/com/vaadin/shared/BrowserDetails.java, line 239 at r1](https://reviewable.io:443/reviews/vaadin/flow/2980#-KzObzPQGMr3qolFFel5-r1-239:-KzSIQpdCsDJG488TKML:b-it31ag) ([raw file](https://github.com/vaadin/flow/blob/c329c1439e6ae338357c39815a922fe63d6ee062/flow-server/src/main/java/com/vaadin/shared/BrowserDetails.java#L239)):*
<details><summary><i>Previously, vaadin-bot (Vaadin Bot) wrote…</i></summary><blockquote>

BLOCKER Rename method "parseChromeOsVersion" to prevent any misunderstanding/clash with method "parseChromeOSVersion" defined on line 218. [rule](https://sonar.projects.vaadin.com/coding_rules#rule_key=squid%3AS1845)
</blockquote></details>

BTW won't fix

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2980)*

**Comment by denis-anisimov** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2980)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2980)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2980)*

**Comment by torok-peter** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-server/src/main/java/com/vaadin/shared/BrowserDetails.java, line 239 at r1](https://reviewable.io:443/reviews/vaadin/flow/2980#-KzObzPQGMr3qolFFel5-r1-239:-KzTdhvPh3o8ExgPN_6e:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/c329c1439e6ae338357c39815a922fe63d6ee062/flow-server/src/main/java/com/vaadin/shared/BrowserDetails.java#L239)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

BTW won't fix
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2980)*

**Pull request merged**
