### PR TITLE
Add Grid.Column component and width related API

### PR DESCRIPTION
**Pull request by ahie**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/2755)

### CODE REVIEW

**Comment by torok-peter** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks broke.

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 468 at r1](https://reviewable.io:443/reviews/vaadin/flow/2755#-Kx8LotCaZTfJyrhNpMD:-Kx8LotCaZTfJyrhNpME:bgurshr) ([raw file](https://github.com/vaadin/flow/blob/bb29083f04b771ae4a13dba08a1334323e54d90e/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L468)):*
> ```Java
>      */
>     @Tag("vaadin-grid-column")
>     public static class Column<T> extends Component {
> ```

Would it make sense to declare the class nonstatic as it needs a reference to an enclosing class instance? That would obsolete the `grid` field below. 

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 520 at r1](https://reviewable.io:443/reviews/vaadin/flow/2755#-Kx8MeOrzEK8cuiISlnV:-Kx8MeOrzEK8cuiISlnW:bb740l2) ([raw file](https://github.com/vaadin/flow/blob/bb29083f04b771ae4a13dba08a1334323e54d90e/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L520)):*
> ```Java
> 
>         /**
>          * Set the width of this column as a CSS-string.
> ```

Sets

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 534 at r1](https://reviewable.io:443/reviews/vaadin/flow/2755#-Kx8MhYwWleoaxj63vY-:-Kx8MhYxvVaD80vQMbBQ:bb6wcqq) ([raw file](https://github.com/vaadin/flow/blob/bb29083f04b771ae4a13dba08a1334323e54d90e/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L534)):*
> ```Java
> 
>         /**
>          * Get the width of this column as a CSS-string.
> ```

Gets

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 544 at r1](https://reviewable.io:443/reviews/vaadin/flow/2755#-Kx8Mm3Y3hMkm4nESywJ:-Kx8Mm3Y3hMkm4nESywK:bb740l2) ([raw file](https://github.com/vaadin/flow/blob/bb29083f04b771ae4a13dba08a1334323e54d90e/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L544)):*
> ```Java
> 
>         /**
>          * Set the flex grow ratio for this column. When set to 0, column width
> ```

Sets

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 558 at r1](https://reviewable.io:443/reviews/vaadin/flow/2755#-Kx8Mp7-hzqDTWhiH_Ap:-Kx8Mp7-hzqDTWhiH_Aq:bb6wcqq) ([raw file](https://github.com/vaadin/flow/blob/bb29083f04b771ae4a13dba08a1334323e54d90e/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L558)):*
> ```Java
> 
>         /**
>          * Get the currently set flex grow value, by default 1.
> ```

Gets

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 582 at r1](https://reviewable.io:443/reviews/vaadin/flow/2755#-Kx8MyhdTBLl7UvlCB1n:-Kx8MyhdTBLl7UvlCB1o:bb6wcqq) ([raw file](https://github.com/vaadin/flow/blob/bb29083f04b771ae4a13dba08a1334323e54d90e/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L582)):*
> ```Java
> 
>         /**
>          * Get whether this column is user-resizable.
> ```

Gets

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2755)*

**Comment by ahie** [comment]
Review status: 2 of 3 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 468 at r1](https://reviewable.io:443/reviews/vaadin/flow/2755#-Kx8LotCaZTfJyrhNpMD:-Kx8Y0vOdhq7xBdpBjSP:bt103bg) ([raw file](https://github.com/vaadin/flow/blob/bb29083f04b771ae4a13dba08a1334323e54d90e/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L468)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

Would it make sense to declare the class nonstatic as it needs a reference to an enclosing class instance? That would obsolete the `grid` field below. 
</blockquote></details>

If we decide to move the `Column` code outside of grid that would make it more difficult. By making it non-static it is easier to end up with code that is tightly coupled with the grid. This would also rule out building columns outside a grid instance.

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 520 at r1](https://reviewable.io:443/reviews/vaadin/flow/2755#-Kx8MeOrzEK8cuiISlnV:-Kx8Yyz3n9qRfDs47tsj:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/bb29083f04b771ae4a13dba08a1334323e54d90e/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L520)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

Sets
</blockquote></details>

Done.

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 534 at r1](https://reviewable.io:443/reviews/vaadin/flow/2755#-Kx8MhYwWleoaxj63vY-:-Kx8YzHoLEmv69Iqc-Kx:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/bb29083f04b771ae4a13dba08a1334323e54d90e/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L534)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

Gets
</blockquote></details>

Done.

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 544 at r1](https://reviewable.io:443/reviews/vaadin/flow/2755#-Kx8Mm3Y3hMkm4nESywJ:-Kx8YzZmPDsKlNL_iqbZ:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/bb29083f04b771ae4a13dba08a1334323e54d90e/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L544)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

Sets
</blockquote></details>

Done.

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 558 at r1](https://reviewable.io:443/reviews/vaadin/flow/2755#-Kx8Mp7-hzqDTWhiH_Ap:-Kx8Yzsyx_pTPKkmrfba:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/bb29083f04b771ae4a13dba08a1334323e54d90e/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L558)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

Gets
</blockquote></details>

Done.

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 582 at r1](https://reviewable.io:443/reviews/vaadin/flow/2755#-Kx8MyhdTBLl7UvlCB1n:-Kx8Z-EipSLR2bfD26cY:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/bb29083f04b771ae4a13dba08a1334323e54d90e/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L582)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

Gets
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2755)*

**Comment by torok-peter** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2755)*

**Comment by gilberto-torrezan** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/views/GridView.java, line 342 at r2](https://reviewable.io:443/reviews/vaadin/flow/2755#-KxBtn_MYs8BBwKADsi6:-KxBtn_MYs8BBwKADsi7:bq9tl6d) ([raw file](https://github.com/vaadin/flow/blob/af5295c74808e7a7787ae69d48f9b775bffca576/flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/views/GridView.java#L342)):*
> ```Java
> 
>         grid.setId("resizable-columns");
>         addCard("Grid with resizable columns", grid);
> ```

You are probably having visualization issues here. The name of the card should be the same String as the `source-example-heading` - in this case "Grid with column resizing".

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 468 at r2](https://reviewable.io:443/reviews/vaadin/flow/2755#-KxBuNALeuTkAqRgbIaO:-KxBuNALeuTkAqRgbIaP:b-6i5ydm) ([raw file](https://github.com/vaadin/flow/blob/af5295c74808e7a7787ae69d48f9b775bffca576/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L468)):*
> ```Java
>      */
>     @Tag("vaadin-grid-column")
>     public static class Column<T> extends Component {
> ```

I'm totally fine with this - in fact, I even suggested to make `Column` a `Component` (or at least `HasElement`). But the problem will be to convince @pleku about this implementation.

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 468 at r2](https://reviewable.io:443/reviews/vaadin/flow/2755#-KxBvCtY3cc7eBHyvWbi:-KxBvCtY3cc7eBHyvWbj:b-rplisw) ([raw file](https://github.com/vaadin/flow/blob/af5295c74808e7a7787ae69d48f9b775bffca576/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L468)):*
> ```Java
>      */
>     @Tag("vaadin-grid-column")
>     public static class Column<T> extends Component {
> ```

Would make sense to separate in a different file, just to reduce the complexity of the Grid?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2755)*

**Comment by gilberto-torrezan** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2755)*

**Comment by ahie** [comment]
Review status: 1 of 3 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/views/GridView.java, line 342 at r2](https://reviewable.io:443/reviews/vaadin/flow/2755#-KxBtn_MYs8BBwKADsi6:-KxC4tYjmL54qGKzhKmV:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/af5295c74808e7a7787ae69d48f9b775bffca576/flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/views/GridView.java#L342)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

You are probably having visualization issues here. The name of the card should be the same String as the `source-example-heading` - in this case "Grid with column resizing".
</blockquote></details>

Done.

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 468 at r2](https://reviewable.io:443/reviews/vaadin/flow/2755#-KxBuNALeuTkAqRgbIaO:-KxC53_8GyAb98diiv2h:bn0wyqr) ([raw file](https://github.com/vaadin/flow/blob/af5295c74808e7a7787ae69d48f9b775bffca576/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L468)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

I'm totally fine with this - in fact, I even suggested to make `Column` a `Component` (or at least `HasElement`). But the problem will be to convince @pleku about this implementation.
</blockquote></details>

Discussed with Pekka and came to the conclusion that adding a javadoc note to `getElement` is enough for now.

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 468 at r2](https://reviewable.io:443/reviews/vaadin/flow/2755#-KxBvCtY3cc7eBHyvWbi:-KxC5BuNUFJfsJIt-MMy:b-wencnf) ([raw file](https://github.com/vaadin/flow/blob/af5295c74808e7a7787ae69d48f9b775bffca576/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L468)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Would make sense to separate in a different file, just to reduce the complexity of the Grid?
</blockquote></details>

Problem is we don't really want to give the impression that you could use a `Column` separately from a `Grid`. I think a nested class highlights this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2755)*

**Comment by gilberto-torrezan** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 527 at r3](https://reviewable.io:443/reviews/vaadin/flow/2755#-KxC8ASyfLI_mE-6zeH0:-KxC8ASzL0TkaY71nFNr:b-zhob27) ([raw file](https://github.com/vaadin/flow/blob/dde668602ad01952d5563712d9bed56118217a82/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L527)):*
> ```Java
>          *
>          * @param width
>          *            the width to set this column to, as a CSS-string
> ```

I suggest mentioning that the width cannot be `null` (You don't need to add a check for that though)

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 589 at r3](https://reviewable.io:443/reviews/vaadin/flow/2755#-KxC88Ka8bMiVRsaogKT:-KxC88Ka8bMiVRsaogKU:b-erh57e) ([raw file](https://github.com/vaadin/flow/blob/dde668602ad01952d5563712d9bed56118217a82/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L589)):*
> ```Java
>          */
>         @Synchronize("resizable-changed")
>         public boolean getResizable() {
> ```

Since it returns a `boolean` it should be `isResizable`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2755)*

**Comment by ahie** [comment]
Review status: 2 of 3 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 527 at r3](https://reviewable.io:443/reviews/vaadin/flow/2755#-KxC8ASyfLI_mE-6zeH0:-KxCqxv3xTu-Y3AJpV3a:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/dde668602ad01952d5563712d9bed56118217a82/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L527)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

I suggest mentioning that the width cannot be `null` (You don't need to add a check for that though)
</blockquote></details>

Done.

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 589 at r3](https://reviewable.io:443/reviews/vaadin/flow/2755#-KxC88Ka8bMiVRsaogKT:-KxCqyJDRDOjjdSbvaTK:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/dde668602ad01952d5563712d9bed56118217a82/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L589)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Since it returns a `boolean` it should be `isResizable`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2755)*

**Comment by gilberto-torrezan** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2755)*

**Comment by gilberto-torrezan** [comment]
Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2755)*

**Pull request merged**
