### PR TITLE
NoTheme annotation for classes never implementing a Theme themselves.

### PR DESCRIPTION
**Pull request by caalador**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3406)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-server/src/main/java/com/vaadin/flow/theme/NoTheme.java, line 34 at r1](https://reviewable.io:443/reviews/vaadin/flow/3406#-L3m7HyXyskCWAx2ErOd:-L3m7HyXyskCWAx2ErOe:byi1d75) ([raw file](https://github.com/vaadin/flow/blob/7f92fc0413cc3422e37e7fe2597fab6977eacab5/flow-server/src/main/java/com/vaadin/flow/theme/NoTheme.java#L34)):*
> public @interface NoTheme {

May be it's better to use `@Theme` with the theme which is some dedicated `AbstractTheme`?
E.g. the theme which doesn't do anything: it translate the URL to itself.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3406)*

**Comment by caalador** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[flow-server/src/main/java/com/vaadin/flow/theme/NoTheme.java, line 34 at r1](https://reviewable.io:443/reviews/vaadin/flow/3406#-L3m7HyXyskCWAx2ErOd:-L3mE6jmOcmhJ4apw4lt:b-f98luw) ([raw file](https://github.com/vaadin/flow/blob/7f92fc0413cc3422e37e7fe2597fab6977eacab5/flow-server/src/main/java/com/vaadin/flow/theme/NoTheme.java#L34)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> public @interface NoTheme {

May be it's better to use `@Theme` with the theme which is some dedicated `AbstractTheme`?
E.g. the theme which doesn't do anything: it translate the URL to itself.
</blockquote></details>

I had that version also, but then we will store a translation cache for it etc.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3406)*

**Comment by gilberto-torrezan** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/flow/3406#-L3mK2Z97Q9tO3Cy1qEf:-L3mK2ZA2je9EsSV-CaP:bisiddg) (no related file):*
What happens with a happy user decides to put `@NoTheme` and `@Theme` together at the same class?

---

*[flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java, line 672 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3406#-L3mJeliAr4ZqTdfz0Qb:-L3mJeliAr4ZqTdfz0Qc:b-srhwnl) ([raw file](https://github.com/vaadin/flow/blob/7f92fc0413cc3422e37e7fe2597fab6977eacab5/flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java#L672)):*
> ```Java
>             if (target.getClass().getAnnotation(NoTheme.class) == null) {
>                 getLogger().warn(
>                         "No @Theme defined for {}. See 'trace' level logs for exact components missing theming.",
> ```

I suggest also mentioning the `@NoTheme` annotation in the message as an option to avoid the warning.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3406)*

**Comment by gilberto-torrezan** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[flow-server/src/main/java/com/vaadin/flow/theme/NoTheme.java, line 32 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3406#-L3mKtt16E_pOR5mUZx9:-L3mKtt16E_pOR5mUZxA:b-gtyeqv) ([raw file](https://github.com/vaadin/flow/blob/7f92fc0413cc3422e37e7fe2597fab6977eacab5/flow-server/src/main/java/com/vaadin/flow/theme/NoTheme.java#L32)):*
> ```Java
> @Target(ElementType.TYPE)
> @Retention(RetentionPolicy.RUNTIME)
> @Inherited
> ```

Should it be inherited? What happens if I extend a component with `@NoTheme` and decide to apply a `@Theme` on it?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3406)*

**Comment by caalador** [comment]
Review status: 3 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/flow/3406#-L3mK2Z97Q9tO3Cy1qEf:-L3mNRWZ78wdtfphtUqr:bq9nwub) (no related file):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

What happens with a happy user decides to put `@NoTheme` and `@Theme` together at the same class?
</blockquote></details>

Theme will be used as it is found.

---

*[flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java, line 672 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3406#-L3mJeliAr4ZqTdfz0Qb:-L3mNJhM2uDZQEyxDVDk:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/7f92fc0413cc3422e37e7fe2597fab6977eacab5/flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java#L672)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

I suggest also mentioning the `@NoTheme` annotation in the message as an option to avoid the warning.
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/flow/theme/NoTheme.java, line 32 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3406#-L3mKtt16E_pOR5mUZx9:-L3mNKcC9hn-ERbHljl6:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/7f92fc0413cc3422e37e7fe2597fab6977eacab5/flow-server/src/main/java/com/vaadin/flow/theme/NoTheme.java#L32)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Should it be inherited? What happens if I extend a component with `@NoTheme` and decide to apply a `@Theme` on it?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3406)*

**Comment by gilberto-torrezan** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3406)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3406)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3406)*

**Comment by gilberto-torrezan** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3406)*

**Pull request merged**
