### PR TITLE
Correct component generator code

### PR DESCRIPTION
**Pull request by denis-anisimov**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/2934)

### CODE REVIEW

**Comment by gilberto-torrezan** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2934#-Kyzvhm8ONhpSitq4A8z:-Kyzvhm9h4dxH3aYz2au:bth86nm) (no related file):*
Did you run the generation of our components to see if it breaks anything?

`mvn install -Pgenerator` on the `flow-generated-components` module, after installing `flow-code-generator-api` in your local maven repository

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2934)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2934#-Kyzvhm8ONhpSitq4A8z:-KyzwVHM_C56Y0FK0Ua4:b5ki1qq) (no related file):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Did you run the generation of our components to see if it breaks anything?

`mvn install -Pgenerator` on the `flow-generated-components` module, after installing `flow-code-generator-api` in your local maven repository
</blockquote></details>

Yes, I did

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2934)*

**Comment by gilberto-torrezan** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2934)*

**Comment by gilberto-torrezan** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2934)*

**Pull request merged**
