### PR TITLE
Correct removeAllChildren() behavior when node is just attached and IT test for setText() 

### LINKED ISSUE #43: Show error to user if trying to bind to undefined model property
To help debugging, we should log an error if a template uses a binding to `foo.bar` but `foo` is not defined.

We can't do the same for bindings to just `foo`, since that's a valid case evaluating to `false` in a boolean context (e.g. `<div [class.something]="foo">`).

### PR DESCRIPTION
**Pull request by denis-anisimov**
Fixes #43

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3771)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
This PR is kind of a hack (though the same as all out client side code).
It fixes (in quite ugly way) the `removeAllChildren()` method behavior. At least so that it works correctly now when the node becomes attached.
The problem with the code without this PR is: recent `removeAllChildren()` behavior is not a stateful behavior. It's events based behavior.
There is such state: remove all children (including client side). Current implementation of `removeAllChildren` (before this PR) is an request (event) to remove all children.
It's quite easy to see from the code: all changes that are made to support _clear_ are event based.
But our client-side communication  code is not event based.
It's state based.
That's why we have `StateTree` and `StateNode`.  And it's not really convenient (and even possible) to express events via state. That's why current implementation (before this PR) is broken : there is no such state as "remove all children" which is preserved. 

But I don't know how to solve this properly unfortunately.  We have only two ways to communicate with the client-side:
- via `StateTree`
- via JS execution

JS execution cannot be used here since we won't be able to keep the order of execution ( e.g. "add" /"remove all"/"add"): JS is always executed in the very end.

So JS cannot be used currently for this. And  `StateTree` is also not a proper way to do it.

So this PR is far away from convenient `removeAllChildren` / `clear` support but I don't see anything better with the current client engine.

**Comment by gilberto-torrezan** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[flow-client/src/main/java/com/vaadin/client/flow/nodefeature/NodeList.java, line 150 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3771#-L8gtUmi6ivdFYY-1NIv:-L8gtUmi6ivdFYY-1NIw:bpx1ler) ([raw file](https://github.com/vaadin/flow/blob/a89491a52a36f4b7bb359dcd247a13d0cef24445/flow-client/src/main/java/com/vaadin/client/flow/nodefeature/NodeList.java#L150)):*
> ```Java
>      */
>     public void clear() {
>         hasBeenCleared = true;
> ```

When is this reset to false?

---

*[flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/NodeListAddRemoveTest.java, line 283 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3771#-L8gsBWL3BFd-tiDLyRC:-L8gsBWL3BFd-tiDLyRD:bhrr8gp) ([raw file](https://github.com/vaadin/flow/blob/a89491a52a36f4b7bb359dcd247a13d0cef24445/flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/NodeListAddRemoveTest.java#L283)):*
> ```Java
> 
>         Assert.assertEquals(3, changes.size());
>         Assert.assertTrue(changes.get(0) instanceof NodeAttachChange);
> ```

Please don't use `Assert.assertTrue(...)` for instanceof checks, since it gives no relevant information on the error log if the test fails.  Use `Assert.assertThat(changes(0), CoreMatchers.instanceOf(NodeAttachChange.class));`.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3771)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-client/src/main/java/com/vaadin/client/flow/nodefeature/NodeList.java, line 150 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3771#-L8gtUmi6ivdFYY-1NIv:-L8kOd630Hml4DL-YJ4_:b-p8c16n) ([raw file](https://github.com/vaadin/flow/blob/a89491a52a36f4b7bb359dcd247a13d0cef24445/flow-client/src/main/java/com/vaadin/client/flow/nodefeature/NodeList.java#L150)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

When is this reset to false?
</blockquote></details>

Never.
Otherwise it's not a state (but this is a part of the state).

You may read my comment about this PR (in discussions).

---

*[flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/NodeListAddRemoveTest.java, line 283 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3771#-L8gsBWL3BFd-tiDLyRC:-L8kOb6j162D6kYnBrTY:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/a89491a52a36f4b7bb359dcd247a13d0cef24445/flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/NodeListAddRemoveTest.java#L283)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Please don't use `Assert.assertTrue(...)` for instanceof checks, since it gives no relevant information on the error log if the test fails.  Use `Assert.assertThat(changes(0), CoreMatchers.instanceOf(NodeAttachChange.class));`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3771)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/NodeListAddRemoveTest.java, line 283 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3771#-L8gsBWL3BFd-tiDLyRC:-L8kP--C9IYioXZHzG49:bfup3gy) ([raw file](https://github.com/vaadin/flow/blob/a89491a52a36f4b7bb359dcd247a13d0cef24445/flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/NodeListAddRemoveTest.java#L283)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The syntax which you are talking about is totally unclear and I'm not able to remember it.
Yes, it's better to write assertion in this way for the test. 
But it's too hard for me to remember it. `assertTrue` is just much easier so every time I will
forget the better approach with ugly syntax and use `assertTrue`. But you may correct me.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3771)*

**Comment by gilberto-torrezan** [comment]
Review status: 8 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-client/src/main/java/com/vaadin/client/flow/nodefeature/NodeList.java, line 150 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3771#-L8gtUmi6ivdFYY-1NIv:-L8kQB_I9gBtHuKgkxXl:b-togyie) ([raw file](https://github.com/vaadin/flow/blob/a89491a52a36f4b7bb359dcd247a13d0cef24445/flow-client/src/main/java/com/vaadin/client/flow/nodefeature/NodeList.java#L150)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Never.
Otherwise it's not a state (but this is a part of the state).

You may read my comment about this PR (in discussions).
</blockquote></details>

Yes, I have seen that, but it doesn't make it clearer for me about the lifecycle of this particular flag. Feels like it would be always cleared after the first `clear` method, everytime the node is bound. Unless the NodeList instance is always recreated from scratch when a new binding is made.

---

*[flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/NodeListAddRemoveTest.java, line 283 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3771#-L8gsBWL3BFd-tiDLyRC:-L8kR_SU7k-jSXbyiPZB:b-pjfneo) ([raw file](https://github.com/vaadin/flow/blob/a89491a52a36f4b7bb359dcd247a13d0cef24445/flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/NodeListAddRemoveTest.java#L283)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

The syntax which you are talking about is totally unclear and I'm not able to remember it.
Yes, it's better to write assertion in this way for the test. 
But it's too hard for me to remember it. `assertTrue` is just much easier so every time I will
forget the better approach with ugly syntax and use `assertTrue`. But you may correct me.
</blockquote></details>

It becomes less ugly (more fluent) when using static import for it: `ssertThat(changes(0), instanceOf(NodeAttachChange.class));.`. But yeah, it took me some time to get used to hamcrest. 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3771)*

**Comment by gilberto-torrezan** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3771)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/NodeListAddRemoveTest.java, line 283 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3771#-L8gsBWL3BFd-tiDLyRC:-L8kTDEr6HKfMddIhPxY:b-qhd9ph) ([raw file](https://github.com/vaadin/flow/blob/a89491a52a36f4b7bb359dcd247a13d0cef24445/flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/NodeListAddRemoveTest.java#L283)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

It becomes less ugly (more fluent) when using static import for it: `ssertThat(changes(0), instanceOf(NodeAttachChange.class));.`. But yeah, it took me some time to get used to hamcrest. 
</blockquote></details>

It doesn't help to remember the string that I need to write.
Every time when I need to use some `boolean` result I have to find an appropriate  `CoreMatchers.xxxxx`. And it's a pain since I don't even remember a name of the class.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3771)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-client/src/main/java/com/vaadin/client/flow/nodefeature/NodeList.java, line 150 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3771#-L8gtUmi6ivdFYY-1NIv:-L8kTpsI6MJObfzkbxbu:b-yl2yq1) ([raw file](https://github.com/vaadin/flow/blob/a89491a52a36f4b7bb359dcd247a13d0cef24445/flow-client/src/main/java/com/vaadin/client/flow/nodefeature/NodeList.java#L150)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Yes, I have seen that, but it doesn't make it clearer for me about the lifecycle of this particular flag. Feels like it would be always cleared after the first `clear` method, everytime the node is bound. Unless the NodeList instance is always recreated from scratch when a new binding is made.
</blockquote></details>

No.
`removeAllChildren` is not really a state.
That's the main issue with the current state of the code ( without this PR).
But the issue is solved via the state.

It's not a state on the server side (and it's bad actually) but there is a way to make it events based on the server side.
But it cannot be done in a reasonable way on the client side.

The state should be _the same_ every time when you try to look at it. In this case it's `NodeList`.
It  should not depend on the time when I check the state.

You implementation just sends an event: clear. 
And if a client of a `NodeList` have not yet register the listener then it misses the event (that exactly what happened) and never knows about "clear"/"remove all".

`hasBeenCleared` is ugly but in this specific case it's enough to know that at some point we requested to remove all children. _In this specific case_ this knowledge is enough. Because if this has happened at some point then we may use this state: all children on the client side should be removed and then we just use the current state of the children from the `NodeList`.
This is possible just because of children semantic. Probably would not have worked in other case.
And this flag should never be cleaned otherwise if you look the first time at the state when it's reset then you never know that clear should have been done.

In reality this flag is used only once: the very first time when you look at the state. Later on you just use the list items and listen the events.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3771)*

**Comment by gilberto-torrezan** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3771#-:-L8kZE3JDTwfREvjI61V:bnfp4nl)*

**Comment by caalador** [comment]
:lgtm:

---

Reviewed 6 of 9 files at r1, 1 of 1 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3771#-:-L8l5cN3BFlPwRMw6RXr:bnfp4nl)*

**Pull request merged**
