### PR TITLE
fix bundle and polyfill paths when servlet not running in root

### PR DESCRIPTION
**Pull request by manolo**
Fixes: #5740

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/5807)

### CODE REVIEW

**Comment by bogdanudrescu** [comment]
I'll start resolving the conflicts.

**Comment by caalador** [comment]
@bogdanudrescu note that there is #5836 that is a continuation of this. So this should probably be left as is.

**Comment by bogdanudrescu** [comment]
@caalador roger that!

**Comment by caalador** [comment]
Closing as issue was fixed in #5836

**Pull request closed without merging**
