### PR TITLE
Properly normalize Vaadin URIs when parsing HTML imports 

### PR DESCRIPTION
**Pull request by Artur-**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3916)

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
Reviewed 4 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[flow-server/src/main/java/com/vaadin/flow/component/internal/HtmlDependencyParser.java, line 140 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3916#-LAO0VpQ3cvuEh7Vk7F5:-LAO0VpQ3cvuEh7Vk7F6:ba1j73r) ([raw file](https://github.com/vaadin/flow/blob/ba085e5ebdca475f46549f5fb5ab581007386f33/flow-server/src/main/java/com/vaadin/flow/component/internal/HtmlDependencyParser.java#L140)):*
> ```Java
>      * @param uri
>      *            the URI to normalize
>      * @return
> ```

Javadoc is incomplete. 

---

*[flow-server/src/main/java/com/vaadin/flow/component/internal/HtmlDependencyParser.java, line 142 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3916#-LAO0MMV6xytQYj2Ga8v:-LAO0MMV6xytQYj2Ga8w:b-6lhc6x) ([raw file](https://github.com/vaadin/flow/blob/ba085e5ebdca475f46549f5fb5ab581007386f33/flow-server/src/main/java/com/vaadin/flow/component/internal/HtmlDependencyParser.java#L142)):*
> ```Java
>      * @return
>      */
>     static String toNormalizedURI(URI uri) {
> ```

`private`?

---

*[flow-server/src/main/java/com/vaadin/flow/component/internal/HtmlDependencyParser.java, line 144 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3916#-LAO1Spq0OxxjFwUDUvi:-LAO1Spq0OxxjFwUDUvj:b-d7ygy4) ([raw file](https://github.com/vaadin/flow/blob/ba085e5ebdca475f46549f5fb5ab581007386f33/flow-server/src/main/java/com/vaadin/flow/component/internal/HtmlDependencyParser.java#L144)):*
> ```Java
>     static String toNormalizedURI(URI uri) {
>         URI normalized = uri.normalize();
>         // This is because of https://github.com/vaadin/flow/issues/3892
> ```

So is the issue fixed by this PR or are there any other changes needed to be done?

---

*[flow-server/src/test/java/com/vaadin/flow/component/internal/HtmlDependencyParserTest.java, line 38 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3916#-LAO36ERB16xwT3rl5xy:-LAO36ERB16xwT3rl5xz:b7rv01x) ([raw file](https://github.com/vaadin/flow/blob/ba085e5ebdca475f46549f5fb5ab581007386f33/flow-server/src/test/java/com/vaadin/flow/component/internal/HtmlDependencyParserTest.java#L38)):*
> ```Java
> public class HtmlDependencyParserTest {
> 
>     private VaadinSession session;
> ```

I see a couple of unused variables here, care to remove those (`session`, `service`)? Most probably unused imports will occur afterwards.

---

*[flow-server/src/test/java/com/vaadin/flow/component/internal/HtmlDependencyParserTest.java, line 158 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3916#-LAO2i68Ep9wAkhl20hn:-LAO2i68Ep9wAkhl20ho:bsrs255) ([raw file](https://github.com/vaadin/flow/blob/ba085e5ebdca475f46549f5fb5ab581007386f33/flow-server/src/test/java/com/vaadin/flow/component/internal/HtmlDependencyParserTest.java#L158)):*
> ```
> frontend://./foo.html
> ```
What about this path? It's mentioned as a special case in the code, but I don't see anything that starts with `frontend://./` in any of the tests. Would it make sense to test it also?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3916)*

**Comment by Artur-** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/component/internal/HtmlDependencyParser.java, line 140 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3916#-LAO0VpQ3cvuEh7Vk7F5:-LAP3C8488jlQrL54bht:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/ba085e5ebdca475f46549f5fb5ab581007386f33/flow-server/src/main/java/com/vaadin/flow/component/internal/HtmlDependencyParser.java#L140)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Javadoc is incomplete. 
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/flow/component/internal/HtmlDependencyParser.java, line 142 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3916#-LAO0MMV6xytQYj2Ga8v:-LAP3BMe5SblfiD_szSr:b-bttoee) ([raw file](https://github.com/vaadin/flow/blob/ba085e5ebdca475f46549f5fb5ab581007386f33/flow-server/src/main/java/com/vaadin/flow/component/internal/HtmlDependencyParser.java#L142)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

`private`?
</blockquote></details>

Added comment

---

*[flow-server/src/main/java/com/vaadin/flow/component/internal/HtmlDependencyParser.java, line 144 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3916#-LAO1Spq0OxxjFwUDUvi:-LAP3CtX08DP1HiABgSQ:b23a01r) ([raw file](https://github.com/vaadin/flow/blob/ba085e5ebdca475f46549f5fb5ab581007386f33/flow-server/src/main/java/com/vaadin/flow/component/internal/HtmlDependencyParser.java#L144)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

So is the issue fixed by this PR or are there any other changes needed to be done?
</blockquote></details>

The fundamental issue is that the protocol is incorrectly defined. Don't think we want to change that now so it is "resolved" by this.

---

*[flow-server/src/test/java/com/vaadin/flow/component/internal/HtmlDependencyParserTest.java, line 38 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3916#-LAO36ERB16xwT3rl5xy:-LAP3dvi0-X6AYSxhaFl:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/ba085e5ebdca475f46549f5fb5ab581007386f33/flow-server/src/test/java/com/vaadin/flow/component/internal/HtmlDependencyParserTest.java#L38)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

I see a couple of unused variables here, care to remove those (`session`, `service`)? Most probably unused imports will occur afterwards.
</blockquote></details>

Done.

---

*[flow-server/src/test/java/com/vaadin/flow/component/internal/HtmlDependencyParserTest.java, line 158 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3916#-LAO2i68Ep9wAkhl20hn:-LAP3lkh9pMoLAdXAoYC:b-xvi3xa) ([raw file](https://github.com/vaadin/flow/blob/ba085e5ebdca475f46549f5fb5ab581007386f33/flow-server/src/test/java/com/vaadin/flow/component/internal/HtmlDependencyParserTest.java#L158)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

> ```
> frontend://./foo.html
> ```
What about this path? It's mentioned as a special case in the code, but I don't see anything that starts with `frontend://./` in any of the tests. Would it make sense to test it also?
</blockquote></details>

It's inndirectly tested through `href='./relative.html'`. Added a couple of cases below also

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3916)*

**Comment by caalador** [comment]
Review status: 2 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[flow-server/src/test/java/com/vaadin/flow/component/internal/HtmlDependencyParserTest.java, line 181 at r3](https://beta.reviewable.io/reviews/vaadin/flow/3916#-LARD7s5E_fv_0iqytjQ:-LARD7s65wrDKY0RCN8P:b8ofpbm) ([raw file](https://github.com/vaadin/flow/blob/966ed2beca41b497c2f2eb1c4fe84865c7f2d094/flow-server/src/test/java/com/vaadin/flow/component/internal/HtmlDependencyParserTest.java#L181)):*
> ```Java
>         assertEquals("http://foo/../bar", normalize("http://foo/../bar"));
>         assertEquals("http://foo/bar", normalize("http://foo/./bar"));
>         assertEquals("http://foo/bar", normalize("http://foo/baz/../bar"));
> ```

Also test with a deeper relative path to have tested the same that bakery has e.g. `src/views/login/../../../bower_components/vaadin-button/src/vaadin-button.html` as per definition it should work, but it should still be tested.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3916)*

**Comment by Artur-** [comment]
Review status: 2 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

*[flow-server/src/test/java/com/vaadin/flow/component/internal/HtmlDependencyParserTest.java, line 181 at r3](https://beta.reviewable.io/reviews/vaadin/flow/3916#-LARD7s5E_fv_0iqytjQ:-LARXBjy3qmzHXp6Bh6M:bb6un1j) ([raw file](https://github.com/vaadin/flow/blob/966ed2beca41b497c2f2eb1c4fe84865c7f2d094/flow-server/src/test/java/com/vaadin/flow/component/internal/HtmlDependencyParserTest.java#L181)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Also test with a deeper relative path to have tested the same that bakery has e.g. `src/views/login/../../../bower_components/vaadin-button/src/vaadin-button.html` as per definition it should work, but it should still be tested.
</blockquote></details>

Done

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3916)*

**Pull request merged**
