### PR TITLE
fix: run setBean validation for changed bindings only (#18735)

### PR DESCRIPTION
**Pull request by tepi**

### CODE REVIEW

**Comment by tepi** [comment]
Once reviewed, needs to be picked to 24.2 and 24.3

**Review by mcollovati — APPROVED** [review]

**Comment by knoobie** [comment]
@tepi @mcollovati This is such a fundamental function, should there be one or multiple tests to verify that it's going to work in the future?

**Comment by mcollovati** [comment]
@knoobie, my bad.
We discussed with Teppo about adding tests, but I mistakenly approved the PR too early, and it got merged.
My apologies.
We will add necessary tests in a new PR.

**Comment by knoobie** [comment]
Don't worry, just wanted to mention it cause all my application rely on this 😬

**Pull request merged**
