### PR TITLE
chore!: Remove the themeModule concept

### PR DESCRIPTION
**Pull request by Artur-**
When splitting code into multiple chunks, there is no way to guarantee that some modules are globally loaded before others

### CODE REVIEW

**Comment by Artur-** [comment]
This probably requires https://github.com/vaadin/web-components/pull/5752 first so that Material styles are also put first in `<head>`. Then we can simplify but not considering some modules "special" in some way, which is problematic in the long run, e.g. when code splitting

**Comment by caalador** [comment]
Will this/chunks have an impact to theme vs `@CssImport`/`@StyleSheet` load order in views?

**Comment by Artur-** [comment]
All tests pass so surely not :)

**Comment by Artur-** [comment]
As I understand it, the feature is used to ensure that annotations on `Lumo` or `Material` end up as imports before other imports in `generated-flow-imports.js`. With the changes for Lumo already done and the changes for Material done in https://github.com/vaadin/web-components/pull/5752, it no longer matters at which point they are imported, because the global styles are always added in the beginning of `<head>`

**Comment by caalador** [comment]
Not all tests seem to pass =P
```

Error:  Failures: 
Error:    FrontendDependenciesTest.annotationsInRouterLayoutWontBeFlaggedAsBelongingToTheme:263 Theme's annotations should come first expected:<[theme-foo].js> but was:<[@vaadin/common-frontend/ConnectionIndicator].js>
Error:    ScannerThemeTest.should_takeThemeFromLayout_ifLayoutAlreadyVisited:190 expected:<com.vaadin.flow.server.frontend.scanner.ScannerTestComponents$Theme1> but was:<null>
Error:    ScannerThemeTest.should_visitDefaultTheme_when_noThemeAnnotationIsGiven:137 Theme4 should have been visited and JsModule collected
```

**Comment by Artur-** [comment]
Yes, I was talking about the integration tests that validate that apps still work. The unit tests test that the code works the old way except for maybe the last that is still a problem

**Comment by Artur-** [comment]
Fixed the tests. As the theme of an entrypoint is only used to get the application theme, it does not seem fruitful to test it in `should_visitDefaultTheme_when_noThemeAnnotationIsGiven`

**Comment by Artur-** [comment]
Rebased... hope it is still the same code

**Review by caalador — APPROVED** [review]

**Review by caalador — APPROVED** [review]

**Pull request merged**
