### PR TITLE
Move TabbedComponentDemoTest to demo-helpers

### PR DESCRIPTION
**Pull request by pekam**
TabbedComponentDemoTest existed only in demo-flow-components, so I migrated it to flow-component-demo-helpers. This is needed by Grid's integrations tests in it's own repository.
Original class was not removed, as it's slightly different and needed by the original components-demo, which will be nuked at some point anyway.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/2985)

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2985#-KzPQcJa9UlsE4gqyHr0:-KzPQcJa9UlsE4gqyHr1:b7g2a2t) (no related file):*
Can you elaborate why is this needed at all?
I see only one usage of it: https://reviewable.io/reviews/vaadin/vaadin-grid-flow/2#-

And this usage is just usual test that needs one method from all the changes? 
Would it be easier to create a bit more abstract method in `TestBenchHelpers` (which is available in both projects, afaik) and use it?

---

*[flow-components-parent/flow-component-demo-helpers/src/main/java/com/vaadin/flow/demo/ComponentDemoTest.java, line 59 at r2](https://reviewable.io:443/reviews/vaadin/flow/2985#-KzPLfH8vhAxAoKjO218:-KzPLfH8vhAxAoKjO219:b-noof2j) ([raw file](https://github.com/vaadin/flow/blob/9971951b12e6b20481d3a4db8200ebb079b9a473/flow-components-parent/flow-component-demo-helpers/src/main/java/com/vaadin/flow/demo/ComponentDemoTest.java#L59)):*
> ```Java
>     }
> 
>     protected Stream<LogEntry> getLogEntries(Level level) {
> ```

Do you intend to use it somewhere else?

Then I propose to move the method into `TestBenchHelpers` from this module.

Also, a javadoc won't hurt in this case or at least a different name would be helpful: it's rather difficult to understand what the method does just by looking at its signature.
It was not really an issue before, since it was `private`, but now it is.

Also, is it wise to return `Stream` here? Once read, it cannot be reread, that may be inconvenient.

---

*[flow-components-parent/flow-component-demo-helpers/src/main/java/com/vaadin/flow/demo/TabbedComponentDemoTest.java, line 39 at r2](https://reviewable.io:443/reviews/vaadin/flow/2985#-KzPROcwpNRf7ALbpT_V:-KzPROcwpNRf7ALbpT_W:b-uxk9sx) ([raw file](https://github.com/vaadin/flow/blob/9971951b12e6b20481d3a4db8200ebb079b9a473/flow-components-parent/flow-component-demo-helpers/src/main/java/com/vaadin/flow/demo/TabbedComponentDemoTest.java#L39)):*
> ```Java
>      *            the name of the tab to navigate to
>      */
>     public void openDemoPageAndCheckForErrors(String tab) {
> ```

I am a bit lost here: why do you need to put one file into `src`, the other into `test` since they do more or less the same?

Do you need this method somewhere? Can you put it into existing utility class like `TestBenchHelpers`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2985)*

**Comment by caalador** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2985#-KzPQcJa9UlsE4gqyHr0:-KzSEGt2dgYFZi5rYhM2:b-yh3xbb) (no related file):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Can you elaborate why is this needed at all?
I see only one usage of it: https://reviewable.io/reviews/vaadin/vaadin-grid-flow/2#-

And this usage is just usual test that needs one method from all the changes? 
Would it be easier to create a bit more abstract method in `TestBenchHelpers` (which is available in both projects, afaik) and use it?
</blockquote></details>

I could agree with moving these helpers to TestBenchHelpers or to Grid if it is the only one using the functionality.

Also it is fine to nuke the original and killing the components-demo tests if we are not going to keep them anyway.
If you want to have some tests that check Grid for each Flow build add them to `flow-tests/test-components`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2985)*

**Comment by pekam** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2985#-KzPQcJa9UlsE4gqyHr0:-KzSbYJt1FqAKjA0LOuB:b8nsp77) (no related file):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

I could agree with moving these helpers to TestBenchHelpers or to Grid if it is the only one using the functionality.

Also it is fine to nuke the original and killing the components-demo tests if we are not going to keep them anyway.
If you want to have some tests that check Grid for each Flow build add them to `flow-tests/test-components`
</blockquote></details>

Splitting component demos into multiple tabs is something we want to support for other components also, even though currently only `Grid` is using it.

I moved the methods for checking browser logs to `TestBenchHelpers` but otherwise I think this code is specific for our component demo tests, so they should be in `flow-component-demo-helpers`.

About removing the stuff from `demo-flow-components`: I suggest doing that after `Grid` is published as it's own module, at the same time when we can remove all the `Grid` code from Flow repo.

---

*[flow-components-parent/flow-component-demo-helpers/src/main/java/com/vaadin/flow/demo/ComponentDemoTest.java, line 59 at r2](https://reviewable.io:443/reviews/vaadin/flow/2985#-KzPLfH8vhAxAoKjO218:-KzSeeJfmIuj4tGCEAII:bb7f2mf) ([raw file](https://github.com/vaadin/flow/blob/9971951b12e6b20481d3a4db8200ebb079b9a473/flow-components-parent/flow-component-demo-helpers/src/main/java/com/vaadin/flow/demo/ComponentDemoTest.java#L59)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Do you intend to use it somewhere else?

Then I propose to move the method into `TestBenchHelpers` from this module.

Also, a javadoc won't hurt in this case or at least a different name would be helpful: it's rather difficult to understand what the method does just by looking at its signature.
It was not really an issue before, since it was `private`, but now it is.

Also, is it wise to return `Stream` here? Once read, it cannot be reread, that may be inconvenient.
</blockquote></details>

done

---

*[flow-components-parent/flow-component-demo-helpers/src/main/java/com/vaadin/flow/demo/TabbedComponentDemoTest.java, line 39 at r2](https://reviewable.io:443/reviews/vaadin/flow/2985#-KzPROcwpNRf7ALbpT_V:-KzSe0qc3IyLJxcqBUu2:b58fjk0) ([raw file](https://github.com/vaadin/flow/blob/9971951b12e6b20481d3a4db8200ebb079b9a473/flow-components-parent/flow-component-demo-helpers/src/main/java/com/vaadin/flow/demo/TabbedComponentDemoTest.java#L39)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

I am a bit lost here: why do you need to put one file into `src`, the other into `test` since they do more or less the same?

Do you need this method somewhere? Can you put it into existing utility class like `TestBenchHelpers`?
</blockquote></details>

This method is specific to our tabbed component demos. For example, it assumes that the main-component is a `div`.

I'm not sure I understand your first question (one into src, other into test?). Probably covered by the answer above?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2985)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 6 of 6 files at r3.
Review status: 5 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-components-parent/flow-component-demo-helpers/src/main/java/com/vaadin/flow/demo/TabbedComponentDemoTest.java, line 39 at r2](https://reviewable.io:443/reviews/vaadin/flow/2985#-KzPROcwpNRf7ALbpT_V:-KzSewA9_3_WuAFOspOW:b-q5l4f0) ([raw file](https://github.com/vaadin/flow/blob/9971951b12e6b20481d3a4db8200ebb079b9a473/flow-components-parent/flow-component-demo-helpers/src/main/java/com/vaadin/flow/demo/TabbedComponentDemoTest.java#L39)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

This method is specific to our tabbed component demos. For example, it assumes that the main-component is a `div`.

I'm not sure I understand your first question (one into src, other into test?). Probably covered by the answer above?
</blockquote></details>

I think I got it now, but fix me, if I'm mistaken: there are two almost identical sets of files: one is in `demo-flow-components/src/test`, the other is in `flow-component-demo-helpers/src/main` and both of them contain `ComponentDemoTest` and `TabbedComponentDemoTest`. 
And we plan to remove `demo-flow-components/src/test` later, right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2985)*

**Comment by SomeoneToIgnore** [comment]
*[flow-components-parent/flow-component-demo-helpers/src/main/java/com/vaadin/flow/demo/TabbedComponentDemoTest.java, line 28 at r4](https://reviewable.io:443/reviews/vaadin/flow/2985#-KzSfxW736SvFoc8glYU:-KzSfxW736SvFoc8glYV:bpwrvjs) ([raw file](https://github.com/vaadin/flow/blob/f6de5d53071cc0de4a5ce9145099ee4c75fd1dc4/flow-components-parent/flow-component-demo-helpers/src/main/java/com/vaadin/flow/demo/TabbedComponentDemoTest.java#L28)):*
> ```Java
>     @Override
>     public void openDemoPageAndCheckForErrors() {
>         // NO-OP
> ```

Ok, last thing that concerns me is this: why do you need to extend `ComponentDemoTest` and omit its only method?
Can you just directly extend `ChromeBrowserTest`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2985)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2985)*

**Comment by pekam** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-components-parent/flow-component-demo-helpers/src/main/java/com/vaadin/flow/demo/TabbedComponentDemoTest.java, line 39 at r2](https://reviewable.io:443/reviews/vaadin/flow/2985#-KzPROcwpNRf7ALbpT_V:-KzSg5GUjs5IcvVkLWj3:b8frpz3) ([raw file](https://github.com/vaadin/flow/blob/9971951b12e6b20481d3a4db8200ebb079b9a473/flow-components-parent/flow-component-demo-helpers/src/main/java/com/vaadin/flow/demo/TabbedComponentDemoTest.java#L39)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

I think I got it now, but fix me, if I'm mistaken: there are two almost identical sets of files: one is in `demo-flow-components/src/test`, the other is in `flow-component-demo-helpers/src/main` and both of them contain `ComponentDemoTest` and `TabbedComponentDemoTest`. 
And we plan to remove `demo-flow-components/src/test` later, right?
</blockquote></details>

Yes. This is basically just about moving the components to their own modules. They get all these helper classes by depending on `flow-component-demo-helpers` so we need to move them there. And once all the demos and ITs are in the individual component modules, we can remove them from  `demo-flow-components`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2985)*

**Comment by SomeoneToIgnore** [comment]
*[flow-components-parent/flow-component-demo-helpers/src/main/java/com/vaadin/flow/demo/TabbedComponentDemoTest.java, line 39 at r2](https://reviewable.io:443/reviews/vaadin/flow/2985#-KzPROcwpNRf7ALbpT_V:-KzSggUhewXv3iQUxu8K:b-83sjo4) ([raw file](https://github.com/vaadin/flow/blob/9971951b12e6b20481d3a4db8200ebb079b9a473/flow-components-parent/flow-component-demo-helpers/src/main/java/com/vaadin/flow/demo/TabbedComponentDemoTest.java#L39)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

Yes. This is basically just about moving the components to their own modules. They get all these helper classes by depending on `flow-component-demo-helpers` so we need to move them there. And once all the demos and ITs are in the individual component modules, we can remove them from  `demo-flow-components`
</blockquote></details>

Nice.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2985)*

**Comment by SomeoneToIgnore** [comment]
*[flow-components-parent/flow-component-demo-helpers/src/main/java/com/vaadin/flow/demo/TabbedComponentDemoTest.java, line 28 at r4](https://reviewable.io:443/reviews/vaadin/flow/2985#-KzSfxW736SvFoc8glYU:-KzSgYx5F6_QIllB_F4w:b10mcx1) ([raw file](https://github.com/vaadin/flow/blob/f6de5d53071cc0de4a5ce9145099ee4c75fd1dc4/flow-components-parent/flow-component-demo-helpers/src/main/java/com/vaadin/flow/demo/TabbedComponentDemoTest.java#L28)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Ok, last thing that concerns me is this: why do you need to extend `ComponentDemoTest` and omit its only method?
Can you just directly extend `ChromeBrowserTest`?
</blockquote></details>

I know that it requires to add `layout` field in this class, but this is relatively small and you duplicate the logic that works with it anyway, so I don't see any profit of extending `ComponentDemoTest`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2985)*

**Comment by SomeoneToIgnore** [comment]
*[flow-components-parent/flow-component-demo-helpers/src/main/java/com/vaadin/flow/demo/TabbedComponentDemoTest.java, line 28 at r4](https://reviewable.io:443/reviews/vaadin/flow/2985#-KzSfxW736SvFoc8glYU:-KzShpAQm-Nme03ZOlz4:bgazbxw) ([raw file](https://github.com/vaadin/flow/blob/f6de5d53071cc0de4a5ce9145099ee4c75fd1dc4/flow-components-parent/flow-component-demo-helpers/src/main/java/com/vaadin/flow/demo/TabbedComponentDemoTest.java#L28)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

I know that it requires to add `layout` field in this class, but this is relatively small and you duplicate the logic that works with it anyway, so I don't see any profit of extending `ComponentDemoTest`
</blockquote></details>

But it's up to you.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2985)*

**Pull request merged**
