### PR TITLE
Add demo-helpers and a super-pom for components

### PR DESCRIPTION
**Pull request by pekam**
We are separating Flow components into their own modules, and they need some common helper-classes and maven configuration. For this reason, two new modules are added under `flow-components-parent`:
 1. `flow-component-demo-helpers` that contains classes for running a jetty demo-server and base-classes and resources for creating the demo-views. The views are copied from `demo-flow-components` and include for example adding those source code snippets.
 2. `flow-component` that is just a pom containing common configuration for individual component modules. It includes for example the build configuration for copying static resources and source codes so they can be shown in the demo.

This allows pom-files of individual components to become very small, as they only need to specify webjar-dependencies needed by the particular component.

This doesn't include unit and integration tests yet. A separate ticket will be created.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/2762)

### CODE REVIEW

**Comment by ahie** [comment]
Reviewed 14 of 15 files at r1.
Review status: 14 of 15 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2762)*

**Comment by ahie** [comment]
Review status: 14 of 15 files reviewed at latest revision, 28 unresolved discussions, some commit checks broke.

---

*[flow-components-parent/flow-component-demo-helpers/src/main/java/com/vaadin/flow/demo/ComponentDemoServer.java, line 58 at r1](https://reviewable.io:443/reviews/vaadin/flow/2762#-KxDLlGUTlaCWgql4gWX-r1-58:-KxDSU6wm8hNIBdp1609:b-pwm470) ([raw file](https://github.com/vaadin/flow/blob/24f9807424f0d999ea731bf6c415ae1a1fa0fe01/flow-components-parent/flow-component-demo-helpers/src/main/java/com/vaadin/flow/demo/ComponentDemoServer.java#L58)):*
<details><summary><i>Previously, vaadin-bot (Vaadin Bot) wrote…</i></summary><blockquote>

MAJOR Close this "ServerConnector". [rule](https://sonar.projects.vaadin.com/coding_rules#rule_key=squid%3AS2095)
</blockquote></details>

I guess `org.eclipse.jetty.server.Server` does this for you?

---

*[flow-components-parent/flow-component-demo-helpers/src/main/java/com/vaadin/flow/demo/ComponentDemoServer.java, line 70 at r1](https://reviewable.io:443/reviews/vaadin/flow/2762#-KxDLlGUTlaCWgql4gWX-r1-70:-KxDTEARmuuGmy4N9x0Z:b1cyl4q) ([raw file](https://github.com/vaadin/flow/blob/24f9807424f0d999ea731bf6c415ae1a1fa0fe01/flow-components-parent/flow-component-demo-helpers/src/main/java/com/vaadin/flow/demo/ComponentDemoServer.java#L70)):*
<details><summary><i>Previously, vaadin-bot (Vaadin Bot) wrote…</i></summary><blockquote>

MAJOR Exceptional return value of java.io.File.mkdirs() ignored in com.vaadin.flow.demo.ComponentDemoServer.startServer() [rule](https://sonar.projects.vaadin.com/coding_rules#rule_key=findbugs%3ARV_RETURN_VALUE_IGNORED_BAD_PRACTICE)
</blockquote></details>

Could check the return value/possible security exception and rethrow?

---

*[flow-components-parent/flow-component-demo-helpers/src/main/java/com/vaadin/flow/demo/ComponentDemoServer.java, line 118 at r1](https://reviewable.io:443/reviews/vaadin/flow/2762#-KxDLlGUTlaCWgql4gWX-r1-118:-KxDSNT3Yt1Oi5Kwpi-X:bqlspte) ([raw file](https://github.com/vaadin/flow/blob/24f9807424f0d999ea731bf6c415ae1a1fa0fe01/flow-components-parent/flow-component-demo-helpers/src/main/java/com/vaadin/flow/demo/ComponentDemoServer.java#L118)):*
<details><summary><i>Previously, vaadin-bot (Vaadin Bot) wrote…</i></summary><blockquote>

CRITICAL Add a nested comment explaining why this method is empty, throw an UnsupportedOperationException or complete the implementation. [rule](https://sonar.projects.vaadin.com/coding_rules#rule_key=squid%3AS1186)
</blockquote></details>

Please do.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2762)*

**Comment by pekam** [comment]
Review status: 14 of 15 files reviewed at latest revision, 28 unresolved discussions, some commit checks broke.

---

*[flow-components-parent/flow-component-demo-helpers/src/main/java/com/vaadin/flow/demo/ComponentDemoServer.java, line 58 at r1](https://reviewable.io:443/reviews/vaadin/flow/2762#-KxDLlGUTlaCWgql4gWX-r1-58:-KxEezgZTzgZX5YL3Dbd:bp9b0gn) ([raw file](https://github.com/vaadin/flow/blob/24f9807424f0d999ea731bf6c415ae1a1fa0fe01/flow-components-parent/flow-component-demo-helpers/src/main/java/com/vaadin/flow/demo/ComponentDemoServer.java#L58)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

I guess `org.eclipse.jetty.server.Server` does this for you?
</blockquote></details>

I would think so. At least in Eclipse's own similar examples the connector is not manually closed (https://www.eclipse.org/jetty/documentation/9.4.x/embedded-examples.html)

---

*[flow-components-parent/flow-component-demo-helpers/src/main/java/com/vaadin/flow/demo/ComponentDemoServer.java, line 70 at r1](https://reviewable.io:443/reviews/vaadin/flow/2762#-KxDLlGUTlaCWgql4gWX-r1-70:-KxEfVcbsA6UyAz-lDWK:b-cd8boy) ([raw file](https://github.com/vaadin/flow/blob/24f9807424f0d999ea731bf6c415ae1a1fa0fe01/flow-components-parent/flow-component-demo-helpers/src/main/java/com/vaadin/flow/demo/ComponentDemoServer.java#L70)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

Could check the return value/possible security exception and rethrow?
</blockquote></details>

I'm not sure how to rethrow properly. I threw a new exception with my own message. Is this what you mean?

---

*[flow-components-parent/flow-component-demo-helpers/src/main/java/com/vaadin/flow/demo/ComponentDemoServer.java, line 118 at r1](https://reviewable.io:443/reviews/vaadin/flow/2762#-KxDLlGUTlaCWgql4gWX-r1-118:-KxEgAlNiT4bC9ET1GbE:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/24f9807424f0d999ea731bf6c415ae1a1fa0fe01/flow-components-parent/flow-component-demo-helpers/src/main/java/com/vaadin/flow/demo/ComponentDemoServer.java#L118)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

Please do.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2762)*

**Comment by ahie** [comment]
Review status: 13 of 15 files reviewed at latest revision, 29 unresolved discussions, some commit checks failed.

---

*[flow-components-parent/flow-component-demo-helpers/src/main/java/com/vaadin/flow/demo/ComponentDemoServer.java, line 70 at r1](https://reviewable.io:443/reviews/vaadin/flow/2762#-KxDLlGUTlaCWgql4gWX-r1-70:-KxHAmDA44KCJctZYA0q:b291sby) ([raw file](https://github.com/vaadin/flow/blob/24f9807424f0d999ea731bf6c415ae1a1fa0fe01/flow-components-parent/flow-component-demo-helpers/src/main/java/com/vaadin/flow/demo/ComponentDemoServer.java#L70)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

I'm not sure how to rethrow properly. I threw a new exception with my own message. Is this what you mean?
</blockquote></details>

Could still check the return value of `mkdirs` and throw if it is not true. From the javadocs of mkdirs:

```
<code>true</code> if and only if the directory was created,
along with all necessary parent directories; <code>false</code>
otherwise
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2762)*

**Comment by pekam** [comment]
Review status: 13 of 15 files reviewed at latest revision, 29 unresolved discussions.

---

*[flow-components-parent/flow-component-demo-helpers/src/main/java/com/vaadin/flow/demo/ComponentDemoServer.java, line 70 at r1](https://reviewable.io:443/reviews/vaadin/flow/2762#-KxDLlGUTlaCWgql4gWX-r1-70:-KxHxntRw6Ao5yLDUXgy:bb7f2mf) ([raw file](https://github.com/vaadin/flow/blob/24f9807424f0d999ea731bf6c415ae1a1fa0fe01/flow-components-parent/flow-component-demo-helpers/src/main/java/com/vaadin/flow/demo/ComponentDemoServer.java#L70)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

Could still check the return value of `mkdirs` and throw if it is not true. From the javadocs of mkdirs:

```
<code>true</code> if and only if the directory was created,
along with all necessary parent directories; <code>false</code>
otherwise
```
</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2762)*

**Comment by ahie** [comment]
Reviewed 1 of 1 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 29 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2762)*

**Pull request merged**
