### PR TITLE
There is a chance that the Uri resolvers adds /. to the resolvedUrl

### PR DESCRIPTION
**Pull request by caalador**
This makes it so that the webJar resolver doesn't find the files.

This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3466)

### CODE REVIEW

**Comment by Legioth** [comment]
This looks like fixing the symptom instead of fixing the root cause. Also, the test coverage could be more rigorous...

**Comment by caalador** [comment]
The issue is that the context root url is added which comes from `getContextRootUrl()` and is 99% of the time /.

**Comment by denis-anisimov** [comment]
Reviewed 1 of 2 files at r2.
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3466#-L4K6ihqlJVFUggDBazS:-L4K6ihqlJVFUggDBazT:b-1zip6f) (no related file):*
Unit tests ?

---

*[flow-server/src/main/java/com/vaadin/flow/server/webjar/WebJarServer.java, line 183 at r2](https://reviewable.io:443/reviews/vaadin/flow/3466#-L4K6DrMX8WzFgfepsJb:-L4K6DrMX8WzFgfepsJc:b-163mx2) ([raw file](https://github.com/vaadin/flow/blob/e5d2881d343e8f32be1bd537bb503d85ee7cb37e/flow-server/src/main/java/com/vaadin/flow/server/webjar/WebJarServer.java#L183)):*
> Pattern.compile("([/.]?[/..]*)" + prefix)

Is it supposed to be at the beginning of the line only ?
Meaning shouldn't the patten start with "^" ?

Also there is no sense to compile the pattern each time when the method is called. Compilation is quite expensive operation which can be done only once in this case.
So please extract `Pattern` instance into a field and initialize it once `prefix` is initialized.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3466)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3466)*

**Comment by caalador** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3466#-L4K6ihqlJVFUggDBazS:-L4Kjrty90-MoMTVazSs:bqmjwcz) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Unit tests ?
</blockquote></details>

Added.

---

*[flow-server/src/main/java/com/vaadin/flow/server/webjar/WebJarServer.java, line 183 at r2](https://reviewable.io:443/reviews/vaadin/flow/3466#-L4K6DrMX8WzFgfepsJb:-L4Kjt8sWvu7rzUMVn3T:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/e5d2881d343e8f32be1bd537bb503d85ee7cb37e/flow-server/src/main/java/com/vaadin/flow/server/webjar/WebJarServer.java#L183)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> Pattern.compile("([/.]?[/..]*)" + prefix)

Is it supposed to be at the beginning of the line only ?
Meaning shouldn't the patten start with "^" ?

Also there is no sense to compile the pattern each time when the method is called. Compilation is quite expensive operation which can be done only once in this case.
So please extract `Pattern` instance into a field and initialize it once `prefix` is initialized.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3466)*

**Comment by denis-anisimov** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3466)*

**Pull request merged**
