### PR TITLE
Remove webjars-bom

### LINKED ISSUE #3236: Kill webjars-bom when stable elements are available
Clone https://github.com/vaadin/platform/ got to `vaadin` directory and run `mvn dependency:tree`

Expected: all dependencies are stable and won't change unpredictably
Actual: `vaadin-upload-flow` webjar dependencies are not fixed:
screen shot 2018-01-02 at 16 58 47

This is bad, since it means that users won't be able to have a stable builds: any minor updates will be picked up automatically.

We should also think of the way of automatically testing this on/after each flow snapshot run.

### PR DESCRIPTION
**Pull request by denis-anisimov**
Fixes #3236

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3956)

### CODE REVIEW

**Comment by ZheSun88** [comment]
Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/flow/3956#-LAXprNP78fR7UmPhEmb:-LAXprNP78fR7UmPhEmc:blgkljl) (no related file):*
There still are some web-components which haven't been released by the componet team

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3956)*

**Comment by ZheSun88** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/flow/3956#-LAXprNP78fR7UmPhEmb:-LAY4iDR5_yvqzPJ_TVw:br2f7v0) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

https://github.com/vaadin/flow/issues/3236#issuecomment-382621856

The question is still valid.
</blockquote></details>

indeed.. we don't need to wait for the component team any more, as the versions in the bom are stable already. 
but one thing is that we might need to move the lumo dependency to the `flow-theme-integrations`.. and maybe you also need to modify the build configuration? 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3956)*

**Comment by denis-anisimov** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/flow/3956#-LAXprNP78fR7UmPhEmb:-LAl2N7pCFcyXGsohI6I:bhz0uy2) (no related file):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

indeed.. we don't need to wait for the component team any more, as the versions in the bom are stable already. 
but one thing is that we might need to move the lumo dependency to the `flow-theme-integrations`.. and maybe you also need to modify the build configuration? 
</blockquote></details>

I definitely need. The question is at which point it needs to be changed: before the review or after....
I will update it now.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3956)*

**Comment by denis-anisimov** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/flow/3956#-LAXprNP78fR7UmPhEmb:-LAl2zphDQX-9MuU814y:b-896fix) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

I definitely need. The question is at which point it needs to be changed: before the review or after....
I will update it now.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3956)*

**Comment by ZheSun88** [comment]
Reviewed 1 of 2 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/flow/3956#-LAXprNP78fR7UmPhEmb:-LAlIzTm6WCbAwQZ_aN2:buvay0p) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I will resolve the comment now.. 
But by the way, is fixing the `flow-component-base` also part of this issue? because it is using the `webjars-bom` also

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3956)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/flow/3956#-LAXprNP78fR7UmPhEmb:-LAlKMB_Db41zOb9GYs2:b-inbei7) (no related file):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

I will resolve the comment now.. 
But by the way, is fixing the `flow-component-base` also part of this issue? because it is using the `webjars-bom` also
</blockquote></details>

Should be part of the ticket but it's not a part of this PR since it's a different project.
I will make a PR for it, thanks.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3956)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/flow/3956#-LAXprNP78fR7UmPhEmb:-LAlKZ3M86GGQnHCU72f:brupvxr) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Should be part of the ticket but it's not a part of this PR since it's a different project.
I will make a PR for it, thanks.
</blockquote></details>

By the way the comment is not resolved and there is not lgtm.
I still cannot merge this.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3956)*

**Comment by ZheSun88** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/flow/3956#-LAXprNP78fR7UmPhEmb:-LAlK_ct-BbuOk0jm4sx:b-a3gos3) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

By the way the comment is not resolved and there is not lgtm.
I still cannot merge this.
</blockquote></details>

okay, i will resolve the comment. thanks

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3956#-:-LAlKvQY3Jgf26eZjOVu:bnfp4nl)*

**Pull request merged**
