### PR TITLE
Move TypeScript client code to separate npm packages 

### LINKED ISSUE #10898: Fusion: move Fusion client-side code to an npm package
Currently, the Fusion client-side code (`Connect.ts`, `Authentication.ts` and `form/`)is under the flow-client module, would be good to move them into an npm package e.g. `fusion-client`, like the [connect-client](https://www.npmjs.com/package/connect-client), so that a Flow user could exclude it from their application.

Note, both Fusion and Flow depend on the connection indicator, we need to separate that into a different npm package as well.

### LINKED ISSUE #10901: Fusion: move Fusion Flow shared client-side code into an npm package
The connection indicator and devmode gizmo are  used by both Fusion and Flow, there is a plan to [move fusion client-side code into an npm package](https://github.com/vaadin/flow/issues/10898), for that to work, we need to move the connection indicator (`ConnectionState.ts` and `ConnectionIndicator.ts`) which will be used by both Fusion and Flow.

### PR DESCRIPTION
**Pull request by Lodin**
Creates two npm packages that will be used as dependencies in both Flow and Fusion:

- `@vaadin/client-commons` - this package contains common client code shared by Flow and Fusion.
- `@vaadin/client-fusion` - this package contains Fusion-specific client code

Resolves #10901 
Resolves #10898

### CODE REVIEW

**Comment by joheriks** [comment]
Two divergent versions of `ConnectionState.ts` and `ConnectionIndicator.ts`. E.g. the former:
https://github.com/vaadin/flow/blob/feat/fusion/npm-client/flow-client/src/main/frontend/ConnectionState.ts
https://github.com/vaadin/flow/blob/feat/fusion/npm-client/client/packages/client-common/src/ConnectionState.ts
Could this be somehow avoided?

**Comment by Lodin** [comment]
@joheriks, yes, the first one should be removed eventually. But I guess I cannot do it right now before the packages are published to npm because it will break the flow-client. I think it should be the next step after publishing packages to npm where we remove the old versions and add the new ones from npm.

**Comment by joheriks** [comment]
> @joheriks, yes, the first one should be removed eventually. But I guess I cannot do it right now before the packages are published to npm because it will break the flow-client. I think it should be the next step after publishing packages to npm where we remove the old versions and add the new ones from npm.

Right. Would be good to add a deprecation notice to the top of the `flow-client` files to avoid accidental divergence of the files.

**Comment by vicb** [comment]
Sorry I have been lazy and didn't check all the changes in this PR.

My question is: would the form component be releases as a standalone package ?

I have discussed that with @vlukashov before (see https://github.com/vaadin/flow/issues/9378) and it would be awesome.

As of today I am using the forms in my client side app with my own custom node server on the backend. There are very few things that I had to change for this to work. The form package is great and I think would be very valuable for the JS/TS community in general.

Thanks

**Comment by haijian-vaadin** [comment]
Hi @vicb, thanks a lot for the feedback, it's really great to hear that you like the form package.

For now, we don't plan to publish the form as a separate package yet. We could do it one day once we have a clear picture of what to do with it as a product.

ping our new PO @gilberto-torrezan.

**Review by haijian-vaadin — CHANGES_REQUESTED** [review]
According to https://github.com/vaadin/fusion/issues/28, it needs sth more to manage the versions.

**Review by haijian-vaadin — DISMISSED** [review]

**Comment by haijian-vaadin** [comment]
> According to [vaadin/fusion#28](https://github.com/vaadin/fusion/issues/28), it needs sth more to manage the versions.

As agreed in the sprint planning session, we can do  [vaadin/fusion#28](https://github.com/vaadin/fusion/issues/28) in a separate PR. So removed my request change. Up to @platosha and @Haprog to check if the code in this PR is fine.

**Review by platosha — CHANGES_REQUESTED** [review]

**Review by platosha — APPROVED** [review]

**Review by platosha — APPROVED** [review]

**Comment by haijian-vaadin** [comment]
ping @vicb, @vaadin/form is finally published as a separate package at `https://www.npmjs.com/package/@vaadin/form`.

**Comment by vicb** [comment]
Thanks a lot @haijian-vaadin !

I love this form framework, simple but feature packed and powerful.

Out of curiosity, is there a plan to decouple it from the vaadin backend ? (i.e. I had to remove a dependency on the DOM to be able to run the validators on a nodejs server)

**Pull request merged**
