### PR TITLE
fix: Redirect to login page without showing the 404 page

### LINKED ISSUE #14520: ViewAccessChecker causes the NotFoundException to flash before redirecting to the login view
### Description of the bug

When an application uses a non-Flow view as the login view the "not found" error view is briefly shown before the user is redirected to the actual login view. The reason is the following logic in the view access checker
```
// Prevent the view from being created
beforeEnterEvent.rerouteToError(NotFoundException.class);

if (loginUrl != null) {
    beforeEnterEvent.getUI().getPage().setLocation(loginUrl);
}
```

Rerouting takes place because the target view instance should not be created nor rendered when the user does not have access. Then the `beforeEnterEvent.getUI().getPage().setLocation(loginUrl);` redirect is only executed after the error view has been rendered, causing it to be briefly shown.

### Expected behavior

The error view should not at all be visible during redirection to the login view.

A potential solution would be #11029 and implementing a `forwardToUrl` in the before enter event so the code could be like
```
if (loginUrl != null) {
    beforeEnterEvent.forwardToUrl(loginUrl); // This must also prevent the view from being created
} else {
    beforeEnterEvent.rerouteToError(NotFoundException.class);
}
```

### Minimal reproducible example

See https://github.com/vaadin/flow/issues/14253#issuecomment-1212577437 for an oauth app where this is clearly visible

### Versions

- Vaadin / Flow version: 23.2.0

### PR DESCRIPTION
**Pull request by Artur-**
Fixes #14520

### CODE REVIEW

**Comment by Artur-** [comment]
Based on #14571

**Comment by Artur-** [comment]
Why does it reload infinitely? Sounds like access is denied to the login page?

**Comment by mcollovati** [comment]
I have the same issue also with 23.2.1, so it seems not related to the change in this PR

**Comment by mcollovati** [comment]
As @Artur- pointed out, reload was because of my configuration mistake on test application.
Redirect works as expected and "not found" page is not shown

**Review by mcollovati — APPROVED** [review]

**Pull request merged**
