### PR TITLE
Use generic interface, not implementation

### PR DESCRIPTION
**Pull request by asashour**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/2981)

### CODE REVIEW

**Comment by asashour** [comment]
Will Flow continue to depend on GWT, or this dependency will be removed later?

I am asking this, in order to add Source Code test case, to prevent using Interfaces for client code.

**Comment by SomeoneToIgnore** [comment]
Review status: 0 of 38 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2981#-KzPNvjwJ3MNSejyzu0_:-KzPNvjwJ3MNSejyzu0a:bogg2v2) (no related file):*
One of the reasons implementations are used is the serialization: the interfaces are not serializable, some implementations are. Is this considered in the pull request?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2981)*

**Comment by asashour** [comment]
Review status: 0 of 38 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2981#-KzPNvjwJ3MNSejyzu0_:-KzPOfRYBJ_dIXkQER4S:btbqoq7) (no related file):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

One of the reasons implementations are used is the serialization: the interfaces are not serializable, some implementations are. Is this considered in the pull request?
</blockquote></details>

They were detected by `sonar` and were reverted.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2981)*

**Comment by SomeoneToIgnore** [comment]
*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2981#-KzPNvjwJ3MNSejyzu0_:-KzPQ0uJ8aYP-nXmWTDa:b-83sjoh) (no related file):*
<details><summary><i>Previously, asashour (Ahmed Ashour) wrote…</i></summary><blockquote>

They were detected by `sonar` and were reverted.
</blockquote></details>

Nice!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2981)*

**Comment by Legioth** [comment]
> Will Flow continue to depend on GWT, or this dependency will be removed later?

If Flow stops using GWT internally, then the relevant parts of the implementation would also have to be rewritten more or less from scratch. You can safely assume that anything in `flow-client` will be specific to GWT and anything outside it won't be. We're not using a separate `shared` module in the same way as Framework does since we haven't had any reason to share any actual code between the server and the client.

**Comment by asashour** [comment]
The requested changes were done, I am not sure how to tell the requester through github.

**Comment by SomeoneToIgnore** [comment]
Reviewed 27 of 41 files at r1, 1 of 6 files at r2, 9 of 11 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2981)*

**Pull request merged**
