### PR TITLE
Format all pom.xml files the same way

### PR DESCRIPTION
**Pull request by Artur-**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3411)

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
Build fix: https://github.com/vaadin/flow/pull/3412

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3411#-:-L3oM0RHyMY3DlGPohKJ:b-hvjlrz)*

**Comment by SomeoneToIgnore** [comment]
Review status: 0 of 30 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3411#-L3oMGO8P00XWDRaI6yi:-L3oMGO8P00XWDRaI6yj:b-trwpyl) (no related file):*
Do you have any way to enforce these changes? 
I've already done something similar before and you see what it turned into after couple of months had passed.

We have a number of Eclipse users who have troubles with spaces and tabs quite frequently, is there a way to configure this ide once and for all? Or add a check/automatic formatter?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3411)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 30 of 30 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3411)*

**Comment by Artur-** [comment]
Review status: 0 of 32 files reviewed at latest revision, 37 unresolved discussions, some commit checks broke.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3411#-L3oMGO8P00XWDRaI6yi:-L3rOV8ILyy5SoQgdz4U:b-8slj10) (no related file):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Do you have any way to enforce these changes? 
I've already done something similar before and you see what it turned into after couple of months had passed.

We have a number of Eclipse users who have troubles with spaces and tabs quite frequently, is there a way to configure this ide once and for all? Or add a check/automatic formatter?
</blockquote></details>

Sonar seems to check this at MINOR level although it's set to use "2 spaces" and not "4 spaces" which is the Eclipse default. Which one should it be?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3411)*

**Comment by SomeoneToIgnore** [comment]
*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3411#-L3oMGO8P00XWDRaI6yi:-L3rZ4AY316GiLL_Pukd:blko05n) (no related file):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Sonar seems to check this at MINOR level although it's set to use "2 spaces" and not "4 spaces" which is the Eclipse default. Which one should it be?
</blockquote></details>

Judging by the other files, it should be 4.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3411)*

**Comment by Artur-** [comment]
Review status: 0 of 30 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3411#-L3oMGO8P00XWDRaI6yi:-L3yUv00AESii1DQYlFI:bwmgka) (no related file):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Judging by the other files, it should be 4.
</blockquote></details>

Now it's 4

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3411)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 30 of 30 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3411#-L3oMGO8P00XWDRaI6yi:-L3yXcNAK6rPaA4c3bOM:b-wdj8z5) (no related file):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Now it's 4
</blockquote></details>

Nice, thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3411)*

**Pull request merged**
