### PR TITLE
First iteration of ComponentRenderers inside the Grid

### PR DESCRIPTION
**Pull request by gilberto-torrezan**
This is not a flawless implementation - but it implements the concept and allows users to use components inside the Grid.

It does so by creating a temporary container at the client-side DOM that holds all the actual components. A custom webcomponent (called `<flow-component-renderer>`) fetches the components from the DOM and attach them to the actual position inside the templated cell.

This is the first iteration. The implementation should be polished in the future for better performance and smaller memory footprint.

The demo is included in the PR, but the tutorial will be created as a separate patch.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/2815)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java, line 675 at r1](https://reviewable.io:443/reviews/vaadin/flow/2815#-KxqGRRwID35o_HEr7Ud:-KxqGRRxFjwn7a3GCgF6:bia7ad9) ([raw file](https://github.com/vaadin/flow/blob/010b65c1f760d10ae53398c6b89c0ebe177ccfbf/flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java#L675)):*
> assert DomApi.wrap(child)
>             .getParentNode() == context.htmlNode : "Invalid element parent";

What's the usecase when it's not true ?
Should another assertion be added in `else` branch in the new code?

---

*[flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/views/GridView.java, line 345 at r1](https://reviewable.io:443/reviews/vaadin/flow/2815#-KxqGnueL4-fjVvWmLQu:-KxqGnueL4-fjVvWmLQv:b8ffcjw) ([raw file](https://github.com/vaadin/flow/blob/3e563a4397ba16c7274f63b118518ba9caabea43/flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/views/GridView.java#L345)):*
> idField.addValueChangeListener(event -> {
>         });

I guess this is workaround which is already not needed.

---

*[flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/views/GridView.java, line 348 at r1](https://reviewable.io:443/reviews/vaadin/flow/2815#-KxqGsM-z4wEe38h6Gio:-KxqGsM-z4wEe38h6Gip:b-8wygls) ([raw file](https://github.com/vaadin/flow/blob/3e563a4397ba16c7274f63b118518ba9caabea43/flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/views/GridView.java#L348)):*
> nameField.addValueChangeListener(event -> {
>         })

Same here.

By the way it was enough to synchronize the `value` property (it's done as a first line in the listener adding method)

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 901 at r1](https://reviewable.io:443/reviews/vaadin/flow/2815#-KxqHuetpUn4aKopKm7b:-KxqHuetpUn4aKopKm7c:b-4ma5u) ([raw file](https://github.com/vaadin/flow/blob/3e563a4397ba16c7274f63b118518ba9caabea43/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L901)):*
> if (renderedDetailComponents != null) {

`if` inside `if`.
You are going to assign an empty hashmap anyway to the field.
You can do it beforehand instead of big `if` block (may be using ternary operator).
And then use `forEach`.

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 1094 at r1](https://reviewable.io:443/reviews/vaadin/flow/2815#-KxqILcX2_j8ykrRExuR:-KxqILcX2_j8ykrRExuS:brgrxww) ([raw file](https://github.com/vaadin/flow/blob/3e563a4397ba16c7274f63b118518ba9caabea43/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L1094)):*
> if (event instanceof DataRefreshEvent) {
<details><summary><i alt="summary">Quoted 9 lines of code…</i></summary>
>                 DataRefreshEvent<T> refreshEvent = (DataRefreshEvent<T>) event;
>                 T item = refreshEvent.getItem();
>                 String key = getDataCommunicator().getKeyMapper().key(item);
>                 RendereredComponent<T> rendereredComponent = renderedComponents
>                         .get(key);
>                 if (rendereredComponent != null) {
>                     Component old = rendereredComponent.component;
>                     Component recreatedComponent = rendereredComponent
>                             .recreateComponent(item);
</details>
>  
>                     if (old.getElement().getNode().getId() != recreatedComponent
>                             .getElement().getNode().getId()) {
>  
>                         ComponentRendererUtil.removeRendereredComponent(
>                                 UI.getCurrent(), container,
>                                 "[data-flow-renderer-item-key='" + key + "']");
>  
<details><summary><i alt="summary">Quoted 9 lines of code…</i></summary>
>                         registerRenderedComponent(componentRenderer,
>                                 renderedComponents, container, key,
>                                 recreatedComponent);
>                     }
>                 }
>             } else {
>                 container.removeAllChildren();
>                 renderedComponents.clear();
>             }
</details>

Huge lambda (with a lot of nested blocks). Too hard to read.
Please extract it to a method and use a method reference.

---

*[flow-server/src/main/java/com/vaadin/ui/renderers/ComponentRendererUtil.java, line 49 at r1](https://reviewable.io:443/reviews/vaadin/flow/2815#-KxqIsW-WgyD-MYBEa7P:-KxqIsW-WgyD-MYBEa7Q:b956fo7) ([raw file](https://github.com/vaadin/flow/blob/3e563a4397ba16c7274f63b118518ba9caabea43/flow-server/src/main/java/com/vaadin/ui/renderers/ComponentRendererUtil.java#L49)):*
> "div"

`Tag.DIV`

---

*[flow-server/src/main/resources/META-INF/resources/flow-component-renderer.html, line 109 at r1](https://reviewable.io:443/reviews/vaadin/flow/2815#-KxqJ65UJfbfJLg7gk4v:-KxqJ65UJfbfJLg7gk4w:bc382oq) ([raw file](https://github.com/vaadin/flow/blob/3e563a4397ba16c7274f63b118518ba9caabea43/flow-server/src/main/resources/META-INF/resources/flow-component-renderer.html#L109)):*
> ```HTML
>     window.customElements.define(FlowComponentRenderer.is, FlowComponentRenderer);
>  </script>
>  </dom-module>
> ```

new line

Would also be good to do something with other formatting issues here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2815)*

**Comment by gilberto-torrezan** [comment]
Review status: 5 of 8 files reviewed at latest revision, 7 unresolved discussions.

---

*[flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java, line 675 at r1](https://reviewable.io:443/reviews/vaadin/flow/2815#-KxqGRRwID35o_HEr7Ud:-KxqMYUVGcSUnFhR2Gw5:bhbccrd) ([raw file](https://github.com/vaadin/flow/blob/010b65c1f760d10ae53398c6b89c0ebe177ccfbf/flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java#L675)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> assert DomApi.wrap(child)
>             .getParentNode() == context.htmlNode : "Invalid element parent";

What's the usecase when it's not true ?
Should another assertion be added in `else` branch in the new code?
</blockquote></details>

Actually to make this patch work, the important part is "doing nothing if the current parent is different from the parent initially created for the component" (the empty `else`).

This is the case when the server creates a component a child of another component, and then some client-side logic changes the DOM structure.

Added a comment.

---

*[flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/views/GridView.java, line 345 at r1](https://reviewable.io:443/reviews/vaadin/flow/2815#-KxqGnueL4-fjVvWmLQu:-KxqVJkR7dcm5frBbWij:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/3e563a4397ba16c7274f63b118518ba9caabea43/flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/views/GridView.java#L345)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> idField.addValueChangeListener(event -> {
>         });

I guess this is workaround which is already not needed.
</blockquote></details>

Done.

---

*[flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/views/GridView.java, line 348 at r1](https://reviewable.io:443/reviews/vaadin/flow/2815#-KxqGsM-z4wEe38h6Gio:-KxqVK7FbjcMlaggjqs4:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/3e563a4397ba16c7274f63b118518ba9caabea43/flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/views/GridView.java#L348)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> nameField.addValueChangeListener(event -> {
>         })

Same here.

By the way it was enough to synchronize the `value` property (it's done as a first line in the listener adding method)
</blockquote></details>

Done.

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 901 at r1](https://reviewable.io:443/reviews/vaadin/flow/2815#-KxqHuetpUn4aKopKm7b:-KxqQZ5FnkbmdaL5V8lD:b-cr555p) ([raw file](https://github.com/vaadin/flow/blob/3e563a4397ba16c7274f63b118518ba9caabea43/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L901)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> if (renderedDetailComponents != null) {

`if` inside `if`.
You are going to assign an empty hashmap anyway to the field.
You can do it beforehand instead of big `if` block (may be using ternary operator).
And then use `forEach`.
</blockquote></details>

You mean this way? Feels strange to me at the first glance

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 1094 at r1](https://reviewable.io:443/reviews/vaadin/flow/2815#-KxqILcX2_j8ykrRExuR:-KxqVIaOy_E5JvvyhYng:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/3e563a4397ba16c7274f63b118518ba9caabea43/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L1094)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> if (event instanceof DataRefreshEvent) {
>                 DataRefreshEvent<T> refreshEvent = (DataRefreshEvent<T>) event;
>                 T item = refreshEvent.getItem();
>                 String key = getDataCommunicator().getKeyMapper().key(item);
>                 RendereredComponent<T> rendereredComponent = renderedComponents
>                         .get(key);
>                 if (rendereredComponent != null) {
>                     Component old = rendereredComponent.component;
>                     Component recreatedComponent = rendereredComponent
>                             .recreateComponent(item);
>  
>                     if (old.getElement().getNode().getId() != recreatedComponent
>                             .getElement().getNode().getId()) {
>  
>                         ComponentRendererUtil.removeRendereredComponent(
>                                 UI.getCurrent(), container,
>                                 "[data-flow-renderer-item-key='" + key + "']");
>  
>                         registerRenderedComponent(componentRenderer,
>                                 renderedComponents, container, key,
>                                 recreatedComponent);
>                     }
>                 }
>             } else {
>                 container.removeAllChildren();
>                 renderedComponents.clear();
>             }

Huge lambda (with a lot of nested blocks). Too hard to read.
Please extract it to a method and use a method reference.
</blockquote></details>

Done.

---

*[flow-server/src/main/resources/META-INF/resources/flow-component-renderer.html, line 109 at r1](https://reviewable.io:443/reviews/vaadin/flow/2815#-KxqJ65UJfbfJLg7gk4v:-KxqNKzk9jJe6TTNB_p8:b-1ie9zg) ([raw file](https://github.com/vaadin/flow/blob/3e563a4397ba16c7274f63b118518ba9caabea43/flow-server/src/main/resources/META-INF/resources/flow-component-renderer.html#L109)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

new line

Would also be good to do something with other formatting issues here.
</blockquote></details>

I couldn't find a way to auto format this file in Eclipse - it is Javascript inside HTML, and it seems that the editor get lost on it. Do you know how to properly configure it for webcomponents?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2815)*

**Comment by denis-anisimov** [comment]
Reviewed 3 of 3 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 14 unresolved discussions, some commit checks broke.

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 901 at r1](https://reviewable.io:443/reviews/vaadin/flow/2815#-KxqHuetpUn4aKopKm7b:-KxrFbCYFgtgRy8U-K7m:bb7sa0c) ([raw file](https://github.com/vaadin/flow/blob/3e563a4397ba16c7274f63b118518ba9caabea43/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L901)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

You mean this way? Feels strange to me at the first glance
</blockquote></details>

yes.

---

*[flow-server/src/main/java/com/vaadin/ui/renderers/ComponentRendererUtil.java, line 39 at r3](https://reviewable.io:443/reviews/vaadin/flow/2815#-KxrG2SiJuIA2DDZFzbe:-KxrG2SiJuIA2DDZFzbf:b-ev1hrm) ([raw file](https://github.com/vaadin/flow/blob/42f86b68dd4479a7dca30fac104baf51c22f32f3/flow-server/src/main/java/com/vaadin/ui/renderers/ComponentRendererUtil.java#L39)):*
> {@code <flow-component-renderer>}

Will this be handled properly by javadocs ? (`"<"`).
Javadocs validation will complain about it if not.
Not a blocker from my side.

---

*[flow-server/src/main/resources/META-INF/resources/flow-component-renderer.html, line 109 at r1](https://reviewable.io:443/reviews/vaadin/flow/2815#-KxqJ65UJfbfJLg7gk4v:-KxrGSxyjJqXTIArnz0h:brbb1ol) ([raw file](https://github.com/vaadin/flow/blob/3e563a4397ba16c7274f63b118518ba9caabea43/flow-server/src/main/resources/META-INF/resources/flow-component-renderer.html#L109)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

I couldn't find a way to auto format this file in Eclipse - it is Javascript inside HTML, and it seems that the editor get lost on it. Do you know how to properly configure it for webcomponents?
</blockquote></details>

This is HTML file.
So find `HTML files` section ( under the `web`), `Editor` there are formatting settings.
Change settings and reformat the whole file.
Should help.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2815)*

**Comment by gilberto-torrezan** [comment]
Review status: 4 of 8 files reviewed at latest revision, 13 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/ui/renderers/ComponentRendererUtil.java, line 39 at r3](https://reviewable.io:443/reviews/vaadin/flow/2815#-KxrG2SiJuIA2DDZFzbe:-KxrI7rKc1AP1Fltb3_c:bgfepe6) ([raw file](https://github.com/vaadin/flow/blob/42f86b68dd4479a7dca30fac104baf51c22f32f3/flow-server/src/main/java/com/vaadin/ui/renderers/ComponentRendererUtil.java#L39)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> {@code <flow-component-renderer>}

Will this be handled properly by javadocs ? (`"<"`).
Javadocs validation will complain about it if not.
Not a blocker from my side.
</blockquote></details>

`{@code}` accepts any HTML content inside it, so you don't have to escape it. Works like a `<pre>` tag, but it's easier to maintain.

`<code>` on the other hand doesn't escape the content, so you have to escape it yourself.

---

*[flow-server/src/main/resources/META-INF/resources/flow-component-renderer.html, line 109 at r1](https://reviewable.io:443/reviews/vaadin/flow/2815#-KxqJ65UJfbfJLg7gk4v:-KxrIVBEtx33pVrGmnjw:b-zcqgw1) ([raw file](https://github.com/vaadin/flow/blob/3e563a4397ba16c7274f63b118518ba9caabea43/flow-server/src/main/resources/META-INF/resources/flow-component-renderer.html#L109)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

This is HTML file.
So find `HTML files` section ( under the `web`), `Editor` there are formatting settings.
Change settings and reformat the whole file.
Should help.
</blockquote></details>

I couldn't make it work properly on Eclipse - it formats the HTML but not the javascript inside the `<script>` tag. So I copied the file in Atom and formatted it there. I hope it's better now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2815)*

**Comment by denis-anisimov** [comment]
Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2815)*

**Pull request merged**
