### PR TITLE
Enable `@Route` scanning for Spring boot application

### LINKED ISSUE #2567: Router initialization should work with Spring Boot application
Router is initialized correctly when the application is packaged and deployed as a WAR.
But it doesn't work when it's run as a Spring boot application.

It should work correctly in both cases.

It's primarily about `RouteRegistryInitializer`. But it might be some other thing should be done as well.

As a result Router should work with Spring in the same way as without Spring.
It means that no scopes/autowiring/other Spring features are considered here at all.
Router should just work inside Spring boot  app (ignore anything related to managed beans, injections).

### PR DESCRIPTION
**Pull request by denis-anisimov**
Fixes #2567

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/2593)

### CODE REVIEW

**Comment by caalador** [comment]
Reviewed 17 of 19 files at r1, 1 of 1 files at r2.
Review status: 16 of 17 files reviewed at latest revision, 8 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/server/startup/RouteRegistry.java, line 32 at r2](https://reviewable.io:443/reviews/vaadin/flow/2593#-KvfMfEMDrVNBCnRGkrW:-KvfMfEMDrVNBCnRGkrX:b-aehix3) ([raw file](https://github.com/vaadin/flow/blob/80481d2bf33f918106ef6b18bc97be73f53ff0ac/flow-server/src/main/java/com/vaadin/server/startup/RouteRegistry.java#L32)):*
> ```Java
> 
> import javax.servlet.ServletContext;
> ```

This whole file should be reverted as the changes are only changing formatting and do not have anything to do with the actual patch.

---

*[flow-spring-addon/src/main/java/com/vaadin/spring/RouterRegistryServletContextInitializer.java, line 74 at r2](https://reviewable.io:443/reviews/vaadin/flow/2593#-KvfPDucjysiSiQZCJvg:-KvfPDudN-4KfX7DSHKa:bkkhn2j) ([raw file](https://github.com/vaadin/flow/blob/80481d2bf33f918106ef6b18bc97be73f53ff0ac/flow-spring-addon/src/main/java/com/vaadin/spring/RouterRegistryServletContextInitializer.java#L74)):*
> ```Java
>                 Set<Class<? extends Component>> navigationTargets = findNavigationTargets();
> 
>                 registry.setNavigationTargets(navigationTargets);
> ```

Here should be the conflicting annotation check from RouteRegistryInitializer.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2593)*

**Comment by denis-anisimov** [comment]
Review status: 16 of 17 files reviewed at latest revision, 8 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/server/startup/RouteRegistry.java, line 32 at r2](https://reviewable.io:443/reviews/vaadin/flow/2593#-KvfMfEMDrVNBCnRGkrW:-KvfSCAvTT3HDFlZoGF2:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/80481d2bf33f918106ef6b18bc97be73f53ff0ac/flow-server/src/main/java/com/vaadin/server/startup/RouteRegistry.java#L32)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

This whole file should be reverted as the changes are only changing formatting and do not have anything to do with the actual patch.
</blockquote></details>

Done.

---

*[flow-spring-addon/src/main/java/com/vaadin/spring/RouterRegistryServletContextInitializer.java, line 74 at r2](https://reviewable.io:443/reviews/vaadin/flow/2593#-KvfPDucjysiSiQZCJvg:-KvfT7oFFHzVsy8KASdu:bpfugyi) ([raw file](https://github.com/vaadin/flow/blob/80481d2bf33f918106ef6b18bc97be73f53ff0ac/flow-spring-addon/src/main/java/com/vaadin/spring/RouterRegistryServletContextInitializer.java#L74)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Here should be the conflicting annotation check from RouteRegistryInitializer.
</blockquote></details>

Right, thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2593)*

**Comment by denis-anisimov** [comment]
Review status: 15 of 18 files reviewed at latest revision, 8 unresolved discussions.

---

*[flow-spring-addon/src/main/java/com/vaadin/spring/RouterRegistryServletContextInitializer.java, line 74 at r2](https://reviewable.io:443/reviews/vaadin/flow/2593#-KvfPDucjysiSiQZCJvg:-KvfXhsmBpUWcMMpoHAA:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/80481d2bf33f918106ef6b18bc97be73f53ff0ac/flow-spring-addon/src/main/java/com/vaadin/spring/RouterRegistryServletContextInitializer.java#L74)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Right, thanks.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2593)*

**Comment by caalador** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2593)*

**Pull request merged**
