### PR TITLE
Add Starter and Tutorial links to Spring docs

### PR DESCRIPTION
**Pull request by pleku**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/2786)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-documentation/spring/tutorial-spring-examples.asciidoc, line 16 at r1](https://reviewable.io:443/reviews/vaadin/flow/2786#-KxNLvakm1lzeM-eqtbX:-KxNLvald3Z2YDzBwSM0:b-d0wxhj) ([raw file](https://github.com/vaadin/flow/blob/dd4f3fd43eafcec9791856338186b78d0bf3b565/flow-documentation/spring/tutorial-spring-examples.asciidoc#L16)):*
> ```AsciiDoc
> For starting a fresh project with Spring and Flow, you can take the https://github.com/vaadin/flow-spring-tutorial[Skeleton Starter for Flow and Spring].
> It is a project template with the necessary parts there for starting building you own application.
> This starter will later soon be available from https://vaadin.com/start, where you can customize the naming (package, project) for it.
> ```

new line

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2786)*

**Comment by ahie** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2786#-KxNbUiSvs-PVLxV9OPh:-KxNbUiSvs-PVLxV9OPi:b-rxdf0y) (no related file):*
Commented some improvement suggestions.

---

*[flow-documentation/spring/tutorial-spring-examples.asciidoc, line 11 at r1](https://reviewable.io:443/reviews/vaadin/flow/2786#-KxNa5H3yjyyxmOtNXCM:-KxNa5H4k_f91a-mNMeN:b-56e53v) ([raw file](https://github.com/vaadin/flow/blob/dd4f3fd43eafcec9791856338186b78d0bf3b565/flow-documentation/spring/tutorial-spring-examples.asciidoc#L11)):*
> There is a tutorial application which shows the basic parts of a Spring Boot Application with Flow: https://github.com/vaadin/flow-spring-tutorial.

A tutorial application which showcases basic usage of a Spring Boot Application together with Flow is available at https://github.com/vaadin/flow-spring-tutorial.

---

*[flow-documentation/spring/tutorial-spring-examples.asciidoc, line 14 at r1](https://reviewable.io:443/reviews/vaadin/flow/2786#-KxNaUBXUhwdnH6zj0Qn:-KxNaUBXUhwdnH6zj0Qo:b-y9aoy5) ([raw file](https://github.com/vaadin/flow/blob/dd4f3fd43eafcec9791856338186b78d0bf3b565/flow-documentation/spring/tutorial-spring-examples.asciidoc#L14)):*
> For starting a fresh project with Spring and Flow, you can take the

A simple way for starting a fresh project with Spring and Flow is to clone the https://github.com/vaadin/flow-spring-tutorial[Skeleton Starter for Flow and Spring] repository.

---

*[flow-documentation/spring/tutorial-spring-examples.asciidoc, line 15 at r1](https://reviewable.io:443/reviews/vaadin/flow/2786#-KxNamkOae50KDjZeSTQ:-KxNamkOae50KDjZeSTR:b-gh0j5x) ([raw file](https://github.com/vaadin/flow/blob/dd4f3fd43eafcec9791856338186b78d0bf3b565/flow-documentation/spring/tutorial-spring-examples.asciidoc#L15)):*
> with the necessary parts there for starting building you own

with all the necessary configuration included for starting to build your own

---

*[flow-documentation/spring/tutorial-spring-examples.asciidoc, line 16 at r1](https://reviewable.io:443/reviews/vaadin/flow/2786#-KxNbFR8usMZcwelbLqM:-KxNbFR8usMZcwelbLqN:b-ich7ol) ([raw file](https://github.com/vaadin/flow/blob/dd4f3fd43eafcec9791856338186b78d0bf3b565/flow-documentation/spring/tutorial-spring-examples.asciidoc#L16)):*
> later soon be available

soon be available

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2786)*

**Comment by pleku** [comment]
Review status: 1 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[flow-documentation/spring/tutorial-spring-examples.asciidoc, line 11 at r1](https://reviewable.io:443/reviews/vaadin/flow/2786#-KxNa5H3yjyyxmOtNXCM:-KxNryPJIeHCuIZILVUg:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/dd4f3fd43eafcec9791856338186b78d0bf3b565/flow-documentation/spring/tutorial-spring-examples.asciidoc#L11)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

> There is a tutorial application which shows the basic parts of a Spring Boot Application with Flow: https://github.com/vaadin/flow-spring-tutorial.

A tutorial application which showcases basic usage of a Spring Boot Application together with Flow is available at https://github.com/vaadin/flow-spring-tutorial.
</blockquote></details>

Done.

---

*[flow-documentation/spring/tutorial-spring-examples.asciidoc, line 14 at r1](https://reviewable.io:443/reviews/vaadin/flow/2786#-KxNaUBXUhwdnH6zj0Qn:-KxNsglQEEA9e-tw6epT:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/dd4f3fd43eafcec9791856338186b78d0bf3b565/flow-documentation/spring/tutorial-spring-examples.asciidoc#L14)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

> For starting a fresh project with Spring and Flow, you can take the

A simple way for starting a fresh project with Spring and Flow is to clone the https://github.com/vaadin/flow-spring-tutorial[Skeleton Starter for Flow and Spring] repository.
</blockquote></details>

Done.

---

*[flow-documentation/spring/tutorial-spring-examples.asciidoc, line 15 at r1](https://reviewable.io:443/reviews/vaadin/flow/2786#-KxNamkOae50KDjZeSTQ:-KxNsgK8JZJYq055-w9D:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/dd4f3fd43eafcec9791856338186b78d0bf3b565/flow-documentation/spring/tutorial-spring-examples.asciidoc#L15)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

> with the necessary parts there for starting building you own

with all the necessary configuration included for starting to build your own
</blockquote></details>

Done.

---

*[flow-documentation/spring/tutorial-spring-examples.asciidoc, line 16 at r1](https://reviewable.io:443/reviews/vaadin/flow/2786#-KxNLvakm1lzeM-eqtbX:-KxNsfraYBbPipO9ibiW:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/dd4f3fd43eafcec9791856338186b78d0bf3b565/flow-documentation/spring/tutorial-spring-examples.asciidoc#L16)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

new line
</blockquote></details>

Done.

---

*[flow-documentation/spring/tutorial-spring-examples.asciidoc, line 16 at r1](https://reviewable.io:443/reviews/vaadin/flow/2786#-KxNbFR8usMZcwelbLqM:-KxNsg7YZYM7_O_A_x35:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/dd4f3fd43eafcec9791856338186b78d0bf3b565/flow-documentation/spring/tutorial-spring-examples.asciidoc#L16)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

> later soon be available

soon be available
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2786)*

**Comment by ahie** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2786)*

**Comment by ZheSun88** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-documentation/spring/tutorial-spring-examples.asciidoc, line 16 at r1](https://reviewable.io:443/reviews/vaadin/flow/2786#-KxNLvakm1lzeM-eqtbX:-Ky-y0xsRzyc8DuHPbUv:bk2u4zu) ([raw file](https://github.com/vaadin/flow/blob/dd4f3fd43eafcec9791856338186b78d0bf3b565/flow-documentation/spring/tutorial-spring-examples.asciidoc#L16)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@denis-anisimov remember to solve this discussion

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2786)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2786)*

**Pull request merged**
