### PR TITLE
Feat/theme editor license check

### LINKED ISSUE #17279: Theme Editor license checking
Implement frontend license checking for Theme Editor when metadata will be covered.

Continuation of https://github.com/vaadin/flow/pull/16230

### PR DESCRIPTION
**Pull request by abdullahtellioglu**
# 🚧 DO NOT MERGE 🚧

## Description

Implemented license checker to the theme editor. If a valid license is not found, a message is displayed to warn the user to log in or signup. 

login_sign-up-theme-editor

User can use the theme editor once receives a valid license without restarting the server.

In addition to that, Theme Editor's label is renamed as `Theme Editor`

Fixes #17279 

## Type of change

- [ ] Bugfix
- [X] Feature

## Checklist

- [X] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [X] I have added a description following the guideline.
- [X] The issue is created in the corresponding repository and I have referenced it.
- [X] I have added tests to ensure my change is effective and works as intended.
- [X] New and existing tests are passing locally with my change.
- [X] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [X] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

### CODE REVIEW

**Comment by MarcinVaadin** [comment]
Depends on https://github.com/vaadin/flow/issues/17042

**Comment by tarekoraby** [comment]
@abdullahtellioglu/ @MarcinVaadin, Theme Editor requires Vaadin **Prime** (or higher).

**Comment by abdullahtellioglu** [comment]
Updated the message @tarekoraby 
theme-editor-text-updated

**Comment by mshabarov** [comment]
@MarcinVaadin when do you expect this to be merged? Maybe we can close this PR now ?

**Comment by MarcinVaadin** [comment]
No to be merged currently.

**Pull request closed without merging**
