### PR TITLE
feat!: Backporting automatically use available converters and duplicated field guard in Binder

### PR DESCRIPTION
**Pull request by melihkurtaran**
## Description

When binding a field and a property which do not have the same value type
an exception is thrown. With this change, an attempt is made to
automatically pick a suitable converter from the ones provided by the framework.

It was implemented for Vaadin 23  (#13373) now backporting to version 14

+ the fix in #13340 is also backported

## Type of change

- [ ] Bugfix
- [X] Feature

## Checklist

- [X] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [X] I have added a description following the guideline.
- [X] The issue is created in the corresponding repository and I have referenced it.
- [X] I have added tests to ensure my change is effective and works as intended.
- [X] New and existing tests are passing locally with my change.
- [X] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [X] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

### CODE REVIEW

**Comment by mcollovati** [comment]
Hi @melihkurtaran, sorry to bother you but may I ask you to create a new PR that preserves the original commits since the two changes are not strictly related; it would be better to not squash them in a single fix.
If you prefer, you can also create two separated PRs, first one for #13340 and then second one for #13373, to be created after the first is merged.

**Comment by melihkurtaran** [comment]
Hi @mcollovati, that's okay. I am creating two separated PRs.

**Comment by melihkurtaran** [comment]
Two newly created PRs:

#14391

#14392

**Comment by mcollovati** [comment]
Closing, as there are now two new PRs to backport changes

**Pull request closed without merging**
