### PR TITLE
fix: update css-loader(#12863)(CP:2.8)

### PR DESCRIPTION
**Pull request by ZheSun88**
this is a Cherry pick of https://github.com/vaadin/flow/pull/12863
Update css-loader to get a newer version of postcss

### CODE REVIEW

**Comment by mshabarov** [comment]
I have no memories what did we fix with this update. This is a major version update, may bring breaking changes to 14.8 and 14.9 users.

**Comment by ZheSun88** [comment]
if it is not needed, feel free to close this one.

**Comment by mshabarov** [comment]
@caalador do you recall what we fixed by updating this version? Can we skip it for 14.8/14.9 (since it's a major update)

**Comment by caalador** [comment]
As it says  to `get a newer version of postcss` I would guess it is to get a vulnerability patch in postcss

**Review by mshabarov — APPROVED** [review]

**Pull request merged**
