### PR TITLE
refactor!: move renderer package to flow-components

### PR DESCRIPTION
**Pull request by tomivirkki**
This PR removes the renderer package from flow. [Another PR](https://github.com/vaadin/flow-components/pull/2009) copies the package to the flow-components repo.

Part of https://github.com/vaadin/flow-components/issues/1999
Depends on https://github.com/vaadin/flow-components/pull/2009

### CODE REVIEW

**Review by pleku — APPROVED** [review]

**Comment by caalador** [comment]
After this went in the Spring plugin started failing with:
```
[07:14:04]	[Step 2/5] [ERROR] Failed to execute goal com.vaadin:flow-maven-plugin:9.0-SNAPSHOT:build-frontend (default) on project vaadin-test-spring-boot: Could not execute build-frontend goal: Error occured during goal execution: 
[07:14:04]	[Step 2/5] [ERROR] 
[07:14:04]	[Step 2/5] [ERROR]   Failed to find the following files: 
[07:14:04]	[Step 2/5] [ERROR]       - ./flow-component-renderer.js
[07:14:04]	[Step 2/5] [ERROR]   
[07:14:04]	[Step 2/5] [ERROR]   Locations searched were:
[07:14:04]	[Step 2/5] [ERROR]       - `/opt/agent/work/769cb777cb353dfb/vaadin-spring-tests/test-spring-boot/frontend` in this project
[07:14:04]	[Step 2/5] [ERROR]       - `META-INF/frontend` in included JARs
[07:14:04]	[Step 2/5] [ERROR] 
[07:14:04]	[Step 2/5] [ERROR]   Please, double check that those files exist. If you use a custom directory for your resource files instead of default `frontend` folder then make sure you it's correctly configured (e.g. set 'vaadin.frontend.frontend.folder' property)
[07:14:04]	[Step 2/5] [ERROR] 
[07:14:04]	[Step 2/5] [ERROR] Please run Maven with the -e switch (or Gradle with the --stacktrace switch), to learn the full stack trace.
[07:14:04]	[Step 2/5] [ERROR] -> [Help 1]
```

**Comment by caalador** [comment]
Same for MPR:
```
[04:34:40]	[Step 3/5] [ERROR] Failed to execute goal com.vaadin:flow-maven-plugin:9.0-SNAPSHOT:build-frontend (default) on project it-test-v7: Could not execute build-frontend goal: Error occured during goal execution: 
[04:34:40]	[Step 3/5] [ERROR] 
[04:34:40]	[Step 3/5] [ERROR]   Failed to find the following files: 
[04:34:40]	[Step 3/5] [ERROR]       - ./flow-component-renderer.js
[04:34:40]	[Step 3/5] [ERROR]   
[04:34:40]	[Step 3/5] [ERROR]   Locations searched were:
[04:34:40]	[Step 3/5] [ERROR]       - `/opt/agent/work/e4ede00d09c3a35f/mpr-tests/it-test-v7/frontend` in this project
[04:34:40]	[Step 3/5] [ERROR]       - `META-INF/frontend` in included JARs
[04:34:40]	[Step 3/5] [ERROR] 
[04:34:40]	[Step 3/5] [ERROR]   Please, double check that those files exist. If you use a custom directory for your resource files instead of default `frontend` folder then make sure you it's correctly configured (e.g. set 'vaadin.frontend.frontend.folder' property)
[04:34:40]	[Step 3/5] [ERROR] 
[04:34:40]	[Step 3/5] [ERROR] Please run Maven with the -e switch (or Gradle with the --stacktrace switch), to learn the full stack trace.
[04:34:40]	[Step 3/5] [ERROR] -> [Help 1]
```

**Comment by caalador** [comment]
Patient Portal for 9.0 is also broken:
```
[01:30:52]	[Step 2/2] [ERROR] COMPILATION ERROR : 
[01:30:52]	[Step 2/2] [INFO] -------------------------------------------------------------
[01:30:52]	[Step 2/2] [ERROR] /opt/agent/work/fd1cd28c3083c545/src/main/java/com/vaadin/flow/demo/patientportal/ui/PatientsView.java:[35,37] package com.vaadin.flow.data.renderer does not exist
[01:30:52]	[Step 2/2] [ERROR] /opt/agent/work/fd1cd28c3083c545/src/main/java/com/vaadin/flow/demo/patientportal/ui/PatientsView.java:[36,37] package com.vaadin.flow.data.renderer does not exist
[01:30:52]	[Step 2/2] [ERROR] /opt/agent/work/fd1cd28c3083c545/src/main/java/com/vaadin/flow/demo/patientportal/ui/patients/PatientJournal.java:[32,37] package com.vaadin.flow.data.renderer does not exist
[01:30:52]	[Step 2/2] [ERROR] /opt/agent/work/fd1cd28c3083c545/src/main/java/com/vaadin/flow/demo/patientportal/ui/patients/PatientJournal.java:[33,37] package com.vaadin.flow.data.renderer does not exist
[01:30:52]	[Step 2/2] [ERROR] /opt/agent/work/fd1cd28c3083c545/src/main/java/com/vaadin/flow/demo/patientportal/ui/PatientsView.java:[83,24] cannot find symbol
[01:30:52]	[Step 2/2]   symbol:   variable TemplateRenderer
[01:30:52]	[Step 2/2]   location: class com.vaadin.flow.demo.patientportal.ui.PatientsView
[01:30:52]	[Step 2/2] [ERROR] /opt/agent/work/fd1cd28c3083c545/src/main/java/com/vaadin/flow/demo/patientportal/ui/PatientsView.java:[83,13] cannot access com.vaadin.flow.data.renderer.Renderer
[01:30:52]	[Step 2/2]   class file for com.vaadin.flow.data.renderer.Renderer not found
[01:30:52]	[Step 2/2] [ERROR] /opt/agent/work/fd1cd28c3083c545/src/main/java/com/vaadin/flow/demo/patientportal/ui/PatientsView.java:[88,13] reference to addColumn is ambiguous
[01:30:52]	[Step 2/2]   both method addColumn(com.vaadin.flow.function.ValueProvider<T,?>) in com.vaadin.flow.component.grid.Grid and method addColumn(com.vaadin.flow.data.renderer.Renderer<T>) in com.vaadin.flow.component.grid.Grid match
[01:30:52]	[Step 2/2] [ERROR] /opt/agent/work/fd1cd28c3083c545/src/main/java/com/vaadin/flow/demo/patientportal/ui/PatientsView.java:[90,13] reference to addColumn is ambiguous
[01:30:52]	[Step 2/2]   both method addColumn(com.vaadin.flow.function.ValueProvider<T,?>) in com.vaadin.flow.component.grid.Grid and method addColumn(com.vaadin.flow.data.renderer.Renderer<T>) in com.vaadin.flow.component.grid.Grid match
[01:30:52]	[Step 2/2] [ERROR] /opt/agent/work/fd1cd28c3083c545/src/main/java/com/vaadin/flow/demo/patientportal/ui/PatientsView.java:[99,28] cannot find symbol
[01:30:52]	[Step 2/2]   symbol:   class LocalDateRenderer
[01:30:52]	[Step 2/2]   location: class com.vaadin.flow.demo.patientportal.ui.PatientsView
[01:30:52]	[Step 2/2] [ERROR] /opt/agent/work/fd1cd28c3083c545/src/main/java/com/vaadin/flow/demo/patientportal/ui/patients/PatientJournal.java:[61,28] cannot find symbol
[01:30:52]	[Step 2/2]   symbol:   class LocalDateRenderer
[01:30:52]	[Step 2/2]   location: class com.vaadin.flow.demo.patientportal.ui.patients.PatientJournal
[01:30:52]	[Step 2/2] [ERROR] /opt/agent/work/fd1cd28c3083c545/src/main/java/com/vaadin/flow/demo/patientportal/ui/patients/PatientJournal.java:[64,13] reference to addColumn is ambiguous
[01:30:52]	[Step 2/2]   both method addColumn(com.vaadin.flow.function.ValueProvider<T,?>) in com.vaadin.flow.component.grid.Grid and method addColumn(com.vaadin.flow.data.renderer.Renderer<T>) in com.vaadin.flow.component.grid.Grid match
[01:30:52]	[Step 2/2] [ERROR] /opt/agent/work/fd1cd28c3083c545/src/main/java/com/vaadin/flow/demo/patientportal/ui/patients/PatientJournal.java:[71,13] reference to addColumn is ambiguous
[01:30:52]	[Step 2/2]   both method addColumn(com.vaadin.flow.function.ValueProvider<T,?>) in com.vaadin.flow.component.grid.Grid and method addColumn(com.vaadin.flow.data.renderer.Renderer<T>) in com.vaadin.flow.component.grid.Grid match
[01:30:52]	[Step 2/2] [ERROR] /opt/agent/work/fd1cd28c3083c545/src/main/java/com/vaadin/flow/demo/patientportal/ui/patients/PatientJournal.java:[72,37] cannot find symbol
[01:30:52]	[Step 2/2]   symbol:   variable TemplateRenderer
[01:30:52]	[Step 2/2]   location: class com.vaadin.flow.demo.patientportal.ui.patients.PatientJournal
[01:30:52]	[Step 2/2] [ERROR] /opt/agent/work/fd1cd28c3083c545/src/main/java/com/vaadin/flow/demo/patientportal/ui/patients/PatientJournal.java:[74,75] invalid method reference
[01:30:52]	[Step 2/2]   non-static method getEntry() cannot be referenced from a static context
```

**Comment by caalador** [comment]
Spring one seems to be due to usage of Notification in `test-spring-common`
` - ./flow-component-renderer.js class com.vaadin.flow.component.notification.Notification`

**Comment by caalador** [comment]
MPR probably for having Dialog.

**Pull request merged**
