### PR TITLE
Don't remove attribute from unsupported providers.

### PR DESCRIPTION
**Pull request by caalador**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3950)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---

*[flow-server/src/main/java/com/vaadin/flow/dom/Element.java, line 472 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3950#-LAXNSlB5HvOz8IRR20d:-LAXNSlB5HvOz8IRR20e:b-zfiic5) ([raw file](https://github.com/vaadin/flow/blob/c0e03b82f558cc3f03e8b5430816e9969e215b2d/flow-server/src/main/java/com/vaadin/flow/dom/Element.java#L472)):*
> ```
>         } else if (getStateProvider() instanceof BasicElementStateProvider) {
>             // Only the BasicElementStateProvider supports removeAttribute
> ```

That's the question: should it throw to notify that `removeAttribute` is called incorrectly or it should silently ignore the call.

Because technically `setAttribute`  (as any other method) also may check which provider supports and set it only if supported.
I don't see a logical difference between `setAttribute` and `removeAttribute`. 
Why does one throw and the other doesn't ?

May be instead have an overload `removeAttribute(String, boolean)` where the second attribute is `true` by default ( and `removeAttribute` delegates to it) and means silently ignore unsupported provider or throw?
Or may be `removeAttribute(String, Runnable)` (or `Consumer<ISE>` instead of `Runnable`) which allows to decide how to handle the unsupported case....... ( by default throw a new ISE or throw the provided ISE).
May be we should add such overloads for every method....

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3950)*

**Comment by caalador** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[flow-server/src/main/java/com/vaadin/flow/dom/Element.java, line 472 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3950#-LAXNSlB5HvOz8IRR20d:-LAXQPym48UYNSu677n2:bg91j2p) ([raw file](https://github.com/vaadin/flow/blob/c0e03b82f558cc3f03e8b5430816e9969e215b2d/flow-server/src/main/java/com/vaadin/flow/dom/Element.java#L472)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
>         } else if (getStateProvider() instanceof BasicElementStateProvider) {
>             // Only the BasicElementStateProvider supports removeAttribute
> ```

That's the question: should it throw to notify that `removeAttribute` is called incorrectly or it should silently ignore the call.

Because technically `setAttribute`  (as any other method) also may check which provider supports and set it only if supported.
I don't see a logical difference between `setAttribute` and `removeAttribute`. 
Why does one throw and the other doesn't ?

May be instead have an overload `removeAttribute(String, boolean)` where the second attribute is `true` by default ( and `removeAttribute` delegates to it) and means silently ignore unsupported provider or throw?
Or may be `removeAttribute(String, Runnable)` (or `Consumer<ISE>` instead of `Runnable`) which allows to decide how to handle the unsupported case....... ( by default throw a new ISE or throw the provided ISE).
May be we should add such overloads for every method....
</blockquote></details>

This is a hard question as basically it's fine if it throws when used wrong, but when something else uses it "wrong" inside some for loop of getChildren it's not that fine.

I'm open to suggestions, but would not want to add any extra api with booleans as no one wants to use that.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3950)*

**Comment by Legioth** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[flow-server/src/main/java/com/vaadin/flow/dom/Element.java, line 472 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3950#-LAXNSlB5HvOz8IRR20d:-LAXQtPI19rG6XwJ2ypi:b8cwhw0) ([raw file](https://github.com/vaadin/flow/blob/c0e03b82f558cc3f03e8b5430816e9969e215b2d/flow-server/src/main/java/com/vaadin/flow/dom/Element.java#L472)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

This is a hard question as basically it's fine if it throws when used wrong, but when something else uses it "wrong" inside some for loop of getChildren it's not that fine.

I'm open to suggestions, but would not want to add any extra api with booleans as no one wants to use that.

</blockquote></details>

I'd suggest a much simpler approach: The javadoc says that the method doesn't do anything if the attribute isn't present, so why not instead implement it in tat way, regardless of which  state provider is used?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3950)*

**Comment by caalador** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-server/src/main/java/com/vaadin/flow/dom/Element.java, line 472 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3950#-LAXNSlB5HvOz8IRR20d:-LAXRWK51cQOhpcGmUN1:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/c0e03b82f558cc3f03e8b5430816e9969e215b2d/flow-server/src/main/java/com/vaadin/flow/dom/Element.java#L472)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

I'd suggest a much simpler approach: The javadoc says that the method doesn't do anything if the attribute isn't present, so why not instead implement it in tat way, regardless of which  state provider is used?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3950)*

**Comment by denis-anisimov** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3950#-:-LAXb94kBKv3psujoCd4:bnfp4nl)*

**Pull request merged**
