### PR TITLE
Fix has value Null Check on component generator

### PR DESCRIPTION
**Pull request by ZheSun88**
Unit Test added;
new generated component files added;
fix by Gilberto, tests by Zhe

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3074)

### CODE REVIEW

**Comment by asashour** [comment]
Would it be a little better to have the pattern:

    String value = getElement().getProperty("value");
    return value == null ? getEmptyValue() : value;

**Comment by denis-anisimov** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/ComponentGenerator.java, line 737 at r1](https://reviewable.io:443/reviews/vaadin/flow/3074#-L-AUPSNe6VDzauvT3yG:-L-AUPSNe6VDzauvT3yH:b-fv54p4) ([raw file](https://github.com/vaadin/flow/blob/c8794171b8f191250f09480184f3980829532fa8/flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/ComponentGenerator.java#L737)):*
> method.setBody(String.format(
>                         "JsonObject _obj = (JsonObject) getElement().getPropertyRaw(\"%s\");"

Didn't find the test for this usecase.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3074)*

**Comment by ZheSun88** [comment]
Review status: 10 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/ComponentGenerator.java, line 737 at r1](https://reviewable.io:443/reviews/vaadin/flow/3074#-L-AUPSNe6VDzauvT3yG:-L-Bxo0VCMau2q-gdG_1:b-7tfmjp) ([raw file](https://github.com/vaadin/flow/blob/c8794171b8f191250f09480184f3980829532fa8/flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/ComponentGenerator.java#L737)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> method.setBody(String.format(
>                         "JsonObject _obj = (JsonObject) getElement().getPropertyRaw(\"%s\");"

Didn't find the test for this usecase.
</blockquote></details>

added

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3074)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/ComponentGenerator.java, line 737 at r1](https://reviewable.io:443/reviews/vaadin/flow/3074#-L-AUPSNe6VDzauvT3yG:-L-ByOsA6rHK5zWXbssA:b-vkyngm) ([raw file](https://github.com/vaadin/flow/blob/c8794171b8f191250f09480184f3980829532fa8/flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/ComponentGenerator.java#L737)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

added
</blockquote></details>

I don't see any test which has a string `JsonObject _obj`.
So I guess there are still no tests for this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3074)*

**Comment by ZheSun88** [comment]
Review status: 10 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/ComponentGenerator.java, line 737 at r1](https://reviewable.io:443/reviews/vaadin/flow/3074#-L-AUPSNe6VDzauvT3yG:-L-CBK_BmHR1PwFr9H8v:b-7an5np) ([raw file](https://github.com/vaadin/flow/blob/c8794171b8f191250f09480184f3980829532fa8/flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/ComponentGenerator.java#L737)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

I don't see any test which has a string `JsonObject _obj`.
So I guess there are still no tests for this.
</blockquote></details>

so now i think it is correct

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3074)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3074)*

**Pull request merged**
