### PR TITLE
Resolve name conflict

### PR DESCRIPTION
**Pull request by torok-peter**
Rename `HasDynamicTitle.getTitle` to `getPageTitle` to resolve name conflict with `HtmlComponent.get/setTitle`.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/2601)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2601)*

**Comment by caalador** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2601#-KvkP-090-SX-M4QxJ_q:-KvkP-090-SX-M4QxJ_r:b-c84dtg) (no related file):*
Blocking this until we are clear on which to change. perhaps have dynamic title be getPageTitle

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2601)*

**Comment by denis-anisimov** [comment]
Reviewed 7 of 9 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2601#-Kw-QC2CAE6JVTgaouYS:-Kw-QC2CAE6JVTgaouYT:b-a4x9ft) (no related file):*
> Rename HtmlComponent.get/setTitle to get/setTooltip

Is this a part of this PR ?

---

*[flow-server/src/main/java/com/vaadin/router/Title.java, line 29 at r2](https://reviewable.io:443/reviews/vaadin/flow/2601#-Kw-Q1LR9BvyZfdjY977:-Kw-Q1LR9BvyZfdjY978:bqgzpba) ([raw file](https://github.com/vaadin/flow/blob/7cd2321aec04585c1d28262a16e5993d54b88ffb/flow-server/src/main/java/com/vaadin/router/Title.java#L29)):*
> Title 

Shouldn't this also be renamed ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2601)*

**Comment by torok-peter** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2601#-Kw-QC2CAE6JVTgaouYS:-Kw-QnDrdDJW8kP_XScQ:b-hg7qid) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> Rename HtmlComponent.get/setTitle to get/setTooltip

Is this a part of this PR ?
</blockquote></details>

Updated comment, thanks for spotting :-)

---

*[flow-server/src/main/java/com/vaadin/router/Title.java, line 29 at r2](https://reviewable.io:443/reviews/vaadin/flow/2601#-Kw-Q1LR9BvyZfdjY977:-Kw-R9G34-Var2axFvWJ:bo9964p) ([raw file](https://github.com/vaadin/flow/blob/7cd2321aec04585c1d28262a16e5993d54b88ffb/flow-server/src/main/java/com/vaadin/router/Title.java#L29)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> Title 

Shouldn't this also be renamed ?
</blockquote></details>

What does @legioth sayeth?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2601)*

**Comment by torok-peter** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-server/src/main/java/com/vaadin/router/Title.java, line 29 at r2](https://reviewable.io:443/reviews/vaadin/flow/2601#-Kw-Q1LR9BvyZfdjY977:-Kw-zDOm_XFvMIZuvYH1:bvn80p) ([raw file](https://github.com/vaadin/flow/blob/7cd2321aec04585c1d28262a16e5993d54b88ffb/flow-server/src/main/java/com/vaadin/router/Title.java#L29)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

What does @legioth sayeth?
</blockquote></details>

Discussed with Leif, answer is yes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2601)*

**Comment by denis-anisimov** [comment]
Reviewed 19 of 19 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2601)*

**Comment by caalador** [comment]
Reviewed 2 of 3 files at r5.
Review status: 18 of 19 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-server/src/main/java/com/vaadin/router/NavigationStateRenderer.java, line 37 at r5](https://reviewable.io:443/reviews/vaadin/flow/2601#-Kw42qZeJaocB826Okch:-Kw42qZeJaocB826Okci:bfnol9j) ([raw file](https://github.com/vaadin/flow/blob/6deac7fff98a4dd1129e13a369b087c7d24a9d3b/flow-server/src/main/java/com/vaadin/router/NavigationStateRenderer.java#L37)):*
> ```Java
> import com.vaadin.ui.UI;
> import com.vaadin.ui.common.HasElement;
> import com.vaadin.util.AnnotationReader;
> ```

Is the AnnotationReader used in this file?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2601)*

**Comment by torok-peter** [comment]
Review status: 18 of 19 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-server/src/main/java/com/vaadin/router/NavigationStateRenderer.java, line 37 at r5](https://reviewable.io:443/reviews/vaadin/flow/2601#-Kw42qZeJaocB826Okch:-Kw44T2L-e9Zu2Zq4aiO:b-e5v1ce) ([raw file](https://github.com/vaadin/flow/blob/6deac7fff98a4dd1129e13a369b087c7d24a9d3b/flow-server/src/main/java/com/vaadin/router/NavigationStateRenderer.java#L37)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Is the AnnotationReader used in this file?
</blockquote></details>

Not anymore - removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2601)*

**Comment by caalador** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2601)*

**Pull request merged**
