### PR TITLE
Report additional browser details to server

### LINKED ISSUE #5717: Report missing browser sizing details
Thanks to feedback on #4320, just realized that we should also report the following details back to the server side with `ExtendedClientDetails` :
- the body element size: `document.body.clientWidth` & `document.body.clientHeight` 
- the window size: `window.innerHeight` & `window.innerWidth`

### PR DESCRIPTION
**Pull request by pleku**
Reports window size, body element size and device pixel ratio to server.
Adds missing IT for touch support and screen sizing.

Fixes #5717, #4864

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/5900)

### CODE REVIEW

**Comment by pleku** [comment]
Blocked by #5879

**Comment by caalador** [comment]
```
[10:25:37]	[Step 5/6] [ERROR] /opt/agent/work/a69251da2b2bb9e9/flow-server/src/main/java/com/vaadin/flow/component/page/ExtendedClientDetails.java:333: error: invalid uri: "https://developer.mozilla
[10:25:37]	[Step 5/6] [ERROR]      * from <a href="https://developer.mozilla
[10:25:37]	[Step 5/6] [ERROR]                ^
[10:25:37]	[Step 5/6] [ERROR]    .org/en-US/docs/Web/API/Window/devicePixelRatio"
```

**Comment by pleku** [comment]
@joheriks we already have Java API for listening for updates to window size. Now the initial value is also known.

**Comment by joheriks** [comment]
Ok. Though technically it is not the initial value, but rather "the value when `Page#retrieveExtendedClientDetails` was called.

**Pull request merged**
