### PR TITLE
Fix CI builds because process might not be finished

### PR DESCRIPTION
**Pull request by manolo**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/5276)

### CODE REVIEW

**Comment by caalador** [comment]
https://teamcity.vaadin.com/repository/download/Flow_FlowTests/46185:id/flow-tests/test-npm/error-screenshots/testIds%5BANY_Chrome_%5D(com.vaadin.flow.npmtest.ui.IdTestIT).png

```
Caused by: java.lang.IllegalStateException: Couldn't find the definition of the element with tag 'my-component' in any template file declared using '@JsModule' annotations. Check the availability of the template files in your WAR file or provide alternative implementation of the method getTemplateContent() which should return an element representing the content of the template file
[06:24:37]W:		 [com.vaadin:flow-test-npm] 	at com.vaadin.flow.component.polymertemplate.NpmTemplateParser.getTemplateContent(NpmTemplateParser.java:114)
```

Possibly the stats is faulty/missing.

**Comment by caalador** [comment]
how could this be merged when the Ci has


[12:21:40][Step 5/6] [INFO] Flow tests for NPM annotation ...................... FAILURE [01:00 min]
[12:21:40][Step 5/6] [INFO] Flow tests for PWA annotation ...................... SKIPPED
[12:21:40][Step 5/6] [INFO] Flow common test UI classes ........................ SKIPPED
[12:21:40][Step 5/6] [INFO] Flow root context tests ............................ SKIPPED
[12:21:40][Step 5/6] [INFO] Flow tests for dev mode ............................ SKIPPED
[12:21:40][Step 5/6] [INFO] Flow root ui context tests ......................... SKIPPED
[12:21:40][Step 5/6] [INFO] Flow Server Production Mode ........................ SKIPPED
[12:21:40][Step 5/6] [INFO] Flow Frontend Resources on custom context test under Production Mode SKIPPED
[12:21:40][Step 5/6] [INFO] Flow Router on custom context test ................. SKIPPED
[12:21:40][Step 5/6] [INFO] Flow tests mapped for /context ..................... SKIPPED
[12:21:40][Step 5/6] [INFO] Flow scalability tests ............................. SKIPPED
[12:21:40][Step 5/6] [INFO] Flow memory leak tests ............................. SKIPPED
[12:21:40][Step 5/6] [INFO] Flow servlet registration test ..................... SKIPPED
[12:21:40][Step 5/6] [INFO] Flow themes tests .................................. SKIPPED
[12:21:40][Step 5/6] [INFO] Flow Lumo theme tests .............................. SKIPPED
[12:21:40][Step 5/6] [INFO] Flow Material theme tests .......................... SKIPPED
[12:21:40][Step 5/6] [INFO] flow-servlet-containers-test ....................... SKIPPED
[12:21:40][Step 5/6] [INFO] Flow WebComponent tests ............................ SKIPPED
[12:21:40][Step 5/6] [INFO] Flow components parent project ..................... SKIPPED
[12:21:40][Step 5/6] [INFO] Flow code generator API ............................ SKIPPED
[12:21:40][Step 5/6] [INFO] Flow code generator ................................ SKIPPED
[12:21:40][Step 5/6] [INFO] Flow component demo helpers ........................ SKIPPED
[12:21:40][Step 5/6] [INFO] Flow Generated Component ........................... SKIPPED
[12:21:40][Step 5/6] [INFO] Flow Bill of Materials ............................. SKIPPED

**Comment by bogdanudrescu** [comment]
It's always failing on that IT test. It used to fail previously.

**Comment by caalador** [comment]
but it should run all other tests still an not quit before sonar. the build is incomplete.

**Comment by bogdanudrescu** [comment]
Temporarily fixed with #5289

**Pull request merged**
