### PR TITLE
refactor: make vaadin-dev-server not depend on fusion-endpoint

### PR DESCRIPTION
**Pull request by platosha**
Connected to: vaadin/hilla#208

Removes dependency on `EnpointGeneratorTaskLibraryImpl` in `vaadin-dev-server` tests.

### CODE REVIEW

**Review by Artur- — COMMENTED** [review]
I am not sure what the relevance of DevModeEndpointTest is after this. What does it test?

**Comment by Artur-** [comment]
Does it actually want to test only that this line is in place https://github.com/vaadin/flow/blob/master/vaadin-dev-server/src/main/java/com/vaadin/base/devserver/startup/DevModeInitializer.java#L289 and it does it through 3 different test methods and using a custom task?

**Comment by platosha** [comment]
> Does it actually want to test only that this line is in place https://github.com/vaadin/flow/blob/master/vaadin-dev-server/src/main/java/com/vaadin/base/devserver/startup/DevModeInitializer.java#L289 and it does it through 3 different test methods and using a custom task?

Yes.

**Comment by platosha** [comment]
Should we just assert the invocation using mocks? Or move the test to the integration module?

**Comment by mshabarov** [comment]
@platosha sorry for keeping this PR for a while without feedback, we'll make the review asap, hopefully tomorrow.

**Comment by mshabarov** [comment]
> Should we just assert the invocation using mocks? Or move the test to the integration module?

IMO it can be a unit test, because it checks that the API is generated after dev server start. I doesn't need to be a end-to-end having browser, user interaction or things like that.

**Review by mshabarov — APPROVED** [review]

**Pull request merged**
