### PR TITLE
DependencyParser should add prefix if needed.

### PR DESCRIPTION
**Pull request by caalador**
The HtmlDependencyParser should store the dependency with
the frontend protocol prefix if relative, else we will load wrong.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3693)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3693#-L7ThoJBOiGqvxZZlK6K:-L7ThoJBOiGqvxZZlK6L:b-azlmsh) (no related file):*
> he HtmlDependencyParser should store the dependency with
> the frontend protocol prefix if relative, else we will load wrong.

It doesn't look like a correct statement.
If I have not a frontend URL in my `HtmlImport` then I don't expect that all relative URLs will be prefixed by `frontend://`.

E.g. if my `@HtmlImport` is `@HtmlImport("http://google.com/somfie.html")` and `somfie.html` has relative imports then they should be relative to the absolute URL , not `frontend` schema.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3693)*

**Comment by denis-anisimov** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3693#-L7ThoJBOiGqvxZZlK6K:-L7TiegC_24HtFva_E2x:b3rrx9y) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> he HtmlDependencyParser should store the dependency with
> the frontend protocol prefix if relative, else we will load wrong.

It doesn't look like a correct statement.
If I have not a frontend URL in my `HtmlImport` then I don't expect that all relative URLs will be prefixed by `frontend://`.

E.g. if my `@HtmlImport` is `@HtmlImport("http://google.com/somfie.html")` and `somfie.html` has relative imports then they should be relative to the absolute URL , not `frontend` schema.
</blockquote></details>

And another question : what's the exact usecase which is fixed by the PR ?
Because relative URLs have been calculated based on the main URL (exactly as I said above), see the `HtmlDependencyParser:relativize` method.
Apparently there is something wrong with the method....
What's this exactly ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3693)*

**Comment by caalador** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/flow/3693#-L7ThoJBOiGqvxZZlK6K:-L7Tlx7r24qgLgovKwpl:bkoqcy4) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

And another question : what's the exact usecase which is fixed by the PR ?
Because relative URLs have been calculated based on the main URL (exactly as I said above), see the `HtmlDependencyParser:relativize` method.
Apparently there is something wrong with the method....
What's this exactly ?
</blockquote></details>

This PR fixes template imports for themes as right now if you have a `vaadin-button` import inside the html it will not load the themed version as the path created dependency resolves wrong.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3693)*

**Comment by denis-anisimov** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/flow/3693#-L7ThoJBOiGqvxZZlK6K:-L7TvTOv4t9AB63TxFGu:b-oh52lb) (no related file):*
>This PR fixes template imports for themes as right now if you have a vaadin-button import inside the html it will not load the themed version as the path created dependency resolves wrong.


Sure, I understand this.
But there are two questions:
- why it doesn't work without this PR? What's broken?
- how does it solve this issue?

I see the call `SharedUtil.prefixIfRelative` for every URI.
I don't think it's correct because of my very first comment.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3693)*

**Comment by caalador** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/flow/3693#-L7ThoJBOiGqvxZZlK6K:-L7TwAhO8zL8Bv696FPX:b-nleksz) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

>This PR fixes template imports for themes as right now if you have a vaadin-button import inside the html it will not load the themed version as the path created dependency resolves wrong.


Sure, I understand this.
But there are two questions:
- why it doesn't work without this PR? What's broken?
- how does it solve this issue?

I see the call `SharedUtil.prefixIfRelative` for every URI.
I don't think it's correct because of my very first comment.

</blockquote></details>

The issue is with development mode and webJars which will not resolve correctly if your relative path doesn't target the correct `frontendPrefix` eg `frontend/bower_components/something/something.html` as without the fix we will in 99.6% of the cases target `bower_components/something/something.html` which will resolve wrong.

Also the  prefix if relative will not affect any http://google.com/somfie.html as it has a protocol.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3693)*

**Comment by denis-anisimov** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/flow/3693#-L7ThoJBOiGqvxZZlK6K:-L7U0d5GBnZFS3tvD3Zl:b2tgi35) (no related file):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

The issue is with development mode and webJars which will not resolve correctly if your relative path doesn't target the correct `frontendPrefix` eg `frontend/bower_components/something/something.html` as without the fix we will in 99.6% of the cases target `bower_components/something/something.html` which will resolve wrong.

Also the  prefix if relative will not affect any http://google.com/somfie.html as it has a protocol.


</blockquote></details>

Apparently there is a misunderstanding so there no way to avoid long writing with examples.

Let's assume I have a class:
```
@HtmlImport("http://myhost.com/foo.html")
class A extends PolymerTemplate {
}
```

The `foo.html` content is:
```
<link rel="import" href="bar.html">
```

The URI `bar.html` is relative to `"http://myhost.com/foo.html"`  and will be prefixed with `frontend`.
Am I correct ?
Please let me know where I'm wrong.
If I'm right then the logic is wrong.

And currently each URL is resolved using the `HtmlDependencyParser::relativize` method.

So in the case above the URI will be rewritten as : `"http://myhost.com/bar.html"` which is correct.

If I have a class
```
@HtmlImport("frontend://foo.html")
class A extends PolymerTemplate {
}
```
then again the method mentioned above will relativize the URI as : "frontend://bar.html" which is correct.

So: please show me a usecase with java class +`HtmlImport` + URL inside it + its content with relative path which 
is not covered by the current logic (so that the resulting URI is wrong).

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3693)*

**Comment by caalador** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/flow/3693#-L7ThoJBOiGqvxZZlK6K:-L7U2mh0EOF4IuoK9pOY:b-qnppgw) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Apparently there is a misunderstanding so there no way to avoid long writing with examples.

Let's assume I have a class:
```
@HtmlImport("http://myhost.com/foo.html")
class A extends PolymerTemplate {
}
```

The `foo.html` content is:
```
<link rel="import" href="bar.html">
```

The URI `bar.html` is relative to `"http://myhost.com/foo.html"`  and will be prefixed with `frontend`.
Am I correct ?
Please let me know where I'm wrong.
If I'm right then the logic is wrong.

And currently each URL is resolved using the `HtmlDependencyParser::relativize` method.

So in the case above the URI will be rewritten as : `"http://myhost.com/bar.html"` which is correct.

If I have a class
```
@HtmlImport("frontend://foo.html")
class A extends PolymerTemplate {
}
```
then again the method mentioned above will relativize the URI as : "frontend://bar.html" which is correct.

So: please show me a usecase with java class +`HtmlImport` + URL inside it + its content with relative path which 
is not covered by the current logic (so that the resulting URI is wrong).
</blockquote></details>

The bar.html will not be prefixed as it will get `http://` from the import of `foo.html` and thus has a prefix.

The "old" implementation will fail in the simplest case of our skeleton starter where you have the exampletemplate class
```
@Tag("example-template")
@HtmlImport("src/example-template.html")
public class ExampleTemplate extends PolymerTemplate<ExampleModel> {
}
```
The actual import will get everything correct as it goes through the loops where it receives `frontend://`at some time in space, but the parser will parse without it and the dependency loading will fail on not found.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3693)*

**Comment by caalador** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/flow/3693#-L7ThoJBOiGqvxZZlK6K:-L7U3sycA8ZQpxXCTV3v:b-v8tzb3) (no related file):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

The bar.html will not be prefixed as it will get `http://` from the import of `foo.html` and thus has a prefix.

The "old" implementation will fail in the simplest case of our skeleton starter where you have the exampletemplate class
```
@Tag("example-template")
@HtmlImport("src/example-template.html")
public class ExampleTemplate extends PolymerTemplate<ExampleModel> {
}
```
The actual import will get everything correct as it goes through the loops where it receives `frontend://`at some time in space, but the parser will parse without it and the dependency loading will fail on not found.
</blockquote></details>

The bar.html will have a  `protocol`/`scheme` according to the https://tools.ietf.org/html/rfc3986#section-3.1 specification 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3693)*

**Comment by denis-anisimov** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/flow/3693#-L7ThoJBOiGqvxZZlK6K:-L7U4q6j5aFpoMkulCf8:bk66qa0) (no related file):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

The bar.html will have a  `protocol`/`scheme` according to the https://tools.ietf.org/html/rfc3986#section-3.1 specification 
</blockquote></details>

Aaah, OK.
Got it, thanks.

The thing which confused me is: you check the relative URIs for the dependent  URIs (after their relativization) not the original URL.

Would it be better to prefix the original URI only once with `frontend` instead doing that for every dependent URI ?
(so that they will automatically gets the prefix after relativization) ?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3693)*

**Comment by caalador** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/flow/3693#-L7ThoJBOiGqvxZZlK6K:-L7U9ZQF67UPJCn2g1Fq:b-896fix) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Aaah, OK.
Got it, thanks.

The thing which confused me is: you check the relative URIs for the dependent  URIs (after their relativization) not the original URL.

Would it be better to prefix the original URI only once with `frontend` instead doing that for every dependent URI ?
(so that they will automatically gets the prefix after relativization) ?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3693)*

**Comment by denis-anisimov** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3693#-:-L7UHB3O0wEKbdK8lVyd:bnfp4nl)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3693)*

**Comment by gilberto-torrezan** [comment]
:lgtm:

---

Reviewed 7 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3693#-:-L7Uwg2nVG1Av9mCbrk7:bnfp4nl)*

**Pull request merged**
