### PR TITLE
Add a tutorial for basic renderers.

### PR DESCRIPTION
**Pull request by gilberto-torrezan**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3164)

### CODE REVIEW

**Comment by ahie** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[flow-documentation/flow-components/tutorial-flow-grid.asciidoc, line 309 at r1](https://reviewable.io:443/reviews/vaadin/flow/3164#-L0OJWNVlyy-Bjx81xN1:-L0OJWNVlyy-Bjx81xN2:b-rfcfc2) ([raw file](https://github.com/vaadin/flow/blob/33d6ac3b9ddda1ed55a1883ed8efe172f90d550b/flow-documentation/flow-components/tutorial-flow-grid.asciidoc#L309)):*
> The renderers are separated in three categories:

Would change to:

> Conceptually renderers are split into the three categories listed below.

---

*[flow-documentation/flow-components/tutorial-flow-grid.asciidoc, line 317 at r1](https://reviewable.io:443/reviews/vaadin/flow/3164#-L0OIy7HWRzqSB2CFvcJ:-L0OIy7HWRzqSB2CFvcK:b-sx2qtc) ([raw file](https://github.com/vaadin/flow/blob/33d6ac3b9ddda1ed55a1883ed8efe172f90d550b/flow-documentation/flow-components/tutorial-flow-grid.asciidoc#L317)):*
> There are several basic renderers that can be used to configure Grid columns:

Would change to:

>There are several basic renderers that can be used to configure Grid columns. The currently supported basic renderers are gathered here under their own subsections.

---

*[flow-documentation/flow-components/tutorial-flow-grid.asciidoc, line 378 at r1](https://reviewable.io:443/reviews/vaadin/flow/3164#-L0OLAns1p_u6_jOhiHz:-L0OLAns1p_u6_jOhiI-:b-mqxn6b) ([raw file](https://github.com/vaadin/flow/blob/33d6ac3b9ddda1ed55a1883ed8efe172f90d550b/flow-documentation/flow-components/tutorial-flow-grid.asciidoc#L378)):*
> in the client/server side

on the client/server side

---

*[flow-documentation/flow-components/tutorial-flow-grid.asciidoc, line 392 at r1](https://reviewable.io:443/reviews/vaadin/flow/3164#-L0OIhy15nUmMAjvgmRs:-L0OIhy15nUmMAjvgmRt:b-te1ol5) ([raw file](https://github.com/vaadin/flow/blob/33d6ac3b9ddda1ed55a1883ed8efe172f90d550b/flow-documentation/flow-components/tutorial-flow-grid.asciidoc#L392)):*
> ```AsciiDoc
> ----
> grid.addColumn(
>                 new ButtonRenderer<>(item -> "Remove " + item, clickedItem -> {
> ```

Formatting looks a bit broken here.

---

*[flow-documentation/flow-components/tutorial-flow-grid.asciidoc, line 432 at r1](https://reviewable.io:443/reviews/vaadin/flow/3164#-L0OIlRM4quKRwEfVpdg:-L0OIlRM4quKRwEfVpdh:brhumzt) ([raw file](https://github.com/vaadin/flow/blob/33d6ac3b9ddda1ed55a1883ed8efe172f90d550b/flow-documentation/flow-components/tutorial-flow-grid.asciidoc#L432)):*
> ```AsciiDoc
> ----
> grid.addColumn(
>                 TemplateRenderer.<Person> of("[[item.age]] years old")
> ```

Same here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3164)*

**Comment by ahie** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3164)*

**Comment by gilberto-torrezan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[flow-documentation/flow-components/tutorial-flow-grid.asciidoc, line 309 at r1](https://reviewable.io:443/reviews/vaadin/flow/3164#-L0OJWNVlyy-Bjx81xN1:-L0OU78fMKaW9KSf8hQG:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/33d6ac3b9ddda1ed55a1883ed8efe172f90d550b/flow-documentation/flow-components/tutorial-flow-grid.asciidoc#L309)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

> The renderers are separated in three categories:

Would change to:

> Conceptually renderers are split into the three categories listed below.
</blockquote></details>

Done.

---

*[flow-documentation/flow-components/tutorial-flow-grid.asciidoc, line 317 at r1](https://reviewable.io:443/reviews/vaadin/flow/3164#-L0OIy7HWRzqSB2CFvcJ:-L0OU5p33LzbpSQazZ8E:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/33d6ac3b9ddda1ed55a1883ed8efe172f90d550b/flow-documentation/flow-components/tutorial-flow-grid.asciidoc#L317)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

> There are several basic renderers that can be used to configure Grid columns:

Would change to:

>There are several basic renderers that can be used to configure Grid columns. The currently supported basic renderers are gathered here under their own subsections.
</blockquote></details>

Done.

---

*[flow-documentation/flow-components/tutorial-flow-grid.asciidoc, line 378 at r1](https://reviewable.io:443/reviews/vaadin/flow/3164#-L0OLAns1p_u6_jOhiHz:-L0OU3oPtuntMo2eKKkB:b-7s63uh) ([raw file](https://github.com/vaadin/flow/blob/33d6ac3b9ddda1ed55a1883ed8efe172f90d550b/flow-documentation/flow-components/tutorial-flow-grid.asciidoc#L378)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

> in the client/server side

on the client/server side
</blockquote></details>

dONe.

---

*[flow-documentation/flow-components/tutorial-flow-grid.asciidoc, line 392 at r1](https://reviewable.io:443/reviews/vaadin/flow/3164#-L0OIhy15nUmMAjvgmRs:-L0OQOFT-X2c6QcI_mUF:b-qorvhk) ([raw file](https://github.com/vaadin/flow/blob/33d6ac3b9ddda1ed55a1883ed8efe172f90d550b/flow-documentation/flow-components/tutorial-flow-grid.asciidoc#L392)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

Formatting looks a bit broken here.
</blockquote></details>

That is the formatting generated in the source code by Eclipse (I just copy-pasted it here). I'll add some `//@formatter:off` comments in the source code to make it more friendly for the docs.

Done.

---

*[flow-documentation/flow-components/tutorial-flow-grid.asciidoc, line 432 at r1](https://reviewable.io:443/reviews/vaadin/flow/3164#-L0OIlRM4quKRwEfVpdg:-L0OU1PJxHExTw7XiQXC:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/33d6ac3b9ddda1ed55a1883ed8efe172f90d550b/flow-documentation/flow-components/tutorial-flow-grid.asciidoc#L432)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3164)*

**Comment by ahie** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3164#-:-L0OUSGwfs11u_TVSP9P:bnfp4nl)*

**Comment by gilberto-torrezan** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3164#-L0OnHwMfPwlOP31Nq4h:-L0OnHwNsNBDR-qZiDKz:b-hlqda5) (no related file):*
Well, due to the package renames this PR will have lots of problems with package conflicts and so on. I can't make it compile in my own machine right now, for instance. This PR will have to wait until all changes are made.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3164)*

**Comment by denis-anisimov** [comment]
Needs manual rebase

**Comment by ahie** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3164)*

**Pull request merged**
