### PR TITLE
Add vaadin-core to the starter

### PR DESCRIPTION
**Pull request by mstahv**
Most people will need the basic components, so it should be included in the
starter.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3682)

### CODE REVIEW

**Comment by pleku** [comment]
Thanks! I think you also need to change this:
https://github.com/mstahv/flow/blob/6cdcab0ca2ecffc40f45682997bb0c05d8b77462/flow-spring-boot-starter/src/main/resources/META-INF/spring.provides#L1
I have no idea what that means, but now we are providing a whole lot more than just flow and html components.

**Comment by mstahv** [comment]
I think we are already providing more at this point. As all our components are now in separate packages, the list would actually be huge for us.

If I understood properly based on my googling (https://github.com/spring-projects/spring-boot/issues/1926) it helps with some suggestions with STS (Spring IDE). The feature is not very well documented so, I'm not sure how important that really is. Any insights @snicoll ?

**Comment by snicoll** [comment]
Yeah, I agree it's not very well documented. I've created https://github.com/spring-projects/spring-boot/issues/12435

I wouldn't provide a huge list. One or two items should be enough.

**Comment by pleku** [comment]
Actually, we realized that now the time has come to kick out the Spring-addon for Vaadin Flow outside of Flow's basement. It will go on and live in the woods.

This means that this PR is unnecessary for now, as it introduces circular dependencies instead of fixing the underlying issue - the starter should not depend on Flow or the add-on but on the platform.

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3682#-:-L7TmdUxXdGEgWyJwLO1:b-l9ekpo)*

**Comment by pleku** [comment]
Issue for moving spring add-on https://github.com/vaadin/flow/issues/3695

**Pull request closed without merging**
