### PR TITLE
fix: Allow access to /favicon even when the vaadin mapping is /something

### LINKED ISSUE #16371: Infinite redirect loop when the browser tries to fetch favicon.ico and you use Spring Security
### Description of the bug

When the browser fetches `favicon.ico` it adds a `Sec-Fetch-Dest: image` header to the request. This is checked by `IndexHtmlRequestHandler` so that it does not return an index page for the request, just like it should.

When you use Spring Security and the browser requests `/favicon.ico` though, it redirects to the login page. If this login page is implemented as a Flow view, no index page will be returned. Then Spring Security will redirect to the login page, again, even though the URL currently being fetched is already the login page.

Then the browser gives up after a while with an error like
```
GET http://localhost:8888/urlmapping/my/login/page net::ERR_TOO_MANY_REDIRECTS
```

### Expected behavior

There should certainly not be a redirect loop

### Minimal reproducible example

Can be reproduced using the `flow-tests/vaadin-spring-tests/test-spring-security-flow-urlmapping` test by either opening http://localhost:8888/public/public.txt in the browser or by using
```
curl 'http://localhost:8888/favicon.ico' -H 'Sec-Fetch-Dest: image' -L
```
which results in
```
curl: (47) Maximum (50) redirects followed
```

### Versions

- Vaadin / Flow version: 24.0.1

### PR DESCRIPTION
**Pull request by Artur-**
Allow accessing the error page in security tests so that the 404 is sent to the browser

Fixes #16371

### CODE REVIEW

**Review by mcollovati — DISMISSED** [review]

**Comment by mcollovati** [comment]
Tests are passing locally.
I don't understand why there's a 403 error for `/VAADIN/push` requests on validation build.
In `VaadinWebSecurity` there's a `permitAll` matcher for `/VAADIN/**` 

```
Error:  access_restricted_to_logged_in_users[ANY_Chrome_]  Time elapsed: 5.733 s  <<< FAILURE!
java.lang.AssertionError: Received error message in browser log console right after opening the page, message: [2023-03-23T13:50:51.269Z] [SEVERE] http://localhost:8888/VAADIN/push?v-r=push&v-uiId=2&v-pushId=041720da-95b7-411a-87eb-52ea754187c2&X-Atmosphere-Transport=close&X-Atmosphere-tracking-id=d82d90da-7706-4dae-be2f-88b774cdc698&X-Vaadin-LastSeenServerSyncId=4 - Failed to load resource: the server responded with a status of 403 ()
```

**Comment by Artur-** [comment]
There is more logging in this build https://github.com/vaadin/flow/actions/runs/4500880953/jobs/7920644827?pr=15865 that has the reason
```
2023-03-23T13:18:52.601Z DEBUG 7543 --- [nio-8888-exec-3] o.s.security.web.csrf.CsrfFilter         : Invalid CSRF token found for http://localhost:8888/VAADIN/push?v-r=push&v-uiId=0&v-pushId=0566a788-a56a-4a79-8d65-878b32f8cc4f&X-Atmosphere-Transport=close&X-Atmosphere-tracking-id=48b555c8-b989-44e7-8141-5124ba7185bb&X-Vaadin-LastSeenServerSyncId=3
```

As it is only the push close message that can happen e.g. after you log out, I added an ignore for it

**Review by mcollovati — APPROVED** [review]

**Review by czp13 — DISMISSED** [review]

**Review by mcollovati — CHANGES_REQUESTED** [review]

**Comment by Artur-** [comment]
Fine, lesson learned once again: Don't use regexp

**Comment by mcollovati** [comment]
> Fine, lesson learned once again: Don't use regexp

It was a missing ".*" at the end. I missed it twice :sob:

**Review by mcollovati — APPROVED** [review]

**Review by mcollovati — APPROVED** [review]

**Pull request merged**
