### PR TITLE
chore: Use proper version for jackson-databind

### PR DESCRIPTION
**Pull request by mshabarov**

### CODE REVIEW

**Review by Artur- — CHANGES_REQUESTED** [review]
Why would you do that? What does "proper" mean?

**Review by Artur- — APPROVED** [review]
Ah crap, I read it the wrong way

**Comment by Artur-** [comment]
Was a bit confused there for a second..

**Comment by mshabarov** [comment]
`jackson-databind` used other version which is for other jackson dependencies. This is the only place where the common version used, other places uses `jackson.databind.version` as well.

**Pull request merged**
