### PR TITLE
fix: Use context class loader for class finder

### PR DESCRIPTION
**Pull request by Artur-**
Fixes https://github.com/vaadin/hilla/issues/791

### CODE REVIEW

**Comment by platosha** [comment]
Would it be a good idea to add a unit test using a mock here?

**Comment by Artur-** [comment]
Probably, but what should we test? Explicilty that the code uses the context classloader?

**Comment by platosha** [comment]
Yes, and not the class loader from classes or elsewhere.

**Comment by Artur-** [comment]
Added a basic test

**Review by mshabarov — APPROVED** [review]
I understand that the previous code had a moving parts with picking first class loader from the set. Now the context class loader is used that makes the class loading more deterministic. But I still not sure that this approach wouldn't raise other issue with classloading in application servers. Would ask for one more reviewer to check this PR.

**Comment by Artur-** [comment]
It is not only to be deterministic, but if you do not use the restart class loader in a spring boot application then you will not get the latest classes after a dev tools restart. This is the Hilla issue that changes in classes are not picked up after a dev tools restart

**Pull request merged**
