### PR TITLE
Add API for checking if property is a sub-property of it's property set

### PR DESCRIPTION
**Pull request by pekam**
It's useful to know whether a property definition belongs directly to the property set or is it a sub-property of some other property in the set. This can be used for example in the implementation of BeanGrid, to add columns automatically only for the bean's direct properties. Previously there was no way of differentiating between direct properties and sub-properties.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3095)

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3095)*

**Comment by SomeoneToIgnore** [comment]
*[flow-data/src/test/java/com/vaadin/data/BeanPropertySetTest.java, line 229 at r1](https://reviewable.io:443/reviews/vaadin/flow/3095#-L-WJHbEIqJpLc7IJk_4:-L-WJHbEIqJpLc7IJk_5:b1fyzfd) ([raw file](https://github.com/vaadin/flow/blob/9527ea5f7569ae1096e893381fa1bf20ff70e33f/flow-data/src/test/java/com/vaadin/data/BeanPropertySetTest.java#L229)):*
> ```Java
>                 .get(FatherAndSon.class);
> 
>         Assert.assertTrue(propertySet.getProperty("father.firstName").get()
> ```

As a small note, some check comments would be nice, otherwise it's really hard to understand why and what had failed.
You can make the test fail and think if you can understand what's happening by the output.
But up to you.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3095)*

**Comment by pekam** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-data/src/test/java/com/vaadin/data/BeanPropertySetTest.java, line 229 at r1](https://reviewable.io:443/reviews/vaadin/flow/3095#-L-WJHbEIqJpLc7IJk_4:-L-WMdywIkAR8HVNJsNf:b802a7t) ([raw file](https://github.com/vaadin/flow/blob/9527ea5f7569ae1096e893381fa1bf20ff70e33f/flow-data/src/test/java/com/vaadin/data/BeanPropertySetTest.java#L229)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

As a small note, some check comments would be nice, otherwise it's really hard to understand why and what had failed.
You can make the test fail and think if you can understand what's happening by the output.
But up to you.
</blockquote></details>

Comments added

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3095)*

**Comment by SomeoneToIgnore** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3095#-:-L-WMpSyLwy3JrMo_l01:bnfp4nl)*

**Pull request merged**
