### PR TITLE
Add registration creation shorthands

### PR DESCRIPTION
**Pull request by Legioth**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/7383)

### CODE REVIEW

**Comment by pleku** [comment]
Javadocs failing due to
```
/opt/agent/work/a69251da2b2bb9e9/flow-server/src/main/java/com/vaadin/flow/shared/GwtIncompatible.java:28: error: reference not found
 * @see com.google.gwt.core.shared.GwtIncompatible
```

**Comment by pleku** [comment]
I guess the failing ITs are related to the change https://teamcity.vaadin.com/viewLog.html?buildId=58114&buildTypeId=Flow_FlowTests&tab=buildResultsDiv

**Comment by mehdi-vaadin** [comment]
I this targeted for Flow 2.2?

**Comment by caalador** [comment]
Needs merge from master and conflict resolution.

**Comment by Legioth** [comment]
The `+1.0.0` label is only because of `default serialVersionUID changed`, which isn't something we guarantee between minor versions.

**Comment by mehdi-vaadin** [comment]
What are the targets of this PR? Should it be ported to `3.0` and `2.2`?

**Comment by pleku** [comment]
>I was unable to backport this PR to "2.2" cleanly;
you will need to perform this backport manually.

@Legioth up to you if you want to do it or not

**Comment by Legioth** [comment]
Cherry pick to 2.2 in https://github.com/vaadin/flow/pull/7698.

**Pull request merged**
