### PR TITLE
Introduce DataGenerators

### PR DESCRIPTION
**Pull request by ahie**
Refactors grid selection models and columns to use data generators.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/2850)

### CODE REVIEW

**Comment by gilberto-torrezan** [comment]
Reviewed 6 of 7 files at r1, 1 of 1 files at r2.
Review status: 6 of 7 files reviewed at latest revision, 9 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2850#-KyGJyfvvmevT9Am3AwE:-KyGJyfwWA60pJzdCZhj:b-801dy0) (no related file):*
Is there any test (unit or integration) that could be ported from FW8 for this feature in Flow?

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/AbstractGridSingleSelectionModel.java, line 45 at r2](https://reviewable.io:443/reviews/vaadin/flow/2850#-KyGJciLPlAroE__klLe:-KyGJciLPlAroE__klLf:bdnclq0) ([raw file](https://github.com/vaadin/flow/blob/656f8f4faaa96fe1c4fb69ba87f1aa5348351c8c/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/AbstractGridSingleSelectionModel.java#L45)):*
> ```Java
>         implements GridSingleSelectionModel<T>, DataGenerator<T> {
> 
>     private T selectedItem = null;
> ```

No need to initialize it as `null`. Minor.

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/AbstractGridSingleSelectionModel.java, line 139 at r2](https://reviewable.io:443/reviews/vaadin/flow/2850#-KyGJPvywLPx6tzZTzua:-KyGJPvywLPx6tzZTzub:byzzjkq) ([raw file](https://github.com/vaadin/flow/blob/656f8f4faaa96fe1c4fb69ba87f1aa5348351c8c/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/AbstractGridSingleSelectionModel.java#L139)):*
> ```Java
>     public Registration addSelectionListener(SelectionListener<T> listener) {
>         Objects.requireNonNull(listener, "listener cannot be null");
>         return getGrid().addListener(SingleSelectionEvent.class,
> ```

Is this right? `SelectionListeners` will listen to `SingleSelectionEvents` (just like the method below) ?

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 474 at r1](https://reviewable.io:443/reviews/vaadin/flow/2850#-KyFPbcB0PB9Ukv0wnPP-r1-474:-KyGIQIA32Qxm665v1Yc:bhrroqb) ([raw file](https://github.com/vaadin/flow/blob/b9fa334994d08c02bd4be85cc96434dcb2ec59a0/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L474)):*
<details><summary><i>Previously, vaadin-bot (Vaadin Bot) wrote…</i></summary><blockquote>

CRITICAL Reorder the modifiers to comply with the Java Language Specification. [rule](https://sonar.projects.vaadin.com/coding_rules#rule_key=squid%3AModifiersOrderCheck)
</blockquote></details>

It should be `public abstract static class`

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 999 at r1](https://reviewable.io:443/reviews/vaadin/flow/2850#-KyFPbcB0PB9Ukv0wnPP-r1-999:-KyGIit4xMUrwXFiRijn:b-42l773) ([raw file](https://github.com/vaadin/flow/blob/b9fa334994d08c02bd4be85cc96434dcb2ec59a0/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L999)):*
<details><summary><i>Previously, vaadin-bot (Vaadin Bot) wrote…</i></summary><blockquote>

MINOR Remove useless curly braces around statement [rule](https://sonar.projects.vaadin.com/coding_rules#rule_key=squid%3AS1602)
</blockquote></details>

Upvote for this one

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2850)*

**Comment by gilberto-torrezan** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2850)*

**Comment by ahie** [comment]
Review status: 5 of 7 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2850#-KyGJyfvvmevT9Am3AwE:-KyGMGYdjS2Fy9ABwv5N:bp0eo8s) (no related file):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Is there any test (unit or integration) that could be ported from FW8 for this feature in Flow?
</blockquote></details>

Not really. The new addition is just an interface and existing functionality has been refactored to use it, so the existing tests should cover this.

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/AbstractGridSingleSelectionModel.java, line 45 at r2](https://reviewable.io:443/reviews/vaadin/flow/2850#-KyGJciLPlAroE__klLe:-KyGQR7tX0nIKGbO9n5n:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/656f8f4faaa96fe1c4fb69ba87f1aa5348351c8c/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/AbstractGridSingleSelectionModel.java#L45)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

No need to initialize it as `null`. Minor.
</blockquote></details>

Done.

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/AbstractGridSingleSelectionModel.java, line 139 at r2](https://reviewable.io:443/reviews/vaadin/flow/2850#-KyGJPvywLPx6tzZTzua:-KyGQUBk5vWgUyTEDdun:b-ln6gf9) ([raw file](https://github.com/vaadin/flow/blob/656f8f4faaa96fe1c4fb69ba87f1aa5348351c8c/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/AbstractGridSingleSelectionModel.java#L139)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Is this right? `SelectionListeners` will listen to `SingleSelectionEvents` (just like the method below) ?
</blockquote></details>

`addListener` only takes `ComponentEvent`s, and Single/MultiSelectionEvents extend a different type of component event, so a `SelectionEvent` cannot be used directly. This should have no undesired effect, because the single selection model only fires single selection events in the first place.

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 474 at r1](https://reviewable.io:443/reviews/vaadin/flow/2850#-KyFPbcB0PB9Ukv0wnPP-r1-474:-KyGQQG4U4j3CeVxyzev:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/b9fa334994d08c02bd4be85cc96434dcb2ec59a0/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L474)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

It should be `public abstract static class`
</blockquote></details>

Done.

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 999 at r1](https://reviewable.io:443/reviews/vaadin/flow/2850#-KyFPbcB0PB9Ukv0wnPP-r1-999:-KyGQPljKh_7N3Y501C4:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/b9fa334994d08c02bd4be85cc96434dcb2ec59a0/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L999)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Upvote for this one
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2850)*

**Comment by gilberto-torrezan** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2850)*

**Pull request merged**
