### PR TITLE
AbstractSinglePropertyField should return the correct propertyName

### PR DESCRIPTION
**Pull request by manolo**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/4024)

### CODE REVIEW

**Comment by Legioth** [comment]
Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---

*[flow-server/src/main/java/com/vaadin/flow/component/AbstractSinglePropertyField.java, line 295 at r1](https://reviewable.io/reviews/vaadin/flow/4024#-LB5CHNF2ykO8qtNuUDn:-LB5CHNF2ykO8qtNuUDo:bbbym6u) ([raw file](https://github.com/vaadin/flow/blob/43b59fbb59acc4395b3a4bd5b6c767abd3d32958/flow-server/src/main/java/com/vaadin/flow/component/AbstractSinglePropertyField.java#L295)):*
> ```Java
> 
>     @Override
>     public String getClientValuePropertyName() {
> ```

Might be a problem that method will be removed from `HasValue` by #4003. Why is this needed?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4024)*

**Comment by manolo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-server/src/main/java/com/vaadin/flow/component/AbstractSinglePropertyField.java, line 295 at r1](https://reviewable.io/reviews/vaadin/flow/4024#-LB5CHNF2ykO8qtNuUDn:-LB5Qw9AAT3oVEg4pZvd:bsqxe8d) ([raw file](https://github.com/vaadin/flow/blob/43b59fbb59acc4395b3a4bd5b6c767abd3d32958/flow-server/src/main/java/com/vaadin/flow/component/AbstractSinglePropertyField.java#L295)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

Might be a problem that method will be removed from `HasValue` by #4003. Why is this needed?
</blockquote></details>

`HasValueChangeMode` needs it 

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4024)*

**Comment by Legioth** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-server/src/main/java/com/vaadin/flow/component/AbstractSinglePropertyField.java, line 295 at r1](https://reviewable.io/reviews/vaadin/flow/4024#-LB5CHNF2ykO8qtNuUDn:-LB5RAMX6gbUhm5E9EKG:by9hv81) ([raw file](https://github.com/vaadin/flow/blob/43b59fbb59acc4395b3a4bd5b6c767abd3d32958/flow-server/src/main/java/com/vaadin/flow/component/AbstractSinglePropertyField.java#L295)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

`HasValueChangeMode` needs it 
</blockquote></details>

The default methods in `HasValueChangeMode` will also be removed by #4003. Instead, you should follow the new pattern that is used in `com.vaadin.flow.data.value.ValueChangeModeTest.ValueChangeModeField.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4024)*

**Comment by manolo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-server/src/main/java/com/vaadin/flow/component/AbstractSinglePropertyField.java, line 295 at r1](https://reviewable.io/reviews/vaadin/flow/4024#-LB5CHNF2ykO8qtNuUDn:-LB5RUF6EN2BAY2DbesI:b-5cmq8g) ([raw file](https://github.com/vaadin/flow/blob/43b59fbb59acc4395b3a4bd5b6c767abd3d32958/flow-server/src/main/java/com/vaadin/flow/component/AbstractSinglePropertyField.java#L295)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

The default methods in `HasValueChangeMode` will also be removed by #4003. Instead, you should follow the new pattern that is used in `com.vaadin.flow.data.value.ValueChangeModeTest.ValueChangeModeField.
</blockquote></details>

yep, after 4003 is merged this is not needed, Is it being to be merged soon? then I don't think we need this in the meanwhile

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4024)*

**Comment by Legioth** [comment]
*[flow-server/src/main/java/com/vaadin/flow/component/AbstractSinglePropertyField.java, line 295 at r1](https://reviewable.io/reviews/vaadin/flow/4024#-LB5CHNF2ykO8qtNuUDn:-LB5SEbv2UAiS7t07PLj:bvm1hp0) ([raw file](https://github.com/vaadin/flow/blob/43b59fbb59acc4395b3a4bd5b6c767abd3d32958/flow-server/src/main/java/com/vaadin/flow/component/AbstractSinglePropertyField.java#L295)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

yep, after 4003 is merged this is not needed, Is it being to be merged soon? then I don't think we need this in the meanwhile
</blockquote></details>

You don't need this before #4003 either, you can just use the new pattern right away by explicitly implementing `setValueChangeMode` instead of relying on the default implementation that will be removed.

The original plan was to merge #4003 only after all components have been updated to avoid breaking things up-front, but it might actually maybe make sense to merge it right away so that it's easier to make correct updated to the components?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4024)*

**Comment by manolo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-server/src/main/java/com/vaadin/flow/component/AbstractSinglePropertyField.java, line 295 at r1](https://reviewable.io/reviews/vaadin/flow/4024#-LB5CHNF2ykO8qtNuUDn:-LB5XU5aBadVpHdXntkm:b6gbkor) ([raw file](https://github.com/vaadin/flow/blob/43b59fbb59acc4395b3a4bd5b6c767abd3d32958/flow-server/src/main/java/com/vaadin/flow/component/AbstractSinglePropertyField.java#L295)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

You don't need this before #4003 either, you can just use the new pattern right away by explicitly implementing `setValueChangeMode` instead of relying on the default implementation that will be removed.

The original plan was to merge #4003 only after all components have been updated to avoid breaking things up-front, but it might actually maybe make sense to merge it right away so that it's easier to make correct updated to the components?
</blockquote></details>

I'd rather have those asap

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4024)*

**Comment by manolo** [comment]
Abandoning, not needed.

**Pull request closed without merging**
