### PR TITLE
fix: Look up for theme resource in static resource folder

### PR DESCRIPTION
**Pull request by mshabarov**
Looks up for the static resource in the app's class-path needed for custom theme ~and inlines the content of it into style tag, like it's done for development mode~. This resolves `url(./images/foo.png)` inside CSS properly if a resource is located in the static resource directory, not in the theme folder.

Fixes https://github.com/vaadin/flow/issues/16780

### CODE REVIEW

**Comment by Artur-** [comment]
This would make it impossible for the browser to cache the css

**Comment by mshabarov** [comment]
> This would make it impossible for the browser to cache the css

We have a lots of other styles generated by Flow and inlined on the page. With inline style you don't need an extra request to the server, so in some cases it's beneficial. However, suddenly I start to think about looking up for the resource in the static resources folder in 
```java
    public static URL getThemeResourceFromPrecompiledProductionBundle(
            String themeAssetPath) {
        // lookup in the prod bundle, where themes are copied from project's
        URL resourceUrl = ThemeUtils.class.getClassLoader()
                .getResource(Paths.get(VAADIN_WEBAPP_RESOURCES,
                        VAADIN_STATIC_FILES_PATH, themeAssetPath).toString());
        if (resourceUrl == null) {
            // lookup in the JARs for packaged themes
            resourceUrl = ThemeUtils.class.getClassLoader().getResource(
                    Constants.RESOURCES_JAR_DEFAULT + themeAssetPath);
        }

        // Add this:
        if (resourceUrl == null) {
            // trim 'themes/my-theme/' and look up in the static resources:
            resourceUrl = getStaticResource(trimmedFilenameWithPath);
        }
        return resourceUrl;
    }
```

**Comment by Artur-** [comment]
> We have a lots of other styles generated by Flow and inlined on the page
Should they be done that way?

**Comment by mshabarov** [comment]
Not an option, as it might expose static resources wrapped into theme request.

**Pull request closed without merging**
