### PR TITLE
Allow `@Route` and `@ParentLayout` in same target.

### PR DESCRIPTION
**Pull request by caalador**
This has been added due to a reading mistake
`... @ParentConfigurer or @ParentLayout.  It is not allowed to have both annotations on the same class.`

One issue with the documented method of instead of having `@ParentLayout`
and depending on the `@Route(layout)` is that with `@RouteAlias` we wouldn't
know what to use.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3424)

### CODE REVIEW

**Comment by pleku** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3424#-L40hgLs8e6Bi-zMqynT:-L40hgLs8e6Bi-zMqynU:b-b1lf0r) (no related file):*
Can you also verify with tests that the parent layout is not changed in a situation where it should stay the same:
1) there is no child for the parent layout but then it opens a child target A
2) the child navigation target should changes from A to B ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3424)*

**Comment by caalador** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3424#-L40hgLs8e6Bi-zMqynT:-L40nFXRlQNL4ot3dIfq:bb7f2mf) (no related file):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Can you also verify with tests that the parent layout is not changed in a situation where it should stay the same:
1) there is no child for the parent layout but then it opens a child target A
2) the child navigation target should changes from A to B ?
</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3424)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 2 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3424)*

**Comment by caalador** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3424#-L413cyDf3ZeUaRS4hG5:-L413cyEKZD4TUoLVF4p:bjpjk8e) (no related file):*
I'll add some more tests on this tomorrow.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3424)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 2 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3424)*

**Pull request merged**
