### PR TITLE
Do not remove href attribute when empty

### LINKED ISSUE #2704: new Anchor("", "home") should create <a href="">home</a>
At the moment it creates a `<a>home</a>` without the `href` attribute at all.

(flow-1.0.0.alpha3)

### PR DESCRIPTION
**Pull request by heruan**
Should fix #2704. I didn't find where tests for basic HTML elements are, but I'll commit those if someone point me in the right direction!

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/2718)

### CODE REVIEW

**Comment by torok-peter** [comment]
Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2718)*

**Comment by heruan** [comment]
*[flow-html-components/src/test/java/com/vaadin/ui/html/ComponentTest.java, line 283 at r1](https://reviewable.io:443/reviews/vaadin/flow/2718#-KwnCkHncKM-PR3AJroU:-KwnnPw9O35Od-FKfHxH:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/8efed481aea2ee459b1a69d9b8d84b93bba08985/flow-html-components/src/test/java/com/vaadin/ui/html/ComponentTest.java#L283)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> if (property.removeDefault) {
>                 assertNoPropertyOrAttribute(component, property.name);
>             }

This check is for the case when default value is removed.
The opposite check is required as well: if property should keep it's default value then HTML element needs a check that the property is there and it has the default value.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2718)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-html-components/src/test/java/com/vaadin/ui/html/ComponentTest.java, line 303 at r2](https://reviewable.io:443/reviews/vaadin/flow/2718#-Kwnqc6VEJ2F2M_YhZld:-Kwnqc6VEJ2F2M_YhZle:b57xxzt) ([raw file](https://github.com/vaadin/flow/blob/049d88c1a08e61eb6e41b7791445035d12315950/flow-html-components/src/test/java/com/vaadin/ui/html/ComponentTest.java#L303)):*
> assertPropertyOrAttribute(component, property.name);

This method checks only presence either property or attribute.
But it doesn't check the default value.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2718)*

**Comment by heruan** [comment]
*[flow-html-components/src/test/java/com/vaadin/ui/html/ComponentTest.java, line 303 at r2](https://reviewable.io:443/reviews/vaadin/flow/2718#-Kwnqc6VEJ2F2M_YhZld:-KwntIONIcCdW2b1r4Xm:b-l92mut) ([raw file](https://github.com/vaadin/flow/blob/049d88c1a08e61eb6e41b7791445035d12315950/flow-html-components/src/test/java/com/vaadin/ui/html/ComponentTest.java#L303)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> assertPropertyOrAttribute(component, property.name);

This method checks only presence either property or attribute.
But it doesn't check the default value.
</blockquote></details>

The default value is checked right before that:

```java
Assert.assertEquals(property.defaultValue,
        property.getUsingGetter(component));
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2718)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-html-components/src/test/java/com/vaadin/ui/html/ComponentTest.java, line 303 at r2](https://reviewable.io:443/reviews/vaadin/flow/2718#-Kwnqc6VEJ2F2M_YhZld:-KwnvI-Cf2xe04p1qLSG:b-4yes04) ([raw file](https://github.com/vaadin/flow/blob/049d88c1a08e61eb6e41b7791445035d12315950/flow-html-components/src/test/java/com/vaadin/ui/html/ComponentTest.java#L303)):*
<details><summary><i>Previously, heruan (Giovanni Lovato) wrote…</i></summary><blockquote>

The default value is checked right before that:

```java
Assert.assertEquals(property.defaultValue,
        property.getUsingGetter(component));
```
</blockquote></details>

It's different default value: it's the default value of server-side property.
I'm talking about default value for HTML property which is `""` in this case. And `null` is the default value on the server side.
They are not the same.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2718)*

**Comment by heruan** [comment]
*[flow-html-components/src/test/java/com/vaadin/ui/html/ComponentTest.java, line 303 at r2](https://reviewable.io:443/reviews/vaadin/flow/2718#-Kwnqc6VEJ2F2M_YhZld:-Kwo0djvt7NuNUynFrxL:b-bdh8zy) ([raw file](https://github.com/vaadin/flow/blob/049d88c1a08e61eb6e41b7791445035d12315950/flow-html-components/src/test/java/com/vaadin/ui/html/ComponentTest.java#L303)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

It's different default value: it's the default value of server-side property.
I'm talking about default value for HTML property which is `""` in this case. And `null` is the default value on the server side.
They are not the same.
</blockquote></details>

Got it. Then I need the `PropertyDescriptor`, which is known to the component only and I cannot access it. Do we really need to test this here? Shouldn't this be taken care of in the `PropertyDescriptor` tests?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2718)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-html-components/src/test/java/com/vaadin/ui/html/ComponentTest.java, line 303 at r2](https://reviewable.io:443/reviews/vaadin/flow/2718#-Kwnqc6VEJ2F2M_YhZld:-KwoAZCu7L0fl-Fr9EaI:bl6zhg0) ([raw file](https://github.com/vaadin/flow/blob/049d88c1a08e61eb6e41b7791445035d12315950/flow-html-components/src/test/java/com/vaadin/ui/html/ComponentTest.java#L303)):*
<details><summary><i>Previously, heruan (Giovanni Lovato) wrote…</i></summary><blockquote>

Got it. Then I need the `PropertyDescriptor`, which is known to the component only and I cannot access it. Do we really need to test this here? Shouldn't this be taken care of in the `PropertyDescriptor` tests?
</blockquote></details>

yeah, I think you are right.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2718)*

**Comment by heruan** [comment]
*[flow-html-components/src/test/java/com/vaadin/ui/html/ComponentTest.java, line 303 at r2](https://reviewable.io:443/reviews/vaadin/flow/2718#-Kwnqc6VEJ2F2M_YhZld:-KwoBAjZFh0uVEytBTAK:bgy1y75) ([raw file](https://github.com/vaadin/flow/blob/049d88c1a08e61eb6e41b7791445035d12315950/flow-html-components/src/test/java/com/vaadin/ui/html/ComponentTest.java#L303)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

yeah, I think you are right.
</blockquote></details>

This would test the client side value: https://gist.github.com/heruan/b252dee42f812450fbbcc8bcc0be44ac
Do you think should I commit?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2718)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[flow-html-components/src/test/java/com/vaadin/ui/html/ComponentTest.java, line 303 at r2](https://reviewable.io:443/reviews/vaadin/flow/2718#-Kwnqc6VEJ2F2M_YhZld:-KwoCbhO_ax4xy3Eiba3:by5j0jk) ([raw file](https://github.com/vaadin/flow/blob/049d88c1a08e61eb6e41b7791445035d12315950/flow-html-components/src/test/java/com/vaadin/ui/html/ComponentTest.java#L303)):*
<details><summary><i>Previously, heruan (Giovanni Lovato) wrote…</i></summary><blockquote>

This would test the client side value: https://gist.github.com/heruan/b252dee42f812450fbbcc8bcc0be44ac
Do you think should I commit?
</blockquote></details>

You can create a PR for that, yes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2718)*

**Pull request merged**
