### PR TITLE
Automatically register a DependencyFilter if bundling is detected

### PR DESCRIPTION
**Pull request by ahie**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3174)

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
You've forgotten to put our precious copyrights on top of the new files.

---

Reviewed 1 of 4 files at r1, 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks broke.

---

*[flow-server/src/main/java/com/vaadin/flow/shared/ui/Dependency.java, line 135 at r2](https://reviewable.io:443/reviews/vaadin/flow/3174#-L0eUKW27WKOCJP0rDNt:-L0eUKW27WKOCJP0rDNu:bixfvo5) ([raw file](https://github.com/vaadin/flow/blob/5e1eabc0c363cc4d7e5415656fe259bef13ed4dc/flow-server/src/main/java/com/vaadin/flow/shared/ui/Dependency.java#L135)):*
> ```Java
>         return jsonObject;
>     }
> ```

I miss the point of overloading the methods, can you elaborate on why do you need them?
I see that in new code you put dependencies in `ArrayList` only.

---

*[flow-server/src/main/java/com/vaadin/flow/shared/ui/Dependency.java, line 138 at r2](https://reviewable.io:443/reviews/vaadin/flow/3174#-L0eMKkSTxr9GhZ2QqoI:-L0eMKkSTxr9GhZ2QqoJ:b-z5d69b) ([raw file](https://github.com/vaadin/flow/blob/5e1eabc0c363cc4d7e5415656fe259bef13ed4dc/flow-server/src/main/java/com/vaadin/flow/shared/ui/Dependency.java#L138)):*
> ```Java
>     @Override
>     public int hashCode() {
>         final int prime = 31;
> ```

Can you just use `Objects#hash`?

```
@Override
    public int hashCode() {
        return Objects.hash(type, url, loadMode);
    }
```

---

*[flow-server/src/main/java/com/vaadin/flow/shared/ui/Dependency.java, line 149 at r2](https://reviewable.io:443/reviews/vaadin/flow/3174#-L0eMb23HLg0XQyHfD2s:-L0eMb24Ab_cml1Ddjd4:b-s1qkdh) ([raw file](https://github.com/vaadin/flow/blob/5e1eabc0c363cc4d7e5415656fe259bef13ed4dc/flow-server/src/main/java/com/vaadin/flow/shared/ui/Dependency.java#L149)):*
> ```Java
>     @Override
>     public boolean equals(Object obj) {
>         if (this == obj)
> ```

I propose to put brackets on all ifs and simplify it a bit:

```
@Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Dependency that = (Dependency) o;
        return type == that.type && loadMode == that.loadMode && Objects.equals(url, that.url);
    }
```

---

*[flow-server/src/main/java/com/vaadin/server/startup/BundleDependencyFilter.java, line 30 at r2](https://reviewable.io:443/reviews/vaadin/flow/3174#-L0eOKXWG7_gVrxOKqZb:-L0eOKXWG7_gVrxOKqZc:birwugs) ([raw file](https://github.com/vaadin/flow/blob/5e1eabc0c363cc4d7e5415656fe259bef13ed4dc/flow-server/src/main/java/com/vaadin/server/startup/BundleDependencyFilter.java#L30)):*
> ```Java
>      * into fragments.
>      */
>     static final String MAIN_BUNDLE_URL = "vaadin-flow-bundle.html";
> ```

Have no strong opinion, but everything else in the framework is made thinking about about some hackers that may want to reuse the class, but override some properties.

Would it be feasible to hide the field (make it `private`) and add some `protected` or `public` accessor method instead?

---

*[flow-server/src/main/java/com/vaadin/server/startup/BundleDependencyFilter.java, line 60 at r2](https://reviewable.io:443/reviews/vaadin/flow/3174#-L0e8xVYWevbkTnlMPc2-r2-60:-L0eNgg-MO3S57iRVR1N:b-bn10pt) ([raw file](https://github.com/vaadin/flow/blob/5e1eabc0c363cc4d7e5415656fe259bef13ed4dc/flow-server/src/main/java/com/vaadin/server/startup/BundleDependencyFilter.java#L60)):*
<details><summary><i>Previously, vaadin-bot (Vaadin Bot) wrote…</i></summary><blockquote>

MAJOR Invoke method(s) only conditionally. [rule](https://sonar.projects.vaadin.com/coding_rules#rule_key=squid%3AS2629)
</blockquote></details>

We use slf4j now and don't need any `String.format` calls:
https://www.slf4j.org/faq.html#logging_performance

`logger.debug("The entry is {}.", entry);`

Please also fix all other logging (in `BundleFilterInitializer` at least)

---

*[flow-server/src/main/java/com/vaadin/server/startup/BundleDependencyFilter.java, line 70 at r2](https://reviewable.io:443/reviews/vaadin/flow/3174#-L0ePbQ5fT4Pc9UPg3ij:-L0ePbQ5fT4Pc9UPg3ik:bck0hub) ([raw file](https://github.com/vaadin/flow/blob/5e1eabc0c363cc4d7e5415656fe259bef13ed4dc/flow-server/src/main/java/com/vaadin/server/startup/BundleDependencyFilter.java#L70)):*
> ```Java
>         }
> 
>         bundleUrlsToInclude.stream().forEach(bundleUrl -> {
> ```

Just FYI: `stream()` is not needed for `forEach` call. But see next comment first.

---

*[flow-server/src/main/java/com/vaadin/server/startup/BundleDependencyFilter.java, line 71 at r2](https://reviewable.io:443/reviews/vaadin/flow/3174#-L0eRKu4bdK_Yy9oiAND:-L0eR2kUOQ96sttsukMc:b-2i7u6p) ([raw file](https://github.com/vaadin/flow/blob/5e1eabc0c363cc4d7e5415656fe259bef13ed4dc/flow-server/src/main/java/com/vaadin/server/startup/BundleDependencyFilter.java#L71)):*
> ```Java
> 
>         bundleUrlsToInclude.stream().forEach(bundleUrl -> {
>             if (MAIN_BUNDLE_URL.equals(bundleUrl)) {
> ```

I'm not really fond of `return` in lambdas, since they seem to be slightly confusing and serve more like a break statements which are hard to read, so should we make it simpler?

For instance, all method lines below can be rewritten as

```
// You can eliminate the `0` if you put it in the very beginning of the method, looks reasonable too, who knows if we hit an array resize with this one.
dependenciesWithBundles.add(0, createBundleDependency(MAIN_BUNDLE_URL));

bundleUrlsToInclude.stream()
                .filter(bundleUrl -> !MAIN_BUNDLE_URL.equals(bundleUrl))
                .map(BundleDependencyFilter::createBundleDependency)
                .forEach(dependenciesWithBundles::add);
```

, couldn't they?

---

*[flow-server/src/main/java/com/vaadin/server/startup/BundleFilterInitializer.java, line 58 at r2](https://reviewable.io:443/reviews/vaadin/flow/3174#-L0eTOQ5ItQjldG_5tqe:-L0eTOQ5ItQjldG_5tqf:batg3a) ([raw file](https://github.com/vaadin/flow/blob/5e1eabc0c363cc4d7e5415656fe259bef13ed4dc/flow-server/src/main/java/com/vaadin/server/startup/BundleFilterInitializer.java#L58)):*
> entrySet()

Would it be easier to use just `values()`?

---

*[flow-server/src/test/java/com/vaadin/server/startup/BundleFilterInitializerTest.java, line 50 at r2](https://reviewable.io:443/reviews/vaadin/flow/3174#-L0eVXzag8MOXEFD4C1S:-L0eVXzag8MOXEFD4C1T:b-131rhp) ([raw file](https://github.com/vaadin/flow/blob/5e1eabc0c363cc4d7e5415656fe259bef13ed4dc/flow-server/src/test/java/com/vaadin/server/startup/BundleFilterInitializerTest.java#L50)):*
> ```Java
> import elemental.json.JsonException;
> 
> public class BundleFilterInitializerTest {
> ```

Nice test coverage in both test sets, btw, thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3174#-:-L0eNCa8Lwcy8R9lae5R:bmq00l7)*

**Comment by ahie** [comment]
Review status: 4 of 7 files reviewed at latest revision, 10 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/shared/ui/Dependency.java, line 135 at r2](https://reviewable.io:443/reviews/vaadin/flow/3174#-L0eUKW27WKOCJP0rDNt:-L0hhAHDS_leANSsIeXX:b1dddqe) ([raw file](https://github.com/vaadin/flow/blob/5e1eabc0c363cc4d7e5415656fe259bef13ed4dc/flow-server/src/main/java/com/vaadin/flow/shared/ui/Dependency.java#L135)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

I miss the point of overloading the methods, can you elaborate on why do you need them?
I see that in new code you put dependencies in `ArrayList` only.
</blockquote></details>

Used in at least the tests when comparing equality of lists. Doesn't hurt to have these so I decided to include them.

---

*[flow-server/src/main/java/com/vaadin/flow/shared/ui/Dependency.java, line 138 at r2](https://reviewable.io:443/reviews/vaadin/flow/3174#-L0eMKkSTxr9GhZ2QqoI:-L0hhKJXHTggeQExBA3z:b-1h0h4k) ([raw file](https://github.com/vaadin/flow/blob/5e1eabc0c363cc4d7e5415656fe259bef13ed4dc/flow-server/src/main/java/com/vaadin/flow/shared/ui/Dependency.java#L138)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Can you just use `Objects#hash`?

```
@Override
    public int hashCode() {
        return Objects.hash(type, url, loadMode);
    }
```
</blockquote></details>

Both of these were autogenerated by eclipse. Simplified both with your suggestions.

---

*[flow-server/src/main/java/com/vaadin/server/startup/BundleDependencyFilter.java, line 30 at r2](https://reviewable.io:443/reviews/vaadin/flow/3174#-L0eOKXWG7_gVrxOKqZb:-L0hix1dsnUsDL3BCMpO:b3oi6u1) ([raw file](https://github.com/vaadin/flow/blob/5e1eabc0c363cc4d7e5415656fe259bef13ed4dc/flow-server/src/main/java/com/vaadin/server/startup/BundleDependencyFilter.java#L30)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Have no strong opinion, but everything else in the framework is made thinking about about some hackers that may want to reuse the class, but override some properties.

Would it be feasible to hide the field (make it `private`) and add some `protected` or `public` accessor method instead?
</blockquote></details>

Generally we've avoided making things protected in the framework unless we can at least provide a test demonstrating a valid use case. I would leave this as is for now.

---

*[flow-server/src/main/java/com/vaadin/server/startup/BundleDependencyFilter.java, line 60 at r2](https://reviewable.io:443/reviews/vaadin/flow/3174#-L0e8xVYWevbkTnlMPc2-r2-60:-L0hn07uyq4yBIWjV3LC:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/5e1eabc0c363cc4d7e5415656fe259bef13ed4dc/flow-server/src/main/java/com/vaadin/server/startup/BundleDependencyFilter.java#L60)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

We use slf4j now and don't need any `String.format` calls:
https://www.slf4j.org/faq.html#logging_performance

`logger.debug("The entry is {}.", entry);`

Please also fix all other logging (in `BundleFilterInitializer` at least)
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/server/startup/BundleDependencyFilter.java, line 70 at r2](https://reviewable.io:443/reviews/vaadin/flow/3174#-L0ePbQ5fT4Pc9UPg3ij:-L0hn5sa_cmES-WQvh4M:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/5e1eabc0c363cc4d7e5415656fe259bef13ed4dc/flow-server/src/main/java/com/vaadin/server/startup/BundleDependencyFilter.java#L70)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Just FYI: `stream()` is not needed for `forEach` call. But see next comment first.
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/server/startup/BundleDependencyFilter.java, line 71 at r2](https://reviewable.io:443/reviews/vaadin/flow/3174#-L0eRKu4bdK_Yy9oiAND:-L0hnP42zvUR3nd19M5Y:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/5e1eabc0c363cc4d7e5415656fe259bef13ed4dc/flow-server/src/main/java/com/vaadin/server/startup/BundleDependencyFilter.java#L71)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

I'm not really fond of `return` in lambdas, since they seem to be slightly confusing and serve more like a break statements which are hard to read, so should we make it simpler?

For instance, all method lines below can be rewritten as

```
// You can eliminate the `0` if you put it in the very beginning of the method, looks reasonable too, who knows if we hit an array resize with this one.
dependenciesWithBundles.add(0, createBundleDependency(MAIN_BUNDLE_URL));

bundleUrlsToInclude.stream()
                .filter(bundleUrl -> !MAIN_BUNDLE_URL.equals(bundleUrl))
                .map(BundleDependencyFilter::createBundleDependency)
                .forEach(dependenciesWithBundles::add);
```

, couldn't they?
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/server/startup/BundleFilterInitializer.java, line 58 at r2](https://reviewable.io:443/reviews/vaadin/flow/3174#-L0eTOQ5ItQjldG_5tqe:-L0ho-uaX6gIMWoY9-BH:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/5e1eabc0c363cc4d7e5415656fe259bef13ed4dc/flow-server/src/main/java/com/vaadin/server/startup/BundleFilterInitializer.java#L58)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

> entrySet()

Would it be easier to use just `values()`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3174)*

**Comment by SomeoneToIgnore** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/shared/ui/Dependency.java, line 135 at r2](https://reviewable.io:443/reviews/vaadin/flow/3174#-L0eUKW27WKOCJP0rDNt:-L0hocaUuqcaYoJ9KtsT:b-py1kmm) ([raw file](https://github.com/vaadin/flow/blob/5e1eabc0c363cc4d7e5415656fe259bef13ed4dc/flow-server/src/main/java/com/vaadin/flow/shared/ui/Dependency.java#L135)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

Used in at least the tests when comparing equality of lists. Doesn't hurt to have these so I decided to include them.
</blockquote></details>

Ah, ok.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3174#-:-L0housgkTZh-xEKrYXp:bnfp4nl)*

**Comment by SomeoneToIgnore** [comment]
*[flow-server/src/main/java/com/vaadin/server/startup/BundleDependencyFilter.java, line 70 at r3](https://reviewable.io:443/reviews/vaadin/flow/3174#-L0hqjp3PoQHqcv4X48V:-L0hqjp3PoQHqcv4X48W:b-5nbpu8) ([raw file](https://github.com/vaadin/flow/blob/7d2423ed6f3ec59a7b5b84902a257423c39b61b0/flow-server/src/main/java/com/vaadin/server/startup/BundleDependencyFilter.java#L70)):*
> ```Java
>         }
> 
>         dependenciesWithBundles.add(0, createBundleDependency(MAIN_BUNDLE_URL));
> ```

Looks like I was wrong and this needs to be added only when `bundleUrlsToInclude` is not empty.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3174)*

**Comment by SomeoneToIgnore** [comment]
*[flow-server/src/main/java/com/vaadin/server/startup/BundleDependencyFilter.java, line 70 at r3](https://reviewable.io:443/reviews/vaadin/flow/3174#-L0hqjp3PoQHqcv4X48V:-L0hr-UhaxwSLaq5lmaM:b-49i95m) ([raw file](https://github.com/vaadin/flow/blob/7d2423ed6f3ec59a7b5b84902a257423c39b61b0/flow-server/src/main/java/com/vaadin/server/startup/BundleDependencyFilter.java#L70)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Looks like I was wrong and this needs to be added only when `bundleUrlsToInclude` is not empty.
</blockquote></details>

Nice tests, again :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3174)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3174)*

**Comment by SomeoneToIgnore** [comment]
*[flow-server/src/main/java/com/vaadin/server/startup/BundleDependencyFilter.java, line 30 at r2](https://reviewable.io:443/reviews/vaadin/flow/3174#-L0eOKXWG7_gVrxOKqZb:-L0hyNmWqYZtZup-LoHc:b2nhll9) ([raw file](https://github.com/vaadin/flow/blob/5e1eabc0c363cc4d7e5415656fe259bef13ed4dc/flow-server/src/main/java/com/vaadin/server/startup/BundleDependencyFilter.java#L30)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

Generally we've avoided making things protected in the framework unless we can at least provide a test demonstrating a valid use case. I would leave this as is for now.
</blockquote></details>

Ok.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3174)*

**Pull request merged**
