### PR TITLE
Add autocomplete, autocorrect and autocapitalize mixin interfaces

### PR DESCRIPTION
**Pull request by heruan**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3517)

### CODE REVIEW

**Comment by heruan** [comment]
Any chance to get this reviewed? 🤓

**Comment by pleku** [comment]
>Any chance to get this reviewed, now that beta's storm is passed? 🤓

Yes, thanks for the patience.

**Comment by pleku** [comment]
Reviewed 4 of 5 files at r2.
Review status: 4 of 8 files reviewed at latest revision, 12 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/component/Capitalization.java, line 19 at r2](https://reviewable.io:443/reviews/vaadin/flow/3517#-L7ULge8sR32AjXdC91s:-L7ULge8sR32AjXdC91t:b-y5iurr) ([raw file](https://github.com/vaadin/flow/blob/0be9b54c55b09c36d64bdfd54e52fc322b488bb0/flow-server/src/main/java/com/vaadin/flow/component/Capitalization.java#L19)):*
> ```Java
> 
> /**
>  * Capitalization options for the {@code autocapitalize} attribute.
> ```

The javadocs here are not saying when I would use this, as a Java developer.

---

*[flow-server/src/main/java/com/vaadin/flow/component/Capitalization.java, line 21 at r2](https://reviewable.io:443/reviews/vaadin/flow/3517#-L7UKaCh-a7sxgYa_4gb:-L7UKaCh-a7sxgYa_4gc:b-4hq3fp) ([raw file](https://github.com/vaadin/flow/blob/0be9b54c55b09c36d64bdfd54e52fc322b488bb0/flow-server/src/main/java/com/vaadin/flow/component/Capitalization.java#L21)):*
> ```Java
>  * Capitalization options for the {@code autocapitalize} attribute.
>  */
> public enum Capitalization {
> ```

I'm somewhat hesitant to adding this since there is no guarantee on whether this works on browser/device X and I cannot find that information from an official source.
Two first search hits don't anything about the support for this, and HTML _Living Standard_ is not really something that we want to add API for with light grounds.

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autocapitalize
https://developers.google.com/web/updates/2015/04/autocapitalize 

According to https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input the support is not there yet.
Thus we cannot add this

---

*[flow-server/src/main/java/com/vaadin/flow/component/Completion.java, line 19 at r2](https://reviewable.io:443/reviews/vaadin/flow/3517#-L7UNoiYq0879-_L2qy0:-L7UNoiYq0879-_L2qy1:b-tm6a64) ([raw file](https://github.com/vaadin/flow/blob/0be9b54c55b09c36d64bdfd54e52fc322b488bb0/flow-server/src/main/java/com/vaadin/flow/component/Completion.java#L19)):*
> ```Java
> 
> /**
>  * Completion options for the {@code autocomplete} attribute.
> ```

The javadocs are not saying why and what for this enum exists.

---

*[flow-server/src/main/java/com/vaadin/flow/component/Completion.java, line 21 at r2](https://reviewable.io:443/reviews/vaadin/flow/3517#-L7UNAAIbpG_20KmX-DF:-L7UNAAIbpG_20KmX-DG:b-ksg4kx) ([raw file](https://github.com/vaadin/flow/blob/0be9b54c55b09c36d64bdfd54e52fc322b488bb0/flow-server/src/main/java/com/vaadin/flow/component/Completion.java#L21)):*
> ```Java
>  * Completion options for the {@code autocomplete} attribute.
>  */
> public enum Completion {
> ```

Weird name since the attribute is autocomplete instead of completion

---

*[flow-server/src/main/java/com/vaadin/flow/component/Completion.java, line 28 at r2](https://reviewable.io:443/reviews/vaadin/flow/3517#-L7UNTF4iSV4MIOKKpjh:-L7UNTF4iSV4MIOKKpji:be12y19) ([raw file](https://github.com/vaadin/flow/blob/0be9b54c55b09c36d64bdfd54e52fc322b488bb0/flow-server/src/main/java/com/vaadin/flow/component/Completion.java#L28)):*
> ```Java
>      * not automatically complete the entry.
>      */
>     OFF("off"),
> ```

This won't work for `input` fields in all the  
browsers according to https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion

And it makes no sense for `form`s in Flow

---

*[flow-server/src/main/java/com/vaadin/flow/component/HasCompletion.java, line 19 at r2](https://reviewable.io:443/reviews/vaadin/flow/3517#-L7UO0jKu4qtSbPiSGwb:-L7UO0jKu4qtSbPiSGwc:bi0rjs0) ([raw file](https://github.com/vaadin/flow/blob/0be9b54c55b09c36d64bdfd54e52fc322b488bb0/flow-server/src/main/java/com/vaadin/flow/component/HasCompletion.java#L19)):*
> ```Java
> 
> /**
>  * Mixin interface for fields with {@code autocomplete} attribute.
> ```

Should clarify when this mixin should be applied and how well it is supported.
Links to https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-autocomplete are acceptable.

---

*[flow-server/src/main/java/com/vaadin/flow/component/HasCompletion.java, line 21 at r2](https://reviewable.io:443/reviews/vaadin/flow/3517#-L7UOLrtO-9_qNwyDOic:-L7UOLrtO-9_qNwyDOid:bjowvzn) ([raw file](https://github.com/vaadin/flow/blob/0be9b54c55b09c36d64bdfd54e52fc322b488bb0/flow-server/src/main/java/com/vaadin/flow/component/HasCompletion.java#L21)):*
> ```Java
>  * Mixin interface for fields with {@code autocomplete} attribute.
>  */
> public interface HasCompletion extends HasElement {
> ```

I'm not sure of this name either. It is probably linguistically more correct than `HasAutocomplete` but it doesn't match the attribute name...

---

*[flow-server/src/main/java/com/vaadin/flow/component/HasCompletion.java, line 50 at r2](https://reviewable.io:443/reviews/vaadin/flow/3517#-L7UOrgGg55sGduyoAnN:-L7UOrgGg55sGduyoAnO:buyzkal) ([raw file](https://github.com/vaadin/flow/blob/0be9b54c55b09c36d64bdfd54e52fc322b488bb0/flow-server/src/main/java/com/vaadin/flow/component/HasCompletion.java#L50)):*
> ```Java
>         } else if ("".equals(autocomplete)) {
>             // Default behavior for empty attribute.
>             return Completion.OFF;
> ```

While this may be correct in theory, the practice as stated in a previous comment, does not apply as it is not necessarily `off`.

Maybe it would help to use `DEFAULT` or `BROWSER_DEFAULT` instead ? Then that would have to be documented again... 

---

*[flow-server/src/main/java/com/vaadin/flow/component/HasCorrection.java, line 21 at r2](https://reviewable.io:443/reviews/vaadin/flow/3517#-L7UPmIpHS1PZF_vzqqy:-L7UPmIpHS1PZF_vzqqz:b-wehqe2) ([raw file](https://github.com/vaadin/flow/blob/0be9b54c55b09c36d64bdfd54e52fc322b488bb0/flow-server/src/main/java/com/vaadin/flow/component/HasCorrection.java#L21)):*
> ```Java
>  * Mixin interface for fields with {@code autocorrect} attribute.
>  */
> public interface HasCorrection extends HasElement {
> ```

We are not going to add support for just one browser specific html attributes. This could be published as an add-on in vaadin.com/directory instead for the convenience of those who need it.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-autocorrect

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3517)*

**Comment by pleku** [comment]
Thanks again for the contribution. However, there is some parts in this PR that we don't feel should be integrated into Flow since there are no guarantees that the API would work for all the users.

Only `autocomplete` has a broad browser support, and I think we could take that in to make it more easier to build forms with great UX with Flow. There is some concerns about the naming and `"autocomplete"="off"` since it doesn't really mean that it is off, and this can be confusing.

---

Review status: 4 of 8 files reviewed at latest revision, 12 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3517#-:-L7UQ9zGZnV_GOs0czWK:b54b4h2)*

**Comment by heruan** [comment]
Thank you @pleku for the review. If I understand correctly it's the enums with non-spec values which are problematic as it may not work for all users, right? Would it be acceptable if I remove them and let the value be a string? This will provide a Java API for the three attributes which *are* supported in Vaadin's Web Components (e.g. `vaadin-text-field`).

**Comment by pleku** [comment]
Oh right, you're correct, my bad. But if these are for API used by `Vaadin.TextFieldMixin`, then this PR belongs to vaadin/vaadin-text-field-flow repository, and not Flow. Currently there isn't any other component that we will say would support these attributes. And then it would be fine to keep all the things that this introduces.

There is benefit to having both API exposed, `enum` and `String` since enum gives the autocompletion option in IDEs. `String` is also OK for using a value that is not for some reason available as an enum. But for simplicity, I'd just use perhaps `enum`.

If you migrate this to the other repository, please first make it as-is and then make another commit for resolving the javadoc issues. 

---

Review status: 4 of 8 files reviewed at latest revision, 12 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3517#-:-L7xX4g7i5st-zaKhoyh:bxtcan5)*

**Pull request closed without merging**
