### PR TITLE
Add Flow maven plugin tutorial

### PR DESCRIPTION
**Pull request by denis-anisimov**
Fix for #3289

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3313)

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[flow-documentation/web-components/tutorial-tutorial-flow-maven-plugin.asciidoc, line 1 at r1](https://reviewable.io:443/reviews/vaadin/flow/3313#-L2yXpySwISxdNeYnvVd:-L2yXpySwISxdNeYnvVe:b-khzi1j) ([raw file](https://github.com/vaadin/flow/blob/5139f979f5414e2282784ce9f853972d13220d46/flow-documentation/web-components/tutorial-tutorial-flow-maven-plugin.asciidoc#L1)):*
> ```AsciiDoc
> ---
> ```

The file has two `tutorial-` prefixes, I guess it should have only one.

---

*[flow-documentation/web-components/tutorial-tutorial-flow-maven-plugin.asciidoc, line 23 at r1](https://reviewable.io:443/reviews/vaadin/flow/3313#-L2yYG3VR7HVCLGQeHeA:-L2yYG3VR7HVCLGQeHeB:b3qxq57) ([raw file](https://github.com/vaadin/flow/blob/5139f979f5414e2282784ce9f853972d13220d46/flow-documentation/web-components/tutorial-tutorial-flow-maven-plugin.asciidoc#L23)):*
> once ... is build

I think it should be `built` used here.

> with the Jetty plugin

This may be a bit confusing, should we at least mention that not only Jetty plugin can be used? Also, we don't support both Jetty and Spring.

How about: 

```
Once the project is built for the production mode, you can run the application with `vaadin.productionMode` system property which will tell Flow to use the files built.
For instance, with Jetty maven plugin, the app can be started as:
```

---

*[flow-documentation/web-components/tutorial-tutorial-flow-maven-plugin.asciidoc, line 29 at r1](https://reviewable.io:443/reviews/vaadin/flow/3313#-L2y_5JY9KiPQJyQRdbs:-L2y_5JY9KiPQJyQRdbt:bz2i7xt) ([raw file](https://github.com/vaadin/flow/blob/5139f979f5414e2282784ce9f853972d13220d46/flow-documentation/web-components/tutorial-tutorial-flow-maven-plugin.asciidoc#L29)):*
> ```AsciiDoc
> mvn jetty:run -Dvaadin.productionMode
> ----
> ```

Since everything else below is a straight copy paste from the plugin's README.md, I propose to remove the readme and all the links to it.

I believe the decision to have a link to it was made before the decision to move the plugin into the same repo.
It does not make any sense to have the duplication.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3313)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[flow-documentation/web-components/tutorial-tutorial-flow-maven-plugin.asciidoc, line 1 at r1](https://reviewable.io:443/reviews/vaadin/flow/3313#-L2yXpySwISxdNeYnvVd:-L2z3ZdSpRoCBk2jelW5:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/5139f979f5414e2282784ce9f853972d13220d46/flow-documentation/web-components/tutorial-tutorial-flow-maven-plugin.asciidoc#L1)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

The file has two `tutorial-` prefixes, I guess it should have only one.
</blockquote></details>

Done.

---

*[flow-documentation/web-components/tutorial-tutorial-flow-maven-plugin.asciidoc, line 29 at r1](https://reviewable.io:443/reviews/vaadin/flow/3313#-L2y_5JY9KiPQJyQRdbs:-L2z46nFemfFlWDNhT-V:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/5139f979f5414e2282784ce9f853972d13220d46/flow-documentation/web-components/tutorial-tutorial-flow-maven-plugin.asciidoc#L29)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Since everything else below is a straight copy paste from the plugin's README.md, I propose to remove the readme and all the links to it.

I believe the decision to have a link to it was made before the decision to move the plugin into the same repo.
It does not make any sense to have the duplication.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3313)*

**Comment by SomeoneToIgnore** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3313#-:-L2z5DVv0fCeob8F9Pw2:bnfp4nl)*

**Comment by SomeoneToIgnore** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[flow-documentation/web-components/tutorial-webcomponents-es5.asciidoc, line 362 at r2](https://reviewable.io:443/reviews/vaadin/flow/3313#-L2z7KNBPfTlEfsqb1eb:-L2z7KNBPfTlEfsqb1ec:b-ijmdbv) ([raw file](https://github.com/vaadin/flow/blob/c99e380b367f75042efd25878c909ebf7f70b1af/flow-documentation/web-components/tutorial-webcomponents-es5.asciidoc#L362)):*
> ```AsciiDoc
> 
> [TIP]
> There is <<tutorial-tutorial-flow-maven-plugin#,Taking your app into production>> tutorial available which shows how 
> ```

This url should be also adjusted.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3313)*

**Comment by denis-anisimov** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-documentation/web-components/tutorial-webcomponents-es5.asciidoc, line 362 at r2](https://reviewable.io:443/reviews/vaadin/flow/3313#-L2z7KNBPfTlEfsqb1eb:-L2zEhtRBJpGPM2qdxZ-:bu4ozr6) ([raw file](https://github.com/vaadin/flow/blob/c99e380b367f75042efd25878c909ebf7f70b1af/flow-documentation/web-components/tutorial-webcomponents-es5.asciidoc#L362)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

This url should be also adjusted.
</blockquote></details>

Done.
Thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3313)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3313)*

**Pull request merged**
