### PR TITLE
fix: fix native compilation and runtime

### LINKED ISSUE #16307: Native image compilation fails
### Description of the bug

Building a native image fails with the following error: 

```
[INFO] --- maven-jar-plugin:3.3.0:jar (default-jar) @ spring-skeleton ---
[INFO] Building jar: C:\skeleton-starter-flow-spring-24\skeleton-starter-flow-spring-24\target\spring-skeleton-1.0-SNAPSHOT.jar
[INFO]
[INFO] --- spring-boot-maven-plugin:3.0.4:repackage (repackage) @ spring-skeleton ---
[INFO] Replacing main artifact with repackaged archive
[INFO]
[INFO] <<< native-maven-plugin:0.9.20:compile (default-cli) < package @ spring-skeleton <<<
[INFO]
[INFO]
[INFO] --- native-maven-plugin:0.9.20:compile (default-cli) @ spring-skeleton ---
[INFO] Found GraalVM installation from JAVA_HOME variable.
[INFO] Downloaded GraalVM reachability metadata repository from file:/C:/Users/Tarek%20Oraby/.m2/repository/org/graalvm/buildtools/graalvm-reachability-metadata/0.9.20/graalvm-reachability-metadata-0.9.20-repository.zip
[INFO] [graalvm reachability metadata repository for ch.qos.logback:logback-classic:1.4.5]: Configuration directory not found. Trying latest version.
[INFO] [graalvm reachability metadata repository for ch.qos.logback:logback-classic:1.4.5]: Configuration directory is ch.qos.logback\logback-classic\1.4.1
[INFO] [graalvm reachability metadata repository for org.apache.tomcat.embed:tomcat-embed-core:10.1.5]: Configuration directory not found. Trying latest version.
[INFO] [graalvm reachability metadata repository for org.apache.tomcat.embed:tomcat-embed-core:10.1.5]: Configuration directory is org.apache.tomcat.embed\tomcat-embed-core\10.0.20
[INFO] [graalvm reachability metadata repository for net.java.dev.jna:jna:5.12.1]: Configuration directory not found. Trying latest version.
[INFO] [graalvm reachability metadata repository for net.java.dev.jna:jna:5.12.1]: Configuration directory is net.java.dev.jna\jna\5.8.0
[INFO] [graalvm reachability metadata repository for org.jboss.logging:jboss-logging:3.5.0.Final]: Configuration directory is org.jboss.logging\jboss-logging\3.5.0.Final
[INFO] [graalvm reachability metadata repository for org.hibernate.validator:hibernate-validator:8.0.0.Final]: Configuration directory not found. Trying latest version.
[INFO] [graalvm reachability metadata repository for org.hibernate.validator:hibernate-validator:8.0.0.Final]: Configuration directory is org.hibernate.validator\hibernate-validator\7.0.4.Final
[INFO] Executing: C:\Program Files\graalvm-ce-java19-22.3.0\bin\native-image.cmd @target\tmp\native-image-3343143352888285618.args
Exception in thread "main" java.nio.file.InvalidPathException: Illegal char <> at index 3: C:\skeleton-starter-flow-spring-24\skeleton-starter-flow-spring-24\target\classes
        at java.base@19.0.1/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at java.base@19.0.1/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at java.base@19.0.1/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at java.base@19.0.1/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
        at java.base@19.0.1/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232)
        at java.base@19.0.1/java.nio.file.Path.of(Path.java:147)
        at java.base@19.0.1/java.nio.file.Paths.get(Paths.java:69)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.ClasspathUtils.stringToClasspath(ClasspathUtils.java:52)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.addCustomImageClasspath(NativeImage.java:1582)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.DefaultOptionHandler.processClasspathArgs(DefaultOptionHandler.java:417)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.DefaultOptionHandler.consume(DefaultOptionHandler.java:69)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage$NativeImageArgsProcessor.apply(NativeImage.java:1512)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.DefaultOptionHandler.consume(DefaultOptionHandler.java:204)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage$NativeImageArgsProcessor.apply(NativeImage.java:1512)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.processNativeImageArgs(NativeImage.java:1770)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.completeImageBuild(NativeImage.java:959)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.build(NativeImage.java:1417)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1387)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.main(NativeImage.java:1374)
``` 

### Expected behavior

It works

### Minimal reproducible example

- Download https://github.com/vaadin/skeleton-starter-flow-spring
- Run `mvn -Pproduction -Pnative native:compile`

### Versions

- Vaadin / Flow version: 24.0.0
- Java version: openjdk version "19.0.1" 2022-10-18
- OS version: Windows

### PR DESCRIPTION
**Pull request by mcollovati**
## Description

This change fixes handling of resources in the native build and registers hints for classes required for PWA icon generation at runtime.

Fixes #16307

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

### CODE REVIEW

**Comment by Artur-** [comment]
Not saying we shouldn't do this but in the end, we should really be generating the PWA images during the build and not runtime

**Comment by mcollovati** [comment]
> Not saying we shouldn't do this but in the end, we should really be generating the PWA images during the build and not runtime

This would indeed be great, and would also speed up the startup of the first request.

**Comment by caalador** [comment]
PWA images generation on request is fixed in webPush commit:
https://github.com/vaadin/flow/pull/16994/commits/b9c252483018553819d7d1c1fd4532e334ec16b8

**Comment by mshabarov** [comment]
I'm getting `Execution default-cli of goal org.graalvm.buildtools:native-maven-plugin:0.9.22:compile failed: Version to check '' can't be parsed.` on my mac. Not clear yet, what is a version it tries to check. This might be something related to my setup.

**Comment by caalador** [comment]
Got it to run after removing  `spring-boot-devtools` dependency and adding 
```
        <profile>
            <id>native</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.graalvm.buildtools</groupId>
                        <artifactId>native-maven-plugin</artifactId>
                        <version>0.9.23</version>
                        <configuration>
                            <buildArgs>
                                <arg>-H:-CheckToolchain</arg>
                            </buildArgs>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
```
As for some reason whitout the checkToolchain flag it failed to run native.

**Comment by caalador** [comment]
With PWA I was missing awt Toolkit and Insets. After adding those it worked with PWA also (updated pwa).

**Review by caalador — APPROVED** [review]

**Comment by mshabarov** [comment]
Tried with GraalVM Java 17 and 20, also applied workaround from [here](https://github.com/oracle/graal/issues/6499) and [here](https://stackoverflow.com/questions/76110898/how-to-build-a-spring-boot-3-0-6-rest-api-into-a-working-native-image) with no luck.

**Review by czp13 — APPROVED** [review]

**Comment by mshabarov** [comment]
@czp13 have you tested it on your machine? Do you use mac?

**Comment by czp13** [comment]
I promised to @mshabarov to put here my execution results. After fixing some small environment related things (update node, java/graalvm version, etc).

I got these results (fails) in short:
- I tried with the default `24.1.1`flow version and it was failing for some swallowed error (but seems different than @mshabarov )
```
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:00 min
[INFO] Finished at: 2023-06-28T13:48:58+02:00
[INFO] ------------------------------------------------------------------------
[WARNING]
[WARNING] Plugin validation issues were detected in 1 plugin(s)
[WARNING]
[WARNING]  * org.apache.maven.plugins:maven-site-plugin:3.12.1
[WARNING]
[WARNING] For more or less details, use 'maven.plugin.validation' property with one of the values (case insensitive): [BRIEF, DEFAULT, VERBOSE]
[WARNING]
[ERROR] Failed to execute goal org.graalvm.buildtools:native-maven-plugin:0.9.22:compile (default-cli) on project spring-skeleton: Execution of /Library/Java/JavaVirtualMachines/graalvm-ce-java17-22.3.1/Contents/Home/bin/native-image -cp /Users/pczuczor/Projects/skeleton-starter-flow-spring/target/classes:/Users/pczuczor/.m2/repository/com/vaadin/vaadin-button-flow/24.1.1/vaadin-button-flow-24.1.1.jar:/Users/pczuczor/.m2/repository/com/vaadin/vaadin-spring-boot-starter/24.1.1/vaadin-spring-boot-starter-24.1.1.jar:/Users/pczuczor/.m2/repository/ch/qos/logback/logback-core/1.4.7/logback-core-1.4.7.jar:
```

- tried with a built `24.2-SNAPSHOT` version as well, but somehow it was failing because vaadin bom can not be found.
(I was able to add this to custom projects before, and also remember that the native image build was somewhat working 1-2 months ago when I checked).
```
 mvn -Pproduction -Pnative -Dmaven.plugin.validation=VERBOSE clean package native:compile
./target/spring-skeleton -X -e  -H:+ReportExceptionStackTraces
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Non-resolvable import POM: The following artifacts could not be resolved: com.vaadin:vaadin-bom:pom:24.2-SNAPSHOT (absent): Could not find artifact com.vaadin:vaadin-bom:pom:24.2-SNAPSHOT @ line 36, column 25
[ERROR] 'dependencies.dependency.version' for com.vaadin:vaadin:jar is missing. @ line 47, column 21
[ERROR] 'dependencies.dependency.version' for com.vaadin:vaadin-spring-boot-starter:jar is missing. @ line 52, column 21
[ERROR] 'dependencies.dependency.version' for com.vaadin:vaadin-testbench-junit5:jar is missing. @ line 70, column 21
[ERROR] 'dependencies.dependency.version' for com.vaadin:vaadin-core:jar is missing. @ line 111, column 29
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project com.example:spring-skeleton:1.0-SNAPSHOT (/Users/pczuczor/Projects/skeleton-starter-flow-spring/pom.xml) has 5 errors
[ERROR]     Non-resolvable import POM: The following artifacts could not be resolved: com.vaadin:vaadin-bom:pom:24.2-SNAPSHOT (absent): Could not find artifact com.vaadin:vaadin-bom:pom:24.2-SNAPSHOT @ line 36, column 25 -> [Help 2]
[ERROR]     'dependencies.dependency.version' for com.vaadin:vaadin:jar is missing. @ line 47, column 21
[ERROR]     'dependencies.dependency.version' for com.vaadin:vaadin-spring-boot-starter:jar is missing. @ line 52, column 21
[ERROR]     'dependencies.dependency.version' for com.vaadin:vaadin-testbench-junit5:jar is missing. @ line 70, column 21
[ERROR]     'dependencies.dependency.version' for com.vaadin:vaadin-core:jar is missing. @ line 111, column 29
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelExc
```
This seems independent from native image build.

I used MacOs, M1 chip, graalvm-jdk-17.0.7+8.1, node v18.12.1.

**Comment by czp13** [comment]
The weird thing is that these errors are new and did not see them happening before (the custom builds from flow repo was not causing any problems in any custom projects before). 🤔 

Anyway it is good to keep on eye on this I feel.

**Pull request merged**
