### PR TITLE
Update ejs dependency of webcomponent analyzer

### PR DESCRIPTION
**Pull request by ahie**
Also regenerate components.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3087)

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/tabs/GeneratedVaadinTab.java, line 110 at r1](https://reviewable.io:443/reviews/vaadin/flow/3087#-L-Gh_GuQOiJUuwY0wmC:-L-Gh_GuQOiJUuwY0wmD:b60f1bh) ([raw file](https://github.com/vaadin/flow/blob/cc06503b917bbad48fdaac141577f0a22d3a3e15/flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/tabs/GeneratedVaadinTab.java#L110)):*
> ```Java
>      * @return the {@code value} property from the webcomponent
>      */
>     public String getValue() {
> ```

Have thought that Ahmed had fixed method reordering. Is it a different case?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3087)*

**Comment by ahie** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/tabs/GeneratedVaadinTab.java, line 110 at r1](https://reviewable.io:443/reviews/vaadin/flow/3087#-L-Gh_GuQOiJUuwY0wmC:-L-GhruBTQ23R9WiNE8F:b-rmfr6s) ([raw file](https://github.com/vaadin/flow/blob/cc06503b917bbad48fdaac141577f0a22d3a3e15/flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/tabs/GeneratedVaadinTab.java#L110)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Have thought that Ahmed had fixed method reordering. Is it a different case?
</blockquote></details>

Apparently a different case. All I changed was the `package.json` and ran `mvn clean install -Pgenerator`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3087)*

**Comment by SomeoneToIgnore** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/tabs/GeneratedVaadinTab.java, line 110 at r1](https://reviewable.io:443/reviews/vaadin/flow/3087#-L-Gh_GuQOiJUuwY0wmC:-L-GiAd9qXSQlO6PbnU1:bzdg6kx) ([raw file](https://github.com/vaadin/flow/blob/cc06503b917bbad48fdaac141577f0a22d3a3e15/flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/tabs/GeneratedVaadinTab.java#L110)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

Apparently a different case. All I changed was the `package.json` and ran `mvn clean install -Pgenerator`.
</blockquote></details>

@gilberto-torrezan do you know the details about method reordering fix? Should we fix this too?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3087)*

**Comment by gilberto-torrezan** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/tabs/GeneratedVaadinTab.java, line 110 at r1](https://reviewable.io:443/reviews/vaadin/flow/3087#-L-Gh_GuQOiJUuwY0wmC:-L-Gi0nqqGB3R7y9VI7x:bua28vx) ([raw file](https://github.com/vaadin/flow/blob/cc06503b917bbad48fdaac141577f0a22d3a3e15/flow-components-parent/flow-generated-components/src/main/java/com/vaadin/ui/tabs/GeneratedVaadinTab.java#L110)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

@gilberto-torrezan do you know the details about method reordering fix? Should we fix this too?
</blockquote></details>

The `value` property has a different workflow due to the detection of `HasValue`, so maybe it's not covered by the reordering patch.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3087)*

**Comment by gilberto-torrezan** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-components-parent/flow-webcomponent-api-analyzer/package.json, line 10 at r1](https://reviewable.io:443/reviews/vaadin/flow/3087#-L-GiXmYwW8aawKk1Eog:-L-GiXmYwW8aawKk1Eoh:buqoyjy) ([raw file](https://github.com/vaadin/flow/blob/cc06503b917bbad48fdaac141577f0a22d3a3e15/flow-components-parent/flow-webcomponent-api-analyzer/package.json#L10)):*
> ```JSON
>     "bower": "^1.8.2",
>     "coa": "~1.0.1",
>     "ejs": "~2.5.5",
> ```

The latest version is 2.5.7, shouldn't we fix that version in the package.json?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3087)*

**Comment by SomeoneToIgnore** [comment]
*[flow-components-parent/flow-webcomponent-api-analyzer/package.json, line 10 at r1](https://reviewable.io:443/reviews/vaadin/flow/3087#-L-GiXmYwW8aawKk1Eog:-L-GmplyIJmH0YvG32qa:bk49cqp) ([raw file](https://github.com/vaadin/flow/blob/cc06503b917bbad48fdaac141577f0a22d3a3e15/flow-components-parent/flow-webcomponent-api-analyzer/package.json#L10)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

The latest version is 2.5.7, shouldn't we fix that version in the package.json?
</blockquote></details>

‘~’ does this for us, but we can use  strict version numbers everywhere, if we wont a bit more stable dependencies.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3087)*

**Comment by ahie** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-components-parent/flow-webcomponent-api-analyzer/package.json, line 10 at r1](https://reviewable.io:443/reviews/vaadin/flow/3087#-L-GiXmYwW8aawKk1Eog:-L-H4Pjil9dzirjeMUcD:b-kckstt) ([raw file](https://github.com/vaadin/flow/blob/cc06503b917bbad48fdaac141577f0a22d3a3e15/flow-components-parent/flow-webcomponent-api-analyzer/package.json#L10)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

‘~’ does this for us, but we can use  strict version numbers everywhere, if we wont a bit more stable dependencies.
</blockquote></details>

If you look at `package-lock.json` you can see 2.5.7 is already in use.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3087)*

**Comment by SomeoneToIgnore** [comment]
*[flow-components-parent/flow-webcomponent-api-analyzer/package.json, line 10 at r1](https://reviewable.io:443/reviews/vaadin/flow/3087#-L-GiXmYwW8aawKk1Eog:-L-Vnhgv6maHNtL_lLKG:b-cg2q6n) ([raw file](https://github.com/vaadin/flow/blob/cc06503b917bbad48fdaac141577f0a22d3a3e15/flow-components-parent/flow-webcomponent-api-analyzer/package.json#L10)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

If you look at `package-lock.json` you can see 2.5.7 is already in use.
</blockquote></details>

@gilberto-torrezan 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3087)*

**Pull request merged**
