### PR TITLE
Remap value prop

### PR DESCRIPTION
**Pull request by manolo**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/4023)

### CODE REVIEW

**Comment by gilberto-torrezan** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4023#-:-LB4sK61EUNM_qHgIv8M:bnfp4nl)*

**Comment by denis-anisimov** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/registry/ValuePropertyRegistry.java, line 38 at r1](https://reviewable.io/reviews/vaadin/flow/4023#-LB4snMl1FN-jmOkLPQJ:-LB4snMl1FN-jmOkLPQK:b-4rds1b) ([raw file](https://github.com/vaadin/flow/blob/a8192fd8ef8b9a9abdf5b6ae518a3543e9b9cac0/flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/registry/ValuePropertyRegistry.java#L38)):*
> ```
>     public static Optional<String> getOptionalFor(
>             String elementIdentifier) {
> ```

Shouldn't this method be renamed and return `"value"` if there is not value in the registry ?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4023)*

**Comment by manolo** [comment]
Review status: 1 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/registry/ValuePropertyRegistry.java, line 38 at r1](https://reviewable.io/reviews/vaadin/flow/4023#-LB4snMl1FN-jmOkLPQJ:-LB4whuV9D0cKw7sRd1z:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/a8192fd8ef8b9a9abdf5b6ae518a3543e9b9cac0/flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/registry/ValuePropertyRegistry.java#L38)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
>     public static Optional<String> getOptionalFor(
>             String elementIdentifier) {
> ```

Shouldn't this method be renamed and return `"value"` if there is not value in the registry ?
</blockquote></details>

Done.

---

*[flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/registry/ValuePropertyRegistry.java, line 38 at r1](https://reviewable.io/reviews/vaadin/flow/4023#-LB4pkBkZgNRtw1jwUHT-r1-38:-LB4wiHS1AYvDEZ6qnj4:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/a8192fd8ef8b9a9abdf5b6ae518a3543e9b9cac0/flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/registry/ValuePropertyRegistry.java#L38)):*
<details><summary><i>Previously, vaadin-bot (Vaadin Bot) wrote…</i></summary><blockquote>

CRITICAL Document this public method by adding an explicit description. [rule](https://sonar.projects.vaadin.com/coding_rules#rule_key=squid%3AUndocumentedApi)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4023)*

**Comment by manolo** [comment]
Review status: 4 of 6 files reviewed at latest revision, all discussions resolved.

---

*[flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/ComponentGenerator.java, line 81 at r2](https://reviewable.io/reviews/vaadin/flow/4023#-LB4pkBkZgNRtw1jwUHR-r2-81:-LB52S539I_Yio_Uic9f:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/5d7ef6792590c3aa21dc1f7458f9cc0413f8484d/flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/ComponentGenerator.java#L81)):*
> ```Java
> import com.vaadin.generator.registry.ExclusionRegistry;
> import com.vaadin.generator.registry.PropertyNameRemapRegistry;
> import com.vaadin.generator.registry.ValuePropertyRegistry;
> ```

Done.

---

*[flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/registry/ValuePropertyRegistry.java, line 37 at r2](https://reviewable.io/reviews/vaadin/flow/4023#-LB4pkBkZgNRtw1jwUHT-r2-37:-LB52jOV0aGsHzjRiY6C:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/5d7ef6792590c3aa21dc1f7458f9cc0413f8484d/flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/registry/ValuePropertyRegistry.java#L37)):*
> ```Java
>     }
> 
>     /**
> ```

Done.

---

*[flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/registry/ValuePropertyRegistry.java, line 43 at r2](https://reviewable.io/reviews/vaadin/flow/4023#-LB4pkBkZgNRtw1jwUHT-r2-43:-LB52mJVEPYOdX5YQYuB:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/5d7ef6792590c3aa21dc1f7458f9cc0413f8484d/flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/registry/ValuePropertyRegistry.java#L43)):*
> ```Java
>      *          property name used for value changes
>      */
>     public static String valueName(String elementIdentifier) {
> ```

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4023)*

**Comment by manolo** [comment]
Reviewed 1 of 2 files at r3.
Review status: 5 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4023)*

**Comment by manolo** [comment]
Reviewed 1 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4023)*

**Comment by gilberto-torrezan** [comment]
:lgtm:

---

Reviewed 4 of 5 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4023#-:-LB59ug85gEsyRakrVel:bnfp4nl)*

**Pull request merged**
