### PR TITLE
Download webdrivers once instead of every time a module is cleaned

### PR DESCRIPTION
**Pull request by Artur-**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3414)

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3414#-L3oZ8rtQDmdf2WNE-h3:-L3oZ8rtQDmdf2WNE-h4:bogeajt) (no related file):*
Can you explain when the temporary directory is cleaned?

The reason for cleaning is driver update: if there's some driver at the path specified, the plugin does not check its version and does not overwrite it, we've had cases when tests were run with old driver on dev machines because of this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3414)*

**Comment by SomeoneToIgnore** [comment]
*[flow-components-parent/demo-flow-components/pom.xml, line 274 at r1](https://reviewable.io:443/reviews/vaadin/flow/3414#-L3o__X7yJBD9WwqcNgb:-L3o__X7yJBD9WwqcNgc:b-qq80ni) ([raw file](https://github.com/vaadin/flow/blob/ccab4cbfd3e5fa06adb85700fd277b8cc97212eb/flow-components-parent/demo-flow-components/pom.xml#L274)):*
> ```XML
>                         <configuration>
>                             <onlyGetDriversForHostOperatingSystem>true</onlyGetDriversForHostOperatingSystem>
>                             <rootStandaloneServerDirectory>${project.rootdir}/driver</rootStandaloneServerDirectory>
> ```

We need to remove those directories from .gitignore and adjust maven-clean-plugin in the root pom also.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3414)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3414)*

**Comment by Artur-** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3414#-L3oZ8rtQDmdf2WNE-h3:-L3rFape0f6s719wwOGT:b-22q0wf) (no related file):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Can you explain when the temporary directory is cleaned?

The reason for cleaning is driver update: if there's some driver at the path specified, the plugin does not check its version and does not overwrite it, we've had cases when tests were run with old driver on dev machines because of this.
</blockquote></details>

fixed in https://github.com/Ardesco/selenium-standalone-server-plugin/pull/78
Let’s see if it goes through

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3414)*

**Comment by Artur-** [comment]
I'll reopen once it can be reviewed and merged

**Pull request closed without merging**
