### PR TITLE
Add selection column and select all to Grid

### PR DESCRIPTION
**Pull request by ahie**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/2739)

### CODE REVIEW

**Comment by gilberto-torrezan** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/AbstractGridMultiSelectionModel.java, line 248 at r1](https://reviewable.io:443/reviews/vaadin/flow/2739#-Kwtad-DBI3LIpxcj_SM:-Kwtad-DBI3LIpxcj_SN:b-vi21md) ([raw file](https://github.com/vaadin/flow/blob/eb916e4cc2ff8f94cb5ac3025551fe54e223cd04/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/AbstractGridMultiSelectionModel.java#L248)):*
> ```Java
> 
>     private void doSelect(T item, boolean userOriginated) {
>         Set<T> oldSelection = new LinkedHashSet<>(selected);
> ```

Considering that `contains` has the complexity of `O(1)` for `LinkedHashSet`, this method could be refactored to avoid creating a new collection and copying the object references in cases where the selected item is already selected.

Something like:
```
if (selected.contains(item)) {
    return;
}
Set<T> oldSelection = new LinkedHashSet<>(selected);
selected.add(item);
// ...
```

... but that is just a suggestion. I don't expect to have lots of cases where the user tries to select what is already selected.
(Note: this approach is very similar to the code you have below, for the multiselection)

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 267 at r1](https://reviewable.io:443/reviews/vaadin/flow/2739#-Kwtcv6Zqka9Sr14SMFC:-Kwtcv6Zqka9Sr14SMFD:b-za34bq) ([raw file](https://github.com/vaadin/flow/blob/eb916e4cc2ff8f94cb5ac3025551fe54e223cd04/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L267)):*
> ```Java
>             @Override
>             protected <T> GridSelectionModel<T> createModel(Grid<T> grid) {
>                 return new AbstractGridMultiSelectionModel<T>(grid) {
> ```

Thank you so much for that! That huge inner class was hurting my eyes already.

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 695 at r1](https://reviewable.io:443/reviews/vaadin/flow/2739#-KwtcUkINv6fKqykcwAl:-KwtcUkJajatwItm-brm:buk138i) ([raw file](https://github.com/vaadin/flow/blob/eb916e4cc2ff8f94cb5ac3025551fe54e223cd04/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L695)):*
> ```Java
> 
>     @ClientDelegate
>     private void selectAll() {
> ```

Why `deselectAll` is public and `selectAll` is private?

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/GridMultiSelectionModel.java, line 52 at r1](https://reviewable.io:443/reviews/vaadin/flow/2739#-KwtdOwUgKXL-a9BG01h:-KwtdOwUgKXL-a9BG01i:b-8bu6zl) ([raw file](https://github.com/vaadin/flow/blob/eb916e4cc2ff8f94cb5ac3025551fe54e223cd04/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/GridMultiSelectionModel.java#L52)):*
> ```Java
>          * being fetched from backend to application memory!</b>
>          */
>         VISIBLE,
> ```

I suggest having an extra mode - to toggle the selection of all visible items only (just like GitHub does in its table of issues when you select all). This is definitely a subject for another ticket, tough.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2739)*

**Comment by ahie** [comment]
Review status: 10 of 11 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 695 at r1](https://reviewable.io:443/reviews/vaadin/flow/2739#-KwtcUkINv6fKqykcwAl:-KwtpPxWXrKeUal9VQwh:bke7ems) ([raw file](https://github.com/vaadin/flow/blob/eb916e4cc2ff8f94cb5ac3025551fe54e223cd04/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L695)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Why `deselectAll` is public and `selectAll` is private?
</blockquote></details>

This is actually something I forgot to remove when refactoring. Additionally, `deselectAll` makes sense in both multi and single select, but `selectAll` doesn't in single selection mode.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2739)*

**Comment by ahie** [comment]
Review status: 9 of 11 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/AbstractGridMultiSelectionModel.java, line 248 at r1](https://reviewable.io:443/reviews/vaadin/flow/2739#-Kwtad-DBI3LIpxcj_SM:-Kwtr5CVTATInO6-N7ZB:b-lo305t) ([raw file](https://github.com/vaadin/flow/blob/eb916e4cc2ff8f94cb5ac3025551fe54e223cd04/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/AbstractGridMultiSelectionModel.java#L248)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Considering that `contains` has the complexity of `O(1)` for `LinkedHashSet`, this method could be refactored to avoid creating a new collection and copying the object references in cases where the selected item is already selected.

Something like:
```
if (selected.contains(item)) {
    return;
}
Set<T> oldSelection = new LinkedHashSet<>(selected);
selected.add(item);
// ...
```

... but that is just a suggestion. I don't expect to have lots of cases where the user tries to select what is already selected.
(Note: this approach is very similar to the code you have below, for the multiselection)
</blockquote></details>

Added checks for these cases.

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/GridMultiSelectionModel.java, line 52 at r1](https://reviewable.io:443/reviews/vaadin/flow/2739#-KwtdOwUgKXL-a9BG01h:-Kwtq1okjwLoVNBgkDkQ:b-nzyoxi) ([raw file](https://github.com/vaadin/flow/blob/eb916e4cc2ff8f94cb5ac3025551fe54e223cd04/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/GridMultiSelectionModel.java#L52)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

I suggest having an extra mode - to toggle the selection of all visible items only (just like GitHub does in its table of issues when you select all). This is definitely a subject for another ticket, tough.
</blockquote></details>

Good idea in my opinion. :+1:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2739)*

**Comment by gilberto-torrezan** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2739)*

**Comment by gilberto-torrezan** [comment]
Reviewed 1 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2739)*

**Comment by gilberto-torrezan** [comment]
Reviewed 4 of 5 files at r4.
Review status: all files reviewed at latest revision, 15 unresolved discussions, some commit checks failed.

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/AbstractGridMultiSelectionModel.java, line 143 at r2](https://reviewable.io:443/reviews/vaadin/flow/2739#-KwtY2UgVW9TO_vHD8KD-r2-143:-Kx7wgLMhLHfy8sKotCM:b6yp80l) ([raw file](https://github.com/vaadin/flow/blob/b35302260fba8a56019a1cb5a798902d8fe72c42/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/AbstractGridMultiSelectionModel.java#L143)):*
<details><summary><i>Previously, vaadin-bot (Vaadin Bot) wrote…</i></summary><blockquote>

MAJOR Reduce this anonymous class number of lines from 34 to at most 20, or make it a named class. [rule](https://sonar.projects.vaadin.com/coding_rules#rule_key=squid%3AS1188)
</blockquote></details>

Sonar has a point here - would it be too cumbersome to extract it as a separate class?

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/GridSelectionColumn.java, line 32 at r4](https://reviewable.io:443/reviews/vaadin/flow/2739#-Kx7xMYceZBC5x5W5nJh:-Kx7xMYceZBC5x5W5nJi:bjsgbof) ([raw file](https://github.com/vaadin/flow/blob/0b98db8806ccf8b1cf925f9b3f653f58e77029d0/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/GridSelectionColumn.java#L32)):*
> ```Java
> public class GridSelectionColumn extends Component {
> 
>     private final Runnable selectAllCallback;
> ```

Do we have a `SerializableRunnable` or something like it for this role? I wonder what would happen if the session gets serialized and the `Runnable`s are not serialized.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2739)*

**Comment by ahie** [comment]
Review status: all files reviewed at latest revision, 15 unresolved discussions, some commit checks failed.

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/AbstractGridMultiSelectionModel.java, line 143 at r2](https://reviewable.io:443/reviews/vaadin/flow/2739#-KwtY2UgVW9TO_vHD8KD-r2-143:-Kx7y4NW78MDXTp7DI05:bwtqzmu) ([raw file](https://github.com/vaadin/flow/blob/b35302260fba8a56019a1cb5a798902d8fe72c42/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/AbstractGridMultiSelectionModel.java#L143)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Sonar has a point here - would it be too cumbersome to extract it as a separate class?
</blockquote></details>

It's still a rather short anonymous class so I would rather have it here than a separate `GridMultiSelectImpl` file. Also it needs access to the `grid`object to add the listener.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2739)*

**Comment by ahie** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks broke.

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/GridSelectionColumn.java, line 32 at r4](https://reviewable.io:443/reviews/vaadin/flow/2739#-Kx7xMYceZBC5x5W5nJh:-Kx8VPU5ig9ilAPDkIyn:b-mwy2zf) ([raw file](https://github.com/vaadin/flow/blob/58b652fa319f086b5798d64b061d46024ca66f9b/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/GridSelectionColumn.java#L32)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Do we have a `SerializableRunnable` or something like it for this role? I wonder what would happen if the session gets serialized and the `Runnable`s are not serialized.
</blockquote></details>

Added `SerializableRunnable`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2739)*

**Comment by gilberto-torrezan** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2739)*

**Pull request merged**
