### PR TITLE
Remove ComponentSupplier out of flow and fix component generator

### PR DESCRIPTION
**Pull request by ZheSun88**
Regenerate all components.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3692)

### CODE REVIEW

**Comment by pekam** [comment]
Review status: 0 of 41 files reviewed at latest revision, 15 unresolved discussions.

---

*[flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/ComponentGenerator.java, line 554 at r1](https://reviewable.io:443/reviews/vaadin/flow/3692#-L7TRW2l6aWISHRpcQ0z:-L7TRW2l6aWISHRpcQ1-:b-o9vc8r) ([raw file](https://github.com/vaadin/flow/blob/793170b30034f6db9d48f0f5e905ede645ed28fd/flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/ComponentGenerator.java#L554)):*
> ```Java
>         // javaClass.addInterface(ComponentSupplier.class.getName()
>         // + GENERIC_TYPE_DECLARATION);
>         // }
> ```

remove instead of commenting out

---

*[flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/ComponentGenerator.java, line 872 at r1](https://reviewable.io:443/reviews/vaadin/flow/3692#-L7TRZ3Gc3MEFvn4UX3p:-L7TRZ3Gc3MEFvn4UX3q:b-o9vc8r) ([raw file](https://github.com/vaadin/flow/blob/793170b30034f6db9d48f0f5e905ede645ed28fd/flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/ComponentGenerator.java#L872)):*
> ```Java
>                             + GENERIC_TYPE + ", " + javaType.getName() + ">");
>                     // javaClass.removeImport(ComponentSupplier.class);
>                     // javaClass.removeInterface(ComponentSupplier.class);
> ```

remove instead of commenting out

---

*[flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/ComponentGenerator.java, line 1212 at r1](https://reviewable.io:443/reviews/vaadin/flow/3692#-L7TRwHEJq3TRzQFVZ8i:-L7TRwHEJq3TRzQFVZ8j:b-os68nd) ([raw file](https://github.com/vaadin/flow/blob/793170b30034f6db9d48f0f5e905ede645ed28fd/flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/ComponentGenerator.java#L1212)):*
> ```Java
>     private void addFluentReturnToMethod(MethodSource<JavaClassSource> method) {
>         method.setReturnType(GENERIC_TYPE);
>         method.setBody(method.getBody() + "return (R) this;");
> ```

Are you sure we should still keep the methods fluent?

---

*[flow-data/src/main/java/com/vaadin/flow/data/value/HasValueChangeMode.java, line 58 at r2](https://reviewable.io:443/reviews/vaadin/flow/3692#-L7TSiy23nuz7eHd3UO3:-L7TSiy23nuz7eHd3UO4:b-aifz71) ([raw file](https://github.com/vaadin/flow/blob/c0ab82c3942a55a73c748d1396cea82d815b7de2/flow-data/src/main/java/com/vaadin/flow/data/value/HasValueChangeMode.java#L58)):*
> ```Java
>         Objects.requireNonNull(valueChangeMode,
>                 "New valueChangeMode should not be null");
>         Element element = ((C) this).getElement();
> ```

I think `HasValue` should extend `HasElement` now. So you could directly call just `getElement()` here

---

*[flow-server/src/main/java/com/vaadin/flow/component/Focusable.java, line 61 at r1](https://reviewable.io:443/reviews/vaadin/flow/3692#-L7TT-so7izZ6bJ-u6be:-L7TT-so7izZ6bJ-u6bf:b-hkyumb) ([raw file](https://github.com/vaadin/flow/blob/793170b30034f6db9d48f0f5e905ede645ed28fd/flow-server/src/main/java/com/vaadin/flow/component/Focusable.java#L61)):*
> ```Java
>     default T setTabIndex(int tabIndex) {
>         getElement().setAttribute("tabindex", String.valueOf(tabIndex));
>         return (T) this;
> ```

This should maybe be made just non-fluent now. It's breaking change though so should be verified.

---

*[flow-server/src/main/java/com/vaadin/flow/component/HasOrderedComponents.java, line 87 at r1](https://reviewable.io:443/reviews/vaadin/flow/3692#-L7TTCXWl65S4CGX1hO2:-L7TTCXWl65S4CGX1hO3:b-7krfwy) ([raw file](https://github.com/vaadin/flow/blob/793170b30034f6db9d48f0f5e905ede645ed28fd/flow-server/src/main/java/com/vaadin/flow/component/HasOrderedComponents.java#L87)):*
> ```Java
>                     "The 'component' parameter cannot be null");
>         }
>         Iterator<Component> it = ((T) this).getChildren().sequential()
> ```

I think `getChildren` comes from `HasComponents` so you don't need to cast to `T`

---

*[flow-server/src/main/java/com/vaadin/flow/component/HasOrderedComponents.java, line 106 at r1](https://reviewable.io:443/reviews/vaadin/flow/3692#-L7TTKEO2U1JglxtxpQg:-L7TTKEO2U1JglxtxpQh:bnj7hl0) ([raw file](https://github.com/vaadin/flow/blob/793170b30034f6db9d48f0f5e905ede645ed28fd/flow-server/src/main/java/com/vaadin/flow/component/HasOrderedComponents.java#L106)):*
> ```Java
>      */
>     default int getComponentCount() {
>         return (int) ((T) this).getChildren().count();
> ```

same as above

---

*[flow-server/src/main/java/com/vaadin/flow/component/HasOrderedComponents.java, line 127 at r1](https://reviewable.io:443/reviews/vaadin/flow/3692#-L7TTLUNXMQxmbDGEbHs:-L7TTLUNXMQxmbDGEbHt:bnj7hl0) ([raw file](https://github.com/vaadin/flow/blob/793170b30034f6db9d48f0f5e905ede645ed28fd/flow-server/src/main/java/com/vaadin/flow/component/HasOrderedComponents.java#L127)):*
> ```Java
>                             + index);
>         }
>         return ((T) this).getChildren().sequential().skip(index).findFirst()
> ```

same as above

---

*[flow-server/src/main/java/com/vaadin/flow/component/HasValue.java, line 35 at r1](https://reviewable.io:443/reviews/vaadin/flow/3692#-L7TTPG9o5P_y8BMqSS3:-L7TTPG9o5P_y8BMqSS4:bftmrsv) ([raw file](https://github.com/vaadin/flow/blob/793170b30034f6db9d48f0f5e905ede645ed28fd/flow-server/src/main/java/com/vaadin/flow/component/HasValue.java#L35)):*
> ```Java
>  *            the value type
>  */
> public interface HasValue<C extends Component, V> {
> ```

extend `HasElement`

---

*[flow-server/src/main/java/com/vaadin/flow/component/HasValue.java, line 153 at r1](https://reviewable.io:443/reviews/vaadin/flow/3692#-L7TTS7A2k-CbDRBOAN9:-L7TTS7A2k-CbDRBOANA:bk5jcee) ([raw file](https://github.com/vaadin/flow/blob/793170b30034f6db9d48f0f5e905ede645ed28fd/flow-server/src/main/java/com/vaadin/flow/component/HasValue.java#L153)):*
> ```Java
>     default Registration addValueChangeListener(
>             ValueChangeListener<C, V> listener) {
>         return ((C) this).getElement().addPropertyChangeListener(
> ```

no need to cast after extending `HasElement`

---

*[flow-server/src/main/java/com/vaadin/flow/component/HasValue.java, line 156 at r1](https://reviewable.io:443/reviews/vaadin/flow/3692#-L7TTWCe2wUDM53Na_g6:-L7TTWCe2wUDM53Na_g7:bk5jcee) ([raw file](https://github.com/vaadin/flow/blob/793170b30034f6db9d48f0f5e905ede645ed28fd/flow-server/src/main/java/com/vaadin/flow/component/HasValue.java#L156)):*
> ```Java
>                 getClientValuePropertyName(),
>                 event -> listener
>                         .onComponentEvent(new ValueChangeEvent<>((C) this,
> ```

no need to cast after extending `HasElement`

---

*[flow-server/src/main/java/com/vaadin/flow/component/HasValue.java, line 244 at r1](https://reviewable.io:443/reviews/vaadin/flow/3692#-L7TTWxR4OikbLZZynbq:-L7TTWxR4OikbLZZynbr:bk5jcee) ([raw file](https://github.com/vaadin/flow/blob/793170b30034f6db9d48f0f5e905ede645ed28fd/flow-server/src/main/java/com/vaadin/flow/component/HasValue.java#L244)):*
> ```Java
>      */
>     default void setReadOnly(boolean readOnly) {
>         ((C) this).getElement().setProperty("readonly", readOnly);
> ```

no need to cast after extending `HasElement`

---

*[flow-server/src/main/java/com/vaadin/flow/component/HasValue.java, line 254 at r1](https://reviewable.io:443/reviews/vaadin/flow/3692#-L7TTXWOkIguLuGSwj9p:-L7TTXWOkIguLuGSwj9q:bk5jcee) ([raw file](https://github.com/vaadin/flow/blob/793170b30034f6db9d48f0f5e905ede645ed28fd/flow-server/src/main/java/com/vaadin/flow/component/HasValue.java#L254)):*
> ```Java
>      */
>     default boolean isReadOnly() {
>         return ((C) this).getElement().getProperty("readonly", false);
> ```

no need to cast after extending `HasElement`

---

*[flow-server/src/main/java/com/vaadin/flow/component/HasValue.java, line 267 at r1](https://reviewable.io:443/reviews/vaadin/flow/3692#-L7TTY0C53L0k3rYTsQP:-L7TTY0C53L0k3rYTsQQ:bk5jcee) ([raw file](https://github.com/vaadin/flow/blob/793170b30034f6db9d48f0f5e905ede645ed28fd/flow-server/src/main/java/com/vaadin/flow/component/HasValue.java#L267)):*
> ```Java
>      */
>     default void setRequiredIndicatorVisible(boolean requiredIndicatorVisible) {
>         ((C) this).getElement().setProperty("required",
> ```

no need to cast after extending `HasElement`

---

*[flow-server/src/main/java/com/vaadin/flow/component/HasValue.java, line 277 at r1](https://reviewable.io:443/reviews/vaadin/flow/3692#-L7TTYSb5_gtZkEkw2Br:-L7TTYSb5_gtZkEkw2Bs:bk5jcee) ([raw file](https://github.com/vaadin/flow/blob/793170b30034f6db9d48f0f5e905ede645ed28fd/flow-server/src/main/java/com/vaadin/flow/component/HasValue.java#L277)):*
> ```Java
>      */
>     default boolean isRequiredIndicatorVisible() {
>         return ((C) this).getElement().getProperty("required", false);
> ```

no need to cast after extending `HasElement`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3692)*

**Comment by ZheSun88** [comment]
Review status: 0 of 41 files reviewed at latest revision, 19 unresolved discussions.

---

*[flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/ComponentGenerator.java, line 554 at r1](https://reviewable.io:443/reviews/vaadin/flow/3692#-L7TRW2l6aWISHRpcQ0z:-L7TX5gaaqrCRezeG9T1:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/793170b30034f6db9d48f0f5e905ede645ed28fd/flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/ComponentGenerator.java#L554)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

remove instead of commenting out
</blockquote></details>

Done.

---

*[flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/ComponentGenerator.java, line 872 at r1](https://reviewable.io:443/reviews/vaadin/flow/3692#-L7TRZ3Gc3MEFvn4UX3p:-L7TYn6hyAxRcdI0dPHY:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/793170b30034f6db9d48f0f5e905ede645ed28fd/flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/ComponentGenerator.java#L872)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

remove instead of commenting out
</blockquote></details>

Done.

---

*[flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/ComponentGenerator.java, line 1212 at r1](https://reviewable.io:443/reviews/vaadin/flow/3692#-L7TRwHEJq3TRzQFVZ8i:-L7TYOqo-csWvGzoGjDh:b-3dduar) ([raw file](https://github.com/vaadin/flow/blob/793170b30034f6db9d48f0f5e905ede645ed28fd/flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/ComponentGenerator.java#L1212)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

Are you sure we should still keep the methods fluent?
</blockquote></details>

aww , one idea from me is to rename this method.  how about just simplify to`AddReturnToMethod`

---

*[flow-data/src/main/java/com/vaadin/flow/data/value/HasValueChangeMode.java, line 58 at r2](https://reviewable.io:443/reviews/vaadin/flow/3692#-L7TSiy23nuz7eHd3UO3:-L7TU6v3tM9XKC-HMEjv:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/c0ab82c3942a55a73c748d1396cea82d815b7de2/flow-data/src/main/java/com/vaadin/flow/data/value/HasValueChangeMode.java#L58)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

I think `HasValue` should extend `HasElement` now. So you could directly call just `getElement()` here
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/flow/component/Focusable.java, line 61 at r1](https://reviewable.io:443/reviews/vaadin/flow/3692#-L7TT-so7izZ6bJ-u6be:-L7TZOAJsAfLQAzEJRWR:bqg71u2) ([raw file](https://github.com/vaadin/flow/blob/793170b30034f6db9d48f0f5e905ede645ed28fd/flow-server/src/main/java/com/vaadin/flow/component/Focusable.java#L61)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

This should maybe be made just non-fluent now. It's breaking change though so should be verified.
</blockquote></details>

what would be a proper way to do this?

---

*[flow-server/src/main/java/com/vaadin/flow/component/HasOrderedComponents.java, line 87 at r1](https://reviewable.io:443/reviews/vaadin/flow/3692#-L7TTCXWl65S4CGX1hO2:-L7TV0u3zavKtd42Ddtm:b-ve6y0g) ([raw file](https://github.com/vaadin/flow/blob/793170b30034f6db9d48f0f5e905ede645ed28fd/flow-server/src/main/java/com/vaadin/flow/component/HasOrderedComponents.java#L87)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

I think `getChildren` comes from `HasComponents` so you don't need to cast to `T`
</blockquote></details>

No, `getChildren` comes from `Component` not `HasComponents`. without cast , there will be an compilation error.

---

*[flow-server/src/main/java/com/vaadin/flow/component/HasOrderedComponents.java, line 106 at r1](https://reviewable.io:443/reviews/vaadin/flow/3692#-L7TTKEO2U1JglxtxpQg:-L7TZVzk-zNT-r1FWZNK:brevxe9) ([raw file](https://github.com/vaadin/flow/blob/793170b30034f6db9d48f0f5e905ede645ed28fd/flow-server/src/main/java/com/vaadin/flow/component/HasOrderedComponents.java#L106)):*
> `getChildren` comes from `Component` not `HasComponents`.

---

*[flow-server/src/main/java/com/vaadin/flow/component/HasOrderedComponents.java, line 127 at r1](https://reviewable.io:443/reviews/vaadin/flow/3692#-L7TTLUNXMQxmbDGEbHs:-L7TZZ01mLlxcvjrJrd4:bz7m4tv) ([raw file](https://github.com/vaadin/flow/blob/793170b30034f6db9d48f0f5e905ede645ed28fd/flow-server/src/main/java/com/vaadin/flow/component/HasOrderedComponents.java#L127)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

`getChildren` comes from `Component` not `HasComponents`.

---

*[flow-server/src/main/java/com/vaadin/flow/component/HasValue.java, line 35 at r1](https://reviewable.io:443/reviews/vaadin/flow/3692#-L7TTPG9o5P_y8BMqSS3:-L7TYkFajL-TmozVEf6Z:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/793170b30034f6db9d48f0f5e905ede645ed28fd/flow-server/src/main/java/com/vaadin/flow/component/HasValue.java#L35)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

extend `HasElement`
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/flow/component/HasValue.java, line 153 at r1](https://reviewable.io:443/reviews/vaadin/flow/3692#-L7TTS7A2k-CbDRBOAN9:-L7TYl7xOA7jel59u5mD:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/793170b30034f6db9d48f0f5e905ede645ed28fd/flow-server/src/main/java/com/vaadin/flow/component/HasValue.java#L153)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

no need to cast after extending `HasElement`
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/flow/component/HasValue.java, line 156 at r1](https://reviewable.io:443/reviews/vaadin/flow/3692#-L7TTWCe2wUDM53Na_g6:-L7TVypMy36AKiuZKGMp:bn96foh) ([raw file](https://github.com/vaadin/flow/blob/793170b30034f6db9d48f0f5e905ede645ed28fd/flow-server/src/main/java/com/vaadin/flow/component/HasValue.java#L156)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

no need to cast after extending `HasElement`
</blockquote></details>

this one is different, as `(C) this` refers to the component and (if you notice) this is another `this` following refers the the HasValue instance

---

*[flow-server/src/main/java/com/vaadin/flow/component/HasValue.java, line 244 at r1](https://reviewable.io:443/reviews/vaadin/flow/3692#-L7TTWxR4OikbLZZynbq:-L7TWeSwT6n8P_Q3nF--:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/793170b30034f6db9d48f0f5e905ede645ed28fd/flow-server/src/main/java/com/vaadin/flow/component/HasValue.java#L244)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

no need to cast after extending `HasElement`
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/flow/component/HasValue.java, line 254 at r1](https://reviewable.io:443/reviews/vaadin/flow/3692#-L7TTXWOkIguLuGSwj9p:-L7TWf8tV2a3WQus-9WF:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/793170b30034f6db9d48f0f5e905ede645ed28fd/flow-server/src/main/java/com/vaadin/flow/component/HasValue.java#L254)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

no need to cast after extending `HasElement`
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/flow/component/HasValue.java, line 267 at r1](https://reviewable.io:443/reviews/vaadin/flow/3692#-L7TTY0C53L0k3rYTsQP:-L7TWidQcxJoT67IynSF:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/793170b30034f6db9d48f0f5e905ede645ed28fd/flow-server/src/main/java/com/vaadin/flow/component/HasValue.java#L267)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

no need to cast after extending `HasElement`
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/flow/component/HasValue.java, line 277 at r1](https://reviewable.io:443/reviews/vaadin/flow/3692#-L7TTYSb5_gtZkEkw2Br:-L7TWlGHzXQ3tN6ldivm:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/793170b30034f6db9d48f0f5e905ede645ed28fd/flow-server/src/main/java/com/vaadin/flow/component/HasValue.java#L277)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

no need to cast after extending `HasElement`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3692)*

**Comment by pekam** [comment]
Review status: 0 of 41 files reviewed at latest revision, 11 unresolved discussions.

---

*[flow-data/src/main/java/com/vaadin/flow/data/value/HasValueChangeMode.java, line 58 at r2](https://reviewable.io:443/reviews/vaadin/flow/3692#-L7TSiy23nuz7eHd3UO3:-L7Tg2N0I09utVoVtAy5:b-7jwqui) ([raw file](https://github.com/vaadin/flow/blob/c0ab82c3942a55a73c748d1396cea82d815b7de2/flow-data/src/main/java/com/vaadin/flow/data/value/HasValueChangeMode.java#L58)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I think our conventions is to not use `this` when calling object's own methods.

---

*[flow-server/src/main/java/com/vaadin/flow/component/HasValue.java, line 153 at r1](https://reviewable.io:443/reviews/vaadin/flow/3692#-L7TTS7A2k-CbDRBOAN9:-L7TfnPUoUxxAkVGygPx:bewqrhr) ([raw file](https://github.com/vaadin/flow/blob/793170b30034f6db9d48f0f5e905ede645ed28fd/flow-server/src/main/java/com/vaadin/flow/component/HasValue.java#L153)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I think our convention is to not use `this` when calling object's own methods. Same for below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3692)*

**Comment by pekam** [comment]
Reviewed 1 of 2 files at r4.
Review status: 0 of 41 files reviewed at latest revision, 10 unresolved discussions.

---

*[flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/ComponentGenerator.java, line 614 at r5](https://reviewable.io:443/reviews/vaadin/flow/3692#-L7UR3DU9iW4yWkZItTX:-L7UR3DU9iW4yWkZItTY:b-iyvhz2) ([raw file](https://github.com/vaadin/flow/blob/41e05a1cf441c2ce5fe688828f1e329125ab3a3c/flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/ComponentGenerator.java#L614)):*
> ```Java
>                 .addTagValue(JAVADOC_SEE,
>                         "<a href=\"https://html.spec.whatwg.org/multipage/scripting.html#the-slot-element\">Spec website about slots</a>");
>         
> ```

whitespace

---

*[flow-components-parent/flow-code-generator-api/src/test/java/com/vaadin/generator/ComponentGeneratorTest.java, line 541 at r5](https://reviewable.io:443/reviews/vaadin/flow/3692#-L7USKdjPG7Ijl8suqnj:-L7USKdjPG7Ijl8suqnk:becxvmt) ([raw file](https://github.com/vaadin/flow/blob/41e05a1cf441c2ce5fe688828f1e329125ab3a3c/flow-components-parent/flow-code-generator-api/src/test/java/com/vaadin/generator/ComponentGeneratorTest.java#L541)):*
> ```Java
> 
>     @Test
>     public void generateClass_EventChangeReturn() {
> ```

The thing that you apparently are testing is: If generated class has a property with `notify=true`, is there a `addListener` method which creates an `Event` object and are the correct parameters passed to it. So...
1. The name of the test  should be something like `componentContainsNotifiedProperty_generatedListenerUsesComponentAsEventSource`
2. There's a lot of non-relevant stuff here that you should remove to keep the test focused on the thing that you are actually testing. So only the property-data with `setNotify(true)` should be here, while the other property, the function and the slots can be removed.

---

*[flow-components-parent/flow-code-generator-api/src/test/java/com/vaadin/generator/ComponentGeneratorTest.java, line 570 at r5](https://reviewable.io:443/reviews/vaadin/flow/3692#-L7UUkKRMLO2OBl84tVf:-L7UUkKRMLO2OBl84tVg:bqfw7mw) ([raw file](https://github.com/vaadin/flow/blob/41e05a1cf441c2ce5fe688828f1e329125ab3a3c/flow-components-parent/flow-code-generator-api/src/test/java/com/vaadin/generator/ComponentGeneratorTest.java#L570)):*
> ```Java
>                 "(R) this should be included in the change event return",
>                 generatedClass, containsString(
>                         "(R) this, event.isUserOriginated())));"));
> ```

Now this `(R) this` could be anywhere.
The part that you are testing is something like `ChangeEvent<R>((R) this`, to make sure it's in the event's constructor. Or you can add the `event.isUserOriginated()` there too but then you should change the error-message and the test-name accordingly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3692)*

**Comment by ZheSun88** [comment]
Review status: 0 of 41 files reviewed at latest revision, 10 unresolved discussions.

---

*[flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/ComponentGenerator.java, line 614 at r5](https://reviewable.io:443/reviews/vaadin/flow/3692#-L7UR3DU9iW4yWkZItTX:-L7UYntBeGo_flHGRyHj:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/41e05a1cf441c2ce5fe688828f1e329125ab3a3c/flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/ComponentGenerator.java#L614)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

whitespace
</blockquote></details>

Done.

---

*[flow-components-parent/flow-code-generator-api/src/test/java/com/vaadin/generator/ComponentGeneratorTest.java, line 541 at r5](https://reviewable.io:443/reviews/vaadin/flow/3692#-L7USKdjPG7Ijl8suqnj:-L7UYdquWhK-W3RvaKro:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/41e05a1cf441c2ce5fe688828f1e329125ab3a3c/flow-components-parent/flow-code-generator-api/src/test/java/com/vaadin/generator/ComponentGeneratorTest.java#L541)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

The thing that you apparently are testing is: If generated class has a property with `notify=true`, is there a `addListener` method which creates an `Event` object and are the correct parameters passed to it. So...
1. The name of the test  should be something like `componentContainsNotifiedProperty_generatedListenerUsesComponentAsEventSource`
2. There's a lot of non-relevant stuff here that you should remove to keep the test focused on the thing that you are actually testing. So only the property-data with `setNotify(true)` should be here, while the other property, the function and the slots can be removed.
</blockquote></details>

Done.

---

*[flow-components-parent/flow-code-generator-api/src/test/java/com/vaadin/generator/ComponentGeneratorTest.java, line 570 at r5](https://reviewable.io:443/reviews/vaadin/flow/3692#-L7UUkKRMLO2OBl84tVf:-L7UYdGgriZ0vmRGwKZJ:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/41e05a1cf441c2ce5fe688828f1e329125ab3a3c/flow-components-parent/flow-code-generator-api/src/test/java/com/vaadin/generator/ComponentGeneratorTest.java#L570)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

Now this `(R) this` could be anywhere.
The part that you are testing is something like `ChangeEvent<R>((R) this`, to make sure it's in the event's constructor. Or you can add the `event.isUserOriginated()` there too but then you should change the error-message and the test-name accordingly.
</blockquote></details>

Done.

---

*[flow-data/src/main/java/com/vaadin/flow/data/value/HasValueChangeMode.java, line 58 at r2](https://reviewable.io:443/reviews/vaadin/flow/3692#-L7TSiy23nuz7eHd3UO3:-L7ThDOPgasldyvjSFdh:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/c0ab82c3942a55a73c748d1396cea82d815b7de2/flow-data/src/main/java/com/vaadin/flow/data/value/HasValueChangeMode.java#L58)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

I think our conventions is to not use `this` when calling object's own methods.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3692)*

**Comment by pekam** [comment]
:lgtm:

---

Reviewed 27 of 40 files at r1, 1 of 2 files at r4, 11 of 13 files at r5, 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3692#-:-L7UrffkjmcaLZKrf-Nh:bnfp4nl)*

**Pull request merged**
