### PR TITLE
fix: Always set theme variant

### LINKED ISSUE #16256: Theme variant not applied with precompiled frontend bundle
### Description of the bug

No `theme` attribute is applied to the page root when a theme variant is applied with the `@Theme` annotation's `variant` parameter.

The variant starts working again with `vaadin.frontend.hotdeploy=true`

### Expected behavior

`theme` attrib should be applied to page root element when `variant` is supplied to `@Theme` annotation

### Minimal reproducible example

1. Generate a new V24 application with start.vaadin.com, with the "color mode" set to Dark.
2. Run the app
3. Observe dark mode not getting applied

### Versions

- Vaadin / Flow version: V24

### PR DESCRIPTION
**Pull request by Artur-**
Sets the theme variant in the index page so it is applied in all modes

Fixes #16256

### CODE REVIEW

**Review by mshabarov — COMMENTED** [review]
Tested with starter project, works as expected - DARK theme variant is applied.

Expectations in `NodeUpdateImportsWithByteCodeScannerTest` need to be tuned, it fails without this patch.
Also a new test covering the change would be good.

**Comment by Artur-** [comment]
I added a test in e010bab

**Review by mshabarov — DISMISSED** [review]

**Comment by Artur-** [comment]
Fixed the second test..

**Review by mshabarov — APPROVED** [review]

**Comment by MrDraqon** [comment]
Anything i can do to my current project to get the theme working? or will i have to wait for the next release?

**Comment by mshabarov** [comment]
@MrDraqon this patch is included into Vaadin 24.0.2 which is going to be out today (March 24) or beginning of next week.

**Comment by MrDraqon** [comment]
> @MrDraqon this patch is included into Vaadin 24.0.2 which is going to be out today (March 24) or beginning of next week.

Tried version 24.0.2 i am now getting error bellow when i try to start the app i downloaded a fresh project from starter and made no changes to the project, also checked and the folder with the name 'myapp' is in the right place inside frontend/themes

com.vaadin.flow.server.ExecutionFailedException: Discovered @Theme annotation with theme name 'myapp', but could not find the theme directory in the project or available as a jar dependency. Check if you forgot to create the folder under 'D:\Coding\Web%20Coding\vaadin\test\my-app\my-app\.\frontend\themes' or have mistyped the theme or folder name for 'myapp'.

**Comment by Artur-** [comment]
See #16396

**Comment by knoobie** [comment]
Want me to create a ticket for it?

**Comment by Artur-** [comment]
Nah, it's fixed in #16786

**Pull request merged**
