### PR TITLE
Rename Has*Listener to *Notifier and fix generator

### PR DESCRIPTION
**Pull request by ZheSun88**
Remove HasClickListeners;
Regenerate components.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3900)

### CODE REVIEW

**Comment by gilberto-torrezan** [comment]
Reviewed 15 of 17 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/flow/3900#-LADLh1TElv65VrzYa73:-LADLh1TElv65VrzYa74:ba378aj) (no related file):*
You need to update ClickNotifier to have the same features as the old `HascClickListeners` - basically, the `getSource()` method should return the corecct type of the component, and not just `Component`.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3900)*

**Comment by ZheSun88** [comment]
Review status: 13 of 15 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/flow/3900#-LADLh1TElv65VrzYa73:-LADQLhF2aZfmrOOE4tz:b-qbgb6z) (no related file):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

You need to update ClickNotifier to have the same features as the old `HascClickListeners` - basically, the `getSource()` method should return the corecct type of the component, and not just `Component`.
</blockquote></details>

I just updated `ClickNotifier` and `ClickEvent`. Is this correct?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3900)*

**Comment by ZheSun88** [comment]
Review status: 8 of 15 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/flow/3900#-LADLh1TElv65VrzYa73:-LADZ7Wj1uj6g4XMqLpq:b-jon3xl) (no related file):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

I just updated `ClickNotifier` and `ClickEvent`. Is this correct?
</blockquote></details>

and regenerated the Components

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3900)*

**Comment by ZheSun88** [comment]
Review status: 8 of 17 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/flow/3900#-LADLh1TElv65VrzYa73:-LADgObWCCSDXXgLgF4-:bij1dwy) (no related file):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

and regenerated the Components
</blockquote></details>

@gilberto-torrezan  it is ready to be reviewed now

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3900)*

**Comment by gilberto-torrezan** [comment]
:lgtm:

---

Reviewed 7 of 8 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3900#-:-LAHIGqM4zKKEI__1Rk4:bnfp4nl)*

**Pull request merged**
