### PR TITLE
Make isEmpty() use valueEquals()

### LINKED ISSUE #4067: Make field classes use valueEquals for comparing with the default value
`AbstractField ` and `AbstractCompositeField` should override `isEmpty` to use their own `valueEquals` implementation instead of `Object.equals` that is used by the `default` implementation inherited from `HasValue`.

### PR DESCRIPTION
**Pull request by Legioth**
Fixes #4067

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/4069)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 3 of 4 files at r1.
Review status: 3 of 4 files reviewed at latest revision, all discussions resolved.

---

*[flow-server/src/test/java/com/vaadin/flow/component/AbstractCompositeFieldTest.java, line 46 at r1](https://reviewable.io/reviews/vaadin/flow/4069#-LBewP8gC2SvgAjrKM9T:-LBewP8gC2SvgAjrKM9U:bitzzz7) ([raw file](https://github.com/vaadin/flow/blob/da8e35c5aacbbc3865cd4fbc8f48a608409acf24/flow-server/src/test/java/com/vaadin/flow/component/AbstractCompositeFieldTest.java#L46)):*
> ```
> return value1.trim().equals(value2.trim());
> ```

this makes values `" a "` and `"a"` equals. Is it really expected or there should be also check that both have `0` length ?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4069)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4069)*

**Comment by Legioth** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-server/src/test/java/com/vaadin/flow/component/AbstractCompositeFieldTest.java, line 46 at r1](https://reviewable.io/reviews/vaadin/flow/4069#-LBewP8gC2SvgAjrKM9T:-LBf-xxD-mgwspUQMLtT:bd3ssul) ([raw file](https://github.com/vaadin/flow/blob/da8e35c5aacbbc3865cd4fbc8f48a608409acf24/flow-server/src/test/java/com/vaadin/flow/component/AbstractCompositeFieldTest.java#L46)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
> return value1.trim().equals(value2.trim());
> ```

this makes values `" a "` and `"a"` equals. Is it really expected or there should be also check that both have `0` length ?
</blockquote></details>

I don't think anything is "expected" here since this is just a silly example for being able to test this one case. I can change it if you think it would make the test easier to understand?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4069)*

**Comment by denis-anisimov** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-server/src/test/java/com/vaadin/flow/component/AbstractCompositeFieldTest.java, line 46 at r1](https://reviewable.io/reviews/vaadin/flow/4069#-LBewP8gC2SvgAjrKM9T:-LBf0bcw1qEXHsFn0Wlf:bl2dhnb) ([raw file](https://github.com/vaadin/flow/blob/da8e35c5aacbbc3865cd4fbc8f48a608409acf24/flow-server/src/test/java/com/vaadin/flow/component/AbstractCompositeFieldTest.java#L46)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

I don't think anything is "expected" here since this is just a silly example for being able to test this one case. I can change it if you think it would make the test easier to understand?
</blockquote></details>

Oh, this is just a test.
OK.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4069#-:-LBf0fi39QnY3OIJxl2g:bnfp4nl)*

**Pull request merged**
