### PR TITLE
Add files for component IT test

### PR DESCRIPTION
**Pull request by ZheSun88**
+add ComponentDemoTest class;
+add parent Pom to flow-component and remove overwritten properties;
+add test-util and junit to pom of demo-helper

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/2814)

### CODE REVIEW

**Comment by caalador** [comment]
Check formatting of poms as they are 100% changed with whitespace changes.

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-components-parent/flow-component-demo-helpers/src/main/java/com/vaadin/flow/demo/ComponentDemoTest.java, line 76 at r1](https://reviewable.io:443/reviews/vaadin/flow/2814#-KxmWb4qF5-opf1JtBmM:-KxmWb4qF5-opf1JtBmN:b-byztc7) ([raw file](https://github.com/vaadin/flow/blob/477ff0776eafd81d73b2f37921ed224657f77e1b/flow-components-parent/flow-component-demo-helpers/src/main/java/com/vaadin/flow/demo/ComponentDemoTest.java#L76)):*
> ```Java
>         }
>     }
> }
> ```

New Line

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2814#-:-KxmWpr949zoDFqpppy3:b-yhm1x6)*

**Comment by ZheSun88** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-components-parent/flow-component-demo-helpers/src/main/java/com/vaadin/flow/demo/ComponentDemoTest.java, line 76 at r1](https://reviewable.io:443/reviews/vaadin/flow/2814#-KxmWb4qF5-opf1JtBmM:-KxmX9JsMvArSWxtjIU4:b-1nbo03) ([raw file](https://github.com/vaadin/flow/blob/477ff0776eafd81d73b2f37921ed224657f77e1b/flow-components-parent/flow-component-demo-helpers/src/main/java/com/vaadin/flow/demo/ComponentDemoTest.java#L76)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

New Line
</blockquote></details>

just added.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2814)*

**Comment by ZheSun88** [comment]
yes.. just removed

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2814#-:-KxmXqVIyDlm_VqsjhRp:b-1ohb28)*

**Comment by caalador** [comment]
Reviewed 2 of 3 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2814)*

**Pull request merged**
