### PR TITLE
chore: Remove drivers.xml from project

### PR DESCRIPTION
**Pull request by mshabarov**
## Description

Please list all relevant dependencies in this section and provide summary of the change, motivation and context.

Fixes # (issue)

## Type of change

- [ ] Bugfix
- [ ] Feature

## Checklist

- [ ] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [ ] I have added a description following the guideline.
- [ ] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

### CODE REVIEW

**Comment by ZheSun88** [comment]
is this file still used in flow? i remember @mcollovati have updated flow to use webdriver manager a while ago

**Comment by mshabarov** [comment]
Indeed, it's not needed anymore. Let's remove it from project.

**Comment by ZheSun88** [comment]
by the way.. i am not sure if it is still needed for other branches..
so the cherry pick for this way might be interesting.

**Comment by ZheSun88** [comment]
by a quick look, at 2.7 and 2.8 branches are still using the drivers.xml. ..

**Comment by mcollovati** [comment]
This change cannot be ported to 2.7 and 2.8 because drivers.xml is still in use.
To get rid of drivers file, other than #13710, also #12897 would be needed

**Comment by mshabarov** [comment]
Thanks Marco! I've excluded 2.7 and 2.8 for now.

**Comment by mshabarov** [comment]
Can be merge now, since the version in intern.json is handled automatically.

**Review by mcollovati — APPROVED** [review]

**Pull request merged**
