### PR TITLE
Don't use ServletContext instead use VaadinService/Servlet

### PR DESCRIPTION
**Pull request by caalador**
This is a step in the direction so that we only use one
point for getting our resources and any fixes done
are reflected to every place using getResource[AsStream]

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3656)

### CODE REVIEW

**Comment by gilberto-torrezan** [comment]
Reviewed 1 of 19 files at r1.
Review status: 1 of 19 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3656)*

**Comment by gilberto-torrezan** [comment]
Reviewed 14 of 19 files at r1, 4 of 4 files at r2.
Review status: 13 of 19 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3656#-L793rgVuNkS0n68pc7I:-L793rgVuNkS0n68pc7J:b-judrsw) (no related file):*
The branch is conflicting with master

---

*[flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java, line 2151 at r2](https://reviewable.io:443/reviews/vaadin/flow/3656#-L795IfCs0O4ekqhON1F:-L795IfCs0O4ekqhON1G:bb3vj1f) ([raw file](https://github.com/vaadin/flow/blob/dcaf5149e140d0c950a31a4654ce11a14ac1be33/flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java#L2151)):*
> ```Java
>      *         there is no resource at that path
>      */
>     public abstract URL getResource(String path);
> ```

Asking in a general sense: when should we use `Optional` and when should we return `null` in absence of a value?
I'm perfectly fine with any solution, I just want to make it clear when to use one or another.

---

*[flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java, line 2151 at r2](https://reviewable.io:443/reviews/vaadin/flow/3656#-L79O_1R77PYYYks_P3B:-L79O_1R77PYYYks_P3C:b-fj20fa) ([raw file](https://github.com/vaadin/flow/blob/dcaf5149e140d0c950a31a4654ce11a14ac1be33/flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java#L2151)):*
> ```Java
>      *         there is no resource at that path
>      */
>     public abstract URL getResource(String path);
> ```

What should happen if `path` is `null` ? (same for the `getResourceAsStream` bellow).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3656)*

**Comment by gilberto-torrezan** [comment]
Reviewed 4 of 6 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[flow-server/src/test/java/com/vaadin/flow/component/internal/HtmlDependencyParserTest.java, line 134 at r4](https://reviewable.io:443/reviews/vaadin/flow/3656#-L79QI9heYPJWg8sEDV-:-L79QI9heYPJWg8sEDV0:b-aennsw) ([raw file](https://github.com/vaadin/flow/blob/c62696d7fe548f47adda974fc8203382031a752b/flow-server/src/test/java/com/vaadin/flow/component/internal/HtmlDependencyParserTest.java#L134)):*
> ```Java
>                 dependencies.contains("relative2.html"));
>         Assert.assertTrue(
>                 "Dependencies parser doesn't return the realtive URI which is located sub folder",
> ```

realtive is a cousin of realtime?

---

*[flow-server/src/test/java/com/vaadin/flow/component/internal/HtmlDependencyParserTest.java, line 138 at r4](https://reviewable.io:443/reviews/vaadin/flow/3656#-L79QcBuVtWC53LqPQH4:-L79QcBvEylRMJ1vGxwd:b-c96el3) ([raw file](https://github.com/vaadin/flow/blob/c62696d7fe548f47adda974fc8203382031a752b/flow-server/src/test/java/com/vaadin/flow/component/internal/HtmlDependencyParserTest.java#L138)):*
> ```Java
>         Assert.assertTrue("Dependencies parser doesn't return the absolute URI",
>                 dependencies.contains("/absolute.html"));
>     }
> ```

Since mocks are being used now, would it make sense to verify that the mock was actually called n times during this test?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3656)*

**Comment by caalador** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java, line 2151 at r2](https://reviewable.io:443/reviews/vaadin/flow/3656#-L795IfCs0O4ekqhON1F:-L79TtxYIqdkbTDKYZpv:bh7mpx1) ([raw file](https://github.com/vaadin/flow/blob/dcaf5149e140d0c950a31a4654ce11a14ac1be33/flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java#L2151)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Asking in a general sense: when should we use `Optional` and when should we return `null` in absence of a value?
I'm perfectly fine with any solution, I just want to make it clear when to use one or another.
</blockquote></details>

I don't know, but I hate less asking if the value is `null` than asking if the value `isPresent` and then having to `get` the value

---

*[flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java, line 2151 at r2](https://reviewable.io:443/reviews/vaadin/flow/3656#-L79O_1R77PYYYks_P3B:-L79UQAfM4qwyVhTAGi9:b-62wmnh) ([raw file](https://github.com/vaadin/flow/blob/dcaf5149e140d0c950a31a4654ce11a14ac1be33/flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java#L2151)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

What should happen if `path` is `null` ? (same for the `getResourceAsStream` bellow).
</blockquote></details>

The javadoc say that the path must begin with a `/`. also Accoring to functional spec if you dig deep enough a null will result in a `MalformedURLException` that we actually handle and you will receive a `null`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3656)*

**Comment by caalador** [comment]
Review status: 18 of 19 files reviewed at latest revision, 3 unresolved discussions.

---

*[flow-server/src/test/java/com/vaadin/flow/component/internal/HtmlDependencyParserTest.java, line 134 at r4](https://reviewable.io:443/reviews/vaadin/flow/3656#-L79QI9heYPJWg8sEDV-:-L79WYM_pzcjcgX9XqIn:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/c62696d7fe548f47adda974fc8203382031a752b/flow-server/src/test/java/com/vaadin/flow/component/internal/HtmlDependencyParserTest.java#L134)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

realtive is a cousin of realtime?
</blockquote></details>

Done.

---

*[flow-server/src/test/java/com/vaadin/flow/component/internal/HtmlDependencyParserTest.java, line 138 at r4](https://reviewable.io:443/reviews/vaadin/flow/3656#-L79QcBuVtWC53LqPQH4:-L79WYm0ZGoJEH0GyX6-:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/c62696d7fe548f47adda974fc8203382031a752b/flow-server/src/test/java/com/vaadin/flow/component/internal/HtmlDependencyParserTest.java#L138)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Since mocks are being used now, would it make sense to verify that the mock was actually called n times during this test?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3656)*

**Comment by gilberto-torrezan** [comment]
Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3656)*

**Comment by gilberto-torrezan** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3656#-:-L7T9WCP1MH37G_3yQSH:bnfp4nl)*

**Pull request merged**
