### PR TITLE
Convert Key to interface, add static instances and improve JavaDocs

### LINKED ISSUE #4046: Unclear how to use addKeyDown/Up/PressListener
`KeyNotifier.addKeyDownListener(String key, ComponentEventListener<KeyDownEvent> listener, KeyModifier... modifiers)` javadoc says
```
Adds a {@code keydown} listener to this component, conditional on key and modifiers.
key: the key to match
```

What remains unclear is:
* Why is the key a String? What happens with `addKeyDownListener("abc",...)`?
* How do I listen to enter? Debugging shows that I should use "Enter" as they `key to match`, which was quite unexpected. Especially as "enter" does not work. There is seemingly no way to know upfront if I should use `esc`, `Esc`, `escape` or `Escape` to match the escape key

I would have expected the `key` parameter to be a a character and `13` would listen to enter

### PR DESCRIPTION
**Pull request by heruan**
Improves keyboard event listeners:

- `com.vaadin.flow.component.Key` is now a functional interface;
- the same interface provides several predefined instances (from [MDN/Key_Values](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key/Key_Values))
- JavaDocs on notifier mixins are more exhaustive

Fixes #4046

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/4061)

### CODE REVIEW

**Comment by Legioth** [comment]
Apparently, `<kbd>` is not valid in JavaDocs.

**Comment by heruan** [comment]
Replaced `<kbd>` with `<code>`.

**Comment by heruan** [comment]
Not sure why TC build fails 😕

**Comment by Legioth** [comment]
The build log says `flow-server/src/main/java/com/vaadin/flow/component/Key.java:446: error: unknown attribute: rel` and similarly for rows 456, 463, 470, 1444 (`unknown attribute: title`) and 1445

**Comment by heruan** [comment]
Thank you @Legioth, I'll have a look at that!

Strange enough this is what I see (as guest) on the TC build log:

```
[main] ERROR com.vaadin.flow.router.InternalServerError - There was an exception while trying to navigate to 'fail/params'
java.lang.IllegalArgumentException: Given route parameter 'class java.lang.Long' is of the wrong type. Required 'class java.lang.String'.
	at com.vaadin.flow.router.BeforeEvent.checkUrlParameterType(BeforeEvent.java:241)
	at com.vaadin.flow.router.BeforeEvent.rerouteTo(BeforeEvent.java:218)
	at com.vaadin.flow.router.RouterTest$FailRerouteWithParams.beforeEnter(RouterTest.java:477)
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.executeBeforeEnterNavigation(AbstractNavigationStateRenderer.java:328)
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.handle(AbstractNavigationStateRenderer.java:194)
	at com.vaadin.flow.router.Router.handleNavigation(Router.java:201)
	at com.vaadin.flow.router.Router.navigate(Router.java:172)
	at com.vaadin.flow.router.RouterTest.reroute_fails_with_faulty_url_parameters(RouterTest.java:1490)
```

**Comment by Legioth** [comment]
`There was an exception while trying to navigate to 'fail/params'` comes from a test that is supposed to throw an exception, so that one is fine.

The trick is that when the the build log terminates after a bunch of JavaDoc warnings, then there's also at least one JavaDoc error earlier during the same run. Those errors can be found by searching for "error:" in the log.

**Comment by pleku** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-server/src/main/java/com/vaadin/flow/component/Key.java, line 279 at r4](https://reviewable.io/reviews/vaadin/flow/4061#-LCSq_Hz4-3_w38T_Wnq:-LCSq_Hz4-3_w38T_Wnr:b-xri815) ([raw file](https://github.com/vaadin/flow/blob/9156ebdbf94b1e425e51c21b3ffe9b1a725e2805/flow-server/src/main/java/com/vaadin/flow/component/Key.java#L279)):*
> ```Java
>      * called an "escape sequence."
>      */
>     Key ESCAPE = Key.of("Escape");
> ```

This doesn't work in MS Edge, please use the key code instead (I think it is 27)
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/5290772/#comment-3

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4061)*

**Comment by pleku** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/component/Key.java, line 210 at r4](https://reviewable.io/reviews/vaadin/flow/4061#-LCSrBspCUn-nfG28BJY:-LCSrBspCUn-nfG28BJZ:b-ivl378) ([raw file](https://github.com/vaadin/flow/blob/9156ebdbf94b1e425e51c21b3ffe9b1a725e2805/flow-server/src/main/java/com/vaadin/flow/component/Key.java#L210)):*
> ```Java
>      * The Delete key, <code>Del</code>.
>      */
>     Key DELETE = Key.of("Delete");
> ```

Are you sure this works on MS Edge ? Reported here that it uses `Del` instead https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/5290772/#comment-2
Should change to the key code instead ?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4061)*

**Comment by heruan** [comment]
@pleku What do you mean "change to the key code"? Just for `DELETE`? This PR is all about *not* using key codes, which bring other compatibility issues (with e.g. Asian keyboards).

Seems like Edge does report the wrong value and it's being tackled by the Edge team as a bug. Maybe we should just note this on the JavaDoc of the `DELETE` constant, linking at the bug report?

**Comment by pleku** [comment]
@heruan Edge reports `Del` instead of `Delete` (and `Esc` instead of `Escape` (?)) and it is a bug in Edge, true. Thus the API we have won't work on Edge. But if you use the key code http://keycode.info/ it works on both systems. And that key code is consistent for "functional" and number keys  and even with other keyboards.

>This PR is all about not using key codes
Sorry, I didn't look through the whole PR, so I didn't realise that (we run into this issue elsewhere and I recalled seeing a PR related to it). 

I'm not sure how I want to workaround this issue in this PR, maybe a comment yes... but basically people should be using a key code in stead of the key for cross browser supported `Escape` and `Delete`.  We should maybe add eg. specific `EscPressedEvent` and `DeletePressedEvent` that use the key code instead of key. And also `EnterPressedEvent` could mayhaps be great.

---

Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4061#-:-LCTFfRR2Zo4Yu-YLNCN:b8jl16n)*

**Comment by Legioth** [comment]
I agree with @heruan  that it's in general better to use `key` values instead of `keyCode`. Two solutions to consider include:
1) Make `Key` slightly more abstract so that it can either define a `key` or a `keyCode`.
2) Make `Key` support multiple codes, so that e.g. both `Del` and `Delete` could be considered for `Key.DELETE`.

---

Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4061#-:-LCY3DiEApO_wk3D2yte:b-yfxmtj)*

**Comment by heruan** [comment]
I committed solution 2, to stay consistent with the initial attempt to let the user specify the *semantic* of the key rather than its physical position on the keyboard.

Another matter is whether or not implement an API to specify also the [`code`](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code), which correspond to a physical location of the key, e.g.

- pressing <kbd>Q</kbd> in a US keyboard: `event.key = 'q'` and `event.code = 'KeyQ'`;
- pressing <kbd>A</kbd> in a French keyboard: `event.key = 'a'` but still `event.code = 'KeyQ'`.

Be aware that the value reported by http://keycode.info (i.e. `keyCode`) is [deprecated](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode).

**Comment by pekam** [comment]
Reviewed 2 of 5 files at r1, 1 of 1 files at r5, 1 of 2 files at r6, 1 of 1 files at r7.
Review status: 4 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/component/Key.java, line 368 at r7](https://reviewable.io/reviews/vaadin/flow/4061#-LDB4G3c0fMn16cd-WMt:-LDB4G3c0fMn16cd-WMu:by8otmn) ([raw file](https://github.com/vaadin/flow/blob/808d698709bd979a3a30488700d7babcc9da3eca/flow-server/src/main/java/com/vaadin/flow/component/Key.java#L368)):*
> ```Java
>      * The <code>Power</code> button or key, to toggle power on and off.
>      * <p>
>      * Note: Not all systems pass this key through to to the user agent.
> ```

Duplicate "to"

---

*[flow-server/src/main/java/com/vaadin/flow/component/Key.java, line 832 at r7](https://reviewable.io/reviews/vaadin/flow/4061#-LDB9cV_0swto91Lziee:-LDB9cVa2_PrZmDYxzf9:bcg7x5m) ([raw file](https://github.com/vaadin/flow/blob/808d698709bd979a3a30488700d7babcc9da3eca/flow-server/src/main/java/com/vaadin/flow/component/Key.java#L832)):*
> ```Java
> 
>     /**
>      * Adjusts audio balance twoard the right.
> ```

Typo "twoard"

---

*[flow-server/src/main/java/com/vaadin/flow/component/Key.java, line 1096 at r7](https://reviewable.io/reviews/vaadin/flow/4061#-LDBC1uLA0lD73g2QnkN:-LDBC1uLA0lD73g2QnkO:b53hk26) ([raw file](https://github.com/vaadin/flow/blob/808d698709bd979a3a30488700d7babcc9da3eca/flow-server/src/main/java/com/vaadin/flow/component/Key.java#L1096)):*
> ```Java
> 
>     /**
>      * General-purpose media funciton key, color-coded green; this has index 1
> ```

typo: "funciton"
same for the 4 below

---

*[flow-server/src/main/java/com/vaadin/flow/component/Key.java, line 1147 at r7](https://reviewable.io/reviews/vaadin/flow/4061#-LDBCOao1BSIoM8O3Hpo:-LDBCOao1BSIoM8O3Hpp:bqwd76f) ([raw file](https://github.com/vaadin/flow/blob/808d698709bd979a3a30488700d7babcc9da3eca/flow-server/src/main/java/com/vaadin/flow/component/Key.java#L1147)):*
> ```Java
> 
>     /**
>      * The Exit button, which exits the curreent application or menu.
> ```

typo: "curreent"

---

*[flow-server/src/main/java/com/vaadin/flow/component/Key.java, line 1354 at r7](https://reviewable.io/reviews/vaadin/flow/4061#-LDBETjD75vVdwCObEnA:-LDBETjD75vVdwCObEnB:b2sknue) ([raw file](https://github.com/vaadin/flow/blob/808d698709bd979a3a30488700d7babcc9da3eca/flow-server/src/main/java/com/vaadin/flow/component/Key.java#L1354)):*
> ```Java
>      * A button to move the picture-in-picture view downward.
>      */
>     Key PIP_DOWN = Key.of("PinPDown");
> ```

There's "PIP" and "PinP" with an 'n'
Is this intentional or a typo?
Same for the three below.

---

*[flow-server/src/main/java/com/vaadin/flow/component/Key.java, line 1717 at r7](https://reviewable.io/reviews/vaadin/flow/4061#-LDBTiEZ5e3Kdebb4Pmx:-LDBTiEZ5e3Kdebb4Pmy:b-9w7w01) ([raw file](https://github.com/vaadin/flow/blob/808d698709bd979a3a30488700d7babcc9da3eca/flow-server/src/main/java/com/vaadin/flow/component/Key.java#L1717)):*
> ```Java
>     /**
>      * The decimal point key (typically <code>.</code> or <code>,</code>
>      * depending on the region. In newer browsers, this value to simply be the
> ```

Missing ")"
Missing verb in the next sentence

---

*[flow-server/src/main/java/com/vaadin/flow/component/Key.java, line 1765 at r7](https://reviewable.io/reviews/vaadin/flow/4061#-LDBczM-8dePwgR9ipxT:-LDBczM-8dePwgR9ipxU:bj3z30c) ([raw file](https://github.com/vaadin/flow/blob/808d698709bd979a3a30488700d7babcc9da3eca/flow-server/src/main/java/com/vaadin/flow/component/Key.java#L1765)):*
> ```Java
>      * @return the {@link Key} instance
>      */
>     static Key of(String... keys) {
> ```

Now it allows to pass zero arguments and also seems a bit more confusing than before.

Maybe it could be something like:
`static Key of(String key, String... duplicateKeys)`

and explain in the javadocs that the `duplicateKeys` (or whatever would be a good name for this varargs) should be used only in rare cases where multiple codes map to the same key.

---

*[flow-server/src/main/java/com/vaadin/flow/component/KeyNotifier.java, line 95 at r7](https://reviewable.io/reviews/vaadin/flow/4061#-LDBVZiP0n3D9QvIC72d:-LDBVZiP0n3D9QvIC72e:bhe54z) ([raw file](https://github.com/vaadin/flow/blob/808d698709bd979a3a30488700d7babcc9da3eca/flow-server/src/main/java/com/vaadin/flow/component/KeyNotifier.java#L95)):*
> ```Java
>     /**
>      * Adds a {@code keydown} listener to this component, which will trigger
>      * only if the keys involved in the event matche the {@code key} and
> ```

typo: "matche" (same for the two methods below)

---

*[flow-server/src/main/java/com/vaadin/flow/component/KeyNotifier.java, line 98 at r7](https://reviewable.io/reviews/vaadin/flow/4061#-LDBhaZ24nAmDpwCl5Ym:-LDBhaZ24nAmDpwCl5Yn:bafkexc) ([raw file](https://github.com/vaadin/flow/blob/808d698709bd979a3a30488700d7babcc9da3eca/flow-server/src/main/java/com/vaadin/flow/component/KeyNotifier.java#L98)):*
> ```
> Key#of(String)
> ```
I guess this link doesn't work after changing the parameters to varargs. (same for the two methods below)

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4061)*

**Comment by heruan** [comment]
I apologize for the many typos, descriptions come from MDN and I trusted them too much :sweat_smile: 

---

Review status: 3 of 5 files reviewed at latest revision, 12 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/component/Key.java, line 368 at r7](https://reviewable.io/reviews/vaadin/flow/4061#-LDB4G3c0fMn16cd-WMt:-LDC0Y8QCTxu4z6gIBUK:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/808d698709bd979a3a30488700d7babcc9da3eca/flow-server/src/main/java/com/vaadin/flow/component/Key.java#L368)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

Duplicate "to"
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/flow/component/Key.java, line 832 at r7](https://reviewable.io/reviews/vaadin/flow/4061#-LDB9cV_0swto91Lziee:-LDC0XYh9n9bKgYFUK4A:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/808d698709bd979a3a30488700d7babcc9da3eca/flow-server/src/main/java/com/vaadin/flow/component/Key.java#L832)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

Typo "twoard"
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/flow/component/Key.java, line 1096 at r7](https://reviewable.io/reviews/vaadin/flow/4061#-LDBC1uLA0lD73g2QnkN:-LDC0YiY7n-FVXMeAfxN:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/808d698709bd979a3a30488700d7babcc9da3eca/flow-server/src/main/java/com/vaadin/flow/component/Key.java#L1096)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

typo: "funciton"
same for the 4 below
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/flow/component/Key.java, line 1147 at r7](https://reviewable.io/reviews/vaadin/flow/4061#-LDBCOao1BSIoM8O3Hpo:-LDC0Z55Ebpk8v7J489b:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/808d698709bd979a3a30488700d7babcc9da3eca/flow-server/src/main/java/com/vaadin/flow/component/Key.java#L1147)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

typo: "curreent"
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/flow/component/Key.java, line 1354 at r7](https://reviewable.io/reviews/vaadin/flow/4061#-LDBETjD75vVdwCObEnA:-LDC0ZdY0dpkbJ4qz7JG:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/808d698709bd979a3a30488700d7babcc9da3eca/flow-server/src/main/java/com/vaadin/flow/component/Key.java#L1354)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

There's "PIP" and "PinP" with an 'n'
Is this intentional or a typo?
Same for the three below.
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/flow/component/Key.java, line 1717 at r7](https://reviewable.io/reviews/vaadin/flow/4061#-LDBTiEZ5e3Kdebb4Pmx:-LDC16CS4AW_O-EX9esV:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/808d698709bd979a3a30488700d7babcc9da3eca/flow-server/src/main/java/com/vaadin/flow/component/Key.java#L1717)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

Missing ")"
Missing verb in the next sentence
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/flow/component/Key.java, line 1765 at r7](https://reviewable.io/reviews/vaadin/flow/4061#-LDBczM-8dePwgR9ipxT:-LDC15VW2speC3Irls3A:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/808d698709bd979a3a30488700d7babcc9da3eca/flow-server/src/main/java/com/vaadin/flow/component/Key.java#L1765)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

Now it allows to pass zero arguments and also seems a bit more confusing than before.

Maybe it could be something like:
`static Key of(String key, String... duplicateKeys)`

and explain in the javadocs that the `duplicateKeys` (or whatever would be a good name for this varargs) should be used only in rare cases where multiple codes map to the same key.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4061#-:-LDC1ChNCYe0VxAbd1_1:b-p2bivn)*

**Comment by pekam** [comment]
> I apologize for the many typos, descriptions come from MDN and I trusted them too much 😅

Oh, right. Well now we have better docs than MDN. :D

---

Reviewed 2 of 2 files at r8.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4061#-:-LDC5XmIC2j0j7G3MYhD:b-7piebw)*

**Comment by pekam** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow/4061#-LDCBtoG40V6l23lN8XT:-LDCBtoG40V6l23lN8XU:bdvds72) (no related file):*
One more thing: Now that `Key` can have additional values, we should have a test verifying that if you add a listener for a key with multiple values, the listener gets called for each of those key events.

Just say if you are busy or otherwise need help with this since we'd like to get this in before releasing the RC tomorrow. :)

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4061)*

**Comment by heruan** [comment]
Review status: 4 of 6 files reviewed at latest revision, 5 unresolved discussions.

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow/4061#-LDCBtoG40V6l23lN8XT:-LDCKCss1KrBLYrTChR6:b-xqxuwu) (no related file):*
Sure! The test indeed failed, but now should be okay :nerd_face: 

> we'd like to get this in before releasing the RC tomorrow
>> get this in before releasing the RC tomorrow
>>> before releasing the RC tomorrow
>>>> **RC tomorrow**

:heart_eyes: 

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4061)*

**Comment by pekam** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r10.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[flow-server/src/main/java/com/vaadin/flow/component/KeyNotifier.java, line 95 at r7](https://reviewable.io/reviews/vaadin/flow/4061#-LDBVZiP0n3D9QvIC72d:-LDCTOw28H0GblyDU_JA:bqxp1nk) ([raw file](https://github.com/vaadin/flow/blob/808d698709bd979a3a30488700d7babcc9da3eca/flow-server/src/main/java/com/vaadin/flow/component/KeyNotifier.java#L95)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

typo: "matche" (same for the two methods below)
</blockquote></details>

I fixed it myself, hope you don't mind.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4061#-:-LDCTYJw0Kh0J8T9ofNi:bnfp4nl)*

**Comment by pekam** [comment]
> > RC tomorrow
>
>😍

Sorry @heruan, we'll be releasing another beta after all.

Anyway, thanks again for the contribution and quick responses! :)

**Pull request merged**
