### PR TITLE
Implement server side visibility/conceal feature

### PR DESCRIPTION
**Pull request by denis-anisimov**
Fix for #3136

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3191)

### CODE REVIEW

**Comment by caalador** [comment]
Reviewed 15 of 17 files at r1.
Review status: 15 of 17 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[flow-server/src/main/java/com/vaadin/flow/dom/impl/BasicElementStateProvider.java, line 385 at r1](https://reviewable.io:443/reviews/vaadin/flow/3191#-L0nqHj_XDMYAA7dSlEZ:-L0nqHj_XDMYAA7dSlE_:bl4w0ck) ([raw file](https://github.com/vaadin/flow/blob/7cf8d4a45680aaee46517a658f383d23febfd621/flow-server/src/main/java/com/vaadin/flow/dom/impl/BasicElementStateProvider.java#L385)):*
> ```Java
>     public void setVisi̋ble(StateNode node, boolean visible) {
>         assert node.hasFeature(ConcealData.class);
>         node.getFeature(ConcealData.class).setConcealed(!visible);
> ```

This part would seem like the Concealed name should be changed so that we don't set `!visible` but keep the same that is given
as now isVisible is not concealed.

---

*[flow-server/src/main/java/com/vaadin/flow/server/communication/ServerRpcHandler.java, line 29 at r1](https://reviewable.io:443/reviews/vaadin/flow/3191#-L0nrGSG7tbcL_IQPQYN:-L0nrGSG7tbcL_IQPQYO:b-le185l) ([raw file](https://github.com/vaadin/flow/blob/7cf8d4a45680aaee46517a658f383d23febfd621/flow-server/src/main/java/com/vaadin/flow/server/communication/ServerRpcHandler.java#L29)):*
> ```Java
> import java.util.Map;
> import java.util.function.Function;
> import java.util.stream.Collectors;
> ```

No other changes except formatting changes?

---

*[flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/AbstractRpcInvocationHandler.java, line 55 at r1](https://reviewable.io:443/reviews/vaadin/flow/3191#-L0nrQCWfQB-qPsRaZex:-L0nrQCWfQB-qPsRaZey:b-32ewvg) ([raw file](https://github.com/vaadin/flow/blob/7cf8d4a45680aaee46517a658f383d23febfd621/flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/AbstractRpcInvocationHandler.java#L55)):*
> ```Java
>         boolean invokeRpc = true;
>         if (node.hasFeature(ConcealData.class)) {
>             invokeRpc = !node.getFeature(ConcealData.class).isConcealed();
> ```

Here again is the not if true that wouldn't be needed if we had visible instead of concealed.

---

*[flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/ConcealDataTest.java, line 33 at r1](https://reviewable.io:443/reviews/vaadin/flow/3191#-L0nsGmX811cLQc9Dd9z:-L0nsGmYfKyjY7_J7qJu:byldvwr) ([raw file](https://github.com/vaadin/flow/blob/7cf8d4a45680aaee46517a658f383d23febfd621/flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/ConcealDataTest.java#L33)):*
> ```Java
> 
>         data.setValue(true);
>         Assert.assertTrue(data.getValue());
> ```

Should the data be gotten again from the node as now it seems that we are just testing the getter and setter.
Also the `isConcealed()` should be checked I guess.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3191)*

**Comment by denis-anisimov** [comment]
Review status: 15 of 17 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[flow-server/src/main/java/com/vaadin/flow/dom/impl/BasicElementStateProvider.java, line 385 at r1](https://reviewable.io:443/reviews/vaadin/flow/3191#-L0nqHj_XDMYAA7dSlEZ:-L0oY1UXOMhGUtnXDe5A:b-as6qk7) ([raw file](https://github.com/vaadin/flow/blob/7cf8d4a45680aaee46517a658f383d23febfd621/flow-server/src/main/java/com/vaadin/flow/dom/impl/BasicElementStateProvider.java#L385)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

This part would seem like the Concealed name should be changed so that we don't set `!visible` but keep the same that is given
as now isVisible is not concealed.
</blockquote></details>

`Conceale` has been chosen by me when I started to implement the feature. There were no decision about the name.
Now I can rename the feature and all methods to `visible` .

---

*[flow-server/src/main/java/com/vaadin/flow/server/communication/ServerRpcHandler.java, line 29 at r1](https://reviewable.io:443/reviews/vaadin/flow/3191#-L0nrGSG7tbcL_IQPQYN:-L0oYYSiPSm27xXSdci7:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/7cf8d4a45680aaee46517a658f383d23febfd621/flow-server/src/main/java/com/vaadin/flow/server/communication/ServerRpcHandler.java#L29)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

No other changes except formatting changes?
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/AbstractRpcInvocationHandler.java, line 55 at r1](https://reviewable.io:443/reviews/vaadin/flow/3191#-L0nrQCWfQB-qPsRaZex:-L0o_K40-xDdZJYVIZJh:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/7cf8d4a45680aaee46517a658f383d23febfd621/flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/AbstractRpcInvocationHandler.java#L55)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Here again is the not if true that wouldn't be needed if we had visible instead of concealed.
</blockquote></details>

Done.

---

*[flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/ConcealDataTest.java, line 33 at r1](https://reviewable.io:443/reviews/vaadin/flow/3191#-L0nsGmX811cLQc9Dd9z:-L0oYgxJtvj2EuEdZCvI:by3u1j3) ([raw file](https://github.com/vaadin/flow/blob/7cf8d4a45680aaee46517a658f383d23febfd621/flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/ConcealDataTest.java#L33)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Should the data be gotten again from the node as now it seems that we are just testing the getter and setter.
Also the `isConcealed()` should be checked I guess.
</blockquote></details>

Of course.
My stupid mistake.
Thanks for catching.

I don't see a reason to get data again.
The test is kind of testing getter and setter but just to make sure that the absence of value is treated correctly.
And that's failed. You are right.

`isVisible` should be tested instead of getter.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3191)*

**Comment by denis-anisimov** [comment]
Review status: 7 of 16 files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/dom/impl/BasicElementStateProvider.java, line 385 at r1](https://reviewable.io:443/reviews/vaadin/flow/3191#-L0nqHj_XDMYAA7dSlEZ:-L0oaYB1D9tXoXcTD3XH:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/7cf8d4a45680aaee46517a658f383d23febfd621/flow-server/src/main/java/com/vaadin/flow/dom/impl/BasicElementStateProvider.java#L385)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

`Conceale` has been chosen by me when I started to implement the feature. There were no decision about the name.
Now I can rename the feature and all methods to `visible` .
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3191)*

**Comment by caalador** [comment]
Reviewed 12 of 12 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3191)*

**Comment by caalador** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[flow-server/src/main/java/com/vaadin/flow/component/Component.java, line 490 at r2](https://reviewable.io:443/reviews/vaadin/flow/3191#-L0raYyaq9_J0Xm9HBX1:-L0raYyaq9_J0Xm9HBX2:b-cayb5m) ([raw file](https://github.com/vaadin/flow/blob/9d429c96607ba6ad0b815377175fe28642a468c4/flow-server/src/main/java/com/vaadin/flow/component/Component.java#L490)):*
> ```Java
>      *
>      * @param visible
>      *            the component visibility value
> ```

The method has no parameters. JavaDoc creation fails.

---

*[flow-server/src/main/java/com/vaadin/flow/dom/Element.java, line 1416 at r2](https://reviewable.io:443/reviews/vaadin/flow/3191#-L0raP5u9atdXESnzkrT:-L0raP5u9atdXESnzkrU:b7zk9jq) ([raw file](https://github.com/vaadin/flow/blob/9d429c96607ba6ad0b815377175fe28642a468c4/flow-server/src/main/java/com/vaadin/flow/dom/Element.java#L1416)):*
>   * @param visible
>      *            the element visibility valu
The method has no parameters. JavaDoc creation fails.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3191)*

**Comment by denis-anisimov** [comment]
Review status: 14 of 16 files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/component/Component.java, line 490 at r2](https://reviewable.io:443/reviews/vaadin/flow/3191#-L0raYyaq9_J0Xm9HBX1:-L0rbzugr8-_8RlDatAM:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/9d429c96607ba6ad0b815377175fe28642a468c4/flow-server/src/main/java/com/vaadin/flow/component/Component.java#L490)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

The method has no parameters. JavaDoc creation fails.
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/flow/dom/Element.java, line 1416 at r2](https://reviewable.io:443/reviews/vaadin/flow/3191#-L0raP5u9atdXESnzkrT:-L0rc0EbKUxO3HRSgn6F:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/9d429c96607ba6ad0b815377175fe28642a468c4/flow-server/src/main/java/com/vaadin/flow/dom/Element.java#L1416)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

>   * @param visible
>      *            the element visibility valu
The method has no parameters. JavaDoc creation fails.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3191)*

**Comment by caalador** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3191)*

**Comment by caalador** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3191)*

**Comment by caalador** [comment]
Reviewed 3 of 3 files at r5, 7 of 7 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3191)*

**Pull request merged**
