### PR TITLE
Comparable listeners

### PR DESCRIPTION
**Pull request by berndhopp**
this PR introduces a @ListenerPriority-annotation, which gives users more control over the order of execution for AfterNavigationListener, BeforeEnterListener and BeforeLeaveListener.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3975)

### CODE REVIEW

**Comment by Legioth** [comment]
*[flow-server/src/main/java/com/vaadin/flow/router/Listener.java, line 18 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3975#-LAnQ3aE2EYQxNW9qjO2:-LAnQ3aE2EYQxNW9qjO3:b-xiby9u) ([raw file](https://github.com/vaadin/flow/blob/9e2fa615826e74e8cf1313916ba432bcb551df29/flow-server/src/main/java/com/vaadin/flow/router/Listener.java#L18)):*
> ```Java
>     @Override
>     default int compareTo(T t) {
>         return 0;
> ```

This approach cannot live up to the requirements documented for the the `compareTo` method: `sgn(x.compareTo(y)) == -sgn(y.compareTo(x))` unless all listener implementations are implemented to be aware of each other.

For a solution that actually works, I'd recommend something similar to `AnnotationAwareOrderComparator` in Spring.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3975)*

**Comment by berndhopp** [comment]
*[flow-server/src/main/java/com/vaadin/flow/router/Listener.java, line 18 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3975#-LAnQ3aE2EYQxNW9qjO2:-LAoPKyx8uC07skdFe9M:bmcocf0) ([raw file](https://github.com/vaadin/flow/blob/9e2fa615826e74e8cf1313916ba432bcb551df29/flow-server/src/main/java/com/vaadin/flow/router/Listener.java#L18)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

This approach cannot live up to the requirements documented for the the `compareTo` method: `sgn(x.compareTo(y)) == -sgn(y.compareTo(x))` unless all listener implementations are implemented to be aware of each other.

For a solution that actually works, I'd recommend something similar to `AnnotationAwareOrderComparator` in Spring.
</blockquote></details>

see latest commit, please

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3975)*

**Comment by caalador** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java, line 19 at r2](https://reviewable.io/reviews/vaadin/flow/3975#-LAq2SEi1sSjL2RGkqnD:-LAq2SEi1sSjL2RGkqnE:b-imwbrk) ([raw file](https://github.com/vaadin/flow/blob/dba1c3da72b16b6e46530defcf07e6adab5cc2fa/flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java#L19)):*
> ```Java
> 
> import java.io.Serializable;
> import java.util.*;
> ```

No * imports.

---

*[flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java, line 23 at r2](https://reviewable.io/reviews/vaadin/flow/3975#-LAq1tlQ5_M0Wc4eqw8I:-LAq1tlQ5_M0Wc4eqw8J:b-imwbrk) ([raw file](https://github.com/vaadin/flow/blob/dba1c3da72b16b6e46530defcf07e6adab5cc2fa/flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java#L23)):*
> ```Java
> import java.util.regex.Pattern;
> 
> import com.vaadin.flow.router.*;
> ```

No * imports.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/3975)*

**Comment by berndhopp** [comment]
Reviewed 1 of 24 files at r2.
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/3975)*

**Comment by berndhopp** [comment]
Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/3975)*

**Comment by caalador** [comment]
You shouldn't review your own PRs

**Comment by berndhopp** [comment]
I'm still new to this reviewable thing, I just wanted to see my latest changes.

---

Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/3975#-:-LAqg3gh6VUkktohgNkY:b-dys951)*

**Comment by caalador** [comment]
Build fails with: 
```

[08:19:28][Step 5/6] [ERROR] /opt/agent/work/655b228800368b4e/flow-server/src/main/java/com/vaadin/flow/router/ListenerPriority.java:35: error: unknown tag: ListenerPriority
[08:19:28][Step 5/6] [ERROR] *      @ListenerPriority(5)
[08:19:28][Step 5/6] [ERROR] ^
[08:19:28][Step 5/6] [ERROR] /opt/agent/work/655b228800368b4e/flow-server/src/main/java/com/vaadin/flow/router/ListenerPriority.java:44: error: unknown tag: ListenerPriority
[08:19:28][Step 5/6] [ERROR] *      @ListenerPriority(-5)
[08:19:28][Step 5/6] [ERROR] ^
```

**Comment by caalador** [comment]
```

[11:58:13][Step 5/6] /opt/agent/work/655b228800368b4e/flow-server/src/main/java/com/vaadin/flow/router/ListenerPriority.java:47: error: unexpected end tag: </p>
[11:58:13][Step 5/6]  * </p>
```

**Comment by caalador** [comment]
Reviewed 4 of 5 files at r3.
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow/3975#-LArY-Cq5i53v4Fe9roq:-LArY-Cq5i53v4Fe9ror:b-ge17gn) (no related file):*
A test of the execution ordering should be present.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/3975)*

**Comment by berndhopp** [comment]
*[a discussion](https://reviewable.io/reviews/vaadin/flow/3975#-LArY-Cq5i53v4Fe9roq:-LArwvQc6SQ4YYMj-CsJ:bb7f2mf) (no related file):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

A test of the execution ordering should be present.
</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/3975)*

**Comment by caalador** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/3975#-:-LAwLRUcC-cSiYVILpoz:bnfp4nl)*

**Pull request merged**
