### PR TITLE
Make two way data binding work with beans in list

### LINKED ISSUE #4091: Template model List<> items are not updated on server side when changed on client side.
I have a simple TemplateModel with a getter and setter for a List of items. These items are displayed with a polymer dom-repeat and can be edited by vaadin-text-fields. Expectation here is, that changed made on client side are transported back to server side to be handled in an event handler. 

Currently the items are unchanged. This reflects also back to direct calls of items in the handling method by `@EventData("event.model.item")` (or `@ModelItem` in short).

**Java**
```
public class TodoListDetailView extends PolymerTemplate<TodoListDetailView.Model> implements HasComponents, HasUrlParameter<Long> {
    @EventHandler
    private void handle() {
        // update repository
        System.out.println(getModel().getTodos());
    }

    public interface Model extends TemplateModel {
        @Encode(value = LongToStringEncoder.class, path = "id")
        @Encode(value = LongToStringEncoder.class, path = "list.id")
        void setTodos(List<Todo> list);

        List<Todo> getTodos();
    }
}
```

**Polymer**
```
<template>
        <template is="dom-repeat" items="{{todos}}">
            <vaadin-text-field on-change="handle" class="todo-name" value="{{item.name}}"></vaadin-text-field>
        </template>
</template>
```

Also see: https://github.com/vaadin/flow/issues/4086

### PR DESCRIPTION
**Pull request by denis-anisimov**
Fixes #4091

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/4160)

### CODE REVIEW

**Comment by caalador** [comment]
Seems fine, but I'd like another pair of eyes on this due to the property modifier override.

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java, line 363 at r1](https://reviewable.io/reviews/vaadin/flow/4160#-LDGC-ui9Qn0sfvZjA47:-LDGC-uj7IBcMHnatdjx:b-imm9fs) ([raw file](https://github.com/vaadin/flow/blob/bf9def4ea437124b76b6611afbbebc29d0a325c8/flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java#L363)):*
> ```Java
>     }-*/;
> 
>     private static void handleProeprtyChange(double nodeId, Element host,
> ```

typo: `handlePropertyChange(` not `..Proeprty`

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4160#-:-LDGWms46CbQ4po6J2Zy:b-g8nkzf)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java, line 363 at r1](https://reviewable.io/reviews/vaadin/flow/4160#-LDGC-ui9Qn0sfvZjA47:-LDGcSE47YuiAPLWJ-WC:b-sh0zzy) ([raw file](https://github.com/vaadin/flow/blob/bf9def4ea437124b76b6611afbbebc29d0a325c8/flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java#L363)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

typo: `handlePropertyChange(` not `..Proeprty`
</blockquote></details>

Thanks.
Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4160)*

**Comment by caalador** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4160)*

**Comment by gilberto-torrezan** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java, line 304 at r2](https://reviewable.io/reviews/vaadin/flow/4160#-LD_ipo47a2LPtDf0mno:-LD_ipo47a2LPtDf0mnp:bpi5rac) ([raw file](https://github.com/vaadin/flow/blob/60e1b5edcc08f8fdc37fac1e2c83be6dda0da272/flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java#L304)):*
> ```Java
>             originalReady.apply(this, arguments);
>             @com.vaadin.client.PolymerUtils::fireReadyEvent(*)(element);
>     
> ```

I'd like to see a comment in the code explaining why do we need this JSNI and what does the template and dataHost have to do with it.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4160)*

**Comment by denis-anisimov** [comment]
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java, line 304 at r2](https://reviewable.io/reviews/vaadin/flow/4160#-LD_ipo47a2LPtDf0mno:-LDaN_tX64-N9dc43Uac:b-k4pu8t) ([raw file](https://github.com/vaadin/flow/blob/60e1b5edcc08f8fdc37fac1e2c83be6dda0da272/flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java#L304)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

I'd like to see a comment in the code explaining why do we need this JSNI and what does the template and dataHost have to do with it.
</blockquote></details>

Done.

I may not make the exact explanation since I'm not sure about some of those thing (like `__dataHost`). It's just a result of debugging Polymer code.
And this is more a guess than a specification.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4160)*

**Comment by gilberto-torrezan** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java, line 314 at r3](https://reviewable.io/reviews/vaadin/flow/4160#-LDaQbpN15PJqZUTj2w_:-LDaQbpN15PJqZUTj2wa:b-r5b09o) ([raw file](https://github.com/vaadin/flow/blob/95a8385ae1ee1bee45492e10d630668f91a1f8c8/flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java#L314)):*
> ```
> dom-repeat may be already in the DOM but may be not yet.
> ```

This sentence looks incomplete.

---

*[flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java, line 342 at r3](https://reviewable.io/reviews/vaadin/flow/4160#-LDaRNLS3UNxvrIwvNEJ:-LDaRNLS3UNxvrIwvNEK:bnsvq44) ([raw file](https://github.com/vaadin/flow/blob/95a8385ae1ee1bee45492e10d630668f91a1f8c8/flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java#L342)):*
> ```Java
>                                     // this is the index of the changed item
>                                     var arrayIndex = prop.substr(0,index);
>                                     // this is the property name of the cahnged item
> ```

Typo on `cahnged`

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4160)*

**Comment by gilberto-torrezan** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4160)*

**Comment by denis-anisimov** [comment]
Review status: 6 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java, line 314 at r3](https://reviewable.io/reviews/vaadin/flow/4160#-LDaQbpN15PJqZUTj2w_:-LDaWnXiCpM2TXlHaAmw:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/95a8385ae1ee1bee45492e10d630668f91a1f8c8/flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java#L314)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

> ```
> dom-repeat may be already in the DOM but may be not yet.
> ```

This sentence looks incomplete.
</blockquote></details>

Done.

---

*[flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java, line 342 at r3](https://reviewable.io/reviews/vaadin/flow/4160#-LDaRNLS3UNxvrIwvNEJ:-LDaVMdmC8ct9rzkfmUf:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/95a8385ae1ee1bee45492e10d630668f91a1f8c8/flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java#L342)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Typo on `cahnged`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4160)*

**Comment by gilberto-torrezan** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4160#-:-LDaqNtDAypu8Kr8fAQC:bnfp4nl)*

**Comment by gilberto-torrezan** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4160#-:-LDbANDq-NrAzXbFZXzI:bnfp4nl)*

**Pull request merged**
