### PR TITLE
@Inline annotation for Bootstrap page

### PR DESCRIPTION
**Pull request by caalador**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3135)

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
Reviewed 8 of 8 files at r1, 2 of 3 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3135#-L092S4bGEXAjExnaYCk:-L092S4bGEXAjExnaYCl:bdkxreq) (no related file):*
Should we add an IT test?

---

*[flow-documentation/application-structure/tutorial-bootstrap.asciidoc, line 82 at r3](https://reviewable.io:443/reviews/vaadin/flow/3135#-L0917fNzEIvVZPX0R7t:-L0917fNzEIvVZPX0R7u:b-j39pwk) ([raw file](https://github.com/vaadin/flow/blob/ed13bc2bb9819a98a63b08214737168674907707/flow-documentation/application-structure/tutorial-bootstrap.asciidoc#L82)):*
> ```AsciiDoc
> 
> [NOTE]
> If the Inline annotations is not on a `@Route` Component or a `RouterLayout` used from a route it will not be used.
> ```

That sounds a bit weird and may be counter-intuitive to some people.
Should we allow to use it everywhere and remove `inline` field from other annotations?

---

*[flow-server/src/main/java/com/vaadin/server/BootstrapUtils.java, line 261 at r1](https://reviewable.io:443/reviews/vaadin/flow/3135#-L08r-g8P8rjtaUDWr3m:-L08r-g8P8rjtaUDWr3n:b-o6tbzq) ([raw file](https://github.com/vaadin/flow/blob/82cf28dff664a11f2a9d9f504c9131b7c2a363c8/flow-server/src/main/java/com/vaadin/server/BootstrapUtils.java#L261)):*
> ```Java
>         try (InputStream inlineResourceStream = getInlineResourceStream(request,
>                 url);
>                 BufferedReader bufferedReader = new BufferedReader(
> ```

I always thought that we need to close every reader we have created, haven't we?
If yes, we can move everything into `getInlineResourceStream`or `try` block.

---

*[flow-server/src/main/java/com/vaadin/ui/Inline.java, line 26 at r3](https://reviewable.io:443/reviews/vaadin/flow/3135#-L091gHziXUCTfNXUYSM:-L091gHziXUCTfNXUYSN:bfb688) ([raw file](https://github.com/vaadin/flow/blob/ed13bc2bb9819a98a63b08214737168674907707/flow-server/src/main/java/com/vaadin/ui/Inline.java#L26)):*
> ```Java
> 
> /**
>  * Defines files to inline into the initial page.
> ```

If we leave it working in routing only, we can mention it here explicitly.

---

*[flow-server/src/test/java/com/vaadin/server/BootstrapHandlerTest.java, line 663 at r3](https://reviewable.io:443/reviews/vaadin/flow/3135#-L0923WsGrGvQYse2NEO:-L0923WsGrGvQYse2NEP:b4dcr8v) ([raw file](https://github.com/vaadin/flow/blob/ed13bc2bb9819a98a63b08214737168674907707/flow-server/src/test/java/com/vaadin/server/BootstrapHandlerTest.java#L663)):*
> ```Java
> 
>         Elements allElements = page.head().getAllElements();
>         Assert.assertEquals(
> ```

We have a static import for all those methods already, no need to print `Assert.` everywhere.

---

*[flow-server/src/test/java/com/vaadin/server/BootstrapHandlerTest.java, line 677 at r3](https://reviewable.io:443/reviews/vaadin/flow/3135#-L092CmYPHepZQ2O8h73:-L092CmYPHepZQ2O8h74:bsierfj) ([raw file](https://github.com/vaadin/flow/blob/ed13bc2bb9819a98a63b08214737168674907707/flow-server/src/test/java/com/vaadin/server/BootstrapHandlerTest.java#L677)):*
> ```Java
>                 allElements.get(allElements.size() - 2).toString());
>         Assert.assertEquals(
>                 "File css should have been appended to head element",
> ```

One thing that concerns me a lot is this ton of hardcoded values in the tests: it's a pain to change them later.
But if you think it never happens in the future, leave it as is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3135)*

**Comment by caalador** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3135#-L092S4bGEXAjExnaYCk:-L092gKjtjzqmcwgpzxX:bjmt9w0) (no related file):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Should we add an IT test?
</blockquote></details>

I don't see what the IT test would test better than the JUnit tests that check the build of the bootstrap page.
But if you have a case then we could.

---

*[flow-documentation/application-structure/tutorial-bootstrap.asciidoc, line 82 at r3](https://reviewable.io:443/reviews/vaadin/flow/3135#-L0917fNzEIvVZPX0R7t:-L093V68tqYUHCe2OYH7:bc6bh03) ([raw file](https://github.com/vaadin/flow/blob/ed13bc2bb9819a98a63b08214737168674907707/flow-documentation/application-structure/tutorial-bootstrap.asciidoc#L82)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

That sounds a bit weird and may be counter-intuitive to some people.
Should we allow to use it everywhere and remove `inline` field from other annotations?
</blockquote></details>

Well this is specifically for the bootstrap page and it works with the same restrictions as @Viewport and PageConfigurator

---

*[flow-server/src/main/java/com/vaadin/server/BootstrapUtils.java, line 261 at r1](https://reviewable.io:443/reviews/vaadin/flow/3135#-L08r-g8P8rjtaUDWr3m:-L093GDrgL-Td5qLaIJG:bvimxbv) ([raw file](https://github.com/vaadin/flow/blob/82cf28dff664a11f2a9d9f504c9131b7c2a363c8/flow-server/src/main/java/com/vaadin/server/BootstrapUtils.java#L261)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

I always thought that we need to close every reader we have created, haven't we?
If yes, we can move everything into `getInlineResourceStream`or `try` block.
</blockquote></details>

This is a Java8 try that automatically closes the stream: https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html

---

*[flow-server/src/main/java/com/vaadin/ui/Inline.java, line 26 at r3](https://reviewable.io:443/reviews/vaadin/flow/3135#-L091gHziXUCTfNXUYSM:-L094XclIpkO5dSw2rlC:b40e7tn) ([raw file](https://github.com/vaadin/flow/blob/ed13bc2bb9819a98a63b08214737168674907707/flow-server/src/main/java/com/vaadin/ui/Inline.java#L26)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

If we leave it working in routing only, we can mention it here explicitly.
</blockquote></details>

Well it's not even for Routing as it's only for the Bootstrap page. I have no idea how to word it.

---

*[flow-server/src/test/java/com/vaadin/server/BootstrapHandlerTest.java, line 677 at r3](https://reviewable.io:443/reviews/vaadin/flow/3135#-L092CmYPHepZQ2O8h73:-L093mWqoMC3fHWrbY4G:b-lg1qt) ([raw file](https://github.com/vaadin/flow/blob/ed13bc2bb9819a98a63b08214737168674907707/flow-server/src/test/java/com/vaadin/server/BootstrapHandlerTest.java#L677)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

One thing that concerns me a lot is this ton of hardcoded values in the tests: it's a pain to change them later.
But if you think it never happens in the future, leave it as is.
</blockquote></details>

I don't see why someone would change the test files specifically added for these tests (@Viewport, @Inline and PageConfigurator), but if they do then they should also see that tests fail due to wrong contents on import.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3135)*

**Comment by SomeoneToIgnore** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[flow-documentation/application-structure/tutorial-bootstrap.asciidoc, line 82 at r3](https://reviewable.io:443/reviews/vaadin/flow/3135#-L0917fNzEIvVZPX0R7t:-L095-k8RTtkv_O9wQD9:brmeboq) ([raw file](https://github.com/vaadin/flow/blob/ed13bc2bb9819a98a63b08214737168674907707/flow-documentation/application-structure/tutorial-bootstrap.asciidoc#L82)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Well this is specifically for the bootstrap page and it works with the same restrictions as @Viewport and PageConfigurator
</blockquote></details>

So we have a bootstrap page concept open for users now? Any docs I can read about it?

---

*[flow-server/src/main/java/com/vaadin/server/BootstrapUtils.java, line 261 at r1](https://reviewable.io:443/reviews/vaadin/flow/3135#-L08r-g8P8rjtaUDWr3m:-L095FwKDTmpRuLCxA2n:bhk94st) ([raw file](https://github.com/vaadin/flow/blob/82cf28dff664a11f2a9d9f504c9131b7c2a363c8/flow-server/src/main/java/com/vaadin/server/BootstrapUtils.java#L261)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

This is a Java8 try that automatically closes the stream: https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html
</blockquote></details>

I am aware of try with resources feature, thanks.

But you are closing only the `InputStream`, not `BufferedReader` or `InputStreamReader` and those two implement `Closeable` too, so should we close them either?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3135)*

**Comment by SomeoneToIgnore** [comment]
*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3135#-L092S4bGEXAjExnaYCk:-L096-IFSumhZn4cKwrY:b-j6frt8) (no related file):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

I don't see what the IT test would test better than the JUnit tests that check the build of the bootstrap page.
But if you have a case then we could.
</blockquote></details>

We can at least check that these imports are inlined before other imports are loaded.
But up to you.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3135)*

**Comment by caalador** [comment]
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3135#-L092S4bGEXAjExnaYCk:-L098Ylmw_CVL2mTBSjk:b7gktmt) (no related file):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

We can at least check that these imports are inlined before other imports are loaded.
But up to you.
</blockquote></details>

Does it matter for anything except prepended which can only be done with the bootstrap methods?

---

*[flow-documentation/application-structure/tutorial-bootstrap.asciidoc, line 82 at r3](https://reviewable.io:443/reviews/vaadin/flow/3135#-L0917fNzEIvVZPX0R7t:-L097CRfXCA4iJ-XI-Cq:b-k1obdx) ([raw file](https://github.com/vaadin/flow/blob/ed13bc2bb9819a98a63b08214737168674907707/flow-documentation/application-structure/tutorial-bootstrap.asciidoc#L82)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

So we have a bootstrap page concept open for users now? Any docs I can read about it?
</blockquote></details>

flow-documentation/application-structure/tutorial-bootstrap.asciidoc

It's this documentation.

---

*[flow-server/src/main/java/com/vaadin/server/BootstrapUtils.java, line 261 at r1](https://reviewable.io:443/reviews/vaadin/flow/3135#-L08r-g8P8rjtaUDWr3m:-L097chrnyp3eajfIqLe:bmaxbbm) ([raw file](https://github.com/vaadin/flow/blob/82cf28dff664a11f2a9d9f504c9131b7c2a363c8/flow-server/src/main/java/com/vaadin/server/BootstrapUtils.java#L261)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

I am aware of try with resources feature, thanks.

But you are closing only the `InputStream`, not `BufferedReader` or `InputStreamReader` and those two implement `Closeable` too, so should we close them either?
</blockquote></details>

They are both in the try() so all are auto closed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3135)*

**Comment by SomeoneToIgnore** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[flow-documentation/application-structure/tutorial-bootstrap.asciidoc, line 82 at r3](https://reviewable.io:443/reviews/vaadin/flow/3135#-L0917fNzEIvVZPX0R7t:-L09AVETH8vjZlb3IxZd:b-ucfknh) ([raw file](https://github.com/vaadin/flow/blob/ed13bc2bb9819a98a63b08214737168674907707/flow-documentation/application-structure/tutorial-bootstrap.asciidoc#L82)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

flow-documentation/application-structure/tutorial-bootstrap.asciidoc

It's this documentation.
</blockquote></details>

Thanks!

---

*[flow-server/src/main/java/com/vaadin/server/BootstrapUtils.java, line 261 at r1](https://reviewable.io:443/reviews/vaadin/flow/3135#-L08r-g8P8rjtaUDWr3m:-L09AXol2C08kIHxkUUs:b-pup7it) ([raw file](https://github.com/vaadin/flow/blob/82cf28dff664a11f2a9d9f504c9131b7c2a363c8/flow-server/src/main/java/com/vaadin/server/BootstrapUtils.java#L261)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

They are both in the try() so all are auto closed.
</blockquote></details>

Ah, I was looking at some ancient version, sorry.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3135#-:-L09AbMqx2KTVD56oFnm:bg7igkv)*

**Pull request merged**
