### PR TITLE
refactoring: review fixes

### PR DESCRIPTION
**Pull request by denis-anisimov**

### CODE REVIEW

**Review by pleku — CHANGES_REQUESTED** [review]
Otherwise fine but there are still unresolved comments in the other review PR, check the comments on the _Conversation_ tab

**Comment by denis-anisimov** [comment]
> Otherwise fine but there are still unresolved comments in the other review PR, check the comments on the _Conversation_ tab

Did I miss anything else except `ensureServletContext` ?

**Comment by pleku** [comment]
> > Otherwise fine but there are still unresolved comments in the other review PR, check the comments on the _Conversation_ tab
> 
> Did I miss anything else except `ensureServletContext` ?

Yes, see the `Conversation` tab for the PR and expand the 14 "hidden conversations"
Screenshot 2020-11-03 145724

**Comment by denis-anisimov** [comment]
> > > Otherwise fine but there are still unresolved comments in the other review PR, check the comments on the _Conversation_ tab
> > 
> > 
> > Did I miss anything else except `ensureServletContext` ?
> 
> Yes, see the `Conversation` tab for the PR and expand the 14 "hidden conversations"
> Screenshot 2020-11-03 145724

OK, thanks, I'm not used to this Github review yet :(

**Review by pleku — APPROVED** [review]

**Pull request merged**
