### PR TITLE
Provide es5 adapter for the detected browsers running on IOS 10

### PR DESCRIPTION
**Pull request by ZheSun88**
Fix issue #3959 
Update flow-maven-plugin dependency.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/4099)

### CODE REVIEW

**Comment by ZheSun88** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow/4099#-LCCw1id2i0OFrmE_G5T:-LCCw1id2i0OFrmE_G5U:b-o1s5yo) (no related file):*
block myself for now. need further fix

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4099)*

**Comment by Artur-** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/shared/BrowserDetails.java, line 650 at r2](https://reviewable.io/reviews/vaadin/flow/4099#-LCDyFJo8TX3zL53n6EC:-LCDyFJo8TX3zL53n6ED:bbq0djl) ([raw file](https://github.com/vaadin/flow/blob/4d0dc480c8e3ac0a0cdda53f3000e3df3a58b7d5/flow-server/src/main/java/com/vaadin/flow/shared/BrowserDetails.java#L650)):*
> ```Java
>         // IOS 10 has a problem on `let` bindings, which affects all the browser
>         // running on it. Check https://caniuse.com/#feat=let for more
>         if (!(isIOS() && getOperatingSystemMajorVersion() == 10)) {
> ```

```
if (isIOS() && getOperatingSystemMajorVersion() == 10)) {
   return false;
} 
```

would be a bit more readable and explicit

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4099)*

**Comment by Artur-** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/server/WebBrowser.java, line 583 at r2](https://reviewable.io/reviews/vaadin/flow/4099#-LCE-IL0-BH1Iz9TuWbC:-LCE-IL14yas-W7LR4bM:b-3apbib) ([raw file](https://github.com/vaadin/flow/blob/4d0dc480c8e3ac0a0cdda53f3000e3df3a58b7d5/flow-server/src/main/java/com/vaadin/flow/server/WebBrowser.java#L583)):*
> ```Java
>     public boolean isEs5AdapterNeeded() {
>         if (browserDetails == null) {
>             // Don't know, so assume it is not supported
> ```

What is not supported?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4099)*

**Comment by ZheSun88** [comment]
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/server/WebBrowser.java, line 583 at r2](https://reviewable.io/reviews/vaadin/flow/4099#-LCE-IL0-BH1Iz9TuWbC:-LCE2ftL25JX0xgpXszy:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/4d0dc480c8e3ac0a0cdda53f3000e3df3a58b7d5/flow-server/src/main/java/com/vaadin/flow/server/WebBrowser.java#L583)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

What is not supported?
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/flow/shared/BrowserDetails.java, line 650 at r2](https://reviewable.io/reviews/vaadin/flow/4099#-LCDyFJo8TX3zL53n6EC:-LCE2S0A6XvLkRRoy3eT:bcc9lsu) ([raw file](https://github.com/vaadin/flow/blob/4d0dc480c8e3ac0a0cdda53f3000e3df3a58b7d5/flow-server/src/main/java/com/vaadin/flow/shared/BrowserDetails.java#L650)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

```
if (isIOS() && getOperatingSystemMajorVersion() == 10)) {
   return false;
} 
```

would be a bit more readable and explicit
</blockquote></details>

indeed.. had a few iterations there. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4099)*

**Comment by gilberto-torrezan** [comment]
Reviewed 3 of 5 files at r1, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow/4099#-LCCw1id2i0OFrmE_G5T:-LCh0Rdu196ktxERczRc:b2d49ms) (no related file):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

block myself for now. need further fix
</blockquote></details>

What else is needed?

---

*[flow-server/src/main/java/com/vaadin/flow/shared/BrowserDetails.java, line 650 at r3](https://reviewable.io/reviews/vaadin/flow/4099#-LCh1IULB5aDCiABEtWl:-LCh1IULB5aDCiABEtWm:b-ulhrd9) ([raw file](https://github.com/vaadin/flow/blob/58edbbb7c194825bc65d6e92cd456b26c7600581/flow-server/src/main/java/com/vaadin/flow/shared/BrowserDetails.java#L650)):*
> ```Java
>         // IOS 10 has a problem on `let` bindings, which affects all the browser
>         // running on it. Check https://caniuse.com/#feat=let for more
>         if (isIOS() && getOperatingSystemMajorVersion() == 10) {
> ```

Using the current logic you could just use:
```
if (isEs5AdapaterNeeded()){
    return false;
}
```

---

*[flow-server/src/main/java/com/vaadin/flow/shared/BrowserDetails.java, line 681 at r3](https://reviewable.io/reviews/vaadin/flow/4099#-LCh1cyxDgmKQu9vQJs1:-LCh1cyxDgmKQu9vQJs2:b-iwku0v) ([raw file](https://github.com/vaadin/flow/blob/58edbbb7c194825bc65d6e92cd456b26c7600581/flow-server/src/main/java/com/vaadin/flow/shared/BrowserDetails.java#L681)):*
> ```Java
>     /**
>      * Checks if the browser needs `custom-elements-es5-adapter.js` to be
>      * loaded.
> ```

Extend the documentation by explaining when that file is needed: `This file is needed when the browser has some ES6 capabilities, but a ES5 files are served instead. This happens when the browser doesn't support all ES6 features needed for Flow to work properly, or when some ES6 features have bugs under conditions used by the application`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4099)*

**Comment by ZheSun88** [comment]
Review status: 4 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow/4099#-LCCw1id2i0OFrmE_G5T:-LCh2achAV942XGm-N3W:bby71r4) (no related file):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

What else is needed?
</blockquote></details>

nothing else is needed  now.. this comment was made before we discover the problem is not only on safari 10.

---

*[flow-server/src/main/java/com/vaadin/flow/shared/BrowserDetails.java, line 650 at r3](https://reviewable.io/reviews/vaadin/flow/4099#-LCh1IULB5aDCiABEtWl:-LCh4Ppe8XXMhjn9tmcF:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/58edbbb7c194825bc65d6e92cd456b26c7600581/flow-server/src/main/java/com/vaadin/flow/shared/BrowserDetails.java#L650)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Using the current logic you could just use:
```
if (isEs5AdapaterNeeded()){
    return false;
}
```
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/flow/shared/BrowserDetails.java, line 681 at r3](https://reviewable.io/reviews/vaadin/flow/4099#-LCh1cyxDgmKQu9vQJs1:-LCh4QBM666_4LzD7bQd:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/58edbbb7c194825bc65d6e92cd456b26c7600581/flow-server/src/main/java/com/vaadin/flow/shared/BrowserDetails.java#L681)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Extend the documentation by explaining when that file is needed: `This file is needed when the browser has some ES6 capabilities, but a ES5 files are served instead. This happens when the browser doesn't support all ES6 features needed for Flow to work properly, or when some ES6 features have bugs under conditions used by the application`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4099)*

**Comment by gilberto-torrezan** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4099#-:-LCh5y-VDYPHL_IJagmt:bnfp4nl)*

**Pull request merged**
