### PR TITLE
fix: path difference on windows

### LINKED ISSUE #17998: BundleValidation doesn't detect changes correctly
### Description of the bug

If I add shadow DOM styles to my application, `BundleValidationUtil` will always mark it as a change.

image

Thus, the development bundle is created every time, which significantly slows down the application start.

### Expected behavior

Since there were no changes in theme components CSS files the bundle will not be rebuilt.

### Minimal reproducible example

See [test.zip](https://github.com/vaadin/flow/files/13279677/test.zip)

I took the base spring boot vaadin application and added the shadow DOM styles: `frontend/themes/my-theme/components/vaadin-form-layout.css`.

Every time the application is started, the logs contain information about changes:
<details>
  <summary>LOG</summary>
  
```
2023-11-07T16:10:22.058+04:00  INFO 3532 --- [  restartedMain] c.v.f.s.frontend.BundleValidationUtil    : Checking if a development mode bundle build is needed
2023-11-07T16:10:22.378+04:00  INFO 3532 --- [  restartedMain] c.v.f.s.frontend.BundleValidationUtil    : Detected new or changed theme components CSS files
  themes\my-theme\components\vaadin-form-layout.css

2023-11-07T16:10:22.378+04:00  INFO 3532 --- [  restartedMain] c.v.f.s.frontend.BundleValidationUtil    : Detected removed theme components CSS files
  themes/my-theme/components/vaadin-form-layout.css

2023-11-07T16:10:22.380+04:00  INFO 3532 --- [  restartedMain] c.v.f.s.frontend.BundleValidationUtil    : A development mode bundle build is needed
2023-11-07T16:10:22.501+04:00  INFO 3532 --- [onPool-worker-1] c.v.f.s.frontend.TaskUpdatePackages      : Running `npm install` to resolve and optionally download frontend dependencies. This may take a moment, please stand by...
2023-11-07T16:10:37.184+04:00  INFO 3532 --- [onPool-worker-1] c.v.f.s.frontend.TaskUpdatePackages      : using 'C:\Program Files\nodejs\npm.cmd --no-update-notifier --no-audit --scripts-prepend-node-path=true --ignore-scripts install' for frontend package installation
2023-11-07T16:11:20.550+04:00  INFO 3532 --- [onPool-worker-1] c.v.f.s.frontend.TaskUpdatePackages      : Frontend dependencies resolved successfully.
2023-11-07T16:11:26.173+04:00  INFO 3532 --- [onPool-worker-1] c.v.f.s.frontend.TaskCopyFrontendFiles   : Copying frontend resources from jar files
2023-11-07T16:11:26.436+04:00  INFO 3532 --- [onPool-worker-1] c.v.f.s.frontend.TaskCopyFrontendFiles   : Visited 20 resources. Took 262 ms.
2023-11-07T16:11:26.760+04:00  INFO 3532 --- [onPool-worker-1] c.v.f.s.frontend.TaskRunDevBundleBuild   : Creating a new development mode bundle. This can take a while but will only run when the project setup is changed, addons are added or frontend files are modified
2023-11-07T16:11:51.355+04:00  INFO 3532 --- [onPool-worker-1] c.v.f.s.frontend.TaskRunDevBundleBuild   : Development frontend bundle built
2023-11-07T16:11:51.386+04:00  WARN 3532 --- [onPool-worker-1] c.v.f.s.frontend.TaskRunDevBundleBuild   : Failed to create a README file in src/main/dev-bundle
```

</details>

### Versions

Flow: 24.2.2
Vaadin: 24.2.2
Java: Amazon.com Inc. 19.0.2
OS: amd64 Windows 11 10.0
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36

### PR DESCRIPTION
**Pull request by caalador**
Fix the path when using
windows so that it matches
the stats file path.

Fixes #17998

### CODE REVIEW

**Review by czp13 — APPROVED** [review]
Your fix seems good to me 🎉 , but it seems to me that we have some flaky tests :(. Other PR-s also failing in validation :/.

**Comment by caalador** [comment]
I've seen quite a lot of network issues with downloads and some other sudden failures that should be looked at.

**Comment by mshabarov** [comment]
Does this need a pick to `main` ?

**Comment by caalador** [comment]
No this fix is in main as it came with the compression of dev-bundle, but that again couldn't be picked to 24.2.

**Pull request merged**
