### PR TITLE
#2730: configures JSoup to keep case of tags

### PR DESCRIPTION
**Pull request by paulroemer**
Please check if the way I am converting the InputStream to a String is valid. I may missed a helper class that is doing that already.

It also forced me to change the exception handling a bit.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/2734)

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
Reviewed 1 of 1 files at r1.
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/template/angular/parser/TemplateParser.java, line 76 at r1](https://reviewable.io:443/reviews/vaadin/flow/2734#-Kwt2ZiNaNxsQi2AgW11:-Kwt2ZiNaNxsQi2AgW12:bvc795e) ([raw file](https://github.com/vaadin/flow/blob/05ebee50e5d974d348aa874abb676dc2ce927171/flow-server/src/main/java/com/vaadin/flow/template/angular/parser/TemplateParser.java#L76)):*
> ```Java
>     }
> 
>     private String convertStreamToString(java.io.InputStream is) {
> ```

This method should be `static` in order to fix compile error.

---

*[flow-server/src/main/java/com/vaadin/flow/template/angular/parser/TemplateParser.java, line 77 at r1](https://reviewable.io:443/reviews/vaadin/flow/2734#-Kwt2e5NabQNY1uIYV5Y:-Kwt2e5NabQNY1uIYV5Z:b9auw2q) ([raw file](https://github.com/vaadin/flow/blob/05ebee50e5d974d348aa874abb676dc2ce927171/flow-server/src/main/java/com/vaadin/flow/template/angular/parser/TemplateParser.java#L77)):*
> ```Java
> 
>     private String convertStreamToString(java.io.InputStream is) {
>         try(java.util.Scanner s = new java.util.Scanner(is, "UTF-8")) {
> ```

If you could format the code and add space after `try` it would be awesome.

---

*[flow-server/src/main/java/com/vaadin/flow/template/angular/parser/TemplateParser.java, line 77 at r1](https://reviewable.io:443/reviews/vaadin/flow/2734#-Kwt3Gxn0oawcecYAeam:-Kwt3Gxn0oawcecYAean:b-6pgous) ([raw file](https://github.com/vaadin/flow/blob/05ebee50e5d974d348aa874abb676dc2ce927171/flow-server/src/main/java/com/vaadin/flow/template/angular/parser/TemplateParser.java#L77)):*
> ```Java
> 
>     private String convertStreamToString(java.io.InputStream is) {
>         try(java.util.Scanner s = new java.util.Scanner(is, "UTF-8")) {
> ```

Can you also please use `java.nio.charset.StandardCharsets.UTF_8.name()` instead of `"UTF-8"`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2734)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-server/src/main/java/com/vaadin/flow/template/angular/parser/TemplateParser.java, line 76 at r1](https://reviewable.io:443/reviews/vaadin/flow/2734#-Kwt2ZiNaNxsQi2AgW11:-Kwt3nqAPSpwCu6n3bUY:b-83sjo4) ([raw file](https://github.com/vaadin/flow/blob/05ebee50e5d974d348aa874abb676dc2ce927171/flow-server/src/main/java/com/vaadin/flow/template/angular/parser/TemplateParser.java#L76)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

This method should be `static` in order to fix compile error.
</blockquote></details>

Nice.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2734)*

**Comment by SomeoneToIgnore** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2734#-:-Kwt74dkRPi4PNkAUu8k:bnfp4nl)*

**Comment by SomeoneToIgnore** [comment]
Do you need `1.0.0.alpha5.1` version?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2734#-:-Kwt76bzFserRkzY9kHB:b-5dfkxr)*

**Comment by paulroemer** [comment]
1.0.0.alpha5.1 would be awesome!

**Comment by SomeoneToIgnore** [comment]
On it.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2734#-:-Kwt7bi6-SOcGsMImTgc:bxdh81z)*

**Pull request merged**
