### PR TITLE
Enable logging for testing servers

### PR DESCRIPTION
**Pull request by Legioth**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3436)

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3436#-L458tJ8i_ry-pIdcSui:-L458tJ8i_ry-pIdcSuj:bnmfvv3) (no related file):*
Hmm, what about this one: https://github.com/vaadin/flow/blob/940fe2f3932902cf05103715dd445bf8af30009d/pom.xml#L322

Looks like it's intended to serve the same thing as your change, how will they work together?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3436)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3436)*

**Comment by Legioth** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3436#-L458tJ8i_ry-pIdcSui:-L45HRFDrGsBHqnt1fGT:b-rnyobb) (no related file):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Hmm, what about this one: https://github.com/vaadin/flow/blob/940fe2f3932902cf05103715dd445bf8af30009d/pom.xml#L322

Looks like it's intended to serve the same thing as your change, how will they work together?
</blockquote></details>

`jetty:run` in various `flow-tests` sub modules are not using the `test` scope.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3436)*

**Comment by SomeoneToIgnore** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3436#-L458tJ8i_ry-pIdcSui:-L45HsaAhT4YW11uT1TH:bwt7n6v) (no related file):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

`jetty:run` in various `flow-tests` sub modules are not using the `test` scope.
</blockquote></details>

So, this means that these `log4j12` are useless? 
How about removing them in this PR since they are kind of related?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3436)*

**Comment by Legioth** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3436#-L458tJ8i_ry-pIdcSui:-L45MkSmXIY4EzOfirzB:b9y4xzf) (no related file):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

So, this means that these `log4j12` are useless? 
How about removing them in this PR since they are kind of related?
</blockquote></details>

The `test` scope dependency in `flow/pom.xml` is used by unit tests in all modules.

When running TestBench tests, the previous dependency was only used by the code that runs through JUnit, but not the code running through the Jetty process.

Both are thus needed, even though it could be argued that it's confusing that one part uses `slf4j-log4j12` and the other uses `slf4j-simple`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3436)*

**Comment by SomeoneToIgnore** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3436#-L458tJ8i_ry-pIdcSui:-L45NqZXhN8DGaBQ4YrE:b-ds7e2l) (no related file):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

The `test` scope dependency in `flow/pom.xml` is used by unit tests in all modules.

When running TestBench tests, the previous dependency was only used by the code that runs through JUnit, but not the code running through the Jetty process.

Both are thus needed, even though it could be argued that it's confusing that one part uses `slf4j-log4j12` and the other uses `slf4j-simple`.
</blockquote></details>

Yeah, that's also confusing.

If you want to fix that either, would be cool.
Otherwise you just need to fix the test.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3436)*

**Comment by Legioth** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3436#-L458tJ8i_ry-pIdcSui:-L45Vftss4UcJtdTmlST:b1xs7l9) (no related file):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Yeah, that's also confusing.

If you want to fix that either, would be cool.
Otherwise you just need to fix the test.
</blockquote></details>

Done. The error from the validation build looked like an intermittent network error.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3436)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3436)*

**Comment by Legioth** [comment]
Apparently, we have `ExceptionStacktraceIT.loggerAbsenceWarningAndStacktrace` that explicitly tests that things are broken. That test would have to be pulled out to a separate module without any logging implementation.

**Comment by Legioth** [comment]
I would propose simply removing the test since I cannot come up with any sensible way of excluding the dependency that is defined in the parent pom. Another alternative would be to not use the parent pom for that particular test module, but that would again make the `pom.xml` for this test really bloated.

**Comment by SomeoneToIgnore** [comment]
Sure, go on.

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3436#-:-L4_wGCTO9VFjp4ELsdB:bsy506d)*

**Comment by gilberto-torrezan** [comment]
Reviewed 1 of 3 files at r4.
Review status: 2 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3436)*

**Comment by gilberto-torrezan** [comment]
Reviewed 1 of 3 files at r2, 2 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3436)*

**Pull request merged**
