### PR TITLE
Added HasTheme interface

### PR DESCRIPTION
**Pull request by mikotin**
- For better api to edit theme(s) of component(s)
for example:
        Button button = new Button("Important");
        button.addThemeName("primary");

- Needs to be implemented (directly, or indirectly) to components that support theme-attribute

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/4187)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[flow-server/src/main/java/com/vaadin/flow/component/HasTheme.java, line 24 at r1](https://reviewable.io/reviews/vaadin/flow/4187#-LDaj8XsW4boK4ZCChQC-r1-24:-LDbh2CfAjcpBUq3SKg7:b-jrb7s6) ([raw file](https://github.com/vaadin/flow/blob/1f6259d8980dfedd13e03a5332582224bce9cc1e/flow-server/src/main/java/com/vaadin/flow/component/HasTheme.java#L24)):*
<details><summary><i>Previously, vaadin-bot (Vaadin Bot) wrote…</i></summary><blockquote>

CRITICAL First sentence of Javadoc is incomplete (period is missing) or not present. [rule](https://sonar.projects.vaadin.com/coding_rules#rule_key=checkstyle%3Acom.puppycrawl.tools.checkstyle.checks.javadoc.SummaryJavadocCheck)
</blockquote></details>

Needs to be fixed.

---

*[flow-server/src/main/java/com/vaadin/flow/component/HasTheme.java, line 38 at r1](https://reviewable.io/reviews/vaadin/flow/4187#-LDbhB6hBhQoHS9u-PbQ:-LDbhB6hBhQoHS9u-PbR:bgocret) ([raw file](https://github.com/vaadin/flow/blob/1f6259d8980dfedd13e03a5332582224bce9cc1e/flow-server/src/main/java/com/vaadin/flow/component/HasTheme.java#L38)):*
> ```
> themeName
> ```

Javadoc says it's theme property name.
`themeName` is confusing.

---

*[flow-server/src/main/java/com/vaadin/flow/component/HasTheme.java, line 51 at r1](https://reviewable.io/reviews/vaadin/flow/4187#-LDbhKSoDAM2onQWdvnT:-LDbhKSoDAM2onQWdvnU:b-jgriqh) ([raw file](https://github.com/vaadin/flow/blob/1f6259d8980dfedd13e03a5332582224bce9cc1e/flow-server/src/main/java/com/vaadin/flow/component/HasTheme.java#L51)):*
> ```
> themeName
> ```

same here + method name (and above)

---

*[flow-server/src/main/java/com/vaadin/flow/component/HasTheme.java, line 63 at r1](https://reviewable.io/reviews/vaadin/flow/4187#-LDbhQXb-y9QDK_28tGk:-LDbhQXb-y9QDK_28tGl:b3x2xb6) ([raw file](https://github.com/vaadin/flow/blob/1f6259d8980dfedd13e03a5332582224bce9cc1e/flow-server/src/main/java/com/vaadin/flow/component/HasTheme.java#L63)):*
> ```
> themeName
> ```

and again

---

*[flow-server/src/main/java/com/vaadin/flow/component/HasTheme.java, line 74 at r1](https://reviewable.io/reviews/vaadin/flow/4187#-LDbhVTeD0KylyRQRLPU:-LDbhVTeD0KylyRQRLPV:b-35qvxq) ([raw file](https://github.com/vaadin/flow/blob/1f6259d8980dfedd13e03a5332582224bce9cc1e/flow-server/src/main/java/com/vaadin/flow/component/HasTheme.java#L74)):*
> ```
> getThemeName
> ```

and again

---

*[flow-server/src/main/java/com/vaadin/flow/component/HasTheme.java, line 83 at r1](https://reviewable.io/reviews/vaadin/flow/4187#-LDbhcYy-ZpMjecKporG:-LDbhcYy-ZpMjecKporH:b-rmop2d) ([raw file](https://github.com/vaadin/flow/blob/1f6259d8980dfedd13e03a5332582224bce9cc1e/flow-server/src/main/java/com/vaadin/flow/component/HasTheme.java#L83)):*
> ```
> Despite the name implying a list being returned
> ```

I suspect it's a copy/paste.
But here the method name doesn't say anything about collection nature.
If it's list then it's a list and the sentence is not needed.

But it might be it will be needed after the method name change.
This method name is also need a change.

---

*[flow-server/src/main/java/com/vaadin/flow/component/HasTheme.java, line 104 at r1](https://reviewable.io/reviews/vaadin/flow/4187#-LDbiHYkBrR1EjCfB1wz:-LDbiHYkBrR1EjCfB1x-:b1ld0nn) ([raw file](https://github.com/vaadin/flow/blob/1f6259d8980dfedd13e03a5332582224bce9cc1e/flow-server/src/main/java/com/vaadin/flow/component/HasTheme.java#L104)):*
> ```
> setThemeName(String themeName
> ```

and again.

---

*[flow-server/src/main/java/com/vaadin/flow/component/HasTheme.java, line 116 at r1](https://reviewable.io/reviews/vaadin/flow/4187#-LDbiJxE6R3H7G0Hamzi:-LDbiJxE6R3H7G0Hamzj:betwurn) ([raw file](https://github.com/vaadin/flow/blob/1f6259d8980dfedd13e03a5332582224bce9cc1e/flow-server/src/main/java/com/vaadin/flow/component/HasTheme.java#L116)):*
> ```
> hasThemeName(String themeName
> ```

and again

---

*[flow-server/src/main/java/com/vaadin/flow/component/HasTheme.java, line 126 at r1](https://reviewable.io/reviews/vaadin/flow/4187#-LDbiMkB7r5PRRyIfO_C:-LDbiMkB7r5PRRyIfO_D:b-sohvsm) ([raw file](https://github.com/vaadin/flow/blob/1f6259d8980dfedd13e03a5332582224bce9cc1e/flow-server/src/main/java/com/vaadin/flow/component/HasTheme.java#L126)):*
> ```
> addThemeNames(String... themeNames
> ```

and here

---

*[flow-server/src/main/java/com/vaadin/flow/component/HasTheme.java, line 136 at r1](https://reviewable.io/reviews/vaadin/flow/4187#-LDbiPed97RHojpMMTWC:-LDbiPed97RHojpMMTWD:bmv3upt) ([raw file](https://github.com/vaadin/flow/blob/1f6259d8980dfedd13e03a5332582224bce9cc1e/flow-server/src/main/java/com/vaadin/flow/component/HasTheme.java#L136)):*
> ```
> removeThemeNames(String... themeNames
> ```

and here

---

*[flow-server/src/main/java/com/vaadin/flow/dom/impl/ThemeListImpl.java, line 71 at r1](https://reviewable.io/reviews/vaadin/flow/4187#-LDbj3ca3iqdtebWXk2q:-LDbj3ca3iqdtebWXk2r:byvhfj7) ([raw file](https://github.com/vaadin/flow/blob/1f6259d8980dfedd13e03a5332582224bce9cc1e/flow-server/src/main/java/com/vaadin/flow/dom/impl/ThemeListImpl.java#L71)):*
> ```
> ThemeListImpl
> ```

This is out of the scope of this PR  but I would recommend to rename this class as well.
It's not really a theme list. We are normally use only one theme in the application (at least it's
recommended).
It's a theme properties list.

---

*[flow-server/src/main/java/com/vaadin/flow/dom/impl/ThemeListImpl.java, line 76 at r1](https://reviewable.io/reviews/vaadin/flow/4187#-LDbiWvy004yZfmCOC46:-LDbiWvy004yZfmCOC47:bbk7fnw) ([raw file](https://github.com/vaadin/flow/blob/1f6259d8980dfedd13e03a5332582224bce9cc1e/flow-server/src/main/java/com/vaadin/flow/dom/impl/ThemeListImpl.java#L76)):*
> ```
> s
> ```

Please don't use one letter variables.

---

*[flow-server/src/test/java/com/vaadin/flow/component/HasThemeTest.java, line 127 at r1](https://reviewable.io/reviews/vaadin/flow/4187#-LDbismID-nSTcSnFatR:-LDbismID-nSTcSnFatS:b-ew9e1r) ([raw file](https://github.com/vaadin/flow/blob/1f6259d8980dfedd13e03a5332582224bce9cc1e/flow-server/src/test/java/com/vaadin/flow/component/HasThemeTest.java#L127)):*
> ```
> test
> ```

no need to have it as a prefix

---

*[flow-server/src/test/java/com/vaadin/flow/component/HasThemeTest.java, line 138 at r1](https://reviewable.io/reviews/vaadin/flow/4187#-LDbizdGDY-JmeW6wt8b:-LDbizdGDY-JmeW6wt8c:b-ew9e1r) ([raw file](https://github.com/vaadin/flow/blob/1f6259d8980dfedd13e03a5332582224bce9cc1e/flow-server/src/test/java/com/vaadin/flow/component/HasThemeTest.java#L138)):*
> ```
> test
> ```

no need to have it as a prefix

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4187)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[flow-server/src/main/java/com/vaadin/flow/component/HasTheme.java, line 38 at r1](https://reviewable.io/reviews/vaadin/flow/4187#-LDbhB6hBhQoHS9u-PbQ:-LDosj_sEHTQLWzFKoPO:b-exny07) ([raw file](https://github.com/vaadin/flow/blob/1f6259d8980dfedd13e03a5332582224bce9cc1e/flow-server/src/main/java/com/vaadin/flow/component/HasTheme.java#L38)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
> themeName
> ```

Javadoc says it's theme property name.
`themeName` is confusing.
</blockquote></details>

The method name is fine now but the parameter name still says that it's a `themeName` (here and everywhere).

---

*[flow-server/src/main/java/com/vaadin/flow/dom/impl/ThemeListImpl.java, line 76 at r2](https://reviewable.io/reviews/vaadin/flow/4187#-LDot-042wUVIIgAKZ_4:-LDot-042wUVIIgAKZ_5:b7qefl6) ([raw file](https://github.com/vaadin/flow/blob/1a1298ac051980dd5fe5292d5bb5cd6749cf6595/flow-server/src/main/java/com/vaadin/flow/dom/impl/ThemeListImpl.java#L76)):*
> ```
> themeName
> ```

theme property name

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4187)*

**Comment by gilberto-torrezan** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow/4187#-LEDnP5wDUYJbOAEj1u3:-LEDnP5xDO59M4uV27S6:b-gitvlv) (no related file):*
@denis-anisimov IMO I prefer the original idea of having `add/removeThemeName`, since components can have more than one theme name associated with it. For example, `vaadin-button` can have both `success primary` theme names (see https://vaadin.com/components/vaadin-button/html-examples/button-lumo-theme-demos ).

Making the API similar to the `HasStyle` would make it more consistent and intuitive to use.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4187)*

**Comment by denis-anisimov** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow/4187#-LEDnP5wDUYJbOAEj1u3:-LEDqgrO3li3QyRMssVN:b-q1b88h) (no related file):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

@denis-anisimov IMO I prefer the original idea of having `add/removeThemeName`, since components can have more than one theme name associated with it. For example, `vaadin-button` can have both `success primary` theme names (see https://vaadin.com/components/vaadin-button/html-examples/button-lumo-theme-demos ).

Making the API similar to the `HasStyle` would make it more consistent and intuitive to use.
</blockquote></details>

I don't know.
Whatever if you think it's OK.

My personal opinion: for me it's very confusing to have _themes_  because we may have ONLY one theme globally per application.
If it's not confusing for you then may be I'm the only one such unsatisfied person. So it's possible just ignore me.
Everything is unblocked.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4187#-:-LEDrJyiDvukRb2RNMsL:bnfp4nl)*

**Comment by gilberto-torrezan** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow/4187#-LEDnP5wDUYJbOAEj1u3:-LEDuI3P6pna0NYs-UHf:bdeae9l) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

I don't know.
Whatever if you think it's OK.

My personal opinion: for me it's very confusing to have _themes_  because we may have ONLY one theme globally per application.
If it's not confusing for you then may be I'm the only one such unsatisfied person. So it's possible just ignore me.
Everything is unblocked.
</blockquote></details>

I see, so the confusion is about the relationship between `@Theme` and this interface to add the theme names to components.

I agree that this can be confusing. What other names could be used instead?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4187)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow/4187#-LEDnP5wDUYJbOAEj1u3:-LEDwrPq09U_z4piEMbx:b-pw6hd5) (no related file):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

I see, so the confusion is about the relationship between `@Theme` and this interface to add the theme names to components.

I agree that this can be confusing. What other names could be used instead?
</blockquote></details>

That's exactly the question.

I don't know.

`ThemeProperty`  sound reasonable for me. But I agree that it's not really a good one.
I can't come up with a suitable name for it.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4187)*

**Comment by denis-anisimov** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4187#-:-LEF-gSO1V921-2MP3vc:bnfp4nl)*

**Comment by denis-anisimov** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4187#-:-LEF4uqN7zoRJxHUC92J:bnfp4nl)*

**Comment by mikotin** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-server/src/main/java/com/vaadin/flow/component/HasTheme.java, line 24 at r1](https://reviewable.io/reviews/vaadin/flow/4187#-LDaj8XsW4boK4ZCChQC-r1-24:-LEF5clk1xxTdkEt02M-:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/1f6259d8980dfedd13e03a5332582224bce9cc1e/flow-server/src/main/java/com/vaadin/flow/component/HasTheme.java#L24)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Needs to be fixed.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4187)*

**Comment by denis-anisimov** [comment]
Dismissed @vaadin-bot from a discussion.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4187)*

**Pull request merged**
