### PR TITLE
chore: Maven and Gradle plugins should not be OSGi bundles

### PR DESCRIPTION
**Pull request by Artur-**

### CODE REVIEW

**Comment by Artur-** [comment]
How do you run a Maven plugin through OSGi? 

The newer bnd plugin is not run at all for the plugins but only outputs
```
[13:05:56] :	 [Step 7/11] [INFO] --- bnd-maven-plugin:6.0.0:bnd-process (default) @ flow-maven-plugin ---
[13:05:56] :	 [Step 7/11] [INFO] skip project with packaging=maven-plugin
```

**Comment by mstahv** [comment]
The actual Maven and Gradle plugins probably don't need to be bundles, but the shared library, flow-plugin-base, needs to. @stbischof did I got it right?

**Comment by stbischof** [comment]
yes. It would help to have the shared lib ad an bundle.

**Comment by Artur-** [comment]
Updated so `flow-plugin-base` is still a bundle

**Comment by Artur-** [comment]
Looks good now?

**Comment by stbischof** [comment]
LGTM

**Review by mstahv — APPROVED** [review]

**Pull request merged**
