### PR TITLE
Add VFS support to locate Webjars

### PR DESCRIPTION
**Pull request by heruan**
The default Webjar locator do not support the VFS protocol used e.g. by WildFly. This PR adds the VFS locator as a dependency.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/2845)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2845)*

**Comment by heruan** [comment]
This should be reverted, since I just noticed `webjars-locator-jboss-vfs` declares `jboss-vfs` dependency as "provided", thus throwing CNFE if run outside JBoss/WildFly.

To have Webjars working under WildFly, one needs to add the dependency to its own deployments.

**Comment by denis-anisimov** [comment]
It passed the validation. Which CNFE you are referring ? Since nothing is used from this jar there shouldn't be unsatisfied dependency......

**Comment by heruan** [comment]
This, for example: http://flow.app.fi/components/

The `WebJarAssetLocator` uses a service loader to get all available implementations of interface `UrlProtocolHandler` (see [WebJarAssetLocator.java#L72](https://github.com/webjars/webjars-locator-core/blob/de3f749149541cbf0bc7dcec49f65608fdb570bc/src/main/java/org/webjars/WebJarAssetLocator.java#L72)). The VFS locator has imports from `jboss-vfs`, which is declared as "provided" in the `webjars-locator-jboss-vfs`.

**Comment by denis-anisimov** [comment]
Yep, already got it.
But still it's not clear why our validation works.....
It doesn't fail on Jetty.
But I'm on it, thanks.

**Comment by heruan** [comment]
I guess the `ServiceLoader` not always provide the same order of found implementations, thus the cycle where it tests if the protocol is acceptable for each found locator may load the VFS locator before others and randomly fail.

**Pull request merged**
