### PR TITLE
Change the removeAll behavior to also exclude all client-side nodes

### PR DESCRIPTION
**Pull request by gilberto-torrezan**
Now client-side only nodes are removed when a clear command is issued on the NodeList.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3737)

### CODE REVIEW

**Comment by gilberto-torrezan** [comment]
Review status: 0 of 16 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3737#-L82tI4PMlK5A0M5s_GB:-L82tI4PMlK5A0M5s_GC:b-j5502w) (no related file):*
@legioth please take a look on the implementation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3737)*

**Comment by denis-anisimov** [comment]
Reviewed 16 of 16 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3737#-L82tI4PMlK5A0M5s_GB:-L86C3nu3y6-8K3qxry7:bmxyyvm) (no related file):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

@legioth please take a look on the implementation.
</blockquote></details>

The code looks fine.
But there are two things that I'm worry about:
- API/method name. No one reads javadocs. So I consider method `removeAll()` as just a convenience method for calling `remove` for all children (server side children). And it will be a surprise when it does more than expected. I would suggest _at least_ rename this method to something else (without any _remove_ mention) so that there is no any confusion about `remove` action. Additionally I would keep old `removeAll` and introduce one more method which removes also client side elements. So the word `remove`  will not confuse you at all and most likely you will be aware of what you are doing when you call another method which removes all client side children
- The method is intended to be used with polymer templates. I still think it's dangerous to remove the client side content inside a template element when the children are referenced from the server side. I'm talking about having `@Id` elements inside or between those client side elements which will be removed. I suggest: either totally deny of calling "remove all" if there are descendants referenced via `@Id` (via throwing exception on the server side) or explicitly make API which makes this clear.

For the last item about API :
- we may provide property for `@Id` which allows for the injected element to be removed and may be says what to do in this case: don't do anything, throw an exception when any method on removed element is called.  
- "remove all" method may have an additional argument which is `Consumer` . The `Consumer` instance accepts a list of removed `@Id` (or any server side elements). This method may be overloaded by the method without `Consumer` as an argument but it just call the two argument method with `Consumer` which by default log warning for removed `@Id` elements (or may be better by default it throws an exception if any such element is removed)

---

*[flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/NodeListAddRemoveTest.java, line 271 at r1](https://reviewable.io:443/reviews/vaadin/flow/3737#-L86BPQh8O24g-gIZpSS:-L86BPQh8O24g-gIZpST:bnb81zg) ([raw file](https://github.com/vaadin/flow/blob/6793cfa76b6f24e765916060a5584dbb65df35b3/flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/NodeListAddRemoveTest.java#L271)):*
>  Assert.assertThat(nodeChange,
>                 CoreMatchers.instanceOf(ListClearChange.class));
>         Assert.assertTrue(nodeChange instanceof ListClearChange);

Either one or another. No need to to do both assertions.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3737)*

**Comment by gilberto-torrezan** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3737#-L82tI4PMlK5A0M5s_GB:-L86gQTChoaVyoOy5wj6:b3vy1cs) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

The code looks fine.
But there are two things that I'm worry about:
- API/method name. No one reads javadocs. So I consider method `removeAll()` as just a convenience method for calling `remove` for all children (server side children). And it will be a surprise when it does more than expected. I would suggest _at least_ rename this method to something else (without any _remove_ mention) so that there is no any confusion about `remove` action. Additionally I would keep old `removeAll` and introduce one more method which removes also client side elements. So the word `remove`  will not confuse you at all and most likely you will be aware of what you are doing when you call another method which removes all client side children
- The method is intended to be used with polymer templates. I still think it's dangerous to remove the client side content inside a template element when the children are referenced from the server side. I'm talking about having `@Id` elements inside or between those client side elements which will be removed. I suggest: either totally deny of calling "remove all" if there are descendants referenced via `@Id` (via throwing exception on the server side) or explicitly make API which makes this clear.

For the last item about API :
- we may provide property for `@Id` which allows for the injected element to be removed and may be says what to do in this case: don't do anything, throw an exception when any method on removed element is called.  
- "remove all" method may have an additional argument which is `Consumer` . The `Consumer` instance accepts a list of removed `@Id` (or any server side elements). This method may be overloaded by the method without `Consumer` as an argument but it just call the two argument method with `Consumer` which by default log warning for removed `@Id` elements (or may be better by default it throws an exception if any such element is removed)
</blockquote></details>

One thing to mention: calling `removeAll` doesn't remove elements from the shadow root. So if you have a `PolymerTemplate` with several components inside mapped with `@Id`, those components are not removed when `removeAll` is called.

The test that uses a slot showcases this - only components added to the slot are removed.

About having a separate method for removing client side components, I've suggested that as well, but @legioth convinced me that it wouldn't be needed. I don't recall the arguments though.

---

*[flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/NodeListAddRemoveTest.java, line 271 at r1](https://reviewable.io:443/reviews/vaadin/flow/3737#-L86BPQh8O24g-gIZpSS:-L86iC8H2PA_1S5uPg2l:bppj6ac) ([raw file](https://github.com/vaadin/flow/blob/6793cfa76b6f24e765916060a5584dbb65df35b3/flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/NodeListAddRemoveTest.java#L271)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

>  Assert.assertThat(nodeChange,
>                 CoreMatchers.instanceOf(ListClearChange.class));
>         Assert.assertTrue(nodeChange instanceof ListClearChange);

Either one or another. No need to to do both assertions.
</blockquote></details>

Oops, that was an oversight, the second assert shouldn't be there.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3737)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/flow/3737#-L82tI4PMlK5A0M5s_GB:-L86yRQk5Bbpfr6tMY36:biwmq6d) (no related file):*
> One thing to mention: calling removeAll doesn't remove elements from the shadow root. 

Do you mean `shadowRoot` as the node on which `removeAll` is called or as an ancestor of some element on which `removeAll` is called ?

If it's some element inside `shadowRoot` then I don't understand how `removeAll` works.....
Does it remove only children if the element is a regular element outside of template?

About `removeAll` name: I'm pretty sure it will be a confusion. But let's prove/disprove this by the future UX.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3737)*

**Comment by denis-anisimov** [comment]
Reviewed 2 of 2 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3737)*

**Comment by denis-anisimov** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3737#-:-L8WH6JpCBun-fkWgQ3K:bnfp4nl)*

**Pull request merged**
