### PR TITLE
viewport attributes - enumeration #3597

### PR DESCRIPTION
**Pull request by DiegoSanzVi**
Enumeration for all the attributes of Viewport.

Provide String constants for common @Viewport settings #3597

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/4792)

### CODE REVIEW

**Comment by DiegoSanzVi** [comment]
Maybe it would be better to create another ViewPort annotation or edit the current one:

@ViewportDiego(width = "100%",initialScale = "1.0",userScalable = false)
public class MyView {

}

I think it should be relatively easy to do.

**Comment by DiegoSanzVi** [comment]
Would it be better to use constant attributes names instead of transforming the anotation's method names into viewport attributes?

**Comment by bogdanudrescu** [comment]
@denis-anisimov the original ticket requires only one extra constant to be added besides current `DEFAULT = "width=device-width, initial-scale=1.0";` (although it's not exactly expressed like this, but the meaning is the same). We may keep to ticket's requirements or we may extend the scope if it's necessary and define the annotation as @DiegoSanzVi suggested.

**Comment by DiegoSanzVi** [comment]
I modiffied the PR to add just those 2 fields.
    
String FULL_SCREEN_MOBILE = "width=device-width, initial-scale=1";

String MOBILE_FIXED_ZOOM = "initial-scale=1, maximum-scale=1";

I think it would be better if viewport had those fields in the annotation part, but it is true that it creates a lot of problems as Denis mentioned before.

**Comment by OlliTietavainenVaadin** [comment]
@denis-anisimov I'm not sure if there are other sensible configurations. It's better than nothing?

**Comment by denis-anisimov** [comment]
> @denis-anisimov I'm not sure if there are other sensible configurations. It's better than nothing?

Sure, I'm fine if you are fine.

**Pull request merged**
