### PR TITLE
Improve introduction and vaadin components docs

### PR DESCRIPTION
**Pull request by pleku**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3340)

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[flow-documentation/Overview.asciidoc, line 22 at r1](https://reviewable.io:443/reviews/vaadin/flow/3340#-L33MjzJzBPb0SyR3fT3:-L33MjzJzBPb0SyR3fT4:b-iqa6dw) ([raw file](https://github.com/vaadin/flow/blob/538348dd11e2531ea3dce3bed5ddfc4e5445b207/flow-documentation/Overview.asciidoc#L22)):*
> Flow

Judging by the other changes, you might want to replace it with `Vaadin Flow` also.

---

*[flow-documentation/components/tutorial-flow-components-setup.asciidoc, line 24 at r1](https://reviewable.io:443/reviews/vaadin/flow/3340#-L33O9ddhdnlOf6HPN_I:-L33O9ddhdnlOf6HPN_J:b-2w9q8d) ([raw file](https://github.com/vaadin/flow/blob/538348dd11e2531ea3dce3bed5ddfc4e5445b207/flow-documentation/components/tutorial-flow-components-setup.asciidoc#L24)):*
> https://vaadin.com/elements/vaadin-notification/java-examples

404

---

*[flow-documentation/components/tutorial-flow-components-setup.asciidoc, line 25 at r1](https://reviewable.io:443/reviews/vaadin/flow/3340#-L33OEcYMa78YN8s9rMc:-L33OEcYMa78YN8s9rMd:bdnt3jo) ([raw file](https://github.com/vaadin/flow/blob/538348dd11e2531ea3dce3bed5ddfc4e5445b207/flow-documentation/components/tutorial-flow-components-setup.asciidoc#L25)):*
> https://vaadin.com/elements/vaadin-ordered-layout/java-examples

404

---

*[flow-documentation/components/tutorial-flow-components-setup.asciidoc, line 28 at r1](https://reviewable.io:443/reviews/vaadin/flow/3340#-L33OME1VDtlQNVOKsMn:-L33OME1VDtlQNVOKsMo:b-8a8m0w) ([raw file](https://github.com/vaadin/flow/blob/538348dd11e2531ea3dce3bed5ddfc4e5445b207/flow-documentation/components/tutorial-flow-components-setup.asciidoc#L28)):*
> https://vaadin.com/elements/vaadin-tabs/java-examples

404

---

*[flow-documentation/introduction/introduction-overview.asciidoc, line 47 at r1](https://reviewable.io:443/reviews/vaadin/flow/3340#-L33Op9S9sKHW2miAjKk:-L33Op9S9sKHW2miAjKl:bk0n6x9) ([raw file](https://github.com/vaadin/flow/blob/538348dd11e2531ea3dce3bed5ddfc4e5445b207/flow-documentation/introduction/introduction-overview.asciidoc#L47)):*
> ```AsciiDoc
> 
> textField.addValueChangeListener(event ->
> 	greeting.setText("Hello " + event.getValue()));
> ```

Would it make sense to replace tabs with spaces since we use them everywhere? (same for code snippets below)

---

*[flow-documentation/introduction/introduction-overview.asciidoc, line 76 at r1](https://reviewable.io:443/reviews/vaadin/flow/3340#-L33PDpJ_rWeV-pRkrVk:-L33PDpJ_rWeV-pRkrVl:b-v98iva) ([raw file](https://github.com/vaadin/flow/blob/538348dd11e2531ea3dce3bed5ddfc4e5445b207/flow-documentation/introduction/introduction-overview.asciidoc#L76)):*
> show easy it is to access

Something is missing here.

---

*[flow-documentation/introduction/introduction-overview.asciidoc, line 155 at r1](https://reviewable.io:443/reviews/vaadin/flow/3340#-L33PbJDKiOOpE8FmmWD:-L33PbJDKiOOpE8FmmWE:bd5amkk) ([raw file](https://github.com/vaadin/flow/blob/538348dd11e2531ea3dce3bed5ddfc4e5445b207/flow-documentation/introduction/introduction-overview.asciidoc#L155)):*
> ```AsciiDoc
> See the <<../routing/tutorial-routing-annotation#,Routing and Navigation>> tutorials for more info.
> 
> // TODO could highlight the data binding API here with e.g. bean grid example //
> ```

Since the documentation is publicly available now, would it make sense to create a ticket instead and remove the line?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3340)*

**Comment by caalador** [comment]
The elements do not seem to be on vaadin.com anymore for the 404 results Kirill mentioned 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3340#-:-L33b7bx-PK-B9ymqh3v:brqcksh)*

**Comment by SomeoneToIgnore** [comment]
It's possible to add external url verifications in our docs, but not sure if it's worth it.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3340#-:-L33besYd8aJQ_fFqIth:b-1qlp9n)*

**Comment by pleku** [comment]
Review status: 3 of 6 files reviewed at latest revision, 7 unresolved discussions.

---

*[flow-documentation/Overview.asciidoc, line 22 at r1](https://reviewable.io:443/reviews/vaadin/flow/3340#-L33MjzJzBPb0SyR3fT3:-L41Jrruxfibfat20Gzw:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/538348dd11e2531ea3dce3bed5ddfc4e5445b207/flow-documentation/Overview.asciidoc#L22)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

> Flow

Judging by the other changes, you might want to replace it with `Vaadin Flow` also.
</blockquote></details>

Done.

---

*[flow-documentation/components/tutorial-flow-components-setup.asciidoc, line 24 at r1](https://reviewable.io:443/reviews/vaadin/flow/3340#-L33O9ddhdnlOf6HPN_I:-L41KiPXYocqCqUzF8AG:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/538348dd11e2531ea3dce3bed5ddfc4e5445b207/flow-documentation/components/tutorial-flow-components-setup.asciidoc#L24)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

> https://vaadin.com/elements/vaadin-notification/java-examples

404
</blockquote></details>

Done.

---

*[flow-documentation/components/tutorial-flow-components-setup.asciidoc, line 25 at r1](https://reviewable.io:443/reviews/vaadin/flow/3340#-L33OEcYMa78YN8s9rMc:-L41KimqJ41LroKVfMSx:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/538348dd11e2531ea3dce3bed5ddfc4e5445b207/flow-documentation/components/tutorial-flow-components-setup.asciidoc#L25)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

> https://vaadin.com/elements/vaadin-ordered-layout/java-examples

404
</blockquote></details>

Done.

---

*[flow-documentation/components/tutorial-flow-components-setup.asciidoc, line 28 at r1](https://reviewable.io:443/reviews/vaadin/flow/3340#-L33OME1VDtlQNVOKsMn:-L41KjPMrm9N8K-7e5IE:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/538348dd11e2531ea3dce3bed5ddfc4e5445b207/flow-documentation/components/tutorial-flow-components-setup.asciidoc#L28)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

> https://vaadin.com/elements/vaadin-tabs/java-examples

404
</blockquote></details>

Done.

---

*[flow-documentation/introduction/introduction-overview.asciidoc, line 47 at r1](https://reviewable.io:443/reviews/vaadin/flow/3340#-L33Op9S9sKHW2miAjKk:-L41LLmD5v67iSVpMqqC:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/538348dd11e2531ea3dce3bed5ddfc4e5445b207/flow-documentation/introduction/introduction-overview.asciidoc#L47)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Would it make sense to replace tabs with spaces since we use them everywhere? (same for code snippets below)
</blockquote></details>

Done.

---

*[flow-documentation/introduction/introduction-overview.asciidoc, line 76 at r1](https://reviewable.io:443/reviews/vaadin/flow/3340#-L33PDpJ_rWeV-pRkrVk:-L41LZVx19wODb3Rnc2n:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/538348dd11e2531ea3dce3bed5ddfc4e5445b207/flow-documentation/introduction/introduction-overview.asciidoc#L76)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

> show easy it is to access

Something is missing here.
</blockquote></details>

Done.

---

*[flow-documentation/introduction/introduction-overview.asciidoc, line 155 at r1](https://reviewable.io:443/reviews/vaadin/flow/3340#-L33PbJDKiOOpE8FmmWD:-L41MQxrYsINFIhd1dM-:b8u91yf) ([raw file](https://github.com/vaadin/flow/blob/538348dd11e2531ea3dce3bed5ddfc4e5445b207/flow-documentation/introduction/introduction-overview.asciidoc#L155)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Since the documentation is publicly available now, would it make sense to create a ticket instead and remove the line?
</blockquote></details>

Done
https://github.com/vaadin/flow/issues/3430

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3340)*

**Comment by SomeoneToIgnore** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3340#-:-L41NIijT2bmFE9iWdYn:bnfp4nl)*

**Pull request merged**
