### PR TITLE
@Route annotation now can be used without explicit value

### LINKED ISSUE #3604: Use class name as default path for @Route
`When adding routes, I don't want to specify route paths as magic strings, but instead to be automatically derived from the java class name, so I can write less code.`

Eg. `@Route class Blog extends Div { ... }` would be mapped to `/blog`.

Automatic path derivation will be needed for html files without java classes https://github.com/vaadin/flow/issues/3467

### PR DESCRIPTION
**Pull request by mstahv**
If value is not given for Route annotation, route value is derived from the component class name

Only for preliminary comments at this point, needs some documentation and tests to core at least. Maybe changes to vaadin-spring too? I only tested this in external project.

closes #3604

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/4104)

### CODE REVIEW

**Comment by ZheSun88** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[flow-server/src/main/java/com/vaadin/flow/router/Router.java, line 460 at r2](https://reviewable.io/reviews/vaadin/flow/4104#-LC4zPg2ntsLRl7iaqMp-r2-460:-LCTEAyq4riSwYLRZSJf:b32v57) ([raw file](https://github.com/vaadin/flow/blob/0193b6630577e96a3baf69b2e0b3b09e7ff57d49/flow-server/src/main/java/com/vaadin/flow/router/Router.java#L460)):*
<details><summary><i>Previously, vaadin-bot (Vaadin Bot) wrote…</i></summary><blockquote>

MINOR Move the "MainView" string literal on the left side of this string comparison. [rule](https://sonar.projects.vaadin.com/coding_rules#rule_key=squid%3AS1132)
MINOR Move the "Main" string literal on the left side of this string comparison. [rule](https://sonar.projects.vaadin.com/coding_rules#rule_key=squid%3AS1132)

</blockquote></details>

+1

---

*[flow-server/src/main/java/com/vaadin/flow/server/startup/AbstractRouteRegistryInitializer.java, line 29 at r2](https://reviewable.io/reviews/vaadin/flow/4104#-LCTDp8dBPto6T5CKrYs:-LCTDp8dBPto6T5CKrYt:bdma1mq) ([raw file](https://github.com/vaadin/flow/blob/0193b6630577e96a3baf69b2e0b3b09e7ff57d49/flow-server/src/main/java/com/vaadin/flow/server/startup/AbstractRouteRegistryInitializer.java#L29)):*
> ```Java
> import com.vaadin.flow.component.Component;
> import com.vaadin.flow.component.UI;
> import com.vaadin.flow.router.*;
> ```

according to flow code convention, do not use the * for import. same with other places

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4104)*

**Comment by denis-anisimov** [comment]
Reviewed 4 of 6 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow/4104#-LCXhJdbEtxGYo0I158z:-LCXhJdbEtxGYo0I159-:b-7wzdov) (no related file):*
There is `RouteAlias` annotation which should be handled similarly I think.
And there are not any test.

---

*[flow-server/src/main/java/com/vaadin/flow/router/NavigationState.java, line 78 at r2](https://reviewable.io/reviews/vaadin/flow/4104#-LCXeSMd6zHnH0bXRCKp:-LCXeSMd6zHnH0bXRCKq:bcwujzo) ([raw file](https://github.com/vaadin/flow/blob/0193b6630577e96a3baf69b2e0b3b09e7ff57d49/flow-server/src/main/java/com/vaadin/flow/router/NavigationState.java#L78)):*
> ```
> r
> ```

No one letter variable please.

---

*[flow-server/src/main/java/com/vaadin/flow/router/Route.java, line 42 at r2](https://reviewable.io/reviews/vaadin/flow/4104#-LCXeYeF5ZuZ0bcVCdJr:-LCXeYeF5ZuZ0bcVCdJs:b-wlw7e7) ([raw file](https://github.com/vaadin/flow/blob/0193b6630577e96a3baf69b2e0b3b09e7ff57d49/flow-server/src/main/java/com/vaadin/flow/router/Route.java#L42)):*
> ```
> static final 
> ```

Please remove.

---

*[flow-server/src/main/java/com/vaadin/flow/router/Route.java, line 49 at r2](https://reviewable.io/reviews/vaadin/flow/4104#-LCXecRK2CQ94Mb9RxUL:-LCXecRK2CQ94Mb9RxUM:bc92vo2) ([raw file](https://github.com/vaadin/flow/blob/0193b6630577e96a3baf69b2e0b3b09e7ff57d49/flow-server/src/main/java/com/vaadin/flow/router/Route.java#L49)):*
> ```
>      * name of the component. The derived name will be lower case and possibly
>      * trailing "View" will be removed. Also, MainView or Main names will be
> ```

If I'm lucky then it will be removed and if I'm not then it won't be ? :)
There should be exact description how it works.

In reality we should have a customizable strategy to produce a default route name.
I will create a separate ticket for this.
The logic here should be just a default strategy implementation, but anyway it should say
how it works deterministically.

---

*[flow-server/src/main/java/com/vaadin/flow/router/Route.java, line 54 at r2](https://reviewable.io/reviews/vaadin/flow/4104#-LCXfGey4Tp5NWJgxPpg:-LCXfGey4Tp5NWJgxPph:b-atf41e) ([raw file](https://github.com/vaadin/flow/blob/0193b6630577e96a3baf69b2e0b3b09e7ff57d49/flow-server/src/main/java/com/vaadin/flow/router/Route.java#L54)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>      * <p>Note, framework should not use the value directly, but use the
>      * helper method {@link Router#resolve(Class, Route)}, so that
>      * naming convention based values are dealt correctly.</p>
>      *
> ```
</details>


Is this comment for the end user or for us ?
Use doesn't have a control over the FW so it should be either reformulated (`FW doesn't use directly` instead of `should`) or removed.

---

*[flow-server/src/main/java/com/vaadin/flow/router/Route.java, line 58 at r2](https://reviewable.io/reviews/vaadin/flow/4104#-LCXfl0fEW3DeoS2A6AW:-LCXfl0fEW3DeoS2A6AX:b-n84jw4) ([raw file](https://github.com/vaadin/flow/blob/0193b6630577e96a3baf69b2e0b3b09e7ff57d49/flow-server/src/main/java/com/vaadin/flow/router/Route.java#L58)):*
> ```
> default NAMING_CONVENTION
> ```


This is magic string which technically may be a route. And this is one more reason to have a customizable name producer.
May be it should be replaced with some symbol which definitely may not be a route path ?

---

*[flow-server/src/main/java/com/vaadin/flow/router/Router.java, line 457 at r2](https://reviewable.io/reviews/vaadin/flow/4104#-LCXgpZs-JoJZwA6-ydA:-LCXgpZs-JoJZwA6-ydB:b1xr82w) ([raw file](https://github.com/vaadin/flow/blob/0193b6630577e96a3baf69b2e0b3b09e7ff57d49/flow-server/src/main/java/com/vaadin/flow/router/Router.java#L457)):*
> ```
> public static String resolve(Class<?> component, Route route) {
> ```

The problem with this method is : it may not be overridden.
I would prefer to have it non `static` but it's not easy with the current state of the sources.
May be OK for now to have it `static`

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4104)*

**Comment by caalador** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks broke.

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow/4104#-LCXhJdbEtxGYo0I158z:-LCXhwd-Bs6WYgdQwqaE:b-xkossl) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

There is `RouteAlias` annotation which should be handled similarly I think.
And there are not any test.
</blockquote></details>

Also `RouteAlias` should probable in the case of  default route (e.g. `Main`/`MainView` == "") lead to not "" but Main

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4104)*

**Comment by mstahv** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks broke.

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow/4104#-LCXhJdbEtxGYo0I158z:-LCXnstEE-PU5eKNgGyL:b-nc8jja) (no related file):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Also `RouteAlias` should probable in the case of  default route (e.g. `Main`/`MainView` == "") lead to not "" but Main
</blockquote></details>

I hadn't spotted RouteAlias until this comment, but based on what I read from its JavaDocs, I don't see why we should use the naming convention for that. If users want to use the naming convention, they can use it with the required Route annotation as well?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4104)*

**Comment by mstahv** [comment]
Review status: 3 of 6 files reviewed at latest revision, 9 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/router/NavigationState.java, line 78 at r2](https://reviewable.io/reviews/vaadin/flow/4104#-LCXeSMd6zHnH0bXRCKp:-LCXub4U6wqgo4shzH3l:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/0193b6630577e96a3baf69b2e0b3b09e7ff57d49/flow-server/src/main/java/com/vaadin/flow/router/NavigationState.java#L78)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
> r
> ```

No one letter variable please.
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/flow/router/Route.java, line 42 at r2](https://reviewable.io/reviews/vaadin/flow/4104#-LCXeYeF5ZuZ0bcVCdJr:-LCXucPY3qiDqUg3_BK0:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/0193b6630577e96a3baf69b2e0b3b09e7ff57d49/flow-server/src/main/java/com/vaadin/flow/router/Route.java#L42)):*
<details><summary><i>Previously, mstahv (Matti Tahvonen) wrote…</i></summary><blockquote>

Ok, sure I will. But IMO, it makes things more explicit/readable as developers are not so often working with annotations.
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/flow/router/Route.java, line 43 at r2](https://reviewable.io/reviews/vaadin/flow/4104#-LC4zPg2ntsLRl7iaqMo-r2-43:-LCXud3W44FQwsH3Fwac:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/0193b6630577e96a3baf69b2e0b3b09e7ff57d49/flow-server/src/main/java/com/vaadin/flow/router/Route.java#L43)):*
<details><summary><i>Previously, vaadin-bot (Vaadin Bot) wrote…</i></summary><blockquote>

MINOR "static" is redundant in this context. [rule](https://sonar.projects.vaadin.com/coding_rules#rule_key=squid%3AS2333)
MINOR "final" is redundant in this context. [rule](https://sonar.projects.vaadin.com/coding_rules#rule_key=squid%3AS2333)

</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/flow/router/Route.java, line 49 at r2](https://reviewable.io/reviews/vaadin/flow/4104#-LCXecRK2CQ94Mb9RxUL:-LCXueLJ18qHYq0n77nq:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/0193b6630577e96a3baf69b2e0b3b09e7ff57d49/flow-server/src/main/java/com/vaadin/flow/router/Route.java#L49)):*
<details><summary><i>Previously, mstahv (Matti Tahvonen) wrote…</i></summary><blockquote>

Will refine the documentation. I also thought about allowing customisation for naming convention, but thought it could be added later if requested.
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/flow/router/Route.java, line 54 at r2](https://reviewable.io/reviews/vaadin/flow/4104#-LCXfGey4Tp5NWJgxPpg:-LCXujbgEhoDG0qgp8Z_:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/0193b6630577e96a3baf69b2e0b3b09e7ff57d49/flow-server/src/main/java/com/vaadin/flow/router/Route.java#L54)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
>      * <p>Note, framework should not use the value directly, but use the
>      * helper method {@link Router#resolve(Class, Route)}, so that
>      * naming convention based values are dealt correctly.</p>
>      *
> ```

Is this comment for the end user or for us ?
Use doesn't have a control over the FW so it should be either reformulated (`FW doesn't use directly` instead of `should`) or removed.
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/flow/router/Route.java, line 58 at r2](https://reviewable.io/reviews/vaadin/flow/4104#-LCXfl0fEW3DeoS2A6AW:-LCXukgi8hAGnnIWS5hu:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/0193b6630577e96a3baf69b2e0b3b09e7ff57d49/flow-server/src/main/java/com/vaadin/flow/router/Route.java#L58)):*
<details><summary><i>Previously, mstahv (Matti Tahvonen) wrote…</i></summary><blockquote>

This is why I added three underscores to it. I think that is enough. Maybe write naming convention in Sami language ;-)
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/flow/router/Router.java, line 460 at r2](https://reviewable.io/reviews/vaadin/flow/4104#-LC4zPg2ntsLRl7iaqMp-r2-460:-LCXumPkCg_8GWYcCPZw:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/0193b6630577e96a3baf69b2e0b3b09e7ff57d49/flow-server/src/main/java/com/vaadin/flow/router/Router.java#L460)):*
<details><summary><i>Previously, mstahv (Matti Tahvonen) wrote…</i></summary><blockquote>

Class name can't be null so I'm kind of wasting my time here, but sure...
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/flow/server/startup/AbstractRouteRegistryInitializer.java, line 29 at r2](https://reviewable.io/reviews/vaadin/flow/4104#-LCTDp8dBPto6T5CKrYs:-LCXungV1ak1YAmjxTAQ:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/0193b6630577e96a3baf69b2e0b3b09e7ff57d49/flow-server/src/main/java/com/vaadin/flow/server/startup/AbstractRouteRegistryInitializer.java#L29)):*
<details><summary><i>Previously, mstahv (Matti Tahvonen) wrote…</i></summary><blockquote>

Damn IntelliJ. Will fix.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4104)*

**Comment by ZheSun88** [comment]
Review status: 3 of 6 files reviewed at latest revision, 8 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java, line 31 at r3](https://reviewable.io/reviews/vaadin/flow/4104#-LCXvGgA2z7oSqqBqfHM:-LCXvGgA2z7oSqqBqfHN:ba1hxzw) ([raw file](https://github.com/vaadin/flow/blob/320283363d624b4d73589d895916c77eb32676b9/flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java#L31)):*
> ```Java
> import com.vaadin.flow.di.Instantiator;
> import com.vaadin.flow.internal.ReflectTools;
> import com.vaadin.flow.router.*;
> ```

* here also

---

*[flow-server/src/main/java/com/vaadin/flow/router/internal/RouterUtil.java, line 32 at r3](https://reviewable.io/reviews/vaadin/flow/4104#-LCXvDzxEurwY7Ih1Yx0:-LCXvDzy9jL8th2urvvp:br6021e) ([raw file](https://github.com/vaadin/flow/blob/320283363d624b4d73589d895916c77eb32676b9/flow-server/src/main/java/com/vaadin/flow/router/internal/RouterUtil.java#L32)):*
> ```Java
> import com.vaadin.flow.component.UI;
> import com.vaadin.flow.internal.AnnotationReader;
> import com.vaadin.flow.router.*;
> ```

* here also.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4104)*

**Comment by denis-anisimov** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow/4104#-LCXhJdbEtxGYo0I158z:-LCY0lOBBs99qIxdoUDX:b-o5s7c1) (no related file):*
<details><summary><i>Previously, mstahv (Matti Tahvonen) wrote…</i></summary><blockquote>

I hadn't spotted RouteAlias until this comment, but based on what I read from its JavaDocs, I don't see why we should use the naming convention for that. If users want to use the naming convention, they can use it with the required Route annotation as well?
</blockquote></details>

`RouteAlias` may be really is quite specific which should not be used with generated names.

But tests still would be good to have.

---

*[flow-server/src/main/java/com/vaadin/flow/router/Router.java, line 457 at r2](https://reviewable.io/reviews/vaadin/flow/4104#-LCXgpZs-JoJZwA6-ydA:-LCY0Y6sAWdiGF4TFwrL:b-80bnvp) ([raw file](https://github.com/vaadin/flow/blob/0193b6630577e96a3baf69b2e0b3b09e7ff57d49/flow-server/src/main/java/com/vaadin/flow/router/Router.java#L457)):*
<details><summary><i>Previously, mstahv (Matti Tahvonen) wrote…</i></summary><blockquote>

That's true, but I guess it is not trivial to use custom Router either. I think this is related to your enhancement idea and can be probably changed later if a customisations to naming convention is allowed.
</blockquote></details>

True.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4104)*

**Comment by mstahv** [comment]
Review status: 4 of 6 files reviewed at latest revision, 5 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java, line 31 at r3](https://reviewable.io/reviews/vaadin/flow/4104#-LCXvGgA2z7oSqqBqfHM:-LCYNGra6lSyBqKxjBUy:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/320283363d624b4d73589d895916c77eb32676b9/flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java#L31)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

* here also
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/flow/router/internal/RouterUtil.java, line 32 at r3](https://reviewable.io/reviews/vaadin/flow/4104#-LCXvDzxEurwY7Ih1Yx0:-LCYNJCe3L5Y4oMqYcUm:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/320283363d624b4d73589d895916c77eb32676b9/flow-server/src/main/java/com/vaadin/flow/router/internal/RouterUtil.java#L32)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

* here also.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4104)*

**Comment by mstahv** [comment]
Review status: 4 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow/4104#-LCXhJdbEtxGYo0I158z:-LCYNXBG6Y4Z-Cei15e5:b9ejd2c) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

`RouteAlias` may be really is quite specific which should not be used with generated names.

But tests still would be good to have.
</blockquote></details>

I'm bit confused, probably because of this reviewable thingie. Tests for RouteAlias or for this feature? For this feature for sure. Would you suggest to write integration tests, integration tests or both?

---

*[flow-server/src/main/java/com/vaadin/flow/router/Router.java, line 457 at r2](https://reviewable.io/reviews/vaadin/flow/4104#-LCXgpZs-JoJZwA6-ydA:-LCYO1S9EYblXyi7Mj1f:begrnk2) ([raw file](https://github.com/vaadin/flow/blob/0193b6630577e96a3baf69b2e0b3b09e7ff57d49/flow-server/src/main/java/com/vaadin/flow/router/Router.java#L457)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

True.
</blockquote></details>

So let's leave this as it is? Should I click some button to resolve this :-)

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4104)*

**Comment by denis-anisimov** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow/4104#-LCXhJdbEtxGYo0I158z:-LCYP9NG8YTE8D1XFBFB:b-n00c8r) (no related file):*
<details><summary><i>Previously, mstahv (Matti Tahvonen) wrote…</i></summary><blockquote>

I'm bit confused, probably because of this reviewable thingie. Tests for RouteAlias or for this feature? For this feature for sure. Would you suggest to write integration tests, integration tests or both?
</blockquote></details>

Please ignore `RouteAlias` .
Tests for this feature.
Preferable server side unit test.
(At least for `static` method but also for the places which uses `static` method where possible).

---

*[flow-server/src/main/java/com/vaadin/flow/router/Router.java, line 457 at r2](https://reviewable.io/reviews/vaadin/flow/4104#-LCXgpZs-JoJZwA6-ydA:-LCYPVj_1VgM51qvf5xb:b-qbn2vc) ([raw file](https://github.com/vaadin/flow/blob/0193b6630577e96a3baf69b2e0b3b09e7ff57d49/flow-server/src/main/java/com/vaadin/flow/router/Router.java#L457)):*
<details><summary><i>Previously, mstahv (Matti Tahvonen) wrote…</i></summary><blockquote>

So let's leave this as it is? Should I click some button to resolve this :-)
</blockquote></details>

The comment may be blocking ( by default) or not blocking.
I unblocked the comment so you may ignore this.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4104)*

**Comment by mstahv** [comment]
I think this is now ready.

**Comment by mstahv** [comment]
I actually added only server side integration tests. Should maybe replicate the same for the static resolve method as well.

**Comment by mstahv** [comment]
Now there is also unit tests for the static helper method

**Comment by denis-anisimov** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4104#-:-LCb_4UrCHcHo2H0JRC7:bnfp4nl)*

**Pull request merged**
