### PR TITLE
Add integration test modules for Spring

### LINKED ISSUE #457: Spring Integration Test
The Spring-addon will be in its own repository, but there should be an integration test module for Flow & Spring-addon in the `vaadin/flow´ project. 

This is blocked until we have an actual Spring add-on.

### PR DESCRIPTION
**Pull request by denis-anisimov**
Two modules: tests for web app as a Spring boot app and as a deployable
WAR

Fixes #457

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/2588)

### CODE REVIEW

**Comment by ZheSun88** [comment]
:lgtm:

---

Review status: 0 of 11 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2588#-:-KvXLlvXyxjtFhtm-xuE:bnfp4nl)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[flow-tests/test-spring-boot/pom.xml, line 109 at r1](https://reviewable.io:443/reviews/vaadin/flow/2588#-KvXwt3HIqzZo-VBM6OH:-KvXwt3HIqzZo-VBM6OI:b5rau9l) ([raw file](https://github.com/vaadin/flow/blob/f6faefde6fbc8cfb728afb28a9c4cf078ce7da70/flow-tests/test-spring-boot/pom.xml#L109)):*
> ```XML
>                         <fileset>
>                             <directory>
>                                 ${frontend.working.directory}/bower_components
> ```

Do you have that folder in the project? What about other frontend folders?

---

*[flow-tests/test-spring-boot/src/main/frontend/empty.txt, line 1 at r1](https://reviewable.io:443/reviews/vaadin/flow/2588#-KvXwDg5APW08JYJoRxJ:-KvXwDg5APW08JYJoRxK:b-9ngof1) ([raw file](https://github.com/vaadin/flow/blob/f6faefde6fbc8cfb728afb28a9c4cf078ce7da70/flow-tests/test-spring-boot/src/main/frontend/empty.txt#L1)):*
> ```
> Empty file here to ensure the directory is created, since it's needed by the default Jetty configuration.
> ```

`src/main/frontend` does not look like a **default** configuration path to me.
Since you don't use it, please remove the files and configure the Jetty properly.

I suspect that the other empty directory is not necessary either.

---

*[flow-tests/test-spring-war/pom.xml, line 17 at r1](https://reviewable.io:443/reviews/vaadin/flow/2588#-KvXvCPBiW7jYhQNmtxm:-KvXvCPBiW7jYhQNmtxn:b-w7u1bt) ([raw file](https://github.com/vaadin/flow/blob/f6faefde6fbc8cfb728afb28a9c4cf078ce7da70/flow-tests/test-spring-war/pom.xml#L17)):*
> ```XML
>         <skip.npm>true</skip.npm>
>         <skip.bower>true</skip.bower>
>         <spring-boot.version>1.5.7.RELEASE</spring-boot.version>
> ```

You repeat that version number twice at least.
Will we be using different Spring Boot versions in the project? 
If not, we can simply put it into the root pom.xml

---

*[flow-tests/test-spring-war/src/main/java/com/vaadin/flow/spring/war/TestSpringServlet.java, line 29 at r1](https://reviewable.io:443/reviews/vaadin/flow/2588#-KvXxe6ZZkafYSNrrzbP:-KvXxe6ZZkafYSNrrzbQ:bq30lro) ([raw file](https://github.com/vaadin/flow/blob/f6faefde6fbc8cfb728afb28a9c4cf078ce7da70/flow-tests/test-spring-war/src/main/java/com/vaadin/flow/spring/war/TestSpringServlet.java#L29)):*
> ```Java
>  *
>  */
> @WebServlet(asyncSupported = true, urlPatterns = { "/*" })
> ```

I see that both modules are very alike: same servlets, almost identical pom.xml files.
Is there a possibility to make it with less duplications? For instance, we can create a common parent spring module with common settings and inherit it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2588)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[flow-tests/test-spring-boot/pom.xml, line 109 at r1](https://reviewable.io:443/reviews/vaadin/flow/2588#-KvXwt3HIqzZo-VBM6OH:-KvY0TG9E-SO1veB_pUB:b-iol0v7) ([raw file](https://github.com/vaadin/flow/blob/f6faefde6fbc8cfb728afb28a9c4cf078ce7da70/flow-tests/test-spring-boot/pom.xml#L109)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Do you have that folder in the project? What about other frontend folders?
</blockquote></details>

This is the basis of the integration test project.
I don't know yet what's needed and what's not.
It will be evolving and it's going to happen immediately (but it looks like it won't).

There will be no jetty at all here because it's a Spring Boot application.
It will be run as a Java application. 
I will correct it later on once I start to use it.

I need this patch to proceed my work.
I have several questions:
- Are you aware that you are blocking me to work further?
- Are you aware that I will not be able to work further because you are in the different time zone and I will not be able to do _anything_ tomorrow because of that?
- I thought we have two sub-teams now. And the team which is responsible for this functionality and is able to review and resolve all the issues is in the same timezone. So does it make sense to review and block our team ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2588)*

**Comment by SomeoneToIgnore** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-tests/test-spring-boot/pom.xml, line 109 at r1](https://reviewable.io:443/reviews/vaadin/flow/2588#-KvXwt3HIqzZo-VBM6OH:-KvYfcl4_5iF4V5pt7rF:b-i09pc7) ([raw file](https://github.com/vaadin/flow/blob/f6faefde6fbc8cfb728afb28a9c4cf078ce7da70/flow-tests/test-spring-boot/pom.xml#L109)):*
> I don't know yet what's needed and what's not.
> There will be no jetty at all here because it's a Spring Boot application.

Please, pick one. Since you don't need Jetty also means that you don't need stubs, so I still don't understand why do 
you use Jetty now.

> Are you aware that you are blocking me to work further?
> Are you aware that I will not be able to work further because you are in the different time zone and I will not be able to do anything tomorrow because of that?

I sense lies and unnecessary drama here.
You can easily remove me from all the discussions with two clicks, any time you want to.
You can also use git branches to fulfill your job as long as you can.
Instead you've picked the most suboptimal path to resolve this for some reason, which is not problem.

> I thought we have two sub-teams now. And the team which is responsible for this functionality and is able to review and resolve all the issues is in the same timezone. So does it make sense to review and block our team 

I did not know that, sorry. You're free to do whatever you like, just think, please.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2588)*

**Pull request merged**
