### PR TITLE
Implement dynamic route titles

### LINKED ISSUE #2397: Dynamic route titles
For a navigation target that implements `HasDynamicTitle`, its `getTitle` method is run after delivering `BeforeNavigationEvent` to get the title to use when navigation to that view.

It is not legal for a class to both implement `HasDynamicTitle` and have a `@Title` annotation, which should be detected at initialization phase.

```
@Route("blog")
public void BlogPage extends Div  implements HasUrlParameter<String>, HasDynamicTitle {
  @Override
  public void setParameter(BeforeNavigationEvent event, String id) {
    showPost(BlogService.get().findPost(id));
  }

  @Override
  public String getTitle() {
    return getCurrentPost().getTitle();
  }
}
```

### PR DESCRIPTION
**Pull request by torok-peter**
Plus
* Add a missing `@Test` annotation
* Add a comment to explain an unclear code part

Fixes #2397 

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/2590)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 5 of 8 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[flow-server/src/main/java/com/vaadin/router/NavigationStateRenderer.java, line 251 at r2](https://reviewable.io:443/reviews/vaadin/flow/2590#-KvbSzoQ514VEPCJl__G:-KvbSzoQ514VEPCJl__H:b-i2dz8r) ([raw file](https://github.com/vaadin/flow/blob/2f066d7526b530270a5a77da42788c24c7ba87bf/flow-server/src/main/java/com/vaadin/router/NavigationStateRenderer.java#L251)):*
> if (routeTarget instanceof HasDynamicTitle) {
>             title = ((HasDynamicTitle) routeTarget).getTitle();
>         } else {


I think the requirement in javadoc of `HasDynamicTitle` should be forced here:
throw a runtime exception if routerTarget implements `HasDynamicTitle` and has `HasTitle` annotation.

---

*[flow-server/src/main/java/com/vaadin/router/NavigationStateRenderer.java, line 254 at r2](https://reviewable.io:443/reviews/vaadin/flow/2590#-KvbTI2mm87v0b6JrH0J:-KvbTI2mm87v0b6JrH0K:b-2p6wf4) ([raw file](https://github.com/vaadin/flow/blob/2f066d7526b530270a5a77da42788c24c7ba87bf/flow-server/src/main/java/com/vaadin/router/NavigationStateRenderer.java#L254)):*
> lookForTitleInParents(routeLayoutTypes)

Isn't `HasTitle` annotation inherited ?
In this case `getAnnotation` method should return annotation from some parent class even if it's not directly in the class itself.
Please revisit.

Also there is  `AnnotationReader`  class which contains utility methods for reading annotation and it seems even read title methods.

---

*[flow-server/src/main/java/com/vaadin/server/startup/RouteRegistryInitializer.java, line 72 at r2](https://reviewable.io:443/reviews/vaadin/flow/2590#-KvbU8593gtcoaU8Yz5M:-KvbU85AyRI4ymS7O7kU:bpfpl8x) ([raw file](https://github.com/vaadin/flow/blob/2f066d7526b530270a5a77da42788c24c7ba87bf/flow-server/src/main/java/com/vaadin/server/startup/RouteRegistryInitializer.java#L72)):*
> route.isAnnotationPresent(Title.class)

It might me that another method should be used for inherited annotations.

By the way what about situation: class has `HasTitle`  and its parent has `HasDynamicTitle`(especially if the annotation is inherited).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2590)*

**Comment by caalador** [comment]
Review status: 8 of 9 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[flow-documentation/routing/tutorial-routing-page-titles.asciidoc, line 41 at r3](https://reviewable.io:443/reviews/vaadin/flow/2590#-KvetWaPQK3ZNOJHqb6D:-KvetWaPQK3ZNOJHqb6E:bqyrobw) ([raw file](https://github.com/vaadin/flow/blob/16c3b62746a17200431424774ec04274bdcaeae3/flow-documentation/routing/tutorial-routing-page-titles.asciidoc#L41)):*
> ```AsciiDoc
> Implementing the interface `HasDynamicTitle` allows us to change the title
> from Java at runtime:
> [source,java]
> ```

all source parts need to also be added to a java class. in this case to `com.vaadin.flow.tutorial.routing.RoutingViewTitles`

---

*[flow-server/src/main/java/com/vaadin/router/NavigationStateRenderer.java, line 254 at r2](https://reviewable.io:443/reviews/vaadin/flow/2590#-KvbTI2mm87v0b6JrH0J:-Kves4rtiHGxJ9fVRoZU:bfja96q) ([raw file](https://github.com/vaadin/flow/blob/2f066d7526b530270a5a77da42788c24c7ba87bf/flow-server/src/main/java/com/vaadin/router/NavigationStateRenderer.java#L254)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> lookForTitleInParents(routeLayoutTypes)

Isn't `HasTitle` annotation inherited ?
In this case `getAnnotation` method should return annotation from some parent class even if it's not directly in the class itself.
Please revisit.

Also there is  `AnnotationReader`  class which contains utility methods for reading annotation and it seems even read title methods.
</blockquote></details>

Title should only be taken from the activated navigation target and parents should not be taken into account.

When section titles is implemented then the title for the activated navigation target is sent to all parent layouts so that they may update or replace the title.

---

*[flow-server/src/main/java/com/vaadin/server/startup/RouteRegistryInitializer.java, line 72 at r2](https://reviewable.io:443/reviews/vaadin/flow/2590#-KvbU8593gtcoaU8Yz5M:-KvessYbXtL5gUWtIpRW:b-uhqpdl) ([raw file](https://github.com/vaadin/flow/blob/2f066d7526b530270a5a77da42788c24c7ba87bf/flow-server/src/main/java/com/vaadin/server/startup/RouteRegistryInitializer.java#L72)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> route.isAnnotationPresent(Title.class)

It might me that another method should be used for inherited annotations.

By the way what about situation: class has `HasTitle`  and its parent has `HasDynamicTitle`(especially if the annotation is inherited).
</blockquote></details>

As replied above, parent layout title information should not be considered in any way for this as it's only a restriction for the route target.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2590)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[flow-server/src/main/java/com/vaadin/router/NavigationStateRenderer.java, line 254 at r2](https://reviewable.io:443/reviews/vaadin/flow/2590#-KvbTI2mm87v0b6JrH0J:-Kvf12i0dsAW46vvsBIY:b-l45xfv) ([raw file](https://github.com/vaadin/flow/blob/2f066d7526b530270a5a77da42788c24c7ba87bf/flow-server/src/main/java/com/vaadin/router/NavigationStateRenderer.java#L254)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Title should only be taken from the activated navigation target and parents should not be taken into account.

When section titles is implemented then the title for the activated navigation target is sent to all parent layouts so that they may update or replace the title.

</blockquote></details>

Oh, I misread the code, my bad.
I thought it introspect the Java hierarchy .
But yeah, it introspects the Component hierarchy.
Then my comments has no sense.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2590)*

**Comment by torok-peter** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[flow-server/src/main/java/com/vaadin/router/NavigationStateRenderer.java, line 251 at r2](https://reviewable.io:443/reviews/vaadin/flow/2590#-KvbSzoQ514VEPCJl__G:-KvbfJ9p-acW-GuZ85Ed:baa6w6o) ([raw file](https://github.com/vaadin/flow/blob/2f066d7526b530270a5a77da42788c24c7ba87bf/flow-server/src/main/java/com/vaadin/router/NavigationStateRenderer.java#L251)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> if (routeTarget instanceof HasDynamicTitle) {
>             title = ((HasDynamicTitle) routeTarget).getTitle();
>         } else {


I think the requirement in javadoc of `HasDynamicTitle` should be forced here:
throw a runtime exception if routerTarget implements `HasDynamicTitle` and has `HasTitle` annotation.
</blockquote></details>

It is already enforced at startup time, in `RouteRegistryInitializer.checkForConflictingAnnotations()`.

---

*[flow-server/src/main/java/com/vaadin/server/startup/RouteRegistryInitializer.java, line 72 at r2](https://reviewable.io:443/reviews/vaadin/flow/2590#-KvbU8593gtcoaU8Yz5M:-Kvbfvr_lvl-brmGJEQr:be6sdjn) ([raw file](https://github.com/vaadin/flow/blob/2f066d7526b530270a5a77da42788c24c7ba87bf/flow-server/src/main/java/com/vaadin/server/startup/RouteRegistryInitializer.java#L72)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

As replied above, parent layout title information should not be considered in any way for this as it's only a restriction for the route target.
</blockquote></details>

Hmmm... good point!

Added a test case for it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2590)*

**Comment by torok-peter** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[flow-documentation/routing/tutorial-routing-page-titles.asciidoc, line 41 at r3](https://reviewable.io:443/reviews/vaadin/flow/2590#-KvetWaPQK3ZNOJHqb6D:-KvfALh4PWrDDmJMMqhQ:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/16c3b62746a17200431424774ec04274bdcaeae3/flow-documentation/routing/tutorial-routing-page-titles.asciidoc#L41)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

all source parts need to also be added to a java class. in this case to `com.vaadin.flow.tutorial.routing.RoutingViewTitles`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2590)*

**Comment by caalador** [comment]
Reviewed 2 of 3 files at r4.
Review status: 9 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-server/src/test/java/com/vaadin/router/RouterTest.java, line 467 at r4](https://reviewable.io:443/reviews/vaadin/flow/2590#-KvfK7wTQJFYTO9mPpT3:-KvfK7wVojSskV3pJYM3:br65noy) ([raw file](https://github.com/vaadin/flow/blob/3a7699bf9c77bc3907d54e99c89d9cd8c86398ab/flow-server/src/test/java/com/vaadin/router/RouterTest.java#L467)):*
> ```Java
> 
>     @Test
>     public void page_title_set_from_annotation_in_parent()
> ```

This should not set the title. Only title from the routeTarget is to be used.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2590)*

**Comment by torok-peter** [comment]
Review status: 9 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-server/src/test/java/com/vaadin/router/RouterTest.java, line 467 at r4](https://reviewable.io:443/reviews/vaadin/flow/2590#-KvfK7wTQJFYTO9mPpT3:-KvfOYl9Oe_qYeEwmhPl:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/3a7699bf9c77bc3907d54e99c89d9cd8c86398ab/flow-server/src/test/java/com/vaadin/router/RouterTest.java#L467)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

This should not set the title. Only title from the routeTarget is to be used.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2590)*

**Comment by caalador** [comment]
Reviewed 1 of 3 files at r4, 3 of 3 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2590)*

**Comment by caalador** [comment]
Code needs fixes after merging master.

**Comment by caalador** [comment]
Reviewed 1 of 1 files at r6, 2 of 2 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2590)*

**Pull request merged**
