### PR TITLE
fix: remove natural order sorting of jsmodules and javascript imports (#16820)(CP: 24.0)

### PR DESCRIPTION
**Pull request by tltv**

### CODE REVIEW

**Comment by Artur-** [comment]
Is there a big need to bring this to 24.0?

**Comment by tltv** [comment]
> Is there a big need to bring this to 24.0?

Not any urgent need.

**Comment by Artur-** [comment]
Then I would leave it for 24.1

**Comment by mshabarov** [comment]
The bug for this fix was reported by author who uses V23.3. If it would take reasonable efforts I'd maybe try to backport it to 23 and 24.0.

**Comment by mshabarov** [comment]
Let's close this pull request and skip the back-porting unless this turns into a severe issue for someone.

**Pull request closed without merging**
