### PR TITLE
Read push settings from the same place as viewport settings

### PR DESCRIPTION
**Pull request by Legioth**
Read push settings from the same place as viewport settings

* Simplify finding of page configuration annotations 
* Set the router immediately when the session is available to be able to
apply push settings before UI.init.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3484)

### CODE REVIEW

**Comment by pleku** [comment]
Review status: 0 of 15 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3484#-L4ZzZoxylF0hRljwYld:-L4ZzZoxylF0hRljwYle:b-5maj6j) (no related file):*
Thanks. Don't forget to update the docs https://github.com/vaadin/flow-and-components-documentation please

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3484)*

**Comment by caalador** [comment]
Reviewed 13 of 17 files at r1.
Review status: 11 of 15 files reviewed at latest revision, 5 unresolved discussions, some commit checks broke.

---

*[flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java, line 160 at r1](https://reviewable.io:443/reviews/vaadin/flow/3484#-L4_Ju-xnxYuUmj-pDzD:-L4_Ju-yy_4kjGNedC9E:b-r0whfr) ([raw file](https://github.com/vaadin/flow/blob/26160503be127d784352b609c768be7c6537258c/flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java#L160)):*
> ```Java
>         }
> 
>         private static Class<?> resolvePageConfigurationHolder(UI ui,
> ```

Fully break out context to its own class. now you moved code from utils to handler when they were in utils so that handler wouldn't be so bloated and messy.

---

*[flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java, line 1213 at r1](https://reviewable.io:443/reviews/vaadin/flow/3484#-L4_Kd-st27oc1Z0iYgG:-L4_Kd-st27oc1Z0iYgH:b-3z3rrw) ([raw file](https://github.com/vaadin/flow/blob/26160503be127d784352b609c768be7c6537258c/flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java#L1213)):*
> ```Java
>                         "In development mode, es5 prefix should be equal to '%s' parameter value",
>                         Constants.FRONTEND_URL_ES5),
>                 urlES5, is(es5Prefix + urlPart));
> ```

what's up with the formatter?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3484)*

**Comment by Legioth** [comment]
Review status: 11 of 15 files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---

*[flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java, line 160 at r1](https://reviewable.io:443/reviews/vaadin/flow/3484#-L4_Ju-xnxYuUmj-pDzD:-L4c32bnSgp4ipvMQAkh:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/26160503be127d784352b609c768be7c6537258c/flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java#L160)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Fully break out context to its own class. now you moved code from utils to handler when they were in utils so that handler wouldn't be so bloated and messy.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3484)*

**Comment by caalador** [comment]
Reviewed 2 of 17 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3484)*

**Comment by caalador** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3484#-L4okAUnO-doi33nVxgF:-L4okAUnO-doi33nVxgG:b1dcpf0) (no related file):*
Should this mean that `@Push` is also validated on correct location and `UI` becomes a valid location also for 

---

*[flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java, line 990 at r2](https://reviewable.io:443/reviews/vaadin/flow/3484#-L4ol8KprB7gr-PsiquA:-L4ol8KprB7gr-PsiquB:b9mh3ul) ([raw file](https://github.com/vaadin/flow/blob/2a3f79dc2000623bb38b877396304cb3b5a04373/flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java#L990)):*
> ```Java
> 
>         PushMode pushMode = push.map(Push::value).orElseGet(context.getSession()
>                 .getService().getDeploymentConfiguration()::getPushMode);
> ```

Does this actually work with `@Push` on the `UI` class as the getPageConfigurationAnnotation stops at the top most Route parent which means UI won't be considered?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3484)*

**Comment by caalador** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3484#-L4okAUnO-doi33nVxgF:-L4oljHwHp-3YezYTWyu:bnv8qe0) (no related file):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Should this mean that `@Push` is also validated on correct location and `UI` becomes a valid location also for 
</blockquote></details>

`Viewport`, `BodySize`, `Inline`, `Theme`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3484)*

**Comment by caalador** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java, line 990 at r2](https://reviewable.io:443/reviews/vaadin/flow/3484#-L4ol8KprB7gr-PsiquA:-L4om7YTFPRGc7ptzu1Y:b-lr9l28) ([raw file](https://github.com/vaadin/flow/blob/2a3f79dc2000623bb38b877396304cb3b5a04373/flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java#L990)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Does this actually work with `@Push` on the `UI` class as the getPageConfigurationAnnotation stops at the top most Route parent which means UI won't be considered?
</blockquote></details>

I noted that the tests are rigged to work with the annotation on the wrong position. 
This might be quite confusing later on.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3484)*

**Comment by Legioth** [comment]
Review status: 10 of 19 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3484#-L4okAUnO-doi33nVxgF:-L5iIEX6A3woxpJxEizM:bb6un1j) (no related file):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

`Viewport`, `BodySize`, `Inline`, `Theme`
</blockquote></details>

Done

---

*[flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java, line 990 at r2](https://reviewable.io:443/reviews/vaadin/flow/3484#-L4ol8KprB7gr-PsiquA:-L5iI5j-uqjENPzcmm7L:bxxn72h) ([raw file](https://github.com/vaadin/flow/blob/2a3f79dc2000623bb38b877396304cb3b5a04373/flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java#L990)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

I noted that the tests are rigged to work with the annotation on the wrong position. 
This might be quite confusing later on.
</blockquote></details>

Added clarifying comments in all test UIs where `@Push` is used in a non-conventional location.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3484)*

**Comment by caalador** [comment]
Reviewed 9 of 9 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3484)*

**Comment by caalador** [comment]
This one is ok, but waiting for the PR for documentation changes.

**Comment by Legioth** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3484#-L4ZzZoxylF0hRljwYld:-L5soTVveYtKwCG4mNQz:b-kt2yc1) (no related file):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Thanks. Don't forget to update the docs https://github.com/vaadin/flow-and-components-documentation please
</blockquote></details>

Documentation in https://github.com/vaadin/flow-and-components-documentation/pull/20

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3484)*

**Pull request merged**
