### PR TITLE
move component it to test util

### PR DESCRIPTION
**Pull request by ZheSun88**
the component IT tests will be moved to its own repo and the
flow-component-test module will be abandoned finally, some common files
are moving to test util. necessary dependencies have been added inside
pom file.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3063)

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3063)*

**Comment by SomeoneToIgnore** [comment]
*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3063#-L-0cUyQH39av0_qPYmP:-L-0cUyQH39av0_qPYmQ:b3kg39b) (no related file):*
If you plan to modify the module further, I suggest you to add 
`<sonar.skip>true</sonar.skip>` into `properties` tag of the module's `pom.xml`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3063)*

**Comment by ZheSun88** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks broke.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3063#-L-0cUyQH39av0_qPYmP:-L-0ctcuugtX_utlFexD:bwccxmx) (no related file):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

If you plan to modify the module further, I suggest you to add 
`<sonar.skip>true</sonar.skip>` into `properties` tag of the module's `pom.xml`
</blockquote></details>

got it. thanks Kirill.. i will do it now..

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3063)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3063)*

**Pull request merged**
