### PR TITLE
Navigation exception handling.

### LINKED ISSUE #2346: Router Error Handling
Errors are tricked by:
1) If no matching route is found in the resolve phase
2) If an exception is thrown by any part of the process
3) If Errors can be triggered programmatically through `BeforeNavigationEvent::reRouteToError(Exception)` (#2356, not part of this ticket!)

On error, a navigation state with an error handler is activated, as any other navigation, but now with the error state, instead of the original state that was never fully activated. To avoid infinite loops, exceptions during activation of a an error state may be caught and logged without triggering yet another navigation state, and just trigger a 500 error response.

There is special support for navigation targets that are activated to show an error message to the user. These targets generally work in the same way as regular navigation targets, although they do typically not have any specific `@Route` since they are show for arbitrary URLs. But keep in mind that the error handler can specify a parent layout for itself.

Error navigation targets are resolved based on an exception type. There's built-in support for two exception types that are used as a fallbacks if the application doesn't define any custom handlers:
1) `com.vaadin.flow.router.NotFoundException` that corresponds to a HTTP _404_ status code. `BeforeNavigationEvent::rerouteToError(...)` has a shorthand for rerouting with this specific exception type.
2) `java.lang.Exception` that corresponds to a HTTP _500_ status code.

The error navigation targets implement the following interface:
```java
interface HasErrorParameter<T extends Exception> {
  void setErrorParameter(BeforeNavigationEvent event, ErrorParameter<T> errorParameter);
}
```
`ErrorParameter` contains an optional error message and an optional exception instance. The method returns the HTTP status code that should be used in the HTTP response if the navigation was triggered by bootstrapping a page.

For now, the handlers are on global level. Matching exception types to handlers:
1) Match for a specific exception to that handler (without inheritance or clauses)
2) Anything that not matched in 1), should be matched to a handler for `java.lang.Exception`.

Handlers are registered during initialization phase with scanning. If multiple handlers for the same exception are discovered, throw errors.
 
Should add documentation on this and take it into use in the new demo for new router.

Waits for #2343.

### PR DESCRIPTION
**Pull request by caalador**
Handle exceptions when navigating.

Fixes #2346

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/2639)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 17 of 17 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2639#-Kw-aon-xRsrPtr2ogGW:-Kw-aon-xRsrPtr2ogGX:brp18ac) (no related file):*

Don't see tests for `HasErrorParameter` annotation (and views annotated with it).
Only predefined error views are tested.

---

*[flow-documentation/routing/tutorial-routing-exception-handling.asciidoc, line 41 at r1](https://reviewable.io:443/reviews/vaadin/flow/2639#-Kw-XqSZTAuiepE9sWuJ:-Kw-XqSZTAuiepE9sWuK:b-hvc8ry) ([raw file](https://github.com/vaadin/flow/blob/823ceab359de5f7d9ca625b98ec476d4bb4b2ff1/flow-documentation/routing/tutorial-routing-exception-handling.asciidoc#L41)):*
> a

nit: an

---

*[flow-server/src/main/java/com/vaadin/router/ErrorStateRenderer.java, line 110 at r1](https://reviewable.io:443/reviews/vaadin/flow/2639#-Kw-YaKeXT6eHAA2PupK:-Kw-YaKeXT6eHAA2PupL:b-egnaeh) ([raw file](https://github.com/vaadin/flow/blob/823ceab359de5f7d9ca625b98ec476d4bb4b2ff1/flow-server/src/main/java/com/vaadin/router/ErrorStateRenderer.java#L110)):*
> int i

what's `i` ?

---

*[flow-server/src/main/java/com/vaadin/router/HasErrorParameter.java, line 21 at r1](https://reviewable.io:443/reviews/vaadin/flow/2639#-Kw-YmdzlFrCKkBvxWll:-Kw-YmdzlFrCKkBvxWlm:bk2e8c7) ([raw file](https://github.com/vaadin/flow/blob/823ceab359de5f7d9ca625b98ec476d4bb4b2ff1/flow-server/src/main/java/com/vaadin/router/HasErrorParameter.java#L21)):*
> the an

the or an ?

---

*[flow-server/src/main/java/com/vaadin/router/event/NavigationEvent.java, line 102 at r1](https://reviewable.io:443/reviews/vaadin/flow/2639#-Kw-Z_INKnaOqhbnbXP3:-Kw-Z_INKnaOqhbnbXP4:b-mzg36w) ([raw file](https://github.com/vaadin/flow/blob/823ceab359de5f7d9ca625b98ec476d4bb4b2ff1/flow-server/src/main/java/com/vaadin/router/event/NavigationEvent.java#L102)):*
> public ErrorParameter getErrorParameter() 

Looks like it's used only in special cases.
Wouldn't it be better to subclass `NavigationEvent` and use it there ? (and may be not as a setter but as a CTOR parameter)

---

*[flow-server/src/main/java/com/vaadin/server/startup/RouteRegistry.java, line 137 at r1](https://reviewable.io:443/reviews/vaadin/flow/2639#-Kw-_832rzhDp4gqgcA-:-Kw-_832rzhDp4gqgcA0:b-m23lir) ([raw file](https://github.com/vaadin/flow/blob/823ceab359de5f7d9ca625b98ec476d4bb4b2ff1/flow-server/src/main/java/com/vaadin/server/startup/RouteRegistry.java#L137)):*
> Class

`Class<?>` ?

---

*[flow-server/src/main/java/com/vaadin/server/startup/RouteRegistry.java, line 142 at r1](https://reviewable.io:443/reviews/vaadin/flow/2639#-Kw-_Fh-tcYcZDA_VsXK:-Kw-_Fh-tcYcZDA_VsXL:bita9ny) ([raw file](https://github.com/vaadin/flow/blob/823ceab359de5f7d9ca625b98ec476d4bb4b2ff1/flow-server/src/main/java/com/vaadin/server/startup/RouteRegistry.java#L142)):*
> if (exceptionTargets.containsKey(exceptionType)) {
>                 Class<? extends Component> registered = exceptionTargets
>                         .get(exceptionType);
>                 if (registered.isAssignableFrom(target)) {

It's hard to read (I'm already lost) nested `if` inside `if` inside `for`.

Please refactor.

---

*[flow-server/src/main/java/com/vaadin/server/startup/RouteRegistry.java, line 202 at r1](https://reviewable.io:443/reviews/vaadin/flow/2639#-Kw-_mKIiFf8B2HIR0Ez:-Kw-_mKIiFf8B2HIR0F-:b-ghrgto) ([raw file](https://github.com/vaadin/flow/blob/823ceab359de5f7d9ca625b98ec476d4bb4b2ff1/flow-server/src/main/java/com/vaadin/server/startup/RouteRegistry.java#L202)):*
> exception.getClass().getSuperclass();

I think it requires erasure.

E.g. `List<String>` as a superclass is not the same as `List<T>`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2639)*

**Comment by caalador** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2639#-Kw-aon-xRsrPtr2ogGW:-Kw-cXMEaAd4Dwr1gQd8:b-lkrro8) (no related file):*
> HasErrorParameter
It's not an annotation it's an interface.
RouterTest contains tests for classes implementing HasErrorParameter and ones extending default classes etc.

---

*[flow-documentation/routing/tutorial-routing-exception-handling.asciidoc, line 41 at r1](https://reviewable.io:443/reviews/vaadin/flow/2639#-Kw-XqSZTAuiepE9sWuJ:-Kw-cf_TCXVUmY4i_vaC:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/823ceab359de5f7d9ca625b98ec476d4bb4b2ff1/flow-documentation/routing/tutorial-routing-exception-handling.asciidoc#L41)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> a

nit: an
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/router/ErrorStateRenderer.java, line 110 at r1](https://reviewable.io:443/reviews/vaadin/flow/2639#-Kw-YaKeXT6eHAA2PupK:-Kw-cr_RehH8EDxVSfho:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/823ceab359de5f7d9ca625b98ec476d4bb4b2ff1/flow-server/src/main/java/com/vaadin/router/ErrorStateRenderer.java#L110)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> int i

what's `i` ?
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/router/HasErrorParameter.java, line 21 at r1](https://reviewable.io:443/reviews/vaadin/flow/2639#-Kw-YmdzlFrCKkBvxWll:-Kw-cyg2E7Po1fVRQ6uN:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/823ceab359de5f7d9ca625b98ec476d4bb4b2ff1/flow-server/src/main/java/com/vaadin/router/HasErrorParameter.java#L21)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> the an

the or an ?
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/router/event/NavigationEvent.java, line 102 at r1](https://reviewable.io:443/reviews/vaadin/flow/2639#-Kw-Z_INKnaOqhbnbXP3:-Kw-dkue91yBZrT-sDpR:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/823ceab359de5f7d9ca625b98ec476d4bb4b2ff1/flow-server/src/main/java/com/vaadin/router/event/NavigationEvent.java#L102)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> public ErrorParameter getErrorParameter() 

Looks like it's used only in special cases.
Wouldn't it be better to subclass `NavigationEvent` and use it there ? (and may be not as a setter but as a CTOR parameter)
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/server/startup/RouteRegistry.java, line 137 at r1](https://reviewable.io:443/reviews/vaadin/flow/2639#-Kw-_832rzhDp4gqgcA-:-Kw-eQCSOBt_zCYtBJ77:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/823ceab359de5f7d9ca625b98ec476d4bb4b2ff1/flow-server/src/main/java/com/vaadin/server/startup/RouteRegistry.java#L137)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> Class

`Class<?>` ?
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/server/startup/RouteRegistry.java, line 142 at r1](https://reviewable.io:443/reviews/vaadin/flow/2639#-Kw-_Fh-tcYcZDA_VsXK:-Kw-fKYP5sERKoSF754p:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/823ceab359de5f7d9ca625b98ec476d4bb4b2ff1/flow-server/src/main/java/com/vaadin/server/startup/RouteRegistry.java#L142)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> if (exceptionTargets.containsKey(exceptionType)) {
>                 Class<? extends Component> registered = exceptionTargets
>                         .get(exceptionType);
>                 if (registered.isAssignableFrom(target)) {

It's hard to read (I'm already lost) nested `if` inside `if` inside `for`.

Please refactor.
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/server/startup/RouteRegistry.java, line 202 at r1](https://reviewable.io:443/reviews/vaadin/flow/2639#-Kw-_mKIiFf8B2HIR0Ez:-Kw-fZlqFSdAO5eSXSkG:b6ujwoe) ([raw file](https://github.com/vaadin/flow/blob/823ceab359de5f7d9ca625b98ec476d4bb4b2ff1/flow-server/src/main/java/com/vaadin/server/startup/RouteRegistry.java#L202)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> exception.getClass().getSuperclass();

I think it requires erasure.

E.g. `List<String>` as a superclass is not the same as `List<T>`.
</blockquote></details>

Exceptions can not be generic so it is not a problem.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2639)*

**Comment by denis-anisimov** [comment]
Reviewed 8 of 8 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/router/event/ErrorNavigationEvent.java, line 9 at r3](https://reviewable.io:443/reviews/vaadin/flow/2639#-Kw-lBruDieAWHU9y5oS:-Kw-lBruDieAWHU9y5oT:ba0ex1u) ([raw file](https://github.com/vaadin/flow/blob/fa6b85ca4452eb07f5a0815cf352ee33abe98c19/flow-server/src/main/java/com/vaadin/router/event/ErrorNavigationEvent.java#L9)):*
> public class ErrorNavigationEvent

SQ should complain about javadoc absence for the class.

---

*[flow-server/src/main/java/com/vaadin/server/startup/ErrorNavigationTargetInitializer.java, line 32 at r2](https://reviewable.io:443/reviews/vaadin/flow/2639#-Kw-jIgf-O06v-iimxZg:-Kw-jIgf-O06v-iimxZh:b-2z29wa) ([raw file](https://github.com/vaadin/flow/blob/ceae416d1316d247c6b464151d7ed1fcc20208ff/flow-server/src/main/java/com/vaadin/server/startup/ErrorNavigationTargetInitializer.java#L32)):*
> hndler

typo

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2639)*

**Comment by torok-peter** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[flow-documentation/routing/tutorial-routing-exception-handling.asciidoc, line 14 at r1](https://reviewable.io:443/reviews/vaadin/flow/2639#-Kw-fjJE26ww6a2ZOQgY:-Kw-fjJFwPEHs1Ryrc0E:bpzwyz3) ([raw file](https://github.com/vaadin/flow/blob/823ceab359de5f7d9ca625b98ec476d4bb4b2ff1/flow-documentation/routing/tutorial-routing-exception-handling.asciidoc#L14)):*
> ```AsciiDoc
> There is special support for navigation targets that are activated to show an error message to the user.
> 
> These targets generally work in the same way as regular navigation targets, although they do typically not have any specific `@Route` as they are show for arbitrary URLs.
> ```

s/show/shown/

---

*[flow-documentation/routing/tutorial-routing-exception-handling.asciidoc, line 33 at r1](https://reviewable.io:443/reviews/vaadin/flow/2639#-Kw-gIRl5Wq-TH7saTMG:-Kw-gIRl5Wq-TH7saTMH:b5oqh4p) ([raw file](https://github.com/vaadin/flow/blob/823ceab359de5f7d9ca625b98ec476d4bb4b2ff1/flow-documentation/routing/tutorial-routing-exception-handling.asciidoc#L33)):*
> ```AsciiDoc
>     @Override
>     public int setErrorParameter(BeforeNavigationEvent event,
>             ErrorParameter<NotFoundException> parameter) {
> ```

Would it be useful to add some code to demonstrate the use(s) of `ErrorParameter`, e.g. by showing its custom message?

---

*[flow-documentation/routing/tutorial-routing-exception-handling.asciidoc, line 70 at r1](https://reviewable.io:443/reviews/vaadin/flow/2639#-Kw-gh6Om-ujZRKlOZiK:-Kw-gh6Om-ujZRKlOZiL:bjfoq1g) ([raw file](https://github.com/vaadin/flow/blob/823ceab359de5f7d9ca625b98ec476d4bb4b2ff1/flow-documentation/routing/tutorial-routing-exception-handling.asciidoc#L70)):*
> ```AsciiDoc
> 
> [NOTE]
> One exception may only have one exception handler (only extending instances are allowed)
> ```

Add closing dot.

---

*[flow-server/src/main/java/com/vaadin/router/ErrorParameter.java, line 27 at r1](https://reviewable.io:443/reviews/vaadin/flow/2639#-Kw-jYXbI-kYd04I3Gan:-Kw-jYXbI-kYd04I3Gao:bb2nl6o) ([raw file](https://github.com/vaadin/flow/blob/823ceab359de5f7d9ca625b98ec476d4bb4b2ff1/flow-server/src/main/java/com/vaadin/router/ErrorParameter.java#L27)):*
> ```Java
> 
>     private T exception;
>     private String customMessage;
> ```

Should this be an `Optional<String>`?

---

*[flow-server/src/main/java/com/vaadin/router/ErrorStateRenderer.java, line 46 at r1](https://reviewable.io:443/reviews/vaadin/flow/2639#-Kw-hW7zac1B9yUpJrYl:-Kw-hW7zac1B9yUpJrYm:b23josq) ([raw file](https://github.com/vaadin/flow/blob/823ceab359de5f7d9ca625b98ec476d4bb4b2ff1/flow-server/src/main/java/com/vaadin/router/ErrorStateRenderer.java#L46)):*
> ```Java
> 
>     /**
>      * Constructs a new NavigationStateRenderer that handles the given
> ```

NavigationStateRenderer is incorrect. (IMHO, mentioning the class name here is redunant anyway, and just opens up the possibility for errors like this.)

---

*[flow-server/src/main/java/com/vaadin/router/HasErrorParameter.java, line 30 at r1](https://reviewable.io:443/reviews/vaadin/flow/2639#-Kw-j6vIGh7LbvUfXy9_:-Kw-j6vIGh7LbvUfXy9a:b-a9azmu) ([raw file](https://github.com/vaadin/flow/blob/823ceab359de5f7d9ca625b98ec476d4bb4b2ff1/flow-server/src/main/java/com/vaadin/router/HasErrorParameter.java#L30)):*
> ```Java
> 
>     /**
>      * Method called for the implementing class when corresponding exception has
> ```

*a* corresponding exception

---

*[flow-server/src/main/java/com/vaadin/router/HasErrorParameter.java, line 36 at r1](https://reviewable.io:443/reviews/vaadin/flow/2639#-Kw-jFYvGBZv5ZBN7EvD:-Kw-jFYvGBZv5ZBN7EvE:b-7c1hws) ([raw file](https://github.com/vaadin/flow/blob/823ceab359de5f7d9ca625b98ec476d4bb4b2ff1/flow-server/src/main/java/com/vaadin/router/HasErrorParameter.java#L36)):*
> ```Java
>      *            the before navigation event for this request
>      * @param parameter
>      *            error parameter class containing custom exception and caught
> ```

Is "class" really needed here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2639)*

**Comment by caalador** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[flow-documentation/routing/tutorial-routing-exception-handling.asciidoc, line 14 at r1](https://reviewable.io:443/reviews/vaadin/flow/2639#-Kw-fjJE26ww6a2ZOQgY:-Kw-nXJ3hDgPUOfznUtG:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/823ceab359de5f7d9ca625b98ec476d4bb4b2ff1/flow-documentation/routing/tutorial-routing-exception-handling.asciidoc#L14)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

s/show/shown/
</blockquote></details>

Done.

---

*[flow-documentation/routing/tutorial-routing-exception-handling.asciidoc, line 33 at r1](https://reviewable.io:443/reviews/vaadin/flow/2639#-Kw-gIRl5Wq-TH7saTMG:-Kw-nafyzhrZYFB8T9lx:bqx4wyp) ([raw file](https://github.com/vaadin/flow/blob/823ceab359de5f7d9ca625b98ec476d4bb4b2ff1/flow-documentation/routing/tutorial-routing-exception-handling.asciidoc#L33)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

Would it be useful to add some code to demonstrate the use(s) of `ErrorParameter`, e.g. by showing its custom message?
</blockquote></details>

Probably, but it should be added with: 
`If Errors can be triggered programmatically through BeforeNavigationEvent::reRouteToError(Exception)` #2356
As right now we don't really have any way to give a custom message.

---

*[flow-documentation/routing/tutorial-routing-exception-handling.asciidoc, line 70 at r1](https://reviewable.io:443/reviews/vaadin/flow/2639#-Kw-gh6Om-ujZRKlOZiK:-Kw-nwgVFL9TbQHXrg9J:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/823ceab359de5f7d9ca625b98ec476d4bb4b2ff1/flow-documentation/routing/tutorial-routing-exception-handling.asciidoc#L70)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

Add closing dot.
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/router/ErrorStateRenderer.java, line 46 at r1](https://reviewable.io:443/reviews/vaadin/flow/2639#-Kw-hW7zac1B9yUpJrYl:-Kw-qo-NOBTqiWColjg-:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/823ceab359de5f7d9ca625b98ec476d4bb4b2ff1/flow-server/src/main/java/com/vaadin/router/ErrorStateRenderer.java#L46)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

NavigationStateRenderer is incorrect. (IMHO, mentioning the class name here is redunant anyway, and just opens up the possibility for errors like this.)
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/router/HasErrorParameter.java, line 30 at r1](https://reviewable.io:443/reviews/vaadin/flow/2639#-Kw-j6vIGh7LbvUfXy9_:-Kw-q5qyDQ_zH47ra84M:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/823ceab359de5f7d9ca625b98ec476d4bb4b2ff1/flow-server/src/main/java/com/vaadin/router/HasErrorParameter.java#L30)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

*a* corresponding exception
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/router/HasErrorParameter.java, line 36 at r1](https://reviewable.io:443/reviews/vaadin/flow/2639#-Kw-jFYvGBZv5ZBN7EvD:-Kw-q27bf5jvEnkX1lcg:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/823ceab359de5f7d9ca625b98ec476d4bb4b2ff1/flow-server/src/main/java/com/vaadin/router/HasErrorParameter.java#L36)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

Is "class" really needed here?
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/router/event/ErrorNavigationEvent.java, line 9 at r3](https://reviewable.io:443/reviews/vaadin/flow/2639#-Kw-lBruDieAWHU9y5oS:-Kw-qEibifVKcfCfocQ-:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/fa6b85ca4452eb07f5a0815cf352ee33abe98c19/flow-server/src/main/java/com/vaadin/router/event/ErrorNavigationEvent.java#L9)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> public class ErrorNavigationEvent

SQ should complain about javadoc absence for the class.
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/server/startup/ErrorNavigationTargetInitializer.java, line 32 at r2](https://reviewable.io:443/reviews/vaadin/flow/2639#-Kw-jIgf-O06v-iimxZg:-Kw-qHvDW9fxsHGXyxX-:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/ceae416d1316d247c6b464151d7ed1fcc20208ff/flow-server/src/main/java/com/vaadin/server/startup/ErrorNavigationTargetInitializer.java#L32)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> hndler

typo
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2639)*

**Comment by denis-anisimov** [comment]
Reviewed 7 of 7 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2639)*

**Comment by torok-peter** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/router/ErrorStateRenderer.java, line 46 at r1](https://reviewable.io:443/reviews/vaadin/flow/2639#-Kw-hW7zac1B9yUpJrYl:-Kw0-uEWlyU_W9sOFlsi:blzmen) ([raw file](https://github.com/vaadin/flow/blob/823ceab359de5f7d9ca625b98ec476d4bb4b2ff1/flow-server/src/main/java/com/vaadin/router/ErrorStateRenderer.java#L46)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Doesn't seem so...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2639)*

**Comment by caalador** [comment]
Review status: 17 of 19 files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/router/ErrorStateRenderer.java, line 46 at r1](https://reviewable.io:443/reviews/vaadin/flow/2639#-Kw-hW7zac1B9yUpJrYl:-Kw02lYMSz-yBmhsr2hX:b-axv0u4) ([raw file](https://github.com/vaadin/flow/blob/823ceab359de5f7d9ca625b98ec476d4bb4b2ff1/flow-server/src/main/java/com/vaadin/router/ErrorStateRenderer.java#L46)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

Doesn't seem so...
</blockquote></details>

Oh. I updated the main javadoc.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2639)*

**Comment by torok-peter** [comment]
:lgtm:

---

Review status: 17 of 19 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2639#-:-Kw04Tb0vFM6RJT0UPAe:bnfp4nl)*

**Comment by torok-peter** [comment]
Reviewed 7 of 17 files at r1, 4 of 8 files at r2, 6 of 7 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2639)*

**Comment by denis-anisimov** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2639)*

**Pull request merged**
