### PR TITLE
Support @Viewport on @Route or top RouterLayout.

### PR DESCRIPTION
**Pull request by caalador**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3072)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 12 of 14 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/router/util/RouterUtil.java, line 79 at r2](https://reviewable.io:443/reviews/vaadin/flow/3072#-L-5Mk233ZOm0j77-G6a:-L-5Mk233ZOm0j77-G6b:brvsk8b) ([raw file](https://github.com/vaadin/flow/blob/2c87fcdc03f1df457152343f80f2e855c2cc026b/flow-server/src/main/java/com/vaadin/router/util/RouterUtil.java#L79)):*
> router

`route` actually.

The logic doesn't count `@RouteAlias`. Should it ?
Well the latter annotation should always come with `@Route` so I guess it can be ignored here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3072)*

**Comment by caalador** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[flow-server/src/main/java/com/vaadin/router/util/RouterUtil.java, line 79 at r2](https://reviewable.io:443/reviews/vaadin/flow/3072#-L-5Mk233ZOm0j77-G6a:-L-5PB8eodsQpTfq5kLY:b-g076bg) ([raw file](https://github.com/vaadin/flow/blob/2c87fcdc03f1df457152343f80f2e855c2cc026b/flow-server/src/main/java/com/vaadin/router/util/RouterUtil.java#L79)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> router

`route` actually.

The logic doesn't count `@RouteAlias`. Should it ?
Well the latter annotation should always come with `@Route` so I guess it can be ignored here.
</blockquote></details>

I noted that the `RouteAlias` can have a different parent  than what the `Route` uses and this does impact the functionality.
I need to check that the `RouteAlias` works in the navigator at the same time as it uses the `getParentLayouts` which doesn't take into account that it might use the `RouteAlias` path of building the layout.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3072)*

**Comment by caalador** [comment]
Review status: 8 of 20 files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[flow-server/src/main/java/com/vaadin/router/util/RouterUtil.java, line 79 at r2](https://reviewable.io:443/reviews/vaadin/flow/3072#-L-5Mk233ZOm0j77-G6a:-L-6dlvn3CSvJozMshfC:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/2c87fcdc03f1df457152343f80f2e855c2cc026b/flow-server/src/main/java/com/vaadin/router/util/RouterUtil.java#L79)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

I noted that the `RouteAlias` can have a different parent  than what the `Route` uses and this does impact the functionality.
I need to check that the `RouteAlias` works in the navigator at the same time as it uses the `getParentLayouts` which doesn't take into account that it might use the `RouteAlias` path of building the layout.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3072)*

**Comment by denis-anisimov** [comment]
Reviewed 11 of 12 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/router/util/RouterUtil.java, line 87 at r4](https://reviewable.io:443/reviews/vaadin/flow/3072#-L-AaPBbjKY9dyRgnbq8:-L-AaPBbjKY9dyRgnbq9:b-a6p877) ([raw file](https://github.com/vaadin/flow/blob/f8b2f64ba27dedfe08ad240029221e3f9e992fb7/flow-server/src/main/java/com/vaadin/router/util/RouterUtil.java#L87)):*
> for (RouteAlias alias : routeAliases) {
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>
>                 if (path.equals(alias.value())
>                         && !alias.layout().equals(UI.class)) {
>                     list.addAll(collectRouteParentLayouts(alias.layout()));
>                     break;
>                 }
>             }
</details>


I would recommend to rewrite it using `Stream.filter().findFirst()`because now it's (`if` inside )`for` inside `else`.
Or extract as a separate method.

---

*[flow-server/src/main/java/com/vaadin/router/util/RouterUtil.java, line 151 at r4](https://reviewable.io:443/reviews/vaadin/flow/3072#-L-Ab4opkxzKL6wuz5nf:-L-Ab4opkxzKL6wuz5ng:b5v7pkr) ([raw file](https://github.com/vaadin/flow/blob/f8b2f64ba27dedfe08ad240029221e3f9e992fb7/flow-server/src/main/java/com/vaadin/router/util/RouterUtil.java#L151)):*
> if (route.isPresent() && path.equals(route.get().value())
<details><summary><i alt="summary">Quoted 10 lines of code…</i></summary>
>                 && !route.get().layout().equals(UI.class)) {
>             return recuseToTopLayout(route.get().layout());
>         } else {
>             for (RouteAlias alias : routeAliases) {
>                 if (path.equals(alias.value())
>                         && !alias.layout().equals(UI.class)) {
>                     return recuseToTopLayout(alias.layout());
>                 }
>             }
>         }
</details>

This logic looks very familiar. Can it be reused ? (may be not)
But again: `if` inside `for` inside `else`.

---

*[flow-server/src/main/java/com/vaadin/server/startup/AbstractRouteRegistryInitializer.java, line 114 at r4](https://reviewable.io:443/reviews/vaadin/flow/3072#-L-AbbpPX7ip14xCX7OU:-L-AbbpPX7ip14xCX7OV:b-g1e9im) ([raw file](https://github.com/vaadin/flow/blob/f8b2f64ba27dedfe08ad240029221e3f9e992fb7/flow-server/src/main/java/com/vaadin/server/startup/AbstractRouteRegistryInitializer.java#L114)):*
> for (RouteAlias alias : route.getAnnotationsByType(RouteAlias.class)) {
<details><summary><i alt="summary">Quoted 12 lines of code…</i></summary>
>             if (route.isAnnotationPresent(Viewport.class)
>                     && !UI.class.equals(alias.layout())) {
>                 throw new InvalidRouteLayoutConfigurationException(String
>                         .format("Viewport annotation needs to be on the top parent layout '%s' not on '%s'",
>                                 RouterUtil.getTopParentLayout(route,
>                                         alias.value()).getName(),
>                                 route.getName()));
>             }
>             List<Class<? extends RouterLayout>> parentLayouts = RouterUtil
>                     .getParentLayouts(route, alias.value());
>             Class<? extends RouterLayout> topParentLayout = RouterUtil
>                     .getTopParentLayout(route, alias.value());
</details>
>  
>             validateParentViewport(parentLayouts, topParentLayout);
>         }


Looks like a separate method.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3072)*

**Comment by caalador** [comment]
Review status: 17 of 20 files reviewed at latest revision, 3 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/router/util/RouterUtil.java, line 87 at r4](https://reviewable.io:443/reviews/vaadin/flow/3072#-L-AaPBbjKY9dyRgnbq8:-L-Aoee2SxbcuAOYEnpk:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/f8b2f64ba27dedfe08ad240029221e3f9e992fb7/flow-server/src/main/java/com/vaadin/router/util/RouterUtil.java#L87)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> for (RouteAlias alias : routeAliases) {
>                 if (path.equals(alias.value())
>                         && !alias.layout().equals(UI.class)) {
>                     list.addAll(collectRouteParentLayouts(alias.layout()));
>                     break;
>                 }
>             }


I would recommend to rewrite it using `Stream.filter().findFirst()`because now it's (`if` inside )`for` inside `else`.
Or extract as a separate method.
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/router/util/RouterUtil.java, line 151 at r4](https://reviewable.io:443/reviews/vaadin/flow/3072#-L-Ab4opkxzKL6wuz5nf:-L-ApOEnp09aeVjWLSX0:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/f8b2f64ba27dedfe08ad240029221e3f9e992fb7/flow-server/src/main/java/com/vaadin/router/util/RouterUtil.java#L151)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> if (route.isPresent() && path.equals(route.get().value())
>                 && !route.get().layout().equals(UI.class)) {
>             return recuseToTopLayout(route.get().layout());
>         } else {
>             for (RouteAlias alias : routeAliases) {
>                 if (path.equals(alias.value())
>                         && !alias.layout().equals(UI.class)) {
>                     return recuseToTopLayout(alias.layout());
>                 }
>             }
>         }

This logic looks very familiar. Can it be reused ? (may be not)
But again: `if` inside `for` inside `else`.
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/server/startup/AbstractRouteRegistryInitializer.java, line 114 at r4](https://reviewable.io:443/reviews/vaadin/flow/3072#-L-AbbpPX7ip14xCX7OU:-L-Aqj5vzbv6aySbsqjx:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/f8b2f64ba27dedfe08ad240029221e3f9e992fb7/flow-server/src/main/java/com/vaadin/server/startup/AbstractRouteRegistryInitializer.java#L114)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> for (RouteAlias alias : route.getAnnotationsByType(RouteAlias.class)) {
>             if (route.isAnnotationPresent(Viewport.class)
>                     && !UI.class.equals(alias.layout())) {
>                 throw new InvalidRouteLayoutConfigurationException(String
>                         .format("Viewport annotation needs to be on the top parent layout '%s' not on '%s'",
>                                 RouterUtil.getTopParentLayout(route,
>                                         alias.value()).getName(),
>                                 route.getName()));
>             }
>             List<Class<? extends RouterLayout>> parentLayouts = RouterUtil
>                     .getParentLayouts(route, alias.value());
>             Class<? extends RouterLayout> topParentLayout = RouterUtil
>                     .getTopParentLayout(route, alias.value());
>  
>             validateParentViewport(parentLayouts, topParentLayout);
>         }


Looks like a separate method.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3072)*

**Comment by denis-anisimov** [comment]
Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3072)*

**Pull request merged**
