### PR TITLE
Add basic html5 elements to flow

### PR DESCRIPTION
**Pull request by knoobie**
Adds the following html5 elements to the component collection of flow:

- article
- aside
- footer
- header
- main
- nav
- section

Discussion/Question: Do you want me to add the specific role attributes for the components as well or should this be a task for the user/developer? 

For example:

```
<nav>       should be         <nav role="navigation">
<main>      should be         <main role="main">
```

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3188)

### CODE REVIEW

**Comment by Legioth** [comment]
> Discussion/Question: Do you want me to add the specific role attributes for the components as well or should this be a task for the user/developer?

Without any detailed analysis, I think it would be great to have API for setting those attributes since it would encourage using the HTML elements in the way they are intended to be used.

**Comment by knoobie** [comment]
@Legioth do you prefer this API redundant in each of the new elements or should / can I add something like this to HTMLContainer? We could also make `role` an enum. 


     roleDescriptor =  PropertyDescriptors.optionalAttributeWithDefault("role", "");

     public XXX(String role) {
        setRole(role);
     }
 
    /**
     * Gets the xxx role.
     *
     * @return the xxx role
     */
    public String getRole() {
        return get(roleDescriptor);
    }
    
    /**
     * Sets the xxx role.
     *
     * @param src
     *            the xxx role
     */
    public void setRole(String role) {
        set(roleDescriptor, role);
    }`

**Comment by Legioth** [comment]
Not changing roles later sounds like the only high level API should be through the constructor of the component. It should of course still be possible to go against the recommendations by using the `Element` API. On the other hand, the API grows quite substantially if adding a new constructor to all element components for which `role` might apply (i.e. all of them).

An enum would help with discoverability, but has the problem that it might become stale if the specification is updated to support additional roles. Another complicating factor is that the set of officially supported roles is different for different elements. The solution would be very complex if we would want to also provide API guidance on that account.

Overall, it starts to feel like any specific support for the `role` attribute is quite complex and requires some additional thought. I'd therefore suggest continuing with this PR without `role` support and then considering the addition separately.

**Comment by knoobie** [comment]
Okay, reasonable! So this pr is ready to review.

**Comment by SomeoneToIgnore** [comment]
:lgtm:

---

Reviewed 14 of 15 files at r1.
Review status: 14 of 15 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3188#-:-L2KWA4C2gw_4pySJnts:bnfp4nl)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 1 of 15 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3188)*

**Pull request merged**
