### PR TITLE
Prevent killing UI if heartbeats are pending

### PR DESCRIPTION
**Pull request by ZheSun88**
Port Change from framework 8,3.0.alpha1
Original commit is vaadin/framework#10371

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3674)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3674)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3674)*

**Comment by pekam** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java, line 1378 at r2](https://beta.reviewable.io/reviews/vaadin/flow/3674#-L74rDxiJuN9T0Ndkavj-r2-1378:-L7P1kmH10u3zoODimTI:b-n0tjw8) ([raw file](https://github.com/vaadin/flow/blob/4f94121385438bd532cab34d4a3899ed1af23639/flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java#L1378)):*
<details><summary><i>Previously, vaadin-bot (Vaadin Bot) wrote…</i></summary><blockquote>

MAJOR Merge this if statement with the enclosing one. [rule](https://sonar.projects.vaadin.com/coding_rules#rule_key=squid%3AS1066)
</blockquote></details>

yes please

---

*[flow-tests/test-root-ui-context/src/main/java/com/vaadin/flow/uitest/ui/LockingUI.java, line 40 at r2](https://beta.reviewable.io/reviews/vaadin/flow/3674#-L7P14UT67UDh5MJ4YWb:-L7P14UT67UDh5MJ4YWc:b2w2jdl) ([raw file](https://github.com/vaadin/flow/blob/4f94121385438bd532cab34d4a3899ed1af23639/flow-tests/test-root-ui-context/src/main/java/com/vaadin/flow/uitest/ui/LockingUI.java#L40)):*
> ```Java
>                         "Timeout should not get interrupted.");
>             }
>                     message.setText(LOCKING_ENDED);
> ```

fix indentation

---

*[flow-tests/test-root-ui-context/src/test/java/com/vaadin/flow/uitest/ui/LockingIT.java, line 21 at r2](https://beta.reviewable.io/reviews/vaadin/flow/3674#-L7P0gvf7-XIcUJmu6gT:-L7P0gvf7-XIcUJmu6gU:b-145htn) ([raw file](https://github.com/vaadin/flow/blob/4f94121385438bd532cab34d4a3899ed1af23639/flow-tests/test-root-ui-context/src/test/java/com/vaadin/flow/uitest/ui/LockingIT.java#L21)):*
> ```Java
>     }
> 
>     private void clickButtonAndCheckNotification(String buttonId, String text) {
> ```

rename `Notification` to `Message` in this method name

---

*[flow-tests/test-root-ui-context/src/test/java/com/vaadin/flow/uitest/ui/LockingIT.java, line 22 at r2](https://beta.reviewable.io/reviews/vaadin/flow/3674#-L7P0et7-3WAfOuJTNdr:-L7P0et7-3WAfOuJTNds:b-uv7i6k) ([raw file](https://github.com/vaadin/flow/blob/4f94121385438bd532cab34d4a3899ed1af23639/flow-tests/test-root-ui-context/src/test/java/com/vaadin/flow/uitest/ui/LockingIT.java#L22)):*
> ```Java
> 
>     private void clickButtonAndCheckNotification(String buttonId, String text) {
>         
> ```

remove whitespace

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3674)*

**Comment by pekam** [comment]
Reviewed 2 of 3 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3674)*

**Comment by pekam** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3674#-:-L7PEuJV8vZS66QJps2P:bnfp4nl)*

**Comment by pekam** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3674#-:-L7PbdeJGHCLWB7DCjIS:bnfp4nl)*

**Comment by pekam** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3674#-:-L7Pn99s0tJPDk2lk4p8:bnfp4nl)*

**Pull request merged**
