### PR TITLE
Make LitTemplateParserImpl public. Fixes #9169

### LINKED ISSUE #9169: Please make LitTemplateParserImpl public
Vaadin 18.0.0.alpha1. Please make LitTemplateParserImpl public otherwise it's really hard to hook into the template loading mechanism.

### PR DESCRIPTION
**Pull request by mvysny**
Fixes #9169

### CODE REVIEW

**Review by denis-anisimov — COMMENTED** [review]
What's the purpose of having `LitTemplateParserImpl` `public`?

It has been done package local in purpose: `public` opens API and allows it to use by everyone. It's not API and may be needed only in special cases.
One such special case is testing. For that reason I made a proper way to instantiate the parser via factory and restricted visibility to package local.
In case of testing the package structure is not really important and you may just put your subclass in your own module into the same package and extend this class without any problems.

So in case there are no other cases except testing there is no need to make this `public`.
If there are other cases, then:
  - please let me know such cases
  - the class should be moved into some `internal`  package which indicates that this class is not supposed to be used externally (there was no such need if it's package local).

**Comment by mvysny** [comment]
Karibu-Testing needs to patch into the `LitTemplateParserImpl` loading mechanism, to load the js/ts files from the local filesystem. That requires to extend the `LitTemplateParserImpl` class and override the `LitTemplateParserImpl.getSourcesFromTemplate()` function.

> In case of testing the package structure is not really important and you may just put your subclass in your own module into the same package and extend this class without any problems.

Yes, this hack can be used to make `LitTemplateParserImpl` effectively public. This hack can indeed be used. Unfortunately, with Karibu-Testing the situation is a bit more complex.

The reason is that Karibu-Testing compiles against Vaadin 14 in order to be always compatible with the latest LTS. In order to extend a Vaadin 18 class, a ByteBuddy dynamic extension mechanism needs to be used, which then fails with `IllegalAccessError... cannot access its superclass`.

Possible solutions:
1. Make `LitTemplateParserImpl` public
2. Make ByteBuddy generate the overriding class into the `com.vaadin.flow.component.littemplate` package and use `ClassLoadingStrategy.Default.INJECTION` - under testing.
3. Make Karibu-Testing compile against Vaadin 18 but test against Vaadin 14. Tricky, but will get rid of ByteBuddy hacks.

> So in case there are no other cases except testing there is no need to make this public.

Yeah, probably no other use-case. I can't picture anyone wishing to tinker with this loading mechanism. However, if someone does, then it's quite hard: `LitTemplateParserImpl` contains lots of code that needs to either be copied, or extended. The former is fragile (what if the class changes), the latter is hard (the `LitTemplateParserImpl` was not designed to be extensible, also it's package-private).

**Comment by mvysny** [comment]
Fair enough, yeah the pure interface approach would make more sense. Thank you for explanation.

That being said, LitTemplateParserImpl contains a lot of logic which every implementor of LitTemplateParser will need (the annotation parsing+iteration). To be extra clean, we should extract some of the code into a helper classes or some kind of SPI layer. Alternatively, another factory for just locating the template file would be handy to have - then both `LitTemplateParserImpl.getSourcesFromTemplate(String tag, String url)` and NpmParser would delegate to that factory.

> Is the option 2 really that hard ? I would go with it unless it's extremely cumbersome.

I have found a way to configure ByteBuddy to be able to work, so option 2 is viable, code-wise. However, what about security? Java 9 Module mechanism prevents exactly this kind of 'split package' scenario: https://www.logicbig.com/tutorials/core-java-tutorial/modules/split-and-private-package.html .

**Comment by denis-anisimov** [comment]
I didn't know about Java 9 module security (but I'm glad that they implemented this now : I never liked that package visibility could be broken so easily).

OK, then please :
- keep the class `public`
- move it to some `internal` package.

The question how to make this impl eligible for reusing is more complicated and it's not clear whether this is really necessary.
So let's not solve it now.

**Comment by mvysny** [comment]
> The question how to make this impl eligible for reusing is more complicated and it's not clear whether this is really necessary.
So let's not solve it now.

I agree. For my purposes it's enough if I can extend the `LitTemplateParserImpl` class - no need for additional SPI. And you're right - nobody else wanted this feature so far, so no need to bother with SPIs and stuff.

@denis-anisimov just that I understand correctly: should I move the `LitTemplateParserImpl` class into the `com.vaadin.flow.component.littemplate.internal` package and keep it in the `flow-lit-template` Maven module?

**Comment by denis-anisimov** [comment]
Yes, `com.vaadin.flow.component.littemplate.internal` I think is the proper package name.
Sure, keep it inside the same module. This functionality is lit related only.

**Review by denis-anisimov — APPROVED** [review]

**Comment by mvysny** [comment]
@denis-anisimov one test failed:

```
java.lang.AssertionError: com.vaadin.flow.component.littemplate.internal.LitTemplateParserImpl
	at com.vaadin.flow.testutil.ClassesSerializableTest.serializeAndDeserialize(ClassesSerializableTest.java:336)
	at com.vaadin.flow.testutil.ClassesSerializableTest.classesSerializable(ClassesSerializableTest.java:308)
Caused by: java.io.NotSerializableException: com.vaadin.flow.component.littemplate.internal.LitTemplateParserImpl
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at com.vaadin.flow.testutil.ClassesSerializableTest.serializeAndDeserialize(ClassesSerializableTest.java:232)
	at com.vaadin.flow.testutil.ClassesSerializableTest.serializeAndDeserialize(ClassesSerializableTest.java:334)
	... 26 more
```

However, I don't think `LitTemplateParserImpl` should be made serializable... Could you let me know how to exclude LitTemplateParserImpl from the serialization test please?

**Comment by caalador** [comment]
@mvysny See `LitClassesSerializableTest` in the module

**Review by denis-anisimov — APPROVED** [review]

**Pull request merged**
