### PR TITLE
Remove VaadinServlet resource methods

### PR DESCRIPTION
**Pull request by Artur-**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3946)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3946#-:-LAWepId0gI9x0XQK7s1:bnfp4nl)*

**Comment by SomeoneToIgnore** [comment]
Compilation errors are in the build.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/3946#-:-LAq7lWh1rRFQ4i23ekC:bul4jd7)*

**Comment by Artur-** [comment]
Review status: 4 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-server/src/test/java/com/vaadin/flow/server/MockServletServiceSessionSetup.java, line 119 at r1](https://reviewable.io/reviews/vaadin/flow/3946#-LAseV2v89rg2AOcuKE9:-LAvXNba7fEdI4xxGLPC:b-ez4mo6) ([raw file](https://github.com/vaadin/flow/blob/462dd4a188c0792a976b85345febbdf11668b135/flow-server/src/test/java/com/vaadin/flow/server/MockServletServiceSessionSetup.java#L119)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

This is still used in `BootstrapHandlerDependenciesTest.setup()`
</blockquote></details>

Yes, this PR depends on #3929

---

*[flow-server/src/test/java/com/vaadin/flow/server/MockServletServiceSessionSetup.java, line 124 at r1](https://reviewable.io/reviews/vaadin/flow/3946#-LAsemeE10CTU-SRVRZZ:-LAvXQHFAcXWiiOIbhjm:b-ez4mo6) ([raw file](https://github.com/vaadin/flow/blob/462dd4a188c0792a976b85345febbdf11668b135/flow-server/src/test/java/com/vaadin/flow/server/MockServletServiceSessionSetup.java#L124)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

This is still used in `BootstrapHandlerDependenciesTest.setup()`
</blockquote></details>

Yes, this PR depends on #3929

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/3946)*

**Comment by SomeoneToIgnore** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/3946#-:-LAwn83m0mB-6yiyHlef:bnfp4nl)*

**Pull request merged**
