### PR TITLE
Update layouts to use the webcomponents

### PR DESCRIPTION
**Pull request by ZheSun88**
this is the first step for migrate it to it own repo

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/2700)

### CODE REVIEW

**Comment by ZheSun88** [comment]
This is a issue with `@HtmlImport`, because there is no correct import yet

**Comment by denis-anisimov** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/layout/FlexLayout.java, line 36 at r1](https://reviewable.io:443/reviews/vaadin/flow/2700#-KwiMKb_l2Gvh6ynBVK5:-KwiMKb_l2Gvh6ynBVK6:b8w1bn9) ([raw file](https://github.com/vaadin/flow/blob/38b65b096a95b2152215cd93ff37e97c3144c0cc/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/layout/FlexLayout.java#L36)):*
> @Tag(Tag.DIV)

Do we need it here at all ?
May be this class should be made `abstract` without any tag declaration ?

What about javadocs ?
Are they still applicable to the class ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2700)*

**Comment by ZheSun88** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/layout/FlexLayout.java, line 36 at r1](https://reviewable.io:443/reviews/vaadin/flow/2700#-KwiMKb_l2Gvh6ynBVK5:-KwiTKyI184dr-zscNwr:b-trtn2g) ([raw file](https://github.com/vaadin/flow/blob/2f02a9f8c26605e1aa9c6d099f100e7494950b72/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/layout/FlexLayout.java#L36)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> @Tag(Tag.DIV)

Do we need it here at all ?
May be this class should be made `abstract` without any tag declaration ?

What about javadocs ?
Are they still applicable to the class ?
</blockquote></details>

we are using it for now as the first step to migrate the webcomponents to their own repo.  or this is required in this ticket.  #2475

i will check the javadocs, after it passes the build. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2700)*

**Comment by denis-anisimov** [comment]
Review status: 1 of 46 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2700#-KwiyWJjg30gsdHGXZto:-KwiyWJjg30gsdHGXZtp:b-kfe3ud) (no related file):*
Looks like a lot of generated files that shouldn't be in the git at all.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2700)*

**Comment by ZheSun88** [comment]
Review status: 1 of 46 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2700#-KwiyWJjg30gsdHGXZto:-Kwiz0S75jaQylrGpRug:b-6cwmxw) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Looks like a lot of generated files that shouldn't be in the git at all.
</blockquote></details>

Yes it is.. i `git  clone` the whole folder of  `vaadin-ordered-layout` for using the correcting import vertical and horizontal layout.  I think later i need to switch to `webjars`. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2700)*

**Comment by torok-peter** [comment]
Reviewed 1 of 3 files at r1, 3 of 45 files at r2.
Review status: 4 of 46 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2700)*

**Comment by denis-anisimov** [comment]
Review status: 4 of 46 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2700#-KwiyWJjg30gsdHGXZto:-Kwj0mmmwsYKiV4T8qoc:b-60ejct) (no related file):*
<details><summary><i>Previously, ZheSun88 wrote…</i></summary><blockquote>

Yes it is.. i `git  clone` the whole folder of  `vaadin-ordered-layout` for using the correcting import vertical and horizontal layout.  I think later i need to switch to `webjars`. 
</blockquote></details>

Why did you import `vaadin-ordered-layout` folder ?

You shouldn't care about client side at all here.
`webjars` are not yet available. So the client side part should be imported in each project separately.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2700)*

**Comment by ZheSun88** [comment]
Review status: 4 of 46 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2700#-KwiyWJjg30gsdHGXZto:-Kwj2lF6l4nvFJyvXjwp:b-ytdlja) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Why did you import `vaadin-ordered-layout` folder ?

You shouldn't care about client side at all here.
`webjars` are not yet available. So the client side part should be imported in each project separately.
</blockquote></details>

import the `vaadin-ordered-layout` for adding bower dependencies for the layouts.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2700)*

**Comment by denis-anisimov** [comment]
Review status: 4 of 46 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2700#-KwiyWJjg30gsdHGXZto:-Kwj9M6r6dck_Yq8UkE1:b-qcvr78) (no related file):*
<details><summary><i>Previously, ZheSun88 wrote…</i></summary><blockquote>

import the `vaadin-ordered-layout` for adding bower dependencies for the layouts.
</blockquote></details>

The client side code at at the moment is not included into Flow components at all.

See demo. Each time when developer adds a dependency to a flow component he should care about the client side bower import by himself.
We don't distribute the client side code at all at the moment with Flow.
(thought it's weird, I agree)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2700)*

**Comment by ZheSun88** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2700#-KwiyWJjg30gsdHGXZto:-KwjKEqDKbmicUkZPFR7:bgesr2u) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

The client side code at at the moment is not included into Flow components at all.

See demo. Each time when developer adds a dependency to a flow component he should care about the client side bower import by himself.
We don't distribute the client side code at all at the moment with Flow.
(thought it's weird, I agree)
</blockquote></details>

now, there is not need the folder of `ordered-layout`. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2700)*

**Comment by heruan** [comment]
> Each time when developer adds a dependency to a flow component he should care about the client side bower import by himself.

@denis-anisimov is this the case also after #2634? Seems like Flow components will depend on Webjars which will include client-side code as well.

**Comment by denis-anisimov** [comment]
Reviewed 3 of 45 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2700)*

**Comment by ZheSun88** [comment]
@heruan  yes, you are correct and also thanks @denis-anisimov for the explanations. 

The migration will be done in about 3 steps, which just separates @heruan 's first step into two different tickets. .. I am working on that.

**Pull request merged**
