### PR TITLE
chore: Upgrade webpack dependencies to match V23

### PR DESCRIPTION
**Pull request by Artur-**

### CODE REVIEW

**Comment by caalador** [comment]
Webpack seems to fail on unknown option with the new version:
```
[10:39:47]W:		 [com.vaadin:flow-test-pnpm-dev-mode] [ForkJoinPool.commonPool-worker-1] ERROR dev-webpack - Webpack failed with the exception:
[10:39:47]W:		 [com.vaadin:flow-test-pnpm-dev-mode] [webpack-cli] Error: Unknown option '--watchDogPort=45043'
[10:39:47]W:		 [com.vaadin:flow-test-pnpm-dev-mode] [webpack-cli] Run 'webpack --help' to see available commands and options
```

**Comment by Artur-** [comment]
There are at least 801dd252e3fb2bd69ceeb540a257b244e235e2fd and d890ddfebe0 that might be relevant here

**Comment by caalador** [comment]
at least #9934 should be picked.

**Comment by Artur-** [comment]
Pretty sure we would need to backport 801dd252e3fb2bd69ceeb540a257b244e235e2fd first

**Comment by caalador** [comment]
Most likely. There were some issues with it (can't specifically remember what) and then builds broke so didn't have time to continue.

**Comment by MarcinVaadin** [comment]
Current build issue:
```
Caused by: org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'ip-172-16-1-218.eu-west-1.compute.internal', ip: '172.16.1.218', os.name: 'Linux', os.arch: 'amd64', os.version: '4.14.231-173.361.amzn2.x86_64', java.version: '1.8.0_201'
```

and on second run:
```
Caused by: org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'ip-172-16-1-159', ip: '172.16.1.159', os.name: 'Linux', os.arch: 'amd64', os.version: '4.9.0-0.bpo.6-amd64', java.version: '1.8.0_201'
```

**Comment by MarcinVaadin** [comment]
Current state: `webpack-babel-multi-target-plugin` 2.5.0 is not compatible with `webpack-dev-server` 4.x

**Comment by Artur-** [comment]
Uh, why did the tests pass now? I re-ran them to check the 2.8 build, not this particular PR..

**Comment by czp13** [comment]
### Code reviewed:
Seems good to me.

### Tested the build 
with locally built Flow-server dependency and included it in my custom V14 application.
Hosted locally, and opened the port to be reachable from Browserstack

### Smoke test 
- seen components
-  and manipulable, textField works, notification works, radio button looks nice,
with BrowserStack

Windows 10
- IE 108✅ 
- IE 109✅ 
- IE 110 ✅ 
- IE 111 ✅ 

Windows  11
- IE 108✅ 
- IE 109✅ 
- IE 110 ✅ 
- IE 111 ✅ 

![image](https://user-images.githubusercontent.com/61667986/234985989-1eb02dba-532f-44a7-a786-f51f13e1ceec.png)


**Let me know if more OS/Browser shall be tested.**


Webpack works nicely it seems to me (from logs):
```
2023-04-27 22:15:05.388  INFO 21170 --- [onPool-worker-3] dev-updater                              : Frontend dependencies resolved successfully.
2023-04-27 22:15:05.395  INFO 21170 --- [onPool-worker-3] dev-updater                              : Copying frontend resources from jar files ...
2023-04-27 22:15:05.405  INFO 21170 --- [onPool-worker-3] dev-updater                              : Visited 14 resources. Took 10 ms.
2023-04-27 22:15:05.427  INFO 21170 --- [onPool-worker-5] dev-webpack                              : Starting webpack-dev-server

------------------ Starting Frontend compilation. ------------------
2023-04-27 22:15:06.056  INFO 21170 --- [onPool-worker-5] dev-webpack                              : Running webpack to compile frontend resources. This may take a moment, please stand by...
2023-04-27 22:15:14.377  INFO 21170 --- [onPool-worker-5] dev-webpack                              : Started webpack-dev-server. Time: 8324ms
```


All Startup logs:

```
~/Projects/vaadin-14-expertise    main ?19  mvn                                                                                                                                                                                                                              ✔  base   16.14.2   10:14:43 PM 
[INFO] Scanning for projects...
[INFO]
[INFO] --------------------< com.example:spring-skeleton >---------------------
[INFO] Building Project base for Spring Boot and Vaadin Flow 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] >>> spring-boot-maven-plugin:2.6.7:run (default-cli) > test-compile @ spring-skeleton >>>
[INFO]
[INFO] --- maven-resources-plugin:3.2.0:resources (default-resources) @ spring-skeleton ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Using 'UTF-8' encoding to copy filtered properties files.
[INFO] Copying 1 resource
[INFO] Copying 1 resource
[INFO]
[INFO] --- vaadin-maven-plugin:14.8.18:prepare-frontend (default) @ spring-skeleton ---
[INFO] Added 4 default dependencies to main package.json
[INFO] Copying frontend resources from jar files ...
[INFO] Visited 114 resources. Took 112 ms.
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ spring-skeleton ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-resources-plugin:3.2.0:testResources (default-testResources) @ spring-skeleton ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Using 'UTF-8' encoding to copy filtered properties files.
[INFO] skip non existing resourceDirectory /Users/pczuczor/Projects/vaadin-14-expertise/src/test/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ spring-skeleton ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] <<< spring-boot-maven-plugin:2.6.7:run (default-cli) < test-compile @ spring-skeleton <<<
[INFO]
[INFO]
[INFO] --- spring-boot-maven-plugin:2.6.7:run (default-cli) @ spring-skeleton ---
[INFO] Attaching agents: []
22:14:51.683 [Thread-0] DEBUG org.springframework.boot.devtools.restart.classloader.RestartClassLoader - Created RestartClassLoader org.springframework.boot.devtools.restart.classloader.RestartClassLoader@9e013c3

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.6.7)

2023-04-27 22:14:51.935  INFO 21170 --- [  restartedMain] org.vaadin.example.Application           : Starting Application using Java 11.0.17 on Peters-Air with PID 21170 (/Users/pczuczor/Projects/vaadin-14-expertise/target/classes started by pczuczor in /Users/pczuczor/Projects/vaadin-14-expertise)
2023-04-27 22:14:51.937  INFO 21170 --- [  restartedMain] org.vaadin.example.Application           : No active profile set, falling back to 1 default profile: "default"
2023-04-27 22:14:51.960  INFO 21170 --- [  restartedMain] .e.DevToolsPropertyDefaultsPostProcessor : Devtools property defaults active! Set 'spring.devtools.add-properties' to 'false' to disable
2023-04-27 22:14:51.960  INFO 21170 --- [  restartedMain] .e.DevToolsPropertyDefaultsPostProcessor : For additional web related logging consider setting the 'logging.level.web' property to 'DEBUG'
2023-04-27 22:14:52.356  INFO 21170 --- [  restartedMain] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2023-04-27 22:14:52.361  INFO 21170 --- [  restartedMain] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2023-04-27 22:14:52.361  INFO 21170 --- [  restartedMain] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.62]
2023-04-27 22:14:52.395  INFO 21170 --- [  restartedMain] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2023-04-27 22:14:52.395  INFO 21170 --- [  restartedMain] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 435 ms
2023-04-27 22:14:52.994  INFO 21170 --- [  restartedMain] c.v.f.s.VaadinServletContextInitializer  : Search for subclasses and classes with annotations took 0 seconds
2023-04-27 22:14:52.994  INFO 21170 --- [  restartedMain] c.v.f.s.VaadinServletContextInitializer  : Due to slow search it is recommended to use the whitelisted-packages feature to make scanning faster.

See the whitelisted-packages section in the docs at https://vaadin.com/docs/latest/flow/integrations/spring/configuration#special-configuration-parameters
2023-04-27 22:14:52.996  INFO 21170 --- [  restartedMain] c.v.f.server.startup.DevModeInitializer  : Starting dev-mode updaters in /Users/pczuczor/Projects/vaadin-14-expertise folder.
2023-04-27 22:14:53.011  INFO 21170 --- [  restartedMain] dev-updater                              : Visited 102 classes. Took 13 ms.
Vaadin application has been deployed and started to the context path "/".
2023-04-27 22:14:53.019  INFO 21170 --- [onPool-worker-3] dev-updater                              : Added 4 default dependencies to main package.json
2023-04-27 22:14:53.048  INFO 21170 --- [onPool-worker-3] dev-updater                              : Running `npm install` to resolve and optionally download frontend dependencies. This may take a moment, please stand by...
2023-04-27 22:14:53.175  INFO 21170 --- [  restartedMain] o.s.b.d.a.OptionalLiveReloadServer       : LiveReload server is running on port 35729
2023-04-27 22:14:53.222  INFO 21170 --- [  restartedMain] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
2023-04-27 22:14:53.227  INFO 21170 --- [  restartedMain] org.vaadin.example.Application           : Started Application in 1.538 seconds (JVM running for 1.757)
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: no-name@undefined
npm WARN Found: webpack-dev-server@3.11.0
npm WARN node_modules/webpack-dev-server
npm WARN   dev webpack-dev-server@"4.10.0" from the root project
npm WARN   1 more (webpack-babel-multi-target-plugin)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer webpack-dev-server@"^3.1.0" from webpack-babel-multi-target-plugin@2.5.0
npm WARN node_modules/webpack-babel-multi-target-plugin
npm WARN   dev webpack-babel-multi-target-plugin@"2.5.0" from the root project
2023-04-27 22:15:05.388  INFO 21170 --- [onPool-worker-3] dev-updater                              : Frontend dependencies resolved successfully.
2023-04-27 22:15:05.395  INFO 21170 --- [onPool-worker-3] dev-updater                              : Copying frontend resources from jar files ...
2023-04-27 22:15:05.405  INFO 21170 --- [onPool-worker-3] dev-updater                              : Visited 14 resources. Took 10 ms.
2023-04-27 22:15:05.427  INFO 21170 --- [onPool-worker-5] dev-webpack                              : Starting webpack-dev-server

------------------ Starting Frontend compilation. ------------------
2023-04-27 22:15:06.056  INFO 21170 --- [onPool-worker-5] dev-webpack                              : Running webpack to compile frontend resources. This may take a moment, please stand by...
2023-04-27 22:15:14.377  INFO 21170 --- [onPool-worker-5] dev-webpack                              : Started webpack-dev-server. Time: 8324ms

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.6.7)

2023-04-27 22:15:16.032  INFO 21170 --- [  restartedMain] org.vaadin.example.Application           : Starting Application using Java 11.0.17 on Peters-Air with PID 21170 (/Users/pczuczor/Projects/vaadin-14-expertise/target/classes started by pczuczor in /Users/pczuczor/Projects/vaadin-14-expertise)
2023-04-27 22:15:16.033  INFO 21170 --- [  restartedMain] org.vaadin.example.Application           : No active profile set, falling back to 1 default profile: "default"
2023-04-27 22:15:16.288  INFO 21170 --- [  restartedMain] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2023-04-27 22:15:16.289  INFO 21170 --- [  restartedMain] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2023-04-27 22:15:16.289  INFO 21170 --- [  restartedMain] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.62]
2023-04-27 22:15:16.321  INFO 21170 --- [  restartedMain] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2023-04-27 22:15:16.321  INFO 21170 --- [  restartedMain] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 284 ms
2023-04-27 22:15:18.299  INFO 21170 --- [  restartedMain] c.v.f.s.VaadinServletContextInitializer  : Search for subclasses and classes with annotations took 1 seconds
2023-04-27 22:15:18.309  INFO 21170 --- [  restartedMain] c.v.f.s.VaadinServletContextInitializer  : Due to slow search it is recommended to use the whitelisted-packages feature to make scanning faster.

See the whitelisted-packages section in the docs at https://vaadin.com/docs/latest/flow/integrations/spring/configuration#special-configuration-parameters
2023-04-27 22:15:18.312  INFO 21170 --- [  restartedMain] c.v.f.server.startup.DevModeInitializer  : Starting dev-mode updaters in /Users/pczuczor/Projects/vaadin-14-expertise folder.
2023-04-27 22:15:18.343  INFO 21170 --- [  restartedMain] dev-updater                              : Visited 102 classes. Took 29 ms.
Vaadin application has been deployed and started to the context path "/".
2023-04-27 22:15:18.377  INFO 21170 --- [onPool-worker-5] dev-updater                              : Skipping `npm install` because the frontend packages are already installed in the folder '/Users/pczuczor/Projects/vaadin-14-expertise/node_modules' and the hash in the file '/Users/pczuczor/Projects/vaadin-14-expertise/node_modules/.vaadin/vaadin.json' is the same as in 'package.json'
2023-04-27 22:15:18.464  INFO 21170 --- [onPool-worker-5] dev-updater                              : Copying frontend resources from jar files ...
2023-04-27 22:15:18.539  INFO 21170 --- [onPool-worker-5] dev-updater                              : Visited 14 resources. Took 75 ms.
2023-04-27 22:15:18.603  INFO 21170 --- [  restartedMain] o.s.b.d.a.OptionalLiveReloadServer       : LiveReload server is running on port 35729
2023-04-27 22:15:18.626  INFO 21170 --- [  restartedMain] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
2023-04-27 22:15:18.635  INFO 21170 --- [  restartedMain] org.vaadin.example.Application           : Started Application in 2.643 seconds (JVM running for 27.165)
2023-04-27 22:15:18.637  INFO 21170 --- [  restartedMain] .ConditionEvaluationDeltaLoggingListener : Condition evaluation unchanged


2023-04-27 22:21:47.126  INFO 21170 --- [nio-8080-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2023-04-27 22:21:47.129  INFO 21170 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2023-04-27 22:21:47.175  INFO 21170 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 46 ms
2023-04-27 22:21:47.251  INFO 21170 --- [nio-8080-exec-1] c.v.f.s.DefaultDeploymentConfiguration   :
Vaadin is running in DEBUG MODE.
When deploying application for production, remember to disable debug features. See more from https://vaadin.com/docs/
2023-04-27 22:21:51.032  INFO 21170 --- [nio-8080-exec-1] c.vaadin.flow.spring.SpringInstantiator  : The number of beans implementing 'I18NProvider' is 0. Cannot use Spring beans for I18N, falling back to the default behavior
```

The only interesting thing is the double startup (after the webpack compilation Spring starts again, maybe it is normal) and the warning messages, but I am not sure if it is related to this change:
```
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: no-name@undefined
npm WARN Found: webpack-dev-server@3.11.0
npm WARN node_modules/webpack-dev-server
npm WARN   dev webpack-dev-server@"4.10.0" from the root project
npm WARN   1 more (webpack-babel-multi-target-plugin)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer webpack-dev-server@"^3.1.0" from webpack-babel-multi-target-plugin@2.5.0
npm WARN node_modules/webpack-babel-multi-target-plugin
```

**Review by czp13 — CHANGES_REQUESTED** [review]
It would be good if a second pair of eyes could double checked the warning messages:
```
npm WARN While resolving: no-name@undefined
npm WARN Found: webpack-dev-server@3.11.0
npm WARN node_modules/webpack-dev-server
npm WARN   dev webpack-dev-server@"4.10.0" from the root project
npm WARN   1 more (webpack-babel-multi-target-plugin)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer webpack-dev-server@"^3.1.0" from webpack-babel-multi-target-plugin@2.5.0
npm WARN node_modules/webpack-babel-multi-target-plugin
```

But as said, smoke test was good, just builds having some warning messages.

**Comment by czp13** [comment]
Tested with `flow-server 2.8.4` version just for reference.

Key differences:
- different warn message:
- no double Spring startup phase.

Smoke Test on Mac/Chrome worked.

Full logs:
```
mvn                                                                                                                                                                                                                          INT ✘  base   16.14.2   10:51:12 PM 
[INFO] Scanning for projects...
[INFO]
[INFO] --------------------< com.example:spring-skeleton >---------------------
[INFO] Building Project base for Spring Boot and Vaadin Flow 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] >>> spring-boot-maven-plugin:2.6.7:run (default-cli) > test-compile @ spring-skeleton >>>
[INFO]
[INFO] --- maven-resources-plugin:3.2.0:resources (default-resources) @ spring-skeleton ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Using 'UTF-8' encoding to copy filtered properties files.
[INFO] Copying 1 resource
[INFO] Copying 1 resource
[INFO]
[INFO] --- vaadin-maven-plugin:14.8.18:prepare-frontend (default) @ spring-skeleton ---
[INFO] Copying frontend resources from jar files ...
[INFO] Visited 113 resources. Took 62 ms.
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ spring-skeleton ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-resources-plugin:3.2.0:testResources (default-testResources) @ spring-skeleton ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Using 'UTF-8' encoding to copy filtered properties files.
[INFO] skip non existing resourceDirectory /Users/pczuczor/Projects/vaadin-14-expertise/src/test/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ spring-skeleton ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to /Users/pczuczor/Projects/vaadin-14-expertise/target/test-classes
[INFO]
[INFO] <<< spring-boot-maven-plugin:2.6.7:run (default-cli) < test-compile @ spring-skeleton <<<
[INFO]
[INFO]
[INFO] --- spring-boot-maven-plugin:2.6.7:run (default-cli) @ spring-skeleton ---
[INFO] Attaching agents: []
22:51:34.154 [Thread-0] DEBUG org.springframework.boot.devtools.restart.classloader.RestartClassLoader - Created RestartClassLoader org.springframework.boot.devtools.restart.classloader.RestartClassLoader@2ceddac1

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.6.7)

2023-04-27 22:51:34.463  INFO 22722 --- [  restartedMain] org.vaadin.example.Application           : Starting Application using Java 11.0.17 on Peters-Air with PID 22722 (/Users/pczuczor/Projects/vaadin-14-expertise/target/classes started by pczuczor in /Users/pczuczor/Projects/vaadin-14-expertise)
2023-04-27 22:51:34.464  INFO 22722 --- [  restartedMain] org.vaadin.example.Application           : No active profile set, falling back to 1 default profile: "default"
2023-04-27 22:51:34.498  INFO 22722 --- [  restartedMain] .e.DevToolsPropertyDefaultsPostProcessor : Devtools property defaults active! Set 'spring.devtools.add-properties' to 'false' to disable
2023-04-27 22:51:34.498  INFO 22722 --- [  restartedMain] .e.DevToolsPropertyDefaultsPostProcessor : For additional web related logging consider setting the 'logging.level.web' property to 'DEBUG'
2023-04-27 22:51:35.098  INFO 22722 --- [  restartedMain] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2023-04-27 22:51:35.109  INFO 22722 --- [  restartedMain] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2023-04-27 22:51:35.109  INFO 22722 --- [  restartedMain] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.62]
2023-04-27 22:51:35.156  INFO 22722 --- [  restartedMain] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2023-04-27 22:51:35.156  INFO 22722 --- [  restartedMain] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 657 ms
2023-04-27 22:51:35.768  INFO 22722 --- [  restartedMain] c.v.f.s.VaadinServletContextInitializer  : Search for subclasses and classes with annotations took 0 seconds
2023-04-27 22:51:35.768  INFO 22722 --- [  restartedMain] c.v.f.s.VaadinServletContextInitializer  : Due to slow search it is recommended to use the whitelisted-packages feature to make scanning faster.

See the whitelisted-packages section in the docs at https://vaadin.com/docs/latest/flow/integrations/spring/configuration#special-configuration-parameters
2023-04-27 22:51:35.770  INFO 22722 --- [  restartedMain] c.v.f.server.startup.DevModeInitializer  : Starting dev-mode updaters in /Users/pczuczor/Projects/vaadin-14-expertise folder.
2023-04-27 22:51:35.783  INFO 22722 --- [  restartedMain] dev-updater                              : Visited 102 classes. Took 12 ms.
Vaadin application has been deployed and started to the context path "/".
2023-04-27 22:51:35.832  INFO 22722 --- [onPool-worker-3] dev-updater                              : Running `npm install` to resolve and optionally download frontend dependencies. This may take a moment, please stand by...
2023-04-27 22:51:35.963  INFO 22722 --- [  restartedMain] o.s.b.d.a.OptionalLiveReloadServer       : LiveReload server is running on port 35729
2023-04-27 22:51:36.023  INFO 22722 --- [  restartedMain] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
2023-04-27 22:51:36.028  INFO 22722 --- [  restartedMain] org.vaadin.example.Application           : Started Application in 1.869 seconds (JVM running for 2.173)
2023-04-27 22:51:36.359  INFO 22722 --- [nio-8080-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2023-04-27 22:51:36.359  INFO 22722 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2023-04-27 22:51:36.363  INFO 22722 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 2 ms
2023-04-27 22:51:36.394  INFO 22722 --- [nio-8080-exec-1] c.v.f.s.DefaultDeploymentConfiguration   :
Vaadin is running in DEBUG MODE.
When deploying application for production, remember to disable debug features. See more from https://vaadin.com/docs/
2023-04-27 22:51:39.935  INFO 22722 --- [nio-8080-exec-4] c.vaadin.flow.spring.SpringInstantiator  : The number of beans implementing 'I18NProvider' is 0. Cannot use Spring beans for I18N, falling back to the default behavior
npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated fsevents@1.2.13: The v1 package contains DANGEROUS / INSECURE binaries. Upgrade to safe fsevents v2
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
2023-04-27 22:51:56.650  INFO 22722 --- [onPool-worker-3] dev-updater                              : Frontend dependencies resolved successfully.
2023-04-27 22:51:56.655  INFO 22722 --- [onPool-worker-3] dev-updater                              : Copying frontend resources from jar files ...
2023-04-27 22:51:56.666  INFO 22722 --- [onPool-worker-3] dev-updater                              : Visited 14 resources. Took 10 ms.
2023-04-27 22:51:56.683  INFO 22722 --- [onPool-worker-3] dev-webpack                              : Starting webpack-dev-server

------------------ Starting Frontend compilation. ------------------
2023-04-27 22:51:57.390  INFO 22722 --- [onPool-worker-3] dev-webpack                              : Running webpack to compile frontend resources. This may take a moment, please stand by...
2023-04-27 22:52:04.154  INFO 22722 --- [onPool-worker-3] dev-webpack                              : Started webpack-dev-server. Time: 6768ms
```

**Comment by mshabarov** [comment]
I bet double reloads were the bug in some old versions, but were fixed afterwards. To be able to apply this patch, we have to find a commit that fixes the double reload. If it takes a significant efforts, I propose to close this PR.

**Comment by Artur-** [comment]
The peer dependency warning is real as https://github.com/DanielSchaffer/webpack-babel-multi-target-plugin depends on webpack-dev-server 3.x. It is not easy to say though if it would still work with webpack-dev-server 4.x or if there are edge cases where it would fail.

**Comment by Artur-** [comment]
Spring Boot restarts because something on the classpath changed. You can see what by adding 
```
logging.level.org.springframework.boot.devtools.autoconfigure.[LocalDevToolsAutoConfiguration$RestartingClassPathChangeChangedEventListener]=DEBUG
```
to `application.properties`

**Comment by Artur-** [comment]
The webpack-babel-multi-target-plugin project is dead though, with no commits in a couple of years and a webpack 5 PR that was "finished" in 2021 but never merged. So no reason to imagine that it will ever be updated officially for webpack-dev-server 4.x

**Comment by czp13** [comment]
As we discussed in our daily once more, we close this PR.

If anytime in the future `webpack-babel-multi-target-plugin` is updated to be stable with `webpack-dev-server 4.x`:
- their open PR got merged (https://github.com/DanielSchaffer/webpack-babel-multi-target-plugin/pull/86)
- and starts to have commits, and updates fresher than 2 years)

**Pull request closed without merging**
