### PR TITLE
fix: refresh dev-tools token on server restart

### LINKED ISSUE #18398: Push cannot re-establish connection after a while
### Description of the bug

in a Hilla project, if a tab is open for a while it loses connection to the server and cannot establish a new connection due to an invalid JSON response and is stuck in an infinite loop.

ws

I investigated the bug and My findings are below:  

UI cannot parse the JSON that is generated in VaadinService -> wrapJsonForClient.
```
private static String wrapJsonForClient(JsonObject json) {
        return "for(;;);[" + JsonUtil.stringify(json) + "]";
}
```
PushHandler -> callWithUi
```
 try {
                ui = service.findUI(vaadinRequest);
                assert UI.getCurrent() == ui;

                if (ui == null) {
                    sendNotificationAndDisconnect(resource,
                            VaadinService.createUINotFoundJSON(true)); <-- This line
                } else {
                    callback.run(resource, ui);
                }
            }

```
Ajax Request sent from client:

Request: 
`http://localhost:8080/VAADIN/push?v-r=push&debug_window&token=c373d72c-915f-4968-b956-5a9de7520d98&X-Atmosphere-tracking-id=8aed545d-bbe2-4734-8030-7e3b81f4f4bc&X-Atmosphere-Framework=3.1.2-javascript&X-Atmosphere-Transport=streaming&X-Atmosphere-TrackMessageSize=true&Content-Type=application%2Fjson%3B%20charset%3DUTF-8&X-atmo-protocol=true&_=1704383588997`

Request Headers:
```
GET /VAADIN/push?v-r=push&debug_window&token=c373d72c-915f-4968-b956-5a9de7520d98&X-Atmosphere-tracking-id=8aed545d-bbe2-4734-8030-7e3b81f4f4bc&X-Atmosphere-Framework=3.1.2-javascript&X-Atmosphere-Transport=streaming&X-Atmosphere-TrackMessageSize=true&Content-Type=application%2Fjson%3B%20charset%3DUTF-8&X-atmo-protocol=true&_=1704383588997 HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: tr-TR,tr;q=0.9,en-US;q=0.8,en;q=0.7
Connection: keep-alive
Content-Type: application/json; charset=UTF-8
Cookie: ajs_anonymous_id=88e3d32e-0354-43bd-b775-afc727ada910; _gcl_au=1.1.1267265298.1698405917; _ga=GA1.1.30122459.1698405917; _fbp=fb.0.1698405916919.2049096238; ajs_user_id=31000000-0000-0000-0000-000000000001; amplitude_id_08bda4db151effa673a3ccced29a643d=eyJkZXZpY2VJZCI6IjZiMzY1ZDIzLTIzZDUtNDRkYy04ZjdjLTY1ZWJjN2E0YmYxMVIiLCJ1c2VySWQiOiIzMTAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMDEiLCJvcHRPdXQiOmZhbHNlLCJzZXNzaW9uSWQiOjE2OTkzNzAwNjkyOTYsImxhc3RFdmVudFRpbWUiOjE2OTkzNzA5NDgwMzgsImV2ZW50SWQiOjAsImlkZW50aWZ5SWQiOjAsInNlcXVlbmNlTnVtYmVyIjowfQ==; _ga_YREEFD0WW1=GS1.1.1699377735.11.0.1699377735.60.0.0; cookieconsent_status=dismiss; csrfToken=46abf1dc-7e94-4c25-b4a7-e67081d50186; JSESSIONID=A6578F0167F15ED0C635C9A147F2F238
Host: localhost:8080
Referer: http://localhost:8080/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
sec-ch-ua: "Not_A Brand";v="8", "Chromium";v="120", "Google Chrome";v="120"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "macOS"
```

Response: 
```
for(;;);[{"meta":{"async":true,"sessionExpired":true}}]
```

### Expected behavior

Should establish a new connection.

### Minimal reproducible example

There is no easy way to clear this example. It happens randomly.

### Versions

- Vaadin / Flow version: 24.3.2
- Java version: 17
- OS version: MacOS Sonoma 14.1.1 
- Browser version (if applicable):
- Application Server (if applicable):
- IDE (if applicable):

### PR DESCRIPTION
**Pull request by mcollovati**
## Description

When the server restarts, a new dev-tools token is generated and the dev-tools websocket reconnection attempts fail because the server does not validate the old token.
This change checks if the token provided by the client was formerly provided by the server, and in that case, forces the client to reconnect with a refreshed token.

Fixes #18398

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [x] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

### CODE REVIEW

**Comment by Artur-** [comment]
Did you consider if it would be easier to retain the token when the server restarts, in a similar way the Vite server port is retained?

**Comment by mcollovati** [comment]
> Did you consider if it would be easier to retain the token when the server restarts, in a similar way the Vite server port is retained?

Nope. I'll take a look. Thanks for pointing out

**Comment by Artur-** [comment]
Or then somebody has broken that feature and never realized it

**Comment by Artur-** [comment]
or then it only works with Spring Boot where the Vaadin classes are retained and only project classes are reloaded when it recreates the app class loader

**Comment by mcollovati** [comment]
Yes, with Spring Boot there are no reconnection issues.
Anyway, looking at how dev server port is stored, I think this PR can be simplified, as you suggested.
I'll try to make some changes

**Review by Artur- — APPROVED** [review]
Looks good. The token() getter could be named getToken()

**Comment by mcollovati** [comment]
> Looks good. The token() getter could be named getToken()

I'll change the method name. Thank you

**Review by Artur- — APPROVED** [review]

**Pull request merged**
