### PR TITLE
Added method asRequired with a custom required validator

### PR DESCRIPTION
**Pull request by ZheSun88**
Port change from framework 8.4.0.alpha1
Original PR is vaadin/framework#10724

Test class will be ported to the component repository

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/4207)

### CODE REVIEW

**Comment by pekam** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow/4207#-LDkCh9i8z4HszcwX0a9:-LDkCh9i8z4HszcwX0aA:bjjpagu) (no related file):*
Test seems to be missing

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4207)*

**Comment by ZheSun88** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java, line 557 at r2](https://reviewable.io/reviews/vaadin/flow/4207#-LDlXTtR5FgUqQX1W89h:-LDohqyV1v3RwS9P2WYt:bg7kcam) ([raw file](https://github.com/vaadin/flow/blob/be39bbeb7771b2504e2d042fa8777233d78aadf7/flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java#L557)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
> assertEquals(1, invokes.get());
> ```

In the original test it equals `0`. (And below it's `1`).
Why there is a difference ?
</blockquote></details>

This is because in flow
```
private void initFieldValue(BEAN bean, boolean writeBackChangedValues) {
            assert bean != null;
            assert onValueChange != null;
            valueInit = true;
            try {
                TARGET originalValue = getter.apply(bean);
                field.setValue(convertToFieldType(originalValue));

                if (writeBackChangedValues && setter != null) {
                    doConversion().ifOk(convertedValue -> {
                        if (!Objects.equals(originalValue, convertedValue)) {
                            setter.accept(bean, convertedValue);
                        }
                    });
                }
            } finally {
                valueInit = false;
            }
        }
```
the `doConversion()` calls the validator once to check the result on whether the binding should accept the converted value or not. BY calling the validator, it will goes to `customRequiredValidator` and causes the increment on  the `invokes`.

 But in framework:
```
 private void initFieldValue(BEAN bean) {
            assert bean != null;
            assert onValueChange != null;
            valueInit = true;
            try {
                getField().setValue(convertDataToFieldType(bean));
            } finally {
                valueInit = false;
            }
        }
```
there is no this part of checking.

---

*[flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java, line 612 at r2](https://reviewable.io/reviews/vaadin/flow/4207#-LDlXlQv7-DijwUedyK1:-LDok2JE-Wc-uR_xQEbO:b-61cdsn) ([raw file](https://github.com/vaadin/flow/blob/be39bbeb7771b2504e2d042fa8777233d78aadf7/flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java#L612)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
> assertEquals(1, invokes.get());
> ```

Same here. In the original commit it's `0`.
</blockquote></details>

same like above

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4207)*

**Comment by denis-anisimov** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4207#-:-LDokqf22aaOi0c7Gcg3:bnfp4nl)*

**Comment by ZheSun88** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow/4207#-LDkCh9i8z4HszcwX0a9:-LDoqXtbABDcyRXRYUAQ:brbpcaj) (no related file):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

Test seems to be missing
</blockquote></details>

test has been added

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4207)*

**Pull request merged**
