### PR TITLE
Enable Atmosphere heartbeat

### PR DESCRIPTION
**Pull request by tepi**
Atmosphere's own heartbeat was disabled earlier due to an issue in atmosphere that has been fixed. This patch re-enables it. Also ignores the heartbeat in vaadin-dev-server websocket connection.

Fixes https://github.com/vaadin/flow/issues/17546
Fixes https://github.com/vaadin/flow/issues/17215

### CODE REVIEW

**Comment by mcollovati** [comment]
When using Push with `Transport.WEBSOCKET` i constantly see at every minute the `Connection Lost/Onine` bat on the top and the websocket connection gets closed.

<details>
   <summary>Browser console logs</summary>

```
Wed Oct 18 2023 08:44:28 GMT+0200 (Central European Summer Time) Atmosphere: websocket.onclose
vaadinPush.js?v=bd67c854571cf25d70105c150c9e1dff729717b001954b354427851f266f95a1:3323 Websocket closed, reason: Connection Idle Timeout - wasClean: true
log @ vaadinPush.js?v=bd67c854571cf25d70105c150c9e1dff729717b001954b354427851f266f95a1:3323
warn @ vaadinPush.js?v=bd67c854571cf25d70105c150c9e1dff729717b001954b354427851f266f95a1:3329
_websocket.onclose @ vaadinPush.js?v=bd67c854571cf25d70105c150c9e1dff729717b001954b354427851f266f95a1:1537
vaadinPush.js?v=bd67c854571cf25d70105c150c9e1dff729717b001954b354427851f266f95a1:3323 Wed Oct 18 2023 08:44:28 GMT+0200 (Central European Summer Time) Atmosphere: Firing onClose (closed case)
FlowClient.js:1054 Push connection closed
vaadinPush.js?v=bd67c854571cf25d70105c150c9e1dff729717b001954b354427851f266f95a1:3323 Wed Oct 18 2023 08:44:28 GMT+0200 (Central European Summer Time) Atmosphere: Request already closed, not firing onClose (closed case)
vaadinPush.js?v=bd67c854571cf25d70105c150c9e1dff729717b001954b354427851f266f95a1:3323 Wed Oct 18 2023 08:44:28 GMT+0200 (Central European Summer Time) Atmosphere: invoking .close() on WebSocket object
vaadinPush.js?v=bd67c854571cf25d70105c150c9e1dff729717b001954b354427851f266f95a1:3323 Wed Oct 18 2023 08:44:28 GMT+0200 (Central European Summer Time) Atmosphere: Firing onReconnect
FlowClient.js:774 Reopening push connection
FlowClient.js:213 Reconnecting because of PUSH failure
NC @ FlowClient.js:213
eq @ FlowClient.js:1024
oq @ FlowClient.js:774
Cp @ FlowClient.js:1054
(anonymous) @ FlowClient.js:1029
Eb @ FlowClient.js:463
Hb @ FlowClient.js:920
(anonymous) @ FlowClient.js:663
_f @ vaadinPush.js?v=bd67c854571cf25d70105c150c9e1dff729717b001954b354427851f266f95a1:2846
_invokeFunction @ vaadinPush.js?v=bd67c854571cf25d70105c150c9e1dff729717b001954b354427851f266f95a1:2804
_tryingToReconnect @ vaadinPush.js?v=bd67c854571cf25d70105c150c9e1dff729717b001954b354427851f266f95a1:2285
_open @ vaadinPush.js?v=bd67c854571cf25d70105c150c9e1dff729717b001954b354427851f266f95a1:1035
_reconnectWebSocket @ vaadinPush.js?v=bd67c854571cf25d70105c150c9e1dff729717b001954b354427851f266f95a1:1736
_websocket.onclose @ vaadinPush.js?v=bd67c854571cf25d70105c150c9e1dff729717b001954b354427851f266f95a1:1568
FlowClient.js:212 Reconnect attempt 1 for PUSH
FlowClient.js:1017 Trying to re-establish server connection...
FlowClient.js:854 Sending heartbeat request...
vaadinPush.js?v=bd67c854571cf25d70105c150c9e1dff729717b001954b354427851f266f95a1:3323 Wed Oct 18 2023 08:44:28 GMT+0200 (Central European Summer Time) Atmosphere: Firing onReconnect
logger.js:46 workbox No route found for: /?v-r=heartbeat&v-uiId=4
FlowClient.js:215 Scheduling heartbeat in 300 seconds
vaadinPush.js?v=bd67c854571cf25d70105c150c9e1dff729717b001954b354427851f266f95a1:3323 Invoking executeWebSocket, using URL: ws://localhost:8080/VAADIN/push?v-r=push&v-uiId=4&v-pushId=fa2bca26-6458-4b7b-adbe-ca7d8a7ed68e&X-Atmosphere-tracking-id=8f72a856-8e86-4cf0-992a-36c9594b1d5b&X-Atmosphere-Framework=3.1.2-javascript&X-Atmosphere-Transport=websocket&X-Atmosphere-TrackMessageSize=true&Content-Type=application/json; charset=UTF-8&X-atmo-protocol=true&X-Vaadin-LastSeenServerSyncId=1
vaadinPush.js?v=bd67c854571cf25d70105c150c9e1dff729717b001954b354427851f266f95a1:3323 Wed Oct 18 2023 08:44:33 GMT+0200 (Central European Summer Time) Atmosphere: websocket.onopen
vaadinPush.js?v=bd67c854571cf25d70105c150c9e1dff729717b001954b354427851f266f95a1:3323 Websocket successfully opened
vaadinPush.js?v=bd67c854571cf25d70105c150c9e1dff729717b001954b354427851f266f95a1:3323 Wed Oct 18 2023 08:44:33 GMT+0200 (Central European Summer Time) Atmosphere: websocket.onmessage
vaadinPush.js?v=bd67c854571cf25d70105c150c9e1dff729717b001954b354427851f266f95a1:3323 Wed Oct 18 2023 08:44:33 GMT+0200 (Central European Summer Time) Atmosphere: Firing onReopen
FlowClient.js:212 Push connection re-established using websocket
FlowClient.js:845 Re-established connection to server
vaadinPush.js?v=bd67c854571cf25d70105c150c9e1dff729717b001954b354427851f266f95a1:3323 Wed Oct 18 2023 08:44:33 GMT+0200 (Central European Summer Time) Atmosphere: Firing onReopen
vaadinPush.js?v=bd67c854571cf25d70105c150c9e1dff729717b001954b354427851f266f95a1:3323 Wed Oct 18 2023 08:45:03 GMT+0200 (Central European Summer Time) Atmosphere: websocket.onclose
vaadinPush.js?v=bd67c854571cf25d70105c150c9e1dff729717b001954b354427851f266f95a1:3323 Websocket closed, reason: Connection Idle Timeout - wasClean: true
log @ vaadinPush.js?v=bd67c854571cf25d70105c150c9e1dff729717b001954b354427851f266f95a1:3323
warn @ vaadinPush.js?v=bd67c854571cf25d70105c150c9e1dff729717b001954b354427851f266f95a1:3329
_websocket.onclose @ vaadinPush.js?v=bd67c854571cf25d70105c150c9e1dff729717b001954b354427851f266f95a1:1537
vaadinPush.js?v=bd67c854571cf25d70105c150c9e1dff729717b001954b354427851f266f95a1:3323 Wed Oct 18 2023 08:45:03 GMT+0200 (Central European Summer Time) Atmosphere: Firing onClose (closed case)
FlowClient.js:1054 Push connection closed
vaadinPush.js?v=bd67c854571cf25d70105c150c9e1dff729717b001954b354427851f266f95a1:3323 Wed Oct 18 2023 08:45:03 GMT+0200 (Central European Summer Time) Atmosphere: Request already closed, not firing onClose (closed case)
vaadinPush.js?v=bd67c854571cf25d70105c150c9e1dff729717b001954b354427851f266f95a1:3323 Wed Oct 18 2023 08:45:03 GMT+0200 (Central European Summer Time) Atmosphere: invoking .close() on WebSocket object
vaadinPush.js?v=bd67c854571cf25d70105c150c9e1dff729717b001954b354427851f266f95a1:3323 Wed Oct 18 2023 08:45:03 GMT+0200 (Central European Summer Time) Atmosphere: Firing onReconnect
FlowClient.js:774 Reopening push connection
FlowClient.js:213 Reconnecting because of PUSH failure
NC @ FlowClient.js:213
eq @ FlowClient.js:1024
oq @ FlowClient.js:774
Cp @ FlowClient.js:1054
(anonymous) @ FlowClient.js:1029
Eb @ FlowClient.js:463
Hb @ FlowClient.js:920
(anonymous) @ FlowClient.js:663
_f @ vaadinPush.js?v=bd67c854571cf25d70105c150c9e1dff729717b001954b354427851f266f95a1:2846
_invokeFunction @ vaadinPush.js?v=bd67c854571cf25d70105c150c9e1dff729717b001954b354427851f266f95a1:2804
_tryingToReconnect @ vaadinPush.js?v=bd67c854571cf25d70105c150c9e1dff729717b001954b354427851f266f95a1:2285
_open @ vaadinPush.js?v=bd67c854571cf25d70105c150c9e1dff729717b001954b354427851f266f95a1:1035
_reconnectWebSocket @ vaadinPush.js?v=bd67c854571cf25d70105c150c9e1dff729717b001954b354427851f266f95a1:1736
_websocket.onclose @ vaadinPush.js?v=bd67c854571cf25d70105c150c9e1dff729717b001954b354427851f266f95a1:1568
FlowClient.js:212 Reconnect attempt 1 for PUSH
FlowClient.js:1017 Trying to re-establish server connection...
FlowClient.js:854 Sending heartbeat request...
vaadinPush.js?v=bd67c854571cf25d70105c150c9e1dff729717b001954b354427851f266f95a1:3323 Wed Oct 18 2023 08:45:03 GMT+0200 (Central European Summer Time) Atmosphere: Firing onReconnect
logger.js:46 workbox No route found for: /?v-r=heartbeat&v-uiId=4
FlowClient.js:215 Scheduling heartbeat in 300 seconds
vaadinPush.js?v=bd67c854571cf25d70105c150c9e1dff729717b001954b354427851f266f95a1:3323 Invoking executeWebSocket, using URL: ws://localhost:8080/VAADIN/push?v-r=push&v-uiId=4&v-pushId=fa2bca26-6458-4b7b-adbe-ca7d8a7ed68e&X-Atmosphere-tracking-id=8f72a856-8e86-4cf0-992a-36c9594b1d5b&X-Atmosphere-Framework=3.1.2-javascript&X-Atmosphere-Transport=websocket&X-Atmosphere-TrackMessageSize=true&Content-Type=application/json; charset=UTF-8&X-atmo-protocol=true&X-Vaadin-LastSeenServerSyncId=1
vaadinPush.js?v=bd67c854571cf25d70105c150c9e1dff729717b001954b354427851f266f95a1:3323 Wed Oct 18 2023 08:45:08 GMT+0200 (Central European Summer Time) Atmosphere: websocket.onopen
vaadinPush.js?v=bd67c854571cf25d70105c150c9e1dff729717b001954b354427851f266f95a1:3323 Websocket successfully opened
vaadinPush.js?v=bd67c854571cf25d70105c150c9e1dff729717b001954b354427851f266f95a1:3323 Wed Oct 18 2023 08:45:08 GMT+0200 (Central European Summer Time) Atmosphere: websocket.onmessage
vaadinPush.js?v=bd67c854571cf25d70105c150c9e1dff729717b001954b354427851f266f95a1:3323 Wed Oct 18 2023 08:45:08 GMT+0200 (Central European Summer Time) Atmosphere: Firing onReopen
FlowClient.js:212 Push connection re-established using websocket
FlowClient.js:845 Re-established connection to server
vaadinPush.js?v=bd67c854571cf25d70105c150c9e1dff729717b001954b354427851f266f95a1:3323 Wed Oct 18 2023 08:45:08 GMT+0200 (Central European Summer Time) Atmosphere: Firing onReopen
```
</detail>

**Comment by mcollovati** [comment]
For `Transport.WEBSOCKET`, it also happens in production mode with `forceProductionBuild=true`

**Comment by mcollovati** [comment]
With `Transport.WEBSOCKET_XHR` the websocket connection gets close every minute, but the offline/online indicator is not shown

**Comment by tepi** [comment]
After debugging concluded that Jetty behavior above is not related to this change as such. Instead it is because nowadays Jetty's default WS idle timeout is 30 seconds. See https://github.com/vaadin/flow/issues/17215 for details.

One option to "fix" the other ticket as well would be to set the atmosphere heartbeat ping interval to 20 seconds. Any thoughts on that?

**Review by mcollovati — APPROVED** [review]
LGTM.
Cannot see the reconnection indicator anymore and also session expiration works as expected when `closeIdleSessions=true`.

**Pull request merged**
