### PR TITLE
Allow property being undefined from the server side except interim subrops

### PR DESCRIPTION
**Pull request by denis-anisimov**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3505)

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
Can you explain it a bit the purpose of the change? 
Did I get it right, that now, every property that is set to be synchronized for a model, will be updated disregarding if it was defined on a server or not? 
Will it be the same if, in `PolymerTemplate#initModel`, we put all `allowedPropertyName` elements into `propertyNames`?

I propose to create a test for this, GWT unit test looks possible to create.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3505#-:-L4q0ZjOfwatdY_fw__D:b-uflqqf)*

**Comment by denis-anisimov** [comment]
> Did I get it right, that now, every property that is set to be synchronized for a model, will be updated disregarding if it was defined on a server or not?

Yes.
It's a bug technically.
I'm pretty sure that the intention of the code was to handle properly subproperties. The subproperty looks like "a.b". Then "a" has to be defined from the server since it's expected to be set from the server and it's value should be `StateNode`.
Otherwise there is no server counterpart which can accept change.

But the "b" which is property inside "a" should be synced even if it's not set.
We set explicitly model _properties_ (but not _subproperties_) but we cannot rely on the value presence anyway since it's still possible to remove property (via special API method).
So this code is a bug. The property should be set from the server side but only if it's not a "leaf".

GWT tests nowadays requires a lot of efforts.
But yes, it has sense to write the test for this. 
Don't have time for this now. So it will be postponed.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3505#-:-L4t4nYqaGpyN048wGPU:bvxnaep)*

**Comment by SomeoneToIgnore** [comment]
Sounds nice.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3505#-L4tW6CzKS5ycFBLHXqn:-L4tW6CzKS5ycFBLHXqo:bwccvda) (no related file):*
Putting it here unresolved unless tests are here or there's a ticket for tests creation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3505#-:-L4tW5FCWp9rmofFO_Hb:bs1fr5m)*

**Comment by denis-anisimov** [comment]
Done

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3505#-L4tW6CzKS5ycFBLHXqn:-L4upF34n2gkRjV70fdp:bb6un1j) (no related file):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Putting it here unresolved unless tests are here or there's a ticket for tests creation.
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3505#-:-L4upEHeLH3n2u_Zq1YN:bb6un1j)*

**Comment by SomeoneToIgnore** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3505#-:-L4upkaRDCbPPIDbfFcS:bnfp4nl)*

**Pull request merged**
