### PR TITLE
Refactor the documentation structure

### LINKED ISSUE #1698: EAP feedback from Stephan Diehl
From @ossd 

"is there a getting started documentation, to understand the development?

- why i need a html file
- what can be generated

my first impression is: i see a lot of static strings, the reference between code and html file. the main reason i use vadim framework is to be able to refactor anything without the risk of runtime errors. we used primefaces in the past and the main problem was, that you reference methods in html files that are not in sync with your java file. when you refactor a method, you will not get an compilation error.

when you need strings in html to reference to variables or methods in java, you will not be type safe. when you ask me, this was the main reason for using java for web development and not php, ruby or something other fancy

my questions for the getting started is: how to work without html files or how to generate them or other way to avoid a runtime error."

### PR DESCRIPTION
**Pull request by pleku**
Fixes #1698

Moves all files around to make sure content is aligned into preferable reading order.
Also adds a very shallow introduction / architecture page.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3305)

### CODE REVIEW

**Comment by pleku** [comment]
Review status: 0 of 92 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3305#-L2etnqkZQVG0owtkjBj:-L2etnqkZQVG0owtkjBk:b-vz16u4) (no related file):*
Still need to revise and fix the page ordering and headers for all sections (used in vcom menu).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3305)*

**Comment by denis-anisimov** [comment]
Reviewed 159 of 159 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-documentation/introduction/introduction-overview.asciidoc, line 41 at r1](https://reviewable.io:443/reviews/vaadin/flow/3305#-L2itt_cOAVTNdIrUbau:-L2itt_cOAVTNdIrUbav:b-rukard) ([raw file](https://github.com/vaadin/flow/blob/2be745e564a2af225f1c2219c937283404168505/flow-documentation/introduction/introduction-overview.asciidoc#L41)):*
> // CODE SNIPPET //

Is it supposed to be filled later on?
Is it OK to keep it as is for now?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3305)*

**Comment by pleku** [comment]
Review status: 70 of 93 files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-documentation/introduction/introduction-overview.asciidoc, line 41 at r1](https://reviewable.io:443/reviews/vaadin/flow/3305#-L2itt_cOAVTNdIrUbau:-L2tRCA4LQ2LsjiWejEQ:b-ueedzu) ([raw file](https://github.com/vaadin/flow/blob/2be745e564a2af225f1c2219c937283404168505/flow-documentation/introduction/introduction-overview.asciidoc#L41)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> // CODE SNIPPET //

Is it supposed to be filled later on?
Is it OK to keep it as is for now?
</blockquote></details>

Yeah I have separate list of things to fix in the documentation content, this one is there and I just with to get the structure change now in so that I don't have to keep on fixing merge conflicts...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3305)*

**Comment by pleku** [comment]
Review status: 70 of 93 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3305#-L2etnqkZQVG0owtkjBj:-L2tRMoNHvDngpTGG_z8:bb6un1j) (no related file):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Still need to revise and fix the page ordering and headers for all sections (used in vcom menu).
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3305)*

**Comment by denis-anisimov** [comment]
Reviewed 13 of 159 files at r1, 22 of 26 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3305)*

**Pull request merged**
