### PR TITLE
refactor: use StaticFileHandler as a service

### PR DESCRIPTION
**Pull request by denis-anisimov**
Part of vaadin/osgi#50

### CODE REVIEW

**Review by caalador — DISMISSED** [review]

**Comment by caalador** [comment]
```
java.lang.IllegalStateException: Found several implementations in the classpath for ApplicationConfigurationFactory SPI: [class com.vaadin.flow.server.startup.DefaultApplicationConfigurationFactory, class com.vaadin.flow.server.startup.LookupServletContainerInitializerTest$TestApplicationConfigurationFactory]. Only one implementation should be registered. Use lookupAll to get all instances of the given type.
	at com.vaadin.flow.di.LookupInitializer.ensureService(LookupInitializer.java:321)
	at com.vaadin.flow.di.LookupInitializer.initialize(LookupInitializer.java:275)
	at com.vaadin.flow.server.startup.LookupServletContainerInitializer.process(LookupServletContainerInitializer.java:85)
	at com.vaadin.flow.server.startup.LookupServletContainerInitializerTest.mockLookup(LookupServletContainerInitializerTest.java:223)
	at com.vaadin.flow.server.startup.LookupServletContainerInitializerTest.mockLookup(LookupServletContainerInitializerTest.java:232)
	at com.vaadin.flow.server.startup.LookupServletContainerInitializerTest.processApplicationConfigurationFactory_factoryIsProvided_providedFactoryIsCreated(LookupServletContainerInitializerTest.java:160)
```

**Comment by denis-anisimov** [comment]
> ```
> java.lang.IllegalStateException: Found several implementations in the classpath for ApplicationConfigurationFactory SPI: [class com.vaadin.flow.server.startup.DefaultApplicationConfigurationFactory, class com.vaadin.flow.server.startup.LookupServletContainerInitializerTest$TestApplicationConfigurationFactory]. Only one implementation should be registered. Use lookupAll to get all instances of the given type.
> 	at com.vaadin.flow.di.LookupInitializer.ensureService(LookupInitializer.java:321)
> 	at com.vaadin.flow.di.LookupInitializer.initialize(LookupInitializer.java:275)
> 	at com.vaadin.flow.server.startup.LookupServletContainerInitializer.process(LookupServletContainerInitializer.java:85)
> 	at com.vaadin.flow.server.startup.LookupServletContainerInitializerTest.mockLookup(LookupServletContainerInitializerTest.java:223)
> 	at com.vaadin.flow.server.startup.LookupServletContainerInitializerTest.mockLookup(LookupServletContainerInitializerTest.java:232)
> 	at com.vaadin.flow.server.startup.LookupServletContainerInitializerTest.processApplicationConfigurationFactory_factoryIsProvided_providedFactoryIsCreated(LookupServletContainerInitializerTest.java:160)
> ```

Done (I hope).

**Comment by caalador** [comment]
Now Lit template tests fail `LitTemplateParserImplTest`

**Comment by denis-anisimov** [comment]
> Now Lit template tests fail `LitTemplateParserImplTest`

yeah, yeah, it will be a long journey. All the modules which use VaadinServlet for some reason may fail.
So there will be many iterations.

**Review by caalador — APPROVED** [review]

**Pull request merged**
