### PR TITLE
chore: Remove unnecessary mkdirp dependency

### PR DESCRIPTION
**Pull request by Artur-**
mkdirSync in Node has had recursive:true support since Node 10

### CODE REVIEW

**Review by czp13 — APPROVED** [review]
Seems good/safe to me.

There are still a couple of dependencies in other sub projects/dirs:
```
vite-production/
flow-client/
test-dev-bundle/
dev-bundle/
test-prod-bundle/
test-npm/
test-pnpm/
vite-basics/
vite-context-path/
```

which have `mkdirp` dependency and usage, mostly in `package.jsons`. I assume those dependencies are still needed.

**Comment by Artur-** [comment]
They would need a `mvn clean install` run so that their package.jsons are cleaned up

**Comment by czp13** [comment]
> They would need a `mvn clean install` run so that their package.jsons are cleaned up
Thank you, all of them was cleaned out.

**Comment by Artur-** [comment]
If you have the updated versions, push them to this same pr

**Comment by Artur-** [comment]
In fact, let's update them after all the deps upgrades have been merged

**Comment by czp13** [comment]
Ok, let's check afterwards on the `main` branch.

Plus I was wrong  :(. Maybe the files were not indexed or I misstyped, but last time I did not see references for `mkdirp`.

 
But now searching again for double check, I still see:
image

Could you check please if in your environment the `mkdirp` dependencies have been cleared out after 
`mvn clean install (-dSkipTests)`?

Plus totally unrelated but I have an error for `Test Dev Bundle` in this week, which I did not have before:
```
[INFO] using '/Users/pczuczor/.nvm/versions/node/v18.12.1/bin/npm --no-update-notifier --no-audit --scripts-prepend-node-path=true --ignore-scripts install' for frontend package installation
[ERROR] Command `/Users/pczuczor/.nvm/versions/node/v18.12.1/bin/npm --no-update-notifier --no-audit --scripts-prepend-node-path=true --ignore-scripts install` failed:
npm ERR! Invalid Version: 24.2.0.alpha1.0
```

I will open a ticket if I can not figure it out.

**Pull request merged**
