### PR TITLE
Update component tutorial after flow-components removed

### PR DESCRIPTION
**Pull request by caalador**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3047)

### CODE REVIEW

**Comment by ZheSun88** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3047)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-documentation/flow-components/tutorial-flow-components-setup.asciidoc, line 68 at r2](https://reviewable.io:443/reviews/vaadin/flow/3047#-Kzi10vR1byTmfAk3pv5:-Kzi10vR1byTmfAk3pv6:b-lzoj43) ([raw file](https://github.com/vaadin/flow/blob/34d5dcc92789bebf12c03b79ee9b28a52f6000df/flow-documentation/flow-components/tutorial-flow-components-setup.asciidoc#L68)):*
> ```AsciiDoc
> 
> The components are released at their own pace as needed so the compliant Flow version should be
> confirmed from ...?
> ```

Should it be finished?

---

*[flow-documentation/flow-components/tutorial-flow-components-setup.asciidoc, line 75 at r2](https://reviewable.io:443/reviews/vaadin/flow/3047#-Kzi1_bZCHA5h8Md5y-1:-Kzi1_bZCHA5h8Md5y-2:b-ud93cx) ([raw file](https://github.com/vaadin/flow/blob/34d5dcc92789bebf12c03b79ee9b28a52f6000df/flow-documentation/flow-components/tutorial-flow-components-setup.asciidoc#L75)):*
> ```AsciiDoc
> ----
> <properties>
>     <component.id>vaadin-button-flow</component.id>
> ```

Looks a bit weird. Can you just put it into `dependency` directly? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3047)*

**Comment by caalador** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-documentation/flow-components/tutorial-flow-components-setup.asciidoc, line 68 at r2](https://reviewable.io:443/reviews/vaadin/flow/3047#-Kzi10vR1byTmfAk3pv5:-Kzi1yNHUWuAAqyMFJjx:bppjthl) ([raw file](https://github.com/vaadin/flow/blob/34d5dcc92789bebf12c03b79ee9b28a52f6000df/flow-documentation/flow-components/tutorial-flow-components-setup.asciidoc#L68)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Should it be finished?
</blockquote></details>

It should, but I have no idea where this would/could/will be documented...

---

*[flow-documentation/flow-components/tutorial-flow-components-setup.asciidoc, line 75 at r2](https://reviewable.io:443/reviews/vaadin/flow/3047#-Kzi1_bZCHA5h8Md5y-1:-Kzi1odq4upzwt6kahJu:bpechmv) ([raw file](https://github.com/vaadin/flow/blob/34d5dcc92789bebf12c03b79ee9b28a52f6000df/flow-documentation/flow-components/tutorial-flow-components-setup.asciidoc#L75)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Looks a bit weird. Can you just put it into `dependency` directly? 
</blockquote></details>

I could, but I would want to highlight that any of the components is applicable, so if you have an idea for that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3047)*

**Comment by SomeoneToIgnore** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-documentation/flow-components/tutorial-flow-components-setup.asciidoc, line 68 at r2](https://reviewable.io:443/reviews/vaadin/flow/3047#-Kzi10vR1byTmfAk3pv5:-Kzi2HZolt8Ui6_PDZ6d:b-mvfsti) ([raw file](https://github.com/vaadin/flow/blob/34d5dcc92789bebf12c03b79ee9b28a52f6000df/flow-documentation/flow-components/tutorial-flow-components-setup.asciidoc#L68)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

It should, but I have no idea where this would/could/will be documented...
</blockquote></details>

We have `platform` bom now with all compliant versions and webjars bom: https://github.com/vaadin/platform/blob/master/vaadin-bom/pom.xml

We can rewrite the tutorial so that 
1. This bom is used (not the webjars one, like now)
2. Say that all up-to-date compliant component versions can be found there.

---

*[flow-documentation/flow-components/tutorial-flow-components-setup.asciidoc, line 75 at r2](https://reviewable.io:443/reviews/vaadin/flow/3047#-Kzi1_bZCHA5h8Md5y-1:-Kzi2dCtRzwGZuLd5m23:b-7buvvf) ([raw file](https://github.com/vaadin/flow/blob/34d5dcc92789bebf12c03b79ee9b28a52f6000df/flow-documentation/flow-components/tutorial-flow-components-setup.asciidoc#L75)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

I could, but I would want to highlight that any of the components is applicable, so if you have an idea for that.
</blockquote></details>

We can say it with text, no need to twist maven configuration for this.
I think it would be more beneficial, since people may be copying the actual xml into their poms.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3047)*

**Comment by caalador** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-documentation/flow-components/tutorial-flow-components-setup.asciidoc, line 68 at r2](https://reviewable.io:443/reviews/vaadin/flow/3047#-Kzi10vR1byTmfAk3pv5:-Kzi45rYFn-vBNBQIuA3:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/34d5dcc92789bebf12c03b79ee9b28a52f6000df/flow-documentation/flow-components/tutorial-flow-components-setup.asciidoc#L68)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

We have `platform` bom now with all compliant versions and webjars bom: https://github.com/vaadin/platform/blob/master/vaadin-bom/pom.xml

We can rewrite the tutorial so that 
1. This bom is used (not the webjars one, like now)
2. Say that all up-to-date compliant component versions can be found there.
</blockquote></details>

Done.

---

*[flow-documentation/flow-components/tutorial-flow-components-setup.asciidoc, line 75 at r2](https://reviewable.io:443/reviews/vaadin/flow/3047#-Kzi1_bZCHA5h8Md5y-1:-Kzi468bqqdWahC-BVKB:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/34d5dcc92789bebf12c03b79ee9b28a52f6000df/flow-documentation/flow-components/tutorial-flow-components-setup.asciidoc#L75)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

We can say it with text, no need to twist maven configuration for this.
I think it would be more beneficial, since people may be copying the actual xml into their poms.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3047)*

**Comment by SomeoneToIgnore** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3047#-:-Kzi4i7MmNuUSWAcXxuA:bnfp4nl)*

**Pull request merged**
