### PR TITLE
Port Grid selection tests from FW8

### PR DESCRIPTION
**Pull request by gilberto-torrezan**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/2696)

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
Does it make any sense to fix any issues here? 
Usually Dennis refused to do so because he was just porting the code.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2696#-:-Kwe8vW9rqLrWUxKQ2Zy:b5efxu5)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2696)*

**Comment by SomeoneToIgnore** [comment]
*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 311 at r1](https://reviewable.io:443/reviews/vaadin/flow/2696#-Kwe9ALVjwudnFkNuIhz:-Kwe9ALVjwudnFkNuIi-:b25dqz6) ([raw file](https://github.com/vaadin/flow/blob/9b5fc447656a88c0ccd60400eae31a66e58ec83c/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L311)):*
> ```Java
>                     @Override
>                     public void deselectAll() {
>                         updateSelection(Collections.emptySet(), selected);
> ```

Does not look like a test migration.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2696)*

**Comment by gilberto-torrezan** [comment]
Well, the fix for one of the tests was a single line in the Grid. I don't want to create a whole bureaucratic process just for that line.

There are two ignored (but compilable)  tests that will be fixed later. And two tests weren't ported because they don't apply anymore to the new Grid.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2696#-:-Kwe9BPqNS8Iw_h8m3q4:b-4xz0yc)*

**Comment by gilberto-torrezan** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 311 at r1](https://reviewable.io:443/reviews/vaadin/flow/2696#-Kwe9ALVjwudnFkNuIhz:-Kwe9nhTki0oLjblWZl9:b-15102o) ([raw file](https://github.com/vaadin/flow/blob/9b5fc447656a88c0ccd60400eae31a66e58ec83c/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L311)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Does not look like a test migration.
</blockquote></details>

That was a bug fixing, yes. Trivial enough to be part of this ticket IMO.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2696)*

**Comment by SomeoneToIgnore** [comment]
*[flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java, line 311 at r1](https://reviewable.io:443/reviews/vaadin/flow/2696#-Kwe9ALVjwudnFkNuIhz:-KweA-kTrdn_vjimX_b8:bos7opg) ([raw file](https://github.com/vaadin/flow/blob/9b5fc447656a88c0ccd60400eae31a66e58ec83c/flow-components-parent/flow-components/src/main/java/com/vaadin/ui/grid/Grid.java#L311)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

That was a bug fixing, yes. Trivial enough to be part of this ticket IMO.
</blockquote></details>

Up to you.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2696)*

**Comment by SomeoneToIgnore** [comment]
What I've meant is that the tests are strange:  `GridMultiSelectionModelTest` has unused fields, for instance.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2696#-:-KweA814wP0lzVqlc9cc:b-l24411)*

**Comment by gilberto-torrezan** [comment]
Oh, those need to be fixed. They are leftovers from the migration. Oddly enough Eclipse didn't show them to me as unused.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2696#-:-KweAY1oNUH0w2jNkpfM:bguhzwr)*

**Comment by SomeoneToIgnore** [comment]
Nice, I'll check the files and mark the issues then.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2696#-:-KweArpZ-mcBz9j5qTLs:bo95anc)*

**Comment by SomeoneToIgnore** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/grid/GridDelegatesToSelectionModelTest.java, line 35 at r1](https://reviewable.io:443/reviews/vaadin/flow/2696#-KweB3vspc037xsyvuHy:-KweB3vspc037xsyvuHz:b-s3hmk9) ([raw file](https://github.com/vaadin/flow/blob/9b5fc447656a88c0ccd60400eae31a66e58ec83c/flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/grid/GridDelegatesToSelectionModelTest.java#L35)):*
> ```Java
>     private class CustomGrid extends Grid<String> {
>         CustomGrid() {
>             super();
> ```

Not needed.

---

*[flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/grid/GridMultiSelectionModelTest.java, line 52 at r1](https://reviewable.io:443/reviews/vaadin/flow/2696#-KweB8AfoL1Sw9EwH8AP:-KweB8AfoL1Sw9EwH8AQ:bheienm) ([raw file](https://github.com/vaadin/flow/blob/9b5fc447656a88c0ccd60400eae31a66e58ec83c/flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/grid/GridMultiSelectionModelTest.java#L52)):*
> ```Java
> public class GridMultiSelectionModelTest {
> 
>     public static final Person PERSON_C = new Person("c", 3);
> ```

All three can be private.

---

*[flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/grid/GridMultiSelectionModelTest.java, line 62 at r1](https://reviewable.io:443/reviews/vaadin/flow/2696#-KweBCmvo8kpeXADkKMb:-KweBCmvo8kpeXADkKMc:b-8rujr7) ([raw file](https://github.com/vaadin/flow/blob/9b5fc447656a88c0ccd60400eae31a66e58ec83c/flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/grid/GridMultiSelectionModelTest.java#L62)):*
> ```Java
>     private AtomicInteger events;
> 
>     public final Map<String, Boolean> generatedData = new LinkedHashMap<>();
> ```

Unused, not needed.

---

*[flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/grid/GridMultiSelectionModelTest.java, line 65 at r1](https://reviewable.io:443/reviews/vaadin/flow/2696#-KweBEpbPPWjhTQ4gyMp:-KweBEpbPPWjhTQ4gyMq:b-ng6tfd) ([raw file](https://github.com/vaadin/flow/blob/9b5fc447656a88c0ccd60400eae31a66e58ec83c/flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/grid/GridMultiSelectionModelTest.java#L65)):*
> ```Java
> 
>     @Before
>     public void generateData() {
> ```

Unused, unnecessary.

---

*[flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/grid/GridMultiSelectionModelTest.java, line 92 at r1](https://reviewable.io:443/reviews/vaadin/flow/2696#-KweBLV1AUQhda3RqEyc:-KweBLV1AUQhda3RqEyd:bd3k6ci) ([raw file](https://github.com/vaadin/flow/blob/9b5fc447656a88c0ccd60400eae31a66e58ec83c/flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/grid/GridMultiSelectionModelTest.java#L92)):*
> ```Java
>     @Test(expected = IllegalStateException.class)
>     @Ignore
>     // Ignored because there's no mechanism to disallow selections yet
> ```

In case we have a ticket, would be nice to to have a reference here, same for all @Ignore

---

*[flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/grid/GridMultiSelectionModelTest.java, line 93 at r1](https://reviewable.io:443/reviews/vaadin/flow/2696#-KweBTVeOFlQ20l1fSSZ:-KweBTVeOFlQ20l1fSS_:bs4se4) ([raw file](https://github.com/vaadin/flow/blob/9b5fc447656a88c0ccd60400eae31a66e58ec83c/flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/grid/GridMultiSelectionModelTest.java#L93)):*
> Excpetion
Typo

---

*[flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/grid/GridMultiSelectionModelTest.java, line 133 at r1](https://reviewable.io:443/reviews/vaadin/flow/2696#-KweBx-iWSqnkfPrK1Od:-KweBx-iWSqnkfPrK1Oe:b-f1dxop) ([raw file](https://github.com/vaadin/flow/blob/9b5fc447656a88c0ccd60400eae31a66e58ec83c/flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/grid/GridMultiSelectionModelTest.java#L133)):*
> ```Java
>         assertFalse(customGrid.getSelectionModel().getFirstSelectedItem()
>                 .isPresent());
>         assertEquals(Arrays.asList(), selectionChanges);
> ```

Technically this is less performant than `Collections.emptyList()` and there are lots of `Arrays.asList(single)` that can be replaced with `Collections.singletonList(single)`, but it's an overkill, imo :)

---

*[flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/grid/GridMultiSelectionModelTest.java, line 502 at r1](https://reviewable.io:443/reviews/vaadin/flow/2696#-KweBkaaGy90GRZWngpA:-KweBkaaGy90GRZWngpB:b-jvnkph) ([raw file](https://github.com/vaadin/flow/blob/9b5fc447656a88c0ccd60400eae31a66e58ec83c/flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/grid/GridMultiSelectionModelTest.java#L502)):*
> ```Java
>         String value = "foo";
> 
>         Grid<String> grid = new Grid<String>();
> ```

Diamonds can be used here and  in `new LinkedHashSet<String>` below.

---

*[flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/grid/GridNoSelectionModelTest.java, line 35 at r1](https://reviewable.io:443/reviews/vaadin/flow/2696#-KweCEZ1FEsHYOVwNu6M:-KweCEZ1FEsHYOVwNu6N:bkwwkba) ([raw file](https://github.com/vaadin/flow/blob/9b5fc447656a88c0ccd60400eae31a66e58ec83c/flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/grid/GridNoSelectionModelTest.java#L35)):*
> ```Java
> public class GridNoSelectionModelTest {
> 
>     public static final Person PERSON_C = new Person("c", 3);
> ```

All three can be `private`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2696)*

**Comment by gilberto-torrezan** [comment]
Review status: 3 of 6 files reviewed at latest revision, 11 unresolved discussions.

---

*[flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/grid/GridDelegatesToSelectionModelTest.java, line 35 at r1](https://reviewable.io:443/reviews/vaadin/flow/2696#-KweB3vspc037xsyvuHy:-KweCoRFUHTrWl1iLfJa:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/9b5fc447656a88c0ccd60400eae31a66e58ec83c/flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/grid/GridDelegatesToSelectionModelTest.java#L35)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Not needed.
</blockquote></details>

Done.

---

*[flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/grid/GridMultiSelectionModelTest.java, line 52 at r1](https://reviewable.io:443/reviews/vaadin/flow/2696#-KweB8AfoL1Sw9EwH8AP:-KweCwoFT7pwQ0vuXTI-:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/9b5fc447656a88c0ccd60400eae31a66e58ec83c/flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/grid/GridMultiSelectionModelTest.java#L52)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

All three can be private.
</blockquote></details>

Done.

---

*[flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/grid/GridMultiSelectionModelTest.java, line 62 at r1](https://reviewable.io:443/reviews/vaadin/flow/2696#-KweBCmvo8kpeXADkKMb:-KweCy2dCp-v71XWPESL:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/9b5fc447656a88c0ccd60400eae31a66e58ec83c/flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/grid/GridMultiSelectionModelTest.java#L62)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Unused, not needed.
</blockquote></details>

Done.

---

*[flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/grid/GridMultiSelectionModelTest.java, line 65 at r1](https://reviewable.io:443/reviews/vaadin/flow/2696#-KweBEpbPPWjhTQ4gyMp:-KweCyRzgo7GdP7J3KOz:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/9b5fc447656a88c0ccd60400eae31a66e58ec83c/flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/grid/GridMultiSelectionModelTest.java#L65)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Unused, unnecessary.
</blockquote></details>

Done.

---

*[flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/grid/GridMultiSelectionModelTest.java, line 92 at r1](https://reviewable.io:443/reviews/vaadin/flow/2696#-KweBLV1AUQhda3RqEyc:-KweFQdmhoTfq9GMbVAN:b-330pt6) ([raw file](https://github.com/vaadin/flow/blob/9b5fc447656a88c0ccd60400eae31a66e58ec83c/flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/grid/GridMultiSelectionModelTest.java#L92)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

In case we have a ticket, would be nice to to have a reference here, same for all @Ignore
</blockquote></details>

This test was removed.

---

*[flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/grid/GridMultiSelectionModelTest.java, line 93 at r1](https://reviewable.io:443/reviews/vaadin/flow/2696#-KweBTVeOFlQ20l1fSSZ:-KweHh9ZkehUMfZxQdFk:bss4a2b) ([raw file](https://github.com/vaadin/flow/blob/9b5fc447656a88c0ccd60400eae31a66e58ec83c/flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/grid/GridMultiSelectionModelTest.java#L93)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

> Excpetion
Typo
</blockquote></details>

Removed.

---

*[flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/grid/GridMultiSelectionModelTest.java, line 133 at r1](https://reviewable.io:443/reviews/vaadin/flow/2696#-KweBx-iWSqnkfPrK1Od:-KweH2hL1Q_IsR_1Alo0:bbsw66i) ([raw file](https://github.com/vaadin/flow/blob/9b5fc447656a88c0ccd60400eae31a66e58ec83c/flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/grid/GridMultiSelectionModelTest.java#L133)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Technically this is less performant than `Collections.emptyList()` and there are lots of `Arrays.asList(single)` that can be replaced with `Collections.singletonList(single)`, but it's an overkill, imo :)
</blockquote></details>

Done. And done.

---

*[flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/grid/GridMultiSelectionModelTest.java, line 502 at r1](https://reviewable.io:443/reviews/vaadin/flow/2696#-KweBkaaGy90GRZWngpA:-KweHD6CEypK0mlBH9JR:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/9b5fc447656a88c0ccd60400eae31a66e58ec83c/flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/grid/GridMultiSelectionModelTest.java#L502)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Diamonds can be used here and  in `new LinkedHashSet<String>` below.
</blockquote></details>

Done.

---

*[flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/grid/GridNoSelectionModelTest.java, line 35 at r1](https://reviewable.io:443/reviews/vaadin/flow/2696#-KweCEZ1FEsHYOVwNu6M:-KweHEp47p2HS-rMpv6m:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/9b5fc447656a88c0ccd60400eae31a66e58ec83c/flow-components-parent/flow-components-test/src/test/java/com/vaadin/flow/tests/components/grid/GridNoSelectionModelTest.java#L35)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

All three can be `private`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2696)*

**Comment by SomeoneToIgnore** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2696#-:-KweIiaGHqkqIxiS1mS0:bnfp4nl)*

**Pull request merged**
