### PR TITLE
Fixed url-mappings of the Spring servlet when it is not mapped to /*

### PR DESCRIPTION
**Pull request by pontusbostrom**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3051)

### CODE REVIEW

**Comment by caalador** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3051#-L-Gx5Lx8npEZ8nLhQPo:-L-Gx5Lx8npEZ8nLhQPp:b6e5v39) (no related file):*
Would there happen to be a test for this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3051)*

**Comment by pontusbostrom** [comment]
*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3051#-L-Gx5Lx8npEZ8nLhQPo:-L-Sr5aovWPfZLvdfpPz:b-hgtaun) (no related file):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Would there happen to be a test for this?
</blockquote></details>

I didn't make any test. I don't even know how to create a test for this feature that would be suitable for automated testing. Also, I will not have much time to work on this feature in the near future, unfortunately

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3051)*

**Comment by caalador** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3051#-L-Gx5Lx8npEZ8nLhQPo:-L-VxrUZRKJaE9rg9KoV:b19wgn7) (no related file):*
<details><summary><i>Previously, pontusbostrom wrote…</i></summary><blockquote>

I didn't make any test. I don't even know how to create a test for this feature that would be suitable for automated testing. Also, I will not have much time to work on this feature in the near future, unfortunately
</blockquote></details>

Ok. I'll look into creating a test for this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3051)*

**Comment by caalador** [comment]
Closing this ticket as outdated as we no longer use special servlet mappings.

**Pull request closed without merging**
