### PR TITLE
chore: update selenium version to match TB used

### PR DESCRIPTION
**Pull request by ZheSun88**
## Description

Please list all relevant dependencies in this section and provide summary of the change, motivation and context.

Fixes # (issue)

## Type of change

- [ ] Bugfix
- [ ] Feature

## Checklist

- [ ] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [ ] I have added a description following the guideline.
- [ ] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

### CODE REVIEW

**Review by mshabarov — APPROVED** [review]

**Comment by mcollovati** [comment]
Seems like that for version 4.x of selenium the artifact `selenium-server-standalone-x.y.z.jar` does not exist anymore.
It may have been renamed to `selenium-server-x.y.z.jar`, but the name is hardcoded in selenium tunnel  implementation used by intern 
https://github.com/theintern/digdug/blob/c5beadf1fca501afad32579f643eb8e6a46b11b1/src/SeleniumTunnel.ts#L144

**Comment by ZheSun88** [comment]
yeah. you are correct.. standalone has been dropped totally.. 

checking one [SOF answer](https://stackoverflow.com/questions/52835958/intern-selenium-error-bug-suiteend-was-received-for-invalid-session), looks like we can get rid of something.. (thanks Guille)

>Also note that you don’t need selenium-server-standalone for Intern tests; by default Intern downloads Selenium and the required WebDriver tunnels on its own, and also starts and shuts down its own instance of Selenium

**Comment by ZheSun88** [comment]
by the way, this change looks not related to the failure in snapshot.. so probably we can leave this one for now.. 
but this selenium version need to be updated somehow.

**Review by taefi — APPROVED** [review]

**Review by taefi — CHANGES_REQUESTED** [review]
Is there such a version as `4.3.0`? Currently the build fails since it cannot download https://selenium-release.storage.googleapis.com/4.3/selenium-server-standalone-4.3.0.jar

**Pull request closed without merging**
