### PR TITLE
Page methods added: setLocation() / open()

### PR DESCRIPTION
**Pull request by Lozadaa**
fix to issue #4869 

Sorry for the spam, I had problems with the previous repository! But it's all OK with this!

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/5131)

### CODE REVIEW

**Comment by Lozadaa** [comment]
pls review @ZheSun88

**Comment by ZheSun88** [comment]
Hi @Lozadaa ,

Thanks for your contribution. 

I had a look at your PR, but I do have a few concerns:
1) by checking the original issue, if i understand correctly, the APIs here should be the same in flow and framework. From this point of view, `setLocation(String)` is fine, but the `open()` method in framework looks like https://github.com/vaadin/framework/blob/master/server/src/main/java/com/vaadin/server/Page.java#L1180, which is different than here. 

2) the PR is missing tests. 

I will ask a senior developer to have a quick look also. -> @denis-anisimov Could you help me a bit?  

Thanks again.

**Comment by Lozadaa** [comment]
@ZheSun88 Hi thanks for your reply.

1. i'll wait for reply of @denis-anisimov 
2. What is the procedure to create test? do you have any test example to use?


thanks to both.

Greetings

**Comment by denis-anisimov** [comment]
Closed in favour of https://github.com/vaadin/flow/issues/5166

**Pull request closed without merging**
