### PR TITLE
Avoid sending extra data for "inactive" StateNodes

### PR DESCRIPTION
**Pull request by denis-anisimov**
Fix for #3208

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3213)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
The PR needs tests

**Comment by gilberto-torrezan** [comment]
Reviewed 2 of 6 files at r1, 1 of 6 files at r3, 1 of 2 files at r4.
Review status: 4 of 9 files reviewed at latest revision, 6 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/internal/StateNode.java, line 357 at r4](https://reviewable.io:443/reviews/vaadin/flow/3213#-L1RrsqunDpJwwBfqRmD:-L1RrsqunDpJwwBfqRmE:b-sbpmiz) ([raw file](https://github.com/vaadin/flow/blob/fbe5f2b79e459bbd027fb09a7f1a1fca916e7bd7/flow-server/src/main/java/com/vaadin/flow/internal/StateNode.java#L357)):*
> ```Java
>                 doCollectChanges(collector, initialFeatures);
>             } else {
>                 doCollectChanges(collector, getDisalowFeatures());
> ```

I need a background explanation here: we do we send "disallowed features" when the node is not active ?

---

*[flow-server/src/main/java/com/vaadin/flow/internal/StateNode.java, line 650 at r4](https://reviewable.io:443/reviews/vaadin/flow/3213#-L1RnFZH9uRXuHJbCiOf:-L1RnFZH9uRXuHJbCiOg:bdk2gdg) ([raw file](https://github.com/vaadin/flow/blob/fbe5f2b79e459bbd027fb09a7f1a1fca916e7bd7/flow-server/src/main/java/com/vaadin/flow/internal/StateNode.java#L650)):*
> ```Java
>     }
> 
>     private boolean isInactive() {
> ```

Since the `isInactive()` method does more things than just returning the `isInactive` flag, I suggest making the method name a bit more explanatory. Since it is a private method, there's no harm in making it more verbose.

Suggestions: `isPartOfInactiveChain`, `isInactiveOrHasInactiveParent` or something like that.

---

*[flow-server/src/main/java/com/vaadin/flow/internal/StateTree.java, line 213 at r4](https://reviewable.io:443/reviews/vaadin/flow/3213#-L1RqhYcPTOPKcjUBjOF:-L1RqhYcPTOPKcjUBjOG:b-22pykh) ([raw file](https://github.com/vaadin/flow/blob/fbe5f2b79e459bbd027fb09a7f1a1fca916e7bd7/flow-server/src/main/java/com/vaadin/flow/internal/StateTree.java#L213)):*
> ```Java
>      */
>     public void collectChanges(Consumer<NodeChange> collector) {
>         Set<StateNode> dirtyNodes = collectDirtyNodes();
> ```

Related to the comment from Sonar: what can't you use the `dirtyNodes` field? Or if the field may be not up-to-date at this point, why is it not reassigned?

---

*[flow-server/src/main/java/com/vaadin/flow/internal/StateTree.java, line 219 at r4](https://reviewable.io:443/reviews/vaadin/flow/3213#-L1RpiYhGgswZq8U9Li-:-L1RpiYhGgswZq8U9Li0:blzbaw4) ([raw file](https://github.com/vaadin/flow/blob/fbe5f2b79e459bbd027fb09a7f1a1fca916e7bd7/flow-server/src/main/java/com/vaadin/flow/internal/StateTree.java#L219)):*
> ```Java
>         // TODO fire preCollect events
> 
>         dirtyNodes.forEach(node -> node.collectChanges(collector));
> ```

You can unify `StateNode::updateActiveState` and `node.collectChanges` in a single private method to avoid iterating over the `Set` twice.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3213)*

**Comment by denis-anisimov** [comment]
Review status: 4 of 9 files reviewed at latest revision, 6 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/internal/StateNode.java, line 357 at r4](https://reviewable.io:443/reviews/vaadin/flow/3213#-L1RrsqunDpJwwBfqRmD:-L1Rsu2uXGCw5jSiWu3t:b-isvey7) ([raw file](https://github.com/vaadin/flow/blob/fbe5f2b79e459bbd027fb09a7f1a1fca916e7bd7/flow-server/src/main/java/com/vaadin/flow/internal/StateNode.java#L357)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

I need a background explanation here: we do we send "disallowed features" when the node is not active ?
</blockquote></details>

`VisibilityData` is the only disallowed feature at the moment.
It should send it's data to be able to hide the node when it's value set to `false` so the client side does something.

Disallow is may be a bad word here. Those are features which makes the node inactive.
But I can't find a better word here.

---

*[flow-server/src/main/java/com/vaadin/flow/internal/StateNode.java, line 650 at r4](https://reviewable.io:443/reviews/vaadin/flow/3213#-L1RnFZH9uRXuHJbCiOf:-L1Rt_Xm9yCIdybBywsx:bm0k01h) ([raw file](https://github.com/vaadin/flow/blob/fbe5f2b79e459bbd027fb09a7f1a1fca916e7bd7/flow-server/src/main/java/com/vaadin/flow/internal/StateNode.java#L650)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Since the `isInactive()` method does more things than just returning the `isInactive` flag, I suggest making the method name a bit more explanatory. Since it is a private method, there's no harm in making it more verbose.

Suggestions: `isPartOfInactiveChain`, `isInactiveOrHasInactiveParent` or something like that.
</blockquote></details>

The method is not just a getter. That's true. But I don't like any of suggested names.
Long names are even worse than the existing one. They don't really tell me what they really does but scare me. I would better go into impl and check what it really does than get it from this long useless name.

May be the `isInactive` field  name should be changed instead. But then I don't see a convenient name for it.

---

*[flow-server/src/main/java/com/vaadin/flow/internal/StateTree.java, line 213 at r4](https://reviewable.io:443/reviews/vaadin/flow/3213#-L1RqhYcPTOPKcjUBjOF:-L1RwBi_HE7zNm8H1q_9:b-rk0jat) ([raw file](https://github.com/vaadin/flow/blob/fbe5f2b79e459bbd027fb09a7f1a1fca916e7bd7/flow-server/src/main/java/com/vaadin/flow/internal/StateTree.java#L213)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Related to the comment from Sonar: what can't you use the `dirtyNodes` field? Or if the field may be not up-to-date at this point, why is it not reassigned?
</blockquote></details>

The SQ comment may be fixed. It's valid.
But `collectDirtyNodes()` does more than just returns `dirtyNodes` field.
It returns the `dirtyNodes` value and resets the `dirtyNodes` field to the empty set.

---

*[flow-server/src/main/java/com/vaadin/flow/internal/StateTree.java, line 219 at r4](https://reviewable.io:443/reviews/vaadin/flow/3213#-L1RpiYhGgswZq8U9Li-:-L1RusqRaNyFhci9_-mb:b-bfx9s7) ([raw file](https://github.com/vaadin/flow/blob/fbe5f2b79e459bbd027fb09a7f1a1fca916e7bd7/flow-server/src/main/java/com/vaadin/flow/internal/StateTree.java#L219)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

You can unify `StateNode::updateActiveState` and `node.collectChanges` in a single private method to avoid iterating over the `Set` twice.
</blockquote></details>

No I can't.
That's the very important thing.

First: go through all of dirty nodes and detect whether it's inactive or not.
Only after this : go and collect changes.

It cannot be done unified.

The reason: dirty node may be visible itself. But it may have invisible parent.
"Inactivity" of the node is calculated based on the inactivity of the node and its ascendant.
If I do both operations at once during navigating the dirty nodes then it's possible that the child node is handled first (and it's not inactive itself) and then parent node is handled (but it's inactive).

In this case the child node will be handled since it was not inactive when it has been checked.
But it will be inactive after the navigation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3213)*

**Comment by denis-anisimov** [comment]
Review status: 3 of 9 files reviewed at latest revision, 6 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/internal/StateNode.java, line 357 at r4](https://reviewable.io:443/reviews/vaadin/flow/3213#-L1RrsqunDpJwwBfqRmD:-L1Rx1alMLt88_pw0KuH:b-pp5imw) ([raw file](https://github.com/vaadin/flow/blob/fbe5f2b79e459bbd027fb09a7f1a1fca916e7bd7/flow-server/src/main/java/com/vaadin/flow/internal/StateNode.java#L357)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

`VisibilityData` is the only disallowed feature at the moment.
It should send it's data to be able to hide the node when it's value set to `false` so the client side does something.

Disallow is may be a bad word here. Those are features which makes the node inactive.
But I can't find a better word here.
</blockquote></details>

`Disallowed`  is a wrong word.
It's not disallowed.
It _disallows_ the changes for the node.

So it's not a subject. It's an actor who makes a decision.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3213)*

**Comment by denis-anisimov** [comment]
Review status: 3 of 9 files reviewed at latest revision, 6 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/internal/StateNode.java, line 650 at r4](https://reviewable.io:443/reviews/vaadin/flow/3213#-L1RnFZH9uRXuHJbCiOf:-L1RxuP91o5lkEa-4yBR:b-6a6dii) ([raw file](https://github.com/vaadin/flow/blob/fbe5f2b79e459bbd027fb09a7f1a1fca916e7bd7/flow-server/src/main/java/com/vaadin/flow/internal/StateNode.java#L650)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

The method is not just a getter. That's true. But I don't like any of suggested names.
Long names are even worse than the existing one. They don't really tell me what they really does but scare me. I would better go into impl and check what it really does than get it from this long useless name.

May be the `isInactive` field  name should be changed instead. But then I don't see a convenient name for it.
</blockquote></details>

What's about `isInactive` -> `isInactiveSelf` ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3213)*

**Comment by gilberto-torrezan** [comment]
Reviewed 1 of 2 files at r2, 3 of 6 files at r3, 1 of 2 files at r4.
Review status: 8 of 9 files reviewed at latest revision, 10 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/internal/StateNode.java, line 650 at r4](https://reviewable.io:443/reviews/vaadin/flow/3213#-L1RnFZH9uRXuHJbCiOf:-L1Rz6sLSzA7BQrDACIf:b-q91nn0) ([raw file](https://github.com/vaadin/flow/blob/fbe5f2b79e459bbd027fb09a7f1a1fca916e7bd7/flow-server/src/main/java/com/vaadin/flow/internal/StateNode.java#L650)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

What's about `isInactive` -> `isInactiveSelf` ?
</blockquote></details>

Sounds ok. The main point is to avoid the `if (isInactive()) { if (!isInactive)` code you have above. Chaing one or the other should be fine.

---

*[flow-server/src/main/java/com/vaadin/flow/internal/StateTree.java, line 219 at r4](https://reviewable.io:443/reviews/vaadin/flow/3213#-L1RpiYhGgswZq8U9Li-:-L1Rzbm5P1EWEvQaaAFj:b-ekcv7t) ([raw file](https://github.com/vaadin/flow/blob/fbe5f2b79e459bbd027fb09a7f1a1fca916e7bd7/flow-server/src/main/java/com/vaadin/flow/internal/StateTree.java#L219)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

No I can't.
That's the very important thing.

First: go through all of dirty nodes and detect whether it's inactive or not.
Only after this : go and collect changes.

It cannot be done unified.

The reason: dirty node may be visible itself. But it may have invisible parent.
"Inactivity" of the node is calculated based on the inactivity of the node and its ascendant.
If I do both operations at once during navigating the dirty nodes then it's possible that the child node is handled first (and it's not inactive itself) and then parent node is handled (but it's inactive).

In this case the child node will be handled since it was not inactive when it has been checked.
But it will be inactive after the navigation.
</blockquote></details>

Ok, so the tests should have the name changed then. I'll comment into those.

---

*[flow-server/src/test/java/com/vaadin/flow/internal/StateNodeTest.java, line 514 at r4](https://reviewable.io:443/reviews/vaadin/flow/3213#-L1RzhVRnNgL05MYLZ_4:-L1RzhVRnNgL05MYLZ_5:bcuvetz) ([raw file](https://github.com/vaadin/flow/blob/fbe5f2b79e459bbd027fb09a7f1a1fca916e7bd7/flow-server/src/test/java/com/vaadin/flow/internal/StateNodeTest.java#L514)):*
> ```Java
> 
>     @Test
>     public void collectChanges_initiallyActiveElement_sendOnlyDisalowedFeatureChangesWhenInactive() {
> ```

`DisalowedFeatures` -> `DisalowFeatures` to avoid the confusion I made above.

---

*[flow-server/src/test/java/com/vaadin/flow/internal/StateNodeTest.java, line 645 at r4](https://reviewable.io:443/reviews/vaadin/flow/3213#-L1Rsol4IHsYRsc9HBRZ:-L1Rsol4IHsYRsc9HBR_:bbdlksd) ([raw file](https://github.com/vaadin/flow/blob/fbe5f2b79e459bbd027fb09a7f1a1fca916e7bd7/flow-server/src/test/java/com/vaadin/flow/internal/StateNodeTest.java#L645)):*
> ```Java
>         Assert.assertEquals(visibilityChanged ? 3 : 2, changes.size());
>         // node is attached event
>         Assert.assertTrue(changes.get(0) instanceof NodeAttachChange);
> ```

I suggest changing all the `Assert.assertTrue(foo instanceof Bar)` for `Assert.assertThat(foo, CoreMatchers.instanceOf(Bar.class));` - reason: the error message is way more clearer when the test fails, and you don't have to write any other message by hand to make it clearer.

---

*[flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/VisibilityIT.java, line 40 at r4](https://reviewable.io:443/reviews/vaadin/flow/3213#-L1RxgmSXn7CCVv4gKRU:-L1RxgmSXn7CCVv4gKRV:b-d6kinu) ([raw file](https://github.com/vaadin/flow/blob/fbe5f2b79e459bbd027fb09a7f1a1fca916e7bd7/flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/VisibilityIT.java#L40)):*
> ```Java
>         // make the element visible
>         WebElement visibilityButton = findElement(By.id("updateVisibiity"));
>         visibilityButton.click();
> ```

You got lucky that this code worked in the test. In the component tests we usually use `clickElementWithJs(element)` or `scrollIntoViewAndClick(element)` to make sure it doesn't break in CI when running with different window sizes.

---

*[flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/VisibilityIT.java, line 103 at r4](https://reviewable.io:443/reviews/vaadin/flow/3213#-L1RxJy2udA_s2omKvns:-L1RxJy2udA_s2omKvnt:b-fhokln) ([raw file](https://github.com/vaadin/flow/blob/fbe5f2b79e459bbd027fb09a7f1a1fca916e7bd7/flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/VisibilityIT.java#L103)):*
> ```Java
>                 label.getAttribute("hidden"));
>     }
> }
> ```

New line.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3213)*

**Comment by gilberto-torrezan** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3213)*

**Comment by gilberto-torrezan** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/internal/StateNode.java, line 357 at r4](https://reviewable.io:443/reviews/vaadin/flow/3213#-L1RrsqunDpJwwBfqRmD:-L1S0loNcBS6ARV0nLka:b-ekcv7t) ([raw file](https://github.com/vaadin/flow/blob/fbe5f2b79e459bbd027fb09a7f1a1fca916e7bd7/flow-server/src/main/java/com/vaadin/flow/internal/StateNode.java#L357)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

`Disallowed`  is a wrong word.
It's not disallowed.
It _disallows_ the changes for the node.

So it's not a subject. It's an actor who makes a decision.
</blockquote></details>

Ok, so the tests should have the name changed then. I'll comment into those.

---

*[flow-server/src/main/java/com/vaadin/flow/internal/StateTree.java, line 219 at r4](https://reviewable.io:443/reviews/vaadin/flow/3213#-L1RpiYhGgswZq8U9Li-:-L1S0g1KRmVtXo_YZyjA:b-dnkfb3) ([raw file](https://github.com/vaadin/flow/blob/fbe5f2b79e459bbd027fb09a7f1a1fca916e7bd7/flow-server/src/main/java/com/vaadin/flow/internal/StateTree.java#L219)):*
> Ok, so the tests should have the name changed then. I'll comment into those.

Wrong comment in the wrong thread =x

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3213)*

**Comment by gilberto-torrezan** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/internal/StateNode.java, line 650 at r4](https://reviewable.io:443/reviews/vaadin/flow/3213#-L1RnFZH9uRXuHJbCiOf:-L1S1y_NipYEoqEe9xX3:bxcdlqq) ([raw file](https://github.com/vaadin/flow/blob/fbe5f2b79e459bbd027fb09a7f1a1fca916e7bd7/flow-server/src/main/java/com/vaadin/flow/internal/StateNode.java#L650)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Sounds ok. The main point is to avoid the `if (isInactive()) { if (!isInactive)` code you have above. Chaing one or the other should be fine.
</blockquote></details>

*Changing

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3213)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/internal/StateNode.java, line 650 at r4](https://reviewable.io:443/reviews/vaadin/flow/3213#-L1RnFZH9uRXuHJbCiOf:-L1S2bq3qt--d5to67LV:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/fbe5f2b79e459bbd027fb09a7f1a1fca916e7bd7/flow-server/src/main/java/com/vaadin/flow/internal/StateNode.java#L650)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

*Changing
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/flow/internal/StateTree.java, line 213 at r4](https://reviewable.io:443/reviews/vaadin/flow/3213#-L1RqhYcPTOPKcjUBjOF:-L1S2fnW6aEADITLgFOy:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/fbe5f2b79e459bbd027fb09a7f1a1fca916e7bd7/flow-server/src/main/java/com/vaadin/flow/internal/StateTree.java#L213)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

The SQ comment may be fixed. It's valid.
But `collectDirtyNodes()` does more than just returns `dirtyNodes` field.
It returns the `dirtyNodes` value and resets the `dirtyNodes` field to the empty set.
</blockquote></details>

Done.

---

*[flow-server/src/test/java/com/vaadin/flow/internal/StateNodeTest.java, line 514 at r4](https://reviewable.io:443/reviews/vaadin/flow/3213#-L1RzhVRnNgL05MYLZ_4:-L1S2xKy-WOT5gQpGJh7:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/fbe5f2b79e459bbd027fb09a7f1a1fca916e7bd7/flow-server/src/test/java/com/vaadin/flow/internal/StateNodeTest.java#L514)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

`DisalowedFeatures` -> `DisalowFeatures` to avoid the confusion I made above.
</blockquote></details>

Done.

---

*[flow-server/src/test/java/com/vaadin/flow/internal/StateNodeTest.java, line 645 at r4](https://reviewable.io:443/reviews/vaadin/flow/3213#-L1Rsol4IHsYRsc9HBRZ:-L1S3WvT71DSGED96bJY:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/fbe5f2b79e459bbd027fb09a7f1a1fca916e7bd7/flow-server/src/test/java/com/vaadin/flow/internal/StateNodeTest.java#L645)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

I suggest changing all the `Assert.assertTrue(foo instanceof Bar)` for `Assert.assertThat(foo, CoreMatchers.instanceOf(Bar.class));` - reason: the error message is way more clearer when the test fails, and you don't have to write any other message by hand to make it clearer.
</blockquote></details>

Done.

---

*[flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/VisibilityIT.java, line 40 at r4](https://reviewable.io:443/reviews/vaadin/flow/3213#-L1RxgmSXn7CCVv4gKRU:-L1S3aQKnOSWZZE2KqC1:b-rbiw11) ([raw file](https://github.com/vaadin/flow/blob/fbe5f2b79e459bbd027fb09a7f1a1fca916e7bd7/flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/VisibilityIT.java#L40)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

You got lucky that this code worked in the test. In the component tests we usually use `clickElementWithJs(element)` or `scrollIntoViewAndClick(element)` to make sure it doesn't break in CI when running with different window sizes.
</blockquote></details>

I don't think it's required here.
The UI for the test is as simple as it can be.
There are only two very small HTML elements and a couple of buttons.

But I've changed it.

---

*[flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/VisibilityIT.java, line 103 at r4](https://reviewable.io:443/reviews/vaadin/flow/3213#-L1RxJy2udA_s2omKvns:-L1S3cCYcyDIj5QUD-qp:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/fbe5f2b79e459bbd027fb09a7f1a1fca916e7bd7/flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/VisibilityIT.java#L103)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

New line.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3213)*

**Comment by gilberto-torrezan** [comment]
Reviewed 3 of 3 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3213)*

**Pull request merged**
