### PR TITLE
Extract classes from Grid to make them available to other components

### PR DESCRIPTION
**Pull request by gilberto-torrezan**
This update is needed for `vaadin-iron-list-flow`. It extracts common classes between `Grid` and `IronList` and make them available in `flow`.

This also adds a refactor needed in the `flow-component-renderer` to work with `iron-list`. Updates to the `vaadin-iron-list-flow` and `vaadin-grid-flow` will follow.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3195)

### CODE REVIEW

**Comment by ahie** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---

*[flow-data/src/test/java/com/vaadin/data/provider/CompositeDataGeneratorTest.java, line 107 at r1](https://reviewable.io:443/reviews/vaadin/flow/3195#-L0rkiibMV--DDxTRPCZ:-L0rkiibMV--DDxTRPC_:b3et2lb) ([raw file](https://github.com/vaadin/flow/blob/0fe41d5ff587e11b93742f084b7f4da8048b0d9c/flow-data/src/test/java/com/vaadin/data/provider/CompositeDataGeneratorTest.java#L107)):*
> orderOfGeneratorsIsRespected

Just as a side note, I don't think a user of `CompositeDataGenerator` should ever rely on the ordering being preserved, especially because it is not documented in the `HasDataGenerators` interface.

---

*[flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java, line 808 at r1](https://reviewable.io:443/reviews/vaadin/flow/3195#-L0oNPokNh1ncz4VbGh4-r1-808:-L0rkLbLZqhMTWr8DVrN:b-fgj4sv) ([raw file](https://github.com/vaadin/flow/blob/0fe41d5ff587e11b93742f084b7f4da8048b0d9c/flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java#L808)):*
> Rename "session" which hides the field declared at line 156.

Could just use that directly?

---

*[flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java, line 811 at r1](https://reviewable.io:443/reviews/vaadin/flow/3195#-L0oNPokNh1ncz4VbGh4-r1-811:-L0rkSLOFOJhjWP1kYo_:bf6v683) ([raw file](https://github.com/vaadin/flow/blob/0fe41d5ff587e11b93742f084b7f4da8048b0d9c/flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java#L811)):*
> Put single-quotes around '-' to use the faster "indexOf(char)" method.

+1

---

*[flow-server/src/main/resources/META-INF/resources/frontend/flow-component-renderer.html, line 22 at r1](https://reviewable.io:443/reviews/vaadin/flow/3195#-L0rjL-QCtpsIL-z84pS:-L0rjL-RZlwJmMiUXA4c:b-t0p60k) ([raw file](https://github.com/vaadin/flow/blob/f4fbebca773495f9d0ba75bede969c8744358605/flow-server/src/main/resources/META-INF/resources/frontend/flow-component-renderer.html#L22)):*
> ```HTML
>     constructor() {
>       super();
>       this.hidden = true;
> ```

How is the hidden property handled after this patch?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3195)*

**Comment by gilberto-torrezan** [comment]
Review status: 7 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[flow-data/src/test/java/com/vaadin/data/provider/CompositeDataGeneratorTest.java, line 107 at r1](https://reviewable.io:443/reviews/vaadin/flow/3195#-L0rkiibMV--DDxTRPCZ:-L0rsmket8jvklaKWxU8:b-swv6i6) ([raw file](https://github.com/vaadin/flow/blob/0fe41d5ff587e11b93742f084b7f4da8048b0d9c/flow-data/src/test/java/com/vaadin/data/provider/CompositeDataGeneratorTest.java#L107)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

> orderOfGeneratorsIsRespected

Just as a side note, I don't think a user of `CompositeDataGenerator` should ever rely on the ordering being preserved, especially because it is not documented in the `HasDataGenerators` interface.
</blockquote></details>

Feels estrange to me that the order of the Generators is not guaranteed. But anyway - do you prefer that I remove this restriction or that I add the note on the `HasDataGenerators` javadoc?

---

*[flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java, line 808 at r1](https://reviewable.io:443/reviews/vaadin/flow/3195#-L0oNPokNh1ncz4VbGh4-r1-808:-L0rt7z5nYbwPBc6Re4C:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/0fe41d5ff587e11b93742f084b7f4da8048b0d9c/flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java#L808)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

> Rename "session" which hides the field declared at line 156.

Could just use that directly?
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java, line 811 at r1](https://reviewable.io:443/reviews/vaadin/flow/3195#-L0oNPokNh1ncz4VbGh4-r1-811:-L0rt8MJVt35Mn72m8pQ:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/0fe41d5ff587e11b93742f084b7f4da8048b0d9c/flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java#L811)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

> Put single-quotes around '-' to use the faster "indexOf(char)" method.

+1
</blockquote></details>

Done.

---

*[flow-server/src/main/resources/META-INF/resources/frontend/flow-component-renderer.html, line 22 at r1](https://reviewable.io:443/reviews/vaadin/flow/3195#-L0rjL-QCtpsIL-z84pS:-L0rpCiJvYO7Tp4S8X48:b-my86zp) ([raw file](https://github.com/vaadin/flow/blob/f4fbebca773495f9d0ba75bede969c8744358605/flow-server/src/main/resources/META-INF/resources/frontend/flow-component-renderer.html#L22)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

How is the hidden property handled after this patch?
</blockquote></details>

It's not needed anymore. In fact, it was causing a lot of problems with `iron-list` in terms of sizing. A hidden cell takes no space, and then `iron-list` starts fetching the next cells.

For grid, the `flow-grid-component-renderer` will use the `visibility` CSS property instead.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3195)*

**Comment by ahie** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[flow-data/src/test/java/com/vaadin/data/provider/CompositeDataGeneratorTest.java, line 107 at r1](https://reviewable.io:443/reviews/vaadin/flow/3195#-L0rkiibMV--DDxTRPCZ:-L0ru1Vq_x0FJTsqwS79:b5135o9) ([raw file](https://github.com/vaadin/flow/blob/0fe41d5ff587e11b93742f084b7f4da8048b0d9c/flow-data/src/test/java/com/vaadin/data/provider/CompositeDataGeneratorTest.java#L107)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Feels estrange to me that the order of the Generators is not guaranteed. But anyway - do you prefer that I remove this restriction or that I add the note on the `HasDataGenerators` javadoc?
</blockquote></details>

I'd say remove the restriction.

---

*[flow-server/src/main/resources/META-INF/resources/frontend/flow-component-renderer.html, line 22 at r1](https://reviewable.io:443/reviews/vaadin/flow/3195#-L0rjL-QCtpsIL-z84pS:-L0rtzfCS9JVrdMlpgO2:b-ec019f) ([raw file](https://github.com/vaadin/flow/blob/f4fbebca773495f9d0ba75bede969c8744358605/flow-server/src/main/resources/META-INF/resources/frontend/flow-component-renderer.html#L22)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

It's not needed anymore. In fact, it was causing a lot of problems with `iron-list` in terms of sizing. A hidden cell takes no space, and then `iron-list` starts fetching the next cells.

For grid, the `flow-grid-component-renderer` will use the `visibility` CSS property instead.
</blockquote></details>

Excellent.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3195)*

**Comment by gilberto-torrezan** [comment]
Review status: 6 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[flow-data/src/test/java/com/vaadin/data/provider/CompositeDataGeneratorTest.java, line 107 at r1](https://reviewable.io:443/reviews/vaadin/flow/3195#-L0rkiibMV--DDxTRPCZ:-L0rvN38Amd1HXL6mdRV:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/0fe41d5ff587e11b93742f084b7f4da8048b0d9c/flow-data/src/test/java/com/vaadin/data/provider/CompositeDataGeneratorTest.java#L107)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

I'd say remove the restriction.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3195)*

**Comment by ahie** [comment]
Reviewed 1 of 2 files at r3.
Review status: 7 of 8 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3195)*

**Comment by ahie** [comment]
Reviewed 1 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3195)*

**Pull request merged**
