### PR TITLE
Add a tutorial and improve javadoc about Component::setVisible

### PR DESCRIPTION
**Pull request by gilberto-torrezan**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3257)

### CODE REVIEW

**Comment by ahie** [comment]
Reviewed 7 of 8 files at r1, 1 of 1 files at r2.
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-documentation/flow-components/tutorial-component-basic-features.asciidoc, line 13 at r2](https://reviewable.io:443/reviews/vaadin/flow/3257#-L2-K9bkmikV2HP6Mdrl:-L2-K9bkmikV2HP6Mdrm:bpu7xx6) ([raw file](https://github.com/vaadin/flow/blob/fe1c5f563c04f3bd1e0440f5e557553f9709c6be/flow-documentation/flow-components/tutorial-component-basic-features.asciidoc#L13)):*
> ```AsciiDoc
> These features are listed below.
> 
> == Visibility
> ```

Could these be reorganized so that id comes first, element second, followed by visibility. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3257)*

**Comment by gilberto-torrezan** [comment]
Review status: 7 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-documentation/flow-components/tutorial-component-basic-features.asciidoc, line 13 at r2](https://reviewable.io:443/reviews/vaadin/flow/3257#-L2-K9bkmikV2HP6Mdrl:-L2-NM6yjhHAaSLHYdF-:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/fe1c5f563c04f3bd1e0440f5e557553f9709c6be/flow-documentation/flow-components/tutorial-component-basic-features.asciidoc#L13)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

Could these be reorganized so that id comes first, element second, followed by visibility. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3257)*

**Comment by ahie** [comment]
Review status: 7 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[flow-documentation/flow-components/tutorial-component-basic-features.asciidoc, line 15 at r2](https://reviewable.io:443/reviews/vaadin/flow/3257#-L2-NOlUbctljPxnppzd:-L2-NOlUbctljPxnppze:bz8fk6k) ([raw file](https://github.com/vaadin/flow/blob/fe1c5f563c04f3bd1e0440f5e557553f9709c6be/flow-documentation/flow-components/tutorial-component-basic-features.asciidoc#L15)):*
> But more than that, a invisible

In addition, an invisible

---

*[flow-documentation/flow-components/tutorial-component-basic-features.asciidoc, line 17 at r2](https://reviewable.io:443/reviews/vaadin/flow/3257#-L2-NUpd_Za2HIqODwyr:-L2-NUpd_Za2HIqODwys:b-id18ft) ([raw file](https://github.com/vaadin/flow/blob/fe1c5f563c04f3bd1e0440f5e557553f9709c6be/flow-documentation/flow-components/tutorial-component-basic-features.asciidoc#L17)):*
> are only transmitted once the component becomes
> visible again

I could be wrong, but if I remember correctly all the server-side updates are discarded as well. Visible components that descend from invisible components do collect changes though, which will be transmitted once the parent becomes visible again (I see that this is already covered in the paragraph below).

---

*[flow-documentation/flow-components/tutorial-component-basic-features.asciidoc, line 38 at r2](https://reviewable.io:443/reviews/vaadin/flow/3257#-L2-PHqzbPFpA_RwnNtX:-L2-PHqzbPFpA_RwnNtY:b-8ib2hh) ([raw file](https://github.com/vaadin/flow/blob/fe1c5f563c04f3bd1e0440f5e557553f9709c6be/flow-documentation/flow-components/tutorial-component-basic-features.asciidoc#L38)):*
> ```AsciiDoc
> again makes all the updates to the children to be transmitted at once.
> 
> === What happens on the client-side when a component is set as invisible
> ```

I am not sure about the correctness of this subsection, maybe @caalador could take a second look?

---

*[flow-documentation/flow-components/tutorial-component-basic-features.asciidoc, line 63 at r2](https://reviewable.io:443/reviews/vaadin/flow/3257#-L2-PZcZAncj0WYFaWSy:-L2-PZcZAncj0WYFaWSz:bcre4a2) ([raw file](https://github.com/vaadin/flow/blob/fe1c5f563c04f3bd1e0440f5e557553f9709c6be/flow-documentation/flow-components/tutorial-component-basic-features.asciidoc#L63)):*
> just make it hidden

just makes it hidden

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3257)*

**Comment by caalador** [comment]
Review status: 7 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[flow-documentation/flow-components/tutorial-component-basic-features.asciidoc, line 38 at r2](https://reviewable.io:443/reviews/vaadin/flow/3257#-L2-PHqzbPFpA_RwnNtX:-L2-hgpRABFdUSEdDQ63:b53tl7v) ([raw file](https://github.com/vaadin/flow/blob/fe1c5f563c04f3bd1e0440f5e557553f9709c6be/flow-documentation/flow-components/tutorial-component-basic-features.asciidoc#L38)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

I am not sure about the correctness of this subsection, maybe @caalador could take a second look?
</blockquote></details>

After a quick check in the code/tests this would seem to be correct.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3257)*

**Comment by ahie** [comment]
Review status: 7 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[flow-documentation/flow-components/tutorial-component-basic-features.asciidoc, line 38 at r2](https://reviewable.io:443/reviews/vaadin/flow/3257#-L2-PHqzbPFpA_RwnNtX:-L2-iaILnK8QbAV0OQSh:bb6mt9b) ([raw file](https://github.com/vaadin/flow/blob/fe1c5f563c04f3bd1e0440f5e557553f9709c6be/flow-documentation/flow-components/tutorial-component-basic-features.asciidoc#L38)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

After a quick check in the code/tests this would seem to be correct.
</blockquote></details>

:+1:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3257)*

**Comment by ahie** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3257)*

**Comment by gilberto-torrezan** [comment]
Review status: 8 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[flow-documentation/flow-components/tutorial-component-basic-features.asciidoc, line 15 at r2](https://reviewable.io:443/reviews/vaadin/flow/3257#-L2-NOlUbctljPxnppzd:-L204Mq6t1ZOFUxRmhP8:bs7wumb) ([raw file](https://github.com/vaadin/flow/blob/fe1c5f563c04f3bd1e0440f5e557553f9709c6be/flow-documentation/flow-components/tutorial-component-basic-features.asciidoc#L15)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

> But more than that, a invisible

In addition, an invisible
</blockquote></details>

Done.

---

*[flow-documentation/flow-components/tutorial-component-basic-features.asciidoc, line 17 at r2](https://reviewable.io:443/reviews/vaadin/flow/3257#-L2-NUpd_Za2HIqODwyr:-L204Ufvx8Cb3jx6doNX:b-bq8hjf) ([raw file](https://github.com/vaadin/flow/blob/fe1c5f563c04f3bd1e0440f5e557553f9709c6be/flow-documentation/flow-components/tutorial-component-basic-features.asciidoc#L17)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

> are only transmitted once the component becomes
> visible again

I could be wrong, but if I remember correctly all the server-side updates are discarded as well. Visible components that descend from invisible components do collect changes though, which will be transmitted once the parent becomes visible again (I see that this is already covered in the paragraph below).
</blockquote></details>

The updates are stored and applied after the node is made visible again. There is a test made specifically for this: https://github.com/vaadin/flow/blob/master/flow-server/src/test/java/com/vaadin/flow/internal/StateNodeTest.java#L780-L781

---

*[flow-documentation/flow-components/tutorial-component-basic-features.asciidoc, line 63 at r2](https://reviewable.io:443/reviews/vaadin/flow/3257#-L2-PZcZAncj0WYFaWSy:-L20BE-2xBR9xE7dXzGF:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/fe1c5f563c04f3bd1e0440f5e557553f9709c6be/flow-documentation/flow-components/tutorial-component-basic-features.asciidoc#L63)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

> just make it hidden

just makes it hidden
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3257)*

**Comment by ahie** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3257)*

**Pull request merged**
