### PR TITLE
Use webdriver manager

### PR DESCRIPTION
**Pull request by haijian-vaadin**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/7612)

### CODE REVIEW

**Comment by haijian-vaadin** [comment]
This is an experimental improvement. 2 benefits trying to achieve:

- We don’t have to manually update the chrome driver versions. it will be handled by the webdriver manager
- The major goal I was trying to achieve it to see if it can reduce some validation build time. Coz through the  webdriver manager uses a shared directory for divers. But it turned out not helpful, seems drivers were somehow shared already.

**Comment by mehdi-vaadin** [comment]
@haijian-vaadin there is one comment waiting for you to respond. :)

**Comment by haijian-vaadin** [comment]
Sorry, for some reason, didn't the notifications. Yes, it's actually should be in the test scope.

**Comment by pleku** [comment]
@haijian-vaadin are you going to get this forward or should be closed ? Or do we wait for it to get the one year anniversary 🍰  ?

**Comment by haijian-vaadin** [comment]
I think we can close it, it doesn't bring too much benefit, we need to update the version for intern manually anyway atm.

**Pull request closed without merging**
