### PR TITLE
Implement BeforeNavigationEvent::postpone

### PR DESCRIPTION
**Pull request by torok-peter**
Also fix some unit tests which left the global session locked

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/2664)

### CODE REVIEW

**Comment by caalador** [comment]
Reviewed 4 of 8 files at r1.
Review status: 4 of 8 files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[flow-documentation/routing/tutorial-routing-lifecycle.asciidoc, line 115 at r2](https://reviewable.io:443/reviews/vaadin/flow/2664#-KwJIru9Wr0zM6dHco1-:-KwJIru9Wr0zM6dHco10:b-4xg0ff) ([raw file](https://github.com/vaadin/flow/blob/060808b019e506602a88eb0bf7260179602340da/flow-documentation/routing/tutorial-routing-lifecycle.asciidoc#L115)):*
> ```AsciiDoc
> Postpone may only be initiated while leaving (deactivating) a page; if the method
> is called while entering / activating the new page, it will have no effect
> and will return `null`.
> ```

Should we just ignore it. 
Here you first say that it will have no effect, but getting null instead of the action is an effect of calling it in the wrong state.

---

*[flow-server/src/main/java/com/vaadin/router/ContinueNavigationAction.java, line 42 at r2](https://reviewable.io:443/reviews/vaadin/flow/2664#-KwJKoPsrGXhTWoFjHSx:-KwJKoPsrGXhTWoFjHSy:bk998xx) ([raw file](https://github.com/vaadin/flow/blob/060808b019e506602a88eb0bf7260179602340da/flow-server/src/main/java/com/vaadin/router/ContinueNavigationAction.java#L42)):*
> ```Java
>      */
>     public void proceed() {
>         callback.run();
> ```

should we just drop the NULL_FUNCTION and do a `if(callback != null) callback.run(); callback=null;`

---

*[flow-server/src/main/java/com/vaadin/router/NavigationStateRenderer.java, line 138 at r2](https://reviewable.io:443/reviews/vaadin/flow/2664#-KwJKRdyI5wY0xo1nEuA:-KwJKRdyI5wY0xo1nEuB:bflvepw) ([raw file](https://github.com/vaadin/flow/blob/060808b019e506602a88eb0bf7260179602340da/flow-server/src/main/java/com/vaadin/router/NavigationStateRenderer.java#L138)):*
> ```Java
>         default:
>             throw new IllegalStateException(
>                     "Unexpected transition outcome: " + transitionOutcome);
> ```

We control the execution so we shouldn't get illegals. I think FINISHED and default should be dropped to keep the method shorter.

---

*[flow-server/src/main/java/com/vaadin/router/NavigationStateRenderer.java, line 172 at r2](https://reviewable.io:443/reviews/vaadin/flow/2664#-KwJJx5ILKWpf13wbGNe:-KwJJx5ILKWpf13wbGNf:b-k895op) ([raw file](https://github.com/vaadin/flow/blob/060808b019e506602a88eb0bf7260179602340da/flow-server/src/main/java/com/vaadin/router/NavigationStateRenderer.java#L172)):*
> switch (transitionOutcome) {
<details><summary><i alt="summary">Quoted 10 lines of code…</i></summary>
>         case REROUTED:
>             return reroute(event, beforeNavigationActivating);
>         case FINISHED:
>             // Continue normally
>             break;
>         case POSTPONED: // It is not valid here, so fall through to default
>         default:
>             throw new IllegalStateException(
>                     "Unexpected transition outcome: " + transitionOutcome);
>         }
</details>
I would say that only check here for `REROUTED.equals(transitionOutcome)` and ignore the rest.
The other parts should not be taken into consideration.

---

*[flow-server/src/main/java/com/vaadin/router/event/BeforeNavigationEvent.java, line 362 at r2](https://reviewable.io:443/reviews/vaadin/flow/2664#-KwJIe5AuLm-V5DqtJHo:-KwJIe5AuLm-V5DqtJHp:b-d445wt) ([raw file](https://github.com/vaadin/flow/blob/060808b019e506602a88eb0bf7260179602340da/flow-server/src/main/java/com/vaadin/router/event/BeforeNavigationEvent.java#L362)):*
> ```Java
>      * This is only valid while leaving (deactivating) a page; if the method is
>      * called while entering / activating the new page, it will have no effect
>      * and will return <code>null</code>.
> ```

Why do we return null? Couldn't we just return the action, but not handle it or store it in any way. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2664)*

**Comment by torok-peter** [comment]
Review status: 4 of 8 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[flow-documentation/routing/tutorial-routing-lifecycle.asciidoc, line 115 at r2](https://reviewable.io:443/reviews/vaadin/flow/2664#-KwJIru9Wr0zM6dHco1-:-Kw_9X0izfjky7mLBW4n:b-okq74h) ([raw file](https://github.com/vaadin/flow/blob/060808b019e506602a88eb0bf7260179602340da/flow-documentation/routing/tutorial-routing-lifecycle.asciidoc#L115)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Should we just ignore it. 
Here you first say that it will have no effect, but getting null instead of the action is an effect of calling it in the wrong state.
</blockquote></details>

As discussed, method will throw instead

---

*[flow-server/src/main/java/com/vaadin/router/ContinueNavigationAction.java, line 42 at r2](https://reviewable.io:443/reviews/vaadin/flow/2664#-KwJKoPsrGXhTWoFjHSx:-Kw_9jp-ilwv9VMYos3Z:b5lighe) ([raw file](https://github.com/vaadin/flow/blob/060808b019e506602a88eb0bf7260179602340da/flow-server/src/main/java/com/vaadin/router/ContinueNavigationAction.java#L42)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

should we just drop the NULL_FUNCTION and do a `if(callback != null) callback.run(); callback=null;`
</blockquote></details>

As discussed, replaced lambda with references to the handler and event

---

*[flow-server/src/main/java/com/vaadin/router/NavigationStateRenderer.java, line 138 at r2](https://reviewable.io:443/reviews/vaadin/flow/2664#-KwJKRdyI5wY0xo1nEuA:-KwZx6A3y3TFmQu96jWu:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/060808b019e506602a88eb0bf7260179602340da/flow-server/src/main/java/com/vaadin/router/NavigationStateRenderer.java#L138)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

We control the execution so we shouldn't get illegals. I think FINISHED and default should be dropped to keep the method shorter.
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/router/NavigationStateRenderer.java, line 172 at r2](https://reviewable.io:443/reviews/vaadin/flow/2664#-KwJJx5ILKWpf13wbGNe:-KwZx51e17JbVHQGNsoW:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/060808b019e506602a88eb0bf7260179602340da/flow-server/src/main/java/com/vaadin/router/NavigationStateRenderer.java#L172)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

> switch (transitionOutcome) {
>         case REROUTED:
>             return reroute(event, beforeNavigationActivating);
>         case FINISHED:
>             // Continue normally
>             break;
>         case POSTPONED: // It is not valid here, so fall through to default
>         default:
>             throw new IllegalStateException(
>                     "Unexpected transition outcome: " + transitionOutcome);
>         }
I would say that only check here for `REROUTED.equals(transitionOutcome)` and ignore the rest.
The other parts should not be taken into consideration.
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/router/event/BeforeNavigationEvent.java, line 362 at r2](https://reviewable.io:443/reviews/vaadin/flow/2664#-KwJIe5AuLm-V5DqtJHo:-Kw_IiAiK6laS2lk7uPC:bb6un1j) ([raw file](https://github.com/vaadin/flow/blob/060808b019e506602a88eb0bf7260179602340da/flow-server/src/main/java/com/vaadin/router/event/BeforeNavigationEvent.java#L362)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Why do we return null? Couldn't we just return the action, but not handle it or store it in any way. 
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2664)*

**Comment by caalador** [comment]
Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2664)*

**Comment by caalador** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2664)*

**Pull request merged**
