### PR TITLE
Fix logic and NPE in RouterLayout

### PR DESCRIPTION
**Pull request by elmot**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3309)

### CODE REVIEW

**Comment by Legioth** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/router/RouterLayout.java, line 36 at r1](https://reviewable.io:443/reviews/vaadin/flow/3309#-L2t6tx6K3Up6gBdle_o:-L2t6tx6K3Up6gBdle_p:b-fnovvb) ([raw file](https://github.com/vaadin/flow/blob/daf2b71c56ee89b6ca849af7f6a299f02218f2f1/flow-server/src/main/java/com/vaadin/flow/router/RouterLayout.java#L36)):*
> ```Java
>      */
>     default void setRouterLayoutContent(HasElement content) {
>         getElement().removeAllChildren();
> ```

Why do we want to remove all other contents?

---

*[flow-server/src/main/java/com/vaadin/flow/router/RouterLayout.java, line 37 at r1](https://reviewable.io:443/reviews/vaadin/flow/3309#-L2t6jawajiaVTZYr698:-L2t6jawajiaVTZYr699:brgjfb8) ([raw file](https://github.com/vaadin/flow/blob/daf2b71c56ee89b6ca849af7f6a299f02218f2f1/flow-server/src/main/java/com/vaadin/flow/router/RouterLayout.java#L37)):*
> ```Java
>     default void setRouterLayoutContent(HasElement content) {
>         getElement().removeAllChildren();
>         if (content != null && content.getElement() != null) {
> ```

Why do we want to allow `null` contents?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3309)*

**Comment by Legioth** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[flow-server/src/main/java/com/vaadin/flow/router/RouterLayout.java, line 37 at r1](https://reviewable.io:443/reviews/vaadin/flow/3309#-L2t72xVBXG_WJPEDiTP:-L2t72xVBXG_WJPEDiTQ:b-u87ru7) ([raw file](https://github.com/vaadin/flow/blob/daf2b71c56ee89b6ca849af7f6a299f02218f2f1/flow-server/src/main/java/com/vaadin/flow/router/RouterLayout.java#L37)):*
> ```Java
>     default void setRouterLayoutContent(HasElement content) {
>         getElement().removeAllChildren();
>         if (content != null && content.getElement() != null) {
> ```

Why do we want to support broken `HasElement` implementations where `getElement()` returns `null`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3309)*

**Comment by elmot** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[flow-server/src/main/java/com/vaadin/flow/router/RouterLayout.java, line 36 at r1](https://reviewable.io:443/reviews/vaadin/flow/3309#-L2t6tx6K3Up6gBdle_o:-L2t876v012PpOcKKvbS:b-8akxxs) ([raw file](https://github.com/vaadin/flow/blob/daf2b71c56ee89b6ca849af7f6a299f02218f2f1/flow-server/src/main/java/com/vaadin/flow/router/RouterLayout.java#L36)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

Why do we want to remove all other contents?
</blockquote></details>

Javadoc says "Set the content". That means "remove old and put new" both in common sense,  in java, and in javascript.

---

*[flow-server/src/main/java/com/vaadin/flow/router/RouterLayout.java, line 37 at r1](https://reviewable.io:443/reviews/vaadin/flow/3309#-L2t72xVBXG_WJPEDiTP:-L2t8fR2-NZ6guIezU3V:b42pgsb) ([raw file](https://github.com/vaadin/flow/blob/daf2b71c56ee89b6ca849af7f6a299f02218f2f1/flow-server/src/main/java/com/vaadin/flow/router/RouterLayout.java#L37)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

Why do we want to support broken `HasElement` implementations where `getElement()` returns `null`?
</blockquote></details>

This is just for safety reasons.

---

*[flow-server/src/main/java/com/vaadin/flow/router/RouterLayout.java, line 37 at r1](https://reviewable.io:443/reviews/vaadin/flow/3309#-L2t6jawajiaVTZYr698:-L2t8qaw7qHazcM1cAPG:b3nvxaq) ([raw file](https://github.com/vaadin/flow/blob/daf2b71c56ee89b6ca849af7f6a299f02218f2f1/flow-server/src/main/java/com/vaadin/flow/router/RouterLayout.java#L37)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

Why do we want to allow `null` contents?
</blockquote></details>

a) It might be useful to show empty page fragment content in certain situations
b) https://github.com/vaadin/flow/blob/19dd36d9f17876a2c29cb21e49e74719608bc220/flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java#L621

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3309)*

**Comment by Legioth** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/router/RouterLayout.java, line 36 at r1](https://reviewable.io:443/reviews/vaadin/flow/3309#-L2t6tx6K3Up6gBdle_o:-L2tAIjWlZgWj4PzsPX9:b-65m6qp) ([raw file](https://github.com/vaadin/flow/blob/daf2b71c56ee89b6ca849af7f6a299f02218f2f1/flow-server/src/main/java/com/vaadin/flow/router/RouterLayout.java#L36)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Javadoc says "Set the content". That means "remove old and put new" both in common sense,  in java, and in javascript.
</blockquote></details>

Maybe the Javadoc is wrong? What is the use case for removing anything that as previously there, based on the assumption that Router will already take care of removing anything that has been set there in that way.

---

*[flow-server/src/main/java/com/vaadin/flow/router/RouterLayout.java, line 37 at r1](https://reviewable.io:443/reviews/vaadin/flow/3309#-L2t6jawajiaVTZYr698:-L2tAk39oOGGH3a7AdeT:bifztja) ([raw file](https://github.com/vaadin/flow/blob/daf2b71c56ee89b6ca849af7f6a299f02218f2f1/flow-server/src/main/java/com/vaadin/flow/router/RouterLayout.java#L37)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

a) It might be useful to show empty page fragment content in certain situations
b) https://github.com/vaadin/flow/blob/19dd36d9f17876a2c29cb21e49e74719608bc220/flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java#L621
</blockquote></details>

Alright. Then the Javadocs should also be updated?

---

*[flow-server/src/main/java/com/vaadin/flow/router/RouterLayout.java, line 37 at r1](https://reviewable.io:443/reviews/vaadin/flow/3309#-L2t72xVBXG_WJPEDiTP:-L2tAnIf1dsRiVwM48aU:bwqtioi) ([raw file](https://github.com/vaadin/flow/blob/daf2b71c56ee89b6ca849af7f6a299f02218f2f1/flow-server/src/main/java/com/vaadin/flow/router/RouterLayout.java#L37)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

This is just for safety reasons.
</blockquote></details>

I'd suggest that we'd instead explicitly check for the condition and complain loudly instead of silently doing a no-op for invalid input.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3309)*

**Comment by elmot** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/router/RouterLayout.java, line 36 at r1](https://reviewable.io:443/reviews/vaadin/flow/3309#-L2t6tx6K3Up6gBdle_o:-L2u-Xqo1i9FlbHIgROU:b-rrm20u) ([raw file](https://github.com/vaadin/flow/blob/daf2b71c56ee89b6ca849af7f6a299f02218f2f1/flow-server/src/main/java/com/vaadin/flow/router/RouterLayout.java#L36)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

Maybe the Javadoc is wrong? What is the use case for removing anything that as previously there, based on the assumption that Router will already take care of removing anything that has been set there in that way.
</blockquote></details>

"Classic" navigation to a page means "remove the whole page and open a new one".  I do not see a point to get too far from it just because of KISS. I think it's better to document the approach better and leave a room for customization to an app developer.

---

*[flow-server/src/main/java/com/vaadin/flow/router/RouterLayout.java, line 37 at r1](https://reviewable.io:443/reviews/vaadin/flow/3309#-L2t72xVBXG_WJPEDiTP:-L2u2Hf_gfC_lWTYaZN7:b6ycfkw) ([raw file](https://github.com/vaadin/flow/blob/daf2b71c56ee89b6ca849af7f6a299f02218f2f1/flow-server/src/main/java/com/vaadin/flow/router/RouterLayout.java#L37)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

I'd suggest that we'd instead explicitly check for the condition and complain loudly instead of silently doing a no-op for invalid input.
</blockquote></details>

Well, I agree.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3309)*

**Comment by elmot** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/router/RouterLayout.java, line 37 at r1](https://reviewable.io:443/reviews/vaadin/flow/3309#-L2t6jawajiaVTZYr698:-L2u3AMX9EfVVD_YxPpi:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/daf2b71c56ee89b6ca849af7f6a299f02218f2f1/flow-server/src/main/java/com/vaadin/flow/router/RouterLayout.java#L37)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

Alright. Then the Javadocs should also be updated?
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/flow/router/RouterLayout.java, line 37 at r1](https://reviewable.io:443/reviews/vaadin/flow/3309#-L2t72xVBXG_WJPEDiTP:-L2u3BV_Md6Zio_G_Khz:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/daf2b71c56ee89b6ca849af7f6a299f02218f2f1/flow-server/src/main/java/com/vaadin/flow/router/RouterLayout.java#L37)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Well, I agree.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3309)*

**Comment by Legioth** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-server/src/main/java/com/vaadin/flow/router/RouterLayout.java, line 36 at r1](https://reviewable.io:443/reviews/vaadin/flow/3309#-L2t6tx6K3Up6gBdle_o:-L2u9ZG3lYPaSlfOrt0x:b1cwmmq) ([raw file](https://github.com/vaadin/flow/blob/daf2b71c56ee89b6ca849af7f6a299f02218f2f1/flow-server/src/main/java/com/vaadin/flow/router/RouterLayout.java#L36)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

"Classic" navigation to a page means "remove the whole page and open a new one".  I do not see a point to get too far from it just because of KISS. I think it's better to document the approach better and leave a room for customization to an app developer.
</blockquote></details>

Other contents in the same component are none of our concerns. Why should we interfere with stuff that the application developer has explicitly but there?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3309)*

**Comment by elmot** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[flow-server/src/main/java/com/vaadin/flow/router/RouterLayout.java, line 36 at r1](https://reviewable.io:443/reviews/vaadin/flow/3309#-L2t6tx6K3Up6gBdle_o:-L2uLZiKM7eP7Qno_fIT:b-hv0tz6) ([raw file](https://github.com/vaadin/flow/blob/daf2b71c56ee89b6ca849af7f6a299f02218f2f1/flow-server/src/main/java/com/vaadin/flow/router/RouterLayout.java#L36)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

Other contents in the same component are none of our concerns. Why should we interfere with stuff that the application developer has explicitly but there?
</blockquote></details>

Why the app developer should put any content  to the placeholder which is supposed to be modified by router and presume it's being kept untouched? How shall we handle  that content? Do we add the routed element at the end, do we insert it into very beginning, or somewhere in the middle? What happens if the developer want to modify his stuff in between of navigation events? How can we track those changes?

I think we have to set some simple contract here, and the app developer is (already) free to override the functionality on his own taste. In the same time, existing "append" approach is not an option, it just accumulates navigation elements during layouts life cycle. 

If  you have any better ideas, I am all ears.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3309)*

**Comment by Legioth** [comment]
*[flow-server/src/main/java/com/vaadin/flow/router/RouterLayout.java, line 36 at r1](https://reviewable.io:443/reviews/vaadin/flow/3309#-L2t6tx6K3Up6gBdle_o:-L2xqkRjhoKEy6iyLZwr:b-mb2qdo) ([raw file](https://github.com/vaadin/flow/blob/daf2b71c56ee89b6ca849af7f6a299f02218f2f1/flow-server/src/main/java/com/vaadin/flow/router/RouterLayout.java#L36)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Why the app developer should put any content  to the placeholder which is supposed to be modified by router and presume it's being kept untouched? How shall we handle  that content? Do we add the routed element at the end, do we insert it into very beginning, or somewhere in the middle? What happens if the developer want to modify his stuff in between of navigation events? How can we track those changes?

I think we have to set some simple contract here, and the app developer is (already) free to override the functionality on his own taste. In the same time, existing "append" approach is not an option, it just accumulates navigation elements during layouts life cycle. 

If  you have any better ideas, I am all ears.
</blockquote></details>

Nothing would be accumulated since Router should explicitly detach the previous view (using `Element.removeFromParent()`) before setting a new one. It's only stuff that the application developer has put there on their own that would be retained.

One quite common case is that the router layout component is a `PolymerTemplate` with a couple of named slots for specific components, e.g. a main menu or a header, and then the default slot is used for the actual view.

Another way of looking at this is which variant is more difficult to deal with:
* Some unknown piece of code removes components that you expect to be there
* Nobody removes the component that you expect to be removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3309)*

**Comment by elmot** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-server/src/main/java/com/vaadin/flow/router/RouterLayout.java, line 36 at r1](https://reviewable.io:443/reviews/vaadin/flow/3309#-L2t6tx6K3Up6gBdle_o:-L2ysgZAW4Q-khx175Ue:burgz37) ([raw file](https://github.com/vaadin/flow/blob/daf2b71c56ee89b6ca849af7f6a299f02218f2f1/flow-server/src/main/java/com/vaadin/flow/router/RouterLayout.java#L36)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

Nothing would be accumulated since Router should explicitly detach the previous view (using `Element.removeFromParent()`) before setting a new one. It's only stuff that the application developer has put there on their own that would be retained.

One quite common case is that the router layout component is a `PolymerTemplate` with a couple of named slots for specific components, e.g. a main menu or a header, and then the default slot is used for the actual view.

Another way of looking at this is which variant is more difficult to deal with:
* Some unknown piece of code removes components that you expect to be there
* Nobody removes the component that you expect to be removed.
</blockquote></details>

Ok, finally I have found how Router works. Both Javadoc and method name are completely misleading. Reverted the logic back and added a note to the javadoc. Should the method be renamed instead?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3309)*

**Comment by Legioth** [comment]
*[flow-server/src/main/java/com/vaadin/flow/router/RouterLayout.java, line 36 at r1](https://reviewable.io:443/reviews/vaadin/flow/3309#-L2t6tx6K3Up6gBdle_o:-L2yu05eoICnlW4etmGO:b-b1r8k2) ([raw file](https://github.com/vaadin/flow/blob/daf2b71c56ee89b6ca849af7f6a299f02218f2f1/flow-server/src/main/java/com/vaadin/flow/router/RouterLayout.java#L36)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Ok, finally I have found how Router works. Both Javadoc and method name are completely misleading. Reverted the logic back and added a note to the javadoc. Should the method be renamed instead?
</blockquote></details>

Any thoughts on what a clearer method name would be?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3309)*

**Comment by elmot** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-server/src/main/java/com/vaadin/flow/router/RouterLayout.java, line 36 at r1](https://reviewable.io:443/reviews/vaadin/flow/3309#-L2t6tx6K3Up6gBdle_o:-L2yxBb7mo4ll1OnXtV7:bv8gppx) ([raw file](https://github.com/vaadin/flow/blob/daf2b71c56ee89b6ca849af7f6a299f02218f2f1/flow-server/src/main/java/com/vaadin/flow/router/RouterLayout.java#L36)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

Any thoughts on what a clearer method name would be?
</blockquote></details>

`insertRouterLayoutContent` or `appendRouterLayoutContent`sounds more precise but a little bit stupid...

`showRoutedContent`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3309)*

**Comment by Legioth** [comment]
*[flow-server/src/main/java/com/vaadin/flow/router/RouterLayout.java, line 36 at r1](https://reviewable.io:443/reviews/vaadin/flow/3309#-L2t6tx6K3Up6gBdle_o:-L2z-iVkxYq97n0pzf_r:bmin0gu) ([raw file](https://github.com/vaadin/flow/blob/daf2b71c56ee89b6ca849af7f6a299f02218f2f1/flow-server/src/main/java/com/vaadin/flow/router/RouterLayout.java#L36)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

`insertRouterLayoutContent` or `appendRouterLayoutContent`sounds more precise but a little bit stupid...

`showRoutedContent`?
</blockquote></details>

I might prefer a combination of those: `showRouterLayoutContent`. I'll ask in `#api` on Slack.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3309)*

**Comment by elmot** [comment]
Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[flow-server/src/main/java/com/vaadin/flow/router/RouterLayout.java, line 36 at r1](https://reviewable.io:443/reviews/vaadin/flow/3309#-L2t6tx6K3Up6gBdle_o:-L32QEivk-FqMRvQyBKC:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/daf2b71c56ee89b6ca849af7f6a299f02218f2f1/flow-server/src/main/java/com/vaadin/flow/router/RouterLayout.java#L36)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

I might prefer a combination of those: `showRouterLayoutContent`. I'll ask in `#api` on Slack.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3309)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 3 of 4 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[flow-server/src/main/java/com/vaadin/flow/router/RouterLayout.java, line 34 at r3](https://reviewable.io:443/reviews/vaadin/flow/3309#-L33o6luU8tRkuCkkO7p:-L33o6luU8tRkuCkkO7q:bdj4khe) ([raw file](https://github.com/vaadin/flow/blob/eb10291e5bd61805534220ef71cb1660a41d84aa/flow-server/src/main/java/com/vaadin/flow/router/RouterLayout.java#L34)):*
> ```Java
>      * annotated with a {@link Route @Route}.
>      * <p>
>      * <strong>Note</strong> implementors should not care about old
> ```

I propose to remove this note, since old routing exists because of v.com only and no one else is supposed to use or care about it so this note might be very confusing for them.

If you insist, then please update the https://github.com/vaadin/flow/issues/2594 so that we won't forget to remove this note before closing that issue.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3309)*

**Comment by elmot** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---

*[flow-server/src/main/java/com/vaadin/flow/router/RouterLayout.java, line 34 at r3](https://reviewable.io:443/reviews/vaadin/flow/3309#-L33o6luU8tRkuCkkO7p:-L37c4c5zQihQvcKjkN_:brjzpyy) ([raw file](https://github.com/vaadin/flow/blob/eb10291e5bd61805534220ef71cb1660a41d84aa/flow-server/src/main/java/com/vaadin/flow/router/RouterLayout.java#L34)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

I propose to remove this note, since old routing exists because of v.com only and no one else is supposed to use or care about it so this note might be very confusing for them.

If you insist, then please update the https://github.com/vaadin/flow/issues/2594 so that we won't forget to remove this note before closing that issue.
</blockquote></details>

This is about old content but not old router

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3309)*

**Pull request merged**
