### PR TITLE
Fire onEnabledStateChanged to real and virtual children.

### PR DESCRIPTION
**Pull request by caalador**
All children for a component is informed of enabled change.
This means that any component mapped in a template with `@Id` will
also receive enabled state change and be disabled as if it were a 
normal component.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3884)

### CODE REVIEW

**Comment by Legioth** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/flow/3884#-L9ysOER3i9MwjW5AxbE:-L9ysOER3i9MwjW5AxbF:b-7oc8s1) (no related file):*
In what way will `@Id` elements not get any change events?

It might still maybe make sense to ignore `@Id` elements since there would otherwise be yet another case when adding `@Id` for a previously unmapped element would cause it to work in a completely different way.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3884)*

**Comment by caalador** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/flow/3884#-L9ysOER3i9MwjW5AxbE:-L9ytUJP9yZRJ_6ToxHt:banise9) (no related file):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

In what way will `@Id` elements not get any change events?

It might still maybe make sense to ignore `@Id` elements since there would otherwise be yet another case when adding `@Id` for a previously unmapped element would cause it to work in a completely different way.
</blockquote></details>

`@Id` elements are virtual children and will not be in the Component:getChildren list  thus if they are not children of the parent component they should not be informed of enabled change on attach.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3884)*

**Comment by Legioth** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/flow/3884#-L9ysOER3i9MwjW5AxbE:-L9yuhCT8sdXPa4e-RHk:b-wiexay) (no related file):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

`@Id` elements are virtual children and will not be in the Component:getChildren list  thus if they are not children of the parent component they should not be informed of enabled change on attach.
</blockquote></details>

I hope we are still blocking RPC for `@Id` components for a disabled template? If that is the case, then it could be argued that they should also be informed about having communications disabled. If it's not the case, then we have a serious security issue.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3884)*

**Comment by denis-anisimov** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/flow/3884#-L9ysOER3i9MwjW5AxbE:-L9yysOO36z3w4irH5Dl:b-suxrhp) (no related file):*
> I hope we are still blocking RPC for @Id components for a disabled template?

We do. Because `getEnabled()`  check parents. Template component is a parent but virtual child is not a child.
That's weird situation we have.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3884)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/flow/3884#-L9ysOER3i9MwjW5AxbE:-L9z6GF78v6Pgzcj_lVl:bj9870l) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> I hope we are still blocking RPC for @Id components for a disabled template?

We do. Because `getEnabled()`  check parents. Template component is a parent but virtual child is not a child.
That's weird situation we have.
</blockquote></details>

This removes inconsistent behavior which I described in the ticket. I'm fine with this.

But is there a real complexity to notify also virtual children about ascendant enabled state change ?
( so discard the change in the current PR with `onComponentAttach` and keep it as is but instead walk through virtual children + children to call `onEnabledStateChanged`  when it's changed for ascendant ) ?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3884)*

**Comment by denis-anisimov** [comment]
`RegistrationForm` example should be (or may be not) updated depending on the decision how we handle virtual children for disabled parent: https://github.com/vaadin/flow-and-components-documentation/blob/master/documentation/components/tutorial-enabled-state.asciidoc

**Comment by denis-anisimov** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-server/src/main/java/com/vaadin/flow/component/ComponentUtil.java, line 297 at r2](https://beta.reviewable.io/reviews/vaadin/flow/3884#-LAMeL833ZvKU7rbcV28:-LAMeL840d4oyk6zNqTW:bi39vc9) ([raw file](https://github.com/vaadin/flow/blob/429cc0c314efc161a64784fa0e254972cdaa8a87/flow-server/src/main/java/com/vaadin/flow/component/ComponentUtil.java#L297)):*
> ```
> private static boolean checkParentChainState(Component component) {
> ```

Doesn't relate to this PR but anyway: doesn't it repeat the `StateNode::isEnabled` logic ?

Related to this PR: do you need `isAttachedToParent` method at all and `isVirtualChild` method ?
Why not  just use `parent` and `isEnabled` state regardless of child nature and it's attached state
(without `isEnabledSelf()`) ?

At the first glance it should work out of the box or I'm missing something ?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3884)*

**Comment by caalador** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/component/ComponentUtil.java, line 297 at r2](https://beta.reviewable.io/reviews/vaadin/flow/3884#-LAMeL833ZvKU7rbcV28:-LAMiFY_7adJSRyPNaBW:blixn0w) ([raw file](https://github.com/vaadin/flow/blob/429cc0c314efc161a64784fa0e254972cdaa8a87/flow-server/src/main/java/com/vaadin/flow/component/ComponentUtil.java#L297)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
> private static boolean checkParentChainState(Component component) {
> ```

Doesn't relate to this PR but anyway: doesn't it repeat the `StateNode::isEnabled` logic ?

Related to this PR: do you need `isAttachedToParent` method at all and `isVirtualChild` method ?
Why not  just use `parent` and `isEnabled` state regardless of child nature and it's attached state
(without `isEnabledSelf()`) ?

At the first glance it should work out of the box or I'm missing something ?
</blockquote></details>

The isAttachedToParent is required for when we receive the disconnect event. As we are only removed from the feature map but else still have a parent reference when onDisconnect is executed.
That's why we need to check the actual connection state or else we will get the wrong enabled state if the parent (or one of its parents) is disabled, but we should be enabled as we would check too far on the component chain.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3884)*

**Comment by caalador** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/flow/3884#-L9ysOER3i9MwjW5AxbE:-LAMo-A_-437C9oX2pxR:bb38f7n) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

This removes inconsistent behavior which I described in the ticket. I'm fine with this.

But is there a real complexity to notify also virtual children about ascendant enabled state change ?
( so discard the change in the current PR with `onComponentAttach` and keep it as is but instead walk through virtual children + children to call `onEnabledStateChanged`  when it's changed for ascendant ) ?
</blockquote></details>

Enabled now works with virtual child components bound through `@Id` in a polymer template.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3884)*

**Comment by denis-anisimov** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3884#-:-LAMscts8HoLNBII3Jg-:bnfp4nl)*

**Pull request merged**
