### PR TITLE
fix: Use es2020 for Vite, es2019 for webpack

### LINKED ISSUE #14589: Warning message "'import.meta' is not available" logged  at Vite startup
On applications running with Flow 23.3 a warning message is logged at Vite startup (the application then starts and works correctly).

```
[vite] warning: "import.meta" is not available in the configured target environment ("es2019") and will be empty
1  |  // @ts-ignore
2  |  if (import.meta.hot) {
   |      ^
3  |    // @ts-ignore
4  |    const hot = import.meta.hot;

  Plugin: vite:esbuild
  File: /home/marco/tmp/buttami/flow-14570/frontend/generated/vite-devmode.ts
```

### Versions:
    - Vaadin / Flow version: 23.3
    - Java version: 11
    - OS version: Ubuntu 22.04

### PR DESCRIPTION
**Pull request by Artur-**
Fixes #14589

### CODE REVIEW

**Comment by mcollovati** [comment]
Should we somehow handle the case that Vite is in use and the `tsconfig.json` already exists with `target=es2019`?

**Comment by Artur-** [comment]
Now upgrades the es version for Vite also

**Comment by mcollovati** [comment]
If use Vite and then switch back to Webpack by enabling the feature flag, the target remains `es2020`
Is this fine or should it be forced to `es2019`

**Comment by Artur-** [comment]
Added some more code for that

**Review by mcollovati — APPROVED** [review]

**Pull request merged**
