### PR TITLE
Rename plugin goal.

### PR DESCRIPTION
**Pull request by SomeoneToIgnore**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3428)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PackageFormProductionMojo.java, line 50 at r1](https://reviewable.io:443/reviews/vaadin/flow/3428#-L41DkMnm5z7TxZrfZzE:-L41DkMoKdQe2mtrQUV8:b-oqaz8e) ([raw file](https://github.com/vaadin/flow/blob/a67d5c9ca37b2e2c44d22cb639f4a6232aa34045/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PackageFormProductionMojo.java#L50)):*
> PackageFormProductionMojo

`m` is extra here as well

---

*[flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PackageFormProductionMojo.java, line 54 at r1](https://reviewable.io:443/reviews/vaadin/flow/3428#-L41DbuTAkHLBfsOkziR:-L41DbuTAkHLBfsOkziS:b-wr4vlk) ([raw file](https://github.com/vaadin/flow/blob/a67d5c9ca37b2e2c44d22cb639f4a6232aa34045/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PackageFormProductionMojo.java#L54)):*
> PackageFormProductionMojo

`PackageForProductionMojo`? `m` is extra

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3428)*

**Comment by pekam** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[flow-documentation/web-components/tutorial-flow-maven-plugin.asciidoc, line 87 at r1](https://reviewable.io:443/reviews/vaadin/flow/3428#-L41CrbOOSD-TOfsN5vB:-L41CrbOOSD-TOfsN5vC:blmmn74) ([raw file](https://github.com/vaadin/flow/blob/a67d5c9ca37b2e2c44d22cb639f4a6232aa34045/flow-documentation/web-components/tutorial-flow-maven-plugin.asciidoc#L87)):*
> ```AsciiDoc
> ### package-for-production
> 
> The intention of the goal is to process application web files in order to optimize them for production usage: minify them, transpile to ES5, if required and bunbdle them (squash all frontend files into bigger files to improve their loading time).
> ```

- Typo: bunbdle
- Shouldn't bundling also be "if required" as transpiling is?
- Maybe "reduce the amount of requests to server" or "reduce the amount of server round-trips" would be more informative that "improve their loading time"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3428)*

**Comment by SomeoneToIgnore** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[flow-documentation/web-components/tutorial-flow-maven-plugin.asciidoc, line 87 at r1](https://reviewable.io:443/reviews/vaadin/flow/3428#-L41CrbOOSD-TOfsN5vB:-L41GiblBQcA0B-nDgRs:b-t7wgv4) ([raw file](https://github.com/vaadin/flow/blob/a67d5c9ca37b2e2c44d22cb639f4a6232aa34045/flow-documentation/web-components/tutorial-flow-maven-plugin.asciidoc#L87)):*
> Shouldn't bundling also be "if required" as transpiling is?

I'll just remove `if required` completely, they'll get it from settings description.

> Maybe "reduce the amount of requests to server" or "reduce the amount of server round-trips" would be more informative that "improve their loading time"?

Done.

---

*[flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PackageFormProductionMojo.java, line 50 at r1](https://reviewable.io:443/reviews/vaadin/flow/3428#-L41DkMnm5z7TxZrfZzE:-L41GZZ2gyS-Ya0QKDO7:b-dtkdrq) ([raw file](https://github.com/vaadin/flow/blob/a67d5c9ca37b2e2c44d22cb639f4a6232aa34045/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PackageFormProductionMojo.java#L50)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> PackageFormProductionMojo

`m` is extra here as well
</blockquote></details>

Done, thanks.

---

*[flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PackageFormProductionMojo.java, line 54 at r1](https://reviewable.io:443/reviews/vaadin/flow/3428#-L41DbuTAkHLBfsOkziR:-L41G_atpXAUaEzkwkxz:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/a67d5c9ca37b2e2c44d22cb639f4a6232aa34045/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PackageFormProductionMojo.java#L54)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> PackageFormProductionMojo

`PackageForProductionMojo`? `m` is extra
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3428)*

**Comment by pekam** [comment]
Reviewed 1 of 4 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3428)*

**Pull request merged**
