### PR TITLE
Url parameter template support.

### PR DESCRIPTION
**Pull request by bogdanudrescu**
Fixes https://github.com/vaadin/flow/issues/2740
Fixes https://github.com/vaadin/flow/issues/4213

Fixes the 2 above issues by defining a low level API that works with `@Route`, `@RoutePrefix` and `@RouteAlias`, which supports parameters within the route string in following format:
- `path/to/:paramName`
- `path/to/:paramName/foo`

Parameter accepting only values matching a regular expression:
- `path/to/:paramName(regex)/foo`

Optional parameters may be defined as:
- `path/to/:paramName?/foo`
- `path/to/:paramName?(regex)/foo`

Wildcard parameter (it is accepted only as the last segment template):
- `path/to/:paramName*`
- `path/to/:paramName*(regex)`

Multiple parameters may be combined within the path:
- `path/to/:paramName1/:paramName2?`
- `path/to/:paramName1/:paramName2?/foo`
- `path/to/:paramName1/foo/:paramName2/bar`
- `path/to/:paramName1(regex)/foo/:paramName2?/bar/:paramName3*`

Parameters are provided to views using `BeforeEnterEvent.getRouteParameters()` which returns a `RouteParameters` instance.

NOTE: In case of `HasUrlParameter`, the last parameter will be automatically defined so the value of `@Route` should not contain any parameter template defined as the last segment. In other words nothing changes to how `HasUrlParameter` is being used.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/7608)

### CODE REVIEW

**Comment by pleku** [comment]
>@pleku pleku removed request for joheriks, fluorumlabs and pleku now

I would expect two reviews from the team would be enough as this is way too big PR anyway.
In case there are parts that would require more opinions, then further reviewers can be pinged separately.

**Comment by bogdanudrescu** [comment]
@mehdi-vaadin I only need to fix some conflicts

**Comment by ipoint-pgerhard** [comment]
Previously it was possible to retrieve the URL specified in the `@Route` annotation by using `getUrl()`. 
As an example:

```java
@Route ( value = "v14/my" )
public class MyRoute implements HasUrlParameter<String> {
}
```

Calling `getUrl()` on the `RouteData` associated with this `@Route` would return `v14/my`.
This PR introduced a breaking change to this method, since it now returns `v14/my/:___url_parameter?`. As the deprecation notice does not provide any input on how to reproduce the previous behaviour again. As far as I know the only way to do this is via the following

```java
RouteConfiguration.forSessionScope().getUrl(MyRoute.class);
```

I have two questions:
* Why was the method deprecated in the first place?
* Is there a better way to achieve the same behaviour as before? Since I already retrieve the RouteData from the RouteConfiguration having to go back to it every time I want to resolve the URL seems clunky

**Comment by pleku** [comment]
@ipoint-pgerhard please create a new issue with the steps to reproduce and the previous behavior as expected behavior. It seems like an regression, probably just overlooked that the API is used both internally + externally.

**Pull request merged**
