### PR TITLE
Deduce tag name from component class name if no @Tag is present

### PR DESCRIPTION
**Pull request by Artur-**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/4186)

### CODE REVIEW

**Comment by gilberto-torrezan** [comment]
Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow/4186#-LDadDvw80m9pVtujIbC:-LDadDvw80m9pVtujIbD:b-gtsjla) (no related file):*
There is no meaningful error message for the case when the user creates a component that doesn't have a webcomponent with a deductible tag name counterpart.

Also I suggest taking the same approach we have for `@Id` - support the annotation without value (and use the deducted name).

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4186)*

**Comment by Artur-** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow/4186#-LDadDvw80m9pVtujIbC:-LDaekOC2m7SNKFMruUd:b-ryuxss) (no related file):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

There is no meaningful error message for the case when the user creates a component that doesn't have a webcomponent with a deductible tag name counterpart.

Also I suggest taking the same approach we have for `@Id` - support the annotation without value (and use the deducted name).
</blockquote></details>

Why is it a good thing to fail if you forget to add `@Tag` and require adding an empty `@Tag` annotation to make it work? `@Id` is different as a field is not necessarily mapped and then you do not have an `@Id` annotation.

As there is no way to know what custom elements exist or not, in what case would you produce an error message? This should work equally well for `Div` as for `MyTemplate`

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4186)*

**Comment by gilberto-torrezan** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow/4186#-LDadDvw80m9pVtujIbC:-LDeMiVY3IrbAHm9OgbZ:b-c7agzq) (no related file):*
It's a good thing because it's not magic. The other way around is harder to figure out (a Component that silently fails due to missing webcomponent with the right tag name).

Forcing the use of `@Tag` makes the developer aware of what's going on under the hood:

> My component is not working! Oh, there's a message in the log saying that I should use a `@Tag`. What is that for? Oh, to define the tag name of the webcomponent. What's the tag name of my webcomponent? Hum, it's defined in my html file. Ok, done.

Vs:

> My component is not working! No errors in the log, I have no idea what's going on.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4186)*

**Comment by Legioth** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow/4186#-LDadDvw80m9pVtujIbC:-LDer5pbBsELOOAWHmNv:bck705h) (no related file):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

It's a good thing because it's not magic. The other way around is harder to figure out (a Component that silently fails due to missing webcomponent with the right tag name).

Forcing the use of `@Tag` makes the developer aware of what's going on under the hood:

> My component is not working! Oh, there's a message in the log saying that I should use a `@Tag`. What is that for? Oh, to define the tag name of the webcomponent. What's the tag name of my webcomponent? Hum, it's defined in my html file. Ok, done.

Vs:

> My component is not working! No errors in the log, I have no idea what's going on.
</blockquote></details>

I don't think deriving from the component class name is a good general approach. My own personal experience is that what's missing isn't `@Tag("my-component")`, but rather e.g. `@Tag("div")` or something along those lines.

Deriving the tag name from the class name is usually only potentially useful when integrating a web component, which means that it might make more sense to tie this to `PolymerTemplate` (where the derived name could be verified based on the template file contents) and/or the magical `@WebComponent` annotation that has been suggested every now and then.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4186)*

**Pull request closed without merging**
