### PR TITLE
Fix some generics warnings

### PR DESCRIPTION
**Pull request by asashour**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3052)

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
Reviewed 3 of 4 files at r1.
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/util/ReflectTools.java, line 576 at r1](https://reviewable.io:443/reviews/vaadin/flow/3052#-KzuJ3qHilzUT7uZCCM1:-KzuJ3qHilzUT7uZCCM2:b385stc) ([raw file](https://github.com/vaadin/flow/blob/77b82717304b241e2f6f01d5119164a580288b15/flow-server/src/main/java/com/vaadin/util/ReflectTools.java#L576)):*
> ```Java
>      */
>     public static Class<?> getGenericInterfaceType(
>             Class<? extends Component> clazz,
> ```

I propose to use just a wildcard here: this is an utility class and it should not know about any Flow-specific types.

---

*[flow-server/src/test/java/com/vaadin/router/RouterTest.java, line 2034 at r1](https://reviewable.io:443/reviews/vaadin/flow/3052#-KzuJUIoja9-rjN1_fXW:-KzuJSbgfySChlKThSVs:b-7iohgt) ([raw file](https://github.com/vaadin/flow/blob/77b82717304b241e2f6f01d5119164a580288b15/flow-server/src/test/java/com/vaadin/router/RouterTest.java#L2034)):*
> ```Java
> 
>     private void assertExceptionComponent(String exceptionText,
>             Class<? extends Component> errorClass) {
> ```

Again, why do you need to narrow the type here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3052)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 1 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3052)*

**Comment by asashour** [comment]
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/util/ReflectTools.java, line 576 at r1](https://reviewable.io:443/reviews/vaadin/flow/3052#-KzuJ3qHilzUT7uZCCM1:-KzwMrk2lWAlKoL6zm95:bhtupeh) ([raw file](https://github.com/vaadin/flow/blob/77b82717304b241e2f6f01d5119164a580288b15/flow-server/src/main/java/com/vaadin/util/ReflectTools.java#L576)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

I propose to use just a wildcard here: this is an utility class and it should not know about any Flow-specific types.
</blockquote></details>

Done. It was restricted, because all callers uses it with `? extends Component` type.

---

*[flow-server/src/test/java/com/vaadin/router/RouterTest.java, line 2034 at r1](https://reviewable.io:443/reviews/vaadin/flow/3052#-KzuJUIoja9-rjN1_fXW:-KzwN2aGY9p36N9WlqIo:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/77b82717304b241e2f6f01d5119164a580288b15/flow-server/src/test/java/com/vaadin/router/RouterTest.java#L2034)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Again, why do you need to narrow the type here?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3052)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3052)*

**Comment by SomeoneToIgnore** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3052#-:-KzwPMeXes9717RM60_b:bnfp4nl)*

**Pull request merged**
