### PR TITLE
Improve HasUrlParameter annotation check to support generic interfaces

### LINKED ISSUE #4590: NoSuchMethodException when setParameter is implemented in a generic interface
```java
public interface SecurityAwareHasUrlParameter<T> extends HasUrlParameter<T> {
    @Override
    default void setParameter(BeforeEvent event, T parameter){
        if(SecurityUtils.isLoggedIn()) {
            setParameterSecure(event, parameter);
        }
    }

    void setParameterSecure(BeforeEvent event, T parameter);
}
```
**Expected results**
 Implementing this interface works just as implementing HasUrlParameter

**Actual results**
`java.lang.IllegalStateException: Failed to find HasUrlParameter::setParameter method when checking for @OptionalParameter`

---
This issue is related to #3518, as they are both caused by `navigationTarget.getMethod(methodName,
                    BeforeEvent.class, parameterClass)` in `ParameterDeserializer`.

### PR DESCRIPTION
**Pull request by F43nd1r**
This fixes #4590

In short: instead of just checking for a method with the exact parameter class, also check for methods with an assignable parameter type. 
This is necessary, because erasure sometimes messes up the parameter types, as demonstrated in #4590.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/5529)

### CODE REVIEW

**Comment by pleku** [comment]
Thanks for the contribution. However, there are a lot of unit test failures, please address those https://teamcity.vaadin.com/viewLog.html?buildId=47586&buildTypeId=Flow_FlowTests

**Comment by F43nd1r** [comment]
@pleku fixed. There's still 1 failed test in TeamCity, but I don't think it is related to this at all, looks more like a timout or something in the test environment.

**Comment by F43nd1r** [comment]
@caalador isn't `filter` before `anyMatch` functionally equivalent to the existing code?

**Comment by caalador** [comment]
The filter by method name is not the same as the original as the original requires the full match of methodName and parameters.

Here the filering on methodName just lets through any and all methods with the correct name and only for those do we check the parameters.

**Comment by F43nd1r** [comment]
As far as I know `.filter(condition1).anyMatch(condition2)` is equivalent to `.anyMatch(condition1 && condition2)`, because  `&&` only evaluates the right side if the left side is true.

**Comment by caalador** [comment]
The end result is the same, but the flow is clearer.
Also the anyMatch is easier to debug if there for some reason is a need for it.

**Comment by caalador** [comment]
Would there be a possibility to add a test that validates that #4590 is covered and that no
one breaks it by mistake at a later point in time?

**Pull request merged**
