### PR TITLE
Fix a bunch of individual test failures on IE11

### PR DESCRIPTION
**Pull request by pekam**
Fixes most tests in package `com.vaadin.flow.uitest.ui`
More comprehensive explanations in the commit messages.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/4278)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 9 of 9 files at r1.
Review status: 2 unresolved discussions, 0 of 1 LGTMs obtained

---

*[flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/SynchronizedPropertyView.java, line 128 at r1](https://reviewable.io/reviews/vaadin/flow/4278#-LEsxuyb5nQTO31HtMX8:-LEsxuyc3Srau-dYWsoL:bln8mxq) ([raw file](https://github.com/vaadin/flow/blob/92b86be8dcfa4043b45eb06526c326109bd01aac/flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/SynchronizedPropertyView.java#L128)):*
> ```
>  private void valueAsNumberShim() {
> ```

Why is it needed?
This is a fix for this specific test or a common issue?
Should it be fixed via transpilation/Flow core?

---

*[flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/AttachExistingElementIT.java, line 87 at r1](https://reviewable.io/reviews/vaadin/flow/4278#-LEsyRKS58j2gfgaVmU6:-LEsyRKS58j2gfgaVmU7:b-sjyzw8) ([raw file](https://github.com/vaadin/flow/blob/6cfb3a70d43bbd4e98bdb456ab57f6642e32639e/flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/AttachExistingElementIT.java#L87)):*
> ```
> getInShadowRoot(
> ```

`getInShadow` is not a replacement for plain selenium queries.
Plain queries don't work if elements are in shadow root.
But that should be verified by tests.
If they pass then it's OK.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4278)*

**Comment by denis-anisimov** [comment]
Review status: 1 unresolved discussion, 0 of 1 LGTMs obtained

---

*[flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/AttachExistingElementIT.java, line 87 at r1](https://reviewable.io/reviews/vaadin/flow/4278#-LEsyRKS58j2gfgaVmU6:-LEt0ICP7lw570kQw2Tt:bo1ybdz) ([raw file](https://github.com/vaadin/flow/blob/6cfb3a70d43bbd4e98bdb456ab57f6642e32639e/flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/AttachExistingElementIT.java#L87)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
> getInShadowRoot(
> ```

`getInShadow` is not a replacement for plain selenium queries.
Plain queries don't work if elements are in shadow root.
But that should be verified by tests.
If they pass then it's OK.
</blockquote></details>

OK, testbench nowadays has logic which cares about shadow root query.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4278)*

**Comment by pekam** [comment]
Review status: 1 unresolved discussion, 0 of 1 LGTMs obtained

---

*[flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/SynchronizedPropertyView.java, line 128 at r1](https://reviewable.io/reviews/vaadin/flow/4278#-LEsxuyb5nQTO31HtMX8:-LEt--f021YxHFQDt5qd:b-nzc81f) ([raw file](https://github.com/vaadin/flow/blob/92b86be8dcfa4043b45eb06526c326109bd01aac/flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/SynchronizedPropertyView.java#L128)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
>  private void valueAsNumberShim() {
> ```

Why is it needed?
This is a fix for this specific test or a common issue?
Should it be fixed via transpilation/Flow core?
</blockquote></details>

The test case is for synchronizing two different properties of the `<input type="number">` element: `value` and `valueAsNumber`. This second property exists in IE11 but is broken and returns always `NaN` and a client-side error is thrown.

Anyway, I could have just changed to sync some other property instead of this one, but there's really nothing like this that changes along when you change the `value` property. So I decided to apply this simple fix for the `valueAsNumber` property getter.

It doesn't affect anything related to the test. The test still tests syncing two different properties. But this allows IE11 to have these specific properties working.

---

*[flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/AttachExistingElementIT.java, line 87 at r1](https://reviewable.io/reviews/vaadin/flow/4278#-LEsyRKS58j2gfgaVmU6:-LEt0LetAUljVnSpKppV:b-67ysin) ([raw file](https://github.com/vaadin/flow/blob/6cfb3a70d43bbd4e98bdb456ab57f6642e32639e/flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/AttachExistingElementIT.java#L87)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

OK, testbench nowadays has logic which cares about shadow root query.
</blockquote></details>

Yeah, I asked this from the protools team

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4278)*

**Comment by denis-anisimov** [comment]
Review status: 1 unresolved discussion, 0 of 1 LGTMs obtained

---

*[flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/SynchronizedPropertyView.java, line 128 at r1](https://reviewable.io/reviews/vaadin/flow/4278#-LEsxuyb5nQTO31HtMX8:-LEt9vGc2fTcTsPGp5r8:b-2u84io) ([raw file](https://github.com/vaadin/flow/blob/92b86be8dcfa4043b45eb06526c326109bd01aac/flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/SynchronizedPropertyView.java#L128)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

The test case is for synchronizing two different properties of the `<input type="number">` element: `value` and `valueAsNumber`. This second property exists in IE11 but is broken and returns always `NaN` and a client-side error is thrown.

Anyway, I could have just changed to sync some other property instead of this one, but there's really nothing like this that changes along when you change the `value` property. So I decided to apply this simple fix for the `valueAsNumber` property getter.

It doesn't affect anything related to the test. The test still tests syncing two different properties. But this allows IE11 to have these specific properties working.
</blockquote></details>

So is it just about the test specifics?
We are aiming to test IE11 in a generic way. So if something is broken then it normally should be fixed either in Flow core or via transpilation.
Unless the test itself relies on some specific feature which is not available in IE11.
So this is the latter case?
(and it won't be fixed out of the box via the transpilation).

So is it true that this test is incorrect for IE11? And to make it correct this change is necessary (or rewriting the test so that it doesn't use IE11 not supported properties/features).

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4278)*

**Comment by denis-anisimov** [comment]
Review status: 1 unresolved discussion, 0 of 1 LGTMs obtained

---

*[flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/SynchronizedPropertyView.java, line 128 at r1](https://reviewable.io/reviews/vaadin/flow/4278#-LEsxuyb5nQTO31HtMX8:-LEtBshrAs3cwiDn2GyU:b46r0ob) ([raw file](https://github.com/vaadin/flow/blob/92b86be8dcfa4043b45eb06526c326109bd01aac/flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/SynchronizedPropertyView.java#L128)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

So is it just about the test specifics?
We are aiming to test IE11 in a generic way. So if something is broken then it normally should be fixed either in Flow core or via transpilation.
Unless the test itself relies on some specific feature which is not available in IE11.
So this is the latter case?
(and it won't be fixed out of the box via the transpilation).

So is it true that this test is incorrect for IE11? And to make it correct this change is necessary (or rewriting the test so that it doesn't use IE11 not supported properties/features).
</blockquote></details>

Anyway, I think two things should be done:
- This is required for IE11 only. So the method name should mention this somehow. 
- Also the exact place where the absent feature is checked ( `if (input.value != input.valueAsNumber)` I guess) should be commented (emphasize this place somehow: It's true for IE11 case and it works out of the box in other browsers).

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4278)*

**Comment by pekam** [comment]
Review status: 1 unresolved discussion, 0 of 1 LGTMs obtained

---

*[flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/SynchronizedPropertyView.java, line 128 at r1](https://reviewable.io/reviews/vaadin/flow/4278#-LEsxuyb5nQTO31HtMX8:-LEtI_Cb4XjRISpRNI4C:b-3pu697) ([raw file](https://github.com/vaadin/flow/blob/92b86be8dcfa4043b45eb06526c326109bd01aac/flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/SynchronizedPropertyView.java#L128)):*
>Unless the test itself relies on some specific feature which is not available in IE11.
So this is the latter case?
(and it won't be fixed out of the box via the transpilation).

This is the case. The property exists but it is broken. Transpilation won't fix it.

The test could use any properties, but I think it's convenient that we have two properties, `value` and `valueAsNumber`, that change at the same time. That's why I decided not to change the test to use other properties, but instead apply a shim for IE11.

Changing the property getter in `input` element's prototype doesn't matter in regards to the test. It's still a property which returns something and we are testing that these property values are synchronized to server.

For the last comment: done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4278)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r2.
Review status: all discussions resolved, 0 of 1 LGTMs obtained

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4278)*

**Comment by denis-anisimov** [comment]
:lgtm:

---

Review status: all discussions resolved, 0 of 1 LGTMs obtained, and 1 stale

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4278#-:-LEwnlMHCKgWMvkAT6mr:bnfp4nl)*

**Pull request merged**
