### PR TITLE
Use the existing DOM counterpart in server-side JS execution

### PR DESCRIPTION
**Pull request by denis-anisimov**
ExistingElementMap is used to retrieve DOM element for JS executions requested from the server-side.

Fix for #2817.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/2867)

### CODE REVIEW

**Comment by caalador** [comment]
Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[flow-tests/test-root-context/src/main/webapp/frontend/divConnector.js, line 6 at r1](https://reviewable.io:443/reviews/vaadin/flow/2867#-KyQexzio1yDUrM2dhTO:-KyQexzio1yDUrM2dhTP:brrqkfb) ([raw file](https://github.com/vaadin/flow/blob/96cdb1aac5e44314f823718a001ebfac557675ae/flow-tests/test-root-context/src/main/webapp/frontend/divConnector.js#L6)):*
> ```JavaScript
>             divComponent.$server.handleClientCall("foo");
>         }
> }
> ```

New Line, while you merge master

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2867)*

**Comment by denis-anisimov** [comment]
Review status: 13 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-tests/test-root-context/src/main/webapp/frontend/divConnector.js, line 6 at r1](https://reviewable.io:443/reviews/vaadin/flow/2867#-KyQexzio1yDUrM2dhTO:-KyUR4ba9o60dqvRj3XO:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/9234a2cb842d0434d44ad3d81de32ecfc2ad5b0c/flow-tests/test-root-context/src/main/webapp/frontend/divConnector.js#L6)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

New Line, while you merge master
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2867)*

**Comment by caalador** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2867)*

**Comment by denis-anisimov** [comment]
The failure is caused by another issue which is a regression introduced recently: https://github.com/vaadin/flow/issues/2874

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2867)*

**Pull request merged**
