### PR TITLE
fix: Prevent NPE when writing field value to bean

### PR DESCRIPTION
**Pull request by knoobie**
Forward port vaadin/framework#12230

### CODE REVIEW

**Comment by knoobie** [comment]
@pleku I tried to create a test for this change, but couldn't get it to work without adding a lot of code.. this doesn't felt reasonable for this, that's why I resigned from committing it. After this is merged, I can create a cherry pick pr with all binder related changes to pick to 2.6

**Comment by pleku** [comment]
I kind of understand the situation, but it is still a bit unfortunate that the code is not easily testable 😬 

This change is a no-brainer though and could have been picked by static code analysis too.

**Review by pleku — APPROVED** [review]

**Comment by pleku** [comment]
> After this is merged, I can create a cherry pick pr with all binder related changes to pick to 2.6

That would be great, thanks.

**Comment by knoobie** [comment]
@pleku can you trigger a rebuild? Looks kinda unrelated 😅

**Comment by pleku** [comment]
> @pleku can you trigger a rebuild? Looks kinda unrelated 😅

✅

**Pull request merged**
