### PR TITLE
Allow to adjust value change mode for components.

### PR DESCRIPTION
**Pull request by SomeoneToIgnore**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3420)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 1 of 5 files at r1.
Review status: 1 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java, line 282 at r2](https://reviewable.io:443/reviews/vaadin/flow/3420#-L4-XpKU6HnRO-E817GB:-L4-XpKU6HnRO-E817GC:bih7a3z) ([raw file](https://github.com/vaadin/flow/blob/ca0b61c96de31cf94088a5a9c0da23489a4043ab/flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java#L282)):*
> if (containsProperty(
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>
>                     model.getList(NodeFeatures.SYNCHRONIZED_PROPERTIES),
>                     subProperty)) {
>                 Console.debug("Ignoring property change for property '"
>                         + fullPropertyName
>                         + "' which is intended to be synchronized separately");
>                 return;
>             }
</details>

Is it ?

If the property is the model property then it doesn't have to be synchronized.
We should get notifications about property change even if the property is not synchornized explicitly (from the server side via registering the event listener for it).

Every model property is expected to "fire" server notification event (without any explicit synchronization).
It might be that the situation is not really correct since we will receive the RPC for the properties that we don't really need but that what we have at the moment.
This is done e.g. to be able to get the most recent value from the `TemplateModel` instance if it has a getter (which is quite common). And the only case when it's not needed is the only setter presence for the property in the model.

So it looks like this code is incorrect.
It should check whether the property is the model property and in this case let it goes as it has been done previously. And if it's not a model property then block its notifications.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3420)*

**Comment by denis-anisimov** [comment]
Reviewed 2 of 5 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java, line 282 at r2](https://reviewable.io:443/reviews/vaadin/flow/3420#-L4-XpKU6HnRO-E817GB:-L40KAIilgdpWiK2OViv:bcvtw6l) ([raw file](https://github.com/vaadin/flow/blob/ca0b61c96de31cf94088a5a9c0da23489a4043ab/flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java#L282)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> if (containsProperty(
>                     model.getList(NodeFeatures.SYNCHRONIZED_PROPERTIES),
>                     subProperty)) {
>                 Console.debug("Ignoring property change for property '"
>                         + fullPropertyName
>                         + "' which is intended to be synchronized separately");
>                 return;
>             }

Is it ?

If the property is the model property then it doesn't have to be synchronized.
We should get notifications about property change even if the property is not synchornized explicitly (from the server side via registering the event listener for it).

Every model property is expected to "fire" server notification event (without any explicit synchronization).
It might be that the situation is not really correct since we will receive the RPC for the properties that we don't really need but that what we have at the moment.
This is done e.g. to be able to get the most recent value from the `TemplateModel` instance if it has a getter (which is quite common). And the only case when it's not needed is the only setter presence for the property in the model.

So it looks like this code is incorrect.
It should check whether the property is the model property and in this case let it goes as it has been done previously. And if it's not a model property then block its notifications.
</blockquote></details>

This approach only improves the situation a bit disabling duplicating events in case of polymer element property.

It's OK for now but the separate ticket about disabling this code in case of non-model property is required.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3420)*

**Comment by SomeoneToIgnore** [comment]
*[flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java, line 282 at r2](https://reviewable.io:443/reviews/vaadin/flow/3420#-L4-XpKU6HnRO-E817GB:-L40njp2X8qBq7pAbzMW:bl15exb) ([raw file](https://github.com/vaadin/flow/blob/ca0b61c96de31cf94088a5a9c0da23489a4043ab/flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java#L282)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

This approach only improves the situation a bit disabling duplicating events in case of polymer element property.

It's OK for now but the separate ticket about disabling this code in case of non-model property is required.
</blockquote></details>

https://github.com/vaadin/flow/issues/3425

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3420)*

**Comment by bmomani1** [comment]
will this feature be available for combo box too, because in my case, I have a combo box and bound  to 
LazyQueryContainer as its container DataSource, so we should take control over firing value change event to reduce server requests.

**Pull request merged**
