### PR TITLE
Fixed Javadoc warnings

### PR DESCRIPTION
**Pull request by eriklumme**
Fixed all Javadoc warnings (#4151).

Also fixed the two ones in flow-test-generic.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/4222)

### CODE REVIEW

**Comment by ZheSun88** [comment]
dont worry, it doesn't matter i think.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow/4222#-LE9l_gB6cGTdvn5WOzp:-LE9l_gB6cGTdvn5WOzq:bhx7fsl) (no related file):*
So the `@since` tag has been removed from the files you have edited only, right?

---

*[flow-server/src/main/java/com/vaadin/flow/component/PushConfiguration.java, line 170 at r1](https://reviewable.io/reviews/vaadin/flow/4222#-LE9kvIQ2YFJR926GUcP:-LE9kvIQ2YFJR926GUcQ:bltuda4) ([raw file](https://github.com/vaadin/flow/blob/3e5b6e33b85e14608ea2d20482fcedd16c7f7e70/flow-server/src/main/java/com/vaadin/flow/component/PushConfiguration.java#L170)):*
>@param factory the factory that will be used to create new instances of {@link PushConnection}

the description of the parameter should be in another line

---

*[flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java, line 883 at r1](https://reviewable.io/reviews/vaadin/flow/4222#-LE9lCGI5uERaVRK8Ih7:-LE9lCGI5uERaVRK8Ih8:b-6h9qho) ([raw file](https://github.com/vaadin/flow/blob/3e5b6e33b85e14608ea2d20482fcedd16c7f7e70/flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java#L883)):*
> ```
> @param appId the id of the application tied with this UI
> ```

same here

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4222#-:-LE9lWQ0D5dZonm0oqEW:bxf32i)*

**Comment by eriklumme** [comment]
*[a discussion](https://reviewable.io/reviews/vaadin/flow/4222#-LE9l_gB6cGTdvn5WOzp:-LE9nAUhDeiVcCkQzzZ2:b-9er7q) (no related file):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

So the `@since` tag has been removed from the files you have edited only, right?
</blockquote></details>

Yes. And these were only `@since` tags without any version that the Javadoc validation complained about

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4222)*

**Comment by ZheSun88** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4222#-:-LE9nxsuBtDlPqY55Euv:bnfp4nl)*

**Comment by ZheSun88** [comment]
Dismissed @vaadin-bot from a discussion.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4222)*

**Pull request merged**
