### PR TITLE
Add a generic way to store data inside StateNode

### PR DESCRIPTION
**Pull request by denis-anisimov**
Part of the fix for #3425

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3475)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Preliminary functionality required for the fix for #3425

**Comment by caalador** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[flow-client/src/main/java/com/vaadin/client/flow/StateNode.java, line 302 at r1](https://reviewable.io:443/reviews/vaadin/flow/3475#-L4LYsNAWgAQ5iTEggMv:-L4LYsNAWgAQ5iTEggMw:b-g67ykk) ([raw file](https://github.com/vaadin/flow/blob/7ecba2ab4881c408c1f64f67803c57496dd3ae0d/flow-client/src/main/java/com/vaadin/client/flow/StateNode.java#L302)):*
> ```Java
>      *            the object to store
>      */
>     public <T> void setCookie(T object) {
> ```

setCookie sounds like it should be doing `document.T = object` perhaps `setNodeData`or the like would be better so it wouldn't get mixed with browser cookies.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3475)*

**Comment by denis-anisimov** [comment]
Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-client/src/main/java/com/vaadin/client/flow/StateNode.java, line 302 at r1](https://reviewable.io:443/reviews/vaadin/flow/3475#-L4LYsNAWgAQ5iTEggMv:-L4L_owotsYRagEuN9Fs:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/7ecba2ab4881c408c1f64f67803c57496dd3ae0d/flow-client/src/main/java/com/vaadin/client/flow/StateNode.java#L302)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

setCookie sounds like it should be doing `document.T = object` perhaps `setNodeData`or the like would be better so it wouldn't get mixed with browser cookies.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3475)*

**Comment by caalador** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3475)*

**Comment by SomeoneToIgnore** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[flow-client/src/test-gwt/java/com/vaadin/client/flow/GwtStateNodeTest.java, line 35 at r2](https://reviewable.io:443/reviews/vaadin/flow/3475#-L4LeGwtRT3olgdUcfrH:-L4LeGwtRT3olgdUcfrI:bcc866c) ([raw file](https://github.com/vaadin/flow/blob/2aac157099d54be59da5b7d77512bb986916b79f/flow-client/src/test-gwt/java/com/vaadin/client/flow/GwtStateNodeTest.java#L35)):*
> getCookie
> SetCookie

Looks a bit confusing after the rename, same in the other test, but up to you.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3475)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[flow-client/src/test-gwt/java/com/vaadin/client/flow/GwtStateNodeTest.java, line 35 at r2](https://reviewable.io:443/reviews/vaadin/flow/3475#-L4LeGwtRT3olgdUcfrH:-L4Lerw9aff7f9j_-cK8:b-nbjxca) ([raw file](https://github.com/vaadin/flow/blob/2aac157099d54be59da5b7d77512bb986916b79f/flow-client/src/test-gwt/java/com/vaadin/client/flow/GwtStateNodeTest.java#L35)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

> getCookie
> SetCookie

Looks a bit confusing after the rename, same in the other test, but up to you.
</blockquote></details>

Right, will rename them in the next PR.
This one is blocking further work.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3475)*

**Pull request merged**
