### PR TITLE
Don't send model properties to the server if they are not updatable

### PR DESCRIPTION
**Pull request by denis-anisimov**
Fix for #3425

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3498)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
More test are needed

**Comment by SomeoneToIgnore** [comment]
Reviewed 2 of 6 files at r1, 11 of 12 files at r2, 6 of 6 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/PolymerTemplate.java, line 209 at r3](https://reviewable.io:443/reviews/vaadin/flow/3498#-L4j_cMUYTJ1C5_BEAlr:-L4j_cMUYTJ1C5_BEAls:bxqscnx) ([raw file](https://github.com/vaadin/flow/blob/b659bdd693addcf85a97654f7500ea433c68cbf2/flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/PolymerTemplate.java#L209)):*
> ```Java
>         List<String> propertyNames = removeSimpleProperties();
> 
>         // This has to be executed BEFORE model population to be able to know
> ```

Is it possible to unite this and the next JS calls into one method call?
So you don't have to care about the order of the calls?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3498)*

**Comment by denis-anisimov** [comment]
Review status: 13 of 17 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/PolymerTemplate.java, line 209 at r3](https://beta.reviewable.io/reviews/vaadin/flow/3498#-L4j_cMUYTJ1C5_BEAlr:-L4jhylx-QTbwRtIwY52:bmj4u3j) ([raw file](https://github.com/vaadin/flow/blob/b659bdd693addcf85a97654f7500ea433c68cbf2/flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/PolymerTemplate.java#L209)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Is it possible to unite this and the next JS calls into one method call?
So you don't have to care about the order of the calls?
</blockquote></details>

Just let me know how.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3498)*

**Comment by SomeoneToIgnore** [comment]
*[flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/PolymerTemplate.java, line 209 at r3](https://beta.reviewable.io/reviews/vaadin/flow/3498#-L4j_cMUYTJ1C5_BEAlr:-L4jiCzQ-pjVN6Rl3rNf:bxvnvdj) ([raw file](https://github.com/vaadin/flow/blob/b659bdd693addcf85a97654f7500ea433c68cbf2/flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/PolymerTemplate.java#L209)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Just let me know how.
</blockquote></details>

To me it is.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3498)*

**Comment by denis-anisimov** [comment]
Review status: 13 of 17 files reviewed at latest revision, all discussions resolved.

---

*[flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/PolymerTemplate.java, line 209 at r3](https://beta.reviewable.io/reviews/vaadin/flow/3498#-L4j_cMUYTJ1C5_BEAlr:-L4jiMwlBcRb3uZrbVjg:b-btymph) ([raw file](https://github.com/vaadin/flow/blob/b659bdd693addcf85a97654f7500ea433c68cbf2/flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/PolymerTemplate.java#L209)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

To me it is.
</blockquote></details>

Just let me know how.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3498)*

**Comment by SomeoneToIgnore** [comment]
*[flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/PolymerTemplate.java, line 209 at r3](https://beta.reviewable.io/reviews/vaadin/flow/3498#-L4j_cMUYTJ1C5_BEAlr:-L4jiUfU3i6tf-gkyAaU:brfhl3m) ([raw file](https://github.com/vaadin/flow/blob/b659bdd693addcf85a97654f7500ea433c68cbf2/flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/PolymerTemplate.java#L209)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Just let me know how.
</blockquote></details>

Well, can you unite two methods into one, get three parameters in it and do all the required stuff in the order required there, can't you?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3498)*

**Comment by denis-anisimov** [comment]
Review status: 13 of 17 files reviewed at latest revision, all discussions resolved.

---

*[flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/PolymerTemplate.java, line 209 at r3](https://beta.reviewable.io/reviews/vaadin/flow/3498#-L4j_cMUYTJ1C5_BEAlr:-L4jj0qa3wgI6lhm9K9j:b-dlk63g) ([raw file](https://github.com/vaadin/flow/blob/b659bdd693addcf85a97654f7500ea433c68cbf2/flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/PolymerTemplate.java#L209)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Well, can you unite two methods into one, get three parameters in it and do all the required stuff in the order required there, can't you?
</blockquote></details>

Ah, sorry. Wrong place of the code. Thought that this is client side code..........
(I'm so tired from this crappy solutions).

Well......
Has sense.
The result will be most likely two more days of fixing tests: now: there are two independent public methods on the client side which are tested via the GWT tests.
In the result there will be one method which will needs tests adoption.

Let's say : I don't want to fix more GWT tests in this patch anymore.
I spent more than 3 days on this shit.
I will create a ticket for this improvement.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3498)*

**Comment by denis-anisimov** [comment]
Review status: 13 of 17 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/PolymerTemplate.java, line 209 at r3](https://beta.reviewable.io/reviews/vaadin/flow/3498#-L4j_cMUYTJ1C5_BEAlr:-L4jm8j44lWkYbwJRQU0:b-8sf5um) ([raw file](https://github.com/vaadin/flow/blob/b659bdd693addcf85a97654f7500ea433c68cbf2/flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/PolymerTemplate.java#L209)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Ah, sorry. Wrong place of the code. Thought that this is client side code..........
(I'm so tired from this crappy solutions).

Well......
Has sense.
The result will be most likely two more days of fixing tests: now: there are two independent public methods on the client side which are tested via the GWT tests.
In the result there will be one method which will needs tests adoption.

Let's say : I don't want to fix more GWT tests in this patch anymore.
I spent more than 3 days on this shit.
I will create a ticket for this improvement.

</blockquote></details>

#3502

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3498)*

**Comment by SomeoneToIgnore** [comment]
Review status: 13 of 17 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/PolymerTemplate.java, line 209 at r3](https://beta.reviewable.io/reviews/vaadin/flow/3498#-L4j_cMUYTJ1C5_BEAlr:-L4jmW1wDoCYEdywx_pD:blq3p9o) ([raw file](https://github.com/vaadin/flow/blob/b659bdd693addcf85a97654f7500ea433c68cbf2/flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/PolymerTemplate.java#L209)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

#3502
</blockquote></details>

Oh, I see, disregard the comment then :)
Thanks.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3498)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 6 of 6 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3498)*

**Pull request merged**
