### PR TITLE
Log JS exceptions in production mode

### PR DESCRIPTION
**Pull request by tepi**
Fixes https://github.com/vaadin/flow/issues/2963

### CODE REVIEW

**Comment by caalador** [comment]
Only thing would be to have a test in a production mode module.
See:
https://github.com/vaadin/flow/pull/3858/files#diff-a1fe593dd03bd0c91ae9e5eb4394e31d21f6a733bb9f026dad551fcab20280e8 and https://github.com/vaadin/flow/pull/2101/files#diff-0b466c731aecc2544bbe3f4582973ddcf82366a19104cf2f246813b21e977399
that combined would sound like a good test case.
For some reason no tests are left for the logging case in production mode which is a shame as we could just mistakenly break the feature. Tested with the old `ClientSideExceptionHandlingView.java` (now not existing) in production mode and the fix does do what it should.

**Comment by caalador** [comment]
`flow-misc-test` module is running production mode so that could be a good place to put the test in.

**Comment by tepi** [comment]
> For some reason no tests are left for the logging case in production mode which is a shame as we could just mistakenly break the feature.

I added tests for the exception cases. Did you mean that we don't have any tests for prod mode logging? Not even to check that debug/info is not logged?

**Comment by tepi** [comment]
Ok, thanks. It's a bit unrelated to this issue so I'll create a separate ticket about that

**Review by caalador — APPROVED** [review]

**Pull request merged**
