### PR TITLE
Update config and generated class for rich-text-editor

### PR DESCRIPTION
**Pull request by yuriy-fix**
Update config and generated class for rich-text-editor, related PR https://github.com/vaadin/vaadin-rich-text-editor-flow/pull/29

Connected to https://github.com/vaadin/vaadin-rich-text-editor-flow/issues/13

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/4754)

### CODE REVIEW

**Review by pekam — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/flow/4754)* status: 1 unresolved discussion, 0 of 1 LGTMs obtained

___
*[flow-components-parent/flow-webcomponent-api-analyzer/bower.json, line 45 at r1](https://reviewable.io/reviews/vaadin/flow/4754#-LQJSQDlC_wVWcecyMN3:-LQJSQDmA_crfZVQw4hg:b3kre) ([raw file](https://github.com/vaadin/flow/blob/81b32aa4299b6fa93513e06e16b057fe69b39d90/flow-components-parent/flow-webcomponent-api-analyzer/bower.json#L45)):*
> ```JSON
>     "vaadin-text-field": "2.1.3",
>     "vaadin-upload": "4.2.1",
>     "vaadin-time-picker": "1.0.0",
> ```

?

**Review by pekam — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/flow/4754)* status: all discussions resolved, 0 of 1 LGTMs obtained

**Review by pekam — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/vaadin/flow/4754#-:-LQJSoe6AP9b0ai8czyD:bnfp4nl)* status: :shipit: complete! all discussions resolved, 1 of 1 LGTMs obtained

**Review by yuriy-fix — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/flow/4754)* status: :shipit: complete! all discussions resolved, 1 of 1 LGTMs obtained

___
*[flow-components-parent/flow-webcomponent-api-analyzer/bower.json, line 45 at r1](https://reviewable.io/reviews/vaadin/flow/4754#-LQJSQDlC_wVWcecyMN3:-LQJSqgA9p1gw7gL7iSs:b-p4ybu) ([raw file](https://github.com/vaadin/flow/blob/81b32aa4299b6fa93513e06e16b057fe69b39d90/flow-components-parent/flow-webcomponent-api-analyzer/bower.json#L45)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

?
</blockquote></details>

Oops, fixed.

**Review by gilberto-torrezan — APPROVED** [review]
:lgtm:

> Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/flow/4754#-:-LRkIQ1r2ypmWIKhE_k_:bnfp4nl)* status: :shipit: complete! all discussions resolved, 2 of 1 LGTMs obtained

**Review by gilberto-torrezan — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vaadin/flow/4754)* status: 1 unresolved discussion, 0 of 1 LGTMs obtained, and 2 stale

___
*[flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/registry/ExclusionRegistry.java, line 71 at r3](https://reviewable.io/reviews/vaadin/flow/4754#-LRvia0d8SjKSrE2yxUc:-LRvia0d8SjKSrE2yxUd:baus8nb) ([raw file](https://github.com/vaadin/flow/blob/50e7c6c905a10f6bfd8b41a31e9728a1a3025be0/flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/registry/ExclusionRegistry.java#L71)):*
> ```Java
>         excludeEvent("vaadin-text-area", "iron-resize");
>         excludeMethod("vaadin-text-field", "clear");
>         excludeMethod("vaadin-text-area", "clear");
> ```

Why the `clear` method needs to be excluded?
And what about password-field?

**Comment by pleku** [comment]
@yuriy-fix can you please answer to the questions or close this PR if it is no longer relevant

**Review by yuriy-fix — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/flow/4754)* status: 1 unresolved discussion, 0 of 1 LGTMs obtained, and 2 stale (waiting on @gilberto-torrezan)

___
*[flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/registry/ExclusionRegistry.java, line 71 at r3](https://reviewable.io/reviews/vaadin/flow/4754#-LRvia0d8SjKSrE2yxUc:-LZtF8sy6cYpb_dZASfJ:bqjf2l5) ([raw file](https://github.com/vaadin/flow/blob/50e7c6c905a10f6bfd8b41a31e9728a1a3025be0/flow-components-parent/flow-code-generator-api/src/main/java/com/vaadin/generator/registry/ExclusionRegistry.java#L71)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Why the `clear` method needs to be excluded?
And what about password-field?
</blockquote></details>

It has not been changed in scope of this PR. However, I remember it's coming from `hasValue` interface. I guess should be added to the `password-field` as well.

**Review by gilberto-torrezan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/flow/4754)* status: all discussions resolved, 0 of 1 LGTMs obtained, and 2 stale

**Review by gilberto-torrezan — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/vaadin/flow/4754#-:-Lb7pz3925R9xBLYGfQK:bg7igkv)* status: :shipit: complete! all discussions resolved, 1 of 1 LGTMs obtained, and 1 stale

**Pull request merged**
