### PR TITLE
feat: Always in-memory update package.json

### LINKED ISSUE #15727: When checking package.json packages an in memory copy should always be updated
When running the needs dev-bundle build check and a package.json file exists in the project it should be updated with the latest versions by regenerating it in memory.

Only in memory package.json can not be used in this case as the file one may contain user made changes to package versions or added packages.

### PR DESCRIPTION
**Pull request by caalador**
Update package.json contents in memory
when checking for bundle build as platform
version might have changed for instance.

Fixes #15727

### CODE REVIEW

**Comment by mshabarov** [comment]
@caalador I tested with a fresh starter and did:
- use platform 24.0.0.alpha9 with locally built flow 24.0-SNAPSHOT
- run the application
- change platform version to 24.0-SNAPSHOT
- re-run the application
- got the following log:

```
2023-01-23T14:39:09.571+02:00  INFO 16017 --- [  restartedMain] c.v.f.s.frontend.TaskRunDevBundleBuild   : Checking if an express mode bundle build is needed
2023-01-23T14:39:09.598+02:00  INFO 16017 --- [  restartedMain] c.v.f.s.frontend.TaskRunDevBundleBuild   : Dependency @vaadin/accordion:24.0.0-alpha12 has the wrong version 24.0.0-alpha11 in the bundle
2023-01-23T14:39:09.598+02:00  INFO 16017 --- [  restartedMain] c.v.f.s.frontend.TaskRunDevBundleBuild   : Dependency @vaadin/app-layout:24.0.0-alpha12 has the wrong version 24.0.0-alpha11 in the bundle
2023-01-23T14:39:09.598+02:00  INFO 16017 --- [  restartedMain] c.v.f.s.frontend.TaskRunDevBundleBuild   : Dependency @vaadin/avatar:24.0.0-alpha12 has the wrong version 24.0.0-alpha11 in the bundle
2023-01-23T14:39:09.598+02:00  INFO 16017 --- [  restartedMain] c.v.f.s.frontend.TaskRunDevBundleBuild   : Dependency @vaadin/avatar-group:24.0.0-alpha12 has the wrong version 24.0.0-alpha11 in the bundle
2023-01-23T14:39:09.598+02:00  INFO 16017 --- [  restartedMain] c.v.f.s.frontend.TaskRunDevBundleBuild   : Dependency @vaadin/board:24.0.0-alpha12 has the wrong version 24.0.0-alpha11 in the bundle
2023-01-23T14:39:09.598+02:00  INFO 16017 --- [  restartedMain] c.v.f.s.frontend.TaskRunDevBundleBuild   : Dependency @vaadin/button:24.0.0-alpha12 has the wrong version 24.0.0-alpha11 in the bundle
2023-01-23T14:39:09.598+02:00  INFO 16017 --- [  restartedMain] c.v.f.s.frontend.TaskRunDevBundleBuild   : Dependency @vaadin/charts:24.0.0-alpha12 has the wrong version 24.0.0-alpha11 in the bundle
2023-01-23T14:39:09.599+02:00  INFO 16017 --- [  restartedMain] c.v.f.s.frontend.TaskRunDevBundleBuild   : Dependency @vaadin/checkbox:24.0.0-alpha12 has the wrong version 24.0.0-alpha11 in the bundle
2023-01-23T14:39:09.599+02:00  INFO 16017 --- [  restartedMain] c.v.f.s.frontend.TaskRunDevBundleBuild   : Dependency @vaadin/checkbox-group:24.0.0-alpha12 has the wrong version 24.0.0-alpha11 in the bundle
2023-01-23T14:39:09.599+02:00  INFO 16017 --- [  restartedMain] c.v.f.s.frontend.TaskRunDevBundleBuild   : Dependency @vaadin/combo-box:24.0.0-alpha12 has the wrong version 24.0.0-alpha11 in the bundle
2023-01-23T14:39:09.599+02:00  INFO 16017 --- [  restartedMain] c.v.f.s.frontend.TaskRunDevBundleBuild   : Dependency @vaadin/confirm-dialog:24.0.0-alpha12 has the wrong version 24.0.0-alpha11 in the bundle
2023-01-23T14:39:09.600+02:00  INFO 16017 --- [  restartedMain] c.v.f.s.frontend.TaskRunDevBundleBuild   : Dependency @vaadin/context-menu:24.0.0-alpha12 has the wrong version 24.0.0-alpha11 in the bundle
2023-01-23T14:39:09.600+02:00  INFO 16017 --- [  restartedMain] c.v.f.s.frontend.TaskRunDevBundleBuild   : Dependency @vaadin/cookie-consent:24.0.0-alpha12 has the wrong version 24.0.0-alpha11 in the bundle
2023-01-23T14:39:09.600+02:00  INFO 16017 --- [  restartedMain] c.v.f.s.frontend.TaskRunDevBundleBuild   : Dependency @vaadin/crud:24.0.0-alpha12 has the wrong version 24.0.0-alpha11 in the bundle
2023-01-23T14:39:09.600+02:00  INFO 16017 --- [  restartedMain] c.v.f.s.frontend.TaskRunDevBundleBuild   : Dependency @vaadin/custom-field:24.0.0-alpha12 has the wrong version 24.0.0-alpha11 in the bundle
2023-01-23T14:39:09.600+02:00  INFO 16017 --- [  restartedMain] c.v.f.s.frontend.TaskRunDevBundleBuild   : Dependency @vaadin/date-picker:24.0.0-alpha12 has the wrong version 24.0.0-alpha11 in the bundle
2023-01-23T14:39:09.601+02:00  INFO 16017 --- [  restartedMain] c.v.f.s.frontend.TaskRunDevBundleBuild   : Dependency @vaadin/date-time-picker:24.0.0-alpha12 has the wrong version 24.0.0-alpha11 in the bundle
2023-01-23T14:39:09.601+02:00  INFO 16017 --- [  restartedMain] c.v.f.s.frontend.TaskRunDevBundleBuild   : Dependency @vaadin/details:24.0.0-alpha12 has the wrong version 24.0.0-alpha11 in the bundle
2023-01-23T14:39:09.601+02:00  INFO 16017 --- [  restartedMain] c.v.f.s.frontend.TaskRunDevBundleBuild   : Dependency @vaadin/dialog:24.0.0-alpha12 has the wrong version 24.0.0-alpha11 in the bundle
2023-01-23T14:39:09.601+02:00  INFO 16017 --- [  restartedMain] c.v.f.s.frontend.TaskRunDevBundleBuild   : Dependency @vaadin/email-field:24.0.0-alpha12 has the wrong version 24.0.0-alpha11 in the bundle
2023-01-23T14:39:09.602+02:00  INFO 16017 --- [  restartedMain] c.v.f.s.frontend.TaskRunDevBundleBuild   : Dependency @vaadin/field-highlighter:24.0.0-alpha12 has the wrong version 24.0.0-alpha11 in the bundle
2023-01-23T14:39:09.602+02:00  INFO 16017 --- [  restartedMain] c.v.f.s.frontend.TaskRunDevBundleBuild   : Dependency @vaadin/form-layout:24.0.0-alpha12 has the wrong version 24.0.0-alpha11 in the bundle
2023-01-23T14:39:09.602+02:00  INFO 16017 --- [  restartedMain] c.v.f.s.frontend.TaskRunDevBundleBuild   : Dependency @vaadin/grid:24.0.0-alpha12 has the wrong version 24.0.0-alpha11 in the bundle
2023-01-23T14:39:09.603+02:00  INFO 16017 --- [  restartedMain] c.v.f.s.frontend.TaskRunDevBundleBuild   : Dependency @vaadin/grid-pro:24.0.0-alpha12 has the wrong version 24.0.0-alpha11 in the bundle
2023-01-23T14:39:09.603+02:00  INFO 16017 --- [  restartedMain] c.v.f.s.frontend.TaskRunDevBundleBuild   : Dependency @vaadin/horizontal-layout:24.0.0-alpha12 has the wrong version 24.0.0-alpha11 in the bundle
2023-01-23T14:39:09.604+02:00  INFO 16017 --- [  restartedMain] c.v.f.s.frontend.TaskRunDevBundleBuild   : Dependency @vaadin/icon:24.0.0-alpha12 has the wrong version 24.0.0-alpha11 in the bundle
2023-01-23T14:39:09.604+02:00  INFO 16017 --- [  restartedMain] c.v.f.s.frontend.TaskRunDevBundleBuild   : Dependency @vaadin/icons:24.0.0-alpha12 has the wrong version 24.0.0-alpha11 in the bundle
2023-01-23T14:39:09.604+02:00  INFO 16017 --- [  restartedMain] c.v.f.s.frontend.TaskRunDevBundleBuild   : Dependency @vaadin/integer-field:24.0.0-alpha12 has the wrong version 24.0.0-alpha11 in the bundle
2023-01-23T14:39:09.605+02:00  INFO 16017 --- [  restartedMain] c.v.f.s.frontend.TaskRunDevBundleBuild   : Dependency @vaadin/item:24.0.0-alpha12 has the wrong version 24.0.0-alpha11 in the bundle
2023-01-23T14:39:09.605+02:00  INFO 16017 --- [  restartedMain] c.v.f.s.frontend.TaskRunDevBundleBuild   : Dependency @vaadin/list-box:24.0.0-alpha12 has the wrong version 24.0.0-alpha11 in the bundle
2023-01-23T14:39:09.605+02:00  INFO 16017 --- [  restartedMain] c.v.f.s.frontend.TaskRunDevBundleBuild   : Dependency @vaadin/login:24.0.0-alpha12 has the wrong version 24.0.0-alpha11 in the bundle
2023-01-23T14:39:09.605+02:00  INFO 16017 --- [  restartedMain] c.v.f.s.frontend.TaskRunDevBundleBuild   : Dependency @vaadin/map:24.0.0-alpha12 has the wrong version 24.0.0-alpha11 in the bundle
2023-01-23T14:39:09.605+02:00  INFO 16017 --- [  restartedMain] c.v.f.s.frontend.TaskRunDevBundleBuild   : Dependency @vaadin/menu-bar:24.0.0-alpha12 has the wrong version 24.0.0-alpha11 in the bundle
2023-01-23T14:39:09.605+02:00  INFO 16017 --- [  restartedMain] c.v.f.s.frontend.TaskRunDevBundleBuild   : Dependency @vaadin/message-input:24.0.0-alpha12 has the wrong version 24.0.0-alpha11 in the bundle
2023-01-23T14:39:09.605+02:00  INFO 16017 --- [  restartedMain] c.v.f.s.frontend.TaskRunDevBundleBuild   : Dependency @vaadin/message-list:24.0.0-alpha12 has the wrong version 24.0.0-alpha11 in the bundle
2023-01-23T14:39:09.606+02:00  INFO 16017 --- [  restartedMain] c.v.f.s.frontend.TaskRunDevBundleBuild   : Dependency @vaadin/multi-select-combo-box:24.0.0-alpha12 has the wrong version 24.0.0-alpha11 in the bundle
2023-01-23T14:39:09.606+02:00  INFO 16017 --- [  restartedMain] c.v.f.s.frontend.TaskRunDevBundleBuild   : Dependency @vaadin/notification:24.0.0-alpha12 has the wrong version 24.0.0-alpha11 in the bundle
2023-01-23T14:39:09.606+02:00  INFO 16017 --- [  restartedMain] c.v.f.s.frontend.TaskRunDevBundleBuild   : Dependency @vaadin/number-field:24.0.0-alpha12 has the wrong version 24.0.0-alpha11 in the bundle
2023-01-23T14:39:09.606+02:00  INFO 16017 --- [  restartedMain] c.v.f.s.frontend.TaskRunDevBundleBuild   : Dependency @vaadin/password-field:24.0.0-alpha12 has the wrong version 24.0.0-alpha11 in the bundle
2023-01-23T14:39:09.607+02:00  INFO 16017 --- [  restartedMain] c.v.f.s.frontend.TaskRunDevBundleBuild   : Dependency @vaadin/polymer-legacy-adapter:24.0.0-alpha12 has the wrong version 24.0.0-alpha11 in the bundle
2023-01-23T14:39:09.607+02:00  INFO 16017 --- [  restartedMain] c.v.f.s.frontend.TaskRunDevBundleBuild   : Dependency @vaadin/progress-bar:24.0.0-alpha12 has the wrong version 24.0.0-alpha11 in the bundle
2023-01-23T14:39:09.607+02:00  INFO 16017 --- [  restartedMain] c.v.f.s.frontend.TaskRunDevBundleBuild   : Dependency @vaadin/radio-group:24.0.0-alpha12 has the wrong version 24.0.0-alpha11 in the bundle
2023-01-23T14:39:09.608+02:00  INFO 16017 --- [  restartedMain] c.v.f.s.frontend.TaskRunDevBundleBuild   : Dependency @vaadin/rich-text-editor:24.0.0-alpha12 has the wrong version 24.0.0-alpha11 in the bundle
2023-01-23T14:39:09.608+02:00  INFO 16017 --- [  restartedMain] c.v.f.s.frontend.TaskRunDevBundleBuild   : Dependency @vaadin/scroller:24.0.0-alpha12 has the wrong version 24.0.0-alpha11 in the bundle
2023-01-23T14:39:09.608+02:00  INFO 16017 --- [  restartedMain] c.v.f.s.frontend.TaskRunDevBundleBuild   : Dependency @vaadin/select:24.0.0-alpha12 has the wrong version 24.0.0-alpha11 in the bundle
2023-01-23T14:39:09.608+02:00  INFO 16017 --- [  restartedMain] c.v.f.s.frontend.TaskRunDevBundleBuild   : Dependency @vaadin/split-layout:24.0.0-alpha12 has the wrong version 24.0.0-alpha11 in the bundle
2023-01-23T14:39:09.609+02:00  INFO 16017 --- [  restartedMain] c.v.f.s.frontend.TaskRunDevBundleBuild   : Dependency @vaadin/tabs:24.0.0-alpha12 has the wrong version 24.0.0-alpha11 in the bundle
2023-01-23T14:39:09.609+02:00  INFO 16017 --- [  restartedMain] c.v.f.s.frontend.TaskRunDevBundleBuild   : Dependency @vaadin/tabsheet:24.0.0-alpha12 has the wrong version 24.0.0-alpha11 in the bundle
2023-01-23T14:39:09.609+02:00  INFO 16017 --- [  restartedMain] c.v.f.s.frontend.TaskRunDevBundleBuild   : Dependency @vaadin/text-area:24.0.0-alpha12 has the wrong version 24.0.0-alpha11 in the bundle
2023-01-23T14:39:09.610+02:00  INFO 16017 --- [  restartedMain] c.v.f.s.frontend.TaskRunDevBundleBuild   : Dependency @vaadin/text-field:24.0.0-alpha12 has the wrong version 24.0.0-alpha11 in the bundle
2023-01-23T14:39:09.610+02:00  INFO 16017 --- [  restartedMain] c.v.f.s.frontend.TaskRunDevBundleBuild   : Dependency @vaadin/time-picker:24.0.0-alpha12 has the wrong version 24.0.0-alpha11 in the bundle
2023-01-23T14:39:09.610+02:00  INFO 16017 --- [  restartedMain] c.v.f.s.frontend.TaskRunDevBundleBuild   : Dependency @vaadin/tooltip:24.0.0-alpha12 has the wrong version 24.0.0-alpha11 in the bundle
2023-01-23T14:39:09.610+02:00  INFO 16017 --- [  restartedMain] c.v.f.s.frontend.TaskRunDevBundleBuild   : Dependency @vaadin/upload:24.0.0-alpha12 has the wrong version 24.0.0-alpha11 in the bundle
2023-01-23T14:39:09.610+02:00  INFO 16017 --- [  restartedMain] c.v.f.s.frontend.TaskRunDevBundleBuild   : Dependency @vaadin/vaadin-lumo-styles:24.0.0-alpha12 has the wrong version 24.0.0-alpha11 in the bundle
2023-01-23T14:39:09.610+02:00  INFO 16017 --- [  restartedMain] c.v.f.s.frontend.TaskRunDevBundleBuild   : Dependency @vaadin/vaadin-material-styles:24.0.0-alpha12 has the wrong version 24.0.0-alpha11 in the bundle
2023-01-23T14:39:09.610+02:00  INFO 16017 --- [  restartedMain] c.v.f.s.frontend.TaskRunDevBundleBuild   : Dependency @vaadin/vaadin-themable-mixin:24.0.0-alpha12 has the wrong version 24.0.0-alpha11 in the bundle
2023-01-23T14:39:09.611+02:00  INFO 16017 --- [  restartedMain] c.v.f.s.frontend.TaskRunDevBundleBuild   : Dependency @vaadin/vertical-layout:24.0.0-alpha12 has the wrong version 24.0.0-alpha11 in the bundle
2023-01-23T14:39:09.611+02:00  INFO 16017 --- [  restartedMain] c.v.f.s.frontend.TaskRunDevBundleBuild   : Dependency @vaadin/virtual-list:24.0.0-alpha12 has the wrong version 24.0.0-alpha11 in the bundle
2023-01-23T14:39:09.611+02:00  INFO 16017 --- [  restartedMain] c.v.f.s.frontend.TaskRunDevBundleBuild   : An express mode bundle build is needed

```

So maybe testing with platform snapshot is not a right way, but I have no idea how to test it manually and make sure that it does the thing.

**Comment by mshabarov** [comment]
Also, when I run the starter with platform alpha 9 and flow 24.0-SNAPSHOT, I got this NPE:

```
java.lang.NullPointerException: Cannot invoke "elemental.json.JsonObject.hasKey(String)" because "frontendHashes" is null
        at com.vaadin.flow.server.frontend.TaskRunDevBundleBuild.frontendImportsFound(TaskRunDevBundleBuild.java:186) ~[flow-server-24.0-SNAPSHOT.jar:24.0-SNAPSHOT]
        at com.vaadin.flow.server.frontend.TaskRunDevBundleBuild.needsBuildInternal(TaskRunDevBundleBuild.java:129) ~[flow-server-24.0-SNAPSHOT.jar:24.0-SNAPSHOT]
        at com.vaadin.flow.server.frontend.TaskRunDevBundleBuild.needsBuild(TaskRunDevBundleBuild.java:82) ~[flow-server-24.0-SNAPSHOT.jar:24.0-SNAPSHOT]
        at com.vaadin.flow.server.frontend.NodeTasks.<init>(NodeTasks.java:105) ~[flow-server-24.0-SNAPSHOT.jar:24.0-SNAPSHOT]

```

Do you think this is an inconsistency between flow and platform versions I made? I expected that the `frontendHashes` is present in the default bundle and not null.

**Comment by caalador** [comment]
Did you use locally built flow-plugin and flow-server?

**Comment by mshabarov** [comment]
Yes, I've built the whole Flow project locally on top of this branch

**Comment by mshabarov** [comment]
Yes, that explains it. But any ideas why I got `Dependency @vaadin/virtual-list:24.0.0-alpha12 has the wrong version 24.0.0-alpha11 in the bundle` ?

**Comment by caalador** [comment]
The reason would be that we do not downgrade non vaadin dependencies. So there might be some missmatch in the versions, there. need to check what the differences are in the read and updated package json files.

**Review by mshabarov — APPROVED** [review]
I gave an another try to test this manually:
- used platform 24.0.0.alpha8 with locally built flow 24.0-SNAPSHOT
- Flow complains that lit has obsolete version 2.5, should 2.6.1 -> makes an app bundle
- switched to platform 24.0.0.alpha9
- Flow complain about components versions `Dependency @vaadin/accordion:24.0.0-alpha11 has the wrong version 24.0.0-alpha10 in the bundle ....`, because apparently it compares not with the default bundle but with the app bindle.

This is quite tricky to verify without having this patch included into platform...The unit test seems to cover the changed method. So I suggest to merge it and make another testing round after we have this patch in two adjacent platform versions.

What do you think?

**Pull request merged**
