### PR TITLE
Add @Theme annotation

### PR DESCRIPTION
**Pull request by caalador**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3295)

### CODE REVIEW

**Comment by ZheSun88** [comment]
Reviewed 11 of 13 files at r1, 4 of 4 files at r2.
Review status: 11 of 13 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[flow-documentation/theme/tutorial-built-in-themes.asciidoc, line 18 at r2](https://reviewable.io:443/reviews/vaadin/flow/3295#-L2_AgBHw2ehJ6EwqG2V:-L2_AgBHw2ehJ6EwqG2W:b4jco67) ([raw file](https://github.com/vaadin/flow/blob/44eb00e5991757126863564aff14168f681bd57f/flow-documentation/theme/tutorial-built-in-themes.asciidoc#L18)):*
> it's
i think i should be `its`?

---

*[flow-server/src/main/java/com/vaadin/flow/router/InternalServerError.java, line 84 at r2](https://reviewable.io:443/reviews/vaadin/flow/3295#-L2_AVEASJ9C2V2bnhab:-L2_AVEASJ9C2V2bnhac:b-k10qpq) ([raw file](https://github.com/vaadin/flow/blob/44eb00e5991757126863564aff14168f681bd57f/flow-server/src/main/java/com/vaadin/flow/router/InternalServerError.java#L84)):*
> ```Java
>         boolean productionMode = vaadinService == null ? false
>                 : vaadinService.getDeploymentConfiguration().isProductionMode();
>         
> ```

extra spaces

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3295)*

**Comment by caalador** [comment]
Review status: 11 of 13 files reviewed at latest revision, 5 unresolved discussions.

---

*[flow-documentation/theme/tutorial-built-in-themes.asciidoc, line 18 at r2](https://reviewable.io:443/reviews/vaadin/flow/3295#-L2_AgBHw2ehJ6EwqG2V:-L2_CmUpxXLhtJJ-t9v3:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/44eb00e5991757126863564aff14168f681bd57f/flow-documentation/theme/tutorial-built-in-themes.asciidoc#L18)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

> it's
i think i should be `its`?
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/flow/router/InternalServerError.java, line 84 at r2](https://reviewable.io:443/reviews/vaadin/flow/3295#-L2_AVEASJ9C2V2bnhab:-L2_Ce12SOgikqkdTHxW:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/44eb00e5991757126863564aff14168f681bd57f/flow-server/src/main/java/com/vaadin/flow/router/InternalServerError.java#L84)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

extra spaces
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3295)*

**Comment by denis-anisimov** [comment]
Reviewed 8 of 13 files at r1, 3 of 4 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks broke.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3295#-L2_Iprmr_S6hB9qGzWS:-L2_Iprmr_S6hB9qGzWT:b-nmvoyi) (no related file):*
Looks like there are many changes in various places.
Are all of them tested ?
I would say there are a number of negative testing (throw checks) and only little positive testing for newly written code (which extends the functionality).
May be something can't tests via Unit tests but then IT tests could be written.

---

*[flow-documentation/theme/tutorial-built-in-themes.asciidoc, line 50 at r2](https://reviewable.io:443/reviews/vaadin/flow/3295#-L2_CC60HbIhdS6PQbY3:-L2_CC60HbIhdS6PQbY4:b-b32o1v) ([raw file](https://github.com/vaadin/flow/blob/44eb00e5991757126863564aff14168f681bd57f/flow-documentation/theme/tutorial-built-in-themes.asciidoc#L50)):*
> If the Theme annotation is not on a `@Route` Component or a `RouterLayout` used from a route it will not be used.

Can we actually do a check for this ?
At the startup time: don't collect any information to store but just check that any class with `@Theme` extends `Component` or `RouterLayout` and throw if it doesn't.

---

*[flow-documentation/theme/tutorial-built-in-themes.asciidoc, line 73 at r2](https://reviewable.io:443/reviews/vaadin/flow/3295#-L2_Cm3dLeEyTuJSLBia:-L2_Cm3dLeEyTuJSLBib:b7z2thx) ([raw file](https://github.com/vaadin/flow/blob/44eb00e5991757126863564aff14168f681bd57f/flow-documentation/theme/tutorial-built-in-themes.asciidoc#L73)):*
> @Override
>     public String getBaseUrl() {
>         return "/src/";
>     }
>  
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>
>     @Override
>     public String getThemeUrl() {
>         return "/theme/myTheme/";
>     }
</details>
>  
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>
>     @Override
>     public List<String> getInlineContents() {
>         return Collections.EMPTY_LIST;
>     }
</details>

I believe we need a detailed description for each of those methods.
Now it just an example which doesn't tell me anything.
I need to go to the `AbstractTheme` declaration, read javadocs and  try to get from there what those methods are about.
I'm not sure that I will actually get what those methods are from the javadoc.......

---

*[flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java, line 640 at r2](https://reviewable.io:443/reviews/vaadin/flow/3295#-L2_Ds5uiJFQxzMYDjxl:-L2_Ds5uiJFQxzMYDjxm:bfy9oyf) ([raw file](https://github.com/vaadin/flow/blob/44eb00e5991757126863564aff14168f681bd57f/flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java#L640)):*
> handleSettingTheme

Looks like confusing name.
The theme is not set externally for this method. It's actually updated here.
May be `updateTheme`  or `updateThemeData` or whatever ?

---

*[flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java, line 664 at r2](https://reviewable.io:443/reviews/vaadin/flow/3295#-L2_EMT4wO3SODqfMH7N:-L2_EMT4wO3SODqfMH7O:brxpbzj) ([raw file](https://github.com/vaadin/flow/blob/44eb00e5991757126863564aff14168f681bd57f/flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java#L664)):*
> private void cacheThemeTranslations() {

Minor: I would pass `theme` as an argument here. Would look more logical. Now it's a bit confusing: `theme` is a field in the class but also it's class a key in some map (why do we need a map if there is 1:1 between class instance and field).
After a while I understand what does it do but it would be faster if the `theme` passed as an argument.

---

*[flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java, line 788 at r2](https://reviewable.io:443/reviews/vaadin/flow/3295#-L2_Fv-Cekmi5V_mP03b:-L2_Fv-Cekmi5V_mP03c:b-oxy9bt) ([raw file](https://github.com/vaadin/flow/blob/44eb00e5991757126863564aff14168f681bd57f/flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java#L788)):*
> if (urlTranslations.containsKey(html.value())) {
>                 return urlTranslations.get(html.value());
>             }

That does double check in the map.
Trying to access by the key and checking the result against the `null` is a bit less readable but faster and shorter.

---

*[flow-server/src/main/java/com/vaadin/flow/router/InternalServerError.java, line 83 at r3](https://reviewable.io:443/reviews/vaadin/flow/3295#-L2_GGProoV4kr1TGfgu:-L2_GGProoV4kr1TGfgv:b-rg2v7t) ([raw file](https://github.com/vaadin/flow/blob/9368d1777a8ea7abf20dafd87301f9bbc3c4f57b/flow-server/src/main/java/com/vaadin/flow/router/InternalServerError.java#L83)):*
> boolean productionMode = vaadinService == null ? false

I believe this is done because of tests.
I agree it's annoying when you need to set vaadin service just because of tests.
But from the  logic of code vaadin service cannot be ever null.
So this check is only because of tests. And that makes it very weird: is it good to have check which may happen only in tests and never in runtime ?
I don't know.
I decided to modify the tests instead of making this change.
At least some comment needs to be added why this check exists at all.

---

*[flow-server/src/main/java/com/vaadin/flow/server/BootstrapUtils.java, line 325 at r3](https://reviewable.io:443/reviews/vaadin/flow/3295#-L2_Hnhh99kUlJqpuuc4:-L2_Hnhh99kUlJqpuuc5:bdbuj7y) ([raw file](https://github.com/vaadin/flow/blob/9368d1777a8ea7abf20dafd87301f9bbc3c4f57b/flow-server/src/main/java/com/vaadin/flow/server/BootstrapUtils.java#L325)):*
> if (navigationTarget.isPresent()) {
<details><summary><i alt="summary">Quoted 10 lines of code…</i></summary>
>                 Optional<Theme> themeAnnotation = getThemeAnnotation(
>                         navigationTarget.get());
>                 if (themeAnnotation.isPresent()) {
>                     AbstractTheme theme = ReflectTools
>                             .createInstance(themeAnnotation.get().value());
>                     return theme.getInlineContents().stream()
>                             .map(BootstrapUtils::createInlineDependencyObject)
>                             .collect(Collectors.toList());
>                 }
>             }
</details>

Please refactor.
Too many nested blocks.

---

*[flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java, line 644 at r3](https://reviewable.io:443/reviews/vaadin/flow/3295#-L2_I2nlVnBN2hCG6J12:-L2_I2nlVnBN2hCG6J13:b-bxwsa8) ([raw file](https://github.com/vaadin/flow/blob/9368d1777a8ea7abf20dafd87301f9bbc3c4f57b/flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java#L644)):*
> s

one letter variable

---

*[flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java, line 285 at r2](https://reviewable.io:443/reviews/vaadin/flow/3295#-L2_IH6JP8uJI7-JBQi5:-L2_IH6JP8uJI7-JBQi6:b-qsznbj) ([raw file](https://github.com/vaadin/flow/blob/44eb00e5991757126863564aff14168f681bd57f/flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java#L285)):*
> "<style type=\"text/css\">/* theme inlined css */\n" + "\n"
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>
>                     + "#preloadedDiv {\n" + "    color: rgba(255, 255, 0, 1);\n"
>                     + "}\n" + "\n" + "#inlineCssTestDiv {\n"
>                     + "    color: rgba(255, 255, 0, 1);\n" + "}\n</style>","<script type=\"text/javascript\">\n"
>                     + "    // document.body might not yet be accessible, so just leave a message\n"
>                     + "    window.messages = window.messages || [];\n"
>                     + "    window.messages.push(\"inline.html\");\n"
>                     + "</script>"
</details>

Is it necessary to have such long real content? 
Short mock content would be better to understand.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3295)*

**Comment by caalador** [comment]
Review status: 9 of 13 files reviewed at latest revision, 10 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3295#-L2_Iprmr_S6hB9qGzWS:-L2_MQT12iiQLItvOwKu:b-7so5ob) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Looks like there are many changes in various places.
Are all of them tested ?
I would say there are a number of negative testing (throw checks) and only little positive testing for newly written code (which extends the functionality).
May be something can't tests via Unit tests but then IT tests could be written.
</blockquote></details>

I'll look into the tests. IT tests at least need design on what we can test.
Have tested by extending one of our demos. Will ponder about this

---

*[flow-documentation/theme/tutorial-built-in-themes.asciidoc, line 50 at r2](https://reviewable.io:443/reviews/vaadin/flow/3295#-L2_CC60HbIhdS6PQbY3:-L2_MhwMTw2eRys0VlOs:b7awakd) ([raw file](https://github.com/vaadin/flow/blob/44eb00e5991757126863564aff14168f681bd57f/flow-documentation/theme/tutorial-built-in-themes.asciidoc#L50)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> If the Theme annotation is not on a `@Route` Component or a `RouterLayout` used from a route it will not be used.

Can we actually do a check for this ?
At the startup time: don't collect any information to store but just check that any class with `@Theme` extends `Component` or `RouterLayout` and throw if it doesn't.
</blockquote></details>

If it's not on a Route or RouterLayout we won't check it. Same as for Viewport, BodySize, Inline.

Will add a initializer check for all of them.

---

*[flow-documentation/theme/tutorial-built-in-themes.asciidoc, line 73 at r2](https://reviewable.io:443/reviews/vaadin/flow/3295#-L2_Cm3dLeEyTuJSLBia:-L2_NYKnYt1xEMZWo_94:bq3i7ci) ([raw file](https://github.com/vaadin/flow/blob/44eb00e5991757126863564aff14168f681bd57f/flow-documentation/theme/tutorial-built-in-themes.asciidoc#L73)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> @Override
>     public String getBaseUrl() {
>         return "/src/";
>     }
>  
>     @Override
>     public String getThemeUrl() {
>         return "/theme/myTheme/";
>     }
>  
>     @Override
>     public List<String> getInlineContents() {
>         return Collections.EMPTY_LIST;
>     }

I believe we need a detailed description for each of those methods.
Now it just an example which doesn't tell me anything.
I need to go to the `AbstractTheme` declaration, read javadocs and  try to get from there what those methods are about.
I'm not sure that I will actually get what those methods are from the javadoc.......
</blockquote></details>

I'll try to expand on this.

---

*[flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java, line 640 at r2](https://reviewable.io:443/reviews/vaadin/flow/3295#-L2_Ds5uiJFQxzMYDjxl:-L2_Jyojy45fXOCBNcqe:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/44eb00e5991757126863564aff14168f681bd57f/flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java#L640)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> handleSettingTheme

Looks like confusing name.
The theme is not set externally for this method. It's actually updated here.
May be `updateTheme`  or `updateThemeData` or whatever ?
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java, line 664 at r2](https://reviewable.io:443/reviews/vaadin/flow/3295#-L2_EMT4wO3SODqfMH7N:-L2_KCSmsWhswEDH2B_Y:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/44eb00e5991757126863564aff14168f681bd57f/flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java#L664)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> private void cacheThemeTranslations() {

Minor: I would pass `theme` as an argument here. Would look more logical. Now it's a bit confusing: `theme` is a field in the class but also it's class a key in some map (why do we need a map if there is 1:1 between class instance and field).
After a while I understand what does it do but it would be faster if the `theme` passed as an argument.
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java, line 788 at r2](https://reviewable.io:443/reviews/vaadin/flow/3295#-L2_Fv-Cekmi5V_mP03b:-L2_KRBm-UDoRLndLgfV:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/44eb00e5991757126863564aff14168f681bd57f/flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java#L788)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> if (urlTranslations.containsKey(html.value())) {
>                 return urlTranslations.get(html.value());
>             }

That does double check in the map.
Trying to access by the key and checking the result against the `null` is a bit less readable but faster and shorter.
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/flow/router/InternalServerError.java, line 83 at r3](https://reviewable.io:443/reviews/vaadin/flow/3295#-L2_GGProoV4kr1TGfgu:-L2_Kvb8EgdTGzN49SRZ:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/9368d1777a8ea7abf20dafd87301f9bbc3c4f57b/flow-server/src/main/java/com/vaadin/flow/router/InternalServerError.java#L83)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> boolean productionMode = vaadinService == null ? false

I believe this is done because of tests.
I agree it's annoying when you need to set vaadin service just because of tests.
But from the  logic of code vaadin service cannot be ever null.
So this check is only because of tests. And that makes it very weird: is it good to have check which may happen only in tests and never in runtime ?
I don't know.
I decided to modify the tests instead of making this change.
At least some comment needs to be added why this check exists at all.
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/flow/server/BootstrapUtils.java, line 325 at r3](https://reviewable.io:443/reviews/vaadin/flow/3295#-L2_Hnhh99kUlJqpuuc4:-L2_M1PMWlk2rlF1UCFd:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/9368d1777a8ea7abf20dafd87301f9bbc3c4f57b/flow-server/src/main/java/com/vaadin/flow/server/BootstrapUtils.java#L325)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> if (navigationTarget.isPresent()) {
>                 Optional<Theme> themeAnnotation = getThemeAnnotation(
>                         navigationTarget.get());
>                 if (themeAnnotation.isPresent()) {
>                     AbstractTheme theme = ReflectTools
>                             .createInstance(themeAnnotation.get().value());
>                     return theme.getInlineContents().stream()
>                             .map(BootstrapUtils::createInlineDependencyObject)
>                             .collect(Collectors.toList());
>                 }
>             }

Please refactor.
Too many nested blocks.
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java, line 644 at r3](https://reviewable.io:443/reviews/vaadin/flow/3295#-L2_I2nlVnBN2hCG6J12:-L2_M8VQoLQ5TZaquSpy:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/9368d1777a8ea7abf20dafd87301f9bbc3c4f57b/flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java#L644)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> s

one letter variable
</blockquote></details>

Done.

---

*[flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java, line 285 at r2](https://reviewable.io:443/reviews/vaadin/flow/3295#-L2_IH6JP8uJI7-JBQi5:-L2_MBhB0_AJIjz7nL5r:b48lgkv) ([raw file](https://github.com/vaadin/flow/blob/44eb00e5991757126863564aff14168f681bd57f/flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java#L285)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> "<style type=\"text/css\">/* theme inlined css */\n" + "\n"
>                     + "#preloadedDiv {\n" + "    color: rgba(255, 255, 0, 1);\n"
>                     + "}\n" + "\n" + "#inlineCssTestDiv {\n"
>                     + "    color: rgba(255, 255, 0, 1);\n" + "}\n</style>","<script type=\"text/javascript\">\n"
>                     + "    // document.body might not yet be accessible, so just leave a message\n"
>                     + "    window.messages = window.messages || [];\n"
>                     + "    window.messages.push(\"inline.html\");\n"
>                     + "</script>"

Is it necessary to have such long real content? 
Short mock content would be better to understand.
</blockquote></details>

Wanted to see that it doesn't wrap it and that it is appended as is. Will add simple test also.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3295)*

**Comment by denis-anisimov** [comment]
Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3295)*

**Comment by caalador** [comment]
Review status: 10 of 17 files reviewed at latest revision, 10 unresolved discussions, some commit checks broke.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3295#-L2_Iprmr_S6hB9qGzWS:-L2eCsxL-Aoz9j4b8vzD:b-7rl0jd) (no related file):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

I'll look into the tests. IT tests at least need design on what we can test.
Have tested by extending one of our demos. Will ponder about this
</blockquote></details>

done.

---

*[flow-documentation/theme/tutorial-built-in-themes.asciidoc, line 50 at r2](https://reviewable.io:443/reviews/vaadin/flow/3295#-L2_CC60HbIhdS6PQbY3:-L2dP8CtXNnUABF__sCO:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/44eb00e5991757126863564aff14168f681bd57f/flow-documentation/theme/tutorial-built-in-themes.asciidoc#L50)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

If it's not on a Route or RouterLayout we won't check it. Same as for Viewport, BodySize, Inline.

Will add a initializer check for all of them.
</blockquote></details>

Done.

---

*[flow-documentation/theme/tutorial-built-in-themes.asciidoc, line 73 at r2](https://reviewable.io:443/reviews/vaadin/flow/3295#-L2_Cm3dLeEyTuJSLBia:-L2dQLVueQlZUHcDfz7I:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/44eb00e5991757126863564aff14168f681bd57f/flow-documentation/theme/tutorial-built-in-themes.asciidoc#L73)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

I'll try to expand on this.
</blockquote></details>

Done.

---

*[flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java, line 285 at r2](https://reviewable.io:443/reviews/vaadin/flow/3295#-L2_IH6JP8uJI7-JBQi5:-L2dYIKK_dwc_l75PVWn:b-uj18pl) ([raw file](https://github.com/vaadin/flow/blob/44eb00e5991757126863564aff14168f681bd57f/flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java#L285)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Wanted to see that it doesn't wrap it and that it is appended as is. Will add simple test also.
</blockquote></details>

Simplified test. Found a bug on the same time.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3295)*

**Comment by denis-anisimov** [comment]
Reviewed 3 of 7 files at r5, 16 of 16 files at r6.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[flow-documentation/theme/tutorial-built-in-themes.asciidoc, line 50 at r2](https://reviewable.io:443/reviews/vaadin/flow/3295#-L2_CC60HbIhdS6PQbY3:-L2eF55wHAwWwweIf10s:bvrgbi1) ([raw file](https://github.com/vaadin/flow/blob/44eb00e5991757126863564aff14168f681bd57f/flow-documentation/theme/tutorial-built-in-themes.asciidoc#L50)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Done.
</blockquote></details>

But now it will throw, right?
So it would be nice to mention that here in tutorial.

---

*[flow-documentation/theme/tutorial-built-in-themes.asciidoc, line 59 at r6](https://reviewable.io:443/reviews/vaadin/flow/3295#-L2eFFawq3PGhlo3j7PL:-L2eFFawq3PGhlo3j7PM:b-srdk6c) ([raw file](https://github.com/vaadin/flow/blob/6d3987e9cf3a178c9857ca031e642d7fc460cc60/flow-documentation/theme/tutorial-built-in-themes.asciidoc#L59)):*
> a import

`an import` ?

---

*[flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java, line 435 at r6](https://reviewable.io:443/reviews/vaadin/flow/3295#-L2eFxIfpF410n-HS0uP:-L2eFxIfpF410n-HS0uQ:b-pdpget) ([raw file](https://github.com/vaadin/flow/blob/6d3987e9cf3a178c9857ca031e642d7fc460cc60/flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java#L435)):*
> element.getAllElements()

So it filters out the children.
There is no `getChildren` method ? Would it  better to use it instead of `getAllElements()`  if there is such method?

---

*[flow-server/src/main/resources/META-INF/services/javax.servlet.ServletContainerInitializer, line 4 at r6](https://reviewable.io:443/reviews/vaadin/flow/3295#-L2eGR9ublSmoCmjp0yB:-L2eGR9ublSmoCmjp0yC:b30ozc3) ([raw file](https://github.com/vaadin/flow/blob/6d3987e9cf3a178c9857ca031e642d7fc460cc60/flow-server/src/main/resources/META-INF/services/javax.servlet.ServletContainerInitializer#L4)):*
> com.vaadin.flow.server.startup.AnnotationValidator

I think Spring Boot needs this separately again.
Could you please create a ticket ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3295)*

**Comment by caalador** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks broke.

---

*[flow-documentation/theme/tutorial-built-in-themes.asciidoc, line 50 at r2](https://reviewable.io:443/reviews/vaadin/flow/3295#-L2_CC60HbIhdS6PQbY3:-L2eHkdmUe6GrBYwomgr:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/44eb00e5991757126863564aff14168f681bd57f/flow-documentation/theme/tutorial-built-in-themes.asciidoc#L50)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

But now it will throw, right?
So it would be nice to mention that here in tutorial.

</blockquote></details>

Done.

---

*[flow-documentation/theme/tutorial-built-in-themes.asciidoc, line 59 at r6](https://reviewable.io:443/reviews/vaadin/flow/3295#-L2eFFawq3PGhlo3j7PL:-L2eJReSc_K307HaAjL4:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/6d3987e9cf3a178c9857ca031e642d7fc460cc60/flow-documentation/theme/tutorial-built-in-themes.asciidoc#L59)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> a import

`an import` ?
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java, line 435 at r6](https://reviewable.io:443/reviews/vaadin/flow/3295#-L2eFxIfpF410n-HS0uP:-L2eI-PCwVcqvMH6CnwP:b-blq14m) ([raw file](https://github.com/vaadin/flow/blob/6d3987e9cf3a178c9857ca031e642d7fc460cc60/flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java#L435)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> element.getAllElements()

So it filters out the children.
There is no `getChildren` method ? Would it  better to use it instead of `getAllElements()`  if there is such method?
</blockquote></details>

Sadly there is no `getChildren` method available. only `getElements(By/Containing/Matching)Xyz` the big negative with the get all is that we get the main document also from there.
We filter it so that we only get the first level children as they bring in the rest of the elements below them.

---

*[flow-server/src/main/resources/META-INF/services/javax.servlet.ServletContainerInitializer, line 4 at r6](https://reviewable.io:443/reviews/vaadin/flow/3295#-L2eGR9ublSmoCmjp0yB:-L2eJK-Cu7E17Uyo3P9j:bbncwm7) ([raw file](https://github.com/vaadin/flow/blob/6d3987e9cf3a178c9857ca031e642d7fc460cc60/flow-server/src/main/resources/META-INF/services/javax.servlet.ServletContainerInitializer#L4)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> com.vaadin.flow.server.startup.AnnotationValidator

I think Spring Boot needs this separately again.
Could you please create a ticket ?
</blockquote></details>

#3303 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3295)*

**Comment by denis-anisimov** [comment]
Reviewed 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3295)*

**Pull request merged**
