### PR TITLE
perf: Cache stats.json loaded from class path

### LINKED ISSUE #9366: InputStream is not closed in com.vaadin.flow.server.frontend.FrontendUtils
Method `com.vaadin.flow.server.frontend.FrontendUtils#getFileContent` fails to close stream obtained via `getFileFromWebpack` or `getFileFromClassPath`

Method `com.vaadin.flow.server.frontend.FrontendUtils#getStatsContent` fails to close stream obtained via `getStatsFromClassPath`, `getStatsFromExternalUrl` or `getStatsFromWebpack`

### LINKED ISSUE #10116: loadtesting causes stats.json to fail to load sometimes
### Description of the bug / feature
I ran some loadtests with apache jmeter. The application works fine during debugging and also during the loadtests until some threshold (around 1000 users). Above that threshold during UI Initialization the application fails to load the stats.json file (I guess due too many open files).
### Minimal reproducible example
Haven't had the time yet to create a minimal example.
### Expected behavior
Opening a ui should cause the server to open the same file each time.
### Actual behavior
It fails to open stats.json
### Versions:
    - Vaadin / Flow version: Vaadin 14.4.7 (production mode, compatibility mode disabled)
    - Java version: 8
    - OS version: debian 9
    - Browser version (if applicable): apache jmeter
    - Application Server (if applicable): tomcat 8
    - IDE (if applicable):

I tried to capture some useful messages from the logs:
```
ERROR [http-nio-8080-exec-71] (FrontendUtils:505) - Cannot get the 'stats.json' from the classpath 'META-INF/VAADIN/config/stats.json'
WARN  [http-nio-8080-exec-71] (UIInitListener:67) - Unexpected exception occured: BootstrapException: Unable to read webpack stats file.
DEBUG [http-nio-8080-exec-71] (UIInitListener:70) - Unexpected exception occured: com.vaadin.flow.server.BootstrapException: Unable to read webpack stats file.
        at com.vaadin.flow.server.BootstrapHandler$BootstrapPageBuilder.setupFrameworkLibraries(BootstrapHandler.java:894)
        at com.vaadin.flow.server.BootstrapHandler$BootstrapPageBuilder.setupDocumentHead(BootstrapHandler.java:771)
        at com.vaadin.flow.server.BootstrapHandler$BootstrapPageBuilder.getBootstrapPage(BootstrapHandler.java:540)
        at com.vaadin.flow.server.BootstrapHandler.synchronizedHandleRequest(BootstrapHandler.java:481)
        at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
        at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1547)
        at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:247)
        at com.vaadin.cdi.CdiVaadinServlet.service(CdiVaadinServlet.java:67)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.openejb.server.httpd.EEFilter.doFilter(EEFilter.java:65)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:200)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.tomee.catalina.OpenEJBValve.invoke(OpenEJBValve.java:45)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:543)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.tomee.catalina.OpenEJBSecurityListener$RequestCapturer.invoke(OpenEJBSecurityListener.java:97)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:615)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:818)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1627)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: The stats file from webpack (stats.json) was not found.
The application is running in production mode.Verify that build-frontend task has executed successfully and that stats.json is on the classpath.Or switch application to development mode.
        at com.vaadin.flow.server.BootstrapHandler$BootstrapPageBuilder.appendNpmBundle(BootstrapHandler.java:926)
        at com.vaadin.flow.server.BootstrapHandler$BootstrapPageBuilder.setupFrameworkLibraries(BootstrapHandler.java:892)
        ... 38 more


```

### PR DESCRIPTION
**Pull request by knoobie**
fixes #10116

### CODE REVIEW

**Comment by knoobie** [comment]
@pleku  @mshabarov Created a PR with the changes from master. I had to adopt the change in the test a little bit, because there was no `VaadinContext` - now all test pass again :) I've added the new method as protected, so this can be easily changed to public in the 2.6 cherry pick of the bot.

**Comment by knoobie** [comment]
Test failure look totally unrelated 🙁

**Comment by mshabarov** [comment]
> Test failure look totally unrelated
Yes, it looks unrelated. And the logs say `SessionCloseLogoutIT` is failing, but it is shown as passed in another place. Will restart the build.

**Comment by mshabarov** [comment]
@knoobie thanks for fixing the tests and making this CP!
Don't you mind if I exclude the stream closing related changes and create an another PR for them?
The problem is that If we merge them into one commit, it then would be not transparent from a git history point of view and gives an additional pain to the guy who would release next version and make the release notes.

**Comment by knoobie** [comment]
@mshabarov I don't mind :) I think allow maintainers to edit is enabled, you can change it as you wish

**Comment by mshabarov** [comment]
InputStream close cherry pick: https://github.com/vaadin/flow/pull/10315

**Review by mshabarov — APPROVED** [review]

**Pull request merged**
