### PR TITLE
chore: Upgrade default installed Node

### PR DESCRIPTION
**Pull request by Artur-**

### CODE REVIEW

**Comment by mshabarov** [comment]
Is it okay to upgrade major version of NPM in the patch release?

**Comment by Artur-** [comment]
18.13 to 18.14 is not major?

**Comment by mshabarov** [comment]
> 18.13 to 18.14 is not major?

I meant minor version, sorry. 18.14 uses npm 9. I just worried that this can be a breaking change.

**Comment by Artur-** [comment]
18.14 is a security fix release recommended to everybody https://nodejs.org/en/blog/vulnerability/february-2023-security-releases/

**Review by mshabarov — APPROVED** [review]

**Pull request merged**
