### PR TITLE
Enable initial page configuration using PageConfigurator.

### PR DESCRIPTION
**Pull request by caalador**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3101)

### CODE REVIEW

**Comment by ZheSun88** [comment]
Reviewed 11 of 12 files at r1.
Review status: 11 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-documentation/application-structure/tutorial-bootstrap.asciidoc, line 115 at r1](https://reviewable.io:443/reviews/vaadin/flow/3101#-L-aiwwiAh2UKG3MfU50:-L-aiwwiAh2UKG3MfU51:b-yifer3) ([raw file](https://github.com/vaadin/flow/blob/2968f372970a04d22bb13b2bcdb31199b7de98c3/flow-documentation/application-structure/tutorial-bootstrap.asciidoc#L115)):*
> ```AsciiDoc
> 
>         head.appendChild(createMeta(document, "og:title", "The Rock"));
>             head.appendChild(createMeta(document, "og:type", "video.movie"));
> ```

oops. this is not your part, but did we lost some formatting?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3101)*

**Comment by caalador** [comment]
Review status: 9 of 13 files reviewed at latest revision, 12 unresolved discussions.

---

*[flow-documentation/application-structure/tutorial-bootstrap.asciidoc, line 115 at r1](https://reviewable.io:443/reviews/vaadin/flow/3101#-L-aiwwiAh2UKG3MfU50:-L-anzwr-AcHKpcUmO06:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/2968f372970a04d22bb13b2bcdb31199b7de98c3/flow-documentation/application-structure/tutorial-bootstrap.asciidoc#L115)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

oops. this is not your part, but did we lost some formatting?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3101)*

**Comment by ZheSun88** [comment]
:lgtm: 

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3101#-:-L-aotTZPdGrIp18qAB_:bg7igkv)*

**Comment by denis-anisimov** [comment]
Reviewed 9 of 12 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/server/BootstrapUtils.java, line 53 at r2](https://reviewable.io:443/reviews/vaadin/flow/3101#-L-eRDWke9v0EPnVLG9Q:-L-eRDWlyjnWiJu0MRq6:b-n6uwff) ([raw file](https://github.com/vaadin/flow/blob/00e21240acb670ddbf236d27b9a1d1b351ea0df3/flow-server/src/main/java/com/vaadin/server/BootstrapUtils.java#L53)):*
> protected 

?
Since its utility class it looks that it should be either package local or `public`.

---

*[flow-server/src/main/java/com/vaadin/server/BootstrapUtils.java, line 93 at r2](https://reviewable.io:443/reviews/vaadin/flow/3101#-L-eRTJ8kbm0FeGKO9qh:-L-eRTJ8kbm0FeGKO9qi:b78zu77) ([raw file](https://github.com/vaadin/flow/blob/00e21240acb670ddbf236d27b9a1d1b351ea0df3/flow-server/src/main/java/com/vaadin/server/BootstrapUtils.java#L93)):*
> protected

same here

---

*[flow-server/src/main/java/com/vaadin/server/InitialPageSettings.java, line 63 at r2](https://reviewable.io:443/reviews/vaadin/flow/3101#-L-eS-oULfBRsm_kPum1:-L-eS-oULfBRsm_kPum2:b-l09048) ([raw file](https://github.com/vaadin/flow/blob/00e21240acb670ddbf236d27b9a1d1b351ea0df3/flow-server/src/main/java/com/vaadin/server/InitialPageSettings.java#L63)):*
> private Map

also `final` ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3101)*

**Comment by caalador** [comment]
Review status: 10 of 13 files reviewed at latest revision, 5 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/server/BootstrapUtils.java, line 53 at r2](https://reviewable.io:443/reviews/vaadin/flow/3101#-L-eRDWke9v0EPnVLG9Q:-L-jW2F5QFX2F2gb3bqu:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/00e21240acb670ddbf236d27b9a1d1b351ea0df3/flow-server/src/main/java/com/vaadin/server/BootstrapUtils.java#L53)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> protected 

?
Since its utility class it looks that it should be either package local or `public`.
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/server/BootstrapUtils.java, line 93 at r2](https://reviewable.io:443/reviews/vaadin/flow/3101#-L-eRTJ8kbm0FeGKO9qh:-L-jW2Wf69v0E-y-kag7:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/00e21240acb670ddbf236d27b9a1d1b351ea0df3/flow-server/src/main/java/com/vaadin/server/BootstrapUtils.java#L93)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> protected

same here
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/server/InitialPageSettings.java, line 63 at r2](https://reviewable.io:443/reviews/vaadin/flow/3101#-L-eS-oULfBRsm_kPum1:-L-jWDi0z7c7tzx-u4Eb:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/00e21240acb670ddbf236d27b9a1d1b351ea0df3/flow-server/src/main/java/com/vaadin/server/InitialPageSettings.java#L63)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> private Map

also `final` ?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3101)*

**Comment by denis-anisimov** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3101)*

**Pull request merged**
