### PR TITLE
Add new interfaces

### PR DESCRIPTION
**Pull request by caalador**
Add new DataView interfaces
and their mixin interfaces.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/8272)

### CODE REVIEW

**Comment by mshabarov** [comment]
___
*[flow-data/src/main/java/com/vaadin/flow/data/provider/ListDataView.java, line 72 at r1](https://reviewable.io/reviews/vaadin/flow/8272#-M6j78oj51zxmERV113c:-M6j78oj51zxmERV113d:bum7gh0) ([raw file](https://github.com/vaadin/flow/blob/c2495aed17a4937b00826a73a1ec7867dc879efc/flow-data/src/main/java/com/vaadin/flow/data/provider/ListDataView.java#L72)):*
> ```Java
>      *         filter to add for the data
>      */
>     void withFilter(SerializablePredicate<T> filter);
> ```

Could we improve it by introducing <? super T> instead of just <T>?

**Comment by mshabarov** [comment]
___
*[flow-data/src/main/java/com/vaadin/flow/data/provider/ListDataView.java, line 72 at r1](https://reviewable.io/reviews/vaadin/flow/8272#-M6j78oj51zxmERV113c:-M6j7XotD35DUCKPFOGf:bw9zduq) ([raw file](https://github.com/vaadin/flow/blob/c2495aed17a4937b00826a73a1ec7867dc879efc/flow-data/src/main/java/com/vaadin/flow/data/provider/ListDataView.java#L72)):*
<details><summary><i>Previously, mshabarov (Mikhail Shabarov) wrote…</i></summary><blockquote>

Could we improve it by introducing <? super T> instead of just <T>?
</blockquote></details>

* instead of just <T>

**Comment by mshabarov** [comment]
___
*[flow-data/src/main/java/com/vaadin/flow/data/provider/ListDataView.java, line 72 at r1](https://reviewable.io/reviews/vaadin/flow/8272#-M6j7mIe-iHA7ZiEutRW:-M6j7mIe-iHA7ZiEutRX:bsws4fj) ([raw file](https://github.com/vaadin/flow/blob/c2495aed17a4937b00826a73a1ec7867dc879efc/flow-data/src/main/java/com/vaadin/flow/data/provider/ListDataView.java#L72)):*
> ```Java
>      *         filter to add for the data
>      */
>     void withFilter(SerializablePredicate<T> filter);
> ```

Could we improve it by changing to <? super T>?

**Comment by mshabarov** [comment]
___
*[flow-data/src/main/java/com/vaadin/flow/data/provider/HasListDataView.java, line 51 at r1](https://reviewable.io/reviews/vaadin/flow/8272#-M6j85pg2aI3S03RPrzt:-M6j85pg2aI3S03RPrzu:b-l0vo3u) ([raw file](https://github.com/vaadin/flow/blob/c2495aed17a4937b00826a73a1ec7867dc879efc/flow-data/src/main/java/com/vaadin/flow/data/provider/HasListDataView.java#L51)):*
> ```Java
>      * @return ListDataView instance
>      */
>     V setDataProvider(Collection<T> items);
> ```

Could we use <? extends T> here?

**Comment by caalador** [comment]
@Legioth @pleku  what do you think?
I would keep them as strong type, but if we would want to have them less restrictive now would perhaps be the time to do it.

**Comment by caalador** [comment]
Closing as I messed this up with a faulty GUI configuration new is #8276

**Pull request closed without merging**
