### PR TITLE
Use VaadinService methods in BundleFilter

### PR DESCRIPTION
**Pull request by Artur-**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3887)

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
Review status: 0 of 36 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[flow-server/src/main/java/com/vaadin/flow/server/startup/BundleFilterInitializer.java, line 82 at r2](https://beta.reviewable.io/reviews/vaadin/flow/3887#-LAJY-YBA8FlKRvhnwDk:-LAJY-YBA8FlKRvhnwDl:b-8s2nhf) ([raw file](https://github.com/vaadin/flow/blob/5485b57b22855fe523fb7fcbf2b123fe73caf5db/flow-server/src/main/java/com/vaadin/flow/server/startup/BundleFilterInitializer.java#L82)):*
> ```
> "frontend://"
> ```

I propose to use `ApplicationConstants.FRONTEND_PROTOCOL_PREFIX`

---

*[flow-server/src/main/java/com/vaadin/flow/server/startup/BundleFilterInitializer.java, line 100 at r2](https://beta.reviewable.io/reviews/vaadin/flow/3887#-LAJXMoY-F5QLlM9rXB8:-LAJXMoY-F5QLlM9rXB9:b30rfce) ([raw file](https://github.com/vaadin/flow/blob/5485b57b22855fe523fb7fcbf2b123fe73caf5db/flow-server/src/main/java/com/vaadin/flow/server/startup/BundleFilterInitializer.java#L100)):*
> ```Java
>                 for (int i = 0; i < bundledFiles.length(); i++) {
>                     String bundledFile = bundledFiles.getString(i);
>                     if (!service.isResourceAvailable(bundledFile, es6Browser,
> ```

My fault, I've missed this in previous PR: this check is wrong.

`bundledFile` is the file that is included in bundle, it should not be present in the `frontend://` directory of the app that's bundled.

What we should check here (and what was checked before you've changed it) is the `bundlePath` availability: it should be present in the `frontend://` directory.
Also, this check should be moved outside the cycle, since it's enough to check it once (this was the fault in the original version that might have tricked you).

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3887)*

**Comment by SomeoneToIgnore** [comment]
*[flow-server/src/test/java/com/vaadin/flow/server/startup/BundleFilterInitializerTest.java, line 62 at r2](https://beta.reviewable.io/reviews/vaadin/flow/3887#-LAJZJTVB_lDUnM9qaSt:-LAJZJTVB_lDUnM9qaSu:b-fzv5vi) ([raw file](https://github.com/vaadin/flow/blob/5485b57b22855fe523fb7fcbf2b123fe73caf5db/flow-server/src/test/java/com/vaadin/flow/server/startup/BundleFilterInitializerTest.java#L62)):*
> ```Java
>         mocks = new MockServletServiceSessionSetup();
>         event = Mockito.mock(ServiceInitEvent.class);
>         Mockito.when(event.getSource()).thenReturn(mocks.getService());
> ```

As it turns out, by the moment `BundleFilterIntializer` executes, there are no `VaadinSession` and `VaadinRequest`.
This PR implicitly fixes the issue caused the demo to fail in production mode, but I propose to modify these tests in a way that clearly shows that there are no mock sessions or requests set up.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3887)*

**Comment by Artur-** [comment]
Review status: 0 of 17 files reviewed at latest revision, 4 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/server/startup/BundleFilterInitializer.java, line 82 at r2](https://beta.reviewable.io/reviews/vaadin/flow/3887#-LAJY-YBA8FlKRvhnwDk:-LAJm7kS9qWiv8f-i8Ta:bdig7s2) ([raw file](https://github.com/vaadin/flow/blob/5485b57b22855fe523fb7fcbf2b123fe73caf5db/flow-server/src/main/java/com/vaadin/flow/server/startup/BundleFilterInitializer.java#L82)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

> ```
> "frontend://"
> ```

I propose to use `ApplicationConstants.FRONTEND_PROTOCOL_PREFIX`
</blockquote></details>

Done, although it feels harder to read `ApplicationConstants.FRONTEND_PROTOCOL_PREFIX + FLOW_BUNDLE_MANIFEST` than `"frontend://" + FLOW_BUNDLE_MANIFEST´ (and it's not like the protocol name is going to change)

---

*[flow-server/src/main/java/com/vaadin/flow/server/startup/BundleFilterInitializer.java, line 100 at r2](https://beta.reviewable.io/reviews/vaadin/flow/3887#-LAJXMoY-F5QLlM9rXB8:-LAJfNgA9ojnlR20eOg-:b-1fsw2q) ([raw file](https://github.com/vaadin/flow/blob/5485b57b22855fe523fb7fcbf2b123fe73caf5db/flow-server/src/main/java/com/vaadin/flow/server/startup/BundleFilterInitializer.java#L100)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

My fault, I've missed this in previous PR: this check is wrong.

`bundledFile` is the file that is included in bundle, it should not be present in the `frontend://` directory of the app that's bundled.

What we should check here (and what was checked before you've changed it) is the `bundlePath` availability: it should be present in the `frontend://` directory.
Also, this check should be moved outside the cycle, since it's enough to check it once (this was the fault in the original version that might have tricked you).
</blockquote></details>

Yep, and apparently the test was changed the wrong way also..

---

*[flow-server/src/test/java/com/vaadin/flow/server/startup/BundleFilterInitializerTest.java, line 62 at r2](https://beta.reviewable.io/reviews/vaadin/flow/3887#-LAJZJTVB_lDUnM9qaSt:-LAJlx2C6PcSWLJIR2s-:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/5485b57b22855fe523fb7fcbf2b123fe73caf5db/flow-server/src/test/java/com/vaadin/flow/server/startup/BundleFilterInitializerTest.java#L62)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

As it turns out, by the moment `BundleFilterIntializer` executes, there are no `VaadinSession` and `VaadinRequest`.
This PR implicitly fixes the issue caused the demo to fail in production mode, but I propose to modify these tests in a way that clearly shows that there are no mock sessions or requests set up.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3887)*

**Comment by SomeoneToIgnore** [comment]
Waits for https://github.com/vaadin/flow/pull/3881 to be merged, otherwise fine.

---

Reviewed 2 of 36 files at r1, 2 of 3 files at r2, 6 of 11 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3887#-:-LANHqqD91mdW7GAYB4t:b3ujns7)*

**Comment by SomeoneToIgnore** [comment]
Two test fail, funny that they have not failed in your previous PR.
The cause is  `VaadinServlet` class with 
```
protected Optional<WebJarServer> getWebJarServer() {
        return Optional.of(webJarServer);
    }
```
method.

It should be `Optional.ofNullable`

---







*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3887#-:-LANlYNH8KyZABCm4Ha7:b-aa95g5)*

**Comment by SomeoneToIgnore** [comment]
Hm, same test for the same code pass for current master, so the problem might be bigger than I thought.

---







*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3887#-:-LANmggY---mZl3uEheS:b-6asj5b)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 1 of 4 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3887)*

**Comment by SomeoneToIgnore** [comment]
Turns out to be fine, it's related to these changes, we init ServletService in the test which inits the BundleFilter which has no session.

:lgtm: 

---







*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3887#-:-LANnVNN9RiISK1on-C3:bpbrg43)*

**Pull request merged**
