### PR TITLE
chore: Remove unused code

### PR DESCRIPTION
**Pull request by Artur-**

### CODE REVIEW

**Comment by Artur-** [comment]
Is this code really not used? No tests are failing... Potentially a left over from #12204

**Comment by caalador** [comment]
As we do not use the stats.json for template contents anymore, do we even need the BundleParser classes? I couldn't see any usage of them anywhere except for in one test.

**Comment by Artur-** [comment]
Seems like `parseTemplateElement` is used by `NpmTemplateParser` and the rest can be removed. Give me one minute..

**Comment by Artur-** [comment]
Let's see if everything still works then..

**Comment by Artur-** [comment]
All seems fine..

**Review by caalador — APPROVED** [review]
Would seem to be fine as expected by usage found.

**Pull request merged**
