### PR TITLE
Extract module to be able to enable production mode

### PR DESCRIPTION
**Pull request by denis-anisimov**
* Enable production mode for root-context module
* Extract dev mode tests to the separate module
* Extract common UI classes to the common module

Fix for #4266

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/4288)

### CODE REVIEW

**Comment by pekam** [comment]
Review status: 2 unresolved discussions, 0 of 1 LGTMs obtained

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow/4288#-LF1KNKQ4KTjptaiGPRC:-LF1KNKQ4KTjptaiGPRD:bm6wjen) (no related file):*
If I run the `test-root-context` tests now with `-Dvaadin.productionMode`, I get 12 failures and 12 errors. At least some of them are clearly dev mode related:
`ExportedJSFunctionIT.productionModeFalseInDevelopmentMode`
`ExportedJSFunctionIT.versionInfoAvailableInDevelopmentMopde`
So should more of the tests be moved to`flow-test-dev-mode`?

Or do you think we should just ignore those tests for IE11? (not part of this ticket, I know, just discussing)

---

*[flow-tests/test-common/src/main/java/com/vaadin/flow/uitest/servlet/Es6UrlViewTestServlet.java, line 38 at r2](https://reviewable.io/reviews/vaadin/flow/4288#-LEyEoiu3OGz2wrdKFQN:-LEyEoiu3OGz2wrdKFQO:bb1pagn) ([raw file](https://github.com/vaadin/flow/blob/87c53d137129bc07ef16a5fc86e8ae6ea5c2867d/flow-tests/test-common/src/main/java/com/vaadin/flow/uitest/servlet/Es6UrlViewTestServlet.java#L38)):*
> ```Java
>             Properties initParameters) {
> 
>         // Configure frontend:// as <context>/frontend/com/vaadin/flow/uitest/
> ```

It doesn't explain why this is needed.
If this is because of the issue in maven plugin, a reference to that ticket could be added here.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4288)*

**Comment by denis-anisimov** [comment]
Review status: 2 unresolved discussions, 0 of 1 LGTMs obtained

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow/4288#-LF1KNKQ4KTjptaiGPRC:-LF1WLEl4gFGux_Lyvj_:b87yeal) (no related file):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

If I run the `test-root-context` tests now with `-Dvaadin.productionMode`, I get 12 failures and 12 errors. At least some of them are clearly dev mode related:
`ExportedJSFunctionIT.productionModeFalseInDevelopmentMode`
`ExportedJSFunctionIT.versionInfoAvailableInDevelopmentMopde`
So should more of the tests be moved to`flow-test-dev-mode`?

Or do you think we should just ignore those tests for IE11? (not part of this ticket, I know, just discussing)
</blockquote></details>

This patch is not about running the tests.
The ticket says: `Enable production mode in flow-test-root-context`.

The production mode is enabled.
I'm expecting quite many test failures. But this is totally different story.
It would be a hell to fix the test here in this PR as well.
The problem is that production mode couldn't be enabled easily for `root-context` tests.
And this is done by the PR.

Now we have the  production mode enabled.

The next step is fix all the test. This is definitely a next step which is unrelated to this task.
It requires a separate discussion and I would prefer to keep in a different place.

Some tests may be ignored.  Some tests are just totally invalid for production mode (there are tests which are executed in production mode but they don't assume transpiled files presence. Quite artificial tests).
Every test requires its own approach. 
It has no sense to care about them here.
The goal was to get transpilation work against the `root-context`  module. That wasn't even close to easy task and now the module can be transpiled.
Everything else is out of the scope.

---

*[flow-tests/test-common/src/main/java/com/vaadin/flow/uitest/servlet/Es6UrlViewTestServlet.java, line 38 at r2](https://reviewable.io/reviews/vaadin/flow/4288#-LEyEoiu3OGz2wrdKFQN:-LF1YQVe89XZtqjfH2km:b-j1eiz9) ([raw file](https://github.com/vaadin/flow/blob/87c53d137129bc07ef16a5fc86e8ae6ea5c2867d/flow-tests/test-common/src/main/java/com/vaadin/flow/uitest/servlet/Es6UrlViewTestServlet.java#L38)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

It doesn't explain why this is needed.
If this is because of the issue in maven plugin, a reference to that ticket could be added here.
</blockquote></details>

I have no any idea why it's needed. 
This is not written by me. 
This is just extracted class from the `root-context` module (AS IS). Don't know why Git didn't recognize this.

I have no answer to the question and will never have.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4288)*

**Comment by pekam** [comment]
Review status: 1 unresolved discussion, 0 of 1 LGTMs obtained

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow/4288#-LF1KNKQ4KTjptaiGPRC:-LF1sAB8BmkGih-QliYF:b76k7m5) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

This patch is not about running the tests.
The ticket says: `Enable production mode in flow-test-root-context`.

The production mode is enabled.
I'm expecting quite many test failures. But this is totally different story.
It would be a hell to fix the test here in this PR as well.
The problem is that production mode couldn't be enabled easily for `root-context` tests.
And this is done by the PR.

Now we have the  production mode enabled.

The next step is fix all the test. This is definitely a next step which is unrelated to this task.
It requires a separate discussion and I would prefer to keep in a different place.

Some tests may be ignored.  Some tests are just totally invalid for production mode (there are tests which are executed in production mode but they don't assume transpiled files presence. Quite artificial tests).
Every test requires its own approach. 
It has no sense to care about them here.
The goal was to get transpilation work against the `root-context`  module. That wasn't even close to easy task and now the module can be transpiled.
Everything else is out of the scope.
</blockquote></details>

I know. Let me re-phrase it a bit:
I tried just for lulz how does it work now if I run the tests in production mode.
I noticed that there are some failing tests, many with the word `development mode` in it.
Your PR moves dev mode related tests to a new module: `flow-test-dev-mode`.
So as a consequence I get a concern that are maybe some tests are still in the wrong package. I'm not saying that they are, but I'm asking you to check because the names of those tests sound suspicious.

---

*[flow-tests/test-common/src/main/java/com/vaadin/flow/uitest/servlet/Es6UrlViewTestServlet.java, line 38 at r2](https://reviewable.io/reviews/vaadin/flow/4288#-LEyEoiu3OGz2wrdKFQN:-LF1r3uK3qEbqC8j-BU7:b-yuke8q) ([raw file](https://github.com/vaadin/flow/blob/87c53d137129bc07ef16a5fc86e8ae6ea5c2867d/flow-tests/test-common/src/main/java/com/vaadin/flow/uitest/servlet/Es6UrlViewTestServlet.java#L38)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

I have no any idea why it's needed. 
This is not written by me. 
This is just extracted class from the `root-context` module (AS IS). Don't know why Git didn't recognize this.

I have no answer to the question and will never have.
</blockquote></details>

Okay, I thought it was from you because you reported earlier a problem that looked like it's related to this (and because Git showed the change).

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4288)*

**Comment by denis-anisimov** [comment]
Review status: 1 unresolved discussion, 0 of 1 LGTMs obtained

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow/4288#-LF1KNKQ4KTjptaiGPRC:-LF24KHnB2AyVR6mWCFO:bvhraum) (no related file):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

I know. Let me re-phrase it a bit:
I tried just for lulz how does it work now if I run the tests in production mode.
I noticed that there are some failing tests, many with the word `development mode` in it.
Your PR moves dev mode related tests to a new module: `flow-test-dev-mode`.
So as a consequence I get a concern that are maybe some tests are still in the wrong package. I'm not saying that they are, but I'm asking you to check because the names of those tests sound suspicious.
</blockquote></details>

The "dev mode" related test in this PR are: the tests which cannot be anyhow kept in this module because our maven plugin just fails (so the build won't be successful). 
I haven't run any test in dev mode.

The UI/View classes that break the maven plugin execution have been moved out from the module.
So now the production mode transpiles the module sources.

It might be that there are a number of other classes which needs to be moved to the `dev-mode` module.
To know that we need to run them in production mode at least once (all the test).
This is another task. (end every such test needs its decision : whether it should be corrected or just moved out)

So yes, only one part is done. But this part fixes the ticket. 
Even if there are other tests that should be executed only in dev mode I care only about classes which allows to transpile.

It's not worth do to everything at once.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4288)*

**Comment by pekam** [comment]
:lgtm:

---

Reviewed 37 of 46 files at r1, 9 of 9 files at r2.
Review status: all discussions resolved, 0 of 1 LGTMs obtained, and 1 stale

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4288#-:-LF2G2OJ9CEcGbA2inmk:bnfp4nl)*

**Pull request merged**
