### PR TITLE
Implement open and setLocation method to Page. (#4869)

### LINKED ISSUE #4869: Page.open() / Page.setLocation() functionality
In previous Vaadin versions, the `Page` object provided methods for opening new browser tabs or opening a new URL with the `open` and `setLocation` methods. Currently in Flow, you need to use `executeJavaScript` or similar to achieve this kind of behavior. It would be convenient to have this functionality available on the Java side, even just as simple facades for JavaScript calls.

### PR DESCRIPTION
**Pull request by sahalsaad**
Fixes #4869 
Implement new method to Page.class:

```
open(String url, String windowName)
open(String url, String windowName, int width, int height)
setLocation(String uri)
setLocation(URI uri)
```

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/5166)

### CODE REVIEW

**Comment by sahalsaad** [comment]
I not sure why in teamcity have extra 28 to the window height.

**Comment by sahalsaad** [comment]
___
*[flow-server/src/main/java/com/vaadin/flow/component/page/Page.java, line 452 at r1](https://reviewable.io/reviews/vaadin/flow/5166#-L_uyFMjBf8HhRHbL5gw:-LaGDzZlDEL5rJ4I0bdK:buz188q) ([raw file](https://github.com/vaadin/flow/blob/cad9bf6da03b16f29f871de5066d63039bea911a/flow-server/src/main/java/com/vaadin/flow/component/page/Page.java#L452)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

I believe `open(String url, String windowName)` should be just a shorthand (convenience) method for `open( url, windowName, Collections.emptyMap())`.

So there should be one main method `open(String url, String windowName, Map<String, String> windowFeatures)` which contain the real implementation and a number of delegates/convenience 
methods.

So I wold say there is no reason to introduce interim convenience method in one PR and then rewrite it via another method in another PR.
</blockquote></details>

The `open(String url, String windowName)` is a private method. Implement `windowFeatures`  with a better design, demo and test worth a PR.

**Comment by denis-anisimov** [comment]
Something weird happens with validation.
I think you should rebase this PR against master branch.

**Comment by sahalsaad** [comment]
@denis-anisimov done.

**Pull request merged**
