### PR TITLE
Extract Renderer interface from ComponentRenderer

### PR DESCRIPTION
**Pull request by denis-anisimov**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/2995)

### CODE REVIEW

**Comment by gilberto-torrezan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2995#-KzTKXGtEuVTrdcYixtk:-KzTKXGtEuVTrdcYixtl:b-vqjrd2) (no related file):*
I'm not sure about this design. `TemplateRenderer` wouldn't be a `Renderer`, which is a bit confusing.

Also, do you have examples of other classes that would implement this interface?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2995)*

**Comment by torok-peter** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/ui/renderers/Renderer.java, line 22 at r1](https://reviewable.io:443/reviews/vaadin/flow/2995#-KzTLGl4e3sqeyhbDZxn:-KzTLGl4e3sqeyhbDZxo:bskcav4) ([raw file](https://github.com/vaadin/flow/blob/061728a19341527176b16b663854e858d7d5d65d/flow-server/src/main/java/com/vaadin/ui/renderers/Renderer.java#L22)):*
> A renderer that allows the usage of regular {@link Component}s as an item representation.

This is the same purpose as for `ComponentRenderer` itself, so why was this interface created?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2995)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2995#-KzTKXGtEuVTrdcYixtk:-KzTLNAVXTCU_mgPumss:bebxttb) (no related file):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

I'm not sure about this design. `TemplateRenderer` wouldn't be a `Renderer`, which is a bit confusing.

Also, do you have examples of other classes that would implement this interface?
</blockquote></details>

That's the exact need : `TemplateRenderer`  is actually quite specific for `Grid` . May be for other components.
It is based on `String` template.

But `RadioButtonGroup`  e.g. doesn't accept/have any strings at all. So it cannot be used with the `RBG`.
The `RBG`  accepts a component.

So any implementation of this interface which returns a component will work for `RBG` (any custom implementation).
So there are infinite examples of implementations.

Technically `ComponentRenderer` should be renamed to `ComponentTemplateRenderer` and `Renderer`  to `ComponentRenderer` .

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2995)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/ui/renderers/Renderer.java, line 22 at r1](https://reviewable.io:443/reviews/vaadin/flow/2995#-KzTLGl4e3sqeyhbDZxn:-KzTMVd2Z3NWMUk7Rwmu:b-wj6dc1) ([raw file](https://github.com/vaadin/flow/blob/061728a19341527176b16b663854e858d7d5d65d/flow-server/src/main/java/com/vaadin/ui/renderers/Renderer.java#L22)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

> A renderer that allows the usage of regular {@link Component}s as an item representation.

This is the same purpose as for `ComponentRenderer` itself, so why was this interface created?
</blockquote></details>

`ComponentRenderer` is a class.
It extends `TemplateRenderer`  with all its stuff which is not needed at all.
That's the reason: interface declares contract which is only needed to be implemented without all `TemplateRenderer`  details.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2995)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/ui/renderers/Renderer.java, line 22 at r1](https://reviewable.io:443/reviews/vaadin/flow/2995#-KzTLGl4e3sqeyhbDZxn:-KzTMqhHW14w70xPK3qs:bqcpn6v) ([raw file](https://github.com/vaadin/flow/blob/061728a19341527176b16b663854e858d7d5d65d/flow-server/src/main/java/com/vaadin/ui/renderers/Renderer.java#L22)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

`ComponentRenderer` is a class.
It extends `TemplateRenderer`  with all its stuff which is not needed at all.
That's the reason: interface declares contract which is only needed to be implemented without all `TemplateRenderer`  details.
</blockquote></details>

Technically the Javadoc  for `ComponentRenderer` is bad and should be corrected.

Also it might be that it should be renamed to `ComponentTemplateRenderer`  as I mentioned in the response to Gilberto.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2995)*

**Comment by gilberto-torrezan** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2995#-KzTKXGtEuVTrdcYixtk:-KzTMdEw1vW3p2E1Lzvx:bxthqmw) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

That's the exact need : `TemplateRenderer`  is actually quite specific for `Grid` . May be for other components.
It is based on `String` template.

But `RadioButtonGroup`  e.g. doesn't accept/have any strings at all. So it cannot be used with the `RBG`.
The `RBG`  accepts a component.

So any implementation of this interface which returns a component will work for `RBG` (any custom implementation).
So there are infinite examples of implementations.

Technically `ComponentRenderer` should be renamed to `ComponentTemplateRenderer` and `Renderer`  to `ComponentRenderer` .
</blockquote></details>

That's a bit odd. How can it work with Components but not with Strings? I mean, in the end the components are translated to bunch of tags (text) that are stamped in a template.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2995)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2995#-KzTKXGtEuVTrdcYixtk:-KzTNLgEiHOJAhAg2-fG:bas86yv) (no related file):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

That's a bit odd. How can it work with Components but not with Strings? I mean, in the end the components are translated to bunch of tags (text) that are stamped in a template.
</blockquote></details>

`RBG` contains a number of `RadioButton` components.
Each `RadioButton` component is a container which has a `<slot>` .
You can set any _component_ directly into the slot without having any `String`s as a template.
`RBG` just doesn't support `template` concept at all.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2995)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2995#-KzTKXGtEuVTrdcYixtk:-KzTNvIdYlcUA2wnJBwV:b-f912wc) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

`RBG` contains a number of `RadioButton` components.
Each `RadioButton` component is a container which has a `<slot>` .
You can set any _component_ directly into the slot without having any `String`s as a template.
`RBG` just doesn't support `template` concept at all.
</blockquote></details>

Of course I can create a wrapper component based on `String` as a template via setting its `innerHtml` property but there is no any sense it this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2995)*

**Comment by gilberto-torrezan** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2995#-KzTKXGtEuVTrdcYixtk:-KzTND_Bn7l8fiF1kU7h:b-3b24n4) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Of course I can create a wrapper component based on `String` as a template via setting its `innerHtml` property but there is no any sense it this.
</blockquote></details>

I see. So the naming is the only problem here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2995)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2995#-KzTKXGtEuVTrdcYixtk:-KzTOObnahE1_dKN5uZu:bb77ucv) (no related file):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

I see. So the naming is the only problem here.
</blockquote></details>

Yep.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2995)*

**Comment by gilberto-torrezan** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2995#-KzTKXGtEuVTrdcYixtk:-KzTOYleQ71jHIUptenZ:bbo639j) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Yep.
</blockquote></details>

Nothing prevents you from using a `SerializableFunction<Component, Item>` though. Except javadocs.

Would be a `ComponentFunction` a good name? No I guess...

I'm out of ideas. The best case would be rename everything like you mentioned.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2995)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2995#-KzTKXGtEuVTrdcYixtk:-KzTP8HbW97t58-DikRq:b3m71c6) (no related file):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Nothing prevents you from using a `SerializableFunction<Component, Item>` though. Except javadocs.

Would be a `ComponentFunction` a good name? No I guess...

I'm out of ideas. The best case would be rename everything like you mentioned.
</blockquote></details>

There was a decision at some point that we need named interfaces for this type of functionality.
So no for `SerializableFunction`.

Let's rename as I suggested, no problems.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2995)*

**Comment by denis-anisimov** [comment]
Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2995#-KzTKXGtEuVTrdcYixtk:-KzTQ-EZUysMUqENJAwe:b-896fix) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

There was a decision at some point that we need named interfaces for this type of functionality.
So no for `SerializableFunction`.

Let's rename as I suggested, no problems.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2995)*

**Comment by gilberto-torrezan** [comment]
Review status: 0 of 7 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2995#-KzTRMkGpqg8xjFqjL2s:-KzTRMkGpqg8xjFqjL2t:bty6y0d) (no related file):*
You will probably have validation errors in the documentation.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2995#-KzTRf9Yyg4v5BGXYFkx:-KzTRf9Yyg4v5BGXYFky:bf467y6) (no related file):*
Also this class rename needs to be  listed as a breaking change next release.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2995)*

**Comment by denis-anisimov** [comment]
Review status: 0 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2995#-KzTRMkGpqg8xjFqjL2s:-KzTTeJM1jBQfOh42mEc:bypb2cy) (no related file):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

You will probably have validation errors in the documentation.
</blockquote></details>

No , there are compilation errors in demo.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2995#-KzTRf9Yyg4v5BGXYFkx:-KzTThBVjY9ETx5TSa4W:b-8wlyz4) (no related file):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Also this class rename needs to be  listed as a breaking change next release.
</blockquote></details>

Yes, but that's not for now, right? Or there is a list if all breaking changes ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2995)*

**Comment by torok-peter** [comment]
Reviewed 10 of 10 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2995)*

**Comment by gilberto-torrezan** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2995#-KzTRf9Yyg4v5BGXYFkx:-KzTjDtmScZuZpCB3viZ:b-hntzrd) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Yes, but that's not for now, right? Or there is a list if all breaking changes ?
</blockquote></details>

Yes, not now. Only when we gather the release notes for the release next Thursday.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2995)*

**Pull request merged**
