### PR TITLE
fix: linux node installation

### LINKED ISSUE #14636: Node 18 does not work because Node installer does not unpack all node files
### Description of the bug

When you do not have a suitable Node installed and Flow downloads it, it is placed in ~/.vaadin

There you get the standard node distribution downloaded, e.g. `node-v18.9.1-darwin-arm64.tar.gz` when upgrading Flow to use 18.9.1 and you use a Mac M1.

Then this version is unpacked somehow into ~/.vaadin/node but not by extracting the archive as you would expect. Instead there is only a `node` file and an `node_modules` folder. Is there any reason to do this instead of just unpacking node like the node team says you should?

For Node 18 this does not even work as if you run
```
~/.vaadin/node/node ~/.vaadin/node/node_modules/npm/bin/npx-cli.js pnpm
```

You get
```
npm ERR! code ENOENT
npm ERR! syscall lstat
npm ERR! path /.../.vaadin/lib
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, lstat '/.../.vaadin/lib'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
```

because the directory structure has been changed

### Expected behavior

Node is installed by unpacking the distribution package and nothing else

### Minimal reproducible example

https://github.com/vaadin/flow/pull/14635

### Versions

- Vaadin / Flow version:
- Java version:
- OS version:
- Browser version (if applicable):
- Application Server (if applicable):
- IDE (if applicable):

### PR DESCRIPTION
**Pull request by caalador**
Fix installation of node for unix systems.
NodeJS 18 is more strict about where
the contents are located than old versions.

Fixes #14636

### CODE REVIEW

**Comment by Artur-** [comment]
Seems like this does not work properly yet. #14661 happens with this PR also

**Comment by caalador** [comment]
npm was copied to the wrong place. Test again. Did not show up for me as I don't have a global old node on my WSL debian so it found the correct place with search.

**Comment by Artur-** [comment]
Still looks for `~/.vaadin/node/node_modules/npm/bin/npm-cli.js` in `FrontendTools.getNpmScriptCommand`, then it fails

**Comment by Artur-** [comment]
Seems like there is some test missing also if the build is green ..

**Comment by caalador** [comment]
I'll see if I can get a test for that also.

**Comment by Artur-** [comment]
Now the app starts and then produces
```
Caused by: java.lang.IllegalStateException: 

======================================================================================================
Your installed 'npm' version (6.14.16) is too old. Supported versions are 8.3+
Please install a new one either:
  - by following the https://nodejs.org/en/download/ guide to install it globally
  - or by running the frontend-maven-plugin goal to install it in this project:
  $ mvn com.github.eirslett:frontend-maven-plugin:1.10.0:install-node-and-npm -DnodeVersion="v18.9.1" 

You can disable the version check using -Dvaadin.ignoreVersionChecks=true
======================================================================================================

	at com.vaadin.flow.server.frontend.FrontendUtils.validateToolVersion(FrontendUtils.java:950)
	at com.vaadin.flow.server.frontend.FrontendTools.validateNodeAndNpmVersion(FrontendTools.java:649)
	at com.vaadin.base.devserver.AbstractDevServerRunner.doStartDevServer(AbstractDevServerRunner.java:352)
	at com.vaadin.base.devserver.AbstractDevServerRunner.doStartDevModeServer(AbstractDevServerRunner.java:215)
	at com.vaadin.base.devserver.AbstractDevServerRunner.runOnFutureComplete(AbstractDevServerRunner.java:171)
	at com.vaadin.base.devserver.AbstractDevServerRunner.lambda$new$0(AbstractDevServerRunner.java:162)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

How many times does it check the npm version in different ways...

**Comment by caalador** [comment]
It should be the same check. Do you still have the eirslett installation in the project under the folder {project}/node?

**Comment by Artur-** [comment]
> Do you still have the eirslett installation in the project under the folder {project}/node?

Nope but some other extra files that apparently caused this

**Comment by caalador** [comment]
I added there the cleanup of the old node_modules position so that should help with updating from an older version.

**Review by Artur- — APPROVED** [review]

**Comment by Artur-** [comment]
Should this target master though and not the node18 branch?

**Comment by caalador** [comment]
This builds on the node18 branch and I though we could get that in at the same time.
Even though this change should work with v16 also.

**Pull request merged**
