### PR TITLE
Use com.vaadin.flow.component package instead of com.vaadin.ui

### PR DESCRIPTION
**Pull request by denis-anisimov**
Generator is changed to use new package name and components are regenerated.

Part of #3032.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3160)

### CODE REVIEW

**Comment by ahie** [comment]
Review status: 0 of 69 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-documentation/src/main/java/com/vaadin/flow/tutorial/router/NavigationEvents.java, line 110 at r1](https://reviewable.io:443/reviews/vaadin/flow/3160#-L0LDRE9vR3jTtZz1isq:-L0LDRE9vR3jTtZz1isr:b-wzxfyv) ([raw file](https://github.com/vaadin/flow/blob/fc5fea969ad9ca2655440d1f0cae176156d91869/flow-documentation/src/main/java/com/vaadin/flow/tutorial/router/NavigationEvents.java#L110)):*
> ```Java
> }
> 
> class GeneratedPaperDialog<T> {
> ```

Weird addition. Why not just use the new import?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3160)*

**Comment by ahie** [comment]
Reviewed 122 of 122 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3160)*

**Comment by pleku** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-documentation/src/main/java/com/vaadin/flow/tutorial/router/NavigationEvents.java, line 110 at r1](https://reviewable.io:443/reviews/vaadin/flow/3160#-L0LDRE9vR3jTtZz1isq:-L0LJ64bwFjN5Hk6idML:b-cqgjsp) ([raw file](https://github.com/vaadin/flow/blob/fc5fea969ad9ca2655440d1f0cae176156d91869/flow-documentation/src/main/java/com/vaadin/flow/tutorial/router/NavigationEvents.java#L110)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

Weird addition. Why not just use the new import?
</blockquote></details>

Even weirder I'd say is the fact that we are still using something *generated*  in our documentation. I'd say that is the problem that should be fixed, not necessarily as part of this PR though

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3160)*

**Comment by caalador** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[flow-documentation/src/main/java/com/vaadin/flow/tutorial/router/NavigationEvents.java, line 110 at r1](https://reviewable.io:443/reviews/vaadin/flow/3160#-L0LDRE9vR3jTtZz1isq:-L0N_X1PXFn2rW36a_Ke:boovs4c) ([raw file](https://github.com/vaadin/flow/blob/fc5fea969ad9ca2655440d1f0cae176156d91869/flow-documentation/src/main/java/com/vaadin/flow/tutorial/router/NavigationEvents.java#L110)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Even weirder I'd say is the fact that we are still using something *generated*  in our documentation. I'd say that is the problem that should be fixed, not necessarily as part of this PR though
</blockquote></details>

This is not in actuality used anywhere and it is the ConfirmDialog that should be stubbed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3160)*

**Comment by denis-anisimov** [comment]
Review status: 68 of 69 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-documentation/src/main/java/com/vaadin/flow/tutorial/router/NavigationEvents.java, line 110 at r1](https://reviewable.io:443/reviews/vaadin/flow/3160#-L0LDRE9vR3jTtZz1isq:-L0NqO8b1rqFHBvmc_ZJ:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/fc5fea969ad9ca2655440d1f0cae176156d91869/flow-documentation/src/main/java/com/vaadin/flow/tutorial/router/NavigationEvents.java#L110)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

True
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3160)*

**Comment by caalador** [comment]
Review status: 68 of 69 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-documentation/src/main/java/com/vaadin/flow/tutorial/router/NavigationEvents.java, line 110 at r1](https://reviewable.io:443/reviews/vaadin/flow/3160#-L0LDRE9vR3jTtZz1isq:-L0NqgbJOEKDSwBAimSD:b-bxay4t) ([raw file](https://github.com/vaadin/flow/blob/fc5fea969ad9ca2655440d1f0cae176156d91869/flow-documentation/src/main/java/com/vaadin/flow/tutorial/router/NavigationEvents.java#L110)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Actually it could just not extend anything and `build(String)` could just return `new ConfirmDialog()` then we wouldn't need the `add(Component)` and `show()` could be a `//NO-OP`, but I'm fine with this also.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3160)*

**Comment by ahie** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3160)*

**Pull request merged**
