### PR TITLE
Change setText behavior to always clear the client side first.

### PR DESCRIPTION
**Pull request by gilberto-torrezan**
Add specific tests for the setText feature.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3762)

### CODE REVIEW

**Comment by Legioth** [comment]
*[flow-server/src/main/java/com/vaadin/flow/dom/Element.java, line 980 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3762#-L8Wa_Xp4_2V0w0O-ZMO:-L8Wa_Xp4_2V0w0O-ZMP:b13rx66) ([raw file](https://github.com/vaadin/flow/blob/0a2008a6c669fa2151b1d4ebc0829d067c2ad60b/flow-server/src/main/java/com/vaadin/flow/dom/Element.java#L980)):*
> ```Java
>         } else {
>             boolean hasText = !textContent.isEmpty();
>             if (getChildCount() == 1 && getChild(0).isTextNode() && hasText) {
> ```

Seems like both the `if` and the `else ` parts now effectively do the same thing, except the minor part about reusing a tiny little `Element` instances. Could consider simplifying the code to always use the `else` case? (not blocking)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3762)*

**Comment by gilberto-torrezan** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-server/src/main/java/com/vaadin/flow/dom/Element.java, line 980 at r1](https://reviewable.io:443/reviews/vaadin/flow/3762#-L8Wa_Xp4_2V0w0O-ZMO:-L8WfJ2oPLuqdJaa3ghb:b-kbq3ir) ([raw file](https://github.com/vaadin/flow/blob/0a2008a6c669fa2151b1d4ebc0829d067c2ad60b/flow-server/src/main/java/com/vaadin/flow/dom/Element.java#L980)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

Seems like both the `if` and the `else ` parts now effectively do the same thing, except the minor part about reusing a tiny little `Element` instances. Could consider simplifying the code to always use the `else` case? (not blocking)
</blockquote></details>

This version is slightly better in terms of network traffic (no need to send data about the creating of a new node). It also produces less garbage on the server, but that's usually not a big issue.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3762)*

**Comment by caalador** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[flow-server/src/main/java/com/vaadin/flow/dom/Element.java, line 990 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3762#-L8a3eobDyj9imrg5ivR:-L8a3eobDyj9imrg5ivS:bgp3mh0) ([raw file](https://github.com/vaadin/flow/blob/0a2008a6c669fa2151b1d4ebc0829d067c2ad60b/flow-server/src/main/java/com/vaadin/flow/dom/Element.java#L990)):*
> ```Java
>                     appendChild(createText(textContent));
>                 }
>             }
> ```

I would propose this so it would be clearer what is happening e.g. if no text we remove everything, else we set content where we update or create a textElement then remove all and append child.

```
boolean hasText = !textContent.isEmpty();
if(!hasText) {
  removeAllChildren();
} else {
  setTextContent(textContent);
}
...

private void setTextContent(String textContent) {
  Element child;
  if(getChildCount() == 1 && getChild(0).isTextNode()) {
    child = getChild(0).setText(textContent);
  } else {
    child = createText(textContent));
  }
  removeAllChildren();
  appendChild(child);
}
```

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3762)*

**Comment by caalador** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3762#-:-L8bC0i33pTijpj3YmTM:bnfp4nl)*

**Pull request merged**
