### PR TITLE
fix: Ignore ENOENT in theme-copy.js

### LINKED ISSUE #13885: devserver crash when editing css with emacs
### Description of the bug

Emacs saves a file, devserver notices a temporary file and tries to load it. But then the file is already gone and devserver crashes. No further updates happen before restarting manually.
```
120225 [qtp1625913564-55] DEBUG com.my-themesoftware.rwd.servlets.ContentPreviewImageServlet  - sending fallback image: no previewimage in content 8
122799 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  - node:internal/fs/utils:344
122799 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  -     throw err;
122799 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  -     ^
122799 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  - 
122799 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  - Error: ENOENT: no such file or directory, stat '/home/me/my-project/frontend/themes/my-theme/components/.#vaadin-text-field.css'
122799 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  -     at Object.statSync (node:fs:1538:3)
122799 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  -     at /home/me/my-project/target/plugins/application-theme-plugin/theme-copy.js:75:12
122799 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  -     at Array.forEach (<anonymous>)
122799 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  -     at collectFolders (/home/me/my-project/target/plugins/application-theme-plugin/theme-copy.js:73:32)
122799 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  -     at /home/me/my-project/target/plugins/application-theme-plugin/theme-copy.js:77:22
122799 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  -     at Array.forEach (<anonymous>)
122799 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  -     at collectFolders (/home/me/my-project/target/plugins/application-theme-plugin/theme-copy.js:73:32)
122799 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  -     at copyThemeResources (/home/me/my-project/target/plugins/application-theme-plugin/theme-copy.js:39:22)
122799 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  -     at handleThemes (/home/me/my-project/target/plugins/application-theme-plugin/theme-handle.js:169:5)
122799 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  -     at findThemeFolderAndHandleTheme (/home/me/my-project/target/plugins/application-theme-plugin/theme-handle.js:97:23) {
122799 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  -   errno: -2,
122799 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  -   syscall: 'stat',
122799 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  -   code: 'ENOENT',
122799 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  -   path: '/home/me/my-project/frontend/themes/my-theme/components/.#vaadin-text-field.css'
122799 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  - }

```

### Expected behavior

theme-copy.js should ignore temporary files. Perhaps ignore all file names starting with a dot, or just file names starting with ".#"

### Minimal reproducible example

The problem does not occur every time a css file is saved in emacs. I'm currenctly using a computer with fast cpu, a lot of ram and the project is on a slow spinner drive. The problem occurs about every 5th time a file is saved. It is a plain java Vaadin 23 project.

### Versions

Vaadin
    23.0.10
Flow
    23.0.7
Java
    JetBrains s.r.o. 17
OS
    amd64 Linux 5.16.9

### PR DESCRIPTION
**Pull request by mijutu**
Catch errors in collectFolders and rethrow all except ENOENTs

## Description

Missing files (or perhaps broken symlinks) created by emacs causes devserver crashes. This igrenores ENOENT errors and rethrows the rest.

Fixes #13885

## Type of change

- [X] Bugfix

### CODE REVIEW

**Comment by mcollovati** [comment]
@mijutu thank you for the contribution.
It looks good to me.
I just wonder if we can add a test for the change; I'll try to figure out something.
Meanwhile, may I ask you to sign the CLA? It is mandatory to merge the PR.

**Comment by mijutu** [comment]
> Meanwhile, may I ask you to sign the CLA?

That text is too difficult to understand. => Sorry, not singing.

**Comment by mcollovati** [comment]
> That text is too difficult to understand. => Sorry, not singing.

Ok, no worries. I'll create a new PR and mention you as contributor in the commit message

**Comment by mcollovati** [comment]
Closing in favor of #15896, as the author decided not to sign the CLA

**Pull request closed without merging**
