### PR TITLE
Fix single selection on the same row, item updates

### LINKED ISSUE #2872: Grid selection changes only on every second click
When using the Vaadin Grid with Flow in the single selection mode, the selection changes on every second click:
grid-demo-toggle-selection-issue-2
The screencast is taken from the [GridView](https://github.com/vaadin/flow/blob/master/flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/views/GridView.java) demo at the current master (commit d5d07b6e2d).

Expected: the selection changes on every click.

### LINKED ISSUE #2874: JS error "Attempted to call itemsUpdated with an invalid value" when triggering grid selection
When using `Grid<>.getSelectionModel().select()` the the demo [GridView](https://github.com/vaadin/flow/blob/master/flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/views/GridView.java) at the current master (commit d5d07b6e2d), I get a JS error in the browser: `(String): Attempted to call itemsUpdated with an invalid value`.

grid-demo-toggle-selection-issue

The browser error log:
screen shot 2017-11-08 at 13 47 40

### PR DESCRIPTION
**Pull request by ahie**
Fixes #2874
Fixes #2872

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/2877)

### CODE REVIEW

**Comment by gilberto-torrezan** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-components-parent/demo-flow-components/src/test/java/com/vaadin/flow/demo/views/GridViewIT.java, line 112 at r1](https://reviewable.io:443/reviews/vaadin/flow/2877#-KyQvlRqhCzWMaLW7VbT:-KyQvlRqhCzWMaLW7VbU:b6q425y) ([raw file](https://github.com/vaadin/flow/blob/558b5fc72ef3af9f6f4ce398baaa9afa9516a6c7/flow-components-parent/demo-flow-components/src/test/java/com/vaadin/flow/demo/views/GridViewIT.java#L112)):*
> ```Java
>                 messageDiv.getText());
> 
>         Assert.assertFalse(isElementPresent(By.className("v-system-error")));
> ```

Is this reliable?
(I asked about this on Slack)
If at some point the box message changes the class name, this test will be green even when a message is shown.
But I don't know a better way of doing this (hence the question on Slack)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2877)*

**Comment by gilberto-torrezan** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-components-parent/demo-flow-components/src/test/java/com/vaadin/flow/demo/views/GridViewIT.java, line 112 at r1](https://reviewable.io:443/reviews/vaadin/flow/2877#-KyQvlRqhCzWMaLW7VbT:-KyQx3nOhCtzb7_5uRJT:b-jann19) ([raw file](https://github.com/vaadin/flow/blob/558b5fc72ef3af9f6f4ce398baaa9afa9516a6c7/flow-components-parent/demo-flow-components/src/test/java/com/vaadin/flow/demo/views/GridViewIT.java#L112)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Is this reliable?
(I asked about this on Slack)
If at some point the box message changes the class name, this test will be green even when a message is shown.
But I don't know a better way of doing this (hence the question on Slack)
</blockquote></details>

Kirill answered with a code that inspects the error messages in the client console. That is more reliable, and could be exported as an Util method for other tests that need the same functionality. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2877)*

**Comment by ahie** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[flow-components-parent/demo-flow-components/src/test/java/com/vaadin/flow/demo/views/GridViewIT.java, line 112 at r1](https://reviewable.io:443/reviews/vaadin/flow/2877#-KyQvlRqhCzWMaLW7VbT:-KyUPlvAOjx8JZTzIAUA:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/558b5fc72ef3af9f6f4ce398baaa9afa9516a6c7/flow-components-parent/demo-flow-components/src/test/java/com/vaadin/flow/demo/views/GridViewIT.java#L112)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Kirill answered with a code that inspects the error messages in the client console. That is more reliable, and could be exported as an Util method for other tests that need the same functionality. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2877)*

**Comment by gilberto-torrezan** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2877)*

**Comment by gilberto-torrezan** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[flow-components-parent/demo-flow-components/src/test/java/com/vaadin/flow/demo/views/GridViewIT.java, line 112 at r2](https://reviewable.io:443/reviews/vaadin/flow/2877#-KyUdGuSh7s6kpHoNYwt:-KyUdGuSh7s6kpHoNYwu:bv94isc) ([raw file](https://github.com/vaadin/flow/blob/d1fa1a95d9ffb80476005bd3c92f796027e9b26a/flow-components-parent/demo-flow-components/src/test/java/com/vaadin/flow/demo/views/GridViewIT.java#L112)):*
> ```Java
>                 messageDiv.getText());
> 
>         Assert.assertFalse(getLogErrors().findAny().isPresent());
> ```

The problem in CI might be that the code also gets all warnings,  and you just want errors.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2877)*

**Comment by gilberto-torrezan** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2877)*

**Pull request merged**
