### PR TITLE
Rename package com.vaadin.ui for HTML components

### PR DESCRIPTION
**Pull request by denis-anisimov**
Part of the package rename #3032

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3161)

### CODE REVIEW

**Comment by ahie** [comment]
Reviewed 221 of 221 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-documentation/src/test/java/com/vaadin/flow/tutorial/TestTutorialCodeCoverage.java, line 134 at r1](https://reviewable.io:443/reviews/vaadin/flow/3161#-L0L9ncaNR9rRsJqT7zT:-L0L9ncaNR9rRsJqT7zU:b-j8xlc8) ([raw file](https://github.com/vaadin/flow/blob/79319e8a859b9f52ddc17201c9ab437bd7faebe9/flow-documentation/src/test/java/com/vaadin/flow/tutorial/TestTutorialCodeCoverage.java#L134)):*
> ```Java
>         try {
>             Class<?> clazz = Class.forName(className, false,
>                     getClass().getClassLoader());
> ```

Changes in this file seem unrelated?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3161)*

**Comment by pleku** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-documentation/src/test/java/com/vaadin/flow/tutorial/TestTutorialCodeCoverage.java, line 134 at r1](https://reviewable.io:443/reviews/vaadin/flow/3161#-L0L9ncaNR9rRsJqT7zT:-L0LL1KqPGE3Ul9z01Rf:bb6un1j) ([raw file](https://github.com/vaadin/flow/blob/79319e8a859b9f52ddc17201c9ab437bd7faebe9/flow-documentation/src/test/java/com/vaadin/flow/tutorial/TestTutorialCodeCoverage.java#L134)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

Changes in this file seem unrelated?
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3161)*

**Comment by ahie** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3161)*

**Comment by caalador** [comment]
Compilation fails due to 'CustomerForm' extending `FormLayout`that imports `com.vaadin.ui.html.Label` which has been moved.

So due to the fact that we have the getStarted tutorial we can't update the html package due to using a component that depends on the html package that we would need to update to update the component which we can't update because it needs the html package that........ infinite loop.

---

Review status: 177 of 180 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3161#-:-L0NjbIe73YFRF4cU1BL:bjtrhgt)*

**Comment by denis-anisimov** [comment]
That was the reason of changes in the TestTutorialCoverage

---

Review status: 177 of 180 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[flow-documentation/src/test/java/com/vaadin/flow/tutorial/TestTutorialCodeCoverage.java, line 134 at r1](https://reviewable.io:443/reviews/vaadin/flow/3161#-L0L9ncaNR9rRsJqT7zT:-L0NlOrfwAIRoHNx_x90:b-p79bxg) ([raw file](https://github.com/vaadin/flow/blob/79319e8a859b9f52ddc17201c9ab437bd7faebe9/flow-documentation/src/test/java/com/vaadin/flow/tutorial/TestTutorialCodeCoverage.java#L134)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Very related.
See comments from Mikael.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3161#-:-L0NlKJEVsAEX1DcRXYF:b-3ova3m)*

**Comment by denis-anisimov** [comment]
Review status: 177 of 181 files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-documentation/src/test/java/com/vaadin/flow/tutorial/TestTutorialCodeCoverage.java, line 134 at r4](https://reviewable.io:443/reviews/vaadin/flow/3161#-L0NpjZqoWHQeiLnUKBs:-L0NpjZqoWHQeiLnUKBt:b59g79m) ([raw file](https://github.com/vaadin/flow/blob/b5267c77dd46573d2de3c35b365a8ea475b03088/flow-documentation/src/test/java/com/vaadin/flow/tutorial/TestTutorialCodeCoverage.java#L134)):*
> Class<?> clazz = Class.forName(className, false,
>                     getClass().getClassLoader());

Please keep it as is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3161)*

**Comment by caalador** [comment]
Reviewed 1 of 1 files at r4.
Review status: 178 of 181 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3161)*

**Comment by ahie** [comment]
Reviewed 3 of 3 files at r3, 1 of 1 files at r5, 7 of 7 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3161)*

**Pull request merged**
