### PR TITLE
feat(TypeScript): Export endpoint superclass methods

### LINKED ISSUE #8237: Endpoint superclass methods not exported
Given 
```
@Endpoint
@AnonymousAllowed
public class PersonEndpoint extends CrudEndpoint<Person, Integer> {
}
```
and
```
public abstract class CrudEndpoint<T, ID> {

    @Override
    public Optional<T> get(ID id) {
 ...
   }

    @Override
    public T update(T entity) {
 ...
    }

    @Override
    public void delete(ID id) {
 ...
    }

}
```

I would expect to get an endpoint TS with 3 methods. 

Instead I get
```
2020-05-05 12:55:19.816  INFO 23474 --- [  restartedMain] c.v.f.s.c.g.OpenApiSpecGenerator         : There are no connect endpoints to genertate.
```

Problems:
1. The error message sounds like there are no endpoint classes found when in reality it seems to interpret the class as having no methods.
2. "genertate" should be "generate"

If I override all methods in my endpoint class, I get the expected result

### PR DESCRIPTION
**Pull request by haijian-vaadin**
Fixes #8237

### CODE REVIEW

**Comment by knoobie** [comment]
Could this help you? https://www.javacodegeeks.com/2013/12/advanced-java-generics-retreiving-generic-type-arguments.html

**Comment by Haprog** [comment]
Two tests seem to be failing (maybe just need to update expected output?)

**Comment by platosha** [comment]
Let me rebase on master, which has the `VerifyBrowserVersionIT` fixed.

**Review by haijian-vaadin — COMMENTED** [review]
Looks good to me, and just tested on with a start wizard project, those workarounds there are not needed anymore. Good job!

But I cannot **Approve** the PR, since I created it. You could just Approve and merge it.

**Review by platosha — APPROVED** [review]

**Pull request merged**
