### PR TITLE
 Fix typos (Fixes #3017)

### LINKED ISSUE #3017: Fix typos in Javadoc and code
Fw8 saw a lot of typos fixed in a series of commits. Many of these are present in Flow as well, but instead of porting one by one, it is much more effective to search and replace. The list includes:
* [ ] overriden
* [ ] strean
* [ ] recieved
* [ ] specifiation
* [ ] defautl
* [ ] propertly
* [ ] occurred
* [ ] fucction
* [ ] blured
* [ ] accommodate
* [ ] hoovering
* [ ] succesfull(y)
* [ ] successfull
* [ ] epocHours
* [ ] syntehtic
* [ ] mach
* [ ] breakoint
* [ ] consuption
* [ ] calender
* [ ] assisitve
* [ ] modifie
* [ ] rememeber
* [ ] instnace
* [ ] paramater
* [ ] an layout
* [ ] lookin
* [ ] compability
* [ ] paramter
* [ ] assosiated
* [ ] eg.
* [ ] shorcut
* [ ] negavive
* [ ] disbales
* [ ] iff
* [ ] the the
* [ ] returned and invalid response

### PR DESCRIPTION
**Pull request by asashour**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3067)

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
Reviewed 26 of 26 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-server/src/main/java/com/vaadin/server/BootstrapHandler.java, line 19 at r1](https://reviewable.io:443/reviews/vaadin/flow/3067#-L-14okh6aJ4F_N4X8rg:-L-14okh6aJ4F_N4X8rh:b-g29fx8) ([raw file](https://github.com/vaadin/flow/blob/dde73e8c8b8943a2e7577a2e40859b7467be9e52/flow-server/src/main/java/com/vaadin/server/BootstrapHandler.java#L19)):*
> ```Java
> package com.vaadin.server;
> 
> import static java.nio.charset.StandardCharsets.UTF_8;
> ```

https://github.com/vaadin/flow/issues/1867

This issue denotes that static imports should be below all other imports, have you used some other guide to set up yours?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3067)*

**Comment by asashour** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-server/src/main/java/com/vaadin/server/BootstrapHandler.java, line 19 at r1](https://reviewable.io:443/reviews/vaadin/flow/3067#-L-14okh6aJ4F_N4X8rg:-L-17HBKbuav59YvOs4S:b-bkgio7) ([raw file](https://github.com/vaadin/flow/blob/dde73e8c8b8943a2e7577a2e40859b7467be9e52/flow-server/src/main/java/com/vaadin/server/BootstrapHandler.java#L19)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

https://github.com/vaadin/flow/issues/1867

This issue denotes that static imports should be below all other imports, have you used some other guide to set up yours?
</blockquote></details>

I use the file `flow/eclipse/VaadinJavaConventions.xml`, I will revert this change, and check the .xml file later.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3067)*

**Comment by SomeoneToIgnore** [comment]
*[flow-server/src/main/java/com/vaadin/server/BootstrapHandler.java, line 19 at r1](https://reviewable.io:443/reviews/vaadin/flow/3067#-L-14okh6aJ4F_N4X8rg:-L-17clph57sjcVDPTy3:b-na7uxd) ([raw file](https://github.com/vaadin/flow/blob/dde73e8c8b8943a2e7577a2e40859b7467be9e52/flow-server/src/main/java/com/vaadin/server/BootstrapHandler.java#L19)):*
<details><summary><i>Previously, asashour (Ahmed Ashour) wrote…</i></summary><blockquote>

I use the file `flow/eclipse/VaadinJavaConventions.xml`, I will revert this change, and check the .xml file later.
</blockquote></details>

Maybe it's me being wrong then, don't bother.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3067)*

**Comment by SomeoneToIgnore** [comment]
*[flow-server/src/main/java/com/vaadin/server/BootstrapHandler.java, line 19 at r1](https://reviewable.io:443/reviews/vaadin/flow/3067#-L-14okh6aJ4F_N4X8rg:-L-18oPh_t8gcj33hC03:b-2ljo0k) ([raw file](https://github.com/vaadin/flow/blob/dde73e8c8b8943a2e7577a2e40859b7467be9e52/flow-server/src/main/java/com/vaadin/server/BootstrapHandler.java#L19)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Maybe it's me being wrong then, don't bother.
</blockquote></details>

Ok, looks like I was right after all, but I have no idea how to adjust the `VaadinJavaConventions.xml` to make it proper.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3067)*

**Comment by asashour** [comment]
Review status: 25 of 26 files reviewed at latest revision, all discussions resolved.

---

*[flow-server/src/main/java/com/vaadin/server/BootstrapHandler.java, line 19 at r1](https://reviewable.io:443/reviews/vaadin/flow/3067#-L-14okh6aJ4F_N4X8rg:-L-19zC-ez9KvKL6RNES:bmbds7g) ([raw file](https://github.com/vaadin/flow/blob/dde73e8c8b8943a2e7577a2e40859b7467be9e52/flow-server/src/main/java/com/vaadin/server/BootstrapHandler.java#L19)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Ok, looks like I was right after all, but I have no idea how to adjust the `VaadinJavaConventions.xml` to make it proper.
</blockquote></details>

Done. Thanks for hinting about the mentioned issue, I will investigate.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3067)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-server/src/main/java/com/vaadin/server/BootstrapHandler.java, line 19 at r1](https://reviewable.io:443/reviews/vaadin/flow/3067#-L-14okh6aJ4F_N4X8rg:-L-1AGqdZgZFURcJIi6z:b-rxg2o) ([raw file](https://github.com/vaadin/flow/blob/dde73e8c8b8943a2e7577a2e40859b7467be9e52/flow-server/src/main/java/com/vaadin/server/BootstrapHandler.java#L19)):*
<details><summary><i>Previously, asashour (Ahmed Ashour) wrote…</i></summary><blockquote>

Done. Thanks for hinting about the mentioned issue, I will investigate.
</blockquote></details>

Thanks for the efforts :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3067)*

**Comment by SomeoneToIgnore** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3067#-:-L-1AJN7t5Bn8-ZINmKT:bnfp4nl)*

**Pull request merged**
