### PR TITLE
changed bnd so it can be used by components like grid in an OSGI envi…

### PR DESCRIPTION
**Pull request by Braus**
…ronment.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/7291)

### CODE REVIEW

**Comment by mehdi-vaadin** [comment]
Hi @Braus, thanks for your PR. Could you please explain what problem this change is going to solve? I suppose at the moment that all the Vaadin components can be used in an OSGi environment in Vaadin 13 or Vaadin 14 compatibility mode.

**Comment by Braus** [comment]
Hi @mehdi-vaadin,

Thanks for looking into this. I'll display the issue in the image down below. So the problem is that multiple Components request for a class in the internal package. However in OSGI the Internal package can be compared to java's **private** modifier. If it is private it can only be used by that bundle. And that's what the DnD is a bundle. Other bundles (grid, gridpro) can only access the public part of the bundle in OSGI. Unfortunately these components refer to a private/internal class so they are unable to load because they are unable to access that class.

I actually feel that the best way to solve this issue is by moving the referenced class out of the internal class completely instead of making the internal package accessiblelike this commit is doing.

I'm currently running my application in compatibility mode but this issue is not related to that.

image

**Comment by Braus** [comment]
I just build them the way I commited it and the way you requested it and there is no difference in the result. it is both:
Export-Package: com.vaadin.flow.component.dnd.internal;uses:="com.vaad
 in.flow.component";version="2.2.0"

**Comment by mehdi-vaadin** [comment]
@Braus thanks again for the fix :)

**Comment by mehdi-vaadin** [comment]
We decided not to add the `internal` package to `export-package` and fix this issue in a better way in `Grid`. So, I'll revert this commit. @Braus thanks anyway for bringing this up 👍🏼.

**Comment by Braus** [comment]
@mehdi-vaadin Very happy to hear that I could make a contribution somehow :)

**Pull request merged**
