### PR TITLE
Support client-originated integers in models

### LINKED ISSUE #4126: Exception when trying to update an int value from the client to the model in Java
If a property is defined as Number in client template (.html) and it tries to update its conterpart field in the Java Model that is also declared as a supported type, as an int, I get this exception:

```
Caused by: java.lang.IllegalArgumentException: The stored model value '1' type 'java.lang.String' cannot be used as a type for a model property with type 'int'
	at com.vaadin.flow.templatemodel.BasicModelType.modelToApplication(BasicModelType.java:64)
```

Source code used to reproduce the error:

```
<dom-module id="x-inter">
	<template>
		<input type="radio" name="toggle" id="id1" value= 1  on-change="_getSelected">One
		<input type="radio" name="toggle" id="id2" value= 2  on-change="_getSelected">Two
	</template>
	<script>
		class XInter extends Polymer.Element{
			static get is(){
				return "x-inter";
			}
			static get properties(){
				return {
					selectedIndex: {
						type: Number,
						reflectToAttribute: true,
						notify: true
					}
				};	
			}
			_getSelected(){
				if(this.shadowRoot.querySelector('input[name=toggle]:checked')){
					this.selectedIndex = this.shadowRoot.querySelector('input[name=toggle]:checked').value;
				}
				else
					this.selectedIndex = -1;
				this.dispatchEvent(new CustomEvent('change', {}));
			}
		}
		customElements.define(XInter.is, XInter);
	</script>
</dom-module>
```

```
<dom-module id="x-element">
	<template>
		<x-inter selected-index= {{selectedValue}} on-change="_valueChanged"></x-inter>
	</template>
	<script>
		class XElement extends Polymer.Element{
			static get is(){
				return "x-element";
			}
			static get properties(){
				return {
					selectedValue:{
						type: Number,
						notify: true
					}	
				};
			}
		}
		customElements.define(XElement.is, XElement);
	</script>
</dom-module>
```

```
@Tag("x-element")
@HtmlImport("x-element.html")
public class XElement extends PolymerTemplate<Model> {

  public XElement() {
    this.getElement().synchronizeProperty("selectedValue", "_valueChanged");
    this.getElement().addPropertyChangeListener("selectedValue", e -> {
      System.out.println(getModel().getSelectedValue());
    });
  }

  public interface Model extends TemplateModel {
    int getSelectedValue();
    void setSelectedValue(int value);
  }
}
```

### PR DESCRIPTION
**Pull request by Legioth**
Fixes #4126

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/4137)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[flow-server/src/main/java/com/vaadin/flow/templatemodel/BasicModelType.java, line 66 at r1](https://reviewable.io/reviews/vaadin/flow/4137#-LD-wr855kVspMYzIt9i:-LD-wr855kVspMYzIt9j:b-lucdxh) ([raw file](https://github.com/vaadin/flow/blob/43f2c9ae68dd32d9cb74b2ec1ea0eb08ffc7a01f/flow-server/src/main/java/com/vaadin/flow/templatemodel/BasicModelType.java#L66)):*
> ```
> (Number) modelValue
> ```

So is it a `Number`  or a `Double`?
Check is done against the `Double`. The cast is to `Number`. 
Has sense to unify.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4137)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow/4137#-LD-xUDv5rHr7NsEJMaV:-LD-xUDv5rHr7NsEJMaW:bex08j4) (no related file):*
May be `BasicComplexModelType` also needs similar correction ?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4137)*

**Comment by Legioth** [comment]
Review status: 1 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow/4137#-LD-xUDv5rHr7NsEJMaV:-LD0b7YO6rtTVtk7fT0N:bb6un1j) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

May be `BasicComplexModelType` also needs similar correction ?
</blockquote></details>

Done

---

*[flow-server/src/main/java/com/vaadin/flow/templatemodel/BasicModelType.java, line 66 at r1](https://reviewable.io/reviews/vaadin/flow/4137#-LD-wr855kVspMYzIt9i:-LD0b8u94ivDRokguCji:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/43f2c9ae68dd32d9cb74b2ec1ea0eb08ffc7a01f/flow-server/src/main/java/com/vaadin/flow/templatemodel/BasicModelType.java#L66)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
> (Number) modelValue
> ```

So is it a `Number`  or a `Double`?
Check is done against the `Double`. The cast is to `Number`. 
Has sense to unify.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4137)*

**Comment by denis-anisimov** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4137#-:-LD0e2_8CkC_p7ywNhj5:bnfp4nl)*

**Pull request merged**
