### PR TITLE
Fix websockets issue and enable test-spring-war module

### PR DESCRIPTION
**Pull request by Artur-**
This reverts commit c69acafd395705f1c2924d7c01ab472c01e80a8f.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3832)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[flow-spring-addon/src/main/java/com/vaadin/flow/spring/VaadinWebsocketEndpointExporter.java, line 55 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3832#-L9OcUOCCKNElGKYnDUh:-L9OcUOCCKNElGKYnDUi:bdkfb5d) ([raw file](https://github.com/vaadin/flow/blob/fa47cd853b390e8e6edbb7f409881b388e867632/flow-spring-addon/src/main/java/com/vaadin/flow/spring/VaadinWebsocketEndpointExporter.java#L55)):*
> ```
> public void afterPropertiesSet() {
> ```

If the issue is fixed then this should be removed.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3832#-:-L9Od0tHCTuhzP9OJHGB:bnfp4nl)*

**Comment by denis-anisimov** [comment]
:lgtm_cancel: 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3832#-:-L9Od4bOBuGnzEiSV84n:b8b79qu)*

**Comment by Artur-** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[flow-spring-addon/src/main/java/com/vaadin/flow/spring/VaadinWebsocketEndpointExporter.java, line 55 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3832#-L9OcUOCCKNElGKYnDUh:-L9Okwn95fKOR9wkpdJ0:b94pywy) ([raw file](https://github.com/vaadin/flow/blob/fa47cd853b390e8e6edbb7f409881b388e867632/flow-spring-addon/src/main/java/com/vaadin/flow/spring/VaadinWebsocketEndpointExporter.java#L55)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
> public void afterPropertiesSet() {
> ```

If the issue is fixed then this should be removed.
</blockquote></details>

This is still needed, the Spring issue is not fixed

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3832)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[flow-spring-addon/src/main/java/com/vaadin/flow/spring/VaadinWebsocketEndpointExporter.java, line 55 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3832#-L9OcUOCCKNElGKYnDUh:-L9OmRwNCnl3mjPYwyiN:b-2dkym2) ([raw file](https://github.com/vaadin/flow/blob/fa47cd853b390e8e6edbb7f409881b388e867632/flow-spring-addon/src/main/java/com/vaadin/flow/spring/VaadinWebsocketEndpointExporter.java#L55)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

This is still needed, the Spring issue is not fixed
</blockquote></details>

But if it's not fixed then `test-spring-war` will fail again.
It looks like `afterPropertiesSet` is called directly on `ServerEndpointExporter` instance not on the `VaadinWebsocketEndpointExporter` instance for some reason.
At least that was the reason why I disabled `test-spring-war` module.
Does this PR changes that ?
Only this line does the fix?
`getServerContainer() == null` 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3832)*

**Comment by denis-anisimov** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3832#-:-L9OqPpf8nAwY6DtIhPi:bnfp4nl)*

**Comment by denis-anisimov** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3832#-:-L9P9d9_BqDgNx-_JXh6:bnfp4nl)*

**Pull request merged**
