### PR TITLE
Take DataView concept into use #141

### PR DESCRIPTION
**Pull request by mshabarov**
See [dataview implementation](https://github.com/vaadin/vaadin-checkbox-flow/tree/dataview-141) in vaadin-checkbox-flow project

This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/8303)

### CODE REVIEW

**Comment by mshabarov** [comment]
*[a discussion](https://reviewable.io/reviews/vaadin/flow/8303#-M76cTgN8Z210tzvkTOA:-M76oc1AAc6m4Ga1Oi8r:b-q7lcsz) (no related file):*
> vaadin/vaadin-checkbox-flow@feature/dataprovider...dataview-141
Yes, my bad. Here is the PR https://github.com/vaadin/vaadin-checkbox-flow/pull/143

---

**Comment by mshabarov** [comment]
___
*[flow-data/src/main/java/com/vaadin/flow/data/provider/ListDataView.java, line 28 at r1](https://reviewable.io/reviews/vaadin/flow/8303#-M76bltF9evojtpDmR-U:-M76pUDP0wvHbse_OZZB:b-cq6i8s) ([raw file](https://github.com/vaadin/flow/blob/0819caa89ad50177faab1e3d0315015ca46c4e03/flow-data/src/main/java/com/vaadin/flow/data/provider/ListDataView.java#L28)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
> public interface ListDataView<T, V extends ListDataView<T, ?>> extends DataView<T> {
> ```

If we will take this route for fluent API I think then we should probably introduce the return type to the type for the lazy type too. (cc: @caalador )
As discussed, it makes no sense for the size/undefinedsize API as those are terminal operations but when we add filtering/sorting API, then it might make more sense ?
</blockquote></details>

Yes, fluent API makes sense for the filtering/sorting methods to be considered in further tickets.

**Comment by mshabarov** [comment]
___
*[flow-data/src/main/java/com/vaadin/flow/data/provider/ListDataView.java, line 90 at r1](https://reviewable.io/reviews/vaadin/flow/8303#-M76ZZoHCLq-MzwsssKt:-M76rI-n0oYP2pL6_CSK:b-wg7pk9) ([raw file](https://github.com/vaadin/flow/blob/0819caa89ad50177faab1e3d0315015ca46c4e03/flow-data/src/main/java/com/vaadin/flow/data/provider/ListDataView.java#L90)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

I agree that instead of a TODO a ticket(s) should be made.
</blockquote></details>

Totally agree.  Will create a ticket.

**Comment by mshabarov** [comment]
___
*[vaadin-checkbox-flow, line 1 at r1](https://reviewable.io/reviews/vaadin/flow/8303#-M76aGCf4iMHoW_8ttPH:-M76sxOx9voMVxur4DZ7:b37ztdm) ([raw file](https://github.com/vaadin/flow/blob/0819caa89ad50177faab1e3d0315015ca46c4e03/vaadin-checkbox-flow#L1)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Hmm, not sure WDYM. Unless the component integrations use the feature snapshot, those will never be merged due to compilation failure.
I was referring to the checkboxgroup changes that don't compile because ...

Right.
</blockquote></details>

Yes, my bad again. I miss the 3.2.dataprovider-SNAPSHOT version.

**Comment by mshabarov** [comment]
https://github.com/vaadin/flow/issues/8313 has been created

**Comment by mshabarov** [comment]
___
*[vaadin-checkbox-flow, line 1 at r1](https://reviewable.io/reviews/vaadin/flow/8303#-M76aGCf4iMHoW_8ttPH:-M77IsfT1MY7S3ODMlvz:b-hw95kl) ([raw file](https://github.com/vaadin/flow/blob/0819caa89ad50177faab1e3d0315015ca46c4e03/vaadin-checkbox-flow#L1)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

@mshabarov you've misunderstood - I don't think you should change the version for Flow or this PR, I just pointed out that the CBG has the wrong version as it cannot rely on `3.2-SNAPSHOT` until we've merged things to master. So basically locally we have to build using flow `3.2-SNAPSHOT` but to merge things for the components, we need to use the feature snapshot version. Like Mikael said, for Flow the version is set by bender in the snapshot build. So this PR should not change the version, but the component PR should.
</blockquote></details>

Ok, so I revert Flow version from 3.2.dataprovider-SNAPSHOT to 3.2.-SNAPSHOT, and change flow.version in CFG to 3.2.dataprovider-SNAPSHOT, right?

**Comment by caalador** [comment]
Will you bring in the abstract data view parts into this PR?

**Comment by mshabarov** [comment]
> Will you bring in the abstract data view parts into this PR?

Yes

**Comment by mshabarov** [comment]
___
*[flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractDataView.java, line 40 at r3](https://reviewable.io/reviews/vaadin/flow/8303#-M7Goi1OCjNXMBVXjJqv:-M7J_Lur0qtrr-jG9D_v:b-6hdr5h) ([raw file](https://github.com/vaadin/flow/blob/37a7f4eaba3a267a5038ea3040b094367709c317/flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractDataView.java#L40)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
> Set<SizeChangeListener>
> ```
I would instead go with `List`, `ArrayList` in this case since we want to notify the listeners in the same order as they have been added.
When you create the list set its size to be `(1)`
</blockquote></details>

Good point! I created a new ticket for listeners handling since we decided to move it on the DC/component side.

**Comment by mshabarov** [comment]
___
*[flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractDataView.java, line 56 at r3](https://reviewable.io/reviews/vaadin/flow/8303#-M7GpVS58Fe2alIRPDEp:-M7Ja7Gv8hhT4Q_IKqBo:bkenidf) ([raw file](https://github.com/vaadin/flow/blob/37a7f4eaba3a267a5038ea3040b094367709c317/flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractDataView.java#L56)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
>     @Override
>     public void sizeEvent(int size) {
> ```
My opinion is that the size event firing should be just delegated to the `DataCommunicator` and we should not really have any state in the data views, other than the link to the `DataCommunicator`. So basically the `AbstractDataView` constructor takes in a `DataCommunicator` and delegates there. For components that don't currently use `DataCommunictor` it is tricky - I think the solution could be to have an interface for the dataview-datacommunicator interaction and have a stub implementation in components (as inner class, not exposing the API as public) that 

It is another question that should the size change listeners be still invoked if the DataCommunicator gets new type of dataprovider or should those be cleared ? I think it is fine to keep them and fire the events since the size change listener. 
</blockquote></details>

I agree. The ticket about event handling and new abstract layer have been created. I wouldn't mix them here, in this PR to avoid mess.

**Comment by mshabarov** [comment]
___
*[flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractDataView.java, line 59 at r3](https://reviewable.io/reviews/vaadin/flow/8303#-M7Gp9CAEgFKXOxUKyGq:-M7JaOYA2K-7nM66vQ2C:b-8n327p) ([raw file](https://github.com/vaadin/flow/blob/37a7f4eaba3a267a5038ea3040b094367709c317/flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractDataView.java#L59)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
> new SizeChangeEvent<>(component, size))
> ```
You should create the event once and fire the same event to all listeners. It is immutable 
</blockquote></details>

Yes, good point.

**Comment by mshabarov** [comment]
___
*[flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractListDataView.java, line 41 at r3](https://reviewable.io/reviews/vaadin/flow/8303#-M7HGGyF63ZF9-117lmc:-M7Ja_9IAb11gwI_jjkH:bb6un1j) ([raw file](https://github.com/vaadin/flow/blob/37a7f4eaba3a267a5038ea3040b094367709c317/flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractListDataView.java#L41)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

As discussed - should be `DataCommunicator` or an interface instead. It seems to me that the only thing that the `AbstractListDataProvider` needs itself is something that provides the `InMemoryDataProvider´ / `ListDataProvider` 

Then the `ListDataProvider` should be always fetched from there whenever needed, and an error should be thrown when the data provider has changed
</blockquote></details>

Done

**Comment by mshabarov** [comment]
___
*[flow-data/src/main/java/com/vaadin/flow/data/provider/DataView.java, line 35 at r4](https://reviewable.io/reviews/vaadin/flow/8303#-M7HqtXoDtfY5jxkJVZv:-M7JacWG5ZDUcDwVKdO2:b-iwnv67) ([raw file](https://github.com/vaadin/flow/blob/e0d82babd11f56a54fffc3391d16c007be7e1b1b/flow-data/src/main/java/com/vaadin/flow/data/provider/DataView.java#L35)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

> ```
>,  F
> ```
Do we need the filter type for anything?
</blockquote></details>

Not really. Removed

**Comment by mshabarov** [comment]
___
*[flow-data/src/main/java/com/vaadin/flow/data/provider/DataView.java, line 38 at r3](https://reviewable.io/reviews/vaadin/flow/8303#-M7GwERf6GGR00Whbebs:-M7JancK7PTO-FAK5_-8:b-4rlgea) ([raw file](https://github.com/vaadin/flow/blob/37a7f4eaba3a267a5038ea3040b094367709c317/flow-data/src/main/java/com/vaadin/flow/data/provider/DataView.java#L38)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

> ```
> sorting.
> ```
Should use sorting. Else the result will be strange.
Also getting the items without any component filter or sort is not that interesting.
</blockquote></details>

Yes, this was weird. Done

**Comment by mshabarov** [comment]
___
*[flow-data/src/main/java/com/vaadin/flow/data/provider/DataView.java, line 53 at r3](https://reviewable.io/reviews/vaadin/flow/8303#-M7H60s53OA8fbAPIfxt:-M7Jawwg-WnrEWh_UnAQ:bb6un1j) ([raw file](https://github.com/vaadin/flow/blob/37a7f4eaba3a267a5038ea3040b094367709c317/flow-data/src/main/java/com/vaadin/flow/data/provider/DataView.java#L53)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

The developer shouldn't have to know queries
</blockquote></details>

Done

**Comment by mshabarov** [comment]
___
*[flow-data/src/main/java/com/vaadin/flow/data/provider/DataView.java, line 53 at r3](https://reviewable.io/reviews/vaadin/flow/8303#-M7H61lwD8WXgdNBzLDx:-M7Jazx25_dXYnZ2-R7j:bb6un1j) ([raw file](https://github.com/vaadin/flow/blob/37a7f4eaba3a267a5038ea3040b094367709c317/flow-data/src/main/java/com/vaadin/flow/data/provider/DataView.java#L53)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

DataView should handle queries in the implementation as needed and shouldn't be shown as API.
</blockquote></details>

Done

**Comment by mshabarov** [comment]
___
*[flow-data/src/main/java/com/vaadin/flow/data/provider/DataView.java, line 90 at r3](https://reviewable.io/reviews/vaadin/flow/8303#-M7GuwVd8PmkhNrIEQdX:-M7Jb20yDi3rW3Neq6Hz:b-egp725) ([raw file](https://github.com/vaadin/flow/blob/37a7f4eaba3a267a5038ea3040b094367709c317/flow-data/src/main/java/com/vaadin/flow/data/provider/DataView.java#L90)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Let's remove this method all together from the interface and have it only in component specific interfaces to get a method name that makes sense for the component.
</blockquote></details>

Yes, i moved it to component specific class. Lets see if it appropriate.

**Comment by mshabarov** [comment]
___
*[flow-data/src/main/java/com/vaadin/flow/data/provider/SizeChangeAwareListDataProvider.java, line 32 at r4](https://reviewable.io/reviews/vaadin/flow/8303#-M7GsbFx7s4m_B6ci081:-M7JbGhs1zQeQCGRB07w:bss4a2b) ([raw file](https://github.com/vaadin/flow/blob/e0d82babd11f56a54fffc3391d16c007be7e1b1b/flow-data/src/main/java/com/vaadin/flow/data/provider/SizeChangeAwareListDataProvider.java#L32)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
> public class SizeChangeAwareListDataProvider<T> extends ListDataProvider<T> implements SizeChangeAware {
>
>    ...
>
>  @Override
    public int size(Query<T, SerializablePredicate<T>> query) {
        int size = super.size(query);
        sizeChangeHandler.sizeEvent(size);
        return size;
    }

> ```
I'm not sure if this is the way to go, to add things to the data provider. I think it would make more sense to have these in the data communicator size.

At least for the lazy case it cannot work like this - the size query might not be executed at all from the data provider if there is a switch from defined to undefined size. And could lead into application bugs if the event is not fired accordingly.

So I think it cannot work like this even for the list case.
</blockquote></details>

Removed.

**Comment by mshabarov** [comment]
___
*[flow-data/src/main/java/com/vaadin/flow/data/provider/ListDataView.java, line 34 at r3](https://reviewable.io/reviews/vaadin/flow/8303#-M7Gvnnf-BfmU4K_8RpV:-M7JbePCEsm7l0iQf8gE:b-iisbv3) ([raw file](https://github.com/vaadin/flow/blob/37a7f4eaba3a267a5038ea3040b094367709c317/flow-data/src/main/java/com/vaadin/flow/data/provider/ListDataView.java#L34)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
>  SerializablePredicate<T>> {
> ```
wat ? why ?
</blockquote></details>

I introduced a generic filter type and made it specific for list data view. But apparently it is just some over-complication and is a mistake basically.

**Comment by mshabarov** [comment]
___
*[flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractListDataView.java, line 99 at r5](https://reviewable.io/reviews/vaadin/flow/8303#-M7MEEoP3rlm0u_SiU_C:-M7MIS4H4kNdxUvW0ZXQ:bvz6lib) ([raw file](https://github.com/vaadin/flow/blob/c6fb8c111931a29dff5a35cc98e92c3dfd2b7b35/flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractListDataView.java#L99)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
>             throw new IllegalStateException(
>                     String.format("ListDataView is incompatible with %s instance",
>                             dataProvider.getClass().getCanonicalName()));
> ```
For a user that accidentally uses a stale/invalid data view this error message doesn't really help as it doesn't say what they did wrong, please fix
</blockquote></details>

Ok, I would reuse @caalador approach with providers and dataview types as a parameters and improve the error message.

**Comment by mshabarov** [comment]
___
*[flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractListDataView.java, line 100 at r5](https://reviewable.io/reviews/vaadin/flow/8303#-M7MDpNr8L9K_bECpQxs:-M7MIxiN-tVX7kL-GLlU:b81rc3e) ([raw file](https://github.com/vaadin/flow/blob/c6fb8c111931a29dff5a35cc98e92c3dfd2b7b35/flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractListDataView.java#L100)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
>     protected void validateDataProvider(final DataProvider<T, ?> dataProvider) {
>         Objects.requireNonNull(dataProvider, "DataProvider cannot be null");
>         if (!(dataProvider instanceof ListDataProvider)) {
>             throw new IllegalStateException(
>                     String.format("ListDataView is incompatible with %s instance",
>                             dataProvider.getClass().getCanonicalName()));
>         }
> ```
Non-blocking: Another approach could be to have the checker in in the super class and have the child just implement a method that returns the required class type of the data provider, but this is probably OK for now even though there is some code duplication. It can be fixed later on.
</blockquote></details>

Alright, will try that

**Comment by mshabarov** [comment]
___
*[flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractListDataView.java, line 91 at r5](https://reviewable.io/reviews/vaadin/flow/8303#-M7MDNYZAozTcmiqdPiB:-M7MJ2YB3htoDTjt342D:bczkyti) ([raw file](https://github.com/vaadin/flow/blob/c6fb8c111931a29dff5a35cc98e92c3dfd2b7b35/flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractListDataView.java#L91)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Non-blocking: I think this might be forced to be delegated to the data communicator too, since the equality could be determined by the provided _identity_ checker (the default is equals). 

But we can leave that for later.
</blockquote></details>

Ok, I propose to do it later on when CBG, Grid and Select will be merged.

**Comment by mshabarov** [comment]
___
*[flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractDataView.java, line 70 at r8](https://reviewable.io/reviews/vaadin/flow/8303#-M7N8mwZ5Kt53PElC6Go:-M7NDiKU-cYe7SVWtHvV:b-4mv19i) ([raw file](https://github.com/vaadin/flow/blob/cfc1c28f70e456414ea3d2268a99d3921a16aef8/flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractDataView.java#L70)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
>     /**
>      * Returns a base {@link DataView} class type for this data view.
>      *
>      * @return base data view type
>      */
>     protected abstract Class<?> getDataViewType();
> ```
I don't think this is needed at all since `this.getClass()` will return the actual type and thus `getSimpleName()` will return the correct name.
</blockquote></details>

Yes, I chosen abstract method so as to restrict class name to high level interface (LazyDataView or ListDataView) to not bother the user with impl subclasses, but anyway the user would have a subclass returned from setDataProvider method, so getClass would be fine. Will change that.

**Comment by mshabarov** [comment]
___
*[flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractDataView.java, line 90 at r8](https://reviewable.io/reviews/vaadin/flow/8303#-M7NA0av2gsmgcYTVR7y:-M7NFAjn8mJNap7ky_Ce:bqog80t) ([raw file](https://github.com/vaadin/flow/blob/cfc1c28f70e456414ea3d2268a99d3921a16aef8/flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractDataView.java#L90)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

I think the error type should be `IllegalStateException` in case the type is validated when the use calls `component.getSomeDataView()`method.
Semantically looking from the constructor it the argument might be wrong but I think it is still more wrong state as the user cannot change the argument
</blockquote></details>

Agreed

**Comment by mshabarov** [comment]
___
*[flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractListDataView.java, line 91 at r5](https://reviewable.io/reviews/vaadin/flow/8303#-M7MDNYZAozTcmiqdPiB:-M7NG4a74dK1LtTCXsp4:b-x3qgqt) ([raw file](https://github.com/vaadin/flow/blob/c6fb8c111931a29dff5a35cc98e92c3dfd2b7b35/flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractListDataView.java#L91)):*
> delegated to the data communicator too, since the equality could be determined by the provided identity checker (the default is equals).
Done

**Pull request merged**
