### PR TITLE
Configure to run IE11 tests in production mode

### PR DESCRIPTION
**Pull request by pekam**
- Trigger production mode and exclude `IgnoreIE11` tests when running in BrowserStack
- Fix es5 frontend path by removing the configuration that sets it the same as for es6
- Move tests and required resources that depend on the above config from `test-root-context` to `test-dev-mode`
- plus a couple of minor test improvements

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/4306)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 1 of 20 files at r1.
Review status: 1 unresolved discussion, 0 of 1 LGTMs obtained

---

*[flow-tests/test-dev-mode/src/main/webapp/frontend/com/vaadin/flow/uitest/vaadin-flow-bundle.html, line 1 at r1](https://reviewable.io/reviews/vaadin/flow/4306#-LFN4Ltt0bSlEiRmipMp:-LFN4Ltt0bSlEiRmipMq:b-6xvzxt) ([raw file](https://github.com/vaadin/flow/blob/4da67e81ee3f41e54a018df3a8ba4970d2592e63/flow-tests/test-dev-mode/src/main/webapp/frontend/com/vaadin/flow/uitest/vaadin-flow-bundle.html#L1)):*
> ```
> 
> ```

This and the change below will have an effect on Tomcat tests which are executed nightly so failures won't be detected during the validation.
Please make sure that Tomcat tests are working with those changes.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4306)*

**Comment by pekam** [comment]
Review status: 1 unresolved discussion, 0 of 1 LGTMs obtained

---

*[flow-tests/test-dev-mode/src/main/webapp/frontend/com/vaadin/flow/uitest/vaadin-flow-bundle.html, line 1 at r1](https://reviewable.io/reviews/vaadin/flow/4306#-LFN4Ltt0bSlEiRmipMp:-LFNAL0gAC4JdZ7VexLa:b-u5xgec) ([raw file](https://github.com/vaadin/flow/blob/4da67e81ee3f41e54a018df3a8ba4970d2592e63/flow-tests/test-dev-mode/src/main/webapp/frontend/com/vaadin/flow/uitest/vaadin-flow-bundle.html#L1)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
> 
> ```

This and the change below will have an effect on Tomcat tests which are executed nightly so failures won't be detected during the validation.
Please make sure that Tomcat tests are working with those changes.
</blockquote></details>

I ran `mvn clean install -Ptomcat` in `servlet-containers` and got two errors for Tomcat 9:
```
[ERROR]   RequestParametersHistoryIT>ChromeBrowserTest.setup:62->ChromeBrowserTest.createHeadlessChromeDriver:76 ▒ SessionNotCreated
[ERROR]   RequestParametersHistoryIT>ChromeBrowserTest.setup:62->ChromeBrowserTest.createHeadlessChromeDriver:76 ▒ SessionNotCreated
```
Seems un-related to this, but  I'll run it again.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4306)*

**Comment by pekam** [comment]
Review status: 1 unresolved discussion, 0 of 1 LGTMs obtained

---

*[flow-tests/test-dev-mode/src/main/webapp/frontend/com/vaadin/flow/uitest/vaadin-flow-bundle.html, line 1 at r1](https://reviewable.io/reviews/vaadin/flow/4306#-LFN4Ltt0bSlEiRmipMp:-LFNC4Zp6AckG922ETlM:bihs6p7) ([raw file](https://github.com/vaadin/flow/blob/4da67e81ee3f41e54a018df3a8ba4970d2592e63/flow-tests/test-dev-mode/src/main/webapp/frontend/com/vaadin/flow/uitest/vaadin-flow-bundle.html#L1)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

I ran `mvn clean install -Ptomcat` in `servlet-containers` and got two errors for Tomcat 9:
```
[ERROR]   RequestParametersHistoryIT>ChromeBrowserTest.setup:62->ChromeBrowserTest.createHeadlessChromeDriver:76 ▒ SessionNotCreated
[ERROR]   RequestParametersHistoryIT>ChromeBrowserTest.setup:62->ChromeBrowserTest.createHeadlessChromeDriver:76 ▒ SessionNotCreated
```
Seems un-related to this, but  I'll run it again.
</blockquote></details>

On the second try all the tests passed.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4306)*

**Comment by denis-anisimov** [comment]
Reviewed 19 of 20 files at r1.
Review status: 2 unresolved discussions, 0 of 1 LGTMs obtained

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow/4306#-LFQrSI6DDHxhGhqj8pP:-LFQrSI6DDHxhGhqj8pQ:b-uk55d8) (no related file):*
There are a number of UI classes that have been moved out of the `root-context` module.
I would like to understand reasons for each of them.
Is it so that they can't be used in production at all even with modifications?
At the first glance I don't see any reasons why they are incompatible with the production mode.

Or they have tests that are executed in production mode which is not a production mode?
There are some tests like that.

BUT.
It's about tests, not about UIs.
There are tests that uses the same UI but they are executed without any production mode. And the same IT test class has tests in production mode.
So instead of moving the UI classes out of the `root-context` module into `dev-mode`  module they should be moved into `common`  module and IT test classes splitted so that the part which doesn't relate to production mode stays in the `root-context` module and the part which is about semi-production mode goes to the `dev-mode`.

---

*[flow-tests/test-root-context/pom.xml, line 83 at r1](https://reviewable.io/reviews/vaadin/flow/4306#-LFQtfAHBJ6L3NTfgynf:-LFQtfAHBJ6L3NTfgyng:b-1n6e5e) ([raw file](https://github.com/vaadin/flow/blob/cad6d39b1764ae18418984d049e2d1ee9689b063/flow-tests/test-root-context/pom.xml#L83)):*
> ```
> <name>vaadin.frontend.url.es5</name>
> ```
This is not needed because you have moved everything into `frontend`  folder in other module.
But may be this has been done intentionally? (I don't know).

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4306)*

**Comment by pekam** [comment]
Review status: 2 unresolved discussions, 0 of 1 LGTMs obtained

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow/4306#-LFQrSI6DDHxhGhqj8pP:-LFREO664d1cI0A4gGhE:b-r35602) (no related file):*
The tests that are moved use the `openProduction()` and/or `openForEs6Url()` which don't work with the production mode.

> Or they have tests that are executed in production mode which is not a production mode?

Yes.

> There are tests that uses the same UI but they are executed without any production mode. And the same IT test class has tests in production mode.

I don't follow. You mean that same view is used in both `test-dev-mode` and `test-root-context`? Where are tests like this?

---

*[flow-tests/test-root-context/pom.xml, line 83 at r1](https://reviewable.io/reviews/vaadin/flow/4306#-LFQtfAHBJ6L3NTfgynf:-LFRGaF0EKZ_LBUL7tCe:blo09kp) ([raw file](https://github.com/vaadin/flow/blob/cad6d39b1764ae18418984d049e2d1ee9689b063/flow-tests/test-root-context/pom.xml#L83)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
> <name>vaadin.frontend.url.es5</name>
> ```
This is not needed because you have moved everything into `frontend`  folder in other module.
But may be this has been done intentionally? (I don't know).
</blockquote></details>

Previously, when there was no "true" production mode, this config was used to serve the same static resources for es5 that we have for es6. Otherwise it would have tried to look for non-existing transpiled resources in some es5 folder.

Now with transpilation enabled, if we want the transpiled resources to be served to IE11, we need to use the default directory for es5 which contains the transpiled resources.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4306)*

**Comment by denis-anisimov** [comment]
Review status: 2 unresolved discussions, 0 of 1 LGTMs obtained

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow/4306#-LFQrSI6DDHxhGhqj8pP:-LFRPB1X4UfxcLWak804:br1elej) (no related file):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

The tests that are moved use the `openProduction()` and/or `openForEs6Url()` which don't work with the production mode.

> Or they have tests that are executed in production mode which is not a production mode?

Yes.

> There are tests that uses the same UI but they are executed without any production mode. And the same IT test class has tests in production mode.

I don't follow. You mean that same view is used in both `test-dev-mode` and `test-root-context`? Where are tests like this?
</blockquote></details>

I've seen such tests. 
All the tests should be checked for this.
Let me find at least one....


`ExportedJSFunctionIT`.
It has methods:
- `versionInfoAvailableInDevelopmentMopde` (name could be corrected by the way)
- `versionInfoNotAvailableInProductionMode` 

The first test uses `open()` which means that it doesn't require anything special to work.
It's not a dev mode actually it's rather a regular run. It will become a production mode run being running in production mode. So the name is bad (and it has extra `p`).
This method ( I expect this) should work in production mode as well.

The second method uses `openProduction()`  . This "open" method changes the URL of the opened UI so that another servlet is used to run the UI for the test and this servlet has production mode enabled.
This is semi-producton mode. Which should not be used with production.

Or may be the first test relies on the production mode and cannot be run in production mode at all.
But the second test should work as is in production mode as well.

It needs to be checked. I'm not sure.
Are all the tests in `ExportedJSFunctionIT` failing in production mode?
If so then it should be completely moved into `dev-mode`.
If only some tests are failing then those tests should be extracted.

And the same for every other test.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4306)*

**Comment by denis-anisimov** [comment]
Review status: 2 unresolved discussions, 0 of 1 LGTMs obtained

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow/4306#-LFQrSI6DDHxhGhqj8pP:-LFRQyR089BX0stnB9N1:b-18fn8m) (no related file):*
> It will become a production mode run being running in production mode

Sorry .
I meant : 

It will become a dev mode run being running in production mode

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4306)*

**Comment by pekam** [comment]
Review status: 2 unresolved discussions, 0 of 1 LGTMs obtained

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow/4306#-LFQrSI6DDHxhGhqj8pP:-LFRXSW_7z7hEsfmBrTh:b-fp8876) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> It will become a production mode run being running in production mode

Sorry .
I meant : 

It will become a dev mode run being running in production mode
</blockquote></details>

Yes, currently tests that use this semi-production mode are in `test-dev-mode`.
I don't know if it's optimal but that's how I got it to work in normal build (without `-PproductionMode`), since those didn't work anymore in `test-root-context`.

Actually I now figured out that I could have kept those in the `test-root-context` if I trigger the `frontend es5` config which I removed only when not running in production mode.

So the configuration is currently like this:
- `test-dev-mode` contains the "old" configuration and everything works as it used to
  - views are served normally under `/view/`
  - views are served in semi-production mode under `/view-production/`: only the servlet parameter is set, but no maven plugin is run
  - views are served in semi-production mode with overridden `frontend.url.es6` under `/view-es6-url/`
- `test-root-context` has the same servlets, but it actually uses only the basic `/view/` paths.
  - when running in production mode with `-PproductionMode` it really runs the maven plugin instead of just setting one parameter, and it uses the same servlet with `/view/`
  - other servlets still exist (`/view-production/` and `/view-es6-url/`) but they are not used and actually they don't even work with the new configuration that expects a "true" production mode where the transpiled es5 files really exist

(I'm not sure if you needed all this explanation but I needed to write it down to clarify for myself at least)

If we want to move all the semi-production mode tests to use "real" production mode, then we would need to run transpilation and everything for every build. I don't think it's necessary since the tests just check that the resource paths are changed based on the servlet parameter. That's why I'd like to just have them in `test-dev-mode`.

But the modules have really bad names in this case... 

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4306)*

**Comment by denis-anisimov** [comment]
Review status: 2 unresolved discussions, 0 of 1 LGTMs obtained

---

*[flow-tests/test-root-context/pom.xml, line 83 at r1](https://reviewable.io/reviews/vaadin/flow/4306#-LFQtfAHBJ6L3NTfgynf:-LFRjt8S5AOdCV7_3tdt:b-wnweig) ([raw file](https://github.com/vaadin/flow/blob/cad6d39b1764ae18418984d049e2d1ee9689b063/flow-tests/test-root-context/pom.xml#L83)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

Previously, when there was no "true" production mode, this config was used to serve the same static resources for es5 that we have for es6. Otherwise it would have tried to look for non-existing transpiled resources in some es5 folder.

Now with transpilation enabled, if we want the transpiled resources to be served to IE11, we need to use the default directory for es5 which contains the transpiled resources.
</blockquote></details>

Yes, but semi-production mode tests have been moved to the `dev-mode`.
And I don't see similar changes in the `pom.xml` of `dev-mode` to be able to handle the resources in the same way as it was in this module.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4306)*

**Comment by pekam** [comment]
Review status: 2 unresolved discussions, 0 of 1 LGTMs obtained

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow/4306#-LFQrSI6DDHxhGhqj8pP:-LFRjnz3El6gwGpv4bjR:b-emx9s7) (no related file):*
>does versionInfoAvailableInDevelopmentMopde fail being running in production mode ?
does versionInfoNotAvailableInProductionMode fail being running in production mode ?

The semi-production mode should be enough to verify these, as they have been using that until this point anyway.

I didn't test now but the first test should fail in production mode and the second one shouldn't. It shouldn't matter whether we use semi-production mode or true production mode here.

>If not then UIs should be moved to the common, IT tests should be splitted between two modules.

Then we need to either run production build always in `test-root-context`, or make the semi-production mode work in there also. I think it's cleaner if we keep the `test-root-context` simple with just the one servlet used for both dev and production mode, and have the other servlets just in `test-dev-mode`.

>Also if you are moving out all semi-production mode related tests then you may move the corresponding production mode servlet into dev-mode module out of the common module.

I agree with this.

---

*[flow-tests/test-root-context/pom.xml, line 83 at r1](https://reviewable.io/reviews/vaadin/flow/4306#-LFQtfAHBJ6L3NTfgynf:-LFRlW2-BISGfAVA7FBq:b-ndl20x) ([raw file](https://github.com/vaadin/flow/blob/cad6d39b1764ae18418984d049e2d1ee9689b063/flow-tests/test-root-context/pom.xml#L83)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Yes, but semi-production mode tests have been moved to the `dev-mode`.
And I don't see similar changes in the `pom.xml` of `dev-mode` to be able to handle the resources in the same way as it was in this module.
</blockquote></details>

We already had that config in the `test-dev-mode`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4306)*

**Comment by denis-anisimov** [comment]
Review status: 1 unresolved discussion, 0 of 1 LGTMs obtained

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow/4306#-LFQrSI6DDHxhGhqj8pP:-LFRpXQjBA5kGPVjodFn:b77uqya) (no related file):*
> I didn't test now but the first test should fail in production mode and the second one shouldn't. It shouldn't matter whether we use semi-production mode or true production mode here.

I don't think so.
The production mode assumes that the servlet is running production mode AND also web resources are transpiled and are in the correct location.
The last thing is exactly which is different for this semi-production mode. And may be this is the purpose of the test:
check what's going on when the user forgets to transpile but still running the production mode in the servlet. ( I don't know anything about those tests).
So let's don't do _any_ assumption for those tests.

>Then we need to either run production build always in test-root-context, or make the semi-production mode work in there also. 

Yes. I'm talking about the second option.
We don't want to run production mode all the time for `root-context` tests.
But why we can't use the same tests as is ?
If those tests works in "semi-production" mode AND they work in a normal production mode then I don't understand what's the problem ?
Why we can't just keep everything as is (as I said: mode UI classes in `common` keep the tests which are working here and move those that don't work to `dev-mode`)?

---

*[flow-tests/test-root-context/pom.xml, line 83 at r1](https://reviewable.io/reviews/vaadin/flow/4306#-LFQtfAHBJ6L3NTfgynf:-LFRrZtGD6SYqin8X-I6:b-py294e) ([raw file](https://github.com/vaadin/flow/blob/cad6d39b1764ae18418984d049e2d1ee9689b063/flow-tests/test-root-context/pom.xml#L83)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

We already had that config in the `test-dev-mode`.
</blockquote></details>

Ah, OK.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4306)*

**Comment by pekam** [comment]
Review status: 1 unresolved discussion, 0 of 1 LGTMs obtained

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow/4306#-LFQrSI6DDHxhGhqj8pP:-LFS8_90DJn5CTqpDBFB:b-oj84z4) (no related file):*
>If those tests works in "semi-production" mode AND they work in a normal production mode then I don't understand what's the problem ?

It makes things more complex and confusing.

I need to trigger specific configuration to make the semi-production mode work when not running real production mode (the configuration for `frontend-es5` which I removed in this PR). So there will be both kinds of production mode in `test-root-context`.

Also, using the same view for both modules makes things more confusing. Usually we have the test view with the test class in the same module, but now we would need to introduce a couple of exceptions which are used in two modules.

But whatever, if you still disagree with me, I will try to make it work to get this forward.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4306)*

**Comment by denis-anisimov** [comment]
Review status: 1 unresolved discussion, 0 of 1 LGTMs obtained

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow/4306#-LFQrSI6DDHxhGhqj8pP:-LFSH9Kn0R4EAqpZvOlz:bo43hv2) (no related file):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

>If those tests works in "semi-production" mode AND they work in a normal production mode then I don't understand what's the problem ?

It makes things more complex and confusing.

I need to trigger specific configuration to make the semi-production mode work when not running real production mode (the configuration for `frontend-es5` which I removed in this PR). So there will be both kinds of production mode in `test-root-context`.

Also, using the same view for both modules makes things more confusing. Usually we have the test view with the test class in the same module, but now we would need to introduce a couple of exceptions which are used in two modules.

But whatever, if you still disagree with me, I will try to make it work to get this forward.
</blockquote></details>

If it's complicated then OK.
I'm just asking because I'm not aware of issues. 
Of course it may be that I just don't see something.
And that's why I'm asking.

Don't see any issues with having shared UI classes for two modules.
They are not tests. They are additional classes which helps to test.

But if it's too hard to make tests work for `root-context` then it's OK just move them out.
I just wanted to be sure that it's really necessary.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4306)*

**Comment by denis-anisimov** [comment]
Review status: all discussions resolved, 0 of 1 LGTMs obtained

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow/4306#-LFQrSI6DDHxhGhqj8pP:-LFSI5jw-w3rFZW9UU4U:b-oe4j0l) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

If it's complicated then OK.
I'm just asking because I'm not aware of issues. 
Of course it may be that I just don't see something.
And that's why I'm asking.

Don't see any issues with having shared UI classes for two modules.
They are not tests. They are additional classes which helps to test.

But if it's too hard to make tests work for `root-context` then it's OK just move them out.
I just wanted to be sure that it's really necessary.
</blockquote></details>

We are releasing now......
Let's wait for the release and don't merge it right now.
I'm blocking this because of the release.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4306)*

**Comment by denis-anisimov** [comment]
:lgtm:

---

Review status: all discussions resolved, 0 of 1 LGTMs obtained, and 1 stale

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4306#-:-LFWhzHuEWQu9XPSPwhV:bnfp4nl)*

**Pull request merged**
