### PR TITLE
Add missing base HTML elements

### LINKED ISSUE #2535: Add class to create paragraph elements (<p>)
Sometimes I want to create a semantic paragraph element instead of a `<div>` or a `<span>`.

### PR DESCRIPTION
**Pull request by heruan**
Fixes #2535 adding `<p>` elements and also `<li>`, `<ul>`, `<ol>`, `<dl>`, `<dt>` and `<dd>`.

Tests are coming.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/2719)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[flow-html-components/src/main/java/com/vaadin/ui/html/DescriptionList.java, line 127 at r1](https://reviewable.io:443/reviews/vaadin/flow/2719#-KwnJ6KPyDOjBjYTgE0L:-KwnJ6KPyDOjBjYTgE0M:b-p3yo2x) ([raw file](https://github.com/vaadin/flow/blob/a5640ea3858d2c83a414cee2780b893520af1723/flow-html-components/src/main/java/com/vaadin/ui/html/DescriptionList.java#L127)):*
> Stream.concat(Stream.of(entry.getKey()),
>                         Stream.of(entry.getValue())

Why not just `Stream.of(entry.getKey(), entry.getValue())` ?

---

*[flow-html-components/src/main/java/com/vaadin/ui/html/OrderedList.java, line 26 at r1](https://reviewable.io:443/reviews/vaadin/flow/2719#-KwnEeUh4F7ylR_1QyEq:-KwnEeUh4F7ylR_1QyEr:bijmxf) ([raw file](https://github.com/vaadin/flow/blob/a5640ea3858d2c83a414cee2780b893520af1723/flow-html-components/src/main/java/com/vaadin/ui/html/OrderedList.java#L26)):*
> <code>&lt;p&gt;</code>

typo

---

*[flow-html-components/src/main/java/com/vaadin/ui/html/OrderedList.java, line 33 at r1](https://reviewable.io:443/reviews/vaadin/flow/2719#-KwnElrpl9diqCXKhzYJ:-KwnElrpl9diqCXKhzYK:bgj5bvz) ([raw file](https://github.com/vaadin/flow/blob/a5640ea3858d2c83a414cee2780b893520af1723/flow-html-components/src/main/java/com/vaadin/ui/html/OrderedList.java#L33)):*
> Type

I would use `ItemType`

---

*[flow-html-components/src/main/java/com/vaadin/ui/html/OrderedList.java, line 59 at r1](https://reviewable.io:443/reviews/vaadin/flow/2719#-KwnF9Kfmy_B7NzB07tY:-KwnF9Kfmy_B7NzB07tZ:bbszf2z) ([raw file](https://github.com/vaadin/flow/blob/a5640ea3858d2c83a414cee2780b893520af1723/flow-html-components/src/main/java/com/vaadin/ui/html/OrderedList.java#L59)):*
> private final String value;

The value is used here inlined in the other private class.
So it's kind of fine.

But it might be there is a sense to open it as open API via public getter ( and then use it in the property descriptor).

I'm not entirely sure whether it's useful or not.

---

*[flow-html-components/src/main/java/com/vaadin/ui/html/OrderedList.java, line 109 at r1](https://reviewable.io:443/reviews/vaadin/flow/2719#-KwnFs7Hu2lBmW8wy30O:-KwnFs7Hu2lBmW8wy30P:b-da8wmo) ([raw file](https://github.com/vaadin/flow/blob/a5640ea3858d2c83a414cee2780b893520af1723/flow-html-components/src/main/java/com/vaadin/ui/html/OrderedList.java#L109)):*
> switch (value) {
<details><summary><i alt="summary">Quoted 14 lines of code…</i></summary>
>         case "1":
>             return Type.NUMBERS;
>         case "A":
>             return Type.UPPERCASE_LETTER;
>         case "a":
>             return Type.LOWERCASE_LETTER;
>         case "I":
>             return Type.UPPERCASE_ROMAN;
>         case "i":
>             return Type.LOWERCASE_ROMAN;
>         default:
>             throw new IllegalStateException(
>                     "The attribute type has an illegal value: " + value);
>         }
</details>


that can go into enumeration.
And instead of multiple `case` it may just go through all enum values and compare them with the `value`.

---

*[flow-html-components/src/main/java/com/vaadin/ui/html/UnorderedList.java, line 24 at r1](https://reviewable.io:443/reviews/vaadin/flow/2719#-KwnETWlQR1TgrXIB8FW:-KwnETWlQR1TgrXIB8FX:bijmxf) ([raw file](https://github.com/vaadin/flow/blob/a5640ea3858d2c83a414cee2780b893520af1723/flow-html-components/src/main/java/com/vaadin/ui/html/UnorderedList.java#L24)):*
> <code>&lt;p&gt;</code>

typo

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2719)*

**Comment by heruan** [comment]
*[flow-html-components/src/main/java/com/vaadin/ui/html/DescriptionList.java, line 127 at r1](https://reviewable.io:443/reviews/vaadin/flow/2719#-KwnJ6KPyDOjBjYTgE0L:-Kwnc9axax89zC0fXrV1:b7joj8x) ([raw file](https://github.com/vaadin/flow/blob/a5640ea3858d2c83a414cee2780b893520af1723/flow-html-components/src/main/java/com/vaadin/ui/html/DescriptionList.java#L127)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> Stream.concat(Stream.of(entry.getKey()),
>                         Stream.of(entry.getValue())

Why not just `Stream.of(entry.getKey(), entry.getValue())` ?
</blockquote></details>

Because it was late :smile: 
Fixed :+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2719)*

**Comment by heruan** [comment]
*[flow-html-components/src/main/java/com/vaadin/ui/html/OrderedList.java, line 59 at r1](https://reviewable.io:443/reviews/vaadin/flow/2719#-KwnF9Kfmy_B7NzB07tY:-KwncUPDoNQMChXAhZDP:bnhe0ni) ([raw file](https://github.com/vaadin/flow/blob/a5640ea3858d2c83a414cee2780b893520af1723/flow-html-components/src/main/java/com/vaadin/ui/html/OrderedList.java#L59)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> private final String value;

The value is used here inlined in the other private class.
So it's kind of fine.

But it might be there is a sense to open it as open API via public getter ( and then use it in the property descriptor).

I'm not entirely sure whether it's useful or not.
</blockquote></details>

I'd keep it private since the actual String value has no use outside the element itself.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2719)*

**Comment by denis-anisimov** [comment]
Reviewed 11 of 11 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-html-components/src/main/java/com/vaadin/ui/html/OrderedList.java, line 75 at r2](https://reviewable.io:443/reviews/vaadin/flow/2719#-KwncOqQ_Ta65PIiU7f9:-KwncOqQ_Ta65PIiU7fA:b-a7gaui) ([raw file](https://github.com/vaadin/flow/blob/7e6a04d0538afefe68e942fa44df35f169236869/flow-html-components/src/main/java/com/vaadin/ui/html/OrderedList.java#L75)):*
> if (ItemType.NUMBERS.value.equals(value)) {
<details><summary><i alt="summary">Quoted 12 lines of code…</i></summary>
>                 return ItemType.NUMBERS;
>             } else if (ItemType.UPPERCASE_LETTER.value.equals(value)) {
>                 return ItemType.UPPERCASE_LETTER;
>             } else if (ItemType.LOWERCASE_LETTER.value.equals(value)) {
>                 return ItemType.LOWERCASE_LETTER;
>             } else if (ItemType.UPPERCASE_ROMAN.value.equals(value)) {
>                 return ItemType.UPPERCASE_ROMAN;
>             } else if (ItemType.LOWERCASE_ROMAN.value.equals(value)) {
>                 return ItemType.LOWERCASE_ROMAN;
>             } else {
>                 throw new IllegalArgumentException(value);
>             }
</details>

Still , I would use:

```
for ( ItemType type: values()){
     if (type.value.equals(value){
        return type;
    }
}
throw new IllegalArgumentException(value);

```

---

*[flow-html-components/src/test/java/com/vaadin/ui/html/ComponentProperty.java, line 32 at r2](https://reviewable.io:443/reviews/vaadin/flow/2719#-Kwnd0-BnggXCwySiNmY:-Kwnd0-BnggXCwySiNmZ:bbd6zh4) ([raw file](https://github.com/vaadin/flow/blob/7e6a04d0538afefe68e942fa44df35f169236869/flow-html-components/src/test/java/com/vaadin/ui/html/ComponentProperty.java#L32)):*
>  T otherValue,

What the `otherValue` is?
How does it differ from `defaultValue`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2719)*

**Comment by heruan** [comment]
*[flow-html-components/src/test/java/com/vaadin/ui/html/ComponentProperty.java, line 32 at r2](https://reviewable.io:443/reviews/vaadin/flow/2719#-Kwnd0-BnggXCwySiNmY:-KwndnhWnDHVDk9kq3vE:b-z27o4m) ([raw file](https://github.com/vaadin/flow/blob/7e6a04d0538afefe68e942fa44df35f169236869/flow-html-components/src/test/java/com/vaadin/ui/html/ComponentProperty.java#L32)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

>  T otherValue,

What the `otherValue` is?
How does it differ from `defaultValue`?
</blockquote></details>

It's a value different from the default to be tested.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2719)*

**Comment by heruan** [comment]
*[flow-html-components/src/main/java/com/vaadin/ui/html/OrderedList.java, line 33 at r1](https://reviewable.io:443/reviews/vaadin/flow/2719#-KwnElrpl9diqCXKhzYJ:-KwndxMf2LXqqDgrynbC:byl72lt) ([raw file](https://github.com/vaadin/flow/blob/a5640ea3858d2c83a414cee2780b893520af1723/flow-html-components/src/main/java/com/vaadin/ui/html/OrderedList.java#L33)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> Type

I would use `ItemType`
</blockquote></details>

On a second thought, that is the "numbering" type and `ItemType` may be confusing. Could `NumberingType` work?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2719)*

**Comment by denis-anisimov** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[flow-html-components/src/test/java/com/vaadin/ui/html/ComponentProperty.java, line 32 at r2](https://reviewable.io:443/reviews/vaadin/flow/2719#-Kwnd0-BnggXCwySiNmY:-KwnkhsXFKqdi29UVAcW:bjbe4jt) ([raw file](https://github.com/vaadin/flow/blob/7e6a04d0538afefe68e942fa44df35f169236869/flow-html-components/src/test/java/com/vaadin/ui/html/ComponentProperty.java#L32)):*
<details><summary><i>Previously, heruan (Giovanni Lovato) wrote…</i></summary><blockquote>

It's a value different from the default to be tested.
</blockquote></details>

How it is used ?
I don't see it's usage except it's initialization the CTOR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2719)*

**Comment by heruan** [comment]
*[flow-html-components/src/test/java/com/vaadin/ui/html/ComponentProperty.java, line 32 at r2](https://reviewable.io:443/reviews/vaadin/flow/2719#-Kwnd0-BnggXCwySiNmY:-Kwnldcf0LuQTE0PrZEy:bh5kdum) ([raw file](https://github.com/vaadin/flow/blob/7e6a04d0538afefe68e942fa44df35f169236869/flow-html-components/src/test/java/com/vaadin/ui/html/ComponentProperty.java#L32)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

How it is used ?
I don't see it's usage except it's initialization the CTOR.
</blockquote></details>

In `ComponentProperty.setToOtherValueUsingSetter` it's used to test a value different form the default assigned to the property. Before this PR the type of the value in tests was assumed to be always `String` and it was initialized with `othervalue = name + name` in CTOR, but this fails if the setter does not accept strings.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2719)*

**Comment by heruan** [comment]
*[flow-html-components/src/main/java/com/vaadin/ui/html/OrderedList.java, line 75 at r2](https://reviewable.io:443/reviews/vaadin/flow/2719#-KwncOqQ_Ta65PIiU7f9:-KwnmTg_t59qRH65DAnL:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/7e6a04d0538afefe68e942fa44df35f169236869/flow-html-components/src/main/java/com/vaadin/ui/html/OrderedList.java#L75)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> if (ItemType.NUMBERS.value.equals(value)) {
>                 return ItemType.NUMBERS;
>             } else if (ItemType.UPPERCASE_LETTER.value.equals(value)) {
>                 return ItemType.UPPERCASE_LETTER;
>             } else if (ItemType.LOWERCASE_LETTER.value.equals(value)) {
>                 return ItemType.LOWERCASE_LETTER;
>             } else if (ItemType.UPPERCASE_ROMAN.value.equals(value)) {
>                 return ItemType.UPPERCASE_ROMAN;
>             } else if (ItemType.LOWERCASE_ROMAN.value.equals(value)) {
>                 return ItemType.LOWERCASE_ROMAN;
>             } else {
>                 throw new IllegalArgumentException(value);
>             }

Still , I would use:

```
for ( ItemType type: values()){
     if (type.value.equals(value){
        return type;
    }
}
throw new IllegalArgumentException(value);

```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2719)*

**Comment by heruan** [comment]
*[flow-html-components/src/main/java/com/vaadin/ui/html/OrderedList.java, line 33 at r3](https://reviewable.io:443/reviews/vaadin/flow/2719#-KwlHoHf-Ahqf4uyoxkp-r3-33:-KwnmccJdgnHy_6kj-ox:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/f0fbf169de69bd0b77903edbb3f94d2390cd4df6/flow-html-components/src/main/java/com/vaadin/ui/html/OrderedList.java#L33)):*
<details><summary><i>Previously, vaadin-bot (Vaadin Bot) wrote…</i></summary><blockquote>

CRITICAL Document this public enum. [rule](https://sonar.projects.vaadin.com/coding_rules#rule_key=squid%3AUndocumentedApi)
MINOR Remove this redundant "static" qualifier. [rule](https://sonar.projects.vaadin.com/coding_rules#rule_key=squid%3AS2786)

</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2719)*

**Comment by heruan** [comment]
*[flow-html-components/src/main/java/com/vaadin/ui/html/OrderedList.java, line 62 at r3](https://reviewable.io:443/reviews/vaadin/flow/2719#-KwlHoHf-Ahqf4uyoxkp-r3-62:-Kwnmey5FD0JY1x3TRdc:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/f0fbf169de69bd0b77903edbb3f94d2390cd4df6/flow-html-components/src/main/java/com/vaadin/ui/html/OrderedList.java#L62)):*
<details><summary><i>Previously, vaadin-bot (Vaadin Bot) wrote…</i></summary><blockquote>

MINOR "private" is redundant in this context. [rule](https://sonar.projects.vaadin.com/coding_rules#rule_key=squid%3AS2333)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2719)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[flow-html-components/src/main/java/com/vaadin/ui/html/OrderedList.java, line 75 at r2](https://reviewable.io:443/reviews/vaadin/flow/2719#-KwncOqQ_Ta65PIiU7f9:-KwnoZ1fVw4CyEnRrr1N:bwzbw32) ([raw file](https://github.com/vaadin/flow/blob/7e6a04d0538afefe68e942fa44df35f169236869/flow-html-components/src/main/java/com/vaadin/ui/html/OrderedList.java#L75)):*
<details><summary><i>Previously, heruan (Giovanni Lovato) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Can be even more shortened with Streams and filter but it's minor. Not blocking.

---

*[flow-html-components/src/test/java/com/vaadin/ui/html/ComponentProperty.java, line 32 at r2](https://reviewable.io:443/reviews/vaadin/flow/2719#-Kwnd0-BnggXCwySiNmY:-KwnoFa3A3Wu2afTyMEp:b-p94idf) ([raw file](https://github.com/vaadin/flow/blob/7e6a04d0538afefe68e942fa44df35f169236869/flow-html-components/src/test/java/com/vaadin/ui/html/ComponentProperty.java#L32)):*
<details><summary><i>Previously, heruan (Giovanni Lovato) wrote…</i></summary><blockquote>

In `ComponentProperty.setToOtherValueUsingSetter` it's used to test a value different form the default assigned to the property. Before this PR the type of the value in tests was assumed to be always `String` and it was initialized with `othervalue = name + name` in CTOR, but this fails if the setter does not accept strings.
</blockquote></details>

Aaaaah. OK, missed that the property has been already used.
OK.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2719)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[flow-html-components/src/main/java/com/vaadin/ui/html/OrderedList.java, line 33 at r3](https://reviewable.io:443/reviews/vaadin/flow/2719#-KwlHoHf-Ahqf4uyoxkp-r3-33:-Kwnp-yi5uiRF2iYcHZO:bmolc3n) ([raw file](https://github.com/vaadin/flow/blob/f0fbf169de69bd0b77903edbb3f94d2390cd4df6/flow-html-components/src/main/java/com/vaadin/ui/html/OrderedList.java#L33)):*
<details><summary><i>Previously, heruan (Giovanni Lovato) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You shouldn't reply to SQ (vaadin-bot) comments.
Otherwise you will need to explicitly dismiss it from the discussion.

Just fix critical and blocker comments.
You may ignore anything else (without any reply).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2719)*

**Comment by heruan** [comment]
*[flow-html-components/src/main/java/com/vaadin/ui/html/OrderedList.java, line 75 at r2](https://reviewable.io:443/reviews/vaadin/flow/2719#-KwncOqQ_Ta65PIiU7f9:-Kwnru-Au2g93QjJSj_6:bal3ggw) ([raw file](https://github.com/vaadin/flow/blob/7e6a04d0538afefe68e942fa44df35f169236869/flow-html-components/src/main/java/com/vaadin/ui/html/OrderedList.java#L75)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Can be even more shortened with Streams and filter but it's minor. Not blocking.
</blockquote></details>

Shortened with stream/filter.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2719)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2719)*

**Comment by denis-anisimov** [comment]
You still need to go through SQ comments and dismiss them.

---

Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2719#-:-KwntAlq-abOsoib3l3r:bhez81b)*

**Comment by heruan** [comment]
*[flow-html-components/src/main/java/com/vaadin/ui/html/OrderedList.java, line 62 at r3](https://reviewable.io:443/reviews/vaadin/flow/2719#-KwlHoHf-Ahqf4uyoxkp-r3-62:-KwoJmUaRRALy4gS_-8n:b32w0x) ([raw file](https://github.com/vaadin/flow/blob/f0fbf169de69bd0b77903edbb3f94d2390cd4df6/flow-html-components/src/main/java/com/vaadin/ui/html/OrderedList.java#L62)):*
<details><summary><i>Previously, heruan (Giovanni Lovato) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2719)*

**Comment by heruan** [comment]
> You still need to go through SQ comments and dismiss them.

@denis-anisimov Seems like I don't have permission to dismiss them!

**Comment by SomeoneToIgnore** [comment]
Reviewed 2 of 2 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2719)*

**Pull request merged**
