### PR TITLE
Rewrite the tutorial about sorting

### PR DESCRIPTION
**Pull request by gilberto-torrezan**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/2986)

### CODE REVIEW

**Comment by torok-peter** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-documentation/flow-components/tutorial-flow-grid.asciidoc, line 581 at r1](https://reviewable.io:443/reviews/vaadin/flow/2986#-KzOw4vkCC6xBdbV3_sN:-KzOw4vkCC6xBdbV3_sO:b-acz0di) ([raw file](https://github.com/vaadin/flow/blob/0265255ce2aff1d187d30a53564746c6f2c7adb0/flow-documentation/flow-components/tutorial-flow-grid.asciidoc#L581)):*
Last sentence is not clear to me. Do you mean

> *Unlike* the `addColumn` [in the options above], this doesn't configure any in-memory sorting

or

> *Apart from* the `addColumn`, this doesn't configure any in-memory sorting

or ... ?

---

*[flow-documentation/flow-components/tutorial-flow-grid.asciidoc, line 617 at r1](https://reviewable.io:443/reviews/vaadin/flow/2986#-KzOwyDdM4FyOwmCVfip:-KzOwyDdM4FyOwmCVfiq:b-45h4up) ([raw file](https://github.com/vaadin/flow/blob/0265255ce2aff1d187d30a53564746c6f2c7adb0/flow-documentation/flow-components/tutorial-flow-grid.asciidoc#L617)):*
> having to *reconfigure* it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2986)*

**Comment by gilberto-torrezan** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-documentation/flow-components/tutorial-flow-grid.asciidoc, line 581 at r1](https://reviewable.io:443/reviews/vaadin/flow/2986#-KzOw4vkCC6xBdbV3_sN:-KzSOo3-pB-BGq5evJa2:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/0265255ce2aff1d187d30a53564746c6f2c7adb0/flow-documentation/flow-components/tutorial-flow-grid.asciidoc#L581)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

Last sentence is not clear to me. Do you mean

> *Unlike* the `addColumn` [in the options above], this doesn't configure any in-memory sorting

or

> *Apart from* the `addColumn`, this doesn't configure any in-memory sorting

or ... ?
</blockquote></details>

Done.

---

*[flow-documentation/flow-components/tutorial-flow-grid.asciidoc, line 617 at r1](https://reviewable.io:443/reviews/vaadin/flow/2986#-KzOwyDdM4FyOwmCVfip:-KzSOocUOZFylaklJA1d:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/0265255ce2aff1d187d30a53564746c6f2c7adb0/flow-documentation/flow-components/tutorial-flow-grid.asciidoc#L617)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

> having to *reconfigure* it
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2986)*

**Comment by ahie** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[flow-documentation/flow-components/tutorial-flow-grid.asciidoc, line 537 at r2](https://reviewable.io:443/reviews/vaadin/flow/2986#-KzSPLpi1tO-nxRVU_ra:-KzSPLpi1tO-nxRVU_rb:b-wwakeh) ([raw file](https://github.com/vaadin/flow/blob/289942d8efc9f8659c19629051684049632a62b9/flow-documentation/flow-components/tutorial-flow-grid.asciidoc#L537)):*
> For the in-memory sorting to work properly

Actually it is impossible to give the `ValueProvider, String ...` overload a provider that provides non-comparable values. Though this is relevant for the `TemplateRenderer` overload. Also should note that the given sort properties should match the properties defined for a given `TemplateRenderer`, because that is the mechanism used to configure the sorting order of the contained value providers. 

---

*[flow-documentation/flow-components/tutorial-flow-grid.asciidoc, line 616 at r2](https://reviewable.io:443/reviews/vaadin/flow/2986#-KzSQoXk6cTDukEGgZcQ:-KzSQoXk6cTDukEGgZcR:b-ahj1y9) ([raw file](https://github.com/vaadin/flow/blob/289942d8efc9f8659c19629051684049632a62b9/flow-documentation/flow-components/tutorial-flow-grid.asciidoc#L616)):*
> Setting a column as not `sortable` doesn't delete any `Comparator`, `sort property` or `SortOrderProvider` previously set

Not really defined what being `sortable` means. It enables the client-side sorting, i.e. it displays the sorter element in the header of the column.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2986)*

**Comment by gilberto-torrezan** [comment]
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[flow-documentation/flow-components/tutorial-flow-grid.asciidoc, line 537 at r2](https://reviewable.io:443/reviews/vaadin/flow/2986#-KzSPLpi1tO-nxRVU_ra:-KzSYKRyksroAGpafKvv:b-hkp74j) ([raw file](https://github.com/vaadin/flow/blob/289942d8efc9f8659c19629051684049632a62b9/flow-documentation/flow-components/tutorial-flow-grid.asciidoc#L537)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

> For the in-memory sorting to work properly

Actually it is impossible to give the `ValueProvider, String ...` overload a provider that provides non-comparable values. Though this is relevant for the `TemplateRenderer` overload. Also should note that the given sort properties should match the properties defined for a given `TemplateRenderer`, because that is the mechanism used to configure the sorting order of the contained value providers. 
</blockquote></details>

Changed the structure a bit, and added a second note.

---

*[flow-documentation/flow-components/tutorial-flow-grid.asciidoc, line 616 at r2](https://reviewable.io:443/reviews/vaadin/flow/2986#-KzSQoXk6cTDukEGgZcQ:-KzSYJbBI09OGoyvh7hN:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/289942d8efc9f8659c19629051684049632a62b9/flow-documentation/flow-components/tutorial-flow-grid.asciidoc#L616)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

> Setting a column as not `sortable` doesn't delete any `Comparator`, `sort property` or `SortOrderProvider` previously set

Not really defined what being `sortable` means. It enables the client-side sorting, i.e. it displays the sorter element in the header of the column.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2986)*

**Comment by ahie** [comment]
:lgtm:

---

Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2986#-:-KzS_XsxYbUqu45WH6oL:bnfp4nl)*

**Comment by ahie** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2986)*

**Comment by torok-peter** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-documentation/flow-components/tutorial-flow-grid.asciidoc, line 581 at r1](https://reviewable.io:443/reviews/vaadin/flow/2986#-KzOw4vkCC6xBdbV3_sN:-KzSZTD01emzSDADQSw_:b-lzbj39) ([raw file](https://github.com/vaadin/flow/blob/0265255ce2aff1d187d30a53564746c6f2c7adb0/flow-documentation/flow-components/tutorial-flow-grid.asciidoc#L581)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Better, but still confusing, as `addColumn` is called in the code sample right below. Does "this" in the sentence above refer to the call to `setSortProperty` only, or to the whole call chain? In the former case, does the whole call chain still result in configuring in-memory sorting? In the latter case, what's the decisive difference between the `addColumn` call here and the `addColumn` calls above, which makes this one not configure in-memory sorting?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2986)*

**Comment by gilberto-torrezan** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[flow-documentation/flow-components/tutorial-flow-grid.asciidoc, line 581 at r1](https://reviewable.io:443/reviews/vaadin/flow/2986#-KzOw4vkCC6xBdbV3_sN:-KzSeyn9RfJQcbcBxcah:b-wnguvn) ([raw file](https://github.com/vaadin/flow/blob/0265255ce2aff1d187d30a53564746c6f2c7adb0/flow-documentation/flow-components/tutorial-flow-grid.asciidoc#L581)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

Better, but still confusing, as `addColumn` is called in the code sample right below. Does "this" in the sentence above refer to the call to `setSortProperty` only, or to the whole call chain? In the former case, does the whole call chain still result in configuring in-memory sorting? In the latter case, what's the decisive difference between the `addColumn` call here and the `addColumn` calls above, which makes this one not configure in-memory sorting?
</blockquote></details>

One more attempt.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2986)*

**Comment by torok-peter** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2986#-:-KzSgT4OSw9jKoqJjOml:bnfp4nl)*

**Pull request merged**
