### PR TITLE
Disable multi logger of springBeans for I18N

### PR DESCRIPTION
**Pull request by ZheSun88**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3724)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[flow-spring-addon/src/main/java/com/vaadin/flow/spring/SpringInstantiator.java, line 39 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3724#-L7xBUiVAzhc9-V5HDmU:-L7xBUiVAzhc9-V5HDmV:bvlkx8f) ([raw file](https://github.com/vaadin/flow/blob/5f9966ff309204dec7a60e6c2d7b378ca3790045/flow-spring-addon/src/main/java/com/vaadin/flow/spring/SpringInstantiator.java#L39)):*
> private VaadinService service;

why?

---

*[flow-spring-addon/src/main/java/com/vaadin/flow/spring/SpringInstantiator.java, line 40 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3724#-L7xBW0t3Xg3yCaJuhQ8:-L7xBW0t3Xg3yCaJuhQ9:b8ltfyd) ([raw file](https://github.com/vaadin/flow/blob/5f9966ff309204dec7a60e6c2d7b378ca3790045/flow-spring-addon/src/main/java/com/vaadin/flow/spring/SpringInstantiator.java#L40)):*
> AtomicBoolean infoLogger = new AtomicBoolean(true);

has to be `private`

The name is bad. What does it mean? Is log enabled? done? or what ?
Depending in the name `true` as a default value is needed or not.
I don't understand which value is correct from the name.

---

*[flow-spring-addon/src/main/java/com/vaadin/flow/spring/SpringInstantiator.java, line 70 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3724#-L7xCdCB9Am1D1yieje5:-L7xCdCB9Am1D1yieje6:b46yo5g) ([raw file](https://github.com/vaadin/flow/blob/5f9966ff309204dec7a60e6c2d7b378ca3790045/flow-spring-addon/src/main/java/com/vaadin/flow/spring/SpringInstantiator.java#L70)):*
> if (infoLogger.compareAndSet(true, false)) {

It's better do not try to set each time during check.

It's better to:
- check whether it's `true` or `false` via `get()` method.
- log depending on the value.
- update the value unconditionally or not (it doesn't really matter in this situation).

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3724)*

**Comment by ZheSun88** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[flow-spring-addon/src/main/java/com/vaadin/flow/spring/SpringInstantiator.java, line 39 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3724#-L7xBUiVAzhc9-V5HDmU:-L7xWgqbBcjEcTycQi9L:b-hfpv0l) ([raw file](https://github.com/vaadin/flow/blob/5f9966ff309204dec7a60e6c2d7b378ca3790045/flow-spring-addon/src/main/java/com/vaadin/flow/spring/SpringInstantiator.java#L39)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> private VaadinService service;

why?
</blockquote></details>

removed

---

*[flow-spring-addon/src/main/java/com/vaadin/flow/spring/SpringInstantiator.java, line 40 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3724#-L7xBW0t3Xg3yCaJuhQ8:-L7xWn8O5_M9t4uQCnNi:batswda) ([raw file](https://github.com/vaadin/flow/blob/5f9966ff309204dec7a60e6c2d7b378ca3790045/flow-spring-addon/src/main/java/com/vaadin/flow/spring/SpringInstantiator.java#L40)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> AtomicBoolean infoLogger = new AtomicBoolean(true);

has to be `private`

The name is bad. What does it mean? Is log enabled? done? or what ?
Depending in the name `true` as a default value is needed or not.
I don't understand which value is correct from the name.
</blockquote></details>

add private and changed the name to loggerEnable, hope the name is better now

---

*[flow-spring-addon/src/main/java/com/vaadin/flow/spring/SpringInstantiator.java, line 70 at r1](https://beta.reviewable.io/reviews/vaadin/flow/3724#-L7xCdCB9Am1D1yieje5:-L7xWveCDYPKH8uDnfLn:b3674ju) ([raw file](https://github.com/vaadin/flow/blob/5f9966ff309204dec7a60e6c2d7b378ca3790045/flow-spring-addon/src/main/java/com/vaadin/flow/spring/SpringInstantiator.java#L70)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> if (infoLogger.compareAndSet(true, false)) {

It's better do not try to set each time during check.

It's better to:
- check whether it's `true` or `false` via `get()` method.
- log depending on the value.
- update the value unconditionally or not (it doesn't really matter in this situation).
</blockquote></details>

used the 1) option in code. 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3724)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[flow-spring-addon/src/main/java/com/vaadin/flow/spring/SpringInstantiator.java, line 39 at r2](https://reviewable.io:443/reviews/vaadin/flow/3724#-L7xY_MHRAWsqgxWRL2i:-L7xY_MHRAWsqgxWRL2j:bps2ofs) ([raw file](https://github.com/vaadin/flow/blob/941f79aa9ed17a97c72d2925d9690b9fce59a922/flow-spring-addon/src/main/java/com/vaadin/flow/spring/SpringInstantiator.java#L39)):*
> loggerEnable

`loggingEnabled`

---

*[flow-spring-addon/src/main/java/com/vaadin/flow/spring/SpringInstantiator.java, line 69 at r2](https://reviewable.io:443/reviews/vaadin/flow/3724#-L7xWsrFJs7YWSMYBi7s:-L7xWsrFJs7YWSMYBi7t:b-u033se) ([raw file](https://github.com/vaadin/flow/blob/941f79aa9ed17a97c72d2925d9690b9fce59a922/flow-spring-addon/src/main/java/com/vaadin/flow/spring/SpringInstantiator.java#L69)):*
> if (loggerEnable.get() == true) {


`== true` ?
No need to compare at all.

Actually you may keep the previous version here `infoLogger.compareAndSet(true, false)`.
It's fine. My bad.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3724)*

**Comment by ZheSun88** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[flow-spring-addon/src/main/java/com/vaadin/flow/spring/SpringInstantiator.java, line 39 at r2](https://reviewable.io:443/reviews/vaadin/flow/3724#-L7xY_MHRAWsqgxWRL2i:-L7xZYY5Oj1xK7FY4z6r:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/941f79aa9ed17a97c72d2925d9690b9fce59a922/flow-spring-addon/src/main/java/com/vaadin/flow/spring/SpringInstantiator.java#L39)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> loggerEnable

`loggingEnabled`
</blockquote></details>

Done.

---

*[flow-spring-addon/src/main/java/com/vaadin/flow/spring/SpringInstantiator.java, line 69 at r2](https://reviewable.io:443/reviews/vaadin/flow/3724#-L7xWsrFJs7YWSMYBi7s:-L7xZZKW3aY6bP5bg9iD:b7amaih) ([raw file](https://github.com/vaadin/flow/blob/941f79aa9ed17a97c72d2925d9690b9fce59a922/flow-spring-addon/src/main/java/com/vaadin/flow/spring/SpringInstantiator.java#L69)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> if (loggerEnable.get() == true) {


`== true` ?
No need to compare at all.

Actually you may keep the previous version here `infoLogger.compareAndSet(true, false)`.
It's fine. My bad.
</blockquote></details>

oops. indeed.. 

No problem.. i am not very familiar with Atomic operation.. good to get some advice on that.. Thanks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3724)*

**Comment by denis-anisimov** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3724#-:-L7x_ttP8DyTRd-nZaOH:bnfp4nl)*

**Pull request merged**
