### PR TITLE
Makes RPC decoders design and implement some hardocded decoders

### PR DESCRIPTION
**Pull request by denis-anisimov**
Implemented deoders:
- String to Number ( to Long, to Integer, to Double, ....)
- String to Enum
- Default decoder (via JsonCodec).

Fix for #2681.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/2849)

### CODE REVIEW

**Comment by caalador** [comment]
Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/nodefeature/ClientDelegateHandlers.java, line 49 at r1](https://reviewable.io:443/reviews/vaadin/flow/2849#-KyFSDB4jhJRgXFUZ--Z:-KyFSDB4jhJRgXFUZ--_:b-2t4akx) ([raw file](https://github.com/vaadin/flow/blob/d953417de1cb89a6023f158790c8aa28d2db42fd/flow-server/src/main/java/com/vaadin/flow/nodefeature/ClientDelegateHandlers.java#L49)):*
> ```Java
>     }
> 
>     @Override
> ```

Does this override anything anymore as the `AbstractServerHandlers` method was removed?
Also I think this is not called from anywhere anymore.

---

*[flow-server/src/main/java/com/vaadin/server/communication/rpc/StringToNumberDecoder.java, line 55 at r1](https://reviewable.io:443/reviews/vaadin/flow/2849#-KyFUt37DlUO7DDVA7D-:-KyFUt37DlUO7DDVA7D0:b-3uk7ay) ([raw file](https://github.com/vaadin/flow/blob/d953417de1cb89a6023f158790c8aa28d2db42fd/flow-server/src/main/java/com/vaadin/server/communication/rpc/StringToNumberDecoder.java#L55)):*
> NumberFormat.getInstance(Locale.ENGLISH)
>                     .parse(stringValue)
This is used 2 times once in an if so it would be easier to read as a method.

Also should UI.getLocale() be used instead of ENGLISH?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2849)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/flow/nodefeature/ClientDelegateHandlers.java, line 49 at r1](https://reviewable.io:443/reviews/vaadin/flow/2849#-KyFSDB4jhJRgXFUZ--Z:-KyF_LPR6DDa9kv6MAx1:bih7y0k) ([raw file](https://github.com/vaadin/flow/blob/d953417de1cb89a6023f158790c8aa28d2db42fd/flow-server/src/main/java/com/vaadin/flow/nodefeature/ClientDelegateHandlers.java#L49)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Does this override anything anymore as the `AbstractServerHandlers` method was removed?
Also I think this is not called from anywhere anymore.
</blockquote></details>

There has been two methods : `ensureSupportedParameterTypes` and `ensureSupportedParameterType`.
Only the last one is removed.
This method is not removed.
It's called from `addHandlerMethod`.

By the way the `@Override`annotation is checked by the compiler. The build would have failed.

---

*[flow-server/src/main/java/com/vaadin/server/communication/rpc/StringToNumberDecoder.java, line 55 at r1](https://reviewable.io:443/reviews/vaadin/flow/2849#-KyFUt37DlUO7DDVA7D-:-KyF_pKWOsTBZfm0tYIw:bhf59kl) ([raw file](https://github.com/vaadin/flow/blob/d953417de1cb89a6023f158790c8aa28d2db42fd/flow-server/src/main/java/com/vaadin/server/communication/rpc/StringToNumberDecoder.java#L55)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

> NumberFormat.getInstance(Locale.ENGLISH)
>                     .parse(stringValue)
This is used 2 times once in an if so it would be easier to read as a method.

Also should UI.getLocale() be used instead of ENGLISH?
</blockquote></details>

No.
It doesn't matter which locale is used by UI.
One single locale should be fixed which we use to deserialize the numbers (matches to serializing process).

Technically the serialized format is not locale dependent. So it's just a protection from using some unexpected locale by default. `EN` locale should be able to parse serialized values correctly (and serialization is done e.g. via `Double.toString()` where locale is not specified). 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2849)*

**Comment by caalador** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/server/communication/rpc/StringToNumberDecoder.java, line 55 at r1](https://reviewable.io:443/reviews/vaadin/flow/2849#-KyFUt37DlUO7DDVA7D-:-KyFdRZWeToQg-I1Ub4Q:b-bsbk9p) ([raw file](https://github.com/vaadin/flow/blob/d953417de1cb89a6023f158790c8aa28d2db42fd/flow-server/src/main/java/com/vaadin/server/communication/rpc/StringToNumberDecoder.java#L55)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

No.
It doesn't matter which locale is used by UI.
One single locale should be fixed which we use to deserialize the numbers (matches to serializing process).

Technically the serialized format is not locale dependent. So it's just a protection from using some unexpected locale by default. `EN` locale should be able to parse serialized values correctly (and serialization is done e.g. via `Double.toString()` where locale is not specified). 
</blockquote></details>

This is used 2 times once in an if so it would be easier to read as a method.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2849)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[flow-server/src/main/java/com/vaadin/server/communication/rpc/StringToNumberDecoder.java, line 55 at r1](https://reviewable.io:443/reviews/vaadin/flow/2849#-KyFUt37DlUO7DDVA7D-:-KyGG29b5NBkrVXyNj-G:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/d953417de1cb89a6023f158790c8aa28d2db42fd/flow-server/src/main/java/com/vaadin/server/communication/rpc/StringToNumberDecoder.java#L55)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

This is used 2 times once in an if so it would be easier to read as a method.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2849)*

**Comment by caalador** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2849)*

**Pull request merged**
