### PR TITLE
Complete rerouting in BeforeNavigationEvent

### PR DESCRIPTION
**Pull request by torok-peter**
* Add new overload `rerouteTo(String route, List<T> routeParams)`
* Extract method `hasRouteTo(String pathString)` in `RouteRegistry` to allow precise error handling in caller code
* Refactor to reuse existing code

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/2625)

### CODE REVIEW

**Comment by caalador** [comment]
Reviewed 3 of 4 files at r1.
Review status: 3 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/router/event/BeforeNavigationEvent.java, line 212 at r1](https://reviewable.io:443/reviews/vaadin/flow/2625#-Kvke_yXs55g80BwmCQi:-Kvke_yXs55g80BwmCQj:b-5xiwqu) ([raw file](https://github.com/vaadin/flow/blob/f6e491b0607de130098db261fdb69ba01cee88ce/flow-server/src/main/java/com/vaadin/router/event/BeforeNavigationEvent.java#L212)):*
> ```Java
>         checkUrlParameterType(routeParam, target);
>         rerouteTo(new NavigationStateBuilder()
>                 .withTarget(target, segments).build());
> ```

Should be able to call `rerouteTo(route, Collections.singletonList(routeParam));`
Basically they should do the same thing.

---

*[flow-server/src/main/java/com/vaadin/router/event/BeforeNavigationEvent.java, line 240 at r1](https://reviewable.io:443/reviews/vaadin/flow/2625#-KvkeCpTSQd6jndZmR--:-KvkeCpTSQd6jndZmR-0:b-oaily6) ([raw file](https://github.com/vaadin/flow/blob/f6e491b0607de130098db261fdb69ba01cee88ce/flow-server/src/main/java/com/vaadin/router/event/BeforeNavigationEvent.java#L240)):*
> checkHasUrlParameter(route, target);
> checkWildcardParameter(routeParams, target);
Instead of these just check that the UrlParameterType is valid e.g. `checkUrlParameterType`

---

*[flow-server/src/main/java/com/vaadin/router/event/BeforeNavigationEvent.java, line 258 at r1](https://reviewable.io:443/reviews/vaadin/flow/2625#-KvkdpE1ykATPdb1DkoH:-KvkdpE1ykATPdb1DkoI:bnie4o4) ([raw file](https://github.com/vaadin/flow/blob/f6e491b0607de130098db261fdb69ba01cee88ce/flow-server/src/main/java/com/vaadin/router/event/BeforeNavigationEvent.java#L258)):*
> ```Java
>     }
> 
>     private void checkHasUrlParameter(String route,
> ```

Will this ever be called? as a non parameter class wouldn't be found in `getTargetOrThrow`.
If we can reach this somehow add a test for that route.

---

*[flow-server/src/main/java/com/vaadin/router/event/BeforeNavigationEvent.java, line 268 at r1](https://reviewable.io:443/reviews/vaadin/flow/2625#-KvkcVbKNw3WDs9iaPGi:-KvkcVbKNw3WDs9iaPGj:bwcvekh) ([raw file](https://github.com/vaadin/flow/blob/f6e491b0607de130098db261fdb69ba01cee88ce/flow-server/src/main/java/com/vaadin/router/event/BeforeNavigationEvent.java#L268)):*
> ```Java
>     }
> 
>     private <T> void checkWildcardParameter(List<T> routeParams,
> ```

Is this actually needed? it will fail already on the `getTargetOrThrow` method.
If we can reach this somehow add a test for that route.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2625)*

**Comment by denis-anisimov** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/router/event/BeforeNavigationEvent.java, line 204 at r1](https://reviewable.io:443/reviews/vaadin/flow/2625#-KvkiQnq7CzJZ_IlXACM:-KvkiQnq7CzJZ_IlXACN:b-7lwdv8) ([raw file](https://github.com/vaadin/flow/blob/f6e491b0607de130098db261fdb69ba01cee88ce/flow-server/src/main/java/com/vaadin/router/event/BeforeNavigationEvent.java#L204)):*
>  public <T> void rerouteTo(String route, T routeParam) {

Shouldn't the method implementation just delegate to `rerouteTo(String route, List<T> routeParams)` with `Collections.singletonList` as a second argument value ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2625)*

**Comment by torok-peter** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/router/event/BeforeNavigationEvent.java, line 204 at r1](https://reviewable.io:443/reviews/vaadin/flow/2625#-KvkiQnq7CzJZ_IlXACM:-KvkotaKN2bTqzPeCWTq:b5ad2x) ([raw file](https://github.com/vaadin/flow/blob/f6e491b0607de130098db261fdb69ba01cee88ce/flow-server/src/main/java/com/vaadin/router/event/BeforeNavigationEvent.java#L204)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

>  public <T> void rerouteTo(String route, T routeParam) {

Shouldn't the method implementation just delegate to `rerouteTo(String route, List<T> routeParams)` with `Collections.singletonList` as a second argument value ?
</blockquote></details>

The difference boiled down to the call to `checkUrlParameterType()`. It seems to be necessary for the single parameter (there is a unit test for it), but not for the multiple parameter case. 
So, checking for this and getting back `T` from a `List<T>` would be awkward IMHO, something like:
```
    public <T> void rerouteTo(String route, T routeParam) {
        rerouteTo(route, Collections.singletonList(routeParam));
    }

    public <T> void rerouteTo(String route, List<T> routeParams) {
        List<String> segments = routeParams.stream().map(Object::toString)
                .collect(Collectors.toList());
        Class<? extends Component> target = getTargetOrThrow(route, segments);

        if (routeParams.size() == 1) {
            Type elementType = ReflectTools.getGenericParameterType(routeParams);
            checkUrlParameterType(elementType, target);
        }
        rerouteTo(new NavigationStateBuilder()
                .withTarget(target, segments).build());
    }
```
I believe the current solution (without delegation) is cleaner and more efficient.

---

*[flow-server/src/main/java/com/vaadin/router/event/BeforeNavigationEvent.java, line 212 at r1](https://reviewable.io:443/reviews/vaadin/flow/2625#-Kvke_yXs55g80BwmCQi:-Kvktob3rgToIJz3lb34:b-34vmyd) ([raw file](https://github.com/vaadin/flow/blob/f6e491b0607de130098db261fdb69ba01cee88ce/flow-server/src/main/java/com/vaadin/router/event/BeforeNavigationEvent.java#L212)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Should be able to call `rerouteTo(route, Collections.singletonList(routeParam));`
Basically they should do the same thing.
</blockquote></details>

See above

---

*[flow-server/src/main/java/com/vaadin/router/event/BeforeNavigationEvent.java, line 240 at r1](https://reviewable.io:443/reviews/vaadin/flow/2625#-KvkeCpTSQd6jndZmR--:-Kvko8mOH1EQOlAGkS-C:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/f6e491b0607de130098db261fdb69ba01cee88ce/flow-server/src/main/java/com/vaadin/router/event/BeforeNavigationEvent.java#L240)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

> checkHasUrlParameter(route, target);
> checkWildcardParameter(routeParams, target);
Instead of these just check that the UrlParameterType is valid e.g. `checkUrlParameterType`
</blockquote></details>

Done.

---

*[flow-server/src/main/java/com/vaadin/router/event/BeforeNavigationEvent.java, line 258 at r1](https://reviewable.io:443/reviews/vaadin/flow/2625#-KvkdpE1ykATPdb1DkoH:-KvkoAvMH2_-cuEZYhww:bss4a2b) ([raw file](https://github.com/vaadin/flow/blob/f6e491b0607de130098db261fdb69ba01cee88ce/flow-server/src/main/java/com/vaadin/router/event/BeforeNavigationEvent.java#L258)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Will this ever be called? as a non parameter class wouldn't be found in `getTargetOrThrow`.
If we can reach this somehow add a test for that route.
</blockquote></details>

Removed.

---

*[flow-server/src/main/java/com/vaadin/router/event/BeforeNavigationEvent.java, line 268 at r1](https://reviewable.io:443/reviews/vaadin/flow/2625#-KvkcVbKNw3WDs9iaPGi:-KvkoDt1uNIM8ncQEfdG:bss4a2b) ([raw file](https://github.com/vaadin/flow/blob/f6e491b0607de130098db261fdb69ba01cee88ce/flow-server/src/main/java/com/vaadin/router/event/BeforeNavigationEvent.java#L268)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Is this actually needed? it will fail already on the `getTargetOrThrow` method.
If we can reach this somehow add a test for that route.
</blockquote></details>

Removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2625)*

**Comment by denis-anisimov** [comment]
Review status: 2 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/router/event/BeforeNavigationEvent.java, line 204 at r1](https://reviewable.io:443/reviews/vaadin/flow/2625#-KvkiQnq7CzJZ_IlXACM:-KvkwqGN9HybHln1MRJ1:bah273s) ([raw file](https://github.com/vaadin/flow/blob/f6e491b0607de130098db261fdb69ba01cee88ce/flow-server/src/main/java/com/vaadin/router/event/BeforeNavigationEvent.java#L204)):*
>The difference boiled down to the call to checkUrlParameterType(). It seems to be necessary for the >single parameter (there is a unit test for it), but not for the multiple parameter case.

I think this is pretty incorrect.
The check should be done for any parameter type. I don't see any reason why it shouldn't be done.

Current behavior at least introduce a logic inconsistence between call:
`rerouteTo(route, param);`  `rerouteTo(route, Collections.singletonList(param));`
So in the first case there will be an exception of parameter is incorrect and there will be no exception in the second case.
This is totally confusing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2625)*

**Comment by denis-anisimov** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2625)*

**Comment by caalador** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/router/event/BeforeNavigationEvent.java, line 204 at r1](https://reviewable.io:443/reviews/vaadin/flow/2625#-KvkiQnq7CzJZ_IlXACM:-KvkxPQmjo85TrLGj_GX:b-4g97dp) ([raw file](https://github.com/vaadin/flow/blob/f6e491b0607de130098db261fdb69ba01cee88ce/flow-server/src/main/java/com/vaadin/router/event/BeforeNavigationEvent.java#L204)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

>The difference boiled down to the call to checkUrlParameterType(). It seems to be necessary for the >single parameter (there is a unit test for it), but not for the multiple parameter case.

I think this is pretty incorrect.
The check should be done for any parameter type. I don't see any reason why it shouldn't be done.

Current behavior at least introduce a logic inconsistence between call:
`rerouteTo(route, param);`  `rerouteTo(route, Collections.singletonList(param));`
So in the first case there will be an exception of parameter is incorrect and there will be no exception in the second case.
This is totally confusing.
</blockquote></details>

It actually doesn't really matter with the list case if you have one or many just check the first route parameter `routeParams.get(0)` that it is correct as they still should both do the check.

---

*[flow-server/src/main/java/com/vaadin/router/event/BeforeNavigationEvent.java, line 212 at r1](https://reviewable.io:443/reviews/vaadin/flow/2625#-Kvke_yXs55g80BwmCQi:-KvkxgoiZWSJ3HY8l2tP:b-wnwylb) ([raw file](https://github.com/vaadin/flow/blob/f6e491b0607de130098db261fdb69ba01cee88ce/flow-server/src/main/java/com/vaadin/router/event/BeforeNavigationEvent.java#L212)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

See above
</blockquote></details>

Moved to above  conversation.

---

*[flow-server/src/main/java/com/vaadin/router/event/BeforeNavigationEvent.java, line 240 at r1](https://reviewable.io:443/reviews/vaadin/flow/2625#-KvkeCpTSQd6jndZmR--:-KvkxwJ2oOaq-xGjIOg7:b-r3f6ym) ([raw file](https://github.com/vaadin/flow/blob/f6e491b0607de130098db261fdb69ba01cee88ce/flow-server/src/main/java/com/vaadin/router/event/BeforeNavigationEvent.java#L240)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Still doesn't check that the first parameter is of a valid type.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2625)*

**Comment by torok-peter** [comment]
Review status: 2 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[flow-server/src/main/java/com/vaadin/router/event/BeforeNavigationEvent.java, line 204 at r1](https://reviewable.io:443/reviews/vaadin/flow/2625#-KvkiQnq7CzJZ_IlXACM:-KvkzQlXIcfN0IQ-xKZ9:b-qfn6ar) ([raw file](https://github.com/vaadin/flow/blob/f6e491b0607de130098db261fdb69ba01cee88ce/flow-server/src/main/java/com/vaadin/router/event/BeforeNavigationEvent.java#L204)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

It actually doesn't really matter with the list case if you have one or many just check the first route parameter `routeParams.get(0)` that it is correct as they still should both do the check.
</blockquote></details>

Sorry, my bad. Done.

---

*[flow-server/src/main/java/com/vaadin/router/event/BeforeNavigationEvent.java, line 240 at r1](https://reviewable.io:443/reviews/vaadin/flow/2625#-KvkeCpTSQd6jndZmR--:-KvlTcCQwXEsH8cAnz4U:bcof0qk) ([raw file](https://github.com/vaadin/flow/blob/f6e491b0607de130098db261fdb69ba01cee88ce/flow-server/src/main/java/com/vaadin/router/event/BeforeNavigationEvent.java#L240)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Still doesn't check that the first parameter is of a valid type.
</blockquote></details>

Done, really :-)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2625)*

**Comment by denis-anisimov** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2625)*

**Pull request closed without merging**
