### PR TITLE
test: fix paths for temp files in tests

### PR DESCRIPTION
**Pull request by caalador**
No temporary test files should
be generated into the project folder.

### CODE REVIEW

**Comment by mcollovati** [comment]
Looks good. I can still see a `config/needs-build` generated on module root, but I have not figured out which test is creating it.

**Comment by mcollovati** [comment]
It looks like it is `NodeTasksHillaTest` that writes `config/needs-build` in module root and does not clean it.

**Comment by caalador** [comment]
I'll check and fix that also

**Comment by mcollovati** [comment]
It seems that `FrontendResourcesAreCopiedAfterCleaningTest` also writes the `config/needs-build` on module root.
It should be the last one.

**Review by mcollovati — DISMISSED** [review]

**Review by mcollovati — APPROVED** [review]

**Pull request merged**
