### PR TITLE
Update Polymer template parser to use VaadinService resource methods

### PR DESCRIPTION
**Pull request by Artur-**
VaadinSession data is no longer used for parsing templates on the server
to avoid potential problems when one session is used for parsing and the
parsed result is used with another session

This change removes VaadinSessionn access from dependency filters to avoid
the session only sometimes being available.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3888)

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
Got a merge conflict, test failure and a Sonar blocker for missing license header for `FakeEs6Browser` file.

---







*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3888#-:-LANrWyhAF9bxemmMPk2:b2o7zda)*

**Comment by Artur-** [comment]
Should be ok now

---

Review status: 0 of 20 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3888#-:-LAReRCn1w89oA2giODr:baq21hj)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 16 of 52 files at r1, 1 of 15 files at r2, 3 of 11 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/DefaultTemplateParser.java, line 80 at r3](https://beta.reviewable.io/reviews/vaadin/flow/3888#-LASVM8G-4CWu-tcOdhA:-LASVM8G-4CWu-tcOdhB:b199iy3) ([raw file](https://github.com/vaadin/flow/blob/7995993e2d0a6926b7dff9e4cfced8f91110432e/flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/DefaultTemplateParser.java#L80)):*
> ```Java
>             VaadinService service) {
>         boolean logEnabled = LOG_CACHE.get(clazz).compareAndSet(false, true);
>         WebBrowser browser = new FakeEs6Browser();
> ```

Is this method frequently called? If so, would it make sense to create a static instance of the `FakeEs6Browser`?

---

*[flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/PolymerTemplate.java, line 91 at r3](https://beta.reviewable.io/reviews/vaadin/flow/3888#-LASUgK80oMl4RSVuB5C:-LASTgdC72ADMyaNlq-F:b99a5tv) ([raw file](https://github.com/vaadin/flow/blob/7995993e2d0a6926b7dff9e4cfced8f91110432e/flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/PolymerTemplate.java#L91)):*
> ```Java
>      *            the related service instance
>      */
>     public PolymerTemplate(TemplateParser parser, VaadinService service) {
> ```

Would it make sense to just get the service vian `VaadinService.getCurrent()` in the original constructor instead of adding an extra constructor? You do that implicitly anyway.
Once the new constructor goes public, we cannot take it back and now it's not even used anywhere.

---

*[flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/TemplateDataAnalyzer.java, line 168 at r3](https://beta.reviewable.io/reviews/vaadin/flow/3888#-LASU3rR4UW2dnjGKDFf:-LASU3rR4UW2dnjGKDFg:bjbo6vx) ([raw file](https://github.com/vaadin/flow/blob/7995993e2d0a6926b7dff9e4cfced8f91110432e/flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/TemplateDataAnalyzer.java#L168)):*
> ```Java
>      * @param parser
>      *            a template parser
>      * @param service
> ```

Spare us from extra javadoc-plugin warning please :)

---

*[flow-server/src/main/java/com/vaadin/flow/server/startup/BundleFilterInitializer.java, line 79 at r3](https://beta.reviewable.io/reviews/vaadin/flow/3888#-LASVH-G1RJSqpFD2mcS:-LASVH-G1RJSqpFD2mcT:ba43xc0) ([raw file](https://github.com/vaadin/flow/blob/7995993e2d0a6926b7dff9e4cfced8f91110432e/flow-server/src/main/java/com/vaadin/flow/server/startup/BundleFilterInitializer.java#L79)):*
> ```Java
>             VaadinService service) {
>         WebBrowser es6Browser = new FakeEs6Browser();
>         String manifestResource = "frontend://" + FLOW_BUNDLE_MANIFEST;
> ```

Any reason to revert it back to hardcoded constant?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3888)*

**Comment by SomeoneToIgnore** [comment]
*[flow-server/src/main/java/com/vaadin/flow/server/startup/FakeEs6Browser.java, line 36 at r4](https://beta.reviewable.io/reviews/vaadin/flow/3888#-L9yolRv5osMi-6Cr_nN-r4-36:-LASg2dv2ziX8Yz4T7dK:b-dxcbts) ([raw file](https://github.com/vaadin/flow/blob/79b7ee157c23b52d5a3a3081d2b7159098b62aec/flow-server/src/main/java/com/vaadin/flow/server/startup/FakeEs6Browser.java#L36)):*
<details><summary><i>Previously, vaadin-bot (Vaadin Bot) wrote…</i></summary><blockquote>

CRITICAL Document this public method by adding an explicit description. [rule](https://sonar.projects.vaadin.com/coding_rules#rule_key=squid%3AUndocumentedApi)
</blockquote></details>

Makes sense.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3888)*

**Comment by SomeoneToIgnore** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3888#-:-LASi1yP62skOlo_E524:bnfp4nl)*

**Comment by SomeoneToIgnore** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow/3888#-:-LASsqm1BJoTupgt_ai3:bnfp4nl)*

**Pull request merged**
