### PR TITLE
Accept user versions

### LINKED ISSUE #8108: Overriding frontend dependencies for pnpm not possible from package.json
It should be possible to override the dependencies coming from the platform based the pnpm hook that reads `version.json` done in https://github.com/vaadin/flow/issues/7432 by adding a local entry to `package.json` or using `pnpm add`. This is the intended behavior but was forgotten in the implementation for the pnpm hook, probably due to the long discussion in Slack where it was mentioned but forgotten to add into the ticket.

Currently our managed dependencies are specified under `vaadin` in the `package.json` since https://github.com/vaadin/flow/issues/7018#issuecomment-558579017

### PR DESCRIPTION
**Pull request by caalador**
If package.json version
has been set to newer than
versions.json says then we
should not touch the file.

Fixes #8108

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/8160)

### CODE REVIEW

**Comment by caalador** [comment]
It will sort of still fall into the only newer allowed as we do not allow older versions to the pom against the vaadin defined versions. The reason is that what ever version we have defined for a package is the minimum version needed as older version may not have the needed api where as the possibility that newer versions do are higher.

**Comment by denis-anisimov** [comment]
>It will sort of still fall into the only newer allowed as we do not allow older versions 

Can we allow or disallow anything ?
User has a whole control over his POM file: he may declare any dependency downgrading it or upgrading.
It's his decision.
Same way he should be able to set any version which he wants. 
We already suggest a predefined versions which we recommend via `versions.json`.
It that sense we already "not allow" to use wrong version.

But if user decides explicitly change the version then it's his decision and we should not disregard it.
The bad thing is : the version which is set explicitly is totally disregarded without any notion.
I still think that it should be a user decision which version to use: if he decides to use an older version then it should be possible : it's his explicit decision.

Anyway if we disallow to downgrade the versions then the user should be aware of that.
And it looks like making him aware of that is more complicated than just do what he wants: if he wants to make a mistake it's his choice.

**Comment by caalador** [comment]
So then what this actually should do is to add the dependency from versions always if the version doesn't exist in dependencies. then we will not interfere with anything the user sets and only lock undefined versions.

**Comment by denis-anisimov** [comment]
Technically, yes.
I'm not sure whether it has sense to check deps within `vaadin` with the real dependencies or not.
May be not.

**Comment by caalador** [comment]
I feel that it doesn't need to check vaadin.dependencies as those are already handled.
I'll update to only adding non existing dependencies and not touching the existing dependencies.

**Comment by denis-anisimov** [comment]
Alright.

**Comment by caalador** [comment]
Right. Actually it's not package nor package-lock it's run for each dependencys package.json e.g. we get the package jsons for
- @vaadin/vaadin-login
- @vaadin/vaadin-menu-bar
- @vaadin/vaadin-upload
- @vaadin/vaadin-notification

I'll do the locking for each component dependency by `./package.json` as
- `vaadin.dependencies[key]` === `dependencies[key]` -> use `versions[key]`
- `vaadin.dependencies[key]` !== `dependencies[key]` -> use main package.json `dependencies[key]`

**Comment by denis-anisimov** [comment]
I would recommend to avoid JS in reading the main `package.json` and read in Java instead.
Generate `version.json` based on content from main `package.json`  and don't touch at all (or with minor changes) `pnpmfile.js`.

**Pull request merged**
