### PR TITLE
test: Test that setVisible works in production

### PR DESCRIPTION
**Pull request by Artur-**

### CODE REVIEW

**Comment by taefi** [comment]
Should this be merged after #14496? In this case, I would mark it as draft or blocked.

**Comment by Artur-** [comment]
If you review and merge #14493 then we can rebase this and see that it fails and properly tests the issue

**Comment by Artur-** [comment]
If so, then it is blocked by #14496 or should be included into that

**Comment by mshabarov** [comment]
> If you review and merge https://github.com/vaadin/flow/pull/14493 then we can rebase this and see that it fails and properly tests the issue

I've verified it locally. It fails.

**Review by mshabarov — APPROVED** [review]

**Comment by mshabarov** [comment]
Included into https://github.com/vaadin/flow/pull/14496

**Pull request closed without merging**
