### PR TITLE
Introduce a delta to verify the scroll position

### PR DESCRIPTION
**Pull request by denis-anisimov**
Fix for #4263

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/4294)

### CODE REVIEW

**Comment by pekam** [comment]
Review status: 1 unresolved discussion, 0 of 1 LGTMs obtained

---

*[flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/scroll/AbstractScrollIT.java, line 26 at r1](https://reviewable.io/reviews/vaadin/flow/4294#-LF1w5n-3XC_r1uOBpNh:-LF1w5n-3XC_r1uOBpNi:b-y00rsb) ([raw file](https://github.com/vaadin/flow/blob/76a0907e1ff5b9702df3ec63f2336f906dd4c0fc/flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/scroll/AbstractScrollIT.java#L26)):*
> ```Java
> abstract class AbstractScrollIT extends ChromeBrowserTest {
> 
>     protected static final int SCROLL_DELTA = 2;
> ```

I don't really understand why you want to pass this as a parameter for every single call instead of adding an overload method which uses this default value.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4294)*

**Comment by denis-anisimov** [comment]
Review status: 1 unresolved discussion, 0 of 1 LGTMs obtained

---

*[flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/scroll/AbstractScrollIT.java, line 26 at r1](https://reviewable.io/reviews/vaadin/flow/4294#-LF1w5n-3XC_r1uOBpNh:-LF23y7U4UJ-vPBpwzhd:bcwir5n) ([raw file](https://github.com/vaadin/flow/blob/76a0907e1ff5b9702df3ec63f2336f906dd4c0fc/flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/scroll/AbstractScrollIT.java#L26)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

I don't really understand why you want to pass this as a parameter for every single call instead of adding an overload method which uses this default value.
</blockquote></details>

One more method can be added, indeed.
But it should be possible to pass this is as a parameter as well.

E.g. I don't want any delta in the method `ensureThatNewPageIsNotScrolled`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4294)*

**Comment by denis-anisimov** [comment]
Review status: 1 unresolved discussion, 0 of 1 LGTMs obtained

---

*[flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/scroll/AbstractScrollIT.java, line 26 at r1](https://reviewable.io/reviews/vaadin/flow/4294#-LF1w5n-3XC_r1uOBpNh:-LF27Ny573J7OUsB-aLT:b-896fix) ([raw file](https://github.com/vaadin/flow/blob/76a0907e1ff5b9702df3ec63f2336f906dd4c0fc/flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/scroll/AbstractScrollIT.java#L26)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

One more method can be added, indeed.
But it should be possible to pass this is as a parameter as well.

E.g. I don't want any delta in the method `ensureThatNewPageIsNotScrolled`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4294)*

**Comment by pekam** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all discussions resolved, 0 of 1 LGTMs obtained, and 1 stale

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4294#-:-LF28ZfeABViHsZ-X8y6:bnfp4nl)*

**Pull request merged**
