### PR TITLE
Extract themes related tests to a separate module

### PR DESCRIPTION
**Pull request by denis-anisimov**
Fix for #4262

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/4277)

### CODE REVIEW

**Comment by pekam** [comment]
Review status: 1 unresolved discussion, 0 of 1 LGTMs obtained

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow/4277#-LEs6wFr8WtmX5cVZJEy:-LEs6wFr8WtmX5cVZJEz:b-uwxm6p) (no related file):*
The idea behind the ticket was that we should not have both `@Theme(Lumo.class)` and `@Theme(MyTheme.class)` in the same module, because otherwise we can't run production mode.

So `CustomStylesView` should not be included in this module, as it has Lumo theme.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4277)*

**Comment by pekam** [comment]
Review status: 1 unresolved discussion, 0 of 1 LGTMs obtained

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow/4277#-LEs6wFr8WtmX5cVZJEy:-LEsC3_80nT-1zGCmv2C:b7rmjad) (no related file):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

The idea behind the ticket was that we should not have both `@Theme(Lumo.class)` and `@Theme(MyTheme.class)` in the same module, because otherwise we can't run production mode.

So `CustomStylesView` should not be included in this module, as it has Lumo theme.
</blockquote></details>

Actually, `CustomStylesView` might be the only view using Lumo. So if it doesn't really test Lumo functionality, it might be that we could just change that to use MyTheme also and then we wouldn't need a new module at all. I'm sorry I just now realized it..

Although we probably should have some UI tests for Lumo, so I'm not sure.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4277)*

**Comment by denis-anisimov** [comment]
Review status: 1 unresolved discussion, 0 of 1 LGTMs obtained

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow/4277#-LEs6wFr8WtmX5cVZJEy:-LEsTols11AoHgShFYNX:b53gx) (no related file):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

Actually, `CustomStylesView` might be the only view using Lumo. So if it doesn't really test Lumo functionality, it might be that we could just change that to use MyTheme also and then we wouldn't need a new module at all. I'm sorry I just now realized it..

Although we probably should have some UI tests for Lumo, so I'm not sure.
</blockquote></details>

The idea was to extract all themes related functionality from the `test-root-context` module which is going to be configured for production.
If you want to have the new module also available for production then it's worth to mentioned that explicitly in the ticket (since there are number of test modules I don't consider this task as implicit : why should I care about this one and don't care about others).

`Lumo` is not tested here and there is no reason to test `Lumo` since it's not a Flow functionality. We are testing themes aspects related to Flow only. `Lumo` should be tested on the components side.

`MyTheme` is totally artificial theme and it may be very hard to test the aspect which is tested via `Lumo`.
The module still had to be extracted because all other tests don't use any theme at all (which means that there is a theme: "no theme"). And with `MyTheme`  the module contains two themes.

I will see if it's possible to reuse MyTheme for the test in the extracted module.
Otherwise one more module will be needed which is quite bad because of code duplication. To avoid this duplication one more module will be needed.
And I don't even see at the moment whether it's worth to make this module ready for production since we are working on `test-root-context` module not on others.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4277)*

**Comment by denis-anisimov** [comment]
Review status: 1 unresolved discussion, 0 of 1 LGTMs obtained

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow/4277#-LEs6wFr8WtmX5cVZJEy:-LEsouEPDV3yUphp_Qer:b-896fix) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

The idea was to extract all themes related functionality from the `test-root-context` module which is going to be configured for production.
If you want to have the new module also available for production then it's worth to mentioned that explicitly in the ticket (since there are number of test modules I don't consider this task as implicit : why should I care about this one and don't care about others).

`Lumo` is not tested here and there is no reason to test `Lumo` since it's not a Flow functionality. We are testing themes aspects related to Flow only. `Lumo` should be tested on the components side.

`MyTheme` is totally artificial theme and it may be very hard to test the aspect which is tested via `Lumo`.
The module still had to be extracted because all other tests don't use any theme at all (which means that there is a theme: "no theme"). And with `MyTheme`  the module contains two themes.

I will see if it's possible to reuse MyTheme for the test in the extracted module.
Otherwise one more module will be needed which is quite bad because of code duplication. To avoid this duplication one more module will be needed.
And I don't even see at the moment whether it's worth to make this module ready for production since we are working on `test-root-context` module not on others.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4277)*

**Comment by pekam** [comment]
Review status: 2 unresolved discussions, 0 of 1 LGTMs obtained

---

*[flow-tests/pom.xml, line 23 at r2](https://reviewable.io/reviews/vaadin/flow/4277#-LEx-LM9DFDWPnNY9rwG:-LEx-LM9DFDWPnNY9rwH:b-i4tsvt) ([raw file](https://github.com/vaadin/flow/blob/a071ad04858077d99f889d49543233d0ed77f5ee/flow-tests/pom.xml#L23)):*
> ```XML
>         <module>test-memory-leaks</module>
>         <module>test-servlet</module>
>         <module>test-themes</module>
> ```

I think this needs to be the same as the folder name to make the build pass.
So to follow the convention, the folder-name should be renamed from `flow-themes` to `test-themes`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4277)*

**Comment by denis-anisimov** [comment]
Review status: 1 unresolved discussion, 0 of 1 LGTMs obtained

---

*[flow-tests/pom.xml, line 23 at r2](https://reviewable.io/reviews/vaadin/flow/4277#-LEx-LM9DFDWPnNY9rwG:-LExPUYMDYUUaUWa-7ag:b-fgz0sb) ([raw file](https://github.com/vaadin/flow/blob/a071ad04858077d99f889d49543233d0ed77f5ee/flow-tests/pom.xml#L23)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

I think this needs to be the same as the folder name to make the build pass.
So to follow the convention, the folder-name should be renamed from `flow-themes` to `test-themes`.
</blockquote></details>

Yes, it should.
Don't know why I gave the name to the module.
Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4277)*

**Comment by denis-anisimov** [comment]
Review status: 2 unresolved discussions, 0 of 1 LGTMs obtained

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow/4277#-LExa1Iw0CcCEA4PEcYS:-LExlAWh5F1S0fsTkQbB:b-rp91fd) (no related file):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

So this PR introduces a couple of duplicate `Servlet` classes, but in the next PR you move those to the common module? Or did I mis-understand?
</blockquote></details>

No and yes.
Yes it introduces, no the next PR doesn't fix it because I'm waring for this PR to be able to do anything further.

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow/4277#-LExaaTk7CXN_3t9H_Hx:-LExlJUpBX46kYPoe7mk:b-f6hf6x) (no related file):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

Are you investigating the test failure?
</blockquote></details>

One more freaking theme is in the root-context module.
Extracted and rewritten.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4277)*

**Comment by denis-anisimov** [comment]
Review status: 2 unresolved discussions, 0 of 1 LGTMs obtained

---

*[a discussion](https://reviewable.io/reviews/vaadin/flow/4277#-LExaaTk7CXN_3t9H_Hx:-LExlRAH2ZuWfhayiuKI:b-896fix) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

One more freaking theme is in the root-context module.
Extracted and rewritten.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4277)*

**Comment by pekam** [comment]
:lgtm:

---

Reviewed 2 of 19 files at r3, 8 of 8 files at r4.
Review status: all discussions resolved, 0 of 1 LGTMs obtained, and 1 stale

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow/4277#-:-LExtiXl3h_Trb4trtTG:bnfp4nl)*

**Pull request merged**
