### PR TITLE
Generated classes with protected methods

### PR DESCRIPTION
**Pull request by gilberto-torrezan**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/3431)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 62 of 62 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3431)*

**Comment by ZheSun88** [comment]
Reviewed 35 of 56 files at r2.
Review status: 70 of 90 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3431#-L45HAYE90WUSmURsdPP:-L45HAYE90WUSmURsdPQ:b-px1aky) (no related file):*
Should we regenerate the paper elements? Because if so, we need to fix the `demo-flow-components`(https://github.com/vaadin/flow/tree/master/flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/views) too...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3431)*

**Comment by gilberto-torrezan** [comment]
Review status: 70 of 90 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3431#-L45HAYE90WUSmURsdPP:-L45KlE3I_tmuybP4-et:b-5xtpny) (no related file):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

Should we regenerate the paper elements? Because if so, we need to fix the `demo-flow-components`(https://github.com/vaadin/flow/tree/master/flow-components-parent/demo-flow-components/src/main/java/com/vaadin/flow/demo/views) too...
</blockquote></details>

Damn, that's a good question - we generate them to validate that the generator is working for elements outside Vaadin, but on the other hand it shouldn't use the same configurations as the Vaadin elements (meaning - they shouldn't use the `protected` methods. So my guess is, for now, we should just remove them. I'll do that and republish.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3431)*

**Comment by ZheSun88** [comment]
Reviewed 36 of 63 files at r1, 21 of 56 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/3431#-L45HAYE90WUSmURsdPP:-L45Ma-NDtfyyjrWcl68:b-jh0rsp) (no related file):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Damn, that's a good question - we generate them to validate that the generator is working for elements outside Vaadin, but on the other hand it shouldn't use the same configurations as the Vaadin elements (meaning - they shouldn't use the `protected` methods. So my guess is, for now, we should just remove them. I'll do that and republish.
</blockquote></details>

great.. less changes are always better.. I will review that after. :-) remember to merge the master into this branch also. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3431)*

**Comment by denis-anisimov** [comment]
Reviewed 54 of 56 files at r2, 51 of 51 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3431)*

**Comment by ZheSun88** [comment]
Reviewed 24 of 24 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/3431)*

**Pull request merged**
