### PR TITLE
Add flow bom.

### PR DESCRIPTION
**Pull request by SomeoneToIgnore**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow/2688)

### CODE REVIEW

**Comment by Legioth** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2688#-KwZvMvb9Nhq8QdFbnQh:-KwZvMvcl3eDJvWwPLL3:b89t8a4) (no related file):*
How will this work once individual components are their own separately versioned modules instead of part of  `vaadin/flow`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2688)*

**Comment by SomeoneToIgnore** [comment]
*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2688#-KwZvMvb9Nhq8QdFbnQh:-Kw_-IZrhJBhPFiqxYXb:b-k0y7l) (no related file):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

How will this work once individual components are their own separately versioned modules instead of part of  `vaadin/flow`?
</blockquote></details>

Nice and smooth, we add those components here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2688)*

**Comment by Legioth** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2688#-KwZvMvb9Nhq8QdFbnQh:-Kw_-UCOadbQsVVCEXbt:bdpl1rv) (no related file):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Nice and smooth, we add those components here.
</blockquote></details>

Sounds like a circular dependency

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2688)*

**Comment by SomeoneToIgnore** [comment]
*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2688#-KwZvMvb9Nhq8QdFbnQh:-Kw_-b51YkYNF6yb1NJO:bpp3pty) (no related file):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

Sounds like a circular dependency
</blockquote></details>

It's a standalone bom that does not depend on anything and other projects should be including it in `dependencyManagement` section.
How does this make a circular dependency?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2688)*

**Comment by Legioth** [comment]
*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2688#-KwZvMvb9Nhq8QdFbnQh:-Kw_-xbr-I9zrM22nZlD:b-al2w0l) (no related file):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

It's a standalone bom that does not depend on anything and other projects should be including it in `dependencyManagement` section.
How does this make a circular dependency?
</blockquote></details>

Might not be a circular dependency from a technical point of view. My concern is more about versioning.

Assuming this bom is part of Flow, should there be a new version of Flow whenever any independently versioned component is updated? 

Should there be a new version of each independently versioned component whenever Flow is updated?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2688)*

**Comment by SomeoneToIgnore** [comment]
*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2688#-KwZvMvb9Nhq8QdFbnQh:-Kw_2DkqFgW5VbZPgbxq:b15sufx) (no related file):*
> Assuming this bom is part of Flow, should there be a new version of Flow whenever any independently versioned component is updated?

I consider this bom as everything our user should have been importing to his project (something similar to Spring: we define every possible resolution the user may need so that the only vaadin version he should use in his pom is the bom version itself)
Bom has a version number and whenever there's a new component released, we can update the bom, but Flow itself does not really need to be updated.
Does it make sense?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2688)*

**Comment by Artur-** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2688#-KwZvMvb9Nhq8QdFbnQh:-Kw_3aDiDwIdKcSkXH49:b6qd7k9) (no related file):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

> Assuming this bom is part of Flow, should there be a new version of Flow whenever any independently versioned component is updated?

I consider this bom as everything our user should have been importing to his project (something similar to Spring: we define every possible resolution the user may need so that the only vaadin version he should use in his pom is the bom version itself)
Bom has a version number and whenever there's a new component released, we can update the bom, but Flow itself does not really need to be updated.
Does it make sense?
</blockquote></details>

You are describing the platform BOM, not a Flow BOM. Flow has no components.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2688)*

**Comment by SomeoneToIgnore** [comment]
*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2688#-KwZvMvb9Nhq8QdFbnQh:-Kw_3qA1Xl3SgzQ9sAP-:b-uans1a) (no related file):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

You are describing the platform BOM, not a Flow BOM. Flow has no components.
</blockquote></details>

Thanks for the correction.
Ok,  s/flow-bom/platform-bom/g

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2688)*

**Comment by Legioth** [comment]
*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2688#-KwZvMvb9Nhq8QdFbnQh:-Kw_4J3qHTwAgKE9SQLW:b-fcejfb) (no related file):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Thanks for the correction.
Ok,  s/flow-bom/platform-bom/g
</blockquote></details>

In that case, the bom cannot be part of the `vaadin/flow` github repository since that would cause lots of confusion with version tags.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2688)*

**Comment by Artur-** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2688#-KwZvMvb9Nhq8QdFbnQh:-Kw_4f6bJ0MzRC-pEfDd:bt9saxf) (no related file):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

In that case, the bom cannot be part of the `vaadin/flow` github repository since that would cause lots of confusion with version tags.
</blockquote></details>

The platform BOM is available at https://github.com/vaadin/platform/tree/master/vaadin-bom

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2688)*

**Comment by SomeoneToIgnore** [comment]
*[a discussion](https://reviewable.io:443/reviews/vaadin/flow/2688#-KwZvMvb9Nhq8QdFbnQh:-Kw_4pNAb2fJKrEwFOBR:bky3neh) (no related file):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

The platform BOM is available at https://github.com/vaadin/platform/tree/master/vaadin-bom
</blockquote></details>

Now we're talking.

Ok, I'm going to commit all dependency resolutions for webjars there then.
I'll post an explanation why it's needed follows in that flamed Slack thread first and we'll decide whether it's a nice idea.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow/2688)*

**Pull request closed without merging**
